### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by nulltoken** [Azure/azure-cosmos-dotnet-v3#1]
Thanks a lot for open sourcing this!

:heart:

**Comment by phillipfisher** [comment]
Same here! Thanks for opening this project up!

What is the plan on open-sourcing Microsoft.Azure.Cosmos.Direct?  It appears that there is alot of functionality still buried in there.  Currently due the dependency on it I am unable to build the solution.

Thanks in advance!

**Comment by k-miyake** [comment]
Lots of developers were waiting for Open sourced. It's a wonderful job.

**Comment by kirillg** [comment]
Thank you guys! @phillipfisher, our intent is to open source as much as we can. There is some complexity to it because a lot of the code inside .NET SDK is shared between the SDK and the Cosmos DB service. Over time you should expect us to move more and more to the open source.
