### ISSUE TITLE
Change feed processor name when using azure function

### ISSUE THREAD

**Issue by jdaaboul** [Azure/azure-cosmos-dotnet-v3#1005]
I am using a cosmos db trigger which uses the change feed mechanism to listen for updates on the collection. In a different "codebase" I would like to be able to have an update on how much work is left for the change feed to finish processing all queue documents.

I was able to find this method which can help me : Container.GetChangeFeedEstimatorBuilder

However it takes a "processorName" by input. My question is the following: From a .net Core 3.0 azure function cosmos db trigger, how can I tell what is the processorName of the change feed used so that I can then use it to monitor progress on this change feed.

Thank you.

**Comment by ealsur** [comment]
You have several options.

1. Use Azure Functions to monitor for changes, see https://medium.com/microsoftazure/azure-cosmos-db-functions-cookbook-monitoring-trigger-pending-work-800b24589235
2. Create an estimator with V3 SDK following this migration guide https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-migrate-from-change-feed-library. The processorName is basically what you set as LeaseCollectionPrefix in the Functions trigger. If you did not set it, it's an empty string (as mentioned in the guide).
