### ISSUE TITLE
CreateAsync() does not honor connection mode gateway

### ISSUE THREAD

**Issue by rangp** [Azure/azure-cosmos-dotnet-v3#1008]
**Bug Description**
When calling `CreateAsync()` on a container I noticed via `netstat` that a lot of tcp connections to different endpoints in the port range 14000-14999 are opened to the server, although I set `ConnectionMode` in my CosmosClient to `ConnectionMode.Gateway`.

From the documentation [here](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips) I gathered that gateway mode is supposed to use HTTPS ports and a single endpoint. When executing a query against my container I can confirm this to be the case but `CreateAsync()` seems to behave differently and does not honor my connection mode settings in the way I want it to.

**To Reproduce**

I reproduced this by setting up a collection and writing a simple console application like
```

            var client = new CosmosClient("connection string");
            client.ClientOptions.ConnectionMode = ConnectionMode.Gateway;
            var container = client.GetContainer("db", "container");
            var random = new Random();

            while (true)
            {
                await container.CreateItemAsync(new { test = "test" }, new PartitionKey(random.Next(0, 100)));
            }
```

**Expected behavior**

One or few connections to the same endpoint in the HTTPS port range are opened.

**Actual behavior**

A lot of connections to different endpoints are opened (36 in my case). The port range seems to be 14000-14999

**Environment summary**
SDK Version: 3.4.1
OS Version: Linux, alpine 3.6

**Comment by j82w** [comment]
You have to pass in the client options in the client constructor. Any changes made to the client options after the client is created will be ignored in most cases. Updating a client options after creating an instance should be blocked to avoid this confusion.

```
var clientOptions = new CosmosClientOptions()
{
    ConnectionMode = ConnectionMode.Gateway
};
 var client = new CosmosClient("connection string", clientOptions );

var container = client.GetContainer("db", "container");
var random = new Random();

while (true)
{
      await container.CreateItemAsync(new { test = "test" }, new PartitionKey(random.Next(0, 100)));
}
```

@kirankumarkolli and @ealsur should we make client options have a read only class that is used after an instance is created to avoid this confusion in vNext SDK?

**Comment by rangp** [comment]
@j82w Ah, yes, thank you! I did not realize it would make a difference. But I can confirm that it works as expected, if I pass it in the constructor.
