### ISSUE TITLE
ThroughputResponse reads wrong header for IsReplacePending

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-cosmos-dotnet-v3#1024]
**Describe the bug**
`ThroughputResponse.IsReplacePending` currently evaluates to a `FormatException` as it reads from the `WFConstants.BackendHeaders.MinimumRUsForOffer` header

**To Reproduce**
Scale the database to a value that requires more allocation at the backend, attempt to read `ThroughputResponse.IsReplacePending` flag

**Expected behavior**
`True` or `False` value to be returned

**Actual behavior**
`System.FormatException` is thrown

**Environment summary**
SDK Version: 3.4.1
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Comment by j82w** [comment]
[3.5.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.5.0) is released.
