### ISSUE TITLE
ReadItemStreamAsync with ResourceToken throws UnauthorizedException

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#1026]
**Describe the bug**
When using ReadItemStreamAsync and a ResourceToken, if the token does not have access to the resource DocumentClient is throwing an exception
```
                    if (!isTokenAvailable)
                    {
                        throw new UnauthorizedException(string.Format(
                           CultureInfo.InvariantCulture, ClientResources.AuthTokenNotFound, resourceAddress));
                    }
```
given that a Stream is being used my expectation is for the failure to be in the HTTP status code and not have do deal with the exception.

Additionally, given that UnauthorizedException is internal to Microsoft.Azure.Cosmos.Direct, it cannot be effectively caught.

**Environment summary**
SDK Version: Source
OS Version Windows 10

**Comment by j82w** [comment]
This is a bug. This exception should have been converted to a ResponseMessage somewhere higher in the stack. The caches have not been converted to be exception-less yet. The current workaround around is the code should catch the exception and convert it. It looks like during the lazy client initialization that loads the caches there is path that is not correctly handling it.

**Comment by ealsur** [comment]
Closing as inactive/old and not reproducible on latest versions
