### ISSUE TITLE
Weird results for .tail() in Gremlin API

### ISSUE THREAD

**Issue by kenewbie** [Azure/azure-cosmos-dotnet-v3#1030]
**Describe the bug**

.tail() does not return entries from the end of a list of vertices

**To Reproduce**

Create an empty graph partitioned on 'a' and seed with the following:

```
g.addV('person').property('a','1').property('name','person 1').property('number',1)
g.addV('person').property('a','1').property('name','person 2').property('number',2)
g.addV('person').property('a','1').property('name','person 3').property('number',3)

g.V().order().by('number')
returns: person 1, person 2, person 3

g.V().order().by('number').tail(1)
returns: person 1

```

I expected .tail() to return from the end of the list
Whats weird is that when i select just a property it works just as I expected:

```
g.V().order().by('number').properties('name')
returns: person 1, person 2, person 3

g.V().order().by('number').properties('name').tail(1)
returns: person 3
```

I have also managed to get it to work by doing a .fold().unfold() before .tail()

I get the same behavior when I run the queries directly in the azure cosmosdb explorer as well, so the quirk does not seem to in the .net SDK itself.

**EDIT:** I just realized this repo is for the SQL API specifically, but I cant find any relevant places to report gremlin issues. Suggestions are welcome and if this just creates clutter for you feel free to close/delete.

**Comment by j82w** [comment]
Please email askcosmosdb@microsoft.com for help. I'm not aware of any github repos for Gremiln API. You can also post on StackOverflow, but the email will get the fastest response.
