### ISSUE TITLE
CosmosDB returns 500 while querying document by documentId which has a trailing space to it, 404 expected

### ISSUE THREAD

**Issue by TestUserAz** [Azure/azure-cosmos-dotnet-v3#1032]
I am using cosmosdb sql sdk in my application while querying document by using its id mistakenly left trailing space along with id value, cosmos returns error 500 with below error message,

"The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign:"

The above error message is confusing. By reading above error, cosmos treats trailing space like a security threat. Error 404 is more convincing when id is supplied with trailing space. Any technical reason why cosmos returns 500 with above confusing/irrelevant error message while appending (by mistake) trailing space to document id while querying document via cosmos db sdk? anything to do with encoding/decoding/security aspects, please clarify.

code used:
var docDB = await _documentDatabase;
var docCollection = await _documentCollection;
var docClient = await _documentClient;
var documentUri = UriFactory.CreateDocumentUri(docDB.Id, docCollection.Id, documentlId);
//where documentlId = "testusername" works; while documentlId = "testusername " with trailing space returns error 500
response = await docClient.ReadDocumentAsync(documentUri)

**Comment by j82w** [comment]
This is the v2 SDK. Please post the issue on the [v2 repo.](https://github.com/Azure/azure-cosmos-dotnet-v2)
