### ISSUE TITLE
Cosmos DB: Gremlin API Request too large exception. 

### ISSUE THREAD

**Issue by Masood10** [Azure/azure-cosmos-dotnet-v3#1046]
I have a Throughput of 1000 RU/s in my Azure Cosmos DB and I have around 290 queries to be executed. I keep getting request too large exception.

Each query have 12 properties and 1 Partition key but I still think with 1000 RU/s the queries should be executed properly.

I have a gremlinClient 

        public static GremlinClient GetGremlinClient()
        {
            var gremlinServer = new GremlinServer(Endpoint, Port, enableSsl: true,
                username: "/dbs/" + Databasename + "/colls/" + Collectionname, password: Authkey);
            var gremlinClient = new GremlinClient(gremlinServer, new GraphSON2Reader(), new GraphSON2Writer(),
                GremlinClient.GraphSON2MimeType);
            return gremlinClient;
        }

A sample query. I am just trying to add vertices 

> g.addV('Experience').property('_test', 'dummy').property('someProperty', 'dummy').property('someProperty', 'dummy').property('someProperty', 'Documentation of the business processes
> of all departments as well as the management level for an informed
> selection of an ERP-system for a medium-sized industrial enterprise;
> Role: Project management ').property('someProperty',
> '2016').property('someProperty', 'Offen').property('someProperty',
> 'Dummy').property('someProperty', 'EN').property('someProperty',
> 'Industry').property('someProperty', 'Process documentation of
> the whole company for a profounded selection of an ERP-System.')

That for-each executes all the queries 

      foreach (string query in queries)
      {
                await gremlinClient.SubmitAsync<dynamic>(query);
      }

The error I get 

> Server error: \r\n\nActivityId : 2312f64f-b865-49cc-bb26-843d46313199\nExceptionType : RequestRateTooLargeException\nExceptionMessage :\r\n\tMessage: {\"Errors\":[\"Request rate is large\"]}\r\n\tActivityId: 157daf87-3238-4e1c-9a81-41bcd6d7c2e1, Request URI: /apps/413f848b-ce17-40fc-ad7f-14c0e21e9633/services/29abd22a-4e74-48c1-aab3-b311be968829/partitions/9e4cb405-4f74-4d7f-8d12-26e79b910143/replicas/132142016542682221s/, RequestStats: \r\n\tRequestStartTime: 2019-10-24T09:27:38.2395067Z, RequestEndTime: 2019-10-24T09:27:38.2395067Z, Number of regions attempted:1\r\n\tResponseTime: 2019-10-24T09:27:38.2395067Z

 Its a simple code I dont understand what I can change in that.

Is there a way to retry the request for the same point or somehow not get the error or to avoid the error

**Comment by j82w** [comment]
This repo is only for the .NET SQL API. Please email askcosmosdb@microsoft.com
