### ISSUE TITLE
TransactionalBatchOperationResult is missing a mocking constructor.

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-cosmos-dotnet-v3#1048]
TransactionalBatchOperationResult has a private parameterless constructor.  Please make it protected instead of private.  This will let us mock it so we can unit test batch code.

**Comment by joshlang** [comment]
...Tried to push this to a new branch & create a pull request to save you guys time, but I have no access.  Doh.

**Comment by j82w** [comment]
Thanks for the PR.

**Comment by j82w** [comment]
[3.5.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.5.0) is released.
