### ISSUE TITLE
CosmosClientOptions should set DefaultApplicationId

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#1054]
`CosmosClientOptions` contains `ApplicationName`, but Core SDK contains `ClientOptions.DiagnosticsOptions.ApplicationId` for the same reason.

To avoid duplication, we can remove `ApplicationName` in favor of `ClientOptions.DiagnosticsOptions.ApplicationId`

**Comment by j82w** [comment]
The user agent string should be added to every diagnostics.
