### ISSUE TITLE
Can we infer the id in ReplaceItemAsync?

### ISSUE THREAD

**Issue by daxfohl** [Azure/azure-cosmos-dotnet-v3#1055]
ReplaceItemAsync requires an explicit id field as an argument.

The id field will always be present on the data object, so this seems redundant and it seems the SDK should be able to infer it.

The SDK does infer the partition key if none is passed in explicitly, so inferring the id would also make the API more consistent.

**Comment by j82w** [comment]
ReplaceItemAsync supports changing the item's id field. Which is why the id value is required. It could be optional and extracted as you pointed out. The down side to this is the performance hit of extracting the id. I do agree that this would make the API easier to use.

@kirankumarkolli what is your opinion?

**Comment by daxfohl** [comment]
I didn't know changing the ID was possible. The docs state

idString <https://docs.microsoft.com/en-us/dotnet/api/system.string>

The cosmos item id, which is expected to match the value within T.


So if it is possible, the docs need corrected. Either way I'd still vote
for making the id field inferred where possible, unless the perf cost is
greater than I'm imagining. (and if it is then consider stating that
explicitly in the documentation, to avoid users requesting it over and over
again)

**Comment by j82w** [comment]
The only operation that infers the id is the `CreateItemAsync<T>` . Read, Delete, and Replace all require the id. The `CreateItemAsync<T>` does a post operation so the URL to the service does not need the id. The service extracts the id value from the body. For the other operation the id is part of the URL that is used to access the item. The SDK needs the id before it can send the request to the service.

**Comment by daxfohl** [comment]
`UpsertItemAsync<T>` infers the `id` too.  I imagine that as a PUT with the id in the URI, same as `ReplaceItemAsync<T>`, but with different header?  Or is that a POST like `CreateItemAsync<T>`?  Anyway yeah I can see the issue here, with `CreateItemAsync<T>` there's no need to extract the `id` before sending the request, whereas `UpdateItemAsync<T>` needs to know the `id` value in order to determine the URI.

Still, seems like something users would expect the SDK to handle automatically under the hood.

**Comment by Qythyx** [comment]
I agree, the docs should clarify if this method allows changing the ID, which would also help clarify why the ID argument is required.
