### ISSUE TITLE
Gotcha:  Max 100 items per batch!?!

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-cosmos-dotnet-v3#1057]
I tried to create 101 documents in a batch and received a `400 (Bad Request)` result from the server with the error `Batch request has more operations than what is supported.`

Creating 100 documents works fine.  Clearly, there is a **limit of 100 operations per batch**.

This is consistent with the table storage API.  But ...really... who's ever heard of that, even :D

There's no documentation I could find anywhere which says the SQL API has the same limitations.  The only hint I could find was this issue over here: https://github.com/Azure/azure-documentdb-datamigrationtool/pull/39

I suggest:
- Add documentation that 100 docs is the max
- Throw an exception when adding operation 101 to TransactionalBatch.  This makes it clear what the problem is exactly when it happens

...I also suggest removing the 100 doc and 2mb payload limit altogether, but... ...yeah, good luck with that :D

**Comment by joshlang** [comment]
FYI: While testing, I was able to create ~8400 documents (empty-ish) with a single call to a stored procedure on a collection with only 400 RU/s allocated.  Results are variable, of course.

**Comment by ealsur** [comment]
@abhijitpai Do we have the differences between Stored Procedures and Batch documented somewhere?

**Comment by abhijitpai** [comment]
We have the transactional batch limit now documented at https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-request-limits. We will look at increasing this over time but as discussed in https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1059 the limit allows for predictability.
