### ISSUE TITLE
CosmosException with throttling status code.

### ISSUE THREAD

**Issue by ashwini-mnnit** [Azure/azure-cosmos-dotnet-v3#1058]
We have recently observed  in our telemetry that the V3 sdk is throwing exception on 429 error. 

CosmosException;StatusCode=429;SubStatusCode=3200;ActivityId=88d1420d-9345-4510-bf1b-c4943d23ace9;RequestCharge=0.76;Message=Response status code does not indicate success: 429 Substatus: 3200 Reason: ().;

**Comment by ealsur** [comment]
This is expected, SDK will retry on 429 but if the amount of retries exceeds the configured retries, it will throw. It's the same behavior as the V2 SDK.

Are you using the Stream APIs?

**Comment by j82w** [comment]
This [exception](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-dot-net-sdk#request-rate-too-large) means that you need to scale the container throughput up. The request are getting throttled.
