### ISSUE TITLE
Queries does not return results from more than one physical partition

### ISSUE THREAD

**Issue by PrzemekGawron** [Azure/azure-cosmos-dotnet-v3#1064]
**Describe the bug**
Due to the fact we are approaching to maximum allowed size for single partition we've decided to migrate documents to partitioned collections using yyyy_MM as partition key. All looked good until probably cosmos db decided to use second physical partition. Then all the queries started to ignore all documents that are sitting in new partitions. The only way to get these documents is to explicitly provide partition key.

**To Reproduce**
```

            using (var client = new CosmosClient(ACCOUNT_ENDPOINT, AUTH_KEY))
            {
                var database = client.GetDatabase(DATABASE_NAME);
                var container = database.GetContainer(COLLECTION_NAME);
                var queryDefinition = new QueryDefinition("SELECT * FROM c WHERE c.id = @id")
                      .WithParameter("@id", "4021828524734779367");

                var options = new QueryRequestOptions() { PartitionKey = new PartitionKey("2019_11") };

                var feed = await container.GetItemQueryIterator<dynamic>(queryDefinition, null, options)
                    .ReadNextAsync();

                var feed2 = await container.GetItemQueryIterator<dynamic>(queryDefinition)
                    .ReadNextAsync();


                Console.WriteLine($"Feed count: {feed.Count}");
                Console.WriteLine($"Feed2 count: {feed2.Count}");
                Console.ReadLine();
            }
```

Output from following code is:
```
Feed count: 1
Feed2 count: 0
```

**Expected behavior**
SDK should handle cross partition queries regardless of physical representation.

**Actual behavior**
Cross partition queries returns only documents from all logical partitions beeing probably only within only first physical partition.

**Environment summary**

SDK Version:
3.4.1

**Comment by j82w** [comment]
Please take a look at the [query samples](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/94d517b69245fd75185d8e364c721cb3fe42da74/Microsoft.Azure.Cosmos.Samples/Usage/Queries/Program.cs#L199). ReadNextAsync is doing a single page to a single partition. This allows the query to be cancelled more frequently, and allows you to process a single page at a time for scenario when all results will not fit on one machine. The query needs to be drained like this:

```
List<dynamic> allItems = new List<dyanamic>();
FeedIterator<dynamic> feedIterator= container.GetItemQueryIterator<dynamic>(query);
while (feedIterator.HasMoreResults)
{
     FeedResponse<dyanamic> response = await feedIterator.ReadNextAsync();
     allItems.AddRange(response);
}
```
