### ISSUE TITLE
AsyncCacheTests test fails (locally)

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-cosmos-dotnet-v3#1066]
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/94d517b69245fd75185d8e364c721cb3fe42da74/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/AsyncCacheTest.cs#L168

This assertion is what fails the test when I run it locally.

The assertion doesn't seem to make sense - it's a race condition at best. After the cancellationTokenSource is .Cancel()'ed, getTask1 can complete at any time, including immediately.

I'm running it Windows 10, visual studio 2019 16.4 Preview 6 via the Test explorer.

In this (and other) tests, I don't understand what the point of checking this after calling cancellationTokenSource.Cancel():
```
            // neither task is complete at this point.
            Assert.IsFalse(getTask2.IsCompleted);
            Assert.IsFalse(getTask1.IsCompleted);
```

The test makes it through the pipelines.  The code itself is also fine.  It's just the test that's flaky in a particular environment.

**Comment by j82w** [comment]
The test `TestCancelOnOneThreadCancelsOtherTaskIfCanceled` also failed for me, but for some reason it seems to be passing in the gates.
