### ISSUE TITLE
Support SourceLink

### ISSUE THREAD

**Issue by KristianJakubik** [Azure/azure-cosmos-dotnet-v3#1069]
**Is your feature request related to a problem? Please describe.**
I think it would be helpful to be able to debug the sdk. It will speed up the integration within the projects in general and gives you a better understanding what's going on under the hood.

**Comment by j82w** [comment]
This looks really interesting. @kirankumarkolli do you see any issue with adding [SourceLink](https://github.com/dotnet/sourcelink) support?

**Comment by ealsur** [comment]
Sounds doable, we already have the symbols if I am not mistaken.

**Comment by KristianJakubik** [comment]
Can I submit PR for this then? Or is it still being discussed?

**Comment by j82w** [comment]
@ausfeldt are you working on this?

**Comment by ausfeldt** [comment]
@j82w No, something different.
