### ISSUE TITLE
QueryMetricText => indexLookupTimeInMs and documentLoadTimeInMs not populated

### ISSUE THREAD

**Issue by zhengwia** [Azure/azure-cosmos-dotnet-v3#1085]
I'm using sdk 3.5 trying to gather some stats, indexLookupTimeInMs and documentLoadTimeInMs seems to be always 0 whereas i can see some value populated via azure portal. 

Full QueryMetricText attached below:
totalExecutionTimeInMs=1.44;queryCompileTimeInMs=0.32;queryLogicalPlanBuildTimeInMs=0.09;queryPhysicalPlanBuildTimeInMs=0.00;queryOptimizationTimeInMs=0.02;VMExecutionTimeInMs=0.00;indexLookupTimeInMs=0.00;documentLoadTimeInMs=0.00;systemFunctionExecuteTimeInMs=0.00;userFunctionExecuteTimeInMs=0.00;retrievedDocumentCount=0;retrievedDocumentSize=0;outputDocumentCount=0;outputDocumentSize=49;writeOutputTimeInMs=0.00;indexUtilizationRatio=0.00

**Comment by j82w** [comment]
@bchong95 or @sboshra can you please take a look?

**Comment by bchong95** [comment]
Did this query even retrieve any documents? The query had a filter that didn't match any documents and you got a 0 document response, so no index look up time?

**Comment by zhengwia** [comment]
yes it returned documents.

**Comment by bchong95** [comment]
could not reproduce. please provide code that reproduces this issue.
