### ISSUE TITLE
Tests with [InternalsVisibleTo] don't catch serialization issues.

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-cosmos-dotnet-v3#1093]
There are various issues in which problems are caused by internal types not being deserialized properly.  Examples:

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1004
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/871

The current tests do not discover the problems because of:
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/65444def73da648460f5a3a6ed7bf0ebc4e0dde8/Microsoft.Azure.Cosmos/src/AssemblyInfo.cs#L23

The `[InternalsVisibleTo]` attribute allows these unit tests to deserialize internal types as if they were *public*.  The unit tests succeed.  But outside of these testing assemblies, the calls would fail because they're actually *internal*.

I would suggest creating a test project which is not referenced by `[InternalsVisibleTo]` and migrating some of the tests over to it.

**Comment by j82w** [comment]
I agree that this is causing a lot of issues. I'm working on a PR right now to address this. We do have a backlog item to start running the samples as part of the test, but I'm not sure when that will get prioritized. What ever the solution is there will be tests to prevent any future regressions like this.

**Comment by j82w** [comment]
Fixed in PR #1105
