### ISSUE TITLE
Change feed processor with lease container partition key other than /id

### ISSUE THREAD

**Issue by skwasiborski** [Azure/azure-cosmos-dotnet-v3#1100]
**Is your feature request related to a problem? Please describe.**
The change feed processor requires lease container with specific partition name. This requires me to provision a dedicated container using at least 100 RU even in my dev/test environments.

**Describe the solution you'd like**
Allow to use arbitrary partitioned lease container.

**Comment by ealsur** [comment]
The lease container is to be used exclusively by the Change Feed Processor, not shared with other load or operations. It can be shared with multiple Change Feed Processor instances, but its main goal is to be the state store for the Processor.

The Change Feed Processor needs to know the Partition Key to execute its operations and hence the requirement to be partitioned by `/id`. If you provided a container with a different Partition Key, then it could interfere with the operations and schema the Change Feed Processor uses (for example, creating hot partitions if the PK is an attribute not used by CFP or generating failures in the queries or operations if the PK matches one of the attributes used by the lease schema).

Reusing the same container to do operations can generate data corruption (deleting or altering leases while the Change Feed Processor instances are running) so it is not recommended.

There are no plans currently to provide support for custom partitioned containers.

**Comment by ealsur** [comment]
Closing as the question has been answered, no current plans to support a custom partitioning schema. 

Pull model without the lease container requirement is in the works, see https://github.com/Azure/azure-cosmos-dotnet-v3/issues/831
