### ISSUE TITLE
VNext move all spatial types to spatial namespace

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1102]
There is a mix of spatial types in the root namespace that should be moved to the spatial namespace.

**Comment by ealsur** [comment]
This was already done in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1072

Any new Spatial types will go to the Spatial namespace in vNext

**Comment by j82w** [comment]
@ealsur take a look at PR #1097 . It adds new types Geo types that are under the common namespace.

**Comment by ealsur** [comment]
Yup, saw it, but that change is not in vNext. Any new change I port to vNext, if its on the client surface/rest contract, I do the namespace adjustments 😄

**Comment by j82w** [comment]
I'm closing this issue then.
