### ISSUE TITLE
PartitionedQueryExecutionInfo cannot be deserialized when using a custom CosmosSerializer

### ISSUE THREAD

**Issue by bartcoppens** [Azure/azure-cosmos-dotnet-v3#1106]
**Reproduce**
Define a custom serializer that implements serialization using System.Text.Json.JsonSerializer.
Query a container using GetItemQueryIterator and ReadNextAsync.
The first value returned will be of type PartitionedQueryExecutionInfo and it will be fed into the FromStream method of the custom CosmosSerializer.

**Actual behavior**
The deserializer will fail to deserialize some important properties after which an exception is thrown because the expected properties are null.

**Expected behavior**
The custom serializer should ideally not be involved in deserializing the PartitionedQueryExecutionInfo. If absolutely necessary, please ensure that System.Text.Json.JsonSerializer can properly deserialize this object.

**Environment summary**
SDK Version: 3.5.1

**Comment by j82w** [comment]
Duplicate #1004. There is a PR #1105 with the fix.
