### ISSUE TITLE
Fix LastModified type

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1111]
ThroughputProperties has `public DateTime LastModified`

All the other types have it has nullable
`public DateTime? LastModified`

**Comment by kirankumarkolli** [comment]
It would be a breaking change now.
May be its usage is not much or none but still a breaking change. 

Is it a user feedback?
Can it be addressed in V4?

**Comment by j82w** [comment]
It's not user feedback.  I guess it best to just fix it in v4.

**Comment by ealsur** [comment]
Closed on vNext
