### ISSUE TITLE
User and Role management for Mongo API

### ISSUE THREAD

**Issue by ctthang** [Azure/azure-cosmos-dotnet-v3#1115]
It is great to see that the User and Role management had been supported https://github.com/Azure/azure-cosmos-dotnet-v3/issues/657

I am using the CosmosDb for Mongo API 3.6 which does still not support the User and Role management API (https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-feature-support-36#user-and-role-management).
I am looking for a solution and my question is that can I use Microsoft.Azure.Cosmos to manage users and roles for my CosmosDb for Mongo API database? 

Please suggest any alternative solutions if possible.

**Comment by ealsur** [comment]
This is the repo for the SQL API SDK, and thus, meant to be used with SQL / Core API accounts.

Mongo API accounts should use Mongo drivers, SDKs, and client-side tools. For Mongo API accounts, please see the official documentation regarding Users and Roles at https://docs.microsoft.com/azure/cosmos-db/mongodb-feature-support-36#user-and-role-management
