### ISSUE TITLE
Unit testable LINQ extensions

### ISSUE THREAD

**Issue by HarshaliRaka** [Azure/azure-cosmos-dotnet-v3#1125]
I am using LINQ extensions MaxAsync and CountAsync in my code. Is there a way for me to Unit test it?
I see comments [here](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/589) and [here](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/893) which say it is very difficult to mock extensions. If you can help with any other way of doing it, it will be really helpful.

Thanks!

**Comment by j82w** [comment]
The easiest solution is create a wrapper as explained in this [issue ](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/893#issuecomment-560809045) you already have linked. 

The other solution is mocking `Container.GetItemLinqQueryable` and return a `List` . When you call `CountAsync` it will just call the `List.Count` method. The downside to this is it won't support any of the inner linq extensions like [IsDefined](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/36444e8914f7224535e7b4ab819d748b66333aa1/Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs#L36).
