### ISSUE TITLE
Ability to know when partition keys in change feed change

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-cosmos-dotnet-v3#1126]
We have a scenario where change feed documents would be processed thusly (all in 1 partition key):

1) Receive `DocA` from change feed
2) Query for `DocB` to determine what we need to do

Since `DocA` and `DocB` are in the same partition, it would be better if we could cache the results of the `DocB` query.  The cache would be updated if `DocB` shows up in the change feed.

Right now, every change feed batch requires a new query for `DocB` because we don't know if the partition key ranges we're covering are the same as from the last batch.

## What I'm asking for:

I'd like a notification whenever the underlying range of partition keys being queried between change feed batches is changed.

**Comment by ealsur** [comment]
Not sure I understand the scenario.

You are listening for changes on the Change Feed, and you use part of the information in the changes to execute a query.

Is the query Cross Partition? Why knowing the Partition Key Range is critical? What is the Cache key?

**Comment by joshlang** [comment]
One of our actual scenarios is to route updates to clients who may be connected via more than one device (to more than one server).  Here's the simplified version of how it happens:

Partition key is the client ID.  Example:  **Bob**

Two document types:  `AccountInfoDoc` and `ConnectedToServersDoc`

When **Bob** connects to a server, we create/update `ConnectedToServersDoc`.

When **Bob** updates his account, we update `AccountInfoDoc`.  

Now the change feed picks up the `AccountInfoDoc` and wants to route it to **Bob** on all his other devices.  So it loads `ConnectedToServersDoc` and acts accordingly.

...

Later, **Bob** updates his account again.  `AccountInfoDoc` is updated.  The change feed sees it.

If the change feed *knew for sure* that it's working with the same partition key (or range) as when it saw the document for the first time, then it does not need to reload `ConnectedToServersDoc`.  Since both documents share the same partition key, the change feed knows `ConnectedToServersDoc` has not changed because it would have received the change in the feed.

But we can't make that assumption.  The partition key range being covered by my instance of the change feed processor may change between each batch.  I might see the two `AccountInfoDoc` updates but miss a `ConnectedToServersDoc` update that happened.

...

We have other scenarios too, usually related to ongoing processing of account-related information over time.

**Comment by ealsur** [comment]
So the ask is to know when a Lease gets re-balanced or moved to another instance because the Cache is local to each instance?

**Comment by joshlang** [comment]
Yep!

**Comment by ealsur** [comment]
But how do you know that a particular lease maps to, in this case, Bob? What if the instance owned 5 different leases and for some reason, one of those 4 moves out as part of a rebalance, how do you know that one was Bob's?

**Comment by joshlang** [comment]
I wouldn't know.  I would just nuke the cache whenever the partition key ranges that I'm covering changes.

**Comment by joshlang** [comment]
It looks like #1210 addresses this via the `Container.GetPartitionKeyRangesAsync` method, although I have not tried out the new model yet!

**Comment by ealsur** [comment]
In a way. You would have to call `Container.GetFeedTokensAsync` and for each one, call `Container.GetPartitionKeyRangesAsync`. That would give you the list of all PKRanges.

**Comment by joshlang** [comment]
I'm going to close this issue for now.  It sounds like I have a way to do what I originally wanted.  I appreciate the hard work!!
