### ISSUE TITLE
InvalidOperationException occurs when debugging

### ISSUE THREAD

**Issue by NoahStahl** [Azure/azure-cosmos-dotnet-v3#1149]
Hello! While debugging, I see the following exceptions logged in Visual Studio upon each Cosmos operation, e.g. ReadItemStreamAsync or others. This seems to be associated with IntelliTrace in VS, because when I disable it, the messages no longer appear in the debug console and the operations are significantly faster (I'm assuming IntelliTrace takes time to process each exception).

This isn't breaking anything as far as I know, just a nuisance in debugging with the output noise and slowdown involved. Wanted to raise here in case there is a way to address it in the SDK.

Exception:

`Exception thrown: 'System.InvalidOperationException' in System.Diagnostics.DiagnosticSource.dll (""Can not stop an Activity that was not started"") Exception thrown: 'System.InvalidOperationException' in System.Diagnostics.DiagnosticSource.dll (""Can not stop an Activity that was not started"")`

What IntelliTrace looks like:

![image](https://user-images.githubusercontent.com/7528994/72234211-c545e680-3580-11ea-8a83-a2f01850a0bd.png)

**To Reproduce**
Run project that uses the SDK to do operations, and observe the Debug output and IntelliTrace events tab. I'm using all the stream-based methods in the preview SDK.

**Expected behavior**
Ideally, no exceptions.

**Environment summary**
SDK Version: 4.0.0 preview3 (also happened with preview1)
OS Version: Windows 10 1909
VS: Visual Studio Enterprise 16.4.2, local Cosmos emulator
System.Diagnostics.DiagnosticSource 4.7.0 referenced in project

Thanks, happy to provide additional info as needed.

**Comment by j82w** [comment]
What .NET version is the project targeting?

**Comment by NoahStahl** [comment]
My project is aspnet core 3.1 / netstandard 2.1.

**Comment by ealsur** [comment]
@NoahStahl Are you attaching a Listener to the SDK DiagnosticSource?

**Comment by NoahStahl** [comment]
@ealsur I'm not sure what that is, so I assume not? :)

**Comment by ealsur** [comment]
I created an ASP.NET Core 3 MVC app, with the Azure.Cosmos package, and I'm doing an operation in one of the Controllers:

**Comment by ealsur** [comment]
Also, can you attach the full stacktrace? How do you know the exception is caused by the SDK code and not related to something else?

**Comment by NoahStahl** [comment]
Thanks for checking into it. I've found that the behavior doesn't happen on VS 2019 preview, only on 16.4.2, same machine. May be something in my VS installation or environment, I'll have to fiddle more and see if I can isolate.

Regarding cause, I didn't mean to suggest SDK was causing, only that there was some interaction. It definitely occurs while stepping over the Cosmos SDK method call in debug.

**Comment by ealsur** [comment]
The interaction might be related to Intellitrace hooking to all DiagnosticSources. The SDK emits diagnostics (like the ones you see in your screenshot that say "Operation will NOT be retried..." it could be that 16.4.2 has some DiagnosticSource behavior that 2019 Preview does not on the way it captures those traces.

**Comment by NoahStahl** [comment]
It turns out it must have been some setting I changed. After doing Visual Studio's "Reset all settings" from the Import/Export Settings Wizard, the behavior disappears. My guess is something in the Debug settings, but I'm not sure. Diffing 3000 lines of exported settings XML doesn't immediately reveal anything. :)

Anyhow, I'll mark as closed, sorry to bother!
