### ISSUE TITLE
Enhance samples and or documentation to describe behavior of cross partition queries

### ISSUE THREAD

**Issue by dustensalinas** [Azure/azure-cosmos-dotnet-v3#1172]
Documentation and samples of V3 do not reflect a key design and implementation functionality that is relatively unique to Cosmos: any cross partition query requires aggregating all result set responses.

Example: If partition is unknown a simple query of `SELECT TOP 1 * FROM c WHERE c.id = "someid"` will can return multiple empty result sets before returning one that has the value.

**Comment by bchong95** [comment]
We expose `FeedIterator` that has a `HasMoreResults` the contract is to drain it while `HasMoreResults` is true and the pages itself may be empty. Empty pages should be treated just like any other pages. If you require a non empty page for your application, then you can drain until you receive a non empty page and aggregate some the headers like RU in your application.

This article also has some insights:

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-pagination
