### ISSUE TITLE
Implement client-side encryption API's for Tables the same way as we have in the WindowsAzure SDK's

### ISSUE THREAD

**Issue by Zimmergren** [Azure/azure-cosmos-dotnet-v3#1177]
**Is your feature request related to a problem? Please describe.**
We cannot re-use and implement all our encryption logic if we move over to the Cosmos SDK's. 
Please see previous issue here: https://github.com/Azure/azure-cosmos-dotnet-v2/issues/710#issuecomment-578607609

**Describe the solution you'd like**
Parity with the API's in the WindowsAzure NuGets for Table Storage, or a new solution for implementing custom client-side encryption techniques like the envelope technique - out of the box. 

**Describe alternatives you've considered**
The only real-world alternative right now is to move back to the WindowsAzure nugets, and stay off of Cosmos' API's until we can resolve the encryption.

**Additional context**
The client-side encryption we're talking about can be found here: 
https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption

**Comment by j82w** [comment]
@Zimmergren can you take a look at this PR?

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1124
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1123

@abhijitpai will the current AKV implementation work with this?

**Comment by abhijitpai** [comment]
@j82w - I believe it should, maybe with some small additional wrapper to meet Tables interface requirements. @Zimmergren - am thinking https://github.com/Azure/azure-cosmos-table-dotnet/issues/30 should be the place to discuss this assuming you want to continue using the Table API with Cosmos DB and are looking for API compat (to the extent possible) with the existing WindowsAzure SDKs. If you are open to switching to our core (SQL) API, the links @j82w pointed to will help with this - let me know which option you are interested in.

**Comment by Zimmergren** [comment]
Ideally I'd love to continue to use the code base I have (the same interfaces and APIs), using the Cosmos nugets. For me the only missing piece right now is the client side encryption capabilities - I've worked around this by using custom property attributes that's handing encryption as needed, but ideally we'd use the built-in approach as per the original Table SDK - if it's on the roadmap, that's awesome - if not, the effort will be that we'll revert back to the WindowsAzure SDK's rather than stay on the Cosmos SDK's.

We don't use SQL in any extent; Purely Azure Storage Accounts.

**Comment by abhijitpai** [comment]
Ok, Tables API functionality is tracked in the repo I mentioned (such as in the issue I linked to).

**Comment by Zimmergren** [comment]
Following it there, thanks @abhijitpai!

**Comment by joshbouganim** [comment]
can this be reopened? v2 hasn't seen a commit in over a month so it doesnt really make sense to track this feature request [over there](https://github.com/Azure/azure-cosmos-dotnet-v2/issues/710).  there is currently no microsoft library with table encryption for .net core. currently only client side blob encryption is supported for .net core

**Comment by abhijitpai** [comment]
@joshbouganim It won't help if you re-open this - the issue I pointed to (https://github.com/Azure/azure-cosmos-table-dotnet/issues/30) is in the SDK repo for Cosmos DB's Table API, and not the v2 repo for Cosmos DB's SQL API.

**Comment by joshbouganim** [comment]
@abhijitpai understood. my mistake. i'll comment there.
