### ISSUE TITLE
ArgumentException on Continuation token when using DISTINCT query with OrderBy and GetItemLinqQueryable

### ISSUE THREAD

**Issue by MortLupus** [Azure/azure-cosmos-dotnet-v3#1181]
**Describe the bug**
When querying cosmosDB with GetItemLinqQueryable<TEntity> which includes a join with both distinct and an order by clause it is unable to return a continuation token. Instead it return the following error:

"DISTINCT queries only return continuation tokens when there is a matching ORDER BY clause.
For example if your query is 'SELECT DISTINCT VALUE c.name FROM c', then rewrite it as 'SELECT DISTINCT VALUE c.name FROM c ORDER BY c.name'."

**To Reproduce**
Example query:
var query = GetContainer().GetItemLinqQueryable<Family>(requestOptions: feedOptions)
	.SelectMany(x => x.Child)
	.Where(c => c.Name = "Name")
	.OrderBy(x => x.Order)
	.Distinct();

var feedResponse = await query.ToFeedIterator().ReadNextAsync();
continuationToken = feedResponse.ContinuationToken;

And when translated to SQL:
SELECT DISTINCT VALUE root FROM root JOIN p0 IN root["child"] WHERE p0["name"] = ORDER BY root.["order"] ASC

**Expected behavior**
Continuation token should be returned and not an error returned.

**Actual behavior**
Exception thrown with error message as above:

**Environment summary**
SDK Version: 3.6.0
OS Version Windows

**Additional context**
From what I understand this is caused by the DistinctQueryType being set to Unordered which results in the continuation token being unable to be retrieved. The description on the enum DistinctQueryType indicated that this happens when the query is not ordered perfectly. But does not describe exactly how this is determined. Is there any way to have this query flagged as Ordered without having to order by every field that is returned in the full Document class?

**Comment by j82w** [comment]
@bchong95 can you take a look?

**Comment by bchong95** [comment]
The error message has the resolution:

The query:

SELECT DISTINCT VALUE root 
FROM root 
JOIN p0 IN root["child"] 
WHERE p0["name"] = <name>
ORDER BY root.["order"] ASC

does not have a matching ORDER BY.

You are taking the distinct of root and ordering by root.order. The projection and order by should match.

**Comment by MortLupus** [comment]
Thanks, @bchong95 But this doesn't help the use case I have where the method
GetItemLinqQueryable returns a full document object that might have many properties in it, and I can't order by all of them. 
Is there no way for the SDK to use a join with distinct and order by and still return a fully hydrated object?

**Comment by MortLupus** [comment]
Hi @bchong95, do you have an answer for my question?

**Comment by aakonnikau** [comment]
having same issue.

**Comment by mwf-shell** [comment]
I'm also having this problem. Has anyone found a solution or workaround?

**Comment by ranjithr702** [comment]
I am also having the same issue. Is there any solution for this problem?
