### ISSUE TITLE
Linq Provider produces invalid SQL query when using deep-nested Any()/Where() clause with filters

### ISSUE THREAD

**Issue by countincognito** [Azure/azure-cosmos-dotnet-v3#1184]
**Describe the bug**
I am using Microsoft.Azure.DocumentDB v3.3.2 (via Cosmonaut) with Linq to filter documents based on the contents of nested properties (**this issue seems to only happen with the nested properties are more than 1 level deep**). Specifically, when using Any() or Where() with filtering conditions the Linq Provider generates an invalid SQL query.

**To Reproduce**
The documents being queried resemble the following structure:

```
[
  {
    "Data": {
      "Readings": [
        {
          "Status": "valid"
        },
        {
          "Status": "invalid"
        }
      ]
    }
  },
  {
    "Data": {
      "Readings": [
        {
          "Status": "invalid"
        },
        {
          "Status": "invalid"
        }
      ]
    }
  }
]
```

When searching a queryable in the following way:

`entities.Where(x => x.Data.Readings.Any())`

the query produced is absolutely fine:

`{{"query":"SELECT VALUE root FROM root JOIN (SELECT VALUE EXISTS(SELECT VALUE v0 FROM root JOIN v0 IN root[\"Data\"][\"Readings\"] ) ) AS v1 WHERE (v1 > 0) "}}`

However, if I include a condition in the Any() clause:

`entities.Where(x => x.Data.Readings.Any(y => y.Status == "valid"))`

then the query produces invalid syntax:

`{{"query":"SELECT VALUE root FROM root JOIN (SELECT VALUE EXISTS(SELECT VALUE 0 FROM root JOIN 0 IN root[\"Data\"][\"Readings\"] WHERE (LOWER(0[\"Status\"]) = \"valid\") ) ) AS v0 WHERE (v0 > 0) "}}`

**Expected behavior**
Ideally, the query produced should look something like the following:

`{{"query":"SELECT VALUE root FROM root JOIN (SELECT VALUE EXISTS(SELECT VALUE v0 FROM root JOIN v0 IN root[\"Data\"][\"Readings\"] WHERE (LOWER(v0[\"Status\"]) = \"valid\") ) ) AS v1 WHERE (v1 > 0) "}}`

using an alias like "v0" instead of "0".

This query works perfectly fine against CosmosDb and produces the expected result.

**Actual behavior**
If I run the actual query that is produced:

`{{"query":"SELECT VALUE root FROM root JOIN (SELECT VALUE EXISTS(SELECT VALUE 0 FROM root JOIN 0 IN root[\"Data\"][\"Readings\"] WHERE (LOWER(0[\"Status\"]) = \"valid\") ) ) AS v0 WHERE (v0 > 0) "}}`

then Cosmos complains that there is a syntax error near the "0" alias (presumably because aliases that begin with numerical characters are invalid).

**Environment summary**

SDK Version: dotnet core 3.1 (v3.3.2 of Microsoft.Azure.DocumentDB)
OS Version (e.g. Windows, Linux, MacOSX): Windows 10 Pro

**Additional context**
I have tested this against Cosmos in the cloud and the latest Cosmos emulator - the same issue seems to occur for both.

I have also try this with the Microsoft.Azure.Cosmos v2.5.1 library, but the problem exists there as well (https://github.com/Azure/azure-cosmos-dotnet-v2/issues/758).

**Comment by khdang** [comment]
The actual translated query contains "LOWER" suggests that either the LINQ expression is not ```entities.Where(x => x.Data.Readings.Any(y => y.Status == "valid"))```, or the SQL query has been modified.

I've tried but was not able to reproduce this issue. Here's the code I used:
```csharp
        public class EntityReading
        {
            public string Status;
        }

        public class EntityData
        {
            public EntityReading[] Readings;
        }

        public class Entity
        {
            public EntityData Data;
        }

        public void TestReproLinq()
        {
            // create testContainer to a test endpoint

            IOrderedQueryable<Entity> query = testContainer.GetItemLinqQueryable<Entity>(allowSynchronousQueryExecution: true);
            string sql = query.Where(x => x.Data.Readings.Any(y => y.Status == "valid")).AsDocumentQuery().ToString();
        }
```

The sql string has the value ```{"query":"SELECT VALUE root FROM root JOIN (SELECT VALUE EXISTS(SELECT VALUE y0 FROM root JOIN y0 IN root[\"Data\"][\"Readings\"] WHERE (y0[\"Status\"] = \"valid\") ) ) AS v0 WHERE v0 "}```.

In order to investigate, could you please share a minimum repro? Thank you.

**Comment by countincognito** [comment]
@khdang My apologies - while investigating the minimal repo you requested I discovered that the real problem stemmed from a dependency buried deep in our code that was manipulating the Linq Expression before it was being passed to the Cosmos SDK. Though the Expression was valid, it was then being interpreted by the DocumentQueryProvider in such a way to produce the SQL listed in my original post.

It seems that the problem is either: a) the DocumentQueryProvider in Microsoft.Azure.Documents.Linq is struggling to interpret this particular style of Expression in order to produce valid SQL; or b) the Expression generated from the Linq is improper for querying CosmosDb. Either way, I don't think it would be right to keep this issue open until I can pinpoint precisely where the problem lies.

For now I will close this issue and (if I can find the real reason for the problem lies in the Cosmos SDK) I will open a new issue later if necessary.

Once again, apologies for the trouble and thank you for your advice.
