### ISSUE TITLE
Doesn't work with json streams that contain encoding bytes

### ISSUE THREAD

**Issue by jbt00000** [Azure/azure-cosmos-dotnet-v3#1194]
`Stream GetStream(object item)
{
    var st = new MemoryStream();
    /*
        The problem here is that in order to create a streamwriter that does not auto-close the underlying stream
        you must also specify an encoding.  When you specify an encoding, that gets output to the underlying stream.
        Cosmos does not understand that encoding mark.
        */
    using (var sw = new StreamWriter(st, Encoding.UTF8, 1024, true))
    {
        Serializer.Serialize(sw, item);
        sw.Flush();
    }
    st.Position = 0;
    return st;
}

async Task SaveTheObject(object item, CosmosContainer container)
{
    using (var st = GetStream(item))
    {
        await container.CreateItemStreamAsync(st, new PartitionKey("MyPartitionKey"));
    }
}

//also impacts custom cosmosserializers
`
"Errors":["The request payload is invalid. Ensure to provide a valid request payload."]

The problem is that when you create the streamwriter, wrap it in a using (as it is disposable and it should be done), you must pass keepOpen=true, or it will close the parent stream.  The only signature which allows you to specify keepOpen also makes you pass in an encoding.  In theory, this should be fine.  However, it will serialize the 2 byte encoding at the start of the stream.

The problem then hits you as CosmosDB sees these 2 initial bytes and chokes.

One can of course be sloppy, not dispose the stream writer, and let the garbage collector clean up after you.

Temporarily I chose to get around this issue was to pass a wrapped stream to the streamwriter that simply disregards the dispose command from the streamwriter.

And... positioning the stream at offset 2 does not work either.  I haven't read the source code, but I believe the SDK may position the stream at 0 instead of using it from the current position....

**Comment by j82w** [comment]
The [default serializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8923507ee78aeb6ae7f6bba64933fabd445dc38a/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs#L108) returns the  open stream. You need to [disable](https://docs.microsoft.com/en-us/dotnet/api/system.text.utf8encoding.-ctor?view=netframework-4.8#System_Text_UTF8Encoding__ctor_System_Boolean_System_Boolean_)emitting the [utf8Encoding](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8923507ee78aeb6ae7f6bba64933fabd445dc38a/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs#L19). If you look at the [documentation](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8923507ee78aeb6ae7f6bba64933fabd445dc38a/Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializer.cs#L26) the serializer will take ownership of the stream and ensure that it will get disposed of.

**Comment by jbt00000** [comment]
Nice to know that you read the issue.  The problem is NOT with your default serializer closing the stream..  It is not with your default serializer at all.  This manifests when you're using CreateItemStreamAsync OR when you replace the default serializer via CosmosClientOptions.  The problems are as follows:

- If you tell StreamWriter to NOT auto close the underlying stream, you cannot prevent it from emitting the BOM.  Obviously this is not your problem

- Cosmos cannot deal with strings that contain a BOM (didn't read the code to see if this was client side in your SDK or server side which cannot accept it).  But if you don't fix in the server, it is the responsibility of your SDK to fix or for you to document.

- You are repositioning the input stream to zero instead of using it from the position you were passed. This is within: Microsoft.Azure.Cosmos.Direct.dll!Microsoft.Azure.Documents.StreamExtension.CopyStreamAndReturnAsync(System.IO.Stream mediaStream)

I think that at minimum, remarks in the documentation about those APIs (we cannot deal with byte order marks and we reposition your stream) are in order.  If you're using the non-built in serializer, those tidbits can save developers gobs of time.  Accommodating BOM and not repositioning input streams are better solutions.

**Comment by jbt00000** [comment]
The problem is NOT with your default serializer closing the stream.. It is not with your default serializer at all. This manifests when you're using CreateItemStreamAsync OR when you replace the default serializer via CosmosClientOptions.

I had a different workaround, you pointing out an alternate constructor on 

`new StreamWriter(st, new System.Text.UTF8Encoding(**false**), 1024 * 1024, **true**)`

rather than blindly using the static instance

`System.Text.Encoding.UTF8`

was better.

That said, it would be great if the documentation you pointed to and CreateItemStreamAsync state that you only accept UTF-8 encoded buffers (sucks if you have a UTF-16 file on disk..) w/o the BOM and that you require a stream that can be repositioned and is zero based. as the following repositions the input:

`Microsoft.Azure.Cosmos.Direct.dll!Microsoft.Azure.Documents.StreamExtension.CopyStreamAndReturnAsync(System.IO.Stream mediaStream)`
