### ISSUE TITLE
Why is index utilization 0.00 %?

### ISSUE THREAD

**Issue by erickbp** [Azure/azure-cosmos-dotnet-v3#12]
Hi,

Can you please help me figure out why index utilization is 0.00 %?

I'm including this path in the indexing policy:
```
{
	"path": "/receivedDateTime/?",
	"indexes": [
		{
			"kind": "Range",
			"dataType": "Number",
			"precision": -1
		},
		{
			"kind": "Hash",
			"dataType": "String",
			"precision": 3
		}
	]
}
```
and this is an example of my documents:
```
{
    "id": "",
    "userId": "XYZ",
    ...
    "receivedDateTime": 635903262620000000,
    ...
}
```

When I run the following query I get zero index utilization.
Notes:
1. It does not happen with any other property/path that I included in the indexing policy
2. UserId is the partition key

```
_client.CreateDocumentQuery<Message>(UriFactory.CreateDocumentCollectionUri(_databaseId, _collectionId),
                    new FeedOptions
                    {
                        PopulateQueryMetrics = true,
                        MaxItemCount = maxItemCount
                    })
                .Where(item => item.UserId == Guid.Parse("XYZ"))
                .OrderBy(m => m.ReceivedDateTime)
                .AsDocumentQuery();
```
![image](https://user-images.githubusercontent.com/10678433/49682162-2eedea00-fa7d-11e8-9217-aa3d0e18a183.png)

On the other hand if I add `item.ReceivedDateTime >= 0` to the where clause I get 98.02 % of index utilization even when `item.ReceivedDateTime >= 0` is true for all the documents.
```
_client.CreateDocumentQuery<Message>(UriFactory.CreateDocumentCollectionUri(_databaseId, _collectionId),
                    new FeedOptions
                    {
                        PopulateQueryMetrics = true,
                        MaxItemCount = maxItemCount
                    })
                .Where(item => item.UserId == Guid.Parse("XYZ") && item.ReceivedDateTime >= 0)
                .OrderBy(m => m.ReceivedDateTime)
                .AsDocumentQuery();
```
![image](https://user-images.githubusercontent.com/10678433/49682190-fac6f900-fa7d-11e8-9368-3246d49d69f1.png)

Thank you

**Comment by j82w** [comment]
This is related to the v2 SDK, and there is already a duplicate question in that repo. https://github.com/Azure/azure-cosmos-dotnet-v2/issues/646
