### ISSUE TITLE
LINQ support for Group By

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#1202]
Capturing requirement for LINQ GroupBy support to track future progress.

**Comment by markjbrown** [comment]
Stack question on this, https://stackoverflow.com/questions/60356762/efcore-3-1-cosmosdb-query-could-not-be-translated

Thanks.

**Comment by pnda489** [comment]
Is there any ETA for this?

**Comment by valerionatangelo** [comment]
We really need an ETA on this feature.

**Comment by dan-matthews** [comment]
/bump... I've been waiting for this feature a loooong time and it seems SO close :)

**Comment by AshishMoradiya** [comment]
Waiting for group by support

**Comment by petro2050** [comment]
any update?

**Comment by joergeugster** [comment]
still waiting....?

**Comment by ealsur** [comment]
@khdang Do you have any updates on this request?

**Comment by onionhammer** [comment]
This would be tremendous! Are the supported operations documented somewhere or do we just figure it out by trial and error at runtime?

**Comment by fvalentiner** [comment]
It would be amazing! It's basically the only thing holding us from migrating to CosmosDB

**Comment by alexeymarkov** [comment]
Any news there?
Requesting all entities to the client and doing GROUP BY and COUNT operations at the client results in a significant higher RUs...

**Comment by adstep** [comment]
Love to see this feature supported.

**Comment by vengi83644** [comment]
Must needed !!!

**Comment by j82w** [comment]
@timsander1 any update on this?

**Comment by timsander1** [comment]
This is on our long-term roadmap but unplanned in the current 6 month semester. For now, we recommend using SQL queries instead of LINQ if you need to use GROUP BY.

**Comment by dan-matthews-takeda** [comment]
> This is on our long-term roadmap but unplanned in the current 6 month semester. For now, we recommend using SQL queries instead of LINQ if you need to use GROUP BY.

Unfortunately, using SQL queries just isn't possible for us - and I suspect most people using LINQ queries. We build up a query using LINQ expressions, often using generics through a repository pattern or similar. To construct SQL queries would require an entire and extremely complex re-architecture of our entire solution. Not having GroupBy LINQ support is actually killing our Cosmos DB RUs - we're having to double-hit the DB with large result sets.

I understand that everything has a priority so, given that this ticket has been open over a year already, is the delay due to low priority or complexity of implementation?

**Comment by vengi83644** [comment]
> > This is on our long-term roadmap but unplanned in the current 6 month semester. For now, we recommend using SQL queries instead of LINQ if you need to use GROUP BY.
> 
> Unfortunately, using SQL queries just isn't possible for us - and I suspect most people using LINQ queries. We build up a query using LINQ expressions, often using generics through a repository pattern or similar. To construct SQL queries would require an entire and extremely complex re-architecture of our entire solution. Not having GroupBy LINQ support is actually killing our Cosmos DB RUs - we're having to double-hit the DB with large result sets.
> 
> I understand that everything has a priority so, given that this ticket has been open over a year already, is the delay due to low priority or complexity of implementation?

+100000

**Comment by leonids2005** [comment]
this is a big problem for us as well!!!  Really need this feature!!!

**Comment by randolphpark** [comment]
I am expericing same issue. Please do cosnider to prioritise this feature. Much appriciated.

**Comment by onionhammer** [comment]
GroupBy is kind of an antipattern until cosmos can somehow utilize the index under on the server; currently it has to read through every single document to execute a group by

**Comment by leonids2005** [comment]
why it is an anti-pattern I do not understand? 
If the engine cannot efficiently execute the operation it does not mean this is an anti-pattern :) 

Group by is supported by SDK so it should be supported in Linq... this is a standard functionality imo.

**Comment by onionhammer** [comment]
> If the engine cannot efficiently execute the operation it does not mean this is an anti-pattern :)

it would be great if it were supported, but it would be even better if the server supported it better so groupby's cost wasnt directly proportional to how much data is in your container.

When I query 'select count(c) from c' and get back `127000`, it costs 11 RUs and .6ms

When I query 'SELECT count(c), c.Stage FROM c GROUP BY c.Stage`, I get back 8 records and it costs 4574 RUs and 127ms

**Comment by leonids2005** [comment]
Here I agree with you.... this is really unfair... we pay for their inefficiency :(

**Comment by fvalentiner** [comment]
@orionhammer

We use the Synapse Link feature to do that. So far it has worked great. A bit slow to get the SQL Queries out of Synapse but overall works ok

**Comment by onionhammer** [comment]
@fvalentiner we use that too for our reporting in PowerBI, but not our frontend application servers - too slow, as you said.

**Comment by leonids2005** [comment]
Curiosity, does the CosmosDB team read this, and how often? on the 23rd of April, they said it is not on 6 months roadmap.  
I think we **deserve** some updates after 7 months.  
We have raised this issue in our FastTrack project discussion but also have not gotten any response. :( ... disappointing.

**Comment by PKPublicCode** [comment]
Let me congratulate this feature request on 2-nd anniversary :)
Dear team, when you say 'on long-term roadmap', how really long is this term?

**Comment by timsander1** [comment]
Hi all, quick update that LINQ support for GROUP BY is planned for the first half of this calendar year. We're also investing in some improvements in GROUP BY performance that will be released around the same time.

**Comment by onionhammer** [comment]
> Hi all, quick update that LINQ support for GROUP BY is planned for the first half of this calendar year. We're also investing in some improvements in GROUP BY performance that will be released around the same time.

Meaning investing in improving group by perf on the cosmos server side?

**Comment by dan-matthews-takeda** [comment]
Here's hoping that it will include the ability to sort by more than 1 column without an index ;)

**Comment by timsander1** [comment]
> > Hi all, quick update that LINQ support for GROUP BY is planned for the first half of this calendar year. We're also investing in some improvements in GROUP BY performance that will be released around the same time.
> 
> Meaning investing in improving group by perf on the cosmos server side?

That's correct. Improvements within the query engine.

**Comment by timsander1** [comment]
For additional feedback, could you please share ideas here: https://feedback.azure.com/d365community/forum/3002b3be-0d25-ec11-b6e6-000d3a4f0858

While we review Github issues, they don't get nearly the same attention as the above site. We also post updates on the above site at a regular 6 month cadence, when we plan our roadmap.

**Comment by ivpadim** [comment]
Cant wait for this feature to ship!

**Comment by shekarc** [comment]
Do you know of the anticipated release date for this feature?

**Comment by rmajid2** [comment]
Any updates on Group By Improvements  (Linq support, engine optimization , index, RU Cost, Order By ...) ?

**Comment by dan-matthews** [comment]
Any news on this, Cosmos team? Been waiting for this feature a looooong time ;)

**Comment by markjbrown** [comment]
Adding @jcocchi

**Comment by dave101ua** [comment]
Hello !
Any plans regarding requested feature, please ?

**Comment by adamreed90** [comment]
> FYI https://devblogs.microsoft.com/cosmosdb/introducing-a-new-system-function-and-optimized-query-operators/#group-by-and-distinct-optimizations

Indeed it is supported in the query language but not supported with LINQ, the purpose of this raised issue.

**Comment by dan-matthews** [comment]
o/~ All I want for Christmas... is support for LINQ GroupBy... o/~

**Comment by machielvisser** [comment]
And we reached Q2 2023, even though @timsander1 indicated it was planned for H1 2022. What happened since then?

**Comment by markjbrown** [comment]
Adding @jcodella

**Comment by jmolla31** [comment]
Hi do we have a roadmap for this?

**Comment by dan-matthews** [comment]
June 2023, and still all quiet on this most vital and wanted aspect of Cosmos DB! Given that this is such a hotly awaiting feature by so many people, but it is not ever being implemented - does this suggest the state of the overall Cosmos DB service? *curious*

**Comment by syedfahimabrar** [comment]
fuck you

**Comment by kipusoep** [comment]
Sad Sad little personen.

**Comment by jacobmohl** [comment]
+1 on this...

**Comment by jcocchi** [comment]
Hi everyone, thanks for your patience as we work on this highly anticipated feature- we appreciate your feedback! Group By support in LINQ is planned for Fall 2023.

**Comment by onionhammer** [comment]
Will add #3935 after group by support is added

**Comment by FMax95** [comment]
+1 on this...

**Comment by Mapel** [comment]
yeah, couple minutes ago I had to write a query string because CosmosDB LINQ is not supporting Group By...it's not very fun...

So +1

**Comment by jmolla31** [comment]
We make heavy use of CosmosDB on my company and the lack of GroupBy support is really hurting.

Any eta on this?

**Comment by Marusyk** [comment]
25.11.2023 - Method 'GroupBy' is not supported

**Comment by Rasmus715** [comment]
+1. Please prioritize. It's been 4 years since this issue is opened.

**Comment by Maya-Painter** [comment]
#4074

**Comment by leminh98** [comment]
#4481

**Comment by next-phil** [comment]
Are there any plans to support projections into types rather than only anonymous types as the examples in #4857 demonstrate?
Does this warrant another issue creating?

```
// Current
Enumerable.GroupBy( 
/*keySelector*/ k => k.Id, 
/*valueSelector*/ (key, values) => new
{
    idField = key.key1,
    count = values.Count(),
});

//Proposed
Enumerable.GroupBy( 
/*keySelector*/ k => k.Id, 
/*valueSelector*/ (key, values) => new MyDto
{
    idField = key.key1,
    count = values.Count(),
});
```
