### ISSUE TITLE
Fire and forget

### ISSUE THREAD

**Issue by jbt00000** [Azure/azure-cosmos-dotnet-v3#1203]
When you are creating or upserting large documents the performance is... not great.  One avoidable cause is these APIs always return the created object. So if I upload a 100k doc, I get a download of 100k. And I throw it away. There should be a way to prevent azure from return the created doc. This will increase performance and decrease data egress costs.

**Comment by j82w** [comment]
@kirankumarkolli ?

**Comment by kirankumarkolli** [comment]
It wold be a nice feature to have. Guess Its a gap on service side. 
@j82w please check with service crew.

**Comment by j82w** [comment]
@jbt00000 the feature is in the roadmap for the service. Once it's available we will create a PR to add a request option flag to enable it. Thanks for the suggestion.

**Comment by jbt00000** [comment]
That's great!  It will help all loading scenarios.

**Comment by pentp** [comment]
This is blocking our migration from V2 to V3 (similar situation to #1266).
We have no need for the reflected document object from the response and the `<T>` type is often abstract (which fails on deserialization).
It's also bad for performance, so I would really like to have an option to have the `ItemResponse.Resource` be lazy initialized/optional. Ideally, this should be configurable on `CosmosClientOptions` also (as a default).

Additionally, **this should apply to `DeleteItemAsync<T>` also**.

**Comment by j82w** [comment]
@pentp and @jbt00000 [3.9.0-preview3](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.9.0-preview3) is released

**Comment by jbt00000** [comment]
I'm excited and will test over the weekend.

Next up, compression?!?!
