### ISSUE TITLE
Question: V3/V4 interop

### ISSUE THREAD

**Issue by bartelink** [Azure/azure-cosmos-dotnet-v3#1207]
Looking for formal confirmation of 

1. v2 and V3 SDKs can be used in the same process; they have different names/impls and don't clash (but you're using extra expensive resources such as connections)
2. (obv, but for avoidance of doubt) V2 and V3 have some API differences
3. v3 and v4 will have minimal API differences brought about by CosmosDb (are there transitive deps exposed that vary though ?)
4. it will not be possible to run a v3 and v4 client in the same process; they'll have the same names
5. v4 won't even reference Newtonsoft.Json (V3 provides a way to avoid using it, but it does reference it)
6. _(this is my question, assuming I have not said too much in the previous statements!)_ you can simply swap in v4 Azure.Comos binaries to replace V3 ones ? with binding redirects? 

7. Is there a statement about this stuff anywhere?

8. Is there a preview sdk available somewhere?

eta: I see [this in the changelog](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/changelog.md#key-differences-with-v3) is what I'd been hallucinating about - it all but answers my question

**Comment by j82w** [comment]
@kirankumarkolli is there a statement anywhere about this?

v4 code is currently in the [v4 branch](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/v4)
[v4 changelog](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/changelog.md) and [preview nuget](https://www.nuget.org/packages/Azure.Cosmos/4.0.0-preview3)

1. Yes, but it's not recommended as you pointed out about the extra resource cost. Some of the classes have the same names, but are in different namespaces.
2. V2 and V3 have different APIs
4. v3 (Microsoft.Azure.Cosmos) and v4 (Azure.Cosmos) have different namespaces.
5.  v4 aligns with the [Azure Core SDK team](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core) and their [guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-dependencies) which state all Newtonsoft.Json dependencies need to be removed.

@ealsur can you answer 3 and 6?

**Comment by ealsur** [comment]
3. We are still in preview, but there are already API changes that are breaking changes. Leaving aside the type renames (CosmosContainer), we are [completely removing Newtonsoft.Json](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1119), and we are still under review for further changes.
6. No, these are different DLLs with different namespaces, no binding redirects will apply.

**Comment by bartelink** [comment]
Thanks everyone, I believe that answers all my questions and more
In case anyone missed it, https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/changelog.md#key-differences-with-v3 summarizes all these API changes very well in more detail, and likely will continue to

**Comment by ealsur** [comment]
Glad to know that summary worked, tried to dump all the key differences there. As you said, it's a live document.
