### ISSUE TITLE
DEK cache eviction

### ISSUE THREAD

**Issue by abhijitpai** [Azure/azure-cosmos-dotnet-v3#1211]
Ensure eviction of items in DEK caches used in client side encryption based on security and performance requirements.

**Comment by abhijitpai** [comment]
MemoryCache used within Microsoft Data Encryption clears out expired values, and we no longer own any cache with raw keys in the public model. We can verify for the internal model and close.

**Comment by anujtoshniwal** [comment]
For the internal model (also integrated with Microsoft Data Encryption package), we are no longer caching any sensitive data (raw keys), we are only caching DataEncryptionKeyProperties (non-sensitive).
