### ISSUE TITLE
ETag property throws null ref exception when there's no raw response available (4.0.0-preview3)

### ISSUE THREAD

**Issue by Jaah** [Azure/azure-cosmos-dotnet-v3#1212]
**Describe the bug**
Inheriting from `ItemResponse<T>` class and *not* overriding `ETag` property in the derived class will cause null reference exception being thrown when you try to access the ETag field despite it being nullable.

Looking at the source code, this seems to happen when there is no raw response available;
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/releases/4.0.0-preview3/Microsoft.Azure.Cosmos/azuredata/Resource/Container/ItemResponse.cs#L70

**To Reproduce**
```csharp
public class MockItemResponse<T> : ItemResponse<T>
{
    public MockItemResponse(T value) { }
}

class Program
{
    static void Main(string[] args)
    {
        var response = new MockItemResponse<string>("test");

        var test1 = response.ETag.HasValue; // Null ref exception
        var test2 = response.ETag == null; // Null ref exception
        var test3 = response?.ETag == null; // Null ref exception
    }
}
```

**Expected behavior**
Return null.

**Actual behavior**
NullReferenceException is being thrown.

**Environment summary**
SDK Version: 4.0.0-preview3
OS Version: Windows

**Additional context**
I assume this it not an issue you run into in normal use, but it is a bit unexpected behavior when writing mocks for unit testing purposes, given that the property is marked as nullable.

**Comment by j82w** [comment]
@Jaah thanks for reporting this. It should be updated to do

**Comment by ealsur** [comment]
The ETag property is also `virtual`, if the intent is to mock, why not Mock it to return the value you expect for your scenario?

**Comment by ealsur** [comment]
For reference:
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/Resource/Container/ItemResponse.cs#L70

**Comment by Jaah** [comment]
> 
> 
> The ETag property is also `virtual`, if the intent is to mock, why not Mock it to return the value you expect for your scenario?

That is what I ended up doing after encountering this issue of course. 

The reason why I did not mock it right from the beginning was simply because in this particular case it was fine for the ETag property to be null, which I assumed it would be given the type of the property (before looking at the source).

I guess it could be worth considering whether the property could be changed to be non-nullable, and if the header is not present, return an empty etag instead?

**Comment by ealsur** [comment]
If you use `Mock<ItemResponse<T>>` instead of inheriting from the class it will work as expected. If you inherit from the class, and not override any method, this will use the default implementation.

There is no scenario for ItemResponse where there is no related Response, so adding a null check on the ETag getter makes little sense. It's the same case for Session, the default implementation reads the Response headers.

**Comment by Jaah** [comment]
Fair enough

**Comment by ealsur** [comment]
Closing as mocking is possible and ETag is always expected on the real scenario
