### ISSUE TITLE
JSON Converter support in v4?

### ISSUE THREAD

**Issue by Mortana89** [Azure/azure-cosmos-dotnet-v3#1216]
We're in the process of migrating our microservices to .NET Core 3.1.
One of the big changes is ofcourse the migration to system.text.json. We'd rather do it now instead of do the work twice, as such we're investigating the impact of using the v4 version instead of the Cosmonaut package we're very happy to use, to prevent any remaining discrepancies between JSON serializers.
However, I noticed that for v4, we're still not completely using an existing system.text.json serializer, but something that's similar, CosmosSerializationOptions.

2 Questions;
- Why has there been chosen to use a new serializer options instead of using the existing System.Text.Json/Newtonsoft one?
- How can we pass custom converters to this new serializer option? Without this we can basically never do custom conversions for anything that's not natively supported in STJ (which is quite a big list until .NET 5 :( )

Thanks!

**Comment by j82w** [comment]
The reason CosmosSerializationOptions was chosen for v3 is it reduced dependencies on Newtonsoft. As part of v4 it will be removing all Netwonsoft dependencies. I believe the reason it still CosmosSerializationOptions is it allows easier upgrades from v3 and again reduces the exposure of an external library. 

@ealsur any suggestions on creating custom converters in v4?

**Comment by Mortana89** [comment]
> The reason CosmosSerializationOptions was chosen for v3 is it reduced dependencies on Newtonsoft. As part of v4 it will be removing all Netwonsoft dependencies. I believe the reason it still CosmosSerializationOptions is it allows easier upgrades from v3 and again reduces the exposure of an external library.
> 
> @ealsur any suggestions on creating custom converters in v4?

Since system.text.json is now a native lib compared to the external Newtonsoft, wouldn't V4 be a good moment to align?

**Comment by j82w** [comment]
v4 is still in preview so it's still possibility still. @ealsur is there any plans for this?

**Comment by ealsur** [comment]
V4 is on System.Text.Json, there are no Newtonsoft.Json classes or types that are used.

The CosmosSerializationOptions is just an option for serialization customization. If you were using CosmosSerializationOptions on V3 to customize the Newtonsoft.Json serializer, then you can use the same option values to obtain the same effect but through System.Text.Json.

You can either:
* Customize the System.Text.Json serializer behavior through CosmosSerializationOptions
* Use your own custom serializer by implementing CosmosSerializer
* Decorate your classes with custom System.Text.Json converters and they will be honored by the default serializer

If what you want is create custom System.Text.Json converters for classes, you can either take a look at [one of ours](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/v4/Microsoft.Azure.Cosmos/azuredata/Serializer/Settings) or follow the official docs at https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-converters-how-to

**Comment by Mortana89** [comment]
> V4 is on System.Text.Json, there are no Newtonsoft.Json classes or types that are used.
> 
> The CosmosSerializationOptions is just an option for serialization customization. If you were using CosmosSerializationOptions on V3 to customize the Newtonsoft.Json serializer, then you can use the same option values to obtain the same effect but through System.Text.Json.
> 
> You can either:
> 
> * Customize the System.Text.Json serializer behavior through CosmosSerializationOptions
> * Use your own custom serializer by implementing CosmosSerializer
> * Decorate your classes with custom System.Text.Json converters and they will be honored by the default serializer
> 
> If what you want is create custom System.Text.Json converters for classes, you can either take a look at [one of ours](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/v4/Microsoft.Azure.Cosmos/azuredata/Serializer/Settings) or follow the official docs at https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-converters-how-to

I think I'm following; we're registering all our custom converters in the JsonOptions object upon startup.cs. If I want to reuse these settings, I'd only have options 2, as option 1 does not cover all settings (more specifically, if I read https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/Serializer/CosmosJsonDotNetSerializer.cs I can see no converters being copied over)?

It's not a matter of creating converters/decorators, we all have that in place for the system.text.json migration now. I'm just trying to understand what would be the most efficiënt/solid approach to not register my converters and settings multiple times. So is option 2 in that case still the way forward?

**Comment by ealsur** [comment]
Currently we have no public API that will take your existing JsonOptions. But one thing would be, if you can decorate your classes with the JsonConverter, then that would work anywhere, as long as System.Text.Json is the engine being used.

**Comment by Mortana89** [comment]
> Currently we have no public API that will take your existing JsonOptions. But one thing would be, if you can decorate your classes with the JsonConverter, then that would work anywhere, as long as System.Text.Json is the engine being used.

I'll try this, thanks!

**Comment by Mortana89** [comment]
Just finished updating our queries using the QueryDefinition classes (500+ queries, what a work :D)
So I'm now able to test the converters. I tried following the pattern of creating a custom serializer, because I don't like the idea of cluttering my domain layer with JsonConverter attributes. 
Some possible improvements for v4:
- Make the CosmosSerializer accept JsonConverters/JsonOptions (why make this even internal sealed?)
- Make the existing converters public (I cannot create a custom serializer without copying over all your custom converters and registering them. In essence I have now much duplicated SDK code)

What are your thoughts @ealsur ?

**Comment by ealsur** [comment]
I'm sorry @Mortana89 but I don't understand the issue.

You don't need to pass Converters into the Serializer options unless the classes you are dealing with are not yours or you don't have access to the code.

If I have `MyClass` and I want to provide a converter for it, I just decorate the class:

```csharp
[JsonConverter(typeof(MyClassConverter))]
public class MyClass
{

}
```

Why do you need the existing converters public? The existing converters just deal with the REST API Contract types, like https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/Resource/Settings/AccountProperties.cs#L17

The serialization of these REST API types is controlled by the SDK and thus they have their own Converters. Why do you need access to them?

**Comment by Mortana89** [comment]
> I'm sorry @Mortana89 but I don't understand the issue.
> 
> You don't need to pass Converters into the Serializer options unless the classes you are dealing with are not yours or you don't have access to the code.
> 
> If I have `MyClass` and I want to provide a converter for it, I just decorate the class:
> 
> ```cs
> [JsonConverter(typeof(MyClassConverter))]
> public class MyClass
> {
> 
> }
> ```
> 
> Why do you need the existing converters public? The existing converters just deal with the REST API Contract types, like https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/Resource/Settings/AccountProperties.cs#L17
> 
> The serialization of these REST API types is controlled by the SDK and thus they have their own Converters. Why do you need access to them?

Sorry if I'm not explaining correctly, the System.Text.Json provides a few options of configuring converters. One of those options is indeed using an attribute above the property needing conversion.
Another option is registering the converter in the jsonoptions. This is possible because a converter has a method CanConvert, built-into the System.Text.Json framework.

As we have a few thousand properties that all use the same converter (Enumeration classes converted to string upon serialization), it's very error-prone to annotate each property that is of the type enumeration (we have roughly 150 enumeration classes). We used this approach in the Newtonsoft ages, and it's supported in the System.Text.Json age. It's however not supported in the Cosmos SDK, as such we're trying to find a work-around.
One of those workaround is, as you suggested, a custom cosmos serializer. That is cool, but if we make a custom cosmos serializer, we still want to be able to use the converters you set up in your internal serializer. Since these converters are internal sealed, that makes things even more complicated. A work-around what we now have done, is using reflection to actually under the bonnet get the converters you initialize in the Cosmos serializer, and add these at runtime to our custom cosmos serializer (done once in startup).

Would your cosmos serializer just take over the converters from the JsonOptions instead of assigning an empty list and then adding your two converters, I'd think this would solve it, no?

**Comment by ealsur** [comment]
When you create a custom converter, that only applies to your type operations, it does not apply to the Cosmos DB SDK specific REST contracts.

For example, if you do a CreateContainer, we use our own serializer, not the one you provide, because the types involved are part of the service definition.
If you do user data operation, like CreateItem, then your serializer applies.

Exposing the JsonOptions is good feedback. Currently V4 is aligning with the Azure Core SDK guidelines, and they are investigating based on our case, which would be a good serializer API, so things might change between now and GA (we might end up exposing JsonOptions if it becomes the recommendation from Azure Core).

**Comment by Mortana89** [comment]
I'm not completely sure I'm seeing the behavior that type operations are using our own converters. The behavior I'm seeing is that all conversions from e.g. GetItemQueryIterator are being done through the CosmosSerializer class, which is using it's own JsonOptions, not knowing anything about setup converters in the JsonOptions configured during ASP.net app startup :/ Could you point me to the mentioned behavior in code perhaps?
Sorry for making this a quite lengthy thread! If you'd prefer to take this offline, let me know!

**Comment by ealsur** [comment]
GetItemQueryIterator, being a user data operation, will use the CosmosSerializer implementation you pass.

Onhttps://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/Resource/Container/ContainerCore.Items.cs#L374 we create a stream iterator.
And pass that iterator to the PageIteratorCore with `this.ClientContext.ResponseFactory.CreateQueryFeedResponse` as the factory to generate the item instances. Which is here https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/Resource/CosmosResponseFactory.cs#L41
and uses the serializer defined by the user https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/Resource/CosmosResponseFactory.cs#L32 and https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/CosmosClient.cs#L648

There is another serializer in that file which is the one we use for REST API contracts, but its not used in that operation.

**Comment by Mortana89** [comment]
I understand.
When exposing the JsonOptions, we can add our own custom converters. For now, reflection came to the rescue and we're able to use our own constructors. 
For anybody else still facing issues with System.Text.Json due to missing functionality, I can suggest Dahomey as a nice library.

**Comment by xperiandri** [comment]
I tried this
``` C#
Type CosmosTextJsonSerializerType = typeof(CosmosClientOptions)
                .Assembly.GetTypes()
                .First(t => t.FullName == "Azure.Cosmos.CosmosTextJsonSerializer");
            var serializerConstructor =
                CosmosTextJsonSerializerType
                .GetConstructor(BindingFlags.NonPublic | BindingFlags.Instance, null,
                    new[] { typeof(JsonSerializerOptions) }, null);
            var jsonOptions = Json.getJsonSerializerOptions();
            var converters = jsonOptions.Converters;
            var serializer = serializerConstructor.Invoke(new object[] { jsonOptions }) as CosmosSerializer;
            var options = new CosmosClientOptions() { Serializer = serializer };
            options.Diagnostics.IsLoggingEnabled = true;
            var client = new CosmosClient("https://localhost:8081", "", options);
```
But get `Value cannot be null`
Because `feedResponse.Value` is null.
```
        private IReadOnlyList<T> CreateQueryFeedResponseWithSerializer<T>(
            Response cosmosResponseMessage,
            CosmosSerializer serializer)
        {
            FeedResponse<T> feedResponse = this.CreateQueryFeedResponseHelper<T>(
                cosmosResponseMessage,
                serializer);

            return feedResponse.Value.ToList().AsReadOnly();
        }
```

How could this happen???

``` F#
let getJsonSerializerOptions() =
    let options = JsonSerializerOptions(PropertyNamingPolicy = JsonNamingPolicy.CamelCase)
    let converters = options.Converters
    converters.Add (System.Text.Json.Serialization.JsonStringEnumConverter ())
    converters.Add (System.Text.Json.Serialization.JsonFSharpConverter ())
    options
```

**Comment by xperiandri** [comment]
At the beginning, I tried
```
type CosmosJsonSerializer() =
    inherit CosmosSerializer()
    let options = getJsonSerializerOptions()

    override __.FromStream<'T> (stream: Stream) =
        use memoryStream = new MemoryStream()
        stream.CopyTo(memoryStream)
        stream.Close()
        let item: 'T = JsonSerializer.Deserialize<'T>(new ReadOnlySpan<byte>(memoryStream.ToArray()), options)
        item

    override __.ToStream<'T>(input: 'T) =
        let bytes = JsonSerializer.SerializeToUtf8Bytes(input, options)
        new MemoryStream(bytes) :> Stream
```
But result is the same...

**Comment by xperiandri** [comment]
@Mortana89 what is your solution?

**Comment by xperiandri** [comment]
I localized exception to `CosmosJsonSerializerWrapper.cs`
``` C#
        public override T FromStream<T>(Stream stream)
        {
            T item = this.InternalJsonSerializer.FromStream<T>(stream);
            if (stream.CanRead)
            {
                throw new InvalidOperationException("Json Serializer left an open stream.");
            }

            return item;
        }
```
@ealsur, how is this possible?

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/79809525-5c3cee80-8379-11ea-879d-c89a0e6e4060.png)

**Comment by xperiandri** [comment]
OK, so the issue is that I try to deserialize F# record using FSharp.TextJson but Azure.Cosmos tries to deserialize whole collection of my F# records. But Azure.Cosmos's serializer does not know how to deserialize a collection of F# records.

**Comment by j82w** [comment]
@xperieandri can you create a new issue for the specific issue you are seeing.

**Comment by bartelink** [comment]
FWIW [this custom `CosmosJsonSerializer` integration (in F#)](https://github.com/jet/equinox/blob/fd4abf16b2652f73d920300193978970c4caab84/src/Equinox.CosmosStore/CosmosStoreSerialization.fs#L13-L27)  is working for me (don't forget to [configure it to be used](https://github.com/jet/equinox/blob/fd4abf16b2652f73d920300193978970c4caab84/src/Equinox.CosmosStore/CosmosStore.fs#L1208))

[The Cosmos SDK sample](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson) illustrates some deeper scenarios for `Azure.Core` integration.
