### ISSUE TITLE
Falls the cosmos client into the "Improper Instantiation antipattern"?

### ISSUE THREAD

**Issue by olivermue** [Azure/azure-cosmos-dotnet-v3#1217]
Just stumbled across this helpful article [Performance antipatterns for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/).

There is a section called [Improper Instantiation](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/) which contains (and least for me) well known problems with `HttpClient` (by the way, here the documentation is wrong, cause it should be solved by using the `IHttpClientFactory` and not a static instance of `HttpClient`) and some other common classes.

But to my surprise there is also the `Microsoft.Azure.Documents.Client.DocumentClient` listed that is also known as V2. Due to the fact, that I already upgraded to the CosmosClient (aka V3), I would like to know, if this client has the same problems and should be managed through some kind of factory that holds a pool of clients for re-usage or if these problems are solved internally and within a asp.net core rest api controller we can safely create a new CosmosClient in an transient lifetime for each request?

Unfortunately I couldn't find any documentation about these things nor any extension method for `IServiceCollection` that could maybe answer this question. So, is it okay to create and dispose a `CosmosClient` for each request or should we manage some client pool or even a single lifetime instance, that probably gets multiple calls in parallel?

**Comment by j82w** [comment]
No, you should use a singleton pattern. The SDK won't scale with creating a new instance for each request. The SDK has caches that it warms up on the first requests which costs more overhead. It's listed in the [performance documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips?source=docs).
