### ISSUE TITLE
ReadItemAsync does not throw exception as in documentation

### ISSUE THREAD

**Issue by mpalumbo7** [Azure/azure-cosmos-dotnet-v3#122]
**Describe the bug**
The MS docs state that when `ReadItemAsync` is ran on an entity that does not exist, a 404 exception should be returned. [Link to MS docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmositems.readitemasync?view=azure-dotnet-preview).

In my testing, no exception is thrown but the `CosmosItemResponse<T>` is returned with an `Resource = null` and a `StatusCode = 404`.

**To Reproduce**
Have Cosmos SQL API Collection named `tweets` with partitionKey `/subjectId`.

```csharp
using Microsoft.Azure.Cosmos;
using cosmos.test.Models;
using Xunit;

namespace cosmos.test
{
    public class CosmosTest
    {
        private const string _endpoint = "{endpoint}";
        private const string _authkey = "{authkey}";
        private const string _database = "{database}";

       [Fact]
        public async void ReadFail()
        {
            var client = new CosmosClient(_endpoint, _authkey);

            await Assert.ThrowsAsync<CosmosException>(async () =>
            {
                await client.Databases[_database].Containers["tweets"].Items.ReadItemAsync<Tweet>("foo", "not-a-real-id");
            });
        }
    }
}
```

**Expected behavior**
An exception of type `CosmosException` with `StatusCode = 404` should be thrown.

**Actual behavior**
No exception is thrown.

**Environment summary**
SDK Version: 3.0.0.9-preview
OS Version (e.g. Windows, Linux, MacOSX) MacOSX

**Additional context**
```bash
$ dotnet test
Build started, please wait...
Build completed.

Test run for /Users/mpalumbo7/Code/tweet-api/test/cosmost.test/bin/Debug/netcoreapp2.2/tweet.api.test.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:06.0785620]     cosmos.test.CosmosTest.ReadFail [FAIL]
Failed   cosmos.test.CosmosTest.ReadFail
Error Message:
 Assert.Throws() Failure
Expected: typeof(Microsoft.Azure.Cosmos.CosmosException)
Actual:   (No exception was thrown)
Stack Trace:
   at cosmos.test.CosmosTest.ReadFail() in /Users/mpalumbo7/Code/tweet-api/test/cosmos.test/CosmosTest.cs:line 20

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 6.7763 Seconds

```

**Comment by mpalumbo7** [comment]
I just tested and the same behavior with `ReplaceItemAsync` and `GetItemAsync`.

**Comment by mpalumbo7** [comment]
Here is a screenshot showing the `CosmosItemResponse` with `StatusCode = 404` and yet no exception. Is the documentation just wrong?

![image](https://user-images.githubusercontent.com/20686457/56319593-1d55d680-6130-11e9-856e-262c1f473517.png)

**Comment by j82w** [comment]
In v3 it was designed to not throw an exception for 404. Not finding an item is a valid scenario for most workloads. Throwing an exception is rather expensive, and can hurt performance. The documentation needs to be updated.

**Comment by j82w** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/126

**Comment by mpalumbo7** [comment]
I figured as much. I’ll close the issue since a PR is now opened to fix the documentation.

**Comment by HiroyukiSakoh** [comment]
#513

**Comment by claitonlovato** [comment]
Hi @j82w , I am facing the opposite problem here, I am using 3.1.1 (downgraded to 3.0.0 with same results), and ReadItemAsync actually throws an exception instead of returning a ItemResponse as described on the sample documentation. Any ideas?
Thank you so much.
Claiton

**Comment by j82w** [comment]
Hi @claitonlovato , 

This issue was created while the SDK was still in preview. Because of this issue and several other users reporting the same issue it was decided to make 404 throw. It also makes it easier to migrate from v2 SDK.

**Comment by claitonlovato** [comment]
Thank you so much for the quick reply @j82w !
Ok, I understand.
Not sure I agree with the change back, as you mentioned throwing an exception is quite expensive for a completely valid scenario.
The only thing is that now the documentation is wrong again, like this page that shows a tutorial using the check against the response StatusCode: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-dotnet-application
Kind regards,
Claiton

**Comment by j82w** [comment]
I created an [issue ](https://github.com/MicrosoftDocs/azure-docs/issues/37625) for the document to be updated. If performance is a real concern then it is recommended to use the stream APIs. They don't throw any exceptions, and allows for other optimizations like only deserializing when necessary.

**Comment by nahk-ivanov** [comment]
@j82w can we have this as an option in `RequestOptions` or a separate flag? Performance is a concern and to use stream APIs we need to pass serializer everywhere. It would probably improve ever so slightly if `CosmosClient.ClientOptions.Serializer` would be set to a default one, rather than kept `null`, if nothing specified, but having it in `RequestOption` will allow us to reuse it for all of the read APIs, not just the document.

**Comment by christianrondeau** [comment]
Agreed with @nahk-ivanov - or provide an overload like `ReadItemOptionalAsync<T>`. For what it's worth, I do prefer an approach like `HttpClient` which leaves to the developer the choice of calling a validation method such as `ItemResponse<T>.EnsureSuccess()`.
