### ISSUE TITLE
How do I fork and build this project without the strong name private key?

### ISSUE THREAD

**Issue by jahmai** [Azure/azure-cosmos-dotnet-v3#1222]
**Is your feature request related to a problem? Please describe.**

I have a use-case of enhancing the SDK with some custom Linq query serialization to assist in adapting it to our existing data model types.
I have successfully forked and enhanced the SDK for this purpose and I can successfully run the resulting assembly in a netcore 3.1 app locally.
When attempting to link the assembly with a .net 4.7.2 application, it fails the strong name signing verification while loading the assembly.

```
System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Azure.Cosmos.Client, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```

How can I make this work?
Why is this only failing in my net472 projects?

**Describe the solution you'd like**
To be able to fork, modify and build the SDK and reference it in netcore and net472 projects.

**Describe alternatives you've considered**
Tried removing signing all together from the Microsoft.Azure.Cosmos project, but it fails to build due this error:

```
<any>.cs(15, 44): [CS0281] Friend access was granted by 'Microsoft.Azure.Cosmos.Direct, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', but the public key of the output assembly ('') does not match that specified by the InternalsVisibleTo attribute in the granting assembly.
```

**Additional context**
N/A

**Comment by j82w** [comment]
Do you require a signing validation? You shouldn't need to grant friends access to anything.  Friends is an internal Cosmos project that is not used by the public SDK.

**Comment by jahmai** [comment]
@j82w i dont, but when I disable signing it gives the friends error. Probably because friends is declared using a strong name internal to the other cosmos lib?

**Comment by j82w** [comment]
Does removing Friends from AssemblyInfo.cs file fix the issue?

**Comment by jahmai** [comment]
@j82w No, the problem seems to be that Microsoft.Azure.Cosmos.Direct.dll (which is closed source) declares friends to the strong-named assembly of Microsoft.Azure.Cosmos.Client.dll, as is alluded to in the error message:

> <any>.cs(15, 44): [CS0281] Friend access was granted **by** 'Microsoft.Azure.Cosmos.Direct, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35', but the public key of the output assembly ('') does not match that specified by the InternalsVisibleTo attribute in the granting assembly.

**Comment by jahmai** [comment]
We have dropped .net framework and are only using .net core, which doesn't have this issue. Closing.
