### ISSUE TITLE
PartitionKey is missing methods for comparison

### ISSUE THREAD

**Issue by KristianJakubik** [Azure/azure-cosmos-dotnet-v3#1233]
Hi,
I was a little bit surprised when I found out that the struct `PartitionKey` doesn't implement methods (Equals, GetHashCode, etc.) necessarily for proper comparison and neither operators(`==`, `!=`).

In my case I just wanted to compare two `PartitionKey`s with `==` operator and was not able to do so, because of missing `==` operator overload. 

IMHO: If I'm not missing out something, the implementation should be intuitive. I can provide PR.

**Comment by j82w** [comment]
This seems like a great feature. Looking at the code really quick it should be intuitive to implement. We really appreciate contributions, and would be happy to review any PR submitted.
