### ISSUE TITLE
Microsoft.Azure.Cosmos 3.6.0/3.7.0-preview breaks Xamarin.iOS build for debug/release on device

### ISSUE THREAD

**Issue by 1iveowl** [Azure/azure-cosmos-dotnet-v3#1236]
**Describe the bug**
Microsoft.Azure.Cosmos 3.6 breaks Xamarin.iOS build for debug/release on device with the error:

    .../MTOUCH: Error MT3001: Could not AOT the assembly '/.../obj/iPhone/Debug/device-builds/ipad7.3-13.3.1/mtouch-cache/3-Build/Microsoft.Azure.Cosmos.Client.dll' (MT3001) ([project name])

Compilation for the iPhone Simulator does not have this issue.

**To Reproduce**
Build to iOS device with Visual Studio 2019 on Windows 10 with project using Microsoft.Azure.Cosmos 3.6.0 or 3.7.0-preview.

**Expected behavior**
Microsoft.Azure.Cosmos v3.5.1 builds on devices without any issue as well as run on device.

**Actual behavior**
Build fails with:

    .../MTOUCH: Error MT3001: Could not AOT the assembly '/.../obj/iPhone/Debug/device-builds/ipad7.3-13.3.1/mtouch-cache/3-Build/Microsoft.Azure.Cosmos.Client.dll' (MT3001) ([project name])

**Environment summary**
SDK Version: 3.6.0 and 3.7.0-preview.
OS Version: v13.3.1 - iOS device (not simulator)
Visual Studio for Mac: 8.4.7b17.
Mono Framework MDK version: 6.6.0.166
.NET Core: 3.1.102.
Xamarin iOS: 13.10.0.21.
Mac OS X: 10.15.3.

**Comment by j82w** [comment]
The only major change I see is adding [SourceLink](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1107) support, but I'm not sure how it would cause this.

Can you please provide the full error message? It should have a reason after the Could not AOT the assembly message.

**Comment by 1iveowl** [comment]
I've updated the original post with the full error message as it appears in Visual Studio.

**Comment by 1iveowl** [comment]
The issue is repro'ed here: https://github.com/1iveowl/CosmosResourceTokenBroker/tree/issue/src/sample/client/XamarinForms.Client/XamarinForms.Client.iOS

I've made a branch just for this issue.

**Comment by 1iveowl** [comment]
Here's an even simpler project for repro of the issue. 

Also, more investigating have uncovered that the project will compile if the *Mono Interpreter* is disabled.

[SourceLinkTest.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/4280928/SourceLinkTest.zip)

**Comment by ealsur** [comment]
Do you get the error with 3.6.0? I see similar issues on the Xamarin repo (for example https://github.com/xamarin/xamarin-macios/issues/4012 or https://stackoverflow.com/a/41453470/5641598) where they ask for the complete build log. I'm not sure we have enough knowledge about Xamarin.IOS to debug it, but that might be a starting point.

Don't you get more lines of details besides that single error line?

**Comment by 1iveowl** [comment]
@ealsur Yes, I get the error with v3.6.0 but not with v3.5.1. 

My current guess is that the the *Mono Interpreter* for Xamarin iOS doesn't get along with `Microsoft.SourceLink.Get` but I can't verify this. 

I don't get any other error than that, or I don't know where to look for it.

**Comment by ealsur** [comment]
Are you by any chance using the latest Xamarin AOT compiler and latest Xamarin.iOS ? I wonder if this is something to which support was added later?

**Comment by 1iveowl** [comment]
Yes, I'm using the latest. Please see specific versions in the original post above.

**Comment by ealsur** [comment]
I checked and it seems Xamarin.Forms added support for SourceLink too https://github.com/xamarin/Xamarin.Forms/pull/6886

They are using the same SourceLink package.

**Comment by 1iveowl** [comment]
Thank you. Interesting, as there doesn't seem to be much else that changed between v3.5.1. and v3.60.

**Comment by 1iveowl** [comment]
Found some more error info:

> Mono Ahead of Time compiler - compiling assembly /Users/.../ipad7.3-13.3.1/mtouch-cache/3-Build/Microsoft.Azure.Cosmos.Client.dll
>     AOTID 338FB5C6-A554-486C-9AD7-EAA0447D815A
>     * Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-08/ios/release/mono/mini/mini-generic-sharing.c:1228, condition `is_ok (error)' not met, function:get_wrapper_shared_vtype, VAR 0 (T1) cannot be expanded with type 0x11
>     
>     MTOUCH : error MT3001: Could not AOT the assembly '/Users/.../mtouch-cache/3-Build/Microsoft.Azure.Cosmos.Client.dll'
> Done building target "_CompileToNative" in project "[Project name].csproj" -- FAILED.

**Comment by ealsur** [comment]
Thanks for the detailed issue (the other one you created). I'm going to try and see if I find more information based on the new stack you shared.

**Comment by ealsur** [comment]
What about https://github.com/mono/mono/issues/18676 ?
It seems users are hitting it with different packages, I wonder what all of these have in common? Maybe its SourceLink? I'll keep digging.

**Comment by 1iveowl** [comment]
> Thanks for the detailed issue (the other one you created). I'm going to try and see if I find more information based on the new stack you shared.

Thank you. I've added some more details for Android too in the other post. I have to say that I've been struggeling quite a bit here. The latest challenge have been that `Microsoft.Azure.Cosmos.Serialization.HybridRow` does not seem to be anywhere on Nuget.org. It seems that the .dll is directly embedded in the `Microsoft.Azure.Cosmos` package? If so, do you know why? It seems a bit odd to me.

Also, why are a number of the [dependencies](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1a999ffb2d81a969f99b0c3d93e82f7a7127b37c/Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj#L72) maked as `PrivateAssets` when they are needed in other contexts, as is the case for controlling the linker?

In all, `Microsoft.Azure.Cosmos` doesn't seem particular ready for use in Xamarin Forms scenarios at the moment. Or maybe I'm approaching this from the wrong angle?

**Comment by ealsur** [comment]
The HybridRow and Direct packages marked as Private were there on 3.5.1 so that is not part of the issue.
In both cases, the DLLs are packaged as part of the SDK package: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj#L94

As for the `Microsoft.SourceLink.GitHub` being a PrivateAsset, it is the same approach Xamarin.Forms took https://github.com/xamarin/Xamarin.Forms/blob/master/Directory.Build.props#L18

It looks like the issue in Mono was fixed (https://github.com/dotnet/runtime/pull/31670), but merged less than a month ago, so I'm not sure if it's released or not.

**Comment by 1iveowl** [comment]
> The HybridRow and Direct packages marked as Private were there on 3.5.1 so that is not part of the issue.

Agree and apologies for the confusion. I've been working on multiple issues the past days and I got them mixed up.

The *HybridRow and Direct packages* issue is not related to the *Error MT3001: Could not AOT the assembly...* issue. That issue I believe have now been pined down to be related to Mono and **The Interpreter**. Thank you for helping out with that.

The struggles I've had with the private assets approach to the *HybridRow and Direct packages* has to do with Linking when Linking is set to `Link All` as outlined in #1243. These challenges have been further complicated by HybridRow not being available as a Nuget by itself. 

Maybe, I'm missing something, but when I read through #1243, the work-arounds described here are rather convoluted, I think. It took me many hours and multiple evenings to figure it all out.

> In both cases, the DLLs are packaged as part of the SDK package: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj#L94

Thank you. I would love to understand better the thinking behind this approach? Is there a reason why these packages are not made available as independent Nuget packages?

> As for the `Microsoft.SourceLink.GitHub` being a PrivateAsset, it is the same approach Xamarin.Forms took https://github.com/xamarin/Xamarin.Forms/blob/master/Directory.Build.props#L18

I don't believe that `Microsoft.SourceLink.GitHub` is as big an issue as the *HybridRow and Direct packages* as `Microsoft.SourceLink.GitHub` does indeed have an internal only function, as far as I understand it.

Also, in the testing I've done with using the Linker with `Link All` in a Xamarin iOS project and an Android project `Microsoft.SourceLink.GitHub` can just be ignored without causing issues. The same cannot be said about *HybridRow and Direct*, those need to be dealt with as outlined in #1243.

> 
> It looks like the issue in Mono was fixed ([dotnet/runtime#31670](https://github.com/dotnet/runtime/pull/31670)), but merged less than a month ago, so I'm not sure if it's released or not.
> 
> EDIT: Found it was linked to 6.10 milestone release https://github.com/mono/mono/milestone/18

Cool. Currently Xamarin iOS relies on Mono version 6.6.0.166. Hopefully Mono 6.10.x will enter the stage soon.
