### ISSUE TITLE
Batch - update property on existing items

### ISSUE THREAD

**Issue by danhamlin** [Azure/azure-cosmos-dotnet-v3#1248]
In the bulk executor library there is a concept of an update operation that allows for updating properties on existing documents.
https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-dot-net#bulk-update-data-in-your-azure-cosmos-account

Does this same concept exist in the Batch api?

Thank you.

**Comment by danhamlin** [comment]
Thank you for the clarifications Matias.  Do you think using the bulk operations to read and then update a single property on each item in a collection (~1.6MM records) would be the best way currently available?

**Comment by ealsur** [comment]
You could certainly do Bulk Read (list of Tasks for Read operations, await Task.WhenAll), apply changes, and do Bulk Replace (list of Tasks for Replace operations, await Task.WhenAll).
