### ISSUE TITLE
List all documents within a container in v3

### ISSUE THREAD

**Issue by microsoft-rorezend** [Azure/azure-cosmos-dotnet-v3#1251]
This is something that is possible with v2 using ReadDocumentFeedAsync and using the REST API https://docs.microsoft.com/en-us/rest/api/cosmos-db/list-documents

Is there any equivalent public API in v3? What's the best way (using least amount of RUs) to list all documents (cross partition) within a collection? I'm assuming that a cross partition query "select all" would be more expensive than the list-documents API, is that true?

**Comment by j82w** [comment]
Read feed is the same as a select * query. It was decided to merge the apis. The [samples ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6067c1bec56598abaef3851666d243a61521709c/Microsoft.Azure.Cosmos.Samples/Usage/Queries/Program.cs#L99)show you simply need to pass null in for the query text to get the read feed.

I believe the query is slightly more expensive than a read feed, but I haven't validated.
