### ISSUE TITLE
LINQ with Contains and Enum does not consider converterType

### ISSUE THREAD

**Issue by SeriousJul** [Azure/azure-cosmos-dotnet-v3#1253]
**Describe the bug**
azure-cosmos-dotnet-v3 supports LINQ query generation. When working with enum serialized as string in simple where clause, the expression is properly translated in SQL using the string value of the enum.
But when using Contains operator to generate "IN" clause. This does not work with array of enum, as the SQL translated from it always contains ordinal values of enum, regardless of the model definition.

**To Reproduce**

```c#
public class Foo
{
        [JsonProperty("status")]
        [JsonConverter(typeof(StringEnumConverter))]
        public FooStatus Status { get; set; }
}

public enum FooStatus
{
        StatusA,
        StatusB
}
```
```c#
var query = container.GetItemLinqQueryable<Foo>();
query = query.Where(foo => new[]{FooStatus.StatusA}.Contains(foo.Status));
Console.WriteLine(query.ToQueryDefinition().QueryText);
```

**Expected behavior**

```sql
SELECT VALUE root FROM root WHERE (root["status"] IN ("StatusA"))
```

**Actual behavior**

```sql
SELECT VALUE root FROM root WHERE (root["status"] IN (1))
```

**Environment summary**
SDK Version: 3.6.0
OS Version (e.g. Windows, Linux, MacOSX): 
```
Operating System: Ubuntu 19.10
Kernel: Linux 5.3.0-40-generic
Architecture: x86-64
```

**Additional context**
Simple where clause works just as expected

```c#
var query = container.GetItemLinqQueryable<Foo>();
query = query.Where(foo => foo.Status == FooStatus.StatusA);
Console.WriteLine(query.ToQueryDefinition().QueryText);
```
```sql
SELECT VALUE root FROM root WHERE (root["status"] = "StatusA")
```

**Comment by j82w** [comment]
@timsander1 can you take a look?

**Comment by timsander1** [comment]
Thanks for flagging this! I can confirm that this is a bug. For now, could you try this workaround?


original code: query = query.Where(foo => new[]{​​​​​​FooStatus.StatusA}​​​​​​.Contains(foo.Status));
workaround: query = query.Where(foo => new[]{​​​​​​FooStatus.StatusA.ToString()}​​​​​​.Contains(foo.Status));

**Comment by NeilWBruce** [comment]
Yep that works.  Was trying something similar myself yesterday but was just testing out the performance.  All looks good.  Thanks!

**Comment by bhugot** [comment]
We met similar problem with query like  query = query.Where(foo => foo.ADictionary[FooStatus.StatusA] == "a value");
Where foo.ADictionary is Dictionary<FooStatus, string>

**Comment by bhugot** [comment]
I found a workaround but I don't like it it's by using JsonConvert.DefaultSettings, please allow to use CosmosJsonDotNetSerializer  so we can share the JsonSerializerSettings

**Comment by onionhammer** [comment]
This is still an issue. Any update?

**Comment by ekjuanrejon** [comment]
any update on this bug?

**Comment by onionhammer** [comment]
@sboshra @j82w I'd be happy to look into this issue and contribute a PR if this is within reach for a new contributor?

**Comment by onionhammer** [comment]
Looking over the code it looks like this needs to be enhanced to support the serializer settings

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/11b774459a894657dcca8cbf89b945b42e008a86/Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs#L529

**Comment by alice-ep** [comment]
Hi, are there any updates about this?

**Comment by Maya-Painter** [comment]
Hi all, we've merged what we hope will be a solution to this issue by allowing the custom serializer to be used for LINQ translations. This also unblocks having System.Text.Json attributes applied in LINQ queries.

We plan to release this as part of the next preview package, but I also wanted to take this time to confirm these changes meet your needs before finalizing them as part of our public API.  If you try the changes out, please follow up in the thread if this update addresses your concerns. If it doesn't, please let us know why.

To use your own custom serializer for LINQ translations you must implement `CosmosLinqSerializer` and set it as a custom serializer on the `CosmosClient`. There is a sample of this for serialization with System.Text.Json in CosmosLinqSerializer.cs.

**Comment by lukasz-pyrzyk** [comment]
@Maya-Painter thank you for merging the fix. We have tested our code with the nighly build and it fixes our problem with quering againts array of enums marked with `JSonConverter(XYZ)`. 

Do you know when we can expect next preview package available on the nuget feed?

**Comment by Maya-Painter** [comment]
@lukasz-pyrzyk We do not have a release scheduled yet but are hoping to get it out by the end of the month.

**Comment by cultpodcasts** [comment]
Leaving a link to source mentioned in comment above
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs
