### ISSUE TITLE
Insert million of items bulkMode

### ISSUE THREAD

**Issue by AntonioJDios** [Azure/azure-cosmos-dotnet-v3#1254]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I'm just trying to insert one million of data. It would be ideally to different logical partitions, and they would be balance. I would like to know which would be the expected throughput I would need to allocated to get this done in enough time. Should I need to use the bulk mode? would be better avoid bulk mode?

Can you help me with this? 
thanks.

**Comment by ealsur** [comment]
Bulk mode is particularly for these scenarios. The amount of RU/s really depends on the size of your documents.

Check the table on [this PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1074) to have an idea about RUs and time based on the amount of documents (assuming even distribution).

**Comment by AntonioJDios** [comment]
Interesting, so. Regarding that table. If I wan to insert 1millon of data. I need to provision 1Millon throughput and it would take 1 minutes

**Comment by ealsur** [comment]
You can provision less (the table shows 100K for example) but you will face throttles, which with retries, will make the overall time longer.
You could split the load and do 500K at a time or less, if your provisioned RU/s are much less.

**Comment by AntonioJDios** [comment]
Thanks. I will have a look deeply to the code and I will share with my
mates!

**Comment by ealsur** [comment]
Closing as the question is addressed.
