### ISSUE TITLE
FeedToken - Interoperability

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#1262]
Current design of FeedToken (https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1230, https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1210) enables sharing a FeedToken across incompatible operations (for example, take a FeedToken from a Change Feed operation and use it in a Query).

Possible solutions:
* Have different public types: QueryFeedToken, ChangeFeedToken
* Have different implementations but keep the FeedToken as public and check the implementation on runtime
* Have 2 different GetFeedTokens APIs, one for each type:
    * GetChangeFeedTokens()
    * GetQueryFeedToken(QueryDefinition)

**Comment by j82w** [comment]
There should be no ReadFeedToken. There is no ReadFeed APIs. It should just be query.

**Comment by ealsur** [comment]
Fair point. I think with just Query and ChangeFeed we would be good.
