### ISSUE TITLE
UpsertItemStreamAsync and CreateItemStreamAsync throw System.Configuration.ConfigurationException on Android	

### ISSUE THREAD

**Issue by 1iveowl** [Azure/azure-cosmos-dotnet-v3#1267]
**Describe the bug**

`UpsertItemStreamAsync` and `CreateItemStreamAsync` will throw `System.Configuration.ConfigurationException` with Xamarin on Android (emulator and device).

`ReadItemStreamAsync` works fine is same project.

**To Reproduce**

Try to use `UpsertItemStreamAsync` or `CreateItemStreamAsync` on an Android device or an Android emulator.  

The innermost exception says:

> Operation is not supported on this platform

The source of the exception is: `System.Configuration.ConfigurationManager`

[From the API documentation It seems that `System.Configuration.ConfigurationManager`](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager?view=netframework-4.8#applies-to) is supported on Xamarin.Mac but not on the other Xamarin platforms. 

Others are having issues with`System.Configuration.ConfigurationManager` on Android too:
-  [Configuration system throws `PlatformNotSupportedException` on Xamarin Android.](https://github.com/fluentassertions/fluentassertions/issues/1151)
- [[Bug] How to use System.Configuration.ConfigurationManager nuget package in Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/issues/5935).

**Work-around**

Simply ignoring/swallowing the `ConfigurationException` seem to work, as documents are in fact being Upserted or Created in Cosmos DB just fine, despite the exception thrown. 

Of course doing so feels rather hacky and is uncomfortable making one wonder about hidden side-effects.

**Expected behavior**
No such exception is thrown on iOS in [the same project](https://github.com/1iveowl/CosmosResourceTokenBroker), although it does not seem to be supported. 

**Environment summary**
SDK Version: 3.6.0 and 3.7.0-preview.
Android Version: 9.0 (Api level 28-Pie)
Visual Studio 2019: 16.4.5
.NET Core: 3.1.102.

**Comment by dos-ise** [comment]
I have a netstandard library that heavily uses ConfigurationManager and throws this exception.
Since I am not developer of this library is it possible to do anything else. The exception throws immediately when using this lib.
