### ISSUE TITLE
Have option in ItemRequestOptions to return not null Content/Resource for the methods DeleteItemStreamAsync and DeleteItemAsync.

### ISSUE THREAD

**Issue by rorezende** [Azure/azure-cosmos-dotnet-v3#1273]
I see that both DeleteItemAsync and DeleteItemStreamAsync  will always return NoContent code with corresponding Content or Resource members set to null.

I looked to the source code for both DeleteItemStreamAsync and DeleteItemAsync and apparently there is no option or code path for the Stream or Resource to be set with valid content.

My question is (Feature request): 

Is it possible to allow users to provide some option as part of ItemRequestOptions so Content/Resource can be set with the item state at the time of deletion (also a status code different than NoContent in that case)?

I see that https://docs.microsoft.com/en-us/rest/api/cosmos-db/delete-a-document returns NoContent, what is possibly the reason the sdk also returns NoContent.  That may be considered a blocker to offer this feature. 
But still, without it, it seems it is not possible today to know the state of the deleted item consistently, at the best, the state before deletion with a previous Get.

**Comment by microsoft-rorezend** [comment]
Just realized with the new TransactionalBatch API it is possible to achieve it consistently with 
```
CreateTransactionalBatch(new PartitionKey(partitionKey))
.ReadItem(...)
.DeleteItem(...)
```

it may have some perf hit, but apparently it is works correctly. May I assume the isolation model for reads in transactions are either {read-commited, repeated-reads or serializable}?

**Comment by j82w** [comment]
If you simply need the deleted item why not read the item then delete it?

**Comment by microsoft-rorezend** [comment]
Because by the time the delete is performed, the read state might be already outdated.

**Comment by j82w** [comment]
Closing this since there has been no updates.

**Comment by Mario-GG** [comment]
+1 would be useful to have this option

**Comment by kirankumarkolli** [comment]
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.enablecontentresponseonwrite?view=azure-dotnet

`EnableContentResponseOnWrite` control the behavior by de-fault its turned-off, its a client level option.

**Comment by Mario-GG** [comment]
Setting it to true doesn't do anything for DeleteItemStream:
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/136351546/61e93275-32f5-4d0e-a4d4-db83ef684657)

**Comment by kirankumarkolli** [comment]
That's true, my bad.

Documentation do cover that it's not applicable to writes.
> the Cosmos DB response for write item operation like Create, Upsert, Patch and Replace

This will be a service feature request, not SDK.

**Comment by kirankumarkolli** [comment]
+1 to addressing the documentation gap in `DeleteItemStreamAsync`
Will be tracking and work-item to fix it.

**Comment by kirankumarkolli** [comment]
#4291 covering the documentation fix
