### ISSUE TITLE
Fix naming of dictionary keys

### ISSUE THREAD

**Issue by wilcobmsft** [Azure/azure-cosmos-dotnet-v3#1278]
**Is your feature request related to a problem? Please describe.**
Dictionary keys are serialized as property names which may be undesirable. Newtonsoft has a property ProcessDictionaryKeys on their NamingStrategy object to help control the desired behavior. Please consider enabling the same.

**Describe the solution you'd like**
Add a property ProcessDictionaryKeys to CosmosSerializerOptions.

**Comment by j82w** [comment]
@ealsur does System.Text.Json have support for this?

**Comment by ealsur** [comment]
@wilcobmsft Is this for V3 or V4?

System.Text.Json currently does not support Dictionary<T,TValue> out of the box: Please  see the official migration guide: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#dictionary-with-non-string-key

**Comment by j82w** [comment]
Even if it's for v3 I'm not sure if it's a good idea to expose it if v4 can't support the option. It will make the migration from v3 to v4 more difficult. Right now both version support the same options.

**Comment by j82w** [comment]
This is supported via a custom CosmosSerializer.
