### ISSUE TITLE
Serializing ID with JsonProperty doesn't work 

### ISSUE THREAD

**Issue by brunobrandes** [Azure/azure-cosmos-dotnet-v3#1279]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
```json
public abstract class Entity
{
    /// <summary>
    /// Default document entity identifier
    /// </summary>
    [JsonProperty(PropertyName = "id")]
    public string Id { get; set; }

    /// <summary>
    /// Data time to live
    /// </summary>
    [JsonProperty(PropertyName = "ttl")]
    public int Ttl { get; set; }
}
```
When the following method is called, it still expects a id property, so that means JsonProperty did not serialize it correctly. However, if I change the property name to id then it works fine.

**To Reproduce**
Calling  create item async with my custom entity.
```csharp
await _container.CreateItemAsync<TEntity>(entity, partitionKey);
```

**Expected behavior**
Using [JsonProperty(PropertyName = "id")] to serialize lowercase id and create item successfully. 

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version: 4.0.0-preview3
OS Version: Windows

**Additional context**

CosmosException;StatusCode=BadRequest;SubStatusCode=0;ActivityId=aa2daa7a-9f51-4f8f-94d3-8cb0875c8ec4;RequestCharge=1.24;Message=Response status code does not indicate success: 400 Substatus: 0 Reason: (Message: {"Errors":["The input content is invalid because the required properties - 'id; ' - are missing"]}ActivityId: aa2daa7a-9f51-4f8f-94d3-8cb0875c8ec4, Request URI: /apps/DocDbApp/services/DocDbServer22/partitions/a4cb4962-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: RequestStartTime: 2020-03-14T14:50:58.6841005Z, RequestEndTime: 2020-03-14T14:50:59.4512049Z,  Number of regions attempted:1ResponseTime: 2020-03-14T14:50:59.4512049Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer22/partitions/a4cb4962-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 3, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#3, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: CreateAddressResolution - StartTime: 2020-03-14T14:50:59.1129651Z, EndTime: 2020-03-14T14:50:59.1228239Z, TargetEndpoint: https://127.0.0.1:8081//addresses/?$resolveFor=dbs%2fRltiAA%3d%3d%2fcolls%2fRltiAM7z-gk%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=0, SDK: Windows/10.0.18363 cosmos-netstandard-sdk/3.4.1).;Diagnostics

**Comment by brunobrandes** [comment]
CosmosClient suport to define serialize options. To solution the problem, I remove JsonProperty and configure PropertyNamingPolicy to CamelCase. 

```json
_cosmosClient.ClientOptions.SerializerOptions = new CosmosSerializationOptions
{
    Indented = true,
    PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
};
```

**Comment by j82w** [comment]
@brunobrandes v4 doesn't support Newtonsoft. The serializer is switched to [System.Text.Json](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/). You will need to convert all the tags to the System.Text.Json tags.
