### ISSUE TITLE
Expose Quota / capacity information on every response

### ISSUE THREAD

**Issue by brijeshb** [Azure/azure-cosmos-dotnet-v3#13]
Applications can  be designed to prioritize certain I/O over others and make optimum use of provisioned capacity if the current value of RUs consumed / available at the collection / database level would be returned on every request. (Even if this is slightly stale or an approximate measure). Some information is still better than no information.

**Comment by kirankumarkolli** [comment]
Quota & usage information is exposed through Azure monitoring and is the recommended way to consume.
