### ISSUE TITLE
Query returns empty results set, although the database contains items

### ISSUE THREAD

**Issue by dan-vasilov** [Azure/azure-cosmos-dotnet-v3#1300]
**Describe the bug**
The code below returns an empty results set, although it should return some items from the database.

**To Reproduce**
Create a .NET Core 3.1 console app. Replace the code in the program.cs file with the code below.
Configure a CosmosDb account in the code (edit class CosmosDbParameters properties).
Run the code. The code reports "QueryUsingCosmosClient returned 0 results".

`

     // Referenced NuGet packages:
     // - Microsoft.EntityFrameworkCore 3.1.2
     // - Microsoft.EntityFrameworkCore.Cosmos 3.1.2
     // - Microsoft.Extensions.DependencyInjection 3.1.2

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.Azure.Cosmos.Linq;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.DependencyInjection;

    namespace CosmosDbDemo
    {
    #region CosmosDb parameters
    // Define here your CosmosDb database connection
    class CosmosDbParameters
    {
        public const string AccountEndPoint = "{YOUR-COSMOSDB-ACCOUNT}";
        public const string AccountKey = "{YOUR-ACCOUNT-KEY}";
        public const string DbName = "DemoIssues";
        public const string DbContainer = "Offers";
    }
    #endregion

    class Program
    {
        static async Task Main( string[] args )
        {
            // Configure services
            var serviceProvider =
                new ServiceCollection()
                .AddDbContext<OfferContext>( 
                    options => options.UseCosmos(  CosmosDbParameters.AccountEndPoint, CosmosDbParameters.AccountKey, CosmosDbParameters.DbName ) )
                .BuildServiceProvider();

            using var ctx = serviceProvider.GetService<OfferContext>();
        
            // Ensure database has been properly created.
            ctx.Database.EnsureCreated();

            // Insert some items. A future query will try to retrieve only some of them.
            await AddItems( ctx );

            // Bypass EF. This one returns an empty results set.
            await QueryUsingCosmosClient( ctx );
        }

        private static async Task QueryUsingCosmosClient( OfferContext ctx )
        {
            var cosmosClient = ctx.Database.GetCosmosClient();
            var db = cosmosClient.GetDatabase(CosmosDbParameters.DbName );
            var container = db.GetContainer( CosmosDbParameters.DbContainer );
            var queryable = container.GetItemLinqQueryable<Offer>();
            var query = queryable.Where( _ => _.Status == OfferStatus.Created );
            var iterator = query.ToFeedIterator();
            var offers = new List<Offer>();
            while( iterator.HasMoreResults )
            {
                var buffer = await iterator.ReadNextAsync();
                offers.AddRange( buffer );
            }

            Console.WriteLine( $"QueryUsingCosmosClient returned {offers.Count} results" );
        }

        private static async Task AddItems( OfferContext ctx )
        {
            var offer = BuildOffer( "Acme Offer 1", 14 );
            ctx.Add( offer );
            offer = BuildOffer( "Acme Offer 2", 30 );
            ctx.Add( offer );
            offer = BuildOffer( "Coyote Ugly Super Offer 1", 25 );
            ctx.Add( offer );
            offer = BuildOffer( "Sloth Supercars Offer 14", 10 );
            ctx.Add( offer );
            await ctx.SaveChangesAsync();
        }

        private static Offer BuildOffer( string name, int valabilityInDays )
        {
            var result = new Offer
            {
                Id = Guid.NewGuid(),
                Name = name,
                ExpirationDateUtc = DateTime.UtcNow.Date.AddDays( valabilityInDays ),
                Status = OfferStatus.Created
            };

            return result;
        }
    }

    class Offer
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public DateTime ExpirationDateUtc { get; set; }
        public OfferStatus Status { get; set; }
    }

    enum OfferStatus
    {
        Created = 0,
        Approved = 1,
        Accepted = 2,
        Declined = 3
    }

    class OfferContext : DbContext
    {
        public OfferContext( DbContextOptions<OfferContext> options ) : base( options )
        {

        }

        public DbSet<Offer> Offers { get; set; }

        protected override void OnModelCreating( ModelBuilder modelBuilder )
        {
            modelBuilder.HasDefaultContainer( CosmosDbParameters.DbContainer );
            modelBuilder.Entity<Offer>().HasPartitionKey( _ => _.Id );
            modelBuilder.Entity<Offer>().Property( _ => _.Id )
                    .HasConversion( _ => _.ToString( "B" ), _ => Guid.Parse( _ ) );
            modelBuilder.Entity<Offer>().Property( _ => _.Status )
                    .HasConversion( _ => _.ToString(), _ => (OfferStatus)Enum.Parse( typeof( OfferStatus ), _ ) );
        }
    }

}
`

**Expected behavior**
The code should return at least 4 items.

**Actual behavior**
The code returns 0 items.

**Environment summary**
SDK Version: .NET Core 3.1
OS Version: Windows 10

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
This is pretty much the same as #1301 except this time it is Enum. Default Newtonsoft implementation converts Enums to a int and not a string. The Microsoft.EntityFrameworkCore.Cosmos converts the Enum to a string.

Solution 1:
Use the Microsoft.EntityFrameworkCore.Cosmos query logic.

Solution 2:
Add customer JSON converter to the enum. You will also need to write a custom JsonConverter for the id.

```
 class Offer
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public DateTime ExpirationDateUtc { get; set; }

        [JsonConverter(typeof(StringEnumConverter))]
        public OfferStatus Status { get; set; }
    }
```
