### ISSUE TITLE
"Error converting value to type 'System.Guid'.

### ISSUE THREAD

**Issue by dan-vasilov** [Azure/azure-cosmos-dotnet-v3#1301]
**Describe the bug**
The code below tries to read all items from a CosmosDb.  When running, the exception "Error converting value "Offer" to type 'System.Guid'. Path 'Documents[0].id', line 1, position 203." is reported.

**To Reproduce**
Create a .NET Core 3.1 console app. 
Replace the code in Program.cs with the code below.
Add the NuGet packages 
 - Microsoft.EntityFrameworkCore 3.1.2
 - Microsoft.EntityFrameworkCore.Cosmos 3.1.2
 - Microsoft.Extensions.DependencyInjection 3.1.2
Configure an CosmosDb account by editing the consts defined in class CosmosDbParameters.
Run the code. The exception is reported in the console.

`

     // Referenced NuGet packages:
     // - Microsoft.EntityFrameworkCore 3.1.2
     // - Microsoft.EntityFrameworkCore.Cosmos 3.1.2
     // - Microsoft.Extensions.DependencyInjection 3.1.2

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.Azure.Cosmos.Linq;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.DependencyInjection;

    namespace CosmosDbDemo
    {
    #region CosmosDb parameters
    // Define here your CosmosDb database connection
    class CosmosDbParameters
    {
        public const string AccountEndPoint = "{YOUR-ACCOUNT-ENDPOINT-HERE}";
        public const string AccountKey = "{YOUR-ACCOUNT-KEY-HERE}";
        public const string DbName = "DemoIssues";
        public const string DbContainer = "Offers";
    }
    #endregion

    class Program
    {
        static async Task Main( string[] args )
        {
            // Configure services
            var serviceProvider =
                new ServiceCollection()
                .AddDbContext<OfferContext>( 
                    options => options.UseCosmos(  CosmosDbParameters.AccountEndPoint, CosmosDbParameters.AccountKey, CosmosDbParameters.DbName ) )
                .BuildServiceProvider();

            using var ctx = serviceProvider.GetService<OfferContext>();
        
            // Ensure database has been properly created.
            ctx.Database.EnsureCreated();

            // Insert some items. A future query will try to retrieve only some of them.
            await AddItems( ctx );

            // Bypass EF. Simply try to return all available items.
            // Fails with error 
            // "Error converting value "Offer" to type 'System.Guid'. Path 'Documents[0].id', line 1, position 203."
            await QueryUsingCosmosClient2( ctx );
        }

        private static async Task QueryUsingCosmosClient2( OfferContext ctx )
        {
            try
            {
                var cosmosClient = ctx.Database.GetCosmosClient();
                var db = cosmosClient.GetDatabase(CosmosDbParameters.DbName );
                var container = db.GetContainer( CosmosDbParameters.DbContainer );
                var queryable = container.GetItemLinqQueryable<Offer>();
                var query = queryable.Where( _ => true );
                var iterator = query.ToFeedIterator();
                var offers = new List<Offer>();
                while( iterator.HasMoreResults )
                {
                    var buffer = await iterator.ReadNextAsync();
                    offers.AddRange( buffer );
                }

                Console.WriteLine( $"QueryUsingCosmosClient2 returned {offers.Count} results" );
            }
            catch( Exception ex )
            {
                Console.WriteLine( ex );
            }

        }

        private static async Task AddItems( OfferContext ctx )
        {
            var offer = BuildOffer( "Acme Offer 1", 14 );
            ctx.Add( offer );
            offer = BuildOffer( "Acme Offer 2", 30 );
            ctx.Add( offer );
            offer = BuildOffer( "Coyote Ugly Super Offer 1", 25 );
            ctx.Add( offer );
            offer = BuildOffer( "Sloth Supercars Offer 14", 10 );
            ctx.Add( offer );
            await ctx.SaveChangesAsync();
        }

        private static Offer BuildOffer( string name, int valabilityInDays )
        {
            var result = new Offer
            {
                Id = Guid.NewGuid(),
                Name = name,
                ExpirationDateUtc = DateTime.UtcNow.Date.AddDays( valabilityInDays ),
                Status = OfferStatus.Created
            };

            return result;
        }
    }

    class Offer
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public DateTime ExpirationDateUtc { get; set; }
        public OfferStatus Status { get; set; }
    }

    enum OfferStatus
    {
        Created = 0,
        Approved = 1,
        Accepted = 2,
        Declined = 3
    }

    class OfferContext : DbContext
    {
        public OfferContext( DbContextOptions<OfferContext> options ) : base( options )
        {

        }

        public DbSet<Offer> Offers { get; set; }

        protected override void OnModelCreating( ModelBuilder modelBuilder )
        {
            modelBuilder.HasDefaultContainer( CosmosDbParameters.DbContainer );
            modelBuilder.Entity<Offer>().HasPartitionKey( _ => _.Id );
            modelBuilder.Entity<Offer>().Property( _ => _.Id )
                    .HasConversion( _ => _.ToString( "B" ), _ => Guid.Parse( _ ) );
            modelBuilder.Entity<Offer>().Property( _ => _.Status )
                    .HasConversion( _ => _.ToString(), _ => (OfferStatus)Enum.Parse( typeof( OfferStatus ), _ ) );
        }
    }

}

`

**Expected behavior**
The code should retrieve all items from the database.

**Actual behavior**
The code reports an exception.

**Environment summary**
SDK Version: .NET Core 3.1
OS Version Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
The problem is you are using the Microsoft.EntityFrameworkCore.Cosmos to create the items, but are using the Microsoft.Azure.Cosmos SDK to do the query. The Microsoft.Azure.Cosmos SDK doesn't use the Model converter and Newtonsoft doesn't know how to convert `"{bf9ec86f-5444-4ffb-bb5b-f2a2709df5f1}"` string to a guid.

Solution 1:
 Use the Microsoft.EntityFrameworkCore.Cosmos query logic.
`var offers = ctx.Offers.ToList();`

Solution 2:
Add a custom JsonConverter to the Id
