### ISSUE TITLE
Please ensure XML comments for the API methods are available and packaged with NUGET

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-cosmos-dotnet-v3#1303]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
The methods of the API should consistently have accompanying XML comments so that the developer gets hints through intellisense while using Visual Studio, thereby improving developer productivity.

Refer my observations in the end of this issue
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1264

**To Reproduce**
Write some code in Visual Studio which uses the `Microsoft.Azure.Cosmos.Container ` class and then invokes the `ReadItemAsync `method . No need to compile.
Press F12 when the mouse is over `ReadItemAsync` method

**Expected behavior**
I intend to see XML comments when I press F12 over a method

### System.DataTable
![image](https://user-images.githubusercontent.com/20245330/77560298-2f4e0680-6eb5-11ea-9c1b-a1a50e35405a.png)

###  SqlDataReader class
![image](https://user-images.githubusercontent.com/20245330/77561277-65d85100-6eb6-11ea-9b95-aad202b0145f.png)

**Actual behavior**

## Example of what intellisense experience with Cosmos SDK looks today
![image](https://user-images.githubusercontent.com/20245330/77560061-d54d4100-6eb4-11ea-8378-713655a2f3a2.png)

**Environment summary**
SDK Version: 3.6
OS Version Windows 10

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
It might be related to issue https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1281

**Comment by j82w** [comment]
Fixed in 3.7.0 release
