### ISSUE TITLE
PartitionKey.Equals throws NullReferenceException

### ISSUE THREAD

**Issue by GrimGadget** [Azure/azure-cosmos-dotnet-v3#1307]
**Describe the bug**
`PartitionKey.Equals` throws `NullReferenceException` for default(PartitionKey).

**To Reproduce**
`var b = default(PartitionKey).Equals(default(PartitionKey))`

Alternatively, use NSubstitute for unit testing and set up a return value for `CreateItemAsync` with `Arg.Any<PartitionKey>()` for the `PartitionKey` condition.

**Expected behavior**
Should not throw a `NullReferenceException`.  

`default(PartitionKey).Equals()` should correctly evaluate against the parameter without throwing an exception.

**Actual behavior**
Throws NullReferenceException

**Environment summary**
SDK Version: NETStandard.Library 2.0.3
OS Version (e.g. Windows, Linux, MacOSX): Windows 10 Pro

**Additional context**
I recently updated to Microsoft.Azure.Cosmos 3.7.0 and this has broken a number of my unit tests, as it fails during test setup.

![image](https://user-images.githubusercontent.com/30664204/77648584-c4491200-6f3e-11ea-9041-ce17c5ded52c.png)

**Comment by GrimGadget** [comment]
I have reverted to 3.6.0, which does not have this bug.

**Comment by j82w** [comment]
@GrimGadget how are you able to pass in null? PartitionKey is a struct and is not nullable.

**Comment by KristianJakubik** [comment]
@j82w 
I  don't think it is throwing there, but rather here:
![image](https://user-images.githubusercontent.com/28342527/77660530-bbc1fd00-6f79-11ea-9078-c8d61e38b0bd.png)
For example:
```
PartitionKey pk = default;
pk.Equals(new PartitionKey("random"));
```
after debugging `Equals()` method `this.InternalKey` contains null. This also fails on `toString()` method as well.

PS:
I wrote the more detailed reasoning in [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1265#discussion_r389863662). Why it was not checked for NullRef.

**Comment by GrimGadget** [comment]
OK, sorry.  I picked the wrong dot in my assumption.

I looked at the PR referenced, and it doesn't actually address this specific problem, other than some discussion and an apparent dismissal.

Also, the unit tests in that PR should probably add some checks where the left-side operand is default(PartitionKey), PartitionKey.None, and PartitionKey.Null for completeness.

**Comment by GrimGadget** [comment]
Edited the original post to correct the assumption as to root cause.
