### ISSUE TITLE
Why is there a release 3.7.0 version of the nuget which does not include the new pull model processor?

### ISSUE THREAD

**Issue by lpunderscore** [Azure/azure-cosmos-dotnet-v3#1317]
I noticed that a nuget version 3.7.0 is available which does not include the features included in the -preview versions.

I notice the release is not listed in the releases section on github.

Were those features abandoned? 

Asking because we started work that relies on those features.

**Comment by ealsur** [comment]
Those features are still in preview. We do not tie feature release with Nuget package numbers, they will be included in the public non-preview package when they go GA, meanwhile, along with other features, are part of the preview/alpha releases.

I know this is not exactly clear by the numbering we use and we are thinking on ways to improve it.

When the feature is GA it will be included in the change log for the version it is released.

And no, it is not being abandoned, we are simply still working on it based on feedback.

**Comment by lpunderscore** [comment]
Thanks for the answer, It was confusing to update to the released nuget version and lose features.
