### ISSUE TITLE
Allow forcing read from a read-only replica either per request or as a client setting

### ISSUE THREAD

**Issue by jahmai** [Azure/azure-cosmos-dotnet-v3#1321]
**Is your feature request related to a problem? Please describe.**
When configuring a Cosmos account with read-only replicas, it assigns RU to those replica's and you pay for them. It would be good to be able to force read to a replica in order to balance those RU's between the master and the replicas.

**Describe the solution you'd like**
A setting on the QueryRequestOptions/ItemRequestOptions to force the request to go to a read-only replica, or a client setting that forces all reads to replicas.

**Describe alternatives you've considered**
Doing it automatically internally when the primary returns 429 is not ideal because it leads to overloading the primary database and creating fights conditions with the write workloads before moving over to a replica.

**Additional context**
This feature may already exist but I cannot find any information about it?

**Comment by kirankumarkolli** [comment]
@jahmai Cosmos SDK already leverages all replica's. Please check the Diagnostics which reflect which replica was used. 

Please re-open with more context/scenario with related diagnostics string to further troubleshoot.

**Comment by jahmai** [comment]
@kirankumarkolli Yes, I am aware of that. The feature request is to _force_ reading from replicas instead of letting the SDK do it itself. The rationale being there are some read operations that I never want to consume to RU of the primary. Does that make sense? Is that something the SDK can currently do?

**Comment by j82w** [comment]
@jahmai are you referring to geo-replicated replicas? 

For example:
Application location is EastUS
Primary CosmosDB location is EastUS, and geo-replicated to WestUS
The application can decide to take the additional latency hit to go to the WestUS for certain read operations.

If you are referring to the local replicas what's the reason for needing to force to read from the replicas?

**Comment by jahmai** [comment]
@j82w I am referring to geo-replicated _read_ replicas. There are some operations (like reports) where time is not of the essence but tend to drain a large amount of RUs to complete, which would be ideal to force to read from WestUS instead of competing for more critical operations on EastUS.

I know that if you have multi-write regions enabled you can nominate which region you prefer to send all operations to, but I would like to do the same thing for read-only replicas in other regions for certain operations only. Per request is ideal, but I could just also create a while new client instance with the preferred setting. Is this something already built-in?

**Comment by j82w** [comment]
The best way to do this is with multiple client instances with preferred region settings. Then the application can decide which client to use.

**Comment by jahmai** [comment]
@j82w Yes I think that's the way it should be done, with CosmosClientOptions.ApplicationPreferredRegions. I will close this ticket and re-open if it doesn't work the way I expect. Thanks!
