### ISSUE TITLE
CreatePermissionAsync - tokenExpiryInSeconds causes Exception "One of the specified inputs is invalid"

### ISSUE THREAD

**Issue by middiu** [Azure/azure-cosmos-dotnet-v3#1326]
**Describe the bug**
When I try to create a permission token on a container I keep getting this exception:
```
DocumentClientException with status code BadRequest, message: Message: {"Errors":["One of the specified inputs is invalid"]}, inner exception: null, and response headers: {
"x-ms-schemaversion": "1.9",
"x-ms-request-validation-failure": "1",
"x-ms-transport-request-id": "3",
"x-ms-serviceversion": " version=2.10.0.0",
...
}
```

After many hours I could identify that the issue is in using the parameter **tokenExpiryInSeconds** of method **CreatePermissionAsync**

This is the piece of code I'm using:
```
PermissionProperties p = new PermissionProperties(
                        id: _permissionId,
                        permissionMode: permissionMode,
                        container: container
                    );

                    permission = await user.CreatePermissionAsync(p, 60);
```

A new permission token should be created with the token lifetime specified in the CreatePermissionAsync method. 

If I run this code everything works fine:
```
                    PermissionProperties p = new PermissionProperties(
                        id: _permissionId,
                        permissionMode: permissionMode,
                        container: container
                    );

                    permission = await user.CreatePermissionAsync(p);
```

**Environment summary**
SDK Version: Latest Version

**Comment by j82w** [comment]
I did some quick testing and it appears to be failing for anything under 600 seconds.

**Comment by kirankumarkolli** [comment]
@j82w is read also failing for > 10M?

**Comment by j82w** [comment]
@kirankumarkolli it's working for values greater than 600 seconds/10 minutes.

**Comment by middiu** [comment]
Is this the expected behaviour? I remember to read in the documentation that the minimum value could 1 min

**Comment by danielkon96** [comment]
I am having the same issue and only more than 600 seconds works. This is definitely a bug since the documentation says 1 minute.

**Comment by kirankumarkolli** [comment]
Short-term leased token bound to cause refresh cycles which are quite unnecessary. Most typical cases we have seen the expiry is much higher than 10M. 

@middiu , @danielkon96 do 10M min interval fit into your scenarios?

@j82w  lets please address the docs gaps.

**Comment by middiu** [comment]
@kirankumarkolli yeah 10min works for me at this stage.

Cheers

**Comment by danielkon96** [comment]
@kirankumarkolli I'm running tests, so I just wanted to address the bug and let the cosmosDB team know. I don't have a production scenario right now.

**Comment by John-HLC** [comment]
@danielkon96  - Do you need any further assistance documenting this?

Please update documentation or fix the SDK to match documentation.
If documentation (and intelligence) says we can set as low as 10 seconds, an exception for invalid input should not be thrown if I'm trying to set to 180 seconds for a test.  :) I would rather not admit how many hours (days) lost on this thinking I was going crazy triple checking everything, even started spiraling out to different issues because I never would have thought to bump it up over 600 seconds given the explicit documentation to be as low as 10 seconds.
