### ISSUE TITLE
Use Resource Token in Cassandra API

### ISSUE THREAD

**Issue by tonylife** [Azure/azure-cosmos-dotnet-v3#1327]
We are recently exploring the way to use resource token to access Cosmos DB using Cassandra API.
You may already have this feature. But we didn't find documentation around it.
Please clarify whether this feature exists and provide a sample if it is.

Also want to mention, we did find a sample for Gremlin API.
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-use-resource-tokens-gremlin

**Comment by ealsur** [comment]
This is the Github repo for the Cosmos DB SQL API SDK, not for Cassandra.

For Cassandra, there is protocol compatibility, if this is a feature that is available in Cassandra but does not work on Cosmos DB Cassandra API, please follow up the request at https://feedback.azure.com/forums/263030-azure-cosmos-db?category_id=323344
