### ISSUE TITLE
Linq Expression Visitor for Dictionary.ContainsKey

### ISSUE THREAD

**Issue by GravlLift** [Azure/azure-cosmos-dotnet-v3#1333]
**Is your feature request related to a problem? Please describe.**
It seems like the Linq SQL query visitor could support `Dictionary.ContainsKey` expressions for dictionaries with JSON-friendly keys, such as `int`, `string` or `Guid`.

**Describe the solution you'd like**
Being able to evaluate `Container.GetItemLinqQueryable().Where(r => r.Dictionary.ContainsKey("key"))` such that the resulting query would look something like
`SELECT VALUE root FROM root WHERE (IS_DEFINED(root["Dictionary"]["key"]))`

**Describe alternatives you've considered**
At the moment, for dictionaries with non-nullable values, you can write `Container.GetItemLinqQueryable().Where(r => r.Dictionary["key"] != null)` and VS will merely mark it with a CS0472 warning (`The result of the expression is always the same since a value of this type is never equal to 'null'`). I've been unable to find a workaround for Dictionaries with nullable values.

**Comment by khdang** [comment]
@GravlLift thanks for the suggestion. We will consider it. From the description, one alternative you can try to achieve IS_DEFINED(root["Dictionary"]["key"]) is to use the extension method IsDefined() in the Microsoft.Azure.Cosmos.Linq namespace, as following:
```
Container.GetItemLinqQueryable().Where(r => r.Dictionary["key"].IsDefined())
```

**Comment by khdang** [comment]
We've taken note of this and will consider supporting it in the future. As there is an equivalent way for this scenario, I'm closing this issue for now
