### ISSUE TITLE
Container.UpsertItemAsync() throws a JsonSerializationException after a burst of 429 error retries

### ISSUE THREAD

**Issue by dlmelendez** [Azure/azure-cosmos-dotnet-v3#1335]
SDK Version 3.7.0

**Describe the bug**
Container.UpsertItemAsync() throws a JsonSerializationException after a burst of 429 errors from the container. [Documentation]( https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.upsertitemasync?view=azure-dotnet) shows this function should only throw an AggregateExecption or CosmosException.

**To Reproduce**
Create Azure function to insert 3000-4000 inserts and handle 429 errors with the suggested retry back off time in the header. The exception only happens after a heavy load at random.

**Expected behavior**
Throw a CosmosException 429 exception, not a JsonSerializationException.

**Actual behavior**
JsonSerializationException is thrown. "InnerException":null,"HelpLink":null,"Source":"Microsoft.Azure.Cosmos.Client","HResult":-2146233088} Cannot create and populate list type Microsoft.Azure.Cosmos.Headers. Path 'Headers', line 1, position 456. 

**Environment summary**
SDK Version: 3.7.0
OS Version: Windows
Azure Functions - Consumption Plan, v3 using .NET Core 3.1 with dependency injection.

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).
Full stack trace showing the JsonSerializationException is throw from the Microsoft.Azure.Cosmos SDK:
The activity function 'Image-Upsert-DocDbEntity' failed: "Failed to deserialize exception from TaskActivity:
```
 {"$type":"Microsoft.Azure.Cosmos.CosmosException, Microsoft.Azure.Cosmos.Client","ResponseBody":"{\r\n  \"Errors\": [\r\n    \"Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429\"\r\n  ]\r\n}","StatusCode":429,"SubStatusCode":3200,"RequestCharge":0.38,"ActivityId":"97ed0890-aba0-48e4-b363-0c644d235a29","RetryAfter":"00:00:00.0720000","Headers":["x-ms-request-charge","x-ms-activity-id","x-ms-substatus","x-ms-retry-after-ms","lsn","x-ms-schemaversion","x-ms-quorum-acked-lsn","x-ms-current-write-quorum","x-ms-current-replica-set-size","x-ms-xp-role","x-ms-global-Committed-lsn","x-ms-number-of-read-regions","x-ms-transport-request-id","x-ms-cosmos-llsn","x-ms-cosmos-quorum-acked-llsn","x-ms-serviceversion"],"Diagnostics":{"$type":"Microsoft.Azure.Cosmos.CosmosDiagnosticsCore, Microsoft.Azure.Cosmos.Client"} 
```
,"StackTrace":"   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()\r\n   at Microsoft.Azure.Cosmos.CosmosResponseFactory.ProcessMessageAsync[T](Task`1 cosmosResponseTask, Func`2 createResponse)\r\n   at Microsoft.Azure.Cosmos.ContainerCore.UpsertItemAsync[T](T item, Nullable`1 partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken)\r\n   at ObserveAi.Data.Image.ImageDocDbContext.UpsertAsync(ImageActionsCdbEntity entity) in D:\\a\\1\\s\\src\\ObserveAi.Data.Image\\ImageDocDbContext.cs:line 212\r\n   at ObserveAi.Web.App.Functions.Image.ImageFunctions.ImageUpsertDocDbEntity(IDurableActivityContext context, ILogger log) in D:\\a\\1\\s\\src\\ObserveAi.Web.App.Functions\\Image\\ImageFunctions.cs:line 604\r\n   at ObserveAi.Web.App.Functions.Image.ImageFunctions.ImageUpsertDocDbEntity(IDurableActivityContext context, ILogger log) in D:\\a\\1\\s\\src\\ObserveAi.Web.App.Functions\\Image\\ImageFunctions.cs:line 623\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 585\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 532\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 468\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 278","Message":"Response status code does not indicate success: TooManyRequests (429); Substatus: 3200; ActivityId: 97ed0890-aba0-48e4-b363-0c644d235a29; Reason: ({\r\n  \"Errors\": [\r\n    \"Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429\"\r\n  ]\r\n});","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib"},"InnerException":null,"HelpLink":null,"Source":"Microsoft.Azure.Cosmos.Client","HResult":-2146233088}". See the function execution logs for additional details. Failed to deserialize exception from TaskActivity: {"$type":"Microsoft.Azure.Cosmos.CosmosException, Microsoft.Azure.Cosmos.Client","ResponseBody":"{\r\n  \"Errors\": [\r\n    \"Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429\"\r\n  ]\r\n}","StatusCode":429,"SubStatusCode":3200,"RequestCharge":0.38,"ActivityId":"97ed0890-aba0-48e4-b363-0c644d235a29","RetryAfter":"00:00:00.0720000","Headers":["x-ms-request-charge","x-ms-activity-id","x-ms-substatus","x-ms-retry-after-ms","lsn","x-ms-schemaversion","x-ms-quorum-acked-lsn","x-ms-current-write-quorum","x-ms-current-replica-set-size","x-ms-xp-role","x-ms-global-Committed-lsn","x-ms-number-of-read-regions","x-ms-transport-request-id","x-ms-cosmos-llsn","x-ms-cosmos-quorum-acked-llsn","x-ms-serviceversion"],"Diagnostics":{"$type":"Microsoft.Azure.Cosmos.CosmosDiagnosticsCore, Microsoft.Azure.Cosmos.Client"},"StackTrace":"   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()\r\n   at Microsoft.Azure.Cosmos.CosmosResponseFactory.ProcessMessageAsync[T](Task`1 cosmosResponseTask, Func`2 createResponse)\r\n   at Microsoft.Azure.Cosmos.ContainerCore.UpsertItemAsync[T](T item, Nullable`1 partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken)\r\n   at ObserveAi.Data.Image.ImageDocDbContext.UpsertAsync(ImageActionsCdbEntity entity) in D:\\a\\1\\s\\src\\ObserveAi.Data.Image\\ImageDocDbContext.cs:line 212\r\n   at ObserveAi.Web.App.Functions.Image.ImageFunctions.ImageUpsertDocDbEntity(IDurableActivityContext context, ILogger log) in D:\\a\\1\\s\\src\\ObserveAi.Web.App.Functions\\Image\\ImageFunctions.cs:line 604\r\n   at ObserveAi.Web.App.Functions.Image.ImageFunctions.ImageUpsertDocDbEntity(IDurableActivityContext context, ILogger log) in D:\\a\\1\\s\\src\\ObserveAi.Web.App.Functions\\Image\\ImageFunctions.cs:line 623\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 585\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 532\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 468\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 278","Message":"Response status code does not indicate success: TooManyRequests (429); Substatus: 3200; ActivityId: 97ed0890-aba0-48e4-b363-0c644d235a29; Reason: ({\r\n  \"Errors\": [\r\n    \"Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429\"\r\n  ]\r\n});","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib"},"InnerException":null,"HelpLink":null,"Source":"Microsoft.Azure.Cosmos.Client","HResult":-2146233088} Cannot create and populate list type Microsoft.Azure.Cosmos.Headers. Path 'Headers', line 1, position 456.

**Comment by ealsur** [comment]
@dlmenendez Looks like you are trying to serialize the CosmosException (maybe Jsonserializer.Serialize(exception)).

A workaround would be to just consume the exception.ToString()?

**Comment by dlmelendez** [comment]
@ealsur No, if you look at the stack, the JsonSerialization exception is coming from the Microsoft.Azure.Cosmos.ContainerCore.UpsertItemAsync[T](T item, Nullable1 partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken) method. This exception is popping before it hits my code.
The only workaround (if you want to call it that) is to do something like this to not break my retry logic around.
```
try
{
    Container tenantdc = await GetTenantContainerAsync("containerName");
    var imageNew = await tenantdc.UpsertItemAsync<Entity>(entity, new PartitionKey(entity.PartitionKey), this.RequestOptions);
     return imageNew.Resource;
 }
 catch (JsonSerializationException) 
{
   throw new CosmosException("SDK serialization error.", HttpStatusCode.TooManyRequests, 3200, Guid.NewGuid().ToString()), 0d);
 }
```

**Comment by dlmelendez** [comment]
Looks like the JsonSerializationException is actually coming from the Durable Functions framework after doing some more testing. Closing this issue.
