### ISSUE TITLE
Bulk Support is not working as Bulk Executor Library

### ISSUE THREAD

**Issue by TianyuHou** [Azure/azure-cosmos-dotnet-v3#1337]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Our project used bulk executor before and works fine for us,  for the old library we just need to input the entire data we need to do the bulk import and with a lower throughput, it works perfectly fine. But with the new bulk SDK, we used same data as input and throughput but receives so many error of TooManyRequest and we have to increase the throughput to a real large number.  I'm wondering what's the difference under the hood for these two libraries, and why the old one can directly take over all the setup and optimized throughput?
**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
There is a [blog post](https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/) explaining the bulk executor.
@ealsur any other suggestions?

**Comment by TianyuHou** [comment]
@j82w  yes, we have checked on that blog and followed every document recommended from your side. Our scenario is a 1000 documents per partitionKey and distributed evenly for paging purpose. So we don't mind the writing process is slow, but we indeed want to choose a lower throughput to keep costs down. But we don't understand why the new SDK always throws 429s(Too Many Requests) while the Bulk Executor library doesn't, do we need to configure anything in the code that not mentioned in the doc?

**Comment by j82w** [comment]
@ealsur and @abhijitpai are the experts. I'll let them respond.

There was [congestion control ](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1074) added in the preview releases which seems like it would help with this scenario.

**Comment by abhijitpai** [comment]
@TianyuHou what version of the SDK are you using?

**Comment by TianyuHou** [comment]
@abhijitpai  .Net Core 3.1    Microsoft.Azure.Cosmos 3.7.0

**Comment by ealsur** [comment]
The point here is Bulk Executor library seems to have a "custom" retry mechanism, when the retry count is 0 and it will retry forever until it succeeds.
In V3 we honor the Retry configuration on the CosmosClientOptions.

In an under-provisioned scenario, V2 library would retry forever until it succeeds, it would take a long time, but it would eventually succeed.

In V3, the control is on the user side, to avoid having that obscure behavior. User can then increase the Retry count to keep doing more retries (and match the behavior of V2 library).

**Comment by TianyuHou** [comment]
@ealsur  Appreciate your explanation!
