### ISSUE TITLE
Release for v3.7.0 missing from "Releases" page

### ISSUE THREAD

**Issue by mcpappas** [Azure/azure-cosmos-dotnet-v3#1338]
Don't know if this is the right way to raise this issue, but I noticed that the [v3.7.0 Nuget package](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.7.0) was published on 3/26, but I don't see it nor its release notes on the releases tab in GitHub, nor does it seem to have a corresponding tag in the repository. I made my first contribution a few weeks back and came looking to see if it made it into a release when I noticed.

Let me know if there is anything I can do to help resolve, or if there is a better place/way to raise an issue like this in the future.

**Comment by j82w** [comment]
Thanks for pointing this out. I added the tag and updated the releases.
