### ISSUE TITLE
Add estimated release date for v4

### ISSUE THREAD

**Issue by Kiril1512** [Azure/azure-cosmos-dotnet-v3#1370]
Hello.

It is possible to add the estimated release date for the v4 SDK? What can I find is only the preview change log [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/changelog.md) but I can't find when it is planed to roll out the full release for the version 4. 

Thank you!

**Comment by ealsur** [comment]
At this point we don't have any hard dates, particularly due to the nature of the involved changes and how that might affect other related services. We will communicate clearly when we have a GA date.

**Comment by Kiril1512** [comment]
Thank you, closing this issue.
