### ISSUE TITLE
Response Headers: Make RetryAfter Public instead of Internal

### ISSUE THREAD

**Issue by cgelon** [Azure/azure-cosmos-dotnet-v3#1374]
**Is your feature request related to a problem? Please describe.**
When using streaming methods (DeleteItemStreamAsync), exceptions are not used for throttling (status code 429). The only place to currently get the RetryAfter TimeSpan (to help limit the requests sent to the backend) is in the CosmosException. Headers.cs internally has RetryAfter, but it is never exposed to the user.

**Describe the solution you'd like**
Make Headers.RetryAfter public so users of the Cosmos SDK can handle customized throttling.

**Describe alternatives you've considered**
We can use DeleteItemAsync, which returns CosmosExceptions with the RetryAfter property, but that degrades performance due to exception handling.

**Additional context**
Pull request can be found here: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1373

**Comment by j82w** [comment]
The retry after can be accessed with the following code.
```C#
if (response.Headers.TryGetValue("x-ms-retry-after-ms", out string retryAfterStringValue))
{
     long retryIntervalInMilliseconds = 0;
     if (long.TryParse(retryAfterStringValue, NumberStyles.Number, CultureInfo.InvariantCulture, out retryIntervalInMilliseconds))
     {
          return TimeSpan.FromMilliseconds(retryIntervalInMilliseconds);
     }
}
```

**Comment by cgelon** [comment]
The only response header that my process returns (at least from a DeleteItemStreamAsync call that had status code 429) is x-ms-substatus (which was 3200). Looking internally into the response Headers while debugging I could confirm that the internal RetryAfter field had a value. Does that indicate any other issues? The call is being made against a 100 GB collection with around 40k RU/s.

**Comment by ealsur** [comment]
RetryAfter obtains the value from the Headers, check out this test: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HeadersTests.cs#L153

What you are saying is that if you read the `x-ms-retry-after-ms` header, you are getting no value?

**Comment by j82w** [comment]
@cgelon I verified it that the code does work. I created a [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1379) with a sample to get the value.

**Comment by ealsur** [comment]
Please re-open if the provided workaround/samples do not work.
