### ISSUE TITLE
Encryption on FeedResponse - How to handle partial decryption success

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#1378]
For Feed operations (Change Feed, Read Feed, Query), when using `FeedResponse<T>`, if the user is using encryption support and one of the documents cannot be decrypted, it shouldn't be a complete failure.

There are cases where the rest of the documents in the FeedResponse need to be accessed regardless of the one that failed decryption.

**Comment by anujtoshniwal** [comment]
This issue has been addressed as part of the below PR. 
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1465
