### ISSUE TITLE
[Documentation] CosmosClientBuilder.WithThrottlingRetryOptions description incorrect

### ISSUE THREAD

**Issue by richsch** [Azure/azure-cosmos-dotnet-v3#1391]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
The documentation for [CosmosClientBuilder.WithThrottlingRetryOptions](https://docs.microsoft.com/en-us/dotnet/api/azure.cosmos.fluent.cosmosclientbuilder.withthrottlingretryoptions?view=azure-dotnet-preview#Azure_Cosmos_Fluent_CosmosClientBuilder_WithThrottlingRetryOptions_System_TimeSpan_System_Int32_) states "Sets the minimum time to wait between retry and the max number of times to retry on throttled requests." However, when you inspect the parameters, you see it is used to set the _maximum_ time between requests.

This incorrect description is also present on the [CosmosClientBuilder](https://docs.microsoft.com/en-us/dotnet/api/azure.cosmos.fluent.cosmosclientbuilder?view=azure-dotnet-preview) class description, next to the `WithThrottlingRetryOptions(TimeSpan, Int32)` method name.

**Expected behavior**
Description should read:
"Sets the maximum time to wait between retry and the max number of times to retry on throttled requests."

**Additional context**
Was requested to log the issue here after querying this on twitter - my first time submitting a report, so apologies if this isn't the right place for it!

**Comment by j82w** [comment]
@ealsur can this be closed because of this PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1388?

**Comment by ealsur** [comment]
Yes, didn't see this issue to link
