### ISSUE TITLE
CosmosDB is not opening on device but code works on Emulator

### ISSUE THREAD

**Issue by petevick** [Azure/azure-cosmos-dotnet-v3#1394]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I am using CosmosDB for the first time, and all was going well – until I deployed to the devices instead of the emulator.

Using the emulator, opening the database, retrieving, inserting and updating all work perfectly.

Deploy to the device.

**To Reproduce**
using Microsoft.Azure.Cosmos;
…

private static CosmosClient cosmosClient = null;
…

try
                {
                    cosmosClient = new CosmosClient(EndpointUri, PrimaryKey);
                                                                                
                                                                                
Always fails on the device – error is:-
                                                                                
?ex
{System.TypeInitializationException: The type initializer for 'Microsoft.Azure.Documents.UserAgentContainer' threw an exception. ---> System.UnauthorizedAccessException: Access to the path "/proc/sys/kernel/ostype" is denied.

Should open as it does on the emulator

Fails on iPhone and Android Devices but works on Emulator

**Environment summary**
SDK Version:3.8.0
Windows 10 Version 1909 OS Build 18363.778

**Comment by j82w** [comment]
Hi @petevick, 

Are you using Xamarin? Any chance you can provide a sample that is hitting the issue?

It seems like the application doesn't have the correct permissions to access the OS type which is included in the [user agent string](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/EnvironmentInformation.cs).  Are you sure you are running the same iPhone and Android version as the emulator?

**Comment by petevick** [comment]
Hi 
Using Xamarin forms - OS 13.4.1 on emulator and device. 

Code is simply
 const string accountURL = @"xxxxxxx";
        const string accountKey = @"yyyyy";
        const string databaseId = @"ToDoList";
        const string collectionId = @"Items";

        // The Cosmos client instance
        private static CosmosClient cosmosClient = null;

if (cosmosClient == null)
            {
                try
                {
                    cosmosClient = new CosmosClient(accountURL, accountKey);
                    database = await cosmosClient.CreateDatabaseIfNotExistsAsync(databaseId);
                    container = await database.CreateContainerIfNotExistsAsync(collectionId, "/_partitionkey");
                   
                    return true;
                }
                catch (Exception ex)
                {
.....

Fails on the first statement -  cosmosClient = new CosmosClient(accountURL, accountKey);

Just created a test ToDoItems and tested on emulator and device - fails on device

Thanks

Pete

**Comment by ealsur** [comment]
By Emulator I guess you mean Device Emulator and not the Cosmos DB Emulator.

On UserAgentContainer, we obtain device/OS information through NET Standard RuntimeInformation (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation?view=netframework-4.8). This is a NET Standard class, so should be implemented in all NET Standard 2.0 frameworks (otherwise you'd get a NotImplementedException).

It does look like the App, when deployed, does not have enough permissions to access that information.

**Comment by petevick** [comment]
Sorry - yes the device emulator.
It does appear to be a permissions issue - and can be reproduced very easily - or at least it can by me :)

**Comment by ealsur** [comment]
Are you requesting permissions on the device? I am not familiar with Xamarin specifics, but it looks like you need to have a Permissions file that declares the required permissions. 
Also are there differences between the Emulator OS version and the Device OS version? Could it be that the App is targeting the Emulator OS version but when it differs on the Device it does not work?
