### ISSUE TITLE
What is Microsoft.Azure.Cosmos.Serialization.HybridRow and how to build v4 sources?

### ISSUE THREAD

**Issue by xperiandri** [Azure/azure-cosmos-dotnet-v3#1404]

**Comment by ealsur** [comment]
V4 can be built from any environment by cloning the V4 branch and building locally. As part as out CI and release pipeline we build it in random machines that get used on Azure DevOps.

Are you getting any errors while running `dotnet build` on a cloned repo?

**Comment by xperiandri** [comment]
Yes, `Microsoft.Azure.Cosmos.Serialization.HybridRow` is not available in NuGet

**Comment by ealsur** [comment]
Are you building with `dotnet build` or from Visual Studio? We all have this repo cloned in our personal machines to develop, and the process restores the HybridRow package just like it would do on any other machine. The repository contains a [Nuget.Config](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/NuGet.config) file also that defines the Nuget endpoints to use.

**Comment by ealsur** [comment]
Please make sure that you are building with the Nuget.config file present in the repository. Reopen in case this isn't working.

**Comment by xperiandri** [comment]
Yes, I've just added the project as a source to a project in another folder. That is why MyGet source was not used in my setup.
