### ISSUE TITLE
Client Encryption & SDK contracts

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1406]
The goal of this issue is track a plan to remove all Client Encryption dependencies from the CosmosClient.

Why is this important?
1. Most users won't use Client Encryption. Adding additional properties, contracts, and other resources unnecessarily increase the API surface area for customers.
2. It allows Client Encryption to have major version bumps without forcing the SDK to also increase.\
3. It will allow users to independently increase the versions. The user doesn't have to wait for a new Client Encryption release to get the latest SDK.
4. It will make it clear if the user is using encryption. Having a flag in the SDK makes it easy to miss during investigation, and encryption adds a lot of complex scenarios that can result in unexpected behavior.

Draft Design:
Have a custom item request option.

```C#
namespace Microsoft.Azure.Cosmos
public abstract class CosmosStreamTransformer
{
     public abstract ValueTask<Stream> RequestItemStreamTransformerAsync(
          Stream stream);

     public abstract ValueTask<Stream> ResponseItemStreamTransformerAsync(
           Stream stream);
}
```

```C#
namespace Microsoft.Azure.Cosmos
public class CosmosItemRequestOptions
{
     public CosmosStreamTransformer StreamTransformer {get; set;}
     ...
}
```

```C#
namespace Microsoft.Azure.Cosmos.Encryption
public class  EncryptionStreamer : CosmosStreamTransformer
{
    public EncryptionStreamer(
        Encryptor encryptor,
        EncryptionOptions encryptionOptions,
        Action<Stream> encryptionFailure){

    }
    public override ValueTask<Stream> RequestItemStreamTransformerAsync(
          Stream stream)
    {
          
    }

     public override ValueTask<Stream> ResponseItemStreamTransformerAsync(
           Stream stream)
    {

    }
}
```

// Example of the API
```C#
public async  Task<T>  CreateEncryptedItem<T>(
    T item,
    Container container,
    Encryptor encryptor)
{
    byte[] failedEncryptionPayload = null;
    Action<byte[]> error = (payload) => failedEncryptionPayload = payload;

    ItemRequestOptions requestOptions = new ItemRequestOptions()
    {
        StreamTransformer = new EncryptionStreamer(encryptor, error );
    }

    ItemResponse<T> itemResponse = await container.CreateItemAsync<T>(item, requestOptions);
    if(failedEncryptionPayload != null){
         log.Failure(failedEncryptionPayload);
    }
}
```

**Comment by kirankumarkolli** [comment]
EncryptionStreamer  will be part of Encryption library.
Also EncryptionStreamer  might need instantiation with encryption context/EncryptionOptions.

**Comment by kirankumarkolli** [comment]
One more alternative discussed was 

SDK package: 
```C#
CosmosClient
{
   public CosmosClientOptions { get; }
}

CosmosClientOptions 
{
   public CosmosSerailzier Serializer { get; }
}
```

Encryption Package: 

```C#
EncryptionItemOptions : ItemRequestOptions 
{
  ....
  
  EncryptionOptions options { get; set;}
}


class EncryptedContainer : Container
{
   public EncryptedContainer(
		Container c) 
   {
		// TWO possibilites
		// 1. Equicalnet of Copy CTOR for composition
		// 2. ExtensionMethod on Database (from Encryption Package)
   }

   override CreateItem<T>(...) 
   {
		if (requestOptions is EncryptionItemOptions) 
		{
			// Prepare stream payload
			// 1. Type<T> -> Stream: Serialization abstraction
			// 2. Encrypt stream
			//
			// NOTE: PK extraction: NotImplemented ??
		}
		
		ResponseMessage message = c.CreateItemStream();
		
		// Decrypt response message, might be no-op with MinimalResponse s opted for
		return message;
   }
   
   override CreateItemStream(...)
   {
   }
}


Container c = db.GetContainer(...); 
Container real = new EncryptedContainer(c);

real.CreateItem<Conversation>();


EncryptionItemOptions options = new ...;
options.IfMatch = ;
options.EncryptionOptions = new EncryptionOptions()
{
   ...
};

Container c = db.GetEncryptedContainer(...); 
```

Two open items
1. **Decrypt response message, might be no-op with MinimalResponse s opted for**
    @j82w, @ealsur , @FabianMeiswinkel thoughts on making this contract pulic (of-course with generic serializer)

2. CosmosElement leverage: For now encryption package will start without it and later when needed will explore file-sharing (bigger surface area) or explore other options.

3. Certain query code paths might result in extra serialization/de-serialization over-head. Deferring for now.

/cc: @moderakh (for java reference)

**Comment by ealsur** [comment]
Regarding point 2. If there is code sharing in place, on two independent packages, it is bound to cause runtime errors at some point when the user updates one package but not the other (this happened in the past with Bulk Executor early versions).
