### ISSUE TITLE
Query Diagnostic improvements

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1418]
1. Add correlation activity id.
2. Add total execution time to query page diagnostics
3. Buffered pages
4. Have some way to note parallel calls

**Comment by balaksms** [comment]
Please change all duration in millisecond instead of timespan

**Comment by balaksms** [comment]
Please add tag for any remote region calls

**Comment by balaksms** [comment]
can we add some metric to capture scheduling delay the task  posted by the sdk on the client
