### ISSUE TITLE
Refactor code to decouple encryption logic from SDK client 

### ISSUE THREAD

**Issue by anujtoshniwal** [Azure/azure-cosmos-dotnet-v3#1427]
At this point all the encryption and decryption seems to happen outside of the core SDK logic since it's encrypting the document before write and decrypting after read. We can instead have an EncryptedContainer class that composes / wraps Container and just wraps all the methods appropriately so that core SDK logic will not need to know about encryption.

The EncryptedContainer is just an internal implementation class that is never directly exposed to users. All the encryption logic is completely external to the SDK. It's just like if an external users created the package.

public sealed class EncryptionDatabaseCore : Database
{
   private Database database;
    public override Container GetContainer(string id){ return new EncryptionContainerCore();}
 }

public sealed class EncryptionContainerCore : Container
{ 
    private Container container;
    public override ItemResponse<T> CreateItemAsync<T>(){}
   .....
}

**Comment by j82w** [comment]
@anujtoshniwal this is a duplicate of the existing [issue](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1406)

**Comment by anujtoshniwal** [comment]
Decided to go ahead with a different proposal.
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1406
