### ISSUE TITLE
ToQueryDefinition() throws ArgumentNullException on LINQ query without Where clause

### ISSUE THREAD

**Issue by matthewhancock** [Azure/azure-cosmos-dotnet-v3#1438]
**Describe the bug**
Calling `.ToQueryDefinition()` throws an `ArgumentNullException` with message `Value cannot be null. (Parameter 'sqlQuery')` if a Where clause hasn't been added to the LINQ query.

The string representation of the IOrderedQueryable is the url path to the Container.
![image](https://user-images.githubusercontent.com/6509921/80403904-3df15a00-8875-11ea-9cea-25544fb5125e.png)

If I set a dummy lambda (`.Where(q => true)`) the query works.
![image](https://user-images.githubusercontent.com/6509921/80404093-8446b900-8875-11ea-9f45-50ce360ecacd.png)

**To Reproduce**
```
new CosmosClient("...connection string here...")
    .GetDatabase("AAA")
    .GetContainer("BBB")
    .GetItemLinqQueryable<Test>()
    .ToQueryDefinition();
```

**Expected behavior**
The query will return the Items in the Container.

**Actual behavior**
An `ArgumentNullException` is thrown.

**Environment summary**
SDK Version: 3.6.0 and 3.8.0
OS Version: Windows 10, Visual Studio Professional 2019 16.5.3

**Additional context**
Was previously reported and closed as Resolved: #719

**Comment by alveflo** [comment]
Any workaround for this issue?

**Comment by V4A001** [comment]
I have the same issue I believe. Ethical hackers are concerned about "SELECT * from ".. stuff and LINQ takes care of proper formatting. For that reason (and strong typed) I prefer linq. However, I run in similar issue when trying next:

`public async Task<Company> GetCompanyBycompanyNumberAsync(string companyNumber)
        {
            try
            {
                IOrderedQueryable<Company> queryable = this._container.GetItemLinqQueryable<Company>();
                queryable.Where(p => p.companyNumber == companyNumber);

                QueryDefinition queryDefinition = queryable.ToQueryDefinition();

                using (FeedIterator feedIterator = this._container.GetItemQueryStreamIterator(
                    queryDefinition,
                    null,
                    new QueryRequestOptions() { PartitionKey = new PartitionKey(Company.PartitionKeyPath) }))
                {
                    while (feedIterator.HasMoreResults)
                    {
                        using ResponseMessage responseMessage = await feedIterator.ReadNextAsync();
                        if (responseMessage.IsSuccessStatusCode)
                        {
                            var company = StreamExtensions.FromStream<Company>(responseMessage.Content);
                            return company;
                        }
                    }
                    return null;
                }
                throw new Exception("More than 1 record returned.");
                //var q = this._container.GetItemLinqQueryable<Company>();
                //var iterator = q.Where(p => p.companyNumber == companyNumber).ToFeedIterator();
                //// Can write raw SQL, but the iteration is a little annoying. 
                ////var iterator = this._container.GetItemQueryIterator<Company>($"SELECT * FROM c WHERE c.companyNumber = '{companyNumber}'");
                //while (iterator.HasMoreResults)
                //{
                //    foreach (var item in (await iterator.ReadNextAsync()).Resource)
                //    {
                //        company = item;
                //    }
                //}
                //return company;
            }
            catch (CosmosException ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                return null;
            }
        }`

For an ORM I would expect something easier to query on the index key like the PartitionKeyPath which for most developers is not the id to start with. Most likely a user, email or something know and entered by humans.

Help appreciated.

**Comment by Matthewsre** [comment]
I just hit this issue as well. Is there at least a way to easily check the IQueryable? I don't want to rely on try/catch for my logic on this.

**Comment by j82w** [comment]
@Matthewsre did you hit this running the latest 3.18.0 SDK?

**Comment by V4A001** [comment]
This isssue is still there with 3.20.0.0

If I add the where clause it works, but without it, it does not:

`                Company company = null;
                var queryable = this._container.GetItemLinqQueryable<Company>();
                    //.Where(q => true);
                queryable.Where(p => p.GLN== gln);

                QueryDefinition queryDefinition = queryable.ToQueryDefinition();`

**Comment by sourabh1007** [comment]
If you want to Select everything without any condition. Right way to do it is:

_this._container.GetItemLinqQueryable().Select(x => x)_

Pasting few links for your reference : 
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/select-clause
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.select?view=net-5.0

**Comment by j82w** [comment]
If doing the following causes a null ref it still needs to be fixed.

`this._container.GetItemLinqQueryable().ToQueryDefinition();`
