### ISSUE TITLE
Increase data, increase throughput needed

### ISSUE THREAD

**Issue by AntonioJDios** [Azure/azure-cosmos-dotnet-v3#1446]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I think this is not a bug, it is just cosmos works. However, I would like to get your input. We have a collection and we insert materialized views each days. (thusends of documents). However, each sometimes appears new physicall partitions because we have a lot data. Then the TH provisioned for each partition decreased as <<documentation says>>. So I need to increase the throughput for that collection. 

**To Reproduce**
Insert a lot data into a collection.

**Expected behavior**
What I would like is to keep the same throughput over the time in the collection. If this is not possible  I guess an   archive strategy to save old documents which are cold would be great.

thanks

**Comment by markjbrown** [comment]
Hi Antonio. This growing RU/s is a function of [minimum RU/GB](https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits). Currently in Cosmos this is 1GB for 10 RU/s. If you are ingesting large amounts of data and do not need to keep it using TTL will keep your RU/s at a constant rate.

Hope that helps.

thanks.

**Comment by AntonioJDios** [comment]
Thanks, it was what I thought. Please, you can close this:)
