### ISSUE TITLE
The same queries some time do reattemp

### ISSUE THREAD

**Issue by AntonioJDios** [Azure/azure-cosmos-dotnet-v3#1452]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I am doing one queries to get the data from Cosmos doing the calls from postman. The RU is 20 RU for that query. Sometimes the query take more times and it shows this result:

DocDBTrace Warning: 0 : Operation will be retried after 6815 milliseconds. Current attempt 1, Cumulative delay 00:00:06.8150000
No body is using the database and it happens frequently. 
**To Reproduce**
Just doing a query with some filtering and just to a partition key.

**Expected behavior**
Always take the same time and it shouldn't do reattemp.

**Actual behavior**
Do reattemp in 20 % of cases

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
Can you please attach the` FeedResponse.Diagnostics.ToString()`?

**Comment by ealsur** [comment]
Also, have you checked the account metrics for 429s during that period?

**Comment by AntonioJDios** [comment]
Hi. I will add the diagnostic. I would like to explain. I have a query
first to get the total number of documents which is a bit low than de th
per partitions. Then a second query which is just 20RU.  Always run both
together and sometimes the second get 429. But not alwats. Could it be
because sometimes they run very fast both? And other times the code between
then is slower?

Next monday I will be able to add more info. Thanks

**Comment by AntonioJDios** [comment]
{"Summary":{"StartUtc":"2020-05-04T08:55:50.7752481Z","ElapsedTime":"00:00:01.9364472","UserAgent":"cosmos-netstandard-sdk/3.6.0|3.4.2|20324|X64|Microsoft Windows 10.0.17134 |.NET Core 4.6.27110.04|"},"Context":[{"Id":"QueryReadNextAsync","ElapsedTime":"00:00:01.9381292"},{"PKRangeId":"14","QueryMetric":"totalExecutionTimeInMs=28.12;queryCompileTimeInMs=0.22;queryLogicalPlanBuildTimeInMs=0.09;queryPhysicalPlanBuildTimeInMs=0.18;queryOptimizationTimeInMs=0.02;VMExecutionTimeInMs=27.38;indexLookupTimeInMs=27.35;documentLoadTimeInMs=0.00;systemFunctionExecuteTimeInMs=0.00;userFunctionExecuteTimeInMs=0.00;retrievedDocumentCount=0;retrievedDocumentSize=0;outputDocumentCount=1;outputDocumentSize=64;writeOutputTimeInMs=0.00;indexUtilizationRatio=1.00","IndexUtilization":"","SchedulingTimeSpan":{"TurnaroundTimeInMs":"1936.5079","ResponseTimeInMs":"0.0239","RunTimeInMs":"1936.4818","WaitTimeInMs":"0.0261","NumberOfPreemptions":"1"},"Context":[{"Id":"RequestInvokerHandler","ElapsedTime":"00:00:01.9364472"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","ElapsedTime":"00:00:01.9363873"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","ElapsedTime":"00:00:00.0966725"},{"Id":"TransportHandler","ElapsedTime":"00:00:00.0966433"},{"Id":"PointOperationStatistics","ActivityId":"b2aeabb1-7073-4c26-ae3b-34c07a46d1ca","StatusCode":429,"SubStatusCode":3200,"RequestCharge":0.38,"RequestUri":"dbs/heatloss/colls/meter_details_materialized_view","RequestSessionToken":null,"ResponseSessionToken":"0:-1#10120379","ClientRequestStats":{"RequestStartTimeUtc":"2020-05-04T08:55:50.7766444Z","RequestEndTimeUtc":"2020-05-04T08:55:52.7126040Z","RequestLatency":"00:00:01.9359596","IsCpuOverloaded":false,"NumberRegionsAttempted":1,"ResponseStatisticsList":[{"ResponseTime":"2020-05-04T08:55:50.8724913Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14056/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327616733587026s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: , IsValid: True, StatusCode: 429, SubStatusCode: 3200, RequestCharge: 0.38, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"},{"ResponseTime":"2020-05-04T08:55:52.712604Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: 14, IsValid: True, StatusCode: 200, SubStatusCode: 0, RequestCharge: 288.21, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"}],"AddressResolutionStatistics":[],"SupplementalResponseStatistics":[],"FailedReplicas":[],"RegionsContacted":["https://cos-dev-analytics-westeurope.documents.azure.com:443/"],"ContactedReplicas":["rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14056/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327616733587026s/","rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/"]}},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","ElapsedTime":"00:00:00.1402044"},{"Id":"TransportHandler","ElapsedTime":"00:00:00.1401878"},{"Id":"PointOperationStatistics","ActivityId":"0a21b0bc-05f0-4da9-9d00-01034769b463","StatusCode":200,"SubStatusCode":0,"RequestCharge":288.59,"RequestUri":"dbs/heatloss/colls/meter_details_materialized_view","RequestSessionToken":null,"ResponseSessionToken":"14:-1#10120379","ClientRequestStats":{"RequestStartTimeUtc":"2020-05-04T08:55:50.7766444Z","RequestEndTimeUtc":"2020-05-04T08:55:52.7126040Z","RequestLatency":"00:00:01.9359596","IsCpuOverloaded":false,"NumberRegionsAttempted":1,"ResponseStatisticsList":[{"ResponseTime":"2020-05-04T08:55:50.8724913Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14056/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327616733587026s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: , IsValid: True, StatusCode: 429, SubStatusCode: 3200, RequestCharge: 0.38, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"},{"ResponseTime":"2020-05-04T08:55:52.712604Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: 14, IsValid: True, StatusCode: 200, SubStatusCode: 0, RequestCharge: 288.21, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"}],"AddressResolutionStatistics":[],"SupplementalResponseStatistics":[],"FailedReplicas":[],"RegionsContacted":["https://cos-dev-analytics-westeurope.documents.azure.com:443/"],"ContactedReplicas":["rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14056/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327616733587026s/","rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/"]}}]}]}

DocDBTrace Warning: 0 : Operation will be retried after 6764 milliseconds. Current attempt 1, Cumulative delay 00:00:06.7640000




{"Summary":{"StartUtc":"2020-05-04T08:55:52.7224367Z","ElapsedTime":"00:00:07.0004326","UserAgent":"cosmos-netstandard-sdk/3.6.0|3.4.2|20324|X64|Microsoft Windows 10.0.17134 |.NET Core 4.6.27110.04|"},"Context":[{"Id":"QueryReadNextAsync","ElapsedTime":"00:00:07.1091879"},{"PKRangeId":"14","QueryMetric":"totalExecutionTimeInMs=3.65;queryCompileTimeInMs=0.21;queryLogicalPlanBuildTimeInMs=0.13;queryPhysicalPlanBuildTimeInMs=0.13;queryOptimizationTimeInMs=0.02;VMExecutionTimeInMs=2.65;indexLookupTimeInMs=2.20;documentLoadTimeInMs=0.18;systemFunctionExecuteTimeInMs=0.00;userFunctionExecuteTimeInMs=0.00;retrievedDocumentCount=20;retrievedDocumentSize=12494;outputDocumentCount=20;outputDocumentSize=14063;writeOutputTimeInMs=0.02;indexUtilizationRatio=1.00","IndexUtilization":"","SchedulingTimeSpan":{"TurnaroundTimeInMs":"7104.5397","ResponseTimeInMs":"0.0088","RunTimeInMs":"7103.9692","WaitTimeInMs":"0.5709","NumberOfPreemptions":"2"},"Context":[{"Id":"RequestInvokerHandler","ElapsedTime":"00:00:07.0004326"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","ElapsedTime":"00:00:07.0003780"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","ElapsedTime":"00:00:00.1014276"},{"Id":"TransportHandler","ElapsedTime":"00:00:00.1014212"},{"Id":"PointOperationStatistics","ActivityId":"2836f267-a567-4233-b62a-eda86b332ac8","StatusCode":429,"SubStatusCode":3200,"RequestCharge":0.38,"RequestUri":"dbs/heatloss/colls/meter_details_materialized_view","RequestSessionToken":null,"ResponseSessionToken":"0:-1#10120379","ClientRequestStats":{"RequestStartTimeUtc":"2020-05-04T08:55:52.8275556Z","RequestEndTimeUtc":"2020-05-04T08:55:59.8274932Z","RequestLatency":"00:00:06.9999376","IsCpuOverloaded":false,"NumberRegionsAttempted":1,"ResponseStatisticsList":[{"ResponseTime":"2020-05-04T08:55:52.9288485Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: , IsValid: True, StatusCode: 429, SubStatusCode: 3200, RequestCharge: 0.38, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"},{"ResponseTime":"2020-05-04T08:55:59.8274932Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: 14, IsValid: True, StatusCode: 200, SubStatusCode: 0, RequestCharge: 12.42, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"}],"AddressResolutionStatistics":[],"SupplementalResponseStatistics":[],"FailedReplicas":[],"RegionsContacted":["https://cos-dev-analytics-westeurope.documents.azure.com:443/"],"ContactedReplicas":["rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/","rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/"]}},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","ElapsedTime":"00:00:00.1257320"},{"Id":"TransportHandler","ElapsedTime":"00:00:00.1257158"},{"Id":"PointOperationStatistics","ActivityId":"dbb257c3-d520-4241-a4f4-9ab32ed51276","StatusCode":200,"SubStatusCode":0,"RequestCharge":12.8,"RequestUri":"dbs/heatloss/colls/meter_details_materialized_view","RequestSessionToken":null,"ResponseSessionToken":"14:-1#10120379","ClientRequestStats":{"RequestStartTimeUtc":"2020-05-04T08:55:52.8275556Z","RequestEndTimeUtc":"2020-05-04T08:55:59.8274932Z","RequestLatency":"00:00:06.9999376","IsCpuOverloaded":false,"NumberRegionsAttempted":1,"ResponseStatisticsList":[{"ResponseTime":"2020-05-04T08:55:52.9288485Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: , IsValid: True, StatusCode: 429, SubStatusCode: 3200, RequestCharge: 0.38, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"},{"ResponseTime":"2020-05-04T08:55:59.8274932Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: 14, IsValid: True, StatusCode: 200, SubStatusCode: 0, RequestCharge: 12.42, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"}],"AddressResolutionStatistics":[],"SupplementalResponseStatistics":[],"FailedReplicas":[],"RegionsContacted":["https://cos-dev-analytics-westeurope.documents.azure.com:443/"],"ContactedReplicas":["rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/","rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/"]}}]},{"PKRangeId":"14","QueryMetric":"totalExecutionTimeInMs=3.12;queryCompileTimeInMs=0.22;queryLogicalPlanBuildTimeInMs=0.13;queryPhysicalPlanBuildTimeInMs=0.18;queryOptimizationTimeInMs=0.02;VMExecutionTimeInMs=2.18;indexLookupTimeInMs=1.73;documentLoadTimeInMs=0.24;systemFunctionExecuteTimeInMs=0.00;userFunctionExecuteTimeInMs=0.00;retrievedDocumentCount=20;retrievedDocumentSize=12438;outputDocumentCount=20;outputDocumentSize=13997;writeOutputTimeInMs=0.02;indexUtilizationRatio=1.00","IndexUtilization":"","SchedulingTimeSpan":{"TurnaroundTimeInMs":"103.5182","ResponseTimeInMs":"0.0088","RunTimeInMs":"103.5087","WaitTimeInMs":"0.0099","NumberOfPreemptions":"1"},"Context":[{"Id":"RequestInvokerHandler","ElapsedTime":"00:00:00.1034780"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","ElapsedTime":"00:00:00.1034325"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","ElapsedTime":"00:00:00.1034096"},{"Id":"TransportHandler","ElapsedTime":"00:00:00.1034029"},{"Id":"PointOperationStatistics","ActivityId":"a5a10f4a-312c-423e-ba00-a0dc7987d9d4","StatusCode":200,"SubStatusCode":0,"RequestCharge":8.029,"RequestUri":"dbs/heatloss/colls/meter_details_materialized_view","RequestSessionToken":null,"ResponseSessionToken":"14:-1#10120379","ClientRequestStats":{"RequestStartTimeUtc":"2020-05-04T08:55:52.7235097Z","RequestEndTimeUtc":"2020-05-04T08:55:52.8267513Z","RequestLatency":"00:00:00.1032416","IsCpuOverloaded":false,"NumberRegionsAttempted":1,"ResponseStatisticsList":[{"ResponseTime":"2020-05-04T08:55:52.8267513Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14056/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327616733587026s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: 14, IsValid: True, StatusCode: 200, SubStatusCode: 0, RequestCharge: 8.03, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"}],"AddressResolutionStatistics":[],"SupplementalResponseStatistics":[],"FailedReplicas":[],"RegionsContacted":["https://cos-dev-analytics-westeurope.documents.azure.com:443/"],"ContactedReplicas":["rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14056/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327616733587026s/"]}}]}]}Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.b601d58cb4e646ad9aee518478ed6443.RemoteDependency","time":"2020-05-04T08:55:52.7201419Z","iKey":"b601d58c-b4e6-46ad-9aee-518478ed6443","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.role":"fabric:/HeatStaticDataServiceSF/HeatStaticDataService.WebApi","ai.cloud.roleInstance":"132330558659121016","ai.operation.id":"64c9c3404dbcf3418cbd433101415b11","ai.operation.parentId":"|64c9c3404dbcf3418cbd433101415b11.f51ef8a3_1.aa06684b_","ai.operation.name":"GET MeterDetails/GetListMaterializedView","ai.location.ip":"172.20.192.132","ai.internal.sdkVersion":"dotnet:2.9.1-26108","ai.internal.nodeName":"ES-ADG-HP850G4"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"Get From Cosmos MeterDetailsDocuments","id":"zJ7WTT3SbZg=","duration":"00:00:07.1362347","success":true,"type":"Cosmos Repository","properties":{"_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","ServiceFabric.ApplicationName":"fabric:/HeatStaticDataServiceSF","ServiceFabric.NodeName":"_Node_0","ServiceFabric.ApplicationTypeName":"HeatStaticDataServiceSFType","ServiceFabric.InstanceId":"132330558659121016","ServiceFabric.PartitionId":"816a65bf-22b4-4649-a458-bbb71a46f12b","ServiceFabric.ServiceName":"fabric:/HeatStaticDataServiceSF/HeatStaticDataService.WebApi","AspNetCoreEnvironment":"Development","DeveloperMode":"true","X-Correlation-Id":"80000006-0002-f600-b63f-84710c7967bb","ServiceFabric.ServiceTypeName":"HeatStaticDataService.WebApiType"}}}}

**Comment by AntonioJDios** [comment]
I added the diagnostics when I get the 429 and it slow.. when it is fast I will add in the next post.

**Comment by AntonioJDios** [comment]
{"Summary":{"StartUtc":"2020-05-04T09:03:15.4440539Z","ElapsedTime":"00:00:00.1989827","UserAgent":"cosmos-netstandard-sdk/3.6.0|3.4.2|20324|X64|Microsoft Windows 10.0.17134 |.NET Core 4.6.27110.04|"},"Context":[{"Id":"QueryReadNextAsync","ElapsedTime":"00:00:00.2007560"},{"PKRangeId":"14","QueryMetric":"totalExecutionTimeInMs=28.51;queryCompileTimeInMs=0.21;queryLogicalPlanBuildTimeInMs=0.13;queryPhysicalPlanBuildTimeInMs=0.15;queryOptimizationTimeInMs=0.03;VMExecutionTimeInMs=27.72;indexLookupTimeInMs=27.67;documentLoadTimeInMs=0.00;systemFunctionExecuteTimeInMs=0.00;userFunctionExecuteTimeInMs=0.00;retrievedDocumentCount=0;retrievedDocumentSize=0;outputDocumentCount=1;outputDocumentSize=64;writeOutputTimeInMs=0.00;indexUtilizationRatio=1.00","IndexUtilization":"","SchedulingTimeSpan":{"TurnaroundTimeInMs":"199.0564","ResponseTimeInMs":"0.0331","RunTimeInMs":"199.0159","WaitTimeInMs":"0.0409","NumberOfPreemptions":"1"},"Context":[{"Id":"RequestInvokerHandler","ElapsedTime":"00:00:00.1989827"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","ElapsedTime":"00:00:00.1988706"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","ElapsedTime":"00:00:00.1988300"},{"Id":"TransportHandler","ElapsedTime":"00:00:00.1988226"},{"Id":"PointOperationStatistics","ActivityId":"948cd5f9-847f-49ea-8b14-b26376bbc9d5","StatusCode":200,"SubStatusCode":0,"RequestCharge":288.21,"RequestUri":"dbs/heatloss/colls/meter_details_materialized_view","RequestSessionToken":null,"ResponseSessionToken":"14:-1#10120379","ClientRequestStats":{"RequestStartTimeUtc":"2020-05-04T09:03:15.4456847Z","RequestEndTimeUtc":"2020-05-04T09:03:15.6443375Z","RequestLatency":"00:00:00.1986528","IsCpuOverloaded":false,"NumberRegionsAttempted":1,"ResponseStatisticsList":[{"ResponseTime":"2020-05-04T09:03:15.6443375Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14348/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327903779704449s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: 14, IsValid: True, StatusCode: 200, SubStatusCode: 0, RequestCharge: 288.21, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"}],"AddressResolutionStatistics":[],"SupplementalResponseStatistics":[],"FailedReplicas":[],"RegionsContacted":["https://cos-dev-analytics-westeurope.documents.azure.com:443/"],"ContactedReplicas":["rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14348/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327903779704449s/"]}}]}]}


{"Summary":{"StartUtc":"2020-05-04T09:03:15.6480568Z","ElapsedTime":"00:00:00.1837448","UserAgent":"cosmos-netstandard-sdk/3.6.0|3.4.2|20324|X64|Microsoft Windows 10.0.17134 |.NET Core 4.6.27110.04|"},"Context":[{"Id":"QueryReadNextAsync","ElapsedTime":"00:00:00.3612536"},{"PKRangeId":"14","QueryMetric":"totalExecutionTimeInMs=3.15;queryCompileTimeInMs=0.21;queryLogicalPlanBuildTimeInMs=0.11;queryPhysicalPlanBuildTimeInMs=0.13;queryOptimizationTimeInMs=0.02;VMExecutionTimeInMs=2.36;indexLookupTimeInMs=1.94;documentLoadTimeInMs=0.19;systemFunctionExecuteTimeInMs=0.00;userFunctionExecuteTimeInMs=0.00;retrievedDocumentCount=20;retrievedDocumentSize=12494;outputDocumentCount=20;outputDocumentSize=14063;writeOutputTimeInMs=0.02;indexUtilizationRatio=1.00","IndexUtilization":"","SchedulingTimeSpan":{"TurnaroundTimeInMs":"359.9595","ResponseTimeInMs":"0.0081","RunTimeInMs":"358.9771","WaitTimeInMs":"0.9824","NumberOfPreemptions":"2"},"Context":[{"Id":"RequestInvokerHandler","ElapsedTime":"00:00:00.1837448"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","ElapsedTime":"00:00:00.1837063"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","ElapsedTime":"00:00:00.1836823"},{"Id":"TransportHandler","ElapsedTime":"00:00:00.1836735"},{"Id":"PointOperationStatistics","ActivityId":"b9741beb-08c9-4630-9ec2-907f8139b1d7","StatusCode":200,"SubStatusCode":0,"RequestCharge":12.42,"RequestUri":"dbs/heatloss/colls/meter_details_materialized_view","RequestSessionToken":null,"ResponseSessionToken":"14:-1#10120379","ClientRequestStats":{"RequestStartTimeUtc":"2020-05-04T09:03:15.8250751Z","RequestEndTimeUtc":"2020-05-04T09:03:16.0085061Z","RequestLatency":"00:00:00.1834310","IsCpuOverloaded":false,"NumberRegionsAttempted":1,"ResponseStatisticsList":[{"ResponseTime":"2020-05-04T09:03:16.0085061Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14373/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132302260259481444p/, LSN: 10120379, GlobalCommittedLsn: 10120379, PartitionKeyRangeId: 14, IsValid: True, StatusCode: 200, SubStatusCode: 0, RequestCharge: 12.42, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"}],"AddressResolutionStatistics":[],"SupplementalResponseStatistics":[],"FailedReplicas":[],"RegionsContacted":["https://cos-dev-analytics-westeurope.documents.azure.com:443/"],"ContactedReplicas":["rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14373/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132302260259481444p/"]}}]},{"PKRangeId":"14","QueryMetric":"totalExecutionTimeInMs=3.14;queryCompileTimeInMs=0.32;queryLogicalPlanBuildTimeInMs=0.12;queryPhysicalPlanBuildTimeInMs=0.13;queryOptimizationTimeInMs=0.02;VMExecutionTimeInMs=2.23;indexLookupTimeInMs=1.78;documentLoadTimeInMs=0.20;systemFunctionExecuteTimeInMs=0.00;userFunctionExecuteTimeInMs=0.00;retrievedDocumentCount=20;retrievedDocumentSize=12438;outputDocumentCount=20;outputDocumentSize=13997;writeOutputTimeInMs=0.02;indexUtilizationRatio=1.00","IndexUtilization":"","SchedulingTimeSpan":{"TurnaroundTimeInMs":"175.2114","ResponseTimeInMs":"0.0081","RunTimeInMs":"175.2016","WaitTimeInMs":"0.0098","NumberOfPreemptions":"1"},"Context":[{"Id":"RequestInvokerHandler","ElapsedTime":"00:00:00.1751681"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","ElapsedTime":"00:00:00.1751219"},{"Id":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","ElapsedTime":"00:00:00.1750718"},{"Id":"TransportHandler","ElapsedTime":"00:00:00.1750605"},{"Id":"PointOperationStatistics","ActivityId":"0f00a46d-8f91-4af0-abe6-09da98b6d8d4","StatusCode":200,"SubStatusCode":0,"RequestCharge":8.029,"RequestUri":"dbs/heatloss/colls/meter_details_materialized_view","RequestSessionToken":null,"ResponseSessionToken":"14:-1#10120379","ClientRequestStats":{"RequestStartTimeUtc":"2020-05-04T09:03:15.6488925Z","RequestEndTimeUtc":"2020-05-04T09:03:15.8237070Z","RequestLatency":"00:00:00.1748145","IsCpuOverloaded":false,"NumberRegionsAttempted":1,"ResponseStatisticsList":[{"ResponseTime":"2020-05-04T09:03:15.823707Z","ResourceType":2,"OperationType":15,"StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/, LSN: 10120379, GlobalCommittedLsn: 10120378, PartitionKeyRangeId: 14, IsValid: True, StatusCode: 200, SubStatusCode: 0, RequestCharge: 8.03, ItemLSN: -1, SessionToken: -1#10120379, UsingLocalLSN: True, TransportException: null"}],"AddressResolutionStatistics":[],"SupplementalResponseStatistics":[],"FailedReplicas":[],"RegionsContacted":["https://cos-dev-analytics-westeurope.documents.azure.com:443/"],"ContactedReplicas":["rntbd://cdb-ms-prod-westeurope1-fd29.documents.azure.com:14031/apps/831506b7-9e96-439f-a272-9f861d902a00/services/88283c26-95f2-4019-9fd5-c3b44bf344b7/partitions/008a5f41-460f-4c0c-a74b-149734af5f8e/replicas/132327982488445935s/"]}}]}]}

**Comment by j82w** [comment]
Based on the diagnostics what is happening is the SDK is doing retries on 429s which it is designed to do. To avoid the 429s you can try [optimizing the queries](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance) or to increase the container throughput. I would suggest looking in the portal at the [monitoring page ](https://docs.microsoft.com/en-us/azure/cosmos-db/monitor-cosmos-db)to see how often you are hitting 429s
