### ISSUE TITLE
InvalidOperationException on reading diagnostics string representation

### ISSUE THREAD

**Issue by maxvasil** [Azure/azure-cosmos-dotnet-v3#1467]
**Describe the bug**
In my service I see rare occasional `System.InvalidOperationException` thrown on reading diagnostics string.

**To Reproduce**
The issue is intermittent, therefore there's no reliable way to reproduce it. Here are examples of code that can lead to that exception:
```c#
// Example #1
ItemResponse<T> response = await cosmosContainer
   .ReadItemAsync<T>(itemId, new PartitionKey(partitionKey), cancellationToken: cancellationToken)
   .ConfigureAwait(false);

response.Diagnostics.ToString();    // Could throw

// Example #2
FeedResponse<T> response = await cosmosContainer
   .GetChangeFeedIterator<T>(continuation, options)
   .ReadNextAsync(cancellationToken);

response.Diagnostics.ToString();    // Could throw
```
Stack trace for example №1:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.Azure.Cosmos.Diagnostics.CosmosDiagnosticsSerializerVisitor.Visit(CosmosDiagnosticsContext cosmosDiagnosticsContext)
   at Microsoft.Azure.Cosmos.Diagnostics.CosmosDiagnosticsInternal.ToString()
```

**Expected behavior**
Expected to receive diagnostic information string.

**Actual behavior**
Most of the time code returns diagnostic information string, but sometimes InvalidOperationException is thrown

**Environment summary**
SDK Version: 3.7.1-preview
OS Version (e.g. Windows, Linux, MacOSX): Microsoft Windows 10.0.17763 |.NET Framework 4.7.3610.0

**Comment by j82w** [comment]
Hi @maxvasil,

The only way this should be possible is if the response is still getting processed when calling the Diagnostics.ToString(). Any chance you can reproduce the error? Do you use any custom handlers?
 
For example 1 is the missing await just a copy paste mistake?

**Comment by maxvasil** [comment]
Hi @j82w, thanks for quick answer.

So far I didn't find the way to reproduce the issue.
Custom handlers are not used.

> For example 1 is the missing await just a copy paste mistake?
Thanks for notice, that is copy-paste mistake. I've fixed it in the issue description.

**Comment by j82w** [comment]
@maxvasil I haven't had any luck with reproducing the issue. Is there any chance that you can catch the exception and try logging the diagnostics again so we can see what is being added to the diagnostics after the response has returned?

**Comment by maxvasil** [comment]
@j82w, sure, I'll try to do that. Is there a chance that 2nd attempt to get diagnostic string representation will be successful?
