### ISSUE TITLE
Default serialization of DateTime is not sortable

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-cosmos-dotnet-v3#1468]
Cosmos docs here: https://docs.microsoft.com/en-us/azure/cosmos-db/working-with-dates

^-- These basically say "use `YYYY-MM-DDThh:mm:ss.fffffffZ`".  Agreed!

System.Text.Json docs here: https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#the-extended-iso-8601-12019-profile-in-systemtextjson

^-- These say truncating zeroes are removed (right near the end of the doc)

When a DateTime is serialized, by default we get data like:

```
    "2020-05-02T18:42:34.978759Z",
    "2020-05-02T18:42:34.9727703Z",
    "2020-05-02T18:39:11.4884521Z",
    "2020-05-02T18:31:04.6478698Z",
    "2020-05-02T18:30:27.319531Z",   <-- 6 decimals
    "2020-05-02T18:23:11.1584903Z",
```

These are not sortable because of the differing number of decimal places:
```
"2020-05-02T18:30:27.3195309Z"
"2020-05-02T18:30:27.319531Z"   <-- this would come last, which is wrong
"2020-05-02T18:30:27.3195311Z"
```

The solution seems to be to create and use a custom converter to always use `YYYY-MM-DDThh:mm:ss.fffffffZ` format in Cosmos.

But the defaults seem like a bit of a subtle trap for users.  I don't have an awesome fix in mind.  Maybe you guys do.  I just wanted to at least raise the issue.

**Comment by ealsur** [comment]
Which SDK version are you using?

**Comment by joshlang** [comment]
`3.9.0-preview` at the moment.

**Comment by ealsur** [comment]
The problem is with System.Text.Json default behavior with dates then? 3.9.0 still uses Newtonsoft.Json though.

**Comment by joshlang** [comment]
My apologies for lack of clarity - Yes, we are using System.Text.Json for all serialization.  We use the Streaming API (`ReadItemStreamAsync`, `CreateItemStreamAsync`, etc)

**Comment by joshlang** [comment]
And I don't mean to imply there's a problem with System.Text.Json OR with this Cosmos SDK.  Both are great.  There's just a bit of a gotcha that I thought should be mentioned.

**Comment by ealsur** [comment]
It's a fair point, I was just trying to understand the scenario 😄 
I would certainly raise this on the System.Text.Json repo. Maybe this helps? https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#specify-date-format

**Comment by joshlang** [comment]
I'm not too sure that it would be well-received in the `System.Text.Json` repo, especially since they're probably concerned more about precision & efficiency as opposed to sortability for a particular use case, even if it *is* cosmos.

I'll consider it though after thinking through some more options.

For our scenario ourselves, we already have a workaround (via a converter), so we're in good shape.

**Comment by gdalsnes** [comment]
I have the same problem with SDK v2 and Newtonsoft Json. Both Newtonsoft and System.Text.Json remove trailing zeroes as default, making it unusable for CosmosDB (even if the docs says "it just works out of the box") https://docs.microsoft.com/en-us/azure/cosmos-db/working-with-dates 
Everything below "Most applications can use the default string representation for DateTime" is simply not true.

**Comment by onionhammer** [comment]
Looks like Cosmos can't handle ISO 8601-1:2019 which system text json serializes to.. so in order to serialize it you should strip out the timezone info from datetimeoffsets (boo) and store as UTC ala `myDateTimeOffset.UtcDateTime` 

This is a massive pain in the ass. Will this be fixed on the cosmos side at some point?

**Comment by Matthewsre** [comment]
For some reason I started having issues with this today when I have never had issues in the past.

Cosmos SDK is storing my model with the time like this:

```
{
	...
	"time": "2021-07-13T19:00:00Z",
	...
}
```

But the query from the SDK is being generated like this:

```
SELECT VALUE root FROM root WHERE ((root["time"] >= "2021-07-13T19:00:00") AND (root["time"] <= "2021-07-13T19:00:00"))
```

That query returns ZERO results when there are 3 objects saved that have **"time": "2021-07-13T19:00:00Z"**.

This has been very frustrating to deal with and it used to work before. Did something happen with how CosmosDB processes these queries?

**Comment by joshlang** [comment]
abandoning
