### ISSUE TITLE
Diagnostics to use Trace Event format

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1474]
# Description
To improve the diagnostics experience and troubleshooting the events will be converted to use the [chrome Trace Event](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.xqopa5m0e28f) format. 

## Reasons
1. This will allow the diagnostics to be viewed in [speedscope](https://github.com/jlfwong/speedscope). This will greatly help users and engineers diagnosis issues by being able to easily see where the time is being spent. 
2. This sets the SDK to use a well known format that other tools can possibly use.
3. Java and other SDKs can also follow the well defined standard so all SDKs have the same diagnostics format. 
3. The format provides better flexibility then the current design. No need to reinvent the wheel.

JSON will still contain a summary and a property for the TraceEvents. This will make it easier at first glance to get critical information.

Use the speedscope [samples ](https://github.com/jlfwong/speedscope/tree/master/sample/profiles/trace-event) to see working trace-events in the speedscope app.
```json
{
"Version": 3,
"Summary":{
   "UserAgent": "",
   "TotalElapsedTimeInMs":"",
   "StartUtc": "",
   "EstimatedSdkTimeInMs": "",
   "EstimatedNetworkingTimeInMs": ""
},
"TraceEvent":
[
        {"pid": 0, "tid": 0, "ph": "X", "name": "CreateItemAsync", "ts": 0, "dur":1100, "args": {"Summary":{ "UserAgent":".NETSDK"}}},
        {"pid": 0, "tid": 0, "ph": "X", "name": "ItemEncryption", "ts": 10, "dur":20},
        {"pid": 0, "tid": 0, "ph": "X", "name": "PkExtraction", "ts": 40, "dur":10},
        {"pid": 0, "tid": 0, "ph": "X", "name": "RequestHandler", "ts": 100, "dur": 950},
        {"pid": 0, "tid": 0, "ph": "X", "name": "GatewayStore", "ts": 150, "dur": 400, "args": {"detail": "429"}},
        {"pid": 0, "tid": 0, "ph": "X", "name": "RetryDelay", "ts": 600, "dur":100},
        {"pid": 0, "tid": 0, "ph": "X", "name": "GatewayStore", "ts": 750, "dur": 150, "args": {"detail": "200"}}
]
}
```

Rough example of how the speedscope app looks
![image](https://user-images.githubusercontent.com/8868107/81215905-e21e8380-8f8e-11ea-8eb6-80edd5775a8e.png)

**Comment by ealsur** [comment]
And we can even automate analysis for any support cases regarding the SDK

**Comment by j82w** [comment]
Speedscope can't currently handle async event and requires them to be put as a separate pid and/or tid. This makes it unusable for troubleshooting query and other async operations as it requires switching between multiple views.
