### ISSUE TITLE
Need client SDK to expose underlying feedIterator to make decryption work for ChangeFeed Processor

### ISSUE THREAD

**Issue by anujtoshniwal** [Azure/azure-cosmos-dotnet-v3#1484]
Need client SDK to expose underlying FeedIterator for ChangeFeed Processor. This can then be overriden in Encryption package to add decryption support.

**Comment by ealsur** [comment]
Could this be done by hooking something through the Change Feed Processor builder?

**Comment by anujtoshniwal** [comment]
Would need to be able to define the FeedIterator instance to be used through the Change Feed Processor builder.

**Comment by j82w** [comment]
What about taking a response factory into the builder?

**Comment by ealsur** [comment]
ChangeFeedProcessorOptions goes down all the way to the creation of the FeedIterator.
If we enable a new WithXXXXX() on the Builder, which sets a new ChangeFeedProcessorOptions property, then use that on the FeedIterator?

**Comment by anujtoshniwal** [comment]
Setting a new property on ChangeFeedProcessorOptions to use for FeedIterator creation might not help with decryption. We need a way to override the underlying FeedIterator and be able to use EncryptionFeedIterator (internal to Encryption package). Or else we can decrypt the response message from Change Feed Processor and use ResponseFactory to reconstruct the response to be sent as Jake suggested.

**Comment by kirankumarkolli** [comment]
Is this for PUSH iterator?

**Comment by ealsur** [comment]
Yes, this is the Push API.
Why not then pass a response factory?

**Comment by j82w** [comment]
We could also do a delegate to avoid requiring the entire response factory.

**Comment by ealsur** [comment]
Would a delegate exposing the Stream from the iterator work?

**Comment by anujtoshniwal** [comment]
Yes, a delegate exposing the response message stream would work. We can decrypt the stream and return the decrypted content.

**Comment by anujtoshniwal** [comment]
@ealsur ping on this.

**Comment by ealsur** [comment]
Sorry @anujtoshniwal what is the ping for? I thought this thread was to discuss options? Is there a need to implement this now? If so, which is the desired course?

**Comment by anujtoshniwal** [comment]
Right, we do need to implement this as well. 
Can we go the route of having a delegate exposing the response message stream, we can then decrypt the stream and return the decrypted content which can be used to construct the response and return to the client?

**Comment by j82w** [comment]
Can't we do composition on the ChangesHandler? Then change the type of the ChangeFeedProcessorBuilder to JObject. 

Something like this:
```c#
 ChangeFeedProcessor processor = this.Container
                .GetChangeFeedProcessorBuilder<JObject>("test", async (IReadOnlyCollection<JObject> docs, CancellationToken token) =>
                {
                    List<TestClass> decryptedDocs = new List<TestClass>();
                    foreach(var doc in docs)
                    {
                        // Do the async decrypt here
                        decryptedDocs.Add(doc.ToObject<TestClass>());
                    }
                    // Call the original passed in delegate
                    await customerDelegate(decryptedDocs, token);
                })
```
