### ISSUE TITLE
CosmosClient.CreateDatabaseStreamAsync throws ArgumentException in ValidateResource() call instead of returning ResponseMessage with correct error-code

### ISSUE THREAD

**Issue by sivethe** [Azure/azure-cosmos-dotnet-v3#1485]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
CosmosClient.CreateDatabaseStreamAsync throws ArgumentException in ValidateResource() call instead of returning ResponseMessage with correct error-code.  This breaks the exception-less contract.

**To Reproduce**
Create a database name with space at the end.

**Expected behavior**
ResponseMessage with BadRequest statusCode.

**Actual behavior**
System.ArgumentException: The resource name can't end with space.
   at Microsoft.Azure.Cosmos.DocumentClient.ValidateResource(String resourceId)
   at Microsoft.Azure.Cosmos.CosmosClient.CreateDatabaseStreamAsync(DatabaseProperties databaseProperties, Nullable`1 throughput, RequestOptions requestOptions, CancellationToken cancellationToken)

**Environment summary**
Azure CosmosDB Compute

**Additional context**
ComputeDebug
| where ActivityId == "f97db752-2f65-4037-b81d-c78c889b2f73"

**Comment by ealsur** [comment]
@sivethe What kind ResponseMessage should it be, if there is no actual network call? 

Stream APIs contract of not throwing exceptions is related to the actual network operation or service response. But if the invoked method has wrong parameters, those are surfaced as exceptions.

For example, calling `CreateDatabaseStreamAsync` with a null parameter:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0a1f95e43d83d47fdddcf2ae1d8d14a599599101/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L763

![image](https://user-images.githubusercontent.com/1633401/81458039-5141d680-914d-11ea-889c-fcc83e08d470.png)

or passing `id` as `null`:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0a1f95e43d83d47fdddcf2ae1d8d14a599599101/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L460
![image](https://user-images.githubusercontent.com/1633401/81458056-70d8ff00-914d-11ea-81f9-b10bd08e004b.png)

The referenced exception is just another validation taken place.

**Comment by sivethe** [comment]
@ealsur :  I had an offline chat with Kiran and we decided to fix this in our layer.  We can close this bug
