### ISSUE TITLE
Set MaxItemCount = TopCount

### ISSUE THREAD

**Issue by bchong95** [Azure/azure-cosmos-dotnet-v3#1486]
Have the query set MaxItemCount = TopCount. This should automatically mitigate issues like these where the TOP clause isn't pushed down to the backend:

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1340

**Comment by YohanSciubukgian** [comment]
Should LIMIT be part of this issue ?

**Comment by YohanSciubukgian** [comment]
Do you have a link on the PR and/or release that will contains this fix ?
