### ISSUE TITLE
Please put spatial classes in separate Nuget

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#15]
Developers will reference the spatial classes in their own classes. It would be helpful if they didn't need to reference the entire Cosmos SDK.

It goes without saying that you'll need to remove the "internal" keyword from your spatial classes to make them useful.

**Comment by ealsur** [comment]
This is planned in the roadmap. Common classes will be on a separate package and open sourced for GA.

**Comment by jackbond** [comment]
Now that we can see the code, as it stands the spatial classes will be included in the same NuGet. Is the separation planned prior to the next GA release?

**Comment by operationslazlo326** [comment]
Please reopen this issue.
