### ISSUE TITLE
Documentation: Is ParitionKey required for GetItemLinqQueryable call?

### ISSUE THREAD

**Issue by seangwright** [Azure/azure-cosmos-dotnet-v3#1501]
**Is your feature request related to a problem? Please describe.**
I would like some documentation clarifying whether or not a partition key is required when using `GetItemLinqQueryable` in order for the query to be scoped to a single partition.

An example is when the LINQ used with `GetItemLinqQueryable` includes a `.Where(i => i.Pk == "Car");` where `.Pk` is the partition key path of the container and `"Car"` scopes the query to a single partition.

In this case, do I need to specify the `new PartitionKey("Car")` in the request options passed to `GetItemLinqQueryable`?

**Describe the solution you'd like**
Either in the repository samples or on docs.microsoft.com, some examples showing if/when the partition key is inferred from usage in a LINQ query.

**Describe alternatives you've considered**
Currently I'm specifying the partition key value explicitly in every `GetItemLinqQueryable` as opposed to using a `.Where()` call.

**Additional context**
n/a

Thanks 😊!

**Comment by j82w** [comment]
@bchong95 can you please take a look?

**Comment by bchong95** [comment]
No you don't need to specify the partition key in the feed options if you already have it in the LINQ filters. In fact that is the preferred solution.

**Comment by azzimuth** [comment]
But is the partition key required when using `GetItemLinqQueryable`? I get an NullPointerException when I don't include it in LINQ filters but the documentation doesn't specifically say that it's required.

**Comment by j82w** [comment]
@azzimuth can you open a new issue with a sample or a way to reproduce the issue. The SDK should not be throwing a NullPointerException, and it should be considered a bug.

**Comment by azzimuth** [comment]
@j82w, #2479
