### ISSUE TITLE
Diagnostics improvements

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1504]
1. Investigate integration with: https://opentelemetry.io/
2. Nest context objects to show hierarchy
3. Create a object model for diagnostics
4. Add networking time vs SDK time
5. Provide a better aggregation overview like v2 SDK which has table with text.

**Comment by bchong95** [comment]
Resolved by https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2097

1) Opentelemetry would require a dependency approval and doesn't provide the customization flexiblity (like components and source file). 
2) Nesting was a first class design of the TraceTree approach
3) ITrace is a object model with schema and schema free components
4) Transport time is clearly marked out with a component enum
5) Text writing output is provided and the tree object model means anyone can traverse it to provide the aggregation support they need.
