### ISSUE TITLE
ReadContainerAsync not retrieving CompositeIndexes

### ISSUE THREAD

**Issue by markbeij** [Azure/azure-cosmos-dotnet-v3#1508]
**Describe the bug**
Although a composite index is present in the container, I can't check for its existence in code using `Container.ReadContainerAsync()`.

**To Reproduce**
In Azure Portal add a Composite Index to a container.

Then execute the following
```
var container = CosmosClient.GetContainer(DatabaseId, ContainerId);
var response = container.ReadContainerAsync().Result;

ContainerProperties containerProperties = response;

if (!containerProperties.IndexingPolicy.CompositeIndexes.Any())
{
  throw Exception("No composite index found!");
}
```

**Expected behavior**
The aforementioned should throw an exception because the container does have a composite index.

**Actual behavior**
No composite index is found.

**Environment summary**
SDK Version: 3.8.0 and 3.9.0-preview3
OS Version: Windows

**Additional context**
In the startup of my ASPNet Core 2.1 Rest API I want to check if a composite index is created. If not it should be created. If it does, then don't bother as this operation makes queries fail when they make use of this composite index.

**Comment by ealsur** [comment]
@markbeij Was the container created using the V3 SDK?

**Comment by ealsur** [comment]
For reference, we have a test that verifies this against an account: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/856ce66c7d1180ab1b4f54f70e649389e14ff97c/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs#L37

**Comment by markbeij** [comment]
My mistake. The IndexPolicy got overwritten in other parts of my code.
@ealsur thanks for pointing me to this unit test!
