### ISSUE TITLE
Add DecryptionResults to the FeedIterator response to make it easier for the consumer

### ISSUE THREAD

**Issue by anujtoshniwal** [Azure/azure-cosmos-dotnet-v3#1518]
**Is your feature request related to a problem? Please describe.**
In case of query / feed response consisting of multiple documents, if we fail to decrypt one or more documents, DecryptionResultHandler (if configured) will be invoked for each failure (not per request). We then return the encrypted documents as is (without decryption) as part of the FeedResponse.

The client needs to buffer the DecryptionResult (which has the exception details) coming from the callback so that after receiving the FeedResponse, it can use the buffered DecryptionResults and match them with documents in the response to identify the documents which failed decryption and act on them according to the exception.

Ask is to make the DecryptionResults part of the response to avoid having to do this.

**Describe the solution you'd like**
We can define a new DecryptionWrapper<T> class which consists of the decryption related details like exception etc. The client can then request FeedIteratorWithDecryptionWrapper which returns an iterator over DecryptionWrapper<T>, for eg FeedResponse<DecryptionWrapper<T>>. 
This way we can ensure that the response has the exception details as well along with the encrypted document as is to act on. We can do away with the callback per failure since it won't be adding any value now.

**Comment by anujtoshniwal** [comment]
Additionally, Teams have a requirement for us to add an indicator to the response to indicate whether the data stored was really encrypted and the data retrieved was actually decrypted during the process. This is for the services to be able to validate that the encryption is happening as expected, apart from helping with auditing purposes. One of the services has already run into this issue in production, where they mistakenly assumed that they were encrypting data. 

Here is a proposal to address the given issue and also the above requirement -

We will have a new container class which will have extension methods that provide the desired additional information along as part of the response.

```c#
public class DecryptionInfo
{
	bool IsDecrypted;
	IList<String> pathsDecrypted;
	String dekId;
}

// for stream APIs
public class ResponseMessageWithDecryptionInfo : ResponseMessage
{
       Stream DecryptionInfoContent;
}

// for point APIs
public class ItemResponseWithDecryptionInfo<T> : ItemResponse<T>
{
       DecryptionInfo decryptionInfo;
}

// for feed iterator
public class FeedResponseWithDecryptionInfo<T> : FeedResponse<T>
{
       IEnumerator<DecryptionInfo> GetEnumeratorForDecryptionInfo();
}

public class EncryptionContainerWithDecryptionInfo : EncryptionContainer
{
       // sample of point API
       public async Task<ItemResponseWithDecryptionInfo<T>> CreateItemAsync();

       // sample of stream API
       public async Task<ResponseMessageWithDecryptionInfo> CreateItemStreamAsync();

       // sample of feed iterator API
       public FeedIteratorWithDecryptionInfo<T> GetItemQueryIterator<T>();
              => ReadNextAsync() method returns FeedResponseWithDecryptionInfo<T>

      public FeedIteratorWithDecryptionInfo GetItemQueryStreamIterator();
              => ReadNextAsync() method returns ResponseMessageWithDecryptionInfo
}
```

With this approach, we can get rid of the delegate method handler for handling exceptions. We would expose both the flavors - regular EncryptionContainer with regular response which throws on exception and the EncryptionContainerWithDecryptionInfo with extended response including decryption details which doesn't throw in case of exception, rather populates the details to indicate failure.

**Comment by kirankumarkolli** [comment]
/cc: @j82w, @moderakh , @ealsur , @FabianMeiswinkel , @kushagraThapar

**Comment by kirankumarkolli** [comment]
Lets use this thread to also close on the CFP + decryption failures API/design.

**Comment by anujtoshniwal** [comment]
We can extend the above approach for CFP scenario also - if there is a decryption failure, then we will throw in case of regular EncryptionContainer, whereas in case of EncryptionContainerWithDecryptionInfo we won't throw the exception, but populate the results aalong with failure information.

As for the API implementation to support decryption for CFP, the [approach](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1484#issuecomment-642707005) suggested by Jake should work.

**Comment by bchong95** [comment]
I personally don't get why need to expose extra types. Why not return a failed to decrypt error message for the first decryption failure and let the user fix that. I don't see why they need a error response for each document instead of the first of the payload. This would be if newtonsoft returned an error for everything wrong in the json instead of the first parse error. I also don't see why we need to give the decrypted document. Can you provide  samples of how a user will handle these decryption failures?

**Comment by j82w** [comment]
The amount of control and information they are asking for is there any reason they don't just do the decryption themselves? This seems more like a special case for a single customer rather than the normal user scenario.

**Comment by kirankumarkolli** [comment]
- Callback contract vs Return-type
- Buffered context vs Itemized call-back: First is better

Auditing: 
	- Cross cutting concern (CF, Pipeline??)
	- Per request concern 

Two behaviors (CX applicaton side)
	- Knowing if-any failures
	- What are the failures
	- Success/Partial errors -> UsageInfo

EncryptedContainer vs Container
	- Container -> Regular usage (Transparent encryption), Still needs ReqeustOptions specializations
	- EncryptedContainer -> ErrorHandler

Alternative-0: 
	Listed on GitHub issue

Alternative-1: 
	// Behavior & Diagnositcs
	EncDecyptContext { 
		EncryptionKey = ;
		
		// Optin for usageInfo ??
		UsageInfo = {} -> { (pk, id) -> (Paths, key) }+
	}


	Usage scenario (1):
		context: new EncDecyptContext();
		await encContainer.createItem(context);
		
	// After completion (Success/Exception)
	context.UsageInfo


Alternative-3: 
	CosmosDiagnostics.ContextDict<Type, Object>;
		- getContext<T>();
	

Alternative-3.1:


Alternative-2: 
	Request.ContextDict<Key, Object>; // Behavior vs Options
	Response.ContextDict<Key, Object>;


Alternative-4: 
	Enrich Diagnositcs with UsageInfo
	CosmosDiagnostics
		- Cast to a type to use?

Alternative-5: 
	ItemResponse<T>
		Define a promoted type EncryptedContext<T> -> return typed context

**Comment by kirankumarkolli** [comment]
MOM notes
Attendees: Mohammad, Abhijit, Anuj, Kiran, Jake, Matias, Santosh, Brandon

Requirements
	- Programmable aspects: What happened (DecryptableItem will carry this context)
		- Which DEK is used (ref by Name) for encryption/de-cryption
		- What paths are encrypted/decrypted
	- Programamble error handling: 
		- Default to exception behavior, CosmosException vs **CosmosEncryptedException** Non-Cosmos-exception??
			- Applicable to Stream and <T> 
		- Option-in override to not throw
			- Point operations CRUD: ItemEncryptionResponse? What will get returned, won't NULL result in mis-expectations?
			- Batch operations: Is behavior contained to item only?
			- Bulk operations: 
			- Feed operations:
			- **ChangeFeedProcessor:
		- At item granularity (for feed or multi-item interactions, scenario: Multi-tenant)
	- Transparent encryption/de-cryption: Expose encryption programming constucts
	- API consistency with SQL? Including
		- DEK store, KeyEncryptionProvider etc...
		- DEK in-memory cache (Why to re-invent)



- Callback contract vs Return-type
- Buffered context vs Itemized call-back: First is better

Auditing: 
	- Cross cutting concern (CF, Pipeline??)
	- Per request concern 

Two behaviors (CX applicaton side)
	- Knowing if-any failures
	- What are the failures
	- Success/Partial errors -> UsageInfo

EncryptedContainer vs Container
	- Container -> Regular usage (Transparent encryption), Still needs ReqeustOptions specializations
	- EncryptedContainer -> ErrorHandler

Alternative-0: 
	Listed on GitHub issue

Alternative-1: 
	// Behavior & Diagnositcs
	EncDecyptContext { 
		EncryptionKey = ;
		
		// Optin for usageInfo ??
		UsageInfo = {} -> { (pk, id) -> (Paths, key) }+
	}


	Usage scenario (1):
		context: new EncDecyptContext();
		await encContainer.createItem(context);
		
	// After completion (Success/Exception)
	context.UsageInfo


Alternative-3: 
	CosmosDiagnostics.ContextDict<Type, Object>;
		- getContext<T>();
	

Alternative-3.1:


Alternative-2: 
	Request.ContextDict<Key, Object>; // Behavior vs Options
	Response.ContextDict<Key, Object>;


Alternative-4: 
	Enrich Diagnositcs with UsageInfo
	CosmosDiagnostics
		- Cast to a type to use?



Alternative-5: 
	ItemResponse<T>
		Define a promoted type EncryptedItem -> return typed context
		
		// (X) : IDisposable
		class LazyItem  {
		}
		
		LazyItem item = await container.ReadItemAsync<LazyItem>();
		
		try {
			item.As<T>();
		} catch (EncryptedOptions) {
		}

		try {
			item.AsStream();
		} catch (EncryptedOptions) {
		}

	Names
		LazyItem
		EncryptedItem
		DecryptableResult
		**DecryptableItem
