### ISSUE TITLE
Bulk Operations - Progress Update

### ISSUE THREAD

**Issue by alexdrenea** [Azure/azure-cosmos-dotnet-v3#1532]
For scenarios when inserting a lot of data using the Bulk (Batch) API, provide a mechanism for users to be able to get a progress update on the operation.

The current sample code, guides users to create a container with CosmosClientOptions.AllowBulk = true, creating tasks for cosmos operations and waiting them all at the end ([docs](https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/))

It would be nice to be able to monitor the progress of the bulk operation particularly in initial load situations where there are thousands / millions of items to be loaded / operations to process.

Couple of options for implementation:
1. Helper method to perform a batch operation ( `container.ProcessItemsAsync()` ) with a progress report callback action parameter

2. ProgressUpdate delegate exposed on the `container` object that clients can subscribe to get updates from.

I'm curious if this idea has been considered internally and is something the team thinks might be valuable to expose. I'd be happy to extend the conversation and even come back with more thoughts on implementation details if this is something of interest.

**Comment by ealsur** [comment]
You can already do this. Just have a `ContinueWith` on the Task you create and update a global state. Just make sure you are not introducing a lock or something that will hurt the TPL.

**Comment by alexdrenea** [comment]
Oh wow, never thought of that! Let me play a bit and see how that'd work. Might be worth offering it as a sample code or example. Thanks for the suggestion.

**Comment by ealsur** [comment]
The thing is it's very situational (because the way Bulk works is that it leverages the TPL, you can have many Bulk operations from many processes going one and they will all get piped together), but yeah, could be something that can be added to the samples (or we can merge a PR 😉 ).

**Comment by ealsur** [comment]
If you use ContinueWith, just make sure to check for Exceptions in the resulting Task. Otherwise, unobserved exceptions bring issues.

**Comment by alexdrenea** [comment]
Did a first attempt, works pretty nicely and not very difficult

```
var results = new ConcurrentBag<ResponseMessage>();
var statsTimer =new Timer(_ => 
     {
         Console.WriteLine($"Processed {results.Count()}");
     }, null, 10000, 10000)
;
Container container = cosmosClient.GetContainer("myDb", "myCollection");

// Assuming your have your data available to be inserted or read
List<Task> concurrentTasks = new List<Task>();
foreach(Item itemToInsert in ReadYourData())
{
    var task = container.CreateItemAsync(itemToInsert, new PartitionKey(itemToInsert.MyPk))
                     .ContinueWith((res) => {
                         if(res.IsCompletedSuccessfully) 
                         {
                            results.Add(res.Result); 
                         }
                         return res; });
    concurrentTasks.Add(task).;
}

await Task.WhenAll(concurrentTasks);
```

I'll refine this a bit more and maybe propose a sample update. 

I think it's safe to close the issue, but ping me if I can help with this further.

**Comment by ealsur** [comment]
Another idea would be to have another Task reading the concurrentbag every X time and printing the progress and stop when it reaches the total expected.

Remember to inspect the exception:

```
.ContinueWith((res) => {
                         if(res.IsCompletedSuccessfully) 
                         {
                            results.Add(res.Result); 
                         }
                         else
                         {
                           // store or inspect the res.Exception
                         }
                         return res; });
```
