### ISSUE TITLE
Cosmos SDK not usable on UWP apps

### ISSUE THREAD

**Issue by MichalStrehovsky** [Azure/azure-cosmos-dotnet-v3#1549]
Sorry if this is not the right repo, but I can't find the one that builds Microsoft.Azure.Cosmos.Direct.dll.

Microsoft.Azure.Cosmos.Direct.dll has following code in the `ServiceInteropWrapper` class (I disassembled this with ILSpy because I don't know where the source for this is):

```
internal static Lazy<bool> AssembliesExist = new Lazy<bool>(delegate
{
	if (!IsGatewayAllowedToParseQueries())
	{
		return true;
	}
	DefaultTrace.TraceInformation("Assembly location: " + Assembly.GetExecutingAssembly().Location);
	if (Assembly.GetExecutingAssembly().IsDynamic)
	{
		return true;
	}
	string directoryName = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
	string[] array = new string[1]
	{
		"Microsoft.Azure.Cosmos.ServiceInterop.dll"
	};
	foreach (string path in array)
	{
		string text = Path.Combine(directoryName, path);
		if (!File.Exists(text))
		{
			DefaultTrace.TraceVerbose("ServiceInteropWrapper assembly not found at " + text);
			return false;
		}
	}
	return true;
});
```

In .NET Native (but also soon in .NET 5 single file apps), the `Assembly.Location` returns an empty string (as documented in the `Location` documentation). Passing an empty string to `Path.GetDirectoryName` returns null. Passing the null to `Path.Combine` results in `ArgumentNullException`.

This makes Cosmos SDK unusable when building Universal Windows Platform applications.

**Comment by j82w** [comment]
Hi @MichalStrehovsky ,

The [Microsoft.Azure.Cosmos.ServiceInterop.dll](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance#common-sdk-issues) is a native dll used to parse query locally instead of requiring it go to gateway. You can simply delete the file and the SDK will still work. It will just have to always go to the gateway to get the query plan.

**Comment by MichalStrehovsky** [comment]
I see there's a `File.Exists` check, but as I described above, in a .NET Native compiled app this code crashes before it gets to the `File.Exists` check. We have an internal thread with Theo so hopefully this gets resolved there.

**Comment by sbomer** [comment]
The same code also crashes on .NET5 with single-file apps, where `Assembly.Location` returns null.

**Comment by sourabh1007** [comment]
If `Assembly.Location` or `Path.Combine` throws any exception, it falls back to Gateway to generate the query plan. 

As it is very old one. Hence closing it.
