### ISSUE TITLE
CPU monitor refresh task failed

### ISSUE THREAD

**Issue by skurik** [Azure/azure-cosmos-dotnet-v3#1558]
Hi, I just upgraded to Microsoft.Azure.Cosmos 3.9.1 in our ASP.NET MVC 5 application.

After running the application locally, I see the following in the debugger output:

```
DocDBTrace Error: 0 : The CPU monitor refresh task failed. Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Valid CPU load values must be between 0.0 and 100.0
Parameter name: value
Actual value was 100.
   at Microsoft.Azure.Documents.Rntbd.CpuLoad..ctor(DateTime timestamp, Single value)
   at Microsoft.Azure.Documents.Rntbd.CpuMonitor.<RefreshLoopAsync>d__15.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Valid CPU load values must be between 0.0 and 100.0
Parameter name: value
Actual value was 100.
   at Microsoft.Azure.Documents.Rntbd.CpuLoad..ctor(DateTime timestamp, Single value)
   at Microsoft.Azure.Documents.Rntbd.CpuMonitor.<RefreshLoopAsync>d__15.MoveNext()<---
```

This is the code we use to initialize the client:

```
var clientBuilder = new CosmosClientBuilder(connectionString);
var clientWithSerialization = clientBuilder.WithSerializerOptions(new CosmosSerializationOptions
{
    PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
});

Client = clientWithSerialization.Build();

var database = Client.CreateDatabaseIfNotExistsAsync(DatabaseName).ConfigureAwait(false).GetAwaiter().GetResult().Database;
var containerTasks = ContainerDefinitions.Select(c => database.CreateContainerIfNotExistsAsync(c.Properties));
Task.WhenAll(containerTasks).ConfigureAwait(false).GetAwaiter().GetResult();
```

I am connecting the client to a Cosmos DB emulator running on the same machine.

**Environment summary**
SDK Version: 3.9.1
OS Version: Windows 10 Pro, version 1903, build 18362.836

**Comment by j82w** [comment]
@FabianMeiswinkel can you take a look at this? It might be a rounding issue, but it seems like the exception down casted a float to an int.

```c#
if ((value < 0.0) || (value > 100.0))
{
    throw new ArgumentOutOfRangeException(
        nameof(value), value,
        "Valid CPU load values must be between 0.0 and 100.0");
 }
```

**Comment by FabianMeiswinkel** [comment]
@skurik - just out of curiosity are you seeing this repeatedly - or was it a one-time error?

I assume you didn't hit any actual exceptions/failures but were just curious why the error is logged? While it is not expected it should not cause any errors/exceptions. Like @j82w mentioned most likely it is an incorrectly handled rounding - but I would assume that it only happened once and is not reproducible in this case.

**Comment by skurik** [comment]
@FabianMeiswinkel I am not able to reproduce it anymore, but it wasn't a one-time error. When it happened, it kept happening pretty often throughout the application lifetime, every couple of seconds.

It's true it didn't cause any exceptions to bubble up, but the error message was suspicious (__Valid CPU load values must be between 0.0 and 100.0. Actual value was 100.__), probably as you said due to rounding.

**Comment by FabianMeiswinkel** [comment]
Thanks @skurik - in that case I think I know what was happening and will prepare a fix. It should have shown up every 10 seconds - so not causing any livesite impact - but definitely worth fixing. Thanks for reporting it.
