### ISSUE TITLE
Samples: ItemManagement. Example "1.3 - Read all items in a Collection" is not implemented

### ISSUE THREAD

**Issue by santiagoIT** [Azure/azure-cosmos-dotnet-v3#1559]
The ItemManagement sample provides a summary of all CRUD operations that are demonstrated in the sample at the top of the [file](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs).

CRUD Operation **"1.3 - Read all items in a Collection"** is listed in the summary, but the implementation is missing.

**Comment by j82w** [comment]
Fixed in #1564
