### ISSUE TITLE
Confusing documentation for EnableContentResponseOnWrite

### ISSUE THREAD

**Issue by skurik** [Azure/azure-cosmos-dotnet-v3#1560]
The [code documentation](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0470549a9800f6ceeb23f72010e0cfb85094f1ac/Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs#L119) suggests that the server will not serialize back the resource to the response __if the value is true__.

However, the [usage itself](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0470549a9800f6ceeb23f72010e0cfb85094f1ac/Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs#L178) suggests it has to be __false__ to not serialize the resource to the response.

Which one is it?

**Comment by j82w** [comment]
I'm sorry about this. I missed updating this comment. We originally had the flag reversed. I thought I updated all the comments, but I obviously missed this one. I'll send out a PR today to fix it. 

// No content response
EnableContentResponseOnWrite = false

// Content in response
EnableContentResponseOnWrite = true
