### ISSUE TITLE
Resource present in write response even if EnableContentResponseOnWrite is false

### ISSUE THREAD

**Issue by skurik** [Azure/azure-cosmos-dotnet-v3#1562]
**Describe the bug**
`EnableContentResponseOnWrite` seems to be ignored when calling `CreateItemAsync`.

**To Reproduce**
```
var options = new ItemRequestOptions() { EnableContentResponseOnWrite = false };
var response = await container.CreateItemAsync(item, requestOptions: options);
```

**Expected behavior**
`response.Resource` is `null`.

**Actual behavior**
`response.Resource` contains the resource written.

**Environment summary**
SDK Version: 3.9.1
OS Version: Windows 10

**Comment by j82w** [comment]
@skurik are you running against an emulator or production? If it's an emulator can you please upgrade to the latest. I just tested it locally and verified it is working for me. The [tests](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContentResponseTests.cs) are also passing.

**Comment by skurik** [comment]
Thanks @j82w, I confirm that after updating to the latest emulator version, it's working fine. I also tried it against Azure Cosmos now and it works as well.
