### ISSUE TITLE
Add IsSuccessStatusCode & EnsureSuccessStatusCode to ContainerResponse/DatabaseResponse

### ISSUE THREAD

**Issue by YohanSciubukgian** [Azure/azure-cosmos-dotnet-v3#1566]
**Is your feature request related to a problem? Please describe.**
We need to implement our own method to check if the StatusCode is valid or to raise an Exception when required.

**Describe the solution you'd like**
Provide the same implementation as ResponseMessage which provides access to :
```
public virtual bool IsSuccessStatusCode { get; }
public virtual ResponseMessage EnsureSuccessStatusCode();
```

**Describe alternatives you've considered**
I create my own methods to manage these behaviors because the following methods are not public :
```
internal static bool IsSuccess(this HttpStatusCode httpStatusCode)
{
        return ((int)httpStatusCode >= 200) && ((int)httpStatusCode <= 299);
}
```
```
throw new CosmosException(
        response.ErrorMessage,
        response.StatusCode,
        (int)response.StatusCode,
        response.Headers.ActivityId,
        response.Headers.RequestCharge);
```

**Comment by j82w** [comment]
@YohanSciubukgian I think there is a misunderstanding on the exception logic. For all typed responses like `ContainerResponse`/`DatabaseResponse`/`ItemResponse<T>` the SDK will throw a `CosmosException` if the status code is a failure. The status code on those objects are used for where you need to tell if an item was created or read when calling something like `CreateContainerIfNotExists`.

APIs that return a `ResponseMessage` like `CreateItemStreamAsync` will not throw service exceptions like 404 Not found. It can still throw argument exceptions or task cancelled exceptions. The `ResponseMessage` contains the `EnsureSuccessStatusCode` method.

**Comment by YohanSciubukgian** [comment]
Thanks for details, I didn't know that the Exception logic was binded to specific types (`ContainerResponse/DatabaseResponse/ItemResponse<T>`). I though it was only related to HttpClient calls that could be done by the SDK.
Is there any documentation (MS doc or on the repository) that could give me more details about which kind of Exception can be raised for each method ?
eg: the HttpClient has code documentation like this :
```
// Exceptions:
//   T:System.ArgumentNullException:
//     The requestUri is null.
//
//   T:System.Net.Http.HttpRequestException:
//     The request failed due to an underlying issue such as network connectivity, DNS
//     failure, server certificate validation or timeout.
```

Some methods doesn't have any override which implement ResponseMessage return type like this `CreateContainerIfNotExistsAsync` method.

**Comment by j82w** [comment]
The SDK should always throw a CosmosException for service issues, and should be documented on the [methods](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readcontainerasync?view=azure-dotnet#exceptions). It's still possible to get an OperationCancelledException or ArgumentException.

**Comment by j82w** [comment]
The reason behind the difference is performance. The stream APIs are designed for advanced scenarios where performance is critical. Throwing exceptions causes a lot of overhead. To avoid that overhead it return a response instead of throwing an exception. This goes against dot net guidelines and what most users except. That is why the typed APIs still throw exceptions to make it more inline what developers are expecting.

**Comment by YohanSciubukgian** [comment]
I like the way it's currently implemented, the StreamAPIs let me customize usages for performance reasons & typed API are used for most common scenarios with Exception handling.

That makes sense to consider different implementation for Management methods.
However, as `CreateDatabaseStreamAsync` & `CreateContainerStreamAsync` exist, could it have values to implement Stream APIs for `CreateDatabaseIfNotExistsAsync` & `CreateContainerIfNotExistsAsync` ?

**Comment by j82w** [comment]
The [CreateDatabaseIfNotExistsAsync](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/3e4b150fc7d3b212454ce8fd5b08dcd922426756/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L460) and CreateContainerIfNotExistsAsync methods do use the stream APIs to handle the logic.

**Comment by YohanSciubukgian** [comment]
Thanks you for all those details.
I have checked the source code & I now have a better understanding on how you are handling all these cases.
