### ISSUE TITLE
Session token and transactional batch

### ISSUE THREAD

**Issue by mwikstrom** [Azure/azure-cosmos-dotnet-v3#1567]
**Is your feature request related to a problem? Please describe.**
I want to keep session consistency up to date when using transactional batch.

**Describe the solution you'd like**
I'd like the transactional batch operation to accept a session token (perhaps via an options construct similar to other operations) and then return an updated session token in its response.

**Describe alternatives you've considered**
If one *really* need to ensure that session consistency is up to date after executing a transactional batch operation the only option I've come up with is to:

1. Execute the batch
2. Capture one of the new item's ETag and Timestamp
3. Query container with current session token repeatedly until the new ETag is visible or a greater Timestamp is observed

In most cases this will incur a single extra round trip but could potentially require many extra round trips.

**Comment by j82w** [comment]
@abhijitpai can you please take a look?

**Comment by mwikstrom** [comment]
Any news on this issue?
