### ISSUE TITLE
Add tests for CancellationToken handling for Query and rate limiting tests for Diagnostics

### ISSUE THREAD

**Issue by visridha** [Azure/azure-cosmos-dotnet-v3#1572]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
We need tests that track 429 failure tracking and a framework for that in the SDK tests. we also need the ability to track CancellationToken

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
Fixed in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1584
