### ISSUE TITLE
EnableContentResponseOnWrite still populating Resource with created item.

### ISSUE THREAD

**Issue by Camios** [Azure/azure-cosmos-dotnet-v3#1574]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Trying to test functionality of ItemRequestOptions' EnableContentResponseOnWrite, but it isn't being respected per example given in docs.
According to the documentation when EnableContentResponseOnWrite is set to true and CreateItemAsync is called the SDK or Emulator(?) is incorrectly populating the Resource property with the created object in the response message.
Expected value for Resource is null.

**To Reproduce**
Can use the below .net core console solution code using a nuget ref to the 3.9.1 sdk.
When running it fails the TestTrue (when EnableContentResponseOnWrite is true). 
```
using Microsoft.Azure.Cosmos;
using System;
using System.Net;
using System.Threading.Tasks;

namespace TestEnableResponseOnWrite
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var client = new CosmosClient("AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==");
            var databaseResponse = await client.CreateDatabaseIfNotExistsAsync("TestEnableResponseOnWrite");
            if (HttpStatusCode.Created != databaseResponse.StatusCode
                && HttpStatusCode.OK != databaseResponse.StatusCode)
            {
                throw new Exception("Didn't create database");
            }
            var database = databaseResponse.Database;
            var containerResponse = await database.CreateContainerIfNotExistsAsync("TheContainer", "/description");
            if (HttpStatusCode.Created != containerResponse.StatusCode
                && HttpStatusCode.OK != containerResponse.StatusCode)
            {
                throw new Exception("Didn't create container");
            }
            var container = containerResponse.Container;
            await TestTrue(container);
            await TestFalse(container);
        }

        private static async Task TestTrue(Container container)
        {
            ItemRequestOptions requestOptions = new ItemRequestOptions() { EnableContentResponseOnWrite = true };
            var item = new ToDoActivity { description = "foo" };
            ItemResponse<ToDoActivity> itemResponse = await container.CreateItemAsync(item, new PartitionKey(item.description), requestOptions);
            if (HttpStatusCode.Created != itemResponse.StatusCode)
            {
                throw new Exception("Didn't create item");
            }
            if (itemResponse.Resource == null)
            {
                Console.WriteLine("Test (EnableContentResponseOnWrite = true) passed");
            }
            else
            {
                Console.WriteLine("Test (EnableContentResponseOnWrite = true) failed");
            }
        }

        private static async Task TestFalse(Container container)
        {
            ItemRequestOptions requestOptions = new ItemRequestOptions() { EnableContentResponseOnWrite = false };
            var item = new ToDoActivity { description = "bar" };
            ItemResponse<ToDoActivity> itemResponse = await container.CreateItemAsync(item, new PartitionKey(item.description), requestOptions);
            if (HttpStatusCode.Created != itemResponse.StatusCode)
            {
                throw new Exception("Didn't create item");
            }
            if (itemResponse.Resource != null)
            {
                Console.WriteLine("Test (EnableContentResponseOnWrite = false) passed");
            }
            else
            {
                Console.WriteLine("Test (EnableContentResponseOnWrite = false) failed");
            }
        }

    }

    public class ToDoActivity
    {
        public string id => Guid.NewGuid().ToString();
        public string description { get; set; }
    }
}
```

**Expected behavior**
According to [example](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.itemrequestoptions.enablecontentresponseonwrite?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Azure.Cosmos.ItemRequestOptions.EnableContentResponseOnWrite)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet#examples) when EnableContentResponseOnWrite is true expected value for Resource is null.

**Actual behavior**
Resource incorrectly has a value - so no performance gain.

**Environment summary**
SDK Version: 3.9.1
OS Version Windows 10

**Additional context**
Also the naming of this property seems counter to intuition and behaviour in example.
When I looked at the SDK I couldn't find a unit test for EnableContentResponseOnWrite=true

**Comment by Camios** [comment]
I tried running against an Azure hosted cosmos DB and found that I got failures for both tests.
Which suggests, two problems:

1. The example in the documentation and the implementation are inconsistent.
2. The Emulator [documentation ](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#differences-between-the-emulator-and-the-service) needs updating to mention it doesn't support EnableContentResponseOnWrite or emulator needs fixing to support the correct behaviour.

**Comment by Camios** [comment]
Oddly the type of the flag is nullable, so what is default behaviour (not set) vs setting to true or false? Please elaborate and correct the documentation as part of addressing this ticket.

**Comment by j82w** [comment]
Hi @Camios,

Sorry for the confusion. The documentation has already been updated and a sample has been added in this [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1564). It will be fixed in the next release. 

Please update the emulator to the latest release. The older versions do not know about the new header and treat just ignore it.

The flag is nullable so that if there is demand that a client level options can be added. If the flag isn't set then no option is set to the service and it just uses the services default value. The service defaults with the flag being true. In the v4 SDK this option is being planned to be switched to false by default because of the performance improvements.
