### ISSUE TITLE
Create Item that takes a JSON string

### ISSUE THREAD

**Issue by Camios** [Azure/azure-cosmos-dotnet-v3#1580]
**Is your feature request related to a problem? Please describe.**
I want to put an item in a Cosmos DB container using the SQL API.
If I already have the object in JSON string form (not a stream and not a class), why can't I create the item using the .NET SDK directly? The API expects either a class (which means deserialising) for CreateItemAsync or a stream (for me to copy the string contents into another stream) for CreateItemStreamAsync. Or am I missing something? is it because the SDK would need to copy the string into a stream too?

**Describe the solution you'd like**
A CreateItemAsync override that takes a string because serialization has already been done.

**Comment by j82w** [comment]
1. The string will eventually need to be converted to a stream.
2. It pretty unusual to just have a JSON string. If you are reading in from a file then it can be read in as a file stream. If it's from another service the network stream can be passed into the SDK. Most  JSON serializers support streams. In what scenario do you have just a string?

**Comment by ealsur** [comment]
Adding to what @j82w mentioned.

> A CreateItemAsync override that takes a string because serialization has already been done.

Serialization is not serialization to string, it means serialization to a byte stream that is sent to through the network wire. 
With this definition, the SDK already supports taking content that was already serialized (Stream).

**Comment by Camios** [comment]
> 1. The string will eventually need to be converted to a stream.

Cosmos needing a stream for the json wasn't known to me - it makes sense, but is an implementation detail from SDK consumer point of view.

> 2. Its pretty unusual to just have a JSON string. If you are reading in from a file then it can be read in as a file stream. If it's from another service the network stream can be passed into the SDK. Most  JSON serializers support streams. In what scenario do you have just a string?

The default Cosmos serializer wasn't generating desired output for string enums. So was using Newtonsoft with StringEnumConvertor and was hoping for convenience I didn't need to copy it into another object for CreateItemAsync or stream for CreateItemStreamAsync. Seemed inefficient.

The system.text JSON serializer seems a

> Adding to what @j82w mentioned.
> 
> > A CreateItemAsync override that takes a string because serialization has already been done.
> 
> Serialization is not serialization to string, it means serialization to a byte stream that is sent to through the network wire.
> With this definition, the SDK already supports taking content that was already serialized (Stream).

Actually I meant JSON serialization (from object to string) had already been done.  But understand what you mean.

**Comment by j82w** [comment]
Have you tried using a custom [serializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1930cf3fafd369aee8e3ff18462882629ce2f28b/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L416)? The default implementation is [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs).
