### ISSUE TITLE
Initial continuation token for change feed

### ISSUE THREAD

**Issue by rayao** [Azure/azure-cosmos-dotnet-v3#1586]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Hey maybe I'm just too dumb to find out how to work with the preview APIs.
I want to call GetChangeFeedIterator to enumerate all items, but with a null continuation token, the enumeration always return "NotModified" and a continuation token which represents "now", so with it I can' only get change feed from now on.

**Describe alternatives you've considered**
I figured out that by replacing the "token" value (in following continuation token) to 0 I can start from the beginning, but it's far from elegant, and I'm afraid not supported.
{"V":0,"Rid":"GVYOALvY6Zc=","Continuation":[{"token":"\"40\"","range":{"min":"","max":"FF"}}],"Range":{"min":"","max":"FF"}}

**Additional context**
no

**Comment by j82w** [comment]
Please take a look at this [sample](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e9823a67efcc9239f98e8d5d9aa9b13b65ed479c/Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs#L170). You need to set the start time otherwise it default to DateTime.UtcNow

**Comment by rayao** [comment]
Thanks @j82w
