### ISSUE TITLE
Docs use Newtonsoft instead of System.Text.Json in examples

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cosmos-dotnet-v3#1590]
Docs such as this one: https://docs.microsoft.com/en-us/dotnet/api/azure.cosmos.cosmoscontainer.getitemquerystreamiterator?view=azure-dotnet-preview

Use Newtonsoft.

They should be converted to System.Text.Json

**Comment by ealsur** [comment]
That's not totally correct. When you use Streams, you can use the serialization technology that you want. So the example is not completely incorrect, you can use Newtonsoft.Json if you want.
But it makes sense to update these to System.Text.Json at least for consistency.
