### ISSUE TITLE
Azure Core Diagnostics is not yet supported in v4

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cosmos-dotnet-v3#1592]
If you add a simple console listener to your project:

```csharp
AzureEventSourceListener.CreateConsoleLogger(EventLevel.Informational);
```

You will get the following exception:

```
Exception has occurred: CLR/System.NotImplementedException
An exception of type 'System.NotImplementedException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The method or operation is not implemented.'
   at Microsoft.Azure.Cosmos.RequestMessage.EnumerateHeaders()
   at Azure.Core.RequestHeaders.GetEnumerator()
   at Azure.Core.Pipeline.LoggingPolicy.FormatHeaders(IEnumerable`1 headers)
   at Azure.Core.Pipeline.LoggingPolicy.<ProcessAsync>d__12.MoveNext()
```

You can get around this by Disabling diagnostics in the CosmosClientOptions

```csharp
 CosmosClientOptions options = new CosmosClientOptions
            {
                 Diagnostics = {
                    IsLoggingEnabled = false
                },
                SerializerOptions = new CosmosSerializationOptions { PropertyNamingPolicy = CosmosPropertyNamingPolicy.Default }
            };

            var cosmosSerializerOptions = new CosmosSerializationOptions { PropertyNamingPolicy = CosmosPropertyNamingPolicy.Default };
            CosmosClient cosmosClient = new CosmosClient(
                        Environment.GetEnvironmentVariable("AZURE_COSMOS_ENDPOINT"),
                        Environment.GetEnvironmentVariable("AZURE_COSMOS_KEY"), options);
```

But then Diagnostics is disabled.

This should be considered a v4 ship blocker.

**Comment by ealsur** [comment]
V4 is in experimental phase and meant to keep evolving (in fact the latest code changes public API quite a lot on names for example).

Which V4 version are you using? Which version of `Azure.Core` are you using?

We have a test to verify a listener would work, and it's not getting this error (maybe the ConsoleLogger logs more information): https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Diagnostics/DiagnosticsScopeTests.cs#L16

**Comment by ealsur** [comment]
Was able to repro with the ConsoleLogger and sent a fix.
