### ISSUE TITLE
GetItemQueryStreamIterator API Name, Casing, and Sample Issues

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cosmos-dotnet-v3#1593]
Following the docs here:
https://docs.microsoft.com/en-us/dotnet/api/azure.cosmos.cosmoscontainer.getitemquerystreamiterator?view=azure-dotnet-preview

I was expecting this code:
```csharp
public class ToDoActivity{
    public string id {get; set;}
    public string status {get; set;}
    public int cost {get; set;}
}

QueryDefinition queryDefinition = new QueryDefinition("select * from ToDos t where t.cost > @expensive")
    .WithParameter("@expensive", 9000);
await foreach(Response response in this.Container.GetItemQueryStreamIterator(
                                                queryDefinition,
                                                null,
                                                new QueryRequestOptions() { PartitionKey = new PartitionKey("Error")}))
    {
        using (StreamReader sr = new StreamReader(response.Content))
        using (JsonTextReader jtr = new JsonTextReader(sr))
        {
            JObject result = JObject.Load(jtr);
        }
    }
```

To return each Document inside of the await foreach loop.

But, it actually returns a structure like this:

```
{
  "Documents": []
}
```

So, I had to create a class like this:
```csharp
    public class QueryStream
    {
        [JsonPropertyName("Documents")]
        public QueueMessage[] Documents { get; set; }
    }
```

And then deserialize using that class.

## Issue # 1: "Documents" casing

Because "Documents" is Pascal casing it will conflict with my SerializationOptions and child documents, which have camelCasing.

> Question: Should we use "documents" instead or enable the user to specify casing for the outer documents.  Or ask users to name their property "public QueueMessage[] documents" so the casing is honor.  As you can see above I needed to add a JsonPropertyNames attribute, because I'm deserializing with camel and so it expects Documents to be camel as well.

## Issue # 2: API name

Based on the example and the API name, I was expecting it to yield for every document, not every page.  

> Question: Should this be renamed to GetItemPageQueryStreamIterator?

## Issue # 3: Docs are misleading.

Because the doc has a single item class ToDoActivity, I was led to believe it would return individual items.

> Suggestion: Update the sample to make it very clear what the dev has to do to use it.

Here's the code to get this working...this included a lot of trial and error and debugging to figure out.
```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Azure;
using Azure.Cosmos;
using Azure.Cosmos.Serialization;
using DotNetEnv;
namespace cosmostest
{
    public class QueryStream
    {
        [JsonPropertyName("Documents")]
        public QueueMessage[] Documents { get; set; }
    }

    class Program
    {
        static async Task Main(string[] args)
        {
            Env.Load();

            CosmosClientOptions options = new CosmosClientOptions
            {
                SerializerOptions = new CosmosSerializationOptions { PropertyNamingPolicy = CosmosPropertyNamingPolicy.Default }
            };

            CosmosClient cosmosClient = new CosmosClient(
                        Environment.GetEnvironmentVariable("AZURE_COSMOS_ENDPOINT"),
                        Environment.GetEnvironmentVariable("AZURE_COSMOS_KEY"), options);

            CosmosContainer cosmosContainer = cosmosClient.GetDatabase(Environment.GetEnvironmentVariable("AZURE_COSMOS_DB")).GetContainer(Environment.GetEnvironmentVariable("AZURE_COSMOS_CONTAINER"));
            QueryDefinition queryDefinition = new QueryDefinition("SELECT * FROM c");
            List<QueueMessage> msgs = new List<QueueMessage>();

            await foreach (Response response in cosmosContainer.GetItemQueryStreamIterator(queryDefinition))
            {

                var queryStream = await JsonSerializer.DeserializeAsync<QueryStream>(response.ContentStream,
                    new JsonSerializerOptions() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });

                msgs.AddRange(queryStream.Documents);
            }

        }
    }
}
```

**Comment by ealsur** [comment]
This aligns with the same behavior on V3 SDK, the query results are `Response` which is the actual backend network response without any deserialization. This basically represents the REST API response.

`Documents` is another thing that is part of the REST API contract: https://docs.microsoft.com/en-us/rest/api/cosmos-db/query-documents

**Comment by SeanFeldman** [comment]
This API was really not intuitive. The `GetItemQueryStreamIterator` returning a document with the `Documents` property that's the actual collection of the items is very confusing.

**Comment by Jeremywhiteley** [comment]
> This API was really not intuitive. The `GetItemQueryStreamIterator` returning a document with the `Documents` property that's the actual collection of the items is very confusing.

I totally agree!  Trying to get GetItemQueryStreamIterator working in a web api app is been very difficult because the samples are very confusing.

**Comment by jongio** [comment]
@ealsur updated the docs here: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1599/files 

@Jeremywhiteley Which link has the samples that are confusing?

**Comment by SeanFeldman** [comment]
@jongio, I was tripped by the sample here: https://docs.microsoft.com/en-us/dotnet/api/azure.cosmos.cosmoscontainer.getitemquerystreamiterator?view=azure-dotnet-preview

**Comment by jongio** [comment]
Looks like @ealsur's update didn't make it to docs site yet.  @ealsur Can you look into that?

**Comment by SeanFeldman** [comment]
Also, what the count stands for? Total count? Count for a given iteration while iterating through all the results returned from the server? If it's the latter, the documents collection already provides a count and I'd rather see a "total count".

**Comment by ealsur** [comment]
The doc update didn't make it because we haven't shipped yet a new version with those changes, currently no ETA on the next preview.

@SeanFeldman not sure which Count you refer to? If it's part of the page it would be the number of items in the page?

**Comment by jongio** [comment]
Could we migrate those samples update to the current version as well?

**Comment by jongio** [comment]
Could we migrate those samples update to the the cversion as well?

**Comment by ealsur** [comment]
With current version you mean V3? V3 samples work with Newtonsoft.Json, they use this to deserialize:

```
using (StreamReader sr = new StreamReader(response.Content))
            using (JsonTextReader jtr = new JsonTextReader(sr))
            {
                JObject result = JObject.Load(jtr);
            }
```

Is that not good?

**Comment by SeanFeldman** [comment]
> @SeanFeldman not sure which Count you refer to? If it's part of the page it would be the number of items in the page?

@ealsur, correct. That's the one. Given that the deserialized collection of documents will provide the count, I see it as redundant and rather see a `totalCount` that would tell me how many documents would be returned if I'd continue retrieving results.

**Comment by jongio** [comment]
@SeanFeldman - Were you trying to use v4, but looking at v3 docs?

**Comment by ealsur** [comment]
@SeanFeldman Can you point to the actual code you are looking at? Or write the code here? I don't see any property called `totalCount` in the involved types? The results in a query page are potentially just a subset of the total query, and the total number of results would be available after the entire query has been drained.

**Comment by SeanFeldman** [comment]
> @SeanFeldman Can you point to the actual code you are looking at? Or write the code here? I don't see any property called `totalCount` in the involved types? The results in a query page are potentially just a subset of the total query, and the total number of results would be available after the entire query has been drained.

@ealsur, I didn't say there is a `totalCount`. What I said is that the property `_count` that is returned makes no sense since upon deserialization of the `Documents` collection you know how many items were returned for each iteration.
```
{
  "Documents": [
    {
      "id": "123",
      "Id": "123",
      "metadata": {
        "key-1": "key1",
        "key-2": "key2"
      },
  ],
  "_count": 1
}
```

Thus the returned type could be simply the array of the documents.

**Comment by ealsur** [comment]
@SeanFeldman That is part of the REST API contract. It is not part of the SDK definition nor a contract defined by the SDK, so there is nothing that can be done on the SDK to remove that property, because that is the server response as defined in https://docs.microsoft.com/en-us/rest/api/cosmos-db/query-documents#body-1.

If you are deserializing the Stream (this thread is for the Stream APIs) you could lookup that property to initialize the array/list that contains your results to avoid memory resizing if you wished, not really required, but it's one usage I can think of.
