### ISSUE TITLE
Would it be possible to add [DataContract] to the spatial classes

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#16]
Service Fabric does not natively support Json serialization. It would be really helpful if the spatial classes were marked with DataContract so they could be more easily passed around by Service Fabric services and actors.

**Comment by ealsur** [comment]
@jackbond Is this a blocker in your current project? We have this in the roadmap but if you are blocked we can take that into account to prioritize.

**Comment by jackbond** [comment]
Well I could say it was a blocker, but at this point it's really just an inconvenience. The reality is, the Service Fabric guys have provided a means to write custom serializers for their actor and service calls, but it's full of gotchyas. For example, we wrote one so that we could pass our objects that have a property of DocumentDb.Spatial.Point, but then that messed up the serialization of Exceptions (which I haven't had the time to figure out if there is a workaround.)

Fundamentally, I don't know how much work it would take for you guys to support DataContract, but it does seem that two core Azure services should play a little nicer together. :)

**Comment by ealsur** [comment]
I agree. We'll keep it in the roadmap for GA to support this scenario :)

**Comment by operationslazlo326** [comment]
Is there an estimate for GA? There doesn't appear to be a whole lot of activity in regards to the source.

**Comment by j82w** [comment]
The current estimate for GA is the first half of 2019. This may change base on new feature requests.

**Comment by jackbond** [comment]
So I take it you guys aren't using this repository for your actual source control. It would be nice to be able to provide direct feedback based on ongoing code changes.

**Comment by jackbond** [comment]
Are you guys planning another preview? The lack of spatial support in the existing preview makes it rather difficult to experiment with. Thanks.

**Comment by j82w** [comment]
Hi @jackbond ,

We are planning do to another release soon. After that release we will move to using this repository as the actual source control.
