### ISSUE TITLE
3.9.1 throwing 409 on insert/upsert item when there is no conflict

### ISSUE THREAD

**Issue by wcom939** [Azure/azure-cosmos-dotnet-v3#1606]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
In version 3.9.1 I have only one document in cosmos db, with no unique index specified and a partition key

The documents have an ID in the form of
yyyy-MM-dd-[int between 1-288]-[stock symbol]

In the database there was one document 2020-06-06-278-DIA

upsert/insert of document with ID 2020-06-06-279-DIA caused a conflict 409.

This issue does NOT exist in v 3.5.1 of the SDK.

The partition key for both are 2020-06-06-DIA

**To Reproduce**
Insert docs with the IDs listed above on 3.9.1.

**Expected behavior**
The documents should be inserted

**Actual behavior**
First document is inserted, second throws a conflict (409).

**Environment summary**
SDK Version: 3.9.1
OS Version (e.g. Windows, Linux, MacOSX) Windows 10
.net core 3.1

**Comment by j82w** [comment]
There are [tests ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5d071ea1693a1c784e10d6b71e98f603647b7f1a/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs#L384)that validate this scenario. Any chance you can provide a simple console app that reproduces the issue?

**Comment by ealsur** [comment]
Do you have UniqueKeys defined in your collection?

**Comment by ealsur** [comment]
Closing, please reopen if you have a repro available. If your Collection has [UniqueKeys](https://docs.microsoft.com/en-us/azure/cosmos-db/unique-keys) make sure your second document is not violating the unique key constraint by providing the same value on the attributes.
