### ISSUE TITLE
Duality of XXXXResponse StatusCode and CosmosExceptions

### ISSUE THREAD

**Issue by Camios** [Azure/azure-cosmos-dotnet-v3#1633]
A number of SDK calls return a 'response' object. And it isn't explicitly clear from the documentation of the call when or if the response object should be (also) used to check the success/failure of a request or if the lack of an exception is the sole indication of success. 

e.g. Container's DeleteContainerAsync returns a ContainerResponse.
ContainerResponse has a number of fields with no description (can this be fixed please?). 
Once such field is the StatusCode property. One might assume you should check the http status of the request
But then there's also mention of CosmosException which could be thrown, but only mentions one status code 404 - what if there's a different error - will it be in the exception or the container response? Is it a case of the table is missing other status codes? 

Can the documentation make a distinction please?
Peaking at the code, It might be as simple as improving the 'return' doc to say the ContainerResponse is only returned for success http status codes / Rewording the CosmosException description so we understand that is is only thrown if the http status code does't indicate success

**Comment by j82w** [comment]
Hi @Camios, 

Please check out the new [exception](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/TroubleshootingGuides/Exceptions.md) documentation. The status code on the response is used for very success scenarios. For example CreateIfNotExists will allow you to determine if it the resource was created or if it already existed.

**Comment by j82w** [comment]
I added more documentation in PR #1638
