### ISSUE TITLE
How to get a JSON list of all the Container IDs

### ISSUE THREAD

**Issue by Camios** [Azure/azure-cosmos-dotnet-v3#1634]
I'm trying to query a Cosmos Database to find out the ids of all of its containers.
I'm using the example from [here ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.database.getcontainerquerystreamiterator?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Azure.Cosmos.Database.GetContainerQueryStreamIterator);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet)

The doco says GetContainerQueryStreamIterator queries comply with the SQL query language, but that isn't the case.
The returned JSON doesn't return what is queried. Instead of an array of object it returns a single json object 'wrapper' and if you try to send a query knowing this, it doesn't work and if assume the object is a wrapper around the response and change the query to access fields within the DocumentCollections, that doesn't work either. You either get an exception or nothing in the DocumentCollections.

See this [stackoverflow](https://stackoverflow.com/questions/62401529/cosmos-sql-query-which-doesnt-return-an-array) for example and its comments for failed attempts

**Comment by j82w** [comment]
Cosmos DB returns all all query, read feed, and change feed operations in a wrapper. I agree that is not a great scenario and we are looking into removing the outer wrapper.

Here are some examples of how to do it:
```c#
 using (FeedIterator feedIterator = this.cosmosDatabase.GetContainerQueryStreamIterator(
                "select value c.id From c "))
            {
               // The current logic is not handling if there is a loop.
                while (feedIterator.HasMoreResults)
                {
                    using (ResponseMessage response = await feedIterator.ReadNextAsync())
                    {
                        response.EnsureSuccessStatusCode();
                        using (StreamReader streamReader = new StreamReader(response.Content))
                        {
                            string content = await streamReader.ReadToEndAsync();
                            // Output will be:
                            // {"_rid":"7p8wAA==","DocumentCollections":["4d310b0d-1716-4bc8-adfa-861a66e4034b","e3eb4ac7-f8a4-47ce-bd71-f65ab43dcb53"],"_count":2}
                            int arrayStart = content.IndexOf('[');
                            int arrayEnd = content.IndexOf(']');
                            string json = content.Substring(arrayStart, arrayEnd - arrayStart + 1);
                        }
                    }
                }
            }
```

```c#
   List<string> ids = new List<string>();
            using (FeedIterator<string> feedIterator = this.cosmosDatabase.GetContainerQueryIterator<string>(
                    "select value c.id From c "))
            {
                while (feedIterator.HasMoreResults)
                {
                    FeedResponse<string> iterator = await feedIterator.ReadNextAsync();
                    ids.AddRange(iterator);
                }
            }

string json = JsonConvert.SerializeObject(ids);
```

**Comment by j82w** [comment]
@Camios if the previous comment doesn't answer your question please reopen the issue.
