### ISSUE TITLE
LINQ - new ignore case flags do not work

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-cosmos-dotnet-v3#1647]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
From https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1615#issuecomment-646398795

Linq to SQL not implemented for this yet?
Just upgraded to latest, and it misinterprets the parameters

**3.9.1**
Expression
`(x => x.FromName.ToLower().Contains(nameLower))`

**SQL**
`CONTAINS(LOWER(root["fromName"]), "searchString")`

**3.10.1**
Expression
`(x => x.FromName.Contains(name, StringComparison.OrdinalIgnoreCase))`

**SQL**
`AND CONTAINS("searchString", 3)`

**To Reproduce**
Execute a LINQ query to Cosmos passing in an `IgnoreCase` parameter`

**Expected behavior**
SDK to generate SQL to ignore case when performing the query

**Actual behavior**
Does not generate SQL that ignores case

**Environment summary**
SDK Version: 3.10.1
OS Version (e.g. Windows, Linux, MacOSX) Windows 

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by bchong95** [comment]
@khdang any estimates on the LINQ updates?

**Comment by wahyuen** [comment]
any news if this is something that is planned for development any time soon? or is this something further down the track?

**Comment by kweebtronic** [comment]
Really need this feature parity! I'm duplicating lower-cased data just to work around this right now

**Comment by j82w** [comment]
@wahyuen and @kweebtronic 3.12.0 is released with the support.
