### ISSUE TITLE
Get ETag value for items returned by CreateItemQuery

### ISSUE THREAD

**Issue by happywisepaul** [Azure/azure-cosmos-dotnet-v3#165]
When getting an item using **ReadItemAsync** the result has ETag available from the **CosmosItemResponse** wrapper of the entity object [**SalesOrder**](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/CodeSamples/Shared/SalesOrder.cs):

```c#
CosmosItemResponse<SalesOrder> itemResponse = 
    await container.Items.ReadItemAsync<SalesOrder>(
        partitionKey: "Account1",
        id: "SalesOrder1");
Console.WriteLine("ETag of read item - {0}", itemResponse.ETag);
```

But when getting an item using **CreateItemQuery** (passing a SQL), the result is put in **CosmosQueryResponse** containing only the array of items instead of an array of **CosmosItemResponse**, so I cannot get the ETag of each item. Definition of entity **Family** is at [the end of this file](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs).

```c#
var query = new CosmosSqlQueryDefinition("SELECT * FROM Families f WHERE f.id = @id AND f.Address.City = @city")
    .UseParameter("@id", "AndersonFamily")
    .UseParameter("@city", "Seattle");
List<Family> results = new List<Family>();
var resultSetIterator = container.Items.CreateItemQuery<Family>(query, partitionKey: "Anderson");
while (resultSetIterator.HasMoreResults) {
    results.AddRange((await resultSetIterator.FetchNextSetAsync()));
}
```

I cannot find other ways to get items using SQL so the ETag is returned with the item itself.  So how about adding another method to **CosmosResultSetIterator** which return an array of CosmosItemResponse wrapper over the entity?

**Comment by bchong95** [comment]
The `Family` class you are using does not have an Etag property, so when we take the response and deserialize it into a `List<Family>` the Etag property is lost. You can add an etag property with the correct serializer settings.

**Comment by happywisepaul** [comment]
Thank you, that does it.  I made my entities to derive from a common Class:
``` c#
    public class CosmosDBEntity
    {
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }   // for CosmosDB required id, initialize with Guid.NewGuid().ToString()
        [JsonProperty(PropertyName = "_etag")]
        public string ETag { internal get; set; }   // for CosmosDB so we can get the ETag but doesn't get serialized to CosmosDB
    }
```
