### ISSUE TITLE
Updating from 3.9.1 to 3.10.1 throws System.MissingMethodException

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-dotnet-v3#1651]
Updating from 3.9.1 to 3.10.1 started throwing the below exception:

> System.MissingMethodException: Method not found: 'System.String Microsoft.Azure.Documents.PathsHelper.GeneratePath(Microsoft.Azure.Documents.ResourceType, System.String, Boolean, Microsoft.Azure.Documents.OperationType)'. 

Here's the full stack trace:

[exception.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/4807180/exception.txt)

**Comment by j82w** [comment]
Hi @petro2050,

Can you provide a console app that reproduces this? It seems to be referencing this [code](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1de241a41b311ca287ec5c0178298602b7f63d02/Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs#L420), and all the gates are passing. The only idea I have right now is there is a stale dll like `Microsoft.Azure.Cosmos.Direct.dll` that is cached. Can you try to do a clean and rebuild?

**Comment by ealsur** [comment]
Do you have a solution with multiple projects that reference each other? Is the SDK being included in multiple of these projects? Can you verify if the versions of the SDK across these projects are the same or you are using binding redirects?

**Comment by petro2050** [comment]
I'm deploying a Function app, so I believe there was a stale dll somewhere. I did a clean and rebuild, and it fixed the issue.
