### ISSUE TITLE
Partition Key Isolation

### ISSUE THREAD

**Issue by worldspawn** [Azure/azure-cosmos-dotnet-v3#1652]
**Is your feature request related to a problem? Please describe.**
I have several dynamic (they go up, new ones get made, old ones destroyed) development environments. It would be advantageous from a provisioning time stand point and (more importantly) a cost standpoint if I could run multiple environments backed by the same containers.

**Describe the solution you'd like**
An obvious solution to this problem would be to prefix all our partition keys with an environment specific prefix and ensure that prefix is always applied to partition keys passed to the SDK. A comparative approach is the stackexchange redis client's WithKeyPrefix method on IDatabase.

https://github.com/StackExchange/StackExchange.Redis/pull/92

This approach is awesome because I can configure it in DI and the rest of my application doesn't need to know its happening. It also results in no breaking changes.

**Describe alternatives you've considered**
Currently my approach is to define this in my DI:

``` csharp
For<CreatePartitionKey>()
    .Use(x =>
    {
        var prefix = Configuration.Get(x => x.CosmosPrefix);
        return (string name, out string fullName) =>
        {
            fullName = $"{prefix}_{name}";
            return new PartitionKey(fullName);
        };
    });
```
``` csharp
public delegate PartitionKey CreatePartitionKey(string name, out string fullName);
```

And then i inject and use that delegate anywhere i need a PartitionKey instance. Mostly this works but it's not the bullet proof solution i have in my redis client. A dev is still free to make whatever partition key they like and break it.

A little side query, I have the `out string fullName` so I can get the partition key's name as a string. I do this so I can set it on TModel.PartitionKey (if upserting). PartitionKey.ToString() returns some json form of the value so I can't get the key from that (simply). Am I able to change the type of TModel.PartitionKey from string to PartitionKey? That would solve the need for a string representation of the key. Still think I should be able to get the plain name from a PartitionKey instance.

**Additional context**

``` csharp
var partitionKey = _createPartitionKey($"{nameof(UserDocumentListViewModel)}_${@event.EntityId}",
                out string partitionKeyString);

//...

var viewModel = new UserDocumentListViewModel
{
    Id = documentRef.Key,
    Title = documentEntity.Title,
    Owner = ownerEntity.ToString(),
    Role = documentRef.Value,
    PartitionKey = partitionKeyString
};

using (var ms = new MemoryStream())
{
    await JsonSerializer.SerializeAsync(ms, viewModel,
        new JsonSerializerOptions() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase },
        cancellationToken);
    tasks.Add(_container.UpsertItemStreamAsync(ms, partitionKey, cancellationToken: cancellationToken));
}
```

**Comment by j82w** [comment]
Have you look at [shared throughput on databases](https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#set-throughput-on-a-database)? I'm not sure if it is a concern, but there is a restriction of [25 containers](https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-account-limits) per a database.

**Comment by worldspawn** [comment]
Hi @j82w, I had not considered that. Topologically it seems more complex an approach then a string prefix. I would need to make container names configurable and differ per env. Small complaints but... we programmers are fickle :D

I suppose that is one way to solve this. Personally I would prefer to use a prefix to the key. As a concept its simple, doesn't grow the surface area of my topology and, afaik won't run into any artificial caps on usage.
