### ISSUE TITLE
Poor performance on getting many filtered records?

### ISSUE THREAD

**Issue by MichalLechowski** [Azure/azure-cosmos-dotnet-v3#1654]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Quite simple query getting too long to get the data.

**To Reproduce**
Using latest v3 SDK and .NET Core 3.1 I've created LINQ query like this:
 ``` 
var querable = _cosmosDbService.Container.GetItemLinqQueryable<DeviceModel>(requestOptions: new QueryRequestOptions() { MaxItemCount = -1 });
            var filters= querable.Where(x => x.Timestamp >= request.TimeInterval.StartDate && x.Timestamp <= request.TimeInterval.EndDate).Where(x => request.DeviceIds.Contains(x.DeviceId));

            var iterator = filters.ToFeedIterator();
            
            var results = new List<Dictionary<string, object>>();
            while (iterator.HasMoreResults)
            {
                foreach (var item in await iterator.ReadNextAsync())
                {
                    var singleResult = new Dictionary<string, object>();
                    singleResult.Add(nameof(item.Id), item.Id);
                   
                    foreach (var property in item.Properties)
                    {
                        singleResult.Add(property.Name, property.Value);
                    }
                    results.Add(singleResult);
                }
            }

            return results;
```

which results in simple query like this example:
` SELECT VALUE root FROM root WHERE (((root["timestamp"] >= "2020-03-01T05:28:36.386Z") AND (root["timestamp"] <= "2020-06-16T05:28:36.386Z")) AND (root["deviceId"] IN ("ASD"))) `

**Expected behavior**
Response in xx or xxx ms instead a few seconds.

**Actual behavior**
Right now this query returns around 6500 (db has ~122k records atm) records and the request process time called from API within THE SAME resource group (the same region) is around 2,4 seconds which is ridiculous (tested using swagger). When I setup a stopwatch in the handler code provided above, it's all the cosmos db code, all the time taken is within the request code. The less the records, the faster the query but 6500 records is still nothing so why the latency grows so rapidly for a very simple time range filter and deviceId filter (deviceId is partition key)?

**Environment summary**
SDK Version: latest v3
OS Version (e.g. Windows, Linux, MacOSX); AppService with deployed .NET Core 3.1 WebAPI
Region: the same resource group for DB and for AppService, region West Europe.
CosmosDB settings:
1) manual 4000 RU/s (it's development environment so the DB is working pretty much without any heavier load, not even medium)
2) Indexing policies:
``` {
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/*"  (I tried moving it to excluded paths, didn't help or maybe I have to wait longer?)
        },
        {
            "path": "/deviceId/?" (THIS IS PARTITION KEY)
        },
        {
            "path": "/timestamp/?"
        }
    ],
    "excludedPaths": [
        {
            "path": "/\"_etag\"/?"
        }
    ],
    "compositeIndexes": [
        [
            {
                "path": "/deviceId",
                "order": "ascending"
            },
            {
                "path": "/timestamp",
                "order": "ascending"
            }
        ],
        [
            {
                "path": "/deviceId",
                "order": "descending"
            },
            {
                "path": "/timestamp",
                "order": "descending"
            }
        ]
    ]
} 
```

3) API is deployed to AppService running on B2 plan, also not-loaded, just for development purposes.

**Additional context**

getting 0-100 records stats:
![image](https://user-images.githubusercontent.com/34692839/85293248-62e10280-b49d-11ea-8264-d966ed682e31.png)

when I spam "load more" a few times:
![image](https://user-images.githubusercontent.com/34692839/85293456-a3d91700-b49d-11ea-8d2d-72bb4b7514b9.png)

Do you guys know what's going on here and how to fix this? I obviously can't have multiple parition keys so deviceId (GUID) is the obvious choice. But we use timestamp range (ISO 8601 format) to get the data all the time along with deviceId. What am I doing here wrong that it takes so long to get the larger amount of data?

**Comment by j82w** [comment]
Have you looked at the [Cosmos db query troubleshooting guide](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance)? 

@bchong95 can you take a look?

**Comment by j82w** [comment]
Also can you please provide the [diagnostics](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1376b1cc3d8bb566cec7b4dce99bb29e7cdf5b67/Microsoft.Azure.Cosmos/src/Resource/Response.cs#L71).

**Comment by MichalLechowski** [comment]
> 
> 
> Have you looked at the [Cosmos db query troubleshooting guide](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance)?
> 

A little bit, yes. Tried a few things from various sites, including msdn. Been stuck on this for a few days already :( 


> 
> 
> Also can you please provide the [diagnostics](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1376b1cc3d8bb566cec7b4dce99bb29e7cdf5b67/Microsoft.Azure.Cosmos/src/Resource/Response.cs#L71).
> 
> ```cs
> while (iterator.HasMoreResults)
> {
>    var response = await iterator.ReadNextAsync();
> 
>    Console.WriteLine(response.Diagnostics.ToString());
>    foreach (var item in response )
>    {
> ```

Sure, it's a lot so there's a TXT file below.

[cosmosDbDiag.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/4813773/cosmosDbDiag.txt)

**Comment by j82w** [comment]
I think you might have a bug in the way you are logging the diagnostics. It's the same diagnostics output duplicated over and over again.

Are you running this application in the same region as the Cosmos DB instance? The diagnostics are pointing to a networking issue. It shows that networking layer took 1243ms, but Cosmos DB total execution time was only 55ms. Which means that 1188ms was spent in networking time.

**Comment by MichalLechowski** [comment]
> 
> 
> I think you might have a bug in the way you are logging the diagnostics. It's the same diagnostics output duplicated over and over again.
> 
> Are you running this application in the same region as the Cosmos DB instance? The diagnostics are pointing to a networking issue. It shows that networking layer took 1243ms, but Cosmos DB total execution time was only 55ms. Which means that 1188ms was spent in networking which is way higher than it should be. Also make sure that you have [accelerated networking enabled](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-dotnet-sdk-v3-sql) if you have an Azure VM.

Yes, you are right. My bad. Ok let's leave that file since it was from locally run API. Here is a correct log for API running in the cloud:


[query_data.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/4817674/query_data.zip)

We're not using VMs.

**Comment by j82w** [comment]
The issue is your application is running in x86 in the cloud instead of x64 like your local instance. There is a [native service interop dll](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance#common-sdk-issues) that parses and optimizes the query that only work in windows x64. Since it's not running in x86 it is doing an additional network call to get the query plan from the gateway.

Please upgrade to 3.10.1. There is a bug in 3.10.0 that causes additional overhead and tracing.

**Comment by MichalLechowski** [comment]
> 
> 
> The issue is your application is running in x86 in the cloud instead of x64 like your local instance. There is a [native service interop dll](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance#common-sdk-issues) that parses and optimizes the query that only work in windows x64. Since it's not running in x86 it is doing an additional network call to get the query plan from the gateway.
> 
> Please upgrade to 3.10.1. There is a bug in 3.10.0 that causes additional overhead and tracing.
> 
> The total time in networking was 573ms. The get gateway query plan took 355ms.

Okay this is a good lead. I've changed API AppService settings to:
![image](https://user-images.githubusercontent.com/34692839/85407364-6a6adf00-b563-11ea-84b5-54acb337cd87.png)

Also updated SDK to 3.10.1 and I can feel the speed difference. It's not huge but it's already visible.

Here is a new log. What do you think about it now?
[query_data_updatednuget_windowsx64.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/4819567/query_data_updatednuget_windowsx64.zip)

**Comment by j82w** [comment]
The networking time is roughly .5 seconds. 

1. Inserting into a dictionary can be very costly. You could use Newtonsoft JObject instead and get roughly the same functionality. I would at least try moving the conversion logic to after the feediterator and just insert the results into a list. 
2. The FeedIterator should be wrapped in a using statement. This could lead to memory leaks
3. Try setting the MaxBufferedItemCount  to -1. This will let the SDK buffer pages in the background.
4. There is some overhead to warm up some caches on the first operation after creating a CosmosClient. You should do a warm up query or run it multiple times during your validation to make sure it's not including the one time warm up cost.

**Comment by MichalLechowski** [comment]
> 
> 
> The networking time is roughly .5 seconds. The create query time is now 1.8ms instead of the previous 355ms.
> 
>     1. Inserting into a dictionary can be very costly. You could use Newtonsoft JObject instead and get roughly the same functionality. I would at least try moving the conversion logic to after the feediterator and just insert the results into a list.
> 
>     2. The FeedIterator should be wrapped in a using statement. This could lead to memory leaks
> 
>     3. Try setting the MaxBufferedItemCount  to -1. This will let the SDK buffer pages in the background.
> 
>     4. There is some overhead to warm up some caches on the first operation after creating a CosmosClient. You should do a warm up query or run it multiple times during your validation to make sure it's not including the one time warm up cost.

1. I've tried with JObject but there isn't much difference. So now I just push the results to List<DeviceModel> while iterating and then after it ends, I'm making the conversion to List<Dictionary<string,object>> and the whole conversions is like 15-25ms when measured
2. I did that
3. I've tried, I don't see much difference, tho.
4. I'm always testing with at least 20-30 requests, also different query params (different device ids, difference timestamps) and waiting till the response times "settle". The problem is with the amount of data e.g. when I insert two deviceIds in the query, the time is pretty much doubled (the amount of records from 2 deviceIds is exactly twice as many as from a single deviceId). 

Now the code looks like this:

``` var querable = _cosmosDbService.Container.GetItemLinqQueryable<DeviceModel>(requestOptions: new QueryRequestOptions() { MaxItemCount = -1 });
            var dateQuery = querable.Where(x => x.Timestamp >= request.TimeInterval.StartDate && x.Timestamp <= request.TimeInterval.EndDate);
            if (request.DeviceIds.Any()) dateQuery = dateQuery.Where(x => request.DeviceIds.Contains(x.DeviceId));

            var results = new List<Dictionary<string, object>>();
            var devmodels = new List<DeviceModel>();

            Log.Debug("QUERY EXECUTION STARTS HERE");
            using (var iterator = dateQuery.ToFeedIterator())
            {
                while (iterator.HasMoreResults)
                {
                    var reader = await iterator.ReadNextAsync();
                    Log.Debug("MY DIAG LOG: " + reader.Diagnostics.ToString());
                    foreach (var item in reader)
                    {
                        devmodels.Add(item);
                    }
                }
            }
            Log.Debug("QUERY EXECUTION ENDS HERE");

            var sw = new Stopwatch();
            sw.Start();
            foreach (var item in devmodels)
            {
                var singleResult = new Dictionary<string, object>
                {
                    { nameof(item.Id), item.Id },
                    { nameof(item.DeviceId), item.DeviceId },
                    { nameof(item.Timestamp), item.Timestamp.ToString("yyyy-MM-dd HH:mm:ss.fff") }
                };
                foreach (var property in item.Properties)
                {
                    singleResult.Add(property.Name, property.Value);
                }
                results.Add(singleResult);
            }
            sw.Stop();
            Log.Debug(sw.Elapsed.TotalMilliseconds.ToString());
            return results;
```

I have MaxItemCount = -1 all the time, is that the correct approach here?

**Comment by j82w** [comment]
Yes, that is the correct approach.

The last diagnostics shows the query completed in roughly 1 second and returned 17,199 records. Is that within your expectations?

**Comment by MichalLechowski** [comment]
> 
> 
> Yes, that is the correct approach.
> 
> The last diagnostics shows the query completed in roughly 1 second and returned 17,199 records. Is that within your expectations?

Frankly, we have to get as fast as possible or change database completely. The project gets sensor data from cosmos (e.g. temperature etc.) that is saved e.g. every 5 minutes, and you can have as many sensors as you want so for example getting 7 days of data from e.g. 10 sensors means A LOT of records. And we need this to be as close to real-time as can be since the data is used in Angular app to create visualizations etc. 

I have a question regarding one thing. When processing this code that handles cosmos, there is always multiple:
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll

so when I enable to break at CLR exceptions I get:
![image](https://user-images.githubusercontent.com/34692839/85519484-def45b00-b601-11ea-8046-50cde225876f.png)
![image](https://user-images.githubusercontent.com/34692839/85519523-eb78b380-b601-11ea-9aa1-bf1e83a1b235.png)

Is that normal?

**Comment by j82w** [comment]
@bchong95 can you take a look at the operation cancelled exception, and do you have any suggestions on improving the performance?

**Comment by otif11** [comment]
in some cases where the query is few results the "while" has failed in terms of performance and we have had to change it to an "if".

This is even one of the incidents discussed in the SDK.

**Comment by MichalLechowski** [comment]
> 
> 
> in some cases where the query is few results the "while" has failed in terms of performance and we have had to change it to an "if".
> 
> This is even one of the incidents discussed in the SDK.

Can you tell what exactly are you referring to? My problem (this topic) is that the more the results query has to retury, the slower the execution time and your answer seems to be exactly the opposite. Also provide a like to the mentioned discussion if you can.

Greetings

**Comment by bchong95** [comment]
This nuget and soon the 3.17 release will have the tracing we need to investigate issues like this:

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2172

Please reopen this issue with the latest diagnostics if the issue is persistent.
