### ISSUE TITLE
Scripts to be extensions in different namespace

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#167]
# Scripts namespace change

All Scripts (Stored Procedures, UDFs, Triggers) will move to the `Microsoft.Azure.Cosmos.Scripts` namespace and inlined.

Based on a Container, the Scripts can be accessed by calling the extension `GetScripts()`.

For example

    CosmosScripts cosmosScripts = container.GetScripts();
    CosmosStoredProcedureSettings storedProcedure = await cosmosScripts.CreateStoredProcedureAsync("scriptId", script);
    string result = await cosmosScripts.ExecuteStoredProcedureAsync<object ,string >(id : "scriptId", partitionKey : documentDefinition.Id, input : null);

**Comment by j82w** [comment]
@ealsur can you elaborate a little more on what this involves? I'm worried about how unit testing will be supported if it is converted to extension methods.

**Comment by ealsur** [comment]
As per @kirankumarkolli suggestion, this is the idea:

    Microsoft.Azure.Cosmos.Script

    public static class ScriptsExtensions
    {
        public static CosmosResponse<StoredProcedureSettigns> CreateStoredProcedureAsync(this CosmosContainer ....)
        {

        }
    }

**Comment by j82w** [comment]
C# doesn't support mocking static methods. How can this support user unit testing?

**Comment by j82w** [comment]
Why not keep scripts in it's own class and have an extension method to get a scripts class? That way scripts stays in it's own namespace, it prevents it from over crowding containers, and still allows it to be unit testable.

```
    public static CosmosScripts GetScripts(this CosmosContainer ....)
    {

    }

   public abstract class Scripts{ }
```
