### ISSUE TITLE
CreateItemStreamAsync for partition key name containing special characters fails with BadRequest

### ISSUE THREAD

**Issue by john-pao** [Azure/azure-cosmos-dotnet-v3#1675]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When attempting to call CosmosClient.CreateItemStreamAsync() for an item/collection with partition key name containing special characters, the request always fails with BadRequest "PartitionKey extracted from document doesn't match the one specified in the header".

**To Reproduce**
1) Create collection with partition key name containing special characters.
2) Attempt to insert a document (with a defined partition key) into the collection using CosmosClient.CreateItemStreamAsync().
3) Examine the ResponseMessage status code and error message.

See emulator test added in branch users/jopao/pkSpecialCharacters:
https://github.com/Azure/azure-cosmos-dotnet-v3/compare/users/jopao/pkSpecialCharacters?expand=1

**Expected behavior**
Expect that the request succeeds and the item is inserted into the collection.

**Actual behavior**
The response message indicates failure with status code BadRequest and error message "PartitionKey extracted from document doesn't match the one specified in the header".

**Environment summary**
SDK Version: 3.10.1
OS Version: Windows 10 Enterprise, Version 10.0.18363

**Comment by ealsur** [comment]
On Stream APIs, the Stream is the one you generate. The error is related to the Partition key header value not matching with the data in the document represented in the Stream.

Do you have a property in the document that matches the PartitionKeyDefinition in the Container with the same encoding as you are passing the PartitionKey value?

For example,if you container has `/myPartitionKey` as PK, does your stream contain a property `myPartitionKey` with a value that matches what you are passing as Partition Key to the parameter? Are you using UTF8 encoding to generate the stream?

**Comment by j82w** [comment]
@john-pao the issue with your example is the item does not have the partition key path specified in the container creation. The container has the path to the partition key. The item operations require the partition key value which must be at the path specified in the container.

Here are valid values for your test.
```c#
const string PartitionKeyPath = "/\"/my !@#$%&*()_+|?.,><~`/ pk\"";
const string ItemJsonPayload = "{\"label\":\"blah\",\"id\":\"08d39221-15f5-4312-ad9a-bd40923469e8\",\"/my !@#$%&*()_+|?.,><~`/ pk\":\"blah2\"}";
const string ItemPartitionKey = "blah2";
```

**Comment by john-pao** [comment]
I created a container using the same PartitionKeyPath as is specified in the ItemJsonPayload.

The path is: /\"/my !@#$%&*()_+|?.,><~`/ pk\"

const string PartitionKeyPath = "/\"/my !@#$%&*()_+|?.,><~`/ pk\"";
this.containerSettings = new ContainerProperties(id: containerName, partitionKeyPath: PartitionKeyPath);

The property name is: \"/my !@#$%&*()_+|?.,><~`/ pk\"

const string ItemJsonPayload = "{\"label\":\"blah\",\"id\":\"08d39221-15f5-4312-ad9a-bd40923469e8\",\"/my !@#$%&*()_+|?.,><~`/ pk\":\"blah2\"}";

**Comment by john-pao** [comment]
@j82w  After further testing it seems your suggested correction was not quite correct for the scenario

```c#
const string PartitionKeyPath = "/\"/my !@#$%&*()_+|?.,><~`/ pk\"";
const string ItemJsonPayload = "{\"label\":\"blah\",\"id\":\"08d39221-15f5-4312-ad9a-bd40923469e8\",\"/my !@#$%&*()_+|?.,><~`/ pk\":\"blah2\"}";
const string ItemPartitionKey = "blah2";
```

Using this, the partition key property name embedded in the document is missing the surrounding escaped double-quotes, which while successful, seems to lead to the SDK creating the document in the Undefined partition rather than using the desired "blah2" partition key value.

 I'm going to re-open this for tracking.

I've also fixed the collection partition key path in the repro sample to both simplify it and reflect my intentions:

``` c#
const string PartitionKeyPath = "/\"mypk\"";
const string ItemJsonPayload = "{\"label\":\"blah\",\"id\":\"08d39221-15f5-4312-ad9a-bd40923469e8\",\"\\\"mypk\\\"\":\"blah2\"}";
const string ItemPartitionKey = "blah2";
```

The special characters in this case around the escaped double-quotes in the partition key property name.

**Comment by j82w** [comment]
This seems to be more of a bug in v2 SDK/Cosmos DB. The PK path specified does exist and it does have a value. The correct PK value is "blah2". The fact that the v2 SDK is extracting the value as undefined and the backend also is not able to find it seems like a bug.

**Comment by john-pao** [comment]
The V2 SDK correctly extracts the partition key value "blah2" from the document.

In my above comment, I was referring to the 'valid values' you had previously provided; they do work with the V3 SDK test, but only because you omitted the embedded double-quotes that should be embedded in the document's PK property name such that the document is assigned the Undefined partition key rather than correctly extracting "blah2":

``` c#
const string PartitionKeyPath = "/\"/my !@#$%&*()_+|?.,><~`/ pk\"";
```
versus
``` c#
const string ItemJsonPayload = "..., \"/my !@#$%&*()_+|?.,><~`/ pk\":\"blah2\"}";
```

When the values are corrected as follows for the V3 SDK, the request fails as I had initially described in this issue.

``` c#
const string PartitionKeyPath = "/\"/my !@#$%&*()_+|?.,><~`/ pk\"";
const string ItemJsonPayload = "{\"label\":\"blah\",\"id\":\"08d39221-15f5-4312-ad9a-bd40923469e8\",\"\\\"/my !@#$%&*()_+|?.,><~`/ pk\\\"\":\"blah2\"}";
const string ItemPartitionKey = "blah2";
```

{"Response status code does not indicate success: BadRequest (400); Substatus: 1001; ActivityId: c4c02641-41c9-454d-89e8-a09aaee29b18; Reason: (Message: {\"Errors\":[\"PartitionKey extracted from document doesn't match the one specified in the header\"]}\r\nActivityId: c4c02641-41c9-454d-89e8-a09aaee29b18, Request URI: /apps/DocDbApp/services/DocDbServer6/partitions/a4cb4952-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: Please see CosmosDiagnostics, SDK: Windows/10.0.18363 cosmos-netstandard-sdk/3.11.1);"}

**Comment by j82w** [comment]
After more testing the only reason this is working in v2 is it is always setting the partition key to undefined. This makes it not possible for the user to read the document back if they use the partition key value specified in the document. They have to switch the partition key value to the undefined in order to read it.

V3 since it requires the user to pass in the partition key value on the CreateItemStreamAsync method it fails on the insert rather than the read. Users could still do what v2 is using a specify the undefined partition key value, but that seems like the incorrect behavior.

**Comment by john-pao** [comment]
Looking at our partition key documentation, it seems like this may not even be a valid scenario to begin with.

https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview

> The partition key path accepts alphanumeric and underscore(_) characters. You can also use nested objects by using the standard path notation(/).

We're going to adjust our test case to match the valid characters described there (just combinations of alphanumerics and underscores) and not test against values such as escaped double-quotes in the partition key path

Thanks for your help investigating this issue, Jake.
