### ISSUE TITLE
Container Fluent creation - Support Autoscale

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-cosmos-dotnet-v3#1677]
**Is your feature request related to a problem? Please describe.**
Current documentation recommends that containers are created using the Fluent API, however, there doesn't currently seem to be a way to create a container with Autoscale throughput. It would be great if this was supported.

It appears that `ContainerBuilder` currently only supports the following contract `CreateIfNotExistsAsync(int? throughput)`

**Describe the solution you'd like**
Method overload that supports creating a container with `ThroughputProperties`
eg.
```csharp
database.DefineContainer("test", "somekey").Attach()
    .CreaterIfNotExistsAsync(ThroughputProperties.CreateAutoscaleThroughput(10000))
```

**Describe alternatives you've considered**

Create a container manually without the fluent API calling `Create` against the database or do something like the following

```csharp
var properties = database.DefineContainer("test", "somekey").Attach().Build();
database.CreateContainerIfNotExistsAsync(properties, ThroughputProperties.CreateAutoscaleThroughput(10000));
```

**Comment by j82w** [comment]
@wahyuen [3.11.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.11.0) is out with the support.
