### ISSUE TITLE
BulkSupport for Cosmos DB graph bulk insert, both vertices and edges?

### ISSUE THREAD

**Issue by FrankTeusink** [Azure/azure-cosmos-dotnet-v3#1690]
I am trying to achieve the above.
Inserting vertices goes fine.
But I cannot find any way to insert edges.
Nor can I find examples for doing this.
Is it not possible, or do I mis some documentation?

**Comment by j82w** [comment]
@abhijitpai do you know if this is possible?

**Comment by ealsur** [comment]
This SDK is for the SQL API, not for Graph, so it does not handle the concept of edges, it's all documents.

**Comment by alexdrenea** [comment]
I'm not sure if this is "good" advice, but you can treat edges as documents too and use the same Bulk concepts that exist for SQL. It is relying on understanding the "shape" of the edge document behind the scenes which is not documented and potentially can change at any time.

**Comment by FrankTeusink** [comment]
Thank you. 
I decided to go for the classic BulkExecutor approach. Only limits me to the .NET Framework, but that’s ok. 
I fiddled a bit with the edge/document approach, but couldn’t get that to work. If you have a working example, I’d like to have it for in mij backpack (c:

Frank

**Comment by ealsur** [comment]
Thanks @FrankTeusink for confirming, will close this issue now.
