### ISSUE TITLE
Diagnostics: Add way to get the region the operation occurred on

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1701]
There are many scenarios where users need to know which region a request actually completed. This issue is to discuss exposing a way for the user to see which region it was completed on.

```c#
    public abstract class CosmosDiagnostics
    {
        public abstract string GetLastEndpoint()
        {
        }

        public virtual TimeSpan GetClientElapsedTime()
        {
        }

        public abstract override string ToString();
    }
```

**Comment by lingdaLi** [comment]
Yeah since we have a account replicate globally this will really helpfully for us to monitor the traffic

**Comment by j82w** [comment]
Open question is should it expose all the endpoints that it accessed/attempted or just the last one where it completed?

**Comment by lingdaLi** [comment]
I feel on most cases we don't need accessed/attempted, especially under the condition the operation succeed. But it's no harm to have, depends on the developing diffculties

**Comment by bchong95** [comment]
Once ITrace and the corresponding TraceDatums are public then users can navigate to StoreResponseStatistics to get this information.
