### ISSUE TITLE
CosmosClient Cold start

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#1706]
Current implementation in any mode (Gateway/Direct) requires the client to be fully initialized.
Initialization typically involves covering blow state
- Databases/container information
- Partitions & address information

Current implementation results blocking any data-plane request: Till caches are fully initialized, Its variant based on the #databases/#container/#pattitions.

Few possible alternatives & scenarios mix (rough draft)

1. Non-blocking & Optimize data operations: SDK will choose the connection mode dynamically. (not just scoped to the cold-start theme)

Scenarios:
> Blocking is not acceptable, trad-able against latencies
> Once in steady state the behavior must be predictable

Design possibilities:
> - Cold start: Client can start with Gateway mode and then fall back to direct seamlessly as optimization (Gateway implementation needs to de-couple from initialization though)
> - Fallback to gateway on persistent 410's: To be explored
> - Request scope region fall-back (Client retry-policy): Auto route through gateway (to optimize on connections??)

Will Auto mode selection go against application expectation (ex: SLA's, latencies, etc...)? 
Can a scoped choice (i.e only cold start-up Gateway -> Direct) be a good enough for most CX scenarios?

2. Application wants to control the behavior: 

Scenarios: 
> Explicit start-up initialization is acceptable
> Definite state when app can decide to use it

Design possibilities: Ref: #1671 
I.e. let application define the target state and initialize for it explicitly. #1671 do cover it partially.

**Comment by j82w** [comment]
Some other optimizations.

1. Have gateway return all the required caches via single API call.
2. Have the ability to Backup/Restore caches locally. This way users can call backup and then restore after

**Comment by pencal** [comment]
Hi @kirankumarkolli ; Thanks for starting this thread. This is Calvin from LinkedIn, one of the tech leads in K2; I am curious in general what is the expected time for the caches to be fully initialized?

**Comment by kirankumarkolli** [comment]
@pencal its depends on the ~#database/#containers/#partitions. 
For large account noticed that initialization might take few seconds (there might be few outliers even for simpler Account set-up as well).

**Comment by kirankumarkolli** [comment]
Warn-up involves two parts: 
- Meta-data initialization
- Connections creation: In direct mode connection's are practically dedicated. And based on the concurrency load more connections might need to be created. 

Few possible options are
- Meta-data initialization only: Work around is to run one single cross partition order-by query
- Pre-create N connections per replica: It will result in lots of connections created ahead. I.e. for a container with 1K partitions, the total connections warmed-up would be 4NK connections. 

How about start with just the meta-data initialization only? (FWIW this is how even prior SDK's did as well)

**Comment by ealsur** [comment]
Initialization is scoped only to the Container/Partition that the data-plane operation is targeted for though, right? That means that if the client does a write, it won't ask for Addresses for ALL the Partitions, just the Partition the write is targeted to. 
This means that the cold-start effect is over time, as operations start to spread other partitions, then the cache with the Addresses gets built.

The alternative of going to Gateway assumes that the Gateway latency is less than getting the Addresses and opening the TCP connection to the replicas?

In the V2 SDK we had an API called `OpenAsync()` on the client, that basically populated all caches:
* Got the information from ALL the Containers
* Got the addresses for ALL Partitions within each Container

This API worked fine if the account had a few Containers, but in accounts with a LOT of Containers, the overhead was pretty big, considering that the app was potentially only using a few of those Containers.

What about a middle ground of having a `Container.OpenAsync()` that will only warm-up connections to all Partitions only for a particular container?

**Comment by j82w** [comment]
I'm against the `OpenAsync()` API. Most customers did not know about it and it is difficult to discover. 

What about the following model where customer can add a list of containers to initialize. If it is null then it will

```c#
// Warmup all containers
CosmosClient cosmosClient = CosmosClient.CreateAndInitialize(
string endpoing
string key); 
```

```c#
// Warmup a subset of containers
CosmosClient cosmosClient = CosmosClient.CreateAndInitialize(
string endpoing
string key,
IReadOnlyList<string> containers); 
```

**Comment by kirankumarkolli** [comment]
/cc: @moderakh , @milismsft , @kushagraThapar , @mbhaskar , @FabianMeiswinkel

**Comment by milismsft** [comment]
We already tell users to use OpenAsync() as one of the performance tips: https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips
The downside of it is where lots of containers (and respective partitions) are created for the particular account.
Correct me if I'm wrong but a ReadAsync() on the container itself, wouldn't that be enough to "warm" the connections?

**Comment by j82w** [comment]
There has been many CRIs and issues because customer's don't know about the OpenAsync(), and we still get customers with these questions.  OpenAsync() is very ambiguous in what it actually does, and the name does not convey that it is initializing all the caches.

The model I suggested is a standard design pattern for initializing objects that require async work. It's more discoverable than OpenAsync, and it is clear what it is doing.

**Comment by ealsur** [comment]
Another alternative would be an API on the Container itself?

```
Container container = client.GetContainer("mydb", "mycontainer");
await container.InitializeConnectionsAsync(); //or some other name
```

@milismsft The ReadAsync on the container just reads the metadata of the container, through Gateway, it does not open TCP connections.

**Comment by j82w** [comment]
The problem with this design is we have some users that are calling it for ever single time they do an operation on the container. I think the client is still the best approach and avoids users calling it multiple times and consuming all the meta-data throughput.

One alternative would be this but from what I have seen in customer code most people are recreating the container which still results in the previously mentioned problem. 
`Container container = await client.GetContainerAndInitializeAsync("mydb", "mycontainer");`

That why I think the client level is still the best choice.

**Comment by ealsur** [comment]
But even if they do call it for every single call, since the caches are already populated, the subsequent calls would be a no-op?

**Comment by onionhammer** [comment]
This could be improved quite a lot; realistically people aren't running async calls when they're initializing their ServiceProvider; making the `CreateAndInitializeAsync` API quite awkward to use in practice 

@ealsur @j82w @Maya-Painter
