### ISSUE TITLE
SelfHelp: Enrich error message context

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1707]
This issue is to discuss adding additional context the service should add to make troubleshooting various scenarios easier.

This should be returned on all responses
1.    Service execution time included in the header
       a. Used to help determine if latency is from SDK, networking, or Cosmos DB service.

Requires a new header to enable the additional context in the error messages. The order shows the current priority.
1.	Not found Exception
   a.  Resource type (Is it the database or container or document)
   a.	Resource name/id and partition key value 
1.	429 (Throttles)
   a.	Logical (PK, id)  
1.	449
   a.	Logical (PK, id) 
1.	400
   a.	Try to remove any place that throws: One of the specified inputs is invalid
   b.	An example: The token is required to be 10minutes or greater, but nothing explains that.
       1. https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1326
2.	Partition key mismatch
   a.	Partition key value from document
   b.	Partition key value from header

**Comment by boylec** [comment]
It sure would be awesome if this was implemented.
