### ISSUE TITLE
Change Feed Processor: Add support to estimate change feed progress on a per lease basis

### ISSUE THREAD

**Issue by bonz0** [Azure/azure-cosmos-dotnet-v3#1730]
**Is your feature request related to a problem? Please describe.**
I'm testing out the ChangeFeedProcessor library right now and for some reason the ChangeFeedEstimator has been stuck at 20 for a few days. The ChangeFeed seems to be working as expected, but there are 20 pending changes that are stuck somewhere. While it's nice that we can find out about these pending changes on a container level, it would really help if we could find out the pending changes per lease.

**Describe the solution you'd like**
Have a way to estimate pending changes per lease/partition.

**Describe alternatives you've considered**
One way to find the stuck lease would be to monitor the leases container (by possible having change feed running against it) to find the lease that is stuck. But I feel like there should be a simpler way to do this.

**Additional context**
Talked to Matias about this

**Comment by ealsur** [comment]
The ask is to have a similar API as the CFP V2: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.changefeedprocessor.partitionmanagement.iremainingworkestimator.getestimatedremainingworkperpartitionasync?view=azure-dotnet#Microsoft_Azure_Documents_ChangeFeedProcessor_PartitionManagement_IRemainingWorkEstimator_GetEstimatedRemainingWorkPerPartitionAsync

```
public Task<IReadOnlyList<RemainingPartitionWork>> GetEstimatedRemainingWorkPerPartitionAsync ();
```

Since CFP V3 works as a push model, we can introduce it as a new delegate:

```
public delegate Task ChangesEstimationDetailedHandler(
            IReadOnlyList<ChangeFeed.RemainingLeaseTokenWork> estimatedPendingChanges,
            CancellationToken cancellationToken);
```

Where `RemainingLeaseTokenWork` uses the `FeedRange` to identity which range the lease is for:

```
public class RemainingLeaseTokenWork
    {
        /// <summary>
        /// Gets the lease token for which the remaining work is calculated
        /// </summary>
        public FeedRange LeaseToken { get; }

        /// <summary>
        /// Gets the amount of documents remaining to be processed.
        /// </summary>
        public long RemainingWork { get; }
    }
```

**Comment by bonz0** [comment]
Thanks, @ealsur!

I see that you mentioned that `FeedRange` can be used to identify which range the lease is for. I'd like to understand how this would work, though. Would customers be able to look at the `FeedRange` and map that to a certain partition/partition key? And how would they do that? Would they need to look at the lease documents?

**Comment by ealsur** [comment]
Technically, each lease has a `LeaseToken` attribute which is a serialization and would match the `FeedRange.ToString()`. We could also just have it as a string on the `RemainingLeaseWork` too (it would be another design aspect)

**Comment by bonz0** [comment]
I just took a look at the lease documents and I saw the `LeaseToken` attribute - which is simply a stringified number (eg: `"6"`). So the `FeedRange.ToString()` would just be that number then, right?
If that's the case, this makes sense, although, a small recommendation would be to keep the name consistent. So consider changing `RemainingLeaseWork.FeedRange` to `RemainingLeaseWork.LeaseToken` - if that makes sense

**Comment by ealsur** [comment]
After design discussion, it was mentioned that a pull alternative would give the user more control over errors and periodicity of estimations.

With this in mind, the alternative API would be:

1. Container

Add a new API on the container that just takes the `processorName`, and obtains a `ChangeFeedEstimatorBuilder`.
```
public abstract ChangeFeedEstimatorBuilder GetChangeFeedEstimatorBuilder(string processorName);
```

2. ChangeFeedEstimatorBuilder

`ChangeFeedEstimatorBuilder` is a **new public API** that is scoped just to build the Estimator:

```
namespace Microsoft.Azure.Cosmos;

public class ChangeFeedEstimatorBuilder
{
    public ChangeFeedEstimatorBuilder WithLeaseContainer(Container leaseContainer);
   public ChangeFeedEstimator Build();
}
```

Ideally the user would use it like so:

```
ChangeFeedEstimator estimator = container
    .GetChangeFeedEstimatorBuilder(processorName: "test")
    .WithLeaseContainer(leaseContainer).Build();
```

3. ChangeFeedEstimator

`ChangeFeedEstimator` would be a **new public API** that would have the following definition:

```
namespace Microsoft.Azure.Cosmos;

public abstract class ChangeFeedEstimator
    {
        /// <summary>
        /// Calculates an estimate of the pending work remaining to be read in the Change Feed in amount of documents in the whole container.
        /// </summary>
        /// <param name="cancellationToken">(Optional) <see cref="CancellationToken"/> representing request cancellation.</param>
        /// <returns>An estimation of pending work in amount of documents.</returns>
        public abstract Task<long> GetEstimatedRemainingWorkAsync(CancellationToken cancellationToken);

        /// <summary>
        /// Calculates an estimate of the pending work remaining to be read in the Change Feed in amount of documents per distributed lease token.
        /// </summary>
        /// <param name="cancellationToken">(Optional) <see cref="CancellationToken"/> representing request cancellation.</param>
        /// <returns>An array of an estimation of pending work in amount of documents per distributed lease token.</returns>
        public abstract Task<IReadOnlyList<RemainingLeaseWork>> GetEstimatedRemainingWorkPerLeaseAsync(CancellationToken cancellationToken);
    }
```

This would allow the user to manually ask for the estimation in both flavors, including the `GetEstimatedRemainingWorkPerLeaseAsync` which would cover this request.

4. RemainingLeaseWork

```
using Microsoft.Azure.Cosmos;

public class RemainingLeaseWork
    {
        public string LeaseToken { get; }

        public long RemainingWork { get; }

        public string InstanceName { get; }

        public bool IsSuccessfulResponse { get; }

        public CosmosException EstimationError { get: }
    }
```

## How to consume it

```
ChangeFeedEstimator estimator = container
    .GetChangeFeedEstimatorBuilder(processorName: "test")
    .WithLeaseContainer(leaseContainer).Build();
    
    
IReadOnlyList<RemainingLeaseWork> estimation = await estimator.GetEstimatedRemainingWorkPerLeaseAsync();
foreach (RemainingLeaseWork leaseWork in estimation)
{
    if (leaseWork.IsSuccessfulResponse)
    {
        Console.WriteLine($"Lease {leaseWork.LeaseToken}, owned by {leaseWork.InstanceName} has an estimated lag of {leaseWork.RemainingWork}");
    }
    else
    {
        Console.WriteLine($"Error estimating lease {leaseWork.LeaseToken}, owned by {leaseWork.InstanceName}: {leaseWork.EstimationError}");
    }
}
```

**Comment by ealsur** [comment]
Updating thread with the approved design.

The `Container` will have the following public API:

```
ChangeFeedEstimator estimator =  container.GetChangeFeedEstimator(processorName: "test", leaseContainer);
```

Exposing the `ChangeFeedEstimator`:

```
public abstract class ChangeFeedEstimator
{
    public abstract FeedIterator<RemainingLeaseWork> GetRemainingLeaseWorkIterator(ChangeFeedEstimatorRequestOptions);
}
```

The `ChangeFeedEstimator` will have a `GetRemainingLeaseWorkIterator` that will produce an iteration of `RemainingLeaseWork`:

```
public class RemainingLeaseWork
{
    public string LeaseToken { get; }

    public long RemainingWork { get; }

    public string InstanceName { get; }
}
```

The user can then consume this API like:

```
FeedIterator<RemainingLeaseWork> iterator =  estimator.GetRemainingLeaseWorkIterator();

while (HasMoreResults)
{
    FeedResponse<RemainingLeaseWork> leaseWork = await iterator.ReadNextAsync(CancellationToken);
    foreach (RemainingLeaseWork estimation in leaseWork)
    {
        Console.WriteLine($"Lease {estimation.LeaseToken} owned by {estimation.InstanceName} has {estimation.RemainingWork} estimated pending items.");
    }
}
```

**Comment by ealsur** [comment]
@bonz0 can you test the new 3.14.0-preview package and see if the new API solves your issue?
