### ISSUE TITLE
Question: Cross partition search with limited partition range?

### ISSUE THREAD

**Issue by Kesudan** [Azure/azure-cosmos-dotnet-v3#1745]
Is it possible to search for items in a cross partition search, using a limited partition range?

For example..
_Partition strategy: Part1_Part2_Part3_

Using a partition key comprised of 3 forms of identifiers, is it possible to search for items across partitions using only part of a partition key?

PartitionKey = new PartitionKey("Part1_Part2_*")

**Comment by j82w** [comment]
The short answer is no. Partition key gets converted to a hash. Only having a partial value doesn't help as the hash will still be different. There is some work in progress to support multiple partition keys, but I don't have a time frame for it.

The best solution is probably to do a query on the two fields you do know or change the partition key structure to only include values you will always have. https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview
