### ISSUE TITLE
Need consistency between PartitionKey, PartitionKeyPath, and PartitionKeyValue

### ISSUE THREAD

**Issue by mdrichardson** [Azure/azure-cosmos-dotnet-v3#1746]
**Is your feature request related to a problem? Please describe.**

There's some ambiguity in the terms, `PartitionKey`, `PartitionKeyPath`, `PartitionValue` and their usage. I fully understand when and how they're used, but have noticed they're not consistent across the SDK and it causes a little confusion when I try to explain some of this with our customers.

For example, let's say we have a document:

```js
{
  data: <someDataObject>,
  id: '123'
}
```

In [the README for this SDK](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/README.md), it shows:

![image](https://user-images.githubusercontent.com/40401643/89057437-7f7d1f80-d312-11ea-84aa-97875ce0230d.png)

So, I would expect `PartitionKeyPath` to be `/id` and `PartitionKey` to be `'123'`.

However, in the Cosmos Azure Resource > Data Explorer, we have:

![image](https://user-images.githubusercontent.com/40401643/89057584-c5d27e80-d312-11ea-8e81-93a2fe3de458.png)

So, now it looks like `/id` is the `PartitionKey`, so what's the `PartitionKeyPath`? (again, I understand it's really like the first example).

And [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/9a7537318fad949cc6281b359209eb5dea66732f/Microsoft.Azure.Cosmos/src/PartitionKey.cs#L55), we use `PartitionKey` and `PartitionKeyValue`: 

```csharp
public PartitionKey(string partitionKeyValue)
        {
[...]
```

So here, it looks like `PartitionKeyValue` is equivalent to the `PartitionKeyPath` and not the value on the document?

**Describe the solution you'd like**

Personally, I like `ParitionKeyPath` and `PartitionKeyValue`, as that matches the typical `key/value` object pairing.

Regardless, I think there needs to be both consistency and clarity across the SDK, Docs, and Azure Data Explorer GUI.

**Comment by ealsur** [comment]
PartitionKeyPath is the path within a Json document to reach the PartitionKey.

So in this example:
```
Container container = await database.CreateContainerIfNotExistsAsync(
    "MyContainerName",
    "/someAttributeName",
    400);
```

This creates a container where the Partition Key path is `/someAttributeName` and where documents are expected to have a `someAttributeName` attribute. The Partition Key value or Partition Key is the actual value for a given document, of such property.

```
{
  data: <someDataObject>,
  id: '123',
  someAttributeName: 10
}

{
  data: <someDataObject>,
  id: '123',
  someAttributeName: 20
}
```

Are two different documents, where the first one has a Partition Key of 10 and the second one has a Partition Key of 20.

**Comment by mdrichardson** [comment]
@ealsur 

Should this not say "Partition Key Path", then? I think this is where a lot of confusion stems from:

![image](https://user-images.githubusercontent.com/40401643/89079272-eadae780-d33a-11ea-877c-38140163f90a.png)

I feel like since they're basically the same thing, even nested: `/country/state/county` vs `country.state.county`, they "should" be called the same thing. Does the Cosmos team just use them interchangeably?

**Comment by ealsur** [comment]
I understand the confusion and probably the Portal should say "Partition key path" too, since it is the actual Json path (not a value).
