### ISSUE TITLE
Azure.Cosmos Version=4.x

### ISSUE THREAD

**Issue by crazyiter** [Azure/azure-cosmos-dotnet-v3#1747]
System.Reflection.ReflectionTypeLoadException:“Unable to load one or more of the requested types.
Method 'RecordRequest' in type 'Microsoft.Azure.Cosmos.CosmosClientSideRequestStatistics' from assembly 'Azure.Cosmos, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'UpdateAsync' in type 'Microsoft.Azure.Cosmos.Routing.GlobalAddressResolver' from assembly 'Azure.Cosmos, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'UpdateAsync' in type 'Azure.Cosmos.AddressResolver' from assembly 'Azure.Cosmos, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'UpdateAsync' in type 'Azure.Cosmos.AddressResolver' from assembly 'Azure.Cosmos, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'UpdateAsync' in type 'Azure.Cosmos.AddressResolver' from assembly 'Azure.Cosmos, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'UpdateAsync' in type 'Azure.Cosmos.AddressResolver' from assembly 'Azure.Cosmos, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'UpdateAsync' in type 'Azure.Cosmos.AddressResolver' from assembly 'Azure.Cosmos, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.”
![image](https://user-images.githubusercontent.com/45249055/89138516-6ffa1280-d56e-11ea-9717-c36257a924c6.png)

**Comment by ealsur** [comment]
Can you explain a bit more what is "Scan" and what does it do? 
Are you using Nuget references or are you manually referencing DLLs? 
Do you have project references and are you using the same Nuget version across all of them?

**Comment by ealsur** [comment]
Closing, please reopen with the requested information to help troubleshoot.
