### ISSUE TITLE
Slow query performance when using STRINGEQUALS on document ids

### ISSUE THREAD

**Issue by cowlinb6** [Azure/azure-cosmos-dotnet-v3#1749]
I've found that there seems to be a significant differences in terms of the amount of RUs used when using STRINGEQUALS within a query.

I have a collection with 5 million records, using the default indexing policy and partitioned using property called pid. The documents stored are referenced by a string field called id.

Using the example below. 

Query 1: This uses STRINGEQUALS and used 4950RUs
Query 2: This uses = and used 2.87RUs

I've performed these tests using the Data Explorer in the Azure Portal.

Query 1
SELECT * FROM c WHERE (STRINGEQUALS(c.id, 'd2f545f1-2dee-483a-8f5a-e15cfde8c9b5', true))

Results 1
METRIC |   | VALUE
-- | -- | --
Request Charge |   | 4950.62 RUs
Showing Results |   | 1 - 1
Retrieved document count |   | 1
Retrieved document size |   | 2477 bytes
Output document count |   | 1
Output document size |   | 2575 bytes
Index hit document count |   | 1
Index lookup time |   | 1722.13 ms
Document load time |   | 0.060000000000000005 ms
Query engine execution time |   | 0.1 ms
System function execution time |   | 0 ms
User defined function execution time |   | 0 ms
Document write time |   | 0 ms
Round Trips |   | 1

Query 2
SELECT * FROM c WHERE c.id = 'd2f545f1-2dee-483a-8f5a-e15cfde8c9b5'

Results 2
METRIC |   | VALUE
-- | -- | --
Request Charge |   | 2.87 RUs
Showing Results |   | 1 - 1
Retrieved document count |   | 1
Retrieved document size |   | 2477 bytes
Output document count |   | 1
Output document size |   | 2526 bytes
Index hit document count |   | 1
Index lookup time |   | 0.15 ms
Document load time |   | 0.07 ms
Query engine execution time |   | 0.030000000000000002 ms
System function execution time |   | 0 ms
User defined function execution time |   | 0 ms
Document write time |   | 0 ms
Round Trips |   | 1

**Comment by bchong95** [comment]
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-stringequals

Case insensitive search is not going to be as performant as a case sensitive search.

You can write the query as:

`SELECT * FROM c WHERE (STRINGEQUALS(c.id, 'd2f545f1-2dee-483a-8f5a-e15cfde8c9b5', false))`

or 

`SELECT * FROM c WHERE (STRINGEQUALS(c.id, 'd2f545f1-2dee-483a-8f5a-e15cfde8c9b5'))`

to make it an apples to apple comparison.
