### ISSUE TITLE
CreateContainerIfNotExistsAsync Crashes without exception when running in xUnit

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#175]
**Describe the bug**
Using the local emulator or azure instance, CreateContainerIfNotExistsAsync crashes out the xUnit application without any exception. The offending line is in TransportHandler.cs line 87. The same code runs fine in a Console application

**To Reproduce**
```
using (var client = new CosmosClient("AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="))
{
    var database = await client.Databases.CreateDatabaseIfNotExistsAsync(_databaseId);
}
```

**Expected behavior**
At a minimum some exception

**Actual behavior**
Blows out the application

**Environment summary**
SDK Version: NetCore 3.0.100-preview5-011363 with Cosmos source
OS Version Windows

**Comment by j82w** [comment]
Closing this since there has been no updates. Please reopen if it still an issue.

**Comment by crgarcia12** [comment]
+1 CreateDatabaseIfNotExistsAsync can hang forever, or crash with no exception
