### ISSUE TITLE
CreateItemAsync object serializing causes "Specified input is invalid" or "required properties - 'id; ' - are missing" or "PartitionKey extracted from document doesn't match"

### ISSUE THREAD

**Issue by romerve** [Azure/azure-cosmos-dotnet-v3#1762]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When creating items in a container using CosmosContainer.CreateItemAsync(), and passing a serializable object that does not explicitly contains lower case "id" property, an unhandled exception is thrown:
`Reason: (Message: {"Errors":["The input content is invalid because the required properties - 'id; ' - are missing"]}`

if the [JsonPropertyName("id")] attribute is added to the property and System.Text.Json.Serialization is used to serialize the object in order to transform the object property "id" (lower case vs whatever other name or case), an unhandled exception is also thrown:
`Reason: (Message: {"Errors":["One of the specified inputs is invalid"]}` 

Also applies to partition key if the property doesnt match the expected case 
`Reason: (Message: {"Errors":["PartitionKey extracted from document doesn't match the one specified in the header"]}`

**To Reproduce**
Create any item with an object that uses an ID property that does not match Cosmos DB expected "id"
``` csharp
public class Heroe
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("location")]
        public string Location { get; set; }
    }

----------------------

FAILS: await this._container.CreateItemAsync(JsonSerializer.Serialize(heroe), new PartitionKey(heroe.Location));

```

**Expected behavior**
CreateItemAsync() respects System.Text.Json.Serializer

**Actual behavior**
CreateItemAsync() ignores [JsonPropertyName]

**Environment summary**
SDK Version:   3.1.302
Commit:    41faccf259
OS Version: MacOSX 10.15

**Comment by j82w** [comment]
@romerve there is a few issues with your example. JsonSerializer.Serialize returns a string. Then newtonsoft is trying to serialize that string.

Solution 1:
Use the [CosmosClientOptions.CosmosSerializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/4411655cee17aa1eac54e36c3b931f6b78826c26/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L417) to override the default Newtonsoft behavior. This prevents you from needing to put custom logic for each method. [Here is an example](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/Serializer/CosmosTextJsonSerializer.cs)  of how to implement it.

Solution 2:
Use the stream APIs to pass in the serialized content.
```c#
await using MemoryStream streamPayload = new MemoryStream();
            await using Utf8JsonWriter utf8JsonWriter = new Utf8JsonWriter(streamPayload);
            JsonSerializer.Serialize<Heroe>(utf8JsonWriter, heroe);
            streamPayload.Position = 0;
            using ResponseMessage responseMessage = await container.CreateItemStreamAsync(streamPayload, new PartitionKey(heroe.Location));
            responseMessage.EnsureSuccessStatusCode();
            Heroe heroeResponse = await JsonSerializer.DeserializeAsync<Heroe>(responseMessage.Content);
```
