### ISSUE TITLE
Going from SerializerOptions to a custom Serializer makes it impossible to read the data back

### ISSUE THREAD

**Issue by kawazoe** [Azure/azure-cosmos-dotnet-v3#1782]
**Describe the bug**
I started a project using the following `CosmosClientOptions`:

```
new CosmosClientOptions
{
    ConnectionMode = ConnectionMode.Gateway,
    SerializerOptions = new CosmosSerializationOptions
    {
        PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
    },
}
```

But eventually, I needed more control over the serialization of my data so I switched to a custom serializer:
```
new CosmosClientOptions
{
    ConnectionMode = ConnectionMode.Gateway,
    Serializer = new CustomCosmosSerializer()
}
```

Since then, all queries that require composite indexes fail with missing indexes. It looks like the database thinks that my properties are in PascalCase. Changing my indexes to pascal case and trying the queries again yields empty arrays to my serializer instead of triggering an error. It never gets a chance to deserialize any data.

I suspect that my serializer is not used for metadata queries on the Database and Collection objects and cannot participate in the serialization of the query itself. This means that I lost to ability to use LINQ to request objects with camel case properties. Since I cannot use both `SerializerOptions` and `Serializer` at the same time to control that internal serializer, I have no way to work around this issue without rewriting a large chunk of code and adding attributes everywhere, which is what I was trying to avoid by using my own serializer in the first place.

**To Reproduce**
- Create a command-line app that connects to CosmosDb by setting the PropertyNameingPolicy to camel case like in the previous snippet.
- Use the client to create some documents.
- Create a query using the following form to force the use of a composite index:
```
container.GetItemLinqQueryable<T>()
    .OrderBy(c => c.Prop1)
    .ThenBy(c => c.Prop2)
```

- After validating that it does return some results replace the `SerializerOptions` property with the second snippet, using the following dummy serializer:
```
public class DummyJsonCosmosSerializer : CosmosSerializer
    {
        public override T FromStream<T>(Stream stream)
        {
            return default;
        }

        public override Stream ToStream<T>(T input)
        {
            return new MemoryStream();
        }
    }
```

**Expected behavior**
The stream passed to the serializer should contain the same set of results as if I was using `SerializerOptions`. In other words, the use of a custom serializer should not change the outcome of the query and the serializer should see the same data in the stream in both scenarios.

**Actual behavior**
The internal serializer reverts to pascal case causing queries that depends on custom indexes (like an `OrderBy().ThenBy()` query) to fail with the following message: `BadRequest (400) - The order by query does not have a corresponding composite index that it can be served from.` Queries that do not require specialized indexes will simply call the serializer with an empty array all the time.

This means that it is currently impossible to switch between `SerializerOptions` with camel case and a custom `Serializer` without dumping the database and recreating it from scratch and converting all custom indexes.

**Environment summary**
SDK Version: 3.12.0
OS Version (e.g. Windows, Linux, MacOSX) Windows 10 build 1909

**Notes**
I feel like most of this could be avoided if both properties could be used at the same time. At least, I would still be able to read my data and it would be up to me to ensure that my serializer is compatible with the `SerializerOptions`. The best case scenario would be to use the custom serializer everywhere, but I'm sure there is a reason why it isn't the case already.

Also, no data is lost in this process. You can always switch back to the old version of the code and get everything working again... As long as no documents have been written with the new serializer before you notice that you can't read anything back. Those documents will probably have to be hand-edited to read them with `SerializerOptions` again. I haven't tried this scenario.

**Comment by j82w** [comment]
I see the following solutions to the problems.

1. Allow both SerializerOptions and CosmosSerializer to be set at the same time. It's up to the user to make sure they are in sync.
2. Add SerializerOptions as a public property onto CosmosSerializer. This would make it more obvious that the user should change the setting based on the customer serializer.

I'm leaning more toward option 1 as it prevents adding a new property to the cosmos serializer, and gives the same benefits.

@kirankumarkolli , @ealsur, @FabianMeiswinkel  what do you think?

**Comment by FabianMeiswinkel** [comment]
I am fine with both approaches - my personal preference would be #2 because I would expect it to avoid confusion around what has precedence when allowing to specify both.

**Comment by kawazoe** [comment]
I am not convinced about option 2. As stated, it feels a little confusing to me. Do you mean that I would have to use this property to correctly configure my own serializer? Or do you mean that I should expose my configuration through this property to configure the system serializer?

If it's the first case, I feel like this is just like option 1, but a little bit more explicit. You would still need to be able to set those values somewhere.
If it's the second one, I would think that it might still be confusing for people since you still have the `SerializerOptions` property on `CosmosClientOptions`.

As an experienced user though, I am ok with both options.

**Comment by MITIN33** [comment]
@j82w when i try to set both Serilazer and SerializerOption it throws ArgumentException -"'SerializerOptions is not compatible with Serializer. Only one can be set. "'

**Comment by mikanyg** [comment]
I have a similiar issue where my queries using linq provider works when just setting the CosmosSerializationOptions and stops working when setting a CustomSerializer instead.
I setup up the custom CosmosSerializer using the fluent CosmosClientBuilder API, where a CosmosClient is registered in the IServiceCollection.
I tried adding a serializer with an exact copy of the code from `CosmosJsonDotNetSerializer` and registering it as a CustomSerializer called `MyCosmosJsonDotNetSerializer`.
All my integration test executing queries (using Linq synax) started failing.

working code:
``` csharp

return new CosmosClientBuilder(cosmosConstring)
    .WithSerializerOptions(new CosmosSerializationOptions { PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase })
    .Build();
```

not working code:
``` csharp

return new CosmosClientBuilder(cosmosConstring)
   .WithCustomSerializer(new MyCosmosJsonDotNetSerializer(new CosmosSerializationOptions { PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase }))
    .Build();
```

So now I have to rewrite all my queries from Linq syntax to Sql syntax, as I have a need to use a custom serializer using Converters.

**Comment by j82w** [comment]
Please try using [3.17.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.17.0) nuget.

**Comment by BrandonWilliamsCS** [comment]
@j82w I must insist that this issue is NOT solved. The linked PR provides a workaround, not a solution. Further, it's not even an *obvious* or even *well-documented* workaround! The documentation acts as if the new argument is there to *override* options, but the truth is that (when using a custom Serializer) we must use this argument to provide any options whatsoever.

As @kipusoep mentioned, what we actually need is a way to define these options in the same place as we define the custom serializer, as both need to behave the same way. Having to repeat the configuration for every linq query is problematic.

The two suggestions presented in the original question will do the job perfectly, so please reopen this issue and consider one of the proposed solutions.

**Comment by kipusoep** [comment]
Yes, what @BrandonWilliamsCS says.

**Comment by refex** [comment]
I'm facing the same issue years later, come on...

**Comment by refex** [comment]
I eventually solved it by passing a `DefaultContractResolver` with a `NamingStrategy` to my `CustomCosmosSerializer`

```C#
var serializerSettings = new JsonSerializerSettings
{
    Converters = 
    {
        new CustomJsonConverter()
    },
    ContractResolver = new DefaultContractResolver
    {
        // this is a replacement of PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
        NamingStrategy = new CamelCaseNamingStrategy()
    }
};
new CosmosClientOptions
{
    ConnectionMode = ConnectionMode.Gateway,
    Serializer = new CustomCosmosSerializer()
}
```
