### ISSUE TITLE
How do I patch a large JSON document in Cosmos (something similar to T-SQL UPDATE) ?

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-cosmos-dotnet-v3#1785]
**Is your feature request related to a problem? Please describe.**
I have a Cosmos database with hundreds of documents and each document is over 2 KB. We have added a new application feature and as a result of which  there is a need to update a certain fragment in the JSON or add a new fragment to the JSON.

## Scenario 1- Update
In the following example, I would like to update the `city` of all records from LDN to LONDON
```
{
 "firstname":"John",
 "lastname":"Doe",
 "city":"LDN"
}
```

## Scenario 2 - Add new fields
In the following example, I would like to insert the `country` field to all records to GB and `region` to 'WEST  EUROPE`
```
{
 "firstname":"John",
 "lastname":"Doe",
 "city":"LDN",
 "country":"GB",
 "region":"WEST EUROPE"
}
```

**Describe the solution you'd like**
Something similar on the lines of T-SQL but relevant for JSON. 
E.g. 
```
update Customers c where c.city="London" set "$.country="GB" , set "$.region="WEST EUROPE"
```

**Describe alternatives you've considered**
I have had to write C# code on a case by case basis. In my code, I am having to deal with the JSON manipulation. This has become very burdensome when compared with how easy such a scenario would have been in the MSSQL world.

**Comment by j82w** [comment]
Currently the best solution would be to use to [Stored Procedures](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-write-stored-procedures-triggers-udfs). Here are the v3 samples: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c074f97fc952d39b34829e1b371c05de585647ed/Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/Program.cs#L108

**Comment by sdg002** [comment]
What about the Bulk executor library that is documented here?
https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-dot-net#bulk-update-data-in-your-azure-cosmos-account

The snippet of code appears to demonstrate a scenario resembling my requirements, i.e. do partial updates on the JSON. 
```
SetUpdateOperation<string> nameUpdate = new SetUpdateOperation<string>("Name", "UpdatedDoc");
UnsetUpdateOperation descriptionUpdate = new UnsetUpdateOperation("description");

List<UpdateOperation> updateOperations = new List<UpdateOperation>();
updateOperations.Add(nameUpdate);
updateOperations.Add(descriptionUpdate);

List<UpdateItem> updateItems = new List<UpdateItem>();
for (int i = 0; i < 10; i++)
{
 updateItems.Add(new UpdateItem(i.ToString(), i.ToString(), updateOperations));
}
```

Or, am I strectching my imagination too far?

Thank you

**Comment by ealsur** [comment]
Bulk Executor Library has a BulkUpdate API true, but this is just a wrapper of the following:

* Read the entire document.
* Apply the UpdateOperation
* Replace the entire document

There is no real partial update, it's just wrapping a set of operations you can do yourself.

**Comment by sdg002** [comment]
Understood. Thank you.

**Comment by ealsur** [comment]
This would probably be possible once Patch support is live https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1616

**Comment by iamalexmang** [comment]
@ealsur, since #1616 is merged, do we now have patch support working? And if so... how does it work?

**Comment by ealsur** [comment]
@iamalexmang That PR adds the APIs but it's internal, this means the feature is not yet ready for public consumption / preview, when it is, it will be announced through the change log (and another PR would mark the APIs public). Documentation would also be provided then for user consumption, but the original PR has a rough example of the usage.

**Comment by stuartleeks** [comment]
What is the ETA for this feature being publicly available?

**Comment by j82w** [comment]
This is GA as of [3.23.0](https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.23.0)
