### ISSUE TITLE
[QUERY] How do I determine the size of an existing container?

### ISSUE THREAD

**Issue by daveoshinsky** [Azure/azure-cosmos-dotnet-v3#1792]
Is there an API in v3 SDK to determine the size of an existing container?

[This page](url) alludes to using documentsSize in container response header to obtain the sum total size of the documents in a container.

I have tried code like the following with 3.7.0-preview3 and 3.13.0-preview, but the output of the code always shows the value of the header as the name of the header.

Code:
                ContainerRequestOptions cro = new ContainerRequestOptions();
                cro.PopulateQuotaInfo = true;
                ContainerResponse cr = container.ReadContainerAsync(requestOptions: cro).GetAwaiter().GetResult();
                Headers headers = cr.Headers;
                ContainerProperties cp = cr.Resource;
                Console.WriteLine("Headers '{0}' properties '{1}'", headers.ToString(), cp.ToString());
                foreach (string header in headers)
                {
                    string value;
                    headers.TryGetValue(header, out value);
                    Console.WriteLine("header '{0}' value '{0}'", header, value);
                }

Output:
Headers 'Microsoft.Azure.Cosmos.Headers'
header 'x-ms-request-charge' value 'x-ms-request-charge'
header 'x-ms-activity-id' value 'x-ms-activity-id'
.....
header 'x-ms-resource-quota' value 'x-ms-resource-quota'
header 'x-ms-resource-usage' value 'x-ms-resource-usage'
.....
header 'Content-Location' value 'Content-Location'

Why is the value the same as the header name (key=value)?  How do I see the actual total documents size?  I have also tried headers.GetValueOrDefault() and other methods, but all show key=value.

**Comment by ealsur** [comment]
This works:

```
ContainerRequestOptions cro = new ContainerRequestOptions();
            cro.PopulateQuotaInfo = true;
            ContainerResponse cr = await container.ReadContainerAsync(cro);
            Headers headers = cr.Headers;
            foreach (string key in headers.AllKeys())
            {
                Console.WriteLine($"{key}: {headers[key]}");
            }
```

![image](https://user-images.githubusercontent.com/1633401/90791369-f5dfc280-e2bd-11ea-8fec-6257324782ea.png)

**Comment by daveoshinsky** [comment]
Thanks Matias!
