### ISSUE TITLE
PartitionKey is not respected in the GetChangeFeedStreamIterator method in v 3.13.0-preview

### ISSUE THREAD

**Issue by MariaCobretti** [Azure/azure-cosmos-dotnet-v3#1796]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
when you try to read the change feed with the pull model and specify a partition key, you get the changes over the whole collection

**To Reproduce**
var feedRange = FeedRange.FromPartitionKey(new PartitionKey(x));
var feedIterator = Container.GetChangeFeedStreamIterator(ChangeFeedStartFrom.Time(from, feedRange));

it is working in version 3.11.0-preview

**Environment summary**
SDK Version: 3.13.0-preview

**Comment by j82w** [comment]
This should be fixed now. Please re-open if it still an issue.
