### ISSUE TITLE
Failed to compile the Microsoft.Azure.Cosmos project

### ISSUE THREAD

**Issue by leixnj** [Azure/azure-cosmos-dotnet-v3#180]
After clone the zure-cosmos-dotnet-v3 project, VS2017 reports failure to compile the project,  without any definition for PartitionAddressInformation class. how do we solve that? or am I missing some library? I check the SDK folder, NETStadard 2.0.3 was installed. 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0738	'AddressResolver' does not implement interface member 'IAddressResolver.ResolveAsync(DocumentServiceRequest, bool, CancellationToken)'. 'AddressResolver.ResolveAsync(DocumentServiceRequest, bool, CancellationToken)' cannot implement 'IAddressResolver.ResolveAsync(DocumentServiceRequest, bool, CancellationToken)' because it does not have the matching return type of 'Task<AddressInformation[]>'.	Microsoft.Azure.Cosmos	D:\OpenSource\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\src\Routing\AddressResolver.cs	25	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'PartitionAddressInformation' could not be found (are you missing a using directive or an assembly reference?)	Microsoft.Azure.Cosmos	D:\OpenSource\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\src\Routing\AddressResolver.cs	55	Active

**Comment by simplynaveen20** [comment]
Please check that your project downloaded library  "Microsoft.Azure.Cosmos.Direct" correctly .Try deleting it from your .nuget directory and build your sln again.

**Comment by simplynaveen20** [comment]
There is an issue , working on it , please wait for the update

**Comment by j82w** [comment]
Here is a [PR ](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/182) fixing the issue.

**Comment by leixnj** [comment]
cool,  j82w

**Comment by kirankumarkolli** [comment]
#182

**Comment by leixnj** [comment]
verified, bug was fixed.
