### ISSUE TITLE
STRINGEQUALS does not work correctly on null values

### ISSUE THREAD

**Issue by mywyb2** [Azure/azure-cosmos-dotnet-v3#1800]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
`STRINGEQUALS(null, null)` returns undefined. The workaround is cumbersome and potentially RU-expensive, having to write something like this in order to compare two case-insensitive properties:

`... WHERE ((c.a ?? null) = null AND (c.b ?? null) = null)) OR STRINGEQUALS(c.a, c.b, true)`

**To Reproduce**
Run the SQL query:
`SELECT VALUE (STRINGEQUALS(null, null))`

**Expected behavior**
`STRINGEQUALS(null, null)` should return true. Even better if additionally `STRINGEQUALS(undefined, undefined)` returns true.

**Actual behavior**
`STRINGEQUALS(null, null)` returns undefined.

**Comment by timsander1** [comment]
@ginamr @bchong95 @sboshra 

Should comparisons of null values with STRINGEQUALS return true to be consistent with other equality comparisons documented here? https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-operators

**Comment by bchong95** [comment]
I think it is consistent. StringEquals first tries to cast the JSON value to a string, but it sees a JSON null the function returns undefined.

**Comment by timsander1** [comment]
This is not consistent with how an equality comparison (without a system function) would work. In that case, we'd return true if you compare two null values. Shouldn't StringEquals be the same?

**Comment by wahyuen** [comment]
Because in 2023 we need to waste hours on this issue because Microsoft expose idiosyncrasies of how the service work instead of just implementing principal of least astonishment and having equality of nulls work as someone would expect.

**Comment by patroza** [comment]
yes this is super frustrating, similarly
`LOWER(x.x) <> "a"` doesn't return null or missing but
`x.x <> "a"` does.
