### ISSUE TITLE
Coalesce operator (??) does not work on null values

### ISSUE THREAD

**Issue by mywyb2** [Azure/azure-cosmos-dotnet-v3#1802]
**Describe the bug**
`undefined ?? "foo"` is `"foo"` but `null ?? "foo"` is `null`.

**To Reproduce**
Run queries with coalesce operator in Data Explorer.

**Expected behavior**
Either `null ?? "foo"` should return `"foo"`, or alternatively there should be another null-coalesce operator.

**Comment by timsander1** [comment]
Undefined and null are different values. If a property has a value of null that it has a defined value (the value of the property is null). This is different from a property being omitted from an item and having undefined value. This is the correct behavior and not a bug.

**Could you ternary operator (with equality filter for null) for this use case?** 

Something like: 

SELECT (c.myValue = null) ? "myValue is null": "myValue is not null" AS myValue
FROM  c

Learn more: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-operators#-and--operators

**Comment by mywyb2** [comment]
I know that undefined and null are different values in Cosmos DB. It’s just that a coalesce operator for null is missing, so for a very common use case, you have to write something clumsy like

 

(c.myValue ?? null) = null ? “fallback” : c.myValue

 

instead of 

 

c.myValue ?? “fallback”

 

or, if you insist on “??” coalescing only undefined and not null, by having a separate null-coalesce operator “???”:

 

c.myValue ?? null ??? “fallback”

 

Another problem with the current semantics of “??” is that the LINQ to SQL translation in the SDKs translate C#’s null coalesce operator into Cosmos DB’s undefined-coalesce operator, a trap that I’m sure many developers will fall into.

 

Von: Tim Sander <notifications@github.com> 
Gesendet: Montag, 31. August 2020 20:50
An: Azure/azure-cosmos-dotnet-v3 <azure-cosmos-dotnet-v3@noreply.github.com>
Cc: mywyb2 <moritz.becker@gatesscholar.org>; Author <author@noreply.github.com>
Betreff: Re: [Azure/azure-cosmos-dotnet-v3] Coalesce operator (??) does not work on null values (#1802)

 

Undefined and null are different values. If a property has a value of null that it has a defined value (the value of the property is null). This is different from a property being omitted from an item and having undefined value. This is the correct behavior and not a bug.

Could you ternary operator (with equality filter for null) for this use case?

Something like:

SELECT (c.myValue = null) ? "myValue is null": "myValue is not null" AS myValue
FROM c

Learn more: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-operators#-and--operators

**Comment by roji** [comment]
One good reason to introduce a null-coalescing operator (or function), is that the conditional operator solution causes double evaluation of the value being coalesced: `x == null ? y : x` evaluates x twice when it is non-null, and if x is expensive to evaluate (e.g. a complex scalar subquery), that can be quite a problem.

It's probably possible to work around this by lifting x out via a JOIN, and referencing the JOIN ailas in the conditional operator, but that seems like an overly elaborate solution to this relatively simple (and probably common) problem.
