### ISSUE TITLE
How to delete a document without PartitionKey value

### ISSUE THREAD

**Issue by lommez** [Azure/azure-cosmos-dotnet-v3#1807]
Is possible to delete a document without the partitionkey value?

In older SDK, it could be used like this:
new PartitionKey(Undefined.Value)

**Comment by j82w** [comment]
Does your Document have a partition key?
If No, then PartitionKey.Undefined
If Yes, then there is a way but it's very expensive and slow. You should really change your data model so you know both values.

**Comment by lommez** [comment]
My document was built in a wrong way, the partitionkey is defined but not used, the value is always null.
In older sdk library it was possible to delete without the partitionkey.
The PartitionKey.Undefined is defined in the new CosmosDB SDK Library
In the new SDK i didnt find a way to delete a document without the partitionkey value

**Comment by j82w** [comment]
@lommez I just realized that I made a mistake. There is a [PartitionKey.None](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d48fb274e84f00a965dacd53028f3623be457365/Microsoft.Azure.Cosmos/src/PartitionKey.cs#L22) which is the same as Undefined and [PartitionKey.Null](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d48fb274e84f00a965dacd53028f3623be457365/Microsoft.Azure.Cosmos/src/PartitionKey.cs#L28).


await this.Container.DeleteItemAsync<ToDoActivity>(partitionKey: PartitionKey.None, id: itemId)

**Comment by lommez** [comment]
Thanks so much @j82w
It works perfectly

**Comment by mikocot** [comment]
@j82w PartitionKey.None is meant to represent unknown (any) value of the partition key, effectrively running across all partitions, or it's only used for cases where for some reasons PK was never set? 

I keep getting NotFound results when using PartitionKey.None, if partition key was set on a record and I don't see any other way to delete such record otherwise (unless I first query it and find the PK value).

**Comment by kirankumarkolli** [comment]
CosmosDB started with non-partitioned collations/containers. 
Now every collection is now logically treated as partitioned. 
- For migrated collections all the data will be with partition  key `ParitionKey.None`
- Any changes(Create, update, delete) demands a partition-key explicitly and `ParitionKey.None` can be used for such collections
