### ISSUE TITLE
Change Feed support for deleted items

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-dotnet-v3#1808]
If I remember correctly, this was mentioned on User Voice. Can you please give us an update on where you're at? I'd like my deleted items to be seen by Change Feed. Right now, I use a soft delete flag, but this creates issues when I need the item to be unique in a logical partition. I can't add a new item with the same partition key and id while there is a soft deleted item with the same partition key and id. I need to wait until Change Feed removes the soft deleted item, so there is incurred latency which forces the user to wait before they can create a new item.

**Comment by ealsur** [comment]
This is not related to the SDK but it's a product feature, see https://azure.microsoft.com/en-us/updates/change-feed-with-full-database-operations-for-azure-cosmos-db/. This new feature, when released, will be supported by the SDK.

**Comment by petro2050** [comment]
@ealsur This is great to hear. Can you give us some ETA on when to expect this? In the article, it's mentioned to arrive in the coming months, and the article was published in May. I'd really like to get full auditing support with Cosmos DB before going to production for the first time.

**Comment by ealsur** [comment]
I don't have any ETAs at this point, @timsander1 do you have any information regarding the roadmap of Full Fidelity?

**Comment by timsander1** [comment]
Hi @petro2050, this is coming soon early this fall. At that time, it will be a preview feature.

**Comment by petro2050** [comment]
Thanks!

**Comment by sdg002** [comment]
@timsander1  Would you have any recent updates on this front ?

Thank you.

**Comment by timsander1** [comment]
Thanks for checking in. Work on this feature is still in-progress. We will post updates here: https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/38873458-delete-notifications-for-change-feed
