### ISSUE TITLE
Database.ReadProvisionedThroughputAsync throws if no container exists in the DB

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#181]
Database read throughput throws an exception if no container exists in the database. It should just return the 10,000RUs.
```
 // An object containing relevant information about the response
CosmosDatabase database = await client.Databases.CreateDatabaseIfNotExistsAsync(databaseId, 10000);

// Get the current throughput for the database
 int? throughput = await database.ReadProvisionedThroughputAsync();
```

CosmosRequestException;StatusCode=BadRequest;SubStatusCode=0;ActivityId=0fef9c2b-d6ff-480c-8307-301b7eb89ad8;RequestCharge=0;Message=Message: {"Errors":["There are no collections using the shared database offer. Please retry the scale operation after creating a collection that uses database offer"]}

**Comment by simplynaveen20** [comment]
Throughput api changed in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/402
