### ISSUE TITLE
Date and time functions support

### ISSUE THREAD

**Issue by lbicknese** [Azure/azure-cosmos-dotnet-v3#1810]
The current v3 SDK does not support all [date and time functions](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-date-time-functions). The following functions are not supported:

- [GetCurrentTicks](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-getcurrentticks)
- [DateTimePart](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-datetimepart)
- [DateTimeToTicks](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-datetimetoticks)
- [TicksToDateTime](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-tickstodatetime)

I receive the following error(s) when running the sample queries provided in the links above:

```
Exception thrown: 'Microsoft.Azure.Cosmos.CosmosException' in System.Private.CoreLib.dll: 'Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"errors":[{"severity":"Error","location":{"start":7,"end":22},"code":"SC2005","message":"'GetCurrentTicks' is not a recognized built-in function name."}]}
```

I would like the SDK to be updated to support these methods.

Currently, I am using string functions to manipulate dates. This is less than ideal, and would prefer to use the date and time functions. I am able to run the queries with these methods through Data Explorer. I have tested on versions 3.12.0 and 3.13.0-preview.

**Comment by timsander1** [comment]
@j82w these new system functions were released back in July (0701 train). What's the timeline for the next SDK release that will support them?

**Comment by william-liebenberg** [comment]
Hi @j82w  

Just tried the 3.13.0-preview release and none of the mentioned date functions from the OP work.

Is there another release coming for that?

Thanks

**Comment by j82w** [comment]
The release is planned for next week.

**Comment by j82w** [comment]
@william-liebenberg please try [3.13.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.13.0)

**Comment by william-liebenberg** [comment]
Hi @j82w 

Confirmed :) its working nicely. 

Thanks.
