### ISSUE TITLE
Tuple support

### ISSUE THREAD

**Issue by iamalexmang** [Azure/azure-cosmos-dotnet-v3#1814]
Hi,

Often enough I find myself in the position of querying for an item (or list of items). What I don't want to do is define a class containing the documents' properties to be able to deserialize the information properly.
Ideally, I would be able to query the data of a single item (using the `ReadItemAsync<T>` method) or a number of items (using a query), but retrieve back something defined as a tuple.

For example, if I'd have a reusable method to query for items (which I typically do because I create testable business-bound services), I would end up writing something like this.

```
public async Task<T> ReusableGetItem<T>(string partition, string id)
{
  var response = await container.ReadItemAsync<T>(
    partitionKey: new PartitionKey(partition),
    id: id);
  return response.Resource;
}
```

In such a scenario, I'd love to be able to use the method using:
```
var document = await ReusableGetItem<(string PropA, string PropB)>("partitionKey", "documentId");
```

If I'd do this, this would even allow me to quickly get a single property back (on the client side):
```
var documentAttribute = (await ReusableGetItem<(string PropA, string PropB)>("partitionKey", "documentId").PropB);
```
In my opinion, this would be super cool and would save me from creating single-use classes which are just boilerplate.

**Comment by ealsur** [comment]
The `T` used in `ReadItemAsync` is used with Newtonsoft.Json serializer, so it is really tied to Newtonsoft.Json support for Tuples.

You can either implement your own custom serializer and handle Tuple mapping yourself, handle it by a JsonConverter, or even use `ReadItemAsync<dynamic>` and have some helper that maps the Tuple property names with `dynamic` properties.
