### ISSUE TITLE
Group By Produces Inconsistent Counts

### ISSUE THREAD

**Issue by tsharp** [Azure/azure-cosmos-dotnet-v3#1815]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When retrieving record counts directly the results are different than expected. If I run the query through the query explorer in azure storage or in the browser vs running the same query via the sdk in .net core I get two different record counts.

**To Reproduce**
1. Create database
2. Create container
3. populate container with ~2k items with 2 different partition keys
4. Run following sql query to get count in c#
SELECT VALUE COUNT(1) FROM (SELECT root.id FROM root WHERE (root["dateField"] <= "2020-08-28T15:50:12.9709035+00:00") and root.partitionKey = 'key0' GROUP BY root.id) as c

The count will be different than when run in storage explorer.

**Expected behavior**
Same counts returned in both.

**Actual behavior**
Different counts are observed.

**Environment summary**
SDK Version: 3.12.0
OS Version (e.g. Windows, Linux, MacOSX)
Windows & Linux

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by timsander1** [comment]
Queries with an aggregate system function and a subquery with GROUP BY are not supported in Cosmos DB. Learn more here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-group-by

**Comment by bchong95** [comment]
@tsharp the workaround here is the use the following variant

```
SELECT VALUE COUNT(1) 
FROM root
WHERE (root["dateField"] <= "2020-08-28T15:50:12.9709035+00:00" and root.partitionKey = 'key0'
GROUP BY root.id
```
