### ISSUE TITLE
DISTINCT Produces Inconsistent Results

### ISSUE THREAD

**Issue by tsharp** [Azure/azure-cosmos-dotnet-v3#1816]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When retrieving record counts directly the results are different than expected. If I run the query through the query explorer in azure storage or in the browser vs running the same query via the sdk in .net core I get two different record counts.

**To Reproduce**
1. Create database
2. Create container
3. populate container with ~2k items with 2 different partition keys
4. Run following sql query to get count in c#
SELECT VALUE COUNT(1) FROM (SELECT DISTINCT root.id FROM root WHERE (root["dateField"] <= "2020-08-28T15:50:12.9709035+00:00") and root.partitionKey = 'key0') as c

The count will be different than when run in storage explorer.

**Expected behavior**
Same counts returned in both.

**Actual behavior**
A zero count is retuned or a count of all items in the container is returned.

**Environment summary**
SDK Version: 3.12.0
OS Version (e.g. Windows, Linux, MacOSX)
Windows & Linux

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by timsander1** [comment]
Hello @tsharp. Queries with an aggregate system function and a subquery with DISTINCT are not supported in Cosmos DB. Learn more here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-keywords#distinct

**Comment by bchong95** [comment]
Same issue as 

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1815

**Comment by DavidKlempfner** [comment]
Did this get fixed?

**Comment by tsharp** [comment]
@DavidKlempfner No - it did not.
