### ISSUE TITLE
DISTINCT OFFSET LIMIT Returns No Data if OFFSET is other than 0

### ISSUE THREAD

**Issue by tsharp** [Azure/azure-cosmos-dotnet-v3#1817]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
DISTINCT OFFSET LIMIT Returns No Data if OFFSET is other than 0

**To Reproduce**
1. Create database
2. Create container
3. populate container with ~2k items with 2 different partition keys
4. Run following sql query to get count in c#
SELECT root.id FROM root WHERE (root["dateField"] <= "2020-08-28T15:50:12.9709035+00:00") and root.partitionKey = 'key0' OFFSET 100 LIMIT 101

**Expected behavior**
Data is retrieved by C# and Data Explorer

**Actual behavior**
Data is retrieved on the first page but on the second page data is not retrieved. Upon further investigation - fiddler does in fact show that data was returned but no data is present in the C# object. Storage explorer and the browser return the expected data.

**Environment summary**
SDK Version: 3.12.0
OS Version (e.g. Windows, Linux, MacOSX)
Windows & Linux

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
Did you completely drain the query? [Empty pages](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance#common-sdk-issues) are expected.

**Comment by tsharp** [comment]
I did no try to drain the query. I'll give that a shot.

**Comment by bchong95** [comment]
Query needs to be drained fully.
