### ISSUE TITLE
Please add non generic base or interface to Response<T>.

### ISSUE THREAD

**Issue by geukhan** [Azure/azure-cosmos-dotnet-v3#1818]
**Is your feature request related to a problem? Please describe.**
I am trying to implement a common way to emit diagnostics data from cosmos response object, however it seems like I cannot do it without reflection.

**Describe the solution you'd like**
If https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c5a5b8836aa8ce2f8d93a863f4abdb2d2818fa5b/Microsoft.Azure.Cosmos/src/Resource/Response.cs had a non generic base with all the properties but Resource, I could cast the response I receive to Response object and access Diagnostics property without needing to use reflection in a generic method that wraps logging of diagnostics. An alternative would be to add an interface like IResponse or something like that.

**Describe alternatives you've considered**
I considered alternative code design but none of it solved the situation as simple and straightforward as having non generic Response base class.

**Additional context**
I am running a method that takes a Func<TResult> to execute a cosmos request:

``` CSharp
TResult result = await func();
```

In my use case, ```TResult``` is always ```Response<T>```. Before I return the ```result``` I would like to dump some diagnostics and emit some metrics about usage etc.. If the base was not ```Response<T>``` but something like ```IResponse``` then I could easily do something like this ```(IResponse)result.Diagnostics``` to access diagnostics without using reflection.

**Comment by j82w** [comment]
Have you tried using a [custom handler](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/Handlers) to log all the responses?

Could you use dynamic?
`Response<dynamic> response = await functAsync();`

**Comment by geukhan** [comment]
Thanks, custom handler works. I still think it would be still very useful to have a non generic base for other use cases as well and for convenience. I would not prefer using dynamic or reflection in certain code bases.

In addition, maybe not so related but CosmosClient is not very easy to mock. I had to extend CosmosClient to create my own interface to be able to mock it easily. It'd be nice if CosmosClient implemented something like ICosmosClient.

In my case I generated this code:

``` CSharp

    /// <summary>
    /// Extracted interface from Microsoft.Azure.Cosmos.CosmosClient for testability.
    /// </summary>
    /// <inheritdoc cref="Azure.Cosmos.CosmosClient"/>
    public interface ICosmosClient
    {
        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.ClientOptions"/>
        CosmosClientOptions ClientOptions { get; }

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.Endpoint"/>
        Uri Endpoint { get; }

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.ReadAccountAsync"/>
        Task<AccountProperties> ReadAccountAsync();

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.GetDatabase"/>
        Database GetDatabase(string id);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.GetContainer"/>
        Container GetContainer(string databaseId, string containerId);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.CreateDatabaseAsync(string, int?, RequestOptions, CancellationToken)"/>
        Task<DatabaseResponse> CreateDatabaseAsync(string id, int? throughput = null, RequestOptions requestOptions = null, CancellationToken cancellationToken = default);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.CreateDatabaseAsync(string, ThroughputProperties, RequestOptions, CancellationToken)"/>
        Task<DatabaseResponse> CreateDatabaseAsync(string id, ThroughputProperties throughputProperties, RequestOptions requestOptions = null, CancellationToken cancellationToken = default);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.CreateDatabaseIfNotExistsAsync(string, ThroughputProperties, RequestOptions, CancellationToken)"/>
        Task<DatabaseResponse> CreateDatabaseIfNotExistsAsync(string id, ThroughputProperties throughputProperties, RequestOptions requestOptions = null, CancellationToken cancellationToken = default);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.CreateDatabaseIfNotExistsAsync(string, int?, RequestOptions, CancellationToken)"/>
        Task<DatabaseResponse> CreateDatabaseIfNotExistsAsync(string id, int? throughput = null, RequestOptions requestOptions = null, CancellationToken cancellationToken = default);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.GetDatabaseQueryIterator{T}(QueryDefinition, string, QueryRequestOptions)"/>
        FeedIterator<T> GetDatabaseQueryIterator<T>(QueryDefinition queryDefinition, string continuationToken = null, QueryRequestOptions requestOptions = null);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.GetDatabaseQueryStreamIterator(QueryDefinition, string, QueryRequestOptions)"/>
        FeedIterator GetDatabaseQueryStreamIterator(QueryDefinition queryDefinition, string continuationToken = null, QueryRequestOptions requestOptions = null);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.GetDatabaseQueryIterator{T}(string, string, QueryRequestOptions)"/>
        FeedIterator<T> GetDatabaseQueryIterator<T>(string queryText = null, string continuationToken = null, QueryRequestOptions requestOptions = null);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.GetDatabaseQueryStreamIterator(string, string, QueryRequestOptions)"/>
        FeedIterator GetDatabaseQueryStreamIterator(string queryText = null, string continuationToken = null, QueryRequestOptions requestOptions = null);

        /// <inheritdoc cref="Azure.Cosmos.CosmosClient.CreateDatabaseStreamAsync(DatabaseProperties, int?, RequestOptions, CancellationToken)"/>
        Task<ResponseMessage> CreateDatabaseStreamAsync(DatabaseProperties databaseProperties, int? throughput = null, RequestOptions requestOptions = null, CancellationToken cancellationToken = default);

        /// <inheritdoc cref="IDisposable.Dispose"/>
        void Dispose();
    }
```

**Comment by j82w** [comment]
@geukhan  what is hard about [mocking the CosmosClient](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/dccd91597af952292f00a91ee5df0cf1e622ba7d/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/CosmosVirtualUnitTest.cs#L95)? All the methods are virtual and it is not sealed.

```c#
Mock<CosmosClient> mockClient = new Mock<CosmosClient>();
            mockClient.Setup(x => x.CreateDatabaseAsync(
                    It.IsAny<string>(), 
                    It.IsAny<int?>(),
                    It.IsAny<RequestOptions>(),
                    It.IsAny<CancellationToken>()))
                .Returns(Task.FromResult(mockDbResponse.Object));
```

**Comment by geukhan** [comment]
You are right, they are virtual. It seems I was not paying enough attention there, my bad.
