### ISSUE TITLE
Memory leak with UpsertItemAsync

### ISSUE THREAD

**Issue by Kyle2123** [Azure/azure-cosmos-dotnet-v3#1819]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
We are experiencing constantly growing memory usage in our application writing to CosmosDb with calls to UpsertItemAsync.  Unknown if this problem is specific to UpsertItemAsync or if it impacts other types of operations as well - the only thing our application does with Cosmos is upserts records.

**To Reproduce**
Repeated calls to UpsertItemAsync in a high volume environment.  The memory usage grows at a fairly steady, continuous rate, until it eventually exceeds available memory and the process is restarted.

**Expected behavior**
Memory usage should remain more or less constant as the application continues upserting records to Cosmos.

**Actual behavior**
Memory usage continuously grows over time.

**Environment summary**
SDK Version: 3.12.0
OS Version (e.g. Windows, Linux, MacOSX)
Linux 

**Additional context**

All of the application's interaction with Cosmos runs through this method:
![image](https://user-images.githubusercontent.com/4731333/91739725-543f5780-eb80-11ea-8cfc-684606b62ee4.png)

GetClient() retrieves the CosmosClient instance from a cache or creates if does not exist.
GetContainer() retrieves the Container from a cache or creates if does not exist.
Analysis of the memory dump shows exactly one CosmosClient and Container in memory.  These objects are cached for the lifetime of the application.

Screenshot of top items in managed memory from a dump, sorted by size:
![image](https://user-images.githubusercontent.com/4731333/91738268-34a72f80-eb7e-11ea-9939-1cd78817ab26.png)

Screenshot of top items in managed memory from a dump, sorted by inclusive bytes:
![image](https://user-images.githubusercontent.com/4731333/91741561-e5173280-eb82-11ea-867f-71e1c245f798.png)

Screenshot of top items in managed memory from a dump, sorted by item count:
![image](https://user-images.githubusercontent.com/4731333/91739277-b21f6f80-eb7f-11ea-9c53-23baa012c87c.png)

Screenshot of application memory usage:
![image](https://user-images.githubusercontent.com/4731333/91738584-ada68700-eb7e-11ea-852b-d2397909b276.png)

Screenshot of same application after disabling upserts to Cosmos:
![image](https://user-images.githubusercontent.com/4731333/91738710-e2b2d980-eb7e-11ea-81ee-ceba5c97d842.png)

**Comment by ealsur** [comment]
Does `GetClient()` do a `new CosmosClient(...)` ?

**Comment by Kyle2123** [comment]
The purpose of GetClient() is to cache the CosmosClient and reuse it - it should only create it once for the lifetime of the app.  I verifed in the memory dump that there is exactly one instance of CosmosClient in the heap so I believe this method is working as intended.

```c#

        private CosmosClient GetClient(string connectionString, bool isBulk = false)
        {
            CosmosClient result;
            var key = string.Concat(isBulk ? "BULK:" : string.Empty, connectionString);
            if (!_mapConnectionStringToClient.TryGetValue(key, out result))
            {
                lock (_mapConnectionStringToClient)
                {
                    if (!_mapConnectionStringToClient.TryGetValue(key, out result))
                    {
                        var accountEndPoint = ExtractValueFromConnectionString(connectionString, "AccountEndpoint");
                        var accountKey = ExtractValueFromConnectionString(connectionString, "AccountKey");
                        result = new CosmosClient(accountEndPoint, accountKey, new CosmosClientOptions()
                        {  
                            ApplicationName = "MyApp",
                            AllowBulkExecution = isBulk
                        });
                        _mapConnectionStringToClient.Add(key, result);
                    }
                }
            }
            return result;
        }
```

**Comment by Kyle2123** [comment]
Please hold off on any further research for this, I believe I have the problem isolated on my end.  I thought my database access class was registered as a singleton but it was marked as transient.  The internal resources weren't getting disposed properly.  Sorry for the trouble and thanks for your assistance.
