### ISSUE TITLE
Create a way to enable random ordering 

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-cosmos-dotnet-v3#1823]
Cosmos Db SQL API has [RAND()](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-rand) function. But there is no way to order by this random after obtaining `IQueryable<T>`. 

Suggestion: create [Rand] attribute.

**Comment by bchong95** [comment]
In general this requires ORDER BY on the runtime. it's a feature that is on the roadmap.

**Comment by petro2050** [comment]
@bchong95 any eta on this one?

**Comment by bchong95** [comment]
@timsander1 Can give feedback on ETAs.

**Comment by timsander1** [comment]
Hi @petro2050. This is on our long-term roadmap but not planned in the upcoming 6 months.

**Comment by j82w** [comment]
Closing this as it is a service side feature.

**Comment by amastaneh** [comment]
It's a real blocker. Is there a creative or alternative solution?

**Comment by baynezy** [comment]
@amastaneh the only solution we could come up with was to store the relevant metadata we wanted to query on in SQL Server in addition to the documents in Cosmos.

We then execute our queries against SQL Server. This returns a record set of primary keys in Cosmos in the correct order. We then get those from Cosmos and return them to the client.

Not ideal, but it works.
