### ISSUE TITLE
Invalid SDK version in error messages

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#183]
The SDK version is incorrect for exceptions/error message. This is the current version that is returned.

SDK: Microsoft.Azure.Documents.Common/2.2.0.0, Windows/10.0.18362 cosmos-netstandard-sdk/3.0.0;

**Comment by simplynaveen20** [comment]
Fixed in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/630
