### ISSUE TITLE
Ability to return a random item from a container

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-dotnet-v3#1838]
Given a partition key (and other matching fields), I want the database to return a random item. Right now, to accomplish something like this, I have to fetch everything in memory and pick a random item using LINQ. This wastes a lot of RUs.

**Comment by j82w** [comment]
What is the use case of this feature? I can't think of a valid use case where a developer would need to return a random item in production.

**Comment by petro2050** [comment]
@j82w Suppose I need to show a list of customer reviews on a product in an infinitely scrolling list. I want to show a random comment on each review along with the review itself. So, this is a parent -> child relationship where each parent displays a random child on the UI. Right now, I fetch the top 10 children and randomly select a child. It'd be great if the database could return a random item.

I want to supply the partition key and a soft delete flag (possible a few other fields) and get a random `id`.

**Comment by ealsur** [comment]
@petro2050 This is not related to SDK. What you are asking is a query feature in Cosmos DB that supports a Random in a SELECT statement. Anything in the client SDK would imply getting all results and doing a random client-side (like you are doing right now) so there would be no RU benefit.

You might want to request the feature in the Uservoice https://feedback.azure.com/forums/263030-azure-cosmos-db?category_id=321988
