### ISSUE TITLE
Unable to use Microsoft.Azure.Cosmos.Encryption with Microsoft.Azure.Cosmos.3.13.0-preview

### ISSUE THREAD

**Issue by ORuban** [Azure/azure-cosmos-dotnet-v3#1847]
**Describe the bug**
In Microsoft.Azure.Cosmos.3.13.0-preview (and in current master) the `ChangeFeedRequestOptions` class is **sealed**. 
But `Cosmos.Encryption` proj defines `EncryptionChangeFeedRequestOptions` inherited from it: 
```public sealed class EncryptionChangeFeedRequestOptions : ChangeFeedRequestOptions```
As a result, you cannot instantiate it.

**To Reproduce**
1. Create Console App
2. Add reference to Microsoft.Azure.Cosmos.3.13.0-preview
3. Add reference to Microsoft.Azure.Cosmos.Encryption.1.0.0.0-preview6 (or preview5)
4. Create instance of EncryptionChangeFeedRequestOptions
   `var option = new EncryptionChangeFeedRequestOptions();`
5. Run

**Expected behavior**
`EncryptionChangeFeedRequestOptions` instance created

**Actual behavior**
> System.TypeLoadException: 'Could not load type 'Microsoft.Azure.Cosmos.Encryption.EncryptionChangeFeedRequestOptions' from assembly 'Microsoft.Azure.Cosmos.Encryption, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' because the parent type is sealed.'

**Environment summary**
SDK Version: .NET Framework 4.7.2 (should be the same problem for .NET Core)

**Comment by ealsur** [comment]
@abhijitpai @anujtoshniwal Are we planning for a new release of Encryption that might be compatible with the latest SDK preview?

**Comment by abhijitpai** [comment]
Yes, this is waiting on PRs for the refactoring to get around the class being made sealed and the precursor steps for that. @kirankumarkolli

**Comment by anujtoshniwal** [comment]
There is a regression in 3.13.0-preview release of the Cosmos SDK. Waiting for the bug to be fixed to upgrade to the newer release.

**Comment by bchong95** [comment]
As discussed requestoptions will not be unsealed unless we have a strong reason for it.
