### ISSUE TITLE
Container.DeleteItemAsync<T> should not be generic

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-cosmos-dotnet-v3#1848]
It should be Container.DeleteItemAsync(string id, ...) without being generic method.

**Comment by j82w** [comment]
@MhAllan why should it not be generic? By default it returns the item that is being deleted.

You can also do the following:
```c#
using (await this.Container.DeleteItemStreamAsync(id, new PartitionKey(pk))) { }
```

**Comment by MhAllan** [comment]
I didn't pay attention that it returns.
