### ISSUE TITLE
Client roadmap

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#1851]
Do you guys have a client roadmap? Azure.Cosmos NuGet preview 3 was released 8 months ago, but no updates since. Thanks.

**Comment by j82w** [comment]
The v4 SDK is currently gated on some new service features which are expected to GA early next year. The current priority is to stabilize and improve the v3 SDK performance.

**Comment by bartelink** [comment]
Can you offer any forward looking statements as to when a preview might appear?

Context: I'm tentatively building things against V4 preview, but am hoping key bug/perf fixes might make it there in some reasonable timeframe.

Even more context: It doesn't make sense for us to use V3 for prod stuff; we're stuck on V2 pending https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1765

**Comment by j82w** [comment]
The current plan is to have a new v4 preview by the end of the year.

**Comment by PingPongSet** [comment]
As of 2022 now, what is the plan for Azure.Cosmos V4 preview?
https://www.nuget.org/packages/Azure.Cosmos
