### ISSUE TITLE
Documentation has html char entities 

### ISSUE THREAD

**Issue by subbarayudukamma** [Azure/azure-cosmos-dotnet-v3#1855]
Azure.Comos library documentation(https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.transactionalbatch?view=azure-dotnet) has issues like below.
 
List&lt;PatchOperation&gt; patchOperations = new List&lt;PatchOperation&gt;();

**Comment by j82w** [comment]
Everything in the [file](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/3e5f0bcec44d85979366975e4056ce2bed0bf28b/Microsoft.Azure.Cosmos/src/Batch/TransactionalBatch.cs#L20) looks correct. It might be an issue with the docs website.

**Comment by ealsur** [comment]
Closing as the code is correctly rendered
