### ISSUE TITLE
Ability to migrate from manual to autoscale and vice versa through .Net V3 SDK

### ISSUE THREAD

**Issue by sanalkumarp** [Azure/azure-cosmos-dotnet-v3#1856]
We are unable to migrate an existing container or database from autoscale to manual.
This feature would greatly help us switch between these on a demand basis. Please let us know if there are plans already to add the support and a rough timeline.

Currently, though the documentation says that the manual/autoscale migration is not supported through SDK, we are able to migrate from manual to autoscale, but not from autoscale to manual.

Below error is thrown on trying to migrate from autoscale to manual:
_**Response status code does not indicate success: BadRequest (400); Substatus: 0; Reason: (Message: {"Errors":["x-ms-cosmos-migrate-offer-to-autopilot must be supplied and offercontent must not contain autopilotSettings for migration from manual throughput to autoscale."]}**_

**Comment by j82w** [comment]
The SDK does not support the migration because the assumption that once you switch to autoscale there is no reason to go back to manual. Since it's a one time operation coding this into the application does not make since. There is portal and powershell support if you have a large number of databases/containers that need to be converted. 

Why do you need to go back to manual after switching to autoscale?

**Comment by sanalkumarp** [comment]
Hi @j82w,
If the database or containers that are converted to autoscale, and later if we found that the their usage is more cost effective in manual throughput, we will have to delete and recreate the container. To do this, we will have to take care of the data not being loss. 
If we have the same support of converting autoscale to manual which Azure already supports from portal, we can do this by just updating the app configuration itself.

**Comment by FabianMeiswinkel** [comment]
Hi @sanalkumarp - in most cases the migration of throughput is a one-off operation. Also most customers actually make the throughput adjustments either via portal or Devops pipelines (via Azure CLI, ARM etc. - via the control plane).
If you want to stick doing it form the application you could look at the Microsoft.Azure.Management-fluent library that we have - basically a separate SDK in >net allowing to make management operations/control-plane operations similar to Azure CLI natively from .Net.
We have a sample for doing a throughput migration here: https://github.com/Azure-Samples/cosmos-management-net/blob/de4333b83bb385ac9c94718bdd24451ce457aca0/cosmos-management-generated/Sql.cs#L96
