### ISSUE TITLE
No service for type 'System.Net.IHttpClientFactory' has been registered

### ISSUE THREAD

**Issue by ylr-research** [Azure/azure-cosmos-dotnet-v3#1860]
I used the same sample code you have for HttpClientFactory, and after running the app got the error below. See Main method below as well.

![image](https://user-images.githubusercontent.com/63487874/93670671-2193cb00-fa6b-11ea-9a66-b9d9791347ca.png)

``` C#
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
            builder.Services.AddSingleton<CosmosClient>(serviceProvider =>
            {
                IHttpClientFactory httpClientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();

                CosmosClientOptions cosmosClientOptions = new CosmosClientOptions
                {
                    HttpClientFactory = httpClientFactory.CreateClient,
                    ConnectionMode = ConnectionMode.Gateway
                };

                return new CosmosClient("<connection-string>", cosmosClientOptions);
            });
            builder.Services.AddLocalization(options => options.ResourcesPath = "Resources");

            await builder.Build().RunAsync();
        }
```

**Comment by j82w** [comment]
@ylr-research if you look at the error message it is failing on getting the http client factory, and has nothing to do with the Cosmos SDK.  It seems like you are missing something with the blazor setup. I'm not familiar with Blazor but maybe you need to to [create the httpclient](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1#named-httpclient-with-ihttpclientfactory) first?  

@ealsur do you have a suggestion or sample?

**Comment by ealsur** [comment]
You have not registered the IHttpClientFactory.

`IHttpClientFactory httpClientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();`

That line says you are asking for the instance of `IHttpClientfactory` but you have not registered it anywhere.

You are missing a `services.AddHttpClient();`, which is part of `Microsoft.Extensions.Http`.

References:

* https://medium.com/@marcodesanctis2/using-ihttpclientfactory-with-blazor-webassembly-7cc702f5e9f8
* https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests
* https://devblogs.microsoft.com/cosmosdb/httpclientfactory-cosmos-db-net-sdk/#this-sounds-similar-to-ihttpclientfactory-in-net

**Comment by ylr-research** [comment]
@ealsur you're right. I did add it before though but this is the error message
![image](https://user-images.githubusercontent.com/63487874/93796207-8173a880-fc08-11ea-8e7c-4c06422f1dc7.png)

**Comment by ealsur** [comment]
Looks like this is a bug introduced recently on a refactoring, PR with the fix is inbound.

**Comment by ylr-research** [comment]
thanks

**Comment by j82w** [comment]
@ylr-research please try the latest [3.13.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.13.0)
