### ISSUE TITLE
dotnet/runtime WebAssembly System.PlatformNotSupportedException: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by kjpou1** [Azure/azure-cosmos-dotnet-v3#1862]
**Describe the bug**
Proxy settings are not supported and will throw `System.PlatformNotSupportedException: Operation is not supported on this platform.` when creating an HttpClient.

**To Reproduce**
To reproduce see the issue: https://github.com/dotnet/aspnetcore/issues/26043

**Expected behavior**
No PNSE thrown

**Actual behavior**
The actual behavior can be seen here: https://github.com/dotnet/aspnetcore/issues/26043

**Environment summary**
SDK Version: "Microsoft.Azure.Cosmos" Version="3.13.0-preview"
OS Version (e.g. Windows, Linux, MacOSX): WebAssembly

The best way to resolve this problem is checking if proxy settings are supported before setting the code in the following lines.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8c31ca03d52d8550a103155a6ed4966a9eb51980/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L99-L107

The following code snippet should work.

```
        public static HttpMessageHandler CreateHttpClientHandler(int gatewayModeMaxConnectionLimit, IWebProxy webProxy)
        {
            // https://docs.microsoft.com/en-us/archive/blogs/timomta/controlling-the-number-of-outgoing-connections-from-httpclient-net-core-or-full-framework
            if (RuntimeInformation.OSDescription == "Browser")
                return new HttpClientHandler ();
            else
            {
                return new HttpClientHandler
                {
                    Proxy = webProxy,
                    MaxConnectionsPerServer = gatewayModeMaxConnectionLimit
                };
            }
        }
```

Or check the property `HttpClientHandler.SupportsProxy Property`

```
        public static HttpMessageHandler CreateHttpClientHandler(int gatewayModeMaxConnectionLimit, IWebProxy webProxy)
        {
            // https://docs.microsoft.com/en-us/archive/blogs/timomta/controlling-the-number-of-outgoing-connections-from-httpclient-net-core-or-full-framework
            HttpClientHandler handler = new HttpClientHandler();
            if (handler.SupportsProxy)
            {
                handler.Proxy = webProxy;
                handler.MaxConnectionsPerServer = gatewayModeMaxConnectionLimit;
            }
            return handler;
        }
```

**Comment by j82w** [comment]
@kjpou1 a possible work around is to provide an HttpClientFactory. Can you see if that works to unblock you?

**Comment by j82w** [comment]
@kjpou1 please try the latest [3.13.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.13.0)

**Comment by kjpou1** [comment]
@j82w thank you for the information.

@ylr-research could you try the latest release above to see if it fixes the problem.
