### ISSUE TITLE
No errors in FeedIterator when getting 429; just no results 

### ISSUE THREAD

**Issue by kirk-marple** [Azure/azure-cosmos-dotnet-v3#1867]
**Describe the bug**
It appears that I'm not getting any exceptions thrown or error returned when getting a 429, using a FeedIterator.

From looking at CosmosDB metrics, I got 429s around that time, so my assumption is that the 429 was "eaten" somehow and I wasn't able to retry.  Given this is a generic "GetById" method, I don't really know if no result is an error or if the document isn't there.

**To Reproduce**
I'm evaluating a query via FeedIterator, against CosmosDB, with this code:

```
protected async Task<(IEnumerable<S> Models, ServiceError Error)> EvaluateQueryableAsync<S>(IQueryable<S> query) where S : ModelBase
{
                using var q = query.ToFeedIterator();
                var r = await CosmosDBHelpers.EvaluateFeedIteratorAsync(this.Logger, q);
/* snip */
}
```

        public static async Task<List<S>> EvaluateFeedIteratorAsync<S>(ILogger logger, FeedIterator<S> feed)
        {
            var models = new List<S>();
            double requestCharge = 0.0;

            while (feed.HasMoreResults)
            {
                var response = await feed.ReadNextAsync();

                if (response == null)
                    throw new InvalidOperationException($"Failed to read results from feed.");

                requestCharge += response.RequestCharge;

                models.AddRange(response);
            }

**Expected behavior**
If I would hit a 429 in this situation, I'd expect to get an exception thrown, which I could handle and retry the query.

**Actual behavior**
Under a load test, I found some situations where my query returned no results, but the document was in the database.  I can see 5+ log entries beforehand where the document was found, and then one where it wasn't found.  (And I validated afterwards the document is still there). 

**Environment summary**
SDK Version: 3.12.0
OS Version: Windows 10, Visual Studio 2019 Preview

**Comment by ealsur** [comment]
According to the query docs, empty pages are sometimes expected?
https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance#common-sdk-issues
![image](https://user-images.githubusercontent.com/1633401/93906604-3bbeea80-fcb1-11ea-8cae-1f32de33e22e.png)

**Comment by kirk-marple** [comment]
@ealsur Thanks Matias, but given I'm reading until feed doesn't have more results, would that be taken care of already?  I'm not breaking out of my loop if there's no responses - only if ReadNextAsync gives a null or feed.HasMoreResults is false.

**Comment by ealsur** [comment]
If you are reading until HasMoreResults is false, you should get all results, empty pages would just go by and not add any new result to the list you are currently aggregating on. By the way, if this is a "GetById" type of query, are you not doing "ReadItemAsync" because you don't know the PartitionKey of the document?

@bchong95 Can confirm if a 429 would surface as an exception or an empty page

**Comment by bchong95** [comment]
429s should surface as a retryable exception. After the pagination library:

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1669

You should be able to retry on a 429 by just calling ReadNextAsync one more time on the iterator:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/770ee191bb2cfcef83d4d1bb3798de66776ada34/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/PartitionRangeEnumeratorTests.cs#L61

**Comment by kirk-marple** [comment]
Just ran across this again, and it may only happen when making parallel queries via ICosmosDbContainer.

Is it thread-safe to call GetItemLinqQueryable on same ICosmosDbContainer in parallel from multiple-threads?

In this case, I'm running 3 queries in parallel, within a parallel foreach (using System.Threading.Tasks.Dataflow).

Here's how I query and evaluate the feed iterator.  Each call is a 'get by id', and I've confirmed manually that the queries run successfully in Azure Portal.

```
                var query = Container.GetItemLinqQueryable<S>(allowSynchronousQueryExecution: true,
                    requestOptions: GenerateDefaultQueryRequestOptions(SINGLE_ITEM_COUNT, ModelHelpers.GeneratePartitionKey<S>(ownerId)))
                    .Where(d => d.TypeName == typeof(S).Name)
                    .Where(d => d.Id == id);

                if (!String.IsNullOrEmpty(ownerId))
                    query = query?.Where(d => d.OwnerId == ownerId);

                if (filterDeletedModels)
                    query = query?.Where(d => d.State != ModelState.Deleted.ToString());

                query = query?.Take(SINGLE_ITEM_COUNT);
```

```
                using var q = query.ToFeedIterator();
                var r = await CosmosDBHelpers.EvaluateFeedIteratorAsync(this.Logger, q);
```
```
        public static async Task<List<S>> EvaluateFeedIteratorAsync<S>(ILogger logger, FeedIterator<S> feed)
        {
#if DEBUG_REPOSITORY
            logger?.LogDebug($"Attempting to evaluate feed iterator.");
#endif

            var sw = Stopwatch.StartNew();

            var models = new List<S>();
            double requestCharge = 0.0;

            while (feed.HasMoreResults)
            {
                var response = await feed.ReadNextAsync();

                if (response == null)
                    throw new InvalidOperationException($"Failed to read results from feed.");

#if DEBUG_REPOSITORY
                logger?.LogDebug("Successfully read feed results, [" + response.Count + "] model(s), request charge [{RequestCharge}].", response.RequestCharge);
#endif

                requestCharge += response.RequestCharge;

                models.AddRange(response);
            }

#if DEBUG_REPOSITORY
            logger?.LogDebug("Successfully evaluated feed iterator, [" + models.Count + "] model(s), total request charge [{RequestCharge}], took [{ElapsedTime}] [{ElapsedTimeMsec}].", requestCharge, sw.Elapsed, sw.ElapsedMilliseconds);
#endif

            return models;
        }
```

From my logs, you can see the three similar calls in parallel:

Attempting to query Tag by id [17c6700a-8e13-48f2-a686-70628def4e32], owner [43196bba-8641-40d7-907d-79dca002a445], type name [Tag].
Attempting to query Tag by id [5a858135-0d68-43d4-917b-6c7afa42287f], owner [43196bba-8641-40d7-907d-79dca002a445], type name [Tag].
Attempting to query Tag by id [40ab6dae-16ec-404d-bcd3-92643e586fe5], owner [43196bba-8641-40d7-907d-79dca002a445], type name [Tag].
Evaluating query [{\"query\":\"SELECT TOP 1 VALUE root FROM root WHERE ((((root[\\\"id\\\"] = \\\"17c6700a-8e13-48f2-a686-70628def4e32\\\") AND (root[\\\"type\\\"] = \\\"Tag\\\")) AND (root[\\\"ownerId\\\"] = \\\"43196bba-8641-40d7-907d-79dca002a445\\\")) AND (root[\\\"state\\\"] != \\\"Deleted\\\"))\"}].
Evaluating query [{\"query\":\"SELECT TOP 1 VALUE root FROM root WHERE ((((root[\\\"id\\\"] = \\\"5a858135-0d68-43d4-917b-6c7afa42287f\\\") AND (root[\\\"type\\\"] = \\\"Tag\\\")) AND (root[\\\"ownerId\\\"] = \\\"43196bba-8641-40d7-907d-79dca002a445\\\")) AND (root[\\\"state\\\"] != \\\"Deleted\\\"))\"}].
Evaluating query [{\"query\":\"SELECT TOP 1 VALUE root FROM root WHERE ((((root[\\\"id\\\"] = \\\"40ab6dae-16ec-404d-bcd3-92643e586fe5\\\") AND (root[\\\"type\\\"] = \\\"Tag\\\")) AND (root[\\\"ownerId\\\"] = \\\"43196bba-8641-40d7-907d-79dca002a445\\\")) AND (root[\\\"state\\\"] != \\\"Deleted\\\"))\"}].
Attempting to evaluate feed iterator.
Attempting to evaluate feed iterator.
Attempting to evaluate feed iterator.
Successfully read feed results, [0] model(s), request charge [2.79].
Successfully read feed results, [0] model(s), request charge [2.79].
Successfully read feed results, [1] model(s), request charge [3.43].
Successfully evaluated feed iterator, [0] model(s), total request charge [2.79], took [00:00:00.0647712] [64].
Successfully evaluated feed iterator, [0] model(s), total request charge [2.79], took [00:00:00.0720368] [72].
Successfully evaluated feed iterator, [1] model(s), total request charge [3.43], took [00:00:00.0822747] [82].

And then it only returns one of them... no errors or anything.

But for sure, that model is there in the db.
