### ISSUE TITLE
Support First, Single in LINQ

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-cosmos-dotnet-v3#1869]
I noticed "First" and "Single" are not supported here:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1ef6e399f114a0fd580272d4cdca86b9f8732cf3/Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs#L1111-L1221

As they can be derived from `Take(1)`, it should be within the abilities of the SQL syntax to implement them (albeit not there exactly, since those don't perform instantiation).

**Comment by timsander1** [comment]
Hello @Arithmomaniac , this work is planned for later this calendar year.

**Comment by Maya-Painter** [comment]
LINQ support for FirstOrDefault was introduced in version 3.38.0. 
More details: #4286
