### ISSUE TITLE
Doubts in Change feeds

### ISSUE THREAD

**Issue by AntonioJDios** [Azure/azure-cosmos-dotnet-v3#1881]
Hi all, we can receive with the azure function and change processor those documents which have been inserted or updated in the container. However, I would only be interested in what logical partitions have change since the last time. Does any way of doing this exist?

thanks.

**Comment by ealsur** [comment]
I'm not sure I understand this statement, can you clarify a bit?

> I would only be interested in what logical partitions have change since the last time

Change Feed exposes the complete document that was either inserted or updated, currently there is no way to differentiate the type of operation (insert or replace), but the document contains all properties, including the partition key.

**Comment by AntonioJDios** [comment]
Sure. I have a collection where we insert many documents. Then we want
archive cosmos collection into blobs. Each blob will be a logical partition
from cosmos. So, each time we get a new document in any partition I want to
replace the blob for that partition. With change feed I receive for the
same partition many documents. With just one document will be enough. To
summary; what I need to know is when each logical partition has a new or
updated document.. does it make sense?
Thanks Matias!

**Comment by ealsur** [comment]
That would be logic you need to do in your application code. Change Feed cannot have that kind of filter. The Change Feed will contain all changes happening in your container, and that's it.

If you want your application to react or do something only when a document in a Partition Key value changes, your code should be tracking that and checking the incoming changes.

The documents you receive in the Change Feed all contain the value of the Partition Key, so you can simply Group the incoming changes using a LINQ expression or something and just get the distinct Partition Key values.

**Comment by AntonioJDios** [comment]
Cool. It was my solution. Just to confirm there is no other way of doing!.
Feel free to close this ticket.
