### ISSUE TITLE
Should we remove ConsistencyLevel  in write operation options?

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-cosmos-dotnet-v3#1889]
I understand ConsistencyLevel in read operations, but I don't understand what does it do in write operations like this

```csharp
var options = new ItemRequestOptions
{
     ConsistencyLevel = ConsistencyLevel.Eventual
};

await _container.CreateItemAsync<T>(item, partitionKey, options);
```

If it has no effect, maybe it should be removed from write operations options, otherwise the documentations need updates as we can only read about consistency level from the read point of view.

**Comment by ealsur** [comment]
Where does it say that consistency levels do not affect writes? Strong writes do not behave the same way as other consitencies for example: https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels-tradeoffs#write-latency-and-strong-consistency

**Comment by MhAllan** [comment]
Hi @ealsur , what I said is that there is no documentations about writes and consistency level. Thanks for referring me to that documentation, but that is not the whole story. Strong and Eventual writes could be understood. But we still have more consistency levels (session, boundless stale, .. etc). I am asing because we are using the client and write operations can take any consistency level, but we don't know the effect of each consistency on the write operation!

**Comment by ealsur** [comment]
I understand that there are other consistency level between Strong and Eventual and that how Consistency Levels work on write operations (outside of these two already documented ones) might be unknown.
You can file an issue in any of the documentation pages (including the one I linked) and ask for clarification, which will be taken care of by the owners of the service documentation.

From the SDK perspective though, it does make sense to be able to change the Consistency for an item operation (read and write) as it does have effects on both (on writes at least it is documented for Strong and Eventual), so as long as there is one scenario where changing it is valid, then it should be possible.

**Comment by MhAllan** [comment]
Thanks @ealsur
