### ISSUE TITLE
Scalability for running multiple threads of a change feed processor?

### ISSUE THREAD

**Issue by secretclean** [Azure/azure-cosmos-dotnet-v3#1903]
Hello.

I have a custom CosmosDB Change Feed Processor I built based on the SDK. I converted the entire application into a Windows Service, with the singleton instances of the connection strings and the delegate running as a task. There is one single CosmosDB database, one monitored collection, and one lease, for which events are propagated to be routed to specific systems. For example: someone changes a "Product" in one system, the event goes to CosmosDB, and then my CFP determines its EventType and routes it to a specific API designed to handle the event ("Products" in this case). My CFP sends the information in a "PutAsync" and then waits for the response before firing off another event--the logic being that we don't want to flood the APIs with requests.

This worked perfectly fine for my company for a while. But now it's in production, and someone just released 20,000 records. So now the CFP ITSELF is flooded with requests, since it takes 2-3 seconds to process each record.

I need a way to run this in parallel. People that I've talked to on various websites say there's no way to have one monitored collection, one lease, and multiple threads reading from that same lease. Is there a way to do this, given that the lease is the same? Is it possible to create leases with specific prefixes to monitor specific event types, such as "product?" I'm working on it right now, but it's an urgent issue, and I'm not sure if it's possible and I'm just configuring it incorrectly or not.

If it's not possible, can this feature be added?

Please let me know ASAP. Thank you.

**Comment by ealsur** [comment]
Please see https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1853

**Comment by ealsur** [comment]
The Change Feed Processor runs one parallel thread for each lease document in the leases collection, each lease document currently represents a physical partition.

**Comment by secretclean** [comment]
> The Change Feed Processor runs one parallel thread for each lease document in the leases collection, each lease document currently represents a physical partition.

Okay, thanks. My physical partition is based on "/id." Not sure how to create logical partition leases to monitor individual events with specific event types. What would you recommend for separating out events with the id prefix "product" from those of "order" or "customer" so they can all process simultaneously?

**Comment by ealsur** [comment]
> Okay, thanks. My physical partition is based on "/id." Not sure how to create logical partition leases to monitor individual events with specific event types. What would you recommend for separating out events with the id prefix "product" from those of "order" or "customer" so they can all process simultaneously?

That's incorrect. As per the documentation (https://docs.microsoft.com/en-us/azure/cosmos-db/partition-data) you create Logical Partitions, the physical partitions are created based on the volume of data.

Change Feed Processor reads from Change Feed, and Change Feed has no way to filter particular items with some prefix. If all your items are in the same container, then the id filtering needs to be done on your delegate. There is no way to achieve parallelization the way you describe.

Another alternative is to have different containers for each prefix, each container can have it's own independent Change Feed, so a Change Feed Processor hooked to one of these containers would only receive events for that particular prefix.

**Comment by ealsur** [comment]
Closed as not a functional issue.

**Comment by secretclean** [comment]
The delegate already does that. The problem is that it's too slow using one. And I asked if it could be added as a feature, not that it was a functional issue. The Pull model is able to
