### ISSUE TITLE
CosmosClient with wrong key throws DocumentClientException instead of CosmosException

### ISSUE THREAD

**Issue by NRam0s** [Azure/azure-cosmos-dotnet-v3#1906]
This ticket relates with another one that was been previously closed (https://github.com/Azure/azure-cosmos-dotnet-v3/pull/785). I have basically implemented exactly what was described on that ticket.
I am trying to create a cosmos client with a wrong key. I am able to get a DB and a container but as soon as I try to do a container action I get a DocumentClientException.

```
new CosmosClient(_appSettings.CosmosDbEndpoint, wrongKey,
       new CosmosClientOptions()
       {
           ConnectionMode = ConnectionMode.Direct,
           SerializerOptions = new CosmosSerializationOptions
           {
              PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
            }
         });

_database = client.GetDatabase(_databaseId);
_container = _database.GetContainer(_transactionsContainerId);
```

```
try
{
   var response = await _container.CreateItemAsync(item);
   response.Resource.ETag = response.ETag;

   return response.Resource;
}
catch (CosmosException e)
{
 ...
}
catch (DocumentClientException e1)
{
...
}
catch (Exception e)
{
... The exception comes here as nothing seems to be able to catch a DocumentClientException
 }
```

We are using Microsoft.Azure.Cosmos 3.13.0

One of my colleagues did some research and he found that the issue might be on this line of code. It might need to be inside the try catch: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs#L332

Some more details I have found. If we initialize the client with a valid key and then the key gets rotated, we get the CosmosException as expected with the following details: 
`Response status code does not indicate success: Unauthorized (401); Substatus: 0; ActivityId: XXX; Reason: (Message: {"Errors":["The MAC signature found in the HTTP request is not the same as the computed signature. Server used following string to sign - XXX...
`

However, as I mentioned above, the DocumentClientException is still thrown if the client is initialized already with an invalid key.

**Comment by j82w** [comment]
1. How are you catching the DocumentClientException it is an internal type?
2. Is the incorrect key a resource token? Is there any chance you can provide a repro of the issue? I just ran the following [test ]((https://github.com/Azure/azure-cosmos-dotnet-v3/blob/01c36b2b2c5e3e0eec8388f00c98b97edc8b990e/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosPermissionTests.cs#L359))and it passed. It seems to be testing the exact scenario you are describing.

**Comment by NRam0s** [comment]
> 1. How are you catching the DocumentClientException it is an internal type?
> 2. Is the incorrect key a resource token? Is there any chance you can provide a repro of the issue? I just ran the following [test](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/01c36b2b2c5e3e0eec8388f00c98b97edc8b990e/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosPermissionTests.cs#L359) and it passed. It seems to be testing the exact scenario you are describing.

1 - I am not catching it. If I debug I can see the type of the exception. I did try to import the nuget package "Microsoft.Azure.DocumentDB.Core" which imports the type (DocumentClientException), however the exception still does not fall on that catch block, although while debugging it shoes the type as being DocumentClientException
2- I will need some time to create a test repo as I am currently experiencing this on a repo from my organisation (I will update here once I get to create a small test repo)

**Comment by ealsur** [comment]
Could it be that you are getting some logs / events? Sometimes the SDK does have DocumentClientException internally that might popup in event tracing, but the public facing type is CosmosException (there are places where we convert the DocumentClientException to CosmosException before doing the actual throw).

**Comment by NRam0s** [comment]
As I mentioned. I won't be able to create a test repo that quickly. But here are some pics attached so show what I am getting
![1](https://user-images.githubusercontent.com/63396961/95220780-b9751100-07ee-11eb-87af-6bfe886fc571.PNG)
![2](https://user-images.githubusercontent.com/63396961/95220785-bbd76b00-07ee-11eb-8a9e-2a10481ce960.PNG)
![3](https://user-images.githubusercontent.com/63396961/95220861-cc87e100-07ee-11eb-86ce-4599910873aa.PNG)

**Comment by NRam0s** [comment]
In regards to the way we set the client, I have attached the picture below. We have a DI which gets sorted at runtime. All I doin order to reproduce the error is while debugging, just change a letter on the primary key obtained and that makes the exception occur.
![4](https://user-images.githubusercontent.com/63396961/95221607-84b58980-07ef-11eb-85a9-89fb8b2b3db7.PNG)

**Comment by j82w** [comment]
Can you provide the full exception with the stack trace?

**Comment by ealsur** [comment]
@j82w This reproes on Write operations:

```
[TestMethod]
public async Task EnsureUnauthorized_ThrowsCosmosClientException()
{
    string authKey = ConfigurationManager.AppSettings["MasterKey"];
    string endpoint = ConfigurationManager.AppSettings["GatewayEndpoint"];
    // Take the key and change some middle character
    authKey = authKey.Replace("m", "M");
    CosmosClient cosmosClient = new CosmosClient(
        endpoint,
        authKey);
    CosmosException exception = await Assert.ThrowsExceptionAsync<CosmosException>(() => cosmosClient.GetContainer("test", "test").CreateItemAsync<dynamic>(new { id = "test" }));
    Assert.AreEqual(HttpStatusCode.Unauthorized, exception.StatusCode);
}
```

**Comment by ealsur** [comment]
@NRam0s was right about the location for the fix, sharing PR in a min

**Comment by NRam0s** [comment]
Thanks guys 👍
