### ISSUE TITLE
Expose default serializer

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#191]
**Is your feature request related to a problem? Please describe.**
Cosmos REST contracts are JSON.net annotated. For customers using streaming API a serialization implementation which can work with them is required.

**Describe the solution you'd like**
CosmosJsonSerializer.Default

**Describe alternatives you've considered**
Custom JSON.net code but it breaks once moved out of JSON.net FX.

**Comment by fuocor** [comment]
I left my opinion in another thread. The core API should be serialization agnostic and implement "stream only" functionality. The serialization should then be implemented in extensions and abstractions in a manner similar to how aspnet mvc abstracted away JSON.Net.
