### ISSUE TITLE
Gateway retry and timeout design

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1912]
The current design has the gateway timeout with always a [minimum of 65 seconds](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/67a2c582f510e91afdc9609b3779f06a8e04ec69/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L20). This causes high latency issues when there is a transient networking problem or other issues with gateway.

Proposed guideline:
### Metadata operations 
Non-hotpath (Account information)
Read:
5 second timeout (No delay on first retry)
10 second timeout
20 second timeout

Hotpath (QueryPlan, partition key ranges, address refresh)
Read retry in the same region. Does not impact region failover:
.5 second timeout (No delay on first retry)
5 second timeout
10 second timeout

Create, Update, Delete:
65 seconds

Timeouts will kill the connection.

**Comment by ealsur** [comment]
For 1, this basically would mean requests for metadata resources (Databases, Collections, etc), and also Query Plan?

Should backoff be exponential?

**Comment by j82w** [comment]
### Metadata operations 
Non-hotpath (Account information)
Read:
5 second timeout (No delay on first retry)
10 second timeout
20 second timeout

Hotpath (QueryPlan, partition key ranges, address refresh)
Read retry in the same region. Does not impact region failover:
.5 second timeout (No delay on first retry)
5 second timeout
10 second timeout

Create, Update, Delete:
65 seconds

Timeouts will kill the connection.

**Comment by sivethe** [comment]
@j82w : Does Query follow the same timeout patterns as Read?  What about ReadFeed operations?

**Comment by j82w** [comment]
This is only optimizing control plane requests. I was told the default is 65 seconds to allow gateway to handle split scenarios.

**Comment by j82w** [comment]
@sivethe just to be clear all item operations like read, query, ReadFeed, ChangeFeed, etc all follow the 65 second timeout for gateway mode.
