### ISSUE TITLE
Add support ContentResponseOnWrite option in CosmosClientBuilder

### ISSUE THREAD

**Issue by buchizo** [Azure/azure-cosmos-dotnet-v3#1917]
Currently .NET SDK support ContentResponseOnWrite option in ItemRequestOptions per requests. But that option doesn't configures in CosmosClientBuilder.

I would like to set default behavior for content response on write. For example, I want to default behavior is false about EnableContentResponseOnWrite option, and specific operation require response.

For example solution (want):

```csharp
var cosmosclient = new CosmosClientBuilder(connString)
                    .WithConnectionModeDirect()
                    .WithBulkExecution(false)
                    .WithContentResponseOnWrite(false) // <- want this
                    .Build();
```

relatded: https://devblogs.microsoft.com/cosmosdb/enable-content-response-on-write/#comment-168

**Comment by ealsur** [comment]
For reference, in Java SDK, the client has this setting at the client configuration level.

**Comment by kirankumarkolli** [comment]
Boolean as argument vs explicit method names (like WithNoContect...). Thoghts?

**Comment by asketagarwal** [comment]
Currently, JAVA has boolean as an argument for this property.
https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.cosmosclientbuilder.contentresponseonwriteenabled?view=azure-java-stable
