### ISSUE TITLE
When can we expect ChangeFeed to support hard deletion of documents in Cosmos

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-cosmos-dotnet-v3#1923]
**Is your feature request related to a problem? Please describe.**
In the current release of Change Feed,  hard deletes are not recognized. Therefore if a document has been physically deleted, then the downstream systems which is trying to react to changes will have no knowledge about this change.

There are GDPR regulations that require us to delete the records of our customers, which entails pysically deleting Comos documents.

**Describe the solution you'd like**
The Change Feed API should recognize hard deletion of documents and the document IDs should be made availabel via the API. 

**Describe alternatives you've considered**
Soft deletion is a work around. But, we would like a more permanent solution otherwise we end up with orphaned records.

**Additional context**
NA

**Comment by petro2050** [comment]
See #1808. I need the same thing. @timsander1 @ealsur can you please give us an update?

**Comment by timsander1** [comment]
Full fidelity change feed (deletes + intermediate updates) is currently in development. 

Here is our doc on current change feed limitations and recommended workarounds: https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-design-patterns#current-limitations

I can confirm that the Full fidelity change feed will address the Intermediate updates and Deletes limitation in the linked doc.

**Comment by ealsur** [comment]
Thanks Tim, closing as answered.

**Comment by petro2050** [comment]
@timsander1 I believe this was slated to go live in the fall of this year. Are you getting close to release?

**Comment by RichMercer** [comment]
It's a year later and still no sign of it. Has this feature been dropped?

**Comment by bartelink** [comment]
AIUI, At SDK level, it's preview and is reliant on the server side support being finalised, which is not something this repo can work around. [SO link asking same question](https://stackoverflow.com/questions/66360999/how-to-enable-full-fidelity-in-azure-cosmos-db-change-feed)

**Comment by ealsur** [comment]
@RichMercer  as @bartelink confirmed, this repo's scope is the client SDK, which contains the required APIs in preview. How the feature is enabled for existing users or how the feature is developed on the backend is unrelated to it and we just cannot answer that. If there are any required changes on the SDK based on the feature's evolution, they will be done here, but otherwise, these are questions we simply cannot answer.
