### ISSUE TITLE
Is it better to dynamically count records belonging to the same partition key or use an increment/decrement procedure?

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-dotnet-v3#1924]
I need to store some aggregate information in a separate container (i.e. post counts, follower counts, following counts, etc.). As of now, my strategy is that every time an item is inserted into or soft deleted from a container, I fire up its trigger and execute a Count query against the container and save the count value in a separate container. This seems to be working fine, but I have concerns about whether this is a scalable approach.

In a hypothetical scenario, if a post had, say, 100K likes, is it a good idea to Count (via a LINQ query) each time or should I use an increment/decrement directly on the existing counts? I'm also not sure whether dynamically getting counts from the containers over and over is cost effective. In my tests counting up to 200 records via LINQ, I noticed the RU cost stayed the **same** as the number of records to count increased. Would it still stay the same if I was counting tens of thousands of records?

I'm looking for guidance from the team as this is a crucial design decision on my part.

**Comment by ealsur** [comment]
Hi @petro2050, this is out of scope for this repo. Please use [Q&A](https://docs.microsoft.com/en-us/answers/topics/azure-cosmos-db.html) or [StackOverflow](https://stackoverflow.com/questions/tagged/azure-cosmosdb) for these types of questions.
