### ISSUE TITLE
Support multiple permissions with a single CosmosClient instance

### ISSUE THREAD

**Issue by alexmarchis** [Azure/azure-cosmos-dotnet-v3#1934]
**Context**
We are currently using Cosmos DB with the SQL API as the storage option for a .NET project where we configured multiple containers each with its own user permission.
The .NET SDK v2 DocumentClient can be constructed using a list of permissions that allows us to use a Singleton instance of DocumentClient to access multiple containers based on their specific permssions.

**Issue**
We would like to upgrade to the Cosmos .NET SDK v3 but we have an issue:
The v3 CosmosClient can only be instantiated with a single Permission.Token, thus implying the creation of a CosmosClient for each CosmosDB call to a different container. As the Microsoft Docs recommend to only instantiate one CosmosClient throughout the lifetime of the application (Singleton), we cannot migrate to v3 without sacrificing security or performance. Thus, the only way to maintain a single instance of CosmosClient is to use the Master Key meaning we lose the granular container level access permissions.

**Question/Suggestions**
Is there a plan to support this type of scenario in the future?
For example:
- CosmosClient instantiated with multiple permissions
- OR allow passing the Permission.Token as part of the RequestOptions with each request

What is Microsoft's recommendation for the design mismatch between recommending a single instance of CosmosClient and only allowing a single permission to be used per CosmosClient instance?

**Comment by tomasdeml** [comment]
I think this has already been reported under #651.
