### ISSUE TITLE
Creating databases with shared throughput is not reliable

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-dotnet-v3#1942]
I create 4 databases (under the same Cosmos DB account) back to back programmatically using your .NET SDK for Cosmos v3. It seems there is some kind of bug with shared throughput per database.

```
const int throughput = 800;
await cosmosClient.CreateDatabaseIfNotExistsAsync(databaseId, throughput);
```

The SDK sometimes creates the first database with 800 shared throughput, but it will ignore this request for subsequent databases. So the other 3 databases will be created with dedicated throughput per **container**. Now, what's strange is sometimes the SDK works as expected and creates 4 databases with 800 shared throughput each. I just got slammed with an unexpected bill because of this. I was also able to reproduce this several times.

**Comment by ealsur** [comment]
Can you share how the 4 databases are created? Are there any code differences? If you are using the same code to create all 4 databases, it sounds weird that some of them might be created differently?

Also, if you create a database with shared throughput, you can still create containers with dedicated throughput inside. When creating the container the throughput should not be specified. 

You can view who/how were any databases/containers created using the Log Analytics: https://docs.microsoft.com/en-us/azure/cosmos-db/audit-control-plane-logs

**Comment by bartelink** [comment]
Are you perhaps exceeding the max 25 containers with shared database throughput limit? (IIRC you can still add containers at that point, but only with RUs allocated at the Container level - perhaps your code is specifying the limits at Database and Container level?)

**Comment by ealsur** [comment]
@bartelink has a good point, see https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#set-throughput-on-a-database 

![image](https://user-images.githubusercontent.com/1633401/96522941-58efc600-1229-11eb-822a-b7885c280208.png)

**Comment by petro2050** [comment]
I'm not exceeding the 25 container limit. My databases have 7 containers each (28 total). When I deploy my Function app, it creates a 'leases' container in each database, hence the reason for 800 throughput per database. Also I do not specify throughput per container.

`var containerResponse = await database.CreateContainerIfNotExistsAsync(containerProperties);`

This line is executed per container in each database. `throughput` is a nullable int in the method signature and I leave it untouched.

As I said before, this issue is intermittent. I'll pay attention to log analytics going forward to see if there is anything there.

**Comment by ealsur** [comment]
The SDK only sends the payload to the backend, if you are not specifying throughput, then we don't send it to the backend. 

Having the SDK send a random throughput number when the user is not specifying it makes little sense to me. I mean, I don't see a technical way for this to happen. 

You mentioned lease containers, are you creating them with the `CreateContainerIfNotExistsAsync` or are you using the `CosmosDBTrigger` function binding create it for you?

**Comment by petro2050** [comment]
Just like you said, this may not be an SDK problem but a backend issue. I create the lease containers with the `CosmosDBTrigger`. The routine I follow is first create the databases and containers and then redeploy the function app which seems to create the lease containers. I also have a `TimerTrigger` that runs every minute to try to reduce cold start times.

**Comment by ealsur** [comment]
`CosmosDBTrigger` uses V2 SDK: 

* https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs#L192
* https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/CosmosDBUtility.cs#L111

If you are not specifying the `LeasesCollectionThroughput` then it's not being passed and the decision is on the backend.

**Comment by ealsur** [comment]
Closing as not related to the SDK. Please reopen if you have a repro we can use to diagnose.
