### ISSUE TITLE
RequestMessage.Properties dictionary is not preserved for CreateContainerIfNotExistsAsync

### ISSUE THREAD

**Issue by stpetzinger** [Azure/azure-cosmos-dotnet-v3#1948]
**Description**
The Properties property of RequestOptions gets zero'd out when calling CreateContainerIfNotExistsAsync with an already existing container.  When Properties are specified on the RequestOptions for the operation, by the time the RequestMessage is picked up by any Request Handlers, the Properties Dictionary is empty. If the Container doesn't exist, another operation (POST) will occur internally to create the Container, and this will have the properties.  But we use these properties for logging and telemetry, so we would prefer that we have this information for all Cosmos DB calls.  The same scenario doesn't apply to CreateDatabaseIfNotExists (i.e. the Properties will be preserved for both the read and create operations).  Is this behavior by design?  Is there a way I can write my code so that I can still get the required information?

**To Reproduce**
To reproduce the issue, create a Request Handler that will just output the Properties dictionary of requestMessage.  Attach the Request Handler to a CosmosClient and call CreateContainerIfNotExistsAsync with a new ReadOnlyDictionary of some test data in the RequestOptions parameter.  Call the function twice each to observe the behavior when the container does and doesn't exist.

**Example code**
```
public class TestRequestHandler : RequestHandler
{
	public override Task<ResponseMessage> SendAsync(RequestMessage request, CancellationToken cancellationToken)
	{
		Console.WriteLine($"\t{request.Method}-{request.RequestUri} Property count: {request.Properties.Count}");
		foreach (var property in request.Properties)
		{
			Console.WriteLine($"\t\t{property.Key}: {property.Value}");
		}
		return base.SendAsync(request, cancellationToken);
	}
}
	
private static async Task Main(string[] args)
{
	string endpoint = "<removed>";
	string authKey = "<removed>";
	string databaseId = Guid.NewGuid().ToString();
	string containerId = Guid.NewGuid().ToString();

	var cosmosClientBuilder = new CosmosClientBuilder(endpoint, authKey);
	cosmosClientBuilder.AddCustomHandlers(new TestRequestHandler());

	var client = cosmosClientBuilder.Build();

	IReadOnlyDictionary<string, object> props = new ReadOnlyDictionary<string, object>(
		new Dictionary<string, object>
		{
			{ "test1", "value1" },
			{ "test2", "value2" }
		});

	Console.WriteLine("CreateDatabaseIfNotExistsAsync (new database)");
	var databaseResponse = await client.CreateDatabaseIfNotExistsAsync(DatabaseId, requestOptions: new RequestOptions { Properties = props });

	Console.WriteLine("CreateDatabaseIfNotExistsAsync (existing database)");
	await client.CreateDatabaseIfNotExistsAsync(DatabaseId, requestOptions: new RequestOptions { Properties = props });

	var database = databaseResponse.Database;

	Console.WriteLine("CreateContainerIfNotExistsAsync (new container)");
	// GET will contain 0 Properties
	await database.CreateContainerIfNotExistsAsync(ContainerId, "/Key", 400, new RequestOptions { Properties = props });

	Console.WriteLine("CreateContainerIfNotExistsAsync (existing container)");
	// GET will contain 0 Properties
	await database.CreateContainerIfNotExistsAsync(ContainerId, "/Key", 400, new RequestOptions { Properties = props });
}
```
**Expected behavior**
When calling CreateContainerIfNotExists, the GET operation to determine if the container exists will retain its request options Properties from the parameters that the function was called with.

**Actual behavior**
The GET operation to get the existing container no longer has the request options properties that the function was called with.  The POST operation to create the container (if necessary) does, however, retain the RequestOptions properties.

**Environment summary**
SDK Version: v3.14
OS Version: Windows 10 and Cosmos DB Emulator

**Comment by j82w** [comment]
@stpetzinger  please try the latest [3.15.0 release](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.15.0)
