### ISSUE TITLE
Count number of items in the container function.

### ISSUE THREAD

**Issue by Kiril1512** [Azure/azure-cosmos-dotnet-v3#1951]
Hello. It is possible to create on the SDK a container function that will return the number of items in the container? For example, we could have:

- `Count()` that will return count of all items in the container;
- `Count<T>()` that will return count of all items of type `T` in the container;
- `Count(query)` that will return count of all items in the container using the query;
- `Count<T>(query)` that will return count of all items of type `T` in the container using the query.

If we want to do something like that today, we need to do this:

```c#
public async Task<int> CountItems()
{
    int count = 0;

    var query = this._container.GetItemQueryIterator<int>(new QueryDefinition("SELECT value count(1) FROM cosmosItem"));

    while (query.HasMoreResults)
    {
        FeedResponse<int> response = await query.ReadNextAsync();

        count += response.Resource.FirstOrDefault();
    }

    return count;
}
```

If this feature is not possible, what is the best way to count items in the container using as less as possible RU/s?

Thank you!

**Comment by j82w** [comment]
@Kiril1512 what is the reason for needing to know the number of items in the container?

**Comment by Kiril1512** [comment]
> @Kiril1512 what is the reason for needing to know the number of items in the container?

There are many reasons I can think for counting the number of items on the container. 

In my case, I need to retrieve a certain % of items at a time. So if a container has 100 items, and I want to retrieve 20% of the items, I need to calculate how much is 20% of 100 items and retrive only that number (20 items).

Since this is a multi model database, I have multi models on the container so this example is if I have customers with region attribute:

```json
{
  "customers": [
    {
      "id": "1",
      "name": "SomeCustomer",
      "region": "WesternEurope"
    },
    {
      "id": "2",
      "name": "AnotherCustomer",
      "region": "NorthAmerica"
    },
    {
      "id": "3",
      "name": "DummyCustomer",
      "region": "WesternEurope"
    }
  ]
}
```

If I want just to count the number of customers that are from "WesternEurope", I need to retrieve all customers and then do the count on the server. 

With `Count("SELECT value count(1) FROM customers WHERE customers.region == "WesternEurope")` the SDK would return me 2 and it would be more easier.

**Comment by Kiril1512** [comment]
Any feedback about this?

**Comment by diegosasw** [comment]
This was a good idea. It's disappointing that it's been closed.

I'm working with CosmosDb for first time and it's unfortunate there isn't a straightforward way to count all the items within a container which satisfy certain conditions.

For example, there could be a method that counts and accepts iqueryable. Right now if you have a linq query with a where clause (Expression<Func<T, bool>>, it's not possible to count.

An extension method to support that would be ideal.
