### ISSUE TITLE
CosmosClientBuilder ArgumentException with HTTP Client Factory and Gateway connection mode.

### ISSUE THREAD

**Issue by jirikopecky** [Azure/azure-cosmos-dotnet-v3#1953]
**Describe the bug**
When configuring Cosmos client using `CosmosClientBuilder`, exception is thrown if I call `WithHttpClientFactory` and then `WithConnectionModeGateway`.

**To Reproduce**
Following code will throw ArgumentException:
```
var builder = new CosmosClientBuilder("<<endpoint-here>>", "<<key-here>>")
    .WithHttpClientFactory(_httpClientFactory.CreateClient)
    .WithConnectionModeGateway();
```

**Expected behavior**
A client builder is created with configured HTTP client factory and Gateway connection mode.

**Actual behavior**
ArgumentException is thrown. 

**Environment summary**
SDK Version: 3.14.0
OS Version (e.g. Windows, Linux, MacOSX): Windows 10 x64

**Additional context**
```
Stack Trace Information Details: 
======================================
at Microsoft.Azure.Cosmos.CosmosClientOptions.set_WebProxy(IWebProxy value)
at Microsoft.Azure.Cosmos.Fluent.CosmosClientBuilder.WithConnectionModeGateway(Nullable`1 maxConnectionLimit, IWebProxy webProxy)
```

**Comment by j82w** [comment]
@jirikopecky please try the latest [3.15.0 release](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.15.0)
