### ISSUE TITLE
Using the value of one operation as input for another, within the same TransactionalBatch

### ISSUE THREAD

**Issue by RichWK** [Azure/azure-cosmos-dotnet-v3#1958]
This is mostly directed at @ealsur (sorry 😉 ) in reference to a comment he made on the [blog post](https://devblogs.microsoft.com/cosmosdb/introducing-transactionalbatch-in-the-net-sdk/) originally announcing TransactionalBatch as a feature.

At the bottom, he stated:

_"Using a value from one operation as input of another within the same TransactionalBatch is not currently supported."_

Which left me wondering... is that something which will change in the future? Is that kind of functionality on the roadmap?

The reason I'm interested: I'm currently putting together something which requires an atomic read-write, and it looks like the only way to currently achieve this with CosmosDB is via a stored procedure written in JavaScript. That's fine, I've almost finished writing it, but... that particular area of CosmosDB seems stagnant at best. (The main documentation for the server-side Javascript environment it uses hasn't been updated since 2018, for example.)

So it'd be great to get a little bit of clarification on the intended future direction for situations like mine.

**Comment by ealsur** [comment]
@abhijitpai Could you share if this is something that is on the roadmap or any ideas?

**Comment by j82w** [comment]
@RichWK can you give an example of why you need atomic read-write?

**Comment by RichWK** [comment]
It's basically the same situation as described in Tom Robinson's comment on that blog post I linked to. This is what's happening:

- We have a frontend where a user can request 1 to 10 unique IDs
- These IDs are sequential, so they might end up with "100,000,022", "100,000,023" and "100,000,024", for example
- If two users make a request at exactly the same time, they **must not** receive the same IDs

Previously I had an Azure Function talking to a Cosmos DB and doing this:

- Read the "current ID"
- Increment by however many IDs the user requested
- Update the new "current" value back to the database (and supply the user with their IDs)

But that resulted in the same IDs being issued if two people made a request at exactly the same time — hence my current situation, writing a stored procedure for an atomic read-write.

Am I approaching this incorrectly?

**Comment by ealsur** [comment]
Mmmm number incremental identifiers for distributed databases is kind of a tight pinch, isn't it?

**Comment by j82w** [comment]
Is there any reason [unique-keys](https://docs.microsoft.com/en-us/azure/cosmos-db/unique-keys) wouldn't solve the issue?

**Comment by RichWK** [comment]
@ealsur Hahah yes, when you put it like that... it doesn't sound great. 😄 The frontend has very low usage, so CosmosDB was attractive due to serverless billing recently having entered preview status.

So regardless, it seems like this is too much of an edge case to be supported in the .NET SDK.

@j82w There isn't actually more than a single record being created, ever — this is the entire database:

![image](https://user-images.githubusercontent.com/23324243/97061397-931fd700-154b-11eb-825b-94720cf80999.png)

**Comment by abhijitpai** [comment]
If you have low concurrency for the requests trying to get these unique ids, just a read-increment-replace loop where the replace uses optimistic concurrency control as per https://docs.microsoft.com/en-us/azure/cosmos-db/database-transactions-optimistic-concurrency#optimistic-concurrency-control may suffice. The caller is only provided with the ids after the replace has succeeded.

For high concurrency, stored procedures as you mentioned could be an option for now to achieve what you need. 
We are looking at exposing item patch functionality with an increment operator in future that can help simplify this use case.

**Comment by RichWK** [comment]
Thanks for the advice! Much appreciated. @abhijitpai
