### ISSUE TITLE
Documentation - Sample Correction

### ISSUE THREAD

**Issue by laultman** [Azure/azure-cosmos-dotnet-v3#1959]
Error in the sample: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs#L203-L241

**Describe the bug**
The code at the very end of the file does not work. In this case "database" is a DatabaseResponse object not the Database.
`// Create with a throughput of 1000 RU/s
            container = await database.CreateContainerIfNotExistsAsync(
                containerProperties,
                throughput: 1000);`

The code should look like ... = await database.Database.CreateContainerIfNotExistsAsync(...

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
@lautman CreateContainerIfNotExist returns a DatabaseResponse but DatabaseResponse has an [implicit Database operator](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseResponse.cs#L71).

![image](https://user-images.githubusercontent.com/1633401/97324041-a45c3280-182e-11eb-9b00-c529f03c9557.png)

**Comment by ealsur** [comment]
Closing. There is really no issue here, the project has no runtime or build errors. The type is correct as per the implicit operation.

Please reopen if you can share which is the error you are encountering while running the sample.
