### ISSUE TITLE
Shared offer Database create is forbidden as count of shared offer database has exceeded 5.

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-cosmos-dotnet-v3#1964]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Create database returns the following exceptions:

> Unhandled exception. CosmosException;StatusCode=BadRequest;SubStatusCode=1020;ActivityId=937aa208-63ef-46cf-ba5a-9164e37a042f;RequestCharge=0;
> Message=Response status code does not indicate success: 400 Substatus: 1020 
> Reason: (Message: {"Errors":["Shared offer Database create is forbidden as count of shared offer database has exceeded 5."]}
> 	ActivityId: 937aa208-63ef-46cf-ba5a-9164e37a042f,
> 	Request URI: /apps/74ef0a94-e7cd-4176-9106-f135a5cc22df/services/58e444c8-3c56-4bfb-8e8f-7f01ac9b09fc/partitions/0e81d68a-ceac-42de-9734-0ec69010fcce/replicas/132475546319198142p,
> 	RequestStats: RequestStartTime: 2020-10-26T23:07:44.6042854Z,
> 	RequestEndTime: 2020-10-26T23:07:44.6042854Z,
> 	Number of regions attempted:1
> 	ResponseTime: 2020-10-26T23:07:44.6042854Z, 
> 	StoreResult: 
> 	StorePhysicalAddress: rntbd://10.0.0.26:11000/apps/74ef0a94-e7cd-4176-9106-f135a5cc22df/services/58e444c8-3c56-4bfb-8e8f-7f01ac9b09fc/partitions/0e81d68a-ceac-42de-9734-0ec69010fcce/replicas/132475546319198142p,
> 	LSN: 6396, 
> 	GlobalCommittedLsn: 6396, 
> 	PartitionKeyRangeId: ,
> 	IsValid: True, 
> 	StatusCode: 400, 
> 	SubStatusCode: 1020, 
> 	RequestCharge: 0, 
> 	ItemLSN: -1, 
> 	SessionToken: -1#6396,
> 	UsingLocalLSN: False,
> 	TransportException: null,
> 	ResourceType: Database,
> 	OperationType: BatchApply,
> 	SDK: Microsoft.Azure.Documents.Common/2.11.0,
> 	Linux/10 cosmos-netstandard-sdk/3.3.0).;Diagnostics

It works before, could you please suggest what does it mean? I can't find any info about that error
As I understand, I can't use more than 5 Databases with shared Throughput in this account, but in other, it works. Can be the reason that Free Tier Discount is Opted In for the account? Where I can find any docs?

**To Reproduce**

`_client.CreateDatabaseIfNotExistsAsync(databaseName, throughput).GetAwaiter().GetResult();`

**Expected behavior**
The new database should be created

**Actual behavior**
Error.

**Environment summary**
SDK Version: 3.3.3
OS Version Windows and Linux

**Additional context**
In azure Free Tier Discount is Opted In for my Azure Cosmos DB account

**Comment by ealsur** [comment]
This is not an SDK issue, this is a response coming from the service. Please see the Service Limits: https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#free-tier-account-limits
