### ISSUE TITLE
Flaky ChangeFeedIteratorCoreTests

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1968]
The following test appears to have a bug causing it occasionally fail in the gates.
Microsoft.Azure.Cosmos.Tests.FeedRange.ChangeFeedIteratorCoreTests.ChangeFeedIteratorCore_HandlesSplitsThroughPipelineazure-pipelines/ azure-cosmos-dotnet-v3-functionalMicrosoft.Azure.Cosmos.Tests.FeedRange.ChangeFeedIteratorCoreTests.ChangeFeedIteratorCore_HandlesSplitsThroughPipelineAssert.AreEqual failed. Expected:<100>. Actual:<99>.

Link: https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=24451&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&s=d654deb9-056d-50a2-1717-90c08683d50a&t=c5b2d381-db84-5070-406d-2daac9cef82b&l=2060

**Comment by j82w** [comment]
Microsoft.Azure.Cosmos.EmulatorTests.FeedRanges.ChangeFeedIteratorCoreTests.ChangeFeedIteratorCore_OfT_ReadAll
Test method Microsoft.Azure.Cosmos.EmulatorTests.FeedRanges.ChangeFeedIteratorCoreTests.ChangeFeedIteratorCore_OfT_ReadAll threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by j82w** [comment]
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=24605&view=logs&jobId=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f&j=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f&t=9a2f41b1-a565-5286-ece2-d41341f47180

**Comment by j82w** [comment]
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=24812&view=logs&jobId=fef5d8be-9ecf-5e7a-84d5-f2c0b04a2d13&j=fef5d8be-9ecf-5e7a-84d5-f2c0b04a2d13&t=29c9c104-7def-54b3-f016-d8bb3a0670a7

**Comment by j82w** [comment]
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=24976&view=logs&j=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f&t=9a2f41b1-a565-5286-ece2-d41341f47180&l=2046

**Comment by j82w** [comment]
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=25369&view=logs&jobId=fef5d8be-9ecf-5e7a-84d5-f2c0b04a2d13&j=fef5d8be-9ecf-5e7a-84d5-f2c0b04a2d13&t=29c9c104-7def-54b3-f016-d8bb3a0670a7

**Comment by bchong95** [comment]
I haven't seen this test fail in recent history.
