### ISSUE TITLE
Missing JsonSerialization parameter

### ISSUE THREAD

**Issue by JohnLTaylor** [Azure/azure-cosmos-dotnet-v3#197]
**Describe the bug**
If the DocumentClient is created with a JsonSerializerSettings with DateFormatHandling set to MicrosoftDateFormat, then calls to Create the document correctly encode the string, but upsert and replace do not correctly encode the date.

The problem is that the function UpsertDocumentPrivateAsync in the call to [DocumentServiceRequest.Create](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d6b7638a03fc88698d75b5d59ae2f9eaff17d38a/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L3115) passes a default null for the JsonSerializerSettings param instead of call this.GetSerializerSettingsForRequest(options) like CreateDocumentPrivateAsync.

It also looks like [ReplaceDocumentPrivateAsync](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d6b7638a03fc88698d75b5d59ae2f9eaff17d38a/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L5505) is suffering from the same problem.

**To Reproduce**
Create a database client with a JsonSerializerSettings with DateFormatHandling set to MicrosoftDateFormat,.  Call UpsertDocumentAsync with a document containing a date field

**Expected behavior**
The date field should be encoded with the MicrosoftDateFormat

**Actual behavior**
The date field is encoded with the default IsoDateFormat

**Environment summary**
SDK Version:
Found in 2.2.1
Verified in 2.4.0
Code checked in 3.0.0.10
OS Version Windows 10

**Comment by JohnLTaylor** [comment]
Created fix in [pull request 199](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/199)

**Comment by j82w** [comment]
In v3 SDK you can implement a CosmosJsonSerializer.

`CosmosClient cosmosClient = new CosmosClientBuilder("http://localhost", "SuperSecretKey").UseCustomJsonSerializer(new CustomJsonSerializer).Build()`

**Comment by JohnLTaylor** [comment]
Setting the serializer option isn't the problem.  The upsert/replace methods do not honor the serializer setting.

**Comment by j82w** [comment]
I'm closing this issue since this is a v2 problem. Please create an [issue here](https://github.com/Azure/azure-cosmos-dotnet-v2) for it. 

In the v3 SDK we removed serializer settings and converted everything to use a CosmosJsonSerializer. There is a default implementation, and users can implement their own version. All the methods in v3 go through this serializer so it doesn't have the same bug has v2.

**Comment by JohnLTaylor** [comment]
From reading the code I still see the problem.  In my PR I'm making UpsertDocumentPrivateAsync and ReplaceDocumentPrivateAsync match [CreateDocumentPrivateAsync](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e76130550be20271390569de064abba906108d8c/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L1841)
