### ISSUE TITLE
[Question] Log executed query without parameters

### ISSUE THREAD

**Issue by darthkurak** [Azure/azure-cosmos-dotnet-v3#1970]
Hello. I would like to log and monitor queries executed by our platform.
I'm going to use CustomHandlers, which seems to have almost all information which i need.
I can get executed query from request.Content, but i wonder - is there any way to get that query without parameters values?
(We can't log full query with values due to privacy concern).

**Comment by j82w** [comment]
@bchong95 any suggestions?

**Comment by darthkurak** [comment]
Another thing is that there are a lot useful information like (operationName, adressResolved, whole DocumentServiceRequest, which are internal and i can't them without using reflection. There is possibility that you could make them public? :)

**Comment by bchong95** [comment]
You can parse the Content, since it's a Json Object with queryText and paramaters property. log only the queryText.

**Comment by darthkurak** [comment]
Yes, but the content for queries generated from linq or passed as pure string has query in whole version - without parameters. I don't want to force usage of SDK in my whole platform to API .WithParameters(). And there is always chance that someone put pure string query anyway.

**Comment by bchong95** [comment]
It sounds like you want to emit an obfuscated query. In which case I recommend parsing the query with this parser:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Query/Core/Parser/SqlQueryParser.cs

and use this obfuscator:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectObfuscator.cs

You are going to need access to internals to get this to work.

**Comment by bchong95** [comment]
Please reopen the issue if there are further questions.
