### ISSUE TITLE
WithParameter in QueryDefinition Throws error using json nested dotted notation.

### ISSUE THREAD

**Issue by laultman** [Azure/azure-cosmos-dotnet-v3#1990]
We are using automation to build queries from existing data and there are nested json objects. The automation resolves nested json objects as dotted notation nested parameters. It generates the replaceable @parameter part from the field parameter resolved. With this very limited parameter replacement method we have to write a considerable amount of code to manage this issue.
Our current workaround is to filter the dots and ensure the fields remain unique matches.

Example:
In a cosmos document there could be a nested object
},
"Updated":{ "unixtime":15336895,"status":true},
The failing query pattern:
SELECT TOP 10 * from PLsystem c where c.opstatus=@opstatus and c.ApplicationId=@ApplicationId and c.Updated.unixtime>=@Updated.unixtime
**Describe the bug**
.WithParameter("@Updated.unixtime", 1565705133)

Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"Errors":["Invalid query. Specified parameter name '@Updated.unixtime' is invalid. Parameter names should be in the format of symbol '@' followed by a valid identifier. E.g. @param1"]}

**To Reproduce**
Use the sample [project](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/Queries/Program.cs#L154-L186)
Start at line 194. In line 200, Modify the query definition to use nested parameters using the full path.
QueryDefinition query = new QueryDefinition("SELECT * FROM Families f WHERE f.id = @id AND f.Address.City = @Address.City")
Change line 202 to: .WithParameter("@Address.City", "Seattle");

**Expected behavior**
I would expect that the parameter would not care about dotted notation and accept the input.

**Actual behavior**
Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"Errors":["Invalid query. Specified parameter name '@Updated.unixtime' is invalid. Parameter names should be in the format of symbol '@' followed by a valid identifier. E.g. @param1"]}

**Environment summary**
SDK Version: v3
OS Version (e.g. Windows, Linux, MacOSX) Window 10 current version.

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by bchong95** [comment]
The grammar for parameter does not accept dots, since it would conflict with PropertyReferences. A workaround is to PascalCase your parameter names so:

```
QueryDefinition query = new QueryDefinition("SELECT * FROM Families f WHERE f.id = @id AND f.Address.City = @Address.City")
Change line 202 to: .WithParameter("@Address.City", "Seattle");
```

becomes

```
QueryDefinition query = new QueryDefinition("SELECT * FROM Families f WHERE f.id = @id AND f.Address.City = @AddressCity")
Change line 202 to: .WithParameter("@AddressCity", "Seattle");
```
