### ISSUE TITLE
Readfeed: Initial page regression

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1991]
The performance testing with ReadFeed found that the pagination library has dropped throughput by roughly 1/3 (roughly 12,000 to 4,000 RPS). Can you please prioritize fixing this performance regression as it is blocking any future release. This will triple the latency of any customer that does a paging API with read feed. 

  4aafe495fa80084c635ad6d14af2b4f9c2ee2c21 // Before pagination library
              "Top10PercentAverageRps": 11892,
    "Top20PercentAverageRps": 11668,
    "Top30PercentAverageRps": 11513,
    "Top40PercentAverageRps": 11393,
    "Top50PercentAverageRps": 11276,
    "Top60PercentAverageRps": 11166,
    "Top70PercentAverageRps": 11054,
    "Top80PercentAverageRps": 10945,
    "Top90PercentAverageRps": 10758,
    "Top95PercentAverageRps": 10599,
    "Top50PercentLatencyInMs": 5.8927,
    "Top75PercentLatencyInMs": 8.5627,
    "Top90PercentLatencyInMs": 14.23982666666666,
    "Top95PercentLatencyInMs": 33.17296499999997,
    "Top99PercentLatencyInMs": 423.85041366666525,
    "AverageRps": 10419,
              
              
              a0d24da61bc34b1b350731fe86335530e28e85ad // After pagination library
    "Top10PercentAverageRps": 3725,
    "Top20PercentAverageRps": 3694,
    "Top30PercentAverageRps": 3663,
    "Top40PercentAverageRps": 3628,
    "Top50PercentAverageRps": 3597,
    "Top60PercentAverageRps": 3569,
    "Top70PercentAverageRps": 3542,
    "Top80PercentAverageRps": 3512,
    "Top90PercentAverageRps": 3471,
    "Top95PercentAverageRps": 3435,
    "Top50PercentLatencyInMs": 20.1692,
    "Top75PercentLatencyInMs": 23.3745,
    "Top90PercentLatencyInMs": 50.03446333333333,
    "Top95PercentLatencyInMs": 82.87432999999993,
    "Top99PercentLatencyInMs": 1276.8166326666667,
              "AverageRps": 3383,

Internal ReadFeed: Adds pagination library adoption commit: a0d24da61bc34b1b350731fe86335530e28e85ad (orange)
https://github.com/Azure/azure-cosmos-dotnet-v3/commit/a0d24da61bc34b1b350731fe86335530e28e85ad

Commit before is: 4aafe495fa80084c635ad6d14af2b4f9c2ee2c21 (blue)

![perf](https://user-images.githubusercontent.com/8868107/98598292-1866f380-228f-11eb-9ef0-2ce91beb95e5.jpg)

This is being run on an Azure VM in the same region as the container using Direct + TCP. 
https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Tools/Benchmark

You can build and run the project using:
dotnet build --configuration Release -p:"OSSProjectRef=true;ShouldUnsetParentConfigurationAndPlatform=false"
$log = git log -1
$commit = $log.Split([Environment]::NewLine)[0].Substring(7)
$branch = git branch --show-current
dotnet run  -c Release --no-build  -- -e https://.documents.azure.com:443/ -k UPa== --disablecoresdklogging --publishresults --resultspartitionkeyvalue headerTest --branchname $branch  --database testdb --container testcol --partitionkeypath /pk -n 2000000 -w ReadFeedStreamV3 --pl 200 --commitid $commit --commitdate 'Wed Aug 12 2020' --committime  '05:49:38' –enablelatencypercentiles

**Comment by j82w** [comment]
Please validate the full end to end scenario where the entire read feed is drained.

**Comment by bchong95** [comment]
I ran the read feed benchmark that is checked into the performance project:


Before:
```
|   Method |      Type |       Mean |     Error |     StdDev |     Median |         Q3 |        P80 |        P85 |        P90 |        P95 |       P100 |    Op/s | Gen 0 | Gen 1 | Gen 2 | Allocated | Completed Work Items | Lock Contentions |
|--------- |---------- |-----------:|----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|--------:|------:|------:|------:|----------:|---------------------:|-----------------:|
| ReadFeed |    Stream |   920.3 us |  98.42 us |   274.4 us |   845.5 us | 1,009.3 us | 1,062.3 us | 1,159.1 us | 1,371.8 us | 1,544.8 us | 1,709.4 us | 1,086.6 |     - |     - |     - |  37.59 KB |               1.0000 |                - |
| ReadFeed |       OfT | 4,000.0 us | 432.75 us | 1,262.3 us | 3,594.8 us | 4,836.8 us | 5,123.0 us | 5,406.7 us | 5,931.5 us | 6,344.9 us | 7,692.6 us |   250.0 |     - |     - |     - | 552.84 KB |               1.0000 |                - |
| ReadFeed | OfTCustom | 3,963.8 us | 393.90 us | 1,142.8 us | 3,852.8 us | 4,777.8 us | 4,894.8 us | 5,155.5 us | 5,755.6 us | 6,139.9 us | 7,058.1 us |   252.3 |     - |     - |     - | 553.21 KB |               1.0000 |                - |
```
After:
```
|   Method |      Type |       Mean |     Error |     StdDev |     Median |         Q3 |        P80 |        P85 |        P90 |        P95 |       P100 |    Op/s | Gen 0 | Gen 1 | Gen 2 | Allocated | Completed Work Items | Lock Contentions |
|--------- |---------- |-----------:|----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|--------:|------:|------:|------:|----------:|---------------------:|-----------------:|
| ReadFeed |    Stream |   948.8 us |  74.64 us |   205.6 us |   896.2 us | 1,070.0 us | 1,108.3 us | 1,127.7 us | 1,193.5 us | 1,378.8 us | 1,569.1 us | 1,053.9 |     - |     - |     - |   40.2 KB |               2.0000 |                - |
| ReadFeed |       OfT | 4,609.1 us | 468.50 us | 1,366.6 us | 4,379.8 us | 5,426.5 us | 5,562.0 us | 6,110.0 us | 6,722.1 us | 7,214.0 us | 8,184.3 us |   217.0 |     - |     - |     - | 555.81 KB |               1.0000 |                - |
| ReadFeed | OfTCustom | 3,819.3 us | 350.74 us |   995.0 us | 3,537.3 us | 4,218.6 us | 4,523.2 us | 4,948.0 us | 5,454.2 us | 5,997.5 us | 6,601.6 us |   261.8 |     - |     - |     - |  555.8 KB |               1.0000 |                - |
```

So no significant regression.

**Comment by j82w** [comment]
The benchmarks I provided originally are full end to end in production tests. The mocked benchmarks you posted completely bypass all transport logic, and will not show any issues caused by additional network calls.

**Comment by j82w** [comment]
This was fixed in PR: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2012 . The pagination library introduced a regression that caused read feed to go to every partition even when a single partition key was selected.
