### ISSUE TITLE
[RFC] Proxy support

### ISSUE THREAD

**Issue by nulltoken** [Azure/azure-cosmos-dotnet-v3#2]
re: azure/azure-cosmos-dotnet-v2#434

I'd be willing to contribute a pull request to support that.

However, as there may potentially be various ways to put that in place, I'd like first to discuss about how you would prefer to see this implemented.

[Java][proxy-java] and [Node][proxy-node] versions of the SDK seem to expose the proxy address through a get/setter exposed by the `ConnectionPolicy` class.

However, I'm wondering if that wouldn't be actually easier to 
 - Accept an optional `HttpMessageHandler` which would be wrapped by the [internal][internal-handler] `HttpMessageHandler` and from which we would build the `HttpClient`
 - Or accept an optional delegate that would be used to create an `HttpMessageHandler`. This may actually pave the way to later leverage the `HttpClientFactory`.

I understand that going the `HttpMessageHandler` way would actually make this SDK API differ from the other languages from an API standpoint. However, it's not uncommon for a .NET Api to accept a handler from which the back channel is built.

Thoughts?`

 [internal-handler]: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/7e49190e518b5ee3e0a604f8d17586c7603912f8/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L855
 [proxy-java]: https://github.com/Azure/azure-cosmosdb-java/blob/b491cb1b40e29e3114ec23d8dad89a16d18cbe4d/commons/src/main/java/com/microsoft/azure/cosmosdb/ConnectionPolicy.java#L345
 [proxy-node]: https://github.com/Azure/azure-cosmosdb-node/blob/ca337c9ddff136e01d6f589a45e24957d3efe5e3/source/lib/documents.js#L283

**Comment by southpolesteve** [comment]
@nulltoken 👋 Node SDK maintainer here. FWIW I'm advocating to change this in the next major release of the Node SDK as well. I would like to have proxy support by passing a custom agent such as https://github.com/TooTallNate/node-proxy-agent

**Comment by nulltoken** [comment]
@southpolesteve Thanks a lot for the feedback!

⚠️ Full disclosure here: **Not a Node expert**. Although, from what I read from the doc, the `http.Agent` approach indeed looks very similar to what I had in mind.

Once again, thanks for sharing.

**Comment by christopheranderson** [comment]
Hey @nulltoken, we're about to release this support in the 2.x version of the SDK (which can be found here: https://github.com/azure/azure-cosmos-dotnet-v2). This support will likely also be in 3.x, which is what this repo is here for.
