### ISSUE TITLE
System.MissingMethodException BulkExecutor..ctor when referencing .NET Standard from .NET Framework

### ISSUE THREAD

**Issue by weng271190436** [Azure/azure-cosmos-dotnet-v3#200]
**Describe the bug**
I am using Microsoft.Azure.CosmosDB.BulkExecutor 2.3.0-preview2.

If I call new BulkExecutor(DocumentClient, DocumentCollection) from a .NET Standard 2.0 library and I call the .NET Standard library from .NET Framework 4.7.2, a System.MissingMethodException: 'Method not found: 'Void Microsoft.Azure.CosmosDB.BulkExecutor.BulkExecutor..ctor(Microsoft.Azure.Documents.Client.DocumentClient, Microsoft.Azure.Documents.DocumentCollection)'.'
is thrown.

**To Reproduce**

My .NET Framework 4.7.2 console app.

```
namespace NetFrameworkConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            NetStandardLibrary.Class1.CreateBulkExecutor();
        }
    }
}
```

.NET Framework console app's csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetStandardLibrary\NetStandardLibrary.csproj" />
  </ItemGroup>

</Project>
```

My .NET Standard 2.0 library.

```
using Microsoft.Azure.CosmosDB.BulkExecutor;
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;
using System;
using System.Linq;

namespace NetStandardLibrary
{
    public class Class1
    {
        public static void CreateBulkExecutor()
        {
            var client = new DocumentClient(
                new Uri("https://documentdb.com"),
                "documentkey",
                ConnectionPolicy.Default,
                ConsistencyLevel.Session);
            DocumentCollection documentCollection = client.CreateDocumentCollectionQuery(UriFactory.CreateDatabaseUri("mydatabase"))
                .Where(c => c.Id == "mycollectionid").AsEnumerable().FirstOrDefault();
            var bulkExecutor = new BulkExecutor(client, documentCollection);
        }
    }
}
```

.NET Standard 2.0 library's csproj.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.CosmosDB.BulkExecutor" Version="2.3.0-preview2" />
  </ItemGroup>

</Project>
```

**Expected behavior**
Should be able to call the BulkExecutor constructor.

**Actual behavior**
The MissingMethodException was thrown at runtime when I try to step into NetStandardLibrary.Class1.CreateBulkExecutor(); in Visual Studio 2019.

**Environment summary**

SDK Version:
Microsoft.Azure.CosmosDB.BulkExecutor 2.3.0-preview2.

OS Version (e.g. Windows, Linux, MacOSX): 
Windows 10 Enterprise 10.0.18362 Build 18362

**Additional context**
I have to add nuget package Microsoft.Azure.DocumentDB.Core to my .NET Framework 4.7.2 console app. Else, I will hit System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Azure.DocumentDB.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'

**Comment by weng271190436** [comment]
I posted this issue in Azure/azure-cosmos-dotnet-v2 repository as well. 
https://github.com/Azure/azure-cosmos-dotnet-v2/issues/701

Not sure where is the right place.

**Comment by JohnLTaylor** [comment]
I saw this a long time ago.  Double check the version of DocumentDB vs the installed version of Service Fabric SDK.  I was running an old SDK with a newer DocumentDB version.  Updating the SDK fixed my problem.

It would be nice if there was a better error message :)

**Comment by weng271190436** [comment]
> I saw this a long time ago. Double check the version of DocumentDB vs the installed version of Service Fabric SDK. I was running an old SDK with a newer DocumentDB version. Updating the SDK fixed my problem.
> 
> It would be nice if there was a better error message :)

Thanks for trying to help. However in my case I don't have Service Fabric SDK installed though. Are you saying that there is version conflict between Microsoft.Azure.CosmosDB.BulkExecutor 2.3.0-preview2 and some other packages that I am using?

**Comment by JohnLTaylor** [comment]
> Thanks for trying to help. However in my case I don't have Service Fabric SDK installed though. Are you saying that there is version conflict between Microsoft.Azure.CosmosDB.BulkExecutor 2.3.0-preview2 and some other packages that I am using?

This was just my experience and I was running locally.

**Comment by ealsur** [comment]
Closing as this is not related to Cosmos DB SDK V3, please see linked Cosmos DB V2 SDK issue.
