### ISSUE TITLE
Support Stream on CosmosStoredProcedure.ExecuteAsync

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#201]
The ```CosmosStoredProcedure.ExecuteAsync``` does not have a stream equivalent.

**Describe the solution you'd like**
```CosmosStoredProcedureCore.ProcessAsync``` exposes the equivalent but is not accessible

**Describe alternatives you've considered**
Lot's of low level stuff I want to avoid

**Additional context**
I am using the ```Utf8JsonWriter``` to serialize my documents and batch the data into a stream for processing. Currently you do not allow for a custom ```CosmosJsonSerializer``` and even if  you did it would not do what I need because it would take 2 serialization runs. One to calculate the stream size and another in the ExecuteAsync. By consuming a stream in the ExecuteAsync, I can get it all done in one pass.

PS - the tight controls over internal setters in a lot of the API is very frustrating

**Comment by kirankumarkolli** [comment]
Stream support for StoredProcedure is a good improvement. 

On custom CosmosJsonSerializer part: 
Layer wise typed is always treated as on-top of stream. And Stream to T conversion is delegated to  CosmosJsonSerializer. Am not fully clear on two-serialization runs part, @fuocor  can you please elaborate more?

**Comment by fuocor** [comment]
**Without direct stream support**, if I ran a batch and wanted to keep it within a specific chunk size I would need to serialize once to calculate the batch chunks, and then send the corresponding object collection subset the ExecuteAsync method which would serialize it again.

**With direct stream**, I can serialize the individual items in the collection, determine where to chunk, and send the payload without the need to reserialize.
