### ISSUE TITLE
BatchTransactions in v4 SDK?

### ISSUE THREAD

**Issue by Dave76** [Azure/azure-cosmos-dotnet-v3#2015]
I have been playing around with the latest preview of the v4 SDK - which is looking good by the way.  I tried porting some of my code using the v3 sdk and realized that v4 doesn't currently have support for container.CreateBatchTransaction().  

Will this be supported in a future release of v4?

**Comment by ealsur** [comment]
V4 currently is an experimental SDK, currently it does not have TransactionalBatch and we don't have any timelines for it to have it currently. The only rough estimate that we have for V4 is end of next year.

If you are building a greenfield application, please use V3.

**Comment by Dave76** [comment]
Thanks @ealsur . Good to know.

**Comment by Dave76** [comment]
You may want to consider hiding the v4 info from the main docs --- that's the only reason I knew about the v4 sdk.

![image](https://user-images.githubusercontent.com/584050/99611770-457b7a80-29e2-11eb-909d-e43240ec7c4c.png)
