### ISSUE TITLE
UpsertItem returns misleading error code and message

### ISSUE THREAD

**Issue by JacksonHong** [Azure/azure-cosmos-dotnet-v3#2023]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).
Using the latest 3.14.0

**Describe the bug**
When upserting a document into a collection that does not have large partition key check box selected during creation, and if the collection already has a document that shares the same id and the first 100 bytes of the partitionKey, the upsert operation would fail with a misleading error code 403.

Example here:
"ResponseBody": "Message: {\"Errors\":[\"Request is blocked. Please check your authorization token and Cosmos DB account firewall settings.\"]}\r\nActivityId: xxx, Request URI: /apps/xxx/services/xxx/partitions/xxx/replicas/xxx/, RequestStats: Please see CosmosDiagnostics, SDK: Windows/10.0.19042 cosmos-netstandard-sdk/3.14.0",

**To Reproduce**
1. Create a collection without checking the Large Partition Key check box from Azure Portal
2. Create a document with long partition key and a pre-determined id
3. Use Cosmos SDK v3.14.0 to upsert another document with same id and the same first 100 bytes of the partition key

**Expected behavior**
Expected to get an error indicating conflict, such as HTTP 409

**Actual behavior**
403 was returned with this error message "Request is blocked. Please check your authorization token and Cosmos DB account firewall settings" This was so confusing and I spent an hour trying to figure out what went wrong. I only discovered this settings issue after I tried to use AddItem instead of UpsertItem. AddItem correctly returned 409 which helped me to discover the issue.
https://docs.microsoft.com/en-us/azure/cosmos-db/large-partition-keys?tabs=dotnetv3

**Environment summary**
SDK Version: 3.14.0
OS Version (e.g. Windows, Linux, MacOSX)
Windows

**Additional context**

**Comment by j82w** [comment]
This exception is coming from the service. The SDK can not fix this issue. Can you please [contact support](https://aka.ms/azure-support) for help with this issue. You can also try leaving feed back [here](https://feedback.azure.com/forums/263030-azure-cosmos-db).

**Comment by JacksonHong** [comment]
> This exception is coming from the service. The SDK can not fix this issue. Can you please [contact support](https://aka.ms/azure-support) for help with this issue. You can also try leaving feed back [here](https://feedback.azure.com/forums/263030-azure-cosmos-db).

The feedback link does not look like the right place for this issue. This is a bug rather than a feature ask. Is there a place to report service bug?

**Comment by j82w** [comment]
@JacksonHong were you not able to file an issue with the [contact support](https://aka.ms/azure-support) link?

**Comment by xenoverse-us** [comment]
Guess this is still not fixed after 2 years...
