### ISSUE TITLE
System.NullReferenceException during container.GetFeedRangesAsync() call on recreating container with same name

### ISSUE THREAD

**Issue by varadahemeswari** [Azure/azure-cosmos-dotnet-v3#2024]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Creating container after deleting a previous container with same name is causing null reference exception during GetFeedRangesAsync call as the rid of deleted container is used to get feed ranges.

**To Reproduce**

Database database = await CosmosClient.CreateDatabaseIfNotExistsAsync("db");

            for (int i = 0; i < 10; i++) // using a loop to repro because sometimes cache refresh happens providing correct collection rid
            {
                try
                {
                    ContainerResponse containerResponse = await database.CreateContainerIfNotExistsAsync(
                            new InteropContainerProperties("coll", "/pk"),
                            throughput: 10000);
                    await containerResponse.Container.DeleteContainerAsync();

                    ContainerResponse recreatedContainer = await database.CreateContainerIfNotExistsAsync(
                            new InteropContainerProperties("coll", "/pk"),
                            throughput: 10000);
                    IReadOnlyList<FeedRange> result = await recreatedContainer.Container.GetFeedRangesAsync();
                    await recreatedContainer.Container.DeleteContainerAsync();
                }
                catch (Exception ex)
                {
                    Assert.IsTrue(ex is NullReferenceException);
                }
            }

**Expected behavior**
GetFeedRangeAsync should try to refresh cache to determine the rid of current container. 

**Actual behavior**
Throws null reference exception as pk ranges could not be found for specific container rid 

**Environment summary**
SDK Version:
OS Version Windows

**Additional context**

Debug output - 
DocDBTrace Warning: 0 : Routing Map Null for collection: Jvk9APdCC3Q= for range: [,FF), forceRefresh:True
**<partitionKeyRanges>5__3** was null.

Call stack -
  at Microsoft.Azure.Cosmos.ContainerCore.<GetFeedRangesAsync>d__34.MoveNext() in D:\CosmosDB\Product\SDK\.net\OSS\V3\Microsoft.Azure.Cosmos\src\Resource\Container\ContainerCore.cs:line 266
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__38`1.MoveNext() in D:\CosmosDB\Product\SDK\.net\OSS\V3\Microsoft.Azure.Cosmos\src\Resource\ClientContextCore.cs:line 418
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at

**Comment by j82w** [comment]
I would recommend avoiding recreating containers with the same name whenever possible. 

The issue is the following code. It it getting the cached RID value, but it does not properly handle if the RID value is stale.  Since it is a TryGetOverlappingRangesAsync it will return null instead of throwing the exception.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d7a18ebb035160bfc9626cca28c0161815ebf653/Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs#L259
```c#
public async Task<IReadOnlyList<FeedRange>> GetFeedRangesAsync(
            CosmosDiagnosticsContext diagnosticsContext,
            CancellationToken cancellationToken = default)
        {
            PartitionKeyRangeCache partitionKeyRangeCache = await this.ClientContext.DocumentClient.GetPartitionKeyRangeCacheAsync();
            string containerRId = await this.GetRIDAsync(cancellationToken);
            IReadOnlyList<PartitionKeyRange> partitionKeyRanges = await partitionKeyRangeCache.TryGetOverlappingRangesAsync(
                        containerRId,
                        new Range<string>(
                            PartitionKeyInternal.MinimumInclusiveEffectivePartitionKey,
                            PartitionKeyInternal.MaximumExclusiveEffectivePartitionKey,
                            isMinInclusive: true,
                            isMaxInclusive: false),
                        forceRefresh: true);
            List<FeedRange> feedTokens = new List<FeedRange>(partitionKeyRanges.Count);
            foreach (PartitionKeyRange partitionKeyRange in partitionKeyRanges)
            {
                feedTokens.Add(new FeedRangeEpk(partitionKeyRange.ToRange()));
            }

            return feedTokens;
        }
```
