### ISSUE TITLE
Typed OM Item create validate 'Id' for un-supported characters

### ISSUE THREAD

**Issue by lpunderscore** [Azure/azure-cosmos-dotnet-v3#203]
I have a collection with documents that have an MD5 hash as the id. The ReadItemAsync method does not find some of the documents with the specified id even if it exists in the collection if the id contains specific characters "/" for example. Using CreateItemQuery will work properly and return the document.

**To Reproduce**
Have a collection with documents that may have some specific characters in the id, for example: "+96z/GAUV+iH2xAKIlSgqw==" the partitionkey can be any other value, we have a guid there. Use the ReadItemAsync method. See the query.Result is null even if the document exists in the collection. You can validate the object can be fetched using CreateItemQuery instead.

**Expected behavior**
A document is returned if it exists in the collection.

**Actual behavior**
The document is NotFound

**Environment summary**
SDK Version: 3.0.0.10-preview
Windows

**Comment by lpunderscore** [comment]
@kirankumarkolli 

Just commenting here as I don't think this should be considered as an improvement, but rather as a bug.

Unless this is released with GA, this sdk will be unusable since, read, delete, replace operations will not work properly / consistently on documents with those characters in id. Upsert works but not replace for example, leading to major data integrity issues.

**Comment by FrankGagnon** [comment]
I've also encountered this issue with a very simple use case. An entity with the Id "." can be created but not retrieved using ReadItemAsync. The error message is super cryptic too : 

"Response status code does not indicate success: 401 Substatus: 0 Reason: (The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: '{payload}' ActivityId: 962b2585-ca0d-4381-a1c3-3b3b0eeb6228, Microsoft.Azure.Documents.Common/2.4.0.0, Windows/10.0.17763 cosmos-netstandard-sdk/3.0.0)."

**Comment by kirankumarkolli** [comment]
@FrankGagnon thanks for the feedback. 

Fix for this has two parts
1. In Creates don't allow invalid 'id' character
2. In Reads do 'id' validation before reaching out to service (better exception message)

@simplynaveen20 please create two tasks and work on fixes.

**Comment by lpunderscore** [comment]
@kirankumarkolli Wondering if this is an acceptable solution, since this is making the client restrict functionality that is available in the service.  What I mean is that cosmos can handle those characters in its containers without issue, and when the query is properly formed, this data can be queried / created / retreived through the api.

So I don't know if restricting this functionality at the sdk level is a good solution when we could just model the sdk query generator to support it instead.

**Comment by j82w** [comment]
This functionality needs to be done in the service. Closing this since only SDK features are tracked here.
