### ISSUE TITLE
REST from .NET - Sample for stored procedure executing

### ISSUE THREAD

**Issue by sslepova** [Azure/azure-cosmos-dotnet-v3#2033]
Samples for REST API are put in [this azure-cosmod_dotnet-v2 repo](https://github.com/Azure/azure-cosmos-dotnet-v2) which seems to be abandoned. Couldn't find any other resource so I post my request here.
Could you please add to [this sample](https://github.com/Azure/azure-cosmos-dotnet-v2/blob/master/samples/rest-from-.net/Program.cs) an example for executing stored procedure?

**Comment by j82w** [comment]
Hi @sslepova 

The REST APIs are documented in [Azure docs](https://docs.microsoft.com/en-us/rest/api/cosmos-db/execute-a-stored-procedure) which has examples of the body
