### ISSUE TITLE
[Feature Request] ChangeFeed to trigger by different operations and TTL

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-cosmos-dotnet-v3#2035]
That is it, ChangeFeed is not very useful without tracking all operations and especially Ttl because there is no workaround for Ttl

**Comment by j82w** [comment]
Will this feature be enough? https://azure.microsoft.com/en-us/updates/change-feed-with-full-database-operations-for-azure-cosmos-db/

**Comment by MhAllan** [comment]
@j82w   .. Thank you so much, that is what we are looking for

**Comment by j82w** [comment]
I'm closing this issue since it is a service feature rather than a SDK. The SDK will add support once it is available.
