### ISSUE TITLE
Why is Microsoft.Azure.Cosmos.Headers.SubStatusCode internal?

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#2036]
**Describe the bug**
Why is Microsoft.Azure.Cosmos.Headers.SubStatusCode internal?

**To Reproduce**
none required

**Expected behavior**
Using stored procedure call and would like the SubStatusCode to determine if a unique key violation was triggered.

**Actual behavior**
It's internal

**Environment summary**
SDK Version: Source
OS Version  Windows

**Comment by j82w** [comment]
@kirankumarkolli do you see an issue of exposing an int for the substatuscode?

**Comment by j82w** [comment]
@fucor you can actually access the SubStatusCode currently through the headers. 
`response.Headers.GetHeaderValue<string>("x-ms-substatus")`

What scenario requires you to use stored procedure now that there is [TransactionalBatch support](https://devblogs.microsoft.com/cosmosdb/introducing-transactionalbatch-in-the-net-sdk/)?

**Comment by fuocor** [comment]
My scenario is simple. I have high frequency inserts and I don't want the document returned in the result. Just true/false.

**Comment by j82w** [comment]
You can use the [EnableContentResponseOnWrite ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.itemrequestoptions.enablecontentresponseonwrite?view=azure-dotnet) so it will only return the Headers. It will not return the response body. This will be faster than using a StoredProcedure.
https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-dotnet-sdk-v3-sql#sdk-usage

**Comment by fuocor** [comment]
Thanks for the hint...

**Comment by j82w** [comment]
I'm closing this issue since there is a way to access the SubStatusCode value. This a corner case so there isn't a need to expose a API for easier access.

**Comment by fuocor** [comment]
Quick question, is there a corresponding request header for `EnableContentResponseOnWrite`? I have a rest implementation that can benefit from it

**Comment by j82w** [comment]
Key: "Prefer", Value: "return=minimal" https://github.com/Azure/azure-cosmos-dotnet-v3/blob/768c0cfdbaa51206b2b360a424b6599ac87bed85/Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs#L172

**Comment by fuocor** [comment]
thanks
