### ISSUE TITLE
TransportException: RntbdServiceEndpoint closes

### ISSUE THREAD

**Issue by WestCornfield** [Azure/azure-cosmos-dotnet-v3#2039]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
We have consistent, intermittent issues where we can read from our cosmos container, but when we attempt to upsert, we get an IllegalStateException null, under which is a TransportException where RntdServiceEndpoint is closed.

**To Reproduce**
This is the setup for our cosmos client. We set it up as a singleton client, one per container.

client = (new CosmosClientBuilder()).endpoint(accountSettings.getHost()).key(accountSettings.getMasterKey()).consistencyLevel(ConsistencyLevel.SESSION).connectionSharingAcrossClientsEnabled(true).preferredRegions(List.of("East US")).contentResponseOnWriteEnabled(LOGGER.isDebugEnabled()).buildClient();

**Expected behavior**
Read and upsert work as intended.

**Actual behavior**
Provide a description of the actual behavior observed. 
After a certain amount of time, we are able to read data but not upsert data.

**Environment summary**
SDK Version: 4.8.0
OS Version MacOSX

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
@WestCornfield this appears to be for the [Cosmos DB Java SDK](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos). Can you please open an issue in the correct repository.
