### ISSUE TITLE
How do you handle Task.Delay() in this function

### ISSUE THREAD

**Issue by ankku** [Azure/azure-cosmos-dotnet-v3#2046]
Below is the changeFeedprocessor which i am calling from a powershell cmdlet. My question is how do you handle task.Delay(). My below code works fine when task.Delay(500000) but it doesnt work when task.Delay(5000). How should i handle this? I am looking to get the list of all documents where changes happened. 

` protected override void ProcessRecord()
        {

            Task.Run(async () =>
            {

                DateTime particularPointInTime = DateTime.Now.Subtract(MaxAge).ToUniversalTime();
                CosmosClient Client = new CosmosClient("AccountEndpoint = https://test.documents.azure.com:443/;AccountKey=EAA==;");
                
                var database = Client.GetDatabase("testdatabaser");
                var container = database.GetContainer("testcontainer");
                var leaseContainer = database.GetContainer("leases");               
                var cfp = container.GetChangeFeedProcessorBuilder<Recording>('ChangeFeedProcessorName', ProcessChanges)
                    .WithLeaseContainer(leaseContainer)
                    .WithInstanceName('ChangeFeedInstanceName')
                    .WithStartTime(particularPointInTime)
                    .Build();
                await cfp.StartAsync();
                await Task.Delay(50000000);
                await cfp.StopAsync();
            }).Wait();
        }

        public async Task ProcessChanges(IReadOnlyCollection<Recording> docs, CancellationToken cancellationToken)
        {
            foreach (var doc in docs)
            {
                WriteObject(doc, true);
                
            }

        }

    }     `

**Comment by j82w** [comment]
I would recommend using `await Task.Delay(TimeSpan.FromSeconods(5));` to avoid any errors when converting it to Milliseconds. 

What is the reason for the `Task.Delay`? If you are just looking for documents changed over the last 5 minutes is there any reason you can't just do the delay in PowerShell then have the `WithStartTime` go back 5 minutes?

**Comment by ankku** [comment]
I am looking to get the list of changed documents for a particular time where I passed the TimeSpan argument MaxAge from powershell. Now my changedfeed might return 100 records say for last 2 days , now in this second Task.Delay(5000) is not working and it do not call the delegate, while Task.Delay(500000) is able to process the changes and hit the delegate. I hope i made myself clear here. Question is how in general , everyone is doing, all examples I am seeing have used Task.Delay() with a specific number which will fail if Task.Delay() timeout before the changes are processed.

**Comment by j82w** [comment]
The best solution I can think of is using the Preview SDK with [ChangeFeed pull model](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/01c36b2b2c5e3e0eec8388f00c98b97edc8b990e/Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs#L1247).

@ealsur and @FabianMeiswinkel do you have any other suggestions?

**Comment by ankku** [comment]
I am posting my code here , just to understand what approach should be taken to handle this Task.Delay(), also since I am calling this via powershell cmdlet , it will require me to call WriteObject() from Processrecord() method only and not in the delegate method. let say I would like to return list of all Ids coming in the change feed, how should I achieve that.right now I have WriteObject command in delegate which will not work, and I would need to return this to Processrecord()

`using Microsoft.Azure.Cosmos;
using System;
using System.Collections.Generic;
using System.Management.Automation;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace abc.PowerShell
{
    [Cmdlet(VerbsCommon.Get, "ChangedRecordings")]
    [OutputType(typeof(List<Recording>))]

    public class SyncRecording : PSCmdlet

    {
        [Parameter(Mandatory = true,
            Position = 0,
            ValueFromPipeline = true,
            ValueFromPipelineByPropertyName = true, HelpMessage = "Provide the duration in days from when the changes in recording are seeked")]

        public TimeSpan MaxAge { get; set; }

        [Parameter(Mandatory = true,
            Position = 1,
            ValueFromPipeline = true,
            ValueFromPipelineByPropertyName = true, HelpMessage = "Provide a Unique name for the Instance")]

        public string ChangeFeedInstanceName { get; set; }

        [Parameter(Mandatory = true,
            Position = 2,
            ValueFromPipeline = true,
            ValueFromPipelineByPropertyName = true, HelpMessage = "Provide a Unique name for the ChangeProcessor")]

        public string ChangeFeedProcessorName { get; set; }

      `protected override void ProcessRecord()
{

        Task.Run(async () =>
        {

            DateTime particularPointInTime = DateTime.Now.Subtract(MaxAge).ToUniversalTime();
            CosmosClient Client = new CosmosClient("AccountEndpoint = https://test.documents.azure.com:443/;AccountKey=^***;");
            
            var database = Client.GetDatabase("testdatabaser");
            var container = database.GetContainer("testcontainer");
            var leaseContainer = database.GetContainer("leases");               
            var cfp = container.GetChangeFeedProcessorBuilder<Recording>('ChangeFeedProcessorName', ProcessChanges)
                .WithLeaseContainer(leaseContainer)
                .WithInstanceName('ChangeFeedInstanceName')
                .WithStartTime(particularPointInTime)
                .Build();
            await cfp.StartAsync();
            await Task.Delay(50000000);
            await cfp.StopAsync();
        }).Wait();
    }




    public async Task ProcessChanges(IReadOnlyCollection<Recording> docs, CancellationToken cancellationToken)
    {
        foreach (var doc in docs)
        {
            WriteObject(doc.Id, true);
            
        }

    }

} `
`

**Comment by ealsur** [comment]
As @j82w mentioned, for this scenario, you should be using Change Feed Pull Model, not Change Feed processor.

**Comment by ankku** [comment]
I am still not clear how I should be approaching that with Pull model, Below id the code I have where Now I have defined the ChangeProcessor, but since I am trying to call this from PowerShell cmdlet, its not allowing me to pass it in process record and giving an async issue. How should I be calling this change feed service from PowerShell cmdlet>

```
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Documents;
using System;
using System.Collections.Generic;
using System.Management.Automation;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;

namespace abcr.PowerShell
{
    [Cmdlet(VerbsCommon.Get, "ChangedRecordings")]
    [OutputType(typeof(List<Recording>))]

    public class SyncRecording : PsCmdlet

    {
        [Parameter(Mandatory = true,
            Position = 0,
            ValueFromPipeline = true,
            ValueFromPipelineByPropertyName = true, HelpMessage = "Provide the duration in days from when the changes in recording are seeked")]

        public TimeSpan MaxAge { get; set; }

        [Parameter(Mandatory = true,
            Position = 1,
            ValueFromPipeline = true,
            ValueFromPipelineByPropertyName = true, HelpMessage = "Provide a Unique name for the Instance")]

        public string ChangeFeedInstanceName { get; set; }

        [Parameter(Mandatory = true,
            Position = 2,
            ValueFromPipeline = true,
            ValueFromPipelineByPropertyName = true, HelpMessage = "Provide a Unique name for the ChangeProcessor")]

        public string ChangeFeedProcessorName { get; set; }

        protected override void BeginProcessing()
        {
            var twister = this.Twister;
        }

        protected override void ProcessRecordAsync()
        {

            var client = new CosmosClient("AccountEndpoint = https://test.documents.azure.com:443/;AccountKey=******;");
            var database = client.GetDatabase("test");
            var container = database.GetContainer("ftestl");

            var options = new ChangeFeedProcessorOptions
            {
                BufferCapacity = 10,
                InstanceName = ChangeFeedInstanceName,
                LeaseContainer = database.GetContainer("leases"),
                ProcessorName = ChangeFeedProcessorName,
                StartTime = DateTime.Now.AddDays(-7).ToUniversalTime()
            };

            var count = 0;
            foreach (var doc in container.GetChangeFeed<Document>(options))
            {
                Console.Write(doc);

                count++;

                if (count == 6)
                {
                    break;
                }
            }

        }

    }

    public static class ChangeFeed
    {
        public static async IAsyncEnumerable<document> GetChangeFeed<document>(this Container self, ChangeFeedProcessorOptions options, [EnumeratorCancellation] CancellationToken cancellationToken = default)
        {
            var channel = Channel.CreateBounded<document>(new BoundedChannelOptions(options.BufferCapacity)
            {
                FullMode = BoundedChannelFullMode.Wait,
                SingleReader = true,
                SingleWriter = true
            });

            var processor = self
                .GetChangeFeedProcessorBuilder<document>(options.ProcessorName, async (items, cancellation) =>
                {
                    foreach (var item in items)
                    {
                        await channel.Writer.WriteAsync(item, cancellation);
                    }
                })
                .WithLeaseContainer(options.LeaseContainer)
                .WithInstanceName(options.InstanceName)
                .WithStartTime(options.StartTime)
                .Build();

            await processor.StartAsync();
            try
            {
                await foreach (var item in channel.Reader.ReadAllAsync(cancellationToken))
                {
                    yield return item;
                }
            }
            finally
            {
                await processor.StopAsync();
            }
        }
    }

    public class ChangeFeedProcessorOptions
    {
        public int BufferCapacity { get; set; }
        public string ProcessorName { get; set; }
        public Container LeaseContainer { get; set; }
        public string InstanceName { get; set; }
        public DateTime StartTime { get; set; }
    }
}
```

**Comment by ealsur** [comment]
For Change Feed pull model you can take a look at the documentation here: https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-pull-model, it should be easy to wire that into your current code as you can control the flow of changes and control when you want to read more or when to pause.

Unfortunately, how to wire up Powershell is beyond my expertise, I would not be able to recommend/help there.
