### ISSUE TITLE
Version 3.15.0 of the SDK does not return results when calling feedIterator.ReadNextAsync with larger volumnes of data

### ISSUE THREAD

**Issue by To-Marshall** [Azure/azure-cosmos-dotnet-v3#2051]
**Describe the bug**
While running version 3.15.0, when calling await feedIterator.ReadNextAsync on a set of data (in our case was 25,000 documents),  the code will not progress from the feeIterator, seemingly never receiving a task completion. Running of 3.13.0 does not produce this problem and the results are returned successfully.

**To Reproduce**
Call  await feedIterator.ReadNextAsync on a query that produces a larger set of results (we experienced it as mentioned before with 25,000 documents )

**Expected behavior**
feedIterator.ReadNextAsync should return the documents requested from the query.

**Actual behavior**
feedIterator.ReadNextAsync does not return a result and as such the code does not progress.

**Environment summary**
SDK Version: 3.15.0
OS Version: Windows 10

**Comment by bchong95** [comment]
Can you provide a console app that reproduces the issue.

**Comment by To-Marshall** [comment]
Hi,

So trying to recreate this in a console app has shown that there seems to be something with our data/database and 3.15.0 that causes it to fail while still working on 3.13.0. I have been given permission for you to access this test enviroments data but obviously there still needs to be a degree of confidenciality so is there a best way for me to privately send the console app to you with the connection strings?

**Comment by LiDamon** [comment]
[Thread 28.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/5758577/Thread.28.txt)
I have same issue, the attachment is dump file

**Comment by skurik** [comment]
@To-Marshall Hey, could you please try with 3.16.0? I think we hit the [same issue](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2100) and 3.16.0 seems to work.

**Comment by To-Marshall** [comment]
@skurik Hi, I did a quick test with 3.16 and that seems to work while 3.15 still fails so seems that yeah these are similair or the same issue.

**Comment by j82w** [comment]
This is likely fixed by : https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2060
