### ISSUE TITLE
InsertTableRowAsync Method Cause Unrecoverable Corruption in Table

### ISSUE THREAD

**Issue by laultman** [Azure/azure-cosmos-dotnet-v3#2057]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Creating a data migration tool for government customer. There are >100 databases and data tables collected over many years. Many were created by Microsoft Access.  The "id" fields are unreliable due to duplications.  The plan is to bring them into Cosmos DB Tables and the post import scrub the data.
We are attempting to preserve all the existing records (government retention policy) so we are retaining all the key fields. The new code is generating a GUID for each record then taking the entities as they are and inserting into Cosmos DB Tables.  The writes are succeeding with the data containing its embedded "id".
However the tables cannot be read.

**To Reproduce**
Create a Cosmost DB instance for Tables.
Add a Table eg TestTable1
In Data explorer Add Entry with PartitionKey = "DataItem", RowKey = "076DBE5B-4DEB-7641-21AD-C855725CA0BF" and then add a new property: id = "076DBE5B-4DEB-7641-21AD-C855725CA0BF".
As expected Cosmos DB does not save the entity due to collision with the "hidden" id field.
Repeat the above process but this time change the property to "idx" from id. The write will succeed.
Next clear all data from table.
Using C# create  an app that connects to your Comos DB
Create an new DynamicTableEntity containing a PartitionKey, RowKey and a property named "id".
Here is my code accepting json data that contains a field called "id".
`        /// <summary>Processes <strong>single</strong> json string containg a JObject into a table storage DynamicTableEntity.</summary>
        /// <param name="jsonText">The message the json object with properties.</param>
        /// <param name="partitionKey">The partition key (required).</param>
        /// <param name="rowKey">The row key (required).</param>
        /// <returns>DynamicTableEntity or null if missing partitionKey or json text.</returns>
        /// <remarks>
        ///   <para>Takes a jsonText string with <strong>single</strong> JObject deserializes it and creates a Azure Storage
        /// DynamicTableEntity object to store in an Azure Table.</para>
        ///   <para>
        ///     <font color="#333333">Exported SQL data or other external exported data often contains an "ID" key field. The
        /// call may provide the name of the key field. If not supplied the method defaults to a key name of "id" and trys
        /// to use that. If no id is found then a new PowerLine compatible GUID is created and keys the record.</font>
        ///   </para>
        /// IoT sensing data buffered into an array of readings. It is a simple json array and has the form:
        /// <br /> [{"id":125489, "psi":2600, "temp":384, "ts":1293840449494},{"id":125490, "psi":2549, "temp":398, "ts":1293840449897}]
        /// </remarks>
        internal static DynamicTableEntity ProcessJsonObjectUseRowKey(this string jsonText, string partitionKey, string rowKey)
        {
            var jObject = JToken.Parse(jsonText).Children<JObject>().FirstOrDefault();

            var dynamicTableEntity = new DynamicTableEntity
            {
                PartitionKey = partitionKey,
                RowKey = rowKey
            };

            foreach (KeyValuePair<string, JToken> keyValuePair in jObject)
            {
                dynamicTableEntity.Properties.Add(keyValuePair.Key, EntityProperty.CreateEntityPropertyFromObject(keyValuePair.Value));
            }

            return dynamicTableEntity;
        }
`
With your DynamicTableEntity next insert the record.
here is my insert:                 tableResult = await table.InsertTableRowAsync(entity);

This succeeds, no errors are thrown and the tableResult returns as expected. StatusCode 204

Subsequent reads using the point rowKey fail with Server error 500: Server encountered an internal error.Please try again after some time.: Value is expected to be an object instead it was 'Number'.:InternalServerError
        Details: Value is expected to be an object instead it was 'Number'.:Value is expected to be an object instead it was 'Number'.

To validate the record did in fact write to the database but in a corrupt condition.
Using Azure Explorer App (not the portal) to access the data. It will display the error when attempting to load the table.
Finally if you attempt to Insert the record again into the database you will get a storageException that the record already exists.
There is no recovery.

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
VS 2019 Version 16.8.3 
SDK Version: 5.0.101
OS Version (e.g. Windows, Linux, MacOSX)
Window 10 Enterprise latest update as of 12/10/2020

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
@laultman This repo is not for the Table API SDK, there is no InsertTableRowAsync in the SQL API SDK.

**Comment by laultman** [comment]
@ealsur Corrected the Method name.

**Comment by laultman** [comment]
@j82w

**Comment by laultman** [comment]
Bluntly, if you insert into a Cosmos DB table any JSON records from a service where those records contain their own "id" property Cosmos DB throws a hard server 500 error when trying to enumerate the table. The records are written but the table is corrupt. I need to maintain the id for backward linking to external databases and I need a new unique id on the record. Cosmos does not properly handle JSON record. Table Storage (not Cosmos) works properly. Table Storage lacks advanced features of Cosmos.

**Comment by laultman** [comment]
This is the Insert:
`        internal static async Task<TableResult> InsertTableRowAsync(this CloudTable table, DynamicTableEntity dynamicTableEntity)
        {
            if (dynamicTableEntity == null || dynamicTableEntity.Properties.Count == 0) return null;

            var tableOperation = TableOperation.Insert(dynamicTableEntity);
            return await table.ExecuteAsync(tableOperation);
        }

`

**Comment by laultman** [comment]
This is the retrieve that fails after the above Insert.
`        internal static async Task<TableResult> RetrieveTableRowAsync(this CloudTable table, string partitionKey, string rowKey, List<string> columnNames = null)
        {
            if (string.IsNullOrEmpty(partitionKey) || string.IsNullOrEmpty(rowKey)) return null;

            var tableOperation = TableOperation.Retrieve(partitionKey, rowKey);
            if (columnNames != null && columnNames.Count > 0)
                tableOperation = TableOperation.Retrieve(partitionKey, rowKey, columnNames);

            return await table.ExecuteAsync(tableOperation);
        }
`
This throws a server 500 exception in Cosmos.

**Comment by ealsur** [comment]
@laultman This is the wrong repo for your issue, the SDK you are using is not the SQL API SDK (Microsoft.Azure.Cosmos), but the Table API SDK: https://github.com/Azure/azure-cosmos-table-dotnet/issues
