### ISSUE TITLE
Does the method DeleteItemAsync of the Container class attempt a retry?

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-cosmos-dotnet-v3#2062]
**Is your feature request related to a problem? Please describe.**
Does the method `DeleteItemAsync` of the `Container` class , internally attempt a retry or do I as the consumer code need to put in some retry logic.

**Describe the solution you'd like**
Two things
- The documentation on the method `DeleteItemAsync` should be clear whether or not retry is required?
- Guidance on what should we retry on? E.g. anything besides 429 status codes.

**Describe alternatives you've considered**
At the moment we have written re-try logic when calling `DeleteItemAsync`. However, we would like to discontinue doing that if the SDK is already doing it internally. There is significant unit testing burden involved.

**Additional context**
Not applicable

**Comment by j82w** [comment]
@sdg002 I sent out a PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2076 which will add the documentation to the [exception documentation](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Exceptions.md).
