### ISSUE TITLE
ChangeFeed Diagnostics broken in PR #1933

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2066]
The ChangeFeed diagnostic tests were ignored in the following PR. The tests still fail. This has already shipped in the latest SDK. If the diagnostics is completely broken then troubleshooting ChangeFeed issues will not be possible.

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1933/files#r508043182

**Comment by bchong95** [comment]
This looks to be resolved with the ITrace PR:

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2097
