### ISSUE TITLE
Change Feed mode design

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#2067]
Change Feed is introducing in preview shortly the Full Fidelity Change Feed.

The way to enable the retention on a container is defined in PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2020.

Once retention has been enabled on a container, the user can consume the change feed in Full Fidelity mode, exposing deletes (within the retention period configured in the container).

The user can still consume Change Feed in the normal mode (Incremental) even if the retention is enabled, so they should be able to select one or the other when starting the Change Feed consumptions.

Because the continuations are valid for both modes, it is also possible to change the mode after capturing some previous continuation, so maintaining the mode as part of the continuation state is not really required.

## Proposed API

Exposing a configuration on the `ChangeFeedRequestOptions` that allows the user to set the mode, similar to the page size hint:

```
public class ChangeFeedRequestOptions
{

        /// <summary>
        /// Gets or sets the desired mode on which to consume the Change Feed.
        /// </summary>
        /// <value>Default value is <see cref="ChangeFeedMode.Incremental"/>. </value>
        public ChangeFeedMode FeedMode { get; set; } = ChangeFeedRequestOptions.DefaultMode;

}
```
Following a similar model to `StartFrom`, the different modes can be implemented as abstract class implementations.

The user can then set the FeedMode to two different values:
* Incremental (default): This is the default Change Feed, the current mode that surfaces creations and replaces.
* Full Fidelity: Available if the container has a retention period defined.

### Setting the FeedMode

Setting it to Incremental (the default):

```
ChangeFeedRequestOptions changeFeedRequestOptions = new ChangeFeedRequestOptions
            {
                FeedMode = ChangeFeedMode.Incremental()
            };
```

Setting it to Full Fidelity:

```
ChangeFeedRequestOptions changeFeedRequestOptions = new ChangeFeedRequestOptions
            {
                FeedMode = ChangeFeedMode.FullFidelity()
            };
```

And use it as part of the iterator:

```
FeedIterator feedIterator = container.GetChangeFeedStreamIterator(
        ChangeFeedStartFrom.Now(),
        new ChangeFeedRequestOptions()
       {
            FeedMode = ChangeFeedMode.FullFidelity(),
            PageSizeHint = 50
        });
```

The FeedMode implementation will define the `A_IM` header correctly to specify the desired mode.

**Comment by j82w** [comment]
I would suggest promoting this to a method member like start from. This is something have every user should be aware of. 

```c#
FeedIterator feedIterator = container.GetChangeFeedStreamIterator(
        ChangeFeedStartFrom.Now(),
        ChangeFeedMode.FullFidelity,
```

Is there any reason this is not just a Enum?
```c#
public enum ChangeFeedMode{
    Incremental,
    FullFidelity
}
```

**Comment by ealsur** [comment]
We could use an enum, thought it would be cleaner to have an abstract class, like :

```
public abstract class ChangeFeedMode
{
    internal abstract void Accept(RequestMessage requestMessage);
    public static ChangeFeedMode Incremental()
    {
        return ChangeFeedModeIncremental.Instance;
    }
    
    public static ChangeFeedMode FullFidelity()
    {
        return ChangeFeedModeFullFidelity.Instance;
    }
}

internal sealed class ChangeFeedModeIncremental : ChangeFeedMode
{
    internal override void Accept(RequestMessage requestMessage)
    {
        requestMessage.Headers.Add(HttpConstants.HttpHeaders.A_IM, HttpConstants.A_IMHeaderValues.IncrementalFeed);
    }
}

internal sealed class ChangeFeedModeFullFidelity : ChangeFeedMode
{
    internal override void Accept(RequestMessage requestMessage)
    {
        requestMessage.Headers.Add(HttpConstants.HttpHeaders.A_IM, HttpConstants.A_IMHeaderValues.FullFidelityFeed);
    }
}
```

So if we need to add more modes, we touch nothing else other than implementing a new type, instead of fishing where the value is and having a switch over an enum.

**Comment by ealsur** [comment]
Taking the good idea from Jake, the public API would look something like:

```
FeedIterator feedIterator = container.GetChangeFeedStreamIterator(
        ChangeFeedStartFrom.Now(),
        ChangeFeedMode.FullFidelity)
```

Promoting the Mode selection for the user to make a conscious choice.

While using the abstract class, but instead of methods, the `ChangeFeedMode.FullFidelity` and `ChangeFeedMode.Incremental` will have property accessors.

**Comment by bchong95** [comment]
I don't agree with the object model pattern for a field that could be an enum. By having a class we need to check for null throughout the code, which is something we wouldn't have to worry about if it were an enum.

Setting the request header should probably be done in a single place, so I don't see the need for a full visitor pattern.

**Comment by ealsur** [comment]
My concern with the enum is that it might not work with the Incremental Full Fidelity mode (which will not be initially available).
Incremental Full Fidelity could allow the customer to define a particular point in time (that gets passed as a different header) on which the backend will stop being Incremental and begin being Full Fidelity (used for migration scenarios).

The object model allows for this to be added at a later time without changing the public API, so it's more extensible.

**Comment by petro2050** [comment]
+1 for properties because `ChangeFeedMode.Incremental()` and `ChangeFeedMode.FullFidelity()` are methods and method names should start with a verb.

- What are the minimum and maximum timespans one can set in the full fidelity mode?
- Are there any price or performance implications to setting a very high retention period?

**Comment by j82w** [comment]
I agree with @ealsur that class model is more extensible. The null exceptions can be avoided by enabling the new nullable flag for all the logic that is being added. The one benefit of using the class model is it avoid not implemented run time exception caused by a switch statement not getting updated to handle the new enum type.

**Comment by DmitryKhilyai** [comment]
Is it possible to update Azure Function [trigger](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/CosmosDBAttribute.cs) with FeedMode setting?

**Comment by ealsur** [comment]
@DmitryKhilyai, Full Fidelity is still in private preview. When the feature GAs we will certainly add Functions support, it is part of the roadmap.

**Comment by petro2050** [comment]
@ealsur Do you think FF will be GA'ed this year? I've been waiting for this feature for so long.

**Comment by ealsur** [comment]
@petro2050 I don't have knowledge of the service GA dates, @jcocchi do we have any public roadmap dates?
