### ISSUE TITLE
Cosmos DB throwing Microsoft.Azure.Documents.GoneException with a 503

### ISSUE THREAD

**Issue by nijasbrawther123** [Azure/azure-cosmos-dotnet-v3#2081]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
We are seeing instances of Cosmos DB throwing **Microsoft.Azure.Documents.GoneException** on high load.

**Environment summary**
SDK Version: 3.15
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Additional context**
**Stack Trace:
Response status code does not indicate success: ServiceUnavailable (503)%3b Substatus: 0%3b ActivityId: 4eeb0d5e-d406-409f-94e1-fd354238c483%3b Reason: (Service is currently unavailable. More info: https://aka.ms/cosmosdb-tsg-service-unavailable
ActivityId: 4eeb0d5e-d406-409f-94e1-fd354238c483, Please see CosmosDiagnostics, Windows/10.0.14393 cosmos-netstandard-sdk/3.15.2)%3b**

**Comment by ealsur** [comment]
Did you follow the link that appears in the exception? What are the findings?

**Comment by ealsur** [comment]
Where it says "Please see CosmosDiagnostics" are you capturing the Diagnostics in the exception or capturing the ToString / serialization of the exception?

**Comment by railstolearn** [comment]
Any update on this?

**Comment by ealsur** [comment]
@railstolearn There was no response from the original author, so I will close this issue. If the original author has extra information, it can be reopened, otherwise I don't see any actionable information.
