### ISSUE TITLE
Change Feed Pull Model Memory Issues

### ISSUE THREAD

**Issue by abranaugh** [Azure/azure-cosmos-dotnet-v3#2087]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
We are trying to update our SDK version from 3.9.1 - preview to the latest preview version.  We use the change feed pull model.  We noticed when we updated our version to 3.15.2 - preview and deployed, our machines quickly ran out of RAM.  Looking at the logs, we got up to about 23gb of RAM in use and then crashed.  I was able to reproduce locally and noticed that the RAM on my machine quickly ballooned.  

I put together a console app to verify the behavior wasn't anything in our code, the only dependencies in the console app is to  Cosmos SDK.  In my test, I read off the change feed for 10 minutes and monitored the diagnostics in VS2019.  I tested with various versions and took screenshots of the memory usage in the diagnostic session.  These tests were against a collection that is about ~300GB 

3.15.2 - Preview - Ended up at around 1.8gb for the 10 minutes
![image](https://user-images.githubusercontent.com/44167673/102802619-8c131a80-437c-11eb-99a0-47bf95512e1d.png)

3.15.1 - Preview - 900mb in 10 minutes
![image](https://user-images.githubusercontent.com/44167673/102803986-bb2a8b80-437e-11eb-9df6-02ccc98d75c7.png)

3.15.0 - Preview - 600mb in 10 minutes
![image](https://user-images.githubusercontent.com/44167673/102804021-c8e01100-437e-11eb-8249-c3a06c911982.png)

3.14.0 - Preview - 150mb in 10 minutes
![image](https://user-images.githubusercontent.com/44167673/102804065-d85f5a00-437e-11eb-96cb-5e784d9d241f.png)

3.13.0 - Preview - 150mb in 10 minutes
![image](https://user-images.githubusercontent.com/44167673/102804113-e7dea300-437e-11eb-8444-eab6a52a0cd1.png)

3.9.1 - Preview - 150mb in 10 minutes
![image](https://user-images.githubusercontent.com/44167673/102804149-f62cbf00-437e-11eb-9e49-193955ea8f39.png)

Here is the code for the methods I ran:

3.13 and up
```
public async Task RunFeed()
{
   var connection = "";
   var container = new CosmosClient(connection).GetContainer("", "");
   var totalDocs = 0;
   var options = new ChangeFeedRequestOptions
   {
     PageSizeHint = 5000
   };
    
   using (var iterator = container.GetChangeFeedStreamIterator(ChangeFeedStartFrom.Beginning(), options))
   {
      var watch = Stopwatch.StartNew();
      while (iterator.HasMoreResults && watch.Elapsed < TimeSpan.FromMinutes(10))
      {
          using (var response = await iterator.ReadNextAsync())
          {
              if (!response.IsSuccessStatusCode)
              {
                 break;
              }

              using (var changes = await JsonDocument.ParseAsync(response.Content))
              {
                  var count = changes.RootElement.GetProperty("_count").GetInt32();
                  Console.WriteLine($"Retrieved {count} documents");
                  totalDocs += count;
              }
          }
      }
      Console.WriteLine($"Found {totalDocs} total documents in {watch.Elapsed.TotalMinutes} minutes");
    }
}
```
3.9.1 - Preview
```
public async Task RunFeed()
{
    var connection = "";
    var container = new CosmosClient(connection).GetContainer("", "");
    var totalDocs = 0;
    
    var iterator = container.GetChangeFeedStreamIterator(changeFeedRequestOptions: new ChangeFeedRequestOptions
    {
        StartTime = DateTime.MinValue,
        MaxItemCount = 5000
    });
    
    var watch = Stopwatch.StartNew();
    while (iterator.HasMoreResults && watch.Elapsed < TimeSpan.FromMinutes(10))
    {
        using (var response = await iterator.ReadNextAsync())
        {
            using (var changes = await JsonDocument.ParseAsync(response.Content))
            {
                var count = changes.RootElement.GetProperty("_count").GetInt32();
                Console.WriteLine($"Retrieved {count} documents");
                totalDocs += count;
            }
        }
    }
    
    Console.WriteLine($"Found {totalDocs} total documents in {watch.Elapsed.TotalMinutes} minutes");
}
```
   
**Environment summary**
SDK Version: 3.15.0 - Preview, 3.15.1 - Preview, 3.15.2 - Preview
.Net Core 3.1

**Comment by j82w** [comment]
Likely caused by https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1933

**Comment by j82w** [comment]
@abranaugh please [contact support](https://aka.ms/azure-support) if this is impacting your production so a support ticket is created and will ensure the issue is properly prioritized.

**Comment by j82w** [comment]
@abranaugh any chance you can provide a memory dump or perf trace to help root cause the issue?

**Comment by abranaugh** [comment]
@j82w I can provide a memory dump, how would you like me to provide that to you?  When I dumped out the version running 3.15.2 - preview, it was about 1.8gb.  I don't want to post it publicly on github due to potentially exposing our connection strings and whatnot.  I can open up a support ticket and attach it to that if that is easiest.

**Comment by j82w** [comment]
Please open a support ticket and attach the memory dump as it is the easiest way.

**Comment by shibayan** [comment]
I also encountered this problem using the latest preview version (`3.15.2-preview`). Based on the findings of this issue, I decided to use `3.14.0-preview`, but now I've encountered the issue #1918 and have a difficult version to choose.

**Comment by j82w** [comment]
Fix in PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2129
