### ISSUE TITLE
ContinuationToken not understood

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-cosmos-dotnet-v3#2088]
I am getting FeedResponse.ContinuationToken as a json string of complex object when I am expecting a simple string that I can pass it to the next request. Please example as there is no example for this in V3 in the whole internet and the returned object is too weird to be right

```csharp
{
    "V": 0,
    "Rid": "HZlLAJFYlGM=",
    "Continuation": [{
            "token": "{\"token\":\"HZlLAJFYlGMCAAAAAAAAAA==\",\"range\":{\"min\":\"\",\"max\":\"FF\"}}",
            "range": {
                "min": "",
                "max": "FF"
            }
        }
    ],
    "Range": {
        "min": "",
        "max": "FF"
    }
}

```

**Comment by j82w** [comment]
@MhAllan the continuation token should be treated as an opaque string. The SDK appends additional information required by the SDK to resume the previous state.  Are you trying to take the continuation token from the .NET SDK and use it somewhere else?

**Comment by MhAllan** [comment]
The token, when returned by ASP.Net core within a json object, the quotations are escaped, so when you receive that token again it is not a valid token for Cosmos db. so I had to convert it into base64 every time I return it and convert it back every time I received it.

**Comment by j82w** [comment]
@sboshra what are the recommendations on how to serialize the continuation token?

**Comment by disambiguationuk** [comment]
That's weird, my continuation tokens looks similar but not the same. I don't have the inner token within Continuation and have state instead:

`{
    "V": 2,
    "Rid": "sJU0AI4T7B8=",
    "Continuation": [
        {
            "FeedRange": {
                "type": "Effective Partition Key Range",
                "value": {
                    "min": "",
                    "max": "FF"
                }
            },
            "State": {
                "type": "continuation",
                "value": "\"42\""   
            }
        }
    ]
}`

**Comment by MhAllan** [comment]
@disambiguationuk yours looks cleaner. I don't know what is the reason, I was using emulator and V3 library

**Comment by bchong95** [comment]
@MhAllan Continuation Tokens are opaque strings and should be treated as such (no need to try and understand the format). If you have additional contracts like putting them into an HTTP header, then these things need to be honored in your application layer. Like you said base64 encoding the string is one way of going about this. 

@disambiguationuk Your token is using a new format which is why it's a bit cleaner. It's also for a ChangeFeed request as opposed to a ReadFeed request.
