### ISSUE TITLE
CosmosException on ReadNextAsync() in version 3.7 through 3.15.1 using .NET Core 3.1

### ISSUE THREAD

**Issue by tubli** [Azure/azure-cosmos-dotnet-v3#2090]
**Brief Description**
When using .NET Core 3.1 and Cosmos SDK version >=3.7...
calling queryResultSetIterator.ReadNextAsync() results in an error message

**Attempted Action**
 
      var sqlQueryText = "SELECT * FROM c WHERE c.LastName = 'Andersen'";

      Console.WriteLine("Running query: {0}\n", sqlQueryText);

      QueryDefinition queryDefinition = new QueryDefinition(sqlQueryText);
      FeedIterator<Family> queryResultSetIterator = this.container.GetItemQueryIterator<Family>(queryDefinition);

      List<Family> families = new List<Family>();

      while (queryResultSetIterator.HasMoreResults)
      {
          FeedResponse<Family> currentResultSet = await queryResultSetIterator.ReadNextAsync();
          foreach (Family family in currentResultSet)
          {
              families.Add(family);
              Console.WriteLine("\tRead {0}\n", family);
          }
      }

**Error Message**
Error message occurs on line:
`          FeedResponse<Family> currentResultSet = await queryResultSetIterator.ReadNextAsync();`

InternalServerError error occurred: Microsoft.Azure.Cosmos.CosmosException : Res
ponse status code does not indicate success: InternalServerError (500); Substatu
s: 0; ActivityId: 00000000-0000-0000-0000-000000000000; Reason: (Unable to load
DLL 'Microsoft.Azure.Cosmos.ServiceInterop.dll' or one of its dependencies: The
specified procedure could not be found. (0x8007007F));

Full Error Message is attached:
[FullErrMsg.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/5728410/FullErrMsg.txt)

**Reproduce**

I found the error doing step 7 of the Microsoft getting started tutorial:
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-get-started

The error doesn't occur if using .NET Framework 4.7.2
The error doesn't occur if using .NET core 3.1, Microsoft.Azure.Cosmos 3.2-3.6
The error does occur if using .NET Core 3.1, Microsoft.Azure.Cosmos 3.7 - 3.15.1

I've attached my exact files (minus key and URI) and with the file extensions changed to .txt from .cs
[Family.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/5728411/Family.txt)
[Program.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/5728412/Program.txt)

**Environment**
I'm using latest version of VS2019 on Windows 7 64

**Comment by j82w** [comment]
@tubli can you provide the csproj file? The nuget contains a ServiceInterop.dll which should be getting copied to the applications output directory. It seems that the file is not getting copied.

**Comment by tubli** [comment]
@j82w Thanks for responding.

I thought the same, but the .csproj for the one that works is pretty much the same as the csproj for the version thtat doesn't work. 

Here is the .csproj and screenshot of the bin folder for verison 3.15.1 (has error):
[CosmosDbDemo_3_15_1_csproj.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/5733253/CosmosDbDemo_3_15_1_csproj.txt)
![bin_dir_3_6](https://user-images.githubusercontent.com/33538193/102959207-1ef6a680-449c-11eb-88f5-4778147836d7.PNG)

Here is the .csproj and screenshot of the bin folder for verison 3.6 (no error):
[CosmosDbDemo_3_6_csproj.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/5733254/CosmosDbDemo_3_6_csproj.txt)
![bin_dir_3_15_1](https://user-images.githubusercontent.com/33538193/102959208-1f8f3d00-449c-11eb-8fe3-9af2a1295a78.PNG)

Hopefully you see something that I don't.

**Comment by j82w** [comment]
@tubli can you provide the properties -> details of the ServiceInterop.dll? Then can you do a clean and verify the bin folder is empty and then do a build. The service interop changes with each release of the SDK. It's possible the service interop version is not getting updated when the SDK version is changed.

**Comment by ealsur** [comment]
@tubli Are you running on Windows 7? Please see https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-dot-net-sdk#common-query-issues

![image](https://user-images.githubusercontent.com/1633401/103302139-c2254f80-49b7-11eb-8639-752e13c07f7e.png)

Please use a newer Windows version or if that is not possible, remove the ServiceInterop.dll file from the project output, this would make the SDK retrieve the query plan using a network call.

**Comment by ealsur** [comment]
Closing as by-design when using an older Windows version, please reopen if you are using a newer Windows version and still experiencing the issue.

**Comment by tubli** [comment]
For anyone having the same problem, here's what I found:

Removing the ServiceInterop.dll from the project output didn't fix the issue for .NET 5 or Core 3.1. However, everything works fine on windows 7 if you use .NET Framework 4.7.2 (no modifications needed), so I just switched to that since I didn't have strong cross-platform requirements for this part of the code.
