### ISSUE TITLE
RequestCharge not available for CosmosQueryResponse<T>

### ISSUE THREAD

**Issue by hsavran** [Azure/azure-cosmos-dotnet-v3#21]
I can not access **Resources.RequestCharge** in CosmosQueryResponse object.

To recreate
var resultSet = await querysetIterator.FetchNextSetAsync();

There is no way to get RequestCharge in resultSet. FeedResponse object is private.

**Comment by j82w** [comment]
Request charge is now available: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/177
