### ISSUE TITLE
Timeout for LINQ queries

### ISSUE THREAD

**Issue by skurik** [Azure/azure-cosmos-dotnet-v3#2100]
**Describe the bug**
Request timeout set on `CosmosClientBuilder` using `WithRequestTimeout` is not respected by `Container.GetItemLinqQueryable`. When I run a heavy query, it does not return nor throw after the request timeout of 1 second passes.

I am aware that this request timeout is interpreted as a network request timeout, not an operation timeout. However, in this case, the client does not receive anything from the server. I put a breakpoint to the loop in `CosmosLinqQuery.GetEnumerator()` and I can see no results are returned before the timeout passes.

EDIT: What's also troubling is that it keeps hanging indefinitely on `localFeedIterator.ReadNextAsync`. I left it running for a couple of minutes and it didn't do anything. There surely must be some timeout enforced downstream, right?

**To Reproduce**
Execute a heavy LINQ query and set a request timeout of 1 second.

**Expected behavior**
The request timeout is respected.

**Actual behavior**
The query keeps running even after the timeout period passes.

**Environment summary**
SDK Version: 3.15.0
OS Version (e.g. Windows, Linux, MacOSX): Windows 10

**Comment by j82w** [comment]
The [request timeout](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/3172a1af13b3738a79c2eb8db234e84a76d5cf1d/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L151) that is set is only per a request to the Cosmos DB service.  Depending on the query the SDK may send multiple requests to the Cosmos DB service. `localFeedIterator.ReadNextAsync` takes in a cancellation token and can be used to cancel operation based on the overall time. 

@skurik can you please provide a simple console application that reproduces this?

**Comment by skurik** [comment]
@j82w But we are not calling `localFeedIterator.ReadNextAsync`. We simply use `GetItemLinqQueryable<T>(allowSynchronousQueryExecution: true)`. In that case, it sends `CancellationToken.None` to `ReadNextAsync`.

I will try to replicate it with 3.13.0.

**Comment by skurik** [comment]
I tried now with 3.13.0 and with 3.15.1

__3.15.1__
Behaves the same as __3.15.0__, hangs on `localFeedIterator.ReadNextAsync`. In particular, these are the two call stacks of Cosmos-related threads when I pause it:

This is the thread on which `GetItemLinqQueryable<T>().ToList()` is called:

![image](https://user-images.githubusercontent.com/951352/103558503-1008ee80-4eb5-11eb-8ed1-08662544e0cf.png)

And this is the other one:

![image](https://user-images.githubusercontent.com/951352/103558585-2f078080-4eb5-11eb-8a7c-0e69fd613506.png)

__3.13.0__
Unlike __3.15.0__ and __3.15.1__, it doesn't hang and is looping properly in `CosmosLinqQuery<T>.GetEnumerator()`. The timeout is still not respected, obviously.

**Comment by j82w** [comment]
@skurik if this impacting any production scenarios [contact support](https://aka.ms/azure-support) so a support ticket is created and will ensure the issue is properly prioritized.

**Comment by skurik** [comment]
@j82w Done.

**Comment by skurik** [comment]
@j82w As for 3.15.x hanging in `CosmosLinqQuery<T>.GetEnumerator()`, it seems like the same issue as https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2051.

**Comment by j82w** [comment]
@skurik it is possible that the issues are related, but my guess without investigating is that some change introduced a deadlock for the synchronized execution. If you can provide a sample that reproduces the issues that always helps investigation.

@sboshra owns the incidents and is doing the investigation.

**Comment by skurik** [comment]
@j82w @sboshra To reproduce:

1. Have a moderately sized database (we have 670 million records now).
2. `Container.GetItemLinqQueryable<T>().ToList()` or other query which forces it to go through every partition.

**Comment by khdang** [comment]
@skurik can you please share if it happens with other collections? does it happen with other query or only happens when you do .ToList()?

**Comment by khdang** [comment]
@skurik in your scenario (```Container.GetItemLinqQueryable<T>().ToList()``` on a 670M records collection), isn't the amout of data very large and it would take a long time to complete that synchronous call? could you please elaborate more on the hang behavior: is there any network activity? how did you confirm no progress is being made? 
I've tried with the following code with 3.15.0 on a 9-partition collections and it didn't reproduce what you described.
```csharp
Stopwatch stopwatch = new Stopwatch();
stopwatch.Start();
List<Event> itemList = container.GetItemLinqQueryable<Event>(allowSynchronousQueryExecution:true).ToList<Event>();
stopwatch.Stop();
Console.WriteLine($"Received {itemList.Count} items in {stopwatch.ElapsedMilliseconds} ms");
// Output: Received 864498 items in 67984 ms
```

**Comment by skurik** [comment]
@khdang 

As I checked now, it's not an entirely empty query. The SQL (the result of `query.ToString()`) is

```
{
  "query":  "SELECT VALUE root FROM root WHERE (true AND ((true AND (\"2020-12-25T00:00:00\" <= root[\"createdUtc\"])) AND (root[\"createdUtc\"] < \"2021-01-02T00:00:00\")))"
}
```

I made it artificially heavy by not putting a partition key predicate there. This query matches over 8 million documents.

How do I know there is no progress? I put a breakpoint to `CosmosLinqQuery.GetEnumerator()` on this line:

```
FeedResponse<T> items = TaskHelper.InlineIfPossible(() => localFeedIterator.ReadNextAsync(CancellationToken.None), null).GetAwaiter().GetResult();
```

and with 3.15.0 and 3.15.1, it hits the breakpoint once and then never again. It doesn't return, it doesn't throw an exception, it just hangs.

With 3.13.0 and breakpoint on the same line, I can see it's making progress, it's getting items back.

It certainly doesn't happen on every query, otherwise our system would grind to a halt. We have a single collection.

**Comment by skurik** [comment]
@khdang And as I already mentioned, with 3.15.0, when after a while of waiting I pause the process, this is always on top of the stack:

![image](https://user-images.githubusercontent.com/951352/105331946-5740f000-5bd4-11eb-809d-f58322032d7c.png)

**Comment by skurik** [comment]
Update: The same query does __not__ hang in 3.16.0.

**Comment by bchong95** [comment]
Issue does not seems to reproduce in the latest SDK verison.
