### ISSUE TITLE
feedIterator.HasMoreResults always returns false in Azure

### ISSUE THREAD

**Issue by Daniel-Guenter** [Azure/azure-cosmos-dotnet-v3#2101]
I am trying to get the pull model of the change feed working as described here.

https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-pull-model

```
                using (var feedIterator = _container.GetChangeFeedIterator<NotificationRequestItemDbContainer>(ChangeFeedStartFrom.Time(startUtc)))
                {
                    while (feedIterator.HasMoreResults)
                    {
                        cancellationToken.ThrowIfCancellationRequested();

                        try
                        {
                            var matchedChanges = (await feedIterator.ReadNextAsync(cancellationToken))
```

I am using version 3.15.2-preview of the .net sdk.  When I use this code against my local emulator everything works fine.  HasMoreResults is always true as described in the documentation.  However when I use a cosmos DB hosted in azure, the HasMoreResults returns false immediately.  Even I loop and wait for HasMoreResults to be true it will never return any results.  I know the connection and the container are fine because I can query the data fine with a GetItemQueryIterator. 

Am I missing some setup to get the change feed to work in azure?

_Originally posted by @Daniel-Guenter in https://github.com/Azure/azure-cosmos-dotnet-v3/discussions/2095_

**Comment by j82w** [comment]
@Daniel-Guenter does it work with SDK version 3.13.0-preview?

**Comment by Daniel-Guenter** [comment]
Hi, the problem turned out to be multi region writes.  

![image](https://user-images.githubusercontent.com/7799355/103567832-bc30e200-4e81-11eb-8129-ec72c138d400.png)

Once disabled I was able to read the feed iterator.

**Comment by j82w** [comment]
@Daniel-Guenter did 3.13.0-preview throw an exception? It should be throwing a CosmosException with a bad request for this scenario.

**Comment by Daniel-Guenter** [comment]
Yes, the ReadNextAsync did throw an exception with the following details.

Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Message: {"Errors":["StartTime\/IfMofifiedSince is not currently supported when EnableMultipleWriteLocations is set."]}

The reason I did not initially catch this is because of the blind try/catch suggested in the documentation.  

P.S. 3.13.0 did not work well for me at all. The first few times the HasMoreResults was true then mysteriously changed to false with no exception thrown.  Version 3.14 was the same.  Version 3.15.2 worked as expected with HasMoreResults returning true in perpetuity.

**Comment by ealsur** [comment]
The problem is that the blind try/catch in the documentation is assuming customer is with version 3.14 where Not Modified threw exceptions. It should not be blind catching them but rather filter the status code.

On 3.15.2, do you get an exception on ReadNextAsync or it never gets there?

**Comment by ealsur** [comment]
Verified 3.15.2 also throws the excepted exception, the problem are the docs, so I sent https://github.com/MicrosoftDocs/azure-docs-pr/pull/142108

**Comment by ealsur** [comment]
Docs were updated, should be deployed live in the next 24hs
