### ISSUE TITLE
Group by when my document has array property?

### ISSUE THREAD

**Issue by MichalLechowski** [Azure/azure-cosmos-dotnet-v3#2114]
Hello guys,

I'm glad group by is finally available to use but I have a 'small' problem with it. My document looks like this for instance:
````
{
"deviceId": "1",  
"timestamp": "01-01-2021", 
"properties: [     
   {"Name": "prop1", "Value": "val1"},   
   {"Name": "prop2", "Value": "val2"}  
]  
}
````

So what I'm trying to do is to get the latest document for every device I have. This work just fine:

```
SELECT *
FROM (
SELECT MAX(f.timestamp) as measuredAt, f.deviceId
FROM f
GROUP BY f.deviceId
) AS latestMeasurement
```

returns for instance:

``` [
    {
        "measuredAt": "2020-05-08T06:23:13.3914671Z",
        "deviceId": "1"
    },
    {
        "measuredAt": "2020-05-12T14:21:34.1031887Z",
        "deviceId": "2"
    },
```

But I need properties object which is an array so I get the values from a particular device. So I need something like this:

```
SELECT *
FROM (
SELECT MAX(f.timestamp) as measuredAt, f.deviceId, f.properties
FROM f
GROUP BY f.deviceId
) AS latestMeasurement
```

but it throws:
"SELECT * is not allowed with GROUP BY."

So the question pretty much is if there's a way to make it work? Seems like any array object use "select" underneath or "select value" which is not an option with group by?

**Comment by timsander1** [comment]
For GROUP BY, you can only project properties in the GROUP BY clause or aggregates. There are a few alternatives for this scenario:

1. Once you've obtained the DeviceId, query for the properties in a separate request
2. Run individual queries for each DeviceId (basically grab each DeviceId individually, looking for the max timestamp. Something like:

SELECT * FROM c
FROM c 
WHERE c.deviceId = "val"
ORDER BY c._timestamp DESC

3. Build a real-time materialized view that persists the latest DeviceId document in a separate collection

**Comment by timsander1** [comment]
For #3, here's a video on that materialized views in Cosmos DB - https://www.youtube.com/watch?v=faXkCccz5eA&t=1733s

**Comment by bchong95** [comment]
Looks like the question has gotten answered. Please reopen the ticket if there are further questions.
