### ISSUE TITLE
FeedPollDelay in ChangeFeedProcessorOptions is not respected

### ISSUE THREAD

**Issue by rmaziarka** [Azure/azure-cosmos-dotnet-v3#2127]
Hello everybody,

**Describe the bug**
When FeedPollDelay in CosmosDBTrigger is used (which uses [ChangeFeedProcessorOptions](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/aa4eeafdcf1120358fef2df9fe87c46d2872d4a1/src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs#L281)) delay is not respected by the change feed mechanism. Calls to the `leases` collections are made every few seconds.

**To Reproduce**
ChangeFeedProcessorOptions looks as follows:
```csharp
    public class Func
    {
        public const int FiveMinutesInMiliseconds = 300000;

        [FunctionName("Func")]
        public async Task Run([CosmosDBTrigger(
                databaseName: "databaseName",
                collectionName: "collectionname",
                ConnectionStringSetting = "COSMOSDB_CONNECTION_STRING",
                LeaseCollectionName = "leases",
                CreateLeaseCollectionIfNotExists = true,
                FeedPollDelay = FiveMinutesInMiliseconds)]
```
In the Azure Func option I see that option is set correctly:
![image](https://user-images.githubusercontent.com/5219374/105009216-828fd780-5a3a-11eb-841d-73e241b06d45.png)

There were no runs of the function between 9:15 and 9:40:
![image](https://user-images.githubusercontent.com/5219374/105014476-c685db00-5a40-11eb-9052-5c8bcae66e08.png)

but then in CosmosDB Logs I see that the feed mechanism runs every single second 
![image](https://user-images.githubusercontent.com/5219374/105014614-ecab7b00-5a40-11eb-825b-a58f78035744.png)

I tried to clean lease collection, stop and start a function - nothing helped.

**Expected behavior**
A single function call to the `leases` collection every 5 minutes.

**Actual behavior**
A lot of calls to the `leases` collection.

**Environment summary**
ActivityId to track function run - `6f6d4528-86fa-404a-9a34-7f0a9afc6fdf`
Time when happened - `2021-01-19T09:22:32.782Z`

**Comment by ealsur** [comment]
@rmaziarka This is the wrong repo, don't you mean to send this to the Functions repo? https://github.com/Azure/azure-webjobs-sdk-extensions

In any case, this is not a bug and that setting does not measure the calls to the Leases collection. 

The leases collection is used to store state. State is updated frequently, whenever your code finishes processing some changes, and periodically to refresh ownership of the leases by the current instance.

The FeedPollDelay affects Change Feed requests to the Monitored Collection (doesn't affect any interaction with the leases collection). And only applies when the Change Feed is checked and there are no changes. See the official docs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-trigger?tabs=csharp#configuration

![image](https://user-images.githubusercontent.com/1633401/105062523-8b2ee080-5a2f-11eb-973f-8e3af70bccd6.png)

For more details on the Change Feed Processor see: https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor

**Comment by rmaziarka** [comment]
Thanks @ealsur for that explanation. 

But in that case which class / component / library is responsible for contacting with Lease collection? In a second image that you referred to in the comment, there is information **update the lease store**. So I would assume that it is something in azure-cosmos-dotnet library contacts my Lease collection every few seconds.

**Comment by ealsur** [comment]
@rmaziarka The Change Feed Processor contacts the lease store, like I mentioned, to checkpoint or to renew the leases ownership. The lease store usage (or the reason for it) is explained in https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#components-of-the-change-feed-processor

Checkpoints happen every time your handler finishes processing a set of changes, there is no control over that that you can change, the checkpointing (updating of the lease) needs to happen to mark up to which part of the Change Feed you have already processed, so if the Function crashes or restarts, it can continue from that last point you processed.

Ownership refreshment happens based on the LeaseRenewalInternal that you can configure:

![image](https://user-images.githubusercontent.com/1633401/105096849-8af90a00-5a5c-11eb-88af-c300414c79a2.png)

This is a key part of the dynamic load balancing. If you have multiple Function instances, they distribute the leases among themselves and each instance will process only it's owned leases.

What I don't understand is what is the concern with the lease store and why you want to limit the interactions, which are a core component of how the Change Feed is consumed.

**Comment by rmaziarka** [comment]
@ealsur Let's start from the end. I was misled by the class [ChangeFeedProcessorOptions](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Configuration/ChangeFeedProcessorOptions.cs) in this repo so I thought that this repo is a proper one to ask this question. Do you find it required to move the discussion to the [azure-documentdb-changefeedprocessor-dotnet](https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet) repo?

And going back to my concerns. My case looks like that:
- Once per hour contact a lot of external APIs.
- Base on that put data in Primary and Secondary collections.
- New data in Secondary collection starts CosmosDB Trigger.

Data is stored in CosmosDB **in Serverless mode**. So I pay for a single contact with the CosmosDB. And it turns out that cooperation with the Leases collection is the most expensive one across my app:
![image](https://user-images.githubusercontent.com/5219374/105152632-b97fef00-5b07-11eb-9683-8b371f216898.png)
Mostly because other functions run once per hour. In the meantime, there is no traffic = no calls to CosmosDB = no money spent. But the Leases collection is requested every few seconds from the ChangeFeed. And it is completely pointless because there won't be any new data there. 

So my goal is to cut down these request to the minimum - make them happen periodically every 5/10 minutes.

**Comment by rmaziarka** [comment]
And a few more info about the request to the Leases itself:
![image](https://user-images.githubusercontent.com/5219374/105154113-7c1c6100-5b09-11eb-8c12-6eec5aa49081.png)
Unfortunately, CosmosDB obfuscated the param value, but if needed I can try to get it.

**Comment by ealsur** [comment]
I understand now the context. Sadly the Change Feed Processor (and the Trigger for instance) have a heavy dependency on the leases collection and there is no way to remove it.

The query you see being executed is the Change Feed Processor renewing the leases it owns. 

You can potentially reduce the frequency of these queries/activities on the lease collection (all except the Checkpoint happening at the end of a batch being processed) by changing the values of these [configurations](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-trigger?tabs=csharp#configuration):

![image](https://user-images.githubusercontent.com/1633401/105198266-58015580-5af2-11eb-9980-3d0b99016f6c.png)


The important rule is that the Expiration should be higher than the Renewal or the current instance will start to lose leases.

For example, you can increase the expiration to 120000 and the renewal to 60000, and that will reduce the query volume by ~50% and point operations that renew the lease too. Obviously the downside of this is that if your Function instance crashes unexpectedly, it will take 2 minutes for any other Function instance to be able to pick up the owned lease because it needs to wait 2 minutes until it can mark it as expired.

**Comment by rmaziarka** [comment]
Thanks @ealsur for that. 

Unfortunately I tried these settings and nothing changed:
![image](https://user-images.githubusercontent.com/5219374/105221966-1e643500-5b5a-11eb-9ca7-04e626868c24.png)

![image](https://user-images.githubusercontent.com/5219374/105222128-579ca500-5b5a-11eb-9b37-2411cf8f2150.png)

![image](https://user-images.githubusercontent.com/5219374/105221897-05f41a80-5b5a-11eb-9a18-57e844fc868b.png)
I turned off the function, the whole application but it doesn't make any change.

**Comment by ealsur** [comment]
@rmaziarka Try raising the LeaseAcquireInterval also, to a similar value than the LeaseRenewInterval, 2 minutes maybe. That was the other parameter I mentioned on the screen capture.

**Comment by rmaziarka** [comment]
Ehh, I could assume that I should do it as well 😕

Unfortunately, still no changes:
![image](https://user-images.githubusercontent.com/5219374/105330199-5018e280-5bd2-11eb-94b9-a198b246212d.png)

![image](https://user-images.githubusercontent.com/5219374/105330064-22cc3480-5bd2-11eb-9cc9-66fb3d205cdd.png)

**Comment by ealsur** [comment]
@rmaziarka Is this running on Consumption Plan? Azure Functions in Consumption Plan has an external component that takes care of the scaling, this external component measures the pending number of documents to be read and decides how to scale. They use the Change Feed Processor Estimator API, which reads all leases, checks the current saved point and compares it with the latest state to calculate the difference.

I don't know how frequently they do that, but that would also match with that query and it's totally external to your Function code.

Does your report show the User agent performing those queries?

**Comment by rmaziarka** [comment]
@ealsur yes, I use Consumption Plan for my function app.

There is such information in logs:
![image](https://user-images.githubusercontent.com/5219374/105513545-be44ce80-5cd2-11eb-88cc-6773d0872ea7.png)
I hope it'll help.

**Comment by rmaziarka** [comment]
@ealsur I tried to understand and apply this Change Feed Process Estimator in the project but I don't see any entry point when you use CosmosDBTrigger. 
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-use-change-feed-estimator
Is it something configurable from the function side?

**Comment by ealsur** [comment]
@rmaziarka 

I do not have access to the Consumption Plan details and internal workings, what I am saying is that, if you are on Consumption Plan, then I know the Functions runtime checks the estimation and know if they need to scale up/down. If there are no more events in your Change Feed for more than 5-10 minutes, [Consumption Plan](https://docs.microsoft.com/en-us/azure/azure-functions/consumption-plan) scales down and shuts down all instances. But periodically (I have no clue how often, it could be every 10 seconds) they would use the Estimator APIs, to know if there are any new changes and "wake up" instances to process them, this is not a hunch, this actually happens, so it could be very well the source of these queries. All this logic is completely external to Cosmos DB or the Cosmos DB Trigger, so there is nothing you can configure as far as I know (you could ask the Functions team through a support ticket maybe if the period they use to check is configurable). My only hunch based on the screenshot you pasted is the User Agent. At the end, it says `changefeed-2.2.1`, meaning the source is using the [Change Feed Processor](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.ChangeFeedProcessor/) nuget 2.2.1, in your Function App project, you probably have the Cosmos DB extension nuget, which has a dependency on the CFP nuget, if your version does not match (for example, yours is higher), then it would confirm the suspicion that it's coming from there.

Regarding your second question, all those docs are for the Change Feed Processor, not related to Azure Functions Cosmos DB Trigger. Consumption Plan uses the CFP nuget and this API as far as I know: 

* https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.changefeedprocessor.changefeedprocessorbuilder.buildestimatorasync?view=azure-dotnet#Microsoft_Azure_Documents_ChangeFeedProcessor_ChangeFeedProcessorBuilder_BuildEstimatorAsync
* https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.changefeedprocessor.partitionmanagement.iremainingworkestimator.getestimatedremainingworkperpartitionasync?view=azure-dotnet#Microsoft_Azure_Documents_ChangeFeedProcessor_PartitionManagement_IRemainingWorkEstimator_GetEstimatedRemainingWorkPerPartitionAsync

If your intent is to check if it's the same query, you could do the same from a console app.

**Comment by rmaziarka** [comment]
@ealsur you are right - queries from my application has a different useragent:
![image](https://user-images.githubusercontent.com/5219374/105763437-13dcdd80-5f56-11eb-924a-87db24738726.png)
Thanks for your time, I'll try to find some people from AF to get some details 😊

**Comment by ealsur** [comment]
From the sound of it, it looks like the scaling component of Azure Functions does not work fantastically well with the Serverless offering, and the reason seems to be the fact that they do some queries on the leases collection periodically to check if there is anything new on the Change Feed to decide whether to wake up or scale up instances. cc @ThomasWeiss
