### ISSUE TITLE
Support for Patch on Bulk with retries on response size

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#2130]
Currently, Batch API returns an HTTP 413 as pre-emptive measure of the response is going to be bigger than 4Mb for some items.

For Patch calls leveraging Bulk, that 413 does not let us tell apart a real 413 (customer is actually making the document larger than 2Mb) from a Batch API pre-emption.

Backend team will add a new substatus code to help tell the difference, and once that is done, we can wire up Patch retries.

**Comment by j82w** [comment]
Fixed in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2124
