### ISSUE TITLE
About subquery 

### ISSUE THREAD

**Issue by hassanarteaga** [Azure/azure-cosmos-dotnet-v3#2133]
I'm trying to execute query with subquery with QueryItemsAsync function from C# API
SELECT VALUE COUNT(Products) FROM 
  (SELECT c.ProductCode, Max(c.ProductPrice)  Maximo, Min(c.ProductPrice) as Minimo 
GROUP BY c.ProductCode) Products 

Result is always  0
I'm using Cosmos DB SDK NET 3.16.

If I execute the same query in Azure Portal (Data Explorer) I got the correct value. 
Any idea what's going on ?

Best regards

**Comment by timsander1** [comment]
Hi @hassanarteaga , queries with a subquery with GROUP BY and an aggregate system function are not currently supported. Learn more here: https://docs.microsoft.com/azure/cosmos-db/sql-query-group-by#remarks 

The very fact that you are able to run this query without hitting an error is a bug so you should not use this type of query. We plan to support these types  of queries (DISTINCT/GROUP BY in a subquery + COUNT) in the future.

**Comment by hassanarteaga** [comment]
Thanks guys for the feedback.
