### ISSUE TITLE
Linux performance roadmap?

### ISSUE THREAD

**Issue by NoahStahl** [Azure/azure-cosmos-dotnet-v3#2139]
It's [clearly documented](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-dotnet-sdk-v3-sql) that the SDK has a performance preference for Windows x64:

> We recommend Windows 64-bit host processing for improved performance. The SQL SDK includes a native ServiceInterop.dll to parse and optimize queries locally. ServiceInterop.dll is supported only on the Windows x64 platform.

Given that .NET Core on Linux seems to provide better performance in general, and that hosting on Linux is significantly less expensive, it would be nice if the Cosmos SDK performed well on both. I'm just curious if there are plans to implement the  ServiceInterop equivalent or otherwise get Linux hosting on par with regards to Cosmos DB?

**Comment by j82w** [comment]
@timsander1 can you help answer this? There was already some [improvements](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-3130---2020-09-21) to help in the linux scenario.

**Comment by timsander1** [comment]
For implementing the ServiceInterop equivalent on Linux, there are no upcoming plans. In these cases, we'll go to the gateway to parse and optimize queries. There are no short-term plans to change this but if you are facing any issues with query latency, I'd be happy to help.

**Comment by NoahStahl** [comment]
Thanks for the reply. I understand the gateway approach is the fallback, but since this requires extra round trip it's not a very desirable alternative. My interest comes mainly from seeing this as a hole in the Cosmos performance story, where the low-latency SLA is a major selling point and rightfully so, but has this big asterisk of *only for Windows x64. Given that .NET on Linux is emerging as the best performance combination, and that this is a .NET SDK, it would be nice to not have to choose between either optimal general app performance (Linux) or optimal Cosmos performance (Windows x64). This is not to mention the difference in hosting costs -- on the one hand we have (awesome) serverless and free tier, on the other hand, pay extra for Windows hosting.

I'm still a very happy Cosmos customer, just wanted to register interest which perhaps others share. That said, feel free to close the issue if this isn't useful as something that will be addressed.

**Comment by onionhammer** [comment]
This gap has existed long enough, I think. Time to re-address. Where are the PMs on cosmos at?

**Comment by NoahStahl** [comment]
The [docs](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-query-sdk?tabs=v3&pivots=programming-language-csharp) *seem* to suggest that 64-bit Windows hosting is not the only way to prevent the query plan calls:

`There are two ways to remove this request and reduce the latency of the query operation`
...
(assuming the following sections are the "two ways")
1. Use local Query Plan generation (via 64-bit Windows host)
2. Use single partition queries

If I interpret correctly, option 2 works on Linux. If so, this represents an alternative approach: use straightforward single-partition queries and host on Linux.

Would be great to have some clarity or confirmation from the team.

For what it's worth, I recently migrated a project from Windows x64 to Linux hosting via Azure App Service, and the operations appear to have similar performance, i.e. most queries under 10ms.

**Comment by onionhammer** [comment]
@NoahStahl that's exactly what it means. The optimal way to use Cosmos is not supported in Azure's latest managed hosting solution; Azure Container Apps.. and scenarios where hosting on Windows x64 is going to become rarer and rarer, but I see microsoft making no moves to address this discrepancy.
