### ISSUE TITLE
Full fidelity: Find out which properties have mutated

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-dotnet-v3#2142]
Hello,

I have a question about the upcoming full fidelity feature. If I'm monitoring changes to an item, how would I go about deciding exactly which property has changed? I need to take different actions for different properties. For every mutation, I'd like to know exactly what has mutated. Is this information going to be available to us?

So, if I have a stream coming in that looks like:

1) Insert item
2) Update property A
3) Update property B
4) Delete item

For step 2, I need a way to compare it to step 1 to conclude that property A has changed.

Please help me understand if something like this will be achievable with full fidelity.

**Comment by ealsur** [comment]
Change Feed Full Fidelity is still in preview so this might change.

Current contract based on my tests show that for replace operations, the Change Feed record contains the previous image.

The item would have a "_metadata" property with an "operationType" property with the value "replace" and another property called "previousImage" containing the document before the replace.

For example:

```
{
    "id": "4661bff2-329b-45fd-8963-e3f0c9384938",
    "taskNum": 42,
    "cost": 50.0,
    "description": "CreateRandomToDoActivity",
    "status": "TBDf2d440c3-84a4-4789-ba7a-cbe42e70a8fd",
    "_metadata": {
        "operationType": "replace",
        "previousImage": {
            "id": "4661bff2-329b-45fd-8963-e3f0c9384938",
            "taskNum": 42,
            "cost": 1,
            "description": "CreateRandomToDoActivity",
            "status": "TBDf2d440c3-84a4-4789-ba7a-cbe42e70a8fd"
        }
    }
}
```

> This is subject to change before the feature GA

**Comment by petro2050** [comment]
@ealsur Thanks. This is great. How can I get my hands on the preview?

**Comment by ealsur** [comment]
@timsander1 do you know what is the roadmap for FF public preview? @petro2050 I don't think the preview is public yet.

**Comment by timsander1** [comment]
Hi @petro2050, we don't have a preview available yet. This is still in progress.
