### ISSUE TITLE
Optimize gateway session token logic

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2146]
Currently the .NET SDK is sending the entire session token to the gateway. 

1. This adds unnecessary overhead to compute the entire session token.
2. It causes the headers to grow to large and the service will throw a [400 bad request](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-dot-net-sdk-request-header-too-large) and will prevent users from completing requests.

Java SDK implemented a [fix](https://github.com/Azure/azure-sdk-for-java/pull/16111) that needs to gets to ported to the .NET SDK.

Example of 400 error message:
`Microsoft.Azure.Documents.DocumentClientException: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd"> <HTML><HEAD><TITLE>Bad Request</TITLE> <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD> <BODY><h2>Bad Request - Request Too Long</h2> <hr><p>HTTP Error 400. The size of the request headers is too long.</p> </BODY></HTML> RequestUri: https://account-westus.documents.azure.com/dbs/test/colls/test-doc/docs/BB1cXUJX; RequestMethod: GET; Header: x-ms-consistency-level Length: 7; Header: x-ms-documentdb-partitionkey Length: 12; Header: x-ms-date Length: 29; Header: authorization Length: 84; Header: x-ms-session-token Length: 15837; Header: x-ms-activity-id Length: 36; Header: Cache-Control Length: 8; Header: User-Agent Length: 72; Header: x-ms-version Length: 10; Header: Accept Length: 16; , Request URI: /dbs/amp/colls/amp-doc/docs/BB1cXUJX, RequestStats: , SDK: documentdb-dotnet-sdk/2.11.6 Host/64-bit MicrosoftWindowsNT/10.0.17763.0 at Microsoft.Azure.Documents.GatewayStoreClient.<ParseResponseAsync>d__8.MoveNext()`

**Comment by kirankumarkolli** [comment]
@moderakh please share the earlier PR versions also.

**Comment by moderakh** [comment]
> @moderakh please share the earlier PR versions also.

 https://msdata.visualstudio.com/CosmosDB/_git/document-sql-java/pullrequest/110740
