### ISSUE TITLE
How to implement consistent paging properly?

### ISSUE THREAD

**Issue by justinbhopper** [Azure/azure-cosmos-dotnet-v3#2149]
Is it possible to use the feed iterators to paginate with a **consistent** count returned in each page?

Take this snippet as an example:
```
var feed = container.GetItemQueryIterator<Foo>("select * from root", continuationToken, new QueryRequestOptions
{
    MaxItemCount = 20
});

while (feed.HasMoreResults)
{
    var page = feed.ReadNextAsync();
    ...
}
```

1. Assuming there are over 1000 items of `Foo`, is it true that `page` may have returned less than 20 items (and perhaps even zero)?  I have read that it is recommended to continue draining the feed until I have obtained my desired result count.
2. If the first round trip returns **10 items**, I must make a second round trip to reach my goal of 20 items.  If the second trip returns **15 items**, I now have a total of **25 items**.  Additionally, the continuation token is only good for continuing past the 25th item, which means the caller must accept the 25 results despite having requested only 20.  What if the caller cannot support the 5 extra items?  The SDK does not allow modifying the `maxItemCount` for each trip, so I don't see a way to prevent this.

It seems to me that I can provide paging support, but only in such a way that a page size of N may result in up to N+N-1 items returned.  This might be a huge burden on a caller who can only handle a limited number of results at a time.

**Comment by j82w** [comment]
@timsander1 any suggestions?

**Comment by bchong95** [comment]
There are a couple of options for this.

The first is changing the max item count through each iteration (similar to the linux read API)

```
List<var> items = new List<var>();
const int desiredPageSize = 20;
string continuationToken = null;

while(items.Count != desiredPageSize)
{
     var feedIterator = container.GetItemQueryIterator<Foo>("select * from root", continuationToken , new QueryRequestOptions
     {
         MaxItemCount = desiredPageSize - items.Count
     });

     var page = feed.ReadNextAsync();
     items.AddRange(page);
     continuationToken = page.ContinuationToken;
     if(!feedIterator.HasMoreResults)) break;
}

return items;
```

The second is to perform a take operation with keyset pagination (https://blog.jooq.org/2013/11/18/faster-sql-pagination-with-keysets-continued/):

```
List<var> items = new List<var>();
const int desiredPageSize = 20;
string lastSeenRid = string.Empty;
var feedIterator = container.GetItemQueryIterator<Foo>(
                   $"select TOP {desiredPageSize} * from root WHERE root._rid > {lastSeenRid}", 
                  new QueryRequestOptions
                 {
                        MaxItemCount = int.MaxValue
                  });
while(feedIterator.HasMoreResults)
{
     var page = feed.ReadNextAsync();
     items.AddRange(page);
}

lastSeenRid  = items.Last().GetRid();

return items;
```

**Comment by justinbhopper** [comment]
@bchong95 Thanks for the suggestions.  It didn't occur to me to re-create the feed iterator between loops.  Thank you!
