### ISSUE TITLE
.NET 3.1 upgrades

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2150]
All the tests, benchmarks, and sample projects should be updated to use the latest [.NET 5 version](https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

**Comment by YohanSciubukgian** [comment]
Will we still be able to use the SDK using .Net core 3.1 which is LTS until December 3, 2022 ?
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by j82w** [comment]
The SDK still is targeting .net standard 2.0. You bring up a good point about using .NET core 3.1 until the next LTS version is released.
