### ISSUE TITLE
creating items with negative double properties are quoted in the db

### ISSUE THREAD

**Issue by MariaCobretti** [Azure/azure-cosmos-dotnet-v3#2156]
when creating an item with a double property that has a negative value, that value is being quoted in the database.
when the value is positive it is not.

I dont think this is intended.

**Comment by j82w** [comment]
@MariaCobretti can you provide an example? I just did a quick tests and was not able to reproduce this behavior. 

```
   [TestMethod]
        public async Task CreateDropItemTest()
        {
            ToDoActivity testItem = ToDoActivity.CreateRandomToDoActivity();
            testItem.cost = -2508;
            ItemResponse<ToDoActivity> response = await this.Container.CreateItemAsync<ToDoActivity>(item: testItem);
```

```
{
    "id": "87bd9370-805d-4e9d-88ea-2b1afdc93f16",
    "taskNum": 42,
    "cost": -2508,
```

**Comment by MariaCobretti** [comment]
wasn't able to reproduce it either today.. well nvm then.. no idea how those quotes got there 
thanks you anyways
