### ISSUE TITLE
Cosmos Sql parser : IN / NOT IN operator parsing fails for array of values 

### ISSUE THREAD

**Issue by sumantbhardvaj** [Azure/azure-cosmos-dotnet-v3#2177]
Parsing fails for - Select * from f WHERE f.zipcode IN (2, 3, 4)
Parser does not parse (2,3,4) as array but a single string token.

Another example: this query is also not getting parsed correctly. 
queryText = "SELECT * FROM c WHERE f.state NOT IN ('WA', 'CA')";
After parsing, its parsed as : {​​SELECT * FROM c WHERE ((f.state NOT IN ("WA', 'CA"))}​​
No that "WA','CA" is being treated as single string.

**Comment by j82w** [comment]
@timsander1 or @sboshra any suggestions?

**Comment by timsander1** [comment]
This is not an issue with an unreleased feature and not the public SDK version. Thanks for creating this for tracking purposes!
