### ISSUE TITLE
Cosmos Sql parser : Parsing fails for ARRAY_CONTAINS when single quotes values are being looked up

### ISSUE THREAD

**Issue by sumantbhardvaj** [Azure/azure-cosmos-dotnet-v3#2178]
both of the below query should parse correctly.

"select f.familyName from c JOIN f IN c.children where ARRAY_CONTAINS(f.pets, {​​​​​​​​\"givenName\": \"Goofy\"}​​​​​​​​, true)",
"select f.familyName from c JOIN f IN c.children where ARRAY_CONTAINS(f.pets, {​​​​​​​​'givenName': 'Goofy'}​​​​​​​​, true)",

**Comment by j82w** [comment]
@timsander1 any suggestions?

**Comment by timsander1** [comment]
This is not an issue with an unreleased feature and not the public SDK version. Thanks for creating this for tracking purposes!
