### ISSUE TITLE
ITrace Perf Optimizations

### ISSUE THREAD

**Issue by bchong95** [Azure/azure-cosmos-dotnet-v3#2187]
# ITrace Perf Optimizations
*  object pooling
* lazy allocation for lists of size greater than or equal to 2
* Keep reference to StoreResult without response Stream to avoid .ToString() allocation.

**Comment by j82w** [comment]
8.85385% drop in throughput from ITrace library based on the perf runner (12915 Rps to 11820 Rps).
22.3778% increase in latency from ITrace library based on the perf runner (8.67ms to 10.5ms)
![itracelatency](https://user-images.githubusercontent.com/8868107/107276701-441d8500-6a08-11eb-974a-f9539df7b0cb.jpg)
![itracerps](https://user-images.githubusercontent.com/8868107/107276702-44b61b80-6a08-11eb-8188-5715532bd9e0.jpg)

**Comment by j82w** [comment]
This was mostly fixed in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2204. The new runs shows roughly 2% regression.
