### ISSUE TITLE
Spatial index is not being used when using COUNT in combination with ST_WITHIN

### ISSUE THREAD

**Issue by tomkuijsten** [Azure/azure-cosmos-dotnet-v3#2188]
**Describe the bug**
I created a new collection to test spatial indexes, but when using the COUNT in combination with ST_WITHIN, it's not using the index. 

**To Reproduce**

I'm using geography index with a spatial index path on "/*" as mentioned in the docs. The test documents I create are in the following format:

```json
{
    "id": "adc6e3e5-0f73-48d4-9fa2-b46ec8d51b4e",
    "partitionKey": "0",
    "position": {
        "type": "Point",
        "coordinates": [
            5.96887475070724,
            52.21493333255078
        ]
    }
}
```

When using the ST_WITHIN function in a query, it's very fast and using the index. However, when I use the following query:

```sql

SELECT COUNT(1) 
FROM Locations c 
WHERE ST_WITHIN(c.position, 
{ "type": "Polygon",  "coordinates": [[
	[5.909, 52.262], [5.909, 52.164], 
	[6.018, 52.164], [6.018, 52.262], [5.909, 52.262]]]}
)

```

The index is not used, and all documents are actually retrieved (document count = 1000). Am I missing something?

**Expected behavior**
I expected the document count to be 0 (so, using the index for my query).

**Actual behavior**
It didn't use my index, RU was 100+ and document count was 1000.

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.16.0 (.net Core 3.1 console app)
OS Version (e.g. Windows, Linux, MacOSX): Windows 10

**Comment by j82w** [comment]
@timsander1 or @sboshra any suggestions?

**Comment by timsander1** [comment]
Hi @tomkuijsten, your observation is correct. If your query has a spatial system function, we will use the index for most queries. but not aggregates.

**Comment by tomkuijsten** [comment]
@timsander1 thanks for the quick reply and the clear answer! Any suggestions how to implement this kind of summarized counts? My first idea would be a materialized view with counters per region/polygon, but that requires a lot of management.

**Comment by timsander1** [comment]
That's my recommendation as well. You could build this with an Azure Function [reading from the change feed](https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-design-patterns). This solution will work well if you have a read-heavy scenario (>80% reads) but if there are a lot of writes, it might be expensive and complex to continuously update the materialized view.

**Comment by tomkuijsten** [comment]
It's read heavy, but not 80%. Each location has some properties which change quite often, these are the properties that are used to filter locations as well. What would be the alternative for a write-heavy scenario?

**Comment by timsander1** [comment]
With the materialized view approach, you'll pay more for updating the container with the materialized view. In other words, one write would result in two charges - the new write as well as an update to the materialized view. This will be much less expensive than the query unless it is a write-heavy scenario.

If there's a mix or writes and reads- I recommend doing the math on which is cheaper - having a materialized view or running the expensive query as needed.
