### ISSUE TITLE
Support custom ContractResolver in GetItemLinqQueryable

### ISSUE THREAD

**Issue by Romfos** [Azure/azure-cosmos-dotnet-v3#2199]
According to this comment

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/776af4be89a6ececda78f5454c40fda95336e9db/Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs#L502

"There are two ways to specify a custom attribute", but it is not true.

**There is a third way to do that:**
I can create custom DefaultContractResolver and override CreateProperty method and then return JsonProperty with Converter proeprty

**Change request:**
Now we can use custom CosmosSerializer and support it for serialization\deseriazliation, but GetItemLinqQueryable doesn't not respect it

Could you please support custom DefaultContractResolver for GetItemLinqQueryable method?

**Why do we need it:**

We have 2 assemblies:
1) public interfaces: models + abstract repository interface, zero dependency approach
2) Implementation for repository < cosmos client nuget reference

Now we have to use attributes, but would be better to use ContractResolver that allow us separate flat models from implementation detals (+ it allow us to go in future to system.text.json serializer without changing public interface)

**Comment by j82w** [comment]
@timsander1 can you please take a look?

**Comment by timsander1** [comment]
Hi @Romfos, thanks for bringing this up! I can confirm this is not supported now, but it's something we can look into supporting in the future
