### ISSUE TITLE
CosmosConfiguration should be immutable

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#22]
**Describe the bug**
The CosmosConfiguration that is passed to the CosmosClient constructor can be updated after the CosmosClient creation. The CosmosClient does not handle any updates to the CosmosConfiguration. This can cause unexpected behavior, and lead to confusion.

**To Reproduce**

1.  Create a CosmosClient with a CosmosConfiguration.
2. Add a new handler to the CosmosConfiguration. 
3. The new handler will not be used in any of the calls. A new CosmosClient must be created in order for it to be added.

```
CosmosConfiguration config = new CosmosConfiguration("accountEndPoint", "key");
CosmosClient client = new CosmosClient(config);
//client will not use the added handler
config.AddCustomHandlers(logHandler);
//client2 will use the new handler. Both clients are pointing to the same configuration instance.
CosmosClient client2 = new CosmosClient(config);
```

**Expected behavior**
The current proposal to fix this issue is to add a CosmosClient builder. 

1. The builder will create each instance of CosmosClient with it's own immutable copy of the CosmosConfiguration. This will prevent any modification after the CosmosClient is created.
2. Remove public access to the CosmosClient constructor that takes a CosmosConfiguration. The builder will create the CosmosConfiguration and the client. The other basic constructor on the CosmosClient will remain to prevent unnecessary complexity for simple projects.

```
CosmosClientBuilder builder = new CosmosClientBuilder("accountEndPoint", "key");
CosmosClient client = builder.Build();

//Only client2 will use the added handler
builder.AddCustomHandlers(logHandler);
CosmosClient client2 = builder.Build();

```

**Comment by kirankumarkolli** [comment]
@j82w lets move forward with PR and commit it. 
Any feedback later we can incorporate it.

**Comment by j82w** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/commit/d08a9c305de8d37fc3b6a9b7ad1efeacd621662d
