### ISSUE TITLE
Querying for fields with non-trailing numbers in the property names throws exception

### ISSUE THREAD

**Issue by kalavany** [Azure/azure-cosmos-dotnet-v3#2201]
When I try to retrieve the results for "select c.props.new_data.field2f from c" using ExecuteQueryAsync, I get an exception with message "cannot recover" from sqlParser.program(). This has to do with the "2f" that's in the property name that i'm querying for in the select clause.

The same query can be used successfully to retrieve the results from azure cosmos db emulator.

**Comment by j82w** [comment]
@timsander1 and @sboshra any suggestions?

**Comment by timsander1** [comment]
+ @bchong95

**Comment by bchong95** [comment]
It looks like an exception leaked from the parser. We need to either fix the grammar file or we can wrap the code in a try catch as a stop gap.
