### ISSUE TITLE
Microsoft.Azure.Cosmos v3.16.0 ReplaceStoredProcedureAsync not working

### ISSUE THREAD

**Issue by yogsgit** [Azure/azure-cosmos-dotnet-v3#2209]
Hello,

I have a piece of C# code that creates or updates a stored procedure.

The code to create a stored procedure with CreateStoredProcedureAsync works as expected.

But ReplaceStoredProcedureAsync is not working. More importantly the method does return a success status code, but the stored procedure body in the container is not updated.

The code is quite straight forward:

StoredProcedureProperties storedProcedureProperties = new StoredProcedureProperties(storedProcedureId, body);

StoredProcedureResponse  storedProcedureResponse = await Container.Scripts.ReplaceStoredProcedureAsync(storedProcedureProperties);

Thanks.

**Comment by j82w** [comment]
@yogsgit please provide the full exception message.

**Comment by yogsgit** [comment]
@j82w  There is no exception. The SDK returns a success status code.

**Comment by j82w** [comment]
@yogsgit if you do a read after the replace does it show the correct version?

**Comment by yogsgit** [comment]
Closing the issue as it seems the issue was with the browser cache not updating properly thus showing the stored procedure body as not updated.

Thanks.
