### ISSUE TITLE
EncryptionContainerExtensions.WithEncryptor fails on v3.16.0

### ISSUE THREAD

**Issue by pentp** [Azure/azure-cosmos-dotnet-v3#2215]
`Attempt by method 'Microsoft.Azure.Cosmos.Encryption.Custom.EncryptionContainer..ctor(Microsoft.Azure.Cosmos.Container, Microsoft.Azure.Cosmos.Encryption.Custom.Encryptor)' to access method 'Microsoft.Azure.Cosmos.CosmosClient.get_ResponseFactory()' failed.`

#1809 removed the `InternalsVisibleTo` attributes for encryption package, [CosmosClient.ResponseFactory](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/770ee191bb2cfcef83d4d1bb3798de66776ada34/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L317) however was made public only for "preview" versions, since v3.16 was released and isn't a preview version anymore it reverted to internal and thus the encryption package fails.

**Comment by j82w** [comment]
3.16 preview was never release because of this issue: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2087. There is a 3.17-preview release currently in progress: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2200 which should be released in the next few days.

**Comment by j82w** [comment]
Please try the 3.17.0-preview: https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.17.0-preview

**Comment by pentp** [comment]
Probably need a new version of `Microsoft.Azure.Cosmos.Encryption` also because `1.0.0-previewV10` fails with `System.TypeLoadException: Method 'GetChangeFeedStreamIterator' in type 'Microsoft.Azure.Cosmos.Encryption.Custom.EncryptionContainer' from assembly 'Microsoft.Azure.Cosmos.Encryption, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.`

**Comment by j82w** [comment]
@pentp please try the [latest encryption nuget](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Encryption/1.0.0-previewV11) with the 3.17.0-preview.

**Comment by pentp** [comment]
Tried it and it works now, got at least MMK encryption working E2E.
