### ISSUE TITLE
TraceWriterBaselineTests.TraceData.xml changes with different machine configured CultureInfo

### ISSUE THREAD

**Issue by kr-santosh** [Azure/azure-cosmos-dotnet-v3#2223]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Executing .\UpdateContracts.ps1 results in changes to TraceWriterBaselineTests.TraceData.xml causing test cases to fail.

**To Reproduce**
execute  .\UpdateContracts.ps1, probably with a different culture setting on your machine. I see here the xml changes
mm/dd/yyyy to dd-mm-yyyy

 ┌──────────────────────┬──────────────────────┬────────────────────────────────────┐
            │Start Time (utc)      │End Time (utc)        │Endpoint                            │
            ├──────────────────────┼──────────────────────┼────────────────────────────────────┤
            │  1/1/0001 12:00:00 AM│12/31/9999 11:59:59 PM│                http://localhost.com│
            │  1/1/0001 12:00:00 AM│12/31/9999 11:59:59 PM│                http://localhost.com│
            └──────────────────────┴──────────────────────┴────────────────────────────────────┘
     -------- Changes to Below format       ┌───────────────────┬───────────────────┬──────────────────────────────────────────┐
            │Start Time (utc)   │End Time (utc)     │Endpoint                                  │
            ├───────────────────┼───────────────────┼──────────────────────────────────────────┤
            │01-01-0001 00:00:00│31-12-9999 23:59:59│                      http://localhost.com│
            │01-01-0001 00:00:00│31-12-9999 23:59:59│                      http://localhost.com│
            └───────────────────┴───────────────────┴──────────────────────────────────────────┘
            Store Response Statistics
              Start Time: 0001-01-01T00:00:00.0000000

**Expected behavior**
Test cases should not fail.

**Actual behavior**
Cosmos Tests fail.

**Comment by j82w** [comment]
@sboshra and @bchong95 please take a look.
