### ISSUE TITLE
Document DB and Gremlin, broken compatibility

### ISSUE THREAD

**Issue by sanchez** [Azure/azure-cosmos-dotnet-v3#2231]
**Describe the bug**
Previously I have been using Cosmos with the Gremlin API to read and write data. My typical workflow has consisted with using Gremlin and Gremlin libraries to interface through the Gremlin endpoint and query/read data, and then use the Document Library to upload data. Following a couple of articles and my own exploration I have been able to successfully upload data through the use of the Document Library. This has worked perfected and resulted in great performance benefits for the last couple of months, however I have started noticing today that all uploading through the use of the Document Library are returning 503 errors, I am still attempting to upload in the same format.

**To Reproduce**
1. Create a Cosmos Database with the Gremlin API
2. Use the Document Library to upload data into the database
3. Cry as the error just repeatedly gets thrown at you

**Expected behavior**
The data should just happily be accepted by the system and all data be queryable by Gremlin

**Actual behavior**
The exception is thrown and none of the data being uploaded is accepted

**Environment summary**
SDK Version: Originally 3.14.0, Error also happens with 3.16.0
OS Version: Windows, also tested within a Linux Container

**Additional context**
The Exception that occurs is `System.AggregateException` with the following message:
```
'!application/vnd.gremlin-v2.0+json{"requestId":"c0f806d3-20fd-4866-a3da-93718ccd8d28","op":"eval","processor":"","args":{"gremlin":"g.V().hasLa)'
```

Call Stack:
```
This exception was originally thrown at this call stack:
	Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
	Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.ProcessMessage<T>(Microsoft.Azure.Cosmos.ResponseMessage, System.Func<Microsoft.Azure.Cosmos.ResponseMessage, T>)
	Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.CreateItemResponse<T>(Microsoft.Azure.Cosmos.ResponseMessage)
	Microsoft.Azure.Cosmos.ContainerCore.CreateItemAsync<T>(Microsoft.Azure.Cosmos.CosmosDiagnosticsContext, T, Microsoft.Azure.Cosmos.Tracing.ITrace, Microsoft.Azure.Cosmos.PartitionKey?, Microsoft.Azure.Cosmos.ItemRequestOptions, System.Threading.CancellationToken)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
	Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync<TResult>(Microsoft.Azure.Cosmos.CosmosDiagnosticsContext, Microsoft.Azure.Cosmos.Tracing.ITrace, System.Func<Microsoft.Azure.Cosmos.CosmosDiagnosticsContext, Microsoft.Azure.Cosmos.Tracing.ITrace, System.Threading.Tasks.Task<TResult>>)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    ...
    [Call Stack Truncated]
```

**Comment by j82w** [comment]
@sanchez this appears to be an issue with the service, and not the SDK. Please [contact support](https://aka.ms/azure-support).

**Comment by sanchez** [comment]
Hi thanks for the reply, I managed to do some more troubleshooting and I believe the issue was occuring because of a MITM HTTPS cert manager installed in our company internet. Not sure if it would be possible to detect that sort of thing and provide a better error message within the library or not. Thanks
