### ISSUE TITLE
Remove DefaultTraceListener 

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2238]
DefaultTraceListener causes lock contention and unnecessary overhead for production environments in most cases. This issue is to track removing it by default for the v3 SDK. The CosmosDiagnostics includes most of the necessary information. Testing should be done to verify that customer can enable it if necessary and to document the process.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/fca18fbad82d466dc9ba9ef166cda2917e32284e/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L640

**Comment by ealsur** [comment]
DefaultTraceListener is not enabled by the SDK, it is enabled by default to all NETFX applications. 

Also it's enabled when running in Debug in VS (https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.defaulttracelistener?view=netframework-4.8#remarks).

NET 5 might also have this (not sure as I have not used it).

We can advise in our perf guides to disable it, but we cannot forcefully change this behavior as far as I know.
