### ISSUE TITLE
Frequent page queries cause memory leaks 

### ISSUE THREAD

**Issue by LiDamon** [Azure/azure-cosmos-dotnet-v3#2254]
I used JMeter test my site and there are 10 users on my site, which are query every 2 seconds .The memory always increase .

![Memory Leak](https://user-images.githubusercontent.com/3748285/109135234-d0ae9e00-7791-11eb-8fb5-f4766dea8df7.png)

**Environment summary** 
SDK Version:3.16.0
OS Version Windows
.NET Version:4.7.2

**Comment by j82w** [comment]
@LiDamon can you share the code on how you are draining the query? Are you disposing of the FeedIterator? Does this reproduce with 3.17.0-preview?

**Comment by LiDamon** [comment]
This is my code
![Cosmos code](https://user-images.githubusercontent.com/3748285/109239177-d2b74200-780f-11eb-8fe8-6aa586154dca.png)

I will test 3.17.0-preview

**Comment by j82w** [comment]
1.  ResponseMessage is disposable, but based on the current code it is never disposed of.
2. What is the reason for using the Task.Run? It shouldn't be necessary.
3. Is there any reason you don't use a CancellationToken instead of doing a Task.Wait?

```c#
using CancellationTokenSource cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromMinutes(10));
using FeedIterator iterator = container.GetItemQueryStreamIterator(queryText);
while (iterator.HasMoreResults)
{
       using ResponseMessage response = await iterator.ReadNextAsync(cancellationTokenSource.Token);
       // Check status code and 
}
```

**Comment by LiDamon** [comment]
Use Task.Run because  Asp.Net Framework call async method may be hang.
https://stackoverflow.com/questions/14526377/why-does-this-async-action-hang

I upgrade sdk to 3.17 and memory leak issue always exists.

I changed my code below to:
```
           CosmosClientOptions options = new CosmosClientOptions
            {
                AllowBulkExecution = true,
                ConnectionMode = ConnectionMode.Direct,
                MaxRetryAttemptsOnRateLimitedRequests = 19,
                MaxRetryWaitTimeOnRateLimitedRequests = TimeSpan.FromMinutes(3),
                EnableContentResponseOnWrite = false,
                IdleTcpConnectionTimeout = TimeSpan.FromMinutes(30),
                PortReuseMode = PortReuseMode.PrivatePortPool
            };
            var client = new CosmosClient(key, options);
            var container = client.GetContainer(db, containerName);
            var requestOptions = new QueryRequestOptions { MaxConcurrency = 100000, MaxBufferedItemCount = 100, MaxItemCount = 20 };
            string token = null;
            var queryTask = Task.Run(async () =>
            {
                var query = new QueryDefinition(queryText);
                using (CancellationTokenSource cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromMinutes(10)))
                {
                    using (var queryIterator = container.GetItemQueryStreamIterator(query, token, requestOptions))
                    {
                        while (queryIterator.HasMoreResults)
                        {
                            using (var response = await queryIterator.ReadNextAsync())
                            {
                                if (response.IsSuccessStatusCode)
                                {
                                    token = response.Headers.ContinuationToken;
                                    //....
                                }
                                else
                                {
                                }
                            }
                            break;
                        }
                    }
                }
            });
            queryTask.Wait();
```

BTW, we also have performance issue, slowly position is "Get Container Properties". the diagnostics file :



[json.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/6080391/json.zip)

**Comment by j82w** [comment]
The CosmosClient needs to be a [singleton](https://docs.microsoft.com/azure/cosmos-db/performance-tips-dotnet-sdk-v3-sql#sdk-usage). The client has several caches that get warmed up on the first operation which includes getting the container properties. You can use the new [CosmosClient.CreateAndInitialize](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/73b5da22400c4fc58e76ff08751c4f6e283c22b7/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L297) factory to avoid that additional latency on the first operation. Looking at the diagnostics provided there is at least 10 CosmosClient instances. The fact the CosmosClient is not getting disposed of is the cause of the memory leak.

**Comment by LiDamon** [comment]
@j82w   thank you very much , I fixed the issue .
