### ISSUE TITLE
Question: Approx SDK v4 release schedule

### ISSUE THREAD

**Issue by andrew-tevent** [Azure/azure-cosmos-dotnet-v3#2273]
Hi

Should I be using the v4 SDK for new projects - what's an approximate timeline for it coming out of preview?   Is it aligned with the .Net 6 release in November, or will it be sooner?  (apologies to be re-asking #1370)

It would be useful to know so that I can choose between v4 and v3.   I will go with v4 if it is shortly to come out of preview, but if there is any doubt and the v3 is better supported then I will choose that.

Thanks!

**Comment by j82w** [comment]
Please use the v3 SDK for all new development. The v4 is still does not have any hard dates.
