### ISSUE TITLE
Add CosmosClient.IsEmulator property

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-cosmos-dotnet-v3#2277]
We need to be able to tell if the client is working against the emulator or not, especially consistency level of the emulator is usually "session" which makes all "strong" consistencies fail. with CosmosClient.IsEmulator we can do things properly

**Comment by j82w** [comment]
Hi @MhAllan ,

The SDK team as looked doing this before, and it's not something easy to implement. There is no way for the SDK to determine if it is an emulator or production. The emulator allows users to change passwords, set the endpoint, and run on remote machines. The responses are the same as production. It would require modifying the emulator to add a new header or something to the account, and then adding code to all the SDKs to understand it.

As a work around can you not use [CosmosClient.ReadAccount](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8ac123e1e726196889f88f5fb00049737c45e64a/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L495) to check the [consistency](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8ac123e1e726196889f88f5fb00049737c45e64a/Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs#L194)?  You can also use emulator[ command line arguments](https://docs.microsoft.com/en-us/azure/cosmos-db/emulator-command-line-parameters#command-line) to set the consistency to strong to match your production.

**Comment by MhAllan** [comment]
Thank you for answering @j82w

**Comment by ealsur** [comment]
As @j82w mentioned, there is no easy way to identify the emulator, users can deploy it on VMs, have different routing, the connection can be anything, so we cannot detect it.
