### ISSUE TITLE
Disambiguate 404 & 404 with (owner not found)

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#229]
**Describe the bug**
For non-existing containers or databases, even Item operations return 404 status code. 
404 is ambiguous between if its real Item NotFound or parent not exists. 

424 can be used to disambiguate it. 

Please check #227 for correlated context

**To Reproduce**
```C#
CosmosContainer cosmosContainer; // Create with Random GUID

CosmosResponseMessage response = await cosmosContainer.Items.ReadItemStreamAsync(CosmosContainerSettings.NonePartitionKeyValue, "id1");
```

**Expected behavior**
```C#
Assert.AreEqual(424, response.StatusCode);
```

**Actual behavior**
```C#
Assert.AreEqual(HttpStatusCode.NotFound, response.StatusCode);
```

**Environment summary**
SDK Version: 3.0.0.10-preview

- [x] Breaking change

**Comment by j82w** [comment]
While 424 does appear to be the correct http status code it is not supported by c# [HttpStatusCodes](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=netframework-4.8).

1. Create a Cosmos status code type that extends HttpStatusCode
2. Continue using 404 and add a substatus code to differentiate

**Comment by kirankumarkolli** [comment]
HttpsStatusCode vs CosmosStatusCode

**Comment by kirankumarkolli** [comment]
Needs investigation
- What does Cosmos Gateway return
- What are the patterns used by other popular data services (Azure & across).

**Comment by MovGP0** [comment]
@j82w using a subcode like 404.1 would work, but is not normative. So 424 should be used. 

Maybe it's best to expand the HttpStatusCodes Type in the ASP.NET project.

**Comment by linus-rylander** [comment]
@kirankumarkolli, are there any updates on this issue?

In the meanwhile, is there currently any way to determine if a CosmosException with status code 404/NotFound is thrown because the container provided doesn't exist or the document you are trying to delete doesn't exist (for example)? In our scenario the latter case should be seen as successful while the first shouldn't and therefore stop further processing.

**Comment by ealsur** [comment]
404/1003 is the combination of status code and substatus code when the owner resource doesn't exist
