### ISSUE TITLE
Setting AllowBulkExecution to true is throwing error

### ISSUE THREAD

**Issue by rajeevramadugu** [Azure/azure-cosmos-dotnet-v3#2292]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Setting AllowBulkExecution to true in CosmosClientOptions is throwing "**_DocDBTrace Error: 0 : Exception during BatchAsyncBatcher: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>_** "

**To Reproduce**
```
protected virtual CosmosClient _cosmosClient
    {
        get
        {
            var options = new CosmosClientOptions
            {
                SerializerOptions = new CosmosSerializationOptions
                {
                    IgnoreNullValues = true,
                    PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
                },
                AllowBulkExecution = true
            };

            return new CosmosClient(_connectionString, options);
        }
    }
    protected Container _cosmosContainer
    {
        get => _cosmosClient.GetContainer(_databaseId, _containerId);
    }
protected async Task<T> CreateItemAsync<T>(string id, T model, PartitionKey partitionKey)
        {
            try
            {
                return await _cosmosContainer.CreateItemAsync(model, partitionKey);
            }
            catch (CosmosException ex)
            {
                LogCosmosDbError(ex);

                throw;
            }
        }
```

**Error log**

_DocDBTrace Error: 0 : 'Test.Api.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.4\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.Api.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.4\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception during BatchAsyncBatcher: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Cosmos.Serialization.HybridRow.Result> Microsoft.Azure.Cosmos.Serialization.HybridRow.RecordIO.RecordIOStream.ReadRecordIOAsync(System.IO.Stream, System.Func`2<System.ReadOnlyMemory`1<Byte>,Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>, System.Func`2<System.ReadOnlyMemory`1<Byte>,Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>, Microsoft.Azure.Cosmos.Serialization.HybridRow.MemorySpanResizer`1<Byte>)'.
   at Microsoft.Azure.Cosmos.TransactionalBatchResponse.PopulateFromContentAsync(Stream content, ResponseMessage responseMessage, ServerBatchRequest serverRequest, CosmosSerializerCore serializer, ITrace trace, Boolean shouldPromoteOperationStatus)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.TransactionalBatchResponse.PopulateFromContentAsync(Stream content, ResponseMessage responseMessage, ServerBatchRequest serverRequest, CosmosSerializerCore serializer, ITrace trace, Boolean shouldPromoteOperationStatus)
   at Microsoft.Azure.Cosmos.TransactionalBatchResponse.FromResponseMessageAsync(ResponseMessage responseMessage, ServerBatchRequest serverRequest, CosmosSerializerCore serializer, Boolean shouldPromoteOperationStatus, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.BatchAsyncContainerExecutor.ExecuteAsync(PartitionKeyRangeServerBatchRequest serverRequest, ITrace trace,_ 

**Environment summary**
SDK Version: .net core 5.0 and azure 3.17 sdk
OS Version : Windows 10

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by rajeevramadugu** [comment]
@ealsur ,
I cleaned up bin folder and rebuild solution. Getting same error. Please advise.

**Comment by ealsur** [comment]
Can you provide a CSPROJ that can repro the scenario? We run the SDK in our continuous integration tests, using NET Core 3.1 LTS, and we are not seeing this issue.

The only difference might be NET 5.0.4.

**Comment by rajeevramadugu** [comment]
I was able to fix issue using this procedure. In Console app with AllowBulkExecution to true, it worked. I was getting this error in API. I copied "Microsoft.Azure.Cosmos.Serialization.HybridRow.dll" from bin directory of console app and replaced in bin directory of WebApi, then it worked. Looks like some older version of "Microsoft.Azure.Cosmos.Serialization.HybridRow.dll" is getting copied in WebApi.

**Comment by ealsur** [comment]
Could your web api project depend on another project/library that might have an older version dependency? 

Based on your comment, this sounds more like a .NET build dependency resolution issue, not particularly related to the SDK itself (as you verified with a simple console application).

**Comment by rajeevramadugu** [comment]
Looks like some dependency issue.

**Comment by mxavierciandt** [comment]
I'm facing the same issue. I have some methods on my base repository to do some batch operations on Cosmos DB, they are like that:

       public async Task AddRangeAsync(List<T> entities)
        {
            var container = _cosmosDbClientFactory.GetContainer(CollectionName);
            var entitiesList = entities.Split(_maxItemsPerBatch).ToList();

            foreach (var items in entitiesList)
            {
                var partitionKey = ResolvePartitionKey(items.FirstOrDefault());
                var transactionalBatch = container.CreateTransactionalBatch(partitionKey);

                items.ToList().ForEach(item => transactionalBatch.CreateItem(item));

                var result = await transactionalBatch.ExecuteAsync();

                if (!result.IsSuccessStatusCode)
                {
                    throw new CosmosDbBatchOperationException(result.ErrorMessage);
                }
            }
        }

Today I migrated the dotnet version of my project, from dotnet 3.1 to 5, after that I'm getting this error:

> System.MissingMethodException : Method not found: 'System.Threading.Tasks.Task1<Microsoft.Azure.Cosmos.Serialization.HybridRow.Result> Microsoft.Azure.Cosmos.Serialization.HybridRow.RecordIO.RecordIOStream.ReadRecordIOAsync(System.IO.Stream, System.Func2<System.ReadOnlyMemory1<Byte>,Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>, System.Func2<System.ReadOnlyMemory1<Byte>,Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>, Microsoft.Azure.Cosmos.Serialization.HybridRow.MemorySpanResizer1)'.

This occurs in this line:
`var result = await transactionalBatch.ExecuteAsync();`

Version Info:
- Microsoft.Azure.Cosmos on v3.17.0
- Dotnet 5.0.201

Somebody knows how to solve this?

**Comment by MatheusXavier** [comment]
I'm facing the same issue. I have some methods on my base repository to do some batch operations on Cosmos DB, they are like that:

       public async Task AddRangeAsync(List<T> entities)
        {
            var container = _cosmosDbClientFactory.GetContainer(CollectionName);
            var entitiesList = entities.Split(_maxItemsPerBatch).ToList();

            foreach (var items in entitiesList)
            {
                var partitionKey = ResolvePartitionKey(items.FirstOrDefault());
                var transactionalBatch = container.CreateTransactionalBatch(partitionKey);

                items.ToList().ForEach(item => transactionalBatch.CreateItem(item));

                var result = await transactionalBatch.ExecuteAsync();

                if (!result.IsSuccessStatusCode)
                {
                    throw new CosmosDbBatchOperationException(result.ErrorMessage);
                }
            }
        }

Today I migrated the dotnet version of my project, from dotnet 3.1 to 5, after that I'm getting this error:

> System.MissingMethodException : Method not found: 'System.Threading.Tasks.Task1<Microsoft.Azure.Cosmos.Serialization.HybridRow.Result> Microsoft.Azure.Cosmos.Serialization.HybridRow.RecordIO.RecordIOStream.ReadRecordIOAsync(System.IO.Stream, System.Func2<System.ReadOnlyMemory1<Byte>,Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>, System.Func2<System.ReadOnlyMemory1<Byte>,Microsoft.Azure.Cosmos.Serialization.HybridRow.Result>, Microsoft.Azure.Cosmos.Serialization.HybridRow.MemorySpanResizer1)'.

This occurs in this line:
`var result = await transactionalBatch.ExecuteAsync();`

Version Info:
- Microsoft.Azure.Cosmos on v3.17.0
- Dotnet 5.0.201

Somebody knows how to solve this?

**Comment by j82w** [comment]
@MatheusXavier it might be better to create a new issue. 

1. Do a clean and build. Verify that the bin and obj folders are clean. It's possible that some old file is not getting updated..
2. If you have multiple projects are they all referencing the same version of the SDK?

**Comment by ealsur** [comment]
@MatheusXavier the OP confirmed the issue was related to DLL mismatch (basically project references with different SDK versions generating a deployment where versions mismatched).

Please go through the same points discussed in this thread.

**Comment by rajeevramadugu** [comment]
@MatheusXavier ,
I had similar issue when I was using Microsoft.Azure.Cosmos 3.17 and AspNetCore.HealthChecks.CosmosDb 5.0.3. I had to downgrade AspNetCore.HealthChecks.CosmosDb to 3.x, and bin folder has now correct Microsoft.Azure.Cosmos.Serialization.HybridRow.dll version. You might be having conflicting dll issue too.
cc: @ealsur

**Comment by MatheusXavier** [comment]
I've checked all my projects and they are referecing the same sdk version, so I cleaned my solution and deleted all obj and bin folders and tried again but it didn't work.
Then I tried @rajeevramadugu solution. Because I was using **Microsoft.Azure.Cosmos 3.17.0** with **AspNetCore.HealthChecks.CosmosDb 5.0.3**, so I downgraded **AspNetCore.HealthChecks.CosmosDb** to version **3.1.2** and it worked.
