### ISSUE TITLE
Cosmos: "throughputProperties" Parameter  is incorrectly described as optional 

### ISSUE THREAD

**Issue by roboz0r** [Azure/azure-cosmos-dotnet-v3#2295]
"throughputProperties" Parameter  is incorrectly described as optional 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e96ea8-0b8f-fde0-77a0-743baefcd6c3
* Version Independent ID: 01c62957-c210-85c7-3260-e81328d20a1d
* Content: [Database.CreateContainerIfNotExistsAsync Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.database.createcontainerifnotexistsasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Database.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Database.xml)
* Service: **cosmos-db**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by ealsur** [comment]
@roboz0r the parameter is optional, if you created a Database with provisional throughput, you can create containers without specifying their throughput
