### ISSUE TITLE
Any estimate when v.3 should go to production?

### ISSUE THREAD

**Issue by codefactorydevelopment** [Azure/azure-cosmos-dotnet-v3#23]
I haven't seen this info anywhere and as i am starting new project, i'm trying to see best decision about should i go with 2.2.1. until v.3 goes production or maybe starting with it right away if its close.

So, any known plans?

thanks

**Comment by codefactorydevelopment** [comment]
Found some info here:
https://azure.microsoft.com/en-us/blog/azure-cosmos-dotnet-sdk-version-3-0-now-in-public-preview/

> ...we recommend folks continue to use version 2.x of our .NET SDK for production workloads. We have no immediate plans at this time to deprecate or discontinue support for version 2.x of the .NET SDK.

so i guess this issue can be closed.

**Comment by j82w** [comment]
Hi @codefactorydevelopment ,

We are planning to go GA in the first half of 2019. We can't give a specific date as the amount of work that will need to be done will change on the feedback, and feature requests we get during the preview.
