### ISSUE TITLE
Annotation to indexing policy doesn't roundtrip 

### ISSUE THREAD

**Issue by jayantacs** [Azure/azure-cosmos-dotnet-v3#2305]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2252/files

Due to the change the annotation doesn't roundtrip well. If you read ContainerProperties of container (whose annotation is null) and use to replace another container's property -- the backend call fails. 

A fix could be to not serialize the annotation if it's null. 

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

Database database = await client.CreateDatabaseAsync(DatabaseName);
Container container = db.CreateContainerAsync(
                new InteropContainerProperties(containerName, "/pksrc"),
                ThroughputProperties.CreateManualThroughput(2000));
InteropContainerProperties newContainerProperties = await InteropContainerProperties.ReadAsync(await sourceContainer.ReadContainerStreamAsync()); await container.ReplaceContainerAsync(newContainerProperties);

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
@jayantacs that has the INTERNAL preprocessor flag which is only set for internal project that are using the SDK. The property won't be included in any public SDK nugets. 

@bemill can you please take a look at this?
