### ISSUE TITLE
[Internal] Adding Client Telemetry

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#2323]
**Is your feature request related to a problem? Please describe.**
Client requested for request charge API for CosmosException (ref. https://github.com/Azure/azure-sdk-for-java/issues/13488) 

**Describe the solution you'd like**
Develop a telemetry module which collects and save certain kind of metrics periodically. It is already developed for Java SDK (ref. https://github.com/Azure/azure-sdk-for-java/pull/16822) and need to be implemented for .net SDK also.

**Describe alternatives you've considered**
There is no alternative for this.

**Additional context**
Default client telemetry capturing is off (User can turn on via builder API)

It contains below aggregations
- Document CRUD
- Query operation
- CPU Memory Information
- Metadata cache refresh
- Rntbd connection data points

SDK will collect and store below information
```
timeStamp | Time of capture
clientId | Unique client identifier
processId | host machine identifier
userAgent | User agent container SDK and machine OS version
connectionMode | Direct Vs Gateway
globalDatabaseAccountName | User account name
applicationRegion | User host region if in azure
hostEnvInfo | Host machine information
acceleratedNetworking | If azure vm with accelerated networking
systemInfo | CPU/Memory/Rntbd connection Info
cacheRefreshInfo | Client cache refresh information
operationInfo | CRUD/Query operation aggregation information
```

JSON would look like this :
![image](https://user-images.githubusercontent.com/6362382/111777956-faaf3800-88d9-11eb-80d6-2d7ab66114d4.png)
![image](https://user-images.githubusercontent.com/6362382/111777983-06026380-88da-11eb-8d77-c5838c502070.png)
![image](https://user-images.githubusercontent.com/6362382/111778119-321de480-88da-11eb-8768-fcd13b627e9f.png)
![image](https://user-images.githubusercontent.com/6362382/111778137-3813c580-88da-11eb-9298-4ec8138d3482.png)

**Comment by j82w** [comment]
Can you provide an example with values for the information being sent back?

TIMESTAMP
HostEnvInfo // What information is  included in this?
AcceleratedNetworking // How can this be detected? 
GreaterThan1Kb // Is this a percentage? Count? Bool? Is it for both request and responses?
Consistency // Is the SDK consistency? Is it null if they just use the account default?

// Is this all for latency?
MetricsName
UnitName
Count
Mean
Min
Max
Percentile50
Percentile   90
Percentile   95
Percentile   99
Percentile   999
JsonColumn

**Comment by sourabh1007** [comment]
> > Client requested for request charge API for CosmosException (ref. [Azure/azure-sdk-for-java#13488](https://github.com/Azure/azure-sdk-for-java/issues/13488))
> 
> This is already done in the .NET SDK:
> 
> https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f16153b98627890f3328b3c4b3d2d3c2265f22cf/Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs#L97
> 
> Can you provide an example with values for the information being sent back?
> 
> HostEnvInfo // What information is included in this?
> AcceleratedNetworking // How can this be detected?
> GreaterThan1Kb // Is this a percentage? Count? Bool? Is it for both request and responses?
> Consistency // Is the SDK consistency? Is it null if they just use the account default?
> 
> // Is this all for latency?
> MetricsName
> UnitName
> Count
> Mean
> Min
> Max
> Percentile50
> Percentile 90
> Percentile 95
> Percentile 99
> Percentile 999
> JsonColumn

**Comment by sourabh1007** [comment]
I have updated the schema in the main issue along with sample JSON.

**Comment by kirankumarkolli** [comment]
Few clarifications on the wire format
1. Nesting percentiles: Why are they nested?
2. Greaterthan1KB: won't making it a text-histogram be more useful? Or in other words what scenarios would boolean address.
3. RegionsContacted: will per region be a better alternative? (Like what % requests routed to other regions)

Eventually do client expected to post metrics to the current one in PreferredList configured?

**Comment by sourabh1007** [comment]
1. It represents out of 100 requests, how many requests took under how much time. e.g.
99.9: 63.93
90.0: 39.18
95.0: 63.93
99.0: 63.93
It means, 99.9 requests took less 63.93 sec to get processed. 90.0 requests took less than 39.19 sec and so on.
That's why they are nested.
2. This particular field was requested from "Monitoring Team". They just wanted to know if response size was less than 1kb or not. 
3. Here we will just provide the information about the region contacted. Any kind of analytics can be done on kustos as this information will be available in Kustos.
