### ISSUE TITLE
Documentation related to SDK detailed implementation

### ISSUE THREAD

**Issue by YohanSciubukgian** [Azure/azure-cosmos-dotnet-v3#2325]
**Is your feature request related to a problem? Please describe.**
Do you have any documentation (with schemas?) that describe behaviors of the SDK regarding its detailed implementation ?

I would like to understand impact on the SDK logic when setting XX or YY configuration on clients in order to fine tune as much as possible the right client/query configuration.
I saw that there is already many documentations on the SDK but I didn't see any deep detailed implementation documentation that clearly state about number of roundtrip & RU implication based on the new preemption logic described in the following PR https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2229
It was also interesting to see that different Cosmos SDK (on different stacks) could have different implementation logic.

**Describe the solution you'd like**
It could be great if the documentation could cover the number of roundtrip (which could imply latency) & RU implication based on the kind of query we are querying in relation to any/all of these :
 - Aggregation or not
 - Group by or not
 - PartitionKey set or not
 - Gateway vs Direct calls
 - MaxBufferedItemCount
 - MaxConcurrency 
 - etc...

**Comment by j82w** [comment]
The current performance guidelines are here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-query-metrics

@timsander1 can you please take a look?

**Comment by timsander1** [comment]
Sharing docs on query pagination here: https://docs.microsoft.com/azure/cosmos-db/sql-query-pagination.

There are a few reasons why query execution could be split across multiple pages:

- The container was throttled and there weren't available RUs to return more query results
- The query execution's response was too large
- The query execution's time was too long
- It was more efficient for the query engine to return results in additional executions

When running queries, we recommend following the pagination best practices [here](https://docs.microsoft.com/azure/cosmos-db/sql-query-pagination#handling-multiple-pages-of-results). For query with aggregates (GROUP BY or not), we'll show the results on the final pages. This means that some long-running aggregate queries may return empty pages before query completion. 

Sharing some docs on [MaxBufferedItemCount and MaxConcurrency](https://docs.microsoft.com/azure/cosmos-db/troubleshoot-query-performance#optimizations-that-reduce-query-latency). If you have a container with a high number of physical partitions, you can set MaxConcurrency to improve latency quite a bit.

**Comment by YohanSciubukgian** [comment]
@j82w, @timsander1 Thanks for your quick answers.
It's also about having tradeoffs highlighted in the documentation.

AFAIU, some issues raised are talking about limitations/workarounds based on the behavior of the 'SDK/Cosmos Server' but there is no documentation that highlight these tradeoffs, such as when choosing parallelism vs sequential for each query.
ex: if parallelism is being chosen for the query, multiple queries might be sent to the server in parallel without knowing if a single query could have been enough to fil the need. 
In that case the tradeoff is between the 'goblal execution time' of the query VS 'the number of RU' used (wasted) due to the parallelism configured.
If the reconciliation was done on server side, we could have not used that much RUs (or it could have been invisible to us, users) but for now as it's on SDK side & we have control over the configuration (which is a good thing) we need to fully understand that kind of tradeoffs to properly configure the SDK and avoid wasting ExecutionTime or RU depending on our needs.

https://github.com/microsoft/fhir-server/pull/1757#pullrequestreview-618820203
> There is therefore a significant downside to selecting parallelism when a search is not selective: we will be discarding results after having incurred the request charge to fetch them. So we want to select parallelism only when we are pretty confident that it is the right thing to do for the query.


The section in your documentation in talking about performance on the query but not on the tradeoff.
> Increase MaxConcurrency
Parallel queries work by querying multiple partitions in parallel. But data from an individual partitioned collection is fetched serially with respect to the query. So, if you set MaxConcurrency to the number of partitions, you have the best chance of achieving the most performant query, provided all other system conditions remain the same. If you don't know the number of partitions, you can set MaxConcurrency (or MaxDegreesOfParallelism in older SDK versions) to a high number. The system will choose the minimum (number of partitions, user provided input) as the maximum degree of parallelism.

By reading the documentation I guess that It could be implicitly understood but as it's, at the end of the day, a tradeoff between performance vs money (if too many queries were performed to get the result of the query), I think it should be highlighted to prevent any unwanted behavior and any surprise at the end of the month.

Except for query parallelized, is there any other tradeoff that should be known to fine tune the SDK behavior on other topics like 'Gateway vs Direct calls' ?
