### ISSUE TITLE
ReadMany API

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2326]
This is port the ReadMany API implemented by Java SDK. This API allows users to efficiently read many items from the container. This can be done via query and/or batch currently but makes the process complex and is not user friendly.

Suggested APIs

### 1. Single page response
Pros: It's easier to use. No complex pulling model. No users forgetting to do the HasMoreResult loop.
Cons: Stream response would need a way to join streams from multiple responses.
```c#
class Container
{
     public FeedResponse<T> ReadManyAsync(
          IReadonlyList<(string, PartitionKey)> items,
          RequestOptions requestOptions,
          CancellationToken cancellationToken);

     public ResponseMessage ReadManyStreamAsync(
          IReadonlyList<(string, PartitionKey)> items,
          RequestOptions requestOptions,
          CancellationToken cancellationToken);
}
```
### 2. Multiple page responses
Pros: Follows the same model as query and other multiple page responses
Cons: Requires users to combine the results from multiple pages and know to do the HasMoreResult to fully drain the results
```c#
class Container
{
     public FeedIterator<T> ReadManyAsync(
          IReadonlyList<(string, PartitionKey)> items,
          RequestOptions requestOptions,
          CancellationToken cancellationToken);

     public FeedIterator ReadManyStreamAsync(
          IReadonlyList<(string, PartitionKey)> items,
          RequestOptions requestOptions,
          CancellationToken cancellationToken);
}
```

Java PR: https://github.com/Azure/azure-sdk-for-java/pull/8123

Implementation it will use Query under the covers to provide the functionality. This follows the current Java implementation.

**Comment by abhijitpai** [comment]
Shouldn't this follow a FeedIterator based model to get paginated results if too many items are requested for?

**Comment by j82w** [comment]
Good point, I'll update it to be an iterator.

**Comment by j82w** [comment]
@kirankumarkolli, @asketagarwal, @ealsur, @FabianMeiswinkel  what are your opinions of the two models?

**Comment by asketagarwal** [comment]
As per latest discussion, we have decided to go ahead with the first option (Single Page response) as we think it will be easier for our customers to use. We need to optimize on joining multiple stream responses.

```c#
class Container
{
     public FeedResponse<T> ReadManyAsync(
          IReadonlyList<(string, PartitionKey)> items,
          ReadManyRequestOptions requestOptions,
          CancellationToken cancellationToken);

     public ResponseMessage ReadManyStreamAsync(
          IReadonlyList<(string, PartitionKey)> items,
          ReadManyRequestOptions requestOptions,
          CancellationToken cancellationToken);
}
```

ReadManyRequestOptions is an overload of RequestOptions with sessiontoken and consistency options.

**Comment by j82w** [comment]
closed with https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2352
