### ISSUE TITLE
ApplicationRegion parameter does not work with output from ARM

### ISSUE THREAD

**Issue by sebader** [Azure/azure-cosmos-dotnet-v3#2330]
**Describe the bug**
I have a compute resource in Azure, lets say an AKS cluster. Doesn't really matter which one since the problem is the same across multiple services:

In my deployment pipeline I run a CLI command to retrieve the region, for instance:
`az aks show --resource-group my-rg -n mycluster --query "location" --output tsv`

This outputs something like `northeurope` or `eastus2`. This seems consistent across many Azure resources.

Now, I want to use that output to feed into an app setting which I then want to use to configure my Cosmos DB client with ApplicationRegion:

```
CosmosClientBuilder clientBuilder = new CosmosClientBuilder(SysConfig.CosmosEndpointUri, SysConfig.CosmosPrimaryKey);
var builderOptions = clientBuilder.WithApplicationRegion(Environment.GetEnvironmentVariable("AZURE_REGION"));
```

Turns out, you can't. Because the SDK wants `North Europe` or `East US 2`. I don't see any way how to programmatically split this up

**To Reproduce**
See above.

**Expected behavior**
The SDK should accept standard naming input for Azure regions like `northeurope`.

**Actual behavior**
See above.
![image](https://user-images.githubusercontent.com/11445087/112164699-62bd9100-8bee-11eb-9904-e4904e5e27c1.png)

**Environment summary**
SDK Version: 3.14.0

**Comment by ealsur** [comment]
@sebader Locations have a Name and a DisplayName property, you should be able to use the DisplayName property without issues.

**Comment by sebader** [comment]
@ealsur where do you mean? The CLI output only has one field. and `WithApplicationRegion()` expects only one string which seems to be the DisplayName

**Comment by ealsur** [comment]
Azure CLI modules differ from resource type to resource type, so maybe the aks implementation is different, but ARM locations have Name, DisplayName and other attributes.

If you run `az account list-locations`, it will list all regions available in that cloud, for example:

```
{
    "displayName": "East US",
    "id": "/subscriptions/81cb9df9-8726-4ad7-a878-8385e15c6c4e/locations/eastus",
    "metadata": {
      "geographyGroup": "US",
      "latitude": "37.3719",
      "longitude": "-79.8164",
      "pairedRegion": [
        {
          "id": "/subscriptions/81cb9df9-8726-4ad7-a878-8385e15c6c4e/locations/westus",
          "name": "westus",
          "subscriptionId": null
        }
      ],
      "physicalLocation": "Virginia",
      "regionCategory": "Recommended",
      "regionType": "Physical"
    },
    "name": "eastus",
    "regionalDisplayName": "(US) East US",
    "subscriptionId": null
  },
```

That is the ARM location information. And the `displayName` property matches what is expected on the SDK input.

**Comment by sebader** [comment]
Well, I have worked around it by now using a different way, but for future reference, you can make it like this from AKS...

```
az account list-locations --query "[?name == '$(az aks show -g my-rg -n my-aks --query "location" -o tsv)'].displayName" -o tsv
```

sample ==> `East US`

Do I really like that? TBH, no. That's why I would like to have it as a feature inside the SDK to ideally take either as input: name or displayName

**Comment by ealsur** [comment]
@sebader I agree, and personally I thought all Azure services used the same Location information, after all, it's ARM data. The fact that aks is just returning the `name` is unexpected.

Supporting the `name` and `displayName` sounds valid as a feature thought.

**Comment by sebader** [comment]
It actually seems like every service/RP is doing it differently. Probably not even ARM doing it

Just a few examples:
![image](https://user-images.githubusercontent.com/11445087/112340366-c1ebd600-8cc0-11eb-9132-bf7e880585c9.png)

**Comment by ealsur** [comment]
@sebader the beautiful land of Resource Provider independent implementations

**Comment by sebader** [comment]
so I guess the feature should actually be "support name or displayName in all-lowercase" :D

**Comment by j82w** [comment]
@ealsur do you see any reason why we shouldn't add a normalization logic to the locations names to prevent this issue?

**Comment by ealsur** [comment]
Nope, assuming all regions can be normalized the same way.

When listing the Azure regions in the public cloud, there are cases where a "remove spaces, lowercase" does not apply, for example:

```
{
    "displayName": "United Kingdom",
    "id": "/subscriptions/81cb9df9-8726-4ad7-a878-8385e15c6c4e/locations/uk",
    "metadata": {
      "geographyGroup": null,
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionCategory": "Other",
      "regionType": "Logical"
    },
    "name": "uk",
    "regionalDisplayName": "United Kingdom",
    "subscriptionId": null
  },
```

We can see the Display Name here is `United Kingdom` but the Name is `uk`. Which is different than, for example:

```
{
    "displayName": "United States",
    "id": "/subscriptions/81cb9df9-8726-4ad7-a878-8385e15c6c4e/locations/unitedstates",
    "metadata": {
      "geographyGroup": null,
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionCategory": "Other",
      "regionType": "Logical"
    },
    "name": "unitedstates",
    "regionalDisplayName": "United States",
    "subscriptionId": null
  },
``` 

Where Display Name is `United States` and name is `unitedstates`.

I don't see how we could apply the same algorithm.

**Comment by j82w** [comment]
I wonder if this is still necessary if we added the feature to get the region from the Azure VM API. I was really hoping that just doing lower case + removing space would fix it.

**Comment by ealsur** [comment]
Me too, but sadly the inconsistency kills any possible algorithm

**Comment by sebader** [comment]
@ealsur your example is a `"regionType": "Logical"`, I think you can disregard those. Looking at the output I would say only `"regionType": "Physical"` is important as those are actual regions

**Comment by ealsur** [comment]
Great point, didn't see the difference on the regionType!

**Comment by sebader** [comment]
@ealsur any updates on this one? This is still a major hurdle in many automation scenarios

**Comment by nahk-ivanov** [comment]
Should we expect this to be fixed? It is going to be two-year anniversary of this request soon. Does it really take that long to hard code a table or use equality comparer on the existing one that will do `.ToLowerInvariant().Replace(" ", "")`?

**Comment by kirankumarkolli** [comment]
RegionName type is string which can be extended to cover normalized names. 
So the API will support other normalized names and no extension method is necessary. 

@jcocchi, @ealsur , @FabianMeiswinkel thoughts?

**Comment by nahk-ivanov** [comment]
@kirankumarkolli either that, or just update the dictionary in the `RegionProximityUtil` to use custom equality comparer that normalizes the names. I vote for the later, as we don't usually like to modify user inputs in property setters.

**Comment by kirankumarkolli** [comment]
Agreed upon name normalization
- Spaces
- Case-incensitive

**Comment by kirankumarkolli** [comment]
If ApplicationRegion/PreferredRegions are supporting other normalized regions what are scenarios for Region.TryParse?
