### ISSUE TITLE
'Replace container' doesnt actually work to re-enable indexes

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cosmos-dotnet-v3#2334]
Using the latest version of the SDK against a 'serverless' account, executing 'ReplaceContainerStreamAsync' on the container with properties to enable  the indexing returns an 'OK' result but then the indexing remains disabled in the actual container

![image](https://user-images.githubusercontent.com/969938/112491307-30c34080-8d4e-11eb-8d11-69bee4265bdd.png)

results in

![image](https://user-images.githubusercontent.com/969938/112491357-3ae53f00-8d4e-11eb-8931-bdda6dcf8d3d.png)

**Expected behavior**
The new indexing policy should be applied

**Actual behavior**
Indexing policy remains disabled

**Comment by ealsur** [comment]
@onionhammer This doesn't seem like an SDK issue, as you pointed out, the SDK is receiving an `OK` from the service, whether or not that materializes is out of what the SDK can or should do.

@ThomasWeiss Is this an expected behavior on serverless?

**Comment by ThomasWeiss** [comment]
@ealsur It is not. I tried to disable, then re-enable indexing on a serverless container from the portal, and it succeeded.

**Comment by ealsur** [comment]
@onionhammer Have you tried changing it from the Portal and it works? Did you try refreshing the portal webpage after you executed the SDK operation?

**Comment by onionhammer** [comment]
Yes, it works via the portal, just not the SDK

**Comment by ealsur** [comment]
@onionhammer Can you provide a code repro (not screenshots) that we can use to verify?

**Comment by onionhammer** [comment]
Hmm, I think the issue is that the progress notification was not showing and the table I was enabling indexing on was somewhat large?

![image](https://user-images.githubusercontent.com/969938/112532965-70525280-8d77-11eb-8b0d-125c3e1d873b.png)

I'm not able to reproduce this now. I guess the only issue is that clicking the 'refresh' icon does not reload the indexing policy, you have to actually refresh the entire azure portal window to get the latest settings
