### ISSUE TITLE
CosmosDiagnostics Bug: ITrace on large number of retries causes JSON depth exception

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2354]
If there are hundreds of retries on an operation and a ToString() is done it will hit a JSON depth exception. Internal team hit it in the latest sync. The issue is the retry handler nests the ITrace instead of making all the retries at the same level. 

To reproduce use the transport handler to inject a large number of 449s.

This is a regression that was introduced in 3.17.0 in PR #2097 

There should be 2 separate fixes:
1. ITrace needs to be fixed to not nested retries which will prevent the JSON depth exception. 
2. ITrace should have a max number of retries it records to avoid running out of memory.

The baselines do show the nesting:
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8bf3857ff0c6bbe5c4ce6197cc82aeca3c9e684d/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml#L276

I believe the nesting would be fixed by deleting the following line, but uncertain the reason it was added :
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8bf3857ff0c6bbe5c4ce6197cc82aeca3c9e684d/Microsoft.Azure.Cosmos/src/Handler/AbstractRetryHandler.cs#L25

**Comment by jasontho-ms** [comment]
I already have a fix for this; will submit once the latest sync is complete.
