### ISSUE TITLE
FeedResponse<T>.Headers empty for ordered, cross-partition queries

### ISSUE THREAD

**Issue by ccurrens** [Azure/azure-cosmos-dotnet-v3#2356]
Response headers are missing in `FeedReponse<T>` when the query executed contains an `OrderBy` statement and is cross-partition.

**To Reproduce**
Here's a simplified case:

```csharp
public class Family
{
    [JsonProperty(PropertyName = "id")]
    public string Id { get; set; }

    public string LastName { get; set; }

    [JsonProperty(PropertyName = "_pk")]
    public string PartitionKey => LastName;
}

private Task RunQuery(IQueryable<Family> query)
{
    var iterator = query.ToFeedIterator();
    while (iterator.HasMoreResults)
    {
        var response = await iterator.ReadNextAsync();
        Console.WriteLine(response.Headers.Get("x-ms-documentdb-query-metrics") ?? "MISSING");
    }
}

// Writes "MISSING" to the console
RunQuery(container.GetItemLinqQueryable<Family>().OrderBy(f => f.Id));

// Writes query metrics to the console
RunQuery(container.GetItemLinqQueryable<Family>());
```

**Expected behavior**
Headers from the response should be available in the `FeedResponse`

**Actual behavior**
There are no headers available in the `FeedResponse`

**Environment summary**
SDK Version: 3.17.1 (Also in 3.16, and possibly earlier)
OS Version (e.g. Windows, Linux, MacOSX): All

**Additional context**
The headers are available by adding a `RequestHandler` to the client. This is a complicated workaround when the client is used by multiple threads and you are trying to relate requests to one another.

Since the headers are available when running an ordered query in-partition, it seems to be an issue with `additionalHeaders` [not flowing](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8bf3857ff0c6bbe5c4ce6197cc82aeca3c9e684d/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs#L408) through to the `QueryPage` result (also [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8bf3857ff0c6bbe5c4ce6197cc82aeca3c9e684d/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs#L463))

Ultimately, though, I think this is indicative of a missing feature in the SDK, where it would be really nice to have the [`QueryMetrics`](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8bf3857ff0c6bbe5c4ce6197cc82aeca3c9e684d/Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs) class (or similar) publicly exposed on responses. Apparently, something similar [was available in an earlier SDK version](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-query-metrics#query-execution-metrics). Our particular use case is structured logging, where we enrich our logs with additional properties, including the index utilization ratio, request counts, and retrieved/output document counts.

**Comment by j82w** [comment]
@ccurrens please upgrade to the latest [3.18.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.18.0) release.
