### ISSUE TITLE
Linq queries with nullable enum don't work, if enum uses StringEnumConverter

### ISSUE THREAD

**Issue by Licho1** [Azure/azure-cosmos-dotnet-v3#2373]
It results in exception:
```
System.InvalidCastException: Unable to cast object of type 'Microsoft.Azure.Cosmos.SqlObjects.SqlNullLiteral' to type 'Microsoft.Azure.Cosmos.SqlObjects.SqlNumberLiteral'.
    at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.ApplyCustomConverters(Expression left, SqlLiteralScalarExpression right)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitBinary(BinaryExpression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression inputExpression, TranslationContext context)
```

To replicate use classes like 

```
        public class TestArtifactEnum 
        {
            public MyEnumTest? NullableEnum { get; set; }
        }

        [JsonConverter(typeof(StringEnumConverter))]
        public enum MyEnumTest
        {
            One, Two, Three
        }
```
Then use LINQ query like ``` .Where(x => x.NullableEnum == null) ```  on GetItemLinqQueryable

Nullable enum works fine, if the StringEnumConverter is not used.

**Comment by ccurrens** [comment]
We are running into this issue ourselves, with a different converter. It seems that if the property is a nullable value type AND you have applied a custom `JsonConverter`, then `ExpressionToSql.ApplyCustomConverters` does not handle `null` properly in these situations.

**Comment by PKPublicCode** [comment]
Hi everybody,
May I ask why issue is closed? Does it mean that it's not supposed to be fixed at all?

**Comment by Licho1** [comment]
Probably closed for inactivity?

**Comment by bartelink** [comment]
Multiple issues got accidentally closed that day by a runaway bot - the closing is likely an oversight.
Though not sure how/whether converters can/should be considered given how the json mapping is pluggable - i.e. it could be `System.Text.Json` doing the serialization.
