### ISSUE TITLE
Container methods create and upsert from stream with nullable PartitionKey

### ISSUE THREAD

**Issue by fhtino** [Azure/azure-cosmos-dotnet-v3#2378]
I think that Container CreateItemStreamAsync and UpsertItemStreamAsync should allow nullable PartionKey parameter and default it to null. I see that the underlying methods all acceopt "PartitionKey?". Also the similar methods  UpsertItemAsync and CreateItemAsync accept nullable PartitionKey.  Obviously, when PartitionKey parameter is null, the key is extracted from the doc.

**Comment by j82w** [comment]
Is there any reason you can't use the PartitionKey.Null? 

The partition key is a very important part of designing an application. Having a default value of null will allow developers to build a cosmos DB application without thinking about it. This leads to many issues in the future when the application needs to scale because a logical partition key has several limits such as a [maximum of 20 GB and 10,000 RUs](https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#provisioned-throughput).

**Comment by fhtino** [comment]
@j82w  I perfectly understand the importance of partition key an I want to and need to use it. Let me explain a bit more my suggestion. Perhaps I was not so clear.
I have a container with "mypartkey" as partition key. This works perfectly:
```
MyItem myObj = new MyItem() { id = "00001", mypartkey = "p1", name = "Foo" };
var response1 = await container.UpsertItemAsync(myObj); 
```
Now, I want to do the same using UpsertItemStreamAsync:
```
string myJson = "{\"id\":\"00001\",\"mypartkey\":\"p1\",\"name\":\"Foo\"}";
Stream myStream = new MemoryStream(Encoding.UTF8.GetBytes(myJson));
var response2 = await container.UpsertItemStreamAsync(myStream, new PartitionKey("p1"));
```
As you can see, I have to explicitly pass the partition key value "p1" whereas it's already present in the json stream. 

I have also tried
`var response3 = await container.UpsertItemStreamAsync(myStream, PartitionKey.Null);`
and
`var response4 = await container.UpsertItemStreamAsync(myStream, PartitionKey.None);`
Both return 
`BadRequest, http 400, "PartitionKey extracted from document doesn't match the one specified in the header"`

My suggestion is to allow to use UpsertItemStreamAsync without beeing forced to pass the partition key twice, in the json and as parameter. Or allow something like:
`await container.UpsertItemStreamAsync(myStream, PartitionKey.FromJsonStream)`

**Comment by j82w** [comment]
What is the scenario for using the stream API? Does the additional overhead of having the SDK parse and extract the partition key from the stream not a concern?

**Comment by fhtino** [comment]
Suppose I receive a json from another system. I know for sure the json is ready to be stored , i.e. it already contains the id field and the partition key field. For using UpsertItemStreamAsync, I must parse the json with NetwonsoftJson and extract the partition-key, only to send it alongside the json, already containing it. Not a big performance issue but useless.

**Comment by j82w** [comment]
Can the service that is sending the JSON payload not pass the partition key in the header? Just to be clear the SDK will still have to parse the json to get the partition key.

**Comment by kirankumarkolli** [comment]
Practically in many scenarios the PK is extracted from the context it-self (ex: end REST API addressing) and stream API's are tailed for those scenarios.
