### ISSUE TITLE
StringEnumConverter in CosmosSerializer is ignored when making a LINQ query against an enum

### ISSUE THREAD

**Issue by ivancavlek** [Azure/azure-cosmos-dotnet-v3#2386]
**Describe the bug**
When working with enum serialized as string in simple where clause, the expression is properly translated in SQL using the string value of the enum when StringEnumConverter is set as a C# attribute.
But it doesn't work when working with Fluent interface and inheriting from CosmosSerializer.

**To Reproduce**
```C#
public enum Status
{
  StatusA,
  StatusB
}
```

```C#
public class CosmosNewtonsoftJsonSerializer : CosmosSerializer
{
    private readonly JsonSerializerSettings _jsonSerializerSettings;

    public CosmosNewtonsoftJsonSerializer()
    {
        _jsonSerializerSettings = new JsonSerializerSettings
        {
            Converters = new List<JsonConverter>
            {
                new StringEnumConverter()
            }
        };
        _jsonSerializer = JsonSerializer.Create(_jsonSerializerSettings);
    } 
...
}
```

**Expected behavior**
```C#
var query = container.GetItemLinqQueryable<Foo>();
query = query.Where(foo => foo.Status == Status.StatusA);
Console.WriteLine(query.ToQueryDefinition().QueryText);
```

`SELECT VALUE root FROM root WHERE (root["Status"] = "StatusA")`

**Actual behavior**
`SELECT VALUE root FROM root WHERE (root["Status"] = 0)`

**Environment summary**
SDK Version: 3.17.1
Windows 10
Working with Cosmos Emulator

**Additional context**
```C#
public class Foo
{
    [JsonConverter(typeof(StringEnumConverter))]
    public FooStatus Status { get; set; }
}
```

This configuration works as intended.

**Comment by Ettores88** [comment]
+1 I have the same exact problem!

**Comment by Ettores88** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/bedeabb64bd4c8f7411561fe40f625a885ae5840/Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs#L485

From the code, I see that custom converters are applied only if they are explicitly defined on the definition of the data type. But it completely nullifies the utility of defining a custom serializer for the whole CosmosClient if it isn't enforced equally here.

**Comment by HMoen** [comment]
@ivancavlek , even adding the JsonConverter as a property level attribute does not work for me using 3.26.1.

Not ideal, but this works:
```C#

var query = container.GetItemLinqQueryable<Foo>();
query = query.Where(foo => foo.Status.ToString() == Status.StatusA.ToString);

```

**Comment by ivancavlek** [comment]
@j82w, @sboshra, please reopen this issue.

**Comment by j82w** [comment]
@timsanders1 can you please take a look.

**Comment by Ettores88** [comment]
Any update on this topic?

**Comment by Maya-Painter** [comment]
Hi all, we've merged what we hope will be a solution to this issue by allowing the custom serializer to be used for LINQ translations. This also unblocks having System.Text.Json attributes applied in LINQ queries.

We plan to release this as part of the next preview package, but I also wanted to take this time to confirm these changes meet your needs before finalizing them as part of our public API.  If you try the changes out, please follow up in the thread if this update addresses your concerns. If it doesn't, please let us know why.

To use your own custom serializer for LINQ translations you must implement `CosmosLinqSerializer` and set it as a custom serializer on the `CosmosClient`. There is a sample of this for serialization with System.Text.Json in CosmosLinqSerializer.cs.
