### ISSUE TITLE
Linq to SQL for string.Length doesn't use Cosmos LENGTH()

### ISSUE THREAD

**Issue by j-rewerts** [Azure/azure-cosmos-dotnet-v3#2387]
**Describe the bug**
Linq to SQL for string.Length doesn't use Cosmos LENGTH().

**To Reproduce**
``` c#
class User
{
  public string Email { get; }
}
```

Imagine we want to find all of the users that have an email that isn't null or empty:

``` c#
IQueryable<User> query = _db.Users
  .Where(user => user.Email != null && user.Email.Length > 0);
```

This will result in a SQL query like `user.Email.Length > 0`  rather than one that looks like `LENGTH(user.Email) > 0`. 

**Expected behavior**
String.Length is converted into SQL LENGTH().

**Actual behavior**
Length is treated like a property on an object.

**Environment summary**
SDK Version: v3.17.1
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Comment by j82w** [comment]
@timsander1 do you have any suggestions?

**Comment by timsander1** [comment]
Hi  @j-rewerts , could you try this? Using the COUNT() function will get the string length.

IQueryable<User> query = _db.Users
  .Where(user => user.Email != null && user.Email.Count() > 0);

**Comment by jviau** [comment]
@timsanders1 - `.Count()` does work, but I think `.Length` should work as well, as it is more intuitive to use. Also analyzers flag uses of `.Count()` on `string` and suggest the usage of `.Length`. Look at the code, it should be a very simple fix. [StringBuiltinFunctions](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/StringBuiltinFunctions.cs#L359) just needs to check for `"Length"` as well as `"Count"`.

**Comment by j-rewerts** [comment]
Was this ever fixed?
