### ISSUE TITLE
Query correlated activity id

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2391]
The query backend service can now handle correlated activity id. This will enable better troubleshooting of query issues as there currently isn't any way to correlate cross partition queries.

The change that need to be made:
1. New query should create a new correlated activity id. All the query request sent to the backend should include this property in the header with the key `"x-ms-cosmos-correlated-activityid"` is in the `WFConstants.CorrelatedActivityId`
2. The ITrace diagnostics need to include the correlated activity id
3. The continuation token should be modified to include the correlated activity id. This can be done in a separate PR. Adding the property should not break back compatibility of the current token.

Query already has a [partially wired through correlated activity id](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/12c8affe6119bbeb2410acb4a635b4b4b6622aee/Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs#L78). This will need to be expanded to send it through the NetworkAttachedDocumentContainer and the [query client](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/12c8affe6119bbeb2410acb4a635b4b4b6622aee/Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs#L50).

Testing should use a custom requesthandler to make sure that all the pages sent by the query include the correct correlated activity id.

**Comment by asketagarwal** [comment]
There is still some work to be done here by the query team. Currently the Correlated Activity Id is not making it to the Kusto tables
