### ISSUE TITLE
Add support for managing Users and Resource Tokens

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#240]
**Describe the solution you'd like**
I think DocumentClient . should be made public so that operations such as managing Users and Resource Tokens is accessible.

**Describe alternatives you've considered**
Adding the DocumentDB assembly

**Comment by ealsur** [comment]
@fuocor DocumentClient will be dissapearing, your concern is to be able to manage users and resource tokens on the new V3 client?

**Comment by fuocor** [comment]
yes...

**Comment by wouterdeman** [comment]
We are also blocked in using the new v3 version because we want to make use of the Resource token approach isolating access to a given partition. https://docs.microsoft.com/en-us/azure/cosmos-db/secure-access-to-data#resource-tokens Any update on this topic/feature ?

**Comment by thomaslevesque** [comment]
Without this feature, the v3 is basically a regression from v2... I spent hours trying to migrate to the new SDK before realizing it didn't support this.

**Comment by j82w** [comment]
@fuocor , @wouterdeman , @thomaslevesque the [PR ](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/622)is merged to add user and resource token.

**Comment by thomaslevesque** [comment]
@j82w thanks! Any ETA for the next release?

**Comment by j82w** [comment]
We will hopefully do a release next week. It might be longer if we hit any unexpected bugs are found.
