### ISSUE TITLE
Public access to SqlTranslator to UnitTest LINQ to SQL without a database

### ISSUE THREAD

**Issue by ThomasVandenbon** [Azure/azure-cosmos-dotnet-v3#2413]
**Is your feature request related to a problem? Please describe.**
I have some code that calls a Cosmos DB, but that I'm testing without a real database.
Within this code, LINQ to SQL is being used to fetch documents from Cosmos DB.

Occasionally someone on my team uses a LINQ-method that cannot be translated into a Cosmos-query ("All" for example).
I'd like to add an in-memory check in my unit tests to verify that an Expression can be converted to a Cosmos-query.

This would allow us to detect these problems while developing, rather than when the code is run against an actual database.

**Describe the solution you'd like**
If I was able to call the [SqlTranslator](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Linq/SQLTranslator.cs#L15), then I'd be able to write a check for this.
Sadly this class has been marked as internal.

**Describe alternatives you've considered**
The only alternative I've come up with so far, is to travel through the expression in custom code to perform some rudimentary checks based on the [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-linq-to-sql).
But that has obvious downsides:
- The code from this repository would need to be rewritten/dupplicated
- It would be hard to keep this in sync. This is already demonstrated by the documentation page not listing "Any", while it is supported).

**Additional context**
I've noticed that there are a number of issues here and on StackOverflow which don't have an ideal solution that would probably benefit from this solution as well.

**Comment by j82w** [comment]
Hi @ThomasVandenbon,

Can this be done already via the [ToQueryDefinition()](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/58a23c293080646ad904ece25cd3bc1760b106cb/Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs#L137) extension method?

**Comment by ThomasVandenbon** [comment]
Thank you for your response @j82w .

If I were to use [ToQueryDefinition()](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/58a23c293080646ad904ece25cd3bc1760b106cb/Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs#L137) as you suggested, wouldn't I then run into the problem of not being able to construct `CosmosLinqQuery<T>`? (see #893).

**Comment by j82w** [comment]
Can you provide an example of what you would do if you had access to the SqlTranslator?

**Comment by ThomasVandenbon** [comment]
@j82w thank you for your suggestion.

> Can you provide an example of what you would do if you had access to the SqlTranslator?
> 
> You could do something like this.
> 
> ```cs
> var query = container.GetItemLinqQueryable<Book>().Where(b => b.Title == "War and Peace");
> var queryDefinition = query.ToQueryDefinition();
> var feedIterator = container.GetItemQueryIterator<Book>(queryDefinition);
> ```

I'm srry, but I haven't had time yet to create an example.

As for your suggestion: what I'm strugling to understand is how you'd get the `container` without having an actual database?
Could you elaborate on that?

What I had in mind was that the input of the test would be nothing more than `.Where(b => b.Title == "War and Peace")` in your example, or even just the Func itself: `b => b.Title == "War and Peace"`.

**Comment by j82w** [comment]
The container can be created by creating a CosmosClient that uses a dummy endpoint and password. The linq conversion does not require any async methods so no network calls are being done. 

```c#
CosmosClient client = new CosmosClient("random endpoint", "random value");
Container container = client.GetContainer("DoesNotExist", "DoesNotExist");
var query = container.GetItemLinqQueryable<Book>().Where(b => b.Title == "War and Peace");
var queryDefinition = query.ToQueryDefinition();
```
