### ISSUE TITLE
TransactionalBatch operation fails with 500 Internal Server Error in C#

### ISSUE THREAD

**Issue by zhilin-2011** [Azure/azure-cosmos-dotnet-v3#2421]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When executing "PatchItem" in TransactionalBatch to replace/increment an item's value in my C# function app, the operation fails and I get 500 Internal Server Error.
Here are the NuGet packages we install.
Microsoft.NETCore.App: 3.1.0
Microsoft.Azure.Cosmos: 3.18.0-preview (3.17.1 latest release version does not include PatchItem API)
Here is the info of our Cosmos DB.
Resource Group: dev-delivery-cluster-1-manual-testing-rg
Subscription: PromoteIQTest
DB Name: adserver
Is it because that Cosmos package is in preview version? Do we need to set up some flag on our side? Or is there a whitelist on your side to allow specified user to use this API? If so, could you add us too?

**To Reproduce**
Here is the code to call PatchItem api in our app.
            var metricsContainer = client.GetContainer("adserver", "metrics");

            // batch transaction
            TransactionalBatch batch = metricsContainer
                .CreateTransactionalBatch(new Microsoft.Azure.Cosmos.PartitionKey(partitionKey));
            List<PatchOperation> patchOperations = new List<PatchOperation>
            {
                PatchOperation.Replace("/EntityType", "InProgress"),
                PatchOperation.Increment("/EntityId", 1L)
            };

            batch.PatchItem(id, patchOperations);
            var batchResponse = await batch.ExecuteAsync();

**Expected behavior**
The item is updated correctly.

**Actual behavior**
The item is not updated. We get a 500 Internal Server Error when we call Patch api.

**Environment summary**
SDK Version: 3.18.0-preview
OS Version: MaxOS

**Additional context**
N/A

**Comment by ealsur** [comment]
@zhilin-2011 please share the complete stack trace of the 500 error.

Are you executing on a real account or the emulator?

**Comment by j82w** [comment]
@zhilin-2011 patch is currently in private preview. There is a  service bug that is causing it to return a 500 instead of a 400 with a message saying it is not enabled for the account. A fix is being worked on to return the correct status and message.
