### ISSUE TITLE
CosmosDB bulk upsert extremly slow

### ISSUE THREAD

**Issue by eddadjei** [Azure/azure-cosmos-dotnet-v3#2443]
Below is how I am using the bulk upsert feature in ComosDB. This code is extremely slow even for 15 documents.

```
var container = _database.GetContainer(collectionName);
            var cts = new List<Task>();
            foreach (var d in documents)
            {
                var t = container.UpsertItemAsync(d,
                    new PartitionKey(d.GetPartitionKey())
                );

                cts.Add(t);
            }
            await Task.WhenAll(cts);
```

**Comment by j82w** [comment]
Please look at the following [bulk article](https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/#what-is-not-bulk). Bulk is designed for throughput not latency. 15 documents is small amount and it is probably having to wait for the timer delay rather then executing once there is enough documents.

Some suggestions:
1. Make sure you are using the latest SDK
2. The first call through the cosmos client will be delayed because it has to warm up caches. Please try using the [CreateAndInitializeAsync ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-3170---2021-03-02). 
3. Look at [Batch]((https://devblogs.microsoft.com/cosmosdb/introducing-transactionalbatch-in-the-net-sdk/) to see if fits your scenario better.


If you believe it is a bug please re-open the issue and provide more information on different document counts being used, what the exact latency is for each scenario, and the CosmosDiagnostics for each of these runs.

**Comment by eddadjei** [comment]
So technically then there is no way to make an efficient batch request for 15 items if I want to reduce the number of network calls?

**Comment by j82w** [comment]
[Batch](https://devblogs.microsoft.com/cosmosdb/introducing-transactionalbatch-in-the-net-sdk/) allows you to do a single request for 15 items. Is there any reason this does not work for you?

**Comment by eddadjei** [comment]
it works but I am not sure if you have measured the time or use this in a real web-api project. it's super slow. Even gotten the azure team involved.

**Comment by j82w** [comment]
We have tested this and for point operations we have a runner that continuously monitors performance. More information is needed to investigate if there is a possible bug or some change to improve the performance.

1. How many items are in the batch? 
2. How big are the items if it's create/update?
3. How long is it taking?
4. What is the response.CosmosDiagnostics.ToString() of the slow request?
5. Is it every request? If not what percentage of requests?
6. Is it every operation or just Batch?
7. Can you provide a sample that reproduces the issue?
8. What is the CosmosClientOptions?

**Comment by bartelink** [comment]
Is there a "TL;DR this is how the Batch support works" article anywhere? I'm thinking this might give the OP better context (and, as I have not read the code wrt that, I'd like to see it too)

i.e. if there are 15 requests using 10 unique partition keys with 6 in range 1 and 4 in range 2, how do the requests travel at a high level?

What does the server approximately look like (does it accept requests in terms of a physical partition or a logical partition) ?
Is it all just sent to a built-in stored procedure under the hood and driven by that? (If I thought there was a key efficiency gain or tradeoff compared to that, I'd be interested to know)
Do responses flow back individually or batched per that execution API-based grouping?

**Comment by j82w** [comment]
Batch is always restricted to a single partition key which results in a single physical machine. Here is the Batch documentation: https://docs.microsoft.com/en-us/azure/cosmos-db/transactional-batch . If there is something missing or  if you have suggestions please leave feedback on the page.

Bulk is explained in the following article which clearly states the caveats: https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/

**Comment by bartelink** [comment]
Thanks for being patient, will do (and apologies for not reading the answers you provided in the thread distinguishing between and referencing docs for Batch vs Bulk).

**Comment by eddadjei** [comment]
Thanks for your response. I believe the issue was with the partitions. Say you have 100 documents each with different partition keys what would be the effective way to do inserts?

**Comment by j82w** [comment]
This is a good article explaining Cosmos DB partitioning: https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview 

If it's only 100 documents then doing individual read items is the recommend way. The SDK is thread safe so you can send multiple requests in parallel. Once the SDK connects to a single physical machine it will reuse the connection for future requests. Using the [Benchmark project](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Tools/Benchmark) on Linux VM with 4 cores we are able to get over 10,000 request per a second.
