### ISSUE TITLE
Allow using CreateAndInitializeAsync without blocking configuration

### ISSUE THREAD

**Issue by jesperkristensen** [Azure/azure-cosmos-dotnet-v3#2444]
**Is your feature request related to a problem? Please describe.**
I just read about https://devblogs.microsoft.com/cosmosdb/improve-net-sdk-initialization/ and wanted to try it out. But it seems like CreateAndInitializeAsync tightly couples configuration and initialization of CosmosClient in a way that makes it too difficult to use in our setup.

We register CosmosClient as a singleton in IServiceCollection. This is synchronous, so we cannot call an async method. I don't want to block the rest of our app startup on initializing the CosmosClient.

It looks like CreateAndInitializeAsync won't even return a CosmosClient if a network issue causes initialization to fail. I want our app to be able to start up even if a temporary network issue during startup prevents initialization of the CosmosClient.

I would like to get a reference to a CosmosClient synchronously that I can pass around and use while the initialization runs in the background. I would like that our readiness probe could check if initialization completed, so our app could signal it is ready when initialization of the CosmosClient either succeed or failed, or after a configured timeout.

**Describe the solution you'd like**
One solution could be to make the InitializeContainersAsync method public. Another solution could be to add the initialization options to the synchronous constructor, and expose a Task as a property on the CosmosClient instance that tells when initialization is complete.

**Describe alternatives you've considered**
We currently don't use CreateAndInitializeAsync, since it is not essential.

**Additional context**

**Comment by j82w** [comment]
Would using a [AsyncLazy ](https://devblogs.microsoft.com/pfxteam/asynclazyt/ )which can have retry logic to handle transient network issues solve your problem?

**Comment by jesperkristensen** [comment]
It would be a complex task to properly implement AsyncLazy with retry. It would also mean I would have to change from CosmosClient to Task<CosmosClient> everywhere I get that from the ServiceProvider, and add extra await statements. All in all, it is way too much work compared to the benefit. So I think I will just continue to use CosmosClient without this initialization. The difference in startup performance is not big enough to justify the work.

**Comment by ealsur** [comment]
@jesperkristensen What if the initialization would not fail if there are any errors trying to initialize the caches for any of the parameter collections? 

The only drawback is, you could assume everything was great, and then see a latency spike on the first request.

**Comment by jesperkristensen** [comment]
In that case I might use it for some of our services. It is a trade off between the small performance gain for a small fraction of requests, versus the added complexity.
