### ISSUE TITLE
Expose the ITrace outside the SDK

### ISSUE THREAD

**Issue by anujtoshniwal** [Azure/azure-cosmos-dotnet-v3#2457]
ITrace needs to be exposed so that we can add to it from outside the SDK, for example in the Encryption package.

**Comment by j82w** [comment]
ITrace will likely never be exposed through the public API. There isn't enough of a use case for users to expose it.

The recommendation would be have your own implementation of CosmosDiagnostics which combines any necessary information for encryption with the response from the public SDK.

**Comment by anujtoshniwal** [comment]
Decided on the following workaround - allow Diagnostics on the ResponseMessage to be set publicly. From the Encryption library, then we can append encryption related stuff to the Diagnostics returned by the core SDK and set it on the ResponseMessage.
