### ISSUE TITLE
Add a custom CosmosDisposedException

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2464]
Create a custom ObjectDisposedException like CosmosOperationCancelledException.

The custom exception should include.
1. Diagnostics
2. If and when the client was disposed of

**Comment by ealsur** [comment]
3. Endpoint with which the client was initialized

**Comment by j82w** [comment]
@ealsur how about this as the string?

"The CosmosClient created at {createTime} has been disposed of at {time} for endpoint: {endpoint}. Please make sure to follow best practices and use a singleton instance of a CosmosClient."
