### ISSUE TITLE
Change Feed - CancellationToken not flowing into the pipeline

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#2478]
After the refactoring in #1933, the user CancellationToken on `ReadNexAsync` is not flowing into the pipeline.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedIteratorCore.cs#L250-L253

```
CrossPartitionChangeFeedAsyncEnumerator enumerator = monadicEnumerator.Result;
if (!await enumerator.MoveNextAsync(trace))
{
	throw new InvalidOperationException("ChangeFeed enumerator should always have a next continuation");
}
```

This means that if the CancellationToken cancels, it is not stopping any of the pipeline operations (like retries).

**Comment by maryammadzadeh** [comment]
I am currently investigating a similar issue. Would this also cause the cancellation tokens to change for the retries?

**Comment by ealsur** [comment]
@maryammadzadeh  Since the CancellationToken does not flow through, if a particular ReadNextAsync call has retries (for example, the call hits 429s) and the CancellationToken cancels in-between, then the SDK will retry and the CancellationToken won't stop the retries, if any.
