### ISSUE TITLE
Hang  about query multiple  partition  in SDK 3.17

### ISSUE THREAD

**Issue by LiDamon** [Azure/azure-cosmos-dotnet-v3#2486]
**Describe the bug**
Get three partition data in one query time, the query always hang.

**Code**
![Code](https://user-images.githubusercontent.com/3748285/118953944-de8a4e80-b98f-11eb-86ab-0b000f7fe193.png)

**Environment summary**
SDK Version: 3.17
OS Version: Linux ,Docker with netcore-runtime-base:3.1.12-alpine3.12

**Dump Stack**
OS Thread Id: 0xe24 (25)
        Child SP               IP Call Site
00007F435797A898 00007f46e45fd352 [HelperMethodFrame: 00007f435797a898] System.Threading.Thread.SleepInternal(Int32)
00007F435797A9E0 00007F466F3AAD64 System.Threading.SpinWait.SpinOnceCore(Int32) [/_/src/System.Private.CoreLib/shared/System/Threading/SpinWait.cs @ 242]
00007F435797AA70 00007F4669D4DC79 System.Threading.CancellationTokenSource.WaitForCallbackToComplete(Int64) [/_/src/System.Private.CoreLib/shared/System/Threading/CancellationTokenSource.cs @ 802]
00007F435797AAA0 00007F466C239CB7 System.Net.Http.ConnectHelper+<ConnectAsync>d__1.MoveNext() [/_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs @ 55]
00007F435797AAC0 00007F466C239B7D System.Net.Http.ConnectHelper+<ConnectAsync>d__1.MoveNext()
00007F435797AC30 00007F466C248302 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[System.Net.Http.ConnectHelper+<ConnectAsync>d__1, System.Net.Http]].ExecutionContextCallback(System.Object) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 580]
00007F435797AC70 00007F466E4687ED System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 201]
00007F435797ACC0 00007F466C2480B2 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[System.Net.Http.ConnectHelper+<ConnectAsync>d__1, System.Net.Http]].MoveNext(System.Threading.Thread) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 654]
00007F435797AD30 00007F466C247FC9 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[System.Net.Http.ConnectHelper+<ConnectAsync>d__1, System.Net.Http]].MoveNext() [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 595]
00007F435797AD50 00007F466E47D746 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean) [/_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs @ 804]
00007F435797AD90 00007F466E4689D0 System.Threading.Tasks.Task.RunContinuations(System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs @ 3411]
00007F435797AE30 00007F466E48917F System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]].TrySetResult(System.Threading.Tasks.VoidTaskResult) [/_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Future.cs @ 422]
00007F435797AE60 00007F466E463EF2 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult() [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 273]
00007F435797AE90 00007F466C247EE3 System.Net.Http.ConnectHelper+ConnectEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs) [/_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs @ 102]
00007F435797AEF0 00007F466C352580 System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(System.Object) [/_/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs @ 423]
00007F435797AF00 00007F466E4687ED System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 201]
00007F435797AF50 00007F4669D4F040 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 131]
00007F435797AF60 00007F466C354735 System.Net.Sockets.SocketAsyncEventArgs.FinishWrapperConnectSuccess(System.Net.Sockets.Socket, Int32, System.Net.Sockets.SocketFlags) [/_/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs @ 672]
00007F435797AF80 00007F466C354542 System.Net.Sockets.MultipleConnectAsync.Succeed() [/_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs @ 289]
00007F435797AFA0 00007F466C35448D System.Net.Sockets.MultipleConnectAsync.InternalConnectCallback(System.Object, System.Net.Sockets.SocketAsyncEventArgs) [/_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs @ 219]
00007F435797AFE0 00007F466C353929 System.Net.Sockets.MultipleConnectAsync.AttemptConnection(System.Net.Sockets.Socket, System.Net.Sockets.SocketAsyncEventArgs) [/_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs @ 267]
00007F435797B020 00007F466C35375C System.Net.Sockets.MultipleConnectAsync.AttemptConnection() [/_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs @ 243]
00007F435797B070 00007F466C3534D4 System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(System.IAsyncResult, Boolean) [/_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs @ 132]
00007F435797B0D0 00007F466C353373 System.Net.Sockets.MultipleConnectAsync.DnsCallback(System.IAsyncResult) [/_/src/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs @ 84]
00007F435797B0F0 00007F466A66ADFE System.Net.LazyAsyncResult.Complete(IntPtr) [/_/src/Common/src/System/Net/LazyAsyncResult.cs @ 397]
00007F435797B140 00007F466A66AD53 System.Net.ContextAwareResult.CompleteCallback() [/_/src/Common/src/System/Net/ContextAwareResult.cs @ 394]
00007F435797B160 00007F466A66AD19 System.Net.ContextAwareResult+<>c.<Complete>b__15_0(System.Object) [/_/src/Common/src/System/Net/ContextAwareResult.cs @ 388]
00007F435797B170 00007F466E4687ED System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 201]
00007F435797B1C0 00007F4669D4F040 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 131]
00007F435797B1D0 00007F466A66AC13 System.Net.ContextAwareResult.Complete(IntPtr) [/_/src/Common/src/System/Net/ContextAwareResult.cs @ 388]
00007F435797B200 00007F466A66AAEC System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr) [/_/src/Common/src/System/Net/LazyAsyncResult.cs @ 351]
00007F435797B240 00007F466A66A231 System.Net.Dns.ResolveCallback(System.Object) [/_/src/System.Net.NameResolution/src/System/Net/DNS.cs @ 231]
00007F435797B260 00007F466A66A1CE System.Net.Dns+<>c.<HostResolutionBeginHelper>b__10_0(System.Object) [/_/src/System.Net.NameResolution/src/System/Net/DNS.cs @ 285]
00007F435797B270 00007F4669D64D43 System.Threading.Tasks.Task.InnerInvoke() [/_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs @ 2445]
00007F435797B290 00007F466E484D51 System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 315]
00007F435797B2D0 00007F466E484B0C System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) [/_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs @ 2421]
00007F435797B350 00007F466E47E549 System.Threading.ThreadPoolWorkQueue.Dispatch() [/_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs @ 699]
00007F435797B740 00007f46e366a85f [DebuggerU2MCatchHandlerFrame: 00007f435797b740]

**Comment by j82w** [comment]
@LiDamon why do you have the request timeout configured to 10 minutes? That is the network timeout not an e2e timeout. https://github.com/Azure/azure-cosmos-dotnet-v3/blob/2af3a6dd719c232992abb8dbf3672bef724b226c/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L153

How do you know it has three partitions?

**Comment by ealsur** [comment]
Can you please remove the thread-blocking Wait? You are wrapping async code into a `public void` method, which is bound to deadlock.

When using `async` calls, make sure the stack is `async` and you are `await`ing them.

**Comment by ealsur** [comment]
Please correct the async code and remove locks. In case it reproes on a full async scenario, please share the updated code, environment, and stack trace.

**Comment by j82w** [comment]
Please provide the query and token value or simple sample app that reproduces the issue. The type of query changes the SDK logic used to execute the query.

**Comment by j82w** [comment]
It did not reproduce with the following code:

```c#
       static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            CosmosClientOptions cosmosClientOptions = new CosmosClientOptions()
            {
                AllowBulkExecution = true,
                EnableContentResponseOnWrite = false,
                PortReuseMode = PortReuseMode.PrivatePortPool,
            };

            using CosmosClient client = new CosmosClient(
                "replaceEndpoint",
                "replaceKey",
                cosmosClientOptions);

            Container container = client.GetContainer("db", "coll");

            // Create items to actually query
            //for(int i = 0; i < 50; i++)
            //{
            //    await container.CreateItemAsync(new Book());
            //}

            using CancellationTokenSource cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromMinutes(10));
            var queryTask = Task.Run(async () =>
            {
                using var queryIterator = container.GetItemQueryStreamIterator(
                 "select * from T",
                 null,
                 null);

                while (queryIterator.HasMoreResults)
                {
                    using (ResponseMessage responseMessage = await queryIterator.ReadNextAsync(cancellationTokenSource.Token))
                    {
                        if (responseMessage.IsSuccessStatusCode)
                        {
                            Console.WriteLine("Success");
                        }
                        else
                        {
                            Console.WriteLine($"responseMessage: {responseMessage.StatusCode}, {responseMessage.ErrorMessage}");
                        }
                    }
                }
            });

            Console.WriteLine("Before wait");
            queryTask.Wait(TimeSpan.FromMinutes(5));
 
             Console.WriteLine("Done");
        }

        public class Book
        {
            public string id { get; set; } = Guid.NewGuid().ToString();
            public string pk { get; set; } = Guid.NewGuid().ToString();
        }
    }
```

**Comment by LiDamon** [comment]
This problem is not 100% reproducible. We PORD environment contains 20+ PODs per VM, and each POD has 10+ concurrent threads. We  have  total 300+ POD, about 20+ hang issue every day .

We haven't found this problem when using Windows image before, And this problem only appeared after switching to Linux image recently. I don't know if it has anything to do with this 

BTW, The environment host in AKS.

**Comment by j82w** [comment]
Make sure you are not having any resource governance issues. This is a common issue we have seen when running on AKS.

Remove the RequestTimeout override or at least reduce to 1 minute. If the network request is not done in 1 minute it will likely never complete anyways. It's not an end to end timeout.
