### ISSUE TITLE
Save document with diacritics

### ISSUE THREAD

**Issue by devcrp** [Azure/azure-cosmos-dotnet-v3#25]
**Describe the bug**
When inserting an item that contains diacritics using container.Items.CreateItemAsync it is being inserted like this:
![image](https://user-images.githubusercontent.com/46105751/51550816-708bf600-1e6d-11e9-92b0-d32dbe814f88.png)

I've been playing with the CosmosDefaultJsonSerializer, trying to change the Encoding of the StreamWriter with no luck.

I've also noticed that if I insert the document by using the Data Explorer through Azure Portal it works as expected. Maybe I'm missing some configuration somewhere that would solve this?

**To Reproduce**
Just try to insert an object like this in a collection and check what is being saved.
`new
{
id = "newid",
name = "Román"
}`

**Expected behavior**
Chars with diacritics to be saved properly.

**Actual behavior**
Chars with diacritics are lost during the saving.

**Environment summary**
SDK Version: 3.0.0.1-preview

**Comment by j82w** [comment]
Hi devcrp,

I was not able to repo the issue. I created the item via the SDK and viewed it in the portal data explorer and it appears fine. 
![image](https://user-images.githubusercontent.com/8868107/51616555-33604c00-1edf-11e9-8049-4ee7529d1ae3.png)

What are you using to view the inserted item? When you read the item back via the SDK is it still correct? Can you provide a link to a github repository with the repo?

**Comment by devcrp** [comment]
Hi j82w,

Here's the test project where I can reproduce the issue: https://github.com/devcrp/CosmosDBvsDiacritics 
In this case I'm using the emulator to test it, but the result is the same when using the CosmosDB in the Azure server.

Also, here's where I'm viewing the inserted item
![image](https://user-images.githubusercontent.com/46105751/51619882-85ca5880-1f31-11e9-9d9d-ff3ab9c9cfee.png)

And this is the container's config in case it helps
![image](https://user-images.githubusercontent.com/46105751/51619923-9ed30980-1f31-11e9-88bb-cc9cfe5801e0.png)

**Comment by j82w** [comment]
Hi devcrp,

Thanks for the repo code. I was able to reproduce the issue. I was using a .net core application and you were using .net framework. It works fine in .net core, but is broken in .net framework. The issue will be fixed in the next release which will hopefully happen soon., For now you can do the following workaround. 

```
        public static async Task<string> Insert(Person person)
        {
            using (var cosmosClient = new CosmosClient(new CosmosConfiguration(ENDPOINT, KEY).UseCustomJsonSerializer(new CustomJsonSerializer())))
            {
                var container = cosmosClient.Databases[DB].Containers[CONTAINER];
                var response = await container.Items.CreateItemAsync(person.id, person);
                return JsonConvert.SerializeObject(person);
            }
        }

        public static async Task<Person> Get(string id)
        {
            using (var cosmosClient = new CosmosClient(new CosmosConfiguration(ENDPOINT, KEY).UseCustomJsonSerializer(new CustomJsonSerializer())))
            {
                var container = cosmosClient.Databases[DB].Containers[CONTAINER];
                CosmosItemResponse<Person> result = await container.Items.ReadItemAsync<Person>(id, id: id);
                return result.Resource;
            }
        }

        /// <summary>
        /// The default Cosmos JSON serializer
        /// </summary>
        internal class CustomJsonSerializer : CosmosJsonSerializer
        {
            private static readonly JsonSerializer Serializer = new JsonSerializer();
            private static readonly Encoding DefaultEncoding = new UTF8Encoding(false, true);

            public override T FromStream<T>(Stream stream)
            {
                using (stream)
                {
                    if (typeof(Stream).IsAssignableFrom(typeof(T)))
                    {
                        return (T)(object)(stream);
                    }

                    using (StreamReader sr = new StreamReader(stream))
                    {
                        using (JsonTextReader jsonTextReader = new JsonTextReader(sr))
                        {
                            return CustomJsonSerializer.Serializer.Deserialize<T>(jsonTextReader);
                        }
                    }
                }
            }

            public override Stream ToStream<T>(T input)
            {
                MemoryStream streamPayload = new MemoryStream();
                using (StreamWriter streamWriter = new StreamWriter(streamPayload, encoding: CustomJsonSerializer.DefaultEncoding, bufferSize: 1024, leaveOpen: true))
                {
                    using (JsonWriter writer = new JsonTextWriter(streamWriter))
                    {
                        writer.Formatting = Newtonsoft.Json.Formatting.None;
                        CustomJsonSerializer.Serializer.Serialize(writer, input);
                        writer.Flush();
                        streamWriter.Flush();
                    }
                }

                streamPayload.Position = 0;
                return streamPayload;
            }
        }
```

**Comment by devcrp** [comment]
That did it, thank you!!
