### ISSUE TITLE
Integrated Cache: An error occurs when executing Point Read

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-cosmos-dotnet-v3#2513]
**Describe the bug**

When performing a read operation on a Cosmos DB account provisioned with Dedicated gateway, an error occurs and the operation does not work properly.

**To Reproduce**

Code used for testing.

```csharp
class Program
{
    static async Task Main(string[] args)
    {
        var connectionString = "AccountEndpoint=https://shibayantest.sqlx.cosmos.azure.com/;AccountKey=***;";

        var cosmosClient = new CosmosClient(connectionString, new CosmosClientOptions
        {
            ConnectionMode = ConnectionMode.Gateway,
            SerializerOptions = new CosmosSerializationOptions
            {
                PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
            }
        });

        var container = cosmosClient.GetContainer("HackAzure", "TodoItem");

        var item = await container.ReadItemAsync<TodoItem>("f32199f7-0b30-4da3-b006-5b8a34a99d8f", new PartitionKey("shibayan"));
    }
}
```

**Expected behavior**

Items can be read correctly.

**Actual behavior**

Unable to load items due to `CosmosException`.

**Environment summary**
SDK Version: 3.19.0-preview1
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

```
Microsoft.Azure.Cosmos.CosmosException: 'Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 6c96b689-e1ac-4217-ab4a-3853a3398927; Reason: ({"code":"InternalServerError","message":"System.ArgumentException: Cannot pass CancellationToken.None when requiresRealCancellationToken is true\r\n   at Microsoft.Azure.Cosmos.Compute.Core.InteropClient.InteropClient..ctor(CosmosClient cosmosClient, Boolean isServerlessEnabled, Boolean requiresRealCancellationToken, CancellationToken defaultCancellationToken)\r\n   at Microsoft.Azure.Cosmos.Compute.Runtime.ServiceInteropClient..ctor(CosmosClient cosmosClient, IComputeRequestTracker computeRequestTracker, IChargeModel chargeModel, Boolean isServerlessEnabled, String globalDatabaseAccountName, Boolean requiresRealCancellationToken, OperationLatencyVerifier operationLatencyVerifier, Boolean isTransportLevelRUMonitoringEnabled, ComputeDiagnosticsLogger computeDiagnosticsLogger, CancellationToken defaultCancellationToken)\r\n   at Microsoft.Azure.Cosmos.Compute.Host.ServiceInteropClientFactory.CreateInteropClient(CosmosClient cosmosClient, IComputeRequestTracker computeRequestTracker, IChargeModel chargeModel, Boolean isServerlessEnabled, String globalDatabaseAccountName, Boolean requiresRealCancellationToken, OperationLatencyVerifier operationLatencyVerifier, Boolean isTransportLevelRUMonitoringEnabled, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.Compute.Runtime.CosmosDBRequestPipeline.GetClientsForRequest(Boolean useApiOperationHandler, CosmosDBRequest request, ICosmosDBTransportRequestContext transportRequestContext, AuthorizationResult authResult, IServiceInteropClientFactory interopClientFactory, ITenantContainerServiceProvider tenantContainerServiceProvider, ICosmosDBConfigProvider tenantConfigurationProvider, Boolean disableRateLimitingResponses, IInteropClient& interopClient, IDocumentClient& documentClient, Exception& exception)"}
RequestUri: https://shibayantest.sqlx.cosmos.azure.com/;
RequestMethod: GET;
Header: Authorization Length: 86;
Header: x-ms-date Length: 29;
Header: Cache-Control Length: 8;
Header: User-Agent Length: 84;
Header: x-ms-version Length: 10;
Header: Accept Length: 16;

ActivityId: ccc03c32-b19b-4ecc-8e59-0fd6c6835818, Request URI: /, RequestStats: , SDK: Windows/10.0.19043 cosmos-netstandard-sdk/3.19.1);'
```

**Comment by ealsur** [comment]
@shibayan The stack trace is not from the SDK

System.ArgumentException: Cannot pass CancellationToken.None when requiresRealCancellationToken is true
at Microsoft.Azure.Cosmos.Compute.Core.InteropClient.InteropClient..ctor(CosmosClient cosmosClient, Boolean isServerlessEnabled, Boolean requiresRealCancellationToken, CancellationToken defaultCancellationToken)

Apparently your application type (InteropClient) requires you to pass a cancellationtoken, but you are not passing it on ReadItem?

**Comment by ealsur** [comment]
Re-opening, as it seems this error stack trace is not from your application, but it's not from the SDK either.

**Comment by ealsur** [comment]
@shibayan - Please file a support ticket or contact the person that enabled the cache preview account, this is not an SDK issue, but a service issue.

**Comment by shibayan** [comment]
@ealsur Thanks for the reply. The same thing happened with the Node.js SDK, so it wasn't a problem with the SDK.
I just opened SR 2106010060004117.

**Comment by kavyako** [comment]
@shibayan Did you enable DisableRatelimitingResponses on your account? If yes, could you please set it to false and the exception will go away. This property does not apply to SQL API.

**Comment by shibayan** [comment]
@kavyako Thank you. I don't know when `DisableRatelimitingResponses` was set, but it was indeed set, so I removed it.
However, the same error seems to continue to occur after deletion. Do I need to recreate the Dedicated gateway?

**Comment by kavyako** [comment]
@shibayan There is a bug on our side where removing the capability DisableRatelimitingResponses does not propagate correctly. 
We will address these bugs in the upcoming releases. 

It looks like the property is no longer set on this account shibayantest and the issue is resolved now. Let me know if that is not the case.

**Comment by shibayan** [comment]
@kavyako Simply deleting the relevant properties resulted in an error, but the error was resolved when I recreated the Dedicated gateway afterwards.

Thank you very much for your help.
