### ISSUE TITLE
CosmosClient does not work properly with emulator unless we provide ConnecMode options

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-cosmos-dotnet-v3#2515]
This constructor will construct the object but the queries will throw exception

```csharp
var client = new CosmosClient(connectionString);
```

Exception: **Method not found: 'Void Microsoft.Azure.Documents.StoreClientFactory..ctor(Microsoft.Azure.Documents.Client.Protocol, Int32, Int32, Microsoft.Azure.Documents.UserAgentContainer, Microsoft.Azure.Documents.ICommunicationEventSource, System.String, Int32, Int32, Int32, Int32, Int32, Int32, Microsoft.Azure.Documents.PortReuseMode, Int32, Int32, Int32, Int32, Boolean, Microsoft.Azure.Documents.RetryWithConfiguration, CallerId, Boolean, Microsoft.Azure.Documents.IAddressResolver, System.TimeSpan, Int32)'.**

While this constructor works file
```csharp
var options = new CosmosClientOptions
                {
                    ConnectionMode = ConnectionMode.Gateway
                };
var client = new CosmosClient(connectionString, options);
```

Appeared in  **Microsoft.Azure.Cosmos 3.19.0 or maybe Emulator  2.11.5.0**

**Comment by j82w** [comment]
The issue is the SDK has 2 dlls and it seems that the one that contains most of the direct logic did not get updated. If you clean your solution and do a build it should work.
