### ISSUE TITLE
Status of GetChangeFeedIterator

### ISSUE THREAD

**Issue by PaulHuizer** [Azure/azure-cosmos-dotnet-v3#2549]
Could anyone explain the status of GetChangeFeedIterator in the .NET SDK
It was in preview in 3.17 as preview. Now it is no longer part of 3.19?
It works like a charm. Can we expect to have this pullmode on the change feed back? Or should we adopt another approach?

**Comment by ealsur** [comment]
It is there in [3.19.0-preview](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.19.0-preview). Being a preview feature, until it's GA, it remains in the preview package only.

FYI, it will GA in 3.20
