### ISSUE TITLE
High value for MaxConcurrency leads to perf degradation

### ISSUE THREAD

**Issue by namadabu** [Azure/azure-cosmos-dotnet-v3#2556]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
This is related to issue #2290  . We execute some of our queries with a `MaxConcurrency` value set to `int.MaxValue` because we want to execute in parallel across all partitions. But we are running into problems for accounts that have a large number of physical partitions (4000+). We get no response from the sdk even after 100 seconds (and we eventually timeout upstream).

We use `FeedIterator.ReadNextAsync()` to get our results. We also inject a custom handler to log some response data. For these queries, it seems like the queries complete running on all the partitions. This is because we can see information such as query duration, RU charge, etc logged via our custom handler. But we never get anything back after that since `FeedIterator.ReadNextAsync()` call does not return.

**To Reproduce**

- Have an account with a large number of physical partitions (4000+ ideally)
- Have a cross-partition query that results in searching through all the partitions
- Execute query with varying values for `MaxConcurrency`. We see potential degradation in performance for values over 1000 (see below for more details).

**Expected behavior**
Expect a successful response before 100 seconds.

**Actual behavior**
We do not receive any response from our call to `FeedIterator.ReadNextAsync()` even after 100 seconds (we timeout the call upstream and hence do not know what happens after).

**Environment summary**
SDK Version: 3.18
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Additional context**
We executed the same SQL query (that our app executes via the SDK) using the Data Explorer via the portal on a CosmosDb account with 4000+ partitions. We used varying values for the "maximum degree of parallelism" option and observed the following behavior:

max degree of parallelism | Response 
---------------------------- | ---------
250 | Successfully completes after ~26 seconds and returns the expected records. 
500 | Successfully completes after ~25 seconds and returns the expected records. 
1000 | Successfully completes after ~90 seconds and returns the expected records.
2147483647 |	"Failed to query item for container : failed to fetch" - with no response code.
5000 | "Failed to query item for container : failed to fetch" - with no response code.
-1 | "Failed to query item for container : failed to fetch" - with no response code.

**Comment by ealsur** [comment]
@namadabu Regarding 

> We executed the same SQL query (that our app executes via the SDK) using the Data Explorer via the portal on a CosmosDb account with 4000+ partitions. We used varying values for the "maximum degree of parallelism" option and observed the following behavior:

Does this mean the Portal is also having this issue of failing with a high degree of concurrency?

**Comment by namadabu** [comment]
> @namadabu Regarding
> 
> > We executed the same SQL query (that our app executes via the SDK) using the Data Explorer via the portal on a CosmosDb account with 4000+ partitions. We used varying values for the "maximum degree of parallelism" option and observed the following behavior:
> 
> Does this mean the Portal is also having this issue of failing with a high degree of concurrency?

@ealsur Yes, we tested it via Azure Portal and ran into the above issues for high degree of concurrency.

**Comment by j82w** [comment]
If you look at your CPU usage it is should be at 100%. You are trying to create 4000 tasks where each task is doing work to go communicate to the physical partition. The CPU is spending a lot of it time just switching between all of these tasks. Even on a 32 core machine that is 125 tasks per a core. This is simply over loading the machine. There is no way to optimize doing that many tasks in parallel which is why there is a maximum concurrency configuration. You need to configure the max concurrency to something your machine can handle.

**Comment by brendankowitz** [comment]
@j82w so is there a way to specify _how many partitions we want results from_ (i.e. all) vs just setting the Max number of tasks? 

It looks like this is the code you're referring to:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c8935ac2f864fb829f5d941dda07c74aec86a677/Microsoft.Azure.Cosmos/src/Pagination/ParallelPrefetch.cs#L35-L44


Sequentially querying through partitions takes minutes to find results. We have the logs confirming hitting all partitions takes seconds (expensive in terms of RU, but possible), there just isn't a way to use what comes back in the SDK.

**Comment by brendankowitz** [comment]
Looks like there is a Semaphore based on processor capacity in other places:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1797aaa2c6ae2f8dd9507b5dbf4faff175a27e98/Microsoft.Azure.Cosmos/src/ReadManyQueryHelper.cs#L78-L112
