### ISSUE TITLE
MalformedContinuationTokenException. Could not find continuation token: OrderByContinuationToken

### ISSUE THREAD

**Issue by jcardena** [Azure/azure-cosmos-dotnet-v3#2557]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I am getting the error below

[Microsoft.Azure.Cosmos.Query.Core.Exceptions.MalformedContinuationTokenException]: Invalid Continuation Token - Could not find continuation token: Microsoft.Azure.Cosmos.Query.Core.ContinuationTokens.OrderByContinuationToken Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Invalid Continuation Token - Could not find continuation token: Microsoft.Azure.Cosmos.Query.Core.ContinuationTokens.OrderByContinuationToken););););); Invalid Continuation Token - Could not find continuation token: Microsoft.Azure.Cosmos.Query.Core.ContinuationTokens.OrderByContinuationToken

**To Reproduce**
Unable to repro at the moment

**Expected behavior**
I would expect the continuation token not to be missing

**Actual behavior**
I get the error above (.net sdk)

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos.3.18.0  (.net sdk)
OS Version: windows

**Additional context**
The error above is all I get so far, i have not been able to get a repro, or logged the token string

Query used looks like this
SELECT * FROM c 
WHERE c.PartitionKey IN ('ABC1','ABC2') 
AND c.RequestTimestamp >= '2021-06-02T20:44:51.777000Z' 
AND c.RequestTimestamp < '2021-06-03T20:44:51.777000Z' 
AND c.Property1 != 'foo' 
ORDER BY c.RequestTimestamp ASC

**Comment by j82w** [comment]
@jcardena can you please add the stack trace of the exception.

**Comment by jcardena** [comment]
This the the only stack I get:

EXCEPTION: [Microsoft.Azure.Cosmos.Query.Core.Exceptions.MalformedContinuationTokenException]: Invalid Continuation Token - Could not find continuation token: Microsoft.Azure.Cosmos.Query.Core.ContinuationTokens.OrderByContinuationToken
    Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Invalid Continuation Token - Could not find continuation token: Microsoft.Azure.Cosmos.Query.Core.ContinuationTokens.OrderByContinuationToken);););););
        Invalid Continuation Token - Could not find continuation token: Microsoft.Azure.Cosmos.Query.Core.ContinuationTokens.OrderByContinuationToken

**Comment by ealsur** [comment]
@jcardena Could you share an example of a Continuation Token value that generates this error?

**Comment by j82w** [comment]
@jcardena just to double check that is the out put from exception.ToString()?

**Comment by ealsur** [comment]
Please reopen when new information is available.
