### ISSUE TITLE
Socket exhaustion issue gets logged as Faulted in App Insights

### ISSUE THREAD

**Issue by mathieuisabel** [Azure/azure-cosmos-dotnet-v3#2561]
**Describe the bug**
When a port exhaustion issue arises and the Cosmos DB client's calls are failing because of that, the only thing we can see in the App Insights telemetry is a status of Faulted for the dependency call.

**To Reproduce**
What happened in our scenario was we had an HttpClient leaking connection in a function app. We noticed some of the HttpClient calls to another API were failing because of socket exhaustion but the Cosmos DB calls were simply showing up as Faulted.

**Expected behavior**
Having the exception as to why the Cosmos client couldn't make the call would be helpful in troubleshooting.

**Actual behavior**
Dependency call status only has generic information.

**Environment summary**
SDK Version: 3.18
OS Version Windows
.NET Core 3.1

**Additional context**
This happened on an Azure Functions Premium plan function app but I suspect the same issue can happen in App Service or VM environments.

**Comment by ealsur** [comment]
The SDK does not own the App Insights integration. If Cosmos DB fails to execute an operation, it throws an exception (CosmosException). 

If App Insights is capturing the Http request and producing some insight that is mentioned as Faulted, that is the interpretation App Insights is surfacing to the users, not something triggered or generated by the Cosmos SDK. The only signal the SDK uses are exceptions.

If anything, the App Insights product should be contacted asking about this behavior. Potentially, the errors the SDK is generating might be tracked under Exceptions.

**Comment by mathieuisabel** [comment]
Hi Matias,

I currently have a support case opened about this and they mentioned it might have something to do with how that condition is bubbling up to App Insights. I would appreciate a minimum of consideration before closing the issue.

Mathieu

**Comment by ealsur** [comment]
@mathieuisabel I understand the scenario but there is nothing actionable we can follow through on this repo and the issue's content has no actionable information.

Not saying the problem in itself should not be considered nor solved, but this repository contains absolutely no code related to App Insights or how App Insights bubbles or surfaces their information.

**Comment by ealsur** [comment]
We can certainly help to shed some light on why a particular exception would be thrown by the SDK and if the case gets to that point and you can share details on the exception being thrown by the SDK we can certainly jump in and help to clarify (and you are free to re-open the issue when that happens). 

But how a particular logging framework/platform interprets that exception and chooses to display it for a user in their UI is something that is out of the scope of this repository and that is why the issue is closed. 

Let's say the SDK is throwing a Timeout exception, and App Insights decides to render that as a Faulted dependency without any other information, there is no code in this repository that can be changed to affect that outcome because it's the choice of App Insights how to render or display it and how much detail to show. Any exception thrown by the SDK, for example, contains the full stack trace and Diagnostics that show all the network requests, but we cannot decide how App Insights shows that information nor alter it here.

**Comment by ealsur** [comment]
One potential repository that might be able to handle your request is the App Insights repository: https://github.com/Microsoft/ApplicationInsights-dotnet

**Comment by mathieuisabel** [comment]
@ealsur Thanks for your response, much appreciated!

 Here's what support was telling me:

_The AI SDK is not going to provide any more details on this dependency call out to Cosmos, so we must rely on whatever tools Cosmos DB has for diagnosing failed connections and database calls._ 

I agree with you, typically I would see the Cosmos exception pop-up in App Insights. It's that particular issue that threw me off a bit where that was only surfaced as Faulted without any accompanying exception. 

From what I'm seeing here, the dependency tracking in App Insights only provides minimal information as to what failed. I'm trying to figure out where is the difference in behavior vs what I'm seeing for the SqlClient for instance where those things are popping up as expected with the appropriate exception/status code information. i.e. For the SqlClient I can see this in the dependency Exception property:

![image](https://user-images.githubusercontent.com/15805484/122414267-0059ff80-cf55-11eb-9990-f56d25e3f8ea.png)

Versus the dependency properties for Cosmos would only show the following:

![image](https://user-images.githubusercontent.com/15805484/122414322-0b149480-cf55-11eb-9443-aa7dc4a474d8.png)

I'm also noticing the LogLevel as Informational, not sure if that's correct. Maybe those are informational and if all retries fail then it pops an error/failure/exception event? Not sure what's the current behavior there. If the Cosmos client has to retry like 3 times for the request to go through, that should probably deserve a warning level.

**Comment by ealsur** [comment]
Again, we don't produce any of those logs or warnings, and if the request is retried and AI wants to issue a warning, I guess it's their call to do so, but we don't have any special wiring or notification mechanism to AI.

If the call to the SDK failed, it throws an Exception. You can catch it and log it on your app code, or if you are letting AI log it, it would be ruled by whatever logic AI thinks it should apply, which in this case, for some reason, doesn't shed the details (we cannot comment on why they don't want to display the details of the error).

I would change my app code to wrap my interactions with the SDK in a try/catch block and log any exceptions myself if the AI automatic logging is not doing it's job correctly. Just make sure when you log any CosmosException, to log the ToString of the exception, not just the Message.
