### ISSUE TITLE
How can we achieve global uniqueness in a container?

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-dotnet-v3#2563]
We have a requirement to create a container with a field that must be globally unique. Cosmos DB currently allows uniqueness per logical partition. What are our options as far as achieving global uniqueness? Is there anything we could do to find a solution to this now?

**Comment by FabianMeiswinkel** [comment]
The only option to enforce global uniqueness of a property is to store the value in the "id" property and use "/id" as the partitionkey. That way the values in the id property will be guaranteed to be globally unique. When using this approach it is important that the limitations (see https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits) for both "id" field (max. 1023 bytes, certain disallowed characters - see https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet) as well as for partition keys (100 bytes for Hash V1 or 2048 bytes for Hash V2 - you need to explicitly opt for long partition keys if the values are larger than 100 bytes - see https://docs.microsoft.com/en-us/azure/cosmos-db/large-partition-keys?tabs=dotnetv3)

**Comment by petro2050** [comment]
@FabianMeiswinkel Thanks for the response. Sadly, our case is actually more complex than this as we need to ensure global uniqueness for 3 fields in the same container. If we were to create 3 different containers (each using the id property for uniqueness), then we couldn't do cross container transactions. It's unfortunate that we won't be able to use Cosmos DB for this particular problem.
