### ISSUE TITLE
UpsertItemStreamAsync accesses  memorystream in thread-unsafe fashion?

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cosmos-dotnet-v3#2564]
Cosmos SDK version: 3.19.0
Platform: Windows 10

When trying to execute a bulk import (with `AllowBulkExection`) of data utilizing Microsoft.IO.RecyclableMemoryStream to dole out memory streams for insertion, I ran into an issue where the memory stream would fail to return blocks, logged here:

https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/issues/172

I have since removed usage of the RecyclableMemoryStream for operations against a client with `AllowBulkExection` enabled; should I just remove the dependency altogether? Does Cosmos SDK use always streams in a way that could break this regardless of `AllowBulkExecution`? Unfortunately the operation I was doing wasn't reliably failing so its hard to reproduce

**Comment by j82w** [comment]
The Cosmos DB SDK is thread safe and does operations concurrently. It does not matter if `AllowBulkExection`  is enabled or disabled. Having it enabled just causes this scenario to appear more frequently. The memory stream pool library needs to be thread safe or it will result in these type of exception. From my understanding RecyclableMemoryStream is not thread safe.
