### ISSUE TITLE
Diagnostics additional information

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2570]
The current diagnostics can have a lot of pages. This issue is to describe adding a summary to the top the diagnostics to make it easier to root cause.

Example of suggestion:

```json
"TotalRequestStats":{
   "TotalRequests": 2,
   "FailedRequests":0,
   "ThrottledRequests":0,
   "MaxCpuUsage": 25,
   "TotalTimeInMs": 50,
   "TotalServiceProcessingTimeInMs": 30,
   "TotalNetworkingTimeInMs": 40,
   "TotalSdkTimeInMs":10
}
```

**Comment by sourabh1007** [comment]
What is the difference between _TotalServiceProcessingTimeInMs_ and _TotalNetworkingTimeInMs_. 

If we all feel like that this information is essential then we can discuss about adding this information in telemetry also.

**Comment by j82w** [comment]
TotalServiceProcessingTimeInMs is the time it took for Cosmos DB backend to process the request. It does not include any networking time like how long it was in the queue waiting to be processed.

TotalNetworkingTime is the time from when the SDK put the request on the wire and until it got a response.

**Comment by ealsur** [comment]
Adding a summary would greatly simplify the areas where customer can laser-focus on.

**Comment by kirankumarkolli** [comment]
How about include the wait-times? (concurrency forced waiting times)

**Comment by j82w** [comment]
@kirankumarkolli can you expand on what you mean by concurrency forced waiting times?

**Comment by kirankumarkolli** [comment]
@asketagarwal what else is pending?

**Comment by asketagarwal** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2732
