### ISSUE TITLE
Microsoft.Azure.Cosmos.Container method throwing System.MissingMethodException method at runtime

### ISSUE THREAD

**Issue by SwatantraYadav** [Azure/azure-cosmos-dotnet-v3#2585]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Getting the below exception:
`Exception: System.MissingMethodException: Method not found: 'System.Linq.IOrderedQueryable`1<!!0> Microsoft.Azure.Cosmos.Container.GetItemLinqQueryable(Boolean, System.String, Microsoft.Azure.Cosmos.QueryRequestOptions)'.`

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version: 3.16.0
OS Version (e.g. Windows, Linux, MacOSX): Linux OS

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
@SwatantraYadav can you please provide the code sample of how you are calling the linq method?

**Comment by sakshibe** [comment]
@j82w 
```
 IQueryable<Rule> linqQueryable = this.container.GetItemLinqQueryable<Rule>(
                false,
                null,
                new QueryRequestOptions()
                {
                    PartitionKey = new PartitionKey(partitionKey)
                })
                .Where(rule => rule.Id == $"{myId}");
```

> @SwatantraYadav can you please provide the code sample of how you are calling the linq method?

**Comment by sourabh1007** [comment]
@sakshibe I hope you are follwoing this [documentation ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.getitemlinqqueryable?view=azure-dotnet) to implement it.

I tried to replicate it but never got this exception for this function. Although, if you set `allowSynchronousQueryExecution `flag as _false_ and try to get the list of objects using `ToList<>()`  In that case `System.NotSupportedException: To execute LINQ query please set allowSynchronousQueryExecution true or use GetItemQueryIterator to execute asynchronously.` which is expected.

**Comment by j82w** [comment]
@sakshibe what .NET version are you using (.NET core 3.1, .NET FX 4.7.2, etc)?

**Comment by sakshibe** [comment]
@sourabh1007 
setting allowSynchronousQueryExecution to true did not work.
We upgraded Microsoft.Azure.Cosmos package to Version="3.19.0" from "3.16.0" and it worked.

**Comment by j82w** [comment]
Closing this since upgrading to the latest SDK fixed the issue.
