### ISSUE TITLE
Auto load balance of CFP push model not working 

### ISSUE THREAD

**Issue by wzzdzr** [Azure/azure-cosmos-dotnet-v3#2586]
**Describe the bug**
I create two instances for the same monitored container with the same processor name, same leasecontainer, same leaseconfiguration and **different** instance name.And then I create 100 thread to generate many createItem requests, and the delegate for the processor would delay for 1 second after processing one change.
But all changes are handled only by one instance.

**To Reproduce**
instance1(in process1):
ChangeFeedProcessor changeFeedProcessor = cosmosClient.GetContainer(databaseName, sourceContainerName)
        .GetChangeFeedProcessorBuilder<ToDoItem>(processorName: "changeFeedSample", HandleChangesAsync)
            .WithInstanceName("consoleHost")
            .WithLeaseConfiguration(new TimeSpan(0,0,7), new TimeSpan(0,0,5), new TimeSpan(0,0,10))
            .WithLeaseContainer(leaseContainer)
            .Build();
instance2(in process2):
ChangeFeedProcessor changeFeedProcessor = cosmosClient.GetContainer(databaseName, sourceContainerName)
        .GetChangeFeedProcessorBuilder<ToDoItem>(processorName: "changeFeedSample", HandleChangesAsync)
            .WithInstanceName("consoleHost2")
            .WithLeaseConfiguration(new TimeSpan(0,0,7), new TimeSpan(0,0,5), new TimeSpan(0,0,10))
            .WithLeaseContainer(leaseContainer)
            .Build();

**Expected behavior**
As mentioned in doc: https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor,
Cosmosdb will automatically distribute changes to all running instances to enable load balance.

**Actual behavior**
Just one of the running instances handles all changes.There seems no load balance.

**Environment summary**
SDK Version: 3
OS Version: Windows 10

**Addition**
I wonder if it is a bug or my method to implement multi instances is incorrect ?

**Comment by wzzdzr** [comment]
like #1853

**Comment by ealsur** [comment]
Reference on public documentation: https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#dynamic-scaling

> ... then the change feed processor will, using an equal distribution algorithm, distribute all the leases in the lease container across all running instances of that deployment unit and parallelize compute. One lease can only be owned by one instance at a given time, so the **maximum number of instances equals to the number of leases**.
