### ISSUE TITLE
CosmosClient NumberOfClientsCreated is not being decremented when clients are disposed.

### ISSUE THREAD

**Issue by ezgambac** [Azure/azure-cosmos-dotnet-v3#2587]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
CosmosClient has a static variable used for tracing which tracks the number of clients created.
This is always being incremented when clients are created, but it's not being decremented when clients are disposed, so if you are creating and disposing clients often, this bit of tracing info is useless as the number doesn't reflect the current number of active clients.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/CosmosClient.cs

**To Reproduce**
Create a bunch of clients, dispose most of them, check diagnostic string.

**Expected behavior**
The number of clients created should match the number of existing clients in order to help debugging.

**Actual behavior**
The diagnostic string shows the number of all clients created ever.

**Environment summary**
SDK Version: 3.18 / 3.20
OS Version (e.g. Windows, Linux, MacOSX): 

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by sourabh1007** [comment]
This is not expected behaviour. Expected behaviour is :Number of clients that were created (doesn't matter their state)

**Comment by ezgambac** [comment]
Shouldn't there be another variable then to track the existing number of clients, or number of disposed clients? Otherwise, when working on incidents and providing diagnostic info to the CosmosDb team the number of clients will be a red herring which will delay investigation.

**Comment by j82w** [comment]
There probably is some corner cases where having active client might be helpful but in most cases it doesn't matter. The recommendations are to use a singleton CosmosClient. If a user is recreating(even if it is properly disposing) or has multiple instance of a CosmosClient it's a red flag for latency and scalability issues because of the internal caches and network connections.

**Comment by j82w** [comment]
I created https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2589 to track adding a active client count in the future.

**Comment by ezgambac** [comment]
In our scenario, we are managing hundreds of cosmos clients (each for a different account). Per other discussions with the cosmos team, it was suggested to store them in a memory cache and dispose them if unused.
So we are using singleton clients per accounts, however, we have multiple accounts.
