### ISSUE TITLE
CosmosDiagnostics: Add active client count

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2589]
The diagnostics currently only has the number of created clients. This issue is to track adding the number of active clients. This way we can see if a user is properly disposing of clients for certain cases.

**Comment by ealsur** [comment]
We need to think about scenarios where the customer is doing:

```
using (CosmosClient client = new CosmosClient(...))
```

If this is executed concurrently and in high numbers it is still a bad scenario, the number of clients created would be high and the fact that the active clients might be low doesn't mean everything is correct. 
Creating and disposing continuously will also lead to Connection limiting or issues, because connections are not closed right away (https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/).

**Comment by j82w** [comment]
There will be a TotalNumberOfClientsCreated and a ActiveNumberOfClientsCreated. If there is some crazy number of total clients it will still be obvious. The active number will tell if the user is disposing of the client or has N clients active which will tell us if they are creating and immediately disposing or have an application with a large amount of clients.

**Comment by ezgambac** [comment]
In our scenario we are having the clients in cache where they are removed after a certain time being unused, so we would be creating and deleting them often.

**Comment by kirankumarkolli** [comment]
There are genuine scenarios to create multiple clients (ex: multiple accounts). The data needs to dis-ambiguate or at-least have right semantics of interpretation. One option is to have normalized counter like per account #clients (MAX)

**Comment by j82w** [comment]
For troubleshooting I think having a total active count is good enough. It doesn't matter if they have 100 SDK instances with 100 different accounts vs 100 SDK instance for the same account. Both will run into the same issue of causing to many connections.

**Comment by ezgambac** [comment]
We are currently tracking total number of active clients globally, not per account, if that helps as a data point.
We also make an effort to have 1 client per account.

**Comment by sourabh1007** [comment]
Recommendation is:  Customer should have 1 Client Instance per Account. if User have multiple accounts, then there is no other way except creating multiple client instances.

So We should collect how many clients is being created per account. E.g. Customer have 10 accounts and then  `TotalNumberOfClientsCreated` and  `ActiveNumberOfClientsCreated` will say 10 instances are being created and active (we will consider it as a bad practice),  but in actual, nothing can be done to reduce the number of client instance.
So These 2 metrics may mislead us. But, if we collect it for each account then, we will have clear picture if we should even look into this direction or not.

**Comment by kirankumarkolli** [comment]
UserAgent do already cover some aspects of it. 
What extra context do we get through this telemetry?

**Comment by j82w** [comment]
The number of created clients is more important than number of active clients. The number of created clients tells if the application is creating multiple instances or recreating instances. If just the number of active instances is recorded it will not be possible to tell if the customer is recreating instance for each call.  This is the most common issue observed. 

The problem with just capturing total number of clients created is there are scenarios where customers by design recreates instances. This usually occurs is middle tier services where the customer is reselling Cosmos DB. In those scenarios it's not possible to tell how many active clients instance exist. The process having 2 active clients vs 200 is a big difference, and can be helpful in root causing certain issues.

**Comment by ezgambac** [comment]
In our scenario, we keep the clients in a timed cache, so if they are not accessed within X minutes, they will be disposed of and recreated on the next access.
This is done to prevent port/connection exhaustion on our side.
