### ISSUE TITLE
string.Compare not supported with LINQ to SQL

### ISSUE THREAD

**Issue by jkendle** [Azure/azure-cosmos-dotnet-v3#2598]
**Describe the bug**

[ExpressionToSQL::VisitBinary](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs#L454) does not support `string.Compare`, only `CompareTo`

We're using the [Microsoft.OData.Core](https://www.nuget.org/packages/Microsoft.OData.Core/7.9.0) nuget package to project OData queries into CosmosDB.

The Microsoft.OData.Core nuget package generates expressions with `string.Compare`

**To Reproduce**

We can reproduce without the OData dependency.

We have an `IQueryable` that fails with a `Where` clause like this:

```c#
.Where(m => string.Compare(m.Id, "hello") == 0)
```

However, it works if we do:

```c#
.Where(m => m.Id.CompareTo("hello") == 0);
```

**Expected behavior**

The SDK should generate valid SQL similar to 
```SQL
Id = "hello"
````

**Actual behavior**

The SDK throws an exception of type `DocumentQueryException` with the message "Method 'Compare' is not supported."

**Environment summary**
SDK Version: 3.20.1
OS Version (e.g. Windows, Linux, MacOSX): MacOS, Linux

**Additional context**

**Comment by kylemc** [comment]
@j82w we patched this feature on a fork and would love to commit it back to the main line. Let us know how best we can engage.

**Comment by j82w** [comment]
@kylemc is there anything blocking you from sending a PR? You should be able to create a PR from the fork.

**Comment by petrv7** [comment]
Any updates? I'm having the same problem while using

```csharp
_container.GetItemLinqQueryable<SomeEntity>().Where(x => string.Compare(x.Id, "something", StringComparison.Ordinal) == 0)
```
