### ISSUE TITLE
It is possible to create an item with id containing '/'. Cannot be read/deleted afterwards

### ISSUE THREAD

**Issue by wiz0u** [Azure/azure-cosmos-dotnet-v3#2606]
**Describe the bug**
You can create an item with id containing a slash, but then you cannot read or delete it.

**To Reproduce**
On a container with partition key path = /id :
`await _container.CreateItemAsync(new { id = "ab/cd", val = "dummy" }, new PartitionKey("ab/cd"));`

This works. I can see with Azure CosmosDB Data Explorer that the item has been added.
However it's impossible to read back the item or even delete it using its id (error 404)
It's still possible to read it through a SELECT (FeedIterator) through.
The only solution to get rid of it is to delete the whole container.

**Expected behavior**
`CreateItemAsync` should throw an exception

**Actual behavior**
CreateItemAsync returns succesfully

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.20.0
OS Version: Windows 10

**Additional context**
I tested also with other restricted characters (\\ # ?), items with id containing those can be created/read/deleted apparently.

**Comment by wiz0u** [comment]
The error 404 when trying to read an item with id containing is a slash is:
`Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 2fc5334c-d620-48ad-b0e0-6ee4a9bdc7bd; Reason: (The value 'dbs/DATABASE/colls/CONTAINER/docs/ab/cb' specified  for query '$resolveFor' is invalid.`

**Comment by j82w** [comment]
This is a Cosmos DB service related issue that the SDK can not fix. It's [documented ](https://docs.microsoft.com/azure/cosmos-db/troubleshoot-not-found#invalid-character-in-an-item-id )that the character is not supported, but the Cosmos DB does not block it. Having all the different SDKs implement the validation is not the proper solution as users can still call the REST API directly, and it will add additional over head to the SDK. Please [contact support](https://aka.ms/azure-support) for additional help.
