### ISSUE TITLE
Unable to use UnixDateTimeConverter as it is marked as internal

### ISSUE THREAD

**Issue by chris31389** [Azure/azure-cosmos-dotnet-v3#2618]
`UnixDateTimeConverter` looks to be an internal class, so we can't access it in the way you suggest.

![image](https://user-images.githubusercontent.com/5216375/125626689-e928ac42-1e9a-4c63-8f50-a9180d535733.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4705078b-fbc5-05e2-91c5-4e73d4f54563
* Version Independent ID: c3c064db-c70b-b441-62e2-93ce6c297b42
* Content: [ContainerProperties.LastModified Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.containerproperties.lastmodified?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/ContainerProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/ContainerProperties.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ealsur** [comment]
@chris31389 can you share a code example? I don't think it is meant to be used publicly.  Newtonsoft.Json has a similar type that you could use? https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Converters_UnixDateTimeConverter.htm

**Comment by chris31389** [comment]
Code example is the same one on the website:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.containerproperties.lastmodified?view=azure-dotnet

```
[Newtonsoft.Json.JsonConverter(typeof(Microsoft.Azure.Documents.UnixDateTimeConverter))]
[Newtonsoft.Json.JsonProperty(NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore, PropertyName="_ts")]
public DateTime? LastModified { get; }
```

If we try to add this to any model we load from cosmos it will fail as `Microsoft.Azure.Documents.UnixDateTimeConverter` is internal.

Your suggestion about using Newtonsoft.Json's `UnixDateTimeConverter` worked and I will use that.

I think the documentation could be updated to use Newtonsoft's `UnixDateTimeConverter`?

**Comment by ealsur** [comment]
The point is, that decorator is not for you to use in your models, but rather internal for the ContainerProperties model (hence it is in those docs).

`_ts` is a property that exists in any document and you can receive it as a number (it is what it is) or a date, using any of the existing DateTimeConverters (like `UnixDateTimeConverter` or write your own), but the raw json is just a number (long).

I don't believe the docs should be changed, those docs are not telling you to use that decorator in your models, it is just the decorator used for ContainerProperties.

**Comment by ealsur** [comment]
Closing as non-actionable. The ContainerProperties is a class from the SDK, not part of any documentation that is telling users to use `Microsoft.Azure.Documents.UnixDateTimeConverter`, there is no need to change the definition of this class.

Users when defining their own models can deserialize `_ts` in any way they want, including using the Newtonsoft `UnixDateTimeConverter` or just getting the integer value (the JSON is just a number).
