### ISSUE TITLE
ObjectDisposedException when you construct, don't use, then dispose quickly

### ISSUE THREAD

**Issue by jbt00000** [Azure/azure-cosmos-dotnet-v3#2619]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
In cases where a CosmosClient is created (in my case via DI), not used (not called for in all code paths), and then disposed (scope is completed), you can get an ObjectDisposedException as the DocumentClient is trying to perform async http calls during the constructor.

**To Reproduce**
The description should have it, but a slow network connection will help.

**Expected behavior**
The constructor should NOT perform any async calls. Also... I sure hope whatever data it is asking for is cached across instances.... 

**Actual behavior**
The constructor kicks off an async http action, the object was not used and is disposed, we have a caught exception (where no exception should happen at all).

**Environment summary**
SDK Version: 3.20.1
OS Version: Windows with .NET Core 3.1

**Additional context**
{"Cannot access a disposed object.\r\nObject name: 'System.Net.Http.HttpClient'."}
Thrown from documentclient.cs ~ line 939
            this.initializeTask.ContinueWith(t =>
#pragma warning restore VSTHRD110 // Observe result of async calls
            {
                DefaultTrace.TraceWarning("initializeTask failed {0}", t.Exception);
            }, TaskContinuationOptions.OnlyOnFaulted);

**Comment by ealsur** [comment]
The constructor does not perform any network operation, are you sure you are not calling any operation during initialization?

**Comment by jbt00000** [comment]
The following constructor is in use:

public CosmosClient(string connectionString, CosmosClientOptions clientOptions = null);

I'm passing in clientOptions with

- ConnectionMode: Direct
- AllowBulkExecution: false
- Serializer: custom one based off of Newtonsoft

Simply having it constructed via DI then going out of scope (without any other calls) triggers this behavior.

**Comment by jbt00000** [comment]
The following HelloWorld will show you the issue:

`using Microsoft.Azure.Cosmos;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var connectionString = args[0];
            for (int z = 0; z < 100; ++z)
            {
                var cco = new CosmosClientOptions();
                cco.AllowBulkExecution = false;
                cco.ConnectionMode = ConnectionMode.Direct;

                using (var cosmos = new CosmosClient(connectionString, cco))
                { 
                
                }
            }
        }
    }
}
`

yields

a stream of 

`DocDBTrace Information: 0 : GlobalEndpointManager: Fail to reach gateway endpoint https://cos-pus-traffk.documents.azure.com/, System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
   at System.Net.Http.HttpClient.CheckDisposed()
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.CosmosHttpClientCore.ExecuteHttpHelperAsync(HttpRequestMessage requestMessage, ResourceType resourceType, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.CosmosHttpClientCore.SendHttpHelperAsync(Func`1 createRequestMessageAsync, ResourceType resourceType, HttpTimeoutPolicy timeoutPolicy, IClientSideRequestStatistics clientSideRequestStatistics, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayAccountReader.GetDatabaseAccountAsync(Uri serviceEndpoint)
   at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetAccountPropertiesHelper.GetAndUpdateAccountPropertiesAsync(Uri endpoint)
`

**Comment by jbt00000** [comment]
In fact... you can see this problem with just a connection string...

`namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var connectionString = args[0];
            for (int z = 0; z < 100; ++z)
            {
                using (var cosmos = new Microsoft.Azure.Cosmos.CosmosClient(connectionString))
                { }
            }
        }
    }
}
`

I am running from my local dev machine and hitting Azure Cosmos from a slow (but not packet dropping) network connection. But as we said, nothing should be going over the network during the constructor anyway.

**Comment by ealsur** [comment]
Thanks for the repro, we'll see if that yields more information.

Is the DI registration as a Singleton or Scoped? It should be Singleton, right? Otherwise you'd be creating multiple instances with time and connections are not released when an instance is disposed (OS ends up closing it some time after) so it could potentially become a problem.

**Comment by jbt00000** [comment]
Singletons are problematic.  Writing a multi-tenanted app in which our tenantId is indirectly passed in, validated, and a connection string looked up. We're also hosted in Azure Functions.

If for performance sake, I need to use a pool of CosmosClients, I'll make that change.

But... the underlying issue of not doing work in constructors remains.  Just would be less visible.

**Comment by ealsur** [comment]
Totally worth investigating, yeah.

In multi-tenant applications I have seen users use a MemoryCache with eviction, so you can still cache the clients, you define an upper bound based on the environment limits but for frequent usages, you reuse the instances.

**Comment by kirankumarkolli** [comment]
@ealsur what are the next steps?

**Comment by kirankumarkolli** [comment]
@ealsur what are next steps?

**Comment by ealsur** [comment]
@kirankumarkolli This seems to be related to the background thread that refreshes the account information. We need to see if it is getting properly stopped or maybe it's due to the loop (5 minutes) not checking the state of the client (disposed) before attempting to refresh. Ideally there should be a CancellationToken communication that should stop the cycle.
