### ISSUE TITLE
FeedIterator.HasMoreResults returns true on count 0

### ISSUE THREAD

**Issue by fnseemas** [Azure/azure-cosmos-dotnet-v3#2629]
**Describe the bug**
FeedIterator.HasMoreResults goes into infinite loop as it returns true even when the count is 0.

**Environment summary**
SDK Version: 3.20.0-preview

**Comment by j82w** [comment]
This is by [design](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance#common-sdk-issues). Most likely you are doing a cross partition query. That means the SDK has to talk to each [partition in Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview#replica-sets). Each page the iterator returns is a response from one of those partitions. The reason it was designed to return the empty page was to give users more points they could stop the query if needed. 

It is recommended for [performance ](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance)to restrict a query to a single partition by setting the partition key in the QueryRequestOptions. This guarantees the query will only ever go to one partition. It's still possible to get a empty in this scenario but this usually means it is a very inefficient query.
