### ISSUE TITLE
Consider removing continuationToken from client methods in favor of AsyncPageable.AsPages(ct)

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cosmos-dotnet-v3#2630]
**Is your feature request related to a problem? Please describe.**

Scenario: Add paging to existing API that works with either Cosmos or Table

Cosmos.GetItemQueryIterator<T>() - accepts a continuation token

Table.QueryAsync<T>() - does not accept a continuation token

AsyncPageable.AsPages() - accepts a continuation token

At first I only thought AsyncPageable supported continuationToken, so I implemented it via AsPages. Then I discovered that GetItemQueryIterator also accepts continuationToken, so I switched to that instead that way I don't have to change my API to return Pages instead of Items.

I then went to implement in Tables and discovered that QueryAsync doesn't accept continuationToken.

From dev newish to Paging in SDK I found it confusing to have continuationToken in some clients (Cosmos) and not in others (Table).

To be consistent in my case I think I'll go with .AsPages(continuationToken) instead of using the Cosmos client impl, that way it is consistent across clients, even though it will change my API from returning a Page instead of Items.

**Describe the solution you'd like**

I would like to see one implementation of continuationToken across the Azure API surface.

**Describe alternatives you've considered**

See above.

**Additional context**

azsdke2e
azsdke2e1

**Comment by j82w** [comment]
The v3 Cosmos SDK was released before the [Azure central SDK team](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core) and AsyncPageable existed. That is why the v3 SDK is not using the newer IAsyncEnumerable interface. 

There are plans to do a v4 SDK which will use the central SDK teams interfaces, but currently there is no eta on when it will be available. The v4 SDK currently available was a beta that has not been updated in a long time. It is currently recommended that all productions scenarios use the v3 SDK.

**Comment by j82w** [comment]
You can do the following as a workaround to get a consistent API: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2214#issue-807557189

**Comment by ealsur** [comment]
V4 already supports AsyncPageable https://github.com/Azure/azure-cosmos-dotnet-v3/blob/v4/Microsoft.Azure.Cosmos/azuredata/Resource/Container/CosmosContainer.cs#L812

We could remove the continuationToken parameter there.

The question though is that AsPages is not required, it is optional. If GetItemQueryIterator would not have the continuationToken parameter, how does a user continue if they don't want to do paging on the continuation? What if I want to read 2 pages (using AsPages) and then drain all the pending results without pages? Should that be a supported scenario (mixing paging and completely draining?)

**Comment by jongio** [comment]
That's a great question.  That I think @tg-msft or @pakrym could help answer.

**Comment by pakrym** [comment]
>Should that be a supported scenario (mixing paging and completely draining?)

We didn't get customer requests for this feature. The current thinking is that when you need to use the continuation you get into the paging world and stay there.

**Comment by tg-msft** [comment]
+1 to what @pakrym said.  Plus anyone who really wants this today could use System.Linq.Async's `SelectMany` to convert the rest of the pages into an `IAsyncEnumerable` after reading one or two manually.  That's my preferred solution unless we start hearing reasons it's a blocker for customers.
