### ISSUE TITLE
Thread starvation detection

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2638]
Summary:
Currently the SDK depends on the CPU collection using Task.Run which releases the thread after collecting the info. This showed there was thread starvation if it was not being collected every 10 seconds. The client telemetry changes improved the collection to hold on to a single thread to always collect CPU so we can disambiguate between high CPU and thread starvation scenario. 

Now there is no way to detect thread starvation scenarios. To fix this gap and to give a clear signal the following 3 APIs should also be collected every 10 seconds with the memory and CPU info.

[GetAvailableThread](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.getavailablethreads?view=netstandard-2.0)
GetMaxThreads
GetMinThreads

The [public documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-dot-net-sdk-request-timeout) will need to be updated to have both the old and new logic to detect thread starvation scenarios.

**Comment by sourabh1007** [comment]
This has been implemented and released in latest Direct package i.e 3.21.0 
https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Direct/
