### ISSUE TITLE
Cosmos Db serialization using JsonPropertyNames

### ISSUE THREAD

**Issue by septst** [Azure/azure-cosmos-dotnet-v3#2645]
Hello,

I am facing an issue with serialization during saving the data. One of the properties ("MyClass") in documents has pascal case naming (as below) whilst all the other properties have camel case naming. I want to retain the naming as it is so as not to break the downstream reporting. I have used " CosmosPropertyNamingPolicy.CamelCase" for my client instance as I am unable to save without it. Now the pascal case name of "MyClass" gets overwritten with "myClass". Please advise.

```
Public class MyModel{
[JsonPropertyName("MyClass")]
public MyClass MyClass{ get; set; }

[JsonPropertyName("transactionId")]
public string TransactionId { get; set; }

[JsonPropertyName("userId")]
public string UserId{ get; set; }

[JsonPropertyName("id")]
public string Id { get; set; }
}
```
I have the below code to replace existing records which I fetch from the db based on some criteria.

```
private static async Task ReplaceMultipleAsync(List<Record> records)
        {
            List<Task> concurrentTasks = new List<Task>();
            foreach (var record in records)
            {
                concurrentTasks.Add(_container.ReplaceItemAsync(record, record.Id, new PartitionKey(record.UserId)));
            }

            await Task.WhenAll(concurrentTasks);
        }
```
With this update, my existing documents gets overwritten and MyClass (pascal case) property becomes myclass (Camel case). I don't want this overwrite as we have a lot of records in our db and they are used by some reporting which would break if this is changed.

Creating cosmos client

```
private static void InitializeCosmosClientInstance(IConfigurationSection configurationSection)
        {
            IConfiguration configuration = new ConfigurationBuilder()
                                                .AddJsonFile("appsettings.json", true, true)
                                                .Build();
            //var playerSection = configuration.GetSection(nameof(Player));

            _databaseName = configurationSection["DatabaseName"];
            _containerName = configurationSection["ContainerName"];
            var account = configurationSection["Account"];
            var key = configurationSection["Key"];
            var options = new CosmosClientOptions()
            {
                AllowBulkExecution = true,
                SerializerOptions = new CosmosSerializationOptions()
                {
                    PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase,
                }
            };
            _cosmosClient = new CosmosClient(account, key, options);
        }
```
Getting container instance
```

 _database = _cosmosClient.GetDatabase(_databaseName);
 _container = _database.GetContainer(_containerName);
```

**Environment summary**
SDK Version: 3.20.1
OS Version: Windows
.Net Core: 3.1

Posted here too: https://stackoverflow.com/questions/68578008/force-use-jsonpropertyname-while-saving-into-cosmosdb

**Comment by j82w** [comment]
What is the error you get when you try to save it without CosmosPropertyNamingPolicy? Cosmos DB only requires the "id" (which must be lower case) and the partition key property. If you have both it should matter if what the other properties are.

Under the covers the SDK is just calling newtonsoft serializer.  https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6a1e27a7ec3d64b2c52d3a95136ee6daca245b6f/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs#L48

```c#
JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings()
            {
                NullValueHandling = cosmosSerializerOptions.IgnoreNullValues ? NullValueHandling.Ignore : NullValueHandling.Include,
                Formatting = cosmosSerializerOptions.Indented ? Formatting.Indented : Formatting.None,
                ContractResolver = cosmosSerializerOptions.PropertyNamingPolicy == CosmosPropertyNamingPolicy.CamelCase
                    ? new CamelCasePropertyNamesContractResolver()
                    : null
            };
```

**Comment by septst** [comment]
The error I am getting without specifying serializer options is 

{"Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: ();"}

Can anyone please suggest a way to serialize as per JsonPropertyNames and save the records/documents into cosmos db collection?

**Comment by ealsur** [comment]
@septst `JsonPropertyName` is coming from Newtonsoft.Json or System.Text.Json? If it's the latter, you are using the wrong serialization engine. V3 SDK works with Newtonsoft.Json.

**Comment by septst** [comment]
> @septst `JsonPropertyName` is coming from Newtonsoft.Json or System.Text.Json? If it's the latter, you are using the wrong serialization engine. V3 SDK works with Newtonsoft.Json. Could you also paste the entire exception details / stack trace?

Thanks for saving me for the second time. Changing the attributes from [JsonPropertyName("***")] that uses System.Text.Json to [JsonProperty("MyClass")] to Newtonsoft.Json did the work. Much appreciated.
