### ISSUE TITLE
ChangeFeedIterator.HasMoreResults returns true even all the change feeds returned

### ISSUE THREAD

**Issue by SamGuoMsft** [Azure/azure-cosmos-dotnet-v3#2649]
**Describe the bug**
After get FeedIterator from GetChangeFeedIterator api, the HasMoreResults always return as true even all the change feeds returned. It is cross partition.

**Expected behavior**
We should get HasMoreResult as false after all the change feeds returned.

**Actual behavior**
The HasMoreResult always return s true even FeedResponse Status Code is not modified.

**Environment summary**
SDK Version: 3.20.1-preview
Windows

**Comment by john-soklaski** [comment]
It appears to be expected based on https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-pull-model#consuming-an-entire-containers-changes:

> Because the change feed is effectively an infinite list of items encompassing all future writes and updates, the value of HasMoreResults is always true

**Comment by SamGuoMsft** [comment]
From response, the status code is notmodified, so we should use that to determine based on document you shared. Is that correct?
