### ISSUE TITLE
UseCosmos with serialization options.

### ISSUE THREAD

**Issue by Ethan0007** [Azure/azure-cosmos-dotnet-v3#2651]
How to add CosmosSerializationOptions on UseCosmos? I want to set PropertyNamingPolicy  to CamelCase.

It seems like the JsonPropertyName is not working at all when saving the data.

![image](https://user-images.githubusercontent.com/12542052/128348847-d20b0b98-abb4-4650-8beb-1cdf5a6c84c2.png)

![image](https://user-images.githubusercontent.com/12542052/128347943-ccbdc05d-0baa-45bf-94c0-a3732e577924.png)

**Comment by ealsur** [comment]
The Cosmos DB use does not use System.Text.Json as default serialization engine, it uses Newtonsoft.Json. Please use Newtonsoft.Json decorators (like JsonProperty) instead.

I don't know what `UseCosmos` is, so you might want to contact the authors of that library/extension, but if you want to use System.Text.Json instead, you can do so by setting a custom serializer (provided you have access to the CosmosClientOptions): https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson
