### ISSUE TITLE
[CosmosDB] Cannot create cosmos db document item correctly with PartitionKey parameter

### ISSUE THREAD

**Issue by Jich2018** [Azure/azure-cosmos-dotnet-v3#2655]
[Enter feedback here]

The sample cannot run successfully with the latest .net library Microsoft.Azure.Cosmos 3.20.1. 

```
ToDoActivity test = new ToDoActivity()
	{
		id = Guid.NewGuid().ToString(),
		status = "InProgress"
	};
	var item = await container.CreateItemAsync<ToDoActivity>(test, new PartitionKey(test.status));
```
The exception message is "Response status code does not indicate success: BadRequest (400); Substatus: 1001; ActivityId: ; Reason: ();"

The diagnostics is as follows:
![image](https://user-images.githubusercontent.com/40649144/127800052-1197fac8-2b75-4af6-bc86-c88c39fefc36.png)

If I add the partitionKey field into the ToDoActivity and remove the PartitionKey argument from the CreateItemAsync call, the call can succeed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daeba9b9-e030-811f-7864-f498d9ec9f08
* Version Independent ID: e8b56ad8-9021-3028-bc10-c8a8c7779b0f
* Content: [Container.CreateItemAsync&lt;T&gt;(T, Nullable&lt;PartitionKey&gt;, ItemRequestOptions, CancellationToken) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createitemasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by j82w** [comment]
@Jich2018 what is the partition key path that you defined on the container?

What tool did you use to visualize the json?

**Comment by ealsur** [comment]
The sample assumes you created the collection with `/status` as the Partition Key Definition. The error you are getting means the partition key you are passing is incorrect and does not match the container/collection definition.

**Comment by Jich2018** [comment]
> @Jich2018 what is the partition key path that you defined on the container?
> 
> What tool did you use to visualize the json?

I created a field name /PartitionKey and use it as the partition key. The json in the screenshot is shown using Linqpad.

**Comment by Jich2018** [comment]
> The sample assumes you created the collection with `/status` as the Partition Key Definition. The error you are getting means the partition key you are passing is incorrect and does not match the container/collection definition.

I created a container with `/PartitionKey` as the partition key. The problem here is, the incoming document doesn't contain this `/PartitionKey`. when saving the document to the cosmos db, I want to provide a partition key for it. e.g.

`{"id": "123", "status": "ready", "group": "Product", "revision": "231"}` is the incoming request. I want to save this document into the cosmos DB and make the `/PartitionKey` group+revision. I think the additional parameter PartitionKey in the method `CreateItemAsync` could help on that, but it seems not?  if that is the case, how can I achieve that?

**Comment by j82w** [comment]
The partition key must be in the document. The partition key is used to figure out which physical machine in Cosmos DB should store the item. The parameter avoids the SDK from needing to extract it from the object which adds overhead. Make sure the partition key value is known so you can do ReadItemAsync. If you end up using query to find the item by id it will not scale because every partition in cosmos db will have to be searched for it.

I think there are two options.
1. The easier solution is to use a wrapper to add the partition key value. You could use something like JObject.
2. Use the stream APIs CreateItemsStreamAsync. You could have a custom JSON Converter which adds the additional field. The stream APIs are optimized for performance so they do not throw exceptions.

**Comment by ealsur** [comment]
This is covered in the docs: https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-bad-request#wrong-partition-key-value

As Jake said, the partition key value needs to be in the document's body, you need to add the property and make the concatenation of group+revision before calling CreateItemAsync. And that same value is what you pass in the partition key parameter too.

**Comment by Jich2018** [comment]
Thanks @ealsur and @j82w for confirmation on this. I will continue with your suggestion and close this.
