### ISSUE TITLE
Continuation Token Exception After Using Skip()

### ISSUE THREAD

**Issue by mumby0168** [Azure/azure-cosmos-dotnet-v3#2657]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Continuation token exception (`MalformedContinuationTokenException`)

**To Reproduce**
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bogus;
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Cosmos.Linq;
using Newtonsoft.Json;
using static System.Console;

var client = new CosmosClient(Environment.GetEnvironmentVariable("ConnectionString"));
var database = client.GetDatabase("paging-db");
var response = await database.CreateContainerIfNotExistsAsync(new ContainerProperties
{
    Id = "people",
    PartitionKeyPath = "/id"
});

int pageSize = 10;
int page = 4;

var options = new QueryRequestOptions {MaxItemCount = pageSize};
string continuationToken = null;


var container = response.Container;

int itemsToSkip = (pageSize * page) - pageSize;

var query = container
    .GetItemLinqQueryable<Person>(false, continuationToken, options)
    .Where(i => i.Age > 5)
    .Skip(itemsToSkip);


int count = await container
    .GetItemLinqQueryable<Person>(false, continuationToken, options)
    .Where(i => i.Age > 5).CountAsync();

WriteLine($"{count} items");

using (var iterator = query.ToFeedIterator())
{
    var feedResponse = await iterator.ReadNextAsync();

    WriteLine($"Page {page} returned {feedResponse.Resource.Count()} results and cost {feedResponse.RequestCharge} RUs");
    WriteLine($"Names in page [{string.Join(",", feedResponse.Resource.Select(i => $"{i.Name} ({i.Age})"))}]");

    continuationToken = feedResponse.ContinuationToken;
    page++;
    
};

query = container
    .GetItemLinqQueryable<Person>(false, continuationToken, options)
    .Where(i => i.Age > 5);

using (var iterator = query.ToFeedIterator())
{
    var feedResponse = await iterator.ReadNextAsync();

    WriteLine($"Page {page} returned {feedResponse.Resource.Count()} results and cost {feedResponse.RequestCharge} RUs");
    WriteLine($"Names in page [{string.Join(",", feedResponse.Resource.Select(i => $"{i.Name} ({i.Age})"))}]");

    continuationToken = feedResponse.ContinuationToken;
    page++;
};

async Task Seed()
{
    Faker<Person> peopleFaker = new();
    peopleFaker
        .RuleFor(p => p.Name, f => f.Name.FullName())
        .RuleFor(p => p.Age, f => f.Random.Number(15, 45));

    List<Person> people = peopleFaker.Generate(100);
    foreach (var person in people)
    {
        await container.CreateItemAsync(person);
    }
}

public class Person
{
    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("age")]
    public int Age { get; set; }
}
```

**Expected behavior**
I expected the token to leave me back on the next page where I left off from the offset query.

**Actual behavior**
A exception is thrown `CosmosException` 400 bad request saying the token is malformed.

**Environment summary**
SDK Version: ` <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.20.1" />`
OS Version: MacOS & Windows

**Additional context**
This has been tested against the real cosmos instance.

I have tested this on netcoreapp3.1 and net5.0.

This may be not be a use for tokens here. Any help would be appreciated.

**Comment by mumby0168** [comment]
I have come across this issue as part of working on this PR for the CosmosRepository implementation it has more details about the issue and how I plan to support paging: https://github.com/IEvangelist/azure-cosmos-dotnet-repository/pull/82

**Comment by j82w** [comment]
@mumby0168 please [contact support](https://aka.ms/azure-support) to help get this issue resolved.

**Comment by mumby0168** [comment]
> @mumby0168 please [contact support](https://aka.ms/azure-support) to help get this issue resolved.

Thanks for the response, guessing this is a feature that should work?

I will have to hold off until next week as I cannot create a ticket, will have to get one of the cloud team to do it from company I work for.

**Comment by mumby0168** [comment]
> @mumby0168 please [contact support](https://aka.ms/azure-support) to help get this issue resolved.

The ticket has been raised case number: 2108090050002251 I just referenced this issue in the request.

**Comment by mumby0168** [comment]
Is there any update on this? I raised the ticket a the beginning of the week not heard anything much back as of yet, any update on this would be appreciated 👍

**Comment by j82w** [comment]
@timsander1 or @sboshra any update?

**Comment by mumby0168** [comment]
> @timsander1 or @sboshra any update?

Thank you, spoke to the person handling my support case said he was still waiting on a response from the product team.

**Comment by neildsh** [comment]
@mumby0168  the code has a bug. You cannot create a continuation token with one query and then attempt to use it with a different query. You must use the _same_ query and settings that were used to create the continuation token.

See corrected code below, which also includes a less error prone alternative:

```

            int pageSize = 10;
            int page = 4;

            QueryRequestOptions options = new QueryRequestOptions { MaxItemCount = pageSize };
            string continuationToken = null;


            int itemsToSkip = (pageSize * page) - pageSize;

            IQueryable<Person> query = container
                .GetItemLinqQueryable<Person>(false, continuationToken, options)
                .Where(i => i.Age > 5)
                .Skip(itemsToSkip);

            int count = await container
                .GetItemLinqQueryable<Person>(false, continuationToken, options)
                .Where(i => i.Age > 5).CountAsync();

            Trace.WriteLine($"{count} items");

            using (FeedIterator<Person> iterator = query.ToFeedIterator())
            {
                FeedResponse<Person> feedResponse = await iterator.ReadNextAsync();

                Trace.WriteLine($"Page {page} returned {feedResponse.Resource.Count()} results and cost {feedResponse.RequestCharge} RUs");
                Trace.WriteLine($"Names in page [{string.Join(",", feedResponse.Resource.Select(i => $"{i.Name} ({i.Age})"))}]");

                continuationToken = feedResponse.ContinuationToken;
                page++;
            };

            QueryDefinition queryDefinition = query.ToQueryDefinition<Person>();
            using (FeedIterator<Person> iterator = container.GetItemQueryIterator<Person>(queryDefinition, continuationToken, options))
            {
                FeedResponse<Person> feedResponse = await iterator.ReadNextAsync();

                Trace.WriteLine($"Page {page} returned {feedResponse.Resource.Count()} results and cost {feedResponse.RequestCharge} RUs");
                Trace.WriteLine($"Names in page [{string.Join(",", feedResponse.Resource.Select(i => $"{i.Name} ({i.Age})"))}]");

                continuationToken = feedResponse.ContinuationToken;
                page++;
            };

            IQueryable<Person> query2 = container
                .GetItemLinqQueryable<Person>(false, continuationToken, options)
                .Where(i => i.Age > 5)
                .Skip(itemsToSkip);

            using (FeedIterator<Person> iterator = query2.ToFeedIterator<Person>())
            {
                {
                    FeedResponse<Person> feedResponse = await iterator.ReadNextAsync();

                    Trace.WriteLine($"Page {page} returned {feedResponse.Resource.Count()} results and cost {feedResponse.RequestCharge} RUs");
                    Trace.WriteLine($"Names in page [{string.Join(",", feedResponse.Resource.Select(i => $"{i.Name} ({i.Age})"))}]");

                    continuationToken = feedResponse.ContinuationToken;
                    page++;
                }
            }
```

**Comment by mumby0168** [comment]
> @mumby0168 the code has a bug. You cannot create a continuation token with one query and then attempt to use it with a different query. You must use the _same_ query and settings that were used to create the continuation token.
> 
> See corrected code below, which also includes a less error prone alternative:
> 
> ```
> 
>             int pageSize = 10;
>             int page = 4;
> 
>             QueryRequestOptions options = new QueryRequestOptions { MaxItemCount = pageSize };
>             string continuationToken = null;
> 
> 
>             int itemsToSkip = (pageSize * page) - pageSize;
> 
>             IQueryable<Person> query = container
>                 .GetItemLinqQueryable<Person>(false, continuationToken, options)
>                 .Where(i => i.Age > 5)
>                 .Skip(itemsToSkip);
> 
>             int count = await container
>                 .GetItemLinqQueryable<Person>(false, continuationToken, options)
>                 .Where(i => i.Age > 5).CountAsync();
> 
>             Trace.WriteLine($"{count} items");
> 
>             using (FeedIterator<Person> iterator = query.ToFeedIterator())
>             {
>                 FeedResponse<Person> feedResponse = await iterator.ReadNextAsync();
> 
>                 Trace.WriteLine($"Page {page} returned {feedResponse.Resource.Count()} results and cost {feedResponse.RequestCharge} RUs");
>                 Trace.WriteLine($"Names in page [{string.Join(",", feedResponse.Resource.Select(i => $"{i.Name} ({i.Age})"))}]");
> 
>                 continuationToken = feedResponse.ContinuationToken;
>                 page++;
>             };
> 
>             QueryDefinition queryDefinition = query.ToQueryDefinition<Person>();
>             using (FeedIterator<Person> iterator = container.GetItemQueryIterator<Person>(queryDefinition, continuationToken, options))
>             {
>                 FeedResponse<Person> feedResponse = await iterator.ReadNextAsync();
> 
>                 Trace.WriteLine($"Page {page} returned {feedResponse.Resource.Count()} results and cost {feedResponse.RequestCharge} RUs");
>                 Trace.WriteLine($"Names in page [{string.Join(",", feedResponse.Resource.Select(i => $"{i.Name} ({i.Age})"))}]");
> 
>                 continuationToken = feedResponse.ContinuationToken;
>                 page++;
>             };
> 
>             IQueryable<Person> query2 = container
>                 .GetItemLinqQueryable<Person>(false, continuationToken, options)
>                 .Where(i => i.Age > 5)
>                 .Skip(itemsToSkip);
> 
>             using (FeedIterator<Person> iterator = query2.ToFeedIterator<Person>())
>             {
>                 {
>                     FeedResponse<Person> feedResponse = await iterator.ReadNextAsync();
> 
>                     Trace.WriteLine($"Page {page} returned {feedResponse.Resource.Count()} results and cost {feedResponse.RequestCharge} RUs");
>                     Trace.WriteLine($"Names in page [{string.Join(",", feedResponse.Resource.Select(i => $"{i.Name} ({i.Age})"))}]");
> 
>                     continuationToken = feedResponse.ContinuationToken;
>                     page++;
>                 }
>             }
> ```

Okay that makes sense thank you for looking at that, I have misunderstood how this works, not quite sure how we will handle this in our library will have to re-think.

Thanks for that 👍
