### ISSUE TITLE
StackOverflowException during Cross-Partition SQL Query with Order By and Offset/Limit

### ISSUE THREAD

**Issue by atomaras** [Azure/azure-cosmos-dotnet-v3#2663]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
StackOverflowException during Cross-Partition SQL query execution that contains OrderBy with Offset/Limit.

![image](https://user-images.githubusercontent.com/3913941/128803978-053f7a5f-816f-4e3e-a3c9-2ea4a38ac6df.png)

**To Reproduce**
Use GetItemQueryIterator and ReadNextAsync to execute a query similar to:

SELECT * 
FROM t 
WHERE filters 
ORDER BY t.objectid ASC 
OFFSET 0 LIMIT 24001

**Expected behavior**
Query should execute successfully without exceptions and without unnecessary delays/latency caused by the SDK.

**Actual behavior**
Query execution takes a long time until it finally crashes with StackOverflowException.

**Environment summary**
SDK Version: 3.20.1
OS Version: Windows

**Additional context**
StackTrace:
[CosmosStackOverflowEx.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/6958732/CosmosStackOverflowEx.txt)

![image](https://user-images.githubusercontent.com/3913941/128804189-299593b1-b669-4c71-949e-a0d9b1431fd7.png)

**Comment by ealsur** [comment]
Please [contact support](https://aka.ms/azure-support) and link this incident to the support request for Query related issues. That would help with the service side investigation of why the query would behave this way.

**Comment by atomaras** [comment]
Done. Created a support ticket as well. Thank you.

**Comment by neildsh** [comment]
@atomaras thank you for creating the ticket. If you have a deterministic way of reproducing this error, would you please share a code snippet ?
