### ISSUE TITLE
System.FormatException (handled) repetitively thrown behind the scenes 

### ISSUE THREAD

**Issue by atomaras** [Azure/azure-cosmos-dotnet-v3#2664]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
While debugging we are consistently noticing a flood of System.FormatExceptions being thrown (although handled)
during request execution.

![image](https://user-images.githubusercontent.com/3913941/128902560-9fff09ab-91b6-40b2-a0f5-a1306999627c.png)

**To Reproduce**
Debug any kind of query execution having Just My Code disabled and look at the VS Output window.

**Expected behavior**
Exceptions that are not dangerous and are handled should not be repetitively thrown and caught.
Usually happens if the logic is inside a loop.
Exception handling has a cost to the performance of the application code so doing it in a loop impacts the hosting app.
Either the exception is important and should bubble up so the app can fix the underlying problem once and for all or
it should be thrown and caught once and only once.

**Actual behavior**
The same code keeps throwing and catching the same exception over and over again impacting application performance.

**Environment summary**
SDK Version: 3:20.1
OS Version: Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
@atomaras are you using AAD or resource tokens?

**Comment by atomaras** [comment]
I use the CosmosClientBuilder ctor overload that accepts a connectionString as so:

![image](https://user-images.githubusercontent.com/3913941/128909502-c4f8c597-a417-46b4-9416-2761df3bb86d.png)

The connectionString is copy pasted as is from the Keys section of the CosmosDB account in the Azure Portal.

**Comment by atomaras** [comment]
There are multiple stacktraces but here is one of them:

![image](https://user-images.githubusercontent.com/3913941/128910654-bfd1c813-1a6e-4f28-8c3d-34e21255102e.png)

**Comment by j82w** [comment]
The exception seems to be coming from the following code which is used to help determine if the resource id is name based or rid based. Need to investigate how this can be done while avoiding the exception. There seems to be no API in .NET standard 2.0 that lets you do a Convert.TryFromBase64String

```c#
public static bool Verify(string id, out byte[] buffer)
        {
            if (string.IsNullOrEmpty(id))
                throw new ArgumentNullException("id");

            buffer = null;

            try
            {
                buffer = ResourceId.FromBase64String(id);
            }
            catch (FormatException)
            { }

            if (buffer == null || buffer.Length > ResourceId.Length)
            {
                buffer = null;
                return false;
            }

            return true;
        }

        public static byte[] FromBase64String(string s)
        {
            return Convert.FromBase64String(s.Replace('-', '/'));
        }
```

**Comment by j82w** [comment]
I have a few ideas on how this can be avoided. The performance improvement will be done in a future release. I don't currently have an eta on when it will get fixed.

**Comment by atomaras** [comment]
That sounds good to me. It's not a show stopper. Just good to have for the overall performance of the SDK.

**Comment by j82w** [comment]
Did you do any performance testing or profiling where this showed up? In the profiling we have do so far it did not show. It's possible the code path we tested avoided this check.

**Comment by ealsur** [comment]
Could this be due to the name of a resource (database, container) containing some invalid character?

**Comment by atomaras** [comment]
This did not arise from an performance testing. This was easily visible by simply debugging. 
I know exception throwing and handling has a cost especially when it is in a loop.

I don't think there is anything in the account that looks like a culprit

![image](https://user-images.githubusercontent.com/3913941/128936020-5ceb387e-adc1-4f7d-9b5f-375bb80f0732.png)

**Comment by j82w** [comment]
@ealsur my current idea is to add a new internal constructor to the document service request. Where the database, container, and resource type are passed into it with the flag if it is name based or not. Then add a check to the container ctor to tell if it is name based or rid based. That way it only has to do the check once.

**Comment by NaluTripician** [comment]
In the most recent version of the SDK we have switched to an exceptionless model so these errors should no longer be occurring in the background. Please feel free to re-open this issue if that is not the case.
