### ISSUE TITLE
when will ContinuationToken be null in item of leaseContainer?

### ISSUE THREAD

**Issue by wzzdzr** [Azure/azure-cosmos-dotnet-v3#2667]
**Describe the bug**
I create a new changeFeedProcessor, and create another thread to modify items and wait for these changes.
But It couldn't receive changes. I found Continuation is null in processor item in leaseContainer.
And I check log and found that this processor seems work fine.
So I wonder when will ContinuationToken be null in item of leaseContainer ?

**Additional context**
logs:
DocDBTrace Information: 0 : The store is initialized
DocDBTrace Information: 0 : Processor started.
DocDBTrace Information: 0 : Host 'SuperHandler' 1 partitions, 1 hosts, 1 available leases, target = 1, min = 0, max = 0, mine = 0, will try to take 1 lease(s) for myself'.
DocDBTrace Information: 0 : Lease with token 0: acquired
DocDBTrace Information: 0 : Lease with token 0: renewer task started.
...

processor item in leaseContainer
{
    "id": "unit-test-b77048DeploymentProcessorcustom-resource-sample.documents.azure.comXXXXXX",
    "_etag": "\"130091e8-0000-1900-0000-XXXXXX\"",
    "LeaseToken": "0",
    "Owner": "SuperHandler",
    "ContinuationToken": null,
    ...
}

Thanks for your help!

**Comment by j82w** [comment]
Can you provide a sample of how you are creating the ChangeFeed Processor and starting the processor?

Did you start the processor? https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#implementing-the-change-feed-processor
`await changeFeedProcessor.StartAsync();`

**Comment by ealsur** [comment]
ContinuationNull means there were never any changes being processed for that lease. If you have a collection with multiple physical partitions, you will have multiple leases, each lease covering one partition.

When CFP detects changes for any partition, it reads them, sends them to your delegate and, **if your delegate does not fail to process them**, updates the lease.

Make sure your delegate code is not throwing an unhandled exception (add a try/catch) block there and since you are collecting traces, you can share more of those attached in this issue.

**Comment by wzzdzr** [comment]
> Can you provide a sample of how you are creating the ChangeFeed Processor and starting the processor?
> 
> Did you start the processor? https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#implementing-the-change-feed-processor
> `await changeFeedProcessor.StartAsync();`

yeah I have started the processor

**Comment by wzzdzr** [comment]
> ContinuationNull means there were never any changes being processed for that lease or when they did, they failed with an unhandled exception in your delegate. If you have a collection with multiple physical partitions, you will have multiple leases, each lease covering one partition.
> 
> When CFP detects changes for any partition, it reads them, sends them to your delegate and, **if your delegate does not fail to process them**, updates the lease.
> 
> Make sure your delegate code is not throwing an unhandled exception (add a try/catch) block there and since you are collecting traces, you can share more of those attached in this issue.

hi, these are more traces. Does it mean that it couldn't get any change from source container?
DocDBTrace Information: 0 : RNTBD: ConnectUnicastPortAsync connecting to rntbd://cdb-ms-prod-eastasia1-XXXXXX
DocDBTrace Information: 0 : RNTBD connection established XXXXX
DocDBTrace Information: 0 : RNTBD SSL handshake complete XXXXXX
The thread 0x5824 has exited with code 0 (0x0).
DocDBTrace Error: 0 : Operation will NOT be retried. Current attempt 0, Status Code: NotModified 
DocDBTrace Error: 0 : Operation will NOT be retried. Current attempt 0, Status Code: NotModified 
DocDBTrace Error: 0 : Operation will NOT be retried. Current attempt 0, Status Code: NotModified 
TpTrace Verbose: 0 : 10388, 9, 2021/08/12, 14:21:57.718, 685544945830, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:1XXXXX] localEndPoint: [::ffff:XXXXX]

**Comment by wzzdzr** [comment]
oh I seem find bugs in my program. Thanks to @ @ealsur @j82w  you guys help.
