### ISSUE TITLE
Rename QueryOptions -> FeedOptions

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#267]
Rename QueryOptions -> FeedOptions. Need discussion since change feed, read feed, and query are all feed operations but have different options.

**Comment by kirankumarkolli** [comment]
Multi Item response is -> FeedIterator

Where as request options are specific to operation(CF, Feed, Query)
- Possible for feed to go Cross-partition as well in future
- Query semantics specifics: low precision, CTlimitinKB, query feature flag's etc...
