### ISSUE TITLE
Integrated cache urls dont work with managed identity

### ISSUE THREAD

**Issue by briandunnington** [Azure/azure-cosmos-dotnet-v3#2677]
**Describe the bug**
Using the new integrated cache urls (aaaa.sqlx.cosmos.com) with the `CosmosClient` constructor that accepts a `TokenCredential` results in an error:

`The resource principal named https://aaaa.sqlx.cosmos.azure.com was not found in the tenant named xxxxx-xxxx-xxxx-xxxxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.`

**To Reproduce**
Use an integrated cache url along with the `CosmosClient` constructor that accepts a `TokenCredential`

**Expected behavior**
A valid token can be obtained and used to authenticate database operations.

**Actual behavior**
The following error is thrown:

`The resource principal named https://aaaa.sqlx.cosmos.azure.com was not found in the tenant named xxxxx-xxxx-xxxx-xxxxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.`

**Environment summary**
SDK Version: 3.20.1
OS Version: Windows

**Additional context**
Switching back to the regular account url (for the same database) results in the correct behavior. Using the constructor that accepts the database key also works (but we cannot use it for security compliance issues).

**Comment by j82w** [comment]
This doesn't appear to be an issue with the SDK, but rather with the service. Please [contact support](https://aka.ms/azure-support) to get the service team involved.

**Comment by JereStay** [comment]
This was filed for the same issue: https://github.com/Azure/azure-cli/issues/19269 and that has a comment that links to https://github.com/Azure/azure-sdk-for-net/issues/13603 which seems to be the feature missing in the SDK to enable this use case. If it is indeed working for the python sdk as described in the azure-cli issue.

**Comment by timsander1** [comment]
Hi @JereStay , the integrated cache does not support RBAC yet. This is a temporary limitation in the preview. I'll add a note to the limitations section about this here - https://docs.microsoft.com/en-us/azure/cosmos-db/dedicated-gateway#limitations. Apologies for missing this earlier!

**Comment by j82w** [comment]
Closing the issue since it's a service limitation since it is in preview.
