### ISSUE TITLE
How to use Shims for unit testing ? 

### ISSUE THREAD

**Issue by Sonali00000** [Azure/azure-cosmos-dotnet-v3#2686]
**Describe the solution you'd like**
Our previous code (with DocumentClient) use shims for unit testing where it is using assembly "Microsoft.Azure.Documents.Client.TransientFaultHandling.Fakes;" and creating a object of  "StubIReliableReadWriteDocumentClient" and using "ShimDocumentClientExtensions" for retry mechanism

How should we use this in new .net v3 SDK?

**Comment by ealsur** [comment]
Please reopen with more insights, as stated before, you can mock the V3 SDK without issues.
