### ISSUE TITLE
Is there any method to get changes since specific etag?

### ISSUE THREAD

**Issue by wzzdzr** [Azure/azure-cosmos-dotnet-v3#2689]
**Is your feature request related to a problem? Please describe.**
I am currently try to replace k8s by cosmosdb change feed for some reason. Previously I use kubernetes' to watch changes from specific resourceVersion. And etag of cosmosdb item looks like resourceVersion of kubernetes object. However, currently change feed pull model only support starting fetching changes from continuationToken, which I think may be somehow generated from etag.
So I was wondering that is there any method to get changes since specific etag？or is there any method to generate continuationToken with specific tag.
Thanks in advance.

**Comment by ealsur** [comment]
Short answer: no.

Change Feed can either be started to read from the beginning (full container history), from a particular point in time, or from now (when the iterator is created). Once the iterator is created, it will produce a continuation token that contains enough information to, at a later point, continue (https://docs.microsoft.com/en-us/azure/cosmos-db/sql/change-feed-pull-model#saving-continuation-tokens).
