### ISSUE TITLE
FeedIterator ReadNextAsync() throws NullReferenceException

### ISSUE THREAD

**Issue by gonzaleznicolas** [Azure/azure-cosmos-dotnet-v3#2703]
**Describe the bug**
FeedIterator ReadNextAsync() throws a NullReferenceException.
The output CosmosDiagnostics object suggests that the problem is a timeout. If that is the problem, ReadNextAsync() should throw an exception that is more indicative of the problem.

**Expected behavior**
If that is the problem, ReadNextAsync() should throw an exception that is more indicative of the problem.

**Actual behavior**
A NullReferenceException is thrown.

**Environment summary**
SDK Version: 3.19.0
OS Version: Windows

**Stack Trace and Cosmos Diagnostics**
 ---> System.Exception: Could not complete method 'GetByIds'
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Documents.GoneAndRetryWithRequestRetryPolicy`1.TryHandleResponseSynchronously(DocumentServiceRequest request, TResponse response, Exception exception, ShouldRetryResult& shouldRetryResult)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy, Func`2 prepareRequestAsyncDelegate)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RouterHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.ExecuteHttpRequestAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`3 callShouldRetryException, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(String resourceUriString, ResourceType resourceType, OperationType operationType, RequestOptions requestOptions, ContainerInternal cosmosContainerCore, FeedRange feedRange, Stream streamPayload, Action`1 requestEnricher, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.ExecuteItemQueryAsync(String resourceUri, ResourceType resourceType, OperationType operationType, Guid clientQueryCorrelationId, FeedRange feedRange, QueryRequestOptions requestOptions, SqlQuerySpec sqlQuerySpec, String continuationToken, Boolean isContinuationExpected, Int32 pageSize, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Pagination.NetworkAttachedDocumentContainer.MonadicQueryAsync(SqlQuerySpec sqlQuerySpec, FeedRangeState`1 feedRangeState, QueryPaginationOptions queryPaginationOptions, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Pagination.PartitionRangePageAsyncEnumerator`2.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Pagination.BufferedPartitionRangePageAsyncEnumerator`2.PrefetchAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Pagination.BufferedPartitionRangePageAsyncEnumerator`2.GetNextPageAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Pagination.PartitionRangePageAsyncEnumerator`2.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Pagination.CrossPartitionRangePageAsyncEnumerator`2.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CrossPartition.Parallel.ParallelCrossPartitionQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.LazyQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.NameCacheStaleRetryQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CatchAllQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.ReadNextAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](ITrace trace, Func`2 task) 
 CosmosDiagnostics: {"name":"Typed FeedIterator ReadNextAsync","id":"eb937901-bd4a-4260-98e8-b661971adc47","caller info":{"member":"OperationHelperWithRootTraceAsync","file":"ClientContextCore.cs","line":219},"start time":"05:37:50:255","duration in milliseconds":32134.0886,"data":{"Client Configuration":{"Client Created Time Utc":"2021-09-01T17:37:32.3339345Z","NumberOfClientsCreated":1,"User Agent":"cosmos-netstandard-sdk/3.19.0|3.19.1|02|X64|Microsoft Windows 10.0.14393|.NET Core 3.1.18|N|","ConnectionConfig":{"gw":"(cps:1000, urto:3600, p:False, httpf: False)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: False, pr: ReuseUnicastPort)","other":"(ed:False, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[])"}},"children":[{"name":"Create Query Pipeline","id":"02fe59c2-4ab4-4ece-84b2-d512503bad01","caller info":{"member":"TryCreateCoreContextAsync","file":"CosmosQueryExecutionContextFactory.cs","line":85},"start time":"05:37:50:278","duration in milliseconds":899.3363,"children":[{"name":"Get Container Properties","id":"1d909d6b-f46b-4e1d-9392-4472c84befc1","caller info":{"member":"GetCachedContainerPropertiesAsync","file":"ClientContextCore.cs","line":366},"start time":"05:37:50:282","duration in milliseconds":312.756,"children":[{"name":"Get Collection Cache","id":"f266eb85-5fdd-4f17-b524-bf9df6e41857","caller info":{"member":"GetCollectionCacheAsync","file":"DocumentClient.cs","line":546},"start time":"05:37:50:284","duration in milliseconds":1.5077,"children":[{"name":"Waiting for Initialization of client to complete","id":"edc37e11-0097-40d5-8d07-e6168c04ccbf","caller info":{"member":"EnsureValidClientAsync","file":"DocumentClient.cs","line":1416},"start time":"05:37:50:285","duration in milliseconds":0.1018}]},{"name":"Read Collection","id":"1d112406-161e-4651-90dd-02b93308801d","caller info":{"member":"ReadCollectionAsync","file":"ClientCollectionCache.cs","line":68},"start time":"05:37:50:336","duration in milliseconds":242.168,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2021-09-01T17:37:50.5031928Z","EndTimeUTC":"2021-09-01T17:37:50.5031980Z","RequestUri":"https://-cosmosdb-qa-centralus.documents.azure.com/dbs/_QA/colls","ResourceType":"Collection","HttpMethod":"GET","ActivityId":"01c921ec-c36d-4caa-92f6-22453e366691","StatusCode":"OK"}]}}}]},{"name":"Service Interop Query Plan","id":"d9bef0fa-3566-4ddd-b1d0-ed3a9e0d16d9","caller info":{"member":"GetQueryPlanWithServiceInteropAsync","file":"QueryPlanRetriever.cs","line":58},"start time":"05:37:50:617","duration in milliseconds":267.3489},{"name":"Get Partition Key Ranges","id":"20d5fecf-0cbb-4c35-8ef3-c002e048ab16","caller info":{"member":"GetTargetPartitionKeyRangesAsync","file":"CosmosQueryClientCore.cs","line":242},"start time":"05:37:50:891","duration in milliseconds":232.737,"children":[{"name":"Try Get Overlapping Ranges","id":"7d4daaec-3910-4885-bdd6-56d746f0454b","caller info":{"member":"TryGetOverlappingRangesAsync","file":"PartitionKeyRangeCache.cs","line":53},"start time":"05:37:50:905","duration in milliseconds":216.9974,"children":[{"name":"Read PartitionKeyRange Change Feed","id":"2960d40c-e85a-4592-b360-3802cdae3974","caller info":{"member":"ExecutePartitionKeyRangeReadChangeFeedAsync","file":"PartitionKeyRangeCache.cs","line":239},"start time":"05:37:51:014","duration in milliseconds":64.5246,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2021-09-01T17:37:51.0691033Z","EndTimeUTC":"2021-09-01T17:37:51.0691039Z","RequestUri":"https://-cosmosdb-qa-centralus.documents.azure.com/dbs/D7hAAA==/colls/D7hAALoL+RM=/pkranges","ResourceType":"PartitionKeyRange","HttpMethod":"GET","ActivityId":"892ef13d-69a7-4050-a127-010d0013d541","StatusCode":"OK"}]}}},{"name":"Read PartitionKeyRange Change Feed","id":"66613cba-67fe-43f0-91f1-f56a1ae5df0a","caller info":{"member":"ExecutePartitionKeyRangeReadChangeFeedAsync","file":"PartitionKeyRangeCache.cs","line":239},"start time":"05:37:51:096","duration in milliseconds":5.7648,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2021-09-01T17:37:51.1016316Z","EndTimeUTC":"2021-09-01T17:37:51.1016321Z","RequestUri":"https://-cosmosdb-qa-centralus.documents.azure.com/dbs/D7hAAA==/colls/D7hAALoL+RM=/pkranges","ResourceType":"PartitionKeyRange","HttpMethod":"GET","ActivityId":"e39d1795-e216-46af-92c1-c03b9c25b78c","StatusCode":"NotModified","ReasonPhrase":"Not Modified"}]}}}]}]}]},{"name":"MoveNextAsync","id":"28d9c19c-db43-418d-bc6c-23a63f0906b7","caller info":{"member":"MoveNextAsync","file":"CrossPartitionRangePageAsyncEnumerator.cs","line":113},"start time":"05:37:51:208","duration in milliseconds":31179.8532,"children":[{"name":"Prefetching","id":"23c31a86-45a5-4425-ab21-61eb1ed37e26","caller info":{"member":"PrefetchInParallelAsync","file":"ParallelPrefetch.cs","line":31},"start time":"05:37:51:228","duration in milliseconds":0.1151},{"name":"[05C1D325499320,05C1DBB76DDBB0) move next","id":"8d5b903e-f8b4-487d-a765-299f87d75528","caller info":{"member":"MoveNextAsync","file":"PartitionRangePageAsyncEnumerator.cs","line":49},"start time":"05:37:51:235","duration in milliseconds":31152.9635,"children":[{"name":"Prefetch","id":"65860883-c585-45e4-a977-c9a4bdbbf71c","caller info":{"member":"PrefetchAsync","file":"BufferedPartitionRangePageAsyncEnumerator.cs","line":50},"start time":"05:37:51:240","duration in milliseconds":31147.8341,"children":[{"name":"[05C1D325499320,05C1DBB76DDBB0) move next","id":"28f3da1d-28a8-427f-988c-7dd31150395f","caller info":{"member":"MoveNextAsync","file":"PartitionRangePageAsyncEnumerator.cs","line":49},"start time":"05:37:51:240","duration in milliseconds":31147.6806,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","id":"ec61c478-16cd-4bca-8a4c-09daad13ebd3","start time":"05:37:51:261","duration in milliseconds":31127.1017,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","id":"59c792ed-d8e8-44a1-a30f-93499cd41b7c","start time":"05:37:51:281","duration in milliseconds":31107.3539,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","id":"d79abea9-0bbd-4a46-b7f9-9b34bf2b2d49","start time":"05:37:51:374","duration in milliseconds":31014.1586,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","id":"860a957a-76b4-4603-b7f1-99301da41618","start time":"05:37:51:506","duration in milliseconds":30881.3802,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","id":"0d34dcde-f547-49fa-a82d-abcdd557f99c","start time":"05:37:51:506","duration in milliseconds":30881.3416,"children":[{"name":"Microsoft.Azure.Documents.ServerStoreModel Transport Request","id":"84cac459-5020-42ef-b9a6-183e19c078b2","caller info":{"member":"ProcessMessageAsync","file":"TransportHandler.cs","line":109},"start time":"05:37:51:516","duration in milliseconds":30871.5345,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":["https://-cosmosdb-qa-centralus.documents.azure.com/"],"FailedReplicas":["rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14375/apps/88bc3414-7aba-40b2-a5d5-fc6320b6b18a/services/9a34bddb-212a-430b-9e48-dbeb7bd2b566/partitions/9ecaec82-2893-44ba-9a0a-6279557ca707/replicas/132719682054430208s/","rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14332/apps/88bc3414-7aba-40b2-a5d5-fc6320b6b18a/services/9a34bddb-212a-430b-9e48-dbeb7bd2b566/partitions/9ecaec82-2893-44ba-9a0a-6279557ca707/replicas/132746108201566536s/","rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14058/apps/88bc3414-7aba-40b2-a5d5-fc6320b6b18a/services/9a34bddb-212a-430b-9e48-dbeb7bd2b566/partitions/9ecaec82-2893-44ba-9a0a-6279557ca707/replicas/132744354437093518s/","rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14026/apps/88bc3414-7aba-40b2-a5d5-fc6320b6b18a/services/9a34bddb-212a-430b-9e48-dbeb7bd2b566/partitions/9ecaec82-2893-44ba-9a0a-6279557ca707/replicas/132744783805920816p/"],"AddressResolutionStatistics":[{"StartTimeUTC":"2021-09-01T17:37:51.7977234Z","EndTimeUTC":"2021-09-01T17:37:51.7990011Z","TargetEndpoint":"https://-cosmosdb-qa-centralus.documents.azure.com//addresses/?$resolveFor=dbs%2fD7hAAA%3d%3d%2fcolls%2fD7hAALoL%2bRM%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=2"}],"StoreResponseStatistics":[{"ResponseTimeUTC":"2021-09-01T17:37:57.9564330Z","ResourceType":"Document","OperationType":"Query","LocationEndpoint":"https://-cosmosdb-qa-centralus.documents.azure.com/","StoreResult":{"ActivityId":"ee5771d2-c836-43de-9f29-942c7c606618","StatusCode":"Gone","SubStatusCode":"Unknown","LSN":-1,"PartitionKeyRangeId":null,"GlobalCommittedLSN":-1,"ItemLSN":-1,"UsingLocalLSN":true,"QuorumAckedLSN":-1,"SessionToken":null,"CurrentWriteQuorum":-1,"CurrentReplicaSetSize":-1,"NumberOfReadRegions":-1,"IsClientCpuOverloaded":false,"IsValid":false,"StorePhysicalAddress":"rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14375/apps/88bc3414-7aba-40b2-a5d5-fc6320b6b18a/services/9a34bddb-212a-430b-9e48-dbeb7bd2b566/partitions/9ecaec82-2893-44ba-9a0a-6279557ca707/replicas/132719682054430208s/","RequestCharge":0,"BELatencyInMs":null,"TransportException":"A client transport error occurred: SSL negotiation timed out. (Time: 2021-09-01T17:37:57.9536594Z, activity ID: ee5771d2-c836-43de-9f29-942c7c606618, error code: SslNegotiationTimeout [0x0008], base error: HRESULT 0x80131500, URI: rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14375/, connection: 10.218.0.4:56489 -> 52.182.138.1:14375, payload sent: False, CPU history: (2021-09-01T17:37:34.9247174Z 32.367), CPU count: 2)"}},{"ResponseTimeUTC":"2021-09-01T17:38:03.4471370Z","ResourceType":"Document","OperationType":"Query","LocationEndpoint":"https://-cosmosdb-qa-centralus.documents.azure.com/","StoreResult":{"ActivityId":"ee5771d2-c836-43de-9f29-942c7c606618","StatusCode":"Gone","SubStatusCode":"Unknown","LSN":-1,"PartitionKeyRangeId":null,"GlobalCommittedLSN":-1,"ItemLSN":-1,"UsingLocalLSN":true,"QuorumAckedLSN":-1,"SessionToken":null,"CurrentWriteQuorum":-1,"CurrentReplicaSetSize":-1,"NumberOfReadRegions":-1,"IsClientCpuOverloaded":false,"IsValid":false,"StorePhysicalAddress":"rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14332/apps/88bc3414-7aba-40b2-a5d5-fc6320b6b18a/services/9a34bddb-212a-430b-9e48-dbeb7bd2b566/partitions/9ecaec82-2893-44ba-9a0a-6279557ca707/replicas/132746108201566536s/","RequestCharge":0,"BELatencyInMs":null,"TransportException":"A client transport error occurred: The connection attempt timed out. (Time: 2021-09-01T17:38:03.4172370Z, activity ID: 1685a9bc-e504-4d1f-853f-a974942ccefc, error code: ConnectTimeout [0x0006], base error: HRESULT 0x80131500, URI: rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14332/, connection: <not connected> -> rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14332/, payload sent: False, CPU history: (2021-09-01T17:37:34.9247174Z 32.367), CPU count: 2)"}},{"ResponseTimeUTC":"2021-09-01T17:38:11.6796291Z","ResourceType":"Document","OperationType":"Query","LocationEndpoint":"https://-cosmosdb-qa-centralus.documents.azure.com/","StoreResult":{"ActivityId":"ee5771d2-c836-43de-9f29-942c7c606618","StatusCode":"Gone","SubStatusCode":"Unknown","LSN":-1,"PartitionKeyRangeId":null,"GlobalCommittedLSN":-1,"ItemLSN":-1,"UsingLocalLSN":true,"QuorumAckedLSN":-1,"SessionToken":null,"CurrentWriteQuorum":-1,"CurrentReplicaSetSize":-1,"NumberOfReadRegions":-1,"IsClientCpuOverloaded":false,"IsValid":false,"StorePhysicalAddress":"rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14058/apps/88bc3414-7aba-40b2-a5d5-fc6320b6b18a/services/9a34bddb-212a-430b-9e48-dbeb7bd2b566/partitions/9ecaec82-2893-44ba-9a0a-6279557ca707/replicas/132744354437093518s/","RequestCharge":0,"BELatencyInMs":null,"TransportException":"A client transport error occurred: The connection attempt timed out. (Time: 2021-09-01T17:38:11.4389377Z, activity ID: dcc70f16-0ea2-489d-bc4b-b7788bd05235, error code: ConnectTimeout [0x0006], base error: HRESULT 0x80131500, URI: rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14058/, connection: <not connected> -> rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14058/, payload sent: False, CPU history: (2021-09-01T17:37:34.9247174Z 32.367), CPU count: 2)"}},{"ResponseTimeUTC":"2021-09-01T17:38:20.6631255Z","ResourceType":"Document","OperationType":"Query","LocationEndpoint":"https://-cosmosdb-qa-centralus.documents.azure.com/","StoreResult":{"ActivityId":"ee5771d2-c836-43de-9f29-942c7c606618","StatusCode":"Gone","SubStatusCode":"Unknown","LSN":-1,"PartitionKeyRangeId":null,"GlobalCommittedLSN":-1,"ItemLSN":-1,"UsingLocalLSN":true,"QuorumAckedLSN":-1,"SessionToken":null,"CurrentWriteQuorum":-1,"CurrentReplicaSetSize":-1,"NumberOfReadRegions":-1,"IsClientCpuOverloaded":false,"IsValid":false,"StorePhysicalAddress":"rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14026/apps/88bc3414-7aba-40b2-a5d5-fc6320b6b18a/services/9a34bddb-212a-430b-9e48-dbeb7bd2b566/partitions/9ecaec82-2893-44ba-9a0a-6279557ca707/replicas/132744783805920816p/","RequestCharge":0,"BELatencyInMs":null,"TransportException":"A client transport error occurred: Sending the request timed out. (Time: 2021-09-01T17:38:20.6605955Z, activity ID: ee5771d2-c836-43de-9f29-942c7c606618, error code: SendTimeout [0x000E], base error: HRESULT 0x80131500, URI: rntbd://cdb-ms-prod-centralus1-fd18.documents.azure.com:14026/, connection: 10.218.0.4:56533 -> 52.182.138.1:14026, payload sent: False, CPU history: (2021-09-01T17:37:34.9247174Z 32.367), CPU count: 2)"}}],"HttpResponseStats":[{"StartTimeUTC":"2021-09-01T17:37:51.7989266Z","EndTimeUTC":"2021-09-01T17:37:51.7989269Z","RequestUri":"https://-cosmosdb-qa-centralus.documents.azure.com//addresses/?$resolveFor=dbs%2fD7hAAA%3d%3d%2fcolls%2fD7hAALoL%2bRM%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=2","ResourceType":"Document","HttpMethod":"GET","ActivityId":"ee5771d2-c836-43de-9f29-942c7c606618","StatusCode":"OK"}]}}}]}]}]}]}]}]}]}]}]}]}

**Comment by j82w** [comment]
Please upgrade to [3.20.1](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-3201-preview---2021-06-29). This bug was fixed in the following PR: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2562
