### ISSUE TITLE
The given path's format is not supported

### ISSUE THREAD

**Issue by DynamicDave** [Azure/azure-cosmos-dotnet-v3#2704]
I'm unable to run my Xamarin.Forms app on a (locally connected) iPhone. I get the error:
Unable to copy file "_D:\SystemData\nuget\microsoft.azure.cosmos\3.20.1\contentFiles\any\netstandard2.0\ThirdPartyNotice.txt" to "C:\Users\username\AppData\Local\Temp\Xamarin\HotRestart\Signing\CosmosDbTst.iOS.app\out\Payload\CosmosDbTst.iOS.app\\D:\SystemData\nuget\microsoft.azure.cosmos\3.20.1\contentFiles\any\netstandard2.0\ThirdPartyNotice.txt_". The given path's format is not supported.
I've changed the location of my nuget packages (D:\SystemData\nuget\) but that isn't the issue. There is something strange in the 2nd path; it says C:\users\<snip>\\D:\SystemData... So that's not correct. 

To reproduce, create a new Xamarin.Forms project (any type), install the Microsoft.Azure.Cosmos 3.20.1 package. 
Connect to a Mac and try to run the app on an iPhone.

The expected behavior is being able to build to an iPhone.
And the actual behavior is that it's not possible. 

My environment:
Microsoft.Azure.Cosmos 3.20.1
Windows 10, VS 2019 Pro, Xamarin Forms project, connected to a Mac.

**Comment by sourabh1007** [comment]
It doesn't look like SDK issue. 

Looks like Xamarin is appending 2 paths while looking for ThirdpartyNotice.txt. ( I don't know why it would do it)
