### ISSUE TITLE
RBAC access - Custom role?

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#2705]
On the screen below, what role must I give to an account to allow it to read / write records from Cosmos? I've tried all the Cosmos and DocumentDb ones, and I'm getting the following exception...

"Request is blocked because principal [61ad4795-fb43-4e77-860e-d806bf5aba5e] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]"

This doesn't require a custom role does it?

![CosmosRoles](https://user-images.githubusercontent.com/2799232/132254452-bba62935-22d3-4ff0-a508-4217f8caad1e.png)

**Comment by ealsur** [comment]
This is not related to the SDK, but the roles are not in the Portal yet.

This article shows how to add the custom roles: https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#built-in-role-definitions

You can either create your own or use one of the pre-created ones, and then run the CLI or Powershell commands to assign that to the principal:

https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#using-the-azure-cli-1

![image](https://user-images.githubusercontent.com/1633401/132376505-d4e3a6b2-544c-4110-8043-1f73a0121369.png)

**Comment by nichatur** [comment]
The roles you are looking at provide access to the Cosmos DB control plane. For data plane access, please look at built-in data plane Role Definitions to grant access at the link shared by my colleague above https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#built-in-role-definitions

**Comment by dilisha** [comment]
@nichatur, @ealsur   Thank you for pointing this out. Helped me in figuring out why my code was not working. 
I would like to know, is there any reason why roles for data plane access like _Cosmos DB Built-in Data Contributor_ are not present in azure portal ?

**Comment by ealsur** [comment]
@dilisha if I understand the code correctly, the token gets refreshed, right @j82w ?

**Comment by j82w** [comment]
The token will refreshed automatically in the background.

**Comment by dilisha** [comment]
@ealsur @j82w Thank you for confirming on the token. Could you please clarify my first question too(I would like to know, is there any reason why roles for Cosmos DB data plane access like Cosmos DB Built-in Data Contributor are not present in azure portal?)?

**Comment by ealsur** [comment]
@dilisha That I don't know, this repo is just for the .NET SDK. @ThomasWeiss do you know if these roles will get added to the Azure Portal at any point?

**Comment by ealsur** [comment]
@jackbond @dilisha Is this thread good to be closed? I don't think the topic was directly related to the SDK and it already contains answers to your questions regarding how to setup AAD on CLI.

**Comment by jackbond** [comment]
Knowing that the work is underway to add these roles to the portal is good, just not very developer friendly as it stands. Feel free to close it.
