### ISSUE TITLE
Not able to get session token from ItemResponse<T>

### ISSUE THREAD

**Issue by DhruvBarot** [Azure/azure-cosmos-dotnet-v3#2707]
Hi,
We have durable azure function, where one function write into cosmos database and another one is read from it, 
for the strong consistency in the same session, Azure provide default consistency as session, Now
We are trying to pull the session token from ItemResponse and trying to use same token in while read the document.

but while try to get session token it's give us null. 

Below are the sample code to describe how the 

`var response = await container.UpsertItemAsync(instance, partitionKey, cancellationToken: cancellationToken);
 if (response.StatusCode == HttpStatusCode.OK || response.StatusCode == HttpStatusCode.Created)
{
return response.Headers.Session
}`

Please advise us how we can use session consistency in such a case.

**Comment by j82w** [comment]
@DhruvBarot just to clarify is the default account consistency strong or session? Do you have any custom CosmosClientOptions configured?

**Comment by DhruvBarot** [comment]
@j82w we have default account consistency as session, and we haven't any custom configuration in cosmos CosmosClientOptions.

**Comment by ealsur** [comment]
@DhruvBarot Are you using Bulk mode? Which SDK version are you using?

**Comment by DhruvBarot** [comment]
@ealsur No, we are not using the bulk mode, 
We are using version 3.17 also, I have tried with 3.20 but still have the same behavior.

**Comment by ealsur** [comment]
@DhruvBarot Can you share a complete minimal repro (no keys) of the issue? Some code we can run to test it? Have you tried with the Emulator or other account and does the behavior repeat?
The SessionToken property is just returning the header value.

**Comment by j82w** [comment]
I added validation that the session token is not null on the upsert operation: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2729

**Comment by DhruvBarot** [comment]
@ealsur It's working fine, Our one of the developer enable bulk while registering cosmos client to DI.
Thanks for the quick response, I am closing this ticket.
