### ISSUE TITLE
Increase concurrency level of available regions when CosmosClient starts

### ISSUE THREAD

**Issue by ezgambac** [Azure/azure-cosmos-dotnet-v3#2715]
CosmosClient takes between 35s to 70s to figure out if an account exists (when it doesn't) when ApplicationRegion is used.
From checking the source code, and talking to @ealsur , it seems CosmosClient is using 2 tasks to concurrently check regions, and when an account doesn't exists, the DNS error takes a long time to show up.

**Describe the solution you'd like**
Increase the concurrency level of the check to a much higher number, maybe even N, where N is the number of azure regions.

The logic should be something like this:

```csharp

            List<string> locations = this.GetLocations().SortByDistance(this.ApplicationRegion);

            List<Task<string>> taskList = new(locations.Count);

            foreach (var location in locations)
            {
                taskList.Add(CheckEndpoint(location));
            }

            await Task.WhenAll(taskList).ConfigureAwait(false);

            var selectedLocation = taskList.FirstOrDefault(t => t.IsCompletedSuccessfully).Result ?? throw new Exception("No locations available);
```

**Comment by j82w** [comment]
What the use case for connecting to accounts that do not exist?

A better fix might be to ensure the SDK does not retry on 404 scenarios. 

The maximum concurrency should be limited to the number of processors. If SDK does a fan out to 30+ regions in parallel it may cause thread starvation or CPU spikes further increasing the latency. 

The reason it is limited to 2 tasks 
1. The happy scenario the SDK should be talking to the primary region so no concurrency is needed.
2. The primary region is down \ in bad state. The SDK will try to go to the primary region then it will start 2 tasks to go to the  secondary regions to get the account info. If the best practices are followed the secondary region will be one of those two closest regions to the primary region. The SDK shouldn't have to go through all the regions.

**Comment by ezgambac** [comment]
Our service manages over 300 cosmosdb accounts, so it would be nice to know if a given account doesn't exist.
The problem is that it's taking between 35s-70s for the Cosmos client to figure out the account doesn't exist.
From what I talked to @ealsur, it seems Cosmos client can't figure out if a 404 means bad region, or account doesn't exist, hence it tries everything.
Also, for a non existing account, it might not get 404 at all, but a dns resolution error, which again, might be either bad region or no account.

**Comment by j82w** [comment]
As a temporary mitigation if you know which regions the account is you can specify the [ApplicationPreferredRegions] (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/090af9c26a04d2d208e5443554c6c01d81482dd6/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L119). That way the SDK will only search those few regions instead of all the possible regions.

Do we know why it taking 35 to 70 seconds? If the account doesn't exist the call should be fast since the service isn't doing any work.

**Comment by ezgambac** [comment]
From logs in our service, it shows that it tried every possible endpoint before exploding.

**Comment by ezgambac** [comment]
One or more errors occurred. (Name or service not known (sanjaiga-global-3135f7d.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-centralus.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-westcentralus.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-southcentralus.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-westus2.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-northcentralus.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-westus.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-canadacentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-eastus.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-canadaeast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-eastus2.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-uksouth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-northeurope.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-ukwest.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-francecentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-switzerlandwest.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-westeurope.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-japaneast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-germanywestcentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-japanwest.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-francesouth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-germanynorth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-switzerlandnorth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-norwaywest.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-swedencentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-swedensouth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-norwayeast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-koreacentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-koreasouth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-brazilsouth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-brazilsoutheast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-australiaeast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-eastasia.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-australiacentral2.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-australiacentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-southeastasia.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-australiasoutheast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-uaecentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-southindia.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-uaenorth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-centralindia.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-westindia.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-jioindiawest.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-jioindiacentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-westus3.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-southafricanorth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-southafricawest.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-chinaeast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-ussecwest.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-usnatwest.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-usseceast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-usnateast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-usdodeast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-usgovtexas.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-usgovarizona.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-usdodcentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-centraluseuap.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-chinaeast2.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-chinanorth.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-eastusslv.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-chinanorth2.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-germanynortheast.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-germanycentral.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-eastus2euap.documents.azure.com:443)) (Name or service not known (sanjaiga-global-3135f7d-usgovvirginia.documents.azure.com:443))

**Comment by ezgambac** [comment]
There are 65 regions it seems, so if each request took between around half a second to a little over a second to fail, it would explain the 35s-75s

**Comment by j82w** [comment]
Is it possible for you to use the [ApplicationPreferredRegions](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/090af9c26a04d2d208e5443554c6c01d81482dd6/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L119) as a temporary solution until the fix is released?

**Comment by ezgambac** [comment]
This is currently affecting a background job, not our hotpath, so this is not breaking us as of now, and application preferred regions would be a tricky fix because all the 300 accounts have different settings, and to know the settings, we need the cosmos client.

**Comment by j82w** [comment]
I'll try to get a PR out later this week.

**Comment by kirankumarkolli** [comment]
Azure is expanding more rapidly, more and more are expected to be present. The Discovery work will keep increasing. The only reliable way is to limit to the regions to discover leveraging ApplicationPreferredRegions API as @j82w suggested above.
