### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#2726]
Do you guys have any sort of roadmap published?

Here's the problem I'm facing. Despite being "planned in the roadmap" since 2018, you guys still haven't moved the spatial classes into a separate NuGet package, https://github.com/Azure/azure-cosmos-dotnet-v3/issues/15

Unfortunately, I've now got developers using NetTopologySuite.IO.GeoJSON because they don't want to pull in your SDK because it's close to 4MB. While it serializes identically, I can't query the objects when they make it into Cosmos.

So where does that leave me? I just cloned your repository, thinking maybe I could extract the spatial classes. I could do that, but it doesn't look like there is a way to inject stuff into your expression parsing logic. I've reached the point where I'm thinking, screw it, I'll just clone your code, do a little refactoring, and publish my own version of Microsoft.Azure.Cosmos to our private NuGet.

To be blunt, THIS IS INSANITY, but waiting until 2087 for a half day refactor (if that much) is simply no longer an option.

**Comment by ealsur** [comment]
@jackbond Thanks for the feedback, I would love to understand more about the scenario and some clarification would be nice.

It seems the text seems to define two main group of developers:

* You mentioned that some developers don't want to pull the SDK due to size, how are they interacting with the Cosmos DB account then? Are they using some REST API wrapper?
* Are they only pulling the SDK in for the Spatial types and nothing else? Is that the reason to ask for a Spatial-only package?
* If they are not using the SDK, how is the expression parsing logic in the SDK related? 
 
Would be good to dissect the scenario you are describing a bit more to understand how all these are related or if they are separate issues.

**Comment by jackbond** [comment]
I don't think our organization is unique in need to pass spatial data up and down our stack. Our database guys could care less about a 4MB dependency, but our Blazor guys sure do. So our classes end up with a hodge podge, some using Cosmos spatial types and others using NetTopologySuite spatial types.

All across Microsoft and Azure NuGet packages are isolating lower level classes and interfaces into separate NuGet packages, like Microsoft.Extensions.Configuration.Abstractions.

Here's another example. I've got a microservice that manages a class which contains a Microsoft.Azure.Cosmos.Spatial.Point. It never touches the database, not its job. But CosmosClient and 4MB of other baggage gets deployed along with it.

I've cloned this repository, moved the Spatial classes to a separate NuGet package, it's 13KB. Given that there's already a template to go by, i.e. azure-pipelines-encryption.yml, I estimate it would take me less than two hours to isolate the spatial stuff, including the build pipelines.

I'm already in discussions to stop using the Microsoft.Azure.Cosmos NuGet package in favor of a custom build, which is honestly the last thing in the world I want to be wasting my time on.

**Comment by ealsur** [comment]
Thanks for the clarification, it paints a clearer picture.

If I understand correctly, you use these Spatial types (from NetTopologySuite or SDK or some other source) across your Domain in multiple Models, and at some point, they reach the component that interacts with the SDK to perform some operation (maybe queries?), and you have problems with some of these operations. Could you detail which operations and how are you executing them? Are they queries? Are you using Linq or query texts?

**Comment by ealsur** [comment]
Got it, so the issue would be, LINQ queries when the model uses Spatial types that are not the SDK ones, thanks for all the detailed scenario.

Could you share some of these errors and maybe a small example of how to reproduce them? Not trying to divert the ask for a separate package, but I think the issue might be LINQ related on how it interacts with these other Spatial types. Are you using System.Text.Json by any chance as serialization engine?

**Comment by jackbond** [comment]
Having looked at your code, I can tell you the problem is in ExpressionToSQL.cs, line 696 of the releases/3.21.0 branch. Your code will only do the proper SQL spatial translations when the spatial classes are derived from Microsoft.Azure.Cosmos.Spatial.Geometry. That's why if even just that class were in a separate NuGet, this problem goes away. I don't know if there's a need, but I imagine being able to inject a type / interface into the ExpressionToSQL logic would be useful. Idea being, developers could instruct the Cosmos SDK to use custom logic for user defined types during the LINQ to SQL expression parsing stage. As far as System.Text.Json, we're not using it yet (as you can see in the code for DocumentWrapper.)

![image](https://user-images.githubusercontent.com/2799232/133146397-13053a0c-5aca-4358-b42a-f8aeb189d649.png)

**Comment by ealsur** [comment]
So basically the scenario is: LINQ Geo expressions only work with the Spatial types that are part of the SDK.

**Comment by jackbond** [comment]
Bingo. So your options are

1) Move the spatial types to a separate NuGet.
2) Provide a mechanism for external types to be handled during LinqToSql expression processing.
3) Both, whereby the internal spatial types are treated the same as external types.

If you do 2 or 3, then someone is going to write the expression processing code for the Microsoft.Spatial types, share that code, and then the Cosmos team can simply make it official and save themselves a bunch of work. :)

**Comment by jackbond** [comment]
As far as I can tell, this requires

1. Adding Microsoft.Azure.Cosmos.Spatial to the InternalsVisibleTo list for Microsoft.Azure.Cosmos.Direct (5 seconds)
2. Creating a new class library, Microsoft.Azure.Cosmos.Spatial (10 seconds)
3. Moving the spatial files from Microsoft.Azure.Cosmos to the new class library (15 seconds)
4. Added NuGet reference to new library (5 seconds)
5. Add TypeForwardedTo attributes for moved classes (about 30 classes, so 8 to 10 minutes)
6. Fix a few unit tests, e.g. ClientDllNamespaceTest and ContractChanges (a lot of your unit tests fail due to connectivity issues, so hard to gauge. So how about half a day?) 
7. Creating yml and adding build pipeline (maybe 5 minutes)

All and all, not difficult or time consuming. It makes it incredibly frustrating that in three years nobody has tackled this. I can't do steps 1 and 7, but if someone creates me a branch and gives me permissions, I'll happily do the work.

**Comment by ealsur** [comment]
At this moment there are no plans to ship the Spatial types as a separate package in the immediate term, it is not part of the roadmap or planning in terms of prioritization.
For V4, work alignment needs to follow the Azure SDK team, and https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2755 captures the essence and the problem described in this thread. In V4 we can do breaking changes and extract the Spatial types from the SDK.
