### ISSUE TITLE
ClientTelemetryTests flaky

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2728]
The trace even shows the CPU as NaN: DocDBTrace Information: 0 : System Usage recorded by telemetry is : {"systemHistory":[{"dateUtc":"2021-09-13T15:25:24.0897374Z","cpu":NaN,"memory":11566524.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.6365,"availableThreads":32764,"minThreads":8,"maxThreads":32767}}]}

This causes the following assert to fail.
Assert.AreEqual failed. Expected:<2>. Actual:<1>. System Information Count doesn't Match; [{"metricInfo":{"metricsName":"MemoryRemaining","unitName":"MB","mean":10821.59375,"count":1,"min":10822.0,"max":10822.0,"percentiles":{"50":10821.6240234375,"90":10821.6240234375,"95":10821.6240234375,"99":10821.6240234375,"99.9":10821.6240234375}}}]

**Comment by sourabh1007** [comment]
It will return CPU usage as NaN only in following cases:
- If Native Function (Windows : kernel32.dll, Linux: /proc/stat) is not returning any value.
- If totalElapsedTime is zero means difference between 2 consecutive reading are zero.

Related PR is out to fix this isue

**Comment by sourabh1007** [comment]
Fix will be available in the latest Direct package.

**Comment by j82w** [comment]
Please keep this issue open until the direct package is updated and the assert is re-enabled in the test. Without an issue to track it the assert will not get enabled again.
