### ISSUE TITLE
ItemRequestOptions not flowing to custom RequestHandler RequestMessage when AllowBulkExecution is set to true

### ISSUE THREAD

**Issue by radmint** [Azure/azure-cosmos-dotnet-v3#2741]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I've been trying to access the `.Properties` field on the `RequestMessage` in my custom type deriving from `RequestHandler` after setting the `ItemRequestOptions.Properties` and passing it into `Container.ReadItemAsync()` but every time I would inspect the `RequestMessage.Properties` field while debugging, it was empty.

I read through the source code for `ReadItemAsync` and noticed we [perform a different operation if `BulkOperationIsSupported`](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d215f138c5d885d6b02f36034951ae1ea55ae218/Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs#L295). When stepping into the method called in this conditional, I saw that we [cast `RequestOptions` to `ItemRequestOptions` here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d215f138c5d885d6b02f36034951ae1ea55ae218/Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs#L489). When I attempt this cast in my own code, the result of the cast is always `null`. I suspect this could be the source of the issue.

When I removed the `AllowBulkExecution=true` bool from my `CosmosClientOptions` setup, the `RequestMessage.Properties` in my custom `RequestHandler` had the properties correctly set from what I passed in from `ItemRequestOptions`. 

**To Reproduce**
1. Set up `CosmosClient` and pass in `CosmosClientOptions` with `AllowBulkExcution` set to true.
2. Add a custom request handler which derives from `RequestHandler`
3. Add a `Container.ReadItemAsync()` method and pass in an object of type `ItemRequestOptions` with any properties populated.
4. Put a breakpoint in the custom request handler `.SendAsync()` method.
5. Run the program so that it calls the `ReadItemAsync()` method.
6. When the breakpoint is hit in `.SendAsync()`, inspect `RequestMessage.Properties`.

**Expected behavior**
I expected the fields from the `ItemRequestOptions` passed into `Container.ReadItemAsync()` to be available on the `RequestMessage` in my custom `RequestHandler`.

**Actual behavior**
None of my `ItemRequestOptions` fields were being populated on the `RequestMessage` when inside my custom `RequestHandler.SendAsync()` method.

**Environment summary**
SDK Version: 3.21.0
OS Version: Windows

**Additional context**
![image](https://user-images.githubusercontent.com/23347804/133860518-2cc3edda-ea20-45f5-b566-39a07289a301.png)

**Comment by ealsur** [comment]
This is by design on Bulk. When Bulk mode is on, the operation does not equal the actual network request. The network request is a grouping of operations, which Properties would be sent then? An aggregation of all the Properties of all the grouped operations? What if they have Properties with the same key?

**Comment by j82w** [comment]
@ealsur should it throw an exception if bulk is enabled and properties are set to let users know it can not be passed through?

**Comment by j82w** [comment]
One option is to use the request position as the key and then have a the value be the dictionary of each individual request.

Dictionary<string, object>(){
     "0", itemOperation.RequestOptions.Properties,
     "1", itemOperation.RequestOptions.Properties,
     etc...
}

**Comment by ealsur** [comment]
> @ealsur should it throw an exception if bulk is enabled and properties are set to let users know it can not be passed through?

Yeah, just like we do for the other unsupported options: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs#L128

**Comment by radmint** [comment]
Sounds good, thanks for the info, feel free to close!
