### ISSUE TITLE
DeleteItemAsync<T> responds with Response status code does not indicate success: NotFound

### ISSUE THREAD

**Issue by Gor92** [Azure/azure-cosmos-dotnet-v3#2742]
**Describe the bug**
Trying to delete an item from container with DeleteItemAsync<T> from GenericRepository class using the following:

public virtual async ValueTask<bool> BulkRemove(IEnumerable<T> entities, CancellationToken cancellationToken)
        {

            foreach (var item in entities)
            {
                await _container.DeleteItemAsync<T>(item.Id, new PartitionKey(item.Rid), cancellationToken: 
                cancellationToken).ConfigureAwait(false);
            }

            return true;
        }
When I trying to delete an item which doesn't met the searching conditions there is no any exception, but after adding an item which mets searching conditions I'm accepting 
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: ; Reason: ();

**To Reproduce**
Create 2 containers, implement a GenericRepository Class and implement 2 Repositories for each container. add an item into the first container, add 2 items to second one which holds the Id of the first container Item. After attempting to delete an items from second container WHERE container1ItemId = "some GUID" the response is Response status code does not indicate success: NotFound (404);

Response from Cosmos DB

Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: ; Reason: ();
   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.ProcessMessage[T](ResponseMessage responseMessage, Func`2 createResponse)
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.CreateItemResponse[T](ResponseMessage responseMessage)
   at Microsoft.Azure.Cosmos.ContainerCore.DeleteItemAsync[T](String id, PartitionKey partitionKey, ITrace trace, ItemRequestOptions requestOptions, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](ITrace trace, Func`2 task)
   at Microsoft.Azure.Cosmos.ClientContextCore.OperationHelperWithRootTraceAsync[TResult](String operationName, RequestOptions requestOptions, Func`2 task, TraceComponent traceComponent, TraceLevel traceLevel)
   at ABB.Cart.Data.Abstraction.GenericRepository`1.BulkRemove(IEnumerable`1 entities, CancellationToken cancellationToken) in C:\Users\Gor_Grigoryan\source\repos\Abb-Cart-Service\src\ABB.Cart.Data\Abstraction\GenericRepository.cs:line 218
   at ABB.Cart.Core.BLL.Implementations.CartLineItemsBl.ClearCartAsync(String cartId, CancellationToken cancellationToken) in C:\Users\Gor_Grigoryan\source\repos\Abb-Cart-Service\src\ABB.Cart.Core\BLL\Implementations\CartLineItemsBL.cs:line 85
   at ABB.Cart.Core.Services.CartService.ClearCartAsync(String cartId, CancellationToken cancellationToken) in C:\Users\Gor_Grigoryan\source\repos\Abb-Cart-Service\src\ABB.Cart.Core\Services\CartService.cs:line 151
   at ABB.Cart.Api.Controllers.CartController.ClearCart(String id, CancellationToken cancellationToken) in C:\Users\Gor_Grigoryan\source\repos\Abb-Cart-Service\src\ABB.Cart.Api\Controllers\CartController.cs:line 277
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
--- Cosmos Diagnostics ---{"name":"DeleteItemAsync","id":"c828bff9-562c-48ba-a3ea-5789a7aa0360","caller info":{"member":"OperationHelperWithRootTraceAsync","file":"ClientContextCore.cs","line":219},"start time":"08:10:50:423","duration in milliseconds":495.5039,"data":{"Client Configuration":{"Client Created Time Utc":"2021-09-19T20:10:47.7630181Z","NumberOfClientsCreated":18,"User Agent":"cosmos-netstandard-sdk/3.20.1|3.19.3|10|X64|Microsoft Windows 10.0.19042|.NET 5.0.10|N|F 00000001|","ConnectionConfig":{"gw":"(cps:50, urto:0, p:False, httpf: False)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: False, pr: ReuseUnicastPort)","other":"(ed:False, be:True)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[])"}},"children":[{"name":"Get Collection Cache","id":"2a8d9a2d-eb51-4b56-8bf0-4c591c2ef327","caller info":{"member":"GetCollectionCacheAsync","file":"DocumentClient.cs","line":546},"start time":"08:10:50:423","duration in milliseconds":0.0013},{"name":"Batch Dispatch Async","id":"ee90a1eb-2492-48c0-9f53-47aff618be87","caller info":{"member":"DispatchAsync","file":"BatchAsyncBatcher.cs","line":116},"start time":"08:10:50:539","duration in milliseconds":379.4125,"children":[{"name":"Using Wait","id":"049ea38f-899f-45b0-9d88-33b8f8d40a2f","caller info":{"member":"UsingWaitAsync","file":"Extensions.cs","line":189},"start time":"08:10:50:539","duration in milliseconds":0.0032},{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","id":"f9918c70-9cef-46c3-ad9e-969ff97a005f","start time":"08:10:50:539","duration in milliseconds":374.0725,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","id":"d8177f98-c8b6-423d-ae0c-db0d1803ccc3","start time":"08:10:50:539","duration in milliseconds":374.0416,"data":{"CPU Load History":{"CPU History":"(2021-09-19T20:10:00.0060741Z 8.333), (2021-09-19T20:10:09.9994303Z 20.238), (2021-09-19T20:10:20.0161249Z 27.734), (2021-09-19T20:10:30.0066339Z 5.159), (2021-09-19T20:10:40.0055900Z 3.571), (2021-09-19T20:10:49.9966609Z 14.286)"}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","id":"e97c4cfe-2ac2-4479-814e-adbba4f91550","start time":"08:10:50:539","duration in milliseconds":374.0352,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","id":"b4bb466b-10d9-4c3e-9bd3-9869ff1eb1cc","start time":"08:10:50:539","duration in milliseconds":374.0139,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","id":"facca49d-9ccd-4889-be59-5530cfd0f8c8","start time":"08:10:50:539","duration in milliseconds":374.0094,"children":[{"name":"Microsoft.Azure.Documents.ServerStoreModel Transport Request","id":"34820fb9-cbc0-4d53-b680-a80c87996de2","caller info":{"member":"ProcessMessageAsync","file":"TransportHandler.cs","line":109},"start time":"08:10:50:539","duration in milliseconds":373.9543,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":1,"Uri":"rntbd://cdb-ms-prod-westeurope1-fd61.documents.azure.com:14348/apps/ccba42f0-40a9-487a-9f2f-e4174ead669e/services/79aa7543-967e-43f8-9a89-44fa00590eed/partitions/de32f61b-79d9-4310-97fb-530a885c0cfb/replicas/132748020287596808s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-westeurope1-fd61.documents.azure.com:14145/apps/ccba42f0-40a9-487a-9f2f-e4174ead669e/services/79aa7543-967e-43f8-9a89-44fa00590eed/partitions/de32f61b-79d9-4310-97fb-530a885c0cfb/replicas/132748020332284443s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-westeurope1-fd61.documents.azure.com:14163/apps/ccba42f0-40a9-487a-9f2f-e4174ead669e/services/79aa7543-967e-43f8-9a89-44fa00590eed/partitions/de32f61b-79d9-4310-97fb-530a885c0cfb/replicas/132748020332284444s/"}],"RegionsContacted":["https://cdb-abb-ebuss-we-westeurope.documents.azure.com/"],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[{"ResponseTimeUTC":"2021-09-19T20:10:50.9136412Z","ResourceType":"Document","OperationType":"Batch","LocationEndpoint":"https://cdb-abb-ebuss-we-westeurope.documents.azure.com/","StoreResult":{"ActivityId":"42e91e54-5cb4-499f-b076-fdec7a911ed3","StatusCode":"MultiStatus","SubStatusCode":"Unknown","LSN":16,"PartitionKeyRangeId":"0","GlobalCommittedLSN":16,"ItemLSN":-1,"UsingLocalLSN":false,"QuorumAckedLSN":16,"SessionToken":"-1#16","CurrentWriteQuorum":3,"CurrentReplicaSetSize":4,"NumberOfReadRegions":0,"IsClientCpuOverloaded":false,"IsValid":true,"StorePhysicalAddress":"rntbd://cdb-ms-prod-westeurope1-fd61.documents.azure.com:14004/apps/ccba42f0-40a9-487a-9f2f-e4174ead669e/services/79aa7543-967e-43f8-9a89-44fa00590eed/partitions/de32f61b-79d9-4310-97fb-530a885c0cfb/replicas/132748020332284442p/","RequestCharge":1.24,"BELatencyInMs":"0.641","RntbdRequestStats":[{"EventName":"Created","StartTime":"2021-09-19T20:10:50.5400030Z","DurationInMicroSec":"12"},{"EventName":"ChannelAcquisitionStarted","StartTime":"2021-09-19T20:10:50.5400157Z","DurationInMicroSec":"298594"},{"EventName":"Pipelined","StartTime":"2021-09-19T20:10:50.8386103Z","DurationInMicroSec":"8037"},{"EventName":"Transit Time","StartTime":"2021-09-19T20:10:50.8466474Z","DurationInMicroSec":"66518"},{"EventName":"Received","StartTime":"2021-09-19T20:10:50.9131663Z","DurationInMicroSec":"345"},{"EventName":"Completed","StartTime":"2021-09-19T20:10:50.9135114Z","DurationInMicroSec":"0"}],"TransportException":null}}]}}}]}]}]}]}]},{"name":"Create Trace","id":"72e2a897-01eb-4863-bf95-b4deac2859f3","caller info":{"member":"FromResponseMessageAsync","file":"TransactionalBatchResponse.cs","line":214},"start time":"08:10:50:913","duration in milliseconds":0.0321}]}]}

HEADERS
=======
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ru;q=0.8
Connection: close
Host: localhost:44341
Referer: https://localhost:44341/swagger/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
sec-ch-ua: "Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
origin: https://localhost:44341
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty

![image](https://user-images.githubusercontent.com/14895555/133942015-d9b4bccf-545d-45a7-bafb-738af44988ed.png)

**Expected behavior**
Expected to have already removed items

**Actual behavior**
Response status code does not indicate success: NotFound (404);

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.20.1
OS Version: Windows 10  x64

**Additional context**
Also tried the following but usless

FeedIterator<response> feedIterator = container.GetItemQueryIterator<response>("SELECT * FROM c");

                List<Task> concurrentDeleteTasks = new List<Task>();

                while (feedIterator.HasMoreResults)
                {
                    FeedResponse<response> res = await feedIterator.ReadNextAsync();
                    foreach (var item in res)
                    {                            concurrentDeleteTasks.Add(container.DeleteItemAsync<response>(item.id, new PartitionKey(item.deviceid)));
                    }
                }
                await Task.WhenAll(concurrentDeleteTasks.Take(3));

**Comment by j82w** [comment]
> Create 2 containers, implement a GenericRepository Class and implement 2 Repositories for each container. add an item into the first container, add 2 items to second one which holds the Id of the first container Item. After attempting to delete an items from second container WHERE container1ItemId = "some GUID" the response is Response status code does not indicate success: NotFound (404

You mention the id, but what about the partition key value? An item in Cosmos DB is located with the id and partition key. The partition key determines which logical partition it should be routed to and the id is used to determine the item in that logical partition. If you are not passing the correct partition key the item will not be found.

Few suggestions:
1. Based on the diagnostics it seems like you are not using a singleton for the Cosmos SDK.  https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-dotnet-sdk-v3-sql#sdk-usage
2. Are you doing enough operations to actually get any benefit with bulk? https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/

**Comment by Gor92** [comment]
> 2. Are you doing enough operations to actually get any benefit with bulk? https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/

i was already done 
![image](https://user-images.githubusercontent.com/14895555/134008499-842a4b75-0bfe-4545-9e3e-61fa17687491.png)

**Comment by Gor92** [comment]
> 1. Based on the diagnostics it seems like you are not using a singleton for the Cosmos SDK.  https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-dotnet-sdk-v3-sql#sdk-usage

Good point, already changed it

**Comment by Gor92** [comment]
> > Create 2 containers, implement a GenericRepository Class and implement 2 Repositories for each container. add an item into the first container, add 2 items to second one which holds the Id of the first container Item. After attempting to delete an items from second container WHERE container1ItemId = "some GUID" the response is Response status code does not indicate success: NotFound (404
> 
> You mention the id, but what about the partition key value? An item in Cosmos DB is located with the id and partition key. The partition key determines which logical partition it should be routed to and the id is used to determine the item in that logical partition. If you are not passing the correct partition key the item will not be found.

I'm going to recreate containers to make sure all thing are done in correct way in respect with partition keys

**Comment by j82w** [comment]
Does it work without bulk being enabled?

**Comment by ealsur** [comment]
If you were not using a singleton, are you using Session Consistency? Were you passing the Session Token between client instances?

**Comment by Gor92** [comment]
After recreation the containers and correction within partition keys everything works now.
