### ISSUE TITLE
Thread stuck in Dispatcher#SetConnectionBrokenException 

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-cosmos-dotnet-v3#2767]
tracking the issue here:
https://portal.microsofticm.com/imp/v3/incidents/details/264645266/home

We had a call with customer to discuss this in more detail and understand why this issue is happening to prevent from future re-occurrence.

customer sees high number of Rntbd Dispatcher.SetConnectionBrokenException() in the thread dump.

Dispatcher.SetConnectionBrokenException() is invoked when rntbd connection goes into a bad state.
recommendation to the customer, we need to understand the reason for connections going to bad state.

1) Please investigate your code to make sure you don't have any blocking call. Blocking call may cause thread starvation and results in RNTBD related threading issue.

2) investigate on the networking side if there is any networking issue (SNAP port exhaustion, etc) causing connections to be broken.

On the Cosmos DB engineering team, our team will look at why we have blocking call in Rntbd Dispatcher.SetConnectionBrokenException():

https://msdata.visualstudio.com/_git/CosmosDB?path=/Product/Microsoft.Azure.Documents/SharedFiles/Rntbd2/Dispatcher.cs&version=GBmaster&line=1017&lineEnd=1018&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

 

One of the theories so far (Jake suggested), is as customer is using `DotNetty.Common.Concurrency.SingleThreadEventExecutor`. That may interfere with how rntbd Dispatcher works with respect to releasing semaphore (which needs at least two threads). We need to look at if usage of DotNetty.Common.Concurrency.SingleThreadEventExecutor that customer is using cause any issues with TaskScheduler.Current in rntbd Dispatcher.

**Comment by kirankumarkolli** [comment]
@j82w, @asketagarwal what are the next steps?
