### ISSUE TITLE
Cosmos DB emulator should provide a read-only key

### ISSUE THREAD

**Issue by palenshus** [Azure/azure-cosmos-dotnet-v3#2794]
Our Cosmos DB usage assumes a read-only key and read-write key, which we use for different functions as a guard against unauthenticated users modifying the DB. Unfortunately we have no way to run tests validating that functionality that using the emulator as far as I can tell, the emulator portal only shows a single key.

**Describe the solution you'd like**
The emulator should expose read-write and read-only keys, and show them in the portal.

Thanks for considering!

**Comment by j82w** [comment]
This repository is for the .NET SDK and can not help with emulator feature requests. Please file feedback on the emulator documentation: https://docs.microsoft.com/azure/cosmos-db/emulator-command-line-parameters
