### ISSUE TITLE
ChangeFeed processor ignoring WithMaxItems

### ISSUE THREAD

**Issue by yoliva** [Azure/azure-cosmos-dotnet-v3#2795]
**Describe the bug**
I have a hosted service consuming the changes from a container and sometimes I need to make bulk operations in that container. Because of this requirement, I tried to use the `.WithMaxItems()` configuration to limit the amount of updates that I will received in a single batch but the processor seems to be ignoring the configuration.

**To Reproduce**
```
    public class ChangeFeedProcessor : IHostedService
    {
        private readonly ChangeFeedSettings _feedSettings;
        private readonly Lazy<ChangeFeedProcessor> _changeFeedProcessor;

        public ChangeFeedProcessor(IOptions<ChangeFeedSettings> feedSettings,
            ICustomLogger<AlertsChangeFeedProcessor> logger)
        {
            //some code to get the container
            _changeFeedProcessor = new Lazy<ChangeFeedProcessor>(() => container
                .GetChangeFeedProcessorBuilder<ItemDto>("some_name", OnChangesDelegate)
                .WithInstanceName("instance_name")
                .WithMaxItems(10)
                .WithLeaseContainer(leaseContainer)
                .Build());
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            await _changeFeedProcessor.Value.StartAsync();
        }

        public async Task StopAsync(CancellationToken cancellationToken)
        {
            await _changeFeedProcessor.Value.StopAsync();
        }

        public async Task OnAlertChangesDelegate(IReadOnlyCollection<ItemDto> changes,
            CancellationToken cancellationToken)
        {
            //changes has more than ten elements
            //some logic here
        }
    }
}

```
**Expected behavior**
I expect to receive the specified amount of items at most

**Actual behavior**
I receive a lot more

**Environment summary**
SDK Version: 3.19.0
OS Version: Windows

**Comment by ealsur** [comment]
If you are storing the documents with Stored Procedures or Bulk or TransactionalBatch, this is expected.

Change Feed responses cannot break the transaction, if the documents were saved within the same transaction, they cannot be separated.

**Comment by ealsur** [comment]
This is explained in the Change Feed Iterator options: 

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/RequestOptions/ChangeFeedRequestOptions.cs#L24-L37

We could replicate the same text on the ChangeFeedProcessorBuilder

**Comment by yoliva** [comment]
Thanks for the clarification @ealsur . I wasn't aware of this behavior

**Comment by ealsur** [comment]
I'll leave the issue open to track adding this note to the ChangeFeedProcessorBuilder APIs.
