### ISSUE TITLE
'System.Configuration.ConfigurationManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by raedg2000** [Azure/azure-cosmos-dotnet-v3#2798]
Running a deployed Azure Function on Azure that connects to cosmos db using V4  gives an error.
Even when trying version 3.x it gives the same error.

In this function, I connect to a cosmosdb (SQL API)

Azure Function Project:
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Cosmos" Version="4.0.0-preview3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.0-preview2" />
  </ItemGroup>

Once I try to open a connect to cosmos db  in the deployed azure function:

CosmosClient cosmosClient = new CosmosClient(cosmosDbConnectionString);

this error is captured.

'System.Configuration.ConfigurationManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

When I remove the code that is related to cosmos db , the deployed azure function runs without errors.
Cosmos Db library depends on the System.Configuration.ConfigurationManager version 4.*

regards,
Raed

**Comment by mohamedeshiba** [comment]
I had the same problem when I tried to connect to CosmosDb from a time triggered Azure Function.
Here what I did to solve the problem
1- downgraded the projecto to netcoreapp3.1
2- Used the Azure Function V3
3- used Microsoft.NET.Sdk.Functions version 3.1.1(any version 3)
4- Added <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> in the property Group tag in the .csproj

It worked for me. Hope this helps
