### ISSUE TITLE
EF Core provider gap: CreateContainerIfNotExistsAsync call is required for getting CosmosItem

### ISSUE THREAD

**Issue by divega** [Azure/azure-cosmos-dotnet-v3#28]
In the new SDK, if you need to get `CosmosItems` you first need to call `CreateContainerIfNotExistsAsync()`. 

For SDK customers in general, this means there is no way to get the `CosmosItems` object without creating a container as a side effect, even if that isn't the intent.

For EF Core it means that some existing APIs will have unexpected semantics. 

This issue was found while adapting EF Core provider to work with [Cosmos SDK version 3.0.0.1-preview](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.0.0.1-preview).

cc @AndriySvyryd @ajcvickers @kirillg

**Comment by AndriySvyryd** [comment]
@j82w That does enable our scenario, though this API has low discoverability.

**Comment by j82w** [comment]
We can increase the documentation around this scenario, and add more samples to prevent this in the future. 
@kirankumarkolli and @kirillg do you think it might be worth adding methods like GetDatabase to increase exposure on how to get the objects other than the index overload?

**Comment by j82w** [comment]
@AndriySvyryd we are changing the API to make it easier to discover. I'm closing this issue please look at https://github.com/Azure/azure-cosmos-dotnet-v3/issues/333
