### ISSUE TITLE
ChangeFeedProcessor stops receiving change events and "Owner" set to null in lease container

### ISSUE THREAD

**Issue by komainu85** [Azure/azure-cosmos-dotnet-v3#2801]
**Describe the bug**
I have a CosmosDB SQL API database with multiple containers. 3 of the containers have a single ChangeFeedProcessor each watching for changes, each of these ChangeFeedProcessors are running in a separate task in a dotnet BackgroundService.

The issue that I'm seeing is that 2 of the ChangeFeedProcessor always work correctly. The third seems to work correctly when the application starts up, and it writes the lease to another cosmos container correctly. However after a few minutes it updates the lease container to "Owner": null in the lease container and then stops receiving changes from cosmos.

**Expected behavior**
ChangeFeedProcessor continues to receive change events from CosmosDB

**Actual behavior**
ChangeFeedProcessor stops receiving changed events from CosmosDB

**Environment summary**
SDK Version: 3.20.0.0
OS Version: Windows 10 (19042.1237)

**Comment by ealsur** [comment]
Owner on null means the Processor is releasing the lease.

Make sure you have a global `try/catch` block inside your delegate function and see if you are throwing unhandled exceptions: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/change-feed-processor#error-handling
