### ISSUE TITLE
ExecuteStoredProcedureAsync not accepting arguments

### ISSUE THREAD

**Issue by issacnitin** [Azure/azure-cosmos-dotnet-v3#2806]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Arguments passed to the stored proc are always undefined

**To Reproduce**
```
var response = await container.Scripts.ExecuteStoredProcedureAsync<object>(
                    storedProcedureId: storedProcId,
                    partitionKey: new PartitionKey(partitionKeyValue),
                    parameters: args.ToArray(), 
                    requestOptions: new StoredProcedureRequestOptions()
                    {
                        EnableScriptLogging = true
                    });
```
args = new List<dynamic> {  currentCount - item.Count, type };

**Expected behavior**
Expected console.log statements in stored proc to output values instead of undefined 

**Actual behavior**
console.log statements in stored proc output "undefined"

**Environment summary**
SDK Version: 3.21.0
OS Version (e.g. Windows, Linux, MacOSX) - Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

Stored Proc: 
```
function deleteNItemsInCreatedState(num, type, additionalArgs) {
    if (!num) {
        throw new Error("Argument num cannot be null or undefined");
    }

    if (!type) {
        throw new Error("Argument type cannot be null or undefined");
    }

    console.log("Trace log");
    console.log(num);
    console.log(type);
    console.log(additionalArgs);  
}
```

**Comment by ealsur** [comment]
@issacnitin Could you please share a more complete example that reproduces the problem?

**Comment by issacnitin** [comment]
Issue was because of custom json serializer.
