### ISSUE TITLE
Allow callback for custom failover logic.

### ISSUE THREAD

**Issue by Izikiel** [Azure/azure-cosmos-dotnet-v3#2811]
**Is your feature request related to a problem? Please describe.**
Recently we've had issues where latency performance to a cosmosdb region was severely degraded, but the account failed to failover to it's zone or region. It seems the sdk will only failover to another region when the current region is effectively dead.

**Describe the solution you'd like**
Expose an api for users to implement their own custom logic for failover based on parameters users define.
We know there isn't a one size fits all solution regarding latency and perf management, hence why we ask to have the chance to implement it ourselves, and handle the load balancing across regions.

**Describe alternatives you've considered**
We are bringing this up because things can fail, such as failover, and this would help us reduce the impact for our partners faster than waiting for the cosmosdb team to solve the issue.

**Comment by kirankumarkolli** [comment]
Cosmos SDK do try to fallback across regions for high availability. 

@Izikiel is the behavior you observed impacted latency performance but still resulted in high availability, right?
Can you please share the observed latency performance and expectations.

**Comment by ezgambac** [comment]
Well, no, we didn't have high availability as the latency was so bad that we were dropping requests.
I currently don't have the data on hand as it has gone to cold storage, but it was during a DRD in canary, where CosmosDB had an issue server side and took like an hour to fallback to the other region.
From my discussion with @ealsur , I understand that there isn't a one size fits all fix, but we would like to have the option of monitoring the latency over time of an account, and if we see a degradation, force a failover to an auxiliary region if possible.

**Comment by ealsur** [comment]
Tracking it on https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3488
