### ISSUE TITLE
The CONTAINS function requires 2 argument(s).

### ISSUE THREAD

**Issue by amayd** [Azure/azure-cosmos-dotnet-v3#2813]
I am facing same issue now. I am using latest stable version 3.22 (**Microsoft.Azure.Cosmos**) I again tried switching to 3.10,
Nothing works. Please suggest

**Message: {"errors":[{"severity":"Error","location":{"start":261,"end":305},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."}]}, Windows/10.0.18363 documentdb-netcore-sdk/2.1.3**

_Originally posted by @amayd in https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1615#issuecomment-949308824_

**Comment by jackbond** [comment]
You may want to provide a code example which demonstrates your issue. Are you getting this error with a LINQ to SQL query, or did you write the SQL yourself?

**Comment by amayd** [comment]
I built the SQL query. not using LINQ. I will post the query in sometime.
