### ISSUE TITLE
StoreReader exceptions for high volume of read session not available errors (404, 1002) impacts CPU.

### ISSUE THREAD

**Issue by olivertowers** [Azure/azure-cosmos-dotnet-v3#2814]
**Describe the bug**
Profiling an application during a high CPU issue showed a hotspot on exceptions that are caught and traced with level INFO in `StoreReader` method, but were never thrown to the caller.  When trace listener is enabled for the SDK, this appears to cause a more significant impact.

From the request activity errors, a the highest volume of errors were for read session not available (404, 1002). The workload is performing highly concurrent reads and writes on the same client so it seems reasonable that these errors could be occurring at a higher rate.

Flame graphs for reference: [internal link](https://azureprofiler.azurewebsites.net/#/profiler/collection/cdb-ms-prod-eastus2-fe1-HighCPU/role/CV2CW/process/Microsoft.Azure.Cosmos.Compute.Host.ServiceFabric.exe/flamegraph?container=azure&date=2021-10-13)

`Rntdb.TransportClient.InvokeStoreAsync` throws:
![image](https://user-images.githubusercontent.com/24803650/138522690-e11cfa82-ff60-41a9-a88b-789403f225cc.png)

On the same flame, this is caught in `StoreReader.ReadMultipleReplicasInternalAsync`:
![image](https://user-images.githubusercontent.com/24803650/138522829-42ee0d5b-14d2-4337-8b50-6010a3fcf3a0.png)

The main concern is that each time a store request hits the non-fatal error, the exception is traced with level INFO so when trace listener is configured

**To Reproduce**

Some of the details may be difficult to reproduce exactly. In general though here is the characteristics of the workload:

1. SQL API account with session consistency level.
2. Create a workload that targets a single partition key which performs reads/queries and replace operations in a concurrent manner.
3. Setup a Cosmos client and configure trace listeners with trace level info for the client trace source.
3. Run the workload and monitor/profile CPU on the application

**Expected behavior**

SDK should avoid tracing non-fatal/internal only errors. Minimally they should be debug/verbose level traces.

**Actual behavior**

SDK traces many internal errors that aren't fatal/are retried or are expected in healthy workloads. This can cause impact CPU more significantly.

**Environment summary**
SDK Version: 3.21.0/Any

OS Version: Win 10 19043.1288

**Comment by j82w** [comment]
Internal PR: https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/687432

**Comment by kirankumarkolli** [comment]
@j82w what else is this issue is pending on?

**Comment by j82w** [comment]
The internal PR is merged. Closing the issue.
