### ISSUE TITLE
CPU hotpath originating in `CosmosQueryClientCore.GetCosmosElementResponse`

### ISSUE THREAD

**Issue by olivertowers** [Azure/azure-cosmos-dotnet-v3#2815]
**Describe the bug**
Seeing CPU hotpath that is originating in `CosmosQueryClientCore.GetCosmosElementResponse` which is using 6% of application CPU during a query workload.

Flame graph reference [internal link](https://azureprofiler.azurewebsites.net/#/profiler/collection/cdb-ms-prod-eastus2-fe1-HighCPU/role/CV2CW/process/Microsoft.Azure.Cosmos.Compute.Host.ServiceFabric.exe/flamegraph?container=azure&date=2021-10-13):

![image](https://user-images.githubusercontent.com/24803650/138525533-ecb6825a-94ae-489e-b27b-e1531910203d.png)

Zooming into the `QueryPage` ctor:

![image](https://user-images.githubusercontent.com/24803650/138525981-13a84798-6d45-4823-a695-49f243639bf0.png)

The main issue is whether this CPU impact can be reduced when SDK is handling high volume query workloads.

Within this hotpath two methods are of note:
1. `Page` ctor is creating an `ImmutableDictionary` for `AdditionalHeaders` property, [see](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/9d5689568d3f04351d9d1d9fd97746ae3bf88fe0/Microsoft.Azure.Cosmos/src/Pagination/Page.cs#L47) - `ImmutableDictionary` is known to be much slower than `Dictionary`, so maybe `IReadOnlyDictionary` would be better for this even if the trade-off is that true immutability guarantee is lost?

2. QueryExceutionInfo header is deserialized with Newtonsoft.Json [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c8935ac2f864fb829f5d941dda07c74aec86a677/Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs#L323) -  Would it be more performant to use the Json text readers built-in to the SDK instead?

**To Reproduce**

Run a high volume query workload and monitor/profile on the SDK.
More likely to see the issue with the following setup/workload

1. 10+ partitions collection.
2. Query workload issuing cross partition queries which return no results. This highlights the impact of many empty pages being returned but where the header/execution info is still significant.

**Expected behavior**
Expect a lower CPU impact on an application for the critical path in query responses.

**Actual behavior**
Higher CPU impact for query response handling especially when very few items are returned.

**Environment summary**
SDK Version: 3.21/Any
OS Version: Win 10

**Comment by kirankumarkolli** [comment]
@sourabh1007 what else is pending for this issue?

**Comment by sourabh1007** [comment]
It can be closed now.
