### ISSUE TITLE
Linq IsArray and array length?

### ISSUE THREAD

**Issue by dmcweeney** [Azure/azure-cosmos-dotnet-v3#2837]
Hi,

Upgrading from V2 to V3 I notice that the Linq IsArray() extension is gone - is there a replacement for this?

I also see that the following Linq expression

`.Where( doc => doc.myCollection.Count >= 1 )
`

is generating

`AND root["myCollection"]["Count"] >= 1
`

I would have thought it would have mapped to ARRAY_LENGTH?

Thanks, Donal

**Comment by Maya-Painter** [comment]
@dmcweeney closing as this appears to be addressed.  Please tag me if you have any follow up questions or concerns.

**Comment by Maya-Painter** [comment]
@romain-m-shift Can you share your linq query here? And have you tried something along the lines of

` .Where( doc => doc.myCollection.Count() >= 1 )`

with parenthesis after count?
