### ISSUE TITLE
GetRid behavior with througphut operations

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#284]
**Describe the bug**
Should GetRid throw an exception or return null?

Database GetRid returns null
Container GetRid throws because the cache throws

This causes the throughput operations to behave differently based on if it is a database or container. 

**To Reproduce**
```
CosmosDatabase databaseDoesNoExist = CosmosNotFoundTests.client.Databases[DoesNotExist];
CosmosContainer containerDoesNoExist = databaseDoesNoExist.Containers[DoesNotExist];

await databaseDoesNoExist.ReadProvisionedThroughputAsync();
await databaseDoesNoExist.ReplaceProvisionedThroughputAsync(9001);
await containerDoesNoExist.ReadProvisionedThroughputAsync();
await containerDoesNoExist.ReplaceProvisionedThroughputAsync(9001);

```
**Expected behavior**
That the throughput operations throw same exception when a container or database does not exist.

**Actual behavior**
Current behavior causes null ref exceptions for database operations and container operations to throw document client exceptions.

**Comment by j82w** [comment]
Initial bug report: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/257

**Comment by ealsur** [comment]
The fix needs to take into consideration #255, `Task<ItemResponse<T>> ReadCurrentAsync<T>` in particular

**Comment by kirankumarkolli** [comment]
(Container + shared-throughput) & (Database + shared-throughput) should have same behavior.

Throwing vs null: 
Q: Are throughput API's typed or stream API's
Throughout is kind of typed API (not returning HttpResponseMessage)

Conflicts: Its a typed API -> Exception

PK extraction: scoped to only typed API -> Exception

**Comment by kirankumarkolli** [comment]
Please check with Interop once.

**Comment by kirankumarkolli** [comment]
GetRID dependency is removed we are good with the plan.
