### ISSUE TITLE
[Internal] Performance : Improve Region Contacted information Logic

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#2846]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
It is non functional issue. As region contacted collection logic needs to be optimized.
Avoid reinitialization of this Hashset everytime, it has impact on client telemetry also as this information is getting fetched in each request.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/b73ed615e03aed0e7adec5ec309ad3eecc2d293a/Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs#L49

**Comment by kirankumarkolli** [comment]
- [ ] Perf benchmark to measure the impact
- [ ] Optimization for primary flows

**Comment by kirankumarkolli** [comment]
Benchmarked on the regular perf tool with three runs average, here is how they stack up
|Measure|baseline|snapshot|%overead|
|------|------|-----|-----|
|P50 Rps|11035|10878|1.42|
|P95 Rps|10792|10615|1.64|	
|P99 Rps|10699|10441|2.41|

Of course its not a long running a perf bed. And the allocations might show-up there on higher percentile.

**Comment by sourabh1007** [comment]
p99 is 2.5% percent overhead. I think its considerable overhead.
