### ISSUE TITLE
New APIs for CosmosDiagnostics metrics

### ISSUE THREAD

**Issue by stpetzinger** [Azure/azure-cosmos-dotnet-v3#2848]
From version 3.15.0 we have been using the following 5 fields in our telemetry for diagnostic purposes.  These values used to be available in the "Summary" section of the CosmosDiagnostics Json, but now they have been replaced by other data.  Since this Json is likely to change again in the future, would it be possible to provide first-class APIs for this data on the CosmosDiagnostics class? ([https://github.com/Azure/azure-cosmos-dotnet-v3/blob/40075ebb1a732587703ea355039294a2633d881d/Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs](url) class?  These are the five fields and our use cases for each:

1. StartUtc - used to correlate the start time of our application operation with the actual start time of the Cosmos DB operation
2. RunningElapsedTimeInMs - used to correlate the application elapsed time with the Cosmos DB elapsed time
3. UserAgent - useful for diagnosing client-level issues
4. TotalRequestCount* - useful for identifying potential issues when operations are being retried in the back-end
5. FailedRequestCount* - useful for identifying potential issues when operations are being retried in the back-end

*4 and 5 have been superseded by a Dictionary of Gateway or Direct calls, with their status code, substatus code, and number of attempts.  This data would also be very useful in our troubleshooting as well.

In hindsight it probably wasn't the best idea to parse the diagnostics Json to get these values, but the absence of this data from the new diagnostics is actually holding us back from upgrading because we don't want to lose the telemetry we already have.

Thank you.

**Comment by j82w** [comment]
Most of the information seems to have valid scenarios on why users would want programmatic access to it. The only one that I'm not sure of is what scenario requires you to have the user agent string?

The current CosmosDiagnostics: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs

// Possible sample of the new API
```c#
 public abstract class CosmosDiagnostics
{
        public abstract DateTime GetStartTimeUtc()

        public abstract bool IsRequestRetried()

        public abstract string GetUserAgentString()

        // The current APIs are listed below
        public virtual TimeSpan GetClientElapsedTime()

        public abstract override string ToString();

        public abstract IReadOnlyList<(string regionName, Uri uri)> GetContactedRegions();
}
```

**Comment by kirankumarkolli** [comment]
How is 'TotalRequestCount' expected to be used? It might need more context to make real sense as the count is dependent on the consistency level & gateway interaction as well.

**Comment by stpetzinger** [comment]
> The only one that I'm not sure of is what scenario requires you to have the user agent string?

I can't think of a good reason we would realistically use this, either.  I just did because it was available. 

> How is 'TotalRequestCount' expected to be used? It might need more context to make real sense as the count is dependent on the consistency level & gateway interaction as well.

Technically we only used 'FailedRequestCount' so far to see whether the operation was retried or not.  I would need to dig further to see how 'TotalRequestCount' could be used in the context you mention and whether that would be useful.  We are currently storing it, however so if there is a valid use for it I would like to keep it.

@j82w is there any way we could get the detailed retry information that is currently exposed in the Summary section? We've had a few customers ask for the substatus codes to provide more details on what they see in their diagnostics logs, particularly with 404's.
e.g.
```
"Summary": {
        "Direct": {
            "(404, 1002)": 2,
            "(200, 0)": 1,
        }
    }
```

**Comment by stpetzinger** [comment]
@j82w do you have an updates on this request?

Respectfully,

Steve

**Comment by j82w** [comment]
@kirankumarkolli do you have an eta when this could get prioritized? 

@stpetzinger would having a bool for if the request is retried good enough? What can customers do with the info that the request had retries from a 404/1002? The concern is if we start exposing out status/substatuscode as an API then people end up wanting to know how long each request took. It basically ends up being the full diagnostics in the end because that is what is required to see where all  the latency goes.

**Comment by stpetzinger** [comment]
> It basically ends up being the full diagnostics in the end because that is what is required to see where all the latency goes.

I see where you're going with that.  The reason that these retires were initially brought up was that some customers were seeing excessive amounts of 404's in the AzureDiagnostics logs triggering their alerts, and unless I am mistaken there is no substatus code available in those logs.  They were not using a multi-region configuration so they were confused as to why they would get session consistency errors.  So they wanted to dig deeper and find out more information.  It was at some point suggested (but not confirmed) that 404/1002 errors could occur even with single region configurations and that there were some improvements in later versions of the SDK.

I think a bool for whether the request retried should be sufficient for this purpose.  As a side topic it would be helpful if the AzureDiagnostics logs contained the substatus code for troubleshooting.

Thank for you attention to this.

**Comment by stpetzinger** [comment]
@kirankumarkolli any update on this?  To recap, we are good with a bool for whether the request was retried or not.  So something like the above sample suggested by @j82w would be fine for us.  Thanks.

**Comment by kirankumarkolli** [comment]
Assigned to @SchintaMicrosoft.

**Comment by kirankumarkolli** [comment]
New APIs as requested are merged now. 
```C#
public class CosmosDiagnostics
{

  public abstract DateTime GetStartTimeUtc();
  public abstract int GetFailedRequestCount(); 

}
```
