### ISSUE TITLE
Newtonsoft.Json: Self referencing loop detected for property 'Parent' with type 'Microsoft.Azure.Cosmos.Tracing.Trace'.

### ISSUE THREAD

**Issue by kuromukira** [Azure/azure-cosmos-dotnet-v3#2853]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Using `continuationToken` does not work

**To Reproduce**
1. Create an Azure Function HTTP Trigger
2. Inside the Azure Function, query for a paginated collection
3. Invoke the Azure Function without passing the `continuationToken`
3. Return the paginated result together with the `FeedResponse<T>.ContinuationToken`
4. Invoke the Azure Function again and pass the `continuationToken`

**Expected behavior**
This should get the next page

**Actual behavior**
Getting the following error
> System.Private.CoreLib: Exception while executing function: Some_Paginated_Function. Newtonsoft.Json: Self referencing loop detected for property 'Parent' with type 'Microsoft.Azure.Cosmos.Tracing.Trace'. Path 'Item3.Diagnostics.Value.Children[0]'.

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos v3.22.1
OS Version: MacOSX 12.0.1

**Additional context**
Nothing else is thrown in the terminal

**Comment by ealsur** [comment]
How is the continuation value passed into the SDK? Are you sure the value is not being escaped through HTTP transit? For example: https://stackoverflow.com/questions/66995110/azure-cosmos-pagination-feedresponse-continuationtoken-not-working-in-the-next/66995871#66995871

**Comment by kuromukira** [comment]
Thanks @ealsur , I think I see the difference now from the response and from what I was getting in the parameter. The `+` and `~` and some other parts of the `continuationToken` gets removed when passed back to the endpoint.

**Comment by ealsur** [comment]
You can try escaping or serializing the token as part of a larger object (not just send the token alone) during HTTP transit, it might be that whatever is happening between the token is generated on the initial call and it is received to be used on the second call (Server to Client serialization and/or Client to Server serialization) is modifying it and making it invalid.

**Comment by kuromukira** [comment]
@ealsur 

What I did is return it as a deserialized object from the endpoint and let the client (mobile app) handle it and encode/serialize it back to a json string. And by the time it is needed to be used in the query parameter of the HTTP request, I make sure that it is URL Encoded.

**Comment by ealsur** [comment]
When you did all those steps, did it work? Were you able to get the same format back?

**Comment by kuromukira** [comment]
> @ealsur
> 
> What I did is return it as a deserialized object from the endpoint and let the client (mobile app) handle it and encode/serialize it back to a json string. And by the time it is needed to be used in the query parameter of the HTTP request, I make sure that it is URL Encoded.

I implemented this after you replied with the reference link.

This approach worked on my end and I got the same format back.

**Comment by ealsur** [comment]
Can we close this Issue then?

**Comment by viplavdhande91** [comment]
This issue is not yet solved

**Comment by ealsur** [comment]
@viplavdhande91 Please create a new Issue with your details. The author of this issue declared closure 3 years ago.
