### ISSUE TITLE
No PatchItem methods in 3.22.1 nuget release

### ISSUE THREAD

**Issue by cannehag** [Azure/azure-cosmos-dotnet-v3#2857]
**Patch operation methods missing in 3.22.1 release**
Refering to the same problem as comment on public GA announcement: https://devblogs.microsoft.com/cosmosdb/partial-document-update-ga/

**Environment summary**
SDK Version: 3.22.1

**Comment by j82w** [comment]
We are currently working on a new SDK release to move the APIs to the GA SDK. We are hoping to have a release in the next week or 2.

The APIs should not change so you can use the preview SDK until the new SDK is released. You should only have to change the nuget version once it is released.

**Comment by cannehag** [comment]
Great. Thanks @j82w !
