### ISSUE TITLE
CosmosClientBuilder with TokenCredential throws ArgumentNullException

### ISSUE THREAD

**Issue by Vicasel** [Azure/azure-cosmos-dotnet-v3#2858]
**System.ArgumentNullException when building with CosmosClientBuilder**
After creating a CosmosClientBuilder with TokenCredential a System.ArgumentNullException "Value cannot be null. (Parameter 'uriString')" occurs when Build is called.

```
var builder = new CosmosClientBuilder(
                accountEndpoint: databaseHost,
                tokenCredential: new DefaultAzureCredential());

builder.Build();
```

**Environment summary**
Occurs in version 3.22.1

**Remarks**
Comparing the master with the source of 3.22.1 revealed that the issue has already been fixed in the master branch.
The ctor does not set the field accountEndpoint in the source of 3.22.1, this has been solved in the master. Releasing a new version of the package will fix this issue.

**Comment by j82w** [comment]
This was already fixed in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2844. We are starting to work on the next release so a 3.23.0 will have the fix and should be done in the next week or two.

**Comment by j82w** [comment]
Fixed in https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.23.0
