### ISSUE TITLE
ContinuationToken security

### ISSUE THREAD

**Issue by timjansenortec** [Azure/azure-cosmos-dotnet-v3#2867]
In the past there have been questions about the security of a ContinuationToken.
https://github.com/Azure/azure-cosmos-dotnet-v2/issues/697

There even was a pull request to clarify this in the documention:
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/162

But in the current documention, nothing is stated about this:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.responsemessage.continuationtoken?view=azure-dotnet#Microsoft_Azure_Cosmos_ResponseMessage_ContinuationToken
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.headers.continuationtoken?view=azure-dotnet#Microsoft_Azure_Cosmos_Headers_ContinuationToken
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.feedresponse-1.continuationtoken?view=azure-dotnet

So, are ContinuationToken's safe to give directly to a client or not?
Can a client manipulate a ContinuationToken to break out of a query and get access to data that he is not authorized for?

**Comment by j82w** [comment]
@timsander1 and/or @sboshra can you please take a look?

**Comment by timsander1** [comment]
Hi @timjansennortec, continuation tokens are safe to give to a client. There is no possibility that a client could use a continuation token to gain access to data that it was not otherwise authorized for.
