### ISSUE TITLE
Parameterized queries - can GeoJson values be used? ...

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-cosmos-dotnet-v3#2873]
Hello,

I was asked by the MS documentation team to open this issue as I mistakenly opened the issue under Documentation rather than the SDK.  In a nutshell, parameterized (spatial) queries that use a JSON string seem to fail - rather than repeat the whole issue, the following link describes and illustrates the behavior:

[https://github.com/MicrosoftDocs/azure-docs/issues/81859](https://github.com/MicrosoftDocs/azure-docs/issues/81859)

Thanks in advance.

**Comment by neildsh** [comment]
Hello @bdcoder2, this is likely a year late, but the answer is exactly what you mentioned in https://github.com/MicrosoftDocs/azure-docs/issues/81859. You need to use a geojson object rather than a string.
