### ISSUE TITLE
Cannot reuse the client settings for different cosmos clients' initialization if I set the customHandlers

### ISSUE THREAD

**Issue by renyiSZ** [Azure/azure-cosmos-dotnet-v3#2878]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I tried to reuse the same setting to initialize 2 different cosmos clients.

var option1 = new CosmosClientOptions { CustomHandlers = { new LogHandler() } };
            var client1 = new CosmosClient(repositorySetting.ContainerSettings.AccountEndpoint, repositorySetting.ContainerSettings.AuthKey, option1);
            var client2 = new CosmosClient(repositorySetting.ContainerSettings.AccountEndpoint, repositorySetting.ContainerSettings.AuthKey, option1);

(I set the CustomHandlers in CosmosClientOptions)

if I do this, I will get System.ArgumentOutOfRangeException
![image](https://user-images.githubusercontent.com/32538216/141390447-a9716665-806a-4333-8502-7b771aca1f6a.png)

**Environment summary**
SDK Version: V3
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Comment by ealsur** [comment]
Are the clients connecting to different accounts?

**Comment by renyiSZ** [comment]
> Are the clients connecting to different accounts?
clients connect to the same account

**Comment by ealsur** [comment]
Why do you need multiple clients if they connect to the same account with the same settings?

**Comment by renyiSZ** [comment]
one scenario: we have different accounts -> different clients, but when test locally we use emulator.
by the way, if connect to different accounts, but share same settings, it will also fail with the same exception.

var option1 = new CosmosClientOptions { CustomHandlers = { new LogHandler() } };
            var client1 = new CosmosClient(endpoint1, authKey1, option1);
            var client2 = new CosmosClient(endpoint2, authKey2, option1);

**Comment by j82w** [comment]
This can't be fixed with the current design/implementation. This is the same concept is used by the DelegatingHandler in System.Net.Http library. I'm closing this because there is a workaround and it would require a breaking change to fix. The v4 SDK the contracts are defined by the [central SDK](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core).

**Comment by jl3yr** [comment]
@j82w What is the workaround for this? I'm also running into this.
