### ISSUE TITLE
Convert ContinueWith to async await

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#288]
**Is your feature request related to a problem? Please describe.**
There are several places in code that use continue with instead of async/await. This makes it very difficult to debug, and is less performant for .net core. This also causes the original exception to be wrapped in an aggregate exception which causes developers more pain to unwrap it and more likely to cause bugs.

**Describe the solution you'd like**
Replace all .ContinueWith to use async await.

**Describe alternatives you've considered**
The only alternative is to continue to use ContinueWIth. This will require additional refactoring the exception handling and forcing all developers to deal with aggregate exceptions.

**Additional context**
Here is a good article on why we should convert. We can do our own benchmarks to validate this.
https://medium.com/@joni2nja/why-you-should-not-use-continuewith-in-your-async-code-c9eaf6087e64

We can configure the await to avoid blocking calls:
https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

**Comment by ealsur** [comment]
All CFP code that was ported from CFP repo uses `ConfigureAwait`. I never saw it in V2 code, and always wondered the reason.

**Comment by kirankumarkolli** [comment]
Its implementation details only right. 
@j82w can it be post GA?

**Comment by j82w** [comment]
@kirankumarkolli while it is an implementation detail it causes all exceptions to be wrapped in an aggregate exception which will make it a contract change.

**Comment by j82w** [comment]
Closing since all continue with are removed.
