### ISSUE TITLE
Breaking changes  by adding optional parameters

### ISSUE THREAD

**Issue by carl-berg** [Azure/azure-cosmos-dotnet-v3#2880]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I'm not sure if this constitutes a bug or not, but somewhere along the line this commit was released ae5a60b8f482d7538bc305d91acf80d439eb0f33 which can cause issues.

**To Reproduce**
In my code (referencing the latest `Microsoft.Azure.Cosmos` package, 3.23.0) i reference another nuget dll `Spinit.CosmosDb` which has an older reference to `Microsoft.Azure.Cosmos` 3.8.0. The Spinit.CosmosDb package has code that calls the `ContainerBuilder.CreateIfNotExistsAsync(int? throughput = null)` method. This method have however changed by adding an extra optional parameter which breaks in runtime when calling it through `Spinit.CosmosDb`, i get a `System.MissingMethodException : Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Cosmos.ContainerResponse> Microsoft.Azure.Cosmos.Fluent.ContainerBuilder.CreateIfNotExistsAsync(System.Nullable`1<Int32>)'` exception

**Expected behavior**
I would expect to not get an exception :-)

**Actual behavior**
MethodMissing exception

**Environment summary**
SDK Version: net6.0
OS Version: Windows

**Additional context**
Im not completely sure about what this constitutes SemVer-wise but i would think that this is a breaking change that maybe should have been a major version?

**Comment by ealsur** [comment]
Not sure I understand, the referenced commit adds a new overload with different parameter types. Is Spinit.CosmosDb calling the method with `null`? Through Reflection? Otherwise, if they are passing an `int`, the `cancellationToken` variable should just default to the default value, right?

**Comment by carl-berg** [comment]
As far as i understand, and i'm surely no expert, this can be a breaking change when adding optional parameters rather than new method overloads. This article gives a better explanation than i can give: https://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx

The `Spinit.CosmosDb` calls the method with `(int?) null` as a parameter by the way.

**Comment by kirankumarkolli** [comment]
@carl-berg thanks for sharing. We will keep it forward with new API changes forwards.

To unblock for now can Spinit rebase to the latest version?

**Comment by carl-berg** [comment]
@kirankumarkolli, sounds good! 

We have released a new version targeting a newer package that solves the problem we had
