### ISSUE TITLE
Client Telemetry: Histogram Memory Management

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#2881]
**Problem Statement:**

[HDRHistogram library](http://www.hdrhistogram.org/) has been used for Client Telemetry calculation but looks like it allocates too much memory (below table) with current configuration in .Net which needs to be optimized. 

**Current Configuration and Memory Allocations :**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SOURAB~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SOURAB~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Metrics |   | Histogram   Allocation | Comments
-- | -- | -- | --
CPU | new   LongConcurrentHistogram(1, 99999, 5); | 2 MB | Expecting   histogram to have Minimum CPU Usage of .001% and Maximum CPU Usage of 999.99%
Request   Latency | new   LongConcurrentHistogram(1, TimeSpan.TicksPerHour, 5); | 20 MB | Expecting   histogram to have Minimum Latency of 1 and Maximum Latency of 1 hour
Request   Charge | new   LongConcurrentHistogram(1, 9999900, 5); | 8 MB | Expecting   histogram to have Minimum Request Charge of 1 and Maximum Request Charge of   9999900     Maximum precision can be set as 5 so consider maximum value in 5 digit i.e.   99999 of request charge     So 99999 * HistogramPrecisionFactor = 9999900 is the maximum request charge   we have set.     For all the Document ReadWriteQuery Operations there will be at least 1   request charge
Memory | new   LongConcurrentHistogram(1, Int64.MaxValue, 5); | 48 MB | Expecting   histogram to have Minimum Memory Remaining of 1 MB and Maximum Memory   Remaining of Long Max Value
</body>
</html>

**Analysis and Current Implementation**
Same library (Java version) has been used in Java Client Telemetry for same calculation. There are below difference between Java and .Net:
1. In Java, we have `ConcurrentDoubleHistogram `which records `double `values and .Net we have `ConcurrentLongHistogram `which records `long `values. ( I hope it won't make any difference , I checked memory allocation wise, it was quite similar).
due to which in .Net SDK, we are multiplying all the values by 100 to save precision of data.
2. In Java, `numberOfSignificantDigits` is set as 2 which means value quantization will be within range upto 1/100th (i.e. 1%).

**Open Questions**
1. Should we worry about the data precision while recording values in histogram? Anyway, there is no guarantee that Histogram will record the same exact value.
2. With `numberOfSignificantDigits` as 2 configuration, value quantization will be within range upto 1/100th (i.e. 1%). If understand it correctly, any value can change upto 1%. Are we fine with it?

**Comment by kirankumarkolli** [comment]
For memory it seems 48MB is too high an allocation. We can normalize it like in MB etc... to reduce the dimensionality and reduce allocations?

**Comment by sourabh1007** [comment]
Yes..For me, All the allocations are quite high, Should be optimized.

**Comment by sourabh1007** [comment]
From [Histogram Documentation](http://www.hdrhistogram.org/), _"A Histogram could be configured to track the counts of observed integer values between 0 and 3,600,000,000,000 while maintaining a value precision of 3 significant digits across that range. Value quantization within the range will thus be no larger than 1/1,000th (or 0.1%) of any value."_
So significant digit value get use for Value quantization. 

In our case, number of significant values are 5 which means value quantization within the range will be Upto 1/100000 (or .001%) which means range of values in each bucket would be of .001% difference. Which means more precision value will  lead to more buckets and more space it will need. (It is my understanding, correct me if it is wrong understanding)

In Java "Number of significant digits" are set as 2, which mean value quantization will ne within range upto 1/100th (i.e. 1%)

**Comment by sourabh1007** [comment]
As per discussion with Naveen, We are fine to loose the precision and can go ahead with same configuration as Java.

**Comment by sourabh1007** [comment]
Now Histogram Allocations are:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SOURAB~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SOURAB~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Metrics |   | Histogram   Allocation
-- | -- | --
CPU | new LongConcurrentHistogram(1, 99999, 2); | 63 KB
Request Latency | new LongConcurrentHistogram(1, TimeSpan.TicksPerHour,   4); | 2996 KB
Request Charge | new LongConcurrentHistogram(1, 9999900, 2); | 70 KB
Memory | new LongConcurrentHistogram(1, Int64.MaxValue, 2); | 110 KB



</body>

</html>
