### ISSUE TITLE
Running on Azure App Service in .NET 6 with 3.23.0 yields missing dll error

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cosmos-dotnet-v3#2890]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When I deploy my aspnet core .net 6 application after upgraded from 3.22.1 to Cosmos 3.23.0, the application no longer runs on azure app service, it crashes with this exception:

`Could not load file or assembly 'Microsoft.Azure.Cosmos.Direct, Version=3.23.1.0`

**Environment summary**
SDK Version: 3.23.0
OS Version: Linux with DOTNETCORE|6.0 on Azure App Service

**Comment by ealsur** [comment]
Did you make sure to clean the `bin` or output folder on the new release? Looks like it is trying to load the Direct DLL that comes from SDK 3.23.0 but not finding it.
If the DLL is there, it could be the version from 3.22.1 if you are copying files as deployment mechanism.

**Comment by onionhammer** [comment]
@ealsur yes, the bin has been cleaned and a fresh zip is uploaded as part of the deployment process.

**Comment by onionhammer** [comment]
Ok, I stand corrected... apparently an application will break if you do the following:

1. dotnet publish -c release -o /bin/publish
2. upgrade from 3.22.1 to 3.23.0
3. dotnet publish -c release -o /bin/publish
4. zip & deploy /bin/publish

so I guess? this isn't an issue?

**Comment by ealsur** [comment]
This is common on any shared DLLs if you are doing in-place deployment (normally the reason you deploy to staging and swap). DLLs can be locked while in use which would prevent them to be updated.
I would add a `dotnet clean` before your `dotnet publish` step in your flow.
