### ISSUE TITLE
[Internal] Client Telemetry: Collect Cache Information

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#2895]
We have following Caches in SDK:
1. LocationCache
2. GatewayAddressCache
3. TokenCredentialCache
4. PartitionKeyRangeCache
5. CollectionCache

Telemetry should collect following information about these caches:
1. Hit/Miss Latency (What was the latency at the time of refershing this cache)
2. Memory (How much memory space/response size it is taking)

**Open Questions:**
1. What all caches we have in SDK (other than mentioned above)? and Out of all of the above cache, should we have metrics for all the above caches? Is it worth having metrics for all of them?
2. What are the information we should collect? do you agree, "Latency"/ "Memory" information should be recorded in telemetry?

Related issue #2551

**Comment by kirankumarkolli** [comment]
Lets please clarify on what insights are needed and why (how it impacts our choice or support).

**Comment by sourabh1007** [comment]
Location Cache: 
1. Getting refresh in every 5 Minutes.
2. unavailableLocationsExpirationTime is 5 minutes by default but overidable through config i.e `System.Configuration.ConfigurationManager.AppSettings["UnavailableLocationsExpirationTimeInSeconds"]`

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8d3fb3e4bba1790bbd7ca02a0e70bbbcae33c2a3/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L431

**Comment by sourabh1007** [comment]
We have already implemented Latency telemetry collection for Collection Cache. Need to pick up other caches also.

**Comment by sourabh1007** [comment]
Closing as it is getting tracked in other issue.
