### ISSUE TITLE
EF Core provider gap: No way to know if CreateContainerIfNotExistsAsync actually created the container

### ISSUE THREAD

**Issue by divega** [Azure/azure-cosmos-dotnet-v3#29]
The method could return a bool indicating whether the container was actually created. 

Without this some APIs in EF Core will have unexpected results.

This issue was found while adapting EF Core provider to work with [Cosmos SDK version 3.0.0.1-preview](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.0.0.1-preview).

cc @AndriySvyryd @ajcvickers @kirillg

**Comment by j82w** [comment]
Hi Deigo, 

All of the Async method with throw an exception if it get's an error while creating the container. The exception to this rule is Cosmos Item Stream APIs which only return the status. This is for performance reasons. Also to note that not found is not an exception. This is considered as part of a normal workflow, and will return null for the resource.

The responses are documented [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmoscontainerresponse?view=azure-dotnet-preview).

**Comment by divega** [comment]
@j82w the issue was about being able to more easily distinguish between two different conditions when a call to CreateContainerIfNotExistsAsync succeeds:

- The container already exists and didn’t need to be created
- The container did not exist and was successfully created

I will let @AndriySvyryd comment if he still thinks there is an API usability or discoverability problem worth addressing.

**Comment by j82w** [comment]
@divega if that is the case you can do the read yourself, and if it is null do the create.
