### ISSUE TITLE
CosmosSerializer methods signature change

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-cosmos-dotnet-v3#2903]
Implementing CosmosSerializer is confusing and I believe it can be better.

First, `T FromStream<T>(Stream stream)` is asking me to dispose the stream otherwise it says I left stream open (only when `EnableContentResponseOnWrite = false` so the stream length is 0, but doesn't ask that when the stream has content). Beside this bug, I don't think a class should dispose a stream that doesn't own. the stream is coming from a client to CosmosSerializer, why CosmosSerializer should dispose it? what if the client still needs it? suggestion is to prevent disposing it here.

Second `Stream ToStream<T>(T input)` is unhappy if I dispose the stream, but that is the correct coding, the stream is created by CosmosSerializer so it should be disposed by it, what if the client didn't dispose it? suggestion here is to change signature to `void Write<T>(T input, Stream stream)` and so the CosmosSerializer shouldn't dispose it as it doesn't own it.

**Comment by ealsur** [comment]
At this point we cannot make such a breaking change on V3 SDK.

The request on FromStream makes sense, it is not clear on the requirements from the API perspective.

For ToStream, I am not fully sure I agree. The API says it returns a Stream, if it returns a Stream is for the caller to consume it. If the Stream is disposed inside the implementation, the caller cannot consume it.
I agree that possibly the alternative signature would be better, but again, we cannot change it at this point, this could be very well a feedback for the next SDK version @kirankumarkolli

**Comment by MhAllan** [comment]
Yes, **If the Stream is disposed inside the implementation, the caller cannot consume it** and we shouldn't prevent a class from disposing it's own streams because that is breaking encapsulation and relying on other classes to manage the owner class resources which doesn't look right for me. that is why the stream should come from the caller so the class doesn't temper with it just use it to write on it

**Comment by ealsur** [comment]
The story for V4 is that it needs to align with the central Azure SDK APIs (https://docs.microsoft.com/en-us/dotnet/azure/sdk/azure-sdk-for-dotnet). And they have their own Serializer API (https://docs.microsoft.com/en-us/dotnet/api/azure.core.serialization.objectserializer?view=azure-dotnet#methods) so I think it is already covered.

**Comment by MhAllan** [comment]
Thanks a lot @ealsur I will close this issue then
