### ISSUE TITLE
Disable DefaultTraceListener by default on the .NET SDK

### ISSUE THREAD

**Issue by asketagarwal** [Azure/azure-cosmos-dotnet-v3#2904]
Currently, the SDK enable the trace listener by default.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8d3fb3e4bba1790bbd7ca02a0e70bbbcae33c2a3/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L649

This should be disabled by default on the SDK to reduce lock contentions.

How to enable it by choice needs to be discussed.

**Comment by j82w** [comment]
Closed in: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2926
