### ISSUE TITLE
Missing documentation on how to manage a 404 when querying Cosmos

### ISSUE THREAD

**Issue by Ettores88** [Azure/azure-cosmos-dotnet-v3#2905]
In our program we perform LINQ queries with the SDKv3 with a helper method that looks something like the following example :

```
IQueryable<TEntity> cosmosQuery = _container.GetItemLinqQueryable<TEntity>(
    continuationToken: continuationToken,
    requestOptions: queryOptions
);

if (filter != null)
    cosmosQuery = cosmosQuery.Where(filter);

if (orderBy != null)
    cosmosQuery = cosmosQuery.OrderByDescending(orderBy);

var query = cosmosQuery.Select(select).ToFeedIterator();

var iterator = cosmosQuery.ToFeedIterator();
var items = new List<TEntity>();
while (iterator.HasMoreResults)
{
    var item = await iterator.ReadNextAsync();
    items.AddRange(item);
}
return items;
```

It happens occasionally that the ReadNextAsync raises a Cosmos Exception with StatusCode 404 and SubStatus 0.
Message from ApplicationInsights:
> Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: ; Reason: ();

The documentation specifies that this is expected behavior and the reason is:
> The collection is no longer a resource. For example, the resource may have been deleted.

What I can't find anywhere is how to manage this exception. Could I simply get a new Iterator?
```
...
var query = cosmosQuery.Select(select).ToFeedIterator();
try {
    var iterator = cosmosQuery.ToFeedIterator();
    var items = new List<TEntity>();
    while (iterator.HasMoreResults)
    {
        var item = await iterator.ReadNextAsync();
        items.AddRange(item);
    }
    return items;
}
catch (CosmosException e) when (e.StatusCode == HttpStatusCode.NotFound)
{
    var iterator = cosmosQuery.ToFeedIterator();
    var items = new List<TEntity>();
    while (iterator.HasMoreResults)
    {
        var item = await iterator.ReadNextAsync();
        items.AddRange(item);
    }
    return items;
}
```
Or do I need to open a new IOrderedQueryable from the Container?
I know that the code is really ugly but I hope that I pointed my needs. 

Thank you all!

**Comment by jackbond** [comment]
I've done a lot of Cosmos continuation queries and I don't think I've ever seen random 404s.

Are you dynamically creating / deleting containers in your environment? Perhaps you're receiving a bad error message. Which version of the SDK are you using?

**Comment by Ettores88** [comment]
Our containers are fixed, they are defined by the microservices of the systems, one for each. The 404 error happened only on heavy load scenarios when subsystems performed a high volume of queries on the Cosmos. These operations are performed daily but the 404 error happened only twice in 90 days but it was enough to stop the routines because was an unexpected scenario. This behavior lasted an hour at least during which some queries returned 404 (about 20-30% of the total requests) and after it all stabilized again.
We are using version 3.15.0 but we are evaluating to update to the latest (now it is the 3.23) but probably it won't be done soon.

**Comment by j82w** [comment]
Can you provide the full exception.ToString()?

**Comment by Ettores88** [comment]
**Exception type**: Microsoft.Azure.Cosmos.CosmosException
**Message**: Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: ; Reason: ();
**Call Stack**: 
Microsoft.Azure.Cosmos.CosmosException:
   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode (Microsoft.Azure.Cosmos.Client, Version=3.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Azure.Cosmos.QueryResponse`1.CreateResponse (Microsoft.Azure.Cosmos.Client, Version=3.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1+<ReadNextAsync>d__6.MoveNext (Microsoft.Azure.Cosmos.Client, Version=3.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   .... <our assemblies next>

**Comment by Ettores88** [comment]
We are using DirectMode (we were in GatewayMode but some 410 GONE during scale up&down pushed us to switch mode).

**Comment by j82w** [comment]
I would recommend upgrading latest SDK. Then provide the new exception.ToString(). There has been a lot of improvements in the exception handling and error messages.

**Comment by Ettores88** [comment]
We will evaluate the upgrade (for the new patch operation too). In the meanwhile how would you suggest mitigating this occurrence? The solution that I'm proposing, renewing the Iterator or the IOrderedQueryable could help to mitigate a bit the impact? 

At the same time we will continue to capture and log the exception.

**Comment by Ettores88** [comment]
We will upgrade into production the new SDK in the next week. From that moment we will continue to monitor the production environment and when (or if) a new occurrence of the 404 will happen I will update the issue with the new traces.

**Comment by kirankumarkolli** [comment]
@Ettores88 in previous occurrence are the containers dropped and re-created in-between? 

With re-creates the coding pattern is purely based on the expected application behavior in such cases. Please note that with above logic there might partial state from both old and new containers.

**Comment by Ettores88** [comment]
> @Ettores88 in previous occurrence are the containers dropped and re-created in-between?
> 
> With re-creates the coding pattern is purely based on the expected application behavior in such cases. Please note that with above logic there might partial state from both old and new containers.

No, we never drop containers. At that level, everything is managed outside of the application with proper processes. Strangely this error occurred just twice during massive operations on the Cosmos. After the migration to 3.23, we didn't experience the problem until now. I think that this version have fixed the problem, in fact, from another issue (https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2919) I see that a lot of rework has been done under the hood of the SDK.

**Comment by j82w** [comment]
@Ettores88 can you provide either the ResponseMessage.Diagnostics.ToString() or exception.ToString() of those 404?

**Comment by Ettores88** [comment]
@j82w the exception.ToString() is the one that I already provided: 
"Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: ; Reason: ();"

I cannot get the "ResponseMessage.Diagnostics.ToString()" 'cause a CosmosException is raised from the SDK when the Response is 404. But I see that CosmosException contains a Diagnostics property so with a HOTFIX we are going to trace that out.
