### ISSUE TITLE
creating database and container for gremlin db

### ISSUE THREAD

**Issue by EnenDaveyBoy** [Azure/azure-cosmos-dotnet-v3#2910]
**Describe the bug**
I am trying to create a database and container for a gremlin db, all the documentation says i should be using the Microsoft.Azure.Cosmos, however I am getting the error:

This is while testing locally

Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: Forbidden (403); Substatus: 0; ActivityId: 8d14c9cc-2a28-438a-8145-93d4c5af75cc; Reason: ("Operation 'POST' on resource 'dbs' is not allowed through Azure Cosmos DB endpoint. Please switch on such operations for your account, or perform this operation through Azure Resource Manager, Azure Portal, Azure CLI or Azure Powershell"

Looking up the error, none of the options have anything to do with my case, I have no network policies, I am within my credit limit 

var client = new Cosmos.CosmosClient(CosmosConnectionString);
    //Create Database
    var createResponse = await client.CreateDatabaseIfNotExistsAsync(DatabaseName);
    var db = createResponse.Database;
    //Create Container
    await db.CreateContainerIfNotExistsAsync(GraphName, PartitionKeyPath);

**Expected behavior**
it to create a database and container

**Actual behavior**
error as above

**Environment summary**
c# sdk, gremlin db in azure cosmos db, visual studio code

**Additional context**
the db is in the azure postal, but I am running the azure function locally

**Comment by philipthomas-microsoft** [comment]
Hello @EnenDaveyBoy thanks for contacting us. What you need is the Gremlin.net API. I advise you to checkout the following.

https://docs.microsoft.com/en-us/azure/cosmos-db/graph/create-graph-dotnet

There is also a sample here 

https://github.com/Azure-Samples/azure-cosmos-db-graph-gremlindotnet-getting-started.git

**Comment by philipthomas-microsoft** [comment]
@EnenDaveyBoy Have you taken a look at the following:

https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-forbidden#non-data-operations-are-not-allowed

**Comment by j82w** [comment]
The issue is Cosmos DB offers support for multiple different APIs like Cassandra, Mongo, Gremlin, SQL, etc.. The Microsoft.Azure.Cosmos nuget works with the SQL API. Since it is meant to work with SQL API it is blocked on the service because your account is gremlin. You need to use Azure CLI, Azure Powershell, Portal, ARM. You should be able to use the following nuget to create databases through ARM.  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/README.md

**Comment by EnenDaveyBoy** [comment]
thanks i have it working with Azure.ResourceManager.CosmosDB, bit of a pain it can't use the normal sdk
