### ISSUE TITLE
ReplaceItemAsync return value .Resource property is null in some cases

### ISSUE THREAD

**Issue by vakuras** [Azure/azure-cosmos-dotnet-v3#2911]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
ReplaceItemAsync return value's .Resource property is null is some cases.
We are using Azure Cosmos Db Emulator in the PR validation tests, and the test fails in the pipeline, but successed locally with the emulator.

**To Reproduce**
1. Create an item in a container.
2. Get the item from the container with ReadItemAsync.
3. Change a property on the item.
4. Call ReplaceItemAsync on that item.
5. Verity ReplaceItemAsync return value.

**Expected behavior**
.Resource property is set (!= null).

**Actual behavior**
.Resource propert is unset (== null).

**Environment summary**
cosmos-netstandard-sdk/3.23.1
Pipeline - Windows 10.0.17763
Local - Windows 11

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
Can you provide the [diagnostics ](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-dot-net-sdk-slow-request#capture-diagnostics)when the response is null?

**Comment by vakuras** [comment]
response.Diagnostics: {"Summary":{"DirectCalls":{"(200, 0)":1},"RegionsContacted":1},"name":"ReplaceItemAsync","id":"066f29a0-c211-4b50-8ebc-84bb2d65ce16","caller info":{"member":"OperationHelperWithRootTraceAsync","file":"ClientContextCore.cs","line":244},"start time":"02:42:49:768","duration in milliseconds":69.4006,"data":{"Client Configuration":{"Client Created Time Utc":"2021-11-30T14:42:48.5998036Z","NumberOfClientsCreated":75,"User Agent":"cosmos-netstandard-sdk/3.23.0|3.23.1|10|X64|Microsoft Windows 10.0.17763|.NET Core 3.1.20|N|F 00000001|","ConnectionConfig":{"gw":"(cps:50, urto:10, p:False, httpf: False)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:False, be:True)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[])"}},"children":[{"name":"ItemSerialize","id":"fd44c118-197e-4cc7-b6fd-9db8d7d59173","caller info":{"member":"ExtractPartitionKeyAndProcessItemStreamAsync","file":"ContainerCore.Items.cs","line":941},"start time":"02:42:49:768","duration in milliseconds":0.1863},{"name":"Get Collection Cache","id":"b5048e2a-6e45-4ce1-b0fc-e27cf4dffb16","caller info":{"member":"GetCollectionCacheAsync","file":"DocumentClient.cs","line":546},"start time":"02:42:49:769","duration in milliseconds":0.0017},{"name":"Batch Dispatch Async","id":"ebc4473f-5486-4a7e-9f7d-22aea7695961","caller info":{"member":"DispatchAsync","file":"BatchAsyncBatcher.cs","line":124},"start time":"02:42:49:831","duration in milliseconds":6.4986,"children":[{"name":"Using Wait","id":"db68fc4a-b666-4d6b-9039-7c0165ebcd03","caller info":{"member":"UsingWaitAsync","file":"Extensions.cs","line":189},"start time":"02:42:49:831","duration in milliseconds":0.0039},{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","id":"5c6fabfa-f831-4efc-81a5-6584ab6b42a6","start time":"02:42:49:831","duration in milliseconds":6.3342,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","id":"933300f6-61ad-44bd-9941-e78918c871e2","start time":"02:42:49:831","duration in milliseconds":6.3133,"data":{"System Info":{"systemHistory":[{"dateUtc":"2021-11-30T14:41:47.5052299Z","cpu":20.293,"memory":50211620.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0474,"availableThreads":32764,"minThreads":16,"maxThreads":32767}},{"dateUtc":"2021-11-30T14:41:57.5333143Z","cpu":8.995,"memory":50244204.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.04,"availableThreads":32765,"minThreads":16,"maxThreads":32767}},{"dateUtc":"2021-11-30T14:42:12.5333331Z","cpu":11.289,"memory":50137016.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0493,"availableThreads":32764,"minThreads":16,"maxThreads":32767}},{"dateUtc":"2021-11-30T14:42:27.5342586Z","cpu":15.117,"memory":50123940.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0083,"availableThreads":32764,"minThreads":16,"maxThreads":32767}},{"dateUtc":"2021-11-30T14:42:37.5534620Z","cpu":9.922,"memory":50110248.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0309,"availableThreads":32765,"minThreads":16,"maxThreads":32767}},{"dateUtc":"2021-11-30T14:42:47.5824589Z","cpu":20.132,"memory":50107356.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0101,"availableThreads":32763,"minThreads":16,"maxThreads":32767}}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","id":"7aacc42c-e07e-41d3-8a18-4b9e069874c9","start time":"02:42:49:831","duration in milliseconds":6.3096,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","id":"2c9ac2c8-b2cb-4f4c-8d78-dc03f543c2c7","start time":"02:42:49:831","duration in milliseconds":6.3,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","id":"fe9cb1e2-157a-4dd6-8713-9e627d0c552e","start time":"02:42:49:831","duration in milliseconds":6.2976,"children":[{"name":"Microsoft.Azure.Documents.ServerStoreModel Transport Request","id":"7471fe1f-395c-4037-a5db-d764911e7a84","caller info":{"member":"ProcessMessageAsync","file":"TransportHandler.cs","line":109},"start time":"02:42:49:831","duration in milliseconds":6.2092,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":12,"Uri":"rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer27/partitions/a4cb4967-38c8-11e6-8106-8cdcd42c33be/replicas/1p/"}],"RegionsContacted":["https://127.0.0.1:8081/"],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[{"ResponseTimeUTC":"2021-11-30T14:42:49.8378747Z","ResourceType":"Document","OperationType":"Batch","LocationEndpoint":"https://127.0.0.1:8081/","StoreResult":{"ActivityId":"5a0705c9-e3bf-44e8-b0fc-a5d44dcde445","StatusCode":"Ok","SubStatusCode":"Unknown","LSN":811,"PartitionKeyRangeId":"0","GlobalCommittedLSN":-1,"ItemLSN":-1,"UsingLocalLSN":false,"QuorumAckedLSN":810,"SessionToken":"-1#811","CurrentWriteQuorum":1,"CurrentReplicaSetSize":1,"NumberOfReadRegions":0,"IsValid":true,"StorePhysicalAddress":"rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer27/partitions/a4cb4967-38c8-11e6-8106-8cdcd42c33be/replicas/1p/","RequestCharge":13.71,"RetryAfterInMs":null,"BELatencyInMs":"5.285","transportRequestTimeline":{"requestTimeline":[{"event": "Created", "startTimeUtc": "2021-11-30T14:42:49.8318238Z", "durationInMs": 0.0045},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2021-11-30T14:42:49.8318283Z", "durationInMs": 0.0038},{"event": "Pipelined", "startTimeUtc": "2021-11-30T14:42:49.8318321Z", "durationInMs": 0.2418},{"event": "Transit Time", "startTimeUtc": "2021-11-30T14:42:49.8320739Z", "durationInMs": 5.6807},{"event": "Received", "startTimeUtc": "2021-11-30T14:42:49.8377546Z", "durationInMs": 0.105},{"event": "Completed", "startTimeUtc": "2021-11-30T14:42:49.8378596Z", "durationInMs": 0}],"requestSizeInBytes":1534,"requestBodySizeInBytes":1165,"responseMetadataSizeInBytes":247,"responseBodySizeInBytes":86},"TransportException":null}}]}}}]}]}]}]}]},{"name":"Create Trace","id":"411e3d64-0b79-44cf-900d-e937b300c254","caller info":{"member":"FromResponseMessageAsync","file":"TransactionalBatchResponse.cs","line":214},"start time":"02:42:49:837","duration in milliseconds":0.0357}]}]}

**Comment by ealsur** [comment]
Can you share the CosmosClientOptions you are using? Are you changing the value of EnableContentResponseOnWrite ?

**Comment by j82w** [comment]
The Cosmos DB SDK instance should be a singleton. This is required for bulk scenarios because each SDK instance has it's own connections, caches, and batching logic for the bulk operations.  The diagnostics shows `"NumberOfClientsCreated": 75,` which normally points to it getting recreated for each operation.

**Comment by ealsur** [comment]
Are you sure you don't are not setting EnableContentResponseOnWrite? This behavior exactly maps to that setting being false. 

If you can repro this consistently, and you have the reference of the container, can you check what is the container.Database.Client.ClientOptions.EnableContentResponseOnWrite value during the test?
Is the test injecting any CustomHandler in the pipeline?

**Comment by ealsur** [comment]
I have added a verification to our existing tests on this test PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2913, the Replace operation through Bulk mode is returning a Resource correctly, this is not a unit test, but a test against the Emulator (for all purposes it's a live account in terms of what the SDK does) and the test passes.

This confirms that the Resource is there.

**Comment by vakuras** [comment]
> Are you sure you don't are not setting EnableContentResponseOnWrite? This behavior exactly maps to that setting being false.
> 
> If you can repro this consistently, and you have the reference of the container, can you check what is the container.Database.Client.ClientOptions.EnableContentResponseOnWrite value during the test? Is the test injecting any CustomHandler in the pipeline?

I am sure. The test passes locally, but fails in the pipeline.
I don't have a custom handler.
Is it possible that the Cosmos Emulator is misbehaving in the pipeline?

**Comment by j82w** [comment]
Any chance you can provide a simple project that reproduces it? Are you using the latest emulator version?

**Comment by vakuras** [comment]
It is 2.14.3.0, same as the I have running locally.

**Comment by vakuras** [comment]
Upgrade to 2.13.4 solved the issue.

**Comment by vakuras** [comment]
Thanks!
