### ISSUE TITLE
Patch operation failed when path ends with tilde(~)

### ISSUE THREAD

**Issue by heebaek** [Azure/azure-cosmos-dotnet-v3#2921]
**Describe the bug**
PatchOperation.Add, Remove failed when path ends with tilde.

**To Reproduce**
{
    "list": {
        "123": "",
        "123!": "",
        "123@": "",
        "123#": "",
        "1_2": "",
        "1_2|": "",
        "1_2|.2": ""      
    },
    "pk": "test",
    "id": "test"
}
I tested with this simple document.
for example
PatchOperation.Add("/list/123~", "") => failed

**Expected behavior**
working without exception.

**Actual behavior**
Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: bfa9a491-53b2-4066-b03e-cf35b8b9d830; Reason: (Message: {"Errors":["One of the specified inputs is invalid"]}

**Environment summary**
SDK Version:3.23.0

**Comment by j82w** [comment]
This seems to be an issue with the service and not the SDK. @abhijitpai can you please take a look?

**Comment by j82w** [comment]
It's confirmed that this is related to the service and not the SDK.  @deparash please update this issue once you have more information. It seems to be related to the following RFC spec: https://stackoverflow.com/questions/24419391/how-is-the-tilde-escaping-in-the-json-patch-rfc-supposed-to-operate

**Comment by j82w** [comment]
@heebaek the patch operation is based on the [RFC spec](https://www.rfc-editor.org/rfc/rfc6902#appendix-A.14). To escape a ~ character you need to add 0 to the end.

`PatchOperation.Add("/123~0", "test")`

output:
```json
{
   "123~": "test"
}
```

**Comment by heebaek** [comment]
It seems working.
Thank you:)
