### ISSUE TITLE
Partition key delete

### ISSUE THREAD

**Issue by Mortana89** [Azure/azure-cosmos-dotnet-v3#2922]
Crossposting this from a private repo;
https://github.com/AzureCosmosDB/PartitionKeyDeleteFeedbackGroup/issues/14

The repo seems to be dead. Issue has been open for 4 months now, no reply whatsover.
This functionality used to work, but probably because of some serverside changes, it now fails to work.
I can find some stuff in this repo with regards to partiton-key deletes, but this functionality seems not to be available in the public api surface.

Can anyone guide us what the status of this issue is, what the planning is of including it in the SDK?

**Comment by abhijitpai** [comment]
We are looking at the issue you reported to the private repo and will get back shortly there; apologies for the delay. We are also working to expose this from the SDK version publicly available.
