### ISSUE TITLE
Cosmos DB RBAC - readChangeFeed permission required to read from query FeedIterator

### ISSUE THREAD

**Issue by AlexPiksel** [Azure/azure-cosmos-dotnet-v3#2927]
**Describe the bug**
We are currently replacing a broker-style access system in our solution with RBAC, as documented here: https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac

We have created a custom role for a service principal with the following permissions:

```
"Microsoft.DocumentDB/databaseAccounts/readMetadata",
"Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/*",
"Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/executeQuery"
```

This is applied at the Cosmos account level. This should enable that principal to perform CRUD and query operations on items within containers, but not create or delete databases or containers, or to read change feeds.

However, we are seeing the following errors when running our solution (guid redacted and container names changed):

```
"Request is blocked because principal [guid-redacted] does not have the required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/readChangeFeed] with OperationType [3] and ResourceType [2] on resource [dbs/mydbname/colls/mycontainer]"
```

Debugging this locally, this is being triggered by a routine which retrieves pages of data from a specified partition key:

```
CosmosClient client = await _clientFactory.GetCosmosClientAsync();
Container container = client.GetContainer(_databaseName, _containerName);

QueryRequestOptions options = new QueryRequestOptions
{
	PartitionKey = new PartitionKey(partitionKey),
	MaxItemCount = pagedRequestOptions.ItemsPerPage
};
IOrderedQueryable<T> queryable = container.GetItemLinqQueryable<T>(continuationToken: pagedRequestOptions.ContinuationToken, requestOptions: options);

using (FeedIterator<T> iterator = queryable.ToFeedIterator())
{
	if (iterator.HasMoreResults)
	{
		FeedResponse<T> response = await iterator.ReadNextAsync();
		// Build response with data and continuation token
	}
	else
	{
		//Build empty response
	}
}
```

Specifically, the error is thrown on the call to `iterator.ReadNextAsync()`. This is thrown on the first run, when `continuationToken` is still null.

I can add these permissions as a workaround, but this looks like a bug.

**To Reproduce**
1. Create a Role with the ability to run queries and read items, but not read change feeds.
2. Assign this to a Service Principal.
3. As that Service Principal, create a FeedIterator to read all items in a partition. It should fail on a call to `iterator.ReadNextAsync()`

**Expected behavior**
I would expect the query to execute successfully with the specified set of permissions, rather than requiring readChangeFeed.

**Actual behavior**
Operation fails due to lack of readChangeFeed permissions.

**Environment summary**
SDK Version: 3.23.0, .NET 3.1 latest
OS Version: Windows 10 20H2, also Windows Functions in Azure

**Additional context**
N/A

**Comment by j82w** [comment]
Can you provide the full exception message including the stack trace?

**Comment by AlexPiksel** [comment]
Attached. As in the example above I've redacted the SP GUID and changed the container/db names.

[cosmos_fulltrace_redacted.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/7702536/cosmos_fulltrace_redacted.txt)

**Comment by ealsur** [comment]
@AlexPiksel Is the CosmosClient being created with the default ConnectionMode (Direct) or changed to Gateway?

@j82w Could this be related to reading the change feed for partitions?

**Comment by AlexPiksel** [comment]
The client is being created with DirectConnection mode, although it's currently being explicitly set rather than relying on the default (a hangover from when we were using the V2 SDK):

```
ClientSecretCredential credential = _credentialProvider.GetCredential();
CosmosClientOptions options = new CosmosClientOptions
{
	ConnectionMode = ConnectionMode.Direct,
	MaxRetryAttemptsOnRateLimitedRequests = _config.MaxRetryAttemptsOnThrottledRequests,
	MaxRetryWaitTimeOnRateLimitedRequests = TimeSpan.FromSeconds(_config.MaxRetryWaitTimeOnThrottledRequestsInSeconds),
	SerializerOptions = new CosmosSerializationOptions
	{
		IgnoreNullValues = false // Required for Search APIs
	}
};
_client = new CosmosClient(_config.EndpointUri, credential, options);
```

For reference, `MaxRetryAttemptsOnThrottledRequests` is currently set to 10, `MaxRetryWaitTimeOnThrottledRequestsInSeconds` is currently set to 60 (which seems a bit high now I look).

**Comment by j82w** [comment]
@ThomasWeiss does read feed operations have its own permission or is it the same as the readChangeFeed? I don't see a specific permission for it here: https://docs.microsoft.com/azure/cosmos-db/how-to-setup-rbac

@AlexPiksel the query gets converted to a read feed operation because the LINQ operation does not have any filters.  If you add a filter like queryable it should work.

**Comment by ThomasWeiss** [comment]
Confirmed that `readChangeFeed` covers read feed operations, we'll update the docs to clarify

**Comment by AlexPiksel** [comment]
This discussion has been a bit confusing as I can't see any mention of Read Feed operations in the SDK docs, although they're mentioned in the REST API.

This old ticket suggests that they're now solely an internal concept: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/459

So if we took this sample file: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs

Am I correct that example 1.3 (read all items in a specific partition) would use Read Feed internally and thus require changeFeed permissions, while example 1.4 (query items by account number) would just require executeQuery?

If so, this problem may be difficult to solve just through documentation, given as the Read Feed concept is not visible to the SDK users.

**Comment by j82w** [comment]
You are correct. We will probably need to update the SDK comments to specify it's doing a read feed to avoid confusion in the future.

Read all items in [1.3](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/dd31c667b9dfdd150e3a4b994f2ef797cd4ac502/Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs#L276) is doing a read feed and requires the `readChangeFeed` permission. This is required because both read feed and change feed use the same endpoint unfortunately.

The query in [1.4](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/dd31c667b9dfdd150e3a4b994f2ef797cd4ac502/Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs#L353) requires the `executeQuery` permission.

**Comment by jcocchi** [comment]
I updated the [RBAC documentation](https://docs.microsoft.com/azure/cosmos-db/how-to-setup-rbac) to reflect that executing queries through the SDK requires both `executeQuery` and `readChangeFeed` permissions.
