### ISSUE TITLE
Attachment support in v3?

### ISSUE THREAD

**Issue by Tadimsky** [Azure/azure-cosmos-dotnet-v3#293]
Is there currently a way to read attachments in the v3 SDK or is that still in progress?
I see there are a number of classes and functions related to attachment reading, but it doesn't look like they're accessible yet. Is that true or am I not discovering it correctly?

- https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5ce792f507f3039b7d4d97c0c7909f53a4551635/Microsoft.Azure.Cosmos/src/MediaResponse.cs#L14
- https://github.com/Azure/azure-cosmos-dotnet-v3/blob/7e49190e518b5ee3e0a604f8d17586c7603912f8/Microsoft.Azure.Cosmos/src/MediaOptions.cs#L9
- https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5ce792f507f3039b7d4d97c0c7909f53a4551635/Microsoft.Azure.Cosmos/src/ResourceFeedReaderClientExtensions.cs#L159-L163
- https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5ce792f507f3039b7d4d97c0c7909f53a4551635/Microsoft.Azure.Cosmos/src/IMediaHandler.cs#L32-L34

**Comment by coffeymatt** [comment]
Can this be un-parked? I can't migrate without this functionality.

**Comment by davidxcrowe** [comment]
Am I right in thinking this functionality still isn't available?

**Comment by Tadimsky** [comment]
Unfortunately I believe that CosmosDb attachments are no longer something they're trying to support.
If you search in the CosmosDb docs you'll no longer find references to attachments: [GitHub docs search](https://github.com/MicrosoftDocs/azure-docs/search?q=CreateAttachmentAsync&unscoped_q=CreateAttachmentAsync)

So it's likely they're not planning on support attachments in v3? But it would be nice to get confirmation from them. Maybe it's something the community could add support for to this SDK.

**Comment by DiaAWAY** [comment]
Any news on this? This is currently blocking our migration to .NET core :\

**Comment by aliuy** [comment]
Attachments is a legacy feature supported in v2.

At the point in time, we recommend using Azure Blob Storage as a superior blob storage alternative Cosmos DB attachments. We do not have plans for introducing attachments in v3+ onwards.

To find out more - please see: https://docs.microsoft.com/en-us/azure/cosmos-db/attachments
