### ISSUE TITLE
Client Telemetry: Add Threadpool information

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#2930]
**Is your feature request related to a problem? Please describe.**
Today we have aggregated information of CPU usage and Memory Remaining. We are already collecting Threadpool information in our diagnostics. It can be stored in client Telemetry also.

**Describe the solution you'd like**
In order to get the clear picture of Thread pool information of the customer, Aggregated Thread pool information needs to be pushed  through telemetry.

Available Worker Threads
  Metric Name: AvailableWorkerThreads
  Metric Unit: Threads
Min Worker Threads
  Metric Name: MinWorkerThreads
  Metric Unit: Threads
Max Worker Threads
  Metric Name: MaxWorkerThreads
  Metric Unit: Threads

**Comment by simplynaveen20** [comment]
Is it possible to create some sample diagnostics json including this info , easy to visualize , that under what category it will come
Also this will be .NET specific if we don't have type of pool (including custom) like in other platform including java, lets brainstorm offline on that

**Comment by sourabh1007** [comment]
```
 {
      "resource": "HostMachine",
      "metricInfo": {
        "metricsName": "AvailableWorkerThreads",
        "unitName": "Threads",
        "mean": 32704,
        "count": 2,
        "min": 32640,
        "max": 32767,
        "percentiles": {
          "50": 32767,
          "90": 32767,
          "95": 32767,
          "99": 32767,
          "99.9": 32767
        }
      }
    },
    {
      "resource": "HostMachine",
      "metricInfo": {
        "metricsName": "MinWorkerThreads",
        "unitName": "Threads",
        "mean": 8,
        "count": 2,
        "min": 8,
        "max": 8,
        "percentiles": {
          "50": 8,
          "90": 8,
          "95": 8,
          "99": 8,
          "99.9": 8
        }
      }
    },
    {
      "resource": "HostMachine",
      "metricInfo": {
        "metricsName": "MaxWorkerThreads",
        "unitName": "Threads",
        "mean": 32704,
        "count": 2,
        "min": 32640,
        "max": 32767,
        "percentiles": {
          "50": 32767,
          "90": 32767,
          "95": 32767,
          "99": 32767,
          "99.9": 32767
        }
      }
    }
```

**Comment by simplynaveen20** [comment]
As per offline conversation with Sourabh

Metrics - SystemPool_AvailableThreads  - For Dot Net Specific
Metrics - SystemPool_MaxWorkerThreads  - For Dot Net Specific
Metrics - SystemPool_MinWorkerThreads  - For Dot Net Specific
Metrics - CustomePoolName_AvailableThreads - For any other plaform
Metrics - CustomePoolName_MaxWorkerThreads  - For any other plaform
Metrics - CustomePoolName_MinWorkerThreads  - For any other plaform

**Comment by simplynaveen20** [comment]
"unitName": "Threads" -> "unitName": "ThreadCount",
