### ISSUE TITLE
PatchOperation.Set cannot handle null values

### ISSUE THREAD

**Issue by loraderon** [Azure/azure-cosmos-dotnet-v3#2931]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
PatchOperation.Set throws ArgumentNullException when value is null.

**To Reproduce**
await container.PatchItemAsync<T>(id, PartitionKey.None, new List<PatchOperation> { PatchOperation.Set<string>("/name", null) });

**Expected behavior**
Value should be set to null.

**Actual behavior**
> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Microsoft.Azure.Cosmos.PatchOperationCore`1..ctor(PatchOperationType operationType, String path, T value)
   at Microsoft.Azure.Cosmos.PatchOperation.Set[T](String path, T value)

**Environment summary**
SDK Version: 3.23.0
OS Version (e.g. Windows, Linux, MacOSX) Windows 11

**Additional context**
According to @sajeetharan (https://stackoverflow.com/a/70194090/22092), this seems to be a known issue but I couldn't find any matching issue in github.
![image](https://user-images.githubusercontent.com/76928/146001341-61c48c3f-2983-4f39-a8c1-8474505b79be.png)

**Comment by yang-er** [comment]
Hi, I have a workaround as below which could resolve your problem:

```
await container.PatchItemAsync(id, PartitionKey.None, new List { PatchOperation.Set("/name", new MemoryStream(Encoding.UTF8.GetBytes("null"))) });
```

My thought is that here we shouldn't add null checks for value.

**Comment by Jezternz** [comment]
This sounds like it should work, but it appears that to make this workaround work as expected, modifications to json serialization would somehow have to happen:
![image](https://user-images.githubusercontent.com/987884/152471351-1dbce446-0e94-4a54-b4a7-cb703ecbe4d0.png)

**Comment by rvdvelden** [comment]
This works for me.

Instead of using null I just create a JProperty with the value null. And use that value.

`       
private JToken NullValue
{
    get
    {
        return new JProperty("nullValue", null).Value;
    }
}
`
And use it like this
`
operations.Add(PatchOperation.Set("\customer", value ?? NullValue));
`

**Comment by Jezternz** [comment]
The workaround did not work for me, the container threw an exception complaining that it could not serialize MemoryStream's without additional json serialization configuration. As this is becoming a pretty involved / and would become a horrid workaround and I technically don't need to be able to update nulls yet, I am throwing an exception for now:
```
            if(patchItem.Value == null)
            {
                throw new NotImplementedException(
                    "...CosmosDbRepository.PatchItemAsync "+
                    "does not currently support setting null values. "
                );
                // It would be good to get this working in future
                // however for the time being you cannot patch field values to be null
                // See this issue to track progress https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2931
            }
```

Any ETA on a fix @j82w? this feels kind of serious.

**Comment by yang-er** [comment]
BTW, a much easier to get a null JToken: JRaw.CreateNull()

**Comment by kirankumarkolli** [comment]
@deparash what's the expected server contract for such scenarios?

**Comment by kirankumarkolli** [comment]
Update: (offline closure with @deparash )

Value is expected and it should be JSON NULL. 
Current implementation is using JSON.NET for writing and it can leverage WriteNull() instead.

**Comment by kirankumarkolli** [comment]
@SchintaMicrosoft assigned it to you.

**Comment by onionhammer** [comment]
This should still be open, not closed. There are hacky workarounds for now, commented above

**Comment by j82w** [comment]
Github automatically closes the issue when the PR is merged. A new version should be released hopefully by tomorrow with the fix.

**Comment by onionhammer** [comment]
Not fixed in 3.26.2

**Comment by j82w** [comment]
Sorry about the confusion. The fix is going out in 3.27.0 which can be tracked here: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3172
The 3.27 release is waiting on this fix: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3168
3.26.2 is a hotfix to unblock a customer hitting an issue in production which is why it only has 3 required changes cherry picked.

**Comment by j82w** [comment]
@onionhammer please try the latest SDK release 3.27.0 https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.27.0

**Comment by onionhammer** [comment]
Yep, thanks, that fixes it

**Comment by gagwithgaffer** [comment]
Using Microsoft.Azure.Cosmos 3.28 and i dont see any fix? will have to resort to the above said workaround from [rvdvelden](https://github.com/rvdvelden)
