### ISSUE TITLE
Is there a bulk remove property sample?

### ISSUE THREAD

**Issue by Jen-Pearson** [Azure/azure-cosmos-dotnet-v3#2936]
I'm struggling to find an example - basically I want all documents in my cosmosDB container to have a particular property removed from within an array property.

I think in the older library there might have been an [UnsetUpdateOperation](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/bulk-executor-dot-net)

But am struggling to know if that's what I need to do in the new library - and that it's less likely to max out my RUs like my iteration approach did.

**Comment by j82w** [comment]
There isn't a sample that does exactly what you want. 

.NET v3 Bulk explained here: https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/

Are you trying to remove a property from all the objects in the array? Just the first object? I'm hoping that patch can be used to do the remove.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/dd31c667b9dfdd150e3a4b994f2ef797cd4ac502/Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs#L520

**Comment by Jen-Pearson** [comment]
@j82w  thanks!  yeah so my item has a property of an array of items.  Within that array there is an unused property that I want to remove to avoid confusion.  So yes I do want to do it for every document in my collection that has this property.  I thought patch was just for updating the value of a particular property rather than removing the property altogether?

This is the script I had tried before it maxed out my RUs whilst making very slow progress.

`foreach (var transactionItem in await iteratorToUpdate.ReadNextAsync())
		{
			// grab latest version for optimistic concurrency
			var transactionId = (string)transactionItem["id"];
			var partitionKey = new PartitionKey(transactionId);

			var transactionItemToUpdate = await container.ReadItemAsync<JObject>(transactionId, partitionKey);
			var transaction = transactionItemToUpdate.Resource;
			foreach (var childItem in (JArray)transaction["TransactionLineItems"])
			{
				((JObject)childItem).Remove("TransferId");
				$"Removing 'TransferId' property from transaction '{transactionId}' Item '{childItem["SourceSystemItemId"]}'".Dump();
			}

			var replaceOptions = new ItemRequestOptions { IfMatchEtag = transactionItemToUpdate.ETag };
			await container.ReplaceItemAsync(transaction, transactionId, partitionKey, replaceOptions);

			// Giving some breathing space to Cosmos
			await Task.Delay(300);
		}
`

**Comment by Jen-Pearson** [comment]
@j82w couple of questions on that sample.
1. Trying to access the _etag value when pointing it to my own repository of items throws an exception when trying to get the etag value - despite it being in the cosmosDB items.
itemRequestOptions.IfMatchEtag = item["_etag"].Value<string>();

Do I have to declare my model somewhere or should I just be able to work on the JObject item.  It doesn't seem like the sample uses the MyDocument for the remove property - only on create.

2. Removing this line has run successfully but I've also lost all properties of my documents.  So it doesn't seem like anything other than the id is available on my item so I imagine I'm missing part of the mental puzzle :)

**Comment by Jen-Pearson** [comment]
@j82w I've tried including my class in case that helped - but in all instances all my properties are null except if I call a ReadItemAsync on it.  The top section of this code is the only way I get a populated item otherwise I'm saving back nulls. 

The difference between my document and the sample - the sample items all have lower case properties.  In mine I have "id" but then the rest of the properties are CamelCase.   

![image](https://user-images.githubusercontent.com/8033039/150912462-759ad0a8-d526-415a-a891-d3f67b322130.png)

I'm sure bulk updating will give me better results if I can figure it out - not sure though that I'm going to prevent the excessive RU consumption which is what I was getting as I seem to have to read each item.

**Comment by Jen-Pearson** [comment]
@j82w ok so I've almost got it I think.  My issue though is that the property I want to remove is embedded within an array.  ie. I have a LineItems array and each item could have a TransferId property.  So I have a query that will select the whole object from the root level - but when I call Remove("TransferId") or Remove("LineItems.TransferId") nothing changes.  How would I remove a child property from an array within the document?

**Comment by j82w** [comment]
Looking at the code everything looks good like the property should be removed. If you look at the item.ToString() is the json updated with the property removed? How are you verifying it is not updated?

Scaling up may cause requests to be delayed for several seconds. The SDK has to refresh its caches and reroute the request to the new partition. Scaling down should not have any impact.

**Comment by Jen-Pearson** [comment]
@j82w all good thanks the property gets removed with the updated code above. Was more the concern of it costing 13.x ru per document - adds up to a lot of rus but I guess it’s unavoidable with this flexibility of unstructured data storage 😊 hanks for your help.
