### ISSUE TITLE
Cosmos client 503 disambiguation

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#2942]
Add the following SubStatusCodes for 503's

// Client SubStatusCodes

1. TransportGenerated410 : TransportException creating a 410. Converted to 503 after retries in GoneAndRequestRetryPolicy.
2. TimeoutGenerated410 : 410 generated due to timeout (ThrowGoneifElapsed). Converted to 503 after retries.
3. ClientCPUOverload: 503 from GoneAndRequestRetryPolicy when CPU overload detected.
4. ClientThreadStarvation: 503 from GoneAndRequestRetryPolicy when Thread Starvation detected.
5. TransportGenerated503: TransportException creating a 503

// Server SubStatus Codes

1. ServerGenerated410 : Service generated 410 with 0 substatus code. Converted to 503 after retries
2. GlobalStrongWriteBarrierNotMet: 410 created by ConsistencyWriter. Converted to 503 after retries
3. ReadQuorumNotMet: 410 created QuorumReader. Converted to 503 after retries.
4. ServerGenerated503: Service generated 503 with 0 substatus code
5. NameCacheIsStaleExceededRetryLimit: 410 with namecachestaleexception. Converted to 503.
6. PartitionKeyRangeGoneExceededRetryLimit: 410 with PartitionKeyRangeGoneException. Converted to 503.
7. CompletingSplitExceededRetryLimit: 410 with PartitionKeyRangeIsSplittingException. Converted to 503.
8. CompletingPartitionMigrationExceededRetryLimit: 410 with CompletingPartitionMigrationException. Converted to 503.
9. NoValidStoreResponse: 410 thrown when there is no valid store response from backend.

**Comment by asketagarwal** [comment]
https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/710037
