### ISSUE TITLE
Strong consistency: Optimization

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#2943]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

@asketagarwal please fill the details

**Comment by asketagarwal** [comment]
https://microsoft-my.sharepoint.com/:w:/r/personal/askagarw_microsoft_com/_layouts/15/doc.aspx?sourcedoc=%7B1b7e2236-e46d-41bc-9e08-427e23d66e22%7D&action=edit

**Comment by asketagarwal** [comment]
Upon discussion, we are closing this issue considering the perf improvements were not worth the effort and the risk to make this change.
Branch				P99 Throughput	P90 Throughput	     P90 Latency		  P99 Latency
strongoptimize			6891			7051				3.67				18.92
master					6471			6562				3.45				18.64
