### ISSUE TITLE
Add ServiceInterop.dll fallback support for ARM64

### ISSUE THREAD

**Issue by Krumelur** [Azure/azure-cosmos-dotnet-v3#2951]
**Describe the bug**
Running any SQL-based queries triggers a type load exception on ARM64 (Win 11 preview)

`An exception of type 'System.DllNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Unable to load DLL 'Microsoft.Azure.Cosmos.ServiceInterop.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)'

**To Reproduce**
Use `Container.GetItemQueryIterator()` to execute any `QueryDefinition`.

**Expected behavior**
According to docs <https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-dot-net-sdk?tabs=diagnostics-v3#common-query-issues> a fallback should occur:

> For Linux and *other unsupported platforms* where ServiceInterop.dll isn't available, an additional network call will be made to the gateway to get the optimized query.

With ARM64 being an unsupported platform, a network call should occur instead of an exception.

**Actual behavior**
Type load exception occurs instead of a lower-performance network call fallback.

**Environment summary**
SDK Version: 3.23
OS Version: Windows 11 Insider Preview ARM64

**Comment by ealsur** [comment]
Closed by https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3226. Released in 3.27.2
