### ISSUE TITLE
Client Telemetry: Add current number of established Tcp connections

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#2956]
Knowing the current number of established Tcp connections would be good to troubleshoot  SNAT scenarios.

**Comment by sourabh1007** [comment]
Number of opened TCP connection to particular replica are there in Request diagnostics. 
![image](https://user-images.githubusercontent.com/6362382/158555322-104aa426-da48-4543-bed7-d2d30c75bccb.png)

Related Github issue : https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2744
