### ISSUE TITLE
Database.ReadThroughputAsync overload throws for databases without provisioned throughput

### ISSUE THREAD

**Issue by abhijitpai** [Azure/azure-cosmos-dotnet-v3#2959]
**Describe the bug**
The database.ReadThroughputAsync overload that takes RequestOptions throws the below CosmosException when the database doesn't have throughput provisioned though its documentation has the following remark:
    /// <remarks>
    /// Null value indicates a database with no throughput provisioned.
    /// </remarks>

Error: Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: ; Reason: (Throughput is not configured for fmhzAA==);
   at Microsoft.Azure.Cosmos.CosmosOffers.GetOfferV2Async[T](String targetRID, Boolean failIfNotConfigured, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.CosmosOffers.ReadThroughputAsync(String targetRID, RequestOptions requestOptions, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.DatabaseCore.ReadThroughputAsync(RequestOptions requestOptions, ITrace trace, CancellationToken cancellationToken)

**To Reproduce**
Invoke database.ReadThroughputAsync(null) on an existing database without provisioned throughput.

**Expected behavior**
ThroughputResponse with null ThroughputProperties. This allows the caller to avoid the try-catch in getting the ThroughputProperties (such as auto-scale max throughput) associated with a database.

**Actual behavior**
CosmosException above.

**Environment summary**
SDK Version: 3.23.0
OS Version (e.g. Windows, Linux, MacOSX) - Windows

**Comment by kirankumarkolli** [comment]
@NaluTripician can you please take a look?

**Comment by ealsur** [comment]
@kirankumarkolli Would this be a breaking change though? Any change in behavior should match also for `container.ReadThroughputAsync` right?

**Comment by ealsur** [comment]
@abhijitpai Regarding this issue, wouldn't the change be a breaking change? Assuming users already have logic that reacts to the exception?

**Comment by abhijitpai** [comment]
We can fix the documentation of this and add another overload that doesn't throw the exception.

**Comment by NaluTripician** [comment]
@abhijitpai please let me know your thoughts on the following proposal to fix this issue.

-Adding a new optional input to second overload, `failIfNotConfigured` , that is causing the exception. This would have a default value of `true`. This would allow users to get the information from the `ThroughoutResponse` and would not be a breaking change as if this variable is not set when the method is called it will default to the original behavior.  The new function header would be this: 

```
public async Task<ThroughputResponse> ReadThroughputAsync(
            RequestOptions requestOptions,
            ITrace trace,
            CancellationToken cancellationToken,
            bool failIfNotConfigured)
```
This would also change the `ReadThroughputAsync` method in `CosmosOffers` and in the circumstance where it has null provisioned throughput to return
```
return new ThroughputResponse(
                    HttpStatusCode.NotFound,
                    headers: null,
                    throughputProperties: null,
                    diagnostics: null,
                    requestMessage: null);
```

**Comment by FabianMeiswinkel** [comment]
@NaluTripician - I think this is a really bad idea because it is inconsistent with other APIs in the V3 SDK.

Task<T> ReadXXXAsync will throw NotFoundException on 404 
Task<ResponseMessage> ReadXXXStreamAsync is exceptionless and will return a ResponseMessage without Content (being null) and StatusCode 404 in this case.

Please let's keep the public surface area consistent here!

**Comment by NaluTripician** [comment]
@FabianMeiswinkel thank you for clarifying. So a better approach would be to create a ReadThroughputStreamAysnc method to me more consistent with the rest of the API

**Comment by ealsur** [comment]
@NaluTripician Could you draft a proposed API like you did on the previous comment or update it?
