### ISSUE TITLE
await container.CreateItemAsync<Class>(oC) close my console application without error code or message

### ISSUE THREAD

**Issue by apzyx** [Azure/azure-cosmos-dotnet-v3#2961]
**Describe the bug**
I connect with CosmosDB and do a container.GetItemQueryIterator and work correctly.
But when i do await container.CreateItemAsync<Class>(oC) my console application exit with code 0 (0x0), without message or error, with try/catch not work neither, the application exit.

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

**Environment summary**
SDK Version: 3.23.0
OS Version (e.g. Windows, Linux, MacOSX) Windows 11 (Build 22523 WIP) & Microsoft Visual Studio Community 2022 (64 bits) - Preview Versión 17.1.0 Preview 1.1

**Comment by j82w** [comment]
Please provide a sample that reproduces the issue. There are a lot of tests validating this scenario and they are all passing.

**Comment by ealsur** [comment]
Are you running inside Visual Studio (debugging) or running the console app from prompt? Could you please share more information that can help reproduce the described issue, like the code you are using and screenshots of what you are seeing?

**Comment by apzyx** [comment]
The error is Running inside Visual Studio (debugging),

this is the method:

private async Task primoEncontrado(BigInteger primo)
        {
            String pS = primo.ToString();            
            await container.CreateItemAsync<dynamic>(new { id = pS, isP = true});
        }

and the parameter of "primo" = 13
when do the line "await container.CreateItemAsync<dynamic>(new { id = pS, isP = true});" the application and debugging exit, it is the same for Visual Studio 2019 and Visual Studio 2022,

Thanks you for your time =)

**Comment by apzyx** [comment]
I´m trying and is only when you stop with a debugging stop point, if i don´t set stop debugging point the app works

**Comment by j82w** [comment]
I don't see any obvious issues with the above code. Is there any way you can share the entire project that way everything is the same and we can try running it to see if it reproduces?(make sure to remove any secrets)

**Comment by ealsur** [comment]
There is nothing wrong with the code. Make sure your VS is configured to halt on unhandled exceptions, you can also try running the application outside of VS and see how it behaves. Make sure you have no global try/catch that might be swallowing exceptions.
Like @j82w said, that small code snippet doesn't have any issues.

**Comment by apzyx** [comment]
[pnsS.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/7803286/pnsS.zip)

Here the proyect that is not working only need a cosmosdb with databaseid "ToDoList"  and containerid "Items" =)

**Comment by ealsur** [comment]
Your problem is that you are firing an async task and not waiting it (Fire and Forget antipattern).

Your main is `async`:

```
static async Task Main(string[] args)
```

You are calling `seguirLaBusqueda` without awaiting it, and it's an `async` method:

![image](https://user-images.githubusercontent.com/1633401/147969606-10b0787b-b468-4491-bcb9-04efdd3df2a7.png)


![image](https://user-images.githubusercontent.com/1633401/147969587-31b5e833-5ec6-4e73-8a8d-3060f0bc0126.png)

To fix your program you need to:

1. `await p.seguirLaBusqueda(seguirPor);`  in the `Main`
2. Make sure seguirLaBusqueda is an `async Task` not `async void`: `private async Task seguirLaBusqueda(BigInteger seguirPor)`

This is not an SDK problem but rather the code not following async/await pattern.
