### ISSUE TITLE
Make IndexingPolicyEqualityComparer public

### ISSUE THREAD

**Issue by ccurrens** [Azure/azure-cosmos-dotnet-v3#2964]
**Is your feature request related to a problem? Please describe.**
We have code that uses attributes to mark properties on objects as indexable. We use these attributes to generate an `IndexPolicy` that represents all indexes needed by our applications. At startup, we fetch the container's indexing policy from the server and compare the existing policy with the generated one to see if it needs to update the container and start a new index transformation.

We noticed that an equality comparer already existed in the SDK, but is internal for tests.

**Describe the solution you'd like**
[Make IndexingPolicyEqualityComparer (and related classes) publicly accessible](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/3c6d747326c893eb17c31645282e536938c563af/Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs#L494) as a top-level class.

**Describe alternatives you've considered**
Continue to use our own comparer, use reflection to access the class internal to the SDK, or copy the code directly into our project.

**Additional context**
None.

**Comment by kirankumarkolli** [comment]
So-far its a single ASK, we will revisit making it public contract later.
