### ISSUE TITLE
Fix Cosmos*Headers name to follow .NET standards

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#297]
**Describe the solution you'd like**
The following classes are collections of strings, but do not end with suffix Collection which is against [.NET standards](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1710-identifiers-should-have-correct-suffix?view=vs-2019).

Severity	Code	Description	Project	File	Line	Suppression State
Error	CA1710	Rename Microsoft.Azure.Cosmos.CosmosResponseMessageHeaders to end in 'Collection'.	Microsoft.Azure.Cosmos	C:\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\src\Headers\CosmosResponseMessageHeaders.cs	19	Active
Error	CA1710	Rename Microsoft.Azure.Cosmos.CosmosMessageHeadersBase to end in 'Collection'.	Microsoft.Azure.Cosmos	C:\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\src\Headers\CosmosMessageHeadersBase.cs	14	Active
Error	CA1710	Rename Microsoft.Azure.Cosmos.CosmosRequestMessageHeaders to end in 'Collection'.	Microsoft.Azure.Cosmos	C:\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\src\Headers\CosmosRequestMessageHeaders.cs	18	Active

**Comment by kirankumarkolli** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpheaders?view=netframework-4.8

Its similar to HttpHeader.
