### ISSUE TITLE
Performance: CosmosDiagnostics remove callerinfo and make data dictionary lazy

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2972]
1. The Trace library always creates a CallerInfo object. This adds overhead to both collecting the trace and the CosmosDiagnostic.ToString() logic. There has been no use case for this information so it should be removed until there is a scenario.

2. IReadOnlyDictionary should be created lazily. In most traces no data is being added. A static singleton could be used by default. Once information is being added a new dictionary instance would be created. 
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e3fe30a94403217b1a015e459ae6ad896e633e79/Microsoft.Azure.Cosmos/src/Tracing/Trace.cs#L55

**Comment by kirankumarkolli** [comment]
@asketagarwal can you please take a look?
