### ISSUE TITLE
Fix bug preventing recovering from 410/0 after split

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2974]
This issue was fixed in Java, but it seems to exist in .NET. This change needs to be ported to .NET SDK.
https://github.com/Azure/azure-sdk-for-java/pull/23262

**Comment by kirankumarkolli** [comment]
What will be returned by gateway for a parent partition addresses?

**Comment by j82w** [comment]
Closing this issue because it was not possible to reproduce the issue. This can be revisited in the future if a customer actually finds a scenario it is not working correctly.
