### ISSUE TITLE
Documentation on continuation tokens

### ISSUE THREAD

**Issue by robertbennett1998** [Azure/azure-cosmos-dotnet-v3#2987]
I am trying to understand the behaviours and rationale behind the behaviours of the continuation tokens. However, I cannot find any official documentation on them past a basic article on MSDN (https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-pagination) and the sample it links out to. These diagrams below (generated from experimenting with cosmos db) highlight the sort of behaviours  I mean. Is there any documentation that goes into more detail of how these work. Thanks.

![image](https://user-images.githubusercontent.com/8798036/150123917-448be6f7-4712-4d9f-a1ac-5d2f363054fd.png)

**Comment by ealsur** [comment]
@robertbennett1998 Is your question if continuation tokens behave the way you are describing in the diagrams? @timsander1 is there any specific doc that explains this behavior somewhere?

**Comment by timsander1** [comment]
Hi @robertbennett1998, there's no additional documentation on how continuation tokens work but I can answer some questions here and update the existing doc with important points.

I would define a continuation token in simple language as “a bookmark that allows you to know where you left off in running a query and allows you to resume at that point without repeating most of the previous work”. If you add a new document or update a document, there’s a chance you can miss results across query pages or get multiple results. My analogy to the bookmark example would be that if you have a bookmark on Page 35 of a 100 page book and someone adds a sentence on Page 24, you won’t be able to read that sentence unless you were to start over from Page 1. A continuation token is a bookmark and doesn't contain information about the actual contents of the previous 34 pages.

Here's an example with a query. Let's say I have 100 documents in my collection and MaxItemCount = 10.
Here's my query: SELECT * FROM c ORDER BY c.id

If after the first page of results, I were to delete some of the data that would have appeared on later pages, the query won't return this data. In other words, we'd return fewer than 100 documents in total. The continuation token doesn't capture a snapshot of the documents that existed when the very first page of the query was run. Instead, it's a bookmark for the query to resume at a specific point.

Here's another example with a query where the property values in the ORDER BY clause change. Let's say I had a document with "value" property. Value = 1 to start off.
Here's my query: SELECT * FROM c ORDER BY c.value ASC

If I were to run a query with MaxItemCount = 1 and keep incrementing the "value" after each query page, I'd continue to get the same document back in query results again and again (with the updated value).

**Comment by ealsur** [comment]
Closing as question has been answered
