### ISSUE TITLE
Full Fidelity for CF pull model

### ISSUE THREAD

**Issue by philipthomas-MSFT** [Azure/azure-cosmos-dotnet-v3#2994]
This is subject to change based on in-flight discussions.

P0: CF pull model support in .NET and Java (including split-proofing)
P0: Updating naming in the CF pull model
P0: Update the SDK to include the metadata (previousImage, operationType, etc) in the API itself rather than jammed into the _metadata property

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kirankumarkolli** [comment]
This is completed
