### ISSUE TITLE
Full Fidelity for CFP push model

### ISSUE THREAD

**Issue by philipthomas-MSFT** [Azure/azure-cosmos-dotnet-v3#2995]
This is subject to change based on in-flight discussions.

P1: Basic Change Feed Processor Library support in .NET (it’s okay if not all request options are supported yet)
P1: Basic CFP support in Java (it’s okay if not all request options are supported yet)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kirankumarkolli** [comment]
Completed
