### ISSUE TITLE
Full Fidelity CF/P push and pull model - Complete support

### ISSUE THREAD

**Issue by philipthomas-MSFT** [Azure/azure-cosmos-dotnet-v3#2996]
This is subject to change based on in-flight discussions.

P2: Supporting reading FFCF with Functions triggers (not sure how much work this is)
P2: Full CFP support in .NET
P2: Full CFP support in Java
P2: Change feed estimator support

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by petro2050** [comment]
@philipthomas-MSFT Can you please provide an ETA on this? Full-fidelity was promised a long time ago. Now, it's only in triage?

**Comment by kirankumarkolli** [comment]
Done
