### ISSUE TITLE
ProcessItemAsync<>() should ensure requestOptions is not null before calling ValidatePartitionKey()

### ISSUE THREAD

**Issue by divega** [Azure/azure-cosmos-dotnet-v3#30]
This seems to be a bug in the implementation. 

This issue was identified while adapting EF Core provider to work with [Cosmos SDK version 3.0.0.1-preview](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.0.0.1-preview).

cc @AndriySvyryd @ajcvickers @kirillg

**Comment by j82w** [comment]
Hi Diego,

You are correct this is bug, and it will be fixed in the next release which should hopefully be soon.

**Comment by j82w** [comment]
This was fixed in 3.0.0.9 preview release
