### ISSUE TITLE
CosmosClient.WithEncryption() does not accept AzureKeyVaultStoreProvider

### ISSUE THREAD

**Issue by VTR-AReed** [Azure/azure-cosmos-dotnet-v3#3001]
In the example (https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-always-encrypted?tabs=dotnet), the CosmosClient modifier .WithEncryption() should take a reference of AzureKeyVaultKeyStoreProvider, however it is looking for EncryptionKeyWrapProvider. 

I also tried 3.23.0 (instead of preview) which then renders ClientEncryptionIncludedPath as protected. 

The documentation also shows usage of: 
DataEncryptionKeyAlgorithm.AEAD_AES_256_CBC_HMAC_SHA256

Which seems to actually be: 
DataEncryptionKeyAlgorithm.AeadAes256CbcHmacSha256

**Environment summary**
SDK Version: net6
Azure.Identity" Version="1.5.0"
Microsoft.Azure.Cosmos" Version="3.23.0-preview"
Microsoft.Azure.Cosmos.Encryption" Version="1.0.0-previewV19"
Microsoft.Data.Encryption.AzureKeyVaultProvider" Version="0.2.0-pre"

**Comment by VTR-AReed** [comment]
Under closer inspection, it looks like the example uses: 
AzureKeyVaultKeyStoreProvider

When it should be using: 
AzureKeyVaultKeyWrapProvider

**Comment by j82w** [comment]
@kr-santosh  and/or @abhijitpai can you take a look?
