### ISSUE TITLE
Changing the connection mode of a CosmosClient does not change the protocol used

### ISSUE THREAD

**Issue by stingkun7** [Azure/azure-cosmos-dotnet-v3#3012]
**Describe the bug**
Changing the connection mode of a CosmosClient after it has been instanced does not change the protocol used.
It happens with CosmosClient constructors and also with CosmosClientBuilder.

**To Reproduce**
Create an instance of a CosmosClient:

```           
var client = new CosmosClient(endpointUri, primaryKey, new CosmosClientOptions
{
    ConnectionMode = ConnectionMode.Direct
});
```

Change the connection mode to Gateway with the setter of the `ClientOptions`:

```
 client.ClientOptions.ConnectionMode  = ConnectionMode.Gateway;
```

Enable logging on Debug level.
Now, perform a read operation against a container. 
Search in the logs for 'DocDBTrace Information', some information about RNTDB protocol will appear.
            

**Expected behavior**
It is expected that changing the variable `client.ClientOptions.ConnectionMode` changes the protocol used to perform calls against the Cosmos DB.

**Actual behavior**
The protocol of the `CosmosClient` is still Direct as reflected in the logs.

**Environment summary**
SDK Version: 3.24
OS Version: Windows 11

**Comment by ealsur** [comment]
The CosmosClientOptions are only used once (during the client building/creation), afterwards, they do not impact the existing client.

While obviously a great solution would have been to have the properties as read-only, it's not something that can be changed now and considered a breaking change on the API surface.

What is the reason you are dynamically changing the mode?

**Comment by stingkun7** [comment]
Makes sense, I ran into the issue by chance and I don't have any necessity to change the connection mode dynamically.

I will close the issue.

**Comment by L-E-son** [comment]
It would be great to get this documented as a remark on the CosmosClient's ClientOptions property.
