### ISSUE TITLE
support Jwt token (based on authkey) in the client for authentication

### ISSUE THREAD

**Issue by koushikchitta** [Azure/azure-cosmos-dotnet-v3#3020]
**Problem**
I would like to implement a mid-tier service as described below.
https://docs.microsoft.com/en-us/azure/cosmos-db/secure-access-to-data?tabs=using-primary-key#resource-tokens

The mid-tier service would mask the clients from accessing the authkey of the dbaccount, and instead would provide a custom Jwt token(based on the account auth key) to the clients.
The current TokenCredential method is tightly coupled with Azure identity and is not generic enough.

**Describe the solution you'd like**
The client should support an authentication mechanism when it provides a token based on auth key should be authenticated by the data plane.

**Describe alternatives you've considered**
No alternative available as of now.

**Additional context**

**Comment by kirankumarkolli** [comment]
Cosmos ResourceTokens are the equivalent tokens
