### ISSUE TITLE
Cosmos Patch API Set operation not working correctly.

### ISSUE THREAD

**Issue by jgcordel** [Azure/azure-cosmos-dotnet-v3#3023]
When using the Cosmos Patch API (specifically the Set operation) to update items within a document. The operation is not updating correctly when updating a nested item. For example, consider the following document:
{
    "id": "Andersen.1",
    "LastName": "Andersen",
    "Parents": [
        {
            "FamilyName": "Bob",
            "FirstName": "Thomas"
        },
        {
            "FamilyName": null,
            "FirstName": "Mary Kay"
        }
    ]
}

if you were to do a patch update using the Set operation like the following: {"operations":[{ "op" :"set", "path":"/Parents/0/FamilyName","value":"Test" }]}

The update will actually create a new item in the document so that the document now looks like this:
{
    "id": "Andersen.1",
    "LastName": "Andersen",
    "Parents": [
        {
            "FamilyName": "Bob",
            "FirstName": "Thomas"
        },
        {
            "FamilyName": null,
            "FirstName": "Mary Kay"
        }
    ],
   "Parents/0/FamilyName":"Test"
}

a subsequent operation using the identical operation statement as before will yield the correct result and update the Family name in the 0 element in the parents array.  The Patch API is needlessly creating an additional element within the document. it is again important to note that running a subsequent set operation with the same path and value, will update the inside element as it should have the first time.

**Comment by j82w** [comment]
Are you using the .NET SDK or the REST API directly?

**Comment by jgcordel** [comment]
> Are you using the .NET SDK or the REST API directly?

Using the .NET SDK

**Comment by j82w** [comment]
I added this scenario to the test and it is working correctly. Do you see any difference that could explain why it is behaving differently for you?
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3023

**Comment by jgcordel** [comment]
not immediately, no. what version of the SDK are you using. we are currently on 3.23. below are some code snippets, but everything appears correct to me. we create an IReadOnlyList of patch operations:
![image](https://user-images.githubusercontent.com/73083295/153424661-323d66e3-a0da-48d3-bbb6-f36b451d2434.png)
![image](https://user-images.githubusercontent.com/73083295/153424697-4ae190c8-3c51-46b4-979b-c095e44af5aa.png)
 
and here is what that path and value in that list:
![image](https://user-images.githubusercontent.com/73083295/153424802-70baa2fb-0dc7-4522-bdd9-de93e8089e5e.png)

this results in the path being added as an outer element:
{
    "SourceData": [
        {
            "FirstName": "JohnTest",
            "LastName": "name"
        },
        {
            "FirstName": "secondTest",
            "LastName": "name"
        }
    ],
    "CreatedDate": "2021-06-24T14:09:00.3696383Z",
    "ChangeDescription": "another test",
    "ModifiedDateTime": "2022-02-10T14:05:17.7147848+00:00",
    "SourceData/0/LastName": "LastName",
    "_rid": "lskdjflkjlskjd==",
    "_self": "sdfsdflkjsldkfjlskjdf",
    "_etag": "\"lskjdflksjdlfkjslkdfjs\"",
    "_attachments": "attachments/",
    "_ts": 65465465
}


If I run the set operation again, it will update the inner element:
{
    "SourceData": [
        {
            "FirstName": "JohnTest",
            "LastName": "LastName"
        },
        {
            "FirstName": "secondTest",
            "LastName": "name"
        }
    ],
    "CreatedDate": "2021-06-24T14:09:00.3696383Z",
    "ChangeDescription": "another test",
    "ModifiedDateTime": "2022-02-10T14:05:17.7147848+00:00",
    "SourceData/0/LastName": "LastName",
    "_rid": "lskdjflkjlskjd==",
    "_self": "sdfsdflkjsldkfjlskjdf",
    "_etag": "\"lskjdflksjdlfkjslkdfjs\"",
    "_attachments": "attachments/",
    "_ts": 65465465
}

**Comment by j82w** [comment]
Here is a simple console app that also works. Are you putting a JObject as the value?
[v3ConsoleApp_patchTest.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/8041834/v3ConsoleApp_patchTest.zip)

**Comment by jgcordel** [comment]
The issue can be closed... There were firewalls in other portions of the code that were updating the entire document if it saw a record missing. Thank you for confirming.
