### ISSUE TITLE
Multi collection ACID transactions

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-dotnet-v3#3026]
Currently, there is no support for multi collection ACID transactions. In contrast, I believe Mongo DB allows this. There are use cases that require updating multiple collections simultaneously. Providing this functionality will bring better feature parity with Mongo DB. Please note that this request is for SQL API - not for Mongo DB API.

**Comment by j82w** [comment]
This is not specific to the Cosmos DB .NET SDK. Please post the feature request here: https://feedback.azure.com/d365community/forum/3002b3be-0d25-ec11-b6e6-000d3a4f0858
