### ISSUE TITLE
Make CosmosClient mockable

### ISSUE THREAD

**Issue by NateB2** [Azure/azure-cosmos-dotnet-v3#303]
**Is your feature request related to a problem? Please describe.**
Currently, we can't mock the CosmosClient class, which is essential for our unit tests. The previous version provided an IDocumentClient interface which we were able to use.

**Describe the solution you'd like**
Provide an interface for the CosmosClient that we can use to mock the client.

**Describe alternatives you've considered**
We considered wrapping the CosmosClient in another class, but that is too much work and prone to breaking when the CosmosClient is updated.

**Additional context**
An example of how we would like to use this (we're using FakeItEasy) is below:
```
var fakeCosmosClient = A.Fake<ICosmosClient>();
var fakeDatabases = A.Fake<CosmosDatabases>();
A.CallTo(() => fakeCosmosClient.Databases).Returns(fakeDatabases);

var someClass = new SomeClass(fakeCosmosClient);
await someClass.InitDatabaseAsync();

A.CallTo(() => fakeDatabases.CreateDatabaseIfNotExistsAsync(
               "TheDatabaseToCreate", A<int>._, A<CosmosRequestOptions>._, A<CancellationToken>._)).MustHaveHappenedOnceExactly();
```

**Comment by kirankumarkolli** [comment]
@NateB2 CosmosDatabases is an abstract class and is fully mockable. 
In practice most of the application will be centered around CosmosContainter which is an abstract class and fully mockable.

**Comment by NateB2** [comment]
So what you're saying is that instead of passing the CosmosClient object to the classes, I should be passing the CosmosDatabases object, like this?

```
var fakeDatabases = A.Fake<CosmosDatabases>();

var someClass = new SomeClass(fakeDatabases);
await someClass.InitDatabaseAsync();

A.CallTo(() => fakeDatabases.CreateDatabaseIfNotExistsAsync(
               "TheDatabaseToCreate", A<int>._, A<CosmosRequestOptions>._, A<CancellationToken>._)).MustHaveHappenedOnceExactly();
```

And in the actual implementation, it would be something like this?
```
var client = new CosmosClient(endpoint, accountkey);
var someClass = new SomeClass(client.Databases);
await someClass.InitDatabaseAsync();
```

I updated my unit tests and was able to get everything working, but it would be great to have an example or two of unit tests that use this new pattern, either in the readme or as a sample, as it is quite different than the 2.x SDK version, and the 3.0 SDK unit tests I skimmed appeared to use a mock of the internal constructors which are not accessible to us. It would be really helpful, especially to those of us migrating from 2.x.

**Comment by j82w** [comment]
@NateB2 we will work on more samples once we get closer to GA and the contract stop changing. Is there any reason to not pass the CosmosContainer around?

**Comment by NateB2** [comment]
That would be great - thanks!  Overall, the new SDK is definitely easier to use and looks cleaner - can't wait until it reaches GA.

The class I'm writing now is responsible for setting up Cosmos databases and containers. I want to be able to write unit tests against that class to make sure the databases/containers are named and configured appropriately.

**Comment by wbuck** [comment]
@j82w So how to do purpose we register the cosmos container in the DI container?

Currently we're registering a singleton instance of the `CosmosClient` with DI, and then injecting that into services.
