### ISSUE TITLE
Offer base resource/document type to inherit from

### ISSUE THREAD

**Issue by gunnim** [Azure/azure-cosmos-dotnet-v3#3030]
Would be nice to have a base Document/Resource type to inherit from that had id/_ts/ttl configured with JsonPropertyName configured and proper c# style property naming conventions.

It seems from source to have been [offered in the past](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.document?view=azure-dotnet) but currently the type is marked internal ?

I was also unable to find any reasoning or issue in the repository explaining the change

**Comment by gunnim** [comment]
@j82w I'm a bit confused by your answer, as I understood it Cosmos Db uses Newtonsoft Json to serialize and deserialize items read and written?
F.x. to create a model with an id property that respects c# style naming conventions I am forced to use Newtonsoft Json's JsonProperty("id") attribute anyway.

I do agree that it's not a big deal but if i'm correct that we are forced to use Newtonsoft with Cosmos anyway it seemed like an easy thing to offer in the sdk, especially since it used to be in v2.

In any event, it seems this was done with some forethought so feel free to close if you are inclined not re-add this functionality, thanks for the answers.

**Comment by ealsur** [comment]
You are not forced to use Newtonsoft.Json, you can use whatever serialization technology you want (for example System.Text.Json https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson), if we provided a similar construct as `Document` it would not work for anyone using a custom serialization engine.

**Comment by gunnim** [comment]
I see what you mean, you can create a custom serializer and override the defaults. And then including a base Document might unecessarily hinder those who end up extending it.

I see your PoV, thanks for clarifying
