### ISSUE TITLE
FeedIterator : iterator.ReadNextAsync updates the QueryRequestOptions MaxITemsCount

### ISSUE THREAD

**Issue by chaitanya-ga** [Azure/azure-cosmos-dotnet-v3#3031]
**Describe the bug**
We are creating a `FeedIterator<JObject>` from the `container.GetItemQueryIterator<JObject>(queryDefinition, requestOptions: queryRequestOptions)`. We have set MaxItemCount in queryRequestOptions to some value, say 25. Then we use this iterator in a do while  loop to read through the records like `iterator.ReadNextAsync()` until the point our page size (here 25, from queryRequestOptions.MaxItemCount) is reached.

However it is observed that `iterator.ReadNextAsync()` is modifying the queryRequestOptions used to create the iterator, thus causing the problem when we use it to validate the pageSize.

So in the first go, its returning say 15 records (for max size 25, mostly its half of what is asked). and as we are relying on `queryRequestOptions.MaxItemCount`, 15 items are returned back instead of 25.

This was not happening till SDK version 3.20.1, recently we upgraded to SDK 3.23.0 and started observing this issue.  The problem is observed only when ORDER BY clause is present in the query definition. without that it pulls up the desired page size without any issues.

**To Reproduce**
Pasting the small code snippet we are using here below.

            // Here we have already set the query, and query options, queryRequestOptions.MaxItemCount is set to say 25
            var iterator = container.GetItemQueryIterator<JObject>(queryDefinition, continuationToken, queryRequestOptions);

            do
            {
                var response = await iterator.ReadNextAsync().ConfigureAwait(false);
                documents.AddRange(response.AsEnumerable());
                totalRequestCharge += response.RequestCharge;
                continuationToken = response.ContinuationToken;
            }
            while (!string.IsNullOrWhiteSpace(continuationToken) && documents.Count < queryRequestOptions.MaxItemCount);
            // Here on the above line, queryRequestOptions.MaxItemCount gets set to records fetched by the iterator, say 15, instead of 25, and even though we expect condition to check for max size which is 25, it returns only 15 records.
            // We have tweaked the code now, to solve our problem, however iterator modifying the passed parameters value is an undesired behavior which was not the case till SDK version 3.20.1
            var pagedDocuments = documents.Take(queryRequestOptions.MaxItemCount.Value);

**Expected behavior**
`'FeedIterator<T>` should not modify the `QueryRequestOptions.MaxItemCount` even though it returns the max items or less number of items.

**Actual behavior**
`'FeedIterator<T>` modifies the `QueryRequestOptions.MaxItemCount` when `iterator.ReadNextAsync()` is called to the actual number of records read by the iterator clearing out the actual max item count held by the property.

**Environment summary**
SDK Version: 3.23.0
OS Version: Windows

**Additional context**

1. Until the point we were using SDK 3.20.1, this issue was not observed. Its probably introduced after it.
2. The query we are using is a cross partition query.
3. This happens only to the queries using order by clause. if we drop the clause, we get desired number of records. (This is not validated if records are returned in one go and hence problem is not there or MaxItemCount is not updated)

**Comment by neildsh** [comment]
This is a valid issue. Unfortunately, this is a day zero design issue. Changing FeedOptions to be immutable is a breaking change, and multiple internal teams are unfortunately relying on this mutability
