### ISSUE TITLE
Example in documentation for ReadManyItemsStreamAsync is not working

### ISSUE THREAD

**Issue by SaurabhSharma-MSFT** [Azure/azure-cosmos-dotnet-v3#3033]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Non working example in documentation for ReadManyItemsStreamAsync in CosmosDB C# SDK 

**To Reproduce**
N/A

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by SaurabhSharma-MSFT** [comment]
Submitted a PR to update the example

**Comment by ealsur** [comment]
The PR seems to relate to error handling only, is the example not working at all or simply not showing how to handle an error response?

**Comment by ealsur** [comment]
Nevermind, after looking at the PR is obvious that would not compile :)
