### ISSUE TITLE
CosmosClient doesn't have ReadPartitionKeyRangeFeedAsync method shared

### ISSUE THREAD

**Issue by rmaziarka** [Azure/azure-cosmos-dotnet-v3#3036]
**Describe the bug**
In azure-cosmos-dotnet-v2 _DocumentClient_ was available to use ReadPartitionKeyRangeFeedAsync method.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.readpartitionkeyrangefeedasync?view=azure-dotnet

In azure-cosmos-dotnet-v3 _DocumentClient_ is an internal class and it is not possible to use it in normal code. And _CosmosClient_ doesn't have this method available.

**Expected behavior**
Run _ReadPartitionKeyRangeFeedAsync_ in azure-cosmos-dotnet-v3.

**Actual behavior**
No possibility to run _ReadPartitionKeyRangeFeedAsync_ method.

**Comment by j82w** [comment]
Hi @rmaziarka,
 
Can you explain the scenario why you need the PartitionKeyRangFeedAsync? 

In v3 SDK it is not being directly exposed. A lot of issues occurred with customers not properly understanding the concept and how it worked with splits. In v3 SDK a new concept was introduced called FeedRanges. 

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a6b06e345f14db6f7079bea1c997372fbda2ed81/Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs#L1249
