### ISSUE TITLE
Service unavailable message should change based on cause

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#3051]
All 503s have the same message. In the latest SDK there is a unique sub status code. The error message should change to match the  substatus code to give a clear hint on the root cause. 

For example if the SDK is not able to reach quorum it should add text saying quorum could not be met or could not connect to multiple endpoints or some other scenario.

**Comment by imanvt** [comment]
Closed via Internal PR

**Comment by imanvt** [comment]
reopening until direct package version gets updated
