### ISSUE TITLE
PartitionKey extraction uses wrong PartitionKey to match json elements

### ISSUE THREAD

**Issue by Kek5chen** [Azure/azure-cosmos-dotnet-v3#3056]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When providing a PartitionKey in any kind of way, a "/" in the beginning followed by the name of the Key containing two uppercase letters like the key "/TestPartition" will result in the Program trying to find a Json Element with the exact name being "/TestPartition" including the slash. This resulting in the inability to define a PartitionKey in the first layer not containing a leading "/".
This for some reason does not always work, though exactly reproducing the steps below yield an unexpected result and should therefore suffice for analysis.

I tried this directly in the emulator. But creating the container in the emulator and then writing to it using the Cosmos SDK also yields the same results.

**To Reproduce**

1. Create a Container in an Azure Cosmos Database (I used the newest version of the Azure Cosmos DB Emulator) called "test"
2. For the containers PartitionKey type "/TestKey"
3. Try to insert a test document like the following:
    { "TestKey":"test" }
4. Observe the Error which is being thrown:
![image](https://user-images.githubusercontent.com/52585984/156178696-54e6d6c6-38f4-493e-bef4-80de599939ad.png)
5. Next, try to insert the following test document:
    { "/TestKey":"test" }
6. Observe as it successfully gets written, but does not show any data in the PartitionKey column regarding the document.

**Expected behavior**
The test document from step 3 should successfully get written into the container.

**Actual behavior**
It throws an error and does not write the document into the container.

**Environment summary**
Binary Version: azure-cosmosdb-emulator-2.14.5-ff900d04.msi
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Comment by Kek5chen** [comment]
Further investigations have resulted in the bug also appearing when having the word in lower case but overshooting some word length.

**Comment by Kek5chen** [comment]
I correct myself, i do not know what is causing this. It seems to happen most of the times, and sometimes just not at all.

**Comment by ealsur** [comment]
Can you share code snippets of the operations? 

If you are creating a container (CreateContainerAsync) then you need to provide the Partition Key Definition (for example: `/TestKey`). If you are performing item operations (CreateItemAsync) then you need to provide the Partition Key Value, in your example, you'd need to be passing `new PartitionKey("test")`.

**Comment by Kek5chen** [comment]
![image](https://user-images.githubusercontent.com/52585984/157183335-0652e016-cfa6-4ae7-b298-9b10df02323e.png)
When pressing on the save button the database program returns:
![image](https://user-images.githubusercontent.com/52585984/157183381-4044b61d-0e15-44c7-aa0a-7e5b34bd2a1a.png)

**Comment by Kek5chen** [comment]
The same happens in the code. The error is the same as the one being thrown from the emulator.

![image](https://user-images.githubusercontent.com/52585984/157190333-360de996-efb2-423e-9cb7-5a4c4a366163.png)

**Comment by ealsur** [comment]
Are you running both things in the Emulator? Have you tried updating the Emulator to the latest version? Does it happen also with a real service account or just the emulator? This doesn't seem to be an SDK issue, the web ui you show does not use the .NET SDK.

**Comment by Kek5chen** [comment]
I am running everything in the emulator. It is updated to the latest version. I do not know if it works on a real service account as we have not reached that stage in development yet. The C# Code Snippet contains the Partition key being PermissionGroup and then serialized using Newtonsoft.Json. It gives me the same error as trying it over the web. The container has been created by using the exact steps I listed above.

**Comment by Kek5chen** [comment]
Since there were no more response since last month i pulled the repo and fixed the bug myself.

**Comment by ealsur** [comment]
@Kek5chen can you share what exactly was the bug fix and which files were changed?
