### ISSUE TITLE
Get different result by ReadItemAsync and LINQ-Query when there are same keys with difference case

### ISSUE THREAD

**Issue by wumingcp** [Azure/azure-cosmos-dotnet-v3#3061]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Using cosmosDB SDK get different result by ReadItemAsync and LINQ-Query when there are same keys with difference case, like "A", "a"

**To Reproduce**
1. Create document with different case
~~~ json
{
    "id": "q8hlmn4rk8uQPmCZtZg6A2YBp-B9L2w6Up1rxw3H7Tw=",
    "fileId": "Github-190619942.live.MSDN.azure-dev-docs.ux-beta/quickstart-python/quickstart-python.md",
    "version": "2022-01-27T18:09:33.3242375Z",
    "locale": "en-us",
    "sourceId": "Github-190619942#live",
    "status": "Updated",
    "type": "Xliff",
    "metadata": {
        "locale": {},
        "open_to_public_contributors": {},
        "breadcrumb_path": {},
        "uhfHeaderId": {},
        "feedback_system": {},
        "feedback_github_repo": {},
        "recommendations": {},
        "author": {},
        "manager": {},
        "ms.author": {},
        **"ROBOTS": {},**
        "title": {},
        "description": {},
        "ms.topic": {},
        "ms.date": {},
        "ms.service": {},
        **"robots": {},**
        "canonical_url": {},
        "document_id": {},
        "document_version_independent_id": {},
        "updated_at": {},
        "content_git_url": {},
        "original_content_git_url": {},
        "original_content_git_url_template": {},
        "gitcommit": {},
        "site_name": {},
        "depot_name": "MSDN.azure-dev-docs",
        "_path": {},
        "_rel": {},
        "_op_canonicalUrlPrefix": {},
        "loc_commit_id": "dbdeeda5e84b3150abec3fcdff9acc4534d2570f",
        "moniker_group": "",
        "dhs_asset_id": "ux-beta/quickstart-python/quickstart-python",
        "loc_file_path": "articles/ux-beta/quickstart-python/quickstart-python.md",
        "loc_branch": "live",
        "loc_source_repo_url": "https://github.com/MicrosoftDocs/azure-dev-docs-pr"
    }
}
~~~
2. Get document by ReadItemAsync 
~~~ C#
await _fileEntityContainer.ReadItemAsync<FileStorageModel>(documentId, new PartitionKey(fileId));
~~~
Result
![image](https://user-images.githubusercontent.com/11804619/156485910-853a87f1-50e1-4c20-a91c-3dfc30fc30c6.png)

3. Get document by LINQ-Query
~~~ C#
               using var latestVersionIterator = _fileEntityContainer
                    .GetItemLinqQueryable<FileStorageModel>(false, default, new QueryRequestOptions { PartitionKey = new PartitionKey(fileId) })
                    .Where(e => e.FileId == fileId && e.Locale == locale.ToLower())
                    .OrderByDescending(e => e.Version)
                    .Take(1)
                    .ToFeedIterator();

                while (latestVersionIterator.HasMoreResults)
                {
                    return (await latestVersionIterator.ReadNextAsync()).FirstOrDefault();
                }

                return null;
~~~
Result
![image](https://user-images.githubusercontent.com/11804619/156486120-fd7d8d43-ada8-4034-bd11-a890dc2579bc.png)

**Expected behavior**
The LINQ-Query should also return "ROBOTS" and "robots" in metadata

**Actual behavior**
The LINQ-Query should also return "robots" and "robots" in metadata

**Environment summary**
SDK Version: 3.23.0
OS Version: Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
@timsander1 and @neildsh any suggestions?

**Comment by ealsur** [comment]
These are different documents. The document in the first screenshot has RID. The screenshot for ReadItem has:

![image](https://user-images.githubusercontent.com/1633401/156632789-f3fdf3b5-4211-4c4f-868c-258429f8cb35.png)

The screenshot for the query has:

![image](https://user-images.githubusercontent.com/1633401/156632875-a7f3b641-f052-4418-a214-3d98dee3f4f6.png)


The screenshots do not include Id and Partition Key, can you verify the values of Id and Partition Key are the same? Otherwise, the document you are reading with ReadItem is not the same you are finding on the query.

**Comment by wumingcp** [comment]
Thanks for your reply, as I check our cosmosDB, and you are right, there are multiple documents with same fileId and locale, so the LINQ-Query and ReadItemAsync return different documents.

Great thanks to you for help me to figure out the root cause
