### ISSUE TITLE
Blocking call found in async function: microsoft.azure.cosmos.direct!SystemUsageMonitor.RefreshLoopAsync

### ISSUE THREAD

**Issue by chenfeibo** [Azure/azure-cosmos-dotnet-v3#3063]
**Describe the bug**

When analyzing PerfView data, we noticed there was blocking calls in this function: microsoft.azure.cosmos.direct!SystemUsageMonitor.RefreshLoopAsync.

![image](https://user-images.githubusercontent.com/58605949/156638956-0d6e7b0d-b277-43f2-9e66-eb1e702f2910.png)

Here's the source code: (copied from ILSpy reflected one). The function name has Async, however it is a sync function.

```
private void RefreshLoopAsync(CancellationToken cancellationToken)
{
	while (!cancellationToken.IsCancellationRequested)
	{
		if (!watch.IsRunning)
		{
			watch.Start();
		}
		SystemUsageLoad? systemUsageLoad = null;
		foreach (SystemUsageRecorder value in recorders.Values)
		{
			if (value.IsEligibleForRecording(watch))
			{
				if (!systemUsageLoad.HasValue)
				{
					DateTime utcNow = DateTime.UtcNow;
					systemUsageLoad = new SystemUsageLoad(utcNow, ThreadInformation.Get(), systemUtilizationReader.GetSystemWideCpuUsage(), systemUtilizationReader.GetSystemWideMemoryAvailabilty());
				}
				value.RecordUsage(systemUsageLoad.Value, watch);
			}
		}
		**Task.Delay(pollDelayInMilliSeconds).Wait();**
	}
}

```

**To Reproduce**

1. Start test program and then keep reading/writing entitties to CosmosDB
2. Run PerfView with /threadtime parameter to capture a 20-second trace.
3. Look at the thread time stacks.

**Expected behavior**

The above function should be converted to an async one so that it won't block thread pool thread.

**Actual behavior**

Blocking calls found in PerfView.

**Environment summary**

SDK Version: 3.24.1.0
OS Version (e.g. Windows, Linux, MacOSX)
Windows.

**Additional context**

**Comment by sourabh1007** [comment]
It is intentional. It is one of the important Task which collects System Usage(CPU, Thread, Memory) information and We don't want a scenario where this task goes to Wait state, for some reason Thread pool is exhausted and this task never get a chance to run again. That is the reason it is a blocking call.
I would like to understand what is the impact you are seeing in your application due to this?

**Comment by chenfeibo** [comment]
> It is intentional. It is one of the important Task which collects System Usage(CPU, Thread, Memory) information and We don't want a scenario where this task goes to Wait state, for some reason Thread pool is exhausted and this task never get a chance to run again. That is the reason it is a blocking call. I would like to understand what is the impact you are seeing in your application due to this?

Thank you for explaining! That makes sense. There's no impact found due to this. We were just profiling our services to find out all the places where we could make perf improvements.

Btw, could you please share the link to the source code of SystemUsageMonitor? I believe there should be comments for the intentional part. I searched "SystemUsageMonitor" in this repo but found nothing so went to use ILSpy.

**Comment by sourabh1007** [comment]
Sorry, We cannot really share this code. It is internal code.

**Comment by 928PJY** [comment]
@sourabh1007 
In our case, we find this blocking call cause thread pool starvation like below

**Comment by Avenged** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4551
