### ISSUE TITLE
Question: Choosing an instance name (Change Feed)

### ISSUE THREAD

**Issue by mumby0168** [Azure/azure-cosmos-dotnet-v3#3067]
I am looking for some guidance on the best instance name to use with the change feed processor library. If I understand it correctly let's say I have a worker application called `worker-a` that would be my processor name and I might say deploy 3 of these either on an azure app service or maybe in AKS. In order to have these load balances correctly, I would need to set an instance name. 

My question is what's a good name? Does that name need to persist between deployments? Or could this be a new `Guid` between deployments? I feel it would have to remain consistent so a new processor deployment would pick up where the last left off?

I wondered if there was any docs/guidance on this or any common way this is done. I can't seem to find much on the web and on the MS docs page.

Thanks in advance, Billy

**Comment by mumby0168** [comment]
@IEvangelist cc

**Comment by IEvangelist** [comment]
> @IEvangelist cc - wondering if we can add some guidance for our change feed implementation both for the core library and the event sourcing version. https://github.com/IEvangelist/azure-cosmos-dotnet-repository

@mumby0168  In our libraries, yes, let's do it.

**Comment by ealsur** [comment]
Instance Name refers to the name of the Instance/Machine that is running the processor. A unique identifier for the compute resource, either the VM name, or the pod unique id, or the instance id of your app service.

**Comment by ealsur** [comment]
@mumby0168 - could you verify if the proposed text in the linked PR is better?

**Comment by mumby0168** [comment]
Yeah that works better for me thank you.
