### ISSUE TITLE
503/ServiceUnavailable custom messages with links

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#3098]
Currently the error message on 503 in most scenarios is identical. The problem is a 503 can happen for a number of reason. The newer SDK has a special substatus code for the different scenarios. The error message should be updated to include a short url to a TSG page to help customer's understand why and how to mitigate the issue.

// SDK Codes (Client)
TransportGenerated410 = 20001,
TimeoutGenerated410 = 20002,
TransportGenerated503 = 20003,
Client_CPUOverload = 20004,
Client_ThreadStarvation = 20005,

//SDK Codes (Server)
Server_NameCacheIsStaleExceededRetryLimit = 21001,
Server_PartitionKeyRangeGoneExceededRetryLimit = 21002,
Server_CompletingSplitExceededRetryLimit = 21003,
Server_CompletingPartitionMigrationExceededRetryLimit = 21004,
ServerGenerated410 = 21005,
Server_GlobalStrongWriteBarrierNotMet = 21006,
Server_ReadQuorumNotMet = 21007,
ServerGenerated503 = 21008,
Server_NoValidStoreResponse = 21009

**Comment by imanvt** [comment]
Closed via Internal PR

**Comment by imanvt** [comment]
reopening until direct package version gets updated
