### ISSUE TITLE
Reduce Diagnostics.ToString() by excluding traces under 1ms.

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#3099]
The Diagnostics.ToString() can be extremely large at times. To improve the performance and reduce the string size information that is not needed should be removed. Looking at past diagnostics anything that completed in less than 1MS can be ignored since it completed so quickly.

Proposal to make the following changes:
1. Remove any cache call where it responded under 1 MS.
2. Remove any request handler that took under 1 MS. The request handler completed quickly so there is no need to include it in the logs.
3. Client info, system info, and client side request stats will always be logged

**Comment by ealsur** [comment]
One idea could be filter based on Type? For example, set all non I/O related ones as Verbose/Debug and ToString() only log Info (I/O)?

**Comment by ealsur** [comment]
If other consumers of the Trace (ie Compute) want to log everything, they still can

**Comment by j82w** [comment]
The diagnostics would still always collect everything. The ToString() logic would simply do the filtering to remove traces that are to small to have any impact on the latency so they don't help and just create noise.

**Comment by j82w** [comment]
The number of store responses should be limited to the first 10 and last 5. There are scenarios for 404/1002 that can be retried hundreds of times causing the diagnostics to be massive. All the store responses in the middle are not needed because looking at the first and last gives a good enough understanding of the scenario. Limiting the count will reduce the string size without impacting troubleshooting.

**Comment by aavasthy** [comment]
For this issue the only changes that would be made are in the Diagonostics.ToString() logic and no change in actual diagnostics collected.  Client info, system info, and client side request stats will always be logged.

Proposed approaches:
•	Remove any request handler that took under 1 MS. The request handler completed quickly so there is no need to include it in the logs.
Pros: We remove around 287 characters per parent request handler.
Cons: We would be displaying partial information in terms of handler invoked.

•	Number of store responses should be limited. Remove the store responses from the middle. First few and last few can give a good understanding of the scenario. 
Pros: We remove around 7000 characters per store response.
Cons: which ones to keep and how confident are we if they will provide good info for all scenarios?

•	Remove id and start time fields from each child. We are already recording duration of each child and we have start time specified in the Summary.
Pros: We remove around 120 characters per child

**Comment by aavasthy** [comment]
**Further investigation:**

- Java sdk doesn't include information about any request handler but it displays all store responses. **We can take a decision to either remove request handlers or just remove handlers that take less than 1ms. We remove around 287 characters per request handler.**
- The main reason behind increased string length is retries. Each retry adds approximately 7000 characters.
- Small changes that are feasible and wouldn't disrupt any experience:
    1.   Remove cache collection less than 1ms. We remove around 240 characters
    2.  Remove id and start time fields from each child. We are already record duration of each child and have start time specified in the Summary. We remove around 120 characters per child
