### ISSUE TITLE
Using Distinct in Linq Query 

### ISSUE THREAD

**Issue by SaiNageswarS** [Azure/azure-cosmos-dotnet-v3#3103]
**Is your feature request related to a problem? Please describe.**
We use Linq extensively in our project for Sql queries as it is typesafe and object oriented. Going through documentation there doesn't seem to be any translation for distinct in linq to sql query.

**Describe the solution you'd like**
A feature like below would be appreciated:

```
IEnumerable<string> regions = query
                .Where(x => x.Ring == ring)
                .Select(x => x.Region)
                .Distinct()
                .AsEnumerable<string>();
```

should translate to 

```
SELECT distinct c.Region from c where c.Ring='value';
```

**Comment by j82w** [comment]
There is an extension method called ToFeedIterator that will allow you to execute the query.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/07cca6e3bb54e7cffc360355bc75d5d988e6a60d/Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs#L1250

```c#
// LINQ query generation
using (FeedIterator<string> setIterator = container.GetItemLinqQueryable<Book>()
                    .Where(x => x.Ring == ring)
                    .Select(x => x.Region)
                    .Distinct()
                    .ToFeedIterator<string>())
{                   
    //Asynchronous query execution
    while (setIterator.HasMoreResults)
    {
        foreach(var region in await setIterator.ReadNextAsync())
        {
            Console.WriteLine(region ); 
        }
    }
}
```
