### ISSUE TITLE
Socket exception while calling create data base operation.

### ISSUE THREAD

**Issue by ShekharReddyN** [Azure/azure-cosmos-dotnet-v3#3105]
### Discussed in https://github.com/Azure/azure-cosmos-dotnet-v3/discussions/3104

<div type='discussions-op-text'>

<sup>Originally posted by **ShekharReddyN** March 22, 2022</sup>
I am getting the socket exception while calling CreateDatabaseIfNotExistsAsync 

![image](https://user-images.githubusercontent.com/6689368/159446738-76326624-a5cf-4351-9182-7e909f1cf4a4.png)

Using the V3 - 3.26.1 version SDK.

Could you please help me resolve this issue?</div>

**Comment by j82w** [comment]
> Seems to be a DNS resolution issue on your environment - see https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2?redirectedfrom=MSDN#WSANO_DATA
Closing this issue since the question has already been answered in the discussion. Please reopen if there is still an issue.
