### ISSUE TITLE
Empty query results when specifying PartitionKey in QueryRequestOptions

### ISSUE THREAD

**Issue by Djangoum** [Azure/azure-cosmos-dotnet-v3#3116]
**Describe the bug**
When I specify PartitionKey query I get no query results. 

      PartitionKey partitionKeyStruct = new PartitionKey(partitionKey);

      var queryRequestOptions = new QueryRequestOptions
      {
              PartitionKey = partitionKeyStruct,
      };

      FeedIterator<TEntity> feedIterator = container.GetItemQueryIterator<TEntity>(queryDefinition, requestOptions: queryRequestOptions);

I had a filter in the query and tried to remove that filter but both ways query response was empty.

**To Reproduce**
This is my code to run queries. 

     
                
                Container container = GetContainer(containerId);

                QueryDefinition queryDefinition = new QueryDefinition(sql);

                if (queryParameters != null)
                {
                    foreach (var property in queryParameters.GetType().GetProperties())
                    {
                        queryDefinition.WithParameter("@" + property.Name, property.GetValue(queryParameters));
                    }
                }

                PartitionKey partitionKeyStruct = new PartitionKey(partitionKey);

                var queryRequestOptions = new QueryRequestOptions
                {
                    PartitionKey = partitionKeyStruct,
                };

                FeedIterator<TEntity> feedIterator = container.GetItemQueryIterator<TEntity>(queryDefinition, requestOptions: queryRequestOptions);

                List<TEntity> result = new List<TEntity>();

                while (feedIterator.HasMoreResults)
                {
                    var results = await feedIterator.ReadNextAsync(cancellationToken);
                    if (results.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        result.AddRange(results.Resource);
                    }
                }

                return result;

**Expected behavior**
Query returns the same results when partitionKey is specified and when it is specified in query where clause

**Actual behavior**
When I specify partitionKey value in where clause of the query results are properly returned but when I remove this filter and add the PartitionKey in QueryRequestOptions I've got no result.

**Environment summary**
SDK Version: 3.26.1
OS Version Windows X64 and ubuntu x86_64

**Additional context**
Even though the recommended way of doing queries to a single partition is specifing the partitionKey in the where clause in the query but, we have been having some issue with latency since we migrated our application to kubernetes with linux from Azure AppServices with windows.

As I read in some post, as the SystemInterop dependency only works on windows aditional calls are made to the gateways which causes issues as described in the below post where I also red that I could get rid of these aditional calls by providing the partitionKey in the request and that is why I'm trying this. 
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3032#issuecomment-1040235918

Thank you very much hope somebody can provide some insights about the issue.

Best.

**Comment by j82w** [comment]
Most likely the partition key value is not correct. 
1. Does it return the item if you do a ReadItemAsync with the id and PK value?
2. Does it work if you specify PartitionKey.None in the query request options?

**Comment by Djangoum** [comment]
I'm working with methods like that I think the issue is related with the dynamic type on the partitionKey parameter. My partition key for this container is represented in C# as a long like this : 
![image](https://user-images.githubusercontent.com/9842183/160116674-657904c5-4fbe-4ca6-bd97-7654df3d42a8.png)




        public async Task<IEnumerable<TEntity>> GetManyById<TEntity>(IEnumerable<string> ids, string containerId, dynamic partitionKey, CancellationToken cancellationToken = default)
            where TEntity: class
        {
            Container container = GetContainer(containerId);

            var partitionKeys = ids.Select(_ => (_, new PartitionKey(partitionKey))).ToList().AsReadOnly();

            var result = await container.ReadManyItemsAsync<TEntity>(partitionKeys, cancellationToken: cancellationToken);

            return result.Resource;
        }

The above implementation gives me also no results. I've identified that if I try to make queries to containers which partitionKey is a string these methods and the original issue I described does not happen. It only happens to these containers that have long type partitionKey.

But I've got the following method to upsert documents and it does work.

        public async Task UpsertItemAsync<TEntity>(TEntity item, string containerId, dynamic partitionKey, CancellationToken cancellationToken = default) where TEntity : class
        {
            Container container = GetContainer(containerId);
            await container.UpsertItemAsync(item, new PartitionKey(partitionKey), cancellationToken: cancellationToken);
        }

I'm now clueless how to proceed with this issue.

**Comment by j82w** [comment]
I wrote this test and it worked correctly for me. It was able to read the item both ways. Do you see something missing that could explain why it's failing for you?

```c#
        [TestMethod]
        public async Task QueryWithLongPkValue()
        {
            string id = "testLongPk";
            long pkNumber = 1234;
            Cosmos.PartitionKey pkValue = new Cosmos.PartitionKey(pkNumber);
            ItemResponse<dynamic> item = await this.Container.CreateItemAsync<dynamic>(new {id = "testLongPk", pk = pkNumber }, pkValue);
            Assert.IsNotNull(item);

            ItemResponse<JObject> read = await this.Container.ReadItemAsync<JObject>(id, pkValue);
            Assert.IsNotNull(read);

            List<JObject> items = new List<JObject>();
            using FeedIterator<JObject> feedIterator = this.Container.GetItemQueryIterator<JObject>(
                $"select * from T where T.pk = {pkNumber}");
            while (feedIterator.HasMoreResults)
            {
                FeedResponse<JObject> queryResponse = await feedIterator.ReadNextAsync();
                items.AddRange(queryResponse);
            }

            Assert.AreEqual(1, items.Count);
            items.Clear();

            QueryRequestOptions queryRequestOptions = new()
            {
                PartitionKey = pkValue
            };

            using FeedIterator<JObject> feedIterator2 = this.Container.GetItemQueryIterator<JObject>(
                "select * from T",
                requestOptions: queryRequestOptions);
            while (feedIterator2.HasMoreResults)
            {
                FeedResponse<JObject> queryResponse = await feedIterator2.ReadNextAsync();
                items.AddRange(queryResponse);
            }

            Assert.AreEqual(1, items.Count);
        }
```

**Comment by ealsur** [comment]
You said the PartitionKey is represented by 2 fields? Is the PK the `id` or the `clientId`? Or are you creating a third field that has the concatenation?

Could you show a small code that repros the behavior? For example, share a sample document and share the values you are passing to the SDK methods to find that document.

**Comment by rsciriano** [comment]
> I wrote this test and it worked correctly for me. It was able to read the item both ways. Do you see something missing that could explain why it's failing for you? Any chance you can provide a simple console app that reproduce it?
> 
> ```cs
>         [TestMethod]
>         public async Task QueryWithLongPkValue()
>         {
>             string id = "testLongPk";
>             long pkNumber = 1234;
>             Cosmos.PartitionKey pkValue = new Cosmos.PartitionKey(pkNumber);
>             ItemResponse<dynamic> item = await this.Container.CreateItemAsync<dynamic>(new {id = "testLongPk", pk = pkNumber }, pkValue);
>             Assert.IsNotNull(item);
> 
>             ItemResponse<JObject> read = await this.Container.ReadItemAsync<JObject>(id, pkValue);
>             Assert.IsNotNull(read);
> 
>             List<JObject> items = new List<JObject>();
>             using FeedIterator<JObject> feedIterator = this.Container.GetItemQueryIterator<JObject>(
>                 $"select * from T where T.pk = {pkNumber}");
>             while (feedIterator.HasMoreResults)
>             {
>                 FeedResponse<JObject> queryResponse = await feedIterator.ReadNextAsync();
>                 items.AddRange(queryResponse);
>             }
> 
>             Assert.AreEqual(1, items.Count);
>             items.Clear();
> 
>             QueryRequestOptions queryRequestOptions = new()
>             {
>                 PartitionKey = pkValue
>             };
> 
>             using FeedIterator<JObject> feedIterator2 = this.Container.GetItemQueryIterator<JObject>(
>                 "select * from T",
>                 requestOptions: queryRequestOptions);
>             while (feedIterator2.HasMoreResults)
>             {
>                 FeedResponse<JObject> queryResponse = await feedIterator2.ReadNextAsync();
>                 items.AddRange(queryResponse);
>             }
> 
>             Assert.AreEqual(1, items.Count);
>         }
> ```

You can reproduce the error with `pkNumber = 77000500011179641` 

I think the problem could be in the conversion from long type to PartitionKey type (or the internal use that is made of this value)

![image](https://user-images.githubusercontent.com/2356403/160673433-042370c7-7017-49a5-9317-508d66c5438c.png)

**Comment by Djangoum** [comment]
> You said the PartitionKey is represented by 2 fields? Is the PK the `id` or the `clientId`? Or are you creating a third field that has the concatenation?
> 
> Could you show a small code that repros the behavior? For example, share a sample document and share the values you are passing to the SDK methods to find that document.
> 
> And which is the Partition Key Definition (for example, `/myPartitionKeyField`) for the Container.

Hi! No, my partitionKey is only my /clientId field, as @rsciriano commented out there is an example of a partitionKey value of our database and how is passed to the PartitionKey struct.

**Comment by Djangoum** [comment]
Hi all, 

We've been browsing through SDK source code and making many tests and we realised that the conversion from big long values as  @rsciriano pointed out to double is the root cause of the problem. 

We've been using these partitionKey values since 2 years ago and as we had no "Query" statements or "Get" (point operations) with these partitionKey values (everything was retrieved using Query specifing the partitionKey in the where statement of the query) we had no issue. But now switching to linux in k8s with this latency issue related to extra network calls to the gateway to get query plans this is for us a problem. 

In top of all of that we can not understand why everything is converted to double regarding partitionKeys as PartitionKey value lenght as seen documentation is suposed to be limited to 2048 bytes, not 64 bits. 

[PartitonKey Docs](https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-item-limits)

**Comment by AleksuKey** [comment]
Hi @j82w @ealsur, did you have the change to check last @Djangoum and @rsciriano comments? Thanks!

**Comment by j82w** [comment]
Please contact support via: https://aka.ms/azure-support . From what I can tell via testing this limitation seems to be based on a JSON spec as part of the service and not something specific to the .NET SDK.
