### ISSUE TITLE
ReadNextAsync returns null value for first iteration

### ISSUE THREAD

**Issue by lommez** [Azure/azure-cosmos-dotnet-v3#3128]
Hi,

I'm executing a query without using the partition key, but using some properties as a key to bring just one document.

For the first call of the ReadNextAsync, the resource is null.
Is that a bug even querying a specific document that exists?  Or I need to use "while" instead of just checking the iterator property "HasMoreResults" ?

Here is the evidence showing my cenario:

![CosmosDB ReadNextAsync](https://user-images.githubusercontent.com/10900667/161274329-cd79e5e9-9032-44aa-a14b-24f3f7b82825.gif)

**Comment by j82w** [comment]
1. Empty pages are expected. It's explained here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-query-performance#common-sdk-issues
2. It should use while(iterator.HasMoreResults) to full drain the query. https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0aa04564674584ca75d2f287864a3abc3b8b7f3a/Microsoft.Azure.Cosmos.Samples/Usage/Queries/Program.cs#L197
3. If possible specify the partition key in the request option to make it a single partition query else it will be a cross partition query that will have to visit all the partitions in the container.

**Comment by lommez** [comment]
Thanks @j82w !!
