### ISSUE TITLE
Aggregate queries not taking concurrency and working sequentially

### ISSUE THREAD

**Issue by hemantbajpai4** [Azure/azure-cosmos-dotnet-v3#3129]
Hi,

We used v3 sdk to perform aggregate query in an account and it took more than 30 minutes to execute. Account had more than 256 partitions and 11 tb of data. Based on discussion on this icm https://portal.microsofticm.com/imp/v3/incidents/details/297760314/home it seems query was executed sequentially instead of using concurrency provided in the input. Please provide fix of this issue.

Thanks
Hemant

**Comment by j82w** [comment]
@timsander1 and/or @neildsh can you please take a look?

**Comment by neildsh** [comment]
Fixed by [Query: Adds aggressive prefetching for scalar aggregates #3168](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3168)
