### ISSUE TITLE
Resource not found when reading item with PartitionKey.None

### ISSUE THREAD

**Issue by masonyc** [Azure/azure-cosmos-dotnet-v3#3136]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When calling container.ReadItemAsync with PartitionKey.None, cosmos sdk throws item not found with 404 status code. However, I can retrieve the item when providing the correct partition key.

**To Reproduce**
Create a cosmos document with partition key, call container.ReadItemAsync with  PartitionKey.None.

**Expected behavior**
Item should be retrieved from cosmos when PartitionKey.None is provided.

**Actual behavior**
Cosmos sdk throws item not found with 404 status code
![image](https://user-images.githubusercontent.com/18006944/162396343-500c185a-4100-42d5-afda-1aaf8e81951f.png)
![image](https://user-images.githubusercontent.com/18006944/162396646-c4429b77-9821-45a7-a42c-17488c97f6d3.png)

**Environment summary**
SDK Version: 3.26.1
OS Version Windows

**Comment by j82w** [comment]
Specifying the wrong partition key value will cause a not found exception. Cosmos uses the id and partition key value to uniquely identify an item stored in Cosmos. The partition key is used to determine which partition is needs to be routed to and the id tells which item in that partition. The PartitionKey.None is used when the item does not have the partition key defined.
