### ISSUE TITLE
How to compare 2 IndexingPolicy

### ISSUE THREAD

**Issue by WuZiHong** [Azure/azure-cosmos-dotnet-v3#3143]
Hey guys,

I'm using the .net core cosmos DB sdk and have a small question: How to compare 2 cosmos container CompositeIndexes? I saw that the SDK already contains the [CompositeIndexesEqualityComparer ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/3c6d747326c893eb17c31645282e536938c563af/Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs#:~:text=private%20sealed%20class%20CompositeIndexesEqualityComparer%20%3A%20IEqualityComparer%3CCollection%3CCollection%3CCompositePath%3E%3E%3E)to compare if two compositeIndexes are equal,

but I don't know how to invoke it, could you please help to provide some hints? Thanks in advance!

**Comment by ealsur** [comment]
Given that the IndexingPolicy is serializable to JSON, have you tried simply serializing and comparing the strings? Or do you need to identify which indexes are different?

**Comment by WuZiHong** [comment]
> Given that the IndexingPolicy is serializable to JSON, have you tried simply serializing and comparing the strings? Or do you need to identify which indexes are different?


Thank you ealsur, it works. I just need to know if the two CompositeIndexes are equal. 😁
