### ISSUE TITLE
ChangeFeedStartFrom confusion

### ISSUE THREAD

**Issue by festivus** [Azure/azure-cosmos-dotnet-v3#3144]
I'm confused by the change feed. I was hoping to be able to cycle through all the changes to a single document in a container from the beginning of the container, but it seems only the latest change is ever returned. So my question is what is the point of setting the ChangeFeedStartFrom when you only ever get the latest change?

**Comment by bartelink** [comment]
The changefeed presents all the documents/items in the container.
Within a given logical partition, you're guaranteed to see the oldest updates first.
If you see a give document along the journey, but it's updated after you saw it, you'll see it again.
That lets you maintain syncing of the latest state of everything.

The start point defines how far back in history you want to start from.

For instance, if you want to only sync stuff that's been inserted/updated in the last year, you can filter out older stuff using this mechanism.

(There is a Full Fidelity ChangeFeed feature in private beta that can show every update, but that's only within a constrained timespan i.e. 24h)

**Comment by festivus** [comment]
So, for me, when I see this comment "For instance, if you want to only sync stuff that's been inserted/updated in the last year, you can filter out older stuff using this mechanism.", i read that as i will see all updates. Should that really read "inserted/last updated"??

The documentation is confusing to me. I see things that lead me to believe that I can go back through a container item's history, but that is not in fact the case unless I use the change processor push model (from the very beginning) or build a pull model. But again, either has to have been running from the get go in order to get the full history.

**Comment by bartelink** [comment]
>i read that as i will see all updates. Should that really read "inserted/last updated"??

If you obtained it from the changefeed 2s ago, and you update it in reaction to seeing it, you will see it again a second later. 

Another observer may only see only the final state. I was seeking to convey that you are guaranteed to observe the final state.

>The documentation is confusing to me. I see things that lead me to believe that I can go back through a container item's history, but that is not in fact the case 

I'd suggest raising issues on the doc site regarding anything that confuses you. It's definitely counterintuitive - the name does not help convey what it does.

If the doc site doesnt permit PRs or comments, log it here and someone will route the issue to the right person.


There is nothing stashed to be fed to anyone. There's a cursor per physical partition. The CFP happens to maintain those per-partition containers as documents/items in an 'aux' container (which double up as markers as to which instance of a cluster of consumers has leased that partition atm). Not entirely like Kafka in terms of how the offsets are held per physical partition. Where the analogy breaks down is that there are no messages/copies in brokers being routed around - it's just continuous queries running against the container's nodes.

>unless I use the change processor push model (from the very beginning) or build a pull model.

I have no idea what you mean by this but the bottom line is that no matter what way you look at it, there is a single copy of any item/document in the system at any moment in time (ok there are replicas, and you can get a stale version depending on the consistency model, and multi-master model even means there can be multiple modified versions in flight etc).

Push vs Pull does not change any of those facts.

>But again, either has to have been running from the get go in order to get the full history.

So, again, I need to repeat: there is no "full history"

However, you do have the ability to walk all the documents in a consistent way. What I wouldn't give to have such a feature in the thing I'm working on right now ;)

**Comment by bartelink** [comment]
OK but for avoidance of doubt, you can still miss updates. There's a loop polling the start of the thing. Any time an item is updated, it will move 'past your cursor', and you will see it again. But if you do two updates, and you don't move read and process the first one before it jumps ahead of your cursor again, you won't even be aware it had 2 updates. (Note also that you are only guaranteed to 'read your writes' if the consistency model says so, i.e. if you are running a CFP consumer and reading from the Container in the same process (as opposed to using the document copy from the Change Feed) with Session Consistency, you need to be using the same CosmosClient for the Session Token to be correctly synced to _guarantee_  you will see the same thing you just wrote)

**Comment by festivus** [comment]
Excellent explanation, thank you.
