### ISSUE TITLE
Latest release of Microsoft.EntityFrameworkCore.Cosmos 6.0.4 has dependency Microsoft.Azure.Cosmos >= 3.21.0 which is less than minimum recommended version 3.25.0.

### ISSUE THREAD

**Issue by aluty** [Azure/azure-cosmos-dotnet-v3#3149]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Latest release of Microsoft.EntityFrameworkCore.Cosmos 6.0.4 has dependency Microsoft.Azure.Cosmos >= 3.21.0 which is less than minimum recommended version 3.25.0.

**To Reproduce**
Dependency shown under https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos
If referencing from a project,
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="6.0.4" />
CMD> dotnet list package --include-transitive
Transitive package Resolved
Microsoft.Azure.Cosmos 3.21.0

**Expected behavior**
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-recommended-version
The minimum recommended version is [3.25.0](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#3.25.0).

**Actual behavior**
[[NuGet Gallery | Microsoft.EntityFrameworkCore.Cosmos 6.0.4](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos/6.0.4)[](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos/6.0.4)](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos/6.0.4)
Dependencies
net6.0
[Microsoft.Azure.Cosmos](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/) (>= 3.21.0) **<-- Which does not meet minimum recommended version 3.25.0**
[Microsoft.EntityFrameworkCore](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/) (>= 6.0.4)
[Microsoft.Azure.Cosmos](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/) (>= 3.21.0) 

**Environment summary**
SDK Version: net6.0
OS Version Windows

**Additional context**
Workaround by explicitly adding min version reference like
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.26.1" />

**Comment by j82w** [comment]
Hi @aluty,

The Cosmos SDK team does not own that project. It seems like they already migrated to latest Cosmos version: https://github.com/dotnet/efcore/pull/27680. I'm going to transfer it to the correct repository so they can follow up with a release schedule.
