### ISSUE TITLE
Expose connection string constructors for DocumentClient

### ISSUE THREAD

**Issue by atsapura** [Azure/azure-cosmos-dotnet-v3#3151]
`DocumentClient` has multiple public constructors which take various forms of endpoints and auth keys, but none that consumes a connection string. It brings inconsistency in usage with e.g. `CosmosDb(Trigger)` attributes.

This becomes especially painful when you use centralized configuration, e.g. Azure App Configuration, because you can't just have separate values for auth key and endpoint, since you can't use `CosmosDb` attributes. Of course you can parse connection string yourself, but things like this are definitely should be kept inside SDK if possible.

**Comment by j82w** [comment]
CosmosClient does have a public constructor that takes in the connection string. 
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1ee228cf6b38c0288d0592eb72ba632c4b7ccfa7/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L176

**Comment by atsapura** [comment]
The issue is about `DocumentClient`, not `CosmosClient`. Why did you close it?

**Comment by j82w** [comment]
This GitHub repo is for the .NET v3 Cosmos DB SDK. The DocumentClient is the v2 SDK is in the process of being deprecated. The[ v2 SDK github repo is here](https://github.com/Azure/azure-cosmos-dotnet-v2), but only critical bug fixes are being done.  Why are you asking for a feature to be back ported to the older SDK?

**Comment by atsapura** [comment]
There's [DocumentClient](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/DocumentClient.cs) in this repository as well. Can you add the discussed constructor in it?

**Comment by j82w** [comment]
The DocumentClient is left over from the v3 refactoring. You will notice the file is internal. 

Is there any reason you are not migrating the v3 CosmosClient which has the API you want?
