### ISSUE TITLE
Allow creation of Containers without partition keys in the SDK

### ISSUE THREAD

**Issue by johngallardo** [Azure/azure-cosmos-dotnet-v3#3156]
**Is your feature request related to a problem? Please describe.**
My scenario is that I am using the CosmosDB Emulator in a local test environment. I need the Emulator to be configured for Gremlin connectivity. This creates a constraint whereby I cannot create a partitioned container on the "id" key (this is apparently a limitation of Gremlin API CosmosDB). My test scenario *also* requires me to create a change feed lease container. However, if the Lease container is partitioned it *must* be partitioned on "id" column, which I cannot do if the Emulator is configured for Gremlin API.

So... the workaround we presently have in our test collateral is to use the v2 API (DocumentClient) just to create the Lease container. Recently, however this is getting flagged in our internal code auditing gates since the v2 API is considered deprecated. 

**Describe the solution you'd like**
I understand that we want to promote folks to create partitioned containers because they will more easily scale. However, I think we need a fallback mechanism in the v3 SDK which can be opt-in which allows creation of a non-partitioned container. 

**Describe alternatives you've considered**
See above on current workaround, which is undesirable as it leads to having to also link against the v2 SDK.

**Comment by ealsur** [comment]
CFP works with Gremlin containers: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2491
