### ISSUE TITLE
AI Integration: Do not log Request diagnostics for some failure scenarios

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#3164]
This issue is related to this https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3135#discussion_r858698499 comment.

There can be specific list of status code for which we wouldn't want to log diagnostics.
e.g. 
404 with substatuscode 0 and others.

Decide the exhaustive list of status code and substatuscodes?

Why do we want it?
Generating request diagnostics is costly process and storing it in appinsight in additional cost for customer. So proposal is to generate request diagnostics for some specific status codes only.

**Comment by kirankumarkolli** [comment]
The diagnostics are already conditional on enabling listener, sampling and latency threshold, right? 

IMO Latency threshold already acts as one level of guard and might suffice for now. 

/cc: @ealsur, @FabianMeiswinkel thoughts?

**Comment by sourabh1007** [comment]
It is implemented as separate PR.
