### ISSUE TITLE
Question: Can you add/insert/upsert JSON string instead of an object class to Cosmos DB?

### ISSUE THREAD

**Issue by pmatthews05** [Azure/azure-cosmos-dotnet-v3#3174]
**Describe the bug**
Not sure if a bug, or just not understanding, so asking as a question.

Is it possible to add/insert/upsert JSON string instead of an object class?

I'm using Durable Azure Functions V4, but the value to be read in from an API and inserted into Cosmos could be of different types. You cannot use generics in Azure Durable Functions, so my option is to read in as a JSON String to a dynamic variable type, I need to add something to the dynamic object. Then I convert it back to a JSON String, to be put into my Cosmos DB.

When uploading a json string:
```
"{\"AIntValue\":\"68\",\"id\":\"e09d1c6d-d11b-41ff-83ae-1c778b2feef7\",\"AStringValue\":\"A value to save\",\"ResultContentType\":\"AnExampleContentType\",\"ALongValue\":\"1237396038044506331\"}
``` 
I get the error message:
```
Specified argument was out of the range of valid values. (Parameter 'jsonNavigatorNode must be a Object node. Got String instead.')
```

**To Reproduce**
[Link to Gist](https://gist.github.com/pmatthews05/034ca0920e589f57ea6f4b8280bc7220#file-projectjsonstring-cs)

This is a console example of what I'm trying to achieve. I would have a IDictionary of names and values from an API call, I know the AssemblyName of the Class Object Type. This is how I'm able to convert the IDicitionary into a Dynamic of the Type. This allows me to manipulate a value or two. Then I can convert it back to a JSON String.

I already have a emulated Cosmos running with a Database called "ExampleDatabase" and a container called "ExampleContainer". The partition is on the "ResultContentType". 

**Expected behavior**
An understanding how to upload JSON string to CosmosDB, instead of a defined object. Or a workaround to what I'm trying to attempted.

**Actual behavior**
If I was able to use the Class Object it works when inserting into CosmosDb, but it doesn't work with string.
[Link to Gist](https://gist.github.com/pmatthews05/034ca0920e589f57ea6f4b8280bc7220#file-projectobject-cs)

**Environment summary**
SDK Version: Latest
OS Version: Windows
.NET Version: 6.0

*Additional context**
I'm using Newtonsoft.Json, originally tried not using Newtonsoft.Json at all and converted all using System.Text.Json, but that wouldn't even accept the upload as a class object.

**Comment by ealsur** [comment]
If the content you have is coming as a Stream, you can use the Stream APIs directly: https://github.com/ealsur/ondotnet-cosmosdb/tree/master/src/episode1/streams#streams

You could also pass a `dynamic` to the methods or just use `JObject`:

```
var obj = JObject.Parse(jsonString);
await container.CreateItem(obj);
```

In your gist you are creating a new client on each Create call, please avoid that and follow the Singleton pattern recommendations: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/best-practice-dotnet

**Comment by pmatthews05** [comment]
@ealsur Thank you so much!

The JObject.Parse will work for what I'm trying to do. Although I have a API stream to begin with, I don't want to store all the values, and I also needed to add extra values depending on the initial class type.

I understand my "demo example" doesn't follow best practices. It was just a quick way to put the code together in a Gist. In my Azure Function I'm using singletons.

I was originally trying to ensure I was only using System.Text.Json and remove any reference to Newtonsoft.Json in my code, I was unable to get it to work with Cosmos at all. As Cosmos SDK is using Newtonsoft.Json, is there any plan to move over to native System.Text.Json? Do you think I will continue to have issues if I'm only using System.Text.Json in my code and working with Cosmos SDK?

**Comment by pmatthews05** [comment]
I think I've found my own answer on System.Text.Json. I'll test it out next time I'm at work.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs
