### ISSUE TITLE
Version 3.27.0: CosmosLinqExtensions.ToFeedIterator() throw NullReferenceException when query predict has inline static member

### ISSUE THREAD

**Issue by lifeglam** [Azure/azure-cosmos-dotnet-v3#3188]
Version 3.27.0: CosmosLinqExtensions.ToFeedIterator() throw NullReferenceException when query predict has inline static member.

**To Reproduce**
Below code DOES NOT work on 3.27.0 (but works on 3.26.2):
> var queryable = _remoteContainer.GetItemLinqQueryable<T>(true, null, null);
                Expression<Func<T, bool>> predict = (x => x.CreationTime < DateTime.UtcNow);
                var query = queryable.Where(predict);
                var iterator = query.ToFeedIterator();

Below code works on 3.27.0:
> var queryable = _remoteContainer.GetItemLinqQueryable<T>(true, null, null);
                var dateTime = DateTime.UtcNow;
                Expression<Func<T, bool>> predict = (x => x.CreationTime < dateTime);
                var query = queryable.Where(predict);
                var iterator = query.ToFeedIterator();

**Expected behavior**
ToFeedIterator() call successfully

**Actual behavior**
ToFeedIterator() throw NullReferenceException

**Environment summary**
SDK Version: 3.27.0 (3.26.2 works)

**Additional context**
Per release note https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md 
Might caused by Performance: Adds a LINQ optimization for member access in LINQ-to-SQL https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2924

**Comment by j82w** [comment]
@notheotherben and @khdang can you take a look?

**Comment by j82w** [comment]
@lifeglam can you provide the stack trace of the null ref?

**Comment by notheotherben** [comment]
Was able to reproduce and fix this, you'll find the associated change in #3190 and please let me know if you'd like to see anything else covered there.
