### ISSUE TITLE
Unknown failing requests 429 to GET /logs

### ISSUE THREAD

**Issue by mcmorry** [Azure/azure-cosmos-dotnet-v3#3193]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Application Insights Failures panel of the App Service shows GET requests to /logs that are failing with error 429
The request appears to be as http://169.254.129.2:50051/logs?durationSeconds=-1

**To Reproduce**
I have a .NET 6 Web API project on Azure App Service that accesses Cosmos DB upon user requests.
After upgrading the package from 3.26.1 to 3.27.0 I started getting failing requests to /Logs every minute.

**Expected behavior**
There should not be failing requests, as it was on version 3.26.1

**Actual behavior**
Failing requests appear every minute in Application Insights.
As soon as I reverted to the previous version these requests stopped failing.
![image](https://user-images.githubusercontent.com/1020257/168423746-136c9cb6-5619-4aaa-b4a2-6aa861926f5a.png)

**Environment summary**
SDK Version: ASP .NET 6
OS Version (e.g. Windows, Linux, MacOSX)
Windows 11

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
Make sure to log the exception message and stack trace. This is necessary to understand most issues. The error message should have a link to this page which explains 429s: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-request-rate-too-large?tabs=resource-specific

Please make sure to follow all the best practices: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/best-practice-dotnet

**Comment by ealsur** [comment]
GET /logs isn't the API endpoint on your application's end? What code gets executed on that action? We need the exception details to confirm it is coming from the Cosmos SDK and exactly what it's going on.

**Comment by mcmorry** [comment]
> GET /logs isn't the API endpoint on your application's end?
Correct. It's not my endpoint.

> What code gets executed on that action? We need the exception details to confirm it is coming from the Cosmos SDK and exactly what it's going on.
None, I have no idea where it comes from. I'm not executing any background code, nor calling any endpoint, and still, the failure was happening regularly every minute.

I don't have a stack trace as it's not my code. Looking again at those errors this is all I can find:
![Request](https://user-images.githubusercontent.com/1020257/170594132-677cf001-cd1a-4289-8b84-7c6e11119745.jpg)
![Warning](https://user-images.githubusercontent.com/1020257/170594138-b1b76f7b-91f9-47b0-9f5a-da4e1e1c0e68.jpg)

What is more confusing is that I cannot reproduce it anymore. I just upgraded again to 3.27.1 and there are no failures.
I tried to manually execute a /logs endpoint and I get a 404, as expected.

**Comment by ealsur** [comment]
There is no code in the SDK that performs a GET on some address that is `/logs`, the route the request goes to is an HTTP (not HTTPS) address:

![image](https://user-images.githubusercontent.com/1633401/171298007-3e227892-99a6-4936-87eb-d588a59c0b16.png)

The IP address in the screenshot does not belong to any Cosmos DB SDK endpoint. It looks like a Private IP.

The Category is "Microsoft.Diagnostics.Monitoring.WebApi.RequestLimitTracker", which is an odd one too.

How do you know these 429 (which is not a Cosmos DB exclusive status code) is coming from Cosmos DB or is related to the SDK?
