### ISSUE TITLE
Diagnostics: Log ApplicationRegion in ClientConfiguration trace

### ISSUE THREAD

**Issue by abhijitpai** [Azure/azure-cosmos-dotnet-v3#3198]
Log ApplicationRegion in ClientConfiguration trace to help debugging. We currently log preferred regions in the diagnostics trace only when ApplicationPreferredRegions is set.

**Comment by j82w** [comment]
The diagnostics log only the preferred region. It should also log application region.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Tracing/TraceData/ConsistencyConfig.cs#L27
