### ISSUE TITLE
EF team feedback on various APIs

### ISSUE THREAD

**Issue by divega** [Azure/azure-cosmos-dotnet-v3#32]
The following improvements were identified while porting the EF Core provider to the [Cosmos SDK version 3.0.0.1-preview](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.0.0.1-preview).

cc @AndriySvyryd @ajcvickers @kirillg 

- [ ] Add a constructor to PartitionKeyDefinition that accepts an IEnumerable<string> of paths
- [ ] Remove the parameterless constructor from CosmosContainerSettings since the id and partition keys are required
- [ ] Add a way to get the query and parameters from CosmosSqlQueryDefinition, this would be useful for logging
- [ ] There doesn’t seem to be an advantage to have CosmosResponse<T>.Resource  be strongly typed, as the generic argument cannot always be inferred and frequently needs to be specified explicitly. Returning it as object makes using the methods like DeleteItemAsync<>() simpler as they won’t need the generic argument.
- [ ] It might be better to rename the CreateItemQuery<>() overloads that don’t take a partition key as they could be invoked unintentionally if the partition key is an int. Or move maxConcurrency to requestOptions
- [ ] Improve documentation for the partitionKey parameter in methods like CreateItemAsync<>(). PartitionKey doesn’t have any documentation. And a PartitionKey instance doesn’t seem to be accepted, consider changing the type to string or separating into overloads
- [ ] Allow to provide a custom IDocumentClientRetryPolicy or provide a built in way of using exponential backoff.
- [ ] (Not really API feedback, but a possible way to improve the codebase) Align directory structure of the code with the namespaces and apply other established C# coding conventions - https://docs.microsoft.com/dotnet/csharp/programming-guide/inside-a-program/coding-conventions

**Comment by j82w** [comment]
1. What's the use case for multiple paths?
2. Currently there are several dependencies that use this, but an issue can be created to track it..
3. This is a good idea.  Need to create an issue to track the feature request
4. The type is required to deserialize the response stream to the object. 
5. I believe  the rename will be the best option. We moved it to a parameter to make sure developers are aware of it, and for it to be easier to set.
6.  There currently is a bug that is preventing most partition key types and that will be fixed in the next release. We can definitely add more documentation to clarify the requirements.
7.  The CosmosConfiguration contains MaxRetryAttemptsOnThrottledRequests  and MaxRetryWaitTimeOnThrottledRequests . Are there additional properties or settings that are needed?
8.  An issue can be created for this.

**Comment by AndriySvyryd** [comment]
>Add a constructor to PartitionKeyDefinition that accepts an IEnumerable of paths

> 1. What's the use case for multiple paths?

The benefit of the constructor is the ability to create `CosmosContainerSettings` in one expression:
```C#
var settings = new CosmosContainerSettings
{
    Id = parameters.ContainerId,
    PartitionKey = new PartitionKeyDefinition("/pk")
};
```
instead of
```C#
var pk = new PartitionKeyDefinition();
pk.Paths.Add("/pk");

var settings = new CosmosContainerSettings
{
    Id = parameters.ContainerId,
    PartitionKey = pk
};
```

>Allow to provide a custom IDocumentClientRetryPolicy or provide a built in way of using exponential backoff.

>The CosmosConfiguration contains MaxRetryAttemptsOnThrottledRequests and MaxRetryWaitTimeOnThrottledRequests . Are there additional properties or settings that are needed?

For bursty highly parallelized workloads a more aggressive delay strategy could be required:

1. Additional delay in the form of `c^n` where `c` is a user-specified value and `n` is the current number of failed retry attempts
1. Additional random delay up to the specified amount

**Comment by AndriySvyryd** [comment]
> There doesn’t seem to be an advantage to have CosmosResponse.Resource be strongly typed, as the generic argument cannot always be inferred and frequently needs to be specified explicitly. Returning it as object makes using the methods like DeleteItemAsync<>() simpler as they won’t need the generic argument.

> 4. The type is required to deserialize the response stream to the object.

In the case of `DeleteItemAsync<T>` `Resource` is always `null`

In cases where it isn't you can make deserialization lazy by changing `Resource` property to a method - `GetResource<T>()`

**Comment by j82w** [comment]
1. There is a constructor overload that takes in the path.  
```
var settings = new CosmosContainerSettings(
                id: "SampleContainer",
                partitionKeyPath: "/pk");
```
4. The reason the typed is not lazy is we wanted avoid having everything implement IDisposable. The original response back from Cosmos contains a Stream that needs to be disposed. If we did a lazy deserialization then all the responses would need to wrapped in using statements in the scenario that the objects are never deserialized. This made basic applications look very complex and was very easy for developers to have memory leaks. If you need additional performance or want to do your own deserialization you can use the stream APIs. 
7. We are planning to design a new retry system based on the handler pipeline that would allow custom retry handlers. We're still in the process of planning so I'm not sure when this will be worked on.

**Comment by AndriySvyryd** [comment]
> 4. The reason the typed is not lazy is we wanted avoid having everything implement IDisposable. The original response back from Cosmos contains a Stream that needs to be disposed. If we did a lazy deserialization then all the responses would need to wrapped in using statements in the scenario that the objects are never deserialized. This made basic applications look very complex and was very easy for developers to have memory leaks. If you need additional performance or want to do your own deserialization you can use the stream APIs.

The stream APIs response needs to be disposed anyway. If you established that all responses need to be disposed it would actually make it less likely for a developer to forget to do it as it would be consistent across all of your API and shown in all samples.

**Comment by ealsur** [comment]
@AndriySvyryd @divega  Re 7:  You can apply your custom retry policy as a Handler, in our samples, there is one that covers using Polly: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/CodeSamples/Handlers/ThrottlingHandler.cs

**Comment by AndriySvyryd** [comment]
@ealsur Thanks, would that replace the built-in retry policy or would it run on top of it?

**Comment by ealsur** [comment]
It would run on top of it. If the custom retry is covering a scenario the built-in retry handler already covers, then the default one will be applied first. V3 uses Retry handlers such as https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Handler/RetryHandler.cs to apply the default retry policy. If no default retry handler exists to cover that case, then your custom handler would be the first responder.

**Comment by AndriySvyryd** [comment]
@ealsur I see, then we would still need a way of running the custom handler before the default one or removing it.

**Comment by ealsur** [comment]
Or expose the default one retry options, that would work too, just in the V2 SDK.

**Comment by kirankumarkolli** [comment]
Please create specific issues for gaps if-any.
