### ISSUE TITLE
Calling `GetItemLinqQueryable` uses default serializer for user-provided values

### ISSUE THREAD

**Issue by BrandonWilliamsCS** [Azure/azure-cosmos-dotnet-v3#3207]
**Describe the bug**
I have provided a custom `CosmosSerializer` to my `CosmosClient` via `CosmosClientOptions`, but it is not used when serializing user-provided values (e.g., `new Entity(idValue)`) while generating a `QueryDefinition` after calling `GetItemLinqQueryable`. Instead, the default/internal serializer is used to serialize those values.

**To Reproduce**
Given `public record Entity(string Id);` and a container instantiated like
```
var container = new CosmosClient("...", new CosmosClientOptions
{
    Serializer = new CustomCosmosSerializer(...),
})
```
, call `container.GetItemLinqQueryable<Entity>().Where(doc => doc == new Entity("1")).ToQueryDefinition()`. The generated query definition contains `QueryText` of `SELECT VALUE root FROM root WHERE (root = {"Id": "1"})` and has no parameters.

**Expected behavior**
The `CustomCosmosSerializer` should be used to serialize the `Entity` instance (`new Entity("1")`) provided.

**Actual behavior**
The internal/default serializer is used to serialize the `Entity` instance instead. 

**Environment summary**
SDK Version: 3.27.0
OS Version (e.g. Windows, Linux, MacOSX) Windows 10

**Additional context**
I've done a little digging in the source and see that `CosmosSerializerCore` is set up to use the custom/user serializer when serializing `SqlQuerySpec` parameters. However, values like `new Entity("1")` are NOT treated as parameters, but instead serialized directly into the query text. For comparison, Entity Framework translates all such user-facing values into parameters - in part to mitigate SQL injection issues. I believe this would be a good approach to take here, as well.

**Comment by BrandonWilliamsCS** [comment]
A strongly related but ultimately distinct issue: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2685
That issue is about how *access to the document being queried* is serialized, whereas this is about how *user-provide values that are independent of the document being queried* are serialized.

One simple request shakes out of both issues, plus some others I've seen lately: **please respect the custom serializer**.

**Comment by neildsh** [comment]
Thanks for raising this issue @BrandonWilliamsCS. This issue is accepted and assigned to a dev to be fixed.

**Comment by onionhammer** [comment]
Note that this does not fix enum-as-string handling in LINQ queries; it will still use the enum value;

i.e.

```C#
enum MyEnum
{
  ValueA = 0
}
```

When querying

```
query.Where(c => c.Item == MyEnum.ValueA)
```

will translate to

```
WHERE root["item"] = 0
-- Should be WHERE root["item"] == "ValueA", if JsonStringEnumConverter is configured on JSON Serializer settings
```

**Comment by Maya-Painter** [comment]
Hi all, we've merged what we hope will be a solution to this issue by allowing the custom serializer to be used for LINQ translations. This also unblocks having System.Text.Json attributes applied in LINQ queries.

We plan to release this as part of the next preview package, but I also wanted to take this time to confirm these changes meet your needs before finalizing them as part of our public API.  If you try the changes out, please follow up in the thread if this update addresses your concerns. If it doesn't, please let us know why.

To use your own custom serializer for LINQ translations you must implement `CosmosLinqSerializer` and set it as a custom serializer on the `CosmosClient`. There is a sample of this for serialization with System.Text.Json in CosmosLinqSerializer.cs.
