### ISSUE TITLE
Query definition breaks when the query values are captured from "static readonly" strings, but works constants, general strings etc.

### ISSUE THREAD

**Issue by vidhyasagarreddy** [Azure/azure-cosmos-dotnet-v3#3208]
```
class UserTypeConstants
{
   public static string Admin = "Admin";
}

...Container.GetItemLinqQueryable<T>().Where(m => m.userType == **UserTypeConstants.Admin**);
```

**Comment by ealsur** [comment]
Can you share how it breaks? What is the exception?

**Comment by j82w** [comment]
It's likely related to this issue which has been fixed but not released yet: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3188

**Comment by j82w** [comment]
Please upgrade to 3.27.1 https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.27.1
