### ISSUE TITLE
Client Telemetry: Allow proxy 

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#3229]
ref https://github.com/Azure/azure-sdk-for-java/pull/29022

**Comment by j82w** [comment]
This should already be supported because .NET uses a single http client. If the user defines one for the client then client telemetry will also use it.

**Comment by sourabh1007** [comment]
I didn't really look into it. If you are sure, then we can close this issue. I created it for tracking purpose.
