### ISSUE TITLE
Diagnostics: CPU info is NaN on Mac

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#3235]
According to https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3191, on MacOS with Apple chip, the CPU measurements are NaN but are incorrectly printed and breaking the JSON.

Reference file: https://msdata.visualstudio.com/_git/CosmosDB?path=/Product/Microsoft.Azure.Documents/SharedFiles/Rntbd2/SystemUsageLoad.cs&version=GBmaster&line=36&lineEnd=37&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

We should check with `float.IsNaN` on the condition before writing the value.

**Comment by imanvt** [comment]
Closed via Internal PR

**Comment by imanvt** [comment]
reopening until direct package version gets updated
