### ISSUE TITLE
Long calls to GET /metadata/instance timing out

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cosmos-dotnet-v3#3245]
![image](https://user-images.githubusercontent.com/969938/171663748-49d526e2-f117-40a8-bc32-321d05f0f4bb.png)

I'm seeing long calls to GET /metadata/instance timing out in the cosmos SDK, and wondering if thats why it takes basically forever for my apps to start when running locally. What's the deal with this?

**Describe the bug**
App has always been taking a long time to start (mainly cosmos client SDK initialization time). 

**To Reproduce**
- Using RBAC login, not key-based login with a DefaultAzureCredential

**Expected behavior**
SDK should start up quickly and not throw HTTP timeout errors after 21 seconds

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version: 3.27.1.0
OS Version (e.g. Windows, Linux, MacOSX): Windows 10

**Comment by j82w** [comment]
That meta data call should not block the SDK initialization. It should be a background task that is used in the diagnostics. Are you sure it's blocking the SDK from completing operations?

**Comment by ealsur** [comment]
The graphic does not show that the red request is sequential. The below request that runs in parallel is the Microsoft AAD DefaultAzureCredential is what is taking long.

**Comment by onionhammer** [comment]
@j82w you are right, it's not blocking. It showed up in my debug console as a timeout as my app was hanging so I figured  they were related, but the issue was unrelated.
