### ISSUE TITLE
LINQ: PropertyNamingPolicy set to CamelCase generates wrong query

### ISSUE THREAD

**Issue by vmachacek** [Azure/azure-cosmos-dotnet-v3#3258]
**Describe the bug**
given this query `queryable.Where(r => r.Type == "fooBar" && !r.DeletedAt.HasValue || r.DeletedAt == null).Take(1)` when i set `PropertyNamingPolicy` to `CamelCase` 

the query is generated as follows: 
`SELECT TOP 1 VALUE root FROM root WHERE (((root["type"] = "fooBar") AND (NOT root["deletedAt"]["hasValue"])) OR (root["deletedAt"] = null))` 

and without the param specified is a follows 
`SELECT TOP 1 VALUE root FROM root WHERE (((root["Type"] = "fooBar") AND (NOT IS_DEFINED(root["DeletedAt"]))) OR (root["DeletedAt"] = null))` 

please note presence of `hasValue` in the first query..  this will return wrong results, because "hasValue" is a .net construct

also please note, I cannot use `IsDefined()` extension method because that breaks my tests

**To Reproduce**
run this console app https://gist.github.com/vmachacek/dbb170142a9d60c977c9dd317e2f30e0

**Expected behavior**
query to be same as without parameter specified (except casing)

**Environment summary**
SDK Version: 6.0.300
Library version: 3.27.2
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Comment by Maya-Painter** [comment]
@vmachacek Can you please confirm this is still an issue in SDK version 3.38.0?  

When running your query against the newest release I see the proper query generated with and without camelcasing specified 
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/130110800/18baae36-b8fa-41bd-aa6a-03c39e52b5cb)
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/130110800/22197a9e-ffc1-4a29-9935-4f441d97f5ea)

**Comment by Maya-Painter** [comment]
Closing this issue as addressed.  Please open a new issue if this problem repros in the newest SDK version

**Comment by vmachacek** [comment]
I can confirm its fixed
