### ISSUE TITLE
Right way to use the v3 apis.

### ISSUE THREAD

**Issue by Priya91** [Azure/azure-cosmos-dotnet-v3#327]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
This is not a bug, but a question on how to use these new APIs. 

1. CosmosContainerSettings
The CosmosContainerSettings contructor has a overload that take a container id and a partition key string. The json spec for the partition key is an object that has a path array. How do we specify this path to the CosmosContainerSetting constructor? The API does not match the json spec.

2. Response object results for Create*IfNotExistsAsync methods.
For example, lets take the CreateContainerIfNotExistsAsync api on CosmosContainers. If this api fails to create a container due to auth issue, will it throw CosmosException or return a response object with 401 Statuscode? Or more specifically how do I ensure the operation of creating or reading an existing container was successful, as it seems it may not be sufficient to just try catch the method, but also look at the StatusCode on the response object. Is that the correct way to ensure the success of operation?

**Comment by Priya91** [comment]
cc @srivatsn @DavidObando

**Comment by j82w** [comment]
1.  Cosmos DB currently only supports a single partition key path. It was created as an array so it could eventually support multiple paths, but this normally confuses most users. We decided to have the [constructor](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f9ff931005b5cd97689e7cffff0308af2f5b91ba/Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs#L80) take in the partition key path to simplify it for users. This constructor creates the array and places the single partition key path inside it.

2. All typed operations will throw a CosmosClientException if there is a failure. The status code allows the user to determine if the container already existed or it was created. Not found is not considered an exception and is considered a normal response which the resource will be null. The operation should be wrapped in a try catch to handle any exceptions.

**Comment by Priya91** [comment]
@j82w Thanks for the clarification, closing the issue.
