### ISSUE TITLE
CosmosQueryRequestOptions excludes old FeedOptions

### ISSUE THREAD

**Issue by davetheunissen** [Azure/azure-cosmos-dotnet-v3#33]
**Is your feature request related to a problem? Please describe.**
Not sure if this is a regression bug or feature request but the `PopulateQueryMetrics` feed option is not exposed as a member of the `CosmosQueryRequestOptions` class. 

In fact there are a number of feed options which have been left out between the current client and this one. Have these options been left off for a reason or are they configurable else where?

Comparison between `FeedOptions` & `CosmosQueryRequestOptions`

| Property | Status
| ----------- | ----------- 
| ConsistencyLevel | Supported 
| EnableCrossPartitionQuery |  Internally Set (no public access) 
| EnableLowPrecisionOrderBy | Supported
| EnableScanInQuery | Supported
| JsonSerializerSettings | Not Supported
| MaxBufferedItemCount | Supported
| MaxDegreeOfParallelism | Supported (called MaxConcurrency and no longer request option)
| MaxItemCount | Supported (no longer request option)
| PartitionKey | Supported
| PartitionKeyRangeId | Not Supported
| PopulateQueryMetrics | Not Supported
| RequestContinuation | Not Supported
| ResponseContinuationTokenLimitInKb | Supported
| SessionToken | Supported

**Describe the solution you'd like**
Are there any objections to adding `PopulateQueryMetrics` as an option to `CosmosQueryRequestOptions`? I've tested and confirmed that `CosmosQueryResponse<T>` includes the metrics if set. This setting is really useful for performance tuning etc.

**Comment by davetheunissen** [comment]
If there are no objections to adding `PopulateQueryMetrics` I will submit a PR with the change.

**Comment by j82w** [comment]
I don't see an issue with including it for now, but this will likely have some breaking changes when the diagnostics are updated.

**Comment by j82w** [comment]
We are still working on the v3 diagnostics design. I will create a github issue once we have a design. We want query and point operations to have the same story. In v2 they are completely different which doesn't provide the best user experience. 

These properties have been updated.
| Property | Status
| ----------- | ----------- 
| EnableCrossPartitionQuery |  Internally Set (no public access). Automatically set when uses overload with max concurrency.
| JsonSerializerSettings | Supported via CosmosJsonSerializer
| PartitionKeyRangeId | No plans to support. 
| PopulateQueryMetrics | Planned
| RequestContinuation | Renamed to ContinuationToken

**Comment by martinsmith123456** [comment]
Is this something that will be resolved before GA release?

In the meantime I guess a workaround would be using a handler to add the "x-ms-documentdb-populatequerymetrics" header to the request and read the "x-ms-documentdb-query-metrics" from the Response.

**Comment by RobertDougan** [comment]
Hi, is there an ETA on the `PopulateQueryMetrics` property?
