### ISSUE TITLE
Consider accepting string.Empty as a valid continuationToken equivalent to null

### ISSUE THREAD

**Issue by divega** [Azure/azure-cosmos-dotnet-v3#3316]
This is related to https://github.com/Azure/azure-sdk-for-net/issues/29056 which talks about documenting whether to expect the `ContinuationToken` property will contain `string.Empty` or `null` when there are no additional results. I am arguing there that the issue should be extended to document what value to pass to methods that accept the continuation token as an argument in the initial query. An addition to the description of the parameter in XML documentation would go a long way. 

Our team just hit an issue for incorrectly assuming that `string.Empty` was a reasonable default value to pass as a continuation token in the initial query. 

It turns out that methods like [`Container.GetItemLinQueryable<T>`](https://docs.microsoft.com/dotnet/api/microsoft.azure.cosmos.container.getitemlinqqueryable) won't throw at runtime if `string.Empty` is used for `continuationToken` argument, but a subsequent call to a method that creates the iterator, like `ToFeedIterator` will result in a `MalformedContinuationTokenException`.

Given that in .NET type system `string` does not provide enough expressiveness to make a malformed continuation token error out at compile time and that even the exception is delayed until an iterator is created, I want to suggest that you consider relaxing such methods to accept `string.Empty` as a valid continuation token equivalent to `null`. 

I believe this would result in a slight improvement in usability.

**Comment by neildsh** [comment]
Hello @divega the continuation token is an opaque blob. A `null` continuation token on the response signifies that all results have been returned. This is also reflected in the `FeedIterator.HasMoreResults` returning `false`. Any continuation token passed into the API must either be `null` or exactly the same string that was returned by the API earlier. Specifically, you cannot modify said token. The API contract is silent on the contents on the continuation token. As a result you cannot make any assumptions about the semantics of empty string passed as a continuation token.
