### ISSUE TITLE
Name cache retry handler not working

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#332]
**Describe the bug**

**To Reproduce**
NamedCacheRetryHandler calls to refresh the cache, but the retry still fails. This causes a 410 gone to be returned to the user for iterator operations like GetItemStreamIterator

**Expected behavior**
container.DeleteAsync();
//Return 404 resource not found
container.GetItemStreamIterator();

**Actual behavior**
container.DeleteAsync();
//Return 410 gone with sub status code name cache is stale
container.GetItemStreamIterator();

**Comment by ealsur** [comment]
Fixed by https://github.com/Azure/azure-cosmos-dotnet-v3/pull/281
