### ISSUE TITLE
Release Notes for 3.29.0 has duplicate PR link

### ISSUE THREAD

**Issue by crackalak** [Azure/azure-cosmos-dotnet-v3#3340]
The release notes for https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.29.0 and https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.29.0-preview are showing an incorrect PR link that has been duplicated from the line above.

### Current

> https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3309 Serialization: Fixes default JsonSerializerSettings for [GHSA-5crp-9r3c-p9vr](https://github.com/advisories/GHSA-5crp-9r3c-p9vr)

### Expected

> https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3313 Serialization: Fixes default JsonSerializerSettings for [GHSA-5crp-9r3c-p9vr](https://github.com/advisories/GHSA-5crp-9r3c-p9vr)

**Comment by FabianMeiswinkel** [comment]
Fixed
