### ISSUE TITLE
response.Diagnostics.GetClientElapsedTime() ==> TimeStamp null returned

### ISSUE THREAD

**Issue by Xplz3d** [Azure/azure-cosmos-dotnet-v3#3344]
**Describe the bug**
Trying to get the E2E latency when writing on CosmosDB (https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-dot-net-sdk-slow-request?tabs=cpu-new#capture-diagnostics).

**To Reproduce**
```
ItemResponse<Post> response = await container.CreateItemAsync<Post>(postRecord); //write to cosmosDB
var elapsedTimeForOperation = response.Diagnostics.GetClientElapsedTime();
Console.WriteLine("Diags", elapsedTimeForOperation);
```

**Expected behavior**
Getting the ClientElapsedTime in ms

**Actual behavior**
Elapsedtime returned by GetClientElapsedTime() is null as shown below:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/63337188/178660634-04f7312d-f502-4004-b345-e32c739c76fa.png">

**Environment summary**
SDK Version: 6.0.301 [C:\Program Files\dotnet\sdk]
Package Microsoft.Azure.Cosmos --version 3.29.0
OS Version Windows 11

**Additional context**
/

**Comment by ealsur** [comment]
Can you please share the content of response.Diagnostics.ToString()?

**Comment by Xplz3d** [comment]
@ealsur , please find the content of response.Diagnostics.ToString() below:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/63337188/178774740-27fe666e-6a3e-4487-aa0a-cccde75f2987.png">
<img width="387" alt="image" src="https://user-images.githubusercontent.com/63337188/178774866-35f395c6-c988-45fe-a5f0-b34b9f372bce.png">

And the content in string (extracted from debugger):
`{{"Summary":{"DirectCalls":{"(201, 0)":1},"RegionsContacted":1,"GatewayCalls":{"(200, 0)":3,"(304, 0)":1}},"name":"CreateItemAsync","id":"c87062cd-7d48-4731-846f-793ad5b8e091","start time":"03:40:04:948","duration in milliseconds":4292.2427,"data":{"Client Configuration":{"Client Created Time Utc":"2022-07-13T15:40:04.7189963Z","MachineId":"hashedMachineName:38e3e690-d595-ea26-8767-c2aec39f81f3","NumberOfClientsCreated":1,"NumberOfActiveClients":1,"ConnectionMode":"Gateway","User Agent":"cosmos-netstandard-sdk/3.29.0|1|X64|Microsoft Windows 10.0.22000|.NET 6.0.6|S|","ConnectionConfig":{"gw":"(cps:50, urto:10, p:False, httpf: False)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:False, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[], apprgn: East US)","ProcessorCount":0}},"children":[{"name":"ItemSerialize","id":"9410c773-98fb-4e34-b9ae-11f0b90b5435","start time":"03:40:04:983","duration in milliseconds":487.6586},{"name":"Get PkValue From Stream","id":"0e50d32e-b751-486e-a52c-5c5e0933027b","start time":"03:40:05:478","duration in milliseconds":1579.813,"children":[{"name":"Get Collection Cache","id":"b496bad9-09db-48e0-bc9a-1873675fd250","start time":"03:40:05:496","duration in milliseconds":336.6288,"children":[{"name":"Waiting for Initialization of client to complete","id":"d31cf59b-5908-480e-9d04-33780f65e0d9","start time":"03:40:05:500","duration in milliseconds":331.3313}]},{"name":"Read Collection","id":"f6e6e6b1-6d56-4170-b443-2731ec2d62f8","start time":"03:40:05:887","duration in milliseconds":1080.1534,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[],"HttpResponseStats":[{"StartTimeUTC":"2022-07-13T15:40:05.9399099Z","DurationInMs":923.3941,"RequestUri":"https://centralizedcosmos-eastus.documents.azure.com/dbs/blogdb/colls/posts","ResourceType":"Collection","HttpMethod":"GET","ActivityId":"1a6a9662-382f-45c7-be00-311ed43e36c9","StatusCode":"OK"}]}}}]},{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","id":"712100a9-9d68-416c-b282-fd51995c4881","start time":"03:40:07:080","duration in milliseconds":2145.8012,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","id":"bfe640aa-79df-44eb-933a-34a37c990704","start time":"03:40:07:118","duration in milliseconds":2104.823,"data":{"System Info":{"systemHistory":[{"dateUtc":"2022-07-13T15:40:05.4696196Z","cpu":4.616,"memory":2024136.000,"threadInfo":{"isThreadStarving":"no info","availableThreads":32766,"minThreads":16,"maxThreads":32767},"numberOfOpenTcpConnection":0}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","id":"be08d04b-ad55-4f4a-9693-69dd17d55cf3","start time":"03:40:07:121","duration in milliseconds":2100.4162,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","id":"9ba09b60-1e48-4de3-8563-04ae3cc0e4ba","start time":"03:40:07:134","duration in milliseconds":2083.6684,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","id":"c0bcfe55-1e83-4e77-99dd-56dafc3bad43","start time":"03:40:07:138","duration in milliseconds":2078.0783,"children":[{"name":"Microsoft.Azure.Documents.ServerStoreModel Transport Request","id":"402dc378-3ab8-4cd4-94dd-d00253ad99c1","start time":"03:40:07:150","duration in milliseconds":2062.7205,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus1-be4.documents.azure.com:14054/apps/14daa8b0-3a5e-4a4a-84bd-3f7978f4555c/services/c5fdd623-0cb3-4f84-96df-a6318a487aa0/partitions/f45e4e6e-ddf6-45d9-86d7-5eeead00c840/replicas/133020036646570230p/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus1-be4.documents.azure.com:14058/apps/14daa8b0-3a5e-4a4a-84bd-3f7978f4555c/services/c5fdd623-0cb3-4f84-96df-a6318a487aa0/partitions/f45e4e6e-ddf6-45d9-86d7-5eeead00c840/replicas/133020036702040224s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus1-be4.documents.azure.com:14068/apps/14daa8b0-3a5e-4a4a-84bd-3f7978f4555c/services/c5fdd623-0cb3-4f84-96df-a6318a487aa0/partitions/f45e4e6e-ddf6-45d9-86d7-5eeead00c840/replicas/133020036702040225s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus1-be4.documents.azure.com:14377/apps/14daa8b0-3a5e-4a4a-84bd-3f7978f4555c/services/c5fdd623-0cb3-4f84-96df-a6318a487aa0/partitions/f45e4e6e-ddf6-45d9-86d7-5eeead00c840/replicas/133020036702040226s/"}],"RegionsContacted":["https://centralizedcosmos-eastus.documents.azure.com/"],"FailedReplicas":[],"AddressResolutionStatistics":[{"StartTimeUTC":"2022-07-13T15:40:07.7813376Z","EndTimeUTC":"2022-07-13T15:40:07.9229549Z","TargetEndpoint":"https://centralizedcosmos-eastus.documents.azure.com//addresses/?$resolveFor=dbs%2fCw5pAA%3d%3d%2fcolls%2fCw5pAOVHJQQ%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=0"}],"StoreResponseStatistics":[{"ResponseTimeUTC":"2022-07-13T15:40:09.1337364Z","ResourceType":"Document","OperationType":"Create","LocationEndpoint":"https://centralizedcosmos-eastus.documents.azure.com/","StoreResult":{"ActivityId":"2550a43f-bfd2-483c-9a87-36c95243412e","StatusCode":"Created","SubStatusCode":"Unknown","LSN":38,"PartitionKeyRangeId":"0","GlobalCommittedLSN":37,"ItemLSN":-1,"UsingLocalLSN":false,"QuorumAckedLSN":37,"SessionToken":"-1#38","CurrentWriteQuorum":3,"CurrentReplicaSetSize":4,"NumberOfReadRegions":0,"IsValid":true,"StorePhysicalAddress":"rntbd://cdb-ms-prod-eastus1-be4.documents.azure.com:14054/apps/14daa8b0-3a5e-4a4a-84bd-3f7978f4555c/services/c5fdd623-0cb3-4f84-96df-a6318a487aa0/partitions/f45e4e6e-ddf6-45d9-86d7-5eeead00c840/replicas/133020036646570230p/","RequestCharge":7.05,"RetryAfterInMs":null,"BELatencyInMs":"2.985","transportRequestTimeline":{"requestTimeline":[{"event": "Created", "startTimeUtc": "2022-07-13T15:40:08.0302814Z", "durationInMs": 15.4002},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2022-07-13T15:40:08.0456816Z", "durationInMs": 785.5064},{"event": "Pipelined", "startTimeUtc": "2022-07-13T15:40:08.8311880Z", "durationInMs": 102.7559},{"event": "Transit Time", "startTimeUtc": "2022-07-13T15:40:08.9339439Z", "durationInMs": 145.1078},{"event": "Received", "startTimeUtc": "2022-07-13T15:40:09.0790517Z", "durationInMs": 16.6935},{"event": "Completed", "startTimeUtc": "2022-07-13T15:40:09.0957452Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":1,"openConnections":1},"connectionStats":{"waitforConnectionInit":"True","callsPendingReceive":0,"lastSendAttempt":"2022-07-13T15:40:08.6654464Z","lastSend":"2022-07-13T15:40:08.6689414Z","lastReceive":"2022-07-13T15:40:08.8004003Z"},"requestSizeInBytes":627,"requestBodySizeInBytes":177,"responseMetadataSizeInBytes":424,"responseBodySizeInBytes":385},"TransportException":null}}],"HttpResponseStats":[{"StartTimeUTC":"2022-07-13T15:40:07.2984998Z","DurationInMs":159.2373,"RequestUri":"https://centralizedcosmos-eastus.documents.azure.com/dbs/Cw5pAA==/colls/Cw5pAOVHJQQ=/pkranges","ResourceType":"PartitionKeyRange","HttpMethod":"GET","ActivityId":"3577aa15-6ec1-446c-8023-6ea385f1c554","StatusCode":"OK"},{"StartTimeUTC":"2022-07-13T15:40:07.5316888Z","DurationInMs":178.3704,"RequestUri":"https://centralizedcosmos-eastus.documents.azure.com/dbs/Cw5pAA==/colls/Cw5pAOVHJQQ=/pkranges","ResourceType":"PartitionKeyRange","HttpMethod":"GET","ActivityId":"72ce3e33-25fb-462e-919d-d40fee450d6f","StatusCode":"NotModified","ReasonPhrase":"Not Modified"},{"StartTimeUTC":"2022-07-13T15:40:07.7840649Z","DurationInMs":134.6704,"RequestUri":"https://centralizedcosmos-eastus.documents.azure.com//addresses/?$resolveFor=dbs%2fCw5pAA%3d%3d%2fcolls%2fCw5pAOVHJQQ%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=0","ResourceType":"Document","HttpMethod":"GET","ActivityId":"2550a43f-bfd2-483c-9a87-36c95243412e","StatusCode":"OK"}]}}}]}]}]}]}]},{"name":"Response Serialization","id":"e4cf4a5a-83cf-4201-b18c-0a24d7c543a0","start time":"03:40:09:231","duration in milliseconds":3.9648}]}}`

**Comment by Xplz3d** [comment]
Dear,

IT seems that it's working now ...don't know what happened, by the way, everythings seems ok.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/63337188/178905110-4e30153c-5e70-4313-b4b2-9a9830f04920.png">

Thanks for your investigation.

Regards,
