### ISSUE TITLE
Possible mistake in System.Text.Json example Serialiser?

### ISSUE THREAD

**Issue by oatsoda** [Azure/azure-cosmos-dotnet-v3#3347]
I think maybe in the `Serialize<T>` [method](
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/ca8d48f88451edd657fa4c91dd96f9a58fb69c6d/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs#L43):

```
this.systemTextJsonSerializer.Serialize(streamPayload, input, typeof(T), default);
```

It should probably be

```
 this.systemTextJsonSerializer.Serialize(streamPayload, input, input.GetType(), default);
```

So that it uses the actual runtime type, rather than the Generic T?  I would think in most cases you want to serialise as the actual type rather than any base type?

**Comment by ealsur** [comment]
That will depend on how the SDK APIs are consumed, sure. If you call for example, `ReadItemAsync<MyType>` then `typeof(T)` and `input.GetType()` should be the same.

If you start doing inheritance or dynamic typing probably want to use `input.GetType()` instead. 

From the performance point of view though, they are not the same: https://stackoverflow.com/questions/353342/performance-of-object-gettype/353435#353435

So probably is a matter of choice and hence this is a sample, not an official piece of code that you should blindly use without understanding what it does, like the rest of the samples, they are meant to demonstrate the use of a feature (in this case Custom Serializer).

**Comment by ealsur** [comment]
Having said that, we can certainly update the sample with a legend stating the alternatives. Probably defaulting to `input.GetType()` would be better, feel free to send a PR with the change for sure.
