### ISSUE TITLE
CosmosException  when using QueryDefinition.WithParameter on ORDER BY

### ISSUE THREAD

**Issue by qsdfplkj** [Azure/azure-cosmos-dotnet-v3#3354]
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: ({"errors":[{"severity":"Error","location":{"start":64,"end":72},"code":"SC1001","message":"Syntax error, incorrect syntax near '@orderBy'."}]});
 ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"errors":[{"severity":"Error","location":{"start":64,"end":72},"code":"SC1001","message":"Syntax error, incorrect syntax near '@orderBy'."}]}
 ---> System.Runtime.InteropServices.COMException (0x800A0B00): 0x800A0B00

Provided you have a cosmosContainer the following causes this error. 

        QueryDefinition queryDefinition = new QueryDefinition("SELECT * FROM c ORDER BY @orderBy @sortDirection" )
            .WithParameter("@orderBy", "id").
            .WithParameter("@sortDirection", "ASC");

            var feedIterator = _cosmosContainer.GetItemQueryIterator<JsonElement>(queryDefinition);

            List<JsonElement> result = new();
            while (feedIterator.HasMoreResults)
            {
                result.AddRange(await feedIterator.ReadNextAsync());
            }

**Comment by ealsur** [comment]
This exception is a query format error: `Syntax error, incorrect syntax near '@orderby'.`

You cannot dynamically modify the ORDER BY statement through parametrized querying, parametrized queries are for values, not column names or order values: https://docs.microsoft.com/azure/cosmos-db/sql/sql-query-parameterized-queries.

```
QueryDefinition queryDefinition = new QueryDefinition("SELECT * FROM c ORDER BY c.id ASC" );
```

If you had `where` clauses you could parametrized the value you are filtering, for example:

```
QueryDefinition queryDefinition = new QueryDefinition("SELECT * FROM c where c.property = @value ORDER BY c.id ASC")
                .WithParameter("@value", "something");
```

**Comment by qsdfplkj** [comment]
Ok am I missing something when I will just use string interpolation:  `QueryDefinition queryDefinition = new QueryDefinition($"SELECT * FROM c ORDER BY {orderBy} {sortDirection}"); `
Or should I prepare a querydefinitions for each (orderby, sortdirection) combination and use one of those? Does it perform better when having seperate predefined querydefinitions when compared to the interpolated approach?

**Comment by ealsur** [comment]
There is no performance difference other than in your application space reducing string allocations
