### ISSUE TITLE
First insert/ read takes a much longer time

### ISSUE THREAD

**Issue by adeliab** [Azure/azure-cosmos-dotnet-v3#3355]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I'm running some tests to compare insert/ read/ update durations in cosmos db. I noticed this weird behavior that the first insert/ read takes much longer time than subsequent inserts/ reads. See image below.
The methods used are: CreateItemAsync and ReadItemAsync.
UpsertItemAsync doesn't have the same problem.

![image](https://user-images.githubusercontent.com/7829826/179953191-0bdcc8f3-7b93-4bd1-b953-1ebd28a11969.png)

**To Reproduce**
Sample code to measure insert:

            _stopwatch.Start();
            Task<ItemResponse<CosmosDbDeviceEntity>> task = _container.CreateItemAsync(entity);
            task.Wait();
            
            _stopwatch.Stop();
            var time = _stopwatch.Elapsed.TotalMilliseconds;
            _writeLatenciesInMs.Add(time);
            LogHelpers.LogIndividualInsert(_nrOfRecords, id, time);
            _stopwatch.Reset();

**Expected behavior**
Duration is more or less stable across iterations

**Actual behavior**
First insert/ read takes a very long time

**Environment summary**
SDK Version: 3.29.0
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Additional context**
- CosmosClient, Database and the Container objects live throughout the duration of the test

**Comment by bartelink** [comment]
Are you using [`CreateAndInitializeAsync`](https://devblogs.microsoft.com/cosmosdb/improve-net-sdk-initialization/) ?

**Comment by ealsur** [comment]
This is by design, please see: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-sdk-connection-modes#routing and https://youtu.be/McZIQhZpvew?t=820

**Comment by ealsur** [comment]
Also, for your own sake, don't block async operations. Don't do this:

```
Task<ItemResponse<CosmosDbDeviceEntity>> task = _container.CreateItemAsync(entity);
task.Wait();
```

Use `await` and make your methods be `async`. Even on a console application, you can make the main method `async`.

Reference: https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait

**Comment by adeliab** [comment]
> Are you using [`CreateAndInitializeAsync`](https://devblogs.microsoft.com/cosmosdb/improve-net-sdk-initialization/) ?

No, i didn't. Good to know, thanks!

**Comment by adeliab** [comment]
> This is by design, please see: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-sdk-connection-modes#routing and https://youtu.be/McZIQhZpvew?t=820

I will have a look, thank you

**Comment by adeliab** [comment]
> Are you using [`CreateAndInitializeAsync`](https://devblogs.microsoft.com/cosmosdb/improve-net-sdk-initialization/) ?

I changed my code to use `CreateAndInitializeAsync` but because I delete the container on application start, I support I need to re-initialize the CosmosClient after the containers are re-created.

So now the code does the following:

1. Initialize CosmosClient with `new CosmosClient(connectionString)`
2. Assign database and container variables
3. Delete containers
4. Create containers
5. Re-initialize CosmosClient with `CreateAndInitializeAsync`
6. Re-assign database and container variables
7. Perform inserts

In the container where I use id as its partition key, the first operation is not an anomaly anymore, but I see spikes of duration in some inserts

![image](https://user-images.githubusercontent.com/7829826/180171972-9076da41-76ef-497b-b50c-10d9d7fa167c.png)

In the container where I use another field as its partition key (this field contains substring of the id), the duration seems to be more stable

![image](https://user-images.githubusercontent.com/7829826/180172132-76471c87-ae8b-4c09-a3d5-6849debf941e.png)

The id is a string like AB201900000001, AB201900000002, AB202000000001etc. The 1st container has id as its partition key, the 2nd has the first 6 chars of the id as partition key, for ex AB2019

Are these spikes expected? I've also changed the code to use await instead of Task.Wait

**Comment by bartelink** [comment]
I would say cold start behavior on any freshly created Container is not something to depend on for tonnes of reasons
In fact, I'd be concerned if anyone on the server side spent the slightest bit of time even thinking about optimizing that.
In line with general benchmarking approaches, I'd be throwing away a warmup pass before even looking at any results (Note that I'm not saying that you can/should disregard suboptimal first request cost in general - i.e. InitializeAsync should exist. However even with an API like that, the nature of a JITTed platform is such that you can never achieve 100% warmup unless you actually send a true tracer bullet request through first https://andrewlock.net/reducing-latency-by-pre-building-singletons-in-asp-net-core/).

**Comment by adeliab** [comment]
Understandable with the cold start. But these spikes that now happen in the middle of operations are not cold start anymore I suppose? Just trying to understand the cause

**Comment by bartelink** [comment]
>in the middle of operations

Just saying that the system behavior for the first inserts in a fresh container may not be something that's reliably consistent

So I'd suggest in general eliminating this possible source of variance before attempting to identify such variance

In other words, make the container, add some items, wait minutes to attempt to flush out one-off server-side effects

Just because you observe variance does not mean it's always present; and it's generally explainable if you bolster your experiment enough.

Aside, but not entirely irrelevant: a little known but fantastic book that I'm reading which is teaching me many new things despite having spent plenty time measuring and thinking about this sort of thing - its no trivial beginner book but I can't imagine it not teaching anyone tonnes of stuff, (inc even you, ealsur!) https://www.amazon.com/Understanding-Software-Addison-Wesley-Professional-Computing/dp/0137589735

**Comment by ealsur** [comment]
@adeliab Latency analysis is always on P99/hour (for example, 200K requests in an hour), running an application with 20 requests is not really a representation of P99.

Then you have a lot of other variables:

* Where are you running this code? Is this a production machine? Is the application built as release?
* Are there any issues with your test code? The initial example showed you were blocking threads.
* Is your application deployed in the same Azure region as your Cosmos DB account or are you running from your local machine at your house? Getting perf numbers off a local box really is not an insight that is useful in any way, the network hops involved could be pretty big.

I'd recommend reading https://docs.microsoft.com/azure/cosmos-db/sql/troubleshoot-dot-net-sdk-slow-request for more pointers and if you are interested in the service SLAs: https://azure.microsoft.com/en-us/support/legal/sla/cosmos-db/v1_4/ (look for Latency SLA and the definition of "Application".

@bartelink Thanks for the book pointer, I'll save it for a read!
