### ISSUE TITLE
Exposing QueryMetrics

### ISSUE THREAD

**Issue by emzatos** [Azure/azure-cosmos-dotnet-v3#3357]
**Is your feature request related to a problem? Please describe.**
In SDK V2, the query response contained the actual QueryMetrics object which allowed us to aggregate the metrics of multiple calls for more relevant logging, especially on things like paged queries. Now, the only way to get QueryMetrics information is through the ToString() method of CosmosDiagnostics. This unfortunately removes the consumer's ability to aggregate metrics as they see fit.

**Describe the solution you'd like**
Changing the QueryMetrics object to public would allow us to actually have full control over the metrics, instead of piecing them together manually from the serialized string.

**Describe alternatives you've considered**
If the QueryMetrics class itself cannot be made public, then perhaps exposing a new Metrics object that can still be similarly aggregated (i.e., + operator is overloaded) and has all the fields that were available in V2 could work.

**Comment by neildsh** [comment]
This request has been accepted and a dev is assigned.

**Comment by davidtimovski** [comment]
Is there any news on this one? We also relied on the `IReadOnlyDictionary<string, QueryMetrics> QueryMetrics` property for per-partition telemetry.

**Comment by stowen-msft** [comment]
Hi!  It's six months later and I would really love if nextResult.Diagnostics had a `GetQueryMetrics()` method to get to this info.  I could import the types directly into my own project but it would be really nice to have.
