### ISSUE TITLE
ArgumentException in DiagnosticsHandler with external retry mechanism

### ISSUE THREAD

**Issue by jcoqueret** [Azure/azure-cosmos-dotnet-v3#3358]
**Describe the bug**
I use Polly as a retry mechanism and use the CircuitBreaker to wrap call to CosmosDb.
When a request is retried, I got an ArgumentException in the DiagnosticsHandler. It try to add again a "System Info" key in the request's trace.

**Expected behavior**
Do not throw exception, replace the item in the dictionary.

**Actual behavior**
Code throw an ArgumentException.

**Environment summary**
SDK Version: 3.29.0
OS Version: Linux

**Additional context**
```c#
System.ArgumentException:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Collections.Generic.Dictionary`2.TryInsert (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.Cosmos.Tracing.Trace.AddDatum (Microsoft.Azure.Cosmos.Client, Version=3.28.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler+<SendAsync>d__0.MoveNext (Microsoft.Azure.Cosmos.Client, Version=3.28.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
```

**Comment by ealsur** [comment]
Could you share some way of reproducing the scenario? How are you doing the retry with Polly? Are you using a custom Handler in the pipeline?

**Comment by jcoqueret** [comment]
It will be tricky to extract the code to reproduce right now but I can give you some information.

Yes I use a custom handler to support the retry. It is registered that way :
```c#
builder.AddCustomHandlers(new CustomRetryHandler());
```

And this is what the handler looks like :
```c#
public class CustomRetryHandler: RequestHandler
{
	// This policy exists to stop all attempts across all threads
	private static readonly AsyncCircuitBreakerPolicy<ResponseMessage> TooManyRequestAsyncRetryPolicy = Policy
		.HandleResult<ResponseMessage>(r => r.StatusCode == HttpStatusCode.TooManyRequests)
		.CircuitBreakerAsync(1, TimeSpan.FromSeconds(2));

	// This policy exists to pause attempts rather than fail when the circuit breaker is open
	private static readonly AsyncRetryPolicy<ResponseMessage> WaitAndTestCircuitBreaker = Policy
		.HandleResult<ResponseMessage>(r => r.StatusCode == HttpStatusCode.TooManyRequests)
		.Or<BrokenCircuitException>()
		.WaitAndRetryAsync(new[] {TimeSpan.FromSeconds(3.5), TimeSpan.FromSeconds(3.5)});

	public override async Task<ResponseMessage> SendAsync(RequestMessage request, CancellationToken cancellationToken)
	{
		var response = await WaitAndTestCircuitBreaker.ExecuteAsync(
			() => TooManyRequestAsyncRetryPolicy.ExecuteAsync(
				() => InnerHandler.SendAsync(request, cancellationToken)
			)
		);

		return response;
	}
}
```

I just remark that I call directly the InnerHandler which is the DiagnosticsHandler. Should I call the base instead ?

**Comment by ealsur** [comment]
Based on our examples: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/Handlers/ThrottlingHandler.cs

It should be `base.SendAsync`.

I am not entirely sure why InnerHandler is public 😞

**Comment by jcoqueret** [comment]
Oh, I missed that sample.
Thank you to answer so fast !

**Comment by ealsur** [comment]
Did using `base.SendAsync` fix the error you were seeing?
