### ISSUE TITLE
The addition of ConfigurationManager 6.0 is a breaking change for Azure Function Apps 3

### ISSUE THREAD

**Issue by thed24** [Azure/azure-cosmos-dotnet-v3#3371]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
The dependency on System.Configuration.ConfigurationManager 6.0.0 introduced in the latest version of Azure.Cosmos (3.29.0) conflicts with the pinned version bundled with Azure Function App 3.

**To Reproduce**

1. Create a new Azure Function App on version 3 of the SDK
2. Install Azure.Cosmos 3.29.0
3. Try to use the dependency in any manner, such as initializing a client

**Expected behavior**
The expected behavior is for the exception not to be thrown.

**Actual behavior**
An exception such as the following is thrown when using the library:

```
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 
The system cannot find the file specified.at Microsoft.Azure.Cosmos.DocumentClient.Initialize(Uri serviceEndpoint,ConnectionPolicy connectionPolicy,Nullable`1 desiredConsistencyLevel,HttpMessageHandler handler,ISessionContainer sessionContainer,Nullable`1 enableCpuMonitor,IStoreClientFactory storeClientFactory,TokenCredential tokenCredential)at Microsoft.Azure.Cosmos.DocumentClient..ctor
```

**Environment summary**
SDK Version: 3.29.0
OS Version (e.g. Windows, Linux, MacOSX): MacOSX

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by HNeukermans** [comment]
experienced the same issue

**Comment by ealsur** [comment]
@thed24 Based on https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cin-process%2Cv4&pivots=programming-language-csharp, it looks like the Azure Functions Version 4 is the one recommended for all languages and that contains compatibility with .NET 6 (which is now the LTS). There is a deprecation notice on V3 and below.

**Comment by shibayan** [comment]
This is due to the version 6.0.0 update of `System.Configuration.ConfigurationManager` package from Cosmos DB SDK v3.29 and the assembly optimization process in Azure Functions.

You may need to add `_FunctionsSkipCleanOutput` or `FunctionsPreservedDependencies` to csproj to resolve this.

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
```

or

```xml
  <ItemGroup>
    <FunctionsPreservedDependencies Include="System.Configuration.ConfigurationManager.dll" />
  </ItemGroup>
```

**Comment by ealsur** [comment]
@shibayan I am guessing this is only happening on Functions V3 and not V4?

**Comment by SacredSkull** [comment]
This problem also occurs on Azure Synapse with CSharp notebooks - as there is no csproj to modify this problem does not seem to be solveable without forcibly downgrading to 3.28

**Comment by ealsur** [comment]
@SacredSkull please report the issue to Azure Synapse, the dependencies being loaded and how they handle the .NET runtime is something they might know more about, in this repository we have no visibility of how this package is used there or how they handle dependencies.

**Comment by ealsur** [comment]
Closing due to working on Azure Functions V4. V3 and V2 are deprecated.
