### ISSUE TITLE
Indexer behavior in-consistent between LazyCosmosElement and EagerCosmosElement

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#338]
Indexer behavior in-consistent between LazyCosmosElement and EagerCosmosElement

**To Reproduce**
```C#
  CosmosObject pathTraversal = CosmosObject.Create(jsonNavigator, jsonNavigatorNode);
```
**Expected behavior**
Both Lazy and Eager and supposed to be consistent.

**Actual behavior**
Lazy return null where Eager not.

**Comment by bchong95** [comment]
Good catch! The eager one calls directly into a dictionary. We need to check if the key doesn't exist and return null instead. The same goes for Lazy vs Eager Array.

**Comment by jcocchi** [comment]
@sboshra is this still an issue now that lazy indexing is mostly deprecated? If not, let's close this
