### ISSUE TITLE
Enable ContinuationToken traces in ChangeFeedProcessor

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-cosmos-dotnet-v3#3381]
Recently, there have been few cases customer facing "Change feed token format is invalid" exception caused by continuationToken being in guid format. 

Enable continuationToken traces to help investigation such issues in the future.

**Comment by ealsur** [comment]
@xilian12 there are already traces that show the CT being saved: 

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/b713ce4cb3e482175a8a6a9b8fc7051d9c7b5e91/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionCheckpointerCore.cs#L25
