### ISSUE TITLE
System.ArgumentException for getFeedRangeAsync

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-cosmos-dotnet-v3#3383]
Customer reported that they are getting the following exception for getFeedRangeAsync:
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Azure.Cosmos.Tracing.Trace.AddDatum(String key, TraceDatum traceDatum)
   at Microsoft.Azure.Cosmos.Routing.PartitionKeyRangeCache.<GetRoutingMapForCollectionAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.AsyncCacheNonBlocking`2.AsyncLazyWithRefreshTask`1.<CreateAndWaitForBackgroundRefreshTaskAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.AsyncCacheNonBlocking`2.<GetAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Routing.PartitionKeyRangeCache.<TryLookupAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Routing.PartitionKeyRangeCache.<TryGetOverlappingRangesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ContainerCore.<GetFeedRangesAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__39`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ClientContextCore.<OperationHelperWithRootTraceAsync>d__30`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CDS.NonRelational.Store.Core.CosmosDBClient.<GetFeedRanges>d__28.MoveNext()

The possible reason could be:
The resolution of the DateTime.Now is between 0.5 - 15ms(https://docs.microsoft.com/en-us/dotnet/api/system.datetime.utcnow?view=net-6.0#system-datetime-utcnow), so for scenarios when SDK needs to call gateway for twice in a row, we could get the same value back.

**Comment by ealsur** [comment]
After further investigation, the root cause seems to be on the following scenario: Doing a GetFeedRanges call on a container that has not been interacted with before (first time).

It all starts with https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs#L272-L276, it has a parameter called "forceRefresh" as true.

Looking at https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs#L56-L69, that method calls the TryLookupAsync, which is the one that writes the trace.

When this method is run, it will call TryLookUp, write the trace, return a routingMap value, then goes into the `if (forceRefresh && routingMap != null)`, which is `true` and it will call TryLookupAsync again.

The code inside TryLookUp does: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs#L121-L128

It uses the AsyncNonBlockingCache and calls GetAsync: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/AsyncCacheNonBlocking.cs#L66-L89

This cache was created on the first TryLookup call, so normally, it would not be re-created, BUT there is the forceRefresh parameter:

```
forceRefresh: (currentValue) => PartitionKeyRangeCache.ShouldForceRefresh(previousValue, currentValue));
```

which uses:

```
private static bool ShouldForceRefresh(
	CollectionRoutingMap previousValue,
	CollectionRoutingMap currentValue)
{
	// Previous is null then no need to force a refresh
	// The request didn't access the cache before
	if (previousValue == null)
	{
		return false;
	}

   // currentValue is null then the value just got initialized so
	// is not possible for it to be stale
	if (currentValue == null)
	{
		return false;
	}

   // CollectionRoutingMap uses changefeed to update the cache. The ChangeFeedNextIfNoneMatch
	// is the continuation token for the changefeed operation. If the values do not match
	// then another operation has already refresh the cache since this request was sent. So
	// there is no reason to do another refresh.
	return previousValue.ChangeFeedNextIfNoneMatch == currentValue.ChangeFeedNextIfNoneMatch;
}
```

This would trigger another PKRangeCache request. This is confirmed by capturing the traces for this operation:


```
{
    "Summary": {
        "GatewayCalls": {
            "(200, 0)": 2,
            "(304, 0)": 2
        }
    },
    "name": "GetFeedRangesAsync",
    "id": "861885be-8cf9-4f4f-b5a1-0ca53109cbf6",
    "start time": "04:28:11:849",
    "duration in milliseconds": 132723.7502,
    "data": {
        "Client Configuration": {
            "Client Created Time Utc": "2022-08-29T16:28:00.4105411Z",
            "MachineId": "hashedMachineName:dffcba53-af97-a08f-72b7-73158383ae84",
            "NumberOfClientsCreated": 1,
            "NumberOfActiveClients": 1,
            "ConnectionMode": "Direct",
            "User Agent": "cosmos-netstandard-sdk/3.30.0|1|X64|Microsoft Windows 10.0.19044|.NET 6.0.8|N|",
            "ConnectionConfig": {
                "gw": "(cps:50, urto:10, p:False, httpf: False)",
                "rntbd": "(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)",
                "other": "(ed:False, be:False)"
            },
            "ConsistencyConfig": "(consistency: NotSet, prgns:[], apprgn: )",
            "ProcessorCount": 4
        }
    },
    "children": [
        {
            "name": "Get Partition Key Range Cache",
            "id": "dbbbcbc7-80e6-415d-b941-52ba531a8f4e",
            "start time": "04:28:11:853",
            "duration in milliseconds": 0.0102
        },
        {
            "name": "Get RID",
            "id": "0fa64ff6-49ef-44c5-9586-11cea9b710f4",
            "start time": "04:28:11:855",
            "duration in milliseconds": 486.9035
        },
        {
            "name": "Get Collection Cache",
            "id": "745944e6-5b63-47b1-99df-8142253b39e1",
            "start time": "04:28:11:857",
            "duration in milliseconds": 0.0093
        },
        {
            "name": "Read Collection",
            "id": "a95d7479-dbd9-471c-96e0-f27b62e1ee4c",
            "start time": "04:28:11:889",
            "duration in milliseconds": 440.3393,
            "data": {
                "Client Side Request Stats": {
                    "Id": "AggregatedClientSideRequestStatistics",
                    "ContactedReplicas": [],
                    "RegionsContacted": [],
                    "FailedReplicas": [],
                    "AddressResolutionStatistics": [],
                    "StoreResponseStatistics": [],
                    "HttpResponseStats": [
                        {
                            "StartTimeUTC": "2022-08-29T16:28:11.8907090Z",
                            "DurationInMs": 437.3849,
                            "RequestUri": "https://127.0.0.1:8081/dbs/7129ec67-9c8f-4d54-b0ea-35295345d4df/colls/05fec9f7-9c2b-4850-814b-00b1c60366c0",
                            "ResourceType": "Collection",
                            "HttpMethod": "GET",
                            "ActivityId": "8fbb35f0-e9d9-4ba5-8bf1-92ed1740f3c4",
                            "StatusCode": "OK"
                        }
                    ]
                }
            }
        },
        {
            "name": "Try Get Overlapping Ranges",
            "id": "059bf2a5-9e99-4450-8f72-8c1aa782e471",
            "start time": "04:28:12:351",
            "duration in milliseconds": 665,
            "data": {
                "PKRangeCache Info(2022-08-29T16:28:12.8254936Z)": {
                    "Previous Continuation Token": null,
                    "Continuation Token": "\\"1403\\""
                },
                "PKRangeCache Info(2022-08-29T16:28:13.0115650Z)": {
                    "Previous Continuation Token": "\\"1403\\"",
                    "Continuation Token": "\\"1403\\""
                }
            },
            "children": [
                {
                    "name": "Read PartitionKeyRange Change Feed",
                    "id": "e7724b6c-fc19-4ae8-840f-304a874e57f9",
                    "start time": "04:28:12:367",
                    "duration in milliseconds": 246.6371,
                    "data": {
                        "Client Side Request Stats": {
                            "Id": "AggregatedClientSideRequestStatistics",
                            "ContactedReplicas": [],
                            "RegionsContacted": [],
                            "FailedReplicas": [],
                            "AddressResolutionStatistics": [],
                            "StoreResponseStatistics": [],
                            "HttpResponseStats": [
                                {
                                    "StartTimeUTC": "2022-08-29T16:28:12.3703593Z",
                                    "DurationInMs": 242.7708,
                                    "RequestUri": "https://127.0.0.1:8081/dbs/kjhsAA==/colls/kjhsAKHh-9w=/pkranges",
                                    "ResourceType": "PartitionKeyRange",
                                    "HttpMethod": "GET",
                                    "ActivityId": "f20aabfe-dd06-4493-8797-51fa30a01523",
                                    "StatusCode": "OK"
                                }
                            ]
                        }
                    }
                },
                {
                    "name": "Read PartitionKeyRange Change Feed",
                    "id": "191a7a12-e198-4ccc-b00b-38846e575dbe",
                    "start time": "04:28:12:631",
                    "duration in milliseconds": 175.0648,
                    "data": {
                        "Client Side Request Stats": {
                            "Id": "AggregatedClientSideRequestStatistics",
                            "ContactedReplicas": [],
                            "RegionsContacted": [],
                            "FailedReplicas": [],
                            "AddressResolutionStatistics": [],
                            "StoreResponseStatistics": [],
                            "HttpResponseStats": [
                                {
                                    "StartTimeUTC": "2022-08-29T16:28:12.6313824Z",
                                    "DurationInMs": 174.6925,
                                    "RequestUri": "https://127.0.0.1:8081/dbs/kjhsAA==/colls/kjhsAKHh-9w=/pkranges",
                                    "ResourceType": "PartitionKeyRange",
                                    "HttpMethod": "GET",
                                    "ActivityId": "5184e433-3198-4ee7-8d1d-3448814cbeff",
                                    "StatusCode": "NotModified",
                                    "ReasonPhrase": "Not Modified"
                                }
                            ]
                        }
                    }
                },
                {
                    "name": "Read PartitionKeyRange Change Feed",
                    "id": "4436fe64-d37d-41f2-bb2b-a3bfac408bb2",
                    "start time": "04:28:12:831",
                    "duration in milliseconds": 177.7512,
                    "data": {
                        "Client Side Request Stats": {
                            "Id": "AggregatedClientSideRequestStatistics",
                            "ContactedReplicas": [],
                            "RegionsContacted": [],
                            "FailedReplicas": [],
                            "AddressResolutionStatistics": [],
                            "StoreResponseStatistics": [],
                            "HttpResponseStats": [
                                {
                                    "StartTimeUTC": "2022-08-29T16:28:12.8316827Z",
                                    "DurationInMs": 177.4471,
                                    "RequestUri": "https://127.0.0.1:8081/dbs/kjhsAA==/colls/kjhsAKHh-9w=/pkranges",
                                    "ResourceType": "PartitionKeyRange",
                                    "HttpMethod": "GET",
                                    "ActivityId": "5debd811-f77d-40f4-a0c3-50e423243566",
                                    "StatusCode": "NotModified",
                                    "ReasonPhrase": "Not Modified"
                                }
                            ]
                        }
                    }
                }
            ]
        }
    ]
}
```

We can clearly see 2 `PKRangeCache Info` nodes, if they are within 15ms of each other, this, paired with the precision on `DateTime.UtcNow` could cause the problem.

One way to fix this would be to make the refresh a child:

```
if (forceRefresh && routingMap != null)
{
	using (ITrace childTraceRefresh = trace.StartChild("Refresh", TraceComponent.Routing, Tracing.TraceLevel.Info))
	{
		routingMap = await this.TryLookupAsync(
			collectionRid: collectionRid,
			previousValue: routingMap,
			request: null,
			trace: childTraceRefresh);
	}
}
```
