### ISSUE TITLE
CosmosClient initialization (BuildAndInitializeAsync/CreateAndInitializeAsync) with TokenCredential doesn't respect cancellation token

### ISSUE THREAD

**Issue by benjzh** [Azure/azure-cosmos-dotnet-v3#3392]
The following code (or it's alternative without the builder with CosmosClient/CreateAndInitializeAsync) doesn't respect the cancellation token:
```
return new CosmosClientBuilder(cosmosDbUri, tokenCredential)
                        .WithConnectionModeDirect(enableTcpConnectionEndpointRediscovery: true)
                        .BuildAndInitializeAsync(new[] { (database, container) }, cancellationToken).GetAwaiter().GetResult()
                        .GetDatabase(c.Database)
                        .GetContainer(c.Container);

````

In order to reproduce you can use DefaultAzureCredential locally as it takes some time to find a working credential.

Expected behavior: immediate cancelation
Actual behavior: cancelation after first token is returned or GetTokenAsync threw an exception
SDK Version: 3.29.0
OS Version: Windows (doesn't matter)

I found the bug in the following source file: Microsoft.Azure.Cosmos\src\Authorization\TokenCredentialCache.cs#191, method RefreshCachedTokenWithRetryHelperAsync
```
    this.cachedAccessToken = await this.tokenCredential.GetTokenAsync(
        requestContext: this.tokenRequestContext,
        cancellationToken: default);
```
The cancelation token is not propagated to this call. Only if cancellation was requested just before the call, it will be cancelled.

This bug causes health issues in my Service Fabric service since SF's RunAsync is not able to respond properly. I am creating my own TokenCredential wrapper in order to overcome this issue.

**Comment by ealsur** [comment]
What is the CancellationToken expiration you are using? Also, the principle of CancellationToken is that libraries check its state when it's safe to do so and won't cause an invalid state that is not recoverable, this does not mean that the CT needs to be checked everywhere or passed to every async call.

**Comment by benjzh** [comment]
@***@***.***>, there is no expiration. The cancellation token is coming from Service Fabric when it calls to
StatelessService.RunAsync(CancellationToken cancellationToken), which started the service in the first place and still running. Basically Service Fabric is asking to stop the initialization ASAP and we have about 15sec to do just that. After that the service is marked as unhealthy, and any ongoing deployment would be rolled back. Our service is deployed in all Azure regions so chasing all these failures during each rollout is not feasible. Note that in Service Fabric this timeout is hardcoded.

I agree that if timing for cancellation is chosen wrong - it would harm the internal state. However, don't see how at this point of time (the code that I mentioned) the cancellation could be harmful, while the fix is simple it would solve the problem.
Also, it looks like the usage of BuildAndInitializeAsync/CreateAndInitializeAsync with TokenCredential doesn't seem frequent yet, so have a chance to fix it before it is widely used.

**Comment by ealsur** [comment]
The code you point out is not used only on CreateAndInitialize, it is the TokenCredentialCache, used for all operations. If you look closely, the function it is used on does not receive your CancellationToken:

![image](https://user-images.githubusercontent.com/1633401/185655469-21791030-48bd-4287-a469-d96114e64c86.png)

The reason is this is a Refresh method, used to periodically (on the background) refresh the token. The TokenCredentialCache already checks for cancellation when it's safe to do so (before doing the refresh call):

![image](https://user-images.githubusercontent.com/1633401/185655715-e3ae0d8a-6486-4b0c-b159-ce911680a9d7.png)

That cancellationToken is linked to the client lifetime (because this is a background refresh), so if you dispose the client when you are requested to shutdown, this internal token will cancel.

I am curious as to how you came to the conclusion that this is the code that has the problem when it is not inlined with the CreateAndInitialize.

The CreateAndInitialize method initializes each container concurrently:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1151f55d5356be66526cbe8be9f302879b9a91fe/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L1345-L1363

The CT is then passed down to an initialization logic that just executes a dummy query:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1151f55d5356be66526cbe8be9f302879b9a91fe/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L1401-L1416

The CT is passed all the way down into there, so as long as the CT cancels, the queries will cancel when its safe to do so. 

> asking to stop the initialization ASAP and we have about 15sec to do just that

If you can detect this event, then you could call the client Dispose?

**Comment by benjzh** [comment]
@ealsur, the fact that the call to GetTokenAsync() is the very reason I opened this issue.

I agree that the CancellationToken is mostly respected through the calls however, "mostly" is not enough. 

> I am curious as to how you came to the conclusion that this is the code that has the problem when it is not inlined with the CreateAndInitialize.
I could go into the details, but instead I created a small project that can demonstrate the issue and its root cause: [the link](https://onedrive.live.com/download?cid=7FDE45DC6972FF44&resid=7fde45dc6972ff44%2176099&authkey=AKmSfI9BOeFz7_s). 
I implemented a dummy TokenCredential that becomes stuck until either canceled or finished according to your choice. If you choose to cancel the cancellation token it will be stuck **forever**(!) inside the GetTokenAsync() (you can put a breakpoint on the dummy's implementation of GetTokenAsync() to see how it gets there). Obviously should the cancellation be properly propogate to the  GetTokenAsync() call it would be cancelled gracefully.

> If you can detect this event, then you could call the client Dispose

We have no instance to invoke Dispose() on. There is only a static version of CosmosClient.CreateAndInitializeAsync().

I checked it again; I don't see any problem (only a solution) with passing the cancellation token to GetTokenAsync(). Please note that the only way to cancel it is via disposing of the CosmosClient: you can find a single occurrence of this.cancellationTokenSource.Cancel() call in Dispose() method and only there. So, stopping the background work on disposal makes complete sense to me.

**Comment by ealsur** [comment]
@benjzh We cannot pass the token to `RefreshCachedTokenWithRetryHelperAsync`, there is no link between the token you pass to `CreateAndInitializeAsync` and that piece of code. The place you are referring to is a background refresh, not related to any operation in particular.

I showed the source code pointers that explain what `CreateAndInitializeAsync` is actually doing, which would show any potential place to check the cancellation. There are multiple places where the cancellation is checked, but it cannot be checked on every single line. Within those 15 seconds, the code could be in any other place outside obtaining the Token. Assuming that that single point of code (if changed) would solve your problem completely is not accurate.

>  Obviously should the cancellation be properly propogate to the GetTokenAsync() call it would be cancelled gracefully.

That depends on the implementation of the TokenCredential, what if the TokenCredential implementation you are using (which is not part of this SDK but coming from `Azure.Core`) does not check the token because it is considered not safe? If you have 15 seconds to cancel, even if the token was somehow passed to `GetTokensAsync`, if that implementation is, for example, using HttpClient to issue an HTTP request, there is no guarantee that HttpClient will abort the request when the token cancels either.

All we are discussing is not particular to `CreateAndInitializeAsync` (regarding to your comment about usage). You could not use that API and simply create a normal client and perform operations passing the CancellationToken to the operation (and those CancellationTokens would not be passed to the TokenCredentialCache). AAD token support has been around for more than a year (may 2021) so the usage combination has been available since then (not something recent that is not widely used).

If you have your own custom wrapper of the TokenCredential, then you could take the CancellationToken from the Service Fabric reference and pass it down to the GetTokensAsync (and all other) call, right?

```
internal class ServiceFabricTokenCredential : TokenCredential
{
	private readonly TokenCredential realTokenCredential;
	private readonly CancellationToken serviceFabricCancellationToken;
	
	public ServiceFabricTokenCredential (
		TokenCredential realTokenCredential,
		CancellationToken serviceFabricCancellationToken
	) {
		this.realTokenCredential = realTokenCredential;
		this.serviceFabricCancellationToken = serviceFabricCancellationToken;
	}

	public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
	{
		return this.realTokenCredential(requestContext, serviceFabricCancellationToken);
	}

	public override ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
	{
		return this.realTokenCredential(requestContext, serviceFabricCancellationToken);
	}
}
```

Still that might not guarantee that a token refresh stops at 15 seconds.

**Comment by benjzh** [comment]
@ealsur, I will comment in reversed order. As I mentioned before, I already implemented a workaround similar to yours:
```
        public override ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
        {
            return _original.GetTokenAsync(requestContext, cancellationToken == default ? _additionalToken : cancellationToken);
        }
```
It is already deployed into production into several regions (~4 services in each) and it works well. I am continuing this discussion for the sake of the SDK, my own problem is kind of solved (it could be prettier though 😏and with more confidence).

> Still that might not guarantee that a token refresh stops at 15 seconds.  
   
You will soon see that I agree with this statement.

You are completely right: the token passed to the ```CreateAndInitializeAsync``` is not passed to the ```RefreshCachedTokenWithRetryHelperAsync```. While I knew this, I previously was under the impression that the cancellation will cause the disposal of CosmosClient which will dispose of AuthorizationTokenProvider which in its turn would dispose of the TokenCredentialCache and then ```RefreshCachedTokenWithRetryHelperAsync``` would cancel properly. After looking closely, I found more issues along the way:

1. ```InitializeContainersAsync``` is not async method and it returns a task directly from ```return Task.WhenAll(tasks);```. If it cancels the ```Dispose()``` won't be called, since the execution will be already outside this method. 
2. ```CosmosClient``` doesn't dispose ```AuthorizationTokenProvider```. Note that, the relevant implementation - ```AuthorizationTokenProviderTokenCredential``` - disposes the ```TokenCredentialCache ``` properly.

Therefore, the full fix would be:

- to mark ```InitializeContainersAsync``` as async
- include AuthorizationTokenProvider's disposal to CosmosClient
- propagate the internal cancellation token in the ```RefreshCachedTokenWithRetryHelperAsync``` method to the ```GetTokenAsync``` call.  

 The last is safe since the token source is internal to the class and _cancels upon disposal only_. Users won't be able to cancel the background task without disposal of everything that uses it (including CosmosClient itself, since ```AuthorizationTokenProvider``` is not used directly).

Without these fixes ```InitializeContainersAsync``` may leave a lot of leftovers after the cancellation, even when it succeeds. Moreover, the disposal of the CosmosClient may not cause cancellation of all pending tasks because of [2] even besides the scenario that we started with.

> That depends on the implementation of the TokenCredential, what if the TokenCredential implementation you are using  
  
The other's libraries issues are irrelevant. We fix what we can and open issues on other SDKs if necessary. Moreover, in case of ```TokenCredential``` I could implement my own version that works properly. Also, in my experience HttpClient always cancels fast. My current service does it a lot (up-to several million times a day) and push longer operations to another queue.
   
WDYT?  I could propose a PR with these fixes. The only open question is that there is a ctor that accepts ```AuthorizationTokenProvider```. I am not sure that callers will be happy if we start disposing it. However, these are internal callers only and it could be verified.

**Comment by ealsur** [comment]
@benjzh Thanks for the comments.

1. `InitializeContainerAsync` is `async`. Returning a `Task` or `await` ing it are two ways to deal with async operations, but the method is async regardless. `InitializeContainerAsync` is awaited: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L390. As a side comment, returning the Task is not incorrect (in this case the  `return Task.WhenAll(tasks);`), it just means the current method doesn't do anything after, but someone in the upper chain (in this case `CosmosClient`) is awaiting. You can author an async method that returns a Task and the caller can either await it or handle the Task some other way, it is still a valid async method. This is not a bug.
2. The Authorization is disposed. When the CosmosClient is disposed, the Context is disposed (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L1446), which then disposes the DocumentClient, which disposes the Authorization (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L1253-L1256) which disposes the TokenCredentialCache (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Authorization/AuthorizationTokenProviderTokenCredential.cs#L92-L98)
3. This can potentially be done, yes. I would help on a disposal scenario, I agree. The impact however is not big as disposal of clients is normally related to shutdown scenarios, this Issue can be used to track that improvement.

I respectfully do not agree with this statement:

> Without these fixes InitializeContainersAsync may leave a lot of leftovers after the cancellation, even when it succeeds. Moreover, the disposal of the CosmosClient may not cause cancellation of all pending tasks because of [2] even besides the scenario that we started with.

I explained how the points 1 and 2 are not valid, there are no leftovers as far as I can see in the source code.

The constructor that takes the `AuthorizationTokenProvider` as you mentioned is internal and used in tests: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs#L155

If you agree, I can make this Issue as a tracking item for "propagate the internal cancellation token in the RefreshCachedTokenWithRetryHelperAsync method to the GetTokenAsync call."

**Comment by benjzh** [comment]
@ealsur Thank you for the quick reply.

1. Usually returning a task is not a bug, however when a method is not marked as async it executes without the async state machine. Therefore, in our case since we return the ```Task.WhenAll``` instead of awaiting on it, the cancellation will never be caught in the exception handler. This means - no disposal. Let's look again at the code of ```InitializeContainersAsync``` (I am putting comments inside):
```
           try
            {
                List<Task> tasks = new List<Task>();
                foreach ((string databaseId, string containerId) in containers)
                {
                   // the following doesn't throw in the context of this try/catch block in case Task returned by 
                   // InitializeContainerAsync fails or gets canceled.
                   // It does throw if InitializeContainerAsync fails to return the Task itself
                    tasks.Add(this.InitializeContainerAsync(databaseId, containerId, cancellationToken));
                }

                // same here, if any of the tasks fails - the exception will bubble up the stack, 
                // the below catch doesn't play a role in case of failed tasks
                return Task.WhenAll(tasks);
            }
            catch
            {
                // we get here only if InitializeContainerAsync call fails to return a task, containers == null 
                // or other fringe cases like out of memory
                this.Dispose();
                throw;
            }
```
Please pay attention that if ```CreateAndInitializeAsync``` throws an exception while awaiting on this ```InitializeContainersAsync``` then the instance of cosmosClient just gets abandoned without disposal. 
BTW just for the sake of completeness, returning a `Task` without awaiting loses stack in case of exceptions (not a big deal in many cases). 
2. My bad, you are right. Didn't go so deep inside the code of the context. It does gets disposed!
3. yep

>If you agree, I can make this Issue as a tracking item for "propagate the internal cancellation token in the RefreshCachedTokenWithRetryHelperAsync method to the GetTokenAsync call."
   
Yes, but let's also agree first about the [1] 😏 and then you can decide whether to put these two together or to open another issue.

**Comment by ealsur** [comment]
Fair point on the try/catch, I completely missed it and you are right, the catch won't work if there is a failure.

Let's summarize this issue into 2 improvements:

1. Change the signature of this method to `async` and `await` the call to `Task.WhenAll`: 
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/CosmosClient.cs#L1345-L1363

2. Make sure the calls to `this.tokenCredentialCache.GetTokensAsync` receive `this.cancellationToken`:
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Authorization/TokenCredentialCache.cs#L191-L193

**Comment by benjzh** [comment]
Yes @ealsur, perfectly summarized!
