### ISSUE TITLE
Set IndexKind for index path using DefineContainer

### ISSUE THREAD

**Issue by faresamr** [Azure/azure-cosmos-dotnet-v3#3395]
**Describe the bug**
I'm trying to create container with index policy for a path of kind `Hash`  using [DefineContainer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs#L979)

**To Reproduce**
```
var response = await database.DefineContainer(
                name: "myContainer",
                partitionKeyPath: "/myPartitionKey")
                .WithIndexingPolicy()
                    .WithIncludedPaths()
                        .Path("/myIndexValue/?") // How to set indexKind value?
                        .Attach()
                    .Attach()
                .CreateIfNotExistsAsync();
```

**Expected behavior**
Cosmos container index policy:
```
{
    "indexingMode": "consistent",
    "includedPaths": [
        {
            "path": "/myIndexValue/?",
            "indexes": [
                {
                    "kind": "Hash",
                    "dataType": "String"
                }
            ]
        }
    ]
}
```

**Actual behavior**
There is no method accept index kind value of [IndexKind](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/IndexKind.cs)

**Environment summary**
SDK Version: 3.30.0
OS Version: Windows, Linux

**Comment by ealsur** [comment]
What you are asking is defining an Index on Paths, the IndexKind is not a property of the Path, it's a property of each index in the list of indexes for a path.

My understanding is that defining Indexes on Paths is no longer needed, @jcocchi Can you confirm?

**Comment by neildsh** [comment]
For v2 indexes, Index Kinds are not required. Hence, I am closing this issue.
