### ISSUE TITLE
Json Property Attributes being ignored when upserting to container

### ISSUE THREAD

**Issue by d4sein** [Azure/azure-cosmos-dotnet-v3#3396]
**Describe the bug**
Hi, I'm having issues when setting System.Text.Json as the custom serializer. Some property attributes are ignored when serializing to container. Not 100% sure if it's a bug, hope you guys can help me figure it out.

An example of attribute that works when serializing to cosmos:
```csharp
[JsonPropertyName("id")]
public Guid Id { get; set; } = Guid.NewGuid();
```
An example of attribute that doesn't work when serializing to cosmos:
```csharp
[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
public string? AfiliatedCode { get; set; }
```
Both work when inspecting output in debug mode, even inside the custom serializer.

**To Reproduce**
Define the custom serializer:
```csharp
public class CosmosSystemTextJsonSerializer : CosmosSerializer
{
    private readonly JsonObjectSerializer _systemTextJsonSerializer;

    public CosmosSystemTextJsonSerializer(JsonSerializerOptions jsonSerializerOptions)
    {
        _systemTextJsonSerializer = new JsonObjectSerializer(jsonSerializerOptions);
    }

    public override T FromStream<T>(Stream stream)
    {
        var exMessage = "Could not deserialize model from cosmos. This exception is not supposed to be thrown and needs to be investigated.";

        if (stream.CanSeek && stream.Length == 0)
        {
            throw new InvalidEntityException(exMessage);
        }

        if (typeof(Stream).IsAssignableFrom(typeof(T)))
        {
            return (T)(object)stream;
        }

        using (stream)
        {
            var result = _systemTextJsonSerializer.Deserialize(stream, typeof(T), default)
                ?? throw new InvalidEntityException(exMessage);

            return (T)result;
        }
    }

    public override Stream ToStream<T>(T input)
    {
        var streamPayload = new MemoryStream();
        _systemTextJsonSerializer.Serialize(streamPayload, input, typeof(T), default);

        // For debug purposes, the output is correct (is NOT ignoring the attributes)
        var y = Encoding.ASCII.GetString(streamPayload.ToArray());

        streamPayload.Position = 0;
        return streamPayload;
    }
}
```
Define the SerializerOptions obj: (Can be set directly in the custom serializer class)
```csharp
public static readonly JsonSerializerOptions serializerOptions = new()
{
    Converters = { new JsonStringEnumConverter() },
    PropertyNameCaseInsensitive = true,
    AllowTrailingCommas = true,
};
```
Instantiate the client passing the custom serializer:
```csharp
var client = new CosmosClient(cosmosDbSettings.Endpoint, cosmosDbSettings.Key, new CosmosClientOptions
{
    Serializer = new CosmosSystemTextJsonSerializer(SerializerHelper.serializerOptions),
});
```
Define a class to be inserted in the database:
```csharp
public class MyModel
{
    [JsonPropertyName("id")]
    public Guid Id { get; set; } = Guid.NewGuid();

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? AfiliatedCode { get; set; }
}
```
Upsert two instances of MyModel using `Container.UpsertItemAsync` method:
1. new MyModel() { AfiliatedCode = "CODE" };
2. new MyModel() { AfiliatedCode = null };

**Expected behavior**
- First entity should have a property `"AfiliatedCode"` in the db;
- Second entity should NOT have a property `"AfiliatedCode"` in the db; 

**Actual behavior**
- Property "AfiliatedCode" exists in both entities;

**Environment summary**
SDK Version: 3.30.0
OS Version: Windows 10
TargetFramework: net6.0

**Additional context**
I have a very big Payment object that I want to apply polymorphism to, and only get/upsert valid properties. I know this behavior can be accomplished by using `CosmosSerializationOptions.IgnoreNullValues`, but that creates some limitations I don't wanna take, and I can't use both.

**Comment by d4sein** [comment]
I was working on other stuff while having this whole setup on and I noticed that, when the entity that I'm **upserting** already exists, it DOES consider the json attributes, it only ignores them when I'm creating a new entity, which is really weird.

**Comment by ealsur** [comment]
> I was working on other stuff while having this whole setup on and I noticed that, when the entity that I'm upserting already exists, it DOES consider the json attributes, it only ignores them when I'm creating a new entity, which is really weird.

@d4sein Not sure I understand, the SDK does not perform conditional serialization, the `<T>` is serialized and sent to the server, so in your case, it doesn't matter if the entity existed or not, the serialization should be the same.

**Comment by ealsur** [comment]
I also verified your example, when putting the breakpoint in your line: `var y = Encoding.ASCII.GetString(streamPayload.ToArray());`

I see the serialization clearly showing:

```
{"id":"ac917080-ca32-4b01-88cd-6ade2946c769","AfiliatedCode":"12345"}
```

When AfiliatedCode is set, and:

```
{"id":"6418bcad-6092-4d16-8b35-558f70545873"}
```

When it's not set.

When looking in the Portal at the container, I see:

![image](https://user-images.githubusercontent.com/1633401/185979712-c5d7e12f-25fb-420e-a0e4-5f7eda805178.png)

and:

![image](https://user-images.githubusercontent.com/1633401/185979766-59c94afd-f358-4dec-a672-b0b8c2d544d8.png)

I don't see the AfiliatedCode property being serialized nor existing on the container.

**Comment by ealsur** [comment]
Please reopen with a repro we can use.
