### ISSUE TITLE
Introducing testability

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-cosmos-dotnet-v3#34]
When I write a unit testing with Moq, It can't be mocked.  It says Could not find a parameterless constructor.  

Solution might be adding a parameterless constructor or interface. However, interface might be a good design as an API. 

Another approach is using CosmosDB emulator and having some integration testing. We can do it. However, people might want to unit testing since it is very fast without having remote call.

**Comment by j82w** [comment]
Hi Tsuyoshi,

Can you please provide a list of objects that can not be mocked?

**Comment by TsuyoshiUshio** [comment]
I also try to Mock the method, like this. 

```
                this._containerResponseMock = new Mock<CosmosContainerResponse>();
               

                var expectedCosmosItemResponseMock = new Mock<CosmosItemResponse<Todo>>();
                expectedCosmosItemResponseMock.Setup(p => p.Resource).Returns(ExpectedTodo);
                expectedCosmosItemResponseMock.Setup(p => p.StatusCode).Returns(HttpStatusCode.OK);

                this._containerResponseMock.Setup(p =>
                        p.Container.Items.CreateItemAsync<Todo>(ExpectedPartitionKey, InputTodo, null, default(CancellationToken)))
                    .Returns(Task.FromResult(expectedCosmosItemResponseMock.Object));
```

it causes 

```
Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: Microsoft.Azure.Cosmos.CosmosContainer.
Could not find a parameterless constructor.
```

Seems lack of default constructor. 

I'm a new to this API, so I might misunderstand the implementation. I'm ok if I can write unit testing. (I usually use TDD method). If my implementation is not proper, please let me know how can I write the unit testing using Moq.

**Comment by TsuyoshiUshio** [comment]
Awesome! I appreciate you. I'm trying to understand the new API and how to write unit testing for it. 
I'll write a blog what I learned and current workaround for unit testing.

**Comment by j82w** [comment]
Thanks for the feedback. If you find any other blockers or have any ideas on how to make it easier to unit test please let us know.

**Comment by darthmolen** [comment]
This. Right Here. I also opened #53 with a similar problem (as you're asking for feedback but they're separate from what he's asking)

**Comment by j82w** [comment]
@TsuyoshiUshio and @dathmolen please take a look at the (PR)[https://github.com/Azure/azure-cosmos-dotnet-v3/pull/58]

**Comment by j82w** [comment]
@TsuyoshiUshio and @darthmolen please take a look at the (PR)[https://github.com/Azure/azure-cosmos-dotnet-v3/pull/58]

**Comment by TsuyoshiUshio** [comment]
@j82 awesome!

**Comment by j82w** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/90
