### ISSUE TITLE
StoreResult lifecycle through RefCount

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#3414]
https://dev.azure.com/msdata/CosmosDB/_git/CosmosDB/pullrequest/831633

PR comment: Clean alternative might be to model StoreResult with RefCount mechanism, Now every consumer access raises counter, and all consumers can blindly use it as IDispose.

**Comment by Pilchie** [comment]
Just a note that there is a `RefenceCountedDisposable` implementation at https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ReferenceCountedDisposable.cs.

**Comment by Pilchie** [comment]
I've been taking a look at this, so assigning to myself.

**Comment by Pilchie** [comment]
This change was merged into the internal codebase on 2022-11-11.
