### ISSUE TITLE
Transaction support across multiple containers

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-dotnet-v3#3421]
When can we expect support for transactions across multiple containers? The lack of this feature is seriously making me consider switching to MongoDB Atlas.

**Comment by ealsur** [comment]
This is a service feature you are asking. This repository is for the SQL API SDK, this feature does not exist in the product for the SQL API so there is nothing actionable in this repository.

Please follow up with service feature requests at https://feedback.azure.com/d365community/forum/3002b3be-0d25-ec11-b6e6-000d3a4f0858
