### ISSUE TITLE
[Cosmos Service Upgrade - .NET] Design Document to utilize RNTBD Context Negotiation during `CosmosClient` initialization.

### ISSUE THREAD

**Issue by kundadebdatta** [Azure/azure-cosmos-dotnet-v3#3442]
# Design Approach to utilize Rntbd Context Negotiation during Container Initialization in Direct Mode

## Table of Contents

* [Backgraound.]()
* [Proposed Solution.]()
* [Design Approach.]()
    * Outline.
    * Sequence Diagram for `CosmosClient` initialization.
    * Sequence Diagram when `Rntbd.TransportClient` is invoked from the `GatewayAddressCache`.
    * Sequence Diagram when `RntbdTransportClient` is invoked from the `GatewayAddressCache`.
    * `Azure.Cosmos.Direct` package class diagrams.
    * `Azure.Cosmos.Direct` package list of code changes.
    * `Microsoft.Azure.Cosmos` package class diagrams.
    * `Microsoft.Azure.Cosmos` package list of code changes.
* [Pros of the approach.]()
* [Cons of the approach.]()
* [References.]()

## Backgraound

Currently, during the `CosmosClient` initialization in the .net SDK, we have a method `InitializeContainerAsync`, which leverages dummy query on all feed ranges to open connection, with retry capability to increase the chances of touching max replica. However, there are few drawback with current approach, which are mentioned below.

- It requires unnecessary query plan request to the gateway.
- This approach doesn't guarantee to touch all secondary replicas.
- Does not open connection to primary.
- Expensive in latency and RU.

## Proposed Solution

Instead of using the dummy query during the initialization, we could leverage the Rntbd context negotiation to finish the connection establishment. The design approache to implement the solution, and it's pros/ cons has been discussed below in detail.

### Outline

The basic idea for this approach is to have the `OpenAsync` method in the `IStoreModel` interface, so that it could be implemented by both the `ServerStoreModel` class, present in the `Cosmos.Direct` namespace and `GatewayStoreModel` class present in the `Microsoft.Azure.Cosmos` (v3 sdk) namespace. The benefit of going through the StoreModel route is that this approach maintains the seperation of concerns, between the two mode of connections. To help understand the design better, end to end sequence diagrams has been provided below.

### Sequence Diagram for `CosmosClient` initialization.

The below sequence diagram describes the request and response flow from `CosmosClient` (present in the `Microsoft.Azure.Cosmos` namespace) to the `TransportClient` (present in the `Cosmos.Direct` namespace), during the container initialization.

```mermaid
sequenceDiagram
    participant A as CosmosClient <br> [v3 Code]
    participant B as ClientContextCore <br> [v3 Code]
    participant C as DocumentClient <br> [v3 Code]
    participant D as ServerStoreModel <br> [Direct Code]
    participant E as StoreClient <br> [Direct Code]
    participant F as ReplicatedResourceClient <br> [Direct Code]
    participant G as GlobalAddressResolver <br> [v3 Code]
    participant H as GatewayAddressCache <br> [v3 Code]
    participant I as TransportClient <br> [Direct Code]
    A->>B: 1. InitializeContainerWithRntbdAsync()
    B->>C: 2. OpenConnectionsAsync()
    C->>C: 2.1 storeClientFactory.<br>CreateStoreClient() Sets <br>the ITransportClient
    C->>D: 3. OpenConnectionsToAllReplicasAsync()
    D->>E: 4. OpenConnectionsToAllReplicasAsync()
    E->>F: 5. OpenConnectionsToAllReplicasAsync()
    F->>G: 6. OpenConnectionsToAllReplicasAsync()
    Note over F: Sets the TransportClient deligate and <br> passes it over to the AddressResolver
    G->>G: 6.1 collection = collectionCache.<br>ResolveByNameAsync()
    G->>G: 6.2 partitionKeyRanges = routingMapProvider.<br>TryGetOverlappingRangesAsync(FullRange)
    G->>H: 7. OpenAsync<br>(partitionKeyRangeIdentities)
    Note over G: Resolves the collection by the <br> container link url and fetches <br> the partition key full ranges.
    H->>H: 7.1 GetServerAddressesViaGatewayAsync()
    H->>I: 8. OpenConnectionAsync() <br> using Func<Uri, Task>()
    Note over H: Gets the physical uris from address info <br> and invokes the TransportClient via the Delegate/ Callback <br> method (Func) with the physical uri to establish the Rntbd connection.
```

Depending on the `TransportClient` settings, the SDK could invoke the `Rntbd.TransportClient` or `RntbdTransportClient` present in the `Cosmos.Direct` namespace. The request and response flow are different for the two, and they are described below in detail.

### Sequence Diagram when `Rntbd.TransportClient` is invoked from the `GatewayAddressCache`.

```mermaid
sequenceDiagram
    participant A as GatewayAddressCache <br> [v3 Code]
    participant B as Rntbd.TransportClient <br> [Direct Code]
    participant C as ChannelDictionary <br> [Direct Code]
    participant D as LoadBalancingChannel <br> [Direct Code]
    participant E as LoadBalancingPartition <br> [Direct Code]
    participant F as Channel <br> [Direct Code]
    A->>B: 1. OpenConnectionAsync() <br> using Func<Uri, Task>()
    Note over B: Rntbd.TransportClient <br> implements abstract class <br> Microsoft.Azure.Documents.TransportClient
    B->>C: 2. OpenChannelAsync()
    C->>D: 3. OpenChannelAsync()
    D->>E: 4. OpenChannelAsync()
    E->>F: 5. new Channel()
    Note over F: The Channel Constructor initializes <br> and opens the connection to <br> the respective backend server uri.
    E-->>F: 6. OpenChannelAsync()
    Note over F: Awaits on the channel initialization <br> task to finish in order to ensure that the <br> backend channel was opened deterministically.
```

### Sequence Diagram when `RntbdTransportClient` is invoked from the `GatewayAddressCache`.

```mermaid
sequenceDiagram
    participant A as GatewayAddressCache <br> [v3 Code]
    participant B as RntbdTransportClient <br> [Direct Code]
    participant C as ConnectionPoolManager <br> [Direct Code]
    participant D as ConnectionPool <br> [Direct Code]
    participant E as RntbdConnectionDispenser <br> [Direct Code]
    A->>B: 1. OpenConnectionAsync() <br> using Func<Uri, Task>()
    Note over B: RntbdTransportClient <br> implements abstract class <br> Microsoft.Azure.Documents.TransportClient
    B->>C: 2. GetOpenConnection()
    C->>D: 3. GetOpenConnection()
    D->>E: 4. OpenNewConnection()
    E-->>D: new RntbdConnection()
    D-->>C: IConnection
    C-->>B: IConnection
    B-->>A: OpenConnectionResponse
```

To accomplish the above changes in the request flow, below are the class diagrams and the proposed code changes in both `Azure.Cosmos.Direct` and `Microsoft.Azure.Cosmos` packages.

### Azure.Cosmos.Direct package class diagrams.

Extend the `IStoreModel` interface with `OpenConnectionsAsync()` method. That way, both the `ServerStoreModel` (for Direct mode) and `GatewayStoreModel` (Gateway mode) can implement the `OpenConnectionsAsync()` method. The below class diagram depicts the same behavior.

```mermaid
classDiagram
    IStoreModel --|> ServerStoreModel : implements
    IStoreModel --|> GatewayStoreModel : implements
    <<Interface>> IStoreModel
    IStoreModel: +OpenConnectionsAsync(string databaseName, string containerLinkUri)
    class ServerStoreModel{
      +OpenConnectionsAsync()
    }
    class GatewayStoreModel{
      +OpenConnectionsAsync()
    }
```

Extend the `IAddressResolver` interface with `OpenConnectionsAsync()` method. The `GlobalAddressResolver` can then implement the `OpenConnectionsAsync()` method, which will be called from the `ReplicatedResourceClient` eventually. The `AddressResolver` class can simply implement the method and return an empty `Task`. The `GlobalAddressResolver`.`OpenConnectionsAsync()` is responsible for **a)** resolving the collection by the database name and container link, **b)** fetching the partition key full ranges and **c)** invoking the `GatewayAddressCache` for the preferred region, with the transport client delegate method, passed by the `ReplicatedResourceClient`. The below class diagram depicts the same.

```mermaid
classDiagram
    IAddressResolver --|> GlobalAddressResolver : implements
    IAddressResolver --|> AddressResolver : implements
    <<Interface>> IAddressResolver
    IAddressResolver: +OpenConnectionsAsync(string dbName, string containerLinkUri, Func~Uri, Task~ transportClientDelegate)
    class GlobalAddressResolver{
      +OpenConnectionsAsync()
    }
    class AddressResolver{
      +OpenConnectionsAsync()
    }    
```

Add a new public method `OpenConnectionsAsync` in both the `StoreClient` and `ReplicatedResourceClient` classes, which takes the `databaseName` and `containerLinkUri` as input parameters. The `StoreClient` should eventually call the `ReplicatedResourceClient` with the same parameter/s by invoking the `OpenConnectionsAsync()`. The below class diagram depicts the same.

```mermaid
classDiagram
    IStoreClient --|> StoreClient : implements
    <<Interface>> IStoreClient
    class StoreClient{
      +OpenConnectionsAsync(string databaseName, string containerLinkUri)
    }
    class ReplicatedResourceClient{
      +OpenConnectionsAsync(string databaseName, string containerLinkUri)
    }    
```

Add a `virtual` method `OpenConnectionsAsync()` in `Microsoft.Azure.Documents.TransportClient` abstract class which takes the physical `Uri` as the argument. The `RntbdTransportClient` and `Microsoft.Azure.Documents.Rntbd.TransportClient` can implement the `virtual` method and open the Rntbd connection channel, to the backend replica using the provided `Uri`.

```mermaid
classDiagram
    TransportClient --|> RntbdTransportClient
    TransportClient --|> Rntbd_TransportClient
    <<Abstract>> TransportClient
    TransportClient: ~OpenConnectionsAsync(Uri physicalAddress)*
    class RntbdTransportClient{
      +OpenConnectionsAsync()
    }
    class Rntbd_TransportClient{
      +OpenConnectionsAsync()
    }
```

### Azure.Cosmos.Direct package list of code changes.

- Extend the `IStoreModel` interface with `OpenConnectionsAsync()` method.
- Extend `IAddressResolver` interface with `OpenConnectionsAsync()` method.
- Extend `TransportClient` with `OpenConnectionAsync()` and have the `RntbdTransportClient` as well as the `Microsoft.Azure.Documents.Rntbd.TransportClient` implement the same.
- Add a method `OpenChannel()` in `ChannelDictionary`, `LoadBalancingChannel` and `LoadBalancingPartition` classes respectively. The `LoadBalancingPartition` will eventually open, initialize and return the channel object.
- Implement `OpenConnectionsAsync()` method in `ServerStoreModel`.
- Implement `OpenConnectionsAsync()` method as empty on `GatewayStoreModel`.
- Add `OpenConnectionsAsync()` method to `StoreClient`.
- Add `OpenConnectionsAsync()` method to `ReplicatedResourceClient`.

### Microsoft.Azure.Cosmos package class diagrams.

Extend the `IAddressCache` interface with `OpenConnectionsAsync()` method. The method should take the delegate method `Func<Uri, Task> openConnectionHandlerAsync` along with the other parameters and do the following - **a)** compute the server addresses from the gateway server and fetch the address info and **b)** invoke the delegate `Func<Uri, Task>` method to invoke the respective transport client, either `RntbdTransportClient` or `Rntbd.TransportClient` (based on the `TransportClient` settings) to establish the Rntbd connectivity.

```mermaid
classDiagram
    IAddressCache --|> GatewayAddressCache : implements
    <<Interface>> IAddressCache
    IAddressCache: +OpenConnectionsAsync(..OtherParams, Func~Uri, Task~ openConnectionHandlerAsync)
    class GatewayAddressCache{
      +OpenConnectionsAsync()
    } 
```

### Microsoft.Azure.Cosmos package list of code changes.

- Extend the `IAddressCache` interface with `OpenConnectionsAsync()` method.
- Add a method `InitializeContainerWithRntbdAsync()` in `CosmosClient`.
- Add a method `InitializeContainerWithRntbdAsync()` in `ClientContextCore`.
- Add a method `OpenConnectionsAsync()` in the `DocumentClient`.
- Add a method `OpenConnectionsAsync()` in the `GlobalAddressResolver`, which should resolve the collection by the container link url and fetches the partition key full ranges.
- Add a method `OpenConnectionsAsync()` in the `GatewayAddressCache` which should invoke the delegate of type `RntbdTransportClient` or `Rntbd.TransportClient` (based on the `TransportClient` settings) to establish the Rntbd connectivity.

## Pros of the approach

- Completely maintains the separation of concerns, by multiple abstraction layers.
- Simple to plug and play any future improvements. For example, a similar improvement could be made using the `GatewayStoreModel` for the Gatwway Mode.

## Cons of the approach

- Code changes could be complex, as it touches multiple packages (for e.g. `Cosmos.Direct` and `Microsoft.Azure.Cosmos`), thus increasing the blast radius.

## References

- [Mermaid](https://mermaid-js.github.io/mermaid/#/)

**Comment by ealsur** [comment]
![image](https://user-images.githubusercontent.com/1633401/189202518-7115b353-5d29-42b8-ad89-fe35164792ab.png)

Diagram seems to point that the IConnection is returned across all levels, but in reality it only goes up to the RntbdTransportClient, right?

**Comment by ealsur** [comment]
OpenAsync flow:

1. Read the Account Information through EnsureValidClient -> This reads from Global endpoint, and falls back to PreferredRegions if it cannot reach to Global
2. Fetch the list of partitions of desired containers, this will use the 1st available PreferredRegion
3. If we call the AddressResolver.OpenAsync (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs#L80-L106) we need to make sure not to open it for ALL the regions, but instead, to the PreferredRegion (1st Region on the `addressCacheByEndpoint` list? Needs to be validated). Ideally we should do Write Region and Read Region (PreferredRegion).

**Comment by kundadebdatta** [comment]
> ![image](https://user-images.githubusercontent.com/1633401/189202518-7115b353-5d29-42b8-ad89-fe35164792ab.png)
> 
> Diagram seems to point that the IConnection is returned across all levels, but in reality it only goes up to the RntbdTransportClient, right?

I was thinking if we could return the `IConnection` object all the way back to the `CosmosClient`, so that it could be used in the future to know if the connection was opened successfully. Will add more details on this.
