### ISSUE TITLE
Collection has ClientEncryptionPolicy set, but the document to be written isn't encrypted

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-cosmos-dotnet-v3#3447]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
After upgrading to Cosmos DB encryption sdk from 1.0.1 to 2.0.0, the error happens "Collection has ClientEncryptionPolicy set, but the document to be written isn't encrypted".

Is there any breaking change between 1.0.1 and 2.0.0?

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

Just follow https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-always-encrypted?tabs=dotnet to create new cosmos db with encryption enabled, error happens when inserting new document that contains one path that need encryption.

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
@abhijitpai / @kr-santosh Could you verify the scenario? I don't see any breaking changes indicated in the Encryption package changelog (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Encryption/changelog.md)

**Comment by kr-santosh** [comment]
Can you please share the code which gets an encryption supported client via .WithEncryption()? Is the same client being used to get a database object and container object to create the item? This error usually happens when you try to create items using container objects which does not have encryption enabled on it (using a regular client)

**Comment by ealsur** [comment]
@erich-wang does the scenario described apply to your case? Could you confirm?

**Comment by erich-wang** [comment]
Thank you all for the quick response. Somehow I could not reproduce it, probably caused by mismatch version between cosmos sdk and cosmos encryption sdk. I'm closing this issue now.
