### ISSUE TITLE
[Cosmos Service Upgrade - .NET] Utilize RNTBD Context Negotiation in the `Azure.Cosmos.Direct` package to open connections to backend replica.

### ISSUE THREAD

**Issue by kundadebdatta** [Azure/azure-cosmos-dotnet-v3#3454]
### Goals of the Task.

- Use the RNTBD context negotiation in `Azure.Cosmos.Direct` package to establish initial connection to the backend replica nodes during the `CosmosClient` initialization, instead of dummy (real) requests.

- Practically there are two design choices to open the Rntbd connections to the backend replica nodes, **a)** let the connection creation run as a backend task, executing separately from the caller task, OR **b)** await on the backend task to finish the connection handshake. However, for the interest of this particular work item, we should open the backend connection more deterministically thus choosing the option b as the default design.

- Make necessary code changes in `Azure.Cosmos.Direct` package.

- Write enough unit tests to cover the new code flow.

### Pros and Cons of choosing between two different Channel initialization types.

| Channel Initialization Type | Pros | Cons |
| --- | --- | --- |
| **_non-awaited_** | **A)** Because the `Channel` initialization and Rntbd Context Nogiation happens in the background as a separate task, the `OpenConnection` process becomes much faster from the `LoadBalancingPartition`, thus decreasing the overall `CosmosClient` initialization time significintly from a developer perspective. |  **A)** Does not gurentee that the Channel was opened successfully to the backend replica node, as the connection opening and Rntbd negotiation happens as a background task.  <br> <br> **B)** The concurrency control: because the connections are opened as a background task, there is practically no way to batch the connection opening, which could eventually impact high CPU utilization. |
| **_awaited_** | **A)** Because the `Channel` initialization and Rntbd Context Nogiation calls are awaited, it is guaranteed that either a) the connection was made successfully to the backend replica OR b) the connectivity failed with exception. | **A)** As the Rntbd Context Nogiation calls are awaited, the `OpenConnection` process becomes much slower compared to the non-awaited one. This will eventually increase the overall `CosmosClient` initialization time. <br> <br> **B)** There might be times, where the caller initiates the `CosmosClient` and does not trigger any operation afterwards. Therefore, it is also not guaranteed that the backend replica nodes will still remain healthy during the time an actual request was made. |

**Comment by xinlian12** [comment]
Another concern for not wait is the concurrency control - during openConnections, we will not want to overloading the system so we should have a nob which can help us tuning how fast we allow to open new channels.
