### ISSUE TITLE
ReadItemAsync and bulk execution throwing Bad Request (400) with special characters

### ISSUE THREAD

**Issue by silvioguiso** [Azure/azure-cosmos-dotnet-v3#3456]
**Description**
When creating a `CosmosClient` and setting the option `AllowBulkExecution` to `true`, the client throws a Bad Request Exception with an empty Reason for specific ID / partitionKey values.

Example id value: `NE3cDI8BljAatTkAptI++kPrmDCa+S8j6wBG4Kc7W/A=`

**To Reproduce**
* Create a cosmos db with a container
* Set the id to be the partitionKey
* Create the cosmos client with the options for bulk execution to true
* Read the above id value

```
var key = "cosmosKey";
var endpoint = "cosmosEndpoint";
var dbName = "dbName";
var containerId = "containerId";

var options = new CosmosClientOptions()
{
    AllowBulkExecution = true
};

var client = new CosmosClient(endpoint, key, options);
var container = client.GetContainer(dbName, containerId);

var id = "NE3cDI8BljAatTkAptI++kPrmDCa+S8j6wBG4Kc7W/A=";
var pk = new PartitionKey(id);

try
{
    var item = await container.ReadItemAsync<dynamic>(id, pk);
}
catch (Exception ex)
{

}
```

**Expected behavior**
Error 404 is thrown (Not Found).

**Actual behavior**
Error 400 is thrown (Bad Request), with an empty Reason.

**Environment summary**
SDK Version: 6.0.203
OS Version: windows
Microsoft.Azure.Cosmos
  * 3.29.0
  * 3.29.0-preview
  * 3.30.0
  * 3.30.0-preview
  * 3.30.1
  * 3.30.1-preview

**Additional context**
* When I remove the slash from `NE3cDI8BljAatTkAptI++kPrmDCa+S8j6wBG4Kc7W/A=`, making it `NE3cDI8BljAatTkAptI++kPrmDCa+S8j6wBG4Kc7WA=` it does throw a 404 Not Found exception (expected).
* When I change `AllowBulkExecution` to `false`,  it also throws a 404 Not Found exception (expected).

**Comment by FabianMeiswinkel** [comment]
This is expected because the id value contains invalid characters ('/')

The disallowed characters for the id field are documented here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet#remarks

**Comment by ealsur** [comment]
Thanks for the report. `/` is reported as an unsupported character: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet#remarks

Bulk (or TransactionalBatch, you will probably face the same behavior) use a different network protocol. How they behave with this unsupported characters might differ.

In fact, if you attempt the ReadItem with AllowBulkExecution but with Gateway mode, you will get a different result.

**Comment by silvioguiso** [comment]
Thanks for the feedback and the pointer to the documentation. I appreciate it! I think I am thrown off by the following inconsistencies:

I would not expect these two scenarios to work with `AllowBulkExecution` set to `true`, but they do insert correctly, or return a 404 correctly.
* `CreateItemAsync` with `AllowBulkExecution` set to `true` when an item is given this id: `NE3cDI8BljAatTkAptI++kPrmDCa+S8j6wBG4Kc7W/A=`
* `ReadItemAsync` with `AllowBulkExecution` set to `true` returns 404 (expected, not the 400 as reported before) for this id which also contains a slash, but at the end: `NE3cDI8BljAatTkAptI++kPrmDCa+S8j6wBG4Kc7WA=/`

But for the sake of consistency, I'll stick to avoiding those characters altogether.

Thank you!

**Comment by ealsur** [comment]
The problem is that because of system design, Create operations send the Ids as part of the body. Read operations use the Id as part of the path/url, that is when the `/` character generates problems.

Ideally the service should reject these documents, but that behavior could be interpreted as a breaking change (some customers might be saving data and not using point reads, and it theory works).

But using these characters can lead to failures across different stacks (for example, trying to read those documents in the Portal might also fail).

**Comment by silvioguiso** [comment]
Gotcha, that makes sense. Thank you for your input!
