### ISSUE TITLE
Document class is not present in the package

### ISSUE THREAD

**Issue by techmarki** [Azure/azure-cosmos-dotnet-v3#3460]
**Is your feature request related to a problem? Please describe.**
I am writing an Azure Function with CosmosDBTrigger. The function reads the documents that are of different types, with different fields, so I can't just do a binding to a certain class type, like this

```` c#
[CosmosDBTrigger(
            databaseName: "ToDoList",
            collectionName: "Items",
            ConnectionStringSetting = "string",
            LeaseCollectionName = "leases",
            CreateLeaseCollectionIfNotExists = true)] IReadOnlyList<ClassType> input
````

I could just bind it to a `IReadOnlyList<object> input`

BUT

I really liked the support for such case in version 2 of the package, where there was a Document class, which would give me access to `id` property and also `GetPropertyValue` method

I can install this package:
https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/#readme-body-tab

And use the Document class, the only thing that is bothering me is that the package is marked as deprecated now

**Describe the solution you'd like**
Would it be possible to include the `Document` class into the v3 library and if not, what was the reason of not transitioning it into the v3 library? Is there another alternative in v3 library that I missed?

**Describe alternatives you've considered**
I could just use the object for the input, but in my case it would cause me to Deserialize the same object twice. I could provide an explanation as to why is it that way, but not sure if you guys want to know it

**Comment by ealsur** [comment]
For V2 to V3 SDK migration see: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/migrate-dotnet-v3?tabs=dotnet-v3#classes-replaced-on-net-v3-sdk (particularly the area denoted in this link, which would answer your question).

There is no plan to include `Document` in the V3 SDK.

Azure Functions is outside of the scope of this repo. Please reach out to https://github.com/Azure/azure-webjobs-sdk-extensions/ for issues on that area.

As a side note, the `CosmosDBTrigger` lets you only bind to `Document` on the `3.X` version (your code snippet looks like 3.X). The 4.X package that uses this repo's SDK, let's you use any `<T>` but your code snippet does not point to that version.

**Comment by techmarki** [comment]
Do you know if there's another way to get the document in the input and be able to read it's properties dynamically?

Instead of using object?

**Comment by ealsur** [comment]
The linked documentation explains the alternatives:  https://docs.microsoft.com/en-us/azure/cosmos-db/sql/migrate-dotnet-v3?tabs=dotnet-v3#classes-replaced-on-net-v3-sdk 

> Because the .NET v3 SDK allows users to configure a custom serialization engine, there's no direct replacement for the Document type. When using Newtonsoft.Json (default serialization engine), **JObject** can be used to achieve the same functionality. When using a different serialization engine, you can use its base json document type (for example, JsonDocument for System.Text.Json). The recommendation is to use a C# type that reflects the schema of your items instead of relying on generic types.

You can use **JObject** and it allows exactly the same operations.

**Comment by techmarki** [comment]
Wow, can't believe I missed that part lol Thank you so much for your time!
