### ISSUE TITLE
Emulator: Microsoft.Azure.Cosmos.Compute.Host.ServiceFabric.EntryPoint.exe crashes on startup

### ISSUE THREAD

**Issue by devlie** [Azure/azure-cosmos-dotnet-v3#3465]
Microsoft.Azure.Cosmos.Compute.Host.ServiceFabric.EntryPoint.exe crashes on Emulator startup, but Emulator seems to work just fine.
> System.Collections.Generic.KeyNotFoundException: 'FabricDataPath'

**To Reproduce**
Launch emulator normally.

**Expected behavior**
No crash.

**Actual behavior**
Microsoft.Azure.Cosmos.Compute.Host.ServiceFabric.EntryPoint.exe crashes.

**Environment summary**
OS Version: Windows 11 build 25201 (Dev External Channel) - crashes on multiple builds already.
Emulator version: 2.14.9.0 (crashed on 2.14.7.0 as well).

**Comment by ealsur** [comment]
Please report Emulator issues through the Emulator channels: https://learn.microsoft.com/en-us/azure/cosmos-db/troubleshoot-local-emulator, this repository is for the Cosmos DB .NET V3 SDK.
