### ISSUE TITLE
System Usage Task: Use Thread.Sleep Conditionally for netstandard 2.0 onwards

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#3472]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
In SDK, we have a background job which collects system usage information. Its blocking in nature. We need to optimize it for netstandard2.0 version and above code.

**Fix**
Instead of `Task.Delay().Wait() ` we can use `Thread.Sleep ` for netstandard2.0 version onwards.

**Comment by aavasthy** [comment]
Resolved this issue as part of this PR https://msdata.visualstudio.com/DefaultCollection/CosmosDB/_git/CosmosDB/pullrequest/899941

**Comment by laithhisham** [comment]
@aavasthy could you please send a link to the PR here?
what version of the SDK includes the change?

**Comment by aavasthy** [comment]
Pull request : https://msdata.visualstudio.com/DefaultCollection/CosmosDB/_git/CosmosDB/pullrequest/899941
It will be included in the next release that would take place in 2 weeks. Will update the version number here as soon as it happens.

**Comment by laithhisham** [comment]
Hi @aavasthy 
just checking on the release of this, is it included in the latest release of the cosmos nuget (3.31.1 - https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-3311---2022-10-29)?

**Comment by aavasthy** [comment]
> Hi @aavasthy just checking on the release of this, is it included in the latest release of the cosmos nuget (3.31.1 - https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-3311---2022-10-29)?

Yes @laithhisham it went live with this release.
