### ISSUE TITLE
Make SubStatusCodes public in Azure.Cosmos.Direct package

### ISSUE THREAD

**Issue by ashwinGokhale** [Azure/azure-cosmos-dotnet-v3#3475]
**Is your feature request related to a problem? Please describe.**
When there is an error in a Transactional Batch, it is basically impossible to get any meaningful error response to understand why an error occurred. See #1162. The public properties in TransactionalBatchOperationResult only allow a user to see the status code, but if there is a BadRequest, the SubStatusCode is not public so we don't know what the specific error is.

**Describe the solution you'd like**
Either 1) make the SubStatusCode in TransactionalBatchOperationResult public or 2) always populate the ErrorMessage property in TransactionalBatchResponse

**Comment by ashwinGokhale** [comment]
@ealsur if the ideal scenario is that each reason would have its own substatus code but does not, then I believe that this is a separate work item that the cosmos db team should look into. If you ensure that every error has a unique status + substatus combo then the cosmos sdk can populate an error message and optionally customers of the sdk can derive their own error message based on the status + substatus if they don't want to use the prepopulated one. 

Ideally what I want is not a single ErrorMessage on the TransactionalBatchResponse, but a new ErrorMessage property on each TransactionalBatchOperationResult so that if I have 5 items in the batch and 1, 3, and 5 fail but 2 and 4 succeed, then I can understand why 1, 3, and 5 failed. If the SubStatusCode is public then I can filter out the errors that have FailedDepedency status and Unknown substatus.

**Comment by ealsur** [comment]
Your request makes sense, and aligns with what is asked on the other Issue. 

Both these asks (unique combinations of status + substatus for each combination of error and the presence of the error message on Batch) need to be supported by the service.

Scoping this ask to the latter, I would advice to use the existing Issue that is already tracking that ask. Right now from the SDK perspective there is no code change that we can do because that information is not present in the response.

**Comment by ealsur** [comment]
@ashwinGokhale Can you confirm if you added your concern on the Message related issue? Please do so. I'll close this issue as the other request (having different SubStatusCodes for different cases is not something we can tackle or do on the SDK repo and changing these values for existing errors could be a breaking change from the service perspective).
