### ISSUE TITLE
Not a bug but a query on why my code is slow

### ISSUE THREAD

**Issue by simonziegler** [Azure/azure-cosmos-dotnet-v3#3487]
A query loading all documents from a single partition on a container is very slow. 1481 documents, all of the same type. 6 MB of data takes between 1.5 seconds on my laptop with 200Mbps internet. Would I expect this query to be so slow?

This is a cut down version of the code:

```csharp
            var requestOptions = new QueryRequestOptions()
            {
                MaxBufferedItemCount = -1,
                MaxItemCount = -1,
                PartitionKey = new PartitionKey(partitionKey.ToString()),
            };

            var setIterator = container
                .GetItemLinqQueryable<T>(false, requestOptions: requestOptions).ToFeedIterator();
            
            var list = new List<T>();

            while (setIterator.HasMoreResults)
            {
                var response = await setIterator.ReadNextAsync().ConfigureAwait(false);
                list.AddRange(response);
            }

            // takes 2 to 4 seconds to get here
```

The execution time is all spent running the `ReadNextAsync` function.

Here are query stats from the COSMOS page on Azure:

![image](https://user-images.githubusercontent.com/11708435/193662327-e7828186-b439-43eb-bfb0-ed62f2ec8f46.png)

Thank you.

**Comment by simonziegler** [comment]
Further information. I know that the issue is not to do with deserializing the data returned (that was a possibility). For the sake of benchmarking I added the following lines that take around the same amount of time to execute:

```csharp
            var iterator = container.GetItemQueryStreamIterator($"SELECT * from c WHERE c._partitionKey = \"{partitionKey}\"", requestOptions: requestOptions);
            while (iterator.HasMoreResults)
            {
                using var response = await iterator.ReadNextAsync().ConfigureAwait(false);
                using var sr = new StreamReader(response.Content);
                var line = sr.ReadLine();
            }
```

**Comment by ealsur** [comment]
Please see https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3474

**Comment by simonziegler** [comment]
Thanks for picking up on this fast, @ealsur. I suspect it's a latency thing. My service is a singleton and other queries with little data return in a few milliseconds. I've struggled with setting up diagnostics to test this. Is there a reference that would help?

Simon

**Comment by ealsur** [comment]
```
using var response = await iterator.ReadNextAsync().ConfigureAwait(false);
Console.WriteLine(response.Diagnostics.ToString());
```

Reference: https://learn.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-dot-net-sdk-slow-request?tabs=cpu-new#capture-diagnostics

**Comment by simonziegler** [comment]
Fabulous, here are the results of the first of two `ReadNextAsync()` calls on the feed iterator: https://gist.github.com/simonziegler/de0f6dd7c46125ddc1604e50d57c5ebd

The overall time taken is 1442.73 milliseconds. Transit time is 1385.85 milliseconds. So that must be the issue.

I am only running locally for development purposes. My live app lives on Azure. Can you suggest if you think that there will be a dramatic improvement in transit time for the azure hosted app, and also is there any way to speed things up for my development machine? I have circa 200Mbips internet and am using a VPN to Azure.

Thank you for the help today!

**Comment by ealsur** [comment]
> The overall time taken is 1442.73 milliseconds. Transit time is 1385.85 milliseconds. So that must be the issue.

> I am only running locally for development purposes

Yep, that is the problem. The amount of network hops between your machine and the cloud reflects that latency.

Normally you want to perform latency analysis when running on the Production or real environment, looking for a "problem" you will never have when the app is running in the desired environment is mostly wasting your time.

The recommendation would be to follow https://learn.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-dot-net-sdk-slow-request?tabs=cpu-new#capture-diagnostics and you could **conditionally* log Diagnostics, for requests where the `GetClientElapsedTime` is greater than some threshold defined by your own application requirements (for example, log all requests > than 1 second) and then investigate those.

Keep also in mind that queries in particular, have no latency SLA (complexity of the query and volume of data returned will affect overall latency, the more complex the query, the longer the backend execution, the bigger the results, the longer the network transfer).

**Comment by simonziegler** [comment]
Great advice. I loaded the same dataset in the live app and while it's not timed (yet), it seems pretty snappy. I like the conditional logging idea; I have a couple of datasets in mind that I can detect by id, so I'll log them. Is there anything that you'd suggest I do with options? Varying between a Gateway or Direct connection and enabling bulk data seemed to have no impact.

**Comment by ealsur** [comment]
Bulk does not affect queries. Direct should be faster. Always look at P99 latency though, looking at 10 requests is not representative, capture latency for an hour and see what is the P99 latency overall.
As per the linked document, the Diagnostics contain a BELatency field, if the Transit Time is X and BELatency is very close to X, then it means most of the latency is related to the operation. If the operation is a query, could indicate lack of indexes.

**Comment by simonziegler** [comment]
Will do and thank you
