### ISSUE TITLE
Documentation Issue - This Call Is Not Awaited?

### ISSUE THREAD

**Issue by lanfear** [Azure/azure-cosmos-dotnet-v3#3492]
**Describe the bug**
Here in the docs, I don't believe this call is actually awaited, my CA was informing me.  The internal iteration in the loop is, which is correct, but the iterator creation here doesn't need it right?

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/ff01c1448fe40226d2a8433c135e48d47f66d9b9/README.md?plain=1#L21

**To Reproduce**
(n/a)

**Expected behavior**
(n/a)

**Actual behavior**
(n/a)

**Environment summary**
(n/a)

**Additional context**
(n/a)

**Comment by ealsur** [comment]
Correct, there is no need to await this call, we'll fix the doc, thanks!
