### ISSUE TITLE
Add tests for correct null handling

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#350]
Need to add test coverage to ensure regression like [this ](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/346) doesn't happen again.

**Comment by ealsur** [comment]
@j82w It was a regression then? null values should be rendered as `null`?

**Comment by ealsur** [comment]
@kirankumarkolli It seems like this PR changed the behavior https://github.com/Azure/azure-cosmos-dotnet-v3/pull/97

It added:

    private static readonly JsonSerializer Serializer = new JsonSerializer()
    {
        NullValueHandling = NullValueHandling.Ignore,
    };

Can you confirm if this new behavior (not storing null properties) is effectively what we want? If so, I can send a PR to cover it with a Test to ensure it doesnt change.

**Comment by j82w** [comment]
The default behavior in v2 is to not ignore. Ignoring null values is a regression and should be reverted.

**Comment by ealsur** [comment]
@j82w I disagree, this issue was to track the existence of a unit test. The regression is tracked by #346 and @simplynaveen20 is working on that

**Comment by j82w** [comment]
@ealsur good point, and that's great the fix is getting worked on.
