### ISSUE TITLE
500.30 when publishing to .net 6 Web App with API

### ISSUE THREAD

**Issue by ziron999** [Azure/azure-cosmos-dotnet-v3#3501]
I am trying to do the follow from a web app:
Get the current user logged in (any way)
Used microsoft authentication
Allow get and post based on identity

The site works fine until I connect cosmosdb as a connected service and I tested a Get with the code mentioned on this front page.
It works locally but not after publishing.

**Comment by ealsur** [comment]
The SDK does not return HTTP 500, potentially it's your Web Application failing, not handling the SDK response/exception.

The only way we can help you in this repository is if you share the Cosmos DB .NET SDK exception (if any), we cannot help debugging particular applications.

**Comment by ziron999** [comment]
What is the proper way to make this happen with the SDK?
It would be nice to see an example from the SDK that uses Microsoft auth bearer with cosmos from a web app. That is all I'm really doing but can't pinpoint the lines of code I'm missing. From what I can tell, it should be working.

**Comment by ealsur** [comment]
@ziron999 Not sure I understand your question. 

Let's first start with, the HTTP 500 you are getting, it means there was an error. Which is the error? Are you logging it? If not, then that's where you need to start, you need to see which is actually the error in your app code that is generating this problem? The error if it's an exception, will contain details, the call stack, message and more information. That will tell you where to go next, maybe this has nothing to do with the SDK.

If the exception is an SDK generated from the SDK (type `CosmosException`) then please share all the details here and we can try to help you.

If the code works locally but not when deployed, it's basically the same code, so this is probably related to some configuration missing when deployed or some difference in the environment. 

We cannot help troubleshooting your App, we can only help understanding SDK exceptions if any.

**Comment by ziron999** [comment]
This can be closed, we have moved away from cosmos db
