### ISSUE TITLE
GetChangeFeedIterator: Retrieve change feed as string

### ISSUE THREAD

**Issue by MaximeJonckheere** [Azure/azure-cosmos-dotnet-v3#3502]
`FeedIterator<T> GetChangeFeedIterator<T>`

Currently the iterator returns a deserialized object of the provided type. However, in our case we do not need to have the document deserialized. We would like to iterate through the feed as strings. We can then later decide if we need to deserialize it or not.

Is there a way to iterate the feed as strings?

**Comment by bartelink** [comment]
You can customize exactly how the binding happens by passing a custom `Microsoft.Azure.Cosmos.CosmosSerializer` via `CosmosClientOptions.Serializer`

If you do a custom implementation, you can map the stream to a `string` and/or the `IStream`, but it sounds like you in the typical case will be doing JSON deserialization; typically for that you do one of:
- Out of the box, it uses JSON.net and can you use `Microsoft.Azure.Documents.Document` to get the rawest form
- If you've customized it to use `System.Text.Json` e.g. https://github.com/search?q=org%3Ajet+CosmosJsonSerializer&type=code, you can use `System.Text.Json.JsonDocument` as the `<T>`.

**Comment by ealsur** [comment]
You can use `GetChangeFeedStreamIterator` https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs#L1399, that returns the raw ResponseMessage.
