### ISSUE TITLE
Can not set index kind, dataType and precision to IndexingPolicy IncludedPath

### ISSUE THREAD

**Issue by donghexu** [Azure/azure-cosmos-dotnet-v3#351]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Before 3.0.0.10-preview, we can use the following code to construct the full indexing policy, especially the index kind, dataType, and precision:
    new IndexingPolicy(Index.Range(Microsoft.Azure.Cosmos.DataType.Number, -1), Index.Range(Microsoft.Azure.Cosmos.DataType.String, -1))

After 3.0.0.10-preview, the Indexes field inside IndexingPolicy->IncludedPath is internal visible, and users can only set the Path, but not the Indexes. 

Besides, CosmosContainerSetting Fluent API provides function like
.WithIndexingPolicy()
        .WithIndexingMode(IndexingMode.Consistent)
        .WithAutomaticIndexing(false)
        .WithIncludedPaths()
            .Path("/includepath1")
            .Path("/includepath2")
            .Attach()
However it missed the way to set indexes kind, datatype and precision.

Index class is also internal visible, so users can not use things like RangeIndex to construct IncludedPath. 

**To Reproduce**
Try to construct the full IndexingPolicy with IncludedPath + Indexes, without internal visible. 

**Expected behavior**
Users can still set the index kind, dataType and precision for IncludedPath inside IndexingPolicy

**Actual behavior**
There isn't a way to do that. 

**Environment summary**
SDK Version: 3.0.0.10-preview
OS Version (e.g. Windows, Linux, MacOSX)

**Comment by ealsur** [comment]
PR with extension to Fluent API is out

**Comment by NateB2** [comment]
For us, this is particularly important because we have queries that do range searches against dates, which is not included in the default index.  As it currently exists, we would need to add a deploy step to our release pipeline to add in the index and a separate script to add the index to the local emulator for development work, which is not ideal.

**Comment by LeroyK** [comment]
We cannot create any valid indexes using this SDK and have to resort to the old V2 SDK for that.

Is there any ETA on when this will be fixed?

**Comment by LeroyK** [comment]
It seems that indexes now [default to the Range kind](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-manage-indexing-policy).

> As part of the SDK and Portal upgrade, we are evolving the index policy to align with a new index layout we have rolled out to new containers. With this new layout, all primitive data types are indexed as Range with full precision (-1). Therefore, the index kinds and precision are not exposed to the user anymore. In the future, users will need to simply add paths to the includedPaths section, and ignore indexKinds and precision. This change has no impact on performance and you can continue to update indexing policy using the same syntax. You can continue to use all samples in our existing documentation to update index policy.
