### ISSUE TITLE
[Discussion]Address request honor user cancellation token

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-cosmos-dotnet-v3#3521]
Currently, gateway address calls will not honor user cancellation token, re-examine whether we cancel it while not impacting address calls.

**Comment by ealsur** [comment]
Already discussed on https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3279

**Comment by ealsur** [comment]
Also related https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3284#discussion_r903162843

**Comment by ealsur** [comment]
Closing as by design
