### ISSUE TITLE
[Bug]Validate Gateway Tenant DNS changes impact

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-cosmos-dotnet-v3#3523]
Validate Gateway Tenant DNS changes impact

**Comment by ealsur** [comment]
Clarification: DNS changes on the Gateway tenant, not the account DNS changes

**Comment by xinlian12** [comment]
> Clarification: DNS changes on the Gateway tenant, not the account DNS changes

Thanks Matias, updated the title

**Comment by kirankumarkolli** [comment]
Duplicate of #3658
