### ISSUE TITLE
Query behavior difference when using Continuation Token and ResponseContinuationTokenLimitInKb

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-cosmos-dotnet-v3#3543]
**Background:**
I am testing the query behavior when using Continuation token.

Seeing from this post: https://stackoverflow.com/questions/54216251/cosmos-db-continuation-token-size-influences-whether-query-returns-new-documents/, he never gets documents that were created after the first continuation token had been created. 

But I got different behaviors. When I use the continuation token, I will see the newly added document after the first continuation token is created if I don’t set the token size limit, and I won’t see revised document. Is this behavior expected? 

Also, since I noticed that the continuation token size can grow very large, I would like to restrict the size of token using [FeedOptions.ResponseContinuationTokenLimitInKb](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.feedoptions.responsecontinuationtokenlimitinkb?view=azure-dotnet). But it seems that the limitation on size will lead to potential re-evaluating of the index, and we may get different results.

**What we want to confirm:**
1.	Suppose we restrict the size of a continuation token by setting FeedOptions.ResponseContinuationTokenLimitInKb, except for RU costing difference, will there be any other behavior difference for query(e.g. different query result)? 
2.	And if so, during the query execution with the continuation token, will I see duplicate results (appear multiple times) if the document is being revised concurrently with the FeedOptions.ResponseContinuationTokenLimitInKb being set?
3.  Besides setting this token size limit, would it be a good idea to do string compression/decompression on our side to reduce token length?

**Comment by blankor1** [comment]
Can anyone help provide some information? Any insight would be appreciated!

**Comment by neildsh** [comment]
Hello @blankor1 , my apologies for the late response here.

Please see answers below:

> Suppose we restrict the size of a continuation token by setting FeedOptions.ResponseContinuationTokenLimitInKb, except for RU costing difference, will there be any other behavior difference for query(e.g. different query result)?

You may see a slightly different query result if your document set has changed due to insertion between continuations, and we are forced to reevaluate query because the continuation size was small enough that we could not serialize the filter postings.


> And if so, during the query execution with the continuation token, will I see duplicate results (appear multiple times) if the document is being revised concurrently with the FeedOptions.ResponseContinuationTokenLimitInKb being set?

You will not see duplicate results.

> Besides setting this token size limit, would it be a good idea to do string compression/decompression on our side to reduce token length?

As long as the query api receives the continuation token in the exact same form that it yielded, we do not care how you store your token or if you compress it etc.
