### ISSUE TITLE
MAJOR Perf Regression Using The Same Binaries From Ubuntu 20.04 -> 22.04

### ISSUE THREAD

**Issue by QuinnDamerell** [Azure/azure-cosmos-dotnet-v3#3553]
**Describe the bug**
I'm running the latest NuGet version, I just upgraded to dotnet7, and all systems are 100% updated. I have a service that handles active server connections, so when it restarts to update, all of the current servers connect also reconnect. Usually, that's somewhere between 4k-6k connections trying to re-connect in 10-30 seconds. When the client reconnects, I need to look up its information in my CosmosDB database, so I do a simple query for an indexed unique field representing the client.

Results **Running the exact same binaries under dotnet 7**:
On **Ubuntu 20.04**:  The ~4k connections take about 20 seconds to full reconnect, and my 4 core VM hovers around 20% CPU usage.
On **Ubuntu 22.04**: The ~4k connections take about 5 minutes to fully reconnect, and my 4 core VM is maxed out at around 100% CPU usage.

This is a really bad regression, and it must be related to the OS change. Again, I'm using the exact same complied binaries of the server and CosmosDB SDK. The two VMs are setup identically, the only difference is the OS version. I noticed this issue after upgrading to Ubuntu 22.04; my server got really slow. To validate it, I then created a new VM using the old OS, where I'm able to switch traffic between.

I know that the pref regression is in CosmosDB, because the lookup call is what's taking the majority of the time and seems to be the cause of the 100% CPU load. It seems really suspicious because I get that a large influx of lookup queries all at once might max out the DB, but it wouldn't expect it to max out the client-side CPU, all of the pending client-side tasks should just be awaiting the DB response.

**To Reproduce**
Breaking down my code, basically, it's equivalent to calling this small sudo code block in a concurrent loop about 3-4k times in 20 seconds.

``` 
         var container = Db.GetOctoClientMetaContainer();
                try
                {
                    var it = container.GetItemQueryIterator<OctoClientMeta>($"SELECT * FROM OctoClients u WHERE u.id='{id.ToUpper()}'");
                    while (it.HasMoreResults)
                    {
                        foreach (var client in await it.ReadNextAsync())
                        {
                            return new UpdateResult(true, client);
                        }
                    }
                }
                catch (Exception e)
                {
                       ...
                }
````

**Expected behavior**
Like on Ubuntu 20.04, this should be expensive, but it shouldn't peak out the CPU.

**Actual behavior**
On Ubuntu 22.04, it peaks the CPU and takes a lot longer for all 4k lookups to occur.

**Environment summary**
SDK Version: CosmosDB 3.31.2
OS Version Ubuntu 20.04 and Ubuntu 22.04

**Additional context**
I would love to help gather anymore info that I can, perf traces or whatnot, just let me know.

**Comment by ealsur** [comment]
Thanks for the detailed report, a couple of clarifying questions:

* You mention you are using the same SDK version, does this mean the only variable is upgrading Ubuntu from 20.04 to Ubuntu 22.04? The SDK version is remaining constant?
* There is no Ubuntu-specific code in this library, it's a `netstandard2.0` library, meaning that the underlying framework implementation is responsible for the implementation, not the library. What are the expectations you have from reporting this issue in this repo and not in Ubuntu? If there is no Ubuntu-specific code, what do you expect us to act on?
* Are you using the same .NET version across both Ubuntu versions?

**Comment by QuinnDamerell** [comment]
No problem:

- Yeah, the SDK version is the same. I'm using the exact same build output of my dotnet core server on both OS. The VMs are setup identically; the only difference is the OS version.
- I figured you don't have any platform-specific logic in your lib, but there's some difference here that's impacting your lib significantly. I do agree that it must be something about how dotnet is implemented between the OSs, but I thought maybe it would be better to start here for a perf analysis rather than on the dotnet team. Buyt maybe we should just cut it right over to them?
- Yeah, I'm using dotnet 7 (updated and latest) on both versions of Ubuntu.

Do you have any perf captures or anything I can gather for you? Or should we jump directly over to the dotnet runtime team (is that the correct team?) to open the bug on them?

I'm kind of surprised no one else using this lib has run into this, I'm doing a really simple lookup and the perf difference is really massive. It doesn't seem like my use case where is an outlier, but maybe it is?

**Comment by ealsur** [comment]
Normally when performing CPU investigations you want to narrow down where the CPU is actually on, maybe the CPU is being spent on things that are not related to the library or .NET but on something else. The first step is normally narrow down which are the hot paths you are running on.

A simple query does not just raise CPU by itself. The logic behind the query (assuming you are connecting to the same account, performing the same query) does not change depending on the OS, so it must be some difference on the OS and how it handles some particular operation (but without the hot paths you don't know exactly which component/library is).

It is common for High CPU scenarios to go through the wrong path of assuming the SDK is the source of the High CPU, sometimes there are other environmental conditions driving the CPU up and the SDK is simply impacted because TCP connections are sensible to High CPU.

My recommendation before reaching to the .NET team or Ubuntu or anyone is to investigate which are the hot paths or exactly what is driving the CPU up, and then that should guide you into who to contact. For example, if the CPU has a hot path on the .NET code that opens TCP connections that is used when the SDK needs to open a TCP connection, then that would lead you to the .NET team. If neither the SDK nor .NET is present on the hot path, then that means the problem is coming from somewhere else.

**Comment by ealsur** [comment]
The perf trace is not against the logic, the CPU is not just consumed by that piece of code, you would need to perform a CPU profile on the machine while your application is running. I am not familiar with what tools are available on Ubuntu to obtain the CPU profile though :( 

There are third party alternatives but I don't know which is better for that environment.

**Comment by Pilchie** [comment]
For .NET Specific tracing, try taking a look at https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace.

However, given that this seems to be an OS change, we may need to look at tracing system events as well.

**Comment by ealsur** [comment]
@QuinnDamerell Is the machine only running this app? Is it a VM? Is it the same number of cores/resources? Is it the same SKU?

**Comment by QuinnDamerell** [comment]
Yup, it's the only app, both VMs are setup the exact same way, I just did a clean setup of both. Both OSs are updated all the way, it's the same VM and the same SKU.

That's the really weird thing, I mean everything is the EXACT same beyond the OS versions. It must be something with the dotnet runtime between the two OSs, but I'm surprised there's something causing such a major difference. 

On Ubuntu 20.04 the server restart, clients, connect, and everything is 100% stable in 10-20 seconds. On Ubuntu 22.04, the system is super under load and struggles to get stable even 5 minutes after the restart.

**Comment by QuinnDamerell** [comment]
I'm using dotnet-trace to capture a trace from both servers. Do you know if there are any specific flags I should pass for the capture or just use the defaults?

**Comment by ealsur** [comment]
> Yup, it's the only app, both VMs are setup the exact same way, I just did a clean setup of both. Both OSs are updated all the way, it's the same VM and the same SKU.
> 
> That's the really weird thing, I mean everything is the EXACT same beyond the OS versions. It must be something with the dotnet runtime between the two OSs, but I'm surprised there's something causing such a major difference.
> 
> On Ubuntu 20.04 the server restart, clients, connect, and everything is 100% stable in 10-20 seconds. On Ubuntu 22.04, the system is super under load and struggles to get stable even 5 minutes after the restart.

Is [Accelerated Network](https://docs.microsoft.com/en-us/azure/virtual-network/accelerated-networking-overview) enabled on both?

**Comment by QuinnDamerell** [comment]
They are digital ocean VMs, CPU optimized 4 core. I'm pretty sure it's not a problem with the VM, because I have 7+ VMs all running the same setup worldwide. None of them had a problem on 20.04, but they all have it now after the update to 22.04.

Digital Ocean also doesn't move around VMs as Azure can between hosts when they are turned off or restarted, so they should be running on the same hardware from the 20.04 -> 22.04 move.

**Comment by QuinnDamerell** [comment]
![image](https://user-images.githubusercontent.com/7854873/200928963-b93b4f7d-524e-4336-aa11-8ff3eea08403.png)

I'm not great at understanding CPU perf traces, but the tool shows one difference that looks bad. 22.04 has a function `Interop+Crypto.CryptoNative_DecodePkcs8PrivateKey` where the other trace doesn't show that at all. 

That's really odd. I do know that Ubuntu 20.04 has OpenSSL 1.1 whereas 22.24 had a big move to OpenSSL 3.0. I wonder if there's an implementation difference that's causing it with that.

**Comment by QuinnDamerell** [comment]
Given all of that, do you guys have any suggestions on which repo I should open the new perf issue bug?

**Comment by Pilchie** [comment]
I've been asking a few people, but it's not ringing any bells for any of the .NET runtime folks I've talked to yet.  Can you try using perfcollect to collect a trace that contains more system information too?

https://learn.microsoft.com/en-us/dotnet/core/diagnostics/trace-perfcollect-lttng

**Comment by QuinnDamerell** [comment]
Yeah, will do. 

Thanks for all of the info and help. I will take my finding and traces to open a bug elsewhere. :)
