### ISSUE TITLE
Pass raw json of patch operations to PatchItemStream

### ISSUE THREAD

**Issue by RuntimeRascal** [Azure/azure-cosmos-dotnet-v3#3560]
**Is your feature request related to a problem? Please describe. **
Perhaps. New dotnet web projects use System.Text.Json wheras Cosmos SDK uses Json.net. If there is an option to bypass the serialization differences a bit by just passing raw json to Cosmos SDK, then some issues can be reduced. Currently I am writing converters that convert our Json into an object with all inferred types since System.Text.Json does not infer types. This prevents the SDK from sending values of `"ValueKind"` to Cosmos.

**Describe the solution you'd like**
I think having an overload of `PatchItemStreamAsync` that accepts a json string or `byte[]` or `stream` rather then the `IReadOnlyList<PatchOperation>` that must be serialized.

**Describe alternatives you've considered**
- Update to use System.Text.Json
- Look for traces of incoming patch ops deserialized with System.Text.Json and throw error rather then proceed with patch.

**Additional context**

**Comment by ealsur** [comment]
Does using `System.Text.Json` as the serializer on the client not work as intended? https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson

**Comment by RuntimeRascal** [comment]
That absolutely does work. Thank you for showing me the way. Apparently, Im not so great at discovery sometimes. haha.

I did notice the example does not allow null value in patches.

**Comment by ealsur** [comment]
@RuntimeRascal not your fault, discoverability of these samples is not fantastic.

You can tinker with the System.Text.Json configs to fit your case, the example was just to demonstrate how to create your own serializer.

Let me know if this solves your issue.

**Comment by RuntimeRascal** [comment]
Yes this does solve my issue. Thank you very much.

FYI
```csharp
        _systemTextJsonSerializer.Serialize( streamPayload, input, input?.GetType() ?? typeof(object), default );
```
Solved the null issues for me.
