### ISSUE TITLE
`GetItemLinqQueryable` doesn't return an exception on item that doesn't exist

### ISSUE THREAD

**Issue by LoyalPotato** [Azure/azure-cosmos-dotnet-v3#3565]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I'm querying an item with the `GetItemLinqQueryable` method. The query makes 3 value comparisons to check if any item exists.
No item exists as I'm returning the item straight away and it exits the try/catch even though I have a catch for a `CosmosException`.

**To Reproduce**

Ids are Guids.

```c#
try
            {
                using (FeedIterator<LearningLifecycleDTO> iterator =
                this._cosmosContainer.GetItemLinqQueryable<FooDTO>()
                .Where(foo => foo.TempId == tempId && foo.MetaType == "Foo" && foo.LinkId == linkId)
                .ToFeedIterator())
                {
                    while (iterator.HasMoreResults)
                    {
                        foreach (var item in await iterator.ReadNextAsync())
                        {
                            return item;
                        }
                    }
                }
            }
            catch (CosmosException ex)
            {
                if (ex.StatusCode == HttpStatusCode.NotFound)
                {
                    throw new NotFoundException($"Could not find foo for link id: {linkId.ToString()}");
                }
            }
```

**Expected behavior**
An exception to be thrown with the NotFound status.

**Actual behavior**
No exception.

**Environment summary**
SDK Version: 3.28.0
OS Version (e.g. Windows, Linux, MacOSX): MacOSX

**Comment by ealsur** [comment]
Queries do not return exceptions when they find no results. It is simply an empty query result. 

The 404 failure happens on ReadItem operations, following the REST API contract.
