### ISSUE TITLE
[QUERY] Hierarchical partition key in Azure Cosmos DB PartitionKeyBuilder is inaccesible and cannot create item using stored procedure

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-cosmos-dotnet-v3#3569]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#32513](https://github.com/Azure/azure-sdk-for-net/issues/32513).

### Library name and version

Microsoft.Azure.Cosmos 3.31.2

### Query/Question

I created container with Hierarchical partition key:
![image](https://user-images.githubusercontent.com/6906373/202169788-ec7dda69-452b-4b48-9d98-465903cf9fe3.png)

On webpage [Hierarchical partition key](https://learn.microsoft.com/en-us/azure/cosmos-db/hierarchical-partition-keys?tabs=net-v3%2Carm-json) is shown that we can create object PartitionKeyBuilder to build this partition key:
```
// Specify the full partition key path when creating the item
PartitionKey partitionKey = new PartitionKeyBuilder()
            .Add(item.TenantId)
            .Add(item.UserId)
            .Build();
```
But this class is inaccesible due to protection level. When we look inside code of Microsoft.Azure.Cosmos this class is internal:
```csharp
#if PREVIEW
    public
#else
    internal
#endif
    sealed class PartitionKeyBuilder
    {
```

Now I'm not able to build Hierarchical partition key. I need it to pass to method : ExecuteStoredProcedureAsync:

```csharp
var myProjectName = "MyProjectName12";
var myGroupName = "MyGroupName289";
var myTeamName = "MyTeamName34";
var pk = new PartitionKey($"/{myProjectName}/{myGroupName}/{myTeamName}");
var result = await container.Scripts.ExecuteStoredProcedureAsync<string>("createToDoItems", pk, args, new StoredProcedureRequestOptions() { EnableScriptLogging = true });
```

In this way PartitionKey is created but inside it has only one Path. 
![image](https://user-images.githubusercontent.com/6906373/202170457-cbeabf4b-5e15-4302-9422-453fa0c24c3b.png)

I can't build PartitionKey using PartitionKeyBuilder. And I can't create item using stored procedure because I get error that:
`Stack trace: Error: {\"Errors\":[\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\"]}`

### Environment

PM> dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

...
Visual Studio Professional 2022 17.4

**Comment by rsanghavi4** [comment]
We are planning to use this [3.31.1-preview](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.31.1-preview). What is the roadmap ahead for this preview version. Would Microsoft continue to provide support for this preview version in future ? I believe it won't be deprecated in future as we are going to rely on this preview version. Please let us know asap. Thanks!

**Comment by rsanghavi4** [comment]
Thanks for your response. Could you please suggest which version we should use for production to support hierarchical partition key and access the partitionKeyBuilder class. The latest stable version doesn't support this at the moment.

**Comment by ealsur** [comment]
@rsanghavi4 the latest stable version (3.35.1) has these APIs as available.

**Comment by rsanghavi4** [comment]
As mentioned in thread above, the PartitionKeyBuilder class is not accessible in latest stable version (3.35.1). Which stable version has this class public and accessible ?

**Comment by ealsur** [comment]
@rsanghavi4 Above reference is for 3.31.2.

In 3.35.1 the PartitionKeyBuilder is public:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a25730a77ab43a8e460ddc292f1a6d8eb193395a/Microsoft.Azure.Cosmos/src/PartitionKeyBuilder.cs#L11-L15
