### ISSUE TITLE
NuGet LicenseFile Info missing

### ISSUE THREAD

**Issue by tinohager** [Azure/azure-cosmos-dotnet-v3#3582]
The `Microsoft.Azure.Cosmos` NuGet Package miss the new `<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>` in the project file.

```
<PropertyGroup>
  <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
</PropertyGroup>

<ItemGroup>
  <None Include="..\LICENSE.txt" Pack="true" PackagePath="LICENSE.txt" />
</ItemGroup>
```

Therefore, the license used is not displayed in NuGet, [Microsoft.Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj)
![image](https://user-images.githubusercontent.com/8215186/203745061-f6e3181e-38a5-4394-a268-10cc18f4ad69.png)

Instead of [Microsoft.Azure.Amqp](https://github.com/Azure/azure-amqp/blob/master/src/Microsoft.Azure.Amqp.csproj)
![image](https://user-images.githubusercontent.com/8215186/203745555-a8ab338f-2223-4133-b45e-bd5ba7904e66.png)

**Comment by ealsur** [comment]
@philipthomas-MSFT Could you take a look at this report and see if this property is required?
