### ISSUE TITLE
Azure Cosmos Monitoring Logs - get QueryText by ActivityId

### ISSUE THREAD

**Issue by robertgm** [Azure/azure-cosmos-dotnet-v3#3584]
In system to logs errors from Web site hosted on Azure I get error:
```
Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: xxxxxx; Reason: (One of the input values is invalid.
ActivityId: xxxxx, Windows/10.0.19041 cosmos-netstandard-sdk/3.18.0, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Windows/10.0.14393 cosmos-netstandard-sdk/3.23.1);
```
This error occured because some value from filters that user entered is used to build select clause and executed on Cosmos DB. And value is wrong. I wanted to check what query was executed on Cosmos.
But I can't get this query.
I try use this Kusto query to find this request:
```
CDBDataPlaneRequests
| project TimeGenerated,  ActivityId, _ResourceId, DatabaseName, CollectionName, StatusCode, OperationName, ClientIpAddress
| where ActivityId  == 'xxxxxxxxxxxxxx'
| limit 100
| order  by TimeGenerated desc
```
And it returns log, but in `CDBDataPlaneRequests` there is no property `QueryText` and I can't look what exactly query was executed. `QueryText` is in  `CDBQueryRuntimeStatistics` but I can't find log by the same `ActivityId`.I have these resources: `CDBControlPlaneRequests, CDBControlPlaneRequests, CDBDataPlaneRequests, CDBPartitionKeyRUConsumption CDBPartitionKeyStatistics, CDBQueryRuntimeStatistics`. Log is only in `CDBDataPlaneRequests`.
How can I get full query text to see which select clause was executed by Cosmos DB?

**Comment by ealsur** [comment]
@robertgm We cannot answer this question on this repository as it is scoped to the SDK library code. You could certainly have your own logs that log the query on an HTTP 400 response failure from the query execution.
Remember that for Windows x64, the query parsing is done locally for cross partition queries for better performance: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/performance-tips-query-sdk?tabs=v3&pivots=programming-language-csharp#use-local-query-plan-generation, in those cases there is no call to the service if the query is malformed.

**Comment by robertgm** [comment]
Ok, thanks for answer. I can close question.
