### ISSUE TITLE
Rename Full Fidelity change feed to All Versions and Deletes

### ISSUE THREAD

**Issue by jcocchi** [Azure/azure-cosmos-dotnet-v3#3588]
Rename API surface area for FFCF to reflect new names everywhere applicable.

Incremental --> LatestVersion (Do not change, cannot mark as deprecated)
FullFidelity --> AllVersionsAndDeletes
**Add LatestVersion which has the same behavior as Incremental**
Also, check with Kushagra and Java SDK team

**Comment by philipthomas-MSFT** [comment]
@jcocchi are we just looking to change **ChangeFeedMode**, **ChangeFeedModeIncremental**, and **ChangeFeedModeFullFidelity** types? What about types like **ChangeFeedPolicy**, **A_IMHeaderValues**, **CompositeIndexUtilizationEntity**? And we can't forget code documentation as well. I just want to make sure we align on the impact of change here.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c8935ac2f864fb829f5d941dda07c74aec86a677/Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedModeIncremental.cs

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e7dddbbc14f9647fb1c1d6e17af6bf14cd347714/Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedModeFullFidelity.cs

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e8986626d8e62a5f14967eadae52db34ca9eb148/Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedMode.cs

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/3c6d747326c893eb17c31645282e536938c563af/Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c8935ac2f864fb829f5d941dda07c74aec86a677/Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedModeIncremental.cs#:~:text=requestMessage.Headers.Add(HttpConstants.HttpHeaders.A_IM%2C%20HttpConstants.A_IMHeaderValues.IncrementalFeed

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/01d56abead81a8d7c75a83ab76bd6289452035de/Microsoft.Azure.Cosmos/src/Query/Core/Metrics/CompositeIndexUtilizationEntity.cs#:~:text=public%20bool%20IndexPlanFullFidelity%20%7B%20get%3B%20%7D

**Comment by jcocchi** [comment]
Discussed offline. The goal is to replace Incremental with LatestVersion and FullFidelity with AllVersionsAndDeletes in all places where it would not be a breaking change for GA APIs. Anything without those words in the name can stay as is.
