### ISSUE TITLE
Data-contracts mocking alignment with Azure Guidelines

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#359]
Existing Cosmos API's leaned towards all virtual or mocking. 

Investigate alignment with Azure mocking guidelines: https://azuresdkspecs.z5.web.core.windows.net/DotNetSpec.html#dotnet-mocking

**Comment by ealsur** [comment]
The only difference I see with our current implementation of Settings is they say no public constructors, but instead use Factory:

>In general, model types should not have public constructors, as instances of the type are typically returned from SDK, as opposed to being constructed by the SDK user, yet mock implementations need to create instances of the model types.

**Comment by j82w** [comment]
Having a factory prevents people from extending the class. The downside of a factory is that it gets really ugly for large number of arguments.

**Comment by ealsur** [comment]
Mocking should still be allowed with the Factory, since the properties are virtual. I agree that it gets ugly with multiple parameters though.
The fact that people cannot extend the class seems to be a desired effect.

**Comment by j82w** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/382
