### ISSUE TITLE
Stream API & Serialization

### ISSUE THREAD

**Issue by RapidDev1** [Azure/azure-cosmos-dotnet-v3#3592]
**Describe the bug**

When using the Stream API, and performing a .Net Object Allocation profile for a process using the GetItemQueryStreamIterator, I see many live object instances created of this class 

Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.FieldNameNode

Where I expected no serialization or deserialization to take place.

I am using the below API method to perform the operation

![image](https://user-images.githubusercontent.com/119487466/204749430-68426294-bb1d-4761-b39a-2923f026508a.png)

**To Reproduce**

Perform a query using the GetItemQueryStreamIterator

**Expected behavior**
No serialization related objects being used

**Actual behavior**
JsonTextNavigator being used

**Environment summary**
SDK Version: 3.31.0
OS Version: Windows 11

**Additional context**
I have also seen the same objects being created using the Typed API before our custom serializer is being called. I do have a *.diagsession from Visual Studio 2022 which I can provide if needed

**Comment by ealsur** [comment]
@neildsh / @jcocchi Could anyone from query take a look at this report?

**Comment by neildsh** [comment]
Hi @RapidDev1, the serialization format used by CosmosDB is not exposed to the customers. It need not be text. Thus, the client sdk would have to transcode from whatever encoding is used on the backend to text. In addition, the CosmosDB v3 .NET sdk is a fat client that has some accumulation (reduce) logic for aggregating the results of cross partition queries. This would also result in the sdk deserializing the stream. I hope this helps.
