### ISSUE TITLE
Cosmos Queryable LINQ to SQL translation for decimal type results precision loss

### ISSUE THREAD

**Issue by AmriHS** [Azure/azure-cosmos-dotnet-v3#3606]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Cosmos Queryable LINQ doesn't properly translate decimal type with long digits. It causes precision loss. Hence, when executing queryable LINQ, no items are returned even though the items are in Cosmos DB container. 

Cosmos SDK allows to write document that has property of decimal type with long digits to container and those items are already written in container and shows the property of decimal type with all digits. Hence, the expectation is that Cosmos Queryable LINQ would translate decimal value with all digits when it presented in LINQ `Where` function. 

Example of decimal with long digits: 
```
decimal d = 104.37644171779141 
```

**To Reproduce**

Document class
```
class TestDocument
{
     public decimal SomeProperty { get; set; }
}
```

Code to execute Cosmos queryable LINQ
```
decimal value = 104.37644171779141;
var linqQueryable = container.GetItemLinqQueryable<TestDocument>(allowSynchronousQueryExecution: false, continuationToken, requestOptions)
                .Where(e => e.SomeProperty == value)
```

**Expected behavior**
It should show all decimal precisions/digits.
```
// Get translated SQL syntax
var queryText = linqQueryable.ToQueryDefinition().QueryText;
// queryText = "SELECT VALUE root FROM root WHERE (root["SomeProperty"] = 104.37644171779141)"
```

**Actual behavior**
It shows decimal value without the last digit.
```
// Get translated SQL syntax
var queryText = linqQueryable.ToQueryDefinition().QueryText;
// queryText = "SELECT VALUE root FROM root WHERE (root["SomeProperty"] = 104.3764417177914)"
```

**Environment summary**
SDK Version: 3.31.0

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by AmriHS** [comment]
This is the Pull Request to address this bug (Still WIP): https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3609

**Comment by adityasa** [comment]
@AmriHS thanks for sending out the PR, will take a look.

**Comment by neildsh** [comment]
I discussed this on a call with @AmriHS. The backend supports only 64 bit precision for numbers, so the SDK cannot support more than 64 bits of precision.
