### ISSUE TITLE
Replication latency in single-region vs multi-region write

### ISSUE THREAD

**Issue by shibin-george** [Azure/azure-cosmos-dotnet-v3#3612]
**This is not a bug-report or a feature-request.**

I am trying to get an estimate of how much is the replication latency in the two scenarios below:

**Scenario 1**:
A Cosmos account `A` with Read regions in `R1`, `R2`, `R3`, `R4`, and a single write region in `R1`.
Say a client (with `ApplicationRegion`=`R4`) issues a write operation. Since there's only one write region in `R1`, write occurs in `R1`, and then, the data replication is done in `R2`, `R3`, `R4`.
Assume the replication latency to be in `T1`.

**Scenario 2**:
Another Cosmos account `B` with both **Read** & **Write** regions in `R1`, `R2`, `R3`, `R4`.
A client (with `ApplicationRegion`=`R4`) issues a write operation (same as above). 
Write occurs in `R4`, and then, the data replication is done in `R1`, `R2`, `R3`.
Assume the replication latency to be in `T2`.

Assume that everything else is same in the accounts `A` and `B` (i.e. databases/collections/RUs provisioned/number of clients per region, etc.).

**Question**:
1. How much different is `T2` from `T1`?
  a. Does the difference stem from the conflict resolution that happens only in scenario 2? (say LWW, which is the default) that happens in scenario 2?
2. Does the difference between `T1` and `T2` depend on the consistency level? What if session consistency is configured on both accounts?

Thanks!

**Comment by ealsur** [comment]
@shibin-george This repository is for issues with the .NET V3 SDK. This question is related to behavior of Azure Cosmos DB's global replication and unrelated to the SDK. Please refer to the global distribution (https://learn.microsoft.com/azure/cosmos-db/global-dist-under-the-hood) and consistency (https://learn.microsoft.com/azure/cosmos-db/consistency-levels) documentation pages, if you have any questions about them, at the bottom you can leave questions/feedback about the page:

![image](https://user-images.githubusercontent.com/1633401/208647623-aba998a6-eecb-4e4b-bb16-59d723c37a44.png)
