### ISSUE TITLE
CosmosStoredProcedure.ExecuteAsync<object[], Stream> response is closed and not readable

### ISSUE THREAD

**Issue by donghexu** [Azure/azure-cosmos-dotnet-v3#362]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I notice now the CosmosStoredProcedure could potentially response Stream as the TOutput, I tried it out and the responsed Stream is closed and not readable. I feel this could be a bug if you continue to support Stream type for TOutput.

**To Reproduce**
Make a stored procedure call with Stream as TOutput, something like this:
CosmosItemResponse<Stream> cosmosItemResponse = await storedProcedure.ExecuteAsync<object[], Stream>(
                partitionId,
                new object[]
                {
                    javaScriptParams1.ToArray(),
                    javaScriptParams2.ToArray(),
                    javaScriptParams3.ToArray()
                }
            );
Then try to read it:
using (StreamReader sr = new StreamReader(cosmosItemResponse.Resource))
            {
                Console.WriteLine(sr.ReadToEnd());
            }
Then it will throw:
System.ArgumentException: 'Stream was not readable.'

**Expected behavior**
The output Stream is not closed and ready to use.

**Actual behavior**
The output Stream is closed.

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos.3.0.0.15-preview
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
@donghexu What was the Sproc script that you were using that has a stream as a result? Could you share a sample to repro?

**Comment by ealsur** [comment]
Got a repro offline, will address this in a new PR

**Comment by j82w** [comment]
@ealsur should this even be supported? If the user wants a stream they should call the stream method.

**Comment by ealsur** [comment]
@j82w There is no stream method currently, that is the problem
