### ISSUE TITLE
[Cosmos Service Upgrade - .NET] Replica Validation - Update Diagnostics to Add Replica Health States

### ISSUE THREAD

**Issue by kundadebdatta** [Azure/azure-cosmos-dotnet-v3#3635]
- Update Diagnostics to Add Replica Health States. This requires changes in both `v3` and `Cosmos.Direct` packages.

**Comment by philipthomas-MSFT** [comment]
Waiting for Direct package merge. PR is out.

**Comment by philipthomas-MSFT** [comment]
Complete.
