### ISSUE TITLE
Fix CosmosClientBuilder.WithConnectionModeGateway documentation

### ISSUE THREAD

**Issue by arthuraugsten** [Azure/azure-cosmos-dotnet-v3#3641]
Hey,

The documentation for `CosmosClientBuilder.WithConnectionModeGateway` is a bit confuse. This one is saying that the parameter `maxConnectionLimit` is the time that the client will wait, however, in the end, it is saying about number of connections, and the value is not the current default value! I've analyzed and this value is used on `HttpMessageHandler.MaxConnectionsPerServer`.

Follow a suggestion for the documentation.
`The number specifies the number of connections which may be executed simultaneously. Default is 50 connections.`

I was not able to create a branch and a PR with this suggestion.

**Comment by ealsur** [comment]
@arthuraugsten Thanks for your feedback, can you fork the repository, create a branch and send a PR from your fork?
