### ISSUE TITLE
[Question] Behavior of CosmosClient when httpClientFactory isn't provided during CosmosClient object creation

### ISSUE THREAD

**Issue by ajay-sainy** [Azure/azure-cosmos-dotnet-v3#3654]
SDK version: 3.31.0
ConnectionMode: Direct

I am creating CosmosClient like this:
```
new CosmosClient (
  accountEndpoint
  authKeyOrResourceToken,
  clientOptions: clientOptions);
```

My clientOptions doesn't provide HttpClientFactory. 

According to [this line](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/2681be80b9674fc8a09f1a7552894ef8741b23e2/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L88) of CosmosHttpClientCore, my cosmosdbClient object will get httpclient created like this:

```
HttpClient httpClient = new HttpClient(httpMessageHandler);
```

Does it mean that if my cosmosClient is singleton, it will run into the well known problem [A Singleton HttpClient does not respect DNS changes](https://github.com/dotnet/runtime/issues/18348)?

**Comment by ealsur** [comment]
Can you clarify exactly what problem in that thread applies to Cosmos DB or what exactly is the known problem (the thread is very long and there are multiple points mentioned)? And if you have experienced it, can you share logs/exceptions?

Cosmos DB uses HTTP and TCP, HTTP is used for Gateway interaction (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/sdk-connection-modes). Gateway maintains one DNS entry for each available region which maps to a cluster of machines that can serve these requests. The DNS entry is not for a single machine. If a machine in the cluster has an issue, the IP is still valid.

In the event of a regional outage, the IP cannot be connected to, this translates to an `HttpRequestException` https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/SdkDesign.md#cross-region-retries, which gets retried and handled. The account endpoints are rediscovered in case new regions were added/removed and the client attempts to connect to the next region.

We have not had any reports of any DNS caching affecting availability based on the service architecture as far as I can recall, and the pattern of having a Singleton client (with a singleton HttpClient) has been there for the past 7+ years.

Please let us know what specific concerns you have and I'll try to clarify.

**Comment by ealsur** [comment]
Tracking investigation through https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3658
