### ISSUE TITLE
Bug in patch "incr" operation when operating on arrays

### ISSUE THREAD

**Issue by d-markey** [Azure/azure-cosmos-dotnet-v3#3659]
**Describe the bug**
Patch operation "incr" targeting a number in an array creates additional entries. For instance, if the array is `[1]`, incrementing by 1 produces `[2, 1]`.

**To Reproduce**
Gist available here: https://gist.github.com/d-markey/bab9f3670024147fd3141932e94de8fa

```csharp
var test = new Test() {
    id = Guid.NewGuid().ToString(),
    label = "Created",
    counter = 3,
    numbers = new int[] {5}
};

var pk = new PartitionKey(test.id);

var created = (await container.CreateItemAsync<Test>(test, pk)).Resource;
dump("Create:", created);

var patched = (await container.PatchItemAsync<Test>(test.id, pk, new[] {
    PatchOperation.Set("/label", "Patched"),
    PatchOperation.Increment("/counter", 11),
    PatchOperation.Increment("/numbers/0", 13),
})).Resource;
dump("Patched:", patched);
```

**Expected behavior**
The array length should not change, only the target item should be incremented as specified.

**Actual behavior**
The sample above produces this output:

```
Create:
   id = 99dabb1d-519d-4668-a762-e9c4d539a6b4
   label = Created
   counter = 3
   numbers = 5
Patched:
   id = 99dabb1d-519d-4668-a762-e9c4d539a6b4
   label = Patched
   counter = 14
   numbers = 18, 5 <-- unexpected, the array should only contain 18
```

**Environment summary**
SDK Version: 3.31.2
Windows 10

**Additional context**
Tried against Cosmos DB Emulator as well as a regular Cosmos DB instance.
Also reproduced by calling the REST APIs directly, so the problem's probably not in the SDK but rather in Cosmos DB itself.
The problem also exists when using the patch operation in a transactional batch.

**Comment by ealsur** [comment]
> Also reproduced by calling the REST APIs directly, so the problem's probably not in the SDK but rather in Cosmos DB itself.

Please create a service support ticket, there is nothing that can be done on the SDK to fix this, right?

**Comment by d-markey** [comment]
Agreed but I couldn't find a place for opening a ticket against Cosmos DB. I'm on a free plan and  support options seem limited. I've discovered the problem by "accident" when writing unit tests for a Dart CosmosDB connector I'm working on, so I don't really need a fix. I'll just disable that test and will mention the problem so users can avoid this kind of scenario, but if you point me to the right place I'll report the ticket.

**Comment by ealsur** [comment]
@d-markey If you are on the free plan then yes, support options are limited. I understand you are not directly blocked, but it would be good to get this investigated. Let me see if I can use this Issue to report it.

**Comment by d-markey** [comment]
@ealsur yes, now it's been unearthed, it's be a shame to let it buried!

**Comment by ealsur** [comment]
This was identified and fixed on the service side

**Comment by d-markey** [comment]
Great, thanks!
