### ISSUE TITLE
Change Feed with StartFromTime configuration does not work

### ISSUE THREAD

**Issue by gpinolo** [Azure/azure-cosmos-dotnet-v3#3661]
**Describe the bug**
When specify the _StartFromTime_ for _CosmosDBTrigger_, the change feed is not triggered

**To Reproduce**
Configure a function as shown below:

```
	public async Task run(
            [CosmosDBTrigger("databaseName", "containerName",
                Connection = "COSMOS_CONN",
                LeaseContainerName = "leaseContainer",
                StartFromTime = "2021-02-16T14:19:29Z",
                MaxItemsPerInvocation = 100,
            )] IReadOnlyList<JObject> changeFeedList,
            ILogger log)  
        {
           log.LogInformation("item in changeFeedlist " + changeFeedList.Count);
        }
		
```	

**Expected behavior**
After cleaning the _leaseContainer_ and then running the function, when a _document_ is saved or updated in _containerName_ the number of inserted/modified document are logged 

**Actual behavior**
Nothing is logged

**Environment summary**
SDK Version: 3.1.416
OS Version: Windows 10 Pro

**Additional context**
The DateTimeKind of _time_ is _Local_, so the [ChangeFeedStartFromTime](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e383d83946bf7c9eddeb161cd577b18609e2ac19/Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedStartFromTime.cs#L26) fails to start

**Comment by ealsur** [comment]
For Functions related issues, please use the Extensions repository: https://github.com/Azure/azure-webjobs-sdk-extensions/issues

See https://github.com/Azure/azure-webjobs-sdk-extensions/issues/809 and https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3559

The new SDK will be released this week and can be used in Functions.
