### ISSUE TITLE
High unmanaged memory usage with Change Feed Processor

### ISSUE THREAD

**Issue by shibin-george** [Azure/azure-cosmos-dotnet-v3#3662]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I use the change-feed processor in my service, and I observed that the memory usage drastically increases when Change feed processor is enabled.
Here's the comparison between two instances, one with Change fed processor running, and the other without (all else same).

With Change feed, the unmanaged memory usage is ~600MB
![image](https://user-images.githubusercontent.com/5213412/214163286-58032381-ae6e-46c3-806b-2efdc9e72f0c.png)

Without Change-feed, the unmanaged memory usage is ~180MB
![image](https://user-images.githubusercontent.com/5213412/214163443-4bba215a-f1bf-4e1c-8c50-da073058f8bb.png)

Any suggestions on optimizations that one can do to reduce this memory usage?

**Expected behavior**
I'm not sure about the expected behaviour since no one has reported the expected memory usage when Change feed is enabled. Is such a stark difference expected?

**Environment summary**
SDK Version: 3.29.0
OS Version: Observed in both Linux and Windows (the snapshot above is from Windows machine)

**Comment by ealsur** [comment]
What is unmanaged memory and how do you know the unmanaged memory is coming off the Change Feed Processor? There is no unmanaged code being used on the Change Feed Processor (the source code is in this repository, it is all managed code).

Change Feed Processor is meant to consume resources, and the bigger the container it is monitoring, the more resources it could consume. The design is explained on https://docs.microsoft.com/en-us/azure/cosmos-db/sql/change-feed-processor, there is one Task for each lease. You can distribute this across multiple machines (Deployment Units) to parallelize resource utilization.

Please attach specific evidence that shows that that counter is actually related to Change Feed Processor, this graphic does not really show where that is coming from.
