### ISSUE TITLE
ChangeFeedObserverContextCore CheckpointAsync writes LeaseLostException logs for the expected behavior with Reason "Lease was lost due to load balancing and will be processed by another instance"

### ISSUE THREAD

**Issue by Ubloobok** [Azure/azure-cosmos-dotnet-v3#3669]
**Describe the bug**
I am using CosmosDB Trigger in Azure Function to process data changes, configuration is quite default:
```
[FunctionName(nameof(ChangesProcessor))]
public async Task ChangesProcessor([CosmosDBTrigger(
    "DatabaseName",
    "CollectionName",
    Connection = "ConnectionString",
    LeaseContainerName = "leaseCollection",
    CreateLeaseContainerIfNotExists = true,
    StartFromBeginning = true)]
    IReadOnlyList<Document> changeDocuments, 
    ILogger log)
{
    ...
}
```

Code works well, events are processed, but App Insights contains a lot of exceptions with error LeaseLostException:
* **Message**: Response status code does not indicate success: PreconditionFailed (412); Substatus: 0; ActivityId: ; Reason: (Lease was lost due to load balancing and will be processed by another instance); The lease was lost.    
* **Exception type**: Microsoft.Azure.Cosmos.ChangeFeed.Exceptions.LeaseLostException
* **Failed method**: Microsoft.Azure.Cosmos.ChangeFeed.LeaseManagement.DocumentServiceLeaseCheckpointerCore+<>c__DisplayClass3_0.<CheckpointAsync>b__0

Search over the internet has shown that is the expected behavior, when lease was lost due to load balancing and will be processed by another instance.
Source of exception: [ChangeFeedObserverContextCore, method CheckpointAsync](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/releases/3.31.0/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Observers/ChangeFeedObserverContextCore.cs)

A very similar exception is produced by [DocumentServiceLeaseManagerCosmos, method RenewAsync](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/releases/3.31.0/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManagerCosmos.cs)

Problem that we have alerts for raise of exceptions in logs, and they trigger when ChangeFeedObserverContextCore writes many LeaseLostException. We can exclude them from the alert's query, but that complicates a query, and anyway it spoils our logs with false-positive exceptions.

**Expected behavior**
I would expect to have no exceptions in logs if processing goes well, and we don't need to react or fix something.
At least from my perspective, that would be in accordance with the best SRE practices.

Not sure about the possible solution at this moment, not very familiar with this package.
Could you help to figure out it please?

As an option, provide a global handler for these exceptions where we can log with lower level.

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos.Client, 3.31.0.0
Azure Function Runtime version: ~4.

**Comment by ealsur** [comment]
@Ubloobok Please use the Functions repo to report Functions related Issues https://github.com/Azure/azure-webjobs-sdk-extensions/issues

This has already been addressed to reduce the noisy-ness of the logs https://github.com/Azure/azure-webjobs-sdk-extensions/pull/813

The log itself is correct though, it won't go away under the same circumstances, it was just changed the level of the log.

**Comment by ealsur** [comment]
Should be included in the next Functions release in 1-2 weeks.

**Comment by Ubloobok** [comment]
@ealsur thanks a lot for a quick answer! Will be waiting for the next release.
