### ISSUE TITLE
Default DateTime serialize format creates issue when doing DateTime comparisons in query

### ISSUE THREAD

**Issue by Valyreon** [Azure/azure-cosmos-dotnet-v3#3677]
**Describe the bug**
When cosmos document is saved, timestamps with zero milliseconds are serialized like this: 
![image](https://user-images.githubusercontent.com/18052197/216028839-12403473-0e63-41a3-826b-24fff7e8acec.png)
Notice that the millisecond zeroes are not in the timestamp. This creates an issue when doing query comparison with a timestamp which includes milliseconds. For example:
![image](https://user-images.githubusercontent.com/18052197/216029207-9f2eb561-7855-4208-8079-fef9d7bd8db2.png)
Obviously the result is correct if we are comparing strings, but not timestamps.

**To Reproduce**

1. Create a document which includes a DateTime property and make sure that property has milliseconds set to 0.
2. Run a query on that container doing a comparison with timestamp which has all DateTime parts the same except milliseconds.

**Expected behavior**
Is for cosmos DateTime format to include trailing millisecond zeroes, or at least one decimal place, that way the comparison will be correct.

**Actual behavior**
When serializing documents, cosmos cuts off milliseconds if they are 0, and as a result query results are wrong for certain parameters.

**Environment summary**
SDK Version: 3.31.2
OS Version (e.g. Windows, Linux, MacOSX): Windows 10

**Additional context**
I have tried to set JsonConverter attribute, to find a way for a custom serializer but nothing worked.

**Comment by ealsur** [comment]
Please refer to the public documentation about storing date times: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/working-with-dates#storing-datetimes

**Comment by Valyreon** [comment]
I have seen the documentation and it doesn't change the fact that Cosmos seems to store documents with UTC DateTime in the format "yyyy-MM-ddTHH:mm:ss.**FFFFFFF**Z" and not "yyyy-MM-ddTHH:mm:ss.**fffffff**Z" which makes the problem above possible.

![image](https://user-images.githubusercontent.com/18052197/216141964-3e51c533-3546-477f-8e90-ecf5632b8e91.png)

**Comment by ealsur** [comment]
@Valyreon The database does not store datetimes, it stores strings, JSON does not have DateTime objects, what you are seeing there is a string representation.

How your DateTime object is serialized into a JSON string value depends entirely on two things:

1. The serialization engine: In this case, it's Newtonsoft.Json unless you customize your Serializer for other (like System.Text.Json)
2. How that serialization engine converts a DateTime to a JSON string

The SDK in itself won't do anything other than convert the object through the serialization engine.

If you are using all the defaults, then it boils down to how Newtonsoft.Json converts DateTime objects, which you can validate through for example `JsonConvert`. The default behavior is not set by the SDK.

**Comment by Valyreon** [comment]
Yeah, I just realized that and I created a custom serializer which I used in CosmosClientOptions and set the JsonConvert.DefaultSettings to return serializer settings with my custom converter.

It's just that I would have expected this behavior as default for CosmosDB. Thank for your help nevertheless.

**Comment by ealsur** [comment]
The default behavior is not from Cosmos DB, Cosmos DB as a service just receives JSON documents.

Each language (C#, Java, Python, Node, Go, etc) has its own way to serialize data into JSON. Each language might have some defaults, but the serialization technology that goes from object to JSON is not owned by the Cosmos DB team, it's generic in the language.

For .NET, we use Newtonsoft.Json, which is widely used across .NET applications. We cannot change whatever default that technology has without introducing a breaking change.

Java uses Jackson, same scenario.

What we offer are ways to customize it, just like you could use custom Converters too (Newtonsoft.Json supports that).
