### ISSUE TITLE
PopulateIndexMetrics return unsupported index reccomendations

### ISSUE THREAD

**Issue by IsaacBoy** [Azure/azure-cosmos-dotnet-v3#3678]
**Describe the bug**
PopulateIndexMetrics returns Potential Composite Indexes with missing indexes where the path includes an array, which is not a supported composite index. The issue is also described here: https://stackoverflow.com/questions/75203887/cosmosdbs-index-recommendations-that-include-arrays-seem-to-be-in-an-unsupporte

**Expected behavior**
PopulateIndexMetrics would only return potential indexes that can actually be applied

**Environment summary**
SDK Version: v3.31.2

**Comment by ealsur** [comment]
@neildsh / @jcocchi Could anyone help understand if this is needs to be addressed?

**Comment by jcocchi** [comment]
@leminh98 Is this related to your Index Advisor work?
