### ISSUE TITLE
Latest release does not fix GetItemLinqQueryable issue [Still broken 3/2/23]

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cosmos-dotnet-v3#3697]
**Describe the bug**

#3406 does not completely address #3207, with respect to enum handling in LINQ queries; it will still use the enum's integer value, discarding the serializer preference set on the Cosmos context;

i.e.

```C#
enum MyEnum
{
  ValueA = 0
}
```
When querying

```C#
query.Where(c => c.Item == MyEnum.ValueA)
```

will translate to

```sql
WHERE root["Item"] = 0
-- Should be WHERE root["Item"] == "ValueA", if JsonStringEnumConverter is configured on JSON Serializer settings
```

**Comment by jackbond** [comment]
I'll go ahead and add that the 3.32.0 release also does not properly handle the property name, i.e. if the converter specifies camel casing, the where clause should be

WHERE root["item"] = 0

and not

WHERE root["Item"] = 0

And to be super specific, in the case of System.Text.Json (which is what everyone attempting to use custom converters is doing), if the property is decorated with the System.Text.Json.Serialization.JsonPropertyNameAttribute, that's what should be showing up in the sql query.

And to state the obvious, all of these cases should be covered in unit tests.

**Comment by onionhammer** [comment]
Actually, it's worse than that. 

Now there's no workaround for enums; before 3.32.0, you used to be able to decorate enums with the legacy Newtonsoft property 

```C#
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public UserStatus Status { get; set; } = UserStatus.Active;

```

Now that doesn't even work

**Comment by jackbond** [comment]
@onionhammer Are you using System.Text.Json in your custom serializer? If so, I'd try decorating the property with

`[System.Text.Json.Serialization.JsonConverterAttribute(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))] `

(full namespaces included for clarity)

What's literally bonkers about this is, we're using the custom serializer 100% as intended, and it's FUNDAMENTALLY BROKEN. And it has been FUNDAMENTALLY BROKEN for numerous releases. Do the people coding this not realize how their code is intended to be used? Both inexplicable and unforgiveable. Where's the testing? Where are the unit tests? Where's QA? Where's the PM? Where's the accountability?

**Comment by onionhammer** [comment]
> @onionhammer Are you using System.Text.Json in your custom serializer? If so, I'd try decorating the property with
> 
> `[System.Text.Json.Serialization.JsonConverterAttribute(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))] `
> 
> (full namespaces included for clarity)
> 
> What's literally bonkers about this is, we're using the custom serializer 100% as intended, and it's FUNDAMENTALLY BROKEN. And it has been FUNDAMENTALLY BROKEN for numerous releases. Do the people coding this not realize how their code is intended to be used? Both inexplicable and unforgiveable. Where's the testing? Where are the unit tests? Where's QA? Where's the PM? Where's the accountability?

Yes, I had tried that. No effect.

**Comment by onionhammer** [comment]
It looks as if there is a regression in here somewhere

I'm now seeing this exception ( https://github.com/Azure/azure-cosmos-dotnet-v3/compare/167db87...8a537ce ) since this change 

![image](https://user-images.githubusercontent.com/969938/219493093-9122b5c1-1af5-4c2e-badb-a78f72143688.png)

I'm using Hotchocolate GraphQL which applies filters using an expression visitor, but the resulting expression tree in 3.31.2 translated fine.

**Comment by onionhammer** [comment]
I dug into it further, it looks like the ExpressionToSql.cs is handling enums-as-strings in SOME cases but not others;

For example

```C#
        // PASSES
        [TestMethod]
        public void EnumIsPreservedAsINTest()
        {
            // Arrange
            CosmosLinqSerializerOptions options = new()
            {
                CustomCosmosSerializer = new CustomJsonSerializer()
            };

            // Act
            TestEnum[] values = new[] { TestEnum.One, TestEnum.Two };
            Expression<Func<EnumContainerDocument, bool>> expr = a => values.Contains(a.Value);
            
            string sql = SqlTranslator.TranslateExpression(expr.Body, options);

            // Assert
            Assert.AreEqual("(a[\"Value\"] IN (\"One\", \"Two\"))", sql);
        }

        // FAILS
        [TestMethod]
        public void EnumIsPreservedAsEQUALSTest()
        {
            // Arrange
            CosmosLinqSerializerOptions options = new()
            {
                CustomCosmosSerializer = new CustomJsonSerializer()
            };

            // Act
            TestEnum statusValue = TestEnum.One;
            Expression<Func<EnumContainerDocument, bool>> expr = a => a.Value == statusValue;

            string sql = SqlTranslator.TranslateExpression(expr.Body, options);

            // Assert
            Assert.AreEqual("(a[\"Value\"] = \"One\")", sql);
        }

```

**Comment by onionhammer** [comment]
@ealsur  It is also causing an invalid cast exception here

![image](https://user-images.githubusercontent.com/969938/220752540-c196265a-ab4d-4039-9ef6-2bba52cafc56.png)

**Comment by onionhammer** [comment]
The bug appears to be that the new code changes the constant to a string, but the old code is still expecting it to be a SqlNumberLiteral.

![image](https://user-images.githubusercontent.com/969938/220761252-2cb3764e-a986-48da-88d7-f28598133598.png)

**Comment by onionhammer** [comment]
@ealsur @aavasthy Added a pull request which demonstrates regression

**Comment by ealsur** [comment]
Tagging @leminh98 for LINQ ownership

**Comment by onionhammer** [comment]
@ealsur @leminh98 this is still broken after merging latest from master

```
  Failed EnumIsPreservedAsEQUALSTest [143 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<(a["Value"] = "One")>. Actual:<(a["Value"] = 0)>.
  Stack Trace:
     at Microsoft.Azure.Cosmos.Linq.CosmosLinqJsonConverterTests.EnumIsPreservedAsEQUALSTest() in C:\Development\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Tests\Linq\CosmosLinqJsonConverterTests.cs:line 72
````

**Comment by onionhammer** [comment]
Bumping... This is still an unfixed regression... @ealsur @khdang @adityasa @sboshra @kirankumarkolli

**Comment by leminh98** [comment]
We are actively investigating this issue from our side. As a temporary mitigation, we will be reverting the PR that introduces this regression and put out a more wholistic fix that addresses the original issue

**Comment by kalatchev** [comment]
@leminh98 Any news about this bug?

**Comment by leminh98** [comment]
A new SDK release containing the hot fix to revert the code change that introduces this regression has been released. I am still working on another fix for the original issue.

**Comment by onionhammer** [comment]
@leminh98 Do you have a PR/branch for this?

**Comment by leminh98** [comment]
I haven't been able to get around to this yet. I'm hoping I will be able to tackle it in May

**Comment by Rasmus715** [comment]
Bump!

**Comment by Arcalise08** [comment]
May was a few months ago. Any update?

**Comment by Maya-Painter** [comment]
Hi all, we've merged what we hope will be a solution to this issue by allowing the custom serializer to be used for LINQ translations. This also unblocks having System.Text.Json attributes applied in LINQ queries.

We plan to release this as part of the next preview package, but I also wanted to take this time to confirm these changes meet your needs before finalizing them as part of our public API.  If you try the changes out, please follow up in the thread if this update addresses your concerns. If it doesn't, please let us know why.

To use your own custom serializer for LINQ translations you must implement `CosmosLinqSerializer` and set it as a custom serializer on the `CosmosClient`. There is a sample of this for serialization with System.Text.Json in CosmosLinqSerializer.cs.
