### ISSUE TITLE
Performance: ToStringWithData and timeouts

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#3703]
Reference report: https://github.com/Azure/azure-cosmos-dotnet-v3/discussions/3690

On [GoneAndRetryWithRequestRetryPolicy](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/msdata/direct/Microsoft.Azure.Cosmos/src/direct/GoneAndRetryWithRequestRetryPolicy.cs) we have a lot of `DefaultTrace.TraceWarning/TraceCritical` that materialize strings that are not used if the customer has no Trace Listener.

For example:

```
DefaultTrace.TraceWarning(
                "GoneAndRetryWithRequestRetryPolicy Received exception, will retry, attempt: {0}, regionRerouteAttempt: {1}, backoffTime: {2}, Timeout: {3}, Exception: {4}",
                this.attemptCount,
                this.regionRerouteAttemptCount,
                backoffTime,
                timeout,
                exception?.ToStringWithData() ?? response?.StatusCode.ToString());
```

Normally, if there are no Trace Listener, the `ToString()` method of the parameters is not called but this line is eagerly calling `ToStringWithData()` so it materializes the string.

One potential solution is to have a struct like:

```
struct ErrorOrResponse
{
      public ErrorOrResponse(Exception? ex, int? statusCode)
      {....}
      public string ToString() => exception?.ToStringWithData() ?? response?.StatusCode.ToString();  
}
```

And then use it like: 

```
DefaultTrace.TraceWarning(
                "GoneAndRetryWithRequestRetryPolicy Received exception, will retry, attempt: {0}, regionRerouteAttempt: {1}, backoffTime: {2}, Timeout: {3}, Exception: {4}",
                this.attemptCount,
                this.regionRerouteAttemptCount,
                backoffTime,
                timeout,
                ErrorOrResponse(exception, response?.StatusCode));
```

Which would avoid the materialization and call ToString only when there is a Trace Listener enabled.

**Comment by philipthomas-MSFT** [comment]
Waiting for Kiran's PR approval.

**Comment by iainx** [comment]
This has been merged
