### ISSUE TITLE
FFCF: Add Feature Flag for Archival Tree Caching

### ISSUE THREAD

**Issue by philipthomas-MSFT** [Azure/azure-cosmos-dotnet-v3#3711]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bartelink** [comment]
People watch this public repo! Taking the time to write a proper overview and/or remove boilerplate is worth it ;)

**Comment by philipthomas-MSFT** [comment]
Break up PR

**Comment by philipthomas-MSFT** [comment]
Closed and consolidated into 1 board item #3681 

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3681
