### ISSUE TITLE
Documentation: Update best practices and performance guide for DNS cache

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#3723]
Reference Issue: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3658

Reference articles:

* https://docs.microsoft.com/en-us/azure/cosmos-db/sql/best-practice-dotnet

Update the reference articles to include the way to set the DNS PooledConnectionLifetime.

**Comment by philipthomas-MSFT** [comment]
send PR
