### ISSUE TITLE
Environment.CurrentDirectory on Azure Functions

### ISSUE THREAD

**Issue by PingPongSet** [Azure/azure-cosmos-dotnet-v3#374]
Does this code example works on Azure? Because it doesn't work for me: 
`Environment.CurrentDirectory`

 private static IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(Environment.CurrentDirectory)
                .AddJsonFile("AppSettings.json", optional: true, reloadOnChange: true)
                .Build();

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/Startup.cs

**Comment by ealsur** [comment]
@PingPongSet Please see the code change in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/383, that will make it work when deployed in Azure.

You just need to specify the settings (EndPointUrl and AuthorizationKey) as Application Settings in your Azure Function.
