### ISSUE TITLE
Option to increase/bypass limits in the TransactionalBatch operation 

### ISSUE THREAD

**Issue by aaronzhongg** [Azure/azure-cosmos-dotnet-v3#3745]
**Is your feature request related to a problem? Please describe.**
We're experiencing a scenario where there is either >100 items in the batch to be upserted or >2MB. 

**Describe the solution you'd like**
These limits are described to ensure predictability and to meet SLAs, but for the scenarios in which I need to do the larger batch operation - I'd like to bypass the limits and accept the cost rather than doing one of the alternatives below.

**Describe alternatives you've considered**
- Used a stored proc https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1057
- Split batch/use bulk. This is less than ideal because we want atomicity https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1057 https://stackoverflow.com/questions/75181418/how-to-store-more-than-100-records-using-cosmos-batch-from-azure-cosmos-db-using

**Additional context**

**Comment by ealsur** [comment]
@aaronzhongg Thanks for your feedback, but this is a Service limit. SDKs cannot increase over the service define limits as they are enforced by the service -> https://learn.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-request-limits

There is no change that can be done from the client that can affect the service limit.

Please raise your Service request or provide service feedback: https://feedback.azure.com/d365community/forum/3002b3be-0d25-ec11-b6e6-000d3a4f0858
