### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-cosmos-dotnet-v3#3766]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#34957](https://github.com/Azure/azure-sdk-for-net/issues/34957).

## Details

`Explore the client APIs` button results in 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba68873-71aa-9f3a-f558-5b1a81296560
* Version Independent ID: fe6ec9de-d30e-f8f5-d86e-49af8f7e8fc1
* Content: [Azure Cosmos DB libraries for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/cosmosdb?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/cosmosdb.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/cosmosdb.md)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ealsur** [comment]
@jsquire thanks for the report but these repositories are not for documentation. These are for the actual SDK libraries. No code change in this repo can alter the content of the articles.

For issues related to a doc, at the bottom of the doc, there is a link to provide feedback for the page, which creates a GitHub issue on the repo where the docs exists and tags the author for the fix. Normally the repo is https://github.com/MicrosoftDocs/azure-docs

**Comment by ealsur** [comment]
@jsquire the document with the bad link is however on the Azure SDK repo -> https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/latest/cosmosdb.md

Why does this issue not belong there?

**Comment by jsquire** [comment]
That repository does not accept issues, as the majority of content is automatically generated and pushed from the Azure SDK repositories.  That appears to be a non-generated document that would need to be updated by the Cosmos SDK owners.    There are no MS Docs content authors responsible for that repository.

**Comment by jsquire** [comment]
Thanks.  My thoughts exactly.  I was going to just make the update, but I wasn't sure where to point things.   I'll get that merged in.
