### ISSUE TITLE
400 from bad record get corrupts client with used concurrently 

### ISSUE THREAD

**Issue by davidbergso** [Azure/azure-cosmos-dotnet-v3#3772]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When using ReadItemAsync on the container and getting a 400 due to a bad id (this was created by adding a record with an id containing a "/").
If the same cosmos client is used to make another request on the same container but with a valid row id, this get request also throws a  400.
If the two calls are made sequentially the second one succeeds as expected.
If we create two separate clients and call them both async concurrently the second call also succeeds as expected.

**To Reproduce**
Create a row with a invalid id field contain a "/".
When using ReadItemAsync on the container and getting a 400 due to a bad id (this was created by adding a record with an id containing a "/").
If the same cosmos client is used to make another request on the same container but with a valid row id, this get request also throws a  400.
If the two calls are made sequentially the second one succeeds as expected.
If we create two separate clients and call them both async concurrently the second call also succeeds as expected.

**Expected behavior**
Concurrent call for a valid row should not return 400 (not impacted by previous bad call).

**Actual behavior**
Second call throws 400.

**Environment summary**
SDK Version: 3.32.1
OS Version Windows 11

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
Please attach the complete exceptions (ToString()) for both failures and a way for us to reproduce.
