### ISSUE TITLE
Handle Json ExtensionData in sql translation visitor

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cosmos-dotnet-v3#3777]
**Describe the bug**
Given an object like this:

```C#
class MyEntity
{
    public string MyTypedProperty { get; set; }

    [JsonExtensionData]
    public Dictionary<string, System.Text.Json.JsonElement>? ExtensionData { get; set; }
}
```

Querying against an entity with extensiondata is not possible within a LINQ expression

```
{l => (Convert(l.ExtensionData.get_Item("MyTest"), Object) == Convert(100, Object))}
```

Should convert to:

```
WHERE root["MyTest"] == 100
```

Instead converts to 

```
WHERE root["ExtensionData"]["MyTest"] == 100
```

The underlying entity in Cosmos will serialize like this;

```json
{
    "MyTest": 100
}
```

So it is impossible to query for the "MyTest" field without dropping down to writing raw QueryDefinitions, in which case you do not have the benefit of strongly-typed expressions for the rest of your query

**Comment by onionhammer** [comment]
Workaround: have your type extend `IReadOnlyDictionary<>`, however then you would have to provide your own custom JSON serialization/deserialization for this type in order to still serialize the additional (non-extension data) properties

**Comment by onionhammer** [comment]
Note: I would be happy to fix this, but I already have 3 open pull requests on this repository that have not been looked at. Is it worth my time to try to contribute?

**Comment by neildsh** [comment]
Hello @onionhammer my apologies that the ball was dropped on your other PRs. I will ping the people who were reviewing those PRs, and we will try to get them merged. We can take this particular issue forward once the other PRs have been resolved. Please note that the other PRs will likely not be merged before next week. Thanks.

**Comment by onionhammer** [comment]
@neildsh Any progress on this front? Again, I would definitely be willing to take a crack at this if it means getting it done sooner, but this PR approval process is pretty arduous.

**Comment by adityasa** [comment]
Hey @onionhammer, I am taking a look at this item. I have looked and approved 2 of your other prs.

**Comment by onionhammer** [comment]
@adityasa ok, let me know if  you want any help/tests written

**Comment by adityasa** [comment]
@onionhammer are you talking about Newtonsoft's JsonExtensionData attribute or System.Text.Json.Serialization [https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonextensiondataattribute?view=net-7.0]?

**Comment by adityasa** [comment]
@onionhammer if you are open to making this change, we will be happy to review & approve it. Let me know.

**Comment by onionhammer** [comment]
> @onionhammer are you talking about Newtonsoft's JsonExtensionData attribute or System.Text.Json.Serialization.JsonExtensiondata?

Both should be handled

**Comment by adityasa** [comment]
@onionhammer fyi test below baselines current behavior which shows that Newtonsoft property is already honored:
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3830

**Comment by onionhammer** [comment]
@adityasa so could the code just not ignore the STJ attribute? Would that be the change?

**Comment by adityasa** [comment]
@onionhammer, I am not sure if it's that that straightforward. The sdk uses Newtonsoft.JSON for serialization/deserialization between client and the backend. Newtonsoft library doesn't understand/honor STJ attributes. As a result, this logic needs to be custom implemented on top of existing logic, with due back-compat considerations.

**Comment by onionhammer** [comment]
@adityasa OK I misunderstood what you meant previously. The functionality proposed in this issue doesnt work for either STJ or Newtonsoft attributes - right? I'm not proposing any changes to the way serialization of objects is done, only the behavior of generating cosmos SQL from LINQ.

**Comment by onionhammer** [comment]
@adityasa After looking into this, supporting this is trivial - just a slight modification to `GetMemberName` and `VisitMemberAccess` should be needed.

Supporting STJ is still necessary, but support could be split into a separate PR.

**Comment by onionhammer** [comment]
And then there were 4 (open PRs)
