### ISSUE TITLE
Lease token was taken over by owner exception

### ISSUE THREAD

**Issue by davidtimovski** [Azure/azure-cosmos-dotnet-v3#3779]
Some of our change feed processors are stuck and we're seeing some `OperationCanceledException` as well as these types of `CosmosException`s in the logs:

`Response status code does not indicate success: PreconditionFailed (412); Substatus: 0; ActivityId: ; Reason: (796 lease token was taken over by owner something-6c082e98-54b1-4fe9-9486-fc51ce2be403`

What does it mean for a lease token to be taken by another owner? I was under the impression that a single lease is owned by a single compute instance.
The change feed processors also seem to start running again from time to time and then halt again seemingly randomly.

Our configuration involves:

1. A single monitored container
2. Multiple change feed processors doing different things
3. All of them use the same lease configuration
4. Multiple instances of the processors on multiple hosts where every instance name is postfixed by a guid so it has a unique name

**Comment by ealsur** [comment]
The exception means what the Message says, the lease was rebalanced to another host.

Please see https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-processor?tabs=dotnet

Leases on a steady state are maintained by a single host but there is a period of rebalancing. Check the dynamic scaling section of the article. 

When CFP starts, it will do rebalancing until it reaches a steady point where the leases are evenly distributed. If you increase or decrease instances, rebalancing will occur too.

**Comment by ealsur** [comment]
For `OperationCanceledException` see https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-dotnet-sdk-request-timeout?tabs=cpu-new, this often means you are experiencing network timeouts. Check your resources (CPU, SNAT ports) when you see this issue.

**Comment by ealsur** [comment]
Then you should look into the LIfe Cycle Notifications for `NewChangeFeedProcessor` to understand why it is not making progress or what could be the issue.

Leases are distributed across instances of the same Deployment Unit, a [Deployment Unit](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-processor?tabs=dotnet#deployment-unit) is defined by 1 or more instances of a CFP with the same `processorName`, Monitored, and Lease containers.

If you have a cluster (`A`) of machines where multiple CFP exists, assuming each CFP has a different `processorName` (or Monitored or Lease container) then they are completely independent one from the other. If `NewChangeFeedProcessor` was a new CFP deployed on cluster `A` (but not in `B`) you need to look into what is going on in `NewChangeFeedProcessor` which I guess is different from your previously existing CFP instances?

**Comment by ealsur** [comment]
When rebalancing happens it means another machine took the leases and that machine is processing them. Either the machine is facing some failure condition that it is consistently failing to process or there is something else blocking the progress. Life Cycle notifications will tell you who acquired the leases, when, and if they are running into any processing failures, which are they. You can see who is owning the leases either with the [Estimator](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-use-change-feed-estimator#as-an-on-demand-detailed-estimation) or by inspecting the leases (the `Owner` property matches the `InstanceName` of the machine owning it, assuming each machine has a unique name, if 2 machines have the same InstanceName, then that definetively is a bad configuration).

**Comment by davidtimovski** [comment]
We're still in the process of investigating this. We have some manual checkpointing logic. I've been responsible for migrating this code to Cosmos DB v3 SDK and I might have made mistakes there that cause this issue. I need some clarity on certain differences in the API for creating change feed processors.

In v2 there were `ChangeFeedObserver`s which had `OpenAsync` and `CloseAsync` methods. The docs for these methods just say "this is called when the observer is opened/closed" but don't really explain what that entails. Is there anything in v3 is equivalent to them?

**Comment by bartelink** [comment]
I believe you are looking for `WithLeaseAcquireNotification` and `WithLeaseReleaseNotification`, see https://github.com/jet/propulsion/blob/1d862e907502d727f5508b401deb85c6c60ef1e7/src/Propulsion.CosmosStore/ChangeFeedProcessor.fs#L142-L143 (I ported similar logic with manual checkpointing - the repo had a V2 SDK impl you could compare and contrast with a bit of digging)

**Comment by davidtimovski** [comment]
They seem similar but I don't believe they're equivalent. They look like they've been added for logging, which is how you are using them.

Migrating our code kind of requires us to have something equivalent or we'll have to change it. Our code for manual checkpointing does batching - it collects changes in the handle method and starts what we call a periodic checkpointer (which checkpoints at certain intervals) in `OpenAsync` (cancels this checkpointer in `CloseAsync`).

I don't think doing the same with `OnLeaseAcquire`/`OnLeaseRelease` will result in the same behavior. It appears that when leases are stolen I end up cancelling our periodic checkpointer which is most likely the source of our `OperationCanceledException`s.

**Comment by bartelink** [comment]
You may well be right about them not mapping directly; for a start, the callbacks are not `Async` AFAICT (and are hence not a blocking thing as part of a state transition as they once were; would definitely not suggest attempting to do long running work even if it happened to seem to work in the current impl).

Those callbacks were re-added to the API surface relatively late; Now you mention it, I believe I did a refactor to cope with the absence of the Open/Close notifications (processing logic in Propulsion is not reliant on the notifications. In the case of leases being stolen, any buffered inputs would continue to process, competing with the new owner). If I was looking to prevent that overlapping processing, I'd implement an out-of-band 'Revoked' message to the internal processor, which would then dump/cancel all buffered/in progress work associated with that LeaseToken. (sets of Items get passed as batches along with the `Action` that can be used to trigger the manual checkpoint when they have been processed; an internal process debounces them to only trigger at most one of such checkpoint calls per 5 seconds)

**Comment by davidtimovski** [comment]
@ealsur
>Any failure during processing would release the lease, which would result in a NotifyLeaseReleaseAsync

Was this behavior the same in v2 when using `ClosedAsync`?

We have a spike of errors when a halted CFP starts processing again, 10-40% of all processing. I believe because we're overloading an external service when processing restarts with high volume. It appears that those errors that occur after the restart cause the leases to be released and then reacquired by other instances so sometimes they end up juggling (playing hot potato?) with the leases.

**Comment by ealsur** [comment]
Yes, CloseAsync was called when the lease was released.

"juggling" is the load balancing kicking in to distribute the leases evenly, it's a competitive distribution when the first instance to come up will acquire all and the rest will start to steal until it stabilizes. It's the same algorithm as V2 CFP.

**Comment by ealsur** [comment]
@davidtimovski Are there any other inquiries or topics we can cover on this Issue?

**Comment by davidtimovski** [comment]
@ealsur We're investigating this but for the time being I do not believe it to be related to Cosmos DB v3. We have a bunch of things built on top of the change feed processor SDK and some of them like the batching is probably the crux of it. Soon as I get more understanding of what's happening I'll close this issue :)

**Comment by davidtimovski** [comment]
@ealsur I was having trouble finding the issue because our new v3 code is so similar to the old one. Pretty much the same in the usage of `Observer.ProcessChangesAsync`/`OpenAsync`/`ClosedAsync` vs  the processing delegate and `OnLeaseAcquire`/`OnLeaseRelease` in v3. But now I noticed that one of those isn't equivalent.

In v2 there was `IChangeFeedObserverFactory` which created observers. In our v2 code when there was an uncaught exception we would put that exception in a property of the observer and if `ProcessChangesAsync()` would be called again it would log that the observer is in a faulted state and throw that exception again. But this faulted state would almost never happen as a new observer would be instantiated.
In v3 on the other hand we have a delegate which in our code is the same as the old observer `ProcessChangesAsync()`, but when an uncaught exception happens and we set it to a faulted state it basically remains there since there's no factory to just create a new observer. This seems like something that should be changed as it's not analogous to how v2 worked since now our delegates become forever halted.

Do you think my assumption is correct here?

**Comment by ealsur** [comment]
There is no factory concept or observer concept in V3, correct. The delegate just gets called when changes are delivered, there is no object lifetime, it's just invoking a delegate method. 

However, in V2, the factory would create a new observer when the lease was acquired, and then call OpenAsync. Conceptually that is similar to LeaseAcquireAsync notification.

**Comment by ealsur** [comment]
Thanks @davidtimovski for coming back and sharing the resolution, I think it will help for future users migrating!
