### ISSUE TITLE
How to read the Partitionkey of a container using Cosmosclient

### ISSUE THREAD

**Issue by praveenbarli** [Azure/azure-cosmos-dotnet-v3#3786]
One of the partameters of [CreateItemStreamAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createitemstreamasync?view=azure-dotnet) is the partionkey value in current message. How do we access the current container's partition key?

I see ContainerPropeties has the PartitionKeyPath property, but [Container](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container?view=azure-dotnet) class doesn't have a Resource properlty
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.containerproperties?view=azure-dotnet
```
Container container = await client.GetDatabase("dbName").Containers.CreateAsync("MyCollection", "/country", 50000);
ContainerProperties containerProperties = container.Resource;

```

**Comment by NaluTripician** [comment]
Hello @praveenbarli hopefully the following will help you with your problem. 

A when creating a `Container` for ComsosDB, you must specify at minimum two things. First is the `id` of the container. The second is the `PartitionKeyPath`. The `PartitionKeyPathPath` tells Cosmos where to look for the partition key value of every item you add into a Cosmos Container. This path can have any value also long as the items you add to Cosmos have that property. 

For instance, let's say you will be adding many of the following records to a Cosmos Database. 

```
public record DatabaseItem(
            string id,
            string city, 
            string state,
            string zipcode
            );
``` 

When creating the `Container` that will be used to store these items you can that any of these values are the `PartitionKeyPath`. For example: 

```
Container container = await db.CreateContainerAsync(
                id: "test",
                partitionKeyPath: "/city"
            );
```
or 
```
Container container = await db.CreateContainerAsync(
                id: "test",
                partitionKeyPath: "/state"
            );
```
are both valid (but not the only) ways to create the `Container`. 

Once a `Container` is created and we want to populate it with items we must make sure that the items have a property that matches the `ParitionKeyPath` we specified in the creation of the `Container`. Finding the `ParitionKeyPath` of a `Container` can be done like this: `await container.ReadContainerAsync().PartitionKeyPath`. When using the `CreateItemStreamAsync` method, we must specify two things. First is the stream containing the payload of the item we are creating, and second is the `ParitionKey` of that item.  

Let's look at the following example that details the creation of three items using the `CreateItemStreamAsync` method: 

```
client = new CosmosClient(
                accountEndpoint: endpoint,
                authKeyOrResourceToken: key
            );

db = await client.CreateDatabaseIfNotExistsAsync(
                id: "testDB"
            );

container = await db.CreateContainerAsync(
                id: "test",
                partitionKeyPath: "/thisIsThePartitionKeyPath"
            );

using (ResponseMessage response = await container.CreateItemStreamAsync(
                               partitionKey: new PartitionKey("/TheParitionKey"),
                                              streamPayload: new MemoryStream(Encoding.UTF8.GetBytes("{\"id\":\"document1\",\"thisIsThePartitionKeyPath\":\"/TheParitionKey\"}"))
                                                         ))
{
            Console.WriteLine(response.StatusCode);
}

using (ResponseMessage response = await container.CreateItemStreamAsync(
                               partitionKey: new PartitionKey("/TheOtherParitionKey"),
                                              streamPayload: new MemoryStream(Encoding.UTF8.GetBytes("{\"id\":\"document2\",\"thisIsThePartitionKeyPath\":\"/TheOtherParitionKey\"}"))
                                                         ))
{
             Console.WriteLine(response.StatusCode);
}

using (ResponseMessage response = await container.CreateItemStreamAsync(
                               partitionKey: new PartitionKey("/TheOtherParitionKey"),
                                              streamPayload: new MemoryStream(Encoding.UTF8.GetBytes("{\"id\":\"document3\",\"thisIsThePartitionKeyPath\":\"/TheOtherParitionKey\"}"))
                                                         ))
{
             Console.WriteLine(response.StatusCode);
}
```

Here you can see the difference in what the `PartitonKeyPath` and `PartitionKey` is.  In both cases the `PartitionKeyPath` stays the same, `thisIsThePartitionKeyPath`, while the values of the `PartitionKey` can change from item to item. However, as seen in the second and third items, they can have the same value.  In summary, the `PartitionKeyPath` tells Cosmos where to find the value of the `PartitionKey` within an item and stays the same for each `Container`, while the `PartitionKey` is the actual value the items are partitioned on. 

Please let me know if you have any further questions, if not feel free to close this issue.

**Comment by praveenbarli** [comment]
I tried the suggestion to read the PartitionKeyPath, bug get the below error. Any idea? 

![image](https://user-images.githubusercontent.com/22087406/231908527-6684b527-bec7-4d1f-ba3f-3b91322cecc5.png)

**Comment by bartelink** [comment]
@praveenbarli based solely on the error popup, placing parens before the `await` and after the ReadContainerAync()` might get you closer to the goal?

**Comment by bartelink** [comment]
You should not call `.Result` - always use `await` to hop from a `Task<X>` to an `X` (you can search up an article on these sorts of things with `.net Result await deadlock`)
