### ISSUE TITLE
Cosmos write timeout exception causing high latency

### ISSUE THREAD

**Issue by praveenbarli** [Azure/azure-cosmos-dotnet-v3#3798]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I get operation timeout errors (408) on writing to cosmosdb using [CreateItemStreamAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createitemstreamasync?view=azure-dotnet) api. though they don't appear on server side.

**To Reproduce**
Write at scale.
```
ResponseMessage response = await this.container.CreateItemStreamAsync(
                stream,
                partitionKey,
                options,
                cancellationToken: cancellationToken);

            if(response != null && response.IsSuccessStatusCode)
            {
                return true;
            }
            else
            {
                // Throwing exception explicity as stream API only throws client side exception which does not include RequestEntityTooLarge  
                //https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createitemstreamasync?view=azure-dotnet#remarks
                throw new Exception(response.StatusCode.ToString() + (string.IsNullOrEmpty(response.ErrorMessage) ? "" : response.ErrorMessage));
                
            }
```

**Expected behavior**
The write should happen successfully without exception.

**Actual behavior**
I get lot of System.Exception (details below) with Request.Timeout or Microsoft.Azure.Cosmos.CosmosOperationCanceledException eception

**Environment summary**
SDK Version: 3.31.2
OS Version Windows

**Additional context**
CPU, mem usage on node hosting the sdk: 
![image](https://user-images.githubusercontent.com/22087406/229936020-fca378e4-fee3-424e-88f4-798353043681.png)

System.Exception: RequestTimeoutResponse status code does not indicate success: RequestTimeout (408); Substatus: 0; ActivityId: c92f6f5e-da90-48dc-9e21-9fa4241bf1bc; Reason: (Message: Request timed out. More info: https://aka.ms/cosmosdb-tsg-request-timeout
ActivityId: c92f6f5e-da90-48dc-9e21-9fa4241bf1bc, Request URI: /apps/27468ac2-a8a6-4b1a-9d08-3108423a0e66/services/3f2b52ae-8b8f-4739-9f04-fb1a1a341381/partitions/5c466510-5ddd-44f4-acbf-fb7fbbba54b7/replicas/133247295029350829p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.17763 cosmos-netstandard-sdk/3.29.4);; Diagnostics:{"Summary":{"DirectCalls":{"(408, 0)":1}},"name":"CreateItemStreamAsync","id":"2edfc107-7b95-4dcb-9925-760a02314b29","start time":"08:31:10:242","duration in milliseconds":279234.7112,"data":{"Client Configuration":{"Client Created Time Utc":"2023-03-30T14:55:09.6241646Z","MachineId":"hashedVmId:96b51a8f-d694-7c17-8358-17c6b9a38d19","VM Region":"eastus","NumberOfClientsCreated":4,"NumberOfActiveClients":4,"ConnectionMode":"Direct","User Agent":"cosmos-netstandard-sdk/3.31.2|3|X64|Microsoft Windows 10.0.17763 |.NET Framework 4.7.4038.0|S|","ConnectionConfig":{"gw":"(cps:50, urto:10, p:False, httpf: False)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:False, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[], apprgn: East US)","ProcessorCount":2}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","id":"b3669869-c5b7-4d23-b29a-7bd234305be0","start time":"08:31:10:242","duration in milliseconds":279234.67350000003,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","id":"a6c2ca4f-6a8e-42a2-98fd-80551df083c9","start time":"08:31:10:242","duration in milliseconds":279234.6311,"data":{"System Info":{"systemHistory":[{"dateUtc":"2023-04-03T20:30:25.0482898Z"**_,"cpu":100.00_**0,"memory":576020.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":12.2244,"availableThreads":32756,"minThreads":2,"maxThreads":32767},"numberOfOpenTcpConnection":301},{"dateUtc":"2023-04-03T20:30:36.0019061Z",**_"**cpu":100.000,"**_**memory":473944.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.1154,"availableThreads":32753,"minThreads":2,"maxThreads":32767},"numberOfOpenTcpConnection":301},{"dateUtc":"2023-04-03T20:30:46.6899111Z","cpu":100.000,"memory":366308.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":70.993,"availableThreads":32755,"minThreads":2,"maxThreads":32767},"numberOfOpenTcpConnection":301},{"dateUtc":"2023-04-03T20:30:58.3310056Z","cpu":100.000,"memory":285848.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":308.1368,"availableThreads":32764,"minThreads":2,"maxThreads":32767},"numberOfOpenTcpConnection":301},{"dateUtc":"2023-04-03T20:31:08.9298623Z","cpu":91.636,"memory":310660.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0699,"availableThreads":32758,"minThreads":2,"maxThreads":32767},"numberOfOpenTcpConnection":301},{"dateUtc":"2023-04-03T20:35:46.0277091Z","cpu":20.882,"memory":661228.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":33.6966,"availableThreads":32751,"minThreads":2,"maxThreads":32767},"numberOfOpenTcpConnection":301}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","id":"0d5deae8-89a0-44ae-86c2-f68b2c384486","start time":"08:31:10:242","duration in milliseconds":279234.6078,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","id":"8299445c-53a4-473b-9755-d39128f0e142","start time":"08:31:10:242","duration in milliseconds":279234.58770000003,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","id":"7426d553-963c-4209-a5d7-904c19f197b5","start time":"08:31:10:242","duration in milliseconds":279234.585,"children":[{"name":"Microsoft.Azure.Documents.ServerStoreModel Transport Request","id":"7fa2183d-c527-47c7-b3e7-e7e2053d0d5e","start time":"08:31:10:242","duration in milliseconds":279232.539,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus1-be9.documents.azure.com:14361/apps/27468ac2-a8a6-4b1a-9d08-3108423a0e66/services/3f2b52ae-8b8f-4739-9f04-fb1a1a341381/partitions/5c466510-5ddd-44f4-acbf-fb7fbbba54b7/replicas/133247295029350829p/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus1-be9.documents.azure.com:14057/apps/27468ac2-a8a6-4b1a-9d08-3108423a0e66/services/3f2b52ae-8b8f-4739-9f04-fb1a1a341381/partitions/5c466510-5ddd-44f4-acbf-fb7fbbba54b7/replicas/133247295118888384s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus1-be9.documents.azure.com:14338/apps/27468ac2-a8a6-4b1a-9d08-3108423a0e66/services/3f2b52ae-8b8f-4739-9f04-fb1a1a341381/partitions/5c466510-5ddd-44f4-acbf-fb7fbbba54b7/replicas/133247295118888385s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus1-be9.documents.azure.com:14358/apps/27468ac2-a8a6-4b1a-9d08-3108423a0e66/services/3f2b52ae-8b8f-4739-9f04-fb1a1a341381/partitions/5c466510-5ddd-44f4-acbf-fb7fbbba54b7/replicas/133247295118888386s/"}],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[{"ResponseTimeUTC":"2023-04-03T20:35:49.1849612Z","ResourceType":"Document","OperationType":"Create","LocationEndpoint":"https://cosmosdbclientclose-eastus.documents.azure.com/","StoreResult":{"ActivityId":"c92f6f5e-da90-48dc-9e21-9fa4241bf1bc","StatusCode":"RequestTimeout","SubStatusCode":"Unknown","LSN":-1,"PartitionKeyRangeId":null,"GlobalCommittedLSN":-1,"ItemLSN":-1,"UsingLocalLSN":false,"QuorumAckedLSN":-1,"SessionToken":null,"CurrentWriteQuorum":-1,"CurrentReplicaSetSize":-1,"NumberOfReadRegions":-1,"IsValid":false,"StorePhysicalAddress":"rntbd://cdb-ms-prod-eastus1-be9.documents.azure.com:14361/apps/27468ac2-a8a6-4b1a-9d08-3108423a0e66/services/3f2b52ae-8b8f-4739-9f04-fb1a1a341381/partitions/5c466510-5ddd-44f4-acbf-fb7fbbba54b7/replicas/133247295029350829p/","RequestCharge":0,"RetryAfterInMs":null,"BELatencyInMs":null,"transportRequestTimeline":{"requestTimeline":[{"event": "Created", "startTimeUtc": "2023-04-03T20:31:10.2424276Z", "durationInMs": 0.004},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2023-04-03T20:31:10.2424316Z", "durationInMs": 0.0035},{"event": "Pipelined", "startTimeUtc": "2023-04-03T20:31:10.2424351Z", "durationInMs": 278935.1458},{"event": "Failed", "startTimeUtc": "2023-04-03T20:35:49.1775809Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":9,"openConnections":1},"connectionStats":{"waitforConnectionInit":"False","callsPendingReceive":7,"lastSendAttempt":"2023-04-03T20:31:10.0861623Z","lastSend":"2023-04-03T20:31:10.2111731Z","lastReceive":"2023-04-03T20:31:10.2111731Z"},"requestSizeInBytes":1337,"requestBodySizeInBytes":852},"TransportException":"A client transport error occurred: Acquiring the send stream lock timed out. (Time: 2023-04-03T20:35:49.1849612Z, activity ID: c92f6f5e-da90-48dc-9e21-9fa4241bf1bc, error code: SendLockTimeout [0x000D], base error: HRESULT 0x80131500, URI: rntbd://cdb-ms-prod-eastus1-be9.documents.azure.com:14361/apps/27468ac2-a8a6-4b1a-9d08-3108423a0e66/services/3f2b52ae-8b8f-4739-9f04-fb1a1a341381/partitions/5c466510-5ddd-44f4-acbf-fb7fbbba54b7/replicas/133247295029350829p/, connection: 10.0.4.15:57881 -> 52.146.79.175:14361, payload sent: True)"}}]},"Point Operation Statistics":{"Id":"PointOperationStatistics","ActivityId":"c92f6f5e-da90-48dc-9e21-9fa4241bf1bc","ResponseTimeUtc":"2023-04-03T20:35:49.4818459Z","StatusCode":408,"SubStatusCode":0,"RequestCharge":0,"RequestUri":"dbs/testdb2/colls/testcontainer2","ErrorMessage":"Microsoft.Azure.Documents.RequestTimeoutException: Message: Request timed out. More info: https://aka.ms/cosmosdb-tsg-request-timeout\r\nActivityId: c92f6f5e-da90-48dc-9e21-9fa4241bf1bc, Request URI: /apps/27468ac2-a8a6-4b1a-9d08-3108423a0e66/services/3f2b52ae-8b8f-4739-9f04-fb1a1a341381/partitions/5c466510-5ddd-44f4-acbf-fb7fbbba54b7/replicas/133247295029350829p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.17763 cosmos-netstandard-sdk/3.29.4 ---> Microsoft.Azure.Documents.TransportException: A client transport error occurred: Acquiring the send stream lock timed out. (Time: 2023-04-03T20:35:49.1849612Z, activity ID: c92f6f5e-da90-48dc-9e21-9fa4241bf1bc, error code: SendLockTimeout [0x000D], base error: HRESULT 0x80131500, URI: rntbd://cdb-ms-prod-eastus1-be9.documents.azure.com:14361/apps/27468ac2-a8a6-4b1a-9d08-3108423a0e66/services/3f2b52ae-8b8f-4739-9f04-fb1a1a341381/partitions/5c466510-5ddd-44f4-acbf-fb7fbbba54b7/replicas/133247295029350829p/, connection: 10.0.4.15:57881 -> 52.146.79.175:14361, payload sent: True)\r\n   at Microsoft.Azure.Documents.Rntbd.Channel.<RequestAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.Rntbd.LoadBalancingPartition.<RequestAsync>d__11.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.Rntbd.TransportClient.<InvokeStoreAsync>d__10.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Azure.Documents.Rntbd.TransportClient.<InvokeStoreAsync>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.ConsistencyWriter.<WritePrivateAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Azure.Documents.StoreResult.VerifyCanContinueOnException(DocumentClientException ex)\r\n   at Microsoft.Azure.Documents.ConsistencyWriter.<WritePrivateAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetryAsync>d__6`2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)\r\n   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetryAsync>d__6`2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.ConsistencyWriter.<WriteAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass31_0.<<InvokeAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.RequestRetryUtility.<ProcessRequestAsync>d__2`2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)\r\n   at Microsoft.Azure.Documents.RequestRetryUtility.<ProcessRequestAsync>d__2`2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Documents.StoreClient.<ProcessMessageAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.<ProcessMessageAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.<SendAsync>d__2.MoveNext()","RequestSessionToken":null,"ResponseSessionToken":null,"BELatencyInMs":null}}}]}]}]}]}]}]}
   at Microsoft.Azure.Devices.Routing.CosmosDB.Sinks.CosmosClientWrapper.<CreateItemStreamAsync>d__7.MoveNext() in C:\__w\1\s\routing\Microsoft.Azure.Devices.Routing.CosmosDB\sinks\CosmosClientWrapper.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Routing.CosmosDB.Sinks.RoutingEndpointCosmosDBSqlClient.<CreateAndWriteMessageToCosmosDB>d__8.MoveNext() in C:\__w\1\s\routing\Microsoft.Azure.Devices.Routing.CosmosDB\sinks\RoutingEndpointCosmosDBSqlClient.cs:line 115

**Comment by ealsur** [comment]
Please follow the aka.ms message in the exception and read the article. Then look at the content shared and you will see the reason for your timeouts.

**Comment by ealsur** [comment]
> High CPU utilization is the most common case. For optimal latency, CPU usage should be roughly 40 percent. Use 10 seconds as the interval to monitor maximum (not average) CPU utilization.

You are looking at average CPU
