### ISSUE TITLE
Issues with the cosmosdb emulator 

### ISSUE THREAD

**Issue by Arcalise08** [Azure/azure-cosmos-dotnet-v3#3800]
**Describe the bug**
  It appears the dotnet cosmos sdk is unable to connect to the cosmosdb emulator on versions v2.14.12 & v2.14.11. The issue only appears if you are running a docker app and connecting to the emulator on a host machine. In these instances we would substitute the localhost part of the connection string for `host.docker.internal:8081` which works fine on `v2.14.9` 
  
  Its unclear if the problem is with the sdk or the emulator as we can connect to the rest client just fine.
  
  **To Reproduce**
  Git repo showing the problem is [here.](https://github.com/Arcalise08/CosmosDBConnectionIssues)
  
  I used chocolatey to install different versions of cosmos easier. 
  1. Install the latest version of cosmos emulator
  2. Start the emulator with the following options  
  `/AllowNetworkAccess /Key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==`
  3. Create a new .net 6 console app. Add docker support to it.
  4. Install the cosmos sdk to the console app. 
  5. Copy the connection string from cosmosdb. change the localhost in the connection string to `host.docker.internal`
  6. Attempt to create a database using the sdk.
  
  **Expected behavior**
  A database is created.
  

  **Actual behavior**
![Screenshot 2023-04-05 112831](https://user-images.githubusercontent.com/61042848/230144699-bf9acd0c-f62c-439d-9f40-1a9698397e5a.png)

  
  **Environment summary**
  SDK Version: 3.32.3
  OS Version: Windows 11

**Comment by ealsur** [comment]
@Arcalise08 This repo does not cover support for the Cosmos DB Emulator. If there was a recent regression on the emulator as you mention, please report it through the channels for Emulator Issues -> https://learn.microsoft.com/en-us/azure/cosmos-db/docker-emulator-linux?tabs=sql-api%2Cssl-netstd21#report-an-emulator-issue
