### ISSUE TITLE
Unable to skip SSL authentication when connecting to Emulator running in WSL.

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cosmos-dotnet-v3#3815]
**Describe the bug**
I would like to connect to a cosmos emulator running in WSL. I don't want to use SSL so I overrode `CosmosClientOptions.HttpClientFactory` to skip the SSL validation.

**To Reproduce**
Run the emulator in WSL (Ubuntu 22.04 distro from my side) using:
```bash
$ ipaddr="`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1`"
$ docker run -p 8081:8081 -p 10250-10255:10250-10255 -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1 -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipaddr -i -t mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
```

Console app:
```cs
const string AccountEndpoint = "https://localhost:8081/";
const string AccountKey = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";

var cosmosClient = new CosmosClient(AccountEndpoint, AccountKey, new()
{
    ConnectionMode = ConnectionMode.Gateway,
    HttpClientFactory = () =>
    {
        var httpMessageHandler = new HttpClientHandler
        {
            ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
        };
        return new HttpClient(httpMessageHandler);
    }
});
await cosmosClient.CreateDatabaseIfNotExistsAsync("demo");
```

**Expected behavior**
The program runs successfully.

**Actual behavior**
The program hangs in `cosmosClient.CreateDatabaseIfNotExistsAsync`, never returning and never creating a database.

**Environment summary**
SDK Version: 3.32.3
OS Version: Windows 11

**Additional context**
The issue is similar to #2706 but this issue is closed and I am not able to find a solution.

**Comment by bartelink** [comment]
IME a hang in CreateDatabase is generally a symptom of a connectivity issue - an actual certificate check failure will yield you a specific exception. For a 'hang' like this, you should eventually get a HTTP 408 timeout or similar; generally that's a matter of a port not being mapped etc (example notes I took along the way to figuring out a similar mystery, even if it may look like entirely different circumstances: https://stackoverflow.com/a/75879659/11635)

**Comment by Baltima** [comment]
I don't think it's an network issue or port not being mapped as I can access to https://localhost:8081/_explorer/index.html from my machine (with a SSL issue of course but I can't bypass it in the browser).

**Comment by bartelink** [comment]
Don't bank on it - the port config for the admin UI and Gateway mode connections may or may not coincide.

I note also that your `-p` args are for the Direct ports, but your code is requesting `Gateway` - in general you're probably best off sticking with `Direct` everywhere

_The bottom line is that not being able to create a database is probably not the problem - it's just the first thing you happen to be doing programmatically_. I'd also add that this repo is about the .NET SDK/packages, and things that can be fixed by changing things in there; there's no reason to believe this is the case, so this issue really does not belong here.

**Comment by Baltima** [comment]
I would like to use the Gateway mode locally and disable the SSL validation on the `HttpClient` used with:
```cs
    HttpClientFactory = () =>
    {
        var httpMessageHandler = new HttpClientHandler
        {
            ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
        };
        return new HttpClient(httpMessageHandler);
    }
```

**Comment by bartelink** [comment]
This is not a chat forum for diagnosing/requesting docker configs
This is a repo for the .NET CosmosDB SDK  - you're better off using stackoverflow.com if you're hoping to to/fro with someone; there's only me and 69 other watchers on this repo
I found the MS documentation for configuring the emulator on a Mac to be pretty OK, but it takes time and diligence to figure it out.
*If you have a specific message that you think tells you there is a problem with how you are disabling cert validation, then by all means sit and wait for an answer. Until then, you've yet to disprove that this is a connectivity issue that comes BEFORE all of that.*

**Comment by Baltima** [comment]
I understand that this is not a place for diagnosing. This actually seems to be a bug as with SSL enabled (in gateway connection mode and with the emulator in WSL), it works correctly.

**Comment by bartelink** [comment]
OK, I guess you'll figure it out then.

For me, the key thing is that the connection mode greatly influences the ports used, so it's key to get to a point where you know what those port numbers are, and then validate that they are wired up correctly. You absolutely want to know the connection mode you're talking about and then follow the docs. In my case, I know Direct can be made to work locally, I know I want to use it in prod, and I know that you have  `-p` arguments related to them; hence I'd be targeting that. But if you know better, make sure you know the connection mode and/or ports.

Changing the cert validation policy comes after that - if there's a discrepancy or problem, you'll get a clear exception. You're not that point - it's hanging. (And, for avoidance of doubt, changing the cert check config does not affect the endpoint and/or connection mode.)

**Comment by Baltima** [comment]
I am using Gateway connection mode locally as I do not want to setup any certificate and want to be able to bypass the SSL validation.

**Comment by Baltima** [comment]
> because this thread does not contain any exception or data that we could help with.

Yes because there is no exception.

**Comment by ealsur** [comment]
> Yes because there is no exception.

There should always be an exception unless the operation is still in progress or is hung. If it's hung, it means the thread is being blocked, if not, it is still working or doing something, it might be failing to connect on the HTTP protocol, and that takes longer to surface the failure because the HTTP stack might be attempting to retry, it doesn't mean there is no exception, just that because of the nature of the connectivity problem, it takes longer to surface.
