### ISSUE TITLE
Open Telemetry/AI Integration: `Activity.Kind` should be `Client` in Gateway mode

### ISSUE THREAD

**Issue by Baltima** [Azure/azure-cosmos-dotnet-v3#3825]
**Describe the bug**
Currently, activities started in Gateway mode have a `Kind` = `Internal`. The `Kind` should be `Client` (as in Direct mode).

**To Reproduce**

```cs
var clientOptions = new CosmosClientOptions
{
    ConnectionMode = ConnectionMode.Gateway,
    IsDistributedTracingEnabled = true
};
var client = new CosmosClient(connectionString: "", clientOptions);

var listener = new ActivityListener
{
    ActivityStopped = activity =>
    {
        Console.WriteLine(activity.Kind); // Internal
    },
    ShouldListenTo = activitySource => activitySource.Name == "Azure.Cosmos.Operation",
    Sample = (ref ActivityCreationOptions<ActivityContext> _) => ActivitySamplingResult.AllData
}
ActivitySource.AddActivityListener(listener);

var database = client.GetDatabase("database1");
var container = database.GetContainer("container1");
var item = new MyItem();
await container.CreateItemAsync(item, new PartitionKey(item.Id));
```

**Expected behavior**
The activity `Kind` should be `Client`.

**Actual behavior**
The activity `Kind` is `Internal`.

**Environment summary**
SDK Version: 3.32.3-preview

cc  @sourabh1007

**Comment by ealsur** [comment]
@sourabh1007 could you take a look at this report? Could it be something fixed in the upcoming version?

**Comment by Baltima** [comment]
After further investigation, I found the piece of code responsible for this behaviour and it seems to have been implemented this way explicitly:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e5972ac0ffd53595b2f1f0f10a3faf913ff882e1/Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs#L35-L38

I am not sure to understand why this condition is there and the trace in many monitoring tools (e.g. App Insights) appears as an internal dependency and not as an outgoing request to an external component.

**Comment by Baltima** [comment]
Thank you for your feedback

The problem is that the Cosmos operation is considered as an "in proc" operation in Application Insights while it is a network call to a external component in fact.

![image](https://user-images.githubusercontent.com/130716409/235152903-a1f46d8f-f5f7-4f50-b4c8-007e6fbfac6e.png)

**Comment by Baltima** [comment]
Thank you for your feedback. It is very clear!
