### ISSUE TITLE
Modify querymetrics to be exposed, not a private sealed class.  Maybe .GetQueryMetrics?

### ISSUE THREAD

**Issue by stowen-msft** [Azure/azure-cosmos-dotnet-v3#3837]
**Is your feature request related to a problem? Please describe.**
QueryMetrics provides very useful information, but here is how I have to get it using the newest cosmos SDK.

```
traces
| where message has "Retrieved Document Count"
| extend Query_Metrics_ = tostring(parse_json(tostring(parse_json(tostring(parse_json(tostring(parse_json(tostring(parse_json(tostring(parse_json(message).children))[1].children))[1].children))[0].children))[0].data)).["Query Metrics"])
```
Look at how many levels deep that is!!!

**Describe the solution you'd like**
I can already get Diagnostics like this:

```csharp
var result = await this.container.UpsertItemAsync(entity, entity.ResourceIdentity.GetPartitionKey());
                    this.logger?.LogDebug("{operation} of record {entity} elapsed time {elapsed} query incurred charge of {resourceUnits} RUs",
                        "Update",
                        entity.Id,
                        result.Diagnostics?.GetClientElapsedTime(),
                        result.RequestCharge);
```

Simply expose QueryMetrics as well, via `Diagnostics.GetQueryMetrics()`, instead of having it be a very, very, very deeply nested property.

**Describe alternatives you've considered**
I began to just import the QueryMetrics and other types into my own project and write an extension method to do this, but the code style doesn't mesh well with our project and style-cop was causing issues.

I also tried to write an extension method to handle the conversion from Diagnostics.ToString(), but it looked really gnarly.

**Additional context**

**Comment by ealsur** [comment]
@neilsh Sounds replicate of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3357

**Comment by stowen-msft** [comment]
Very similar, it's still an issue in V3, and was like this as well in V2.
