### ISSUE TITLE
Specifying a JSON serializer/DateTime format for LINQ queries with DateTime

### ISSUE THREAD

**Issue by kojini** [Azure/azure-cosmos-dotnet-v3#3843]
I am searching for a way to specify a JSON serializer or DateTime format for LINQ query to get around an issue.

I call `GetItemLinqQueryable()` with some `Where` clauses and one of them is `DateTime`.  
It works mostly but when `DateTime` has trailing 0s (e.g. `2023-05-10T01:00:15.1234000Z`), the 0s are removed from a query string generated by `QueryBuilder`, which returns wrong results.

My code and a generated query look like this:
```
var queryOptions = new QueryRequestOptions{ PartitionKey = new PartitionKey(id.ToString()) };
var options = new CosmosLinqSerializerOptions{ PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase };
var container = client.GetContainer(dbId, containerName);

IQueryable<ListItem> queryBuilder = container
    .GetItemLinqQueryable<ListItem>(false, null, queryOptions, options)
    .OrderByDescending(x => x.DateCreated);

if (modifiedSince.HasValue)
    queryBuilder = queryBuilder.Where(x => x.DateModified > modifiedSince.Value);

// more Where clauses

var iterator = queryBuilder.ToFeedIterator();
while (iterator.HasMoreResults)
{
    var docs = await iterator.ReadNextAsync();
    if (docs.Any())
        listItems.AddRange(docs);
}
```
```
// got it from queryBuilder.ToQueryDefinition().QueryText;
SELECT TOP 5 VALUE root 
FROM root 
WHERE ((root["dateModified"] > "2023-05-01T04:57:16.3109Z"))
ORDER BY root["dateCreated"] DESC
```
The Where clase doesn't have 0s after `.3109`.  

In my Cosmos Db container, I have data like this
```
{
    "id": "123",
    "dateModified": "2023-05-01T04:57:16.3109000Z",
    ...
}
```

I run the generated query on Azure, it does not return the data shown above. If I add 0s (`3109000Z`), the query returns it. Specifying DateTime format to add 0s at the end will fix the issue but I just can't find how.

Is there a way to specify a JSON serializer or DateTime format for LINQ query?  

I added my custom DateTime Json serializer to `CosmosClientOptions.Serialize` when I create an instance of `CosmosClient` but the seralizer doesn't get called for generating/executing the query.  
I checked some issues like [https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3677](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3677) but it's closed without a solution.
In this issue [https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1732](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1732), a workaround is mentioned but it doesn't work.

**Comment by ealsur** [comment]
LINQ not supporting custom serializer is tracked at https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2685

Serialization uses Newtonsoft.Json, so if you want to customize how a particular property is serialized using a Converter, decorating the property or adding it to the global converters, for example: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3808#issuecomment-1505551450
