### ISSUE TITLE
Making sense of what works and what doesn't

### ISSUE THREAD

**Issue by mathieubergouniouxcab** [Azure/azure-cosmos-dotnet-v3#3846]
I want to believe that the scenarios below **don't** reveal a bug in Cosmosdb 3 with .Net 6, but at the moment I fail to find the consistency in those behaviours.

Could you please read **[this StackOverflow question](https://stackoverflow.com/questions/76226063/cosmosclient-readitemasync-succeeds-getitemlinqqueryable-fails)** , and explain what is wrong there?
I would normally never have the cheek of posting here for such a trivial problem, but there are many questions on the web related to the proper use of the partition key, so I'm not the only one struggling with this.

**Comment by ealsur** [comment]
@mathieubergouniouxcab can you please share a full repro code of the issue? Including any Type definitions and how the client is created, with custom Serializer? We need to be able to repro to investigate.

@kundadebdatta could you take a look once information is available?

**Comment by rinatmini** [comment]
@mathieubergouniouxcab 
1. Related to the 2nd SO example: Currently, SDK doesn't support custom serializers in the `GetItemLinqQueryable`. If you invoke `container.GetItemLinqQueryable<MyType>(true).Where(m => m.Id == id).Expression` you can see translated to SQL query which will be: `SELECT VALUE root FROM root WHERE (root["Id"] = <some id>)` that uses original property name ('Id'), not a name from `JsonPropertyName` attribute ('id' in lowercase). It's a known issue and the SDK team working on this.
See related #2685 for more information.
2. Related to the 5th SO example: This part of code: `.Where(m => m.Id == input.Id).FirstOrDefault();` raises `Microsoft.Azure.Cosmos.Linq.DocumentQueryException: 'Method 'FirstOrDefault' is not supported.` Currently, SDK does not directly support the `FirstOrDefault()` method on the `GetItemLinqQueryable` query.
See [LINQ to SQL translation - Azure Cosmos DB for NoSQL | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/linq-to-sql) for more information.

**Comment by mathieubergouniouxcab** [comment]
Very clear answer, thanks.
I thought I was being a good little dev by trying to use System.Text.Json in my CosmosDb code but it's bringing nothing but issues.
Your answer solves my issue.
