### ISSUE TITLE
Transaction limit on batches

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-cosmos-dotnet-v3#3853]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#36302](https://github.com/Azure/azure-sdk-for-net/issues/36302).

## Details

[Enter feedback here]
No mention transaction limits.  Tried to use to upload 100's of documents and it errored out.  What is the limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c870bbb-ee69-9266-3d09-3f2e68ed4175
* Version Independent ID: 444850f9-9318-3b75-8b76-504ae37357e6
* Content: [Container.CreateTransactionalBatch(PartitionKey) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createtransactionalbatch?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ChuckWalters** [comment]
This documentation should at lest reference it's limitations.
Also was Batch transactions for Bulk uploads.  The Batch documentation should have a "see also" pointing to Bulk transactions to prevent misuse: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/tutorial-dotnet-bulk-import

**Comment by ealsur** [comment]
Linking Bulk documentation in a Batch API is incorrect, they are different use cases.

The right document to link is https://learn.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-request-limits
