### ISSUE TITLE
Support for Microsoft.Azure.Cosmos >= 3.32 in Microsoft.Azure.Cosmos.Encryption

### ISSUE THREAD

**Issue by mortenn** [Azure/azure-cosmos-dotnet-v3#3871]
**Is your feature request related to a problem? Please describe.**
Our project is locked to version 3.31.2 for Microsoft.Azure.Cosmos, but we would like to use the latest version.
We do not have complete knowledge of what differences there exists between 3.31.2 and the latest release, but we know there are some breaking changes we had to work around when rolling back.

**Describe the solution you'd like**
The limitations in Microsoft.Azure.Cosmos.Encryption causing it to require Microsoft.Azure.Cosmos < 3.32 should be resolved

**Describe alternatives you've considered**
Running on Microsoft.Azure.Cosmos < 3.32 - we do this at this time, but am unsure of any consequences in regards to features and bugs.

**Comment by ealsur** [comment]
@kr-santosh Can anyone from encryption help answering this question?

**Comment by kr-santosh** [comment]
@mortenn  We will get back to you at the earliest and update you regarding when can we support the latest Microsoft.Azure.Cosmos . Thanks

**Comment by ealsur** [comment]
@kr-santosh should this issue be closed now that the PR was merged?
