### ISSUE TITLE
Diagnostic data in the 410 error responses contain conflict fields

### ISSUE THREAD

**Issue by rinatmini** [Azure/azure-cosmos-dotnet-v3#3880]
Diagnostic data related to 503/410 errors can have the next information:
```
...
"DirectCalls":{"(410, 20001)
...
"IsValid":true
...
```

In this documentation substatus 20001 means:
[Troubleshoot Azure Cosmos DB service unavailable exceptions | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-service-unavailable)
"The service unavailable error happened because there are client-side [connectivity issues](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-service-unavailable#client-side-transient-connectivity-issues) (failures attempting to connect). The client attempted to recover by [retrying](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/conceptual-resilient-sdk-applications#timeouts-and-connectivity-related-failures-http-408503) but all retries failed."

This documentation mentions that it is Cosmos DB service issue:
[Troubleshoot slow requests in Azure Cosmos DB .NET SDK | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-dotnet-sdk-slow-request?tabs=cpu-new#storeresult) (Requests contain multiple failure error codes, like 410 and `IsValid` is true points to a problem with the Azure Cosmos DB service)

There are incorrectly filling the `IsValid` trace field or conflicts in the documentation that can cause incorrect interpretation logs data.

**Comment by ealsur** [comment]
Documentation seems incorrect, IsValid doesn't seem like it's a deterministic way to tell that it's a service issue.

For example:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/512a7375c3d5ae564e73903b26947cff29e9b165/Microsoft.Azure.Cosmos/src/direct/StoreResult.cs#L225-L227
