### ISSUE TITLE
[Nudge Feature to cleanup our codebase] Remove all Usages of NugetPath_* Properties and Replace them with Pkg* using PackageReference

### ISSUE THREAD

**Issue by kundadebdatta** [Azure/azure-cosmos-dotnet-v3#3884]
### Description:

This issue is intended migrate away from deprecated property usage.

### Fix:

Please remove all usages of `NugetPath_*` properties and replace them with `Pkg*` using `PackageReference` in these projects.
Follow the steps located [here](https://eng.ms/docs/cloud-ai-platform/azure-data/azure-data-azure-databases/cosmos-db/azure-cosmos-db/azure-cosmos-db-tsg/tsg1636).

### Affected Files:
`Product\SDK.net\Microsoft.Azure.Cosmos.Direct\tests\Microsoft.Azure.Cosmos.Direct.Test.csproj`

### Repro Steps:
`msbuild /t:RunESValidationTask /p:ProjectIsUnderDevelopment=true {MyProjectFileInAffectedFilesListAbove}`

### Reference Link to Pull Request:

- [Rntbd Health Check Improvements Part 2: Adds Code to Detect Transit Timeouts Aggressively](https://msdata.visualstudio.com/DefaultCollection/CosmosDB/_git/CosmosDB/pullRequest/1067536#1685644035)

**Comment by kirankumarkolli** [comment]
Its for direct package

**Comment by kundadebdatta** [comment]
> Its for direct package

Yes, my bad. Created a separate issue in the msdata board for tracking.
