### ISSUE TITLE
Get Partition Key Range ID

### ISSUE THREAD

**Issue by albertofori** [Azure/azure-cosmos-dotnet-v3#3890]
### My request:

I want to know if there is any way to get partition key range ID for a given physical partition in the current stable version of the SDK. 

### Background:
My team is migrating to use the CosmosDB V3 SDK. We have a collection for which one of the properties of our Documents is a Partition key range ID that is used for change feed queries to another collection. I see that the `GetPartitionKeyRangesAsync` method for the [Container ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/387ab62dbb55bcc99491bf16b88a32ad1cd663a5/Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs#L1668) class is only exposed in the preview version.  Are there any plans to make this available in the near future for stable versions?  If not, what is the best way to get the partition key range ID for a given physical partition / feed range? This would help maintain compatibility between our collection and without having to hack any properties together to keep both old and new services working during a live migration.

**Comment by bartelink** [comment]
(Dont work for the team but) Would be interested to hear some more detail on the use case to understand what leverage this affords; it sounds like a very coarse thing to depend on a moving distribution in that way? Or do you simply have bespoke changefeedprocessor logic (if so, my condolences:D). I suspect clarifying this will also help anyone properly answering this question.

Also, I doubt it helps but FYI the `LeaseToken` passed in the context of the changefeed callback was formerly labelled `PartitionKeyRangeId` in the unlikely event that this might be useful/give a clue for a different approach...

**Comment by albertofori** [comment]
We currently use the pull model for change feed processing and we persist PartitionKeyRangeId in our leases so our workers can process changes in different physical partitions in parallel. I understand we might need to start using feed ranges going forward, however, we need to still be able to process changes based on the partition key range id from the acquired leases during our migration.

**Comment by ealsur** [comment]
If J understand correctly, you are migrating from Change Feed Query on V2, which required PKRangeId. V3 does not require it and for parallelization you can use FeedRange (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/migrate-dotnet-v3?tabs=dotnet-v3#change-feed-queries).

There is no longer a need to handle split errors either.

If you are storing the PKRangeId you can store the FeedRange.ToJsonString as a conceptual equivalent, and use FeedRange.FromJsonString if you want to deserialize it back.

One important thing is, the continuation token from V2 is not compatible with V3, one possibility is use StartFrom.Time on V3 with a time on which you stop the V2 version and deal with the potential duplicate.
