### ISSUE TITLE
Avoid Custom serialzier on SDK OOB types (including spatial types) 

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#39]
SDK uses custom given serializer for all types serialization including OOB types in SDK.
In some cases custom serialzier might result in un-intended behaviors

Broadly there are below types in SDK, which are ideal candidates 
1.	REST types (Database, …)
2.	Spatial types

Repro: 
Below settings on V2 SDK might result in spatial types serialization breaking the expectation.

JsonSerializerSettings jsonSerializerSettings =
    new JsonSerializerSettings
    {
        ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
        PreserveReferencesHandling = PreserveReferencesHandling.Objects,
        MissingMemberHandling = MissingMemberHandling.Ignore,
        NullValueHandling = NullValueHandling.Ignore,
        DateFormatHandling = DateFormatHandling.IsoDateFormat,
        DateTimeZoneHandling = DateTimeZoneHandling.Utc,
        Formatting = Formatting.None,
        TypeNameHandling = TypeNameHandling.Auto,
    };

**Comment by ealsur** [comment]
@kirankumarkolli We are also using the custom JSON serializer on metadata operations, should it be only used for operations with Documents?

**Comment by j82w** [comment]
@ealsur  if the metadata operations have stream methods exposed then I feel like the correct action is allow custom serializer for those operations or possibly have a different serializer for them. If the stream method for the metadata operations are not exposed then I  agree that we should always use the default JSON serializer for the metadata operations.  The only downside is this would prevent us from removing JSON.net dependencies which causes version conflict issues.

**Comment by ealsur** [comment]
Currently I don't see any stream related signatures for metadata (like `cosmosContainer.ReadAsync`). My line of thinking is that users can specify their own serializers for their data types and have control over that, but metadata operations is over SDK-defined types (like container or database reads), allowing a custom serializer into those calls can impact base operations if there is a performance issue (or any other issue) with the custom serializer and the metadata types.

**Comment by j82w** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/571
