### ISSUE TITLE
ChangeMode Incremental VS LatestVersion ?

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-cosmos-dotnet-v3#3913]
The difference between ChangeMode Incremental vs LatestVersion is not clear!

**Comment by philipthomas-MSFT** [comment]
They have the same behavior.

**Comment by jcocchi** [comment]
@MhAllan LatestVersion is just a rename of Incremental, they have the same behavior. If you're using the pull model you can use Incremental beginning in version 3.34.0 which is [documented here](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-pull-model?tabs=dotnet#working-with-the-pull-model).

The [change feed processor](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-processor?tabs=dotnet) currently only supports latest version mode.
