### ISSUE TITLE
[BUG] Diagnostic Logs: Fixing ContactReplicas to only include the successful replicas contacted per physical partition.

### ISSUE THREAD

**Issue by philipthomas-MSFT** [Azure/azure-cosmos-dotnet-v3#3916]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persists in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Fixing a bug for ContactedReplicas. It should only display the one replica per physical partition that was contacted successfully, not all replicas contacted for the partition.

- Define Replica.
- Define ContactedReplicas and what constitutes as Contacted and Failed.
- Define physical partition. What distinguishes this (look at logs).

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

Print any diagnostic log string where multiple replicas on the same physical partition failed and one was finally successful.

**Expected behavior**
``` json
"ContactedReplicas": [
	{
		"Count": 1,
		"Uri": "rntbd://cdb-ms-prod-westus-fd4.documents.azure.com:14382/apps/9dc0394e-d25f-4c98-baa5-72f1c700bf3e/services/060067c7-a4e9-4465-a412-25cb0104cb58/partitions/2cda760c-f81f-4094-85d0-7bcfb2acc4e6/replicas/132608933859499990p/"
	}
]
```

**Actual behavior**
``` json
"ContactedReplicas": [
	{
		"Count": 1,
		"Uri": "rntbd://cdb-ms-prod-westus-fd4.documents.azure.com:14382/apps/9dc0394e-d25f-4c98-baa5-72f1c700bf3e/services/060067c7-a4e9-4465-a412-25cb0104cb58/partitions/2cda760c-f81f-4094-85d0-7bcfb2acc4e6/replicas/132608933859499990p/"
	},
	{
		"Count": 1,
		"Uri": "rntbd://cdb-ms-prod-westus-fd4.documents.azure.com:14382/apps/9dc0394e-d25f-4c98-baa5-72f1c700bf3e/services/060067c7-a4e9-4465-a412-25cb0104cb58/partitions/2cda760c-f81f-4094-85d0-7bcfb2acc4e6/replicas/132608933859470000s/"
	},
	{
		"Count": 1,
		"Uri": "rntbd://cdb-ms-prod-westus-fd4.documents.azure.com:14382/apps/9dc0394e-d25f-4c98-baa5-72f1c700bf3e/services/060067c7-a4e9-4465-a412-25cb0104cb58/partitions/2cda760c-f81f-4094-85d0-7bcfb2acc4e6/replicas/132608933859471110s/"
	},
	{
		"Count": 1,
		"Uri": "rntbd://cdb-ms-prod-westus-fd4.documents.azure.com:14382/apps/9dc0394e-d25f-4c98-baa5-72f1c700bf3e/services/060067c7-a4e9-4465-a412-25cb0104cb58/partitions/2cda760c-f81f-4094-85d0-7bcfb2acc4e6/replicas/132608933859472220s/"
	}
]
```

**Environment summary**
SDK Version: All
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Solution**

- Identify any tests that contradict the expected behavior. If none exists, create them. Tests should pass.
- Identify the system under test and make the necessary changes.
- Go back to tests, and the tests should fail.
- Fix tests, and tests should pass.

***Impact of change***

**Breaking contracts**: Tempting as it may be, I do not wish to break the current contract which is keeping **ContactedReplicas** as part of an array with a count of 1, even though we are always forcing only the last _contacted replica_ in the array to be revealed. Always open to discuss if we want to break this, but for now, the impact of change is at its minmum.

**Duplicate contact regions**: The method and tests to verify the removing of duplicate contact replicas from the array is unnecessary since we are only revealing the last _contacted region_.

**Comment by philipthomas-MSFT** [comment]
Notes: 
Identify any tests that contradict the expected behavior. If none exists, create them. Tests should pass.
Identify the system under test and make the necessary changes.
Go back to tests, and the tests should fail.
Fix tests, and tests should pass.

**Comment by philipthomas-MSFT** [comment]
What constitutes success? Currently the criteria for a replica being added to **ContactReplicas** is a storeResponse that is not null, and the criteria for a replica being added to **FailedReplicas** is a storeException that is not null, and has a _TransportException_ inner exception.

One thing that I am noticing is that the storeResponse can have a status/subStatus . Is it possible to have a storeResponse with a status/subStatus combination of something like 410/1002 that is also not a storeException _TransportException_?

Investigation continues.

**Comment by philipthomas-MSFT** [comment]
_msdata_ functions that add replicas to **ContactedReplicas**

- StoreReader.ReadMultipleReplicasInternalAsync (private)
  - **StoreReader.ReadMultipleReplicaAsync (public)**
    - ConsistencyWriter.WaitForWriteBarrierAsync (private)
      - **ConsistencyWriter.WriteAsync (public)**
      - ConsistencyWriter.WritePrivateAsync (private)
    - **ConsistencyReader.ReadAnyAsync (public)**
      - ConsistencyReader.ReadPrimaryAsync (private)
    - ConsistencyReader.ReadSessionAsync (private)
      - **ConsistencyReader.ReadAsync (public)**
        - **ReplicatedResourceClient.InvokeAsync (public)**

_msdata_ tests.

- **ReadMultipleReplicaAsync**
  - StoreReaderGoneExceptionHasSubStatusCodeAsync
  - StoreReaderCapturesStoreResultDiagnosticsForSplits
  - StoreReaderFailedReplicasTestAsync
  - VerifyStoreReaderAddressRefreshOnCancellationTokenAsync
  - VerifyStoreReaderBackgroundAddressRefreshFrom410IsThreadSafeAsync
  - StoreReaderBarrierTest
  - StoreReaderContinuationTokenTestAsync
  - DisposeUnusedStoreResultsOnStoreReaderAsync
- **ConsistencyWriter.WriteAsync**
- **ConsistencyReader.ReadAnyAsync**
- **ConsistencyReader.ReadAsync**
- **ReplicatedResourceClient.InvokeAsync**

**Comment by kirankumarkolli** [comment]
Closing the issue, lets re-open with more context
