### ISSUE TITLE
409 Conflict possible for a CreateContainerIfNotExistsAsync? 

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-cosmos-dotnet-v3#3927]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#37107](https://github.com/Azure/azure-sdk-for-net/issues/37107).

## Details

What's the point of "IfNotExists" if a Conflict would be returned? Based on logs, it seems the client library first does a GET on the container, and if it is found, returns success. So, I guess this is a documentation error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9e96ea8-0b8f-fde0-77a0-743baefcd6c3
* Version Independent ID: 01c62957-c210-85c7-3260-e81328d20a1d
* Content: [Database.CreateContainerIfNotExistsAsync Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.database.createcontainerifnotexistsasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Database.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Database.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by changov** [comment]
Then it's a bug. The "IfNotExists" suffix explicitly sets an expectation of no error if the container exists. Either the client library should catch a Conflict from the server, read the container properties, and confirm they match the ones it was given; or the server should implement similar idempotent behavior for creation. Resources get created via an HTTP PUT in Azure, which explicitly requires idempotency. 

[I don't see how I can reactivate this issue. Please do so.]

**Comment by ealsur** [comment]
You are comparing with Azure resource creation but that is done through Azure Resource Manager (ARM) templates ,this is not the same scenario as this is a data plane SDK, not a management plane SDK and does not interact with ARM.

You can use ARM to handle your account creation including support for defining databases and containers as part of the ARM template, which won't be done using this SDK.

**Comment by ealsur** [comment]
Maybe if ARM aligns with your expectations, then using the Management SDK (Azure.ResourceManager.CosmosDB) would be better for your case, it has the plus that it also works when using MSI authentication. Data Plane SDK (Microsoft.Azure.Cosmos) does not allow management operations when using MSI (https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#permission-model)
