### ISSUE TITLE
Subpartitioning: Query with top 50 results are getting into infinite loop.

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#3933]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
If customer has a hierarchal partition key
`select * from c ` query with partiontion is working but `select top 50 * from c` query is going into infinite loop.

**Expected behavior**
`select top 50 * from c` query should return top 50 results

**Environment summary**
SDK Version: 3.25.0
OS Version (e.g. Windows, Linux, MacOSX) any

**Comment by ealsur** [comment]
Similar to https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3865

**Comment by sourabh1007** [comment]
Issue is fixed in attached PR.
