### ISSUE TITLE
We see unexpected huge number of call too https//<account>.documents.azure.com/addresses/?$resolveFor=dbs

### ISSUE THREAD

**Issue by maximecaron** [Azure/azure-cosmos-dotnet-v3#3958]
**Is your feature request related to a problem? Please describe.**
We have an Asp.net core app that is doing a single request to CosmosDB using primary key.
But in Application Insight we see that CosmosDB Client is doing lot request to "https//<account>.documents.azure.com/addresses/?$resolveFor=dbs..." for a each time.
This should not be required "for each request" and this is caused by what I assume is lazy initialization of the client object. 

**Describe the solution you'd like**
Is there a way to make sure this doesn't happen in the critical path.

**Describe alternatives you've considered**
We tried using  EntityFramework DBContext Pooling and it didn't not resolve the problem.

The sequence of request look like this each time:

1. https://skylarc-global-test-eastus.documents.azure.com/dbs/skylarc-global/colls/ServiceContainer
2. https://skylarc-global-test-eastus.documents.azure.com/dbs/BAcUAA==/colls/BAcUAO1zpr8=/pkranges
3. https://skylarc-global-test-eastus.documents.azure.com//addresses/?$resolveFor=dbs%2fBAcUAA%3d%3d%2fcolls%2fBAcUAO1zpr8%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=16
4. https://skylarc-global-test-eastus.documents.azure.com//addresses/?$resolveFor=dbs%2fBAcUAA%3d%3d%2fcolls%2fBAcUAO1zpr8%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=18

**Comment by ealsur** [comment]
These are initialization calls and should happen only once when the client instance is created. See https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/sdk-connection-modes#routing

This most probably means you are not following the Singleton pattern and new client instances are created for every request going through.

Please check your code implementation.

One easy way to confirm is if you can [capture diagnostics](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-dotnet-sdk#capture-diagnostics) for any operation, the number of client instances should be always 1.
