### ISSUE TITLE
Can't Set Value to Null using Patch Operation

### ISSUE THREAD

**Issue by brandonsmith86** [Azure/azure-cosmos-dotnet-v3#3959]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When using `PatchOperation.Replace`, I am unable to set value to null.  I have tried both `null` and `new JProperty(propName, null).Value`.  The latter was attempted due to recommendation in #2931.

**To Reproduce**
This is the code used to create `PatchOperation`: `PatchOperation.Replace($"/{cosmosPropName}", propValue ?? createNullValue(cosmosPropName))`.

`propValue` is type `object?`.  `createNullValue()` creates the `JProperty` mentioned in the description.

**Expected behavior**
I would expect the property to be set to null value.  Below example assumes description property is being set to null:
``` json
{
 "id": "adfda-asdgasd-adsfasdf",
  "partition_key": "aigeqwg-iuiou-qryqer",
  "description": null
}
```
  
**Actual behavior**
Description property is unchanged.

**Environment summary**
SDK Version: 3.32.0
OS Version: Windows 10

**Additional context**
Nothing additional to add.

**Comment by aavasthy** [comment]
@brandonsmith86 I am able to replace the property value with null using the latest SDK version https://www.nuget.org/packages/Microsoft.Azure.Cosmos. You would need to explicitly specify the type argument for 'Replace' method.

Code example:
 ```
 ItemResponse<Product> response = await container.PatchItemAsync<Product>(
            id: newItem.id,
            partitionKey: new PartitionKey(newItem.category),
            patchOperations: new[] { PatchOperation.Replace<string>($"/{cosmosPropName}", null) });
```

Please let me know if you run into any issues with this.

**Comment by brandonsmith86** [comment]
Hi @aavasthy.  Thank you for spending the time to reproduce.  Do you think my problem is version, or lack of generic type?  With my current implementation, I would not be able to supply type as I'm [using reflection](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.propertyinfo.getvalue?view=net-6.0#system-reflection-propertyinfo-getvalue(system-object)) to get the value, which only provides `object?` type.

**Comment by aavasthy** [comment]
@brandonsmith86 Please try with the latest version because I don't see SDK Version: 3.32.0 in here https://www.nuget.org/packages/Microsoft.Azure.Cosmos.
I was able to update the property name even with this code 

```
string val = null;
ItemResponse<Product> response = await container.PatchItemAsync<Product>(
    id: newItem.id,
    partitionKey: new PartitionKey(newItem.category),
    patchOperations: new[] { PatchOperation.Replace($"/propertyName", val) });
```

**Comment by brandonsmith86** [comment]
@aavasthy Decided to give it a try today.  The code that I posted above did not clear out the property.  Very curious...

**Comment by brandonsmith86** [comment]
@aavasthy Found an issue in my logic.  Updating versions _does_ resolve it.  Thank you!

**Comment by brandonsmith86** [comment]
Closing this issue since updating fixed my issue.
