### ISSUE TITLE
Patterns/best practices for maintaining multiple cosmos DB account connections

### ISSUE THREAD

**Issue by pratyush-prateek** [Azure/azure-cosmos-dotnet-v3#3968]
## Background

I am currently working on a project which is a multi-tenant PaaS service based on micro-services architecture. The database layer logic requires writing to multiple different cosmos DB accounts. Think it as a multi-tenant setting where each tenant has a separate cosmos DB account. For that, we need to maintain multiple cosmos clients in memory so that the same can be used to perform the database operation when request comes from different tenants. Also, the compute is shared for all the tenants. 

## Enquiry
I wanted to know if maintaining multiple cosmos clients in memory could cause an issue here or not, given the maximum number of cosmos DB connections could go up-to 100. Issues being, memory overflow, port exhaustion etc. If yes, what could be a good practice here.

**Comment by ealsur** [comment]
@jcocchi / @kirankumarkolli This sounds like a good documentation article to tackle, might be worth brainstorming and see what we can come up with.

**Comment by jackbond** [comment]
Couple questions

1) Do you require separate accounts, or merely separate databases?
2) If you require separate accounts, I'm curious how you intend to share compute across accounts? (I don't think that's supported.)

**Comment by pratyush-prateek** [comment]
@jackbond 

1. We require multiple cosmos DB accounts per tenant. Not the databases.
2. The compute is currently shared. We have a primary and a secondary kubernetes cluster (for failover) per scale unit. For simplification, you can assume that the cosmos DB account details such as the account name and endpoint would be a part of the request only so that a request can identity which cosmos account it has to work with.

**Comment by ealsur** [comment]
@pratyush-prateek Does this help? https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/best-practice-dotnet#best-practices-for-multi-tenant-applications
