### ISSUE TITLE
Unkown calls to offers endpoint

### ISSUE THREAD

**Issue by festivus** [Azure/azure-cosmos-dotnet-v3#3971]
I don't know if this is a bug or not or if it's coming from the SDK. I'm using 3.35.1 in direct mode and I have a serverless account setup. When I look at the Insights page for the account I'm seeing requests being made every hour or so (sometimes 2 hours, sometimes a longer break). These are not calls coming from our app, there actually isn't any activity from our app. When I drill down into the logs it appears something is making calls to the offers endpoint. For Ex:

OperationName: Update
ConnetionMode: Gateway
UserAgent: MasterService
RequestResourceId: offers/VwPH
ClientIpAddress: 40.78.226.49

Does anyone know where this is coming from and why?

I created a ticket in Azure for this but they've not been much help.

**Comment by festivus** [comment]
> Can you please provide more details on this? May be a screenshot of what you are seeing?
> 
> May I know what's the concern here, you just want to know for your information, or you are seeing any misbehavior by SDK due to these calls?

I don't know where they are coming from. I didn't think it was the SDK but wanted to make sure. Must be something with the cosmos service itself, but Azure support has been useless to this point in answering it.

**Comment by ealsur** [comment]
@festivus Can you please share your support case number privately? My email is `maquaran{at}microsoft.com`. I'll see how we can streamline the support. I'm sorry about this support experience.
