### ISSUE TITLE
Warnings logged on response code 304

### ISSUE THREAD

**Issue by mortenbock** [Azure/azure-cosmos-dotnet-v3#3972]
**Describe the bug**
When using the change feed processor, the Cosmos api will often return status 304, to indicate that there are no changes.

This causes an error to be logged with a message about LatencyOverThreshold, which is not actually the case. The response time is below the limit, but the condition also requires that the response code `.IsSuccess()` which means 200-299.

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/1760256/adb6b06a-b2bd-4c29-8749-fa1284bbfb53)

This seems to be the line causing this:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1981fc121408deff3204d50e941dbf4825e035f6/Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/Filters/DiagnosticsFilterHelper.cs#L34

**Expected behavior**
I would expect to only get LatencyOverThreshold warning logged when the latency threshold is exceeded.

If the response has an error code, that should be a different warning/error message, and in this case 304 status is not an error.

**Comment by sourabh1007** [comment]
Thanks for pointing it out @mortenbock , fixing it as part of attached PR. it should be available in next release
