### ISSUE TITLE
IfMatchEtag on ReadItemAsync not honoured

### ISSUE THREAD

**Issue by rudiv** [Azure/azure-cosmos-dotnet-v3#3976]
**Describe the bug**
`IfMatchEtag` does not appear to be working as described.

The documentation states:
> Most commonly used with the Delete* and Replace* methods of [Container](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container?view=azure-dotnet) such as [ReplaceItemAsync<T>(T, String, Nullable<PartitionKey>, ItemRequestOptions, CancellationToken)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.replaceitemasync?view=azure-dotnet#microsoft-azure-cosmos-container-replaceitemasync-1(-0-system-string-system-nullable((microsoft-azure-cosmos-partitionkey))-microsoft-azure-cosmos-itemrequestoptions-system-threading-cancellationtoken)) but can be used with other methods like [ReadItemAsync<T>(String, PartitionKey, ItemRequestOptions, CancellationToken)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readitemasync?view=azure-dotnet#microsoft-azure-cosmos-container-readitemasync-1(system-string-microsoft-azure-cosmos-partitionkey-microsoft-azure-cosmos-itemrequestoptions-system-threading-cancellationtoken)) for caching scenarios.

I have witnessed this working previously on an UpsertItem call as well as a Replace call.

However, it does not appear to work on ReadItemAsync. This can be verified relatively simply.

**To Reproduce**

```
var etag = "....";
var result = await container.ReadItemAsync<T>(id, new PartitionKey(partitionKey), new ItemRequestOptions {
    IfMatchEtag = etag
});
if (result.ETag != etag) {
    throw new Exception("Cosmos returned document with mismatched ETag");
}
```

**Expected behavior**
I would expect a `CosmosException` with either a `PreconditionFailed` or `Conflict` (although the latter is not so semantic) status.

**Actual behavior**
The item is returned without issue, with a different ETag than what was presented. Status Code is `OK`.

**Environment summary**
SDK Version: .NET 3.35.1
OS Version: Mac OSX, also verified on Linux (App Service), and Windows (another dev machine)

**Additional context**
This can be reproduced in the Javascript SDK.

**Comment by ealsur** [comment]
`Conflict` does not make sense, HTTP 409 is only used if you attempt to create a resource that already exists. In your case, you are reading.

* Where is the `etag` variable value coming from?
* Optimistic Concurrency (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/database-transactions-optimistic-concurrency#optimistic-concurrency-control) is meant to cover concurrent updates to the same document, what is the case of using etag on a read? What are you trying to achieve?

**Comment by rudiv** [comment]
Correct 409 wouldn't make sense as I said in the issue. However, PreCondition failed would do and is what would be expected (as per some other methods).

The documentation for `IfMatchEtag` explicitly states that it supports `ReadItemAsync`, if it doesn't that's fine but the documentation should be updated to reflect this.

Apologies for the lack of clarity on the etag variable, I assumed it would be clear that it is an etag from a document that exists in the database.

As per the documentation, this could be used in a caching scenario. Example is that a document is being stored elsewhere (either in a cache on a mid tier layer, or in a client) and being read, this could be used to determine whether the document needs to be re-read. Another example which matches ours is where a document is client side and being merged with the live document from the server, this check is used to catch the stale document at the point of the merge rather than receiving a newer version, performing the merge, only to fail at the save stage. If this works as the documentation states,  it would avoid unnecessary processing.

Again the issue is easily solved by simply checking after the read at the application level. However if this is truly not meant to be supported, the documentation requires an update.

**Comment by rudiv** [comment]
Thanks for coming back again. I'm aware that this isn't an SDK Issue (the header is indeed sent) - shall I reach out to Azure support instead?

Regardless, the documentation does not reflect the current state of availability with the service. It explicitly states that it can be used alongside ReadItemAsync and I assume everyone that expects the documentation to reflect functionality in the service. Otherwise there might as well be a `ReadItemAsync()` method that does not read an item, which would make no sense.

Again, the ETag (nor where it comes from) for the purpose of this issue is not relevant, it could be `12345`, `abc`, or any other value. The point is that when reading a document with `IfMatchETag` set to this value, it still reads the document.

This is a not a question relating to the usage of the SDK or service, it is an issue with a feature that does not work as intended, with a full reproduction provided (even in its existing form with `...` as the value for the ETag).

Just to entertain the tangent, consider the following:

1. A document is read and sent down to a client (with ETag)
2. The client makes modifications to certain properties on the document
3. The client sends this document to the service (with ETag)
4. The service reads the latest version of the document from Cosmos (with `IfMatchEtag`)
5. The service merges in the properties
6. The service performs a CPU-intensive, long running task to compute other properties on the document
7. The service then saves the document back to Cosmos (with `IfMatchEtag`)

Both stages 4 and 7 should present opportunities with `IfMatchEtag` to reject the update as the version of the document that the client had was out of date. The time between both a) the document being sent to the client and sent back and b) the document being read by the service and the long running compute completing should both be able to reject based on the ETag of the supplied original document.

If the document were to be relatively large, say where reading it may cost 12RUs, in my experience the `IfMatchEtag` fails at 1RU.

**Comment by ealsur** [comment]
> From your scenario list, scenario 4 is what is broken and what I have been trying to demonstrate. The 412 result is not returned, instead, it reads the document correctly.

Thanks for confirming. I'll see if I can get confirmation from the service team and if Reads are not expected to work, we'll update the documentation.
