### ISSUE TITLE
[Per Partition Automatic Failover] Extend Automatic Failover For Single Master Write Requests 

### ISSUE THREAD

**Issue by kundadebdatta** [Azure/azure-cosmos-dotnet-v3#3981]
Acceptance Criteria:

- Today, the per partition automatic failover applies to the multi master accounts. The purpose of this task is to extend the automatic failover for the single master accounts. 
- For a single master account, today there is only one write region. Therefore, for failover for the write requests, we will need to mark one of the read regions as a write region and start failing over to that particular region.

**Comment by philipthomas-MSFT** [comment]
@philipthomas-MSFT setting up a meeting with Backend HA team to go over test scenarios in real time and confirming we have all the information needed in their documentation to reproduce.

**Comment by philipthomas-MSFT** [comment]
Meeting done.
