### ISSUE TITLE
[Internal] Client Telemetry Public API Proposal

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#3983]
### Background
As per latest discussion, to get align with Java API and avoid confusion with feature name. We decided to use "Client Telemetry" as a parent feature under which there will be 2 kind of telemetry covered as of now:
**1. Send Client Diagnostic Metrics To Service :** Sending telemetry metrics to Microsoft. 
> Read more about it here: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/observability.md#send-telemetry-from-sdk-to-service-private-preview

**2. Distributed Tracing:** Sending Activities with operation level or network level information to customer's APM tool like AppInsights (May be in future metrics will also be covered). 
> Read more about it here: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/observability.md#distributed-tracing-preview

We are fine if Java API and .Net API doesn't look exactly similar. Here idea is to make sure, it should not confuse customer.

### Java Public API looks like this:

**CosmosClientBuilder** 
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/6362382/d8f954c7-a9d7-4f9d-9e85-35610bc9950c)

**CosmosClientTelemetryConfig** 
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/6362382/0d65ed2f-d062-4920-974f-7fd29405ae74)

**CosmosDiagnosticsThresholds**
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/6362382/17308baf-dbd3-4427-969d-b8376fdcfdad)

### Proposed Public API in .Net SDK to control above features:

By default, both of the above features will be enabled in SDK. 
#### Why?
**1. Send Client Diagnostic Metrics To Service:** It is controlled by portal hence enabling it in SDK, by default, will give seamless experience to the customer where they can just enable it from portal and we can see data flowing to us without any code change. There won't be any perf impact/overhead on sdk, if it is disabled on portal and enabled on SDK as Portal setting has higher priority.
**2. Distributed Tracing**: It works on subscription model, until unless there is no subscriber, it won't generate any activity. Hence no overhead. This feature flag is introduced to support appinsight SDK as customer cannot de-subscribe any activity source there. 

> Want to see distributed tracing in action?
>**OpenTelemetry Way:** 
>https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry
>**AppInsight SDK Way:** 
>https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights
>

In both the cases, there is a scenario where customer would want to disable individual telemetry from SDK.

#### Public APIs

**CosmosClientBuilder** 
| Class Name | Method Name | Return Type | Comment|
|--------|----------|----------|--------|
| CosmosClientBuilder | WithClientTelemetryOptions(CosmosClientTelemetryOptions options) | Returns the client telemetry config instance for this builder| Single function to control/configure any kind of telemetry |

**CosmosClientOptions** 
| Class Name | Method Name | Return Type |  Default value | Comment|
|--------|----------|----------|--------|--------|
| CosmosClientOptions| CosmosClientTelemetryOptions | Set ClientTelemetry Options | new CosmosClientTelemetryOptions() _(Loaded with default values)_ | Option to control/configure any kind of telemetry |

**CosmosClientTelemetryOptions**
| Class Name | Method Name | Return Type | Default value | Comment|
|--------|----------|----------|--------| --------| 
| CosmosClientTelemetryOptions  | DisableSendingMetricsToService() | `void` | false | Disable sending telemetry data to the service i.e. Microsoft |
| CosmosClientTelemetryOptions | DisableDistributedTracing() `PREVIEW` | `void` |   `PREVIEW` ==> false |Disable Distributed Tracing feature, it means it will stop generating activities even if there are subscribers |
| CosmosClientTelemetryOptions | CosmosThresholdOptions(CosmosThresholdOptions options)  `PREVIEW` | `void` |  new CosmosThresholdOptions() | Options to configure threshold for distributed tracing (Later we can use this same config for opentelemetry metrics, similar to Java) |

**CosmosThresholdOptions**
| Class Name | Method Name | Return Type | Default value | Comment |
|--------|----------|----------|--------|--------|
| CosmosThresholdOptions| NonPointOperationLatencyThreshold(TimeSpan span)  `PREVIEW` | `void` | 3s | Set when `LatencyOverThrehold` event with diagnostic string should be created for non-point operations |
| CosmosThresholdOptions| PointOperationLatencyThreshold(TimeSpan span)  `PREVIEW` | `void` | 1s | Set when `LatencyOverThrehold` event with diagnostic string should be created for point operations |

**Comment by jcocchi** [comment]
I recommend `DisableSendingMetricsToService()` instead of `DisableClientTelemetryToService()` to avoid overloading "Client Telemetry". This also aligns better with the proposed feature name of "Send Client Diagnostic Metrics To Service"

**Comment by FabianMeiswinkel** [comment]
Please check whether you really want to go down the road of putting the latency thresholds behind a class named explicity for tracing only

In Java DiagnosticThresholds have more meaning than for tracing - and I think it has proven to be very useful
- used even to decide whether to emit Request-Level metrics - metrics can have dimensions based on replicaId - allowing to also restrict when to emit these metrics allows to avoid overloading the metric system with metrics having way too high cardinality on dimensions
- used for distributed tracing
- and used for logging (probably not relevant for .Net)

So, main ask is to check whether you forsee any ask to also use the same thresholds for metrics - and of course whether .Net needs mroe grnularity on thresholds than just latency (java allows customizing whether to consider a threshold violation based on StatusCode+SubStatusCode), RU-usage, payload size and latency

**Comment by kirankumarkolli** [comment]
Eventually, Is distinction between metrics and push to client telemetry endpoint required?
If so do API needs to reflect that?

**Comment by kirankumarkolli** [comment]
PointOperation: Very unintutive, how is it done for JAVA?

**Comment by sourabh1007** [comment]
In Java API metrics means Open telemetry Metrics. 

Thresholds are applicable only for the data which we are sending to customer

**Comment by sourabh1007** [comment]
> PointOperation: Very unintutive, how is it done for JAVA?

there it has similar name. Please refer above Java API screenshots in the description.

**Comment by kirankumarkolli** [comment]
CosmosDiagnosticsThreshold: Is it applicable to all diagnostics or only for DistributedTracing?

**Comment by jcocchi** [comment]
Sounds like right now these thresholds will only apply to DistributedTracing, but eventually they may also apply to other metrics/ telemetry.

+1 on adding a threshold for RU charge and payload size. 

How would a status code threshold work? We already filter out sending diagnostics for any successful request in Distributed Tracing, so would this be if they want further control over non-success scenarios or is the suggestion to give the user full control and we don't do any filtering by default?

**Comment by sourabh1007** [comment]
@kirankumarkolli  These threshold configurations are applicable for events generated with diagnostics string as part of Distributed Tracing feature.

@jcocchi  regarding, adding a threshold for RU charge and payload size. Right now, we don't have any requirement or ask for .Net SDK. We need to discuss if we want to implement it. cc @kirankumarkolli 

Regarding status code threshold, are you talking about `SetFailureHandler` function? From description, it sounds like that only, customer can filter the events by statuscode and substatuscode. @FabianMeiswinkel  can confirm it.

**Comment by sourabh1007** [comment]
@kirankumarkolli  @jcocchi @FabianMeiswinkel are we closing on above proposal?

**Comment by jcocchi** [comment]
LGTM

**Comment by kirankumarkolli** [comment]
Offline discussion
<img width="574" alt="image" src="https://github.com/Azure/azure-cosmos-dotnet-v3/assets/6880899/ca814d06-b0b0-40e1-becb-601b717e32b1">

**Comment by jcocchi** [comment]
Looks like all the proposed changes are reflected in the above design now. Are we good to close on this?

**Comment by sourabh1007** [comment]
With last discussion with Compute Team, they want us to disable this feature by default in SDK Private preview. So that Client Config API call can be limited to compute gateway. Hence changing `DisableSendingMetricsToService()` API to `SendingMetricsToService(bool enabled)`  
cc @kirankumarkolli @jcocchi

**Comment by jcocchi** [comment]
If we change this to `EnableSendingMetricsToService` now, will it be confusing for customers if we switch back to `DisableSendingMetricsToService` for GA?
