### ISSUE TITLE
how to generate 403 requests in azure monitoring metrics view

### ISSUE THREAD

**Issue by imhdev** [Azure/azure-cosmos-dotnet-v3#3984]
By default, in the TotalRequests metrics view there is an option to select/filter requests based on the set of values the metric provide. Is there any other way to generate a view for 403 requests?

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/43098320/e5ca3668-8d41-4e89-82e9-f2b0c128f39b)

**Comment by ealsur** [comment]
@imhdev How is this issue related to the Cosmos DB .NET SDK?

**Comment by imhdev** [comment]
Oops! Will post to the azure monitor issues board, thanks!
