### ISSUE TITLE
Wrong results when using DISTINCT in a cross-partition subquery

### ISSUE THREAD

**Issue by gukoff** [Azure/azure-cosmos-dotnet-v3#3986]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**

The SDK seems to have a trick for handling the cross-partition DISTINCT queries. This leads to the wrong results when DISTINCT is used in a subquery.

When SDK detects (by [asking the API about QueryInfo](
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8d2691b984dac9a1c668d37f74cbfe306dd03671/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs#L230)) a cross-partition query with DISTINCT, it sends this query to the individual partitions, then [deduplicates the streams](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8d2691b984dac9a1c668d37f74cbfe306dd03671/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Distinct/DistinctQueryPipelineStage.Compute.cs#L109C3-L109C3) from each partition into a single set of distinct values on the client.

(please correct me if I'm wrong in the details - this line suggests it's across not partitions but [_pages_](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8d2691b984dac9a1c668d37f74cbfe306dd03671/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Distinct/DistinctQueryPipelineStage.cs#L14))

This trick only works for the simple queries like `SELECT DISTINCT ... from c` but does not work correctly for the queries that are more complex.

For example, if there is a subquery with DISTINCT, the `QueryInfo` fails to recognize it as a DISTINCT query at all (it get assigned `DistinctQueryType.None`), which disables the deduplication mechanism.

**To Reproduce**

Imagine a DB with 2 physical partitions. Each partition contains millions of documents with a property `"val"`  that randomly takes values `"1"` or `"2"`.

Now this works:

```sql
SELECT DISTINCT VALUE c.val FROM c
> ["1", "2"]
``` 

But this does not:

```sql
SELECT * FROM (
  SELECT DISTINCT VALUE c.val FROM c
)
> ["1", "1", "2", "2"]
``` 

And this does not:

```sql
SELECT COUNT(subCollection.x) FROM (
  SELECT DISTINCT VALUE c.val as x FROM c
) as subCollection
> 4
``` 

(the actual scenario where I see the issue has not 2 but 100K distinct values in the set. But I believe it does not matter)

**Expected behavior**

An exception that SDK can't handle such a query correctly.

Possibly with an ability to suppress the exception and proceed if the user enables some "I know what I'm doing" flag.

**Actual behavior**

Unable to properly perform DISTINCT cross-partition.
Behaviour as if some duplicates were still returned by the subquery.

**Environment summary**

SDK Version: 3.35.1
OS Version: MacOSX

**Additional context**

This problem is not specific to .NET SDK, it reproduces on the portal as well.

<img width="511" alt="Screenshot 2023-07-12 at 12 46 15" src="https://github.com/Azure/azure-cosmos-dotnet-v3/assets/5655837/2bd91cc8-0eee-4237-8e66-4700ca2584c3">

**Comment by adityasa** [comment]
@gukoff this is a known limitation and we have an item that tracks adding validation to detect and disallow this on our side. We don't have an ETA for this as yet.

**Comment by gukoff** [comment]
@adityasa understsood.

I have a follow-up question: how does the SDK get all the results for the DISTINCT query without ORDER BY, if there's [no continuation token](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/pagination#continuation-tokens) for such queries? SDK seems to be able to page through the results just fine, even when there's many pages with results. What kind of queries does it actually send to the Cosmos server to get each page?

**Comment by bchong95** [comment]
One way of handling this is to look at the QueryPlan (I think it's called IL) instead of the query text:

```sql
SELECT DISTINCT VALUE c.val FROM c
```

Which will have the following plan:

```
Project($0)
  Aggregate(groupings = {c.val}) // GROUP BY without AggregateCalls is just DISTINCT
```

```sql
SELECT * FROM (
  SELECT DISTINCT VALUE c.val FROM c
)
```

We emit:

```
Project(STAR)
   Project($0)
      Aggregate(groupings = {c.val}) // GROUP BY without AggregateCalls is just DISTINCT
```

Which will optimize to

```
Project($0)
   Aggregate(groupings = {c.val}) // GROUP BY without AggregateCalls is just DISTINCT
```
^ Note that this is the same QueryPlan as the original

```sql
SELECT COUNT(subCollection.x) FROM (
  SELECT DISTINCT VALUE c.val as x FROM c
) as subCollection
```

Will emit:

```
Project($1)
   Aggregate(groupings = {$0}, aggregates=[COUNT()]) // Doing the COUNT separately AFTER the DISTINCT 
      Aggregate(groupings ={c.val}) // GROUP BY without AggregateCalls is just DISTINCT
```

Note that this query plan is just breaking the COUNT + DISTINCT into two separate aggregation stages, which is great, since the SDK already has execution to support cross partition aggregate + GROUP BY. You can think of this as two-phase aggregation. This also means that as a "workaround" users can run a DISTINCT query and locally take the count, to simulate this query. 

There is also an optimization where you can push both the COUNT and DISTINCT down to the individual partitions if you know that the partitions don't overlap in data.

**Comment by adityasa** [comment]
@gukoff apologies for a late response and you may have already found/guessed the answer by now. The continuation token does exist in such cases, it's just that it's not exposed by the SDK to client code.
