### ISSUE TITLE
Azure Cosmos Db Group By with Select statement

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-cosmos-dotnet-v3#3991]
### Discussed in https://github.com/Azure/azure-cosmos-dotnet-v3/discussions/3989

<div type='discussions-op-text'>

<sup>Originally posted by **ssghoda** July 17, 2023</sup>
Our Cosmos Db Container for Doctors is partitioned by networkId. Each Doctor document has id, fullName, npi, providerType, gender and then there is an array of offices the doctor is working for that networkId.

```
{
"id": "",
"fullName": "",
"npi": "",
"providerType": "",
"gender": "",
"networkId": "",
"offices": [
  {
  "officeId": "",
  "officeName": "",
  "address": ""
  },
  {
  "officeId": "",
  "officeName": "",
  "address": ""
  }
]
}
```

I want to write a query using Group By clause where I want to gather all offices under all networkId partitions for a given doctor's npi.

I am trying something like this and need help writing something which can help my goal:

```
SELECT DISTINCT c.fullName, c.providerType, c.gender, c.npi, [c.offices] as offices
FROM c
WHERE c.npi = 'something'
GROUP BY c.fullName, c.providerType, c.gender, c.npi
```</div>

**Comment by adityasa** [comment]
@ssghoda this question is regarding app/query authoring and you may get better help using forums like stackoverflow for this. Github repo and issues are reserved to track development and issues related to the product.

On an unrelated note, you may get better help if you provide more information such as sample documents, expected output, query you are using and actual output.
