### ISSUE TITLE
.NET 8 Preview 6 and Emulator

### ISSUE THREAD

**Issue by hyspdrt** [Azure/azure-cosmos-dotnet-v3#3992]
**Describe the bug**
Connecting to and attempting to create a database if it doesn't exit and creating a container if doesn't exist using the Emulator, fails to connect, and retries several times over the course of ~7 minutes, ultimately failing and terminating the application.

<pre>
11:01:43:724	DocDBTrace Information: 0 : DocumentClient with id 1 initialized at endpoint: https://localhost:8081/ with ConnectionMode: Direct, connection Protocol: Tcp, and consistency level: null
...truncated
11:08:37:574	DocDBTrace Information: 0 : ClientRetryPolicy: ShouldRetryOnEndpointFailureAsync() Not retrying. Retry count = 121, Endpoint = https://127.0.0.1:8081/
</pre>

**To Reproduce**
Using VS2022 Preview, the latest Cosmos Db SDK Version (3.35.2 or 3.35.1), the latest version of the Emulator (2.14.12), change the TFM from net7.0 to net8.0 (preview 6) in a sample c# api project, start the Emulator (with the same parameters as used for unit tests as found in your contribute.md), then run the sample application (minimal api app - see below). 

<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aec214fb-d52c-479e-a284-671f150a5867</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0-preview.6.*" />
		<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.35.2" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

</Project>

appsettings.json
<pre lang='json'>
{
	"Logging": {
		"LogLevel": {
			"Default": "Trace"
		}
	},
	"AllowedHosts": "*"
}
</pre>

Use app secrets to store the emulator connection string 
<pre lang='json'>
{
    "ConnectionStrings": {
        "DB1": "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
     }
}</pre>

<pre lang='csharp'>
using Microsoft.Azure.Cosmos;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

using var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment()) {
	app.UseSwagger();
	app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.MapGet("/weatherforecast", () => {
	// truncated for brevity
})
.WithName("GetWeatherForecast")
.WithOpenApi();

// BEGIN - COSMOS DB

var dbConnectionString = builder.Configuration.GetConnectionString("DB1");
using CosmosClient client = new(dbConnectionString);

Database database = await client.CreateDatabaseIfNotExistsAsync(
	id: "adventureworks"
);

var response = await database.CreateContainerIfNotExistsAsync("items", "/id");
var policy = response.Resource.IndexingPolicy;

// END - COSMOS DB

app.Run();

internal record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary) {
	public int TemperatureF => 32 + (int)(this.TemperatureC / 0.5556);
}</pre>

**Expected behavior**
For it to not throw exceptions, connect and work as intended, same as when using .net7.0

**Actual behavior**
throws exceptions for 7 minutes before finally terminating.

**Environment summary**
SDK Version: 3.35.2 (or 3.35.1)
Emulator Version: 2.14.12
OS Version Windows 11 Pro 22H2 (all updates applied) - OS Build: 22621.1992

**Additional context**

If you use .net8.0 (preview 6) against regular Azure and not the emulator, it works fine.

If I use a custom HttpClientHandler that allows invalid certificates AND use Gateway mode, it work with just a small number of logged exceptions.

This is the relevant console logging, with the center section being repeated over and over...
<pre>
11:01:45:974	DocDBTrace Information: 0 : TimerPool Created with minSupportedTimerDelayInSeconds = 1
11:01:45:974	DocDBTrace Information: 0 : Creating RNTBD TransportClient with options Rntbd.TransportClient.Options
11:01:45:974	  OpenTimeout: 00:00:05
11:01:45:974	  RequestTimeout: 00:00:06
11:01:45:974	  TimerPoolResolution: 00:00:01
11:01:45:974	  MaxChannels: 65535
11:01:45:974	  PartitionCount: 1
11:01:45:974	  MaxRequestsPerChannel: 1
11:01:45:974	  ReceiveHangDetectionTime: 00:01:05
11:01:45:974	  SendHangDetectionTime: 00:00:10
11:01:45:974	  IdleTimeout: -00:00:01
11:01:45:974	  UserAgent: cosmos-netstandard-sdk/3.35.2|1|X64|Microsoft Windows 10.0.22621|.NET 8.0.0-preview.6.23329.7|N| Suffix: 
11:01:45:974	  CertificateHostNameOverride: 
11:01:45:974	  LocalRegionTimeout: 00:00:05
11:01:45:974	  EnableChannelMultiplexing: False
11:01:45:974	  MaxConcurrentOpeningConnectionCount: 5
11:01:45:974	  Use_RecyclableMemoryStream: False
11:01:45:974	  Use_CustomDnsResolution: False
11:01:45:974	  IsDistributedTracingEnabled: False
11:01:45:974	
11:01:45:974	DocDBTrace Information: 0 : TimerPool Created with minSupportedTimerDelayInSeconds = 1
11:01:45:974	DocDBTrace Information: 0 : Resolving Master service address, forceMasterRefresh: False, currentMaster: 
11:01:45:974	Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Private.CoreLib.dll
11:01:45:974	Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Private.CoreLib.dll
.... truncated
11:01:47:999	Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
11:01:47:999	DocDBTrace Warning: 0 : ClientRetryPolicy: Gateway HttpRequestException Endpoint not reachable. Failed Location: https://127.0.0.1:8081/; ResourceAddress: dbs/adventureworks
11:01:47:999	DocDBTrace Information: 0 : GlobalEndpointManager: Marking endpoint https://127.0.0.1:8081/ unavailable for read
11:01:47:999	DocDBTrace Information: 0 : Current WriteEndpoints = (https://127.0.0.1:8081/) ReadEndpoints = (https://127.0.0.1:8081/)
11:01:47:999	DocDBTrace Information: 0 : Endpoint https://127.0.0.1:8081/ unavailable for Read added/updated to unavailableEndpoints with timestamp 07/18/2023 18:01:47
11:01:47:999	DocDBTrace Information: 0 : GlobalEndpointManager: Marking endpoint https://127.0.0.1:8081/ unavailable for Write
11:01:47:999	DocDBTrace Information: 0 : Current WriteEndpoints = (https://127.0.0.1:8081/) ReadEndpoints = (https://127.0.0.1:8081/)
11:01:47:999	DocDBTrace Information: 0 : Endpoint https://127.0.0.1:8081/ unavailable for Write added/updated to unavailableEndpoints with timestamp 07/18/2023 18:01:47
11:01:47:999	DocDBTrace Information: 0 : Current WriteEndpoints = (https://127.0.0.1:8081/) ReadEndpoints = (https://127.0.0.1:8081/)
11:01:48:987	DocDBTrace Information: 0 : Resolving Master service address, forceMasterRefresh: False, currentMaster: 
11:01:48:987	Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Private.CoreLib.dll
11:01:48:987	Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Private.CoreLib.dll
11:01:48:987	Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll
... truncated
11:08:38:065	Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
11:08:38:065	DocDBTrace Information: 0 : TimerPool Disposing
11:08:38:065	DocDBTrace Information: 0 : TimePool Disposed
11:08:38:065	DocDBTrace Information: 0 : Rntbd.TransportClient disposed.
11:08:38:065	DocDBTrace Information: 0 : TimerPool Disposing
11:08:38:065	DocDBTrace Information: 0 : TimePool Disposed
11:08:38:065	DocDBTrace Information: 0 : Rntbd.TransportClient disposed.
11:08:38:065	Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
11:08:38:065	Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
11:08:38:065	DocDBTrace Information: 0 : Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
11:08:38:065	Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
11:08:38:065	DocumentClient with id 1 disposed.
11:08:38:065	Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
11:08:38:065	The thread 0x6f94 has exited with code 0 (0x0).
11:08:38:417	Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
11:08:38:417	An unhandled exception of type 'System.Net.Http.HttpRequestException' occurred in System.Private.CoreLib.dll
11:08:38:417	The SSL connection could not be established, see inner exception.
</pre>

**Comment by sourabh1007** [comment]
It is not SDK issue as SDK doesn't manage any certificates.

**Comment by sourabh1007** [comment]
You can do something like this as a workaround. It will skip the server certificate check.

```
CosmosClient(endpoint, key, new CosmosClientOptions
            {
                SerializerOptions = new CosmosSerializationOptions
                {
                    PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
                },
                HttpClientFactory = () =>
                {
                    HttpMessageHandler httpMessageHandler = new HttpClientHandler
                    {
                        ServerCertificateCustomValidationCallback = (_, _, _, _) => true
                    };
                    return new HttpClient(httpMessageHandler);
                },
                ConnectionMode = ConnectionMode.Gateway
            });
```

**Comment by hyspdrt** [comment]
For others that may end up here... this was reported on the dotnet runtime site, not too long after I submitted here. And is a regression from Preview 5. It is affected in both Preview 6 and Preview 7

[SSL RemoteCertificateNameMismatch when targeting net8.0](https://github.com/dotnet/runtime/issues/89118)

**Comment by hyspdrt** [comment]
> It is not SDK issue as SDK doesn't manage any certificates.

wouldn't you still want to handle the failure knowing it will never succeed, versus just blindly trying over and over?

**Comment by hyspdrt** [comment]
Here's an alternative, that only returns true (bypassing the cert failure) when there is a Subject Alternative Name with the loop-back IPAddress

<pre lang='csharp'>
var ip = "127.0.0.1"; // or whatever IP Address you want to allow
var serverIPAddress = IPAddress.Parse(ip);
var handler = new HttpClientHandler {
    ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => {
       
        if (sslPolicyErrors == SslPolicyErrors.None) {
            return true;
        }

        if (sslPolicyErrors == SslPolicyErrors.RemoteCertificateNameMismatch) {
            foreach (var ext in cert!.Extensions) {
                if (ext is X509SubjectAlternativeNameExtension san) {
                    foreach (var ipAddr in san.EnumerateIPAddresses()) {
                        //Console.WriteLine(ipAddr);
                        if (serverIPAddress.Equals(ipAddr)) {
                            return true;
                        }
                    }
                }
            }

        }

        return false;

    }
};
</pre>
