### ISSUE TITLE
No DocumentQuery Linq to SQL evaluation

### ISSUE THREAD

**Issue by Elfocrash** [Azure/azure-cosmos-dotnet-v3#4]
As far as I can see there is no equivalent of `CreateDocumentQuery` that supports a LINQ expression path which is converted to SQL behind the scenes but I can see that the evaluator is still in the code.

Are there plans to support this feature?

**Comment by manigandham** [comment]
According to the 3.0 public preview blog post, the LINQ features are in development.

https://azure.microsoft.com/en-us/blog/azure-cosmos-dotnet-sdk-version-3-0-now-in-public-preview/

**Comment by Elfocrash** [comment]
Gotcha thanks
