### ISSUE TITLE
Items by Partition Key

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-cosmos-dotnet-v3#40]
I’m sure this is obvious but how do I get all items by partiton key? do i still use MaxItems = -1 and does the concurrently option come into play?  

thanks!

**Comment by RobinHSanner** [comment]
IDocumentQuery<T> query =
                DocumentClient.CreateDocumentQuery<T>(
                    UriFactory.CreateDocumentCollectionUri( dbName, collectionName),
                    options )
                    .AsDocumentQuery();

            List<T> results = new List<T>();
            while ( query.HasMoreResults )
            {
                // Accumulate results
            }

Where options if an instance of FeedOptions that has the PartitionKey set.
You can set MaxItems or not.  Setting it to -1 allows the DocumentClient to optimize the number of results that come back in each result set.

**Comment by mpaul31** [comment]
thank you however i am looking how to do the equivalent with the new API SDK 3.

**Comment by j82w** [comment]
There are currently 2 overloads for the query. The first overload only queries a single partition. The second overload does cross partitions queries.  I haven't verified the following code, but this should return all the items for the selected partition key. 

```
List<Family> results = new List<Family>();
var resultSetIterator = container.Items.CreateItemQuery<Family>("SELECT * FROM Families f", partitionKey: "Anderson");
while (resultSetIterator.HasMoreResults)
{
     results.AddRange((await resultSetIterator.FetchNextSetAsync()));
}
```

**Comment by mpaul31** [comment]
thank you that works great! 

one more question, does the maxConcurrency only come into play when performing a cross-partition query?

**Comment by j82w** [comment]
Yes, the max concurrency overload method is only needed when performing cross-partition queries.
