### ISSUE TITLE
FFCF API discussion

### ISSUE THREAD

**Issue by iainx** [Azure/azure-cosmos-dotnet-v3#4007]
# FFCF API Discussion

I've made an initial PR for FFCF (aka AllVersionsAndDeletes) support in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4003 and this is to discuss the potential API

The main API for this feature is the addition of a new `ChangeFeedProcessorBuilder` in `Microsoft.Azure.CosmosDB.Container` which takes a new handler type `AllVersionsAndDeleteChangesHandler<T> (IReadOnlyCollection<ChangeFeedProcessItem<T>> changes, CancellationToken cancellationToken)` which is similar to the existing handlers, but instead of a `IReadOnlyCollection<T>` it wraps `T` in a `ChangeFeedProcessItem` which is a wrapper that contains the current and previous state of `T` and then the metadata.

The code reuses the `ChangeFeedMode` type from the other change feed code, but this necessitates the mode being passed through some other public API.

Currently there are no overloads that pass a default mode, but those could be added if we think they're necessary, I don't know how often they're actually meant to be called by a client.

When thinking about how to do this, I looked at the Java API, but it is a completely different system and I felt it was better to match what we have in the rest of the C# API for simplicity's sake.

API example

```csharp

var builder = container.GetAllVersionsChangeFeedProcessorBuilder<CartAction>("migrationProcessor", (ChangeFeedProcessorContext context, IReadOnlyCollection <ChangeFeedItemChange<CartAction>> changes, CancellationToken cancellationToken) =>
{
    Console.WriteLine(changes.Count + " Changes Received");


    foreach (var change in changes)
    {
    }
}

```

**Comment by kirankumarkolli** [comment]
Existing contract for CFPBuilder is below
```C#
        public override ChangeFeedProcessorBuilder GetChangeFeedProcessorBuilder<T>(
            string processorName,
            ChangesHandler<T> onChangesDelegate)
```

One alternative alternative is 
```C#
        public override ChangeFeedProcessorBuilder GetAllVersionsChangeFeedProcessorBuilder<T>(
            string processorName,
            ChangesHandler<ChangeFeedItem<T>> onChangesDelegate)
```

Its almost the same as existing model, except that new delegate type is not needed. 
Also the method is very explicit about AllVersions (no overload with ChangeMode). 

It kind of also deviates from the existing PULL model API's which I think are convention based right?

**Comment by jcocchi** [comment]
@iainx can you please add an example of how change feed mode would be passed in? I'm having trouble visualizing that. If we can avoid introducing a mode to CFP and instead use a different handler or builder that might be a cleaner solution.

We don't need a new `ChangeFeedProcessorItem` class as we can reuse `ChangeFeedItemChange`. I propose we rename the class to `ChangeFeedItem` for simplicity while this is still in preview.

**Comment by philipthomas-MSFT** [comment]
Reached out to @iainx . No response. Changing ownership to myself.
