### ISSUE TITLE
 Issue with Cosmos DB Emulator on Mac with M2 Chip - ERR_CONNECTION_REFUSED when accessing via Local IP

### ISSUE THREAD

**Issue by maandagdev** [Azure/azure-cosmos-dotnet-v3#4011]
**Describe the bug**
I am encountering an issue while trying to use the Cosmos DB Emulator on my Mac with an M2 chip. When following the Microsoft documentation, I successfully start the emulator using the command below:

```
Microsoft.Azure.Cosmos.Emulator.exe /AllowNetworkAccess /Key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
```

**To Reproduce**
1. Install Parallels and set up a Windows virtual machine.
2. Download and install the Cosmos DB Emulator within the virtual machine.
3. Run the emulator using the provided command.
4. Attempt to access the emulator from my Mac using the local IP obtained from `ipconfig`.
5. Observe the `ERR_CONNECTION_REFUSED` error.

Here's the local IP I'm trying to use: 10.211.55.3

Link to the Microsoft guide I followed: [cosmos-db-local-emulator](https://learn.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21)

**Expected behavior**
I expect to be able to access the Cosmos DB Emulator running on my Windows virtual machine using the local IP address from my Mac.

**Actual behavior**
Currently, when attempting to access the emulator using the local IP, I receive an `ERR_CONNECTION_REFUSED` error.

**Environment summary**
- Cosmos DB Emulator Version: 2.14.12
- OS Version: MacOS: Ventura 13.4.1 (22F82)

**Additional context**
- Parallels network settings: Running in "shared" mode.
- I tried port forwarding via Parallels, but it didn't resolve the issue.
- I attempted using the "nofirewall" flag, deleted emulator contents, disabled the firewall, and added allow rules without success.
- Output of `netstat -a | findstr 8081` shows the emulator listening on `127.0.0.1:8081`, which might be the cause of the problem.

**Comment by sourabh1007** [comment]
Its not CosmosDB SDK issue.

You can create this issue at this place https://github.com/Azure/azure-cosmos-db-emulator-docker/issues
