### ISSUE TITLE
Logic Apps: Cosmos DB Query Items DISTINCT and GROUP BY Continuation Token Issue 410187684

### ISSUE THREAD

**Issue by philipthomas-MSFT** [Azure/azure-cosmos-dotnet-v3#4017]
# Logic App Cosmos DB Query Items DISTINCT and GROUP BY Continuation Token Issue 410187684.
#### _Updating the Logic App Cosmos DB connector to handle how items are drained when **GROUP BY**, **DISTINCT** or **DISTINCT VALUE** is used by the CX._
- Affects the following:
    - _Query items._
      - Use _HasMoreResults_ when **GROUP BY**, **DISTINCT** or **DISTINCT VALUE** is used.
      - Use _Continuation Tokens_ when **GROUP BY**, **DISTINCT** or **DISTINCT VALUE** is not used.
    - _Microsoft Learn documentation needs refreshing._
      - https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/pagination#continuation-tokens (Shaun Cooper and Query team)
        - Including exhaustive use cases. And be more descriptive on **GROUP BY**, **DISTINCT** and **DISTINCT VALUE** to include that this only works for single property SELECT list with ORDER BY.
      - https://learn.microsoft.com/en-us/azure/connectors/connectors-create-api-cosmos-db?tabs=standard#connector-reference (Justine Cocchi and SDK team)
        - Include different use cases and possible links to the Pagination Continuation Tokens documentation.
#### _GROUP BY, DISTINCT or DISTINCT Value._
- Affects the following:
  - **Triggers**
    - _None_
  - **Operations**
    - _Query items._

#### Stakeholders
- Query Team
  - Shaun Cooper
- SDK Team
  - Philip Thomas
  - Justine Cocchi
  - Matias Quaranta
- Logic App Team
  - Philip Thomas

#### Other cleanup and quality of life tasks
- More constants, enumerations, and descriptive comments when needed.
- Workflow testing if possible
  - Will require Cosmos Database and Key Vault accounts

## Resources
TBD
## Branch
philipthomas/cosmosdb_query_items_distinct_continuationtoken_issue_410187684
## PR
TBD

## Not in scope
- Inflight in another Issue and PR
  - Updating the Logic App Cosmos DB connector triggers to use Microsoft.Azure.WebJobs.Extensions.CosmosDB version 4.3.0.
  - Updating Logic App Cosmos DB operations and triggers to use Microsoft.Azure.Cosmos version 3.35.2.
  - Add new ExecuteStoredProcedure Cosmos DB operation.
  - Make all operation's Partition Key input parameter optional using PartitionKey.None under the hood.

## Solutions
- **Option 1**: Can check and validate the query text first as some form of validation. If **GROUP BY**, "DISTINCT" or "DISTINCT VALUE" exists in query text, use (_HasMoreResults_). If no **GROUP BY**, **DISTINCT** or **DISTINCT VALUE** is used use (_Continuation Token_). This is hidden from the CX. I don't like it, but then again, I don't necessary like acting on exceptions in this way. **NOTE: Least optimal design. Too many flaws in this design.**

- **Option 2**: Add a checkbox to the Cosmos DB _Query Items_ UI and default it false. Let the CX decide the behavior for using (_HasMoreResults_), or using (_Continuation Token_). The CX has to be knowledgeable of the side effects of choosing one versus the other. Validation warnings could be enforced as well. **NOTE: Contract breaks due to adding a checkbox. The most explicit optimal design.**

- **Option 3**: Catch the **ArgumentException** when attempting to access _FeedResponse.ContinuationToken_ and drain using this (_HasMoreResults_) instead using (_Continuation Token_). **NOTE: No contract breaks. The most implicit optimal design.**

## Clarification
- If I am using _HasMoreResults_, which _RequestCharge_ and _ActivityId_ should I use? The first one, or the last one?
  - cc @ealsur , @jcocchi 

## Testing
- Regression
  - **Triggers**
    - [ ] _Query items._
      - DISTINCT without ORDER BY using 1 field in SELECT LIST
        - `SELECT DISTINCT c.field1 FROM c`
          - Path: HasMoreResults
      - DISTINCT without ORDER BY using 2 or more fields in SELECT LIST
        - `SELECT DISTINCT c.field1, c.field2 FROM c`
          - Path: HasMoreResults
      - DISTINCT with ORDER BY using 1 field in SELECT LIST
        - `SELECT DISTINCT c.field1 FROM c ORDER BY c.field1`
          - Path: HasMoreResults
      - DISTINCT with ORDER BY using 2 or more fields in SELECT LIST
        - `SELECT DISTINCT c.field1, c.field2 FROM c ORDER BY c.field1, c.field2`
          - Path: BadRequest
            - The order by query does not have a corresponding composite index that it can be served from.
      - DISTINCT VALUE without ORDER BY using 1 field in SELECT LIST
        - `SELECT DISTINCT VALUE c.field1 FROM c`
          - Path: HasMoreResults
      - DISTINCT VALUE without ORDER BY using 2 or more fields in SELECT LIST
        - `SELECT DISTINCT VALUE c.field1, c.field2 FROM c`
          - Path: Invalid query text. Only 1 field is allowed in the SELECT LIST for DISTINCT VALUE
      - DISTINCT VALUE with ORDER BY using 1 field in SELECT LIST
        - `SELECT DISTINCT VALUE c.field1 ROM c ORDER BY c.field1`
          - Path: Continuation Token
      - DISTINCT VALUE with ORDER BY using 2 or more fields in SELECT LIST
        - `SELECT DISTINCT VALUE c.field1, c.field2 FROM c ORDER BY c.field1, c.field2`
          - Path: HasMoreResults
      - DISTINCT VALUE with ORDER BY using 1 field in SELECT LIST but SELECT LIST and ORDER BY LIST have different fields.
        - `SELECT DISTINCT VALUE c.field1 FROM c ORDER BY c.field2`
          - Path: TBD
      - DISTINCT VALUE with ORDER BY using 1 field in SELECT LIST but ORDER BY LIST have more than 1 fields.
        - `SELECT DISTINCT VALUE c.field1 FROM c ORDER BY c.field1, c.field2`
          - Path: TBD
      - GROUP BY
      - Queries without DISTINCT or DISTINCT VALUE should continue to function using Continuation Tokens.

**Comment by jcocchi** [comment]
I don't think solution 2 is the correct user experience- the customer shouldn't care how we implement the query logic, they only care about getting the correct results. Logic Apps customers are using the connector so that they don't need to make implementation decisions or understand how the underlying SDK works

**Comment by jcocchi** [comment]
> If I am using _HasMoreResults_, which _RequestCharge_ and _ActivityId_ should I use? The first one, or the last one?
> * cc @ealsur , @jcocchi

Request charge should reflect the charge for the entire Logic Apps action, so I think it should be a sum. 

However, if we're draining some queries and not others that may not be a consistent user experience. We need to call out the explicit behavior in the connector docs based on whatever solution/ design we land on. I can help with the docs edit
