### ISSUE TITLE
Does Logic App -CosmosDB connector support the hierarchical partition key  

### ISSUE THREAD

**Issue by rsanghavi4** [Azure/azure-cosmos-dotnet-v3#4022]
Hello Team,
Does Logic App -CosmosDB connector support the hierarchical (multiple) partition key feature ?

**Comment by philipthomas-MSFT** [comment]
Hello @rsanghavi4 . Thank you for contacting us. Unfortunately. there is no support for hierarchical partition keys with the current release of Logic App AzureCosmosDB connector for Standard Plan. @jcocchi
