### ISSUE TITLE
InitializeAsync and dependency injection

### ISSUE THREAD

**Issue by msft-mw** [Azure/azure-cosmos-dotnet-v3#4023]
On the old v2 SDK I could hook a DI-container's `OnActivated` event and call `OpenAsync` to preheat the client. In v3 I see that there are the `BuildAndInitializeAsync` and `CreateAndInitializeAsync`. I'd really like to be able to use these to lower the performance hit on first request in my service, but I'm not sure how. The MS DI container doesn't support async methods like these, so I can call `Build` but not the `Initialize` part.

Is there a publicly usable equivalent to the 
```csharp
internal async Task InitializeContainersAsync(...)
```

method that I could use? I considered calling `CreateContainerIfNotExistsAsync` on the async callback but I don't think it does the same thing?

**Comment by bartelink** [comment]
This article describes the options: https://devblogs.microsoft.com/cosmosdb/improve-net-sdk-initialization/

In short, the CreateAndInitialize call is not something you can do after the fact, and CreateContainerIfNotExists is not a useful proxy for triggering any sort of useful warmup

So you want to work it into your app startup in as clean a way as possible - there's a pretty complete list in this series: https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-1/

**Comment by Angular2-ngcontent** [comment]
The answer has been found



https://stackdev.space/questions/exploring-the-world-of-asynchronous-methods-to-initialize-a-cosmos-client-within-dependency-injection
