### ISSUE TITLE
Batching of multiple(~20-50) inserts into one single network call to cosmos db?

### ISSUE THREAD

**Issue by joshidp** [Azure/azure-cosmos-dotnet-v3#4028]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to batching of multiple(~20-50) inserts into one single network call to cosmos db? I don't need it to be transactional i.e. I don't want "all or none" which is provided by Transactional batch operations.

**Describe the solution you'd like**
I am looking for a way to batching of multiple(~20-50) inserts into one single network call to cosmos db.

**Describe alternatives you've considered**
Currently, I am insert document in parallel which has overhead of thread pool management and network calls.

**Comment by ealsur** [comment]
This is what Bulk does: https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/

Network requests in Cosmos DB are always targeting a physical partition by system design, the SDK clients can only group operations targeting the same physical partition.

If the inserts are not targeting the same physical partition, then it's impossible to group them.

**Comment by joshidp** [comment]
Our use-case is for a transactional API, within a single transaction we will be pushing 30-50 documents to cosmosdb, our API will receive ~1000 requests per seconds, so it's scaled very well at app service layer, we want to optimize network round-trip to cosmosdb for each insert call, that will save lot of time and resources for us. I didn't go for bulk support in cosmos db because it looks like for higher number of bulk processing e.g. migration.  Threads are not a bottleneck but we want to reduce socket usage by using bulk insert for cosmos.

Is bulk still a good option? https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/
