### ISSUE TITLE
Account key secure string

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#403]
Need to investigate the performance and security of storing account key as secure string. The hash function seems to be recalculating the key byte array for each call.

**Comment by AgSync-Aaron** [comment]
As an outsider just asking a question about SecureString, I thought they were [discouraged](https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md). Is that not necessarily the case internally?

**Comment by j82w** [comment]
@AgSync-Aaron that's why this issue is marked as needs investigation. In the scope of the SDK it requires it to support the account keys to be able to communicate with Azure Cosmos DB. Based on the documentation you pointed to Azure Cosmos DB as a service will need to evaluate the different authentication protocols, and support different a protocol that does require string.

**Comment by j82w** [comment]
After further review we decided to [remove](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/407) SecureString until we have a need for it based.
