### ISSUE TITLE
Too little information

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-cosmos-dotnet-v3#4038]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#38203](https://github.com/Azure/azure-sdk-for-net/issues/38203).

## Details

Needs more explanation.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9923c482-7052-694a-5f83-3ae3eaac35cb
* Version Independent ID: b8f20565-bbe3-ba0d-b680-650b743f4e57
* Content: [RequestOptions.IfNoneMatchEtag Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.requestoptions.ifnonematchetag?view=azure-dotnet#microsoft-azure-cosmos-requestoptions-ifnonematchetag)
* Content Source: [xml/Microsoft.Azure.Cosmos/RequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/RequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ealsur** [comment]
@cwalters-as could you please clarify exactly what is there too little information about?
