### ISSUE TITLE
Overriding the logic for fetching AAD tokens in case of managed identity based authentication

### ISSUE THREAD

**Issue by pratyush-prateek** [Azure/azure-cosmos-dotnet-v3#4044]
# Background

We are an azure 1P PaaS. We have an architecture where our compute lies in the MS tenant and there is a dedicated storage for each of our customers who create an azure resource from our Resource Provider (RP). The storage (cosmos DB) lies in the customer's tenant and we want to leverage managed identity based authentication to access the cosmos account. What we are currently trying is the following

- Enabling system assigned managed identity of the resource our RP creates (this is in the customer subscription)
- Creating cosmos account in the customer subscription (Done via something called Managed Resource Groups, not important for this query).
- Updating the role assignments of cosmos via system assigned identity obtained in the first step. Also, since the resource is created by our RP, we have access to the managed identity metadata for each resource we create. 
 
Now, to access the cosmos account, there is a way to call the Managed Identity control plane along with the managed identity metadata and get the AAD token for authentication. What we want to know is, if there is a way to override the logic to get the AAD token in `CosmosClient`. Suppose, if someone is using `DefaultAzureCredential`, the logic for getting the AAD token is encapsulated within the `DefaultAzureCredential` is my guess. **Please correct me if I am wrong here.**

# Query

Can we somehow override the logic which gives `CosmosClient` the AAD token? Kind of similar to the `KeyVaultClient` implementation where it allows us to pass the authentication callback delegate which fetches the AAD token. Reference - https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclient.authenticationcallback?view=azure-dotnet

My educated guess is that we can maybe override the `TokenCredential` class to provide our own implementation. If this is the correct approach, please suggest some best practices around it.

**Comment by ealsur** [comment]
> My educated guess is that we can maybe override the TokenCredential class to provide our own implementation. If this is the correct approach, please suggest some best practices around it.

Yes, that's correct. But we cannot provide recommendations or best practices, `TokenCredential` is not an abstract class defined in this library.

Please reach out to Azure Identity for recommendations on custom `GetToken` implementations: https://github.com/Azure/azure-sdk-for-net/issues

**Comment by ealsur** [comment]
@pratyush-prateek
TokenCredential does not implement IDisposable: https://learn.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet

**Comment by pratyush-prateek** [comment]
> @pratyush-prateek
> TokenCredential does not implement IDisposable: https://learn.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet

@ealsur Yes it does not, I mean if we implement it manually. Basically, creating a custom credential class which extends TokenCredential (abstract class) and implementing IDisposable. This way, we can create such implementation. My guess is cosmos won’t handle disposing them by default if I am correct.

**Comment by ealsur** [comment]
> My guess is cosmos won’t handle disposing them by default if I am correct.

Correct. SDK interacts with the abstract class (TokenCredential). It cannot call a Dispose method on your custom implementation.

**Comment by pratyush-prateek** [comment]
@ealsur  I had one question related to how `CosmosClient` uses the `TokenCredential` implementations. There are two methods in all `TokenCredential` implementations, one is `GetToken` which is non-async and another one is `GetTokenAsync` which is async. Does the cosmos client ever call the non-async implementation to fetch AAD token? Or it is merely for testing purposes or writing unit tests?
