### ISSUE TITLE
Client Telemetry : Log error signals from client telemetry service

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#4051]
Client Telemetry Service side, few OS are not supported yet. We need some signal at client side i.e SDK which would tell, if service call is failing due to SSL (or due to any reason)

**Comment by kirankumarkolli** [comment]
Lets please talk this though on scenario and scope.

**Comment by sourabh1007** [comment]
It is already discussed multiple times and got suggestion from the team, to use traces to debug these issues. Hence closing.
