### ISSUE TITLE
Marshal.Release not supported on Linux and Mac

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#406]
Marshal.Release(IntPtr) isn't supported on Linux and macOS	Microsoft.Azure.Cosmos	C:\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\src\Query\QueryPartitionProvider.cs	293	Active

MarshalByRefObject.InitializeLifetimeService() isn't supported on Linux, macOS, and Windows	Microsoft.Azure.Cosmos	C:\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\src\MediaStream.cs	130	Active

**Comment by kirankumarkolli** [comment]
@j82w what's the impact of this? 
Does V2 core also already have this limitation?

**Comment by j82w** [comment]
I believe it is a no-op right now for linux users. I got this from a fxcop validation tool that checked for non-supported APIs.

**Comment by ealsur** [comment]
Cleaning up issues with needs-investigation that are dormant/not-actionable
