### ISSUE TITLE
How to query items against physical partition key range in V3?

### ISSUE THREAD

**Issue by v4karuna** [Azure/azure-cosmos-dotnet-v3#4061]
In V2, you could specify the `PartitionKeyRangeId` in `FeedOptions`:

```
var query = documentDbClient.CreateDocumentQuery<Document>(
    UriFactory.CreateDocumentCollectionUri(databaseId, collectionId),
    queryStr,
    new FeedOptions 
    { 
        PartitionKeyRangeId = feedOptions.PartitionKeyRangeId, 
        MaxItemCount = feedOptions.MaxItemCount, 
        EnableCrossPartitionQuery = false,
        RequestContinuation = continuationToken,
    });
```

In V3, the `QueryRequestOptions` only supports partition key?

```
var feedIterator = container.GetItemQueryIterator<Document>(
    "query",
    continuationToken,
    requestOptions: new QueryRequestOptions
    {
        PartitionKey = new Azure.Cosmos.PartitionKey("partitionKey"),
    });
```

We have a use case where we are querying physical partitions in parallel to orchestrate some offline/migration scenarios. Is this possible in V3?

Thanks!

**Comment by ealsur** [comment]
Please refer to the migration guide: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/migrate-dotnet-v3?tabs=dotnet-v3#changes-to-feedoptions-queryrequestoptions-in-v30-sdk
