### ISSUE TITLE
Performance degradation in package version 3.26.1

### ISSUE THREAD

**Issue by huluvu21** [Azure/azure-cosmos-dotnet-v3#4064]
**Describe the bug**
We upgraded the package from 3.25.3 to 3.26.1 and noticed a performance degradation in our load tests. The tests test our API that fetches documents from Cosmos. The queries look mostly very simple "SELECT c.id, c.elements FROM c WHERE c.project_id = xxx AND c.elements.text.value = yyy" where project_id is partition key.

**Expected behavior**
No performance degradation.

**Actual behavior**
Performance degradation.

**Environment summary**
SDK Version: 3.26.1
OS Version: Windows

**Additional context**
You can see a screen from Azure Load Testing.

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/19777142/426157c5-1518-44f5-b94c-9fcf602b997e)

The first test run is before the upgrade, the next 5 runs are after the update and the last 4 runs are after revert of this upgrade. You can see that package version 3.35.3 produces average response time of about 2.4s. The package version 3.26.1 hovers around 3s.

**Comment by bartelink** [comment]
Those version numbers don't make sense, i.e. 'upgrading' from 3.35 to 3.26 - might be worth to double check and update for clarity

**Comment by ealsur** [comment]
@huluvu21 Can you please clarify what package are you upgrading? There is no 3.25.3 version of https://www.nuget.org/packages/Microsoft.Azure.Cosmos#versions-body-tab.

**Comment by ealsur** [comment]
Also please give details on which are the specific operations (with code snippets if possible) that have the issue. From the description it looks like Queries, but we need to be sure.

If that is the case, then capturing the [Diagnostics](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-dotnet-sdk-slow-request?tabs=cpu-new#capture-diagnostics) from the operations would help see where the latency could be coming from.
