### ISSUE TITLE
I am not able to use azure cosmos within azure function app

### ISSUE THREAD

**Issue by ashraqat-sheta** [Azure/azure-cosmos-dotnet-v3#4068]
I am trying to use Microsoft.Azure.Cosmos within azure function app with binding CosmosClient as an input but i am getting error messages and it isn't working.

Can you help me to get it work, please?

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/103435423/ea5281d5-1f41-48e8-97c7-d4cd07419d35)

**Comment by sourabh1007** [comment]
I am not sure what are you trying to do, if you want to connect to cosmosDB using Azure functions, you should follow function's documentation

https://learn.microsoft.com/en-us/azure/azure-functions/functions-add-output-binding-cosmos-db-vs-code?tabs=in-process%2Cv1&pivots=programming-language-csharp
https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2?tabs=in-process%2Cfunctionsv2&pivots=programming-language-csharp#binding-types

May be this screenshot is related your issue.
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/6362382/37f74598-9f94-4428-a98d-b25026d4d68d).

If you still face this issue. Please create an issue in azure functions repo i.e. https://github.com/Azure/Azure-Functions/issues
