### ISSUE TITLE
Does RequestTimeout always need to be greater than 65 seconds?

### ISSUE THREAD

**Issue by ericch-ms** [Azure/azure-cosmos-dotnet-v3#4075]
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/b7b1064ab7e8bb0d90825c95125c5e1e2d74cb50/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L235

I'm seeing that the CosmosHttpClientCore.GatewayRequestTimeout value is hardcoded as 65, and wanted to know if this is by design/requirements?

I'm attempting to adjust CosmosClientOptions.RequestTimeout to lower value (30-ish seconds) because of some transient network/thread issue we are experiencing, based on the guidance from https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-dotnet-sdk-request-timeout?tabs=cpu-new, but I'm confusing if I am only allowed to increase the value over 65, or am I misunderstood? 

Please help clarify the intention of the document&the SDK code for me. Thanks!

**Comment by sourabh1007** [comment]
yes, It is by design. For any HTTP call, timeout cannot be less than 65 seconds.

Configuration mentioned in the above documentation, is applicable for data plane calls when you are running SDK in DIRECT mode.
