### ISSUE TITLE
.NET8 preview 7 seems to be incompatible

### ISSUE THREAD

**Issue by ceccomil** [Azure/azure-cosmos-dotnet-v3#4077]
.NET8 will launch in a few months so we started migrating our code base libraries.

It seems Cosmos SDK cannot work with .NET8 while we don't have any problem with .NET7

Please take a look at this repo for a repro example.
https://dev.azure.com/milanifrancesco/Public%20Tests/_git/CosmosSdkNet8Issue

Examples running:
.NET7 OK
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/40296947/f6c59c51-fc73-40d6-bc06-06d3db6e914c)

.NET8 not working (just hangs...)
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/40296947/0500d6b9-f8fe-40d4-899d-b278e235e9fd)

**Comment by ceccomil** [comment]
After further investigation, I've realised it might just be a problem related to localhost.
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/40296947/c8898f6a-defb-4dbd-83b8-5bfc8a050a53)

**Comment by ealsur** [comment]
Certificate or SSL negotiation is not directly controlled by the SDK, this is the .NET HttpClient. There are known cases (like running the Emulator on a docker image) already documented where you can disable the SSL verification if needed: https://learn.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21#disable-ssl-validation
