### ISSUE TITLE
Default value is wrong

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-cosmos-dotnet-v3#4084]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#38740](https://github.com/Azure/azure-sdk-for-net/issues/38740).

## Details

As you can see in https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs the default value is 6 second.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17f88dfd-aa88-e817-8884-e2fd96c15110
* Version Independent ID: 7dba7648-4f99-e9a0-0c13-bf258ce92510
* Content: [CosmosClientOptions.RequestTimeout Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.requesttimeout?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ealsur** [comment]
ConnectionPolicy is internal, not public.

The XML documentation for CosmosClientOptions.RequestTimeout also says 6 seconds:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0a0e5ae69dc942d1625d3454a8d51467493d9e96/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L222-L228

It seems the web documentation is not updated. @jsquire do you know who is responsible for the web XML documentation to be updated?

**Comment by jsquire** [comment]
@ealsur: I have no insight into the tooling or publishing pipeline that the Cosmos team uses, unfortunately.  To my knowledge, these are completely separate from the Azure SDK assets.

**Comment by philipthomas-MSFT** [comment]
@ealsur Are we waiting for more approvals? What can we do to close this?

**Comment by ealsur** [comment]
@philipthomas-MSFT The linked PR needs to merge and only the owners of the repo can merge, see the discussion there
