### ISSUE TITLE
Make WithDistributedTracingOptions() available in preview

### ISSUE THREAD

**Issue by mortenbock** [Azure/azure-cosmos-dotnet-v3#4094]
**Is your feature request related to a problem? Please describe.**
When running the -preview package, the distributed tracing is logging a lot of traces for requests over the default LatencyTreshold. We cannot change these thresholds because `DistributedTracingOptions` and `WithDistributedTracingOptions()` are internal.

**Describe the solution you'd like**
Make the relevant API's public for -preview, so we can decide the latency threshold we prefer.

**Describe alternatives you've considered**
We considered a TelemetryProcessor for AI to detect and remove these traces, but decided to disable the distributed tracing for cosmos altogether instead.

**Additional context**
We are using Application Insights for out application.

**Comment by sourabh1007** [comment]
Thanks for asking for it.

We are working on it, you would see this option available in next version of preview SDK. Although API name would be changed.
