### ISSUE TITLE
Do not treat 404 for a point read as a dependency failure

### ISSUE THREAD

**Issue by mortenbock** [Azure/azure-cosmos-dotnet-v3#4095]
**Is your feature request related to a problem? Please describe.**
Our application does a lot of lookups by id+partitionkey to decide if a document already exists. If it does not, the 404 response is logged to application insights as a dependency failure, which we do not consider it to be, since the 404 just represents the fact that a document is not there.

**Describe the solution you'd like**
Do not log 404 on point reads as a failure.

**Comment by ealsur** [comment]
@mortenbock What if for other user, a 404 is unexpected and a failure? Isn't this based on each business scenario? 
@jcocchi Do we know if other AI integrations allow the user to set rules of this sort?

**Comment by mortenbock** [comment]
@ealsur Let me turn the question around: How would I ask Cosmos to give me a document if it exists, without causing a dependency failure, if the answer is no?

If I make a query, and there are 0 results, that is not a dependency failure IMO?

If there is no such container, then that is a failure.

**Comment by ealsur** [comment]
@mortenbock Hence my question if this should be a configuration and how other products integrate with OpenTelemetry.

For you, reading a container and getting a 404, is a failure. For others, it might not, they might have a flow that dynamically creates containers. So is it a failure? Depends on the case.

Same goes for reading a document.

Changing the behavior to adjust to a single use-case doesn't sound like the right solution because then others will see it as unexpected?

**Comment by ealsur** [comment]
If there is a Design guideline for Open Telemetry integrations that say (for example): All network interactions with a non-Success status code should be considered a Failed dependency, then a 404, regardless of the context, is a Failure.

Either understanding if there is such a Design principle/guideline or how other products integrated and deciding if there should be a configuration, is probably the path forward.

**Comment by mortenbock** [comment]
IMO, fetching a document is a query operation. It happens to have a 404, because it's an http protocol.

If it was a `select top 1 * from TodoItems where id = 1` on a sql server, the dependency would not track that as a failed query.

But a `select top 1 * from BadTableName where id = 1` would, because the query is invalid according to the schema.

I guess I _could_ do a query instead of a point read to find the document, but it feels like that would be more expensive? But is that the recommended way to do it?

**Comment by ealsur** [comment]
Queries most of the time are less performance than point operations.

Since this feature is in preview, this Issue is probably a good feedback opportunity. Let's see how it evolved.

**Comment by jcocchi** [comment]
I don't know if other integrations with App Insights/ APM tools allow for customization of handling status codes, but I agree this is  a good future optimization to consider

**Comment by sourabh1007** [comment]
It is addressed in latest SDK. 404 is not getting marked as failed trace by SDK.
