### ISSUE TITLE
Validate change feed estimator picks up all new partitions after split when read from different CosmosClient

### ISSUE THREAD

**Issue by jcocchi** [Azure/azure-cosmos-dotnet-v3#4112]
We identified a bug in the Java SDK change feed estimator where not all new partitions were picked up after a partition split. The CFP and estimator were using different CosmosClients and only CFP got all new partitions. The estimator continuously threw 410s on one of the old PKRangeIds of a parent partition.

Unclear if this bug also exists in .NET so we should investigate. Change feed mode in Java was all versions and deletes, but this could happen using any change feed mode.

**Comment by ealsur** [comment]
@jcocchi Was the estimator not refreshing the leases it was checking?

**Comment by ealsur** [comment]
.NET Estimator is used in Azure Functions Scale Controller, if this would not be working, Functions would be broken

**Comment by jcocchi** [comment]
Ah maybe this is a non issue then, just wanted to track it as an investigation. Yes estimator had some cached values that weren't getting refreshed in Java

**Comment by ealsur** [comment]
Yeah, we can do a validation for sure. But Estimator does not cache the leases in .NET, they get the leases on every estimation because leases can change.

**Comment by philipthomas-MSFT** [comment]
I'll keep this on my list to validate. Thanks @ealsur

**Comment by philipthomas-MSFT** [comment]
Confirmed that this is a non-issue in .NET SDK.
