### ISSUE TITLE
Cosmos SDK v3 throws a serialization exception instead of a NotFound exception when JsonConvert.DefaultSettings.MissingMemberHandling=Error

### ISSUE THREAD

**Issue by threddy** [Azure/azure-cosmos-dotnet-v3#4115]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When trying to read an item that does not exist using ReadItemAsync or ReadItemStreamAsync, Cosmos SDK throws a serialization exception rather than a CosmosException with StatusCode NotFound.
I found that this is because 1) We set the default json serializer settings MissingMemberHandling to Error 2) cosmos sdk uses JToken.Parse (and not the custom serializer passed into cosmos client) thereby using the default json serializer settings 3) There is an extra property ‘Errors’ on the exception the sdk is trying to convert to a CosmosException.

**To Reproduce**
One serializer to deserialize successfully retrieved items -- we can customize this serializer when cosmosClient is created.
[ReadItemAsync](http://azure-cosmos-dotnet-v3/Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs%20at%2072e96faca5376afa1a2c9992bfb99cbeda5d11f9%20%C2%B7%20Azure/azure-cosmos-dotnet-v3%20(github.com)) -> ResponseFactory.CreateItemResponse -> [ToObjectPublic](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cosmos-dotnet-v3%2Fblob%2F72e96faca5376afa1a2c9992bfb99cbeda5d11f9%2FMicrosoft.Azure.Cosmos%2Fsrc%2FResource%2FCosmosResponseFactoryCore.cs%23L272&data=05%7C01%7Cthreddy%40microsoft.com%7Cf9aa2e63ad3f4a4601c808dbca82dcd0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326435748365917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G48NGTTdkO%2BDr01%2FOas%2BCjPKcAv5b6kOEj2fl8YE03E%3D&reserved=0)
 
A different serializer - the default Json serializer - is used  to deserialize exceptions.
We set JsonConvert.DefaultSettings.MissingMemberHandling = Error at service host level.
 
When we ReadItemAsync and the item is not found, we expect the cosmos SDK to throw a NotFound exception. Instead, it throws a serialization exception
 
This is because in the ReadItemAsync code path, it tries to create a NotFound CosmosException from the response, but fails to deserialze the response into a CosmosException because it has a property called 'Errors' that does not exist in the CosmosException definition.
 
ReadItemStreamAsync-> ProcessItemStreamAsync -> ProcessResourceOperationStreamAsync -> RequestHandler.SendAsync … -> [ToCosmosResponseMessage](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cosmos-dotnet-v3%2Fblob%2F72e96faca5376afa1a2c9992bfb99cbeda5d11f9%2FMicrosoft.Azure.Cosmos%2Fsrc%2FHandler%2FTransportHandler.cs%23L140&data=05%7C01%7Cthreddy%40microsoft.com%7Cf9aa2e63ad3f4a4601c808dbca82dcd0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326435748387486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7asYTUD73QhP8XUIvsz5451FVE4J5WqDsIT0SS27BCo%3D&reserved=0) -> [Create CosmosException if !IsSuccessStatusCode](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cosmos-dotnet-v3%2Fblob%2F72e96faca5376afa1a2c9992bfb99cbeda5d11f9%2FMicrosoft.Azure.Cosmos%2Fsrc%2FUtil%2FExtensions.cs%23L106&data=05%7C01%7Cthreddy%40microsoft.com%7Cf9aa2e63ad3f4a4601c808dbca82dcd0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326435748394704%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3cuPbGeUZBgg52d%2FpB%2BigNEUfBtZp24z3%2Bd6%2FNlgvHo%3D&reserved=0) -> [deserialize exception](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cosmos-dotnet-v3%2Fblob%2Fmaster%2FMicrosoft.Azure.Cosmos%2Fsrc%2FResource%2FCosmosExceptions%2FCosmosExceptionFactory.cs%23L112&data=05%7C01%7Cthreddy%40microsoft.com%7Cf9aa2e63ad3f4a4601c808dbca82dcd0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326435748401546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lFevNZ7eNQSXaWDzkOeyirkH%2BV4xT9x%2B4pf5VaIuowY%3D&reserved=0)

**Expected behavior**
A CosmosException with StatusCode NotFound should be thrown when ReadItemAsync cannot find the item.

**Actual behavior**
A serialization exception Newtonsoft.Json.JsonSerializationException: Could not find member 'Errors' on object of type 'Error'. Path 'Errors', line 1, position 10.

**Environment summary**
SDK Version: v3
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).
1.	What SDK version are you using? v3
2.	What Newtonsoft.Json version are you using? 13.0.0.0
3.	Are you customizing any other default setting? We set JsonConvert.DefaultSettings.ContractResolver to CamelCasePropertyNamesContractResolver

**Comment by philipthomas-MSFT** [comment]
@threddy requesting more information on reproducing this before I can recommend a solution. Is there a custom serializer that we should be creating for this that is added to the cosmos client? Your note says "_One serializer to deserialize successfully retrieved items -- we can customize this serializer when cosmosClient is created._", but can you give me some insight on what that "One serializer" needs to look like specifically? Me just creating one, gives me the **CosmosException** and not the **JsonSerializationException**.

**Comment by threddy** [comment]
To reproduce this, just set JsonConver.DefaultSettings.MissingMemberHandling = Error and try to read an item that does not exist.
No need to pass in a custom serializer.

Thanks,
Thanika

**Comment by philipthomas-MSFT** [comment]
> To reproduce this, just set JsonConver.DefaultSettings.MissingMemberHandling = Error and try to read an item that does not exist. No need to pass in a custom serializer.

Yes, thanks @threddy for the response and assistance and collaboration on this issue! However, I am trying to understand the problem before applying the recommended fix, so I have more questions. When you say _just set JsonConvert.DefaultSettings.MissingMemberHandling = Error_, which is something that you would set when creating a custom serializer, then you say _No need to pass in a custom serializer_, I am trying to understand when are setting the _JsonConvert.DefaultSettings.MissingMemberHandling = Error_. You can look at the attached PR to see what I am talking about in regard to testing first to validate the failure/bug. I am trying to eliminate ambiguity here on my part, and I appreciate your patience in this regard, and I want to not only resolve your issue but test a bit further to ensure that there are no side effects and if there are other things that we should be questioning. So, no matter how trivial, I want to make sure we get this right. Thanks again.

**Comment by philipthomas-MSFT** [comment]
More testing has found that this also occurs for _DeleteItemAsync_ and _DeleteItemStreamAsync_.

**Comment by threddy** [comment]
In your PR you set MissingMemberHandling = Error on the custom serializer passed to the cosmos client.
I am referring to setting JsonConvert.DefaultSettings before you create the cosmos client:
JsonConvert.DefaultSettings Property (newtonsoft.com)<https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonConvert_DefaultSettings.htm>
Serialize with DefaultSettings (newtonsoft.com)<https://www.newtonsoft.com/json/help/html/DefaultSettings.htm>

**Comment by philipthomas-MSFT** [comment]
> In your PR you set MissingMemberHandling = Error on the custom serializer passed to the cosmos client. I am referring to setting JsonConvert.DefaultSettings before you create the cosmos client: JsonConvert.DefaultSettings Property (newtonsoft.com)

Thanks @threddy . I will be resubmitting a draft PR soon.

**Comment by philipthomas-MSFT** [comment]
Also _PatchItemAsync_ and _PatchItemStreamAsync_.
