### ISSUE TITLE
[Client-side encryption] Stored Procedures doesn't work in client-side encryption scenario.

### ISSUE THREAD

**Issue by ltxtech1999** [Azure/azure-cosmos-dotnet-v3#4154]
**Description**
We use client-side encrypted Cosmos client, the client is set properly, and item CRUD works well. But stored Procedures related things are not encrypted properly. Data processed by stored Procedure is stored in plain text.
Is stored Procedures supported in client-side encrypted? 

From my understanding, stored Procedures works in service side. But data is already encrypted in client side here. They may have some conflicts. And I can't find any sample in this repo related to it. Are stored Procedures related scenarios supported in client-side encryption? If not, the stored Procedures is a widely used scenario in Cosmos DB and remove all related things cost a lot, do we have any walk around case for it?

**Expected behavior**
Data processed by stored Procedures is still encrypted properly. And the stored Procedures can process the data as expected.

**Repro**
`
_cosmosClient.Container(databaseName, containerName).WithEncryptor(new CosmosEncryptor(dekProvider)).Scripts.ExecuteStoredProcedure(procedureId, partitionKey, parameters, requestOptions, cancellationToken);
`

_cosmosClient here is initialized properly as CRUD for items work well. Encrypted items are stored in the database correctly. So the problem may be storePorcedure is not supported.

**Comment by ealsur** [comment]
@kr-santosh / @vipulvishal-ms could you help answering this question?

**Comment by vipulvishal-ms** [comment]
Stored procedure operations don’t support encryption options.
