### ISSUE TITLE
Make `DeleteAllItemsByPartitionKeyStreamAsync` a non-preview method

### ISSUE THREAD

**Issue by janpieterz** [Azure/azure-cosmos-dotnet-v3#4169]
**Is your feature request related to a problem? Please describe.**
We continuously have to disable automatic dependency updates and testing for this specific change. It's been in the SDK for a while, it'd be great if we can get it to be part of the non-preview version.

**Describe the solution you'd like**
The method to be in the non-preview, default SDK

**Describe alternatives you've considered**
Manually fixing our update process every time it runs.

**Comment by jcocchi** [comment]
Hi @janpieterz, this API is in the preview package because it uses an underlying Cosmos DB feature which is still in preview. When the service feature is GA, we will add the API to the GA package as well. The current GA ETA is around 3-6 months. 

Here's a link to the [docs](https://learn.microsoft.com/azure/cosmos-db/nosql/how-to-delete-by-partition-key?tabs=dotnet-example) if you want to learn more.

**Comment by janpieterz** [comment]
@jcocchi  ah I see. I wonder if there's a way to version preview packages so that they don't see moving from `1.0.0-preview` to `1.0.0` as an upgrade. But that would probably entail marking the preview package as a `1.0.1-preview` version 🤔 Because the `-preview` is seen as a preview for the current version, every time we run the analysis it gets flagged as if we're "behind" instead of "ahead".

**Comment by ealsur** [comment]
When an API moves from Preview to GA, it moves in an incremental version.

Let's say Feature X is in preview in `1.0.0-preview`, and it releases in the next version, it will be GA in `1.1.0`. `1.1.0-preview` will have whatever `1.1.0` has as GA + whatever other APIs are still in preview.

**Comment by janpieterz** [comment]
@ealsur yea I got that. It's just that semver sees a 1.0.0-preview as a precursor to 1.0.0, so tools keep asking for upgrades (automated update tools like Dependabot and Renovate, nuget itself, etc.).

**Comment by ealsur** [comment]
Interesting, I guess this was not the case a while ago when this pattern was introduced (first V3 release). But it's a good feedback, I was not aware of this behavior and this is the first time I hear a report about it.

cc @kirankumarkolli

**Comment by janpieterz** [comment]
@ealsur, yea, for example here's the nuget overview (in Rider) for our solution, asking us to upgrade to `3.36.0` while we have `3.36.0-preview` installed (the fact you see a blue version number on the right means there's an update that's not installed). 

Not a big deal in the local manager and our tests will fail, but since it's kind of staying around for so long, it's something we have to deal with at least weekly while our automated dependency scanner and updater runs.

<img width="1226" alt="image" src="https://github.com/Azure/azure-cosmos-dotnet-v3/assets/383634/981ff641-f31d-469f-b2e3-1bbca1b607e1">

**Comment by ealsur** [comment]
cc @Pilchie 

This is something we need to handle in our release process to avoid customers hitting this problem for sure.

**Comment by ealsur** [comment]
@janpieterz Could you take a look at the proposed versioning to see if this aligns better with your environment?

**Comment by janpieterz** [comment]
Hi @ealsur, yup that looks like it'd capture it, neat way to add the patch version behind the preview!
