### ISSUE TITLE
EagerCosmosObject does not serialize undefined objects

### ISSUE THREAD

**Issue by bchong95** [Azure/azure-cosmos-dotnet-v3#417]
If the value of a cosmos object is null, then we get a NRE. We should either disallow null elements, or skip them in the serializaiton. I suppose array suffers from the same issue.

**Comment by kirankumarkolli** [comment]
Is it projection scenarios (ex: select a property which doesn't exist) that result in null? 
How common/un-common is this scenario?

**Comment by bchong95** [comment]
This has been resolved. I just don't remember where.
