### ISSUE TITLE
Question regarding the ItemRequestOptions and CosmosClientOptions configuration

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-cosmos-dotnet-v3#4173]
We are trying to pass a customized key-value pair into the [ItemRequestOptions.Properties](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/4db6078dc5eccb7133c5554e4ae35c5636ae9677/Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs#L38) to be used in the Customized Handler inside the [CosmosClientOptions.CustomHandlers](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/4db6078dc5eccb7133c5554e4ae35c5636ae9677/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L244).

I see by default the ItemRequestOptions is nullable for container class APIs. So I would like to understand:
1. Will there be any behavior difference between the ItemRequestOptions = null and new a ItemRequestOptions with all default property?
2. Is this ItemRequestOptions.Properties an application-level property that will only be used by RequestHandlers, not passing to the backend server? Or it will be passed to the cosmos db server and also take effect in same cases?

Not sure if this is the right place for the question. If no, could you point me to the right place for this question? Looking forward to hearing from you. Thanks a lot!

**Environment summary**
SDK Version: 3.36.0
OS Version: Windows

**Comment by blankor1** [comment]
Thank you! @sourabh1007 

Then do we have any ways to exclude those values in the header to avoid sending it to backend and only limit it to application-level property? If in the future some large context is added here, these properties in the request header would increase the size of the request and may affect the bandwidth and latency.

**Comment by sourabh1007** [comment]
No, we have don't a way to exclude them because it is not expected to have large context. Maybe you can try to exclude them in your custom handler because custom handler gets called before any network call (I didn't try it but you can check if it works)

**Comment by blankor1** [comment]
Sorry for the late reply. I tried to exclude this in my own handler, and it indeed works. Thank you!

But just a suggestion, if this content is expected to be used just in application-level, then I guess it would be better to only be kept in application-level not passing to the backend? I'm thinking this because:
1. As a user, we don't know how Cosmos DB server will deal with it. If a user just passes a contend that is a format the backend server is using, that might lead some problems.
2. Even it's not to pass large context, it can still induce some extra traffic workload that is unnecessary and can be avoid.

Anyway, this is just a suggestion. Thanks again for your explanation and help.

**Comment by kundadebdatta** [comment]
Closing the issue as resolved.
