### ISSUE TITLE
Not all dependency requests are automatically logged to Application Insights when using ConnectionMode "Direct"

### ISSUE THREAD

**Issue by davidxcheng** [Azure/azure-cosmos-dotnet-v3#4190]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

I'm using `<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.36.0" />`

**Describe the bug**
Within the same Azure App Service some Cosmos requests are consistently omitted from the Application Insights log, while other Cosmos requests are consistently logged as expected (expectations based on [this part of the docs](https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#automatically-tracked-dependencies)), when using `ConnectionMode` "Direct".

- The omitted request logs gets their `Container` from the same instance of `CosmosClient` as the requests that show up in the log
- When I switch to `ConnectionMode` "Gateway" all requests are logged as expected

Don't know if this has anything to do with the perceived bug but there is a difference in which method of `Container` that is called:

- Example of call that always gets logged: `container.GetItemQueryIterator<MyModel>(query)`
- Exemple of call that only gets logged when using "Gateway": `await container.ReadItemStreamAsync("123", new PartitionKey("123"))`

**To Reproduce**
Hard to say since it is a mystery to me but I would start with creating an Azure App Service that makes calls using `GetItemQueryIterator()` (plus subsequent `ReadNextAsync()`) and `ReadItemStreamAsync()` and see if both calls gets logged to insights. Then switch between "Direct" and "Gateway".

**Expected behavior**
I expect all requests to Cosmos to be logged as dependency requests in Application Insights [as described in the docs](https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#automatically-tracked-dependencies)

**Actual behavior**
Some requests are consistently omitted in the logs

**Environment summary**
SDK Version: 3.36.0
OS Version Windows on Azure

**Additional context**
We also have this problem i BusTriggered Azure Function Apps.

Screenshot when using "Gateway" (dependency request to both Azure Cognitive Search and Cosmos are logged):
<img width="284" alt="image" src="https://github.com/Azure/azure-cosmos-dotnet-v3/assets/452261/46ea7b15-5775-433e-8e54-00aeb7f158d1">

Screenshot when using "Direct" (only the dependency request to Azure Cognitive Search is logged):
<img width="287" alt="image" src="https://github.com/Azure/azure-cosmos-dotnet-v3/assets/452261/2e0e7e00-9187-44dc-a7cb-151df343c647">

**Comment by sourabh1007** [comment]
If my understanding is correct, you are talking about Distributed Tracing feature in SDK which you enabled it by setting this client option https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclienttelemetryoptions.disabledistributedtracing?view=azure-dotnet#microsoft-azure-cosmos-cosmosclienttelemetryoptions-disabledistributedtracing

Are you using latest version of appinsight SDK i.e. https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.22.0-beta4? 

If not, can you please run your test with this version of ApplicationInsight SDK and let me know if you still face this issue.

Without any of this configuration, ApplicationInsight SDK by default captures only HTTP requests.

**Comment by davidxcheng** [comment]
@sourabh1007 Thx for the feedback! Yes, Distributed Tracing is the feature I'm talking about and I've checked that `DisableDistributedTracing` isn't set to `true`. Pretty sure that we're not using the pre-release of `Microsoft.ApplicationInsights` nuget though so I'll bump it tomorrow and post the result here..

**Comment by davidxcheng** [comment]
@sourabh1007 Updated to `Microsoft.ApplicationInsights` `v2.22.0-beta4` but the issue remains.

Could it have something to do with `XxStreamAsync()` methods using http under the hood? The `ResponseMessage.StatusCode` is of type `HttpStatusCode` so maybe it uses http and somehow those calls are not logged properly when using Direct ConnectionMode 🤔

**Comment by davidxcheng** [comment]
Thank you for looking into it and posting these screenshots :+1: 

I'll close this issue and get back to investigating our settings as your screenshots indicate that solution lies somewhere on our side.

**Comment by davidxcheng** [comment]
@sourabh1007 I got it working using `Microsoft.ApplicationInsights.AspNetCore v2.22.0-beta4` and `Microsoft.Azure.Cosmos v3.37.0` - not sure why it didn't work the other day. Just curious, how do I opt into the Custom Properties I see in your screenshot and that you mention in this issue: [https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3058](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3058)? Did you use some unreleased nugets above? This is what gets logged for me:
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/452261/37cc24c7-a7e5-496a-b69c-3a26162f738f)

**Comment by sourabh1007** [comment]
it should be logged for you also. are you checking operation level activity for these custom properties? The one with pipe ("|") symbol.

**Comment by davidxcheng** [comment]
Aha, thanks for pointing out the difference - I don't have a pipe symbol. Guess I still have a lot left to learn about insights but the main problem is solved. Thank you for your time, much appreciated!
