### ISSUE TITLE
No Response from Cosmos SDK for network issue

### ISSUE THREAD

**Issue by ajaykrish90** [Azure/azure-cosmos-dotnet-v3#4199]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
There is no response from SDK if we have enabled the firewall only to one of IP after private end point creation

**To Reproduce**
Enabled private end point for the Cosmos DB
There would be two IPs which would reflect in DNS
Enable firewall only to 1 IP
Write a azure function app to connect to DB and execute a query
Once the function app is triggered - no response will be received

**Expected behavior**
Failure response should be received with network failure

**Actual behavior**
No response from SDK and Azure function app gets timeout after default time period configured in function app end

**Environment summary**
SDK Version:3.35.2
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Additional context**
Once we enabled firewall for both the IP - we are getting success response. Since we are not aware about the second IP it took almost a month to find the root cause of the issue because SDK was not throwing any response

**Comment by ealsur** [comment]
Can you share how you are creating the CosmosClient (without keys) and what is the operation you are performing and with which parameters? Are you passing a CancellationToken?

The SDK has many [Retry Policies](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/SdkDesign.md#cross-region-retries) and this might be simply a case of long retries due to HTTP failures being retried.

**Comment by ajaykrish90** [comment]
Below is the way we are creating client
` 
  
public class CosmosDBConfig
{
    
private static string UserManagedIdty = Constants.CosmosUsrMgdIdty;
   
private static DefaultAzureCredential credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { ManagedIdentityClientId = UserManagedIdty });
private static string cosmosDBHost = Constants.CosmosConfigDBHost;
private static Lazy<CosmosClient> lazyClient = new Lazy<CosmosClient>(InitializeCosmosClient);
 public static CosmosClient cosmosClient => lazyClient.Value;
private static CosmosClient InitializeCosmosClient()
{
    // Perform any initialization here
   
    return new CosmosClient(cosmosDBHost, credential, new CosmosClientOptions()
    { ApplicationRegion = Constants.CosmosDBRegion, ConnectionMode = Constants.cosmosConnectionMode });
}}
`
Post that  query will be framed for execution


string sqlQuery = null;
cosmosClient = CosmosDBConfig.cosmosClient;
log.LogInformation("cosmosClient Endpoint:"+cosmosClient.Endpoint.ToString());
if (cosmosClient == null)
{
    // to be handled
}
               
sqlQuery = SQLQueries.SQL;
QueryDefinition queryDefinition = new QueryDefinition(sqlQuery);
queryDefinition.WithParameter("@p1", "v1" ?? " * **");
               

FeedResponse<JObject> response = null;
var watch = System.Diagnostics.Stopwatch.StartNew();

container = cosmosClient.GetContainer("DBName", "ContainerName");
log.LogInformation("Database:" + container.Database.Id);
log.LogInformation("Container:" + container.Id);
log.LogInformation("client connected");
log.LogInformation("SQL Query" + JsonConvert.SerializeObject(queryDefinition));

FeedIterator<JObject> feedIterator = container.GetItemQueryIterator<JObject>(queryDefinition, requestOptions: new QueryRequestOptions { MaxConcurrency = 1 });
while (feedIterator.HasMoreResults)
{
    var task = feedIterator.ReadNextAsync();
    task.Wait();
    FeedResponse<JObject> currentResultSet = task.Result;
    if (currentResultSet.Count > 0)
    {
        log.LogInformation("Cosmos Response" + JsonConvert.SerializeObject(currentResultSet));
    }
}
log.LogInformation("Cosmos Connection & Read completed. Duration: ");

**Comment by bartelink** [comment]
Use triple ticks (```) to bound blocks of code

or start with ```csharp to get better syntax highlighting too

**Comment by ealsur** [comment]
```
var task = feedIterator.ReadNextAsync();
task.Wait();
```

This is blocking the async thread. Is there a chance that this blocking might be related? Why not use `FeedResponse currentResultSet = await  feedIterator.ReadNextAsync()l`

**Comment by ajaykrish90** [comment]
Thanks for the comments.

I have tried without using `task.Wait();` as well; however, SDK did not throw any response back; probably it might be retrying as I wasn't passing the cancellation token as mentioned by you.
The firewall I was mentioning is not a Cosmos DB firewall; it is a network-level configuration. As I was trying to connect the Cosmos cross-regionally, in our organisation, any cross-level connectivity needs to be enabled by the network team.
Initially, I enabled only a specific private IP for which we were not receiving responses from the SDK; however, Cosmos DB uses two IPs from the subnet configured. After whitelisting both IPs, the issue was resolved.
Anyway, thanks for providing feedback. I will pass a cancellation token as a solution for such a use case.

**Comment by ealsur** [comment]
@ajaykrish90  Just make sure the value of the CancellationToken is higher than the Request Timeout -> https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-dotnet-sdk-request-timeout?tabs=cpu-new#customize-the-timeout-on-the-azure-cosmos-db-net-sdk
