### ISSUE TITLE
Distributed tracing never emitted to outputs

### ISSUE THREAD

**Issue by msft-personal-acct** [Azure/azure-cosmos-dotnet-v3#4202]
**Describe the bug**
After setting up OpenTelemetry tracing in a ASP.NET Core application with CosmosDB we see ASP.NET Core Activity Traces emitted but no traces from the SDK.

**To Reproduce**
NuGet package versions:
Microsoft.Azure.Cosmos: 3.37.0
OpenTelemetry: 1.6
OpenTelemetry.Extensions.Hosting: 1.6.0
Microsoft.Extensions.Hosting: 8.0.0

dotnet version: 8.0.100

1. Setup OTel:
```csharp
 webAppBuilder.Services.AddOpenTelemetry()
     .WithTracing(
         tracerProviderBuilder =>
         {
             tpb.AddSource("Azure.Cosmos.Operation").AddConsoleExporter();
         });
... 
var forwarder = new AzureEventSourceLogForwarder(serviceProvider.GetRequiredService<ILoggerFactory>());
forwarder.Start();

webAppbuilder.Services.AddSingleton(forwarder);
```

2. Set logging levels to:
```json
"Logging": {
  "LogLevel": {
    "Default": "Trace",
    "Azure-Cosmos-Operation-Request-Diagnostics": "Information"
  }
}
```

3. Create `CosmosClient` using the fluent builder and:
```csharp
.WithClientTelemetryOptions(
    new CosmosClientTelemetryOptions
    {
        DisableDistributedTracing = false,
        CosmosThresholdOptions = new CosmosThresholdOptions
        {
            NonPointOperationLatencyThreshold = TimeSpan.FromMilliseconds(1),
            PointOperationLatencyThreshold = TimeSpan.FromMilliseconds(1)
        }
    })
.WithConnectionModeGateway();
```

4. Use the client to do the following operations:
    - Create an item with a duplicate id (causes a 409).
    - Do an item query using a continuation token.
    - Attempt to do a point query on an id that doesn't exist.

**Expected behavior**
Expected to see distributed tracing data in the console output for Cosmos operations.

**Actual behavior**
Distributed tracing data for ASP.NET Core and HTTP is emitted:
```
Activity.TraceId:            d306e330029507fc35402835dff885f5
Activity.SpanId:             92d93eab8739b9b9
Activity.TraceFlags:         Recorded
Activity.ActivitySourceName: Microsoft.AspNetCore
Activity.DisplayName:        api/test/{id}
Activity.Kind:               Server
Activity.StartTime:          2023-12-05T20:05:13.3759286Z
Activity.Duration:           00:00:03.9001829
```

```
Activity.TraceId:            d306e330029507fc35402835dff885f5
Activity.SpanId:             b8fd3e7c33b631bd
Activity.TraceFlags:         Recorded
Activity.ParentSpanId:       92d93eab8739b9b9
Activity.ActivitySourceName: System.Net.Http
Activity.DisplayName:        unknown
Activity.Kind:               Client
Activity.StartTime:          2023-12-05T20:05:14.1151099Z
Activity.Duration:           00:00:00.0513054
Activity.Tags:
    http.method: GET
    http.url: https://127.0.0.1:8081/unknown
    http.status_code: 200
    http.host: 127.0.0.1
```

**But** Cosmos distributed tracing is never shown. None of the Activity traces show the documented OTel `db` attributes.

**Environment summary**
SDK Version: 3.37.0
OS Version: Windows 22621.2715 (22H2)
Azure Emulator: Windows version 2.14.12.0

**Additional context**
Full repro is closed source but happy to share if contacted internally.

**Comment by sourabh1007** [comment]
Please follow this sample https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/Program.cs

**Comment by msft-personal-acct** [comment]
Thank you. After some experimentation we discovered that the missing line was:

```csharp
AppContext.SetSwitch("Azure.Experimental.EnableActivitySource", true);
```

Is there a timeline when this will no longer be experimental?

**Comment by sourabh1007** [comment]
I cannot commit any timeline yet, but we are planning to GA it by January end.
