### ISSUE TITLE
Microsoft.Azure.Cosmos.Encryption has dependency on Microsoft.Azure.Cosmos with max version 3.35.2 while min recommended versions is 3.35.4

### ISSUE THREAD

**Issue by AndriiTaranet** [Azure/azure-cosmos-dotnet-v3#4207]
I'm unable to upgrade nuget packages which is following by recommendation and upgraded their min version Microsoft.Azure.Cosmos to version 3.35.4. 

Is it possible to fix this?

**Comment by jkonecki** [comment]
Here is CosmosDB documentation stating current minimum recommended version:

https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/sdk-dotnet-v3#recommended-version

**Comment by vipulvishal-ms** [comment]
new nuget released 2.0.4  https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Encryption

**Comment by vipulvishal-ms** [comment]
released Microsoft.Azure.Cosmos.Encryption version 2.0.4 with Microsoft.Azure.Cosmos (>= 3.35.4 && <= 3.37.0)
https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Encryption

**Comment by jkonecki** [comment]
What's the reason for specifying the exact upper version of Microsoft.Azure.Cosmos dependency? Are you planning releasing new version of Microsoft.Azure.Cosmos.Encryption every time Microsoft.Azure.Cosmos is released?

I would expect the upper version to be set to `<4.0.0`

**Comment by chrisribe** [comment]
Same I'm unable to upgrade my Microsoft.Azure.Cosmos nuget packages to 3.37.1 because of:

Microsoft.Azure.Cosmos.Encryption 2.0.4 requires Microsoft.Azure.Cosmos (>= 3.35.4 && <= 3.37.0) but version Microsoft.Azure.Cosmos 3.43.1 was resolved.

@vipulvishal-ms any solution to this or should I open another issue ?
