### ISSUE TITLE
Query/Feed API’s GA Feedback

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#423]
Query/Feed API’s GA Feedback

[Create] other places means a call to service, [Get] means proxy -> Map those concepts to query 
 [ ] CreateItemQuery[Stream] -> GetItemsQuery[Stream]
 [ ] CreateItemIterator -> GetItemsIterator
 [ ] CreateItemQuery -> GetItemsLinq
 [ ] FetchNextSetAsync -> ReadNextAsync() [Get collides with Proxy]

Remove PartitionKey as Argument
Move non-ContinuationToken parameters inside RequestOptions.

[BUG] Query API Argument check
[BUG] LINQ cancellationToken
[BUG] GetItemsIterator<T> (ItemRequestOptions requestOptions = null)

**Comment by kirillg** [comment]
GetItemsQuery somehow doesn't quite click. GetItemsQueryIterator may be? At that point, do we need Items suffix? GetQueryIterator?  (and GetLinq)...
But then I'm not sure if this is critical to address...

**Comment by j82w** [comment]
#425
