### ISSUE TITLE
Add support for other PropertyNamingPolicy options

### ISSUE THREAD

**Issue by bledbet** [Azure/azure-cosmos-dotnet-v3#4238]
**Is your feature request related to a problem? Please describe.**
When we set up our CosmosClient, we inject an implementation of CosmosSerializer that uses a JsonSerializerSettings that has a ContractResolver using the SnakeCaseNamingStrategy, so all of the properties in our json Cosmos documents are in snake_case.

Unfortunately, linq serialization doesn't share these serializer settings, and has to be configured to match if you want linq queries to work.  However the CosmosLinqSerializerOptions.PropertyNamingPolicy only supports "Default" (which would essentially be PascalCase - we don't want to use snake_case in the naming of properties in C#) or "CamelCase".  So the linq queries don't work because linq doesn't derive property names in the same way that the persistence layer does.

**Describe the solution you'd like**
The simplest solution would seem to be to add additional common options for CosmosLinqSerializerOptions.PropertyNamingPolicy enum, specifically for snake_case.

But, is there a good reason for choosing to make this "PropertyNamingPolicy" an enum instead of allowing injection of something like a NamingPolicy implementation? (I imagine you are trying to decouple from Newtonsoft, and don't want to use a Newtonsoft NamingStrategy, so I am imagining "NamingPolicy" as you're own abstract/interface that hides the details of what serializer is being used)

Better yet, it seems like there should be a cohesive way to set the CosmosClient up with a NamingPolicy that would affect both the CosmosSerializer and linq for Cosmos together.

**Describe alternatives you've considered**
We have a workaround - it does work to use the JsonProperty attribute on the properties of the model that is being serialized to Cosmos.  This workaround is not ideal for a few reasons:
 - It couples our models to Newtonsoft
 - It has potential to affect all serialization of that model that happens to be using Newtonsoft to do the serialization (say we are serializing it to put it in a message broker or a cache or a blob, and for whatever reason we need to use a different property naming strategy for that serialization)
 - It litters the code
 - If you add criteria on a property in a linq query, and you forgot to add the JsonProperty attribute, that query will get unexpected results

**Comment by Maya-Painter** [comment]
Hi @bledbet, we just merged an update that allows custom serializers to be applied on LINQ queries.  More details can be found in the description of #4138.  We are planning to include this as part of our next preview release.

**Comment by Maya-Painter** [comment]
This feature is now available to test in version `3.39.0-preview.0`.
