### ISSUE TITLE
_container.GetChangeFeedProcessorBuilder<Feed>("FeedProcessor", Arg.Any<Container.ChangeFeedHandler<Feed>>()).Build()

### ISSUE THREAD

**Issue by SwatiLiyaBasecone** [Azure/azure-cosmos-dotnet-v3#4242]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by SwatiLiyaBasecone** [comment]
_container.GetChangeFeedProcessorBuilder<Feed>("FeedProcessor", Arg.Any<Container.ChangeFeedHandler<Feed>>()).Build()  in  test case returns null

**Comment by sourabh1007** [comment]
@SwatiLiyaBasecone can you please follow the template given in the description and explain the question clearly. Right now closing it as it is not actionable from our side. You can reopen with proper explanation.

**Comment by SwatiLiyaBasecone** [comment]
I am trying to write test case on "ChangeFeedProcessor" in which builder for it returns null ie GetChangeFeedProcessorBuilder is not creating "ChangeFeedProcessorBuilder" object

_container.GetChangeFeedProcessorBuilder("processorName", Arg.Any<Container.ChangeFeedHandler<ConsentFeed>>()).Build().Returns(_changeFeedProcessor);
