### ISSUE TITLE
In Test case on "ChangeFeedProcessor" it return null from _container.GetChangeFeedProcessorBuilder("processorName", Arg.Any<Container.ChangeFeedHandler<ConsentFeed>>()).Build()

### ISSUE THREAD

**Issue by SwatiLiyaBasecone** [Azure/azure-cosmos-dotnet-v3#4243]

**Comment by SwatiLiyaBasecone** [comment]
[TestMethod]
    public async Task ExecuteAsyncTest()
    {
        //Arrange
        var stoppingTokenSource = new CancellationTokenSource();

        _container.GetChangeFeedProcessorBuilder("processorName", Arg.Any<Container.ChangeFeedHandler<ConsentFeed>>()).Build().Returns(_changeFeedProcessor);
        await _worker.StartAsync(stoppingTokenSource.Token);

        await Task.Delay(1000);
        stoppingTokenSource.Cancel();

        await _changeFeedProcessor.Received().StopAsync();
    }


In above test case "GetChangeFeedProcessorBuilder" it return null instead of builder object

**Comment by SwatiLiyaBasecone** [comment]
My worker class contains the "StartChangeFeedProcessorAsync" in which it creates & build "changeFeedProcessor" through "GetChangeFeedProcessorBuilder" so test method throws error there

**Comment by SwatiLiyaBasecone** [comment]
ChangeFeedProcessorBuilder class has internal constructor with parameter and also one of the parameter is "ContainerInternal" which is internal so difficult to create proxy 
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/127828979/5a265731-3f5a-4ec4-a572-32de340e4f85)

**Comment by ealsur** [comment]
@SwatiLiyaBasecone Can you please state what you are trying to do? The ChangeFeedProcessorBuilder cannot be mocked, it's a Builder pattern.

You can however, mock `ChangeFeedProcessor` as an abstract class.

Please search for other similar Issues, like: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3486

**Comment by SwatiLiyaBasecone** [comment]
> @SwatiLiyaBasecone Can you please state what you are trying to do? The ChangeFeedProcessorBuilder cannot be mocked, it's a Builder pattern.
> 
> You can however, mock `ChangeFeedProcessor` as an abstract class.
> 
> Please search for other similar Issues, like: #3486

I want to write test case for ChangeFeedHandler<T> ie "HandleChangesAsync"

**Comment by ealsur** [comment]
In that case you don't need to mock the ChangeFeedProcessor. If your intent is to test your Handler, then you can write a test that calls your handler function with mocked data?

**Comment by SwatiLiyaBasecone** [comment]
public class CosmosContainerFeedProcessor : ICosmosContainerFeedProcessor
    {
        public virtual ChangeFeedProcessor CreateProcessor<T>(Container container, Container leaseContainer, ChangeFeedHandler<T> HandleChangesAsync)
        {
            var changeFeedProcessorBuilder = container.GetChangeFeedProcessorBuilder(processorName: "Processor", onChangesDelegate: HandleChangesAsync);

            return changeFeedProcessorBuilder
            .WithInstanceName(Environment.MachineName)
            .WithLeaseContainer(leaseContainer)
            .WithMaxItems(25)
            .WithStartTime(DateTime.MinValue.ToUniversalTime())
            .WithPollInterval(TimeSpan.FromSeconds(5))
            .Build();
        }
    }

It solved the issue to mock ChangeFeedProcessor. Thanks
