### ISSUE TITLE
A synthetic partition key makes queries with the OFFSET LIMIT clause more expensive

### ISSUE THREAD

**Issue by alesk-kontent** [Azure/azure-cosmos-dotnet-v3#4247]
**Describe the bug**

When I run a query with the `OFFSET LIMIT` clause against the same data, but with a different partitioning scheme, I can see that with a synthetic partition key, the request charge is orders of magnitude higher even if there is only a single physical partition. It seems that the SDK fetches the skipped documents.

**To Reproduce**

I wrote a simple [console application](https://github.com/Azure/azure-cosmos-dotnet-v3/files/13888713/PaginationIssue.zip) to reproduce the issue. Please download the solution, open the `Program.cs` file, and specify a connection string to an Azure Cosmos DB for NoSQL account. The application will create a new database with two containers. For both of them, it will upsert the same set of data, run a query with the `OFFSET LIMIT` clause and display important metrics. You can run the application multiple times, it will create resources and upsert data only once.

Each container contains 100 documents (articles) with the following properties:

- Id : string
- CustomerId : Guid
- Title : string

The value of the `Id` property is composed of the value of the `CustomerId` and a random GUID. The value of the `CustomerId` property is always the same. The value of the `Title` property is unique for each document.

Both containers share the same indexing policy; automatic and consistent. However, the partition key is different. The first container (with large logical partitions) has the partition key `/customerId`, so there is a single logical partition with 100 documents. The second container (with small logical partitions) has the synthetic partition key `/id`, so there are 100 logical partitions with one document.

When I run the query `SELECT * FROM c ORDER BY c.title ASC OFFSET 90 LIMIT 10` against both containers, I can observe the following results:

***Large logical partitions***

I send the customer ID as the partition key (in the request options).

Request charge: 3,49
x-ms-item-count: 10
retrievedDocumentCount: 10
retrievedDocumentSize: 3670
outputDocumentCount: 10
outputDocumentSize: 3729
indexUtilizationRatio: 1.00

***Small logical partitions***

I do not send a partition key.

Request charge: 6,35
x-ms-item-count: 100
retrievedDocumentCount: 100
retrievedDocumentSize: 36692
outputDocumentCount: 100
outputDocumentSize: 45334
indexUtilizationRatio: 1.00

**Expected behavior**

The choice of the partition key will not affect the request charge.

**Actual behavior**

With enough data, higher `OFFSET` values, and a synthetic partition key, the request charge is orders of magnitude higher. The output document count suggests that the SDK fetches the skipped documents.

**Environment summary**

SDK Version: 3.37.1
OS Version: Windows 11 Enterprise (10.0.22631 Build 22631)

**Additional context**

I tried to include the customer ID into the query, i.e. `SELECT * FROM c where c.customerId = @customerId ORDER BY c.title ASC OFFSET 90 LIMIT 10`, but the results were the same. It happens in both `Direct` and `Gateway` modes.

**Comment by adityasa** [comment]
@alesk-kontent thanks for reporting the issue. I tried your application on my collection and I am able to confirm that your observations above are accurate.

A cross (logical) partition query containing OFFSET 90 LIMIT 10 is rewritten as OFFSET 0 LIMIT 100 by the SDK and original OFFSET LIMIT calculations are applied on the client side.
At the moment, SDK client does not (by default) treat collections with single physical partitions specially and always performs the rewrite.

We have released a feature (currently in preview, soon to be released) that addresses this issue by executing the query directly in the backend when collection has a single physical partition. In such cases, you are expected to see RU usage similar to the first case.

You can find out more about it here:
https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/performance-tips-query-sdk?tabs=v3&pivots=programming-language-csharp#optimizing-single-partition-queries-with-optimistic-direct-execution

Here's a screenshot of using this feature in your app:

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/12704155/029b4bcd-d1aa-4c63-9b49-1937139b0f95)
