### ISSUE TITLE
Add new LINQ extension method .Projection()

### ISSUE THREAD

**Issue by olivermue** [Azure/azure-cosmos-dotnet-v3#4266]
**Is your feature request related to a problem? Please describe.**
Quite often we write documents down into the Cosmos DB, which we want to only partially read back. For this purpose the `.Select()` LINQ statement was choosen and can be used as described [here in the documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/linq-to-sql#select-operator). Unfortunately this is not what is mostly desired or needed. Instead we like to project only a sub-part of properties into our own already defined classes. This would be similar to the usage of the Graph SDK where you stick to a specific object type, which will only be partially filled ([see documentation](https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#select-parameter)).

This would be really helpful, to return only partial properties of a given document and deserialize them into a given class and the views and answer of [this SO question](https://stackoverflow.com/q/54309339/1838048) shows there is a demand but no solution.

**Describe the solution you'd like**
To solve this problem we need an extension method that uses the same parameter like the `.Select()` method, but instead of returning `IQueryable<TResult>` it should return `IQueryable<T>` like the `.Where()` method and thous allow _endless chaining_:
```csharp
public static IQueryable<T> Projection<TSource, TResult>(
    this IQueryable<TSource> source,
    Expression<Func<TSource, TResult>> selector)
```
Depending on how far we take the implemenation of this method we could at least quite easily implement a dynamic selection of desired properties at runtime or doing even more advanced stuff and for completeness let's start with a very basic C# class we like to write and read into Cosmos:
```csharp
public class SimpleDocument
{
    [JsonExtensionData]
    public Dictionary<string, object> AdditionalData { get; set; } = new Dictionary<string, object>();

    public string Id { get; set; } = default!;
    public string Name { get; set; } = default!;
    public int Value { get; set; }
    public string PartitionKey { get; set; } = "Default";
}
```

In the most simple implementation, all that is supported is a direct selection of first level properties:
```csharp
var queryRequestOptions = new QueryRequestOptions
{
    ConsistencyLevel = ConsistencyLevel.Session,
    PartitionKey = new PartitionKey("Default"),
}
var query = container.GetItemLinqQueryable<SimpleDocument>(true, null, queryRequestOptions, null)
    .Where(doc => doc.Value > 5)
    .Projection(doc => doc.Name)
    .Projection(doc => doc.Value);
```
But it would already allow to dynamically add properties at runtime as needed:
```csharp
    if (idIsNeeded)
        query = query.Projection(doc => doc.Id);
```
In a next evolution it could (like the `.Select()` implemenation [already does described in example 2](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/linq-to-sql#select-operator)) also allow simple computations:
```csharp
var time = DateTime.UtcNow;
var someRuntimeValue = time.Seconds;
var query = container.GetItemLinqQueryable<SimpleDocument>(true, null, queryRequestOptions, null)
    .Where(doc => doc.Value > 5)
    .Projection(doc => doc.Value - someRuntimeValue);
```
The most complex scenario comes by the usage of anonymous objects within the lambda and a twist about the meaning of the values within this object, but let's start simple:
```csharp
var query = container.GetItemLinqQueryable<SimpleDocument>(true, null, queryRequestOptions, null)
    .Where(doc => doc.Value > 5)
    .Projection(doc => new { doc.Id, doc.Value });
```
This example above uses the auto-property naming by taking the property name of the _right side_ and is equivalent to:
```csharp
var query = container.GetItemLinqQueryable<SimpleDocument>(true, null, queryRequestOptions, null)
    .Where(doc => doc.Value > 5)
    .Projection(doc => new { Id = doc.Id, Value = doc.Value });
```
So far, so good. But if the property name on the left hand side would describe the _source property_ that should be read from the Cosmos document and the right hand side would describe the target property in our C# class we could do some really cool stuff like:
```csharp
var query = container.GetItemLinqQueryable<SimpleDocument>(true, null, queryRequestOptions, null)
    .Where(doc => doc.Value > 5)
    .Projection(doc => new { _etag = doc.Name });
```
With the given line above we would instruct the Cosmos provider to read the property __etag_ and return it to us within the given C# class in property _Name_.
And in the last scenario our class supports _JsonAdditionalData_ which means, all properties that are read from Cosmos, but can't be mapped onto a matching property will be added to the _AdditionalData dictionary_, which means, we could also write something like this here:
```csharp
var query = container.GetItemLinqQueryable<SimpleDocument>(true, null, queryRequestOptions, null)
    .Where(doc => doc.Value > 5)
    .Projection(doc => new { _etag = "fooBar" });
```
The above code would read from Cosmos the property __etag_ and send its value within the property _fooBar_ which doesn't exists in our object and will be written into the dictionary with the key _fooBar_.

**Describe alternatives you've considered**
The Cosmos DB by itself and the Newtonsoft (and in a v4 SDK version also STJ) serializer support all of these described steps. Only the C# SDK misses this functionality. Currently we implemented the first described version above by ourself, but in a very hacky way by calling _queryable.ToQueryDefintion()_, manipulating the query string within the keywords _value_ and _from_, put this new query into a new QueryDefinition and call _container.GetItemQueryIterator<T>(newQueryDefinition)_. But this feels so uncorrect and having a true implementation within the SDK would make it so much easier. Also the implementation shouldn't be _that hard_ (hopefully), cause I would guess a lot of functionality can be taken from interpreting the `.Select()` method.

One last point:
Due to the fact, that you can chain multiple calls of `.Projection()` it can easily happen that a property is named twice:
```csharp
var query = container.GetItemLinqQueryable<SimpleDocument>(true, null, queryRequestOptions, null)
    .Where(doc => doc.Value > 5)
    .Projection(doc => doc.Name)
    .Projection(doc => doc.Value)
    .Projection(doc => doc.Name + "Hello");
```
In that case the implementation could choose between three different behaviours: First wins, last wins or throw exception. My personal favorite would be to throw an exception, but I could also live with one of the two others as long it is documented somewhere in the description of the method.

**Comment by adityasa** [comment]
@olivermue thanks for providing a detailed write-up.
To take this step by step, can you kindly outline the problem you are trying to solve? Best would be to show an example code that you are trying to write and the part of that code that doesn't work (either errors out, or doesn't produce correct results etc).
The stackoverflow example is pretty old and it would be great to get the latest repro.

**Comment by adityasa** [comment]
Hey @olivermue, can you use named type in Select to solve this scenario? Something like:

`IQueryable<MyDocumentClass> queryable = container
    .GetItemLinqQueryable<MyDocumentClass>(allowSynchronousQueryExecution: true)
    .Where(d => d.Revisions != null && d.Revisions[0] == "2000")
    .Select(d => new MyDocumentClass { Name = d.Name });`

For e.g. above projects _**only the names**_ of documents (books in this case) that have a Revision in year 2000. You still receive an `IQueryable<MyDocumentClass>` as a response of IQueryable after Select.

Below is the full test code I tried (for any future reference).

`
[TestMethod]
public async Task LinqProjection()
{
    Container container = await this.CreateSampleDocuments();

    IQueryable<MyDocumentClass> queryable = container
        .GetItemLinqQueryable<MyDocumentClass>(allowSynchronousQueryExecution: true)
        .Where(d => d.Revisions != null && d.Revisions[0] == "2000")
        .Select(d => new MyDocumentClass { Name = d.Name });
    var queryDefinition = queryable.ToQueryDefinition();
    Debug.WriteLine(queryDefinition?.QueryText);

    foreach (MyDocumentClass documentClass in queryable)
    {
        Debug.WriteLine(documentClass.Name);
    }
}

internal class MyDocumentClass
{
    public string id { get; set; }
    public string Name { get; set; }
    public string ISBN { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    public string Publisher { get; set; }
    public string[] Revisions { get; set; }
    public string Country { get; set; }
}

private async Task<Container> CreateSampleDocuments()
{
    ContainerProperties linqProjection = new ContainerProperties(id: "LinqProjection_" + Guid.NewGuid(), partitionKeyPath: "/Country");

    ContainerResponse response = await this.database.CreateContainerAsync(
        linqProjection,
        cancellationToken: this.cancellationToken);

    string[] countries = new string[] { "usa", "brazil", "uk", "china" };
    List<MyDocumentClass> createdList = new List<MyDocumentClass>();
    for (int i = 0; i < countries.Length; i++)
    {
        string pk = countries[i];
        for (int j = 0; j < 4; j++)
        {
            string id = j.ToString();
            MyDocumentClass doc = new MyDocumentClass
            {
                id = id,
                Name = "Name_" + id,
                ISBN = "ISBN_" + id,
                Title = "Title_" + id,
                Author = "Author_" + id,
                Publisher = "Publisher_" + id,
                Revisions = j % 2 == 0 ? 
                    new string[] { "2000" } :
                    new string[] { "2001" },
                Country = pk
            };

            createdList.Add(doc);

            await response.Container.CreateItemAsync<MyDocumentClass>(item: doc);
        }
    }

    return response.Container;
}
`

**Comment by olivermue** [comment]
Hi @adityasa, that is excellent. I had completely overlooked this spelling option and hadn't even tried it. Therefore, this type of partial document retrieval is already integrated. However, the documentation at https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/linq-to-sql#select-operator should be expanded accordingly and also listed there as a possible example.

**Comment by adityasa** [comment]
@olivermue thanks for confirming. We will update the documentation to include a sample for this case.
