### ISSUE TITLE
Custom serializer support for LINQ (#4138) does not utilize custom Date Formatter

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cosmos-dotnet-v3#4298]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When generating queries for Cosmos, DateTimes are formatted with `yyyy-MM-ddTHH:mm:ss.fffffffZ` automatically, but DateTimeOffsets are not, to workaround this you can create a custom serializer:

```C#
        Newtonsoft.Json.JsonConvert.DefaultSettings = () => new Newtonsoft.Json.JsonSerializerSettings
        {
            Converters = new List<Newtonsoft.Json.JsonConverter>
            {
                new Newtonsoft.Json.Converters.IsoDateTimeConverter()
                {
                    // yyyy-MM-ddTHH:mm:ss.fffffffZ
                    DateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffff'Z'",
                },
            }
        };
```

However, with #4138 I believe the values in the queries should also go through the custom serializer, instead of the Newtonsoft serializer.

**To Reproduce**
Add a custom DateTimeOffset serializer to your CosmosLinqSerializer

```C#
    public static readonly JsonSerializerOptions JsonOptions = new ()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        PropertyNameCaseInsensitive = true,
        Converters = {
            new JsonStringEnumConverter(),
            new DateTimeUtcConverter(),
        }
    };
public class DateTimeUtcConverter : JsonConverter<DateTimeOffset>
{
    public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return DateTimeOffset.Parse(reader.GetString()!, CultureInfo.CurrentCulture);
    }

    public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.UtcDateTime.ToString("O"));
    }
}
```

**Expected behavior**
Queries comparing with DateTimeOffset should be formatted in `yyyy-MM-ddTHH:mm:ss.fffffffZ` format in order to be handled as Date objects by Cosmos internally; otherwise it reverts to alphabetical order

**Actual behavior**
Queries use the default Newtonsoft datetimeoffset formatting, ignoring the custom serializer:

output query:
```
{{"query":"SELECT VALUE root FROM root WHERE (root[\"DateLastEvent\"] > \"2024-02-01T17:30:22.4983046+00:00\")"}}
```

**Environment summary**
SDK Version: 3.39.0-preview.0
OS Version (e.g. Windows, Linux, MacOSX): Windows 11

Additional context
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4138

**Comment by Maya-Painter** [comment]
@onionhammer Any chance you could provide some sample code?  When I check the SQL query generated using the custom serializer and your `DateTimeUtcConverter` I get the expected DateTime format.

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/130110800/17e9be92-80fd-482c-b90f-02a176ac35fa)

**Comment by onionhammer** [comment]
Hmm, now it does appear to be working.. I will try to create a repro tomorrow and re-open if I can make it break.

Thank you for looking into this so quickly; maybe I'm crazy
