### ISSUE TITLE
Is there a support for functions also similar to stored procedures

### ISSUE THREAD

**Issue by ajayraaviv** [Azure/azure-cosmos-dotnet-v3#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ajayraaviv** [comment]
The CosmosContianer class provides a managed way to work with storedprocedure it seems. Wondering if there is something similar for the function objects also.

**Comment by j82w** [comment]
Hi @ajayraaviv,

There is currently no support for functions. What's your use case for functions?

**Comment by dantheman999301** [comment]
I was about to raise an issue for this. I can see both triggers and functions are internal at the moment although there are methods further down which support creating both, is there any plan to make these public.

My personal use for them is that I'm building a migration tool and as they are part of Cosmos I wanted to support their management.

**Comment by ajayraaviv** [comment]
Sorry for the delayed response. Below is my use case for functions. 
We are provisioning a new container in the database whenever a new client is on-boarded in the application. The application will perform some queries against the collection that rely on functions to simplify the sql. Since the functions is not supported yet I am deploying these functions(about 10) manually.  I would like to be able to deploy these functions to the container after a container is provisioned and avoid the need of manual intervention. Thanks.

**Comment by dantheman999301** [comment]
@j82w is there any more information you'd like about this? It's been a couple of months now, just wondering if this is planned to be changed.

**Comment by j82w** [comment]
@kirankumarkolli what's the current plan?

**Comment by dantheman999301** [comment]
@j82w @kirankumarkolli Sorry to keep dragging this back up, but there hasn't really been much of a discussion here. Is the plan to make the methods for creating these public? I don't really see the harm in doing so, given you can create stored procedures already and I believe the old SDK supports it.

**Comment by j82w** [comment]
@dantheman999301 sorry for the delayed response.  I missed this issue when we updated our plans.  User defined functions is now supported. It will be available in the next release.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Scripts/CosmosScripts.cs

Related PRs.
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/196
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/304/files
