### ISSUE TITLE
Document that stream must be seekable

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#430]
Update all the stream API documentation to make sure that is noted that the stream must be seekable.

**Comment by ealsur** [comment]
Could we check the CanRead property and throw if not?

**Comment by j82w** [comment]
We do throw if it is not seekable, but we don't mention it anywhere in the documentation to let users know it is required.

**Comment by jcocchi** [comment]
In general, we don't have very good documentation around the Stream APIs, assigning this to myself and putting it in the backlog.
