### ISSUE TITLE
OpenTelemetry net.peer.name attribute is out of date

### ISSUE THREAD

**Issue by JamesNK** [Azure/azure-cosmos-dotnet-v3#4309]
The net.peer.name attribute [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/3f421fbb03f7f93950bd6eb16032ce4d852420c3/Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributeKeys.cs#L19) is out of date.

address.server is the modern name. See https://github.com/open-telemetry/opentelemetry-specification/issues/3199

Should also add peer.service which is a general name: https://github.com/open-telemetry/semantic-conventions/blob/482cb01c4598429c65dd0b123b30259f41b360cb/docs/general/attributes.md#general-remote-service-attributes

**Comment by sourabh1007** [comment]
Discussed this with @lmolkova and @jcocchi. Agreed to make this change as HTTP semantic conventions are stable now.
