### ISSUE TITLE
Activity should have a span kind of client

### ISSUE THREAD

**Issue by JamesNK** [Azure/azure-cosmos-dotnet-v3#4310]
The CreateDatabaseIfNotExistsAsync activity has an kind of unspecified. It should be client. Other activities in the client should probably have a client kind.

**Comment by sourabh1007** [comment]
Right now, every internal operation is of "Internal" type (in Direct Mode, it is of "client" type as of now to support appinsights user experience) and network interactions are of "Client" type.
ref. https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitykind?view=net-8.0#fields

Can you please share a screenshot, where activity has a kind of "unspecified" and information about APM tool. We are always setting this value.

**Comment by JamesNK** [comment]
I took a look and it turns out it is a bug in our tool. Internal was incorrectly mapped to unspecified. Cosmos is doing the right thing. I'll fix our tool.

Something I did notice was the nesting of spans with `CreateDatabaseIfNotExistsAsync`.

First attempt:

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/303201/138bb0e9-8211-438a-922f-055b0b05314c)

Second attempt:

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/303201/c2ecad47-aeec-4ec9-b6b1-00a5087b1c9a)

Seems like an odd result.

**Comment by kirankumarkolli** [comment]
CreateIfNotExists is not a service contract and is the core of the issue here.

Typical flow will be like 
- GET: Check if it exists -> if (EXSITS) return 
- POST: Create
  - Succeeds -> return 
  - Confict -> GET(Read) and return 

Above flow is very interesting. 

@JamesNK possible to share with the all details view?

**Comment by JamesNK** [comment]
![cosmos-client](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/303201/c39194c1-0e03-4c9a-b32d-22ed76a791ec)

I know all the calls are failing. The nesting seems odd.

This is from running the cosmos sample in Aspire and requesting the client website twice: https://github.com/dotnet/aspire/tree/main/playground/CosmosEndToEnd

**Comment by sourabh1007** [comment]
Can you please provide more detail here, what is the odd nesting you are talking about? 

What all you are subscribed to? Azure.Cosmos.Request, Azure.Cosmso.Operation and HttpListener?

**Comment by JamesNK** [comment]
It's here: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4310#issuecomment-1931245345

I'm just running the end-to-end Cosmos sample and I'm seeing some weird telemetry results. I don't know if they are an error or not, but it seems weird. I linked to the sample if you want to investigate and get more information.

**Comment by kirankumarkolli** [comment]
@JamesNK is it about the difference between first and seconds attempts? 
In first case: One of the interactions is outside the nesting.

**Comment by JamesNK** [comment]
If it's correct then you can close this issue.

**Comment by sourabh1007** [comment]
yes, it is expected...
Outside the nesting, you are seeing: 169.254...Is AIMS call https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service
Other calls are related to the operation you are performing ie `CreateDatabaseIfNotExistsAsync`

**Comment by JamesNK** [comment]
> Other calls are related to the operation you are performing ie CreateDatabaseIfNotExistsAsync

But then shouldn't the spans then be nested inside the CreateDatabaseIfNotExistsAsync span?

**Comment by kirankumarkolli** [comment]
CosmosClient part of its initialization do some work which involved network IO. 
And then part of the actual request invocation. 

For the actual request right nesting in-place. The confusion is about the first part. 

@sourabh1007 for emulator targeted client what's the value of IMDS? Can it be conditional?
Possibly one less thing to worry about.
