### ISSUE TITLE
SDK reports "'ORDER BY' is not supported in subqueries" For valid query

### ISSUE THREAD

**Issue by enricoferrari** [Azure/azure-cosmos-dotnet-v3#4328]
**Description**
When I create an Item Queryable with OrderBy and Skip Take then read from a FeedIterator, an exception is thrown with error:
"code":"SC2202","message":"'ORDER BY' is not supported in subqueries."

The Same query executes successfully in Data Explorer and returns results, but fails when using the feed iterator.
Here is the SQL (generated by calling Queryable.ToString) - 
`SELECT VALUE root FROM root WHERE ((root["CompanyId"] = "49c7b17e-2b77-4410-b1f9-d4fee4a11027") AND (root["ShipmentMode"]["FormType"] = 6)) ORDER BY root["ShipmentDate"] ASC OFFSET 0 LIMIT 15
`
**To Reproduce**
This Queryable is basically just:
```
q = container..GetItemLinqQueryable<Shipment>();
q = q.Where(e => e.CompanyId == companyId);
q = q.Where(e => e.ShipmentMode.FormType == formType);
q = q.OrderBy(e => e.ShipmentDate);
q = q.Skip(skipRecords).Take(takeRecords);
using (FeedIterator<ShipmentClass> setIterator = q.ToFeedIterator())
{
    var results = new List<Shipment>();
    while (setIterator.HasMoreResults)
    {
        // ... exception is thrown
        foreach (var item in await setIterator.ReadNextAsync())
        {
            results.Add(item);
        }
    }
}
```

**Expected behavior**
I believe this to be a valid use of OrderBy and Skip Take. The query should execute successfully using the SDK client

**Actual behavior**
The query execution fails. The following exception is thrown:
```
 Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: ({"errors":[{"severity":"Error","location":{"start":168,"end":201},"code":"SC2202","message":"'ORDER BY' is not supported in subqueries."},{"severity":"Error","location":{"start":202,"end":219},"code":"SC2204","message":"'OFFSET LIMIT' clause is not supported in subqueries."}]}););
 ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"errors":[{"severity":"Error","location":{"start":168,"end":201},"code":"SC2202","message":"'ORDER BY' is not supported in subqueries."},{"severity":"Error","location":{"start":202,"end":219},"code":"SC2204","message":"'OFFSET LIMIT' clause is not supported in subqueries."}]} ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x800A0B00
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.<TryGetPartitionedQueryExecutionInfoAsync>d__9.MoveNext()
...

```

**Environment summary**
SDK Version: 3.38.0
OS Version:  Windows 11

**Comment by bartelink** [comment]
as a workaround, does shifting the OrderBy earlier in the query make any difference?

**Comment by enricoferrari** [comment]
> as a workaround, does shifting the OrderBy earlier in the query make any difference?

No it does not. I tried removing all WHERE criteria and I get the same result even for something as simple as this:
```
// db and container names hidden from this snippet
q = cosmosClient.GetDatabase("xxxx").GetContainer("xxxxx").GetItemLinqQueryable<Shipment>();
q = q.OrderBy(e => e.ShipmentDate);
q = q.Skip(skipRecords).Take(takeRecords);
using (FeedIterator<ShipmentClass> setIterator = q.ToFeedIterator())
...
```

I tried removing the orderBy entirely and I get the similar error:
```
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: ({"errors":[{"severity":"Error","location":{"start":56,"end":73},"code":"SC2204","message":"'OFFSET LIMIT' clause is not supported in subqueries."}]}););
 ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"errors":[{"severity":"Error","location":{"start":56,"end":73},"code":"SC2204","message":"'OFFSET LIMIT' clause is not supported in subqueries."}]} ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x800A0B00
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.<TryGetPartitionedQueryExecutionInfoAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
```

**Comment by enricoferrari** [comment]
Update: 
Ultimately I think the issue is with the offset paging. Everything works when I remove the `q = q.Skip(skipRecords).Take(takeRecords);` All of the Where clauses and even the orderby work fine without the paging.

Unfortunately, this style of paging is a requirement for what I am doing. Continuation based paging is not feature rich enough.

**Comment by enricoferrari** [comment]
Ok I think I have found the real issue. A previous part of on my code was calling q.Count() before the paging. while I was refactoring the code this was mistakenly being called AFTER using the feed iterator. THIS is the actual source of the issue. Removing it makes allows the results to be read successfully.  
This issue should be closed. apologies for the confusion
