### ISSUE TITLE
Linq query translator does not use the JsonPropertyName attributes

### ISSUE THREAD

**Issue by the-programmer** [Azure/azure-cosmos-dotnet-v3#4331]
**Describe the bug**
While using LINQ to build query's for Cosmos DB the JsonPropertyName attributes are not respected.

**To Reproduce**
Say we have the following document
``` C#
public class DeviceDocument
{
    [JsonPropertyName("deviceid")]
    public string? DeviceId { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; } = Guid.NewGuid().ToString();
}
```
And the following contents in the container
``` json
{
    "id": "1",
    "deviceid": "MyDevice"
}
```
Next I want to run a query against cosmos with a filter on DeviceId.
``` C#
var queryable = cosmosClient.GetDatabase("MyDatabase").GetContainer("MyContainer").GetItemLinqQueryable<DeviceDocument>();

var query = queryable.Where(x => x.DeviceId == "MyDevice");

var feedIterator = query.ToFeedIterator();

var items = new List<DeviceDocument>();

while (feedIterator.HasMoreResults)
{
    foreach (var item in await feedIterator.ReadNextAsync())
    {
        items.Add(item);
    }
}
return items;
```
**Actual behavior**
The generated query now becomes
``` SQL
SELECT VALUE root FROM root WHERE root["DeviceId"] = "MyDevice"
```
However since "DeviceId" does not match "deviceid" in the database the query does not return anything.

**Expected behavior**
That the query translator also checks for the JsonPropertyNameAttribute on a property and adjusts the query accordingly. So the query becomes
``` SQL
SELECT VALUE root FROM root WHERE root["deviceid"] = "MyDevice"
```

**Environment summary**
SDK Version: 3.38.1
OS Version: Windows 11, .net 8

**Comment by the-programmer** [comment]
While browsing the `GetItemLinqQueryable()` arguments, I noticed we can set the `CosmosLinqSerializerOptions` to use the `CamelCase` naming policy.

My suggestion would be to add a `PropertyName` naming policy, so the behavior can be selected.

**Comment by Maya-Painter** [comment]
There are two serializers

| Type | Stage | Scenarios | Description |
| ---- | ---- | ---- | ------ |
| CosmosSerializer | GA | All except LINQ | Only for POCO type serialization and se-serialization |
| **Preview**: [CosmosLinqSerializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosLinqSerializer.cs) | Preview | All including LINQ | Hints to LINQ about property name conversion |

@the-programmer  Can you please test with the CosmosLinqSerializer which is currently in preview?

**Comment by the-programmer** [comment]
Hi @Maya-Painter. At the moment I didn't get it working but that could just be a skill issue.

First I created the `SystemTextJsonSerializer` from the example in the [CosmosLinqSerializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosLinqSerializer.cs) documentation.

Next I updated the `CosmosClient` to become
```C#
var clientOptions = new CosmosClientOptions()
{
    Serializer = new SystemTextJsonSerializer(new JsonSerializerOptions()),
};

//Add the CosmosDB Client
var cosmosClient = new CosmosClient(connectionstring, clientOptions);
```
Finally I removed the `CosmosLinqSerializerOptions` in `GetItemLinqQueryable`. 

However the query preview still used the property names instead of the attribute names.

**Comment by Maya-Painter** [comment]
Glad to hear it worked for you @the-programmer! We plan on making the LINQ custom serializer public on the next release and will update sample code and documentation to clarify how exactly this feature can be used. Unless you have any other concerns, I can close this issue.

**Comment by the-programmer** [comment]
Yes, the issue can be closed since it will be fixed in the next release.
