### ISSUE TITLE
Incorrect results returned from GetItemQueryIterator

### ISSUE THREAD

**Issue by AndriySvyryd** [Azure/azure-cosmos-dotnet-v3#4339]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
The following query returns less results than expected
```SQL
SELECT DISTINCT c["City"]
FROM root c
WHERE (c["Discriminator"] = "Customer")
ORDER BY c["CustomerID"]
```

**To Reproduce**
Run the attached project [CosmosIssue.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/14490676/CosmosIssue.zip)

**Expected behavior**
The query should return 69 results

**Actual behavior**
The query returns 68 results

**Environment summary**
SDK Version: 3.38.1
OS Version (e.g. Windows, Linux, MacOSX): Windows 11

**Additional context**
Worked correctly on 3.37.0

**Comment by Maya-Painter** [comment]
@AndriySvyryd as a temporary mitigation, can you try setting EnableOptimisticDirectExecution = false in your QueryRequestOptions?  Doing this in your repro resulted in the query returning the expected number of results.

**Comment by Maya-Painter** [comment]
@AndriySvyryd After investigating this further we have discovered that enabling OptimisticDirectExecution was not the source of the issue, rather it exposed a latent bug in our backend.  This issue will be fixed in our next backend release. No action will be needed from your side.  I can update you here once the fix has been deployed to all regions.

Thanks for the repro, it was very helpful in getting to the root of the problem.

**Comment by Maya-Painter** [comment]
@AndriySvyryd All regions should have received the fix at this point, could you confirm that the query now returns the expected number of results?

**Comment by AndriySvyryd** [comment]
@Maya-Painter It still fails for Cosmos emulator v2.14.16. Do you know when a version with the fix would be released?

**Comment by Maya-Painter** [comment]
@AndriySvyryd Unfortunately we don't know when new emulator versions will be released

**Comment by AndriySvyryd** [comment]
Ok. When not running against the emulator I get the correct results now.

**Comment by Maya-Painter** [comment]
@AndriySvyryd Thanks for checking. Closing this issue as resolved, please tag me if you have any further questions or concerns.
