### ISSUE TITLE
Custom Request Handler: When deployed to Azure, Properties nor Headers in Request Options are added to RequestMessage

### ISSUE THREAD

**Issue by j03ybh** [Azure/azure-cosmos-dotnet-v3#4340]
I am configuring my QueryRequestOptions with headers and properties before calling the query method on the CosmosClient, like so:

requestOptions.AddRequestHeaders = (headers) =>
{
    headers.Add(RequestContextPropertyKeys.PermissionType, $"{permissionType}");
};  

requestOptions.Properties = new Dictionary<string, object>()
{
    [RequestContextPropertyKeys.CosmosRequest] = request,
    [RequestContextPropertyKeys.PermissionType] = permissionType
};

Then in my custom Request Handler, I am reading the properties and headers like so:

public override async Task<ResponseMessage> SendAsync(RequestMessage request, CancellationToken cancellationToken)
{
    if (!request.Headers.TryGetValue(RequestContextPropertyKeys.PermissionType, out var permissionType))
    {
        throw new Exception($"Headers do not contain permissionType.");
    }
    ... etc
}

The problem is, locally this works perfectly fine. The RequestMessage.Headers contain 12 headers, of which two are my custom headers added in the QueryRequestOptions. The RequestMessage.Properties are also filled with all properties I add to the QueryRequestOptions. 
But, as soon as I deploy my api in Azure Container Apps, or Azure App Service, then RequestMessage.Properties is empty, and RequestMessage.Headers does not contain any headers I added in the QueryRequestOptions..

I am lost. How and why is it possible that properties and headers are added to RequestMessage from the RequestOptions locally, but not when I deploy my api to Azure?
This behaviour does not seem right at all.

**Comment by ealsur** [comment]
Please share a reproducible example. There is no code in the SDK that would react differently when deploying to any environment.

We cannot help debugging what is happening in your environment, I would make sure that the bits deployed are exactly what you have locally, including DLL version verification.
