### ISSUE TITLE
Wrong sample code for ReadItemAsync

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-cosmos-dotnet-v3#4343]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#42563](https://github.com/Azure/azure-sdk-for-net/issues/42563).

### Type of issue

Code doesn't work

### Description

The sample on this page is wrong.

`await this.container.ReadItemAsync<ToDoActivity>` does not return `ToDoActivity` but `ItemResponse<ToDoActivity>`.
Documented correctly, but not used correctly in the Examples on this page.

Microsoft.Azure.Cosmos 3.38.1

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readitemasync?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml

### Document Version Independent Id

e7668b21-8894-5f28-8fbf-a029dfd82079

### Article author

@azure-sdk

### Metadata

* ID: 78c49c42-9f71-8275-4d4c-b5c38175cf5d 
* Service: **cosmos-db**

**Comment by FabianMeiswinkel** [comment]
The sample is fine - ItemResponse<T> implements implicit cast operator to T - see https://github.com/Azure/azure-cosmos-dotnet-v3/blob/deab135c9b8709abf3e62f7be08e6c022513e4bf/Microsoft.Azure.Cosmos/src/Resource/Response.cs#L24-L31
