### ISSUE TITLE
No preview version of Microsoft.Azure.Cosmos since v3.38.0

### ISSUE THREAD

**Issue by ramondeklein** [Azure/azure-cosmos-dotnet-v3#4358]
The preview method `DeleteAllItemsByPartitionKeyStreamAsync` (see [documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-delete-by-partition-key)) is available in the "preview" packages, but these preview packages are not released anymore since v3.38.0, but the functionality hasn't moved to GA yet.

I would expect that preview versions of this package is being released, until the method is moved into the official package.

Version overview: [NuGet versions](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.38.0) (the v3.39.0-preview versions also don't include this method). The latest version that can be used is [v3.37.1-preview](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.37.1-preview).

**Comment by kundadebdatta** [comment]
Hi @ramondeklein : Please note that this API `DeleteAllItemsByPartitionKeyStreamAsync` is available in the [3.39.0-preview.0 package](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/contracts/API_3.39.0-preview.0.txt#L254). Please let me know if you still have issues using this API.

Here is the [link](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.39.0-preview.0) to the released nuget package.
