### ISSUE TITLE
No SubStatusCode for CosmosException with MalformedChangeFeedContinuationToken

### ISSUE THREAD

**Issue by albertofori** [Azure/azure-cosmos-dotnet-v3#4366]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**

Currently, the CosmosException thrown for MalformedChangeFeedContinuationTokenException has SubStatusCode 0 as it is not populated when [formulating the BadRequestException](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/ab8017023d7414e4966679bdaa6c6abe8842ffd9/Microsoft.Azure.Cosmos/src/Query/Core/ExceptionToCosmosException.cs#L157C13-L164C14). This is inconsistent with the Exception thrown for invalid continuation token in regular queries (sql queries), which has the [SubStatusCode populated](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/ab8017023d7414e4966679bdaa6c6abe8842ffd9/Microsoft.Azure.Cosmos/src/Query/Core/ExceptionToCosmosException.cs#L114C17-L124C14) and can therefore be used to clearly determine that a query has invalid continuation token when CosmosException with status code 400 is thrown. 

To Reproduce**

```cs
            return _container.GetChangeFeedStreamIterator(
                ChangeFeedStartFrom.ContinuationToken("SomeInvalidContinuationToken");,
                ChangeFeedMode.Incremental,
                new ChangeFeedRequestOptions
                {
                    PageSizeHint = 100
                });
```

**Expected behavior**

Throw `CosmosException` with SubStatusCode `20007` (Corresponding to SubStatusCodes.MalformedContinuationToken)

**Actual behavior**

Throws `CosmosException` with SubStatusCode 0
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/102393878/b0cb84ff-c680-48b4-af3f-f7ef7bd934e6)

**Environment summary**
SDK Version: 3.38.0
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by NaluTripician** [comment]
Addressing via [this PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4583). Thanks for bringing this to our attention!
