### ISSUE TITLE
Cosmos DB deserializer fails silently - GetItemQueryIterator

### ISSUE THREAD

**Issue by oragain** [Azure/azure-cosmos-dotnet-v3#4378]
**Describe the bug**
So, I'll preface by saying I am not sure this is a CosmosDB SDK issue or if it is a NewtonSoft issue. 

When you do complex queries with joins on cosmos DB, the query can return the result encapsulated into a nested type. Hence, one of the reasons, why the VALUE keyword exists. (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/select)
And so when doing a search, instead of getting an array of T as a result, you get an array of objects that contain T.

This is where it gets muddy for me. In my case, the following does retrieve 1 record, i do get to response.First():
`
FeedIterator<T> iterator = projectContainer.GetItemQueryIterator<T>(qD);
while (iterator.HasMoreResults)
{
    FeedResponse<T> response = iterator.ReadNextAsync().Result;
    if (response.Any())
    {
        projectAggregate = response.First();
        
        break;
    }
}`
But, because I forgot the VALUE keyword in my QueryDefinition, I get a new T()

So, somewhere between GetItemQueryIterator and FeedIterator, the deserializer failed to parse the incoming object (normal because T is nested) but, instead of failing, it silently fails and replaces the 1 result, with a new T()

Hopefully, that makes sense.

**To Reproduce**
Search a container for an object but instead provide a query definition that will retrieve the object nested.

**Expected behavior**
I would expect an exception of some sort saying that the returned results could not be deserialized

**Actual behavior**
Returns a new object of type T

**Environment summary**
SDK Version: 3.39.0-preivew.1
OS Version: Windows 11
IDE: Visual Studio 2022

**Comment by ealsur** [comment]
Can you please share a working repro? Which is the `T` you are passing? Which is an example of a JSON document?

**Comment by SocVi100** [comment]
I'm experiencing a similar issue, and my objects are not nested...

```c#
        List<Usuario> resultados = new();
        using FeedIterator<Usuario> resultSet = containerUsuarios.GetItemQueryIterator<Usuario>(
            new QueryDefinition(sql),
            requestOptions: new QueryRequestOptions() 
            {
                PartitionKey = claveParticion,
                MaxItemCount = -1 
            });

        while (resultSet.HasMoreResults)
        {
            try
            {
                FeedResponse<Usuario> resp = await resultSet.ReadNextAsync();
                resultados.AddRange(resp);
            }
            catch (CosmosException ex)
            {
                var dummy = ex;
            }
        }

        return resultados;
``` 

The execution halts on "await resultSet.ReadNextAsync();" and the catch block is not honored...

My query is trying to get only three properties of a 20 properties object.
