### ISSUE TITLE
Add Internal/Friends Execute Stored Procedure Function With PK Range Id Option

### ISSUE THREAD

**Issue by kundadebdatta** [Azure/azure-cosmos-dotnet-v3#4382]
- Add Internal/Friends Execute Stored Procedure Function With PK Range Id Option.
- Add an internal/Friends "ReadPartitionKeyRangeFeedAsync" client/container function for Cosmos DB V3 .NET SDK similar to V2.

**Comment by bartelink** [comment]
For things like this, would love to see eve a one-liner as to the use case
For instance I'd be interested to see if the stored proc exec overlaps with the bulk facility as covered in https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1496#issuecomment-1674933345

**Comment by kirankumarkolli** [comment]
All public Stroe procedure invocations are scoped to a single logical partition key. 
There are some internal specific use cases where this capability is needed (ex: V2 bulk library etc...)

**Comment by kundadebdatta** [comment]
This is covered with `msdata` PR: `1322381`

**Comment by kundadebdatta** [comment]
PR merged to `master`
