### ISSUE TITLE
Distributed Tracing: Add RequestChargeThreshold to CosmosThresholdOptions

### ISSUE THREAD

**Issue by jcocchi** [Azure/azure-cosmos-dotnet-v3#4385]
Customers should be able to add a filter for traces based on the RU charge of a request. This option already exists in Java https://learn.microsoft.com/en-us/java/api/com.azure.cosmos.cosmosdiagnosticsthresholds?view=azure-java-stable

**Comment by kirankumarkolli** [comment]
Is Payload size based filtering also a requirement? 

Even if its not for consistency, how about include both?

**Comment by kovarikthomas** [comment]
Hi Kiran - I discussed it with Justine on Teams, the requirement here is mainly around monitoring for queries with high RU charges, but I suppose that anything that closes the gap w.r.t. Java SDK helps. (https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosDiagnosticsThresholds.java)

**Comment by bartelink** [comment]
For a moment my heart skipped a beat thinking that https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1763 was being addressed (I'd still love to be able to define a size or RU budget for queries in general, and ChangeFeedl requests in particular).
Having to pick between ultra conservative 100 docs or setting a huge limit and getting lumpy RU costs when the documents are not of uniform size is very unfortunate in terms of delivering consistent throughput without random large requests causing rate limiting when that's absolutely not the intent of the system.
