### ISSUE TITLE
LINQ: Enums convertor using System.Text.Json is not working

### ISSUE THREAD

**Issue by v-mghabin** [Azure/azure-cosmos-dotnet-v3#4388]
I've followed this https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3250 but sounds it didn't solve the Enums conversation to strings.
The latest solution from that issue is to use a custom serializer `CosmosSystemTextJsonSerializer` that inherits `CosmosSerializer` and `CosmosLinqSerializer` but that won't work because `CosmosLinqSerializer` is internal class and can't be inherited due to protection level. 

My main issue that when trying to use LINQ and filter items based on Enum that has been converted to string, it is not returning any result because it compares the converted string with int.

Record in DB
```
"State": "Finish"
```

Enum in C# converted using System.Text.Json Convertor:
```
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum State
{
    None = 0,
    InProgress = 1,
    Finish = 2,
    Failed = 3,
}
```

**Comment by Maya-Painter** [comment]
@v-mghabin The code proposed in #3250 is incorrect. I had a discussion with the user here- https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2685#issuecomment-1888012810

Here is an example of how you could implement `CosmosLinqSerializer` for your scenario. Please give it a try and let me know how it goes:
```
 class SystemTextJsonLinqSerializer : CosmosLinqSerializer
  {
      private readonly JsonObjectSerializer systemTextJsonSerializer;

      public SystemTextJsonLinqSerializer(JsonSerializerOptions jsonSerializerOptions)
      {
          this.systemTextJsonSerializer = new JsonObjectSerializer(jsonSerializerOptions);
      }

      public override T FromStream<T>(Stream stream)
      {
          if (stream == null)
              throw new ArgumentNullException(nameof(stream));

          using (stream)
          {
              if (stream.CanSeek && stream.Length == 0)
              {
                  return default;
              }

              if (typeof(Stream).IsAssignableFrom(typeof(T)))
              {
                  return (T)(object)stream;
              }

              return (T)this.systemTextJsonSerializer.Deserialize(stream, typeof(T), default);
          }
      }

      public override Stream ToStream<T>(T input)
      {
          MemoryStream streamPayload = new MemoryStream();
          this.systemTextJsonSerializer.Serialize(streamPayload, input, input.GetType(), default);
          streamPayload.Position = 0;
          return streamPayload;
      }

      public override string SerializeMemberName(MemberInfo memberInfo)
      {
          System.Text.Json.Serialization.JsonExtensionDataAttribute jsonExtensionDataAttribute =
              memberInfo.GetCustomAttribute<System.Text.Json.Serialization.JsonExtensionDataAttribute>(true);
          if (jsonExtensionDataAttribute != null)
          {
              return null;
          }

          JsonPropertyNameAttribute jsonPropertyNameAttribute = memberInfo.GetCustomAttribute<JsonPropertyNameAttribute>(true);

          string memberName = !string.IsNullOrEmpty(jsonPropertyNameAttribute?.Name)
              ? jsonPropertyNameAttribute.Name
              : memberInfo.Name;

          return memberName;
      }
  }
```

**Comment by v-mghabin** [comment]
Can u pls elaborate when this change will be released as our team can't use a preview package in production?

**Comment by Maya-Painter** [comment]
@v-mghabin it will be part of the next public package, which we are hoping to release in the next couple weeks

**Comment by v-mghabin** [comment]
@Maya-Painter 
I noticed the new release is published but still it is not reflected in NuGet which is weird!
Can u pls elaborate on this?

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/159933226/ca3b830f-4cc7-4c4a-b6ee-c0a5d95005b3)
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/159933226/15de5d58-74f9-43b6-bd79-88ce9a906c2b)

**Comment by Maya-Painter** [comment]
@v-mghabin Apologies for the delay, there are some failing gates blocking the release.  More discussion here - https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4412

**Comment by Maya-Painter** [comment]
3.39 has been released, thanks everyone for your patience. `CosmosLinqSerializer` is included as part of this release and allows for enum conversion in LINQ queries. Closing this issue as addressed. Please feel free to tag me with any follow up questions or concerns.
