### ISSUE TITLE
Missing NuGet package 3.39.0

### ISSUE THREAD

**Issue by mamk95** [Azure/azure-cosmos-dotnet-v3#4412]
**Describe the bug**
Version 3.39.0 was released two days ago on GitHub (2024-04-10), and according to the release notes it was published to NuGet 7 days ago (2024-04-05). The package is still not available on the NuGet website. Following the link from the release note to NuGet gives the warning of "The specified version 3.39.0 was not found. You have been taken to version 3.38.1."

![cosmos nuget](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/10944333/76ed2c23-3479-4f33-8f76-a2c0f5856dc7)

**To Reproduce**
1. Go to the release notes: https://github.com/Azure/azure-cosmos-dotnet-v3/releases
2. In the top release (3.39.0), see that it was published two days ago (2024-04-10), and that it claims the NuGet package was released 7 days ago (2024-04-05)
3. In the top release (3.39.0), click on the blue link with the text "3.39.0" to be taken to https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.39.0
4. Notice the error message on nuget.org saying the package version doesn't exist: "The specified version 3.39.0 was not found. You have been taken to version 3.38.1."

**Expected behavior**
Version 3.39.0 of the package Microsoft.Azure.Cosmos should be published to NuGet and available for download from https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.39.0

**Actual behavior**
The latest stable release on NuGet is 3.38.1 from 2024-02-08, and the latest pre-release on Nuget is 3.39.0-preview1 from 2024-02-08. Version 3.39.0 is not available.

**Environment summary**
Error trying to find version 3.39.0 tested in multiple browsers (latest version of Firefox, Edge, Chrome on Windows 10 with cache cleared) and using Visual Studio 2022 v17.9.5.

**Additional context**
[NuGet's status page](https://status.nuget.org/) says everything is working correctly on NuGet's side. All recent releases of Microsoft.Azure.Cosmos has been available on NuGet shortly before or after the GitHub release, and has never been delayed for such a long time.

Maybe a release pipeline has gotten stuck?

**Comment by waszakCeneo** [comment]
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/118433754/89824cb0-8d20-495b-b120-fb96fafe6176)
I had the same issue and found that release branch is failing tests.
Maybe this delayed release for nugget package

**Comment by philipthomas-MSFT** [comment]
Apologies. There is a delay. We are already working on correcting this. In retrospective, there are some gates in the process that we need to discuss. However, the goal is to get this release out as soon as possible. We appreciate your patience.

**Comment by onionhammer** [comment]
@philipthomas-MSFT is there a new ETA?

**Comment by philipthomas-MSFT** [comment]
The GA and preview release is now complete. Please close this issue at your earliest convenience.
