### ISSUE TITLE
ChangeFeedProcessorBuilder throws exception for ChangeFeedMode on 3.39.0

### ISSUE THREAD

**Issue by Blackbaud-IanThomas** [Azure/azure-cosmos-dotnet-v3#4423]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
After upgrading to 3.39.0 of the SDK, services using ChangeFeedProcessorBuilder are throwing an exception with the description:
> System.ArgumentException: Switching ChangeFeedMode  to Incremental Feed is not allowed.

**To Reproduce**
The issue appears to be with services where the lease document is a "legacy document". To reproduce requires a service where the lease document does not have the "Mode" property. Using ChangeFeedProcessorBuilder with the following basic configuration:
```
_sourceContainer
                    .GetChangeFeedProcessorBuilder<JObject>("ChangeFeed", HandleChangesAsync)
                    .WithInstanceName($"ChangeFeed-{Guid.NewGuid()}")
                    .WithLeaseContainer(_leaseContainer)
                    .Build();
```
will result in the behavior. 

**Expected behavior**
Services with legacy documents for change feed work after upgrade with no required changes.

**Actual behavior**
Services with legacy documents for change feed throw exception and fail to start change feed processor.

**Environment summary**
SDK Version: 3.39.0
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**

In exploring the underlying code, it appears that the default `ChangeFeedProcessorBuilder` is being set to `ChangeFeedMode.LatestVersion` [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/bf4704f5cfec00fd1e7cb8b81c02ce8d53e15d41/Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs#L464), but that is then getting mapped to a value for `ChangeFeedIncremental`, [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/bf4704f5cfec00fd1e7cb8b81c02ce8d53e15d41/Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedMode.cs#L25C4-L41C90).
When a legacy document is encountered, the mode is defaulted to `LatestVersion` [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/bf4704f5cfec00fd1e7cb8b81c02ce8d53e15d41/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManager.cs#L93C11-L106C14), which doesn't match anymore due to the remapping that took place in between.

**Comment by ernesto1596** [comment]
This is a breaking change for our production service.

**Comment by philipthomas-MSFT** [comment]
Investigation underway. Thanks for your patience:
