### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#4427]
Upgrading from 3.37.1 to 3.38 and above has caused "Illegal instruction" to occur when running queries on 1 developer's virtual machine. Here's the trace info we captured.

DocDBTrace Information: 0 : Initializing VM Metadata API 
DocDBTrace Information: 0 : Loading VM Metadata
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.17\System.Net.Requests.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Repos\*************.SDK\Layer04\*************.Layer04.Tests\bin\Debug\net7.0\Microsoft.IdentityModel.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
DocDBTrace Information: 0 : Azure Environment metadata information not available. 0
DocDBTrace Information: 0 : DocumentClient with id 1 initialized at endpoint: https://***************************.documents.azure.com/ with ConnectionMode: Direct, connection Protocol: Tcp, and consistency level: null
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Repos\*************.SDK\Layer04\*************.Layer04.Tests\bin\Debug\net7.0\Microsoft.Azure.Cosmos.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'testhost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.17\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
DocDBTrace Information: 0 : SystemUsageMonitor started
DocDBTrace Information: 0 : Current WriteEndpoints = (https://***************************-centralus.documents.azure.com/) ReadEndpoints = (https://***************************-centralus.documents.azure.com/)
DocDBTrace Information: 0 : GlobalEndpointManager: StartLocationBackgroundRefreshWithTimer() refreshing locations
DocDBTrace Information: 0 : Creating RNTBD TransportClient with options Rntbd.TransportClient.Options
  OpenTimeout: 00:00:05
  RequestTimeout: 00:00:06
  TimerPoolResolution: 00:00:01
  MaxChannels: 65535
  PartitionCount: 1
  MaxRequestsPerChannel: 30
  ReceiveHangDetectionTime: 00:01:05
  SendHangDetectionTime: 00:00:10
  IdleTimeout: -00:00:01
  UserAgent: cosmos-netstandard-sdk/3.39.0|1|X64|Microsoft Windows 10.0.22631|.NET 7.0.17|N| Suffix: 
  CertificateHostNameOverride: 
  LocalRegionTimeout: 00:00:05
  EnableChannelMultiplexing: False
  MaxConcurrentOpeningConnectionCount: 5
  Use_RecyclableMemoryStream: False
  Use_CustomDnsResolution: False
  IsDistributedTracingEnabled: False

DocDBTrace Information: 0 : TimerPool Created with minSupportedTimerDelayInSeconds = 1
DocDBTrace Information: 0 : Creating RNTBD TransportClient with options Rntbd.TransportClient.Options
  OpenTimeout: 00:00:05
  RequestTimeout: 00:00:06
  TimerPoolResolution: 00:00:01
  MaxChannels: 65535
  PartitionCount: 1
  MaxRequestsPerChannel: 1
  ReceiveHangDetectionTime: 00:01:05
  SendHangDetectionTime: 00:00:10
  IdleTimeout: -00:00:01
  UserAgent: cosmos-netstandard-sdk/3.39.0|1|X64|Microsoft Windows 10.0.22631|.NET 7.0.17|N| Suffix: 
  CertificateHostNameOverride: 
  LocalRegionTimeout: 00:00:05
  EnableChannelMultiplexing: False
  MaxConcurrentOpeningConnectionCount: 5
  Use_RecyclableMemoryStream: False
  Use_CustomDnsResolution: False
  IsDistributedTracingEnabled: False

DocDBTrace Information: 0 : TimerPool Created with minSupportedTimerDelayInSeconds = 1
DocDBTrace Information: 0 : MetadataRequestThrottleRetryPolicy: Routing the metadata request to: https://***************************-centralus.documents.azure.com/ for operation type: ReadFeed and resource type: PartitionKeyRange.
DocDBTrace Information: 0 : MetadataRequestThrottleRetryPolicy: Routing the metadata request to: https://***************************-centralus.documents.azure.com/ for operation type: ReadFeed and resource type: PartitionKeyRange.
The program '[15912] testhost.exe' has exited with code 3221225501 (0xc000001d) 'Illegal Instruction'.

**Comment by ealsur** [comment]
@jackbond thanks for the report.

* Can you please share more details? How is the "Illegal Instruction" tied to the SDK and not some other code in the app?
* Can you please share a repro that can be used?
* If it's happening on 1 developer machine, are other developers executing the same app code successfully?

**Comment by jackbond** [comment]
"How is the "Illegal Instruction" tied to the SDK and not some other code in the app?"

Bug only surfaced when upgrading from 3.37.1 to 3.38, and disappears as soon as package is reverted.

The developer reported that the issue disappeared when he switched from VirtualBox to VMWare. Resolves the issue for us, don't know if anyone else will encounter. Feel free to close.

**Comment by Lucasharskamp** [comment]
I am having the same issue. It appears to be invoked when I call methods using a FeedIterator<T> using a QueryDefinition and a PartitionKey.

Example: 

```
using var feed = ContainerName.GetItemQueryIterator<T>(new QueryDefinition("..."),
    new QueryRequestOptions
    {
        MaxItemCount = pageSize,
        PartitionKey = partitionKey
    });
```

Results in:
```
DocDBTrace Information: 0 : MetadataRequestThrottleRetryPolicy: Routing the metadata request to: XXX for operation type: ReadFeed and resource type: PartitionKeyRange.
```

Which is then read as follows, because of another lingering bug:
```
    private static List<T> ReadDataFromFeed<T>(FeedIterator<T> feed, CancellationToken token = default)
    {
        var results = new List<T>();
        while (feed.HasMoreResults)
        {
            // Iterate query results
            // DO NOT just await feed.ReadNextAsync(), because if it doesn't have results this will cause a deadlock!
            // Just handle the task manually. 
            var task = feed.ReadNextAsync(token);
            task.Wait(token);

            if (task.Result == null || task.Result.Count == 0)
                break;

            results.AddRange(task.Result);
        }
        return results;
    }
```

**Comment by ealsur** [comment]
@Lucasharskamp Can you share the Illegal Instruction error details?

The code you are showing shows throttle on Metadata requests and a code snippet that is blocking an async call. awaiting an async operation would not cause a deadlock, but .Wait would. If your issue is not related to Illegal Instruction, please create another Issue.

**Comment by Lucasharskamp** [comment]
> @Lucasharskamp Can you share the Illegal Instruction error details?

Yes, the output says, as put in my previous comment:
```
DocDBTrace Information: 0 : MetadataRequestThrottleRetryPolicy: Routing the metadata request to: XXX for operation type: ReadFeed and resource type: PartitionKeyRange.
```


> The code you are showing shows throttle on Metadata requests and a code snippet that is blocking an async call. awaiting an async operation would not cause a deadlock, but .Wait would. If your issue is not related to Illegal Instruction, please create another Issue.

That bug has already been created multiple times by others and promptly ignored, so this is my workaround.  In this case I was simply showing where it took place, namely when I started reading data from the feed.

**Comment by jackbond** [comment]
@Lucasharskamp Did you actually get a message with 

"code 3221225501 (0xc000001d) 'Illegal Instruction'."

because it's not contained in any of your posts. It's not clear what issue you're reporting. As for your comment

// DO NOT just await feed.ReadNextAsync(), because if it doesn't have results this will cause a deadlock!

I've got code which awaits feed.ReadNextAsync() which has run literally BILLIONS of times (including with no results) with no issue.

**Comment by ealsur** [comment]
@Lucasharskamp

I'm sorry, where is Illegal Instruction in this text?

DocDBTrace Information: 0 : MetadataRequestThrottleRetryPolicy: Routing the metadata request to: XXX for operation type: ReadFeed and resource type: PartitionKeyRange.

This is a trace that just says that your application is performing a PartitionKeyRange operation, which is part of obtaining the Physical Partitions to route requests: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/sdk-connection-modes#routing

> That bug has already been created multiple times by others and promptly ignored, so this is my workaround. In this case I was simply showing where it took place, namely when I started reading data from the feed.

I'm sorry, I feel like this is not a positive and constructive comment and I will ask you that any conversation in this repository is kept with constructiveness in mind. 

Can you please share exactly where you are seeing a `"code 3221225501 (0xc000001d) 'Illegal Instruction'."` error and if not, create a separate Issue for whatever other problem you are encountering?
