### ISSUE TITLE
Add option to ItemRequestOptions that returns the state of the document before update/patch 

### ISSUE THREAD

**Issue by davidxcheng** [Azure/azure-cosmos-dotnet-v3#4441]
## Context

The codebase I'm working on is part of an event-driven, microservices architecture where each domain stores data in Cosmos. The reason for updating Cosmos documents is usually one of the following:

- A POST/PUT request to a service in a domain that owns the entity that is about to be updated
- A ServiceBusTrigger receives a message, via a topic subscription, that contains the new state of some entity that is owned by some other domain

## The feature request

**Is your feature request related to a problem? Please describe.**

I frequently see this pattern in places that involve db updates:

1. A request/event arrives that warrants a db update
2. **Http request** to fetch the item from Cosmos
3. **Http request** to update the item in Cosmos (etag fram step 2 is included)
4. Compare the previous state from step 2 with the new state..
5. ..and if certain properties have changed, emit events

The problem/opportunity is that this pattern involves 2 http requests which could be only 1 request if there was an `ItemRequestOptions` option in step 3 that returned the state of the Cosmos document _before_ it was changed.

**Describe the solution you'd like**

Add an option to `ItemRequestOptions` that returns the state of the updated document _before_ the update/patch. For lack of a better name I'm calling it `EnablePreviousStateInResponse` in this updated description of the case above:

1. A request arrives that warrants a db update
2. **Http request** to update the item in Cosmos (with `ItemRequestOptions.EnablePreviousStateInResponse` set to `true`)
3. Compare the previous state from step 1 with the new state..
4. ..and if certain properties have changed, emit events

The main benefit is that there's only 1 http request being made. And as a bonus this also removes the need to handle PreConditionFailed response due to etag mismatch.

**Describe alternatives you've considered**

Our current pattern with 2 http requests is the alternative.

**Additional context**

I understand that this feature probably requires a change in the Azure Cosmos service so maybe this is the wrong repo for this issue?

**Comment by bartelink** [comment]
https://github.com/jet/equinox has a stored proc that makes a decision on what changes to apply based on inspecting the document
in some cases it can do a reject, yielding the content it just read
Not suggesting a stored proc is the answer of course - it goes in the 'now you have two problems' bucket!
What's unclear to me though is whether your primary interest is to have a copy of the before-state, along with being able to specify a conditional set of updates, or whether a conditonal update is your core goal.
In general though, I'd say the best general solution given the existing facilities is to have a cache holding the etags and state of the docs, and then use that to create a conditonal update request (make it reject if the etag has changed) - if the cache hit rate is high, you get one roundtrip for the cache hits (this is effectively what Equinox does)

**Comment by davidxcheng** [comment]
Conditional updates is not the goal here. We use conditional PATCH in a lot of cases but we also have several cases where we need to check if a specific property changed and in those cases we need to know what the state was before the update.

Example:
- Domain A publishes the event `aaa-updated` and the `Aaa` entity contains several fields, one of them being `Status`
- Domain B receives the event and updates it's local copy of the entity..
- ..and if `Aaa.Status` has changed Domain B wants to take some action

You could argue that Domain A should have a specific event for this scenario (`aaa-status-updated`) but let's assume that there are several consumers of `aaa-updated` that take action on different fields of the `Aaa` entity.

**Comment by bartelink** [comment]
I'm just like you a consumer of the SDK so please don't confuse me with someone that can do something active; what I am trying to do though is to clarify your ask....
At the item request, I don't get what you're going to achieve by getting the before state as a side effect of an upsert or a conditional update

And (again, obviously - not trying to tell you something new, but making sure we're on the same page) ultimately if lots of things need to react in a generalized fashion, then you have 2 choices at a high level:
- have NxCFP consumers that watch for document changes and make sure everythign is up to date (but that can't usefully show the pre-state unless you use the new allchanges mode. The problem is that those are only available for a finite time and you can't replay over that so this is kinda a dead end/
- have explicit events in the documents noting the changes (like equinox does), let each consumer consume the individual events. At any moment in time you can then retraverse all the changes

So my queston in the end is - what significant thing is achievable if the item level ephemeral request shows you the before state - what is the real use case underlying your desire as stated above?

**Comment by ealsur** [comment]
@davidxcheng It seems your feature request is not for the SDK but rather to the service. SDKs cannot add headers and modify behavior on the service if such a behavior does not exist.

@Pilchie which is the best place for users to request features at the service level?

**Comment by bartelink** [comment]
I agree that it's immensely useful to return the conflicting data in the case of an precondition check fail (as it happens I'd be fine with just etag-based predicates for my use case, but a more general facility is obviously a bonus)

If I had that, Equinox could stop requiring a stored procedure as I'd be able to compose a conditional patch request

As it stands, having to do another roundtrip (and paying the same RUs to read the exact same data) would be a major negative in moving away from the stored procedure

----
(A very comparable system recently added the facility to return the data on condition check failure; said system does not implement stored procedures, [but the entire logic of the stored proc](https://github.com/jet/equinox/blob/5ff259ad44578799f1d8c23174667492cf013c7c/src/Equinox.CosmosStore/CosmosStore.fs#L370-L450) can be expressed more simply as conditional request), which is much more maintainable)

**Comment by davidxcheng** [comment]
@ealsur Makes sense, closing this issue
