### ISSUE TITLE
Support for "All versions and delete mode" with Change Feed Processor

### ISSUE THREAD

**Issue by nikhil-pandey** [Azure/azure-cosmos-dotnet-v3#4451]
**Is your feature request related to a problem? Please describe.**
We have a requirement to use the "All versions and delete mode" feature of the change feed. However, this feature is not currently supported in the SDK through Change Feed Processor. The lack of this feature is a significant limitation for us, as we need to track and process every version of a document, including deletions, for synchronization purposes.

**Describe the solution you'd like**
We would like the "All versions and delete mode" to be supported with the Change Feed Processor. This would allow us to fully utilize the change feed capabilities of Cosmos DB and ensure that our application can maintain a comprehensive record of all changes within our Cosmos DB containers.

**Describe alternatives you've considered**
We can't use the Java SDK.  Using the Change feed pull method means reimplementing a lot of features that Change feed processor already has like lease, polling, parallelize across multiple threads and machines.
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/3397134/52f16949-afb6-4059-95e3-3795fdf8aeed)

**Additional context**
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/3397134/ef8ae266-f4fa-4b5a-a144-eb7bd0c05706)

**Comment by philipthomas-MSFT** [comment]
We have included this recently in the preview package.

https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.40.0-preview.0
