### ISSUE TITLE
CosmosException: Object contains header information from request and response

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#4453]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Right now, `CosmosException` is having Request and Response Object, due to which if this object is getting serialized, it would print all the details in the logger, including headers.

**To Reproduce**
Serialize `CosmosException`

**Expected behavior**
It should not have any sensitive information

**Actual behavior**
Current, it prints, all the information, including headers.

**Environment summary**
SDK Version: All
OS Version (e.g. Windows, Linux, MacOSX): Any

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by FabianMeiswinkel** [comment]
The CosmosException is not printing the request and response headers ever - only customers would be if they serialize the exception to json and log it - that is something the application code would do - not the SDK. And CosmosException.toString as all the info needed. So the fix here is simple - do not serialize the exception to json - Exceptions are serializable for the purpose of being able to use the across AppDomains - not to log them. The .Net API contract is that Exception.Message ro Exception.ToString (including callstack) have the relevant info to log. Serializing a CosmosException to json will result in inefficiency and there are no guraantees to avoid any headers.
