### ISSUE TITLE
Updating Cosmo db from 3.29 to 3.31.2+ causes Kestrel issues

### ISSUE THREAD

**Issue by waszakCeneo** [Azure/azure-cosmos-dotnet-v3#4454]
**Describe the bug**
Every time we want to update cosmosdb package from version 3.29 to 3.35+.
For example to 3.39 we experience issues.
The tricky part is that error always goes from methods Using AzureTable.
Cosmos works fine, and the issue is always network related.

**Small % of request fails not all of them, and retry succeeds always**

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/118433754/0d663fbf-e919-4783-82b9-23c35ddaaf5e)

**To Reproduce**
For us to reproduce its just simple as
changing from  on production
` <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.29.0" />`
to
  ` <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.35.2" />` (this we tried in july 2023)
 `<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.36.0" />` (this in december 2023)
 `<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.39.0" />` (this in april 2024)
  `<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.31.2" />` (this in 29-30 april 2024)

This will cause the issue. Whats its important we have heavy workload on our service. (Not to cosmosdb, but to azure table)
On int environement I was never able to reproduce this error.

We even left this package for few days just to see if its not accident but it is always the case.

**Expected behavior**
I expect that updating package won't cause Kestrel issues.

**Actual behavior**
We see spikes in error in microservice. In unrelated methods.
For example we have method that entires from AzureTable (it doesn't use Cosmosdb at all).
And yet everytime we upgrade package it just starts throwing more.

So from my observation**. New Package causes connectivity issues**

**Environment summary**
SDK Version: 3.39
OS Version Linux -AKS

**Additional context**
> 
> BadHttpRequestException occurred in application [Response.HasStarted: False]: Unexpected end of request content. 
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
>    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
>    at System.Text.Json.JsonSerializer.ReadFromStreamAsync(Stream utf8Json, ReadBufferState bufferState, CancellationToken cancellationToken)
>    at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
>    at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

Our code is like this. We store **comosclient as singletion**
.AddSingleton<ICosmosFactory, CosmosFactory>()

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/118433754/0fb6c80e-7071-4d45-ac56-f4c81c90b42e)

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/118433754/8b6f535e-00f3-4a74-9a8d-3388de1cb7ec)

PS. **We have no issues with cosmos db utilization is lowe, just we have issues with conectivity to our microservice after updating package in unrelated methods.**

**Comment by waszakCeneo** [comment]
We experience this issue for over an year and its stopps us from updating the package
Thats why If there where any breaking changes with this package since 3.29 then would be nice to know.

(I tried multiple times updating this package and always ended in the same issues)

**Comment by ealsur** [comment]
Can you provide some repro or some way for us to see the issue? The stack trace of the exception you mention has no relationship with the SDK.

It's happening on `Microsoft.AspNetCore.Mvc.ModelBinding` which is the step where a Controller reads the body of an incoming HTTP message to bind it to some type you are declaring in the controller method. And the error is that the HTTP content being sent to the controller cannot be deserialized into the expected type.

This is happening on the asp.net controller, not th SDK. Can you provide the SDK error if any?

**Comment by waszakCeneo** [comment]
As I said before **it doesn't cause errors in Comosdb SDK.**
But updating just the package causes errors in asp.net controller with some requests failing. I am not sure its possible to reproduce this error **easily outside of production. We tried for past year**. The only certain thing is that is that updating this package causes spikes in errors.


It's happening on Microsoft.AspNetCore.Mvc.ModelBinding which is the step where a Controller reads the body of an incoming HTTP message to bind it to some type you are declaring in the controller method.

Its always 

> BadHttpRequestException occurred in application [Response.HasStarted: False]: Unexpected end of request content.

We get like milios of request to this method. So error is not big but its correlated just to changing cosmosdb 
version.

So like i was never able to reproduce this error. All we know its related to updating the package.
We update the package keeped for week it was erroring request, we downgraded and its stopped.


I was thinking maybe some socket error or something else. Request stops after like 1ms.
Successful request: false, Response time: 951.4 μs,
Retry works. Just the error rate is higher than normal

**Comment by waszakCeneo** [comment]
I have already seen #23949 year ago, this was the issue we started with investigation

Then after testing changes one by one we ended up with cosmosdb package.
And every time, simple PR with one single line changed of cosmosdb started making this errors.

First we gonna try to update from 3.29 to 3.31.2.

Our hypothesis was that it could be due to Azure.Table or some other library.

**Comment by ealsur** [comment]
> And every time, simple PR with one single line changed of cosmosdb started making this errors

Are the errors constant? Or temporary? Based on the other Issue, the problem is the client, either stopping the request or sending a badly formatted payload. Are you changing anything on the client application that calls your ASP.NET Controllers?

**Comment by waszakCeneo** [comment]
There is no change except for package version. We updated only this dependency with Renovate. 
Errors are constant but every retry succceeds. We hit daily cap so we gonna rollback again.
Sadly because I don't have method to reproduce this on smaller case yet. 

Failure rate is 25k/3M requests. (The method as i said before doesn't even query cosmosdb but azure table)

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/118433754/634d1b80-7cc7-47b9-8337-c2e238ff9794)

**Comment by ealsur** [comment]
Could there be another error that is causing the request to fail and it's missing from the logs? Does it fail on a specific Controller Action or in all? Is the Controller Action executing a Cosmos DB operation? Which operation? Is there any try/catch around SDK operations and logging?
