### ISSUE TITLE
Update `Azure.Core` Library to Latest Nuget Release

### ISSUE THREAD

**Issue by kundadebdatta** [Azure/azure-cosmos-dotnet-v3#4479]
- Update `Azure.Core` Library to Latest Nuget Release. The current version of `Azure.Core` library, referred in our v3 .NET SDK is `1.19.0`, which is quite old. This internally uses `System.Text.Json` version `4.6.0`.

- Update SDK to use `Azure.Core` library version [1.39.0](https://www.nuget.org/packages/Azure.Core/1.39.0). Even the latest version [1.39.0]( https://nuget.info/packages/Azure.Core/1.39.0) library uses the STJ version `4.7.2`.
 
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/87335885/334e51d8-046d-4ba5-b7d9-416ce79ef406)

**Comment by Oliver-Piorun** [comment]
Hi! Our pipeline noticed the following related vuln today:
https://github.com/advisories/GHSA-hh2w-p6rv-4g7w

Greetings ~

**Comment by kirankumarkolli** [comment]
#4819
