### ISSUE TITLE
Refactor read/replace offer on database and container

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-cosmos-dotnet-v3#450]
ReadThroughputAsync/ReplaceThroughputAsync using same code on Database and Container, including older V2 pipeline for offer query result.

Option one is to move same code to some common place for re usability.
Second option is to use new V3 pipeline to get the result of offer query and than take care of refactoring.
This item is for tracking purpose that we will revisit read/replace offer code post V3 GA when we get the bandwidth.

**Environment summary**
SDK Version: V3

**Comment by bartelink** [comment]
if its worth making an issue, it's worth summarizing the thoughts in a bit more depth here, no?

**Comment by simplynaveen20** [comment]
> if its worth making an issue, it's worth summarizing the thoughts in a bit more depth here, no?

Thanks for your comment, please find details.

**Comment by bartelink** [comment]
Perfect, thanks (I'm allergic to 'refactor' in issue text as I am to `Manager` in `class` names)!

(Some context: I'll be dogfooding the API in refactoring [this](https://github.com/jet/equinox/blob/86eba23866020ec252c23c877f0f2862c0b6bc1e/src/Equinox.Cosmos/Cosmos.fs#L474) to target V3 at some point))
