### ISSUE TITLE
Keep A ChangeLog

### ISSUE THREAD

**Issue by bartelink** [Azure/azure-cosmos-dotnet-v3#453]
In order to provide a clearer sense of mission and as a by-product, produce a clear changelog with

a) intuitive intrinsic diffing support
b) good summaries for reviewers like me

I'd suggest using the excellent https://keepachangelog.com/en/1.0.0/ format.

I appreciate that this may seem like busywork at what is a busy time for you; I share this out of remembering how happy I personally was when I finally took my head out of the sand and started keeping one! Examples [1](https://github.com/jet/propulsion/blob/master/CHANGELOG.md) [2](https://github.com/jet/equinox/blob/master/CHANGELOG.md)

Please feel free to just close this if it really Aint Gonna Happen ;)

**Comment by j82w** [comment]
We were looking at possibly trying to use a tool to auto generate the change log based off PRs and issues. I  like the format you recommended.

@kirankumarkolli since we don't have a tool yet to auto generate the change log should we start requiring updating the change log for each PR?

**Comment by bartelink** [comment]
The benefit vs a machine generated thing is that it:

- it's dead simple to do manually (it feels cumbersome the for max 15 mins iff you don't have someone to show the ropes) - you get the odd conflict from adjacent appends but nothing else takes long or causes pain
- admits minor reorgs (you can fix a typo in the next PR and/or when merging)
- you can use a text editor to summarise from preview ones when doing an RC etc.
- if you follow the `<a` pattern in the examples, the GitHub releases can be filled in by copy-pasting a fragment-url link to the ChangeLog
- if done with/during the work either a) the issue text should be a useful starter text or b) the changelog text is a good starter text for the PR description

And calling out in case it's missed (saying coz I missed it!), the links are to the github diffs between the cited release and its base which is really useful

And while advertising stuff we've found useful: https://github.com/adamralph/minver is a neat and foolproof way of deterministically generating versions for simple cases, yet has accommodated all more complex needs too
