### ISSUE TITLE
Inquiry on Implementing Custom Retry Logic with CosmosClient

### ISSUE THREAD

**Issue by khsiehms** [Azure/azure-cosmos-dotnet-v3#4545]
Does the CosmosClient support custom retry policies and logic?

We are trying to utilize the CosmosClient like:

CosmosClient cosmosClient = new CosmosClient("account-endpoint-from-portal", "account-key-from-portal", new CosmosClientOptions());

Container container = db.GetContainer("database-id", "container-id");

container.GetItemQueryIterator();

However, based on the documentation ([CosmosClientOptions Class](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fapi%2Fmicrosoft.azure.cosmos.cosmosclientoptions%3Fview%3Dazure-dotnet&data=05%7C02%7Ckhsieh%40microsoft.com%7C7ac197a10ebe4590625108dc8a56218d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638537349751157574%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=dN0kM9kYVvV7hdwohCIRuItTI4fjdR5jijtwfuczG4w%3D&reserved=0)), it appears we can only specify the maximum retry attempts for throttling in CosmosClientOptions.

Is there a way to set up custom retry policies and logic for different errors? 

For example, we might also want to retry on receiving a 503 (Service Unavailable) response or attempt to create the container if a 404 (Not Found) response is received on the first request.

If there is no way to specify the custom retry logic through the options, what would be your suggestion for achieving it?

**Comment by NaluTripician** [comment]
Hi @khsiehms, I believe that you will be able to achieve what you want using [user defined handlers.](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/SdkDesign.md#handler-pipeline). You should be able to define a custom handler that will be able to retry in the circumstances you mentioned above. I have linked the SDK design document above, which describes the handler pipeline structure. I will also link a sample library we have for custom handlers [here ](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/Handlers)so you can get started with some examples. Please feel free to re-open this issue if you have any other questions.
