### ISSUE TITLE
[Client Telemetry] - Trace error not recording exception

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#4592]
The index needs to be 0 instead of 1. This results in the trace messages not logging the exception. 

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f277ce3428798ec5d90e1a6401f605e4e0cdb957/Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryCollector.cs#L66

Example: DocDBTrace Error: 0 : Error while collecting operation telemetry. Exception : 1

**Comment by bartelink** [comment]
That `$` is also looking very guilty ;)
