### ISSUE TITLE
CosmosException Diagnostics shows 404/429 error but StatusCode returns 200

### ISSUE THREAD

**Issue by lauren-nguyen23** [Azure/azure-cosmos-dotnet-v3#4611]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
In our code, we check if an exception is of type CosmosException. If it is, we extract the StatusCode and Diagnostics from the exception and log those details. However, upon checking the traces, I noticed there are some ReadItemAsync operations with status code 200 but the diagnostics and message show an exception of type 404 Not Found. I have also seen the same issue with 429 exceptions, where diagnostics and exception message indicate a 429 but the status code returned is 200.

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

**Expected behavior**
I expected the status code and exception to match. The status code should be 404 if the diagnostics and exception message indicate a 404.

**Actual behavior**
Diagnostics and exception message indicate 404 but status code extracted from the exception is 200.

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.41.0-preview.0
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Discussed in chat.

**Comment by kirankumarkolli** [comment]
@lauren-nguyen23 can you please include the related diagnostic strings?

**Comment by lauren-nguyen23** [comment]
@kirankumarkolli here is 1 diagnostic string for example:

{
    "Summary": {
        "DirectCalls": {
            "(404, 1002)": 1,
            "(404, 0)": 1
        }
    },
    "name": "ReadItemAsync",
    "start datetime": "2024-07-22T17:59:14.698Z",
    "duration in milliseconds": 1.4728,
    "data": { <removed> },
    "children": [
        {
            "name": "Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler",
            "duration in milliseconds": 1.3559,
            "children": [
                {
                    "name": "Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler",
                    "duration in milliseconds": 1.3492,
                    "data": {
                        "System Info": {
                            "systemHistory": [
                                {
                                    "dateUtc": "2024-07-22T17:58:18.0237901Z",
                                    "cpu": 62.422,
                                    "memory": 9539888.000,
                                    "threadInfo": {
                                        "isThreadStarving": "False",
                                        "threadWaitIntervalInMs": 0.0299,
                                        "availableThreads": 32758,
                                        "minThreads": 4400,
                                        "maxThreads": 32767
                                    },
                                    "numberOfOpenTcpConnection": 14974
                                },
                                {
                                    "dateUtc": "2024-07-22T17:58:28.0390027Z",
                                    "cpu": 63.280,
                                    "memory": 9364000.000,
                                    "threadInfo": {
                                        "isThreadStarving": "False",
                                        "threadWaitIntervalInMs": 0.0032,
                                        "availableThreads": 32763,
                                        "minThreads": 4400,
                                        "maxThreads": 32767
                                    },
                                    "numberOfOpenTcpConnection": 14974
                                },
                                {
                                    "dateUtc": "2024-07-22T17:58:38.0553882Z",
                                    "cpu": 62.676,
                                    "memory": 9382672.000,
                                    "threadInfo": {
                                        "isThreadStarving": "False",
                                        "threadWaitIntervalInMs": 0.0221,
                                        "availableThreads": 32761,
                                        "minThreads": 4400,
                                        "maxThreads": 32767
                                    },
                                    "numberOfOpenTcpConnection": 14975
                                },
                                {
                                    "dateUtc": "2024-07-22T17:58:48.0705010Z",
                                    "cpu": 62.559,
                                    "memory": 9597836.000,
                                    "threadInfo": {
                                        "isThreadStarving": "False",
                                        "threadWaitIntervalInMs": 0.0051,
                                        "availableThreads": 32762,
                                        "minThreads": 4400,
                                        "maxThreads": 32767
                                    },
                                    "numberOfOpenTcpConnection": 14975
                                },
                                {
                                    "dateUtc": "2024-07-22T17:58:58.0862389Z",
                                    "cpu": 63.982,
                                    "memory": 9347028.000,
                                    "threadInfo": {
                                        "isThreadStarving": "False",
                                        "threadWaitIntervalInMs": 0.1854,
                                        "availableThreads": 32763,
                                        "minThreads": 4400,
                                        "maxThreads": 32767
                                    },
                                    "numberOfOpenTcpConnection": 14975
                                },
                                {
                                    "dateUtc": "2024-07-22T17:59:08.1019745Z",
                                    "cpu": 65.035,
                                    "memory": 9364960.000,
                                    "threadInfo": {
                                        "isThreadStarving": "False",
                                        "threadWaitIntervalInMs": 0.8325,
                                        "availableThreads": 32760,
                                        "minThreads": 4400,
                                        "maxThreads": 32767
                                    },
                                    "numberOfOpenTcpConnection": 14975
                                }
                            ]
                        }
                    },
                    "children": [
                        {
                            "name": "Microsoft.Azure.Cosmos.Handlers.TelemetryHandler",
                            "duration in milliseconds": 1.3473,
                            "children": [
                                {
                                    "name": "Microsoft.Azure.Cosmos.Handlers.RetryHandler",
                                    "duration in milliseconds": 1.3457,
                                    "children": [
                                        {
                                            "name": "Microsoft.Azure.Cosmos.Handlers.RouterHandler",
                                            "duration in milliseconds": 1.3401,
                                            "children": [
                                                {
                                                    "name": "Microsoft.Azure.Cosmos.Handlers.TransportHandler",
                                                    "duration in milliseconds": 1.3395,
                                                    "children": [
                                                        {
                                                            "name": "Microsoft.Azure.Documents.ServerStoreModel Transport Request",
                                                            "duration in milliseconds": 1.3261,
                                                            "data": {
                                                                "Client Side Request Stats": {
                                                                    "Id": "AggregatedClientSideRequestStatistics",
                                                                    "ContactedReplicas": [
                                                                        {
                                                                            "Count": 1,
                                                                            "Uri": "<removed>"
                                                                        }
                                                                    ],
                                                                    "RegionsContacted": [],
                                                                    "FailedReplicas": [],
                                                                    "AddressResolutionStatistics": [],
                                                                    "StoreResponseStatistics": [
                                                                        {
                                                                            "ResponseTimeUTC": "2024-07-22T17:59:14.6994740Z",
                                                                            "DurationInMs": 0.5788,
                                                                            "ResourceType": "Document",
                                                                            "OperationType": "Read",
                                                                            "RequestSessionToken": "11:4#143572121#7=-1",
                                                                            "LocationEndpoint": "<removed>",
                                                                            "StoreResult": {
                                                                                "ActivityId": "c0cb0a05-3346-405d-8bee-d7f0467b7b47",
                                                                                "StatusCode": "NotFound",
                                                                                "SubStatusCode": "PartitionKeyRangeGone",
                                                                                "LSN": 143572107,
                                                                                "PartitionKeyRangeId": "11",
                                                                                "GlobalCommittedLSN": 143572103,
                                                                                "ItemLSN": -1,
                                                                                "UsingLocalLSN": true,
                                                                                "QuorumAckedLSN": -1,
                                                                                "SessionToken": "4#143572107#7=-1",
                                                                                "CurrentWriteQuorum": -1,
                                                                                "CurrentReplicaSetSize": -1,
                                                                                "NumberOfReadRegions": 1,
                                                                                "IsValid": true,
                                                                                "StorePhysicalAddress": "<removed>",
                                                                                "RequestCharge": 0,
                                                                                "RetryAfterInMs": null,
                                                                                "BELatencyInMs": "0.118",
                                                                                "ReplicaHealthStatuses": [
                                                                                    "(port: 14031 | status: Unknown | lkt: 7/19/2024 10:57:06 PM)",
                                                                                    "(port: 14055 | status: Unknown | lkt: 7/19/2024 10:57:06 PM)",
                                                                                    "(port: 14082 | status: Unknown | lkt: 7/19/2024 10:57:06 PM)",
                                                                                    "(port: 14380 | status: Unknown | lkt: 7/19/2024 10:57:06 PM)"
                                                                                ],
                                                                                "transportRequestTimeline": {
                                                                                    "requestTimeline": [
                                                                                        {
                                                                                            "event": "Created",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6988556Z",
                                                                                            "durationInMs": 0.0013
                                                                                        },
                                                                                        {
                                                                                            "event": "ChannelAcquisitionStarted",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6988569Z",
                                                                                            "durationInMs": 0.0011
                                                                                        },
                                                                                        {
                                                                                            "event": "Pipelined",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6988580Z",
                                                                                            "durationInMs": 0.0351
                                                                                        },
                                                                                        {
                                                                                            "event": "Transit Time",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6988931Z",
                                                                                            "durationInMs": 0.3982
                                                                                        },
                                                                                        {
                                                                                            "event": "Received",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6992913Z",
                                                                                            "durationInMs": 0.0228
                                                                                        },
                                                                                        {
                                                                                            "event": "Completed",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6993141Z",
                                                                                            "durationInMs": 0
                                                                                        }
                                                                                    ],
                                                                                    "serviceEndpointStats": {
                                                                                        "inflightRequests": 1,
                                                                                        "openConnections": 1
                                                                                    },
                                                                                    "connectionStats": {
                                                                                        "waitforConnectionInit": "False",
                                                                                        "callsPendingReceive": 0,
                                                                                        "lastSendAttempt": "2024-07-22T17:59:14.6965802Z",
                                                                                        "lastSend": "2024-07-22T17:59:14.6966149Z",
                                                                                        "lastReceive": "2024-07-22T17:59:14.6982910Z"
                                                                                    },
                                                                                    "requestSizeInBytes": 602,
                                                                                    "responseMetadataSizeInBytes": 167,
                                                                                    "responseBodySizeInBytes": 56
                                                                                },
                                                                                "TransportException": null
                                                                            }
                                                                        },
                                                                        {
                                                                            "ResponseTimeUTC": "2024-07-22T17:59:14.7000936Z",
                                                                            "DurationInMs": 0.5361,
                                                                            "ResourceType": "Document",
                                                                            "OperationType": "Read",
                                                                            "RequestSessionToken": "11:4#143572121#7=-1",
                                                                            "LocationEndpoint": "<removed>",
                                                                            "StoreResult": {
                                                                                "ActivityId": "c0cb0a05-3346-405d-8bee-d7f0467b7b47",
                                                                                "StatusCode": "NotFound",
                                                                                "SubStatusCode": "Unknown",
                                                                                "LSN": 143572121,
                                                                                "PartitionKeyRangeId": "11",
                                                                                "GlobalCommittedLSN": 143572103,
                                                                                "ItemLSN": -1,
                                                                                "UsingLocalLSN": true,
                                                                                "QuorumAckedLSN": -1,
                                                                                "SessionToken": "4#143572121#7=-1",
                                                                                "CurrentWriteQuorum": -1,
                                                                                "CurrentReplicaSetSize": -1,
                                                                                "NumberOfReadRegions": 1,
                                                                                "IsValid": true,
                                                                                "StorePhysicalAddress": "<removed>",
                                                                                "RequestCharge": 1,
                                                                                "RetryAfterInMs": null,
                                                                                "BELatencyInMs": "0.193",
                                                                                "ReplicaHealthStatuses": [
                                                                                    "(port: 14031 | status: Unknown | lkt: 7/19/2024 10:57:06 PM)",
                                                                                    "(port: 14055 | status: Unknown | lkt: 7/19/2024 10:57:06 PM)",
                                                                                    "(port: 14082 | status: Unknown | lkt: 7/19/2024 10:57:06 PM)",
                                                                                    "(port: 14380 | status: Unknown | lkt: 7/19/2024 10:57:06 PM)"
                                                                                ],
                                                                                "transportRequestTimeline": {
                                                                                    "requestTimeline": [
                                                                                        {
                                                                                            "event": "Created",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6994854Z",
                                                                                            "durationInMs": 0.0027
                                                                                        },
                                                                                        {
                                                                                            "event": "ChannelAcquisitionStarted",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6994881Z",
                                                                                            "durationInMs": 0.0032
                                                                                        },
                                                                                        {
                                                                                            "event": "Pipelined",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6994913Z",
                                                                                            "durationInMs": 0.0625
                                                                                        },
                                                                                        {
                                                                                            "event": "Transit Time",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.6995538Z",
                                                                                            "durationInMs": 0.516
                                                                                        },
                                                                                        {
                                                                                            "event": "Received",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.7000698Z",
                                                                                            "durationInMs": 0.0209
                                                                                        },
                                                                                        {
                                                                                            "event": "Completed",
                                                                                            "startTimeUtc": "2024-07-22T17:59:14.7000907Z",
                                                                                            "durationInMs": 0
                                                                                        }
                                                                                    ],
                                                                                    "serviceEndpointStats": {
                                                                                        "inflightRequests": 1,
                                                                                        "openConnections": 1
                                                                                    },
                                                                                    "connectionStats": {
                                                                                        "waitforConnectionInit": "False",
                                                                                        "callsPendingReceive": 0,
                                                                                        "lastSendAttempt": "2024-07-22T17:59:14.6868346Z",
                                                                                        "lastSend": "2024-07-22T17:59:14.6868731Z",
                                                                                        "lastReceive": "2024-07-22T17:59:14.6873973Z"
                                                                                    },
                                                                                    "requestSizeInBytes": 602,
                                                                                    "responseMetadataSizeInBytes": 160,
                                                                                    "responseBodySizeInBytes": 87
                                                                                },
                                                                                "TransportException": null
                                                                            }
                                                                        }
                                                                    ]
                                                                }
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by NaluTripician** [comment]
Hi @lauren-nguyen23, could you also please provide the CosmosException and message that has the 200 status code? Thank you.

**Comment by lauren-nguyen23** [comment]
hi @NaluTripician I don't see any 200s, which is why I'm confused. This is the exception message from the CosmosException: "Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: c0cb0a05-3346-405d-8bee-d7f0467b7b47; Reason: (\r\nErrors : [\r\n  \"Resource Not Found. Learn more: https:\/\/aka.ms\/cosmosdb-tsg-not-found\"\r\n]\r\n);"

**Comment by lauren-nguyen23** [comment]
hi @NaluTripician just checking in, do you have any updates yet? is there additional information I could provide that could be helpful?

**Comment by kirankumarkolli** [comment]
NotFound 404 is an exception if used with Typed API.
@lauren-nguyen23 can you please expand on where is 200 expected?

**Comment by lauren-nguyen23** [comment]
@kirankumarkolli so the issue is in our code we have a CosmosException object, and we extract the status code and message and diagnostics from this object. While the message and diagnostics indicate a 404 Not Found exception, the status code we got from the same CosmosException object is 200, which is not what we'd expect (we expect the status code to be 404). 

So to answer your question, I don't expect the 200, but I expect the 404 as the status code of the Cosmos exception.

**Comment by ealsur** [comment]
@lauren-nguyen23 The StatusCode property of the CosmosException is used to materialize the Message string:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/9deb6e55107bf0d93f7f1a6e4f85ba053571bb55/Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs#L42-L46

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/9deb6e55107bf0d93f7f1a6e4f85ba053571bb55/Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs#L234-L236

So if the Message was `Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: c0cb0a05-3346-405d-8bee-d7f0467b7b47;....`

That means that the StatusCode was 404 on the CosmosException.StatusCode property.

Do you have any exception instance serialization or other kind of evidence that shows that the StatusCode property was 200?

**Comment by kirankumarkolli** [comment]
CosmosException message contain the statusCode (from above message its 404 not 200)

Code ref: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/db65728c41c03a942a84a0402e294e3d2be0c7b9/Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs#L42

**Comment by kirankumarkolli** [comment]
> CosmosException message contain the statusCode (from above message its 404 not 200)
> 
> Code ref:
> 
> https://github.com/Azure/azure-cosmos-dotnet-v3/blob/db65728c41c03a942a84a0402e294e3d2be0c7b9/Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs#L42

Oops sorry ignore this

**Comment by kirankumarkolli** [comment]
Please re-open with repro context.
