### ISSUE TITLE
PartitionKey.None.GetHashCode() throws an ArgumentNullException

### ISSUE THREAD

**Issue by csdahlberg** [Azure/azure-cosmos-dotnet-v3#4626]
**Describe the bug**

With the latest Microsoft.Azure.Cosmos (v3.42.0), calling `Microsoft.Azure.Cosmos.PartitionKey.None.GetHashCode()` throws a `NullReferenceException`.

**To Reproduce**

Call `Microsoft.Azure.Cosmos.PartitionKey.None.GetHashCode()`:

```
using Microsoft.Azure.Cosmos;

namespace PartitionKeyNullRef;

internal class Program
{
    static void Main(string[] args)
    {
        PartitionKey.None.GetHashCode();
    }
}
```

**Expected behavior**
I do not expect an exception to be thrown.

**Actual behavior**
A `NullReferenceException` is thrown:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Microsoft.Azure.Documents.Routing.PartitionKeyInternal.GetHashCode()
   at Microsoft.Azure.Cosmos.PartitionKey.GetHashCode()
   at PartitionKeyNullRef.Program.Main(String[] args) in C:\Users\Chris\source\repos\PartitionKeyNullRef\PartitionKeyNullRef\Program.cs:line 9
   ```

**Comment by kirankumarkolli** [comment]
@csdahlberg is this a regression observed with latest package version? 

Also can you please share some context on the usecase and impact of this issue.

**Comment by csdahlberg** [comment]
This does not appear to be a regression -- I see the same behavior with v3.0.0 (the oldest version of this library on NuGet).

I was using `PartitionKey.None` in some unit tests, and it ended up being used as a key in a dictionary, at which point the exception was thrown. It was not a big problem for me in this case (`PartitionKey.Null` works fine for my current needs), but since `GetHashCode` should not throw exceptions, it was still unexpected.

**Comment by kirankumarkolli** [comment]
`PartitionKey.None` supposed to be a virtual representation and it will manifest based on ContainerProperties (Parittioned/non-partitioned) into `PartitionKey.Empty` or `PartitionKey.Undefined`

```c#
        internal PartitionKeyInternal NonePartitionKeyValue
        {
            get
            {
                if (this.PartitionKey.Paths.Count == 0 || this.PartitionKey.IsSystemKey.GetValueOrDefault(false))
                {
                    return PartitionKeyInternal.Empty;
                }
                else
                {
                    return PartitionKeyInternal.Undefined;
                }
            }
        }
```

`GetHashCode` is not used explicitly used in the implementation and can be delegated to the base type.

@ramarag thoughts?

**Comment by kirankumarkolli** [comment]
Next direct package refresh will have the fix.

**Comment by sourabh1007** [comment]
It is fixed and released
