### ISSUE TITLE
Cannot disable Analytical store in container (setting AnalyticalStoreTimeToLiveInSeconds to null has not effect)

### ISSUE THREAD

**Issue by hesperanca** [Azure/azure-cosmos-dotnet-v3#4634]
According to the [documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.containerproperties.analyticalstoretimetoliveinseconds?view=azure-dotnet), to disable the analytical store in a container we simply need to set the containerProperties.AnalyticalStoreTimeToLiveInSeconds to null. 

According to our tests, setting the AnalyticalStoreTimeToLiveInSeconds to null in an existing container has not effect (the value doesn't get changed at all).

The code we are using to update the analytical store ttl value is:

```
 var dbContainer = _cosmosClient.GetContainer(<DatabaseName>, <ContainerName>);

 var containerResponse = await dbContainer.ReadContainerAsync();
 var containerProperties = containerResponse.Resource;

 // Only disable the analytical store if it's not already disabled
 if (containerProperties.AnalyticalStoreTimeToLiveInSeconds != null)
 {
     containerProperties.AnalyticalStoreTimeToLiveInSeconds = null;
     await dbContainer.ReplaceContainerAsync(containerProperties);
 }
```

Expected result:
The container property AnalyticalStoreTimeToLiveInSeconds should be set to null and the analytical store disabled in the container.

Actual result:
The value of AnalyticalStoreTimeToLiveInSeconds property remains the same and the analytical store remains enabled in the container.

**Comment by ealsur** [comment]
Verified the SDK client behavior. When `null` is used, then the client correctly does not send the `analyticalStorageTtl` on the REST request. This behavior is the same as the DefaultTimeToLive (`defaultTtl`) which does work as expected.

Managed to repro the behavior on my side too. Will report back if I get more information.

**Comment by hesperanca** [comment]
@ealsur. Thanks for confirming this. Can you think of a workaround in the meantime? We were about to release a new enhancement to our SAAS APP that relied on this (we are an MS ISV)?

Mant thanks.

**Comment by ealsur** [comment]
The feature it seems cannot be disabled even from the Azure Portal, which leads me to believe this is related to system behavior (nothing seems wrong on the client SDK)

![image](https://github.com/user-attachments/assets/d5df6805-6528-4c20-b525-9e3cc2daa5cd)

**Comment by hesperanca** [comment]
I'm just trying to diable it on a specific Container. Not on all of them.

**Comment by ealsur** [comment]
Correct, the above screenshot is the Portal UX for a specific container. The Analytical Storage Time to Live cannot be turned Off. Which maps what is happening on the client SDK (the SDK is sending the REST API payload without the configuration to disable it and the response comes back without disabling the TTL)

**Comment by hesperanca** [comment]
Interestingly, in the portal, you cannot disable it on the Synapse Link section:

![image](https://github.com/user-attachments/assets/b442c7f1-2065-460a-b93f-8b79c7295904)

but you seem to be able to disable it on the Power BI section:

![image](https://github.com/user-attachments/assets/b3fbb78e-cbfe-4abd-a815-d27a643ae991)


Confusing!!

**Comment by ealsur** [comment]
https://learn.microsoft.com/en-us/azure/cosmos-db/analytical-store-introduction#analytical-ttl

It seems according to the documentation 0 or null should disabled it, but on my test, only 0 did. This would be a gap/misleading on the docs.
