### ISSUE TITLE
Issue in GlobalEndpointManager: StartLocationBackgroundRefreshWithTimer() refreshing locations

### ISSUE THREAD

**Issue by VigneashSelvaraj** [Azure/azure-cosmos-dotnet-v3#4659]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
In my ASP MVC app, I have read logics of my cosmos DB in startup.cs file. I don't see any issue in reading documents from cosmos DB, however it doesn't progress to main controller's action method and spins infinitely 

**To Reproduce**
Below is the initialization and document reading operation snippet.

static CosmosClient client;
string tokenEnv = WebConfigurationManager.AppSettings["tokenEnv"];

public void Initialize()
{
    if (client == null)
    {
        DefaultAzureCredential credential;
        if (tokenEnv == "Local")
        {
            credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions
            {
                ExcludeInteractiveBrowserCredential = true,
                ExcludeVisualStudioCredential = false,
                ExcludeVisualStudioCodeCredential = true,
                ExcludeAzurePowerShellCredential = true,
                ExcludeAzureCliCredential = true,
                ExcludeAzureDeveloperCliCredential = true,
                ExcludeWorkloadIdentityCredential = true,
                ExcludeEnvironmentCredential = true,
                ExcludeManagedIdentityCredential = true,
                ExcludeSharedTokenCacheCredential = true
            });
        }
        else
        {
            
            credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { ManagedIdentityClientId = WebConfigurationManager.AppSettings["kvMsiClientId"], TenantId = WebConfigurationManager.AppSettings["tenantID"] });
        }

        try
        {       

            client = new CosmosClient(endPointURL, credential);
        }
        catch (CosmosException)
        {
            throw;
        }
        catch (Exception)
        {
            throw;
        }
    }
}

 public async Task<dynamic> GetDocumentJsonString(string id, string collection)
 {
     try
     {

         var container = client.GetContainer(DatabaseId, collection);
         var query = container.GetItemLinqQueryable<Document>().Where(d => d.Id == id.ToString()).ToFeedIterator();
         var results = await query.ReadNextAsync();
         Document retVal = results.FirstOrDefault();
         return retVal.ToString();

     }
     catch (Exception ex)
     {
         throw ex;
     }
 }

**Expected behavior**
MVC should progress to controller level operation rather than spinning endlessly 

**Actual behavior**
OUTPUT FROM VISUAL STUDIO
14:24:22:670	The thread 32004 has exited with code 0 (0x0).
14:24:22:670	The thread 33336 has exited with code 0 (0x0).
14:25:33:508	DocDBTrace Information: 0 : GlobalEndpointManager: StartLocationBackgroundRefreshWithTimer() - Invoking refresh
14:25:34:747	Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.instrumentationkey.RemoteDependency","time":"2024-09-03T08:55:33.4560245Z","iKey":"InstrumentationKey","tags":{"ai.internal.sdkVersion":"rddf: 2.1.0.363","ai.device.roleInstance":"DESKTOP-J6OVQK0"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"https://QaApp.documents.azure.com:443/","id":"7AkHhY5LWQ0=","value":1055.9529,"resultCode":"200","dependencyKind":1,"success":true,"properties":{"DeveloperMode":"true"}}}}
14:25:34:747	DocDBTrace Information: 0 : Current WriteEndpoints = (https://QaApp-southcentralus.documents.azure.com/) ReadEndpoints = (https://QaApp-southcentralus.documents.azure.com/)
14:25:34:747	DocDBTrace Information: 0 : GlobalEndpointManager: StartLocationBackgroundRefreshWithTimer() refreshing locations
14:25:42:745	The thread 820 has exited with code 0 (0x0).
14:25:42:745	The thread 24820 has exited with code 0 (0x0).
14:25:42:745	The thread 33612 has exited with code 0 (0x0).
14:25:42:745	The thread 10944 has exited with code 0 (0x0).

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos.3.42.0
OS Version: Windows 10

**Additional context**
NA

**Comment by kirankumarkolli** [comment]
@VigneashSelvaraj Did cosmosDB reading document finished successfully with no errors or issues? 

You can trace the exception in Startup.cs to see if there are failures/exceptions.

**Comment by VigneashSelvaraj** [comment]
@kirankumarkolli  - this was due to improper async/await usage. after making my flow in sync mode issue resolved
