### ISSUE TITLE
How to unit test code that uses IsDefined() when the local instance throws Exception?

### ISSUE THREAD

**Issue by d1820** [Azure/azure-cosmos-dotnet-v3#466]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**

**To Reproduce**
Try to use IsDefined() in a unit test.

**Expected behavior**

IsDefined() to not be internal or default to return true when on the client

**Actual behavior**
IsDefined throws " throw new NotImplementedException();"

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Once again the lack of exposing classes and stuff to be testable.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/7c6a2c0829de17dbf8102050d8dc6b36cfbe8f2e/Microsoft.Azure.Cosmos/src/TypeCheckFunctionsExtensions.cs

**Comment by j82w** [comment]
@d1820 can you provide an example scenario you are trying to test so we can better understand the scenario? We've done a lot to make the v3 unit testable.

**Comment by d1820** [comment]
ill try and get some time tonight to send over a test.. thanks

**Comment by j82w** [comment]
@d1820 any chance this is in the v2 SDK? I just noticed that this is internal for v3.

**Comment by d1820** [comment]
Ugh, correct it was v2 sorry i thought we had completed our upgrade.

**Comment by RoelRoel** [comment]
How to overwrite the TypeCheckFunctionsExtensions so they can be used in Unit Tests (with in memory "storage")?
