### ISSUE TITLE
How to determine the write is tentative(uncommitted) or committed write in multi-region write

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-cosmos-dotnet-v3#4663]
When the database is configured with multi-region write:
1. How to determine the write is tentative(uncommitted) or committed write?
2. Is it doable to make the request to be committed write only and tentative write only? I see this doc mentions header, but it don't find the place to configure it: https://learn.microsoft.com/en-us/azure/cosmos-db/global-dist-under-the-hood#:~:text=Clients%20can%20request%20either%20tentative%20or%20committed%20writes%20by%20passing%20a%20request%20header.
3. I see the conflict resolution policy can only be configure at the container creation time, but the database account can change to multi-region write, then what is the conflict resolution policy here? Is it by default one that using "_ts"?

Looking forward to hearing from you. Thanks!

**Comment by kirankumarkolli** [comment]
ComsosDB SDK returns only after the writes are committed. 

Documentation needs refresh/update removing tentative writes
