### ISSUE TITLE
[SDK Cold Start] - Retry Metadata Requests in Other Regions When Preferred Regions is Empty and Hub Region is Offlined

### ISSUE THREAD

**Issue by kundadebdatta** [Azure/azure-cosmos-dotnet-v3#4665]
**Acceptance Criteria:**

- Today, when the .NET sdk is in clod start mode and the primary hub region is experiencing an outage, given that the user didn't specify the preferred regions list, the SDK won't do a cross regional retry to get the metadata information.

- This behavior causes the SDK to act as a single point of failure in the above situation, and the goal of this task is to fix this behavior and do cross regional retry attempts, even when the user didn't specify the preferred regions list. That ideally means to populate the preferred regions internally, when the list is provided empty.

**Comment by kirankumarkolli** [comment]
@kundadebdatta This is not just limited to cold start only right? 
In general to have HA with GlobalEndpoint when the PrefrredRegions are not set.

**Comment by jeet1995** [comment]
> @kundadebdatta This is not just limited to cold start only right? In general to have HA with GlobalEndpoint when the PrefrredRegions are not set.

Correct - I'd say the pending fix won't help with cold start at all as it isn't possible to construct region suffixed endpoints for the SDK to reach out for database account resolution without preferred regions. The fix will help to not have availability be restricted to just hub / primary in case of an outage to hub / primary once the client has been warmed / has cached account metadata even with preferred regions not set.

**Comment by kundadebdatta** [comment]
> @kundadebdatta This is not just limited to cold start only right? In general to have HA with GlobalEndpoint when the PrefrredRegions are not set.

Yes correct - this is not just bounded to cold start scenarios.
