### ISSUE TITLE
Typo in the new hedging API - WithAvailibilityStrategy

### ISSUE THREAD

**Issue by adamnova** [Azure/azure-cosmos-dotnet-v3#4668]
**Describe the bug**
`CosmosClientBuilder.WithAvailibilityStrategy` contains a typo in the word availability and it is inconsistent with `AvailabilityStrategy`.

**Expected behavior**
`CosmosClientBuilder.WithAvailabilityStrategy`

**Comment by kirankumarkolli** [comment]
Thank you @adamnova 
Its a real bad mis from our side, thank you for reporting it. 

@NaluTripician lets please address it ASAP.
