### ISSUE TITLE
Deserializer appends default List value with what's available in database.

### ISSUE THREAD

**Issue by dominikprzywara** [Azure/azure-cosmos-dotnet-v3#4686]
**Describe the bug**
Deserializer appends default List value with what's available in database.

**To Reproduce**
NUnit required:

```cs
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Cosmos.Linq;

namespace CosmosReproArraysBug;

public class Tests
{
    private static readonly CosmosClientOptions s_defaultOptions =
        new()
        {
            SerializerOptions = new CosmosSerializationOptions
                { PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase }
        };

    [Test]
    public async Task BugRepro()
    {
        var connstr = "CHANGE_ME";
        var client = new CosmosClient(connstr, s_defaultOptions);
        var dbName = "tstDb";
        var colName = "listBug";
        await client.CreateDatabaseIfNotExistsAsync(dbName);
        var db = client.GetDatabase(dbName);
        var container = db.GetContainer(colName);
        await container.DeleteContainerAsync();
        await db.CreateContainerIfNotExistsAsync(colName, "/id");

        var insertObj = new Test { ListValues = [1, 1] };
        await container.UpsertItemAsync(insertObj);

        var query = container.GetItemLinqQueryable<Test>();
        using var filteredFeed = query.ToFeedIterator();
        var response = await filteredFeed.ReadNextAsync();
        var result = response.Resource.First();

        Assert.AreEqual(result.ListValues.Count, insertObj.ListValues.Count);
    }
}

public class Test
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public List<int> ListValues { get; set; } = [0, 0];
}

```

**Expected behavior**
Property is replaced with what's in databasee

**Actual behavior**
Lists are merged together

**Environment summary**
SDK Version: 8.0.302
OS Version (e.g. Windows, Linux, MacOSX)
Windows 23H2

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

Object in database

```json
{
    "id": "06e006e7-a927-40de-a1c7-bf0423ce97c7",
    "listValues": [
        1,
        1
    ],
    "_ts": 1726222849
}
```

Object returned by deserializer:

```json
{
    "id": "06e006e7-a927-40de-a1c7-bf0423ce97c7",
    "listValues": [
        0,
        0,
        1,
        1
    ]
}
```

**Comment by kirankumarkolli** [comment]
Cosmos SDK underneath uses Newtonsoft. 
Newtonsoft behavior for Lists deserialization is to append not replace. 
ref: https://github.com/JamesNK/Newtonsoft.Json/issues/2788

@dominikprzywara few possible options
- Avoid the default initialization. 
- Use System.Text.Json (default behavior is Replace) ref: [UseSystemTextJsonSerializerWithOptions](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d4c9438178e16374db26d1dc084ce51136978e47/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L397)
- Write a custom serializer implementation with required Newstonsof customizations.
