### ISSUE TITLE
Script logs lose information (casing and new lines)

### ISSUE THREAD

**Issue by kentcb** [Azure/azure-cosmos-dotnet-v3#47]
**Is your feature request related to a problem? Please describe.**
Trying to debug a sproc. I've set `EnableScriptLogging` in the options, but can't find a way to pull the console output out using the Microsoft.Azure.Cosmos API.

**Describe the solution you'd like**
A way to get the console output.

**Describe alternatives you've considered**
The old way doesn't appear to work any more.

**Comment by kirankumarkolli** [comment]
EnableScriptLogging gets logs in a header named 'x-ms-documentdb-script-log-results', which can be access through CosmosItemResponse.Headers. 

@kentcb are you not seeing 'x-ms-documentdb-script-log-results' header in the response?

**Comment by kentcb** [comment]
Ah, yes I do. Sorry, I missed that somehow. That said, it comes through as encoded (e.g. a space comes through as `%20`) which is probably fine and expected given that it's a header. However, being in a header also means that it comes through as lower case, which means that important information may be lost (e.g. generated IDs will lose casing).

**Comment by kentcb** [comment]
It also loses line breaks between distinct `console.log` calls, which is a bit annoying.

**Comment by kirankumarkolli** [comment]
@kentcb thanks for the feedback. 

Some parts of the feedback (encoding etc..) can be handled by client abstraction but it doesn't cover the lower-casing part, this needs to be addressed by service. 

@kentcb  can you please share this feedback over askcosmosdb[AtT]microsoft.com?

**Comment by kirankumarkolli** [comment]
@mkolt thoughts on lower case issues in script logs?

**Comment by mkolt** [comment]
+@balaperu

**Comment by christopheranderson** [comment]
@mkolt - we need to triage this still. Since this is a backend limitation, my thought is that we should move this off the SDK repo. Did you make any progress on this?

**Comment by mkolt** [comment]
The line breaks etc should be fixed a while ago. We URL-encode the value.
