### ISSUE TITLE
Item with null partition key throwing error on create

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-cosmos-dotnet-v3#471]
**Expected behavior**
Should able to create and read with null partition key

**Actual behavior**
Item with null partition key throwing error on create

**Environment summary**
SDK Version: V3

**Comment by j82w** [comment]
The SDK was treating null as the same as undefined. This is not a true statement. They are both supported and are different values. 

1. Exposed a PartitionKey.Null value to all users to set null in the request options
2. Fixed the partition key extraction to treat undefined and null correctly
