### ISSUE TITLE
[ClientTelemetry] Client telemetry tests are flaky

### ISSUE THREAD

**Issue by neildsh** [Azure/azure-cosmos-dotnet-v3#4731]
`ClientTelemetryTestsBase` has logic that is timing dependent. This causes the tests to be flaky.
The test also appears to be making real network requests, presumably to a server outside the node that tests run on.
Ideally, the `WaitAndAssert` method should be rewritten to correct these deficiencies. 

**To Reproduce**
This reproduces in the PR builds.

**Expected behavior**
Tests should not use calls to `Task.Delay` or make network requests outside the node that they run on. The outcome of a test should be deterministic.

**Comment by kirankumarkolli** [comment]
@sourabh1007 can you please take a look?

**Comment by Pilchie** [comment]
:eyes:

**Comment by Pilchie** [comment]
If we can't prioritize this and identify a fix within this week, we should disable these tests until we can. It unduly impacts the productivity of the entire team.
