### ISSUE TITLE
PartitionKeyRangeCacheTests are flaky

### ISSUE THREAD

**Issue by neildsh** [Azure/azure-cosmos-dotnet-v3#4732]
ClientTelemetryTestsBase has logic that is timing dependent. This causes the tests to be flaky.
Ideally, the `VerifyPkRangeCacheRefreshOnSplitWithErrorsAsync` method should be rewritten to correct these deficiencies.

**To Reproduce**
This reproduces in the PR builds.

**Expected behavior**
Tests should not use calls to `Task.Delay`. The outcome of a test should be deterministic.

**Comment by kirankumarkolli** [comment]
@sourabh1007 can you please look into it?

**Comment by Pilchie** [comment]
:eyes:

**Comment by Pilchie** [comment]
If we can't prioritize this and identify a fix within this week, we should disable these tests until we can. It unduly impacts the productivity of the entire team.

**Comment by kirankumarkolli** [comment]
This is on a critical path of caches, lets look into it. 
Would be a good learning exercises for he new hires forward.

**Comment by sourabh1007** [comment]
If I am not wrong, it has nothing to do with client telemetry. It is just another test depending on `Task.Delay` which is flaky. Or I am missing something here.
