### ISSUE TITLE
`MongoWaitQueueFullException` When Scaling Azure Container Apps with .NET 8.0 API Using Azure Cosmos DB for MongoDB API

### ISSUE THREAD

**Issue by yhsparrow** [Azure/azure-cosmos-dotnet-v3#4734]
**Summary:**

I'm facing a critical issue where my .NET 8.0 API can handle up to **1,000 RPS on a single container instance** without any problems. However, when I enable scaling in Azure Container Apps to handle increased load, I start receiving `MongoWaitQueueFullException` errors from Azure Cosmos DB for MongoDB API. This occurs even though the per-instance load is significantly less than 1,000 RPS. Reducing the per-instance `MaxConnectionPoolSize` to manage total connections sometimes resolves the issue but can also lead to these exceptions occurring unpredictably.

**Environment:**

- **Azure Services:**
  - Azure Container Apps
  - Azure Cosmos DB for MongoDB API
- **Application:**
  - .NET 8.0 API
  - MongoDB .NET Driver
- **Configuration:**
  - **Single Instance:**
    - CPU: 0.5 cores
    - Memory: 1 GB RAM
    - `MaxConnectionPoolSize`: 112
    - Throughput: Handles up to **1,000 RPS without issues**
  - **Scaled Instances:**
    - Auto-scale based on RPS (e.g., scales when RPS > 500)
    - **Encountering exceptions at loads well below 1,000 RPS per instance**

**Problem Details:**

- **Dilemma:**
  - **Single Container Performance:** The application can handle **1,000 RPS on a single container** with `MaxConnectionPoolSize` set to 112.
  - **Scaling Issue:** When scaling out to multiple containers, MongoDB reports connection limits and throws `MongoWaitQueueFullException` errors, even though the per-instance load is lower.
  - **Adjusting `MaxConnectionPoolSize`:** Reducing `MaxConnectionPoolSize` to 20 or 50 per instance sometimes resolves the issue, but the exceptions still occur unpredictably, and per-instance throughput decreases.

- **Exception Received:**

  ```
  MongoDB.Driver.MongoWaitQueueFullException: The wait queue for acquiring a connection to server <cosmosdb-endpoint>:10255 is full.
  ```

- **Impact:**
  - The application cannot maintain the same per-instance throughput when scaling out.
  - Scaling out leads to decreased performance and stability due to connection limitations.
  - The issue occurs even when per-instance loads are well within the capacity handled by a single instance.

**Error Stack Trace:**

```
MongoDB.Driver.MongoWaitQueueFullException: The wait queue for acquiring a connection to server <cosmosdb-endpoint>:10255 is full.
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionHelper.AcquireWaitQueueSlot()
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionHelper.StartCheckingOut()
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionHelper.AcquireConnectionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.GetChannelAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.InitializeAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.CreateAsync(IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.ExecuteAsync[TResult](IRetryableWriteOperation`1 operation, IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperationAsync[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperationAsync[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MyApp.Services.WaitlistService.CreateOrUpdateEntryAsync(WaitlistEntry entry) in /src/Services/WaitlistService.cs:line 41
```

**Steps to Reproduce:**

1. **Set Up Environment:**
   - Deploy a .NET 8.0 API to Azure Container Apps.
   - Configure the API to use Azure Cosmos DB for MongoDB API.
   - Use the MongoDB .NET Driver with `MaxConnectionPoolSize` set to 112.

2. **Load Testing with Single Instance:**
   - Run a load test with up to **1,000 RPS**.
   - Observe that the application handles the load **without exceptions**.

3. **Enable Scaling in Azure Container Apps:**
   - Configure the application to scale out when RPS exceeds a threshold (e.g., 500 RPS).
   - Deploy the updated configuration.

4. **Load Testing with Scaling Enabled:**
   - Run the same load test.
   - Observe that `MongoWaitQueueFullException` errors occur **even at per-instance loads well below 1,000 RPS**.

5. **Adjust `MaxConnectionPoolSize`:**
   - Reduce `MaxConnectionPoolSize` to 20 or 50 per instance to limit total connections when scaling.
   - Run the load test on a single instance and with scaling enabled.
   - **Sometimes the application works without issue; other times, it throws `MongoWaitQueueFullException` errors**, even at lower RPS.

**Expected Behavior:**

- The application should scale out across multiple instances **without encountering `MongoWaitQueueFullException` errors**.
- **Per-instance throughput should remain consistent** when scaling out.
- Adjusting `MaxConnectionPoolSize` should not cause exceptions at lower loads on a single instance or lead to unpredictable behavior.

**Actual Behavior:**

- **Scaling out results in `MongoWaitQueueFullException` errors** under load.
- **Per-instance throughput decreases** when `MaxConnectionPoolSize` is reduced.
- **Exceptions occur unpredictably**, even when per-instance loads are within previously successful thresholds.

**Analysis and Attempts to Resolve:**

- **Initial Hypothesis:**
  - The cumulative number of connections from all instances exceeds the Azure Cosmos DB's capacity.
  - Each instance maintains its own `MongoClient` with its own connection pool of 112 connections, leading to a high total number of connections when scaling.

- **Adjusting `MaxConnectionPoolSize`:**
  - **Reduced `MaxConnectionPoolSize` to 20 or 50** per instance to manage total connections when scaling.
  - **Observed Behavior:**
    - Sometimes the application handles the load without issues.
    - Other times, `MongoWaitQueueFullException` errors occur, even at lower per-instance loads (e.g., 500 RPS).
    - The per-instance throughput is significantly reduced compared to when `MaxConnectionPoolSize` is 112.

- **Trade-Off Observed:**
  - **Higher `MaxConnectionPoolSize` (112):**
    - **Pros:** Single instance handles up to 1,000 RPS without issues.
    - **Cons:** Scaling out leads to cumulative connections exceeding database capacity, causing exceptions.
  - **Lower `MaxConnectionPoolSize` (20 or 50):**
    - **Pros:** Total connections when scaling are within database capacity.
    - **Cons:** Per-instance throughput decreases; exceptions occur unpredictably.

- **Unpredictable Exceptions:**
  - Even after reducing `MaxConnectionPoolSize`, the exceptions occur inconsistently, making it difficult to ensure stable performance.

**Questions and Concerns:**

1. **What is the maximum number of concurrent connections supported by Azure Cosmos DB for MongoDB API?**
   - Unable to find explicit connection limits in the documentation.
   - Cannot use standard MongoDB commands (e.g., `db.serverStatus().connections`) in Azure Cosmos DB to check.

2. **How can I balance `MaxConnectionPoolSize` to support both high per-instance throughput and total connections when scaling?**

3. **Why does reducing `MaxConnectionPoolSize` lead to unpredictable exceptions, even at lower loads?**

4. **Is there a recommended approach to manage connections and scaling with Azure Cosmos DB for MongoDB API in a containerized, scaled-out environment?**

**Relevant Code Snippets:**

**Program.cs:**

```csharp
builder.Services.AddSingleton<IMongoClient>(sp =>
{
    var mongoConnectionString = builder.Configuration["MongoDB-ConnectionString"];
    if (string.IsNullOrEmpty(mongoConnectionString))
    {
        throw new InvalidOperationException("MongoDB connection string is not set.");
    }

    // Configure MongoDB connection with pool size and timeout settings
    var settings = MongoClientSettings.FromConnectionString(mongoConnectionString);

    // Adjusted MaxConnectionPoolSize
    settings.MaxConnectionPoolSize = 112; // Also tested with 20 and 50
    settings.WaitQueueTimeout = TimeSpan.FromSeconds(30); // Timeout for waiting connections

    // Enable logging of MongoDB connection pool events
    settings.ClusterConfigurator = cb =>
    {
        cb.Subscribe<ConnectionPoolOpenedEvent>(e =>
        {
            Console.WriteLine($"MongoDB Connection Pool Opened: {e.ConnectionPoolSettings.MaxConnections}");
        });
    };

    return new MongoClient(settings);
});
```

**WaitlistService.cs:**

```csharp
public class WaitlistService : IWaitlistService
{
    private readonly IMongoCollection<WaitlistEntry> _waitlistEntries;
    private readonly TelemetryClient _telemetryClient;

    public WaitlistService(IMongoClient mongoClient, TelemetryClient telemetryClient)
    {
        var database = mongoClient.GetDatabase("cmCoreDb");
        _waitlistEntries = database.GetCollection<WaitlistEntry>("cmWaitlist");
        _telemetryClient = telemetryClient;
    }

    public async Task<(WaitlistEntry? Entry, bool IsNewEntry)> CreateOrUpdateEntryAsync(WaitlistEntry entry)
    {
        var startTime = DateTime.UtcNow;
        var success = false;
        try
        {
            var filter = Builders<WaitlistEntry>.Filter.Eq(e => e.Email, entry.Email);
            var update = Builders<WaitlistEntry>.Update
                .Set(e => e.FirstName, entry.FirstName)
                .Set(e => e.LastName, entry.LastName)
                .Set(e => e.CompanyName, entry.CompanyName)
                .Set(e => e.CompanySize, entry.CompanySize)
                .Set(e => e.Country, entry.Country)
                .Set(e => e.Role, entry.Role)
                .Set(e => e.Usage, entry.Usage);

            var options = new FindOneAndUpdateOptions<WaitlistEntry>
            {
                IsUpsert = true,
                ReturnDocument = ReturnDocument.After
            };

            var result = await _waitlistEntries.FindOneAndUpdateAsync(filter, update, options);

            success = true;
            var isNewEntry = result.Id != entry.Id;

            return (result, isNewEntry);
        }
        catch (Exception ex)
        {
            _telemetryClient.TrackException(ex);
            return (null, false);
        }
        finally
        {
            var duration = DateTime.UtcNow - startTime;
            _telemetryClient.TrackDependency("MongoDB", "CreateOrUpdateEntry", "cmCoreDb.cmWaitlist", startTime, duration, success);
        }
    }
}
```

**Request for Assistance:**

I'm seeking guidance on the following:

1. **Understanding Azure Cosmos DB for MongoDB API Connection Limits:**
   - **Is there a way to determine or estimate the maximum number of concurrent connections supported?**
   - **Are there hidden or undocumented limits that could explain this behavior?**

2. **Best Practices for Managing Connections in a Scaled-Out Environment:**
   - **How can I configure `MaxConnectionPoolSize` to balance high per-instance throughput and total connections when scaling?**
   - **Are there recommended patterns or configurations for using Azure Cosmos DB with scaled-out containerized applications?**

3. **Addressing the Unpredictable Exceptions:**
   - **Why do exceptions occur unpredictably even after adjusting `MaxConnectionPoolSize`?**
   - **Is there additional configuration or code changes needed to ensure stable performance?**

4. **Optimizing for High Throughput with Scaling:**
   - **How can I maintain high per-instance throughput (up to 1,000 RPS) while scaling out without hitting connection limits?**

**Additional Context:**

- **Monitoring and Logging:**
  - Implemented logging for connection pool events.
  - Monitored Application Insights for exceptions and performance metrics.

- **Scaling Configuration:**
  - Scaling based on RPS with thresholds set to trigger scaling when RPS exceeds certain values (e.g., 500 RPS).
  - Scaling leads to multiple instances each with their own `MongoClient` and connection pool.

- **Application Insights:**
  - Exceptions occur even when overall load should be manageable based on single-instance performance.
  - No significant resource constraints observed on the application instances themselves.

**Attachments:**

- **Full `Program.cs` and `WaitlistService.cs` files.**
- **Application Insights exception logs and performance metrics.**
- **Azure Container Apps scaling configuration.**
- **Load test results demonstrating the issue.**

**Thank You:**

I appreciate any assistance or guidance on resolving this issue. Understanding how to effectively manage connections and scaling with Azure Cosmos DB for MongoDB API is critical for our application's success. Please let me know if any additional information is required.

---

**Note to Maintainers:**

- **Emphasized Point:** The core dilemma is that **the application can handle up to 1,000 RPS on a single container instance without any issues**, but when scaling out to multiple instances, **connection limit exceptions occur** even though the per-instance load is lower.
- **Adjusting `MaxConnectionPoolSize` Doesn't Fully Resolve the Issue:**
  - **Reducing `MaxConnectionPoolSize` per instance helps manage total connections but leads to decreased per-instance throughput and unpredictable exceptions.**
  - **There's a need for a solution that allows high per-instance performance while scaling out without hitting connection limits.**

---

**Looking forward to your insights and recommendations on this matter.**

**Comment by kirankumarkolli** [comment]
@yhsparrow this repo is only for CosmosDB SQL API. 
Can you please raise ICM to follow-up?

**Comment by yhsparrow** [comment]
Done.

Raised a Support request on azure.

Is there a repo for CosmosDB Mongo API?
