### ISSUE TITLE
Make CosmosClient creation non-blocking

### ISSUE THREAD

**Issue by wilcobmsft** [Azure/azure-cosmos-dotnet-v3#475]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled. --- End of inner exception stack trace --- at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at Microsoft.Azure.Cosmos.DocumentClient.get_ConsistencyLevel() at Microsoft.Azure.Cosmos.CosmosClient.Init(CosmosClientConfiguration configuration, DocumentClient documentClient) at Microsoft.Azure.Cosmos.CosmosClient..ctor(CosmosClientConfiguration

**To Reproduce**
Create ASP.NET Core 2.2 app and from a health check initialize a CosmosClient instance, and then invoke the health check. This may not repro consistently.

**Expected behavior**
There shouldn't be any async-blocking calls from CosmosClient's constructor.

**Actual behavior**
Provide a description of the actual behavior observed. 
Deadlock/timeouts.

**Environment summary**
SDK Version: 3.0.0.9-preview
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
@wilcobmsft there has been a lot of changes to the SDK recently. Are you still seeing issues in the latest 3.0.0.18-preview?

**Comment by wilcobmsft** [comment]
We should be on 18-preview sometime next week. From inspecting the code though, I can still see a blocking call made from DocumentClient.get_ConsistencyLevel which is undesirable. At a minimum it'd be great if we could for example explicitly set DesiredConsistencyLevel, and have it skip the call to EnsureValidClientAsync() in that case.

**Comment by fuocor** [comment]
there are other problems with 3.0.0.18-preview preventing a move.
It deadlocks when creating more than one CosmosClient as well as calling CreateDatabaseIfNotExistsAsync more than once (even if the other calls have completed)

**Comment by fuocor** [comment]
This morning's (June 21) build from source seems to fix the problem

**Comment by j82w** [comment]
@kirankumarkolli do you have any suggestions on fix this deadlock issue?

@fuocor all of our tests are [here](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos/tests) on GitHub. They run on every check-in. If you see any scenarios that are missing feel free to create a PR to add them. Can you please create an issue for any other problems that are blocking you.
