### ISSUE TITLE
Significant difference in Duration and RequestCharge between single and multi partitions containers

### ISSUE THREAD

**Issue by markwgit** [Azure/azure-cosmos-dotnet-v3#4767]
**Describe the bug**
When I run same query on single partition container and on multi-partitions (2 levels) container, I detect significant difference in query duration and in query RequestCharge. 
Example: 
- Single partition query: Duration 1.78s and RequestCharge 4.63
- Multi-partition query: Duration: **4.23s** and  RequestCharge **73.16**
Both containers contain exactly same data and I run exactly same query and query returns exactly same result (10 records)

**To Reproduce**
I wrote [a console application](https://github.com/user-attachments/files/17290206/HighRUs.zip) to reproduce the issue. Please download the solution, open the Program.cs file and specify a Auth Key (it can be supplied separately) to our Test Azure Cosmos DB account. The application will run two queries - one to Single partition container and one to Multi partition container and it will display query duration and RequestCharge. 
Following Diagnostics information for problematic query: [Diagnostics.txt](https://github.com/user-attachments/files/17291978/Diagnostics.txt)

**Expected behavior**
Both queries should have relatively same duration and same RequestCharge.

**Actual behavior**
Significant difference in Duration (more than x2)  and in RequestCharge (more than x17)

**Environment summary**
SDK Version: 3.43.1
OS Version Windows 11

**Additional context**
I am working on migration our solution from single partition container to multi partitions container to solve 20GB partition limit.
All customer data was migrated, and we switched the customer to work over new container. We experienced huge increase of RUs and significant performance degradation. The customer migration was paused.

**Comment by markwgit** [comment]
From additional investigation I found that adding partition condition (c.PartitionKey = '06f43ec1-b920-440b-91fb-6dfc5b3af47d') to problematic query significantly reduce RequestCharge from **73 to 16**, but this does not change the duration. Without this condition in query, the "Index Utilization" in Diagnostics is very low - 3% and with condition it is 100%

**Comment by kundadebdatta** [comment]
This was discussed and closed offline. The recommendation is to use the partition directly from the `QueryRequestOptions`.
