### ISSUE TITLE
Distributed Tracing: Operation name not being populated after 3.43.0

### ISSUE THREAD

**Issue by asos-fernandopiccin** [Azure/azure-cosmos-dotnet-v3#4768]
**Describe the bug**
We have upgraded to the latest version of cosmos (3.43.1) - upgrade from 3.41.0 and we have noticed that Cosmos Dependency Tracking on App Insights Dependency table doesn't have the following information:
* target
* name

These aren't being populated and currently show as `n/a` in App Insight's dependencies table.

**To Reproduce**
Install the packages: `Microsoft.Azure.Cosmos 3.43.1` (latest at time of writing)
Install latest package of ApplicationInsights: `Microsoft.ApplicationInsights 2.22.0`
Make SDK operations to Cosmos e.g. `CreateItemStreamAsync` or `ReadItemStreamAsync`.

**Expected behavior**
Expected to see `target` and `name` populated correctly in the `dependencies` table in app insights- like previous nuget package (3.41.0)
![image](https://github.com/user-attachments/assets/5d7db80f-9f03-4212-a687-5440754daa08)

**Actual behavior**
![image](https://github.com/user-attachments/assets/12d146aa-7fb7-46e7-9ba8-beace2578b95)
`Target` and `name` are showing as `n/a` in the `dependencies` table in app insights.

**Environment summary**
SDK Version: 3.43.1
OS Version (e.g. Windows, Linux, MacOSX): .net8 (linux & win11)

**Additional context**
Based on quick look at Cosmos and Application Insights source code, App Insights expects the `db.operation` and `db.name` to populate the name and target fields. [Link here](https://github.com/microsoft/ApplicationInsights-dotnet/blob/e34286b4c8175d7ea47f9227c5b981d661cac470/WEB/Src/DependencyCollector/DependencyCollector/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L356C38-L356C50).
However, these tag names have been recently changed in the Cosmos SDK as part of [this](https://github.com/Azure/azure-cosmos-dotnet-v3/commit/9deb6e55107bf0d93f7f1a6e4f85ba053571bb55#diff-7e1e4d32e5f4367317a5b760f9b7bb767ea0713f3c22b8f452f70c712b6ef19dR49) change. 
![image](https://github.com/user-attachments/assets/3e2149cd-db3d-40d6-892a-271925b79cdd)

Is this an intentional change? Is there any intention for this to be fixed?

**Comment by philipthomas-MSFT** [comment]
> Is this an intentional change? Is there any intention for this to be fixed?

Hello @asos-fernandopiccin,

First, we greatly appreciate you reaching out to us, and we’re excited that you are using our product! Let me attempt to answer your question and help resolve this issue.

Based on the following [PR #4622](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4622) in the Cosmos DB .NET SDK repository, there has been a shift to align with OpenTelemetry conventions. You can find more details in the [OpenTelemetry Semantic Conventions for Microsoft Cosmos DB](https://opentelemetry.io/docs/specs/semconv/database/cosmosdb/).

Regarding the specific attributes:
- The `db.operation` attribute has been replaced by `db.operation.name`. This change reflects a more descriptive and explicit naming for the operation being performed, such as "ReadItem", "WriteItem", or "Query". The goal is to provide clearer insights into the specific type of operation happening within Cosmos DB.
- The `db.name` attribute has been replaced by `db.namespace`. This change allows for better differentiation in scenarios where multiple databases might be used across a single telemetry session. The `db.namespace` provides a more structured identifier, representing the fully qualified name or context of the database, enabling improved observability.

These changes were made to standardize tracing and ensure compatibility with OpenTelemetry, which is widely adopted for distributed tracing and observability.

If you have any further questions, please feel free to ask. We’re here to help!

@sourabh1007 Feel free to give your insight.

**Comment by philipthomas-MSFT** [comment]
> Do you know if there’s any plan from the Cosmos SDK maintainers to reintroduce the old attributes, marking them as obsolete, or is the current expectation that clients wait for a fix from the App Insights SDK?

Hello @asos-fernandopiccin,

We are currently working on a PR and hotfix release to reintroduce the `db.operation` and `db.name` attributes. Thank you for bringing this to our attention. We’ll be sure to take additional precautions in the future to prevent similar issues. We appreciate your continued support and contributions in making our product a success.

**Comment by asos-fernandopiccin** [comment]
Perfect. Thank you very much.

**Comment by sourabh1007** [comment]
Please upgrade to this version https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.44.1.
