### ISSUE TITLE
CosmosClientOptions constructor fails

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#479]
**Describe the bug**
```new CosmosClientOptions()``` throws 
```System.MethodAccessException```
on 
```this.UserAgentContainer = new UserAgentContainer()```

**Expected behavior**
Really should work

**Environment summary**
Library: 3.0.0.18-preview 
SDK Version: 3.0.100-preview6-011767
OS Version  Windows 10

**Comment by j82w** [comment]
@fuocor what framework are you using? I just checked .net core 2.0 and 2.1 it worked for me.

**Comment by j82w** [comment]
@fuocor can you provide a repo? .NET core 3.0 work for me.

**Comment by kirankumarkolli** [comment]
Please re-open with repro.
