### ISSUE TITLE
Getting sane errors out of sprocs

### ISSUE THREAD

**Issue by kentcb** [Azure/azure-cosmos-dotnet-v3#48]
**Is your feature request related to a problem? Please describe.**
I just want a sensible way/guidance to get errors out of procs. Throwing `Error` per the docs is fine and dandy, except now you've no practical way of switching on error codes or the likes from the client side. Throwing a JSON-formatted string and catching `BadRequestException` / `DocumentClientException` seemed promising, except both those exceptions are (inexplicably) internal types with no way of getting the `Error` object without reflection. Also, they get unwrapped into a `CosmosException` which throws away the `Error` property altogether and leaves you with little choice but to do string manipulation on its `Message` property.

**Describe the solution you'd like**
Make it practical to get errors out of sprocs and UDFs in such a way that the client can obtain information about what went wrong. Add relevant information to the docs.

**Describe alternatives you've considered**
As best I can tell, all alternatives are hacks. Reflection, string parsing etc. Yuck.

**Comment by kirankumarkolli** [comment]
@kentcb can you please sent a mail to askcosmosdb[AT]microsoft.com? I will compile and put the summary on this thread.

**Comment by mkolt** [comment]
From inside sproc you can throw new Error(errorCode, "Error message"), where errorCode is a number (short int) like 1234. On client side you can get this code from DocumentClientException as SubStatusCode which can be obtained from DocumentClientException.ResponseHeaders (e.g. see [how to get it](https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet/blob/master/src/DocumentDB.ChangeFeedProcessor/DocDBErrors/SubStatusHelpers.cs)).

**Comment by kentcb** [comment]
Thanks @mkolt - this is great.

Per my original request though, I don't think this issue should be closed until this information has been added to [the docs](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-write-stored-procedures-triggers-udfs). I just tried googling "Cosmos DB SubStatusCode errorCode" and can't find anything in the docs about this. Actually, one of the first results to come up is [this user voice](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/20355553-i-want-to-get-better-support-for-custom-exceptions).

**Comment by andersborum** [comment]
What's the status on this? I am unable to find any official information on the "x-ms-substatus" HTTP response header. I've been using Cosmos DB for some time now and am starting to write SPROCs using typescript (async/await for the win), and with that quickly came the requirement of relaying different error codes back to the caller.

**Comment by AlejandroBlanco** [comment]
I agree. This is poor or forced design. Error codes within errors throws from sprocs cause always a BadRequestException without any data except a cosmosError added by force to suck Exception and the internal sub error codes. I think the container client should parse the error codes, not the user
