### ISSUE TITLE
Inconsistent Handling of Numeric-Looking Keys in Patch Operations

### ISSUE THREAD

**Issue by mrcameron999** [Azure/azure-cosmos-dotnet-v3#4817]
Description:

I am encountering an issue with Azure Cosmos DB where using numeric-looking keys as property names in patch operations leads to unexpected errors. This problem seems to have arisen recently and is affecting the functionality of my application.

**To Reproduce**
1. Initial Document Structure: The document structure is any JSON object where numeric-looking keys are used. For example:

```
{
    "MyDocument": "test",
    "123456789123456789123456789": null
}
```

2. Patch Operation: When attempting to perform a patch operation using the following code, an error occurs:

`PatchOperation.Add($"/123456789123456789123456789", "test");`
```
Error Message: The operation fails with the message:

"Token('123456789123456789123456789') has length longer than expected."
```

3. If adding any sort of letter to the patch patrh it works fine. For example works as expected
`PatchOperation.Add($"/TEST_123456789123456789123456789", "test");`

**Expected behavior**
Patch operations using both numeric-looking strings and prefixed strings as property names should work consistently without errors, similar to other string keys.

**Actual behavior**
The patch operation fails with an error when the key appears numeric, while it succeeds as long as there is at least 1 non number character in the string

**Environment summary**
SDK Version: 3.44.1
OS Version Windows development and Linux container. Both experience same issue

**Additional context**
This was working previously (24-48 hours ago)

**Comment by NaluTripician** [comment]
Hi @mrcameron999 thank you for bringing this to our attention. We will investigate and try to resolve your issues as soon as possible.

**Comment by NaluTripician** [comment]
Hi @mrcameron999 thank you for your patience. What is happening here is a result of you document structure and how patch operations work. Partial document update operations are based on the [JSON Patch RFC](https://www.rfc-editor.org/rfc/rfc6902#appendix-A.14) and the property names need to include the proper escape character. However, if the target path is a valid array index, a new element is inserted into the array at the specified index. In your case, the JSON serializer thinks that your path `123456789123456789123456789` is an index not the name of the path, giving you the error. For your case you can change your Patch Operation to: 

`PatchOperation.Add($"/\"123456789123456789123456789\"", "test");`
or
`PatchOperation.Add($"/~123456789123456789123456789", "test");`

Which should solve your issue. You can also read [this article](https://learn.microsoft.com/en-us/azure/cosmos-db/partial-document-update#supported-operations) which should give more information about partial document updates in Azure Cosmos DB. 

Please feel free to re-open this issue if the solution I gave does not solve your issue.

**Comment by Mario-GG** [comment]
@NaluTripician you suggested escaping, but neither of your examples result in the expected outcome:
(tested it in .NET app: Microsoft.Azure.Cosmos 3.39.0-preview.0)
`PatchOperation.Add("/f/\"1963722725090973\"", "test");` -> `{ "f": { "\"1963722725090973\"": "test" } }`
`PatchOperation.Add("/f/~1963722725090973", "test");` -> `{ "f": { "/963722725090973": "test" } }` (looks like ~1 is replaced by '/')

is there any other way to explicitly state in the patch operation that the path I am referring to is a string and not an interer array index?
