### ISSUE TITLE
Block multiple CosmosClient instance creations

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#485]
Applications should only create a single CosmosClient instance per an account. Creating new instances of causes all the caches to be reloaded, and cause other various performance issues.

Purposed solution:
Add a static hashset of account names that have a CosmosClient. If the user attempts to create a new CosmosClient and it already exists in the hashset it will throw an exception to the user. We could add an additional flag in the options to bypass this check.

**Comment by kirankumarkolli** [comment]
Singleton is a good use-case and it needs to be scoped to a version of client-options (not just credentials, end-point, region/preferred-locations). 

Also it needs attention on life-time. Infinite lifetime might lead to blocking explicit re-initialization asks (ex: bad state for some reason).
