### ISSUE TITLE
Resolved Not Bug: Getting Partition Key doesn't match error when value is confirmed identical

### ISSUE THREAD

**Issue by drewid** [Azure/azure-cosmos-dotnet-v3#4862]
**SDK Version**: Windows/10.0.22631 cosmos-netstandard-sdk/3.36.1

**Describe the bug**
Getting the following error when doing CreateItemAsync on a Container:

```
Unhandled exception. Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 1001; ActivityId: e6b6b95e-0b66-43bb-9c28-b4b159cd4c46; Reason: (Message: {"Errors":["PartitionKey extracted from document doesn't match the one specified in the header. Learn more: https://aka.ms/CosmosDB/sql/errors/wrong-pk-value"]}
ActivityId: e6b6b95e-0b66-43bb-9c28-b4b159cd4c46, Request URI: /apps/7ebc5b84-a56a-4396-80b9-52f8cbe8eff5/services/deaee0df-05d4-4bd1-af1a-6e65251fc09e/partitions/0af77670-158d-4661-b050-66452712894d/replicas/133746939022828536p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22631 cosmos-netstandard-sdk/3.36.1);
```

I have successfully run checks on the database and container that things look correct:

- db.CreateContainerIfNotExistsAsync(containerProperties)
- writeContainer.ReadContainerAsync() to get and confirm the PartitionKeyPath is the same that is being specified in CreateItemAsync

**To Reproduce**
Running the following CreateItemAsync call:
`var itemResponse = await _writeContainer.CreateItemAsync(item, new PartitionKey(PartitionKeyPath));`

**Expected behavior**
After running the following, the item is created in the database container without error: 
`var itemResponse = await _writeContainer.CreateItemAsync(item, new PartitionKey(PartitionKeyPath));`

**Actual behavior**
Getting the following error when doing CreateItemAsync on a Container:

```
Unhandled exception. Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 1001; ActivityId: e6b6b95e-0b66-43bb-9c28-b4b159cd4c46; Reason: (Message: {"Errors":["PartitionKey extracted from document doesn't match the one specified in the header. Learn more: https://aka.ms/CosmosDB/sql/errors/wrong-pk-value"]}
ActivityId: e6b6b95e-0b66-43bb-9c28-b4b159cd4c46, Request URI: /apps/7ebc5b84-a56a-4396-80b9-52f8cbe8eff5/services/deaee0df-05d4-4bd1-af1a-6e65251fc09e/partitions/0af77670-158d-4661-b050-66452712894d/replicas/133746939022828536p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22631 cosmos-netstandard-sdk/3.36.1);
```

**Environment summary**
SDK Version: Windows/10.0.22631 cosmos-netstandard-sdk/3.36.1
OS Version: Windows 11 Pro 23H2
OS Build: 22631.4317
Experience Pack: 1000.22700.1041.0

**Additional context**
`--- Cosmos Diagnostics ---{"Summary":{"DirectCalls":{"(400, 1001)":1},"GatewayCalls":{"(200, 0)":3,"(304, 0)":1}},"name":"CreateItemAsync","start datetime":"2024-10-30T03:48:15.247Z","duration in milliseconds":610.4707,"data":{"Client Configuration":{"Client Created Time Utc":"2024-10-30T03:48:14.2826252Z","MachineId":"hashedMachineName:496ac4f5-9108-38d5-43d3-405eb1360211","NumberOfClientsCreated":2,"NumberOfActiveClients":2,"ConnectionMode":"Direct","User Agent":"cosmos-netstandard-sdk/3.45.0P|2|X64|Microsoft Windows 10.0.22631|.NET 9.0.0-rc.2.24473.5|N|","ConnectionConfig":{"gw":"(cps:50, urto:6, p:False, httpf: False)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:False, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[], apprgn: )","ProcessorCount":20},"DistributedTraceId":"b8eee1d715c9d6546b44d9f53bacadeb"},"children":[{"name":"ItemSerialize","duration in milliseconds":0.3448},{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","duration in milliseconds":606.954,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","duration in milliseconds":603.277,"data":{"System Info":{"systemHistory":[{"dateUtc":"2024-10-30T03:48:14.5632139Z","cpu":0.892,"memory":11283216.000,"threadInfo":{"isThreadStarving":"no info","availableThreads":32765,"minThreads":20,"maxThreads":32767},"numberOfOpenTcpConnection":0}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TelemetryHandler","duration in milliseconds":603.269,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","duration in milliseconds":603.2481,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","duration in milliseconds":600.9207,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","duration in milliseconds":600.918,"children":[{"name":"Microsoft.Azure.Documents.ServerStoreModel Transport Request","duration in milliseconds":593.2223,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus2-be147.documents.azure.com:14019/apps/7ebc5b84-a56a-4396-80b9-52f8cbe8eff5/services/deaee0df-05d4-4bd1-af1a-6e65251fc09e/partitions/0af77670-158d-4661-b050-66452712894d/replicas/133746939022828536p/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus2-be147.documents.azure.com:14123/apps/7ebc5b84-a56a-4396-80b9-52f8cbe8eff5/services/deaee0df-05d4-4bd1-af1a-6e65251fc09e/partitions/0af77670-158d-4661-b050-66452712894d/replicas/133746939138765161s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus2-be147.documents.azure.com:14304/apps/7ebc5b84-a56a-4396-80b9-52f8cbe8eff5/services/deaee0df-05d4-4bd1-af1a-6e65251fc09e/partitions/0af77670-158d-4661-b050-66452712894d/replicas/133746939138765160s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus2-be147.documents.azure.com:14439/apps/7ebc5b84-a56a-4396-80b9-52f8cbe8eff5/services/deaee0df-05d4-4bd1-af1a-6e65251fc09e/partitions/0af77670-158d-4661-b050-66452712894d/replicas/133746939138765162s/"}],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[{"StartTimeUTC":"2024-10-30T03:48:15.4602946Z","EndTimeUTC":"2024-10-30T03:48:15.5051076Z","TargetEndpoint":"https://innovengine-tst-db-eastus2.documents.azure.com//addresses/?$resolveFor=dbs%2fCrkDAA%3d%3d%2fcolls%2fCrkDANnXd2k%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=0"}],"StoreResponseStatistics":[{"ResponseTimeUTC":"2024-10-30T03:48:15.8429602Z","DurationInMs":326.0561,"ResourceType":"Document","OperationType":"Create","LocationEndpoint":"https://innovengine-tst-db-eastus2.documents.azure.com/","StoreResult":{"ActivityId":"e6b6b95e-0b66-43bb-9c28-b4b159cd4c46","StatusCode":"StartingErrorCode","SubStatusCode":"PartitionKeyMismatch","LSN":4,"PartitionKeyRangeId":"0","GlobalCommittedLSN":4,"ItemLSN":-1,"UsingLocalLSN":false,"QuorumAckedLSN":4,"SessionToken":"-1#4","CurrentWriteQuorum":3,"CurrentReplicaSetSize":4,"NumberOfReadRegions":0,"IsValid":true,"StorePhysicalAddress":"rntbd://cdb-ms-prod-eastus2-be147.documents.azure.com:14019/apps/7ebc5b84-a56a-4396-80b9-52f8cbe8eff5/services/deaee0df-05d4-4bd1-af1a-6e65251fc09e/partitions/0af77670-158d-4661-b050-66452712894d/replicas/133746939022828536p/","RequestCharge":1.24,"RetryAfterInMs":null,"BELatencyInMs":"0.393","ReplicaHealthStatuses":["(port: 14019 | status: Connected | lkt: 10/30/24 03:48:15)"],"transportRequestTimeline":{"requestTimeline":[{"event": "Created", "startTimeUtc": "2024-10-30T03:48:15.5181977Z", "durationInMs": 1.8031},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2024-10-30T03:48:15.5200008Z", "durationInMs": 247.5431},{"event": "Pipelined", "startTimeUtc": "2024-10-30T03:48:15.7675439Z", "durationInMs": 10.6508},{"event": "Transit Time", "startTimeUtc": "2024-10-30T03:48:15.7781947Z", "durationInMs": 50.8032},{"event": "Received", "startTimeUtc": "2024-10-30T03:48:15.8289979Z", "durationInMs": 3.9647},{"event": "Completed", "startTimeUtc": "2024-10-30T03:48:15.8329626Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":1,"openConnections":1},"connectionStats":{"waitforConnectionInit":"True","callsPendingReceive":0,"lastSendAttempt":"2024-10-30T03:48:15.7164526Z","lastSend":"2024-10-30T03:48:15.7168432Z","lastReceive":"2024-10-30T03:48:15.7639263Z"},"requestSizeInBytes":822,"requestBodySizeInBytes":400,"responseMetadataSizeInBytes":189,"responseBodySizeInBytes":160},"TransportException":null}}],"HttpResponseStats":[{"StartTimeUTC":"2024-10-30T03:48:15.2727919Z","DurationInMs":64.1094,"RequestUri":"https://innovengine-tst-db-eastus2.documents.azure.com/dbs/innovengine-tst-db/colls/User","ResourceType":"Collection","HttpMethod":"GET","ActivityId":"7ecad5cd-c787-4620-9ae5-5cfce44919fc","StatusCode":"OK"},{"StartTimeUTC":"2024-10-30T03:48:15.3451730Z","DurationInMs":47.7689,"RequestUri":"https://innovengine-tst-db-eastus2.documents.azure.com/dbs/CrkDAA==/colls/CrkDANnXd2k=/pkranges","ResourceType":"PartitionKeyRange","HttpMethod":"GET","ActivityId":"154cb2b5-6d96-443c-ab36-783f9e952240","StatusCode":"OK"},{"StartTimeUTC":"2024-10-30T03:48:15.3984612Z","DurationInMs":50.8357,"RequestUri":"https://innovengine-tst-db-eastus2.documents.azure.com/dbs/CrkDAA==/colls/CrkDANnXd2k=/pkranges","ResourceType":"PartitionKeyRange","HttpMethod":"GET","ActivityId":"d1194e10-fc33-4b7a-b42a-109dc2111ea6","StatusCode":"NotModified","ReasonPhrase":"Not Modified"},{"StartTimeUTC":"2024-10-30T03:48:15.4607803Z","DurationInMs":43.7912,"RequestUri":"https://innovengine-tst-db-eastus2.documents.azure.com//addresses/?$resolveFor=dbs%2fCrkDAA%3d%3d%2fcolls%2fCrkDANnXd2k%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=0","ResourceType":"Document","HttpMethod":"GET","ActivityId":"e6b6b95e-0b66-43bb-9c28-b4b159cd4c46","StatusCode":"OK"}]},"Point Operation Statistics":{"Id":"PointOperationStatistics","ActivityId":"e6b6b95e-0b66-43bb-9c28-b4b159cd4c46","ResponseTimeUtc":"2024-10-30T03:48:15.8543787Z","StatusCode":400,"SubStatusCode":1001,"RequestCharge":1.24,"RequestUri":"dbs/innovengine-tst-db/colls/User","ErrorMessage":"Microsoft.Azure.Documents.BadRequestException: Message: {\"Errors\":[\"PartitionKey extracted from document doesn't match the one specified in the header. Learn more: https://aka.ms/CosmosDB/sql/errors/wrong-pk-value\"]}\r\nActivityId: e6b6b95e-0b66-43bb-9c28-b4b159cd4c46, Request URI: /apps/7ebc5b84-a56a-4396-80b9-52f8cbe8eff5/services/deaee0df-05d4-4bd1-af1a-6e65251fc09e/partitions/0af77670-158d-4661-b050-66452712894d/replicas/133746939022828536p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22631 cosmos-netstandard-sdk/3.36.1\r\n   at Microsoft.Azure.Documents.StoreResult.ToResponse(RequestChargeTracker requestChargeTracker)\r\n   at Microsoft.Azure.Documents.ConsistencyWriter.WritePrivateAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean forceRefresh)\r\n   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)\r\n   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)\r\n   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)\r\n   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)\r\n   at Microsoft.Azure.Documents.ConsistencyWriter.WriteAsync(DocumentServiceRequest entity, TimeoutHelper timeout, Boolean forceRefresh, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass32_0.<<InvokeAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)\r\n   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)\r\n   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)\r\n   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)\r\n   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)","RequestSessionToken":null,"ResponseSessionToken":"0:-1#4","BELatencyInMs":"0.393"}}}]}]}]}]}]}]}]}`

**Comment by sourabh1007** [comment]
You can try to run [this](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createitemasync?view=azure-dotnet) simple example to make sure, if there is an issue in code or cosmos db service.

Anyway, `await _writeContainer.CreateItemAsync(item, new PartitionKey(PartitionKeyPath));` what are you passing in place of `PartitionKeyPath`, it has to be partition key value, not path.

**Comment by drewid** [comment]
> You can try to run [this](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createitemasync?view=azure-dotnet) simple example to make sure, if there is an issue in code or cosmos db service.
> 
> Anyway, `await _writeContainer.CreateItemAsync(item, new PartitionKey(PartitionKeyPath));` what are you passing in place of `PartitionKeyPath`, it has to be partition key value, not path.

Definitely aggravating that the Create and Return related to PartitionKey and PartionKeyPath would be consistent.  A bit aggravating that on create you just don't pass the PartitionKey, etc.

That aside, I doublechecked things and code currently definitely has just the PartitionKey value without the slash.  Getting the same error.

will look at the sample

**Comment by drewid** [comment]
Found my issue:  I had converted to using a Generic Type Parameter for the containers, which caused an issue getting the proper data from the field with the value being used for PartitionKey.

Needed to use the following to get the proper field with the partitionkey value to use:
`typeof(T).GetProperty(item.PartitionKey).GetValue(item).ToString()`
