### ISSUE TITLE
CosmosException constructor failed to set ActivityId

### ISSUE THREAD

**Issue by donghexu** [Azure/azure-cosmos-dotnet-v3#49]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
At this line: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs#L52
It should be this.ActivityId = activityId. Otherwise the ActivityId would never be set.

**Comment by j82w** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/commit/36e431ce1a0cca35f8a6b1d6aa5ffa705f848647
