### ISSUE TITLE
CFP Processor does not work on fixed lease containers

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#491]
Current CFP V2 supports Lease container to be fixed. If a user on V2 migrates to V3, we need to also support the possibility of fixed lease containers. The code was meant to support it but since migrated Fixed containers now have a system PK, it is not behaving as it should.

**Comment by bartelink** [comment]
Apologies for butting in, but is there a place where 'fixed' is defined ? I'm interested to know also what the prescription is wrt how to create a valid lease collection. It seems that creating a collection interactively and setting `id` as the 'Partition Key' (which is mandatory) - just works.
related: https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet/issues/142

**Comment by ealsur** [comment]
V3 SDK only creates partitioned collections. This bugfix is for when someone that was using V2 SDK already had a lease container, and was using V2 CFP, if they decide to migrate to V3, we should be able to handle that. 
But if they start on V3, then all collections should be partitioned, in the case of the Leases, the requirement is that the PK is /id as you mention.

**Comment by bartelink** [comment]
Ah, I see `CreateNonPartitionedContainer` in the PR now and assume _Fixed_ is an alias for `NonPartitioned`. I guess that makes the answer that the official correct way to generate a lease collection is to set partition key = `id` as you say

**Comment by ealsur** [comment]
`CreateNonPartitionedContainer` is a helper we have in the UTs to force creating a fixed container for testing purposes, see: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs#L1371
