### ISSUE TITLE
3.46.0 Release Notes/Changelog references incorrect property name

### ISSUE THREAD

**Issue by ctompkins-bestpass** [Azure/azure-cosmos-dotnet-v3#4912]
**Describe the bug**
The release notes and changelog for v3.46.0 says to set property "DisableNewtonsoftJsonCheck" to `true` however that does not work and the actual property name to set is "AzureCosmosDisableNewtonsoftJsonCheck".

**To Reproduce**
In project's csproj, set:
```
  <PropertyGroup>
    <DisableNewtonsoftJsonCheck>true</DisableNewtonsoftJsonCheck>
  </PropertyGroup>
```
And build error remains. Change to "AzureCosmosDisableNewtonsoftJsonCheck" and build error disappears.

**Expected behavior**
The release notes and changelog should reference the correct property to reduce confusion.

**Actual behavior**
Using the incorrect property name from the release notes and changelog fails to resolve the build failure.

**Environment summary**
SDK Version: 3.46.0
Windows

**Additional context**
I believe the property name was updated during development and PR review but notes were not changed after property name was updated. Actual build error message does include the correct property name.

**Comment by aavasthy** [comment]
Updated changelog and release notes with the correct property name as part of this PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4918
