### ISSUE TITLE
Should CosmosResponse<T> have a non-generic base class?

### ISSUE THREAD

**Issue by kentcb** [Azure/azure-cosmos-dotnet-v3#50]
## Is your feature request related to a problem? Please describe.
Yes, generalized logging of Cosmos responses is made far more convoluted by key information being defined inside a generic class unnecessarily, rather than extracting that information to a non-generic base class. For my actual scenario, see [this stackoverflow question](https://stackoverflow.com/questions/54776232).

## Describe the solution you'd like
I think `CosmosResponse<T>` should inherit from a `CosmosResponse` base class, which contains all properties that don't rely on `T`: `Headers`, `StatusCode`, `RequestCharge`, `ActivityId`, and `ETag`. All of these things are useful to get at in a generalized way, and it would be far easier to do that if you didn't have to fill in `T`.

## Describe alternatives you've considered
The workaround I have right now is shown in my stackoverflow question. It's messy and will perform far worse than if I just had a non-generic base class I could use instead.

**Comment by j82w** [comment]
If you are simply trying to log header information have you looked into using the [handlers](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/CodeSamples/Handlers)?

**Comment by kentcb** [comment]
Oh, hell yes, this is _way_ better. Sorry, had no idea this hook existed. Thanks @j82w!
