### ISSUE TITLE
Most efficient way to call stored proc with >1 arg including a large object

### ISSUE THREAD

**Issue by bartelink** [Azure/azure-cosmos-dotnet-v3#509]
I'm attempting to port some code from V2 to 3.0.0-rc1 and thought I'd ask here in order to get the most efficient approach for what's a heavy throughput call in our system.

The v2 code is as follows:

```
client.ExecuteStoredProcedureAsync(sprocLink, opts, ct, req, ev.index, maxEvents)
```
where `req, ev.index, maxEvents` are respectively a json.net serializable doc, an int and an it. The `req`, being an array of events etc can often be very large (i.e. heading for 1MB), so applying optimal encoding would be warranted.

From looking a the `CodeSamples` it seems based on [this comment](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0e1e2f31d57c00cec4ac61deafcd8d0f04ad1196/Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/Program.cs#L177) that there are some important considerations to maximize the efficiency.

I'd really appreciate it if this case can either be
a) covered in the samples, or 
b) if you'd be so kind as to outline my best angle of attack from a perf perspective, I'll supply a link to [the code](https://github.com/jet/equinox/blob/f7d1625240fcaec5cad270a84c50739725fd0013/src/Equinox.Cosmos/Cosmos.fs#L426) after I've applied any suggestions

(Ideally, I'd still be able to invoke the SP with 3 arguments:- object, number and number, but thats up for grabs if there is a significant perf gain to be had e.g. by having a single object and/or using `ExecuteStoredProcedureStreamAsync`)

**Comment by j82w** [comment]
Unfortunately we are still working on documentation and sample for performance scenarios. We don't currently have any performance numbers.

If you are looking for performance then the stream methods are the best option. 
1. No throwing and catching exceptions which is rather resource intensive. The stream methods only throw argument exceptions. The error message information is returned inside the response message. 
2. Serialization is one of the most resource intensive parts of the SDK. With streams you can use other serializers or implement custom ones that are more efficient then the default Newtonsoft version the SDK uses. 

You can see how we do the serialization in the code [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0e1e2f31d57c00cec4ac61deafcd8d0f04ad1196/Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs#L151).

**Comment by bartelink** [comment]
Thanks for the pointer, which answers the question very well indeed; it should hopefully work well (the transition from a `params object[]` to the present API is non-obvious, but I may have missed it in the xmldoc).

One thing that is not immediately obvious to me (I'm sure spending some time with the code would make it so but...) is why it's not an `Action<Stream>, and/or why there's not a `byte[]` overload (or is a `Span`-centric reworking is on the way?)

**Comment by j82w** [comment]
Here is a [sample](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0a3d1d8fe234d56ccc1e0a129fad12ab2f7be26f/Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/Program.cs#L181) using multiple objects. I created an [issue](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/514) to update the xml docs.

What benefit would an Action<Stream> or byte[] overload give? Span is not supported .NET standard 2.0. We could include the System.Memory nuget, but decided to wait for .NET standard 2.1.  Reworking the SDK to use Span is something we are interested in doing, but we don't currently have any plans for it.

**Comment by kirankumarkolli** [comment]
Thanks @bartelink for feedback. For usability its best to change back arguments to params[]. We will fix it for GA. 

Assuming above SPROC is for multi item CRUD scenario, there is a new preview feature in-pipeline  (Batch API) which lets specify the batch and process them. Related PR: #427

**Comment by j82w** [comment]
@bartelink here is the PR to support params. https://github.com/Azure/azure-cosmos-dotnet-v3/pull/515

**Comment by bartelink** [comment]
Was aware of single partition; makes sense. My SP is more [complex and specific](https://github.com/jet/equinox/blob/master/src/Equinox.Cosmos/Cosmos.fs#L356); I doubt the new facilities can cover it or [its intended successor logic](https://github.com/jet/equinox/pull/110).

The example is useful but very involved for people porting more trivial logic.

Benefit of an `Action` overload is that I don't need to allocate a MemoryStream (and you can pool them and pass them out to me to render into [e.g. using `RecycleableMemoryStreamManager`](https://github.com/jet/equinox/pull/139/files)).

If you're going to make me allocate, forcing me to gen/support something as specific as an `IStream` doesnt give me much - i.e. if I have to make a `MemoryStream` I need to do a lot of work whereas I can render up front into a `byte[]` and have stuff ready more cheaply than providing an `IStream`.

The road you've gone down to solve seems to work for me in general. However, one thing that made me scratch my head lightly is the `dynamic` - while this may have prior art in other API designs (does it?), it doesnt shout to me "these objects will be serialized via the configured serialization hook". Regarding the specific wording in the comment: `(Optional) An array of dynamic objects representing the parameters for the stored procedure.` - it might be useful to mention the process whereby those get mapped (is that via the `cosmosSerilalizer`?)

Upon deeper though, `dynamic` does make sense, but the original API "Didn't Make Me Think' at all (which probably made me consider the possibilities less deeply, which may be suboptimal overall)

**Comment by j82w** [comment]
The reason we chose stream was a lot of the frameworks already deal with streams. Streams also has the ability to allow users to pass a stream through an application and would allow them to avoid loading the entire object in memory. For an example a user could get a file stream and pass that file stream directly to the SDK. This prevents the user from needing to deserialize it.

**Comment by j82w** [comment]
I'm closing this since #515 was merged in.

**Comment by bartelink** [comment]
Thanks, and sorry for letting this run dead. Will try to make time to see how it looks soon but it does seem clearer now.
