### ISSUE TITLE
Request charge information missing for item queries?

### ISSUE THREAD

**Issue by kentcb** [Azure/azure-cosmos-dotnet-v3#51]
## Is your feature request related to a problem? Please describe.
Yes, just being able to get a sense of request charges for different queries.

## Describe the solution you'd like
The `CosmosQueryResponse<T>` type does not inherit from `CosmosResponse<T>`, so it is missing details like request charge. This is crucial for logging and understanding query costs.

## Describe alternatives you've considered
I know of none.

**Comment by kentcb** [comment]
In addition, item queries are not routed through registered `CosmosRequestHandler` instances.

This seems like a big deal to me...am I missing something?

**Comment by donghexu** [comment]
+1 for supporting this feature. Thank you,

**Comment by j82w** [comment]
Fixed in [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/125)
