### ISSUE TITLE
Typed API throw on 404

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#513]
Currently 404 is not treated as failure and returns status code. Its causing confusion with proxy objects + CRUD operations resulting in success. 

With stream API's we have the choice of non-exception API. Typed API throwing exceptions on 404 will help with V2 customers migration and also eases get-started scenarios as well.

**Comment by ausfeldt** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/528
