### ISSUE TITLE
Interface methods returning document feed should use IFeedResponse<T> not the concrete class

### ISSUE THREAD

**Issue by nathansoz** [Azure/azure-cosmos-dotnet-v3#516]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

Even though a IFeedResponse<T> exists, it is not used by IDocumentClient, making mocking of these methods basically impossible. 

**To Reproduce**
Try to mock anything using IDocumentClient that returns a feed response in unit tests. :)

**Expected behavior**
It should return the interface, especially because one exists. 

**Actual behavior**
It returns a non-mockable concrete class. 

**Environment summary**
SDK Version: latest
OS Version: all

Here's an example line: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5c495d2a581effd01dd0b2c9e01e1de53cd61001/Microsoft.Azure.Cosmos/src/IDocumentClient.cs#L2546

I would expect:

`Task<DocumentFeedResponse<Conflict>> ReadConflictFeedAsync(string conflictsLink, FeedOptions options = null);`

to become:

`Task<IDocumentFeedResponse<Conflict>> ReadConflictFeedAsync(string conflictsLink, FeedOptions options = null);`

**Comment by j82w** [comment]
This is the v2 conflicts implementation. The v3 repo still has a lot of code from the v2 SDK. Have you tried the v3 [conflicts](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/dcc56a8ac8e5dfac8af892fb0bf586eec5207d37/Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs)?

**Comment by j82w** [comment]
I'm closing this since it's a v2 issue. If you find an issue in the v3 SDK please create a new issue.

**Comment by nathansoz** [comment]
@j82w Is it possible to update the example repo to use these docs? I was using the v2 conflict implementation because that was the only thing with examples in both the documentation and examples that I could find regarding MultiMaster.

**Comment by j82w** [comment]
@nathansoz  we are in the process of updating all the documentation. Can you provide a link to the example you are referencing?

**Comment by nathansoz** [comment]
@j82w here is the doc link I read. I found the v2 example repo based on this: https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-manage-conflicts#read-from-conflict-feed

**Comment by j82w** [comment]
That docs still hasn't been updated yet. Are you able to figure it out by the [examples](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0d6d29f9ffde6394140a2227644044455fd1886b/Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs#L89)?
