### ISSUE TITLE
Sample v3 Solution missing resources 

### ISSUE THREAD

**Issue by darthmolen** [Azure/azure-cosmos-dotnet-v3#52]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
After doing a git clone, there are various projects that are "unavailable" and the solution is unable to run because of these missing project.

The missing projects are:
1. ContainerManagement
2. DatabaseManagement
3. ItemManagement
4. Microsoft.Azure.Cosmos.Direct
5. Shared

![image](https://user-images.githubusercontent.com/533340/53523820-7182f980-3aa3-11e9-868a-bb63d9244526.png)

**To Reproduce**
In a blank folder, git clone https://github.com/Azure/azure-cosmos-dotnet-v3 master branch and then go to the samples folder and open the SLN file Cosmos.Samples. Run the file and get errors. Also notice in the solution explorer that there are projects missing.

**Expected behavior**
Open the solution file, restore nuget packages, run the samples

**Actual behavior**
Error message about missing references.

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.0.0.1-preview1
Windows 10 Pro

**Comment by ealsur** [comment]
@darthmolen Please fork/clone the repo again or sync to the latest version 😄 

This was fixed in a recent push.

![image](https://user-images.githubusercontent.com/1633401/53746976-224c1880-3e57-11e9-99c5-b72d7de9bba3.png)
