### ISSUE TITLE
Microsoft.Azure.Cosmos.ServiceInterop.dll could not be found when running an Asp.Net application in IIS

### ISSUE THREAD

**Issue by FrankGagnon** [Azure/azure-cosmos-dotnet-v3#526]
**Describe the bug**
I am using the SDK in an Asp.Net application hosted in IIS. When making a query, I get "Unable to load DLL 'Microsoft.Azure.Cosmos.ServiceInterop.dll': The specified module could not be found." .

I think the issue is the same as the one described here : https://stackoverflow.com/questions/344608/unmanaged-dlls-fail-to-load-on-asp-net-server/4598747

How can I use the SDK in IIS without modifying the PATH?

**Environment summary**
SDK Version: 3.0.0.19 preview
Windows Server 2016
IIS 10
.Net Framework 4.7.2
Build targets Any CPU

**Comment by kirankumarkolli** [comment]
@ausfeldt please take a look at the stackoverflow. 
Seems IIS path look-up is different.

**Comment by FrankGagnon** [comment]
Using the GA version (as well as the version listed above) I also have the following problem : 

Project A is using the Microsoft.Azure.Cosmos nuget package.
Project B is referencing ProjectA.dll
Microsoft.Azure.Cosmos.ServiceInterop.dll is never copied to Project B's bin. 

I makes it pretty annoying when Microsoft.Azure.Cosmos is used in an intermediary library referenced by multiple applications.

**Comment by kirankumarkolli** [comment]
@FrankGagnon thanks for the repro. 
@ausfeldt  please investigate.

**Comment by FrankGagnon** [comment]
No problem, thanks for being so responsive! 

Forgot to mention that the same happens for this reference : "Cosmos.CRTCompat.dll"

**Comment by ausfeldt** [comment]
Is Microsoft.Azure.Cosmos.ServiceInterop.dll along side Microsoft.Azure.Cosmos.Client.dll in the bin/output directory on the host machine?

**Comment by FrankGagnon** [comment]
Yes, Microsoft.Azure.Cosmos.ServiceInterop.dll is along side Microsoft.Azure.Cosmos.Client.dll in the bin. Adding the bin to the system PATH fixes the issue so the right version is there, it's simply not found by IIS. I'm using the latest version of the SDK.

**Comment by FrankGagnon** [comment]
Found the issue. After much investigation with fusion logs and procmon, it seems like IIS is unable to load unmanaged dependencies from a remote machine (from a UNC path). Our IIS site is setup to load the files from a remote server so it didn't work. 

Adding the UNC path to the system PATH fixed the issue for some reason. Copying the remote folder locally on the machine running IIS also fixed the issue.
