### ISSUE TITLE
In GatewayMode, reading item from non-existing database/container, ErrorMessage is null

### ISSUE THREAD

**Issue by donghexu** [Azure/azure-cosmos-dotnet-v3#536]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When using GatewayMode to read an item from non-existing database/container, the ErrorMessage is null. However in DirectMode, ErrorMessage is correct. 

**To Reproduce**
CosmosClientBuilder builder = new CosmosClientBuilder([endpoint], [key]);
CosmosClient cosmosClient = builder.WithConnectionModeGateway().Build();

and then read item. The ErrorMessage is null.

**Expected behavior**
ErrorMessage should not be null, should contain error information, just like Direct mode. 

**Environment summary**
SDK Version: 3.0.0.19-preview
OS Version (e.g. Windows, Linux, MacOSX): any

**Comment by simplynaveen20** [comment]
Can you please paste the error stack

**Comment by donghexu** [comment]
Hi @simplynaveen20, there isn't such stack trace here. The operation is ReadItem against non-existence database or container, and with Direct Mode, you will get ErrorMessage in ResponseMessage, however with Gateway Mode, the ErrorMessage is null. But I do see error response from Fiddler.

**Comment by kirankumarkolli** [comment]
@ausfeldt is the response from service/gateway or its SDK manufactured one?
