### ISSUE TITLE
Add a ContinuationToken in the 'GetItemLinqQueryable' method

### ISSUE THREAD

**Issue by miiitch** [Azure/azure-cosmos-dotnet-v3#537]
As in the previous SDK I'd like to use continuation tokens with Linq queries. Right now I can't use a continuation token because the method is missing.

**Comment by adrianknight89** [comment]
I have the same issue. I can't migrate away from V2 because of this.

**Comment by simplynaveen20** [comment]
Can you please paste the code snippet you were using in V2 , it will help us to finalize it on V3 ?

**Comment by adrianknight89** [comment]
If you look [here](https://auth0.com/blog/documentdb-with-aspnetcore/), I do something similar where I get `ResponseContinuation` from the query result and add it to `FeedOptions` for the next fetch.

**Comment by jriouxrandstadca** [comment]
I see that it is merged. Any idea when it will be released?

**Comment by simplynaveen20** [comment]
> I see that it is merged. Any idea when it will be released?

Release is scheduled for next week
