### ISSUE TITLE
How can I create a database with provisioned throughput?

### ISSUE THREAD

**Issue by adrianknight89** [Azure/azure-cosmos-dotnet-v3#539]
I don't see a way to create a database with shared throughput in the new SDK.

`public virtual Task<DatabaseResponse> CreateDatabaseIfNotExistsAsync(string id, int? throughput = null, RequestOptions requestOptions = null, CancellationToken cancellationToken = default);`

`RequestOptions` doesn't have a property for this purpose. Is it currently possible to create a new database with shared throughput?

![Untitled](https://user-images.githubusercontent.com/16855542/61194669-99f14600-a688-11e9-9c36-e5600a9a4cbe.png)

**Comment by j82w** [comment]
@adrianknight89 it's the 2nd parameter. Am I missing something?

public virtual Task<DatabaseResponse> CreateDatabaseIfNotExistsAsync(
string id, 
**int? throughput = null,** 
RequestOptions requestOptions = null, 
CancellationToken cancellationToken = default);

**Comment by adrianknight89** [comment]
@j82w Please do not close this right away. The second parameter seems to be mapping to the second textbox in the image, but for the checkbox, there needs to be another parameter based on what I observed in my test yesterday. Setting the throughput does not make it shared between containers. I'll test this again today.

**Comment by j82w** [comment]
@adrianknight89 what makes you think the throughput is not shared?

**Comment by adrianknight89** [comment]
On the portal, if I create a new database without checking the above checkbox, then I get something like this:

![1](https://user-images.githubusercontent.com/16855542/61222297-08adbe00-a6e0-11e9-802b-4df2570ab815.png)

If I check the checkbox, I get this:

![2](https://user-images.githubusercontent.com/16855542/61222631-b1f4b400-a6e0-11e9-9379-60d77c43f0b3.png)

When I executed `CreateDatabaseIfNotExistsAsync` with an explicit throughput, I ended up creating a database that looked like the first one. Every subsequent container then defaulted to 400 throughput because the database did not set a throughput of its own.

Let me verify this one more time tonight.

**Comment by simplynaveen20** [comment]
Can you please make sure DB doesn't exist with database id  using in  CreateDatabaseIfNotExistsAsync.
In that case it will just return the existing Database instance with original setting.
We verified this api and checked on portal with below screen shot, which is correctly showing the option to scale the throughput .

![image](https://user-images.githubusercontent.com/43345335/61242308-5ee82480-a713-11e9-8d64-7cbbb8ba0a8d.png)

**Comment by kirankumarkolli** [comment]
Contract is not very explicit and its tracked as a separate issue #549

**Comment by adrianknight89** [comment]
Tested this again and it seems to be working. I'm not sure what was happening last night. I think the issue might have been as described in @simplynaveen20's post.
