### ISSUE TITLE
Connecting with Change Feed Processor throws DocumentClientException: SQl Api is not supported for this database account 

### ISSUE THREAD

**Issue by whatisthejava** [Azure/azure-cosmos-dotnet-v3#543]
Hi

I have three cosmos databases created via ARM template 

I created one two weeks ago and the other two a week ago 

The regions are the same and from what i can tell all three cosmos are identical.

Their API is Mongo 

When I try to connect with the ChangeFeedProcessor I get the following error 

Microsoft.Azure.Documents.DocumentClientException
  HResult=0x80131500
  Message=Sql api is not supported for this database account

To connect I am using 

         return new DocumentCollectionInfo
            {
                Uri = new Uri("https://<dbname>.documents.azure.com:443/"),
                MasterKey = "Master Key",
                DatabaseName = "dbname",
                CollectionName = collectionName
            };

Is there any reason why my new databases are not allowing this and my older one is.

**Comment by j82w** [comment]
I'm closing this issue since it a on the v2 SDK. Can you please open an issue here on the [v2 SDK repo](https://github.com/Azure/azure-cosmos-dotnet-v2).

**Comment by sebastian-smith** [comment]
Hi 

> Hi
> 
> I have three cosmos databases created via ARM template
> 
> I created one two weeks ago and the other two a week ago
> 
> The regions are the same and from what i can tell all three cosmos are identical.
> 
> Their API is Mongo
> 
> When I try to connect with the ChangeFeedProcessor I get the following error
> 
> Microsoft.Azure.Documents.DocumentClientException
> HResult=0x80131500
> Message=Sql api is not supported for this database account
> 
> To connect I am using
> 
> ```
>      return new DocumentCollectionInfo
>         {
>             Uri = new Uri("https://<dbname>.documents.azure.com:443/"),
>             MasterKey = "Master Key",
>             DatabaseName = "dbname",
>             CollectionName = collectionName
>         };
> ```
> 
> Is there any reason why my new databases are not allowing this and my older one is.

Did you ever find a solution for this? facing the same error at the moment.

**Comment by whatisthejava** [comment]
yes, Azure turned the feature off

there is a new version of the lib getting released which will allow it in September

**Comment by brudnyhenry** [comment]
Hi,
Is there any update on this ? I don't see this feature being enabled and it's already October
