### ISSUE TITLE
DocumentClient Linq to SQL

### ISSUE THREAD

**Issue by jfoshee** [Azure/azure-cosmos-dotnet-v3#55]
I'm struggling to create a query...  I want to use Linq extension methods (e.g. `.Where()`, `.Select()`) but it seems this API was removed.  However documentation seems to not acknowledge this in a straightforward way, nor give an indication as to the plan...  

If I look at docs for the v2 API it says it is deprecated.  v3 is in preview and obviously incomplete.  Where does that leave me?

**Comment by j82w** [comment]
Where do you see that it is deprecated in the v2 API?

Adding linq support in V3 is a significant amount of work, and we are currently working on it. It is listed in the (GA project)[https://github.com/Azure/azure-cosmos-dotnet-v3/projects/2].  For the v3 API you can write a basic SQL query like in the (samples)[https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs]

**Comment by jfoshee** [comment]
Visiting <https://docs.microsoft.com/en-us/previous-versions/azure/dn850285(v=azure.100)> (linked to from [Cosmos .NET Samples]) I read the banner:

> We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported.

So, "deprecated" was an imprecise word on my part. The impression is that v2 is not a good choice for new development. Meanwhile v3 is in progress, and it is not clear what its state is.  (As you probably know the release notes are empty).  

Thanks for providing the reference to the project page; that is cool. That is the first reference I've seen to that.

I would ask not that your team "code faster", but "communicate better".

[Cosmos .NET Samples]: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-dotnet-samples

**Comment by j82w** [comment]
v2 is still fully supported with linq. That banner appears to be referencing the website where the documentation is hosted, and not the product.

For now use v2 SDK for production
Use the v3 SDK for providing feedback on the new API and features.

**Comment by vip32** [comment]
but will V3 get linq support?

**Comment by j82w** [comment]
V3 will get linq support. It's listed in the notes of the [GA Project](https://github.com/Azure/azure-cosmos-dotnet-v3/projects/2). We are working on getting full query support with integration into the pipeline first.
