### ISSUE TITLE
serializerSettings with v3 client

### ISSUE THREAD

**Issue by coffeymatt** [Azure/azure-cosmos-dotnet-v3#550]
In the previous v2 version I could pass serializer settings to the client. With the new v3 client, it's not so clear how to do that

So I could do something like: 

```
var serializerSettings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };

this.client = new DocumentClient(new Uri(this.options.CosmosDbEndPoint), this.options.CosmosDbKey, serializerSettings: serializerSettings);
```
How do I do this with v3? I've had a look at the docs and the API, I can see an options object with a serializer parameter on it, but I can't figure out how I could configure it as above?

**Comment by j82w** [comment]
@coffeymatt we removed settings and added the ability to have completely custom serializers in v3. 

[CosmosClientOptions.Serializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/63de89ef640c4bb83dbb37f40ffb51bda7d5b8a5/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L161)

This is the SDK's default [serializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/CosmosJsonSerializerCore.cs).

**Comment by coffeymatt** [comment]
@j82w This seems like one step forward, two steps backward. Should you not provide some mechanism to provide settings the default serializer?

Otherwise what I can do with one line of code above now will require me to create a custom serializer.

**Comment by j82w** [comment]
That's a good point. I don't see any reason that can't be supported.  I created an [issue](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/551) to support it.
