### ISSUE TITLE
Next preview release time frame?

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#56]
Looks like there have been some updates to the source code here. Any hints as to the time frame for the next preview NuGet package?

**Comment by jarrettv** [comment]
saw a recent video about this library and there are no new previews since november?

**Comment by j82w** [comment]
We are actively working on releasing a new version. It's taking a while to move all of our build processes to GitHub.

**Comment by ealsur** [comment]
@jackbond We are moving our dev process to GitHub as we speak and the source at this moment is updated, finishing up the required pipelining.

**Comment by mpaul31** [comment]
awesome can't wait!

**Comment by kentcb** [comment]
I don't want to be "that guy", but can we have an update please? This seems to be taking quite a long time...

**Comment by j82w** [comment]
A new version was published: https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.0.0.9-preview
