### ISSUE TITLE
Session Consistency isn't honored

### ISSUE THREAD

**Issue by donghexu** [Azure/azure-cosmos-dotnet-v3#565]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When I do create item and then upsert item, with ItemRequestOptions as Session Consistency, and provide the session toke nfrom insert result to upsert operation, the returned sesson token is different. 

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

1. Do item creation with ItemRequestOptions with ConsistencyLevel.Session, get the returned session token. 
2. Do item upsert with ItemRequestOptions with ConsistencyLevel.Session, and the session token from step 1.
3. The returned session token from step 2 is changed.

**Expected behavior**
Session consistency should make sure the session token consistent. 

**Actual behavior**
Provide a description of the actual behavior observed. 
the session token from each item operation are different, with Session Consistency

**Environment summary**
SDK Version: GA 3.0.0
OS Version (e.g. Windows, Linux, MacOSX): Windows.

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
I think you have some confusion around session token. Session token is like a LSN. It basically an int representing a position in the logs. So every operation the session token increases representing those new operation performed on the database. 

https://stackoverflow.com/questions/50500464/managing-cosmosdb-session-consistency-levels-with-session-token-in-web-environme
