### ISSUE TITLE
Item Query doesn't send out request and return BadRequest with "Message: " as ErrorMessage

### ISSUE THREAD

**Issue by donghexu** [Azure/azure-cosmos-dotnet-v3#566]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**

In our code, we use below code to do query:
     Container container = this.cosmosClient.GetDatabase(TableInteropConstants.TableDatabaseName).GetContainer(containerName);
            FeedIterator iterator = container.GetItemQueryStreamIterator(
                queryDefinition: sqlQueryDefinition,
                continuationToken: continuationToken,
                requestOptions: requestOptions);

            return iterator.ReadNextAsync(cancellationToken: cancellationToken);

The query statement is valid: "select * from entity where (entity['$pk'] = \"tables_batch_1\") ", doing cross partition query.
The RequestOptions is default with MaxConcurrency -1 and MaxItemCount 1000. 

When running the code, it didn’t send out query request after Get Container requests. From Fiddler I can only see one request.

The ResponseMessage is BadRequest with ErrorMessage => "Message: "

However in my separate project, I run the exactly same code above, I can do item query and get response. From Fidder I can see 4 correct requests.

From Cosmos Client codebase, I see the “Message: ” is set at QueryPartitionProvider: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Query/QueryPartitionProvider.cs#L232.

I also checked that the Microsoft.Azure.Cosmos.ServiceInterop.dll is in our output folder.

**To Reproduce**
We have a project A depending on CosmosClient sdk, and project B reference to project A. Run code on project B with query item operation, it produce the BadRequest result. 

**Environment summary**
SDK Version: 3.0.0 GA
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Comment by j82w** [comment]
This seems to be a bug caused by using the wrong service interop version. It causes the service interop to throw a null ref exception which isn't properly handled.

@donghexu can you verify that the size and digital signature in the file properties are the same on both versions?

**Comment by donghexu** [comment]
Hi @j82w , yes the files are same as inside Microsoft.Azure.Cosmos 3.0.0, size is 4756kb.

**Comment by j82w** [comment]
I'm able to run the same exact query in gateway mode and the test passed fine. The only time I've been able to repo this is with the incorrect service interop version.

**Comment by j82w** [comment]
This issue was caused by ServiceInterop version being incorrect. The test folder had the wrong version.
