### ISSUE TITLE
Add support to configure an HTTP proxy

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#580]
Add a HttpHandler to the client options so the user can configure a HTTP proxy

**Comment by kirankumarkolli** [comment]
Are HTTP proxies used in production environment or only for development?

Few options for HTTP proxy support are
- Customizable [IWebProxy](https://docs.microsoft.com/en-us/dotnet/api/system.net.iwebproxy?view=netstandard-2.0)
- HttpHandler (similar to V2): Some ambiguity around V3 handler
- V3 proxy handler (ex: CosmosHttpProxyHandler): Kind of sugar coated V2 version

IWebProxy is basic required contract/abstraction. Handler are nice wrappers around proxies. 
Will just IWebProxy based contract suffice?

**Comment by j82w** [comment]
The other thing that the HttpHandler allowed was disabling SSL verification which is needed for linux environments.
