### ISSUE TITLE
CreateDatabaseIfNotExistsAsync fails with "Sql api is not supported for this database" response

### ISSUE THREAD

**Issue by aristovg** [Azure/azure-cosmos-dotnet-v3#582]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
`CreateDatabaseIfNotExistsAsync` fails with `Forbidden - Sql api is not supported for this database` for one of our Mongo API database accounts.  

**To Reproduce**
Just the basic usage: 
```csharp
using (var client = new CosmosClient(_configurationOptions.AccountEndpoint, _configurationOptions.AccountKey))
{
    var databaseResponse = await client.CreateDatabaseIfNotExistsAsync($"{databaseName}", throughput);

    return databaseResponse;
}
```

The call made with V2 SDK succeeds with the same variables: 
```csharp
            var c = new DocumentClient(new Uri(_configurationOptions.AccountEndpoint), _configurationOptions.AccountKey);
            await c.CreateDatabaseIfNotExistsAsync(new Database()
                {
                    Id = databaseName
                }, new RequestOptions()
                {
                    OfferThroughput = 600
                }
            );
```

**Expected behavior**
The database is created, no exceptions are thrown.

**Actual behavior**
The exception is thrown. 

**Environment summary**
SDK Version: 3.0.0
OS Version: Win 10 1809 (17763.503)

**Additional context**
```
Microsoft.Azure.Cosmos.CosmosException
  HResult=0x80131500
  Message=Response status code does not indicate success: 403 Substatus: 0 Reason: (Sql api is not supported for this database accountActivityId: d1096b10-f9b3-46e9-94f0-2b806ffa8d3c, Microsoft.Azure.Documents.Common/2.4.0.0, RequestStartTime: 2019-07-23T08:46:47.9635759Z, RequestEndTime: 2019-07-23T08:46:47.9635759Z, Number of regions attempted: 1AddressResolution - StartTime: 2019-07-23T08:46:48.0589095Z, EndTime: 9999-12-31T23:59:59.9999999, TargetEndpoint: https://[removed-accountname]-eastus2.documents.azure.com//addresses/?$resolveFor=dbs&$filter=protocol eq rntbd, Windows/10.0.17763 cosmos-netstandard-sdk/3.0.0).
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.ToObjectInternal[T](ResponseMessage cosmosResponseMessage, CosmosSerializer jsonSerializer)
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.<>c__DisplayClass6_0.<CreateDatabaseResponseAsync>b__0(ResponseMessage cosmosResponseMessage)
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.<ProcessMessageAsync>d__12`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.CosmosClient.<CreateDatabaseIfNotExistsAsync>d__40.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Example.Common.DocumentDB.CosmosDb.<CreateDatabaseIfNotExists>d__3.MoveNext() in C:\Example\Example.Common.DocumentDB\CosmosDb.cs:line 48
```

**Comment by j82w** [comment]
@aristovg the .NET SDK is only for the SQL API. Check out the [Mongo quckstart](https://docs.microsoft.com/en-us/azure/cosmos-db/create-mongodb-dotnet).

**Comment by aristovg** [comment]
@j82w The problem that v3 SDK still works for other Database Account (also MongoDb). Not sure which details of the successful request are helpful, but activity ID is `5f293026-c48f-4dbd-bed3-b46f71f438db`. 

Also, according to [Provision throughput using .NET SDK](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-provision-database-throughput#provision-throughput-using-net-sdk) it should work for all APIs? 

If SDK is not supposed to work for all APIs, is there a way to create a mondo database with provisioned throughput programmatically?

**Comment by ealsur** [comment]
See https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-custom-commands#create-database

    {
      customAction: "CreateDatabase",
      offerThroughput: <Throughput that you want to provision on the database>
    }
