### ISSUE TITLE
Enrich user-agent with runtime context

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#586]
Enrich user agent with runtime context (Fx vs core, Win vs Linux etc...)

**Comment by ealsur** [comment]
Suggested format is `{SDK-id}-{process runtime}-{process-arch}-{host-rutnime}-{host-arch}`

**Comment by kirankumarkolli** [comment]
{SDK-id}: Should include the name, version, direct version
