### ISSUE TITLE
Delete items by predicate

### ISSUE THREAD

**Issue by nechesa** [Azure/azure-cosmos-dotnet-v3#596]
There is no way to remove items from container by predicate. It issue was resolver by used prev version by with Document class and its properties SelfLink with DeleteDocumentAsync. But is any opportunity to do it in new version. I can't find something similar in newest version. 
Thank you for attention.

**Comment by nechesa** [comment]
Issue resolved like this, it's not the best and elegant way. I hope you will add support for removing items by predicate

var query = container.GetItemLinqQueryable<T>(requestOptions: new QueryRequestOptions { MaxItemCount = -1 })
                    .Where(predicate).ToFeedIterator();

                while (query.HasMoreResults)
                {
                    FeedResponse<T> results = await query.ReadNextAsync(cancellationToken);
                    foreach (var item in results)
                    {
                        await container.DeleteItemAsync<T>(item.Id, new PartitionKey(item.Id));
                    }

                }

**Comment by j82w** [comment]
@nechesa can you provide an example of how it worked in v2?

**Comment by nechesa** [comment]
IDocumentQuery<T> query = _client.CreateDocumentQuery<T>(
                        UriFactory.CreateDocumentCollectionUri(_databaseId, collectionId),
                        feedOptions)
                        .Where(predicate)
                        .AsDocumentQuery();

                List<Task> deleteTasks = new List<Task>();
                while (query.HasMoreResults)
                {
                    FeedResponse<dynamic> results = await ExecuteWithRetries(() => query.ExecuteNextAsync(), cancellationToken);

                    foreach (Document item in results)
                    {
                        T model = JsonConvert.DeserializeObject<T>(item.ToString());
                        deleteTasks.Add(
                           ExecuteWithRetries(
                               () =>
                               {
                                   var requestOptions = new RequestOptions();

                                   // set partition key if exists
                                   if (CosmosCollectionsSetting.IsCollectionHasPartitionKey(collectionId))
                                   {
                                       requestOptions.PartitionKey = new PartitionKey(item.Id);
                                   }


                                   return _client.DeleteDocumentAsync(item.SelfLink, requestOptions);
                               },
                               cancellationToken
                           )
                       );
                    }
                }

**Comment by nechesa** [comment]
Hello  @j82w  so, what we can expect with this issues ?  Thank you for attention.

**Comment by j82w** [comment]
Hi @nechesa, 

Does this work for your scenario?

```
 FeedIterator<string> feedIterator = this.Container.GetItemLinqQueryable<T>()
                .Where(predicate)
                .Select(x => x.id).ToFeedIterator<string>();

            while (feedIterator.HasMoreResults)
            {
                FeedResponse<string> results = await feedIterator.ReadNextAsync();
                foreach (var id in results)
                {
                    deleteTasks.Add(
                        this.Container.DeleteItemAsync<T>(id, new Cosmos.PartitionKey(id)));
                }
            }
```

**Comment by nechesa** [comment]
Thank you, I'll check it tomorrow and let you know.

**Comment by j82w** [comment]
Depending on your predicate you might also be able to use [stored procedures](https://github.com/Azure/azure-cosmosdb-js-server/blob/master/samples/stored-procedures/bulkDelete.js).

**Comment by nechesa** [comment]
Thank you for helping @j82w  but code you send is buggy
.Select(x => x.id)   we don't know have T.id or not. 
Do you have any other option instead procedure?

**Comment by j82w** [comment]
Every object in Cosmos has an "id" property. It's a required field. I have a few ideas, but I want to validate them first. I'll post an update later today after I get a chance to do some testing.

**Comment by j82w** [comment]
Here is my current solution. I validated that it works. A solution closer to what you currently have will be possible after PR [#604](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/604) is merged.

```
                Expression<Func<Test, bool>> func = (item) => item.id != "test5";
                await DeleteItemsHelper<Test>(container, func);
                Console.WriteLine("delete item helper");
            }
        }

        private class Test
        {
            public string id { get; }
            public int pk { get; }
            public string test { get; }
        }

private interface ItemIdInterface
        {
            string id { get; }
        }

        public async Task DeleteItemsHelper<T>(Container container, Expression<Func<T, bool>> predicate)
        {
            List<Task> deleteTasks = new List<Task>();

// ItemIdInterface does not need to implement type T. It is only use to evaluate the field name "id"
            IQueryable<string> test = container.GetItemLinqQueryable<T>()
                .Where(predicate)
                .Select(item => ((ItemIdInterface)item).id);

            FeedIterator<string> feedIterator = test.ToFeedIterator();
            while (feedIterator.HasMoreResults)
            {
                Microsoft.Azure.Cosmos.FeedResponse<string> results = await feedIterator.ReadNextAsync();
                foreach (var id in results)
                {
                    deleteTasks.Add(container.DeleteItemAsync<dynamic>(id, new Microsoft.Azure.Cosmos.PartitionKey(id)));
                }
            }

            Task.WaitAll(deleteTasks.ToArray());
        }
```

**Comment by nechesa** [comment]
Thank you

**Comment by vip32** [comment]
Id as a partitionkey value, really? that's a partition per key, does not scale

**Comment by j82w** [comment]
@vip32 there is valid scenarios where users don't need to scale and that the data set will always be small. The example can be modified to return multiple values for both an id and a partition key value.
