### ISSUE TITLE
CosmosContainerBuilder with public constructor

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#599]
CosmosContainerBuilder constructor should be internal

**Comment by j82w** [comment]
Should we add a public constructor that takes in name and partition key path. Then on build it takes in the database object?

**Comment by ealsur** [comment]
That would mean that we need to have a different Build method?

**Comment by j82w** [comment]
I guess for now we can just make it internal until we get user request for something. 

I think the better experience would have been the Database having an overload to take a ContainerBuilder as a parameter.
