### ISSUE TITLE
How the old OpenAsync has been handled

### ISSUE THREAD

**Issue by Ponant** [Azure/azure-cosmos-dotnet-v3#6]
Hi Team,
First of I back up what others have said that it is super super cool that you open source the project! :)
DocumentClien.OpenAsync() has been an important feature that needed to be handled properly when using dependency injection in .Net Core. But it seems to have disappeared. Could you explain a bit how that is handled now?

**Comment by kirankumarkolli** [comment]
@Ponant in what scenarios are you using DocumentClient.OpenAsync()?

Doing any operation (Read any document etc...) on CosmosClient ensures OpenAsync(), so it can be leveraged as work-around meanwhile.

**Comment by mpaul31** [comment]
we also use this method to perform our health endpoints.

**Comment by kirankumarkolli** [comment]
DocumentClient OpenAsync() name is little mis-leading. Its role is client initialization only. Once initialized calling again is no-op. Please don't use it for monitoring. 

OpenAsync() is an optional initialization. If not called will happen part of first API call. 
Typically its called explicitly to ensure first API call latency is not high.

CosmosClient does lazy initialization on first request. 
Start-up code can do a dummy API call and ensure initialization happens.
