### ISSUE TITLE
PartitionKey extracted from document doesn't match the one specified in the header

### ISSUE THREAD

**Issue by jedmonsanto** [Azure/azure-cosmos-dotnet-v3#602]
Im using the cosmos v3, tried CreateItemAsync and it throws an error: **PartitionKey extracted from document doesn't match the one specified in the header**

![image](https://user-images.githubusercontent.com/23548643/61917066-ee949b00-af7d-11e9-8fed-8d51085d9760.png)

I wonder maybe the signature is different from the documentation, in **Microsoft.Azure.Cosmos namespace**, the partitionkey is of type object but in the documentation its different, please see below: 

![image](https://user-images.githubusercontent.com/23548643/61917184-6c58a680-af7e-11e9-9a42-1da11831e492.png)

Please see below configuration in my end:

App settings:
![image](https://user-images.githubusercontent.com/23548643/61917222-a5911680-af7e-11e9-9254-7596243fb0e2.png)

and here's my local setup created:
![image](https://user-images.githubusercontent.com/23548643/61917258-ca858980-af7e-11e9-887b-9407d46d5e8a.png)

**Comment by j82w** [comment]
Can you try upgrading to the 3.0.0 GA nuget? Create item now take a PartitionKey object instead of just and object.

**Comment by j82w** [comment]
Since this is not the GA nuget, and there has been no response I'm closing this issue. Please open a new issue if this is still a problem in the GA nuget.

**Comment by jedmonsanto** [comment]
Hi @j82w sorry for the late reply, the Version of my Cosmos is 3.0.0.9-preview

**Comment by j82w** [comment]
@jedmonsanto that is a very old version that could very likely have a bug. Can you please try using the new [3.1.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos) nuget?

**Comment by jedmonsanto** [comment]
I updated the version yesterday. CosmosDatabase and CosmosContainers are no longer present, Can you please direct me where can see the documentation relating to this v3.1.0

**Comment by j82w** [comment]
It was renamed to just Database, Container. You can look at the [samples](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage), and the [docs].(https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos?view=azure-dotnet)

**Comment by vip32** [comment]
docs here
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container?view=azure-dotnet
