### ISSUE TITLE
Allow StartFromBeginning to be set

### ISSUE THREAD

**Issue by Zenuka** [Azure/azure-cosmos-dotnet-v3#603]
Unless I'm mistaking or missing something obvious, I'm not able to set `StartFromBeginning`. The `ChangeFeedProcessorOptions` class is internal and the extension method `ChangeFeedProcessorBuilder.WithStartFromBeginning` is also internal. I did not find another way to access this from within my application.

**Comment by ealsur** [comment]
You should be able to achieve the same result by using WithStartTime with DateTime.Min.
