### ISSUE TITLE
Provide a way of fetching container size and count

### ISSUE THREAD

**Issue by asos-leonardopasta** [Azure/azure-cosmos-dotnet-v3#606]
**Is your feature request related to a problem? Please describe.**
The recommended way to get the collection size and count on SDK v2 is via PopulateQuotaInfo / CurrentResourceQuotaUsage (https://github.com/Azure/azure-cosmos-dotnet-v2/blob/master/samples/partition-stats/Program.cs#L103)
I can't see any way of getting those two metrics in SDKv3 containers, but I can see that we can still set PopulateQuotaInfo and the value is returned, except CurrentResourceQuotaUsage is not public.

**Comment by j82w** [comment]
In v3 there is access to all the headers on the response. This could be promoted on to ContainerResponse to make it easier to access.  Here is a sample on how to access it. 

```
using (CosmosClient cosmosClient = new CosmosClient(
                 account,
                 key))
            {
                Database db = await cosmosClient.CreateDatabaseIfNotExistsAsync("PopulateUsageDbTest");
                Container container = await db.CreateContainerIfNotExistsAsync("PopulateUsage", "/id");

                ContainerRequestOptions containerRequestOptions = new ContainerRequestOptions()
                {
                    PopulateQuotaInfo = true
                };

                ContainerResponse containerResponse = await container.ReadContainerAsync(containerRequestOptions);
                string resourceUsage = containerResponse.Headers.Get("x-ms-resource-usage");
                string resourceQuota = containerResponse.Headers.Get("x-ms-resource-quota");
            }
```

**Comment by asos-leonardopasta** [comment]
Thanks.
I would imagine that promoting it would make the discoverability easier (and easier for developers used to v2), but adding that into the samples and/or [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.containerrequestoptions.populatequotainfo?view=azure-dotnet) (there is nothing in PopolateQuotaInfo page telling where the data will show up) would be fine as well.

**Comment by j82w** [comment]
One of the reasons it didn't get promoted is we wanted more user feedback on how people are using. Is exposing just a string enough or does it need to be parsed into a C# object?

**Comment by asos-leonardopasta** [comment]
Personally, I always end up splitting it into a collection. But it is trivial to do, so if there are any reason not to do it (like performance), I'm fine with it as a string.

**Comment by j82w** [comment]
We think the correct way to expose it is a typed object. There is performance concerns around deserializing it. We don't want to expose a string if we have the object. Until we get more user requests we are not going to promote it since it accessible through the headers. I will add an example to the request option on how to access it for now.
