### ISSUE TITLE
Cannot run triggers because ItemRequestOptions.PreTriggers and PostTriggers are internal

### ISSUE THREAD

**Issue by ravriel** [Azure/azure-cosmos-dotnet-v3#607]
**Describe the bug**
ItemRequestOptions.PreTriggers and ItemRequestOptions.PostTriggers are internal and cannot be specified with C# SDK.

**To Reproduce**

**Expected behavior**
Expected to be able run triggers as documented.

**Actual behavior**
Cannot run triggers.

**Environment summary**
SDK Version: Nuget Microsoft.Azure.Cosmos 3.0.0
OS Version: Windows

**Comment by j82w** [comment]
This is already [fixed](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/557). Check out the [changelong](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md). There should be a release this week with the fix.
