### ISSUE TITLE
GetItemLinqQueryable throwing "Response status code does not indicate success: 400 Substatus: 0 Reason: (Message: {"Errors":["x-ms-documentdb-partitionkey header cannot be specified for this request"]}"

### ISSUE THREAD

**Issue by coffeymatt** [Azure/azure-cosmos-dotnet-v3#610]
**Describe the bug**

I previously reported an issue here:

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/555

Unfortunately it seems the fix that has been merged has not worked and I'm seeing a different error message attempting the same thing. If I try and query for items without where or select conditions, I get an error.

**To Reproduce**

Rough example code:
```
var partition = "example";
var options = new QueryRequestOptions
{
         PartitionKey = new PartitionKey(partition)
};

var query = this.container.GetItemLinqQueryable<ExampleObject>(true, requestOptions: options).AsQueryable();

var allObjects = query.ToList();

```
**Expected behavior**

I should get a list of Example object.

**Actual behavior**

It throws an error:

> Response status code does not indicate success: 400 Substatus: 0 Reason: (Message: {"Errors":["x-ms-documentdb-partitionkey header cannot be specified for this request"]}ActivityId: 869f5188-a259-494d-a9d6-7604fa4ea5d2, Request URI: /apps/c8568c7b-6923-431d-8862-9f1b9c78f80a/services/b32cfe7c-3cb1-484a-8868-5ca172efeb8e/partitions/d0f00795-e827-422f-a1e0-ca9b93ca4e76/replicas/132079474666377990s/, RequestStats: RequestStartTime: 2019-07-30T13:50:05.3769613Z, RequestEndTime: 2019-07-30T13:50:05.4826153Z, Number of regions attempted: 1ResponseTime: 2019-07-30T13:50:05.4826153Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd15.documents.azure.com:14026/apps/c8568c7b-6923-431d-8862-9f1b9c78f80a/services/b32cfe7c-3cb1-484a-8868-5ca172efeb8e/partitions/d0f00795-e827-422f-a1e0-ca9b93ca4e76/replicas/132079474666377990s/, LSN: 48373, GlobalCommittedLsn: 48372, PartitionKeyRangeId: , IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: -1#48373, UsingLocalLSN: True, TransportException: null, ResourceType: Document, OperationType: ReadFeed, SDK: Windows/10.0.18362 cosmos-netstandard-sdk/3.1.3).

If I user the previous work around, e.g. add 'query.Select(i => i).ToList()' it works fine.

**Environment summary**
SDK Version: 3.0.1
OS Version Windows 10

**Additional context**
Related PR:

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/561

**Comment by j82w** [comment]
Hi @coffeymatt ,

I'm sorry I missed this with the other fix. I thought there was test running with read feed and partition key values, but there isn't any test for that scenario. I sent out a [PR ](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/612) with the fix and additional tests to make sure this doesn't happen again.

**Comment by coffeymatt** [comment]
@j82w No worries, I'm impressed with how quick you guys turn around fixes, thanks for your help.
