### ISSUE TITLE
Decimal points on GetItemQueryIterator and GetItemLinqQueryable

### ISSUE THREAD

**Issue by devcrp** [Azure/azure-cosmos-dotnet-v3#613]
**Describe the bug**
The methods GetItemQueryIterator and GetItemLinqQueryable do not parse the decimal value correctly while the ReadItemAsync method does.

**To Reproduce**
I've got this document stored in cosmosDB.
```
{
    "id": "12345",
    "value": 1.5
}
```

Then, if I go and call this method (being T my custom class), I get the expected result, an object with the decimal value properly populated:
```
container.ReadItemAsync<T>(partitionKey: new PartitionKey("12345"), id: "12345");
```

But, if I want to get a list of documents and use instruction like this, I get a 15 for the 'value' field, instead of 1.5

```
FeedIterator<T> iterator = container.GetItemQueryIterator<T>("SELECT * FROM mycontainer c where c.id in ('12345')");

while (iterator.HasMoreResults)
{
    result.AddRange((await iterator.ReadNextAsync()));
}
```

**Expected behavior**
The decimal point is preserved when listing documents.

**Actual behavior**
The decimal point is lost, so a number like 1.5 is parsed to 15.

**Comment by j82w** [comment]
@devcrp any chance you are using 3.0.0? There is a bug in 3.0.0 where query was using the local culture when parsing. It is fixed in 3.1.0.

**Comment by devcrp** [comment]
Right, I was using 3.0.0, I didn't notice the new version. Thank you!

**Comment by j82w** [comment]
Please reopen it if you still hit it in 3.1.0
