### ISSUE TITLE
Method CreateDatabaseIfNotExistsAsync throws ArgumentNullException("stringHMACSHA256Helper")

### ISSUE THREAD

**Issue by msciborski** [Azure/azure-cosmos-dotnet-v3#617]
**Describe the bug**
Hi, when I want to create new datatabase with `CreateDatabaseIfNotExistAsync,` I'm getting `ArgumentNullException("stringHMACSHA256Helper").`

**To Reproduce**
```
                Client = new Microsoft.Azure.Cosmos.CosmosClient(_connectionString);

                Database = await Client.CreateDatabaseIfNotExistsAsync("TestDb");

                Container = await  Database.CreateContainerIfNotExistsAsync("TestContainer", "/id");
```

**Expected behavior**
Create database and return `DatabaseResponse`

**Actual behavior**
Method throws `ArgumentNullException` with message: 

> Value cannot be null. Parameter name: stringHMACSHA256Helper

**Environment summary**
SDK Version: 2.2.104
OS Version: Windows
Microsoft.Azure.Cosmos version: 3.1.0

**Comment by j82w** [comment]
Out of curiosity what was the issue?

**Comment by msciborski** [comment]
> Out of curiosity what was the issue?

Still don't know, but it works in console application, which i have created for testing purpose. But, still doesn't work in place, where I want to use it. Here is a part, which doesn't work:
```

        public async Task<ICosmosClient> InitializeClient()
        {
            try
            {
                _logger.LogInformation(nameof(InitializeClient));

                Client = new Microsoft.Azure.Cosmos.CosmosClient(_settings.ServiceEndpoint, _settings.Key);

                Database = await Client.CreateDatabaseIfNotExistsAsync("TestDb");

                Container = await  Database.CreateContainerIfNotExistsAsync("TestContainer", "/id");
                return this;
            }
            catch (Exception e)
            {
                throw;
            }
        }
```

**Comment by j82w** [comment]
What framework are you using? Is it an ASP.NET application? Is the Direct nuget dependency being loaded?

**Comment by msciborski** [comment]
@j82w I'm using it in class library, which is refered by ASP.NET application.

**Comment by ealsur** [comment]
Is the Direct DLL in the deployed application's folder along the Cosmos SDK DLL?

**Comment by msciborski** [comment]
@j82w @ealsur 
Hi, I have installed Microsoft.Azure.Cosmos.Direct from nuget and it works. Thanks for help.
