### ISSUE TITLE
Getting information if CosmosDB returns 429

### ISSUE THREAD

**Issue by sovaska** [Azure/azure-cosmos-dotnet-v3#618]
Feature req: Getting information (callback/event/?) if CosmosDB returns 429 (not enough RUs available) so that number of RUs can be increased based on real use instead of questimate.

It would be nice to get callback/event if current RUs is too low. This would help to optimize performance and cost of CosmosDB.

**Comment by j82w** [comment]
One solution you can do now is use the new handler pipeline. All the request in v3 go through this handler pipeline. You can monitor 429s from the handler and have it do a call back if necessary. Check out the [samples](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/CodeSamples/Handlers).

**Comment by sovaska** [comment]
Thanks, already tried to use custom handlers, but the problem is that handler will get 429 only after retry count has been exceeded... I would like to get information when first 429 is returned so that I could increase RUs to get rid of 429s...

**Comment by j82w** [comment]
Another solution would be to use the [Azure Monitoring SDK](https://docs.microsoft.com/en-us/azure/azure-monitor/) to check if there is any 429s and scale using that. Then write an Azure function to run it every so often.

**Comment by j82w** [comment]
@simplynaveen20 will [diagnostics ](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/615)have the info for this?

**Comment by j82w** [comment]
CosmosDiagnostics includes this information.
