### ISSUE TITLE
CreateContainerIfNotExistsAsync throws ArgumentException incorrectly stating the PKs don't match

### ISSUE THREAD

**Issue by wilcobmsft** [Azure/azure-cosmos-dotnet-v3#623]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
After upgrading to latest SDK, CreateContainerIfNotExistsAsync throws an ArgumentException stating PK "/x" in Container "foo" does not match PK "/x". The actual paths in the error message are identical though.

**Environment summary**
SDK Version: 3.1.0
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Comment by wilcobmsft** [comment]
Oddly enough I don't see this for every container of mine. Looking at fiddler, it appears the container for which I get this exception, the partition key is explicitly marked as "systemKey": false.

**Comment by j82w** [comment]
This is likely a bug with PR [572](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/572). This feature was added because users were doing create if not exist, but giving a different container pk. Later they would try to do an insert, and it would fail. This causes it to fail fast with a specific error message.

**Comment by simplynaveen20** [comment]
@wilcobmsft Do we know how those container got created initially which is having "systemKey": false. Means which SDK version

**Comment by adstep** [comment]
I'm still seeing this issue using Microsoft.Azure.Cosmos ```3.1.0```.

**Comment by j82w** [comment]
If you look at the [changelog ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md)PR 629 is under the Unreleased tag.
