### ISSUE TITLE
Using Cosmos db in Xamarin.Forms Cross Platform

### ISSUE THREAD

**Issue by PKYADAV** [Azure/azure-cosmos-dotnet-v3#624]
Hi, I am trying to use cosmos db in Xamarin.Forms project but it is showing below errors:

**Severity	Code	Description	Project	File	Line	Suppression State

Error		Can not resolve reference: `Microsoft.Azure.Cosmos.Direct`, referenced by `Microsoft.Azure.Cosmos.Client`. Please add a NuGet package or assembly reference for `Microsoft.Azure.Cosmos.Direct`, or remove the reference to `Microsoft.Azure.Cosmos.Client`.	MobileApp1.Android**			

Also, when I am adding this nuget then another error is showing as below:

**Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `Microsoft.Azure.Cosmos.Serialization.HybridRow`, referenced by `Microsoft.Azure.Cosmos.Client`. Please add a NuGet package or assembly reference for `Microsoft.Azure.Cosmos.Serialization.HybridRow`, or remove the reference to `Microsoft.Azure.Cosmos.Client`.	MobileApp1.Android**			

Please help me to out of this.

**Comment by ealsur** [comment]
Could you share a small repro Xamarin project we can use as base to reproduce it in our side?

**Comment by kirankumarkolli** [comment]
@PKYADAV please re-open with the repro.

**Comment by jackbond** [comment]
This issue occurs when the Cosmos reference is a transitive reference.

[reproduce.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/3714333/reproduce.zip)

**Comment by kirankumarkolli** [comment]
@ausfeldt can u please take a look?

**Comment by ausfeldt** [comment]
@jackbond Thanks for the repro! 

@PKYADAV The issue is .NET Standard project is the new project format that supports PackageReferences and the Android project is the old project format, which uses packages.config. This caused package dependencies of the .NET Standard project fomat to not flow to the Android project, which is the old format. The work around is add the following to your Android project file:

<PropertyGroup>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
</PropertyGroup>

Make sure that your you delete your bin and obj or do a "git clean -fdx" before you build.

**Comment by j82w** [comment]
We should add a sample project for this since other users will likely hit this same issue.

**Comment by kirankumarkolli** [comment]
Also any thoughts on anyways to make the work-around discoverable?

**Comment by jameswhollister** [comment]
@ausfeldt I'm on Jack's team. Tried your suggestion but doesn't appear to have any impact. The project didn't have a packages.config file though before that change all of it's references were in it's csproj file. Here's a new copy of the repro with that change. 





[reproduce.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/3725903/reproduce.zip)

**Comment by ausfeldt** [comment]
@jameswhollister Interesting, depending on the order I build the project is succeeds or fails. Instead adding below to "XamarinAndCosmosNoLike" project, also will fix the issue, but consistently.

```xml
<PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
</PropertyGroup>
```

Apparently this is a known issue that has been open for a while: https://github.com/xamarin/xamarin-macios/issues/3949

**Comment by jameswhollister** [comment]
@ausfeldt that did it. Thank you!

**Comment by 1iveowl** [comment]
Hmm. Using in the main Xamarin Forms .NET Standard 2.1 lib:

```xml
<PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
</PropertyGroup>
```

I can now pick between these too showstoppers:
1. Can not resolve reference: `Microsoft.Azure.Cosmos.Direct`, referenced by `Microsoft.Azure.Cosmos.Client`
2. `microsoft.identity.client.AuthenticationActivity` is generated by more than one managed type.
