### ISSUE TITLE
Incorrect version getting logged in user agent

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-cosmos-dotnet-v3#636]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Version of sdk in user agent is of direct package instead of cosmos client.

**Comment by j82w** [comment]
This is getting fixed with this: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/630
