### ISSUE TITLE
Add support for the Query Metrics

### ISSUE THREAD

**Issue by FrankGagnon** [Azure/azure-cosmos-dotnet-v3#644]
When a request takes more time/RUs than expected, Query Metrics are very useful to have an idea of the problem. 
https://docs.microsoft.com/en-us/azure/cosmos-db/optimize-cost-queries#metrics-for-troubleshooting

Would it be possible to add support for Query Metrics like there was in the SDK v2? 

I've seen it in the SDK codebase but I can't seem to find any plublic API to access it.

**Comment by j82w** [comment]
@simplynaveen20 do we have an issue for this? [PR ](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/615) is currently in progress

**Comment by simplynaveen20** [comment]
We will track this  here  https://github.com/Azure/azure-cosmos-dotnet-v3/issues/645
