### ISSUE TITLE
Query works in emulator portal, but not via client library

### ISSUE THREAD

**Issue by kentcb** [Azure/azure-cosmos-dotnet-v3#65]
## Describe the bug

Assume a document with structure:

```json
{
    "id": "whatever",
    "created": "2019-03-06T23:10:43.897Z",
}
```

The following query works fine in the portal:

```sql
SELECT DISTINCT VALUE u FROM u ORDER BY u.created
```

However, the same query fails to execute with the v3 .NET client:

```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Distict query requires a matching order by in order to return a continuation token.
If you would like to serve this query through continuation tokens, then please rewrite the query in the form 'SELECT DISTINCT VALUE c.blah FROM c ORDER BY c.blah' and please make sure that there is a range index on 'c.blah'.
   at Microsoft.Azure.Cosmos.FeedResponse`1.get_ResponseContinuation()
   at Microsoft.Azure.Cosmos.CosmosItems.<NextResultSetAsync>d__29`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Cosmos.CosmosDefaultResultSetIterator`1.<FetchNextSetAsync>b__7_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UserQuery.<Main>d__0.MoveNext() in C:\Users\Kent\AppData\Local\Temp\LINQPad5\_qtvejoem\query_hddtrt.cs:line 65
---> (Inner Exception #0) System.ArgumentException: Distict query requires a matching order by in order to return a continuation token.
If you would like to serve this query through continuation tokens, then please rewrite the query in the form 'SELECT DISTINCT VALUE c.blah FROM c ORDER BY c.blah' and please make sure that there is a range index on 'c.blah'.
   at Microsoft.Azure.Cosmos.FeedResponse`1.get_ResponseContinuation()
   at Microsoft.Azure.Cosmos.CosmosItems.<NextResultSetAsync>d__29`1.MoveNext()<---
```

**SIDE NOTE:** there's also a typo in the error message: "distict"

## To Reproduce

1. Create the above document
2. Execute query in portal
3. Execute query via the code below

```C#
async Task Main()
{
    var conn = "<<connection string>>";
    var cosmosClient = new CosmosClient(conn);

    var databaseResult = await cosmosClient
        .Databases
        .CreateDatabaseIfNotExistsAsync("my", 400);
    var database = databaseResult.Database;
    var usersContainerResult = await database
        .Containers
        .CreateContainerIfNotExistsAsync("test", "/id");
    var usersContainer = usersContainerResult.Container;

    var sql = new CosmosSqlQueryDefinition("SELECT DISTINCT VALUE u FROM u ORDER BY u.created");
    
    var itemQuery = usersContainer
        .Items
        .CreateItemQuery<JObject>(sql, 2);

    try
    {
        while (itemQuery.HasMoreResults)
        {
            // THIS FAILS
            var currentResultSet = await itemQuery
                .FetchNextSetAsync();
        }
    }
    catch (Exception ex)
    {
        ex.ToString().Dump();
    }
}
```

## Expected behavior

It should work from the .NET client exactly as in the portal.

## Actual behavior

It fails, and asks you to do something you've already done.

## Environment summary

SDK Version: `3.0.0.1-preview`
OS Version: Windows 10

## Additional Context

You may wonder why I'm requiring the `DISTINCT`, `VALUE`, and `ORDER BY` at all. It's because my actual query has a `JOIN` to an inner child collection. So I need the `DISTINCT` because I don't want repeated values (it _does_ repeat but that looks to be a separate bug. See [here](https://stackoverflow.com/questions/55016239/cosmos-distinct-results-with-join-and-order-by)). Because I have `DISTINCT` I then require an `ORDER BY`. And because I want the actual values, that's why I have `VALUE`.

**Comment by rxharr6** [comment]
Having same issue. Exception thrown on FetchNextSetAsynch call even though HasMoreResults is true, and there are in fact result. Exception thrown:


  | Name | Value | Type
-- | -- | -- | --
  | ex.Message | "One or more errors occurred. (Message: {\"Errors\":[\"Resource Not Found\"]}\r\nActivityId: 3811af57-460c-4823-ae3f-52c210ae0bbf, Request URI: /apps/4eaeaec7-bbaa-4f0b-8bff-461c1f3d9156/services/b292046f-db5b-4806-b4e7-b446e82c2482/partitions/d33d2cf7-d2f6-4843-90a4-4498a1c80154/replicas/131987416449307182s, RequestStats: \r\nRequestStartTime: 2019-04-09T23:57:26.2547648Z, RequestEndTime: 2019-04-09T23:57:26.2547648Z, Number of regions attempted: 1\r\nResponseTime: 2019-04-09T23:57:26.2547648Z, StoreResult: StorePhysicalAddress: rntbd://10.0.0.25:13700/apps/4eaeaec7-bbaa-4f0b-8bff-461c1f3d9156/services/b292046f-db5b-4806-b4e7-b446e82c2482/partitions/d33d2cf7-d2f6-4843-90a4-4498a1c80154/replicas/131987416449307182s, LSN: 31, GlobalCommittedLsn: 31, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#31, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read\r\nResponseTime: 2019-04-09T23:57:26.2547648Z, StoreResult: StorePhysicalAddress: rntbd://10.0.0.22:13700/apps/4eaeaec7-bbaa-4f0b-8bff-461c1f3d9156/services/b292046f-db5b-4806-b4e7-b446e82c2482/partitions/d33d2cf7-d2f6-4843-90a4-4498a1c80154/replicas/131975000909281784s, LSN: 31, GlobalCommittedLsn: 31, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#31, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read\r\n, SDK: Microsoft.Azure.Documents.Common/2.2.0.0, Linux/9 cosmos-netstandard-sdk/3.0.0)" | string

**Comment by j82w** [comment]
This is a bug that is hit by Distinct queries. In the current model we are just calling the v2 query methods. For distinct this throws when you try to access the continuation token. I have a [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/109) out that will fix this.

**Comment by j82w** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/109
