### ISSUE TITLE
CosmosClient to support users and permissions creation

### ISSUE THREAD

**Issue by thuannguy** [Azure/azure-cosmos-dotnet-v3#657]
**The problem**
I need to create new users from C# code and grant them permissions to specific containers. Before v3, I was able to do that using DocumentClient, but the class has been changed to internal in v3.

**Solution **
I would love to have the missing APIs supported by CosmosClient.

**Alternatives**
It would be great if someone can show me a good way to do what I need for now.

**Comment by j82w** [comment]
We are working on it currently #622 . Unfortunately there currently isn't a workaround in v3. We will hopefully have a release in the next few weeks.

**Comment by thuannguy** [comment]
That's cool. I'm looking forward to trying them out. Will "next few weeks" be more closer to 2-3 weeks or 7-8 weeks?

**Comment by j82w** [comment]
Hopefully closer to 2-3 weeks.

**Comment by ductranit** [comment]
@j82w Sorry to bother, when do you guys release it? I really need this feature now. I see #622 is merged but I don't see this in latest nuget package.

**Comment by ealsur** [comment]
Closing as Permissions and Users are already available.
