### ISSUE TITLE
PartitionKeyPath Incorrectly Matched

### ISSUE THREAD

**Issue by adstep** [Azure/azure-cosmos-dotnet-v3#659]
**Describe the bug**
CreateContainerIfNotExistsAsync complains that the requested PartitionKeyPath does not match the existing PartitionKeyPath on an existing container.

**To Reproduce**
```
The requested partition key path '/PartitionKey' does not match existing Container 'ExecutionResult' with partition key path '/PartitionKey'
```

**Expected behavior**
No expected errors. The two string values literally match character for character.

**Actual behavior**
Reports the two strings do not match.

**Environment summary**
SDK Version: 3.1.0
OS Version Windows 10

**Comment by j82w** [comment]
Hi @adstep ,

This issue was fixed in PR [#649](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md). We are in the process of unlisting 3.1.0. We are just waiting on a few other fixes before doing another release. 

Thanks for reporting the issue.
