### ISSUE TITLE
Using SqlQuerySpec with CosmosClient

### ISSUE THREAD

**Issue by demali** [Azure/azure-cosmos-dotnet-v3#663]
Currently, we can use SqlQuerySpec with the DocumentClient. But with sdk version 3, we are recommended to use CosmosClient. 
Is there any way to use SqlQuerySpec with the CosmosClient?

The problem of using DocumentClient is that it returns IQueryable<dynamic> instead of IQueryable<T> which we expect from CosmosClient.

Please let me know if we can use SqlQuerySpec with CosmosClient. And if not, why isn't it supported?

**Comment by bartelink** [comment]
Is [`QueryDefinition`](https://github.com/jet/equinox/pull/144/files#diff-fe04b21266b70fe92b8c4b350264c0e5R567`) what you're after ? If not, can you share the code you're trying to port.
(also if you put tick marks around `IQueryable<T>` it doesnt drop the `<T>` bit - if it's about `Document` support, probably best to have a second question - [Do as I say, not as I do :) ](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/616))

**Comment by j82w** [comment]
If that doesn't answer your question please re-open the issue with a sample of what you are trying to do.
