### ISSUE TITLE
BatchOperationRequestOptions vs ItemRequestOptions

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#672]
BatchOperationRequestOptions is missing several options that ItemRequestOptions has. These restrictions should be documented, and verified they are not supported.

**Comment by abhijitpai** [comment]
@j82w, yes they are not supported. The documentation will be covered in https://github.com/Azure/azure-cosmos-dotnet-v3/issues/685 - will resolve this.
