### ISSUE TITLE
Change feed processor with partition key other than /id

### ISSUE THREAD

**Issue by altenstedt** [Azure/azure-cosmos-dotnet-v3#676]
**Is your feature request related to a problem? Please describe.**
I am trying to implement a change feed processor to update a search index.  The container that I want to process is partitioned on something other than /id.  At runtime, I get an `ArgumentException` with the following message:

`The lease collection, if partitioned, must have partition key equal to id.`

As far as I can understand, my scenario is not supported, which I find surprising.  A change feed processor is important for our system design, but /id is not suitable as a partition key (for this collection).

**Describe the solution you'd like**
I want to be able to register a change feed processor on my partitioned container.  If needed, I can provide the partitionKey to the change feed build process.

**Describe alternatives you've considered**
V2 of the SDK seems to support an interface `ILeaseStoreManager` that looks interesting, but from other issues in this repo, it sounds like not surfacing the partition key in the change feed API is intentional.

**Additional context**
C#

**Comment by j82w** [comment]
Hi @altenstedt ,

Can you take a look at this [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/673/files) where we are adding samples. The lease container is separate from the container you want to monitor. The lease container is used by the change feed processor to track various states.

**Comment by ealsur** [comment]
@altenstedt That requirement is not for the Monitored collection, is for the Leases collection. Please refer to this article: https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#implementing-the-change-feed-processor

Your monitored collection (the one where your changes happen) can be partitioned by anything. Is the second collection, the one used to store the state (leases) is the one required to be partitioned by `/id`.

**Comment by altenstedt** [comment]
@j82w I like #673, and I think that these samples would have helped me understand the "lease" concept quicker and make a great addition to the documentation.

But I should also say that the documentation at https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor is good, and the concept of a "monitored" and separate "lease" container is clearly spelled out.

Thanks for a _very_ quick response to my query!
