### ISSUE TITLE
Ignore property attribute

### ISSUE THREAD

**Issue by kevinding0218** [Azure/azure-cosmos-dotnet-v3#678]
My collection is schema-free for example, I have a string property called "visit_history" but it stores as serialized string format value not as json array, when I define the C# object, is there any way that I can mark one or more of the properties as `Ignored` and then de-serialize myself? Like the Table API had the similar [example](https://stackoverflow.com/questions/45517481/create-a-tableentity-with-array-or-list-property) here.
```
public class MyEntity : TableEntity
{
    public string DicPropertyRaw { get; set; }

    [IgnoreProperty] //this is only available in table storage
    public Dictionary<string, string> DicProperty
    {
        get
        {
            return Deserialize(DicPropertyRaw);
        }

        set
        {
            DicPropertyRaw = Serialize(value);
        }
    }
}
```

**Comment by j82w** [comment]
Hi @kevinding0218,

You can use [JsonIgnore](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/50d944cab2894cbf326f565481b1b3e569595efe/Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs#L114). It's a newtonsoft type, and would require adding a newtonsoft attribute.

Create a custom serializer and add a special JsonConverter.

**Comment by ealsur** [comment]
Additionally, you can implement your own [custom serializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs#L278) and manage the serialization process completely, or provide and [get the Streams](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/CustomSerialization/Program.cs#L95) on the operations.

**Comment by kevinding0218** [comment]
Thank you so much for your help!
