### ISSUE TITLE
insert issue UpsertItemAsync: what is invalid?

### ISSUE THREAD

**Issue by vip32** [Azure/azure-cosmos-dotnet-v3#68]
When inserting a new item with a valid partitionKey value (and partitionKeyPath defined on database.Containers.CreateContainerIfNotExistsAsync). Db+collection is created correctly.

What could be the reason for the following error when using container.Items.**UpsertItemAsync**

Response status code does not indicate success: 400 Substatus: 0 Reason: (Message: {"Errors":["One of the specified inputs is invalid"]}

nothing is inserted in the collection.
no way to find out what actually is causing this :(

![image](https://user-images.githubusercontent.com/164303/53972487-3154f400-40ff-11e9-8969-227bf1b1bcde.png)

![image](https://user-images.githubusercontent.com/164303/53972595-63665600-40ff-11e9-9b99-bf382b2badb6.png)

**Comment by ealsur** [comment]
Does your entity contain an `id` property?

**Comment by vip32** [comment]
yes, same entity works fine with cosmos client v2

however not the typical 'id' setup, but works fine with cosmos client v2 and EF core

![image](https://user-images.githubusercontent.com/164303/53992668-b951f280-412d-11e9-9b7a-180893828188.png)

**Comment by vip32** [comment]
just tried with a normal entity (string id)
however the same error appears.

![image](https://user-images.githubusercontent.com/164303/53993131-cd4a2400-412e-11e9-9044-1f32be8cad9b.png)

**Comment by vip32** [comment]
ok, never mind. my ID property did not have a value :( now it works fine
