### ISSUE TITLE
Bulk Stream > Rate limiting

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#690]
Ref #585 

Current rate limiter is based on single concurrent request per Range. Further customization of that limiter is desirable to achieve greater performance.

**Comment by kirankumarkolli** [comment]
Currently only client side buffering is serial per key-range, where as processing the batch is parallel.
And the serial part doesn't include T -> Stream conversion which is a significant part. With-out it its worth validating the requirements once.

**Comment by ealsur** [comment]
What is not yet clear is if we want a Rate limiting based on RU/s (which would need to be across all key-ranges) or at the request-per-key-range level.

**Comment by kirankumarkolli** [comment]
Got it. I mis-interpreted it.
