### ISSUE TITLE
What's the difference behind by using ReadItemAsync and ReadItemStreamAsync?

### ISSUE THREAD

**Issue by kevinding0218** [Azure/azure-cosmos-dotnet-v3#693]
Hello we noticed there are two method by reading an item either with `ReadItemAsync` or `ReadItemStreamAsync`, but which one should we use in development scenario? 

Basically we're looping a list of item and based on each item's id, partition key, read the corresponding object from cosmos db collection, then perform update/insert based on different business scenario. Which one here would provide us with better performance? 

Thank you very much for your advice!

**Comment by mark-manticore** [comment]
ReadItemAsync<T> reads and deserializes your JSON into a strongly typed C# object. If you are modifying documents as part of your backend business logic then this makes the most sense to use.

ReadItemStreamAsync gives you a stream of the JSON document. If you have an endpoint that allows an user to access a document (without backend modifications), you can avoid the double serialization hit (from stream to C# object back to stream) by forwarding the stream directly. It's also useful if you want to modify the underlying JSON before deserializing it into your business logic models (ie data migration/versioning).

Reading a stream and deserializing into your own C# object will likely be the same performance as ReadItemAsync<T> (assuming you're using the standard JSON.NET). The new .NET Core 3 SDK may be more performant but maybe the cosmos sdk will provide an easy switch to use that?

**Comment by kevinding0218** [comment]
@mark-manticore , thank you very much for your explanation and that makes a lot of sense!
