### ISSUE TITLE
Database.ReadThroughputAsync throw CosmosException if no database throughput

### ISSUE THREAD

**Issue by donghexu** [Azure/azure-cosmos-dotnet-v3#696]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Database.ReadThroughputAsync() throws CosmosException in 3.1.1, if there is no database throughput. In 3.0.0, it returns Nullable as expected. 

**To Reproduce**
Create a database without throughput, and use 3.1.1 to read the throughput, it will throw exception. 

**Expected behavior**
Should be consistent with 3.0.0 behavior, which returns nullable.

**Actual behavior**
Throw CosmosException

**Environment summary**
SDK Version: 3.1.1
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Comment by j82w** [comment]
@simplynaveen20 is this a regression?
