### ISSUE TITLE
User-Agent string is too long and truncate customized user agent suffix

### ISSUE THREAD

**Issue by donghexu** [Azure/azure-cosmos-dotnet-v3#697]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
With 3.1.1, once we add customized User-Agent suffix to User-Agent field, from fidder I can see the whole User-Agent header got truncated. Like this:
User-Agent: Windows/10.0.17763 cosmos-netstandard-sdk/3.1.4 3.1.1-.NET Core 4.6.26614.01 X64 637014000798739244 cosmos-tab

We add "cosmos-table-sdk/2.0.0" to it but got truncated.

**Expected behavior**
User-Agent header should be optimized and leave enough space for customized user-agent suffix.

**Environment summary**
SDK Version: 3.1.1
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Comment by kirankumarkolli** [comment]
Is the truncation by service or in kusto.

**Comment by donghexu** [comment]
It is truncated inside ClientOptions. The below screen shot shows that the ApplicationName is correctly set, but the UserAgent gets truncated. 
![UserAgentStringTruncated](https://user-images.githubusercontent.com/39783343/63058295-3170d100-bea1-11e9-9cc1-67f8a8326beb.JPG)

**Comment by ealsur** [comment]
@donghexu The problem seems to be that the Suffix has a limit of 64 characters by definition of the UserAgentContainer.

I'll work on reducing the new detailed information to prioritize the user provided suffix.
