### ISSUE TITLE
AsItemQuery 

### ISSUE THREAD

**Issue by ajayraaviv** [Azure/azure-cosmos-dotnet-v3#7]
Hello,

  One of the examples has a note mentioning about using "AsItemQuery", if we do not want to enumerate through all the results. However I do not see any such method on the CreateItemQuery method or seem to figure out a way to do it. Any help is greatly appreciated. 

Thanks,
Ajay

**Comment by j82w** [comment]
The samples were converted from v2 SDK samples. This is a bug were the comment did not get updated for the v3 SDK. The item query samples are here: [https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs ](url) . Here is how to extend the "QueryWithSqlParameters" example to set the max item count. Each FetchNextSetAsync will pull back 2 items until all the results are returned.

```
List<Family> results = new List<Family>();
var resultSetIterator = container.Items.CreateItemQuery<Family>(
                sqlQueryDefinition: query, 
                partitionKey: "Anderson",
                maxItemCount: 2);
while (resultSetIterator.HasMoreResults)
{
    results.AddRange((await resultSetIterator.FetchNextSetAsync()));
}
```
