### ISSUE TITLE
MultiPolygon and MultiLineString spatial type support

### ISSUE THREAD

**Issue by garethbbits** [Azure/azure-cosmos-dotnet-v3#70]
**The problem:**
When encountering MultiPolygon/MultiLineString GeoJSON data, there is no spatial type available for serialization.

**Desired solution:**
Stronger spatial type support and Microsoft.Azure.Documents.Spatial.Geometry types for MultiPolygon and MultiLineString, along the lines of existing Polygon/Point/LineString types

**Alternatives:**
Continue to use SQL Server or use an alternative DB provider. 

**Additional context;**
When taking shapefile (*.shp) data and exporting it to GeoJSON format for import into Azure Cosmos documents, any data that is either multi polygon or multi line string cannot be directly serialized into a Microsoft.Azure.Documents.Spatial.Geometry type.

Is there any projection for including support for MultiPolygon and MultiLineString spatial types based on  Microsoft.Azure.Documents.Spatial.Geometry in the upcoming release?

**Comment by kirankumarkolli** [comment]
Spatial types will be covered in Microsoft.Azure.Cosomos.Spatial namespce. There are few types already, please check https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.spatial?view=azure-dotnet-preview 

We will fill the missing types from DocumentClient (or V2.X SDK) in this namespace. 
@simplynaveen20 can you please look into it?

**Comment by bchong95** [comment]
One thing to note is that we should only port over the data types that are supported on the backend. I think only MultiPolygon is a missing structure while MultiLineString is missing and not supported on the backend.

**Comment by simplynaveen20** [comment]
MultiPolygon support added in 3.0.0.9-preview
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/79
MultiLineString is still not support in CosmosDB at this point .
