### ISSUE TITLE
Any code sample of how to use Azure Cosmos DB Trigger Functions with ChangeFeedProcessor?

### ISSUE THREAD

**Issue by kevinding0218** [Azure/azure-cosmos-dotnet-v3#701]
Hello we're working with **Cosmos DB Trigger Azure Function** while we're wondering if there is any code sample we can refer regarding the **change feed processor**, we noticed there was a feature around "ChangeFeedProcessor" inside the SDK and seems like there is a [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/673/files/245e06dfa26d4892e2d6a0e5e58447b73e6f9878#diff-a65b0e3e3edc1c63206823660d5137ab) of the code sample but couldn't find it now with master branch, we also found another github code example [link](https://github.com/Azure-Samples/cosmos-dotnet-change-feed-processor) but that seems like something worked within console application but not within the **Cosmos DB Trigger Azure Function**. 

Maybe we were wrong with the ChangeFeed usage in Azure function, we kind of feel like the **ChangeFeedProcessor** is working for the application level, for Azure function, there maybe some other implementation, please feel free to correct us!

If not, would you happen to know where we could refer how to use the ChangeFeedProcessor in Azure Function?

Thank you very much for your help!

**Comment by ealsur** [comment]
Azure Functions at this moment, uses the Change Feed Processor V2, the source code is in this repo: https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet

Azure Functions acts as an abstraction that simplifies the development process by letting the developer only worry about the ProcessChangesAsync implementation and not worrying about VMs or instances.

V3 SDK has a new Change Feed Processor version, included samples here https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed

Conceptually they are the same, the implementation has been made to use the V3 SDK process pipeline.

There is currently no implementation of Change Feed Processor V3 in Azure Functions.

**Comment by GrimGadget** [comment]
Did this ever get implemented?

All of the code samples I'm finding online use the `IReadOnlyList<Document>` type for the list of changed documents, but `Document` is a v2 SDK type.  Trying to figure out how to implement a change feed function in a v3 function app.

**Comment by ealsur** [comment]
@GrimGadget there are a couple of conflicting points in what you say.

When you create a Function, you can only use the provided bindings/triggers. In the case of Cosmos DB, the provided Trigger uses V2 SDK.
You can create your own Trigger as a custom Function Extension, is this what you are asking? You want to create your own Extension and you want to use the V3 SDK? That is totally possible to do.
Or, are you asking if the current Cosmos DB Trigger can be moved to V3 SDK (this is the wrong repo for this)?

If your question is the latter: There was an initial effort but in light of new things coming on the horizon (V4 SDK, System.Text.Json, etc) it requires bigger changes across Functions, so it is on hold. It would not make sense to produce a breaking change (V3) to then produce another breaking change (V4).

**Comment by GrimGadget** [comment]
Sorry.  My mistake.  For some reason I thought this issue was in the project for Azure Functions SDK v3, not Cosmos SDK v3, which I think is the main source of the confusion.

All of our internal data libraries are already converted to Cosmos SDK v3.  Now we're in the process of converting our VS-developed functions to the Functions SDK v3.  The problem is trying to implement the v3 function with v3 Cosmos.  All of the online articles I've been finding for developing Azure Functions to handle Cosmos change feeds are based on Functions v2 + DocumentDb.

My goal was to find documentation or an article on writing a v3 function to handle a change feed without having to use DocumentDb artifacts, so that I wouldn't have to waste days figuring it out myself.  That ship has sailed at this point.
