### ISSUE TITLE
How do you set the TTL when creating a container?

### ISSUE THREAD

**Issue by wpitallo** [Azure/azure-cosmos-dotnet-v3#707]
How do you set the TTL when creating a container?

**Comment by j82w** [comment]
Hi @wpitallo ,

The [samples ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e6510130dd8f97a33097219c6c207282dd72d555/Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/Program.cs#L131) have an example.

**Comment by wpitallo** [comment]
Thank you @j82w

**Comment by wpitallo** [comment]
@j82w is there a way to read stored procedures similar to: DocumentClient.ReadStoredProcedureAsync Method ?

**Comment by j82w** [comment]
We moved stored procedures, triggers, and user defined functions into Scripts under Container. There is sample [here ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e6510130dd8f97a33097219c6c207282dd72d555/Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/Program.cs#L26), [code with examples](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e6510130dd8f97a33097219c6c207282dd72d555/Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs#L218), and [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.scripts.scripts?view=azure-dotnet).

**Comment by wpitallo** [comment]
Thank you @j82w appreciate the help!
