### ISSUE TITLE
Flaky-test: GetCosmosSerializerWithWrapperOrDefaultWithOptionsTest

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#712]
ref: https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_test/analytics?definitionId=44&contextType=build

Test: Microsoft.Azure.Cosmos.Tests.CosmosClientOptionsUnitTests.GetCosmosSerializerWithWrapperOrDefaultWithOptionsTest
Priority: not available
Test file: microsoft.azure.cosmos.tests.dll
Machine: Mac-678
Tested build: 20190816.1
Error message: Assert.AreEqual failed. Expected:<{ "id": "testid", "camelCaseProperty": "TestCamelCase" }>. Actual:<{ "id": "testid", "camelCaseProperty": "TestCamelCase" }>. 
Stack trace: 
at Microsoft.Azure.Cosmos.Tests.CosmosClientOptionsUnitTests.GetCosmosSerializerWithWrapperOrDefaultWithOptionsTest() in /Users/vsts/agent/2.155.1/work/1/s/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs:line 196

**Comment by j82w** [comment]
This is only failing for Mac environment. It appears that the string as different special characters causing it to fail.
