### ISSUE TITLE
Mocking ItemResponse<>

### ISSUE THREAD

**Issue by gdodd1977** [Azure/azure-cosmos-dotnet-v3#714]
There appears to be no way to create an ItemResponse object for unit testing. I'm trying to mock ReadItemAsync, but I can't specify a return item for that call mock.

**Comment by j82w** [comment]
There is a [PR ](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/631/files)here to add samples on Mocking it. ItemResponse all the values are virtual, and it has a protected empty constructor. You should be able to mock any of the fields. What test framework are you using?

**Comment by j82w** [comment]
If you are still having issues please reopen it and provide a repo with the testing framework.
