### ISSUE TITLE
client stalls on item read operations on netcore3 p7 & netcore3 p8

### ISSUE THREAD

**Issue by FluentGuru** [Azure/azure-cosmos-dotnet-v3#717]
For some reason, the cosmos db client v3 stalls on read item operations both not on database/containers o store procedure manipulation operations. This only happens on netcore3 p7 & p8. I've been using it happily in all netcore3 releases since p2 and never had this problem.

_***PS. This issue also happens on the v2 client***_

This is the call that causes the stallness:
```
var doc = await _container.ReadItemAsync<GrainStateEntity>(id, new PartitionKey(partitionKey), new ItemRequestOptions()
                {
                    ConsistencyLevel = _options.GetConsistencyLevel() //Either Session or null. It happens with both
                });
```
This is my current connection policy

![image](https://user-images.githubusercontent.com/2110596/63183204-740de700-c022-11e9-8817-1fc8a45042c2.png)

**Comment by FluentGuru** [comment]
Related https://github.com/dotnet/corefx/issues/40374

**Comment by FluentGuru** [comment]
Additional info/Workaround: Changing `ConnectionMode` to `Gateway` seems to fix the issue.

**Comment by ealsur** [comment]
When you say stall, it means it hangs or takes longer time to complete? The difference between Gateway and Direct would be the protocol (HTTP vs TCP). It could indicate something changed in the communication stack in preview7+ if you are not changing the SDK version.

**Comment by FluentGuru** [comment]
@ealsur yeah. The guys on corefx are interested on it that's why I created a bug in there

**Comment by ealsur** [comment]
@FluentGuru I tried to repro this with this code:

    static async Task Main(string[] args)
    {
        CosmosClient client = new CosmosClient("AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==");

        SampleDoc doc = new SampleDoc(){
            id = Guid.NewGuid().ToString(),
            pk = Guid.NewGuid().ToString()
        };
        Console.WriteLine(RuntimeInformation.FrameworkDescription);
        Console.WriteLine("Creating db");
        await client.CreateDatabaseIfNotExistsAsync("test");
        Console.WriteLine("Creating container");
        await client.GetDatabase("test").CreateContainerIfNotExistsAsync("test", "/pk");
        Console.WriteLine("Creating sample item");
        await client.GetContainer("test", "test").CreateItemAsync(doc, new PartitionKey(doc.pk));
        Console.WriteLine("Reading sample item");
        await client.GetContainer("test", "test").ReadItemAsync<SampleDoc>(doc.id, new PartitionKey(doc.pk));
        Console.WriteLine("Job's done");
    }

    private class SampleDoc
    {
        public string id { get; set; }

        public string pk { get; set; }
    }

Which outputs: 

![image](https://user-images.githubusercontent.com/1633401/63294048-3907ef80-c27e-11e9-80b0-0bad06c2babb.png)

This is on Windows. Are you running in Linux or Mac?

**Comment by FluentGuru** [comment]
I'm using Windows. Try setting the connection mode to direct and the consistency level to session. Alsoat least in my case it happens when first trying to create a database and a container If not exist then trying to read from said container without writing that's the flow of the implementation which causes the error.

**Comment by ealsur** [comment]
@FluentGuru ConnectionMode Direct is default in V3.

I changed the code to this:

    static async Task Main(string[] args)
    {
        CosmosClient client = new CosmosClient("AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==");

        SampleDoc doc = new SampleDoc(){
            id = Guid.NewGuid().ToString(),
            pk = Guid.NewGuid().ToString()
        };
        Console.WriteLine(RuntimeInformation.FrameworkDescription);
        Console.WriteLine("Creating db");
        await client.CreateDatabaseIfNotExistsAsync("test");
        Console.WriteLine("Creating container");
        await client.GetDatabase("test").CreateContainerIfNotExistsAsync("test", "/pk");
        Console.WriteLine("Reading sample item");
        try
        {
            await client.GetContainer("test", "test").ReadItemAsync<SampleDoc>(
                doc.id, 
                new PartitionKey(doc.pk),
                new ItemRequestOptions(){
                    ConsistencyLevel = ConsistencyLevel.Session
                });
        }
        catch (CosmosException ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
        {
            Console.WriteLine("Doc doesnt exist");
        }
        Console.WriteLine("Job's done");
    }

And it still works:

![image](https://user-images.githubusercontent.com/1633401/63294945-60f85280-c280-11e9-825f-29b463e6e5fc.png)

I'm catching the expected CosmosException due to the 404.

**Comment by ealsur** [comment]
@FluentGuru do you have a repro code that you can share? The code I tested works, unless there is something else that is happening outside the actual read calls, like a blocking call to an async method?

**Comment by FluentGuru** [comment]
@ealsur I just changed the connection mode to direct to see if the issue still works after my refactoring to upgrade to v3 and it does.  Here's what I can tell you:
- Our backend is on Microsoft Orleans
- We Use cosmosdb for our grain, reminders and membership storage.
- We made our customer implementations of each storage services
- The issue happen in our implementation of the grain storage.

I'll ask my boss if I can share you a gist of our complete implementation and paste here

**Comment by ealsur** [comment]
We had in the past an issue with Orleans when part of the Direct protocol made a change on the Task Scheduler that was being used (ref https://dotnet.github.io/orleans/Documentation/grains/external_tasks_and_grains.html#task-based-apis).

The fact that your application in Orleans work with the same SDK version on NET Core versions before preview 7 but not after preview 7, it might mean that something in preview 7 might have changed some behavior on the Task Scheduler?

**Comment by FluentGuru** [comment]
@ealsur that makes sense. our issues are more related to Orleans services as opposed to any fetch inside a gran but that's a good lead to keep looking. We have a new stallness issue which is not fixed with changing the connection mode to direct. I'll follow this lead to see

**Comment by FluentGuru** [comment]
@ealsur the guys at Orleans told me they experimented a similar issue and offered a workaround. Here's a quote from a member of the Orleans team:
"Oh, yes, I had tunnel vision sorry. Yes, there is an issue with how CosmosDB's background workers are scheduled. They sometimes capture an activation's TaskScheduler and when that activation is deactivated they are no longer able to run. That's bad behavior from the CosmosDB SDK but we also made a change in 2.3.x to fix it
It's not a .NET core issue. CosmosDB should make a fix, I've told them about it"
It appears that whatever fix they did doesn't work anymore on netcore3 p7+. However, the workaround of wrapping cosmosdb calls inside a `Task.Run` fixes the stallness. That could be something you guys can get behind

**Comment by ealsur** [comment]
@FluentGuru I recall that conversation and we did the fix they requested. Basically there was a version in 2.X that modified the Task Scheduler, but it was reverted. The issue was that we changed to use `TaskScheduler.Current` instead of `TaskScheduler.Default`. But it was reverted back in May.

What I don't understand though is, with the same V3 SDK version, you are running into the issue on different NET Core versions. The variable there is NET Core though.

**Comment by FluentGuru** [comment]
@ealsur That's my guess, things were fine but something changed in p7 that gave out the same issue cause it has the same workaround. What do you suggest?

**Comment by ealsur** [comment]
@FluentGuru Can you confirm this only happens on Direct mode?

**Comment by FluentGuru** [comment]
This happens on direct mode only for `ReadItemAsync` but it happens in both modes for `GetItemLinqQueryable<T>().ToFeedIterator().ReadNextAsync()`

**Comment by ealsur** [comment]
@FluentGuru would you mind sharing the contact with the Orleans team? I honestly don't know which could be the issue or what was the change in preview 7 that triggered this behavior. I assume getting a small Orleans repro is not easy though.

**Comment by FluentGuru** [comment]
@ealsur  It was a conversation with @ReubenBond in the Orleans Gitter if you get in you can see our conversation

**Comment by ReubenBond** [comment]
@FluentGuru are you able to capture a memory dump of a stuck process? If so, I can help to analyze it.

**Comment by FluentGuru** [comment]
@kirankumarkolli @ReubenBond @ealsur
All, tested the upgrade to preview 2 and it worked. Already implemented on my prod. Thank you very much and nice work :)

**Comment by j82w** [comment]
@FluentGuru  [3.2.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.2.0) is released
