### ISSUE TITLE
Firstclass CamelCase support

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#72]
**Is your feature request related to a problem? Please describe.**
Support CamelCase as first class construct in CosmoClient. 

**Describe the solution you'd like**

1. CamelCase as option in CosmosClientBuilder
2. CustomSerializer and CamelCase are exclusive and can't co-exist
3. Typed point operations will do CamelCase serialization
4. Stream API will just pass through the payload (no conversion even if CamelCase is opted)
5. LINQ will generate a cancelCases queries
6. SPROC/UDF etc...: N/A and customer is expected to author them in CamelCase way.

**Describe alternatives you've considered**
Extended custom CosmosJsonSerializer can be used for point operations but will not be integrated into LINQ. LINQ extension can be a separate option but better abstraction to have it across CosmosClient.

**Additional context**

**Comment by bchong95** [comment]
@khdang What are your thoughts on this?

**Comment by kirankumarkolli** [comment]
LINQ + CamelCase is an ask for quite some time. 
Lets prioritize it with this scope.

**Comment by j82w** [comment]
Would it be better to expose some for of interface for a contract resolver that converts member info into json field name? That way it can be extended for other cases, and we can provide a default camel case version.

**Comment by kirankumarkolli** [comment]
Below two PR's address this issue
#650 Enabling serialization customization through CosmosSerializerOptions
#716 Adding camel case serialization on LINQ query generation (#716)
