### ISSUE TITLE
All changes from changefeed going to one instance

### ISSUE THREAD

**Issue by demali** [Azure/azure-cosmos-dotnet-v3#721]
We have currently a service which consumes the changefeed processor and depends on changes coming via changefeed processor to the service instance. Right now, we see only one instance receives the changes from the changefeed processor. 
E.g. if there are 5 service instances, only one of them receive the changes via changefeed. Once I shutdown the instance receiving the changes currently via changefeed processor, one of the remaining 4 will start receiving the changes and so on.

What we need here is for all instances to receive all changes from the changefeed processor from all the partitions. I couldn't find any setting while setting up the changefeed processor. Is this because of the EqualPartitionsBalancingStrategy? Will we need to implement our own partition balancing strategy for this so that all service instances receive all the changes?

**Comment by bartelink** [comment]
do you definitely have >1 range (physical partition) ? (you can inspect number of ranges in portal)

**Comment by ealsur** [comment]
@demali Please see https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#dynamic-scaling

As @bartelink mentioned, if your Leases collection only has 1 lease, then a lease cannot be owned by more than one instance. No matter how many instances you spin up.

Currently the Change Feed Processor can generate one lease per Partition Key Range. Partition Key Ranges grow as your container grows both in RU/s and size. We do have a workitem to track the possibility of making the lease more granular (https://github.com/Azure/azure-cosmos-dotnet-v3/issues/173) but this requires extra work that exceeds the client SDK.

**Comment by demali** [comment]
What we wanted was achieved by providing a distinct workflow name to each instance for which we wanted logs. So, now we have 3 instances, all with different workflow names and they all get all changes from the changefeed.

**Comment by ealsur** [comment]
Might be worth writing a doc article about this scenario, I'm sure in the future there will be more people trying to do it. Will add a workitem.
