### ISSUE TITLE
Documentation on conversion from DocumentDb v2 to Cosmos v3 library

### ISSUE THREAD

**Issue by GrimGadget** [Azure/azure-cosmos-dotnet-v3#725]
**Is your feature request related to a problem? Please describe.**
Due to breaking changes in DocumentDb v2 that were not properly semantically versioned, I'm converting some apps to the Cosmos v3 library.  So many things have changed architecturally that nothing is "intuitive" any more to someone familiar with the DocumentDb v2 library.

**Describe the solution you'd like**
Documentation on significant architectural changes in day-to-day usage
- Instead of UriFactory.CreateXxxxxxxx, do 'blah'
- Instead of RequestOptions, use 'Foo'
- Instead of FeedOptions, do 'blah'
- To manipulate documents, instantiate a container first

**Describe alternatives you've considered**
Extensive sample code would be useful but much more time-consuming for devs already familiar with DocumentDb v2

**Additional context**

**Comment by kirankumarkolli** [comment]
Topics to cover
- Client creation options mapping
- Serialization options
- Auto id generation pattern
- Missing Document type handling
- RequestOptions mapping to new model
- Diagnostics
- Resource mapping (Collection -> Container, Document -> Item)
- Scripts exaplined

**Comment by j82w** [comment]
https://docs.microsoft.com/en-us/azure/cosmos-db/migrate-dotnet-v3?tabs=dotnet-v3
