### ISSUE TITLE
ReadNextAsync should throw if called after query is done

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#727]
For query operations if ReadNextAsync is called after HasMoreResults is false an exception should be thrown saying the query operation is done. It currently returns the last  FeedResponse.

**Comment by GrimGadget** [comment]
I would argue that it should return a null instead of throwing

**Comment by j82w** [comment]
@GrimGadget what scenario would it be better for it to return null? This seems like a bug in the code if ReadNextAsync is getting called after HasMoreResults is set to false. The reason are thinking about throwing is it's how a list or array works. If you try to access length + 1 it will throw an out of bound exception.

**Comment by GrimGadget** [comment]
To me, `null` represents precisely "no result"

No results or no further results is not actually exceptional.  It's pretty common.

```csharp
var iterator = Blah();
return (await iterator?.ReadNextAsync())?.SingleOrDefault();
```

**Comment by j82w** [comment]
This code is valid and will still work. Queries with 0 results will still return an empty IEnumerable. It will only throw if you continue to call ReadNextAsync after the HasMoreResults is false.
```
var iterator = Blah();
return (await iterator.ReadNextAsync())?.SingleOrDefault();
```

Here is an example that will cause an exception to be thrown.
```
var iterator = Blah();
List<Book> books = new List<Book>();
while(iterator.HasMoreResults){
   books.AddRange(await iterator.ReadNextAsync());
}

// This will throw an exception because you are attempting to read a query 
// that is already completely drained.
await iterator.ReadNextAsync();
```
