### ISSUE TITLE
EnableMultipleWriteLocations marked internal

### ISSUE THREAD

**Issue by jasontho-ms** [Azure/azure-cosmos-dotnet-v3#735]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
This should not be internal.

**To Reproduce**
Observe the internal-ness

**Expected behavior**
It should be public

**Actual behavior**
It is internal

**Environment summary**
SDK Version: 3.1.1
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
EnableMultipleWriteLocations is enabled by default. No reason for it to be public.
