### ISSUE TITLE
RU calculation from ItemResponse

### ISSUE THREAD

**Issue by kevinding0218** [Azure/azure-cosmos-dotnet-v3#742]
Hello, we're kind of confused by tracking the RU spent with `RequestCharge` from `ItemResponse` using current SDK v3, we've referred the documentation via [here](https://docs.microsoft.com/en-us/azure/cosmos-db/find-request-unit-charge), however, in our scenario, we found our RU from reading one document is always **1**...so for reading 80 items the total RU is **80**...And it never changes no matter how many documents existed in our collection or if our document schema changes... Which doesn't seem to be correct number compared to use _SQL Query_ within azure portal.

Here is a screenshot of our code implementation and output result:
![image](https://user-images.githubusercontent.com/13737436/63802195-098d5e80-c8e0-11e9-84c5-859eb5c90fbe.png)

![image](https://user-images.githubusercontent.com/13737436/63802128-ee225380-c8df-11e9-8453-b4c3f8bf6b80.png)

Thank you very much for your help!

**Comment by bartelink** [comment]
A point read of one item of < 1024b is literally defined as being 1 RU (1 RU per KiB or part thereof), and intentionally is not affected by amount of records etc. Perhaps you're comparing with charges for queries? even a query that yields a single document with a basic query has a completely different set of charges - definitely strongly recommend reading the charging model docs - its the real instructions on how to best use CosmosDB.

**Comment by bartelink** [comment]
Yes, very much so (the other nice thing is that a NotFound is 1 RU, and a NotModified if you put an IfNotModified etag in the request also costs 1 RU even e.g. if you are [not] reading a 100K item).

I have a doc about [some of these things](https://github.com/jet/equinox/blob/master/DOCUMENTATION.md#azure-cosmosdb-concerns) mixed into a larger set of discussions - while there are lots of completely unrelated concerns you might be able to find something relevant by searching for `RU.

**Comment by bartelink** [comment]
CosmosExceptions have RU counts as a property too (one reason being if you invoke a stored proc etc., it can incur plenty cost before failing).
