### ISSUE TITLE
How to list databases and containers

### ISSUE THREAD

**Issue by aloneguid** [Azure/azure-cosmos-dotnet-v3#746]
Is there any way to list those? There are methods `CreateIfNotExists()` and others, however I can't find one to list.

**Comment by simplynaveen20** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6f610954032d913eef13727669d0b7e0f061116c/Microsoft.Azure.Cosmos.Samples/CodeSamples/DatabaseManagement/Program.cs#L96
