### ISSUE TITLE
Is changing indexing policy supported in v3?

### ISSUE THREAD

**Issue by kevinding0218** [Azure/azure-cosmos-dotnet-v3#748]
Hello, we've noticed that change indexing policy was available through v2 via [documented](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-manage-indexing-policy), but we didn't have an opportunity to find similar functionality here...Just curious if this is also available or would be available in v3 SDK?

best,

**Comment by kirankumarkolli** [comment]
Yes, please check sample at https://github.com/Azure/azure-cosmos-dotnet-v3/blob/users/kirankk/tmp_id_generation/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs#L50-L89 (ReIndexingTest)

**Comment by kevinding0218** [comment]
Hello @kirankumarkolli ,  when we changed indexing policy during run-time, will it cost any RU by doing it?
