### ISSUE TITLE
Mechanism to detect the region from where request is served

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#75]
**Is your feature request related to a problem? Please describe.**
Mechanism to detect the region from where request is served

**Describe the solution you'd like**
*Response types expose a way to know the region which served the request. 
Queries which are served from multiple regions also needs to be covered.

**Describe alternatives you've considered**
Currently this information is not available.

**Additional context**
NA

**Comment by bchong95** [comment]
@kirankumarkolli and @j82w  This information is already in the PointOperationDiagnostics right?

**Comment by j82w** [comment]
It does have contacted regions, but it's not just the region. Is this good enough or do we need an explicit region name field?

For example:
URL from data explorer:
`https://myAccountTemp.documents.azure.com:443/`

String from diagnostics:
`{https://myAccountTemp-eastus2.documents.azure.com/}`

**Comment by kirankumarkolli** [comment]
Explicit will make it quite useful if it needs programmatic logic.
For queries, should it be a collection of regions?

**Comment by j82w** [comment]
This only works for direct + TCP mode where the client side request diagnostics exists. There is a PR adding the clients side request statistics to the query diagnostics which will return each page as a JSON object with the query metrics, client side request statistics, and some other info required for debugging.

**Comment by j82w** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2312
