### ISSUE TITLE
Batches cannot be used to insert more than 2 MB of data at a time

### ISSUE THREAD

**Issue by FrankGagnon** [Azure/azure-cosmos-dotnet-v3#750]
It seems like batches cannot be used to insert more than 2 MB of data at once. Since the maximum size of an entity is 2 MB and the batch operation limit is 100 it should be possible to insert 200 MB at once.

**Comment by kirankumarkolli** [comment]
Batches are atomic(or transactional), ordered and meant for OLTP workload which are latency sensitive. 

We will be shortly previewing a bulk capability which will enable non-transactional, un-ordered throughput optimized capability. It enables bulk import/export scenarios. 

@FrankGagnon will bulk suit for your scenarios?

**Comment by FrankGagnon** [comment]
@kirankumarkolli It's going to be useful but not for my actual usecase. 

I am currently implementing a chunking mechanism to split up entities with a larger than 2 MB payload. I would've liked to insert them all at once in an atomic operation.

**Comment by kirankumarkolli** [comment]
Batch is transactional in semantics & split can;t guarantee it. For applications which doesn't need transactional semantics use our Bulk API.
