### ISSUE TITLE
Support creation of indices on collections in the SQL API

### ISSUE THREAD

**Issue by jorgensigvardsson** [Azure/azure-cosmos-dotnet-v3#751]
Please support managing indices in the new version of the SDK. Version 2 allowed setting the property `Indexes` on `IncludedPath`. Version 3 does not (the property is marked as internal).

**Comment by bchong95** [comment]
The fields have been deprecated, so they are not public anymore. In terms of query compat the collection will be created with range and precision -1.

**Comment by jorgensigvardsson** [comment]
How am I supposed to manage indices then? Please don't say "via the portal"...

(The documentation is, shall we say "sparse")

**Comment by bartelink** [comment]
curious; what do you specifically want to do with them, i.e. what would you do in the portal?

**Comment by bchong95** [comment]
The concept of indices have been deprecated. Everything is going to be:
* DataType = `number` + `string` (null, boolean)
* Precision = `-1`
* Type = `Range`

So in terms on querying you are going to have a superset of what you used to have. There have been improvements made to storage, so you won't see a bloat.

You may still choose what paths are indexed by using `included` vs `excluded`.

**Comment by jorgensigvardsson** [comment]
@bchong95  Thanks for the info, I appreciate it!
