### ISSUE TITLE
When connection mode is direct, protocol can't set to https

### ISSUE THREAD

**Issue by yamatoya** [Azure/azure-cosmos-dotnet-v3#757]
**Describe the bug**
[This article](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips#use-tcp) says that when connection mode is direct, protocol can select both tcp and https in the .NET SDK.
But, `CosmosClientOptions` can't set the protocol.

```
        /// <summary>
        /// Gets or sets the connection protocol when connecting to the Azure Cosmos service.
        /// </summary>
        /// <value>
        /// Default value is <see cref="Protocol.Tcp"/>.
        /// </value>
        /// <remarks>
        /// This setting is not used when <see cref="ConnectionMode"/> is set to <see cref="Cosmos.ConnectionMode.Gateway"/>.
        /// Gateway mode only supports HTTPS.
        /// For more information, see <see href="https://docs.microsoft.com/azure/documentdb/documentdb-performance-tips#use-tcp">Connection policy: Use the TCP protocol</see>.
        /// </remarks>
        internal Protocol ConnectionProtocol
        {
            get => this.connectionProtocol;
            set
            {
                this.ValidateDirectTCPSettings();
                this.connectionProtocol = value;
            }
        }
```

**Actual behavior**
I imaget that `internal Protocol ConnectionProtocol` is `public Protocol ConnectionProtocol`

**Comment by bartelink** [comment]
Your article describes the V1/2 API terms and settings.
V3 flattens 2 settings down into one - I've enumerated [the choices here](https://github.com/jet/equinox/pull/144/files#diff-fe04b21266b70fe92b8c4b350264c0e5L1056) - in V3, you get such an enum out of the box.
See [this comparison](https://github.com/jet/equinox/pull/144/files#diff-fe04b21266b70fe92b8c4b350264c0e5R1072) for how the changes compare.

**Comment by j82w** [comment]
What is the reason for wanting to use Direct mode with HTTPS?

**Comment by yamatoya** [comment]
Thank you for your response. I understood it.
Before using this sdk, I confirm the option. So I'm interesting to  ConnectionProtocol.
I don't have the reason for using Direct mode with HTTPS.
I decide to use default mode (direct).
