### ISSUE TITLE
Cosmos ChangeFeedOptions?

### ISSUE THREAD

**Issue by aragacalledpat** [Azure/azure-cosmos-dotnet-v3#766]
Hello!

Maybe I'm missing something here  - but the old change feed processor supported certain options like startFromBeginning and specifying only a particular partition to pull from.  It seems like these features no longer exist and I'm not sure if this is intentional or if they will be supported again in the future.  Thanks and sorry if I'm missing something obvious.

**Comment by bartelink** [comment]
bumping semi-related issue https://github.com/Azure/azure-cosmos-dotnet-v3/issues/616 @ealsur ;)

**Comment by ealsur** [comment]
@aragacalledpat Start from the beginning or any point in time is supported, see https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-change-feed-start-time

Pulling from a particular partition explicitly is not and there is no plan to support it.  There is a pulling mode in the works, but at no point it allows to specify a particular partition.
