### ISSUE TITLE
Misleading documentation comment in CosmosSerializer.FromStream

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-cosmos-dotnet-v3#771]
According to the documentation comment on `CosmosSerializer.FromStream<T>` the caller will "ensure the stream is disposed":
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/272aa1e80b0fd0bc7337332b9e355c151df21606/Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializer.cs#L16-L17

This is misleading. To me, "ensure it's disposed" means "dispose it if it isn't already", but the reality is that it checks that the stream is disposed and throw an exception if not. The wording could be made clearer.

**Comment by j82w** [comment]
You are right this could be a rewritten to make it easier to understand. Is the better or do you have another suggestion?

```
/// <summary>
/// Convert a Stream of JSON to an object. 
/// The implementation needs to dispose of the stream. 
/// This will prevent memory leaks if an exception is hit.
/// </summary>
```

**Comment by bartelink** [comment]
```
/// The implementation needs to dispose of the stream. 
/// This will prevent memory leaks if an exception is hit.
```
Maybe 
> Implementation is responsible for Disposing of the stream to avoid leaking it (including if X throws)

**Comment by thomaslevesque** [comment]
> Implementation is responsible for disposing of the stream to avoid memory leaks if an exception is thrown.
