### ISSUE TITLE
MongoDB samples 

### ISSUE THREAD

**Issue by vpaulino** [Azure/azure-cosmos-dotnet-v3#777]
I think it would be useful to have examples of using mongodb api with the popular drivers and also cosmosdb sdk latest version. Setup indexes CRUD operations  queries and agregation if supported !

**Describe the solution you'd like**
One csproj for each driver usage and in each one of them with classes for each use cases.

**Comment by j82w** [comment]
Hi @vpaulino ,

I think there is some confusion around the way Cosmos DB works. The Azure Cosmos MongoDB accounts use the [Mongo driver](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction). This repo is only for the .NET  SQL SDK which only works for the Cosmos DB SQL accounts.

**Comment by vpaulino** [comment]
Did not realized it was only about sql. I have asked this because i have observed diferent behaviour on the mongodb driver when comunicating with cosmosdb vs a real mongodb database.

**Comment by vpaulino** [comment]
The examples could be use to show that all features are compatible using the .net mongodb driver against mongodb database and cosmosdb.
