### ISSUE TITLE
Container migration from non-partitioned to partitioned does not work as in demo

### ISSUE THREAD

**Issue by bartsokol** [Azure/azure-cosmos-dotnet-v3#786]
**Describe the bug**
According to [this migration demo](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/CodeSamples/NonPartitionContainerMigration/Program.cs) reading the non-partitioned container (e.g. created in SDK v2) with SDK v3 should return the container with the `PartitionKeyPath` populated with default value (`_partitionKey`, I suppose). Instead, its value is `null` and the demo throws an exception.

**To Reproduce**
Run the `NonPartitionContainerMigration` demo.

**Expected behavior**
Container is read with default value of `PartitionKeyPath` other than null.

**Actual behavior**
Exception is being thrown as the read container does not have `PartitionKeyPath` set (property's value is null).

**Environment summary**
SDK Version: 3.0.0, 3.1.1, 3.2.0-preview2
OS Version: Windows

**Additional context**
I haven't found any working solution to migrate the container from non-partitioned to partitioned. This prevents us from migrating to the newer version of SDK and utilizing additional features, including partitioning. [Official docs](https://docs.microsoft.com/en-us/azure/cosmos-db/migrate-containers-partitioned-to-nonpartitioned) aren't really helpful and point to this not working demo.

**Comment by kirankumarkolli** [comment]
@simplynaveen20  can you please take a look?

**Comment by bartsokol** [comment]
Seems like the issue is related with the Cosmos emulator version; I had 2.2.x version installed, after updating to 2.5.6 demo started working, so did the reading and writing items using the new SDK with PK set to `PartitionKey.None`. Maybe some update of the docs indicating the minimal emulator version would be useful?
