### ISSUE TITLE
Can the SDK itself take "Primary" and "Secondary" auth keys and silently use either? This avoids client to have a policy based on exception to create new clients.

### ISSUE THREAD

**Issue by arunmannengal-zz** [Azure/azure-cosmos-dotnet-v3#789]
**Is your feature request related to a problem? Please describe.**
Can the SDK itself take "Primary" and "Secondary" auth keys and silently use either? This avoids client to have a policy based on exception to create new clients.

It could be an overload to CosmosClient( ,,,,) so that customers wanting to use it can use it 

**Describe the solution you'd like**
The CosmosClient creation should take in "primary" and "secondary" key so that if one of them is regenerated, it silently uses the other key to establish connection without the customers having to incorporate policy.

**Describe alternatives you've considered**
Customer policy based on exception. 

**Additional context**

**Comment by j82w** [comment]
The problem with that approach is that it will only ever allow a single key rotation. It might be better to add a new method like `client.UpdateKey("newKey");` which would allow the client to switch to the secondary key and then to the new primary key.

**Comment by ealsur** [comment]
Closed by https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3276
