### ISSUE TITLE
ReadNextAsync and ActivityId

### ISSUE THREAD

**Issue by meechy79** [Azure/azure-cosmos-dotnet-v3#793]
Is there any reason why the ActivityId is not returning from a call to ReadNextAsync? 

```
            FeedIterator<string> it = container.GetItemQueryIterator<string>("SELECT VALUE c.id FROM c");

            FeedResponse<string> result = await it.ReadNextAsync();

            Assert.IsNotNull(result.ActivityId);
```

**Comment by meechy79** [comment]
Could it be fixed by passing the CorrelatedActivityId in CosmosCrossPArtitionQueryExecutionContext

```
 CosmosQueryResponseMessageHeaders responseHeaders = new CosmosQueryResponseMessageHeaders(
                continauationToken: continuation,
                disallowContinuationTokenMessage: null,
                resourceType: this.queryContext.ResourceTypeEnum,
                containerRid: this.queryContext.ContainerResourceId)
            {
                ActivityId = this.queryContext.CorrelatedActivityId.ToString()
            };
```

**Comment by j82w** [comment]
Why do you want the activity id?

The reason it doesn't return an activity id is there is no way to combine an activity id for aggregate queries. The correlated activity might be useful for client side traces, but it is not sent to Cosmos DB. Which makes it useless for trying to troubleshoot any issues with the Cosmos DB service. The next release will have the Diagnostics which will have all the metrics with all the different responses, and should have the activity id for each response.

**Comment by j82w** [comment]
@meechy79 can you please respond to the above question?
