### ISSUE TITLE
IndexManagement project is missing?

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-cosmos-dotnet-v3#794]
>// We cover index policies in detail in IndexManagement sample project

The samples make [reference](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/bec2d8160d7423572cf8eeecb3eadb345e6cb19f/Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/Program.cs#L114) to a project called `IndexManagement` for indexing, but it's not found in the samples repo.

**Comment by ealsur** [comment]
This is a failure when the sample was ported to V3, the reference is to https://github.com/Azure/azure-cosmos-dotnet-v2/tree/master/samples/code-samples/IndexManagement

**Comment by SeanFeldman** [comment]
Thank you @ealsur for the confirmation.
Will it be ported?

**Comment by ealsur** [comment]
@SeanFeldman Working on it, expect the PR today

**Comment by SeanFeldman** [comment]
Thank you @ealsur.
