### ISSUE TITLE
skip/take?

### ISSUE THREAD

**Issue by vip32** [Azure/azure-cosmos-dotnet-v3#8]
will this new cosmos client support proper skip/take?

https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6350987--documentdb-allow-paging-skip-take

**Comment by DibranMulder** [comment]
Skip and Take are now supported! https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-sql-query#OffsetLimitClause
Should definitely be part of the first major release, in my opinion :)

**Comment by DibranMulder** [comment]
This issue can be closed with completing PR #249 
Maybe RequiredForGa tag can be added?

**Comment by vip32** [comment]
very very nice. are the other linq operators supported now (where, firstordefeault,orderby)?

**Comment by DibranMulder** [comment]
Those are already supported for quite a while, see the full list of supported operators here: https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-sql-query#SupportedLinqOperators

**Comment by vip32** [comment]
really, in the new v3 client? can't find anything in the samples

**Comment by j82w** [comment]
@simplynaveen20 is working on a [PR ](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/209) to add linq support to v3. The v3 SDK currently does not have any linq support.

**Comment by vip32** [comment]
exactly, we need proper linq in the **v3** client :)

**Comment by j82w** [comment]
PR #249 is now merged.
