### ISSUE TITLE
GetItemQueryStreamIterator not making concurrent requests

### ISSUE THREAD

**Issue by mark-manticore** [Azure/azure-cosmos-dotnet-v3#803]
**Describe the bug**
We have a database provisioned with 1100 RU's and we scaled it up to 25000 and then eventually back down (for load testing). We noticed that queries (without a specified partition key) made with GetItemQueryStreamIterator and QueryRequestOptions.MaxConcurrency = 10 would return a json result with "_count" of 0 and no documents in the array. The feed iterator would say there is more and contain a continuation token. Invoking ReadNextAsync returns the next set that also contains no documents. The third and final request returns the expected document that matches the query. Prior to scaling the database, the document would be found in the first query response.

**Expected behavior**
My understanding is that due to scaling up the database to 25000 we forced our documents to split into 3 physical partitions. From the documentation I was expecting that setting MaxConcurrency to a number > 1 would make requests to each partition in parallel and the result would not need to call ReadNextAsync if partition count < MaxConcurrency setting (ie the cosmos client would send requests concurrently and batch the results before returning to the caller).

**Actual behavior**
What I'm seeing is I have to exhaust the feed iterator by invoking and awaiting ReadNextAsync until I find my expected results regardless of the MaxConcurrency option. Is this intended? This seems like a performance issue if I must continue to query sequentially.

**Environment summary**
SDK Version: Tested with 3.1.0 and 3.1.1
OS Version: Windows 10

**Comment by j82w** [comment]
The SDK does send and receive request concurrently, but it does not batch the results. This allows the user to get the RUs and diagnostics for each request. It likely after the first page the following pages are already cached.

**Comment by mark-manticore** [comment]
Thanks for the clarification. I think I would have come to that conclusion if I received an IEnumerable or some collection of response objects. This does raise some more questions.

1. Is there a way for me to know whether a result from `ReadNextAsync()` was batch requested or not?
2. Should I assume the SDK will attempt to maximize concurrency and I only need to set it lower when desired?
3. If I set `MaxItemCount` to 1 and no partition key, will I receive 1 item (at most) per ReadNextAsync per physical partition? (ie 3 physical partitions can give me 0 to 3 total items?)
4. If I need 20 documents that meet some criteria and want to sort in descending order, is it true that I not only write the query but need to aggregate the results, resort in descending (as each physical partition only gave me its known order descending), and then return the 20 I need?

I've mostly been testing in the local emulator and scaling up with the actual service has uncovered some unexpected side effects in our application.

**Comment by j82w** [comment]
1. This should be possible after the next release where the diagnostics are being exposed.
2. Yes, the SDK will always attempt to maximize the concurrency. You can just set maxConcurrency to int.Max to be on the safe side.
3. MaxItemCount will always return 0 or 1 item per a ReadNextAsync as the MaxItemCount is 1. More then 1 item per a physical partition might be buffered. For example a distinct query will possibly need to load more items in case multiple partitions have the same value.
4. The SDK will aggregate the result from the different partitions, and do the order by logic. The SDK will only return the 20 items based on the query. 

The local emulator does not support multiple physical partitions. All the logical partitions are mapped to the same physical partition. You will get very different performance results testing against a real instance.

**Comment by mark-manticore** [comment]
Thanks for the fast response. I will close this issue as it sounds like it's working. Its good know the cosmos SDK is handling the complexities of questions 3 & 4. I was worried that because I wasn't receiving a batched result that I was getting raw responses from the partitions.
