### ISSUE TITLE
Default Connection Mode Inconsistent with Documentation

### ISSUE THREAD

**Issue by zhusulai** [Azure/azure-cosmos-dotnet-v3#812]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When a new CosmosClient is created, the ConnectionMode defaults to `Direct` instead of `Gateway` as described in various documentations.

**To Reproduce**
Create a new CoismosClinet by calling `new CosmosClient(endpointUrl, primaryKey)` and inspect the `ConnectionMode` property of the connection.

**Expected behavior**
ConnectionMode should be `Gateway`.

**Actual behavior**
ConnectionMode is `Direct`.

**Environment summary**
SDK Version: 3.1.1
OS Version (e.g. Windows, Linux, MacOSX): MacOSX 10.14.4

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
Hi @zhusulai ,

In the v3 SDK the default changed from Gateway mode to Direct. Direct mode has better performance. Can you share a link of the documentation so it can be updated?

**Comment by ealsur** [comment]
@zhusulai All the existing documentation (for example, https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips) talks about the DocumentClient (V2 SDK), not V3.

It makes sense that we should update the documentation to reflect the difference.
