### ISSUE TITLE
Auto generation of id when creating document is not working

### ISSUE THREAD

**Issue by ahesami** [Azure/azure-cosmos-dotnet-v3#815]
**Describe the bug**
Auto generation of id when creating an item does not work as previous version. We are trying to upgrade to 3.x and previously we had the practice to leave id generation to database to make sure its one entity that is generating ids, but all the parts of the code which we were creating documents (items) is now throwing the following exception:

CosmosException;StatusCode=BadRequest;SubStatusCode=0;ActivityId=1062eeb7-4963-4968-9fda-0a07f406c389;RequestCharge=1.24;Message=Response status code does not indicate success: 400 Substatus: 0 Reason: (Message: {"Errors":["The input name 'null' is invalid. Ensure to provide a unique non-empty string less than '255' characters."]}ActivityId: 1062eeb7-4963-4968-9fda-0a07f406c389, Request URI: /apps/DocDbApp/services/DocDbServer9/partitions/a4cb4955-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: RequestStartTime: 2019-09-18T02:12:56.5086626Z, RequestEndTime: 2019-09-18T02:12:56.5096598Z, Number of regions attempted: 1ResponseTime: 2019-09-18T02:12:56.5096598Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer9/partitions/a4cb4955-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 106903, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#106903, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Create, SDK: Microsoft.Azure.Documents.Common/2.2.0.0, Windows/10.0.17763 cosmos-netstandard-sdk/3.1.4).;

**To Reproduce**
In order to reproduce:

- Install Microsoft.Azure.Cosmos 3.1.1 Nuget.
- Implement a test document class which is the model to be added:

`
public class TestDocument
{
[JsonProperty("id")]
public string Id { get; set; }

[JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
public string Title { get; set; }

[JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "partitionKeyValue")]
public string PartitionKeyValue { get; set; }
}

`

- Initialize cosmos client: 
`var cosmosClient = new CosmosClient(ServiceEndPoint, AuthenticationKey, new CosmosClientOptions());`

- Create an instance of the test document class and don't set id:
`var testDocument = new TestDocument
			{
				Title = "test title",
				PartitionKeyValue = "test-partition"
			};`

- Add the document to the container:
`var response = await container.CreateItemAsync(testDocument, new PartitionKey(testDocument.PartitionKeyValue));`

**Expected behavior**
Id should get auto generated in database engine if it's not set.

**Actual behavior**
CosmosException with status code 400 is thrown complaining about id not being set. 

**Environment summary**
SDK Version: 3.1.1
OS Version : Windows 10
Target framework: netcoreapp2.0

**Comment by j82w** [comment]
In the v2 SDK it was checking each object. Then creating an id if it did not exist and inserting into the document. The problem with doing this is it takes a rather large performance hit, and it also caused confusion for some new users. In the v3 SDK we removed a lot of the work that was being done behind the scene to make users more aware of the performance impact.  Is there any reason you are not just setting id to a new guid?

**Comment by ahesami** [comment]
Thanks for the comment, yes we want to have one entity issuing the ids so we reduce the possibility of getting duplicates. Now we have to make big changes, we have more than one instance for our servers and this would make each server requiring to issue ids which defeats the purpose of having one entity, which used to be cosmos db core, to generate ids.

**Comment by j82w** [comment]
If you are using Guid to generate the id you shouldn't be getting collisions. The [v2 SDK](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/b5eee576104aa399951e6ab774d9527b851202a9/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L1897) just uses Guid.NewGuid() to generate the ids. If you want to do something similar in [v3 SDK with an extension method](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f2f4ea121c5393f80d0fbd7399213de001e252cd/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs#L1634).

**Comment by ahesami** [comment]
We ended up using a stored procedure to create documents. We can still keep the id generation in each collection.

**Comment by Ben-Russell** [comment]
Sorry to necro an old issue. But I somehow stumbled upon this same problem/error in typescript. I had been using null on the id of the item I was trying to create. Using 'undefined' instead, made it start to work again.

**Comment by dubnemo** [comment]
@Ben-Russell what do you mean by 'undefined'.  are you stating you set id to 'undefined' literally as a string?  We are trying to solve the same issue in LogicApps as Create_or_update_document_(V2) is not ready for prime time.  There does not seem to be way to pass a parameter to let Cosmos auto-increment the id like @identity columns in SQL Server.
