### ISSUE TITLE
AllowBulkExecution is internal for stable builds

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-cosmos-dotnet-v3#817]
`CosmosClientOptions.AllowBulkExecution` is public for the preview build `3.2.0-preview2`, but internalized for the final version `3.2.0`. I'd like to avoid using preview. What is the reason for this conditional compilation?

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/b045e33824760d3fa4d4a16268501f8efff98e44/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L355-L360

**Comment by j82w** [comment]
Bulk and Batch are still in preview because they are brand new features. We want to get more customer feedback and validation before making them part of the official build. This way if we get a lot of feedback that a breaking change needs to happen it can be done without doing a v4 SDK.

**Comment by SeanFeldman** [comment]
So for someone who wants to use it, they would not be able to use the latest release with fixes? Or will be a 3.x.y-preview?

**Comment by j82w** [comment]
The plan is to always do a preview release when a new official release is ready. For example there will be a 3.3.0 and a 3.3.0-preview package.

**Comment by SeanFeldman** [comment]
Got it. So `3.2.0-preview2` would be an equivalent to `3.2.0` that includes bulk option. Is that assumption correct?

**Comment by Dave76** [comment]
Hello,

I have been using the Bulk feature for the past week, and have some great results to share.  Would be happy to do so, but not sure who to direct them to. 

And to answer SeanFeldman's question, I am using the `3.2.0-preview2` version of the package. 

Dave

**Comment by j82w** [comment]
The preview features will not be included in the official release of the same version. A lot of the features in the SDK have changes in the Cosmos DB service. The changes to the service need to be ran for a while to verify the performance and stability of the new feature. We need to ship the SDK faster than the features are ready. To better explain how the versioning is currently working here is an example of the bulk feature.

Bulk is in 3.2.0-preview2
Bulk is not in 3.2.0
Bulk might be in 3.3.0 or it could still be a separate 3.3.0-preview package.

@Dave76 I think the best way to share your results is a github issue. That way everyone can see it.

**Comment by j82w** [comment]
@SeanFeldman please take a look at this [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/830) to update the changelog to make it a little bit clearer on how the preview versions work.
