### ISSUE TITLE
Cannot set an offer throughput on an existing container that uses the database shared throughput

### ISSUE THREAD

**Issue by ajk2018** [Azure/azure-cosmos-dotnet-v3#82]
If a container has not had it's throughput set before (i.e. we are using the DB shared throughput), and you try to call CosmosContainer.ReplaceProvisionedThroughputAsync(int) to set a throughput on that container.  The method will throw saying

"ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Throughput is not configured"  

This looks like it was possible using the older SDK per this example:  https://github.com/markjbrown/cosmosdb-offers/blob/master/ChangeOfferNetCore/Program.cs

If we should be using a different method to set a throughput on an existing container for this case, please let me know.

Thanks

**Comment by kirankumarkolli** [comment]
@simplynaveen20 can you please look into it?

**Comment by simplynaveen20** [comment]
@ajk2018  Error is due to the reason there is no offer for the container  , offer is configured on Database .
The V2 code sample you provided also throwing exception on UpdateCollectionOffer(), have you able to run  sample successfully ?

**Comment by ajk2018** [comment]
I had not tried yet since we were working with the 3.x SDK.  I'll try it out on our side and get back to you

**Comment by j82w** [comment]
@simplynaveen20 both a [database and a container](https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#set-throughput-on-a-database-and-a-container) can have RU's specified. Can the container throughput only be specified on creation?

**Comment by ajk2018** [comment]
@simplynaveen20 , I verified the provided example does not work. The query for offer fails.  I think the question still stands though that @j82w mentions well.  We seem to be hearing different things from different teams.

**Comment by simplynaveen20** [comment]
We cant update throughput on collection which was created without throughput. Portal, V2, V3 all in sync with this .
