### ISSUE TITLE
Guideline/recommendation for ASP.NET injection of different Container instances

### ISSUE THREAD

**Issue by liquidsnk** [Azure/azure-cosmos-dotnet-v3#829]
Hi!, I'm starting out with the SDK and would like any recommendations for my scenario.
I have an ASP.NET Core application and was thinking on injecting the appropriate Container instance into my repositories. 
The problem comes from ASP.NET injection not having a way to distinguish the different Container registrations I want to make (no named registrations), for example:
```
services.AddSingleton<Container>(userContainer);
services.AddSingleton<Container>(ticketContainer);

// :(
// class UserRepository { UserRepository(Container container) { } }
```

And as I don't control the creation of the Container directly but it's done through the CosmosClient, I cannot subclass it as a way to resolve the ambiguity on my repositories.
To get around this I've created a wrapper for Container and sub-classed it for each specific one:

```
// Something like this:
// class ContainerWrapper : Container { ContainerWrapper(Container container) { } }
// class UserContainer : ContainerWrapper
// class UserRepository { UserRepository(UserContainer container) { } }

services.AddSingleton<UserContainer>(new UserContainer(userContainer));
services.AddSingleton<TicketContainer>(new TicketContainer(ticketContainer));
```

This works well enough but it's cumbersome as my wrapper basically has to do a pass-through of all Container methods which is obviously not ideal.
I suppose it's more of a limitation of the DI container used, but would like to know your thoughts on how to deal with this.

1. I have the preference of  injecting the Container object because it seems cleaner to me, as opposed to injecting the CosmosClient or a factory function for Container. Do you think this is a good idea?
1. Do you see a better way to achieve this?
1. Is it a good idea to keep the Container objects as singletons or what are the recommended lifetime for them and CosmosClient?
1. Any other recommendations based on this scenario?

**Comment by ealsur** [comment]
@liquidsnk My take on DI and Singletons is that you would mainly use it to store objects that are reusable and expensive to create, or where (like the CosmosClient) it is recommended to maintain a single instance to benefit from how the object behaves (caching request routing like the CosmosClient).

In the case of the Container, the Container has no cost, so using DI doesn't make much sense. It would be arguable that the consumer of the DI instance doesn't need to know the container name (a string), but they are indirectly knowing it (they are asking for a specific container).

I would just keep the CosmosClient in DI, and call `GetContainer` when needed on the Controllers. They already know which container they want to access. You could have a helper class if you don't want to have strings around, that would be like:

    public static ContainerHelper
    {
        private static string database = "YourDatabase"; // This would also come from IConfiguration and not have a static class?
        private static string userContainer = "users";
        private static string ticketsContainer = "tickets";

        public static Container GetUserContainer(CosmosClient client) => client.GetContainer(ContainerHelper.database, ContainerHelper.userContainer);
        public static Container GetTicketsContainer(CosmosClient client) => client.GetContainer(ContainerHelper.database, ContainerHelper.ticketsContainer);
    }

It can be improved by leveraging IConfiguration, but serves as a rough example.

**Comment by liquidsnk** [comment]
Thanks you for your answer!. Is good to know that Container is currently a lightweight construct.
I like the option of being able to provide instances with what they need to work and no more, they don't even need to be aware of the lifetime of Container as long as it's equal to or exceeds their own. 
This might be very dependent on how these repositories are designed however (one per container), and I'm not entirely against injecting CosmosClient instead, so I'll keep it in mind in case the wrapper thing becomes unbearable!

**Comment by BarnabyDove** [comment]
@liquidsnk I share your thoughts on this.

You can support this entirely in the DI layer if you are happy to use implementation factory methods. Something like:

```
services.AddSingleton(_ => new CosmosClient(settings.CosmosDbConnectionString));

services.AddTransient<IUserService>(sp =>
{
    var cosmosClient = sp.GetRequiredService<CosmosClient>();
    var container = cosmosClient.GetContainer(settings.databaseName, "Users");

    return new UserService(container);
});

services.AddTransient<ITicketService>(sp =>
{
    var cosmosClient = sp.GetRequiredService<CosmosClient>();
    var container = cosmosClient.GetContainer(settings.databaseName, "Tickets");

    return new TicketService(container);
});
```

I like this approach, as it avoids having to introduce additional abstractions purely for the purposes of DI. I think `CosmosClient.GetContainer` is a lightweight proxy, so is OK to construct the containers from the `CosmosClient` on each lifetime in this way.

On the flip side, it does mean that you need to get all dependencies for each service and pass to the service ctors yourself. Only real issue with this is having to update the DI factory methods when the service dependencies change (e.g. another dependency is added).
