### ISSUE TITLE
Cosmos: Using Sytem.Configuration.ConfigurationManager, Not compatible with Xamarin.Android

### ISSUE THREAD

**Issue by ajcvickers** [Azure/azure-cosmos-dotnet-v3#83]
Moving from https://github.com/aspnet/EntityFrameworkCore/issues/15053 originally filed by 	@mbordogna.

When deploying to the Android emulator...
03-17 20:55:28.057 D/Mono    ( 5436): Assembly Loader probing location: 'System.Configuration.ConfigurationManager'.
03-17 20:55:28.057 F/monodroid-assembly( 5436): Could not load assembly 'System.Configuration.ConfigurationManager' during startup registration.
03-17 20:55:28.057 F/monodroid-assembly( 5436): This might be due to an invalid debug installation.
03-17 20:55:28.057 F/monodroid-assembly( 5436): A common cause is to 'adb install' the app directly instead of doing from the IDE.

The only remaining reference I have is coming from Microsoft.Azure.Comos.Direct's 
Depenency on System.Configuration.ConfigurationManager

### Steps to reproduce
Include EFCore.Cosmos Nuget in NetStandard Xamarin root project.
Start emulator, Try to deploy

### Further technical details
EF Core version: 3.19153.1
Database Provider:   Microsoft.EntityFrameworkCore.Cosmos
Operating system: Win10 
IDE:  Visual Studio 2017 15.9
Android Emulator x86 Oreo

Resolution Options: 
Replace ConfigurationManager with cross platform Supported Configuration implementation, or fix ConfigurationManager to support android.

**Comment by ajcvickers** [comment]
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/15053 since this dependency is brought in by the Cosmos SDK.

**Comment by ealsur** [comment]
Thanks @ajcvickers, we are already tracking this issue with `ConfigurationManager` and working on alternatives 😄

**Comment by kirankumarkolli** [comment]
@ealsur is this still an issue?

**Comment by ealsur** [comment]
@kirankumarkolli In the public SDK code we are still using ConfigurationManager is several places (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs#L57, https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs#L110, https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L56), and if somewhere inside the Direct package ConfigurationManager is still used,

**Comment by vecalion** [comment]
@kirankumarkolli may I kindly ask if there is any ETA on getting this fixed?

**Comment by kirankumarkolli** [comment]
@ealsur is the root of the problem ConfigurationManager not working in Xamarian.Android platform/emulator?

**Comment by ealsur** [comment]
The issue is the ConfigurationManager Netstandard package not supporting Xamarin.Android https://www.nuget.org/packages/System.Configuration.ConfigurationManager/

**Comment by kirankumarkolli** [comment]
@ealsur is it possible to detect Xamarian.Android at run-time?
Looking for ways to avoid ConfigurationManager invocations (of-course implementation details).

**Comment by j82w** [comment]
@kirankumarkolli will that not cause confusion if the settings are just ignored in Xamarin.Android since they would work in Linux and Windows OS?

**Comment by vecalion** [comment]
It looks like there are just a few places where ConfigurationManager is used. It would be great to abstract it away with an interface and let non-supported platforms to inject their own implementation.
