### ISSUE TITLE
Queries throw exception when connecting to cosmos emulator from linux docker containers

### ISSUE THREAD

**Issue by pistotniks** [Azure/azure-cosmos-dotnet-v3#834]
**Describe the bug**
Queries fail against emulator when running in not win x64 environments (e.g. docker linux containers) due to failure to generate a query plan.

**To Reproduce**
Create a database and collection using the cosmos db emulator
Write some code using the sdk to try and read from the collection using something like :

        public async Task<SomeResponse> ReadDocumentAsync(string someValue)
        {
            QueryDefinition sql = new QueryDefinition(
                    "select * from something s WHERE s.someField= @someValue")
                .WithParameter("@someValue", someValue);

            var container = _documentClient
                .GetContainer("databaseName", "collectionName");
            FeedIterator<SomeResponse> query = 
                container
                    .GetItemQueryIterator<SomeResponse>(
                        sql,
                requestOptions: new QueryRequestOptions()
                {                    
                    PartitionKey = new PartitionKey(someValue),
                    MaxItemCount = 1
                });

            while (query.HasMoreResults)
            {
                var doc = (await query.ReadNextAsync()).First(); //fails here
                return doc;
            }

            return null;
        }

**Expected behavior**
Should return a list of documents

**Actual behavior**
throws an exception (differs based on version of emulator)

**Environment summary**
SDK Version: 3.1.0, 3.2.0 or 3.2.0-preview
OS Version (e.g. Windows, Linux, MacOSX): Windows 10 x64
Cosmos Emulator Versions: 2.2.1.0 and 2.5.6.0

**Additional context**
After some investigation we have come to some conclusion as to the cause of the issue
In CosmosQueryExecutionContextFactory, there is a branch that seems to make a network call for a query plan if not on x64 os, which fails in different manners based on the version of the emulator.

	PartitionedQueryExecutionInfo partitionedQueryExecutionInfo;
	            if (this.CosmosQueryContext.QueryClient.ByPassQueryParsing() && TestFlag)
	            {
	                // For non-Windows platforms(like Linux and OSX) in .NET Core SDK, we cannot use ServiceInterop, so need to bypass in that case.
	                // We are also now bypassing this for 32 bit host process running even on Windows as there are many 32 bit apps that will not work without this
	                partitionedQueryExecutionInfo = await QueryPlanRetriever.GetQueryPlanThroughGatewayAsync(
	                    this.CosmosQueryContext.QueryClient,
	                    this.CosmosQueryContext.SqlQuerySpec,
	                    this.CosmosQueryContext.ResourceLink,
	                    cancellationToken);
	            }
	            else
	            {

We have tried this against two version of the cosmos emulator
2.2.1.0 and 2.5.6.0, each throwing a slighty different exception when attempting to handle the response for the query plan. 
This however works correctly when running against a real cosmos db account

**Comment by j82w** [comment]
It should be working with the latest emulator. The older emulators should throw since they don't have the new endpoint to get the query plan. @pistotniks can you please add the exception for both emulator versions?

**Comment by j82w** [comment]
@pistotniks I'm closing this issue since you haven't responded. If you are still hitting please re-open the issue.
