### ISSUE TITLE
Unauthorized after 3.2.0 upgrade on Linux and macOS

### ISSUE THREAD

**Issue by bricelam** [Azure/azure-cosmos-dotnet-v3#847]
We (the Entity Framework team) tried updating to version 3.2.0 and our CI started failing with the following exception on Linux and macOS.

Version 3.1.1 works fine.

```
System.InvalidOperationException: Delete database failed. Status code: Unauthorized. Message: 'The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'gettue, 24 sep 2019 16:01:24 gmt'ActivityId: 20370510-e924-4a37-9a37-6ca2becd62e9, Microsoft.Azure.Documents.Common/2.5.1, Darwin/10.13 cosmos-netstandard-sdk/3.2.1'
   at Microsoft.EntityFrameworkCore.Cosmos.Storage.Internal.CosmosClientWrapper.DeleteDatabaseOnceAsync(DbContext _, Object __, CancellationToken cancellationToken) in /_/src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs:line 194
```

cc @Pilchie @ajcvickers @AndriySvyryd

**Comment by j82w** [comment]
@bricelam is this against the emulator or production?

**Comment by smitpatel** [comment]
Production. Our library depends on netstandard2.1 so we cannot target netstandard1.3.

**Comment by j82w** [comment]
Is this consistently happening on every request?

**Comment by bricelam** [comment]
Three times in a row on the first call of the test suite. (which caused the rest of the suite to not run)

**Comment by j82w** [comment]
Did you verify going back to 3.1.1 worked? This exception normally means the key is not correct or the machine has clock skew which is causing the time stamp to be wrong.

**Comment by milismsft** [comment]
also can you please confirm if the collections/containers get created every time the test is run?

**Comment by milismsft** [comment]
It will be great if we can get the name of the account, the database and the regions used to further help with the investigation.

**Comment by smitpatel** [comment]
Reverting back to 3.1.1 worked.
Collections/Containters/Database are recreated for each test suite (or test run for assembly).
Azure Cosmos Db account: ef-nightly-test
Region: West US
Database: NonExistent appended by a random guid.

**Comment by smitpatel** [comment]
Also the database actually does not exist on server. We just try to delete it.

**Comment by j82w** [comment]
Any chance you can provide a basic repo of the issue?

**Comment by j82w** [comment]
We verified that 3.2.0 works on a Mac connecting to prod. Can you please provide a repo?

**Comment by AndriySvyryd** [comment]
It doesn't repro anymore for me, perhaps it was an Azure issue.

**Comment by j82w** [comment]
I'm going to close the issue then. If it happens again feel free to re-open it.
