### ISSUE TITLE
Request Latency is missing in v3 responses

### ISSUE THREAD

**Issue by ylibrach** [Azure/azure-cosmos-dotnet-v3#864]
**Is your feature request related to a problem? Please describe.**
In v2 of the library, responses had a `RequestLatency` field which showed the latency of the raw request against Cosmos DB. In v3, it seems that this field is no longer available. I see that internally, the library is storing this value within the specific `CosmosDiagnostics` class for each response type, but it's not publicly accessible without deserializing through `CosmosDiagnostics.ToString()`, which is not a performant or efficient solution.

**Describe the solution you'd like**
The `Response<'T>` type should expose the `RequestLatency` value, or else provide an easily consumable form of `CosmosDiagnostics` that is not internal.

**Describe alternatives you've considered**
Deserializing the `CosmosDiagnostics.ToString()`, but the cost to do this for every single request is too heavy.

**Comment by j82w** [comment]
What's the use case for just needing the request latency? In v3 the diagnostics are rather generic so it can easily be modified to add or remove values based on feedback and real world troubleshooting that is done so it easier to root cause issues in the future. There has also been a lot of scenarios where user will only record the activity id and the latency or other partial information. Without all the information in the diagnostics it makes it very difficult to impossible to root cause latency issues.

**Comment by ylibrach** [comment]
We use request latency for multiple purposes, most important of which are:
1. Monitor query performances against Cosmos DB and be alerted to spikes
2. We have our own autoscaler that automatically scales both a) the Cosmos collection's throughput; and b) maximum thread parallelization for each of our microservices. The autoscaling logic relies heavily on understanding request latencies - in addition to RUs, etc - in order to make determinations such as single-thread RU/s which helps us throttle our services and/or increase/decrease collection throughputs.

I'm not sure if I understand your concern regarding v3 diagnostics? The diagnostics objects in v3 are internal and not publicly consumable. How would publicly exposing the `RequestLatency` inside these diagnostics objects cause any problems?

**Comment by j82w** [comment]
@kirankumarkolli what are your thought on exposing the request latency?

Based on the description it sounds like the application is doing the scaling. The better design here is to log the information and have a separate application relying on telemetry to do the scaling. This way the container can be scaled with multiple application instances.

**Comment by ylibrach** [comment]
> Based on the description it sounds like the application is doing the scaling. The better design here is to log the information and have a separate application relying on telemetry to do the scaling. This way the container can be scaled with multiple application instances.

We actually have both:
1. The individual microservices are throttling themselves (max parallelization) based on their own single-thread RU/s consumed over the past several minutes (this is where Request Latency comes into play), compared to total RU consumed by all microservices against a specific collection.
2. There is a separate dedicated autoscaler microservice which monitors the total aggregate RUs hitting each collection across all microservices, and makes throughput adjustments for the collections accordingly.

**Comment by ealsur** [comment]
@ylibrach You can get the required statistics for Autoscale from Azure Monitor: https://docs.microsoft.com/en-us/azure/cosmos-db/logging#interpret which can be read programmatically to generate an autoscale logic.

I have trouble understanding point #1. RequestLatency is the time it takes for the request to go from the origin and get back, if there is a network blip or your connections/sockets are starved, that latency will be affected. How is that related to RU consumption and self throttling? That seems to be related to RequestCharge.
