### ISSUE TITLE
Impossible to delete a Document with empty partition key

### ISSUE THREAD

**Issue by Simon-Bru** [Azure/azure-cosmos-dotnet-v3#879]
**Description**
Using the SDK, it is impossible to delete a document which has no partition key. In my collection some documents will have no partition keys, and those will be removed and replaced by another document with a good partition key later in the workflow. However, the SDK doesn't allow me to delete the empty partition key's document.

**Reproduce**
To reproduce, create any document with no partition key, then fetch it in your c# code and try to delete it using: 
```
await client.DeleteDocumentAsync(anonymousEvent.SelfLink);
```
It will give you the following error: 
![image](https://user-images.githubusercontent.com/15661640/66384675-7efc4c80-e9bf-11e9-86e5-66c594eb94ba.png)

After some research I found I have to give a partitionKey in requestOptions so I tried this code: 
```
await client.DeleteDocumentAsync(anonymousEvent.SelfLink, new RequestOptions { PartitionKey = new PartitionKey(anonymousEvent.IdCustomer) });

// OR 
await client.DeleteDocumentAsync(anonymousEvent.SelfLink, new RequestOptions { PartitionKey = new PartitionKey(null) });

// OR 
await client.DeleteDocumentAsync(anonymousEvent.SelfLink, new RequestOptions { PartitionKey = new PartitionKey("") });
```
But it all gave me the following error: (Obviously it doesn't find the document as it searches only in the provided partition which is probably not found)
![image](https://user-images.githubusercontent.com/15661640/66384628-60965100-e9bf-11e9-876f-459ee446da7f.png)

**Expected behavior**
The options parameter should be optional and the document should be deletable only by selflink or with crosspartition option.

**Actual behavior**
Unable to locate an empty partition key

**Environment summary**
SDK Version: 3.0.3
OS Version Windows

**Comment by j82w** [comment]
There is a few different items to cover here.
1. This is not the v3 SDK. The exception shows version 2.2.0. v2 issues should be posted to the [v2 repo](https://github.com/Azure/azure-cosmos-dotnet-v2). The v3 SDK also doesn't have any methods named in the example.
2. If you are starting a new application I would strongly recommend using the v3 SDK. It's far more user friendly.
3. A document or item in Cosmos DB is identified by 2 values. The id and the partition key value. I would recommend reading the documentation around [partition keys](https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview). TLDR: PartitionKey correlates to what machine in Cosmos. The id is where in that machine the document is. This allows true horizontal scaling. 
4. It looks like you are not providing the correct partition key value here. What partition key path did you define when creating the collection?

**Comment by j82w** [comment]
I'm closing this issue since it's not related to the v3 SDK.

**Comment by Simon-Bru** [comment]
Ah yes I'm sorry about that I'm using v2 indeed as I use the Azure function binders.
Thank you for your help
