### ISSUE TITLE
Allow to set the JSON Serializer to DateTimeOffset

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/azure-cosmos-dotnet-v3#880]
**Is your feature request related to a problem? Please describe.**
I want to store my Date Time values in a `DateTimeOffset`. I have a place where is it convent to get the `JObject` from the cosmos DB and work with the `DateTimeOffset`. I found no easy way to set Json parser to `DateTimeOffset`.
(in v2 I had
```csharp
                    serializerSettings: new JsonSerializerSettings
                    {
                        DateParseHandling = DateParseHandling.DateTimeOffset
                    }
```
)

**Describe the solution you'd like**
I want to configure this in a similar way as in v2 of the sdk:
```csharp
                    .WithSerializerOptions(new CosmosSerializationOptions
                    {
                        DateParseHandling = DateParseHandling.DateTimeOffset
                    }
```

**Describe alternatives you've considered**
I think I need to write a custom class like: https://gist.github.com/richstokoe/c82fc831c6b4020926f5b5f772f7cd70

**Additional context**
#551 Add support for JSON.net JsonSerializerSettings
#650 Enabling serialization customization through CosmosSerializerOptions

**Comment by j82w** [comment]
The best option is to do a custom class like you linked to. The v3 SDK tried to reduce has many Newtonsoft dependencies as possible to make it easier to convert to use the newer System.Text.Json serializer. The current features in `CosmosSerializationOptions` are the same in both serializer so it's easy to map between the to serializer.

**Comment by StefanSchoof** [comment]
Sounds reasonable. I had hopped this is only a option that simply needs to add. Is there an issue to track for the System.Text.Json convertion? System.Text.Json solves the DateTime vs DateTimeOffset in a nicer way for me and than I no longer need my Custom Serializer.

**Comment by j82w** [comment]
We don't currently have a time frame. We are working towards becoming complaint with the [Azure SDK for NET](https://github.com/Azure/azure-sdk-for-net) repo.

**Comment by ravibha-hub** [comment]
@StefanSchoof  Were you able to fix this issue without implementing a custom serializer?

**Comment by StefanSchoof** [comment]
No, I use one like https://gist.github.com/richstokoe/c82fc831c6b4020926f5b5f772f7cd70
