### ISSUE TITLE
ChangeFeedProcessorBuilder.WithLeaseContainer requires a non-partitioned Container

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#886]
**Describe the bug**
ChangeFeedProcessorBuilder.WithLeaseContainer requires a non-partitioned Container that exists, with no means in the sdk to create one

**To Reproduce**
```
var leaseContainer= _cosmosClient.GetContainer(database.Id, "someLeaseValue")
_container.GetChangeFeedProcessorBuilder(processorName, onChangesDelegate)
                .WithLeaseContainer(leaseContainer)
                .WithInstanceName(Guid.NewGuid().ToString())
                .Build();
```

**Expected behavior**
Either provide a method to create a non-partitioned container or modify ```ChangeFeedProcessorCore<T>.InitializeLeaseStoreManagerAsync``` so that is creates one if none exists.

**Actual behavior**
```Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: 404 Substatus: 0 Reason: (Message: {"Errors":["Resource Not Found"]}```

**Environment summary**
SDK Version: 3.0.100
Cosmos: 3.0.2
OS Version: Windows 10

**Comment by j82w** [comment]
I recommend taking a look at the [samples](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/06b961a6c181995590097f764b296403169974f8/Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs#L143).

**Comment by fuocor** [comment]
The sample assumes that the lease container exists and the SDK V3 does not allow me to create one.
The unit tests in the repo use an internal method to post a REST call to create the lease container.

All I'm trying to point out is the fact that the SDK V3 does not seem to have a clear cut method to allocate a lease container.

**Comment by bartelink** [comment]
@fuocor [you need to nominate `"id"` as the partition key](https://github.com/jet/equinox/blob/master/src/Equinox.Cosmos/Cosmos.fs#L550)

**Comment by ealsur** [comment]
@fuocor our tests create the lease collection: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/BaseChangeFeedClientHelper.cs#L19, https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs#L15 with the `/id` as PK for the leases as @bartelink mentions.

We have 1 test that uses the internal method to actually verify that we are backward compatible. https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs#L82

**Comment by fuocor** [comment]
Sorry I seem to have missed the obvious. I had found a helper that was making a rest call

**Comment by ealsur** [comment]
It's not a problem, that helper can throw people off. But we needed to do it in order to verify people migrating from V2 could still use CFP in V3 and not lose their current progress/data.
