### ISSUE TITLE
Could not load file or assembly 'Microsoft.Azure.Cosmos.Direct, Version=3.3.0.0

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#894]
**Describe the bug**
I am using a project reference to ```Microsoft.Azure.Cosmos``` due to code changes related to my pull request. Everything works fine locally but when I publish my unit tests to the azure build pipeline i'm getting ```Could not load file or assembly 'Microsoft.Azure.Cosmos.Direct, Version=3.3.0.0```

I noticed some funky project includes in the SDK project. I was wondering what I need to do to get the assemblies pushed out for my unit tets.

**Expected behavior**
No Exception

**Actual behavior**
Cannot load assembly

**Environment summary**
SDK Version: 3.0.100
Cosmos: Source
OS Version Windows 10

**Comment by ealsur** [comment]
Do you mean the unit tests in this repo or a unit test project that you created that targets the SDK?

**Comment by fuocor** [comment]
A unit test I created...

**Comment by j82w** [comment]
@fuocor since its a project reference you have to add a reference to nuget [Microsoft.Azure.Cosmos.Direct](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Direct/).

@ausfeldt please correct me if I'm wrong.

**Comment by ausfeldt** [comment]
@j82w correct

**Comment by fuocor** [comment]
great... I had it in the wrong project
