### ISSUE TITLE
Possible imporvements by comparison to a homemade API

### ISSUE THREAD

**Issue by Ponant** [Azure/azure-cosmos-dotnet-v3#9]
Hi Team,
I come to you because I have been struggling with similar issues around the object model of the old sdk when I first started using documentdb a year ago and I made a homemade api that resembles in some aspects the object model you now have. I said to myself I can now drop my api after reviewing this 3.0 preview, but I think there are a few things you might be interested to include in your sdk (I did not yet fully looked at the preview sdk, though).

1) One of the things is to consider that a cosmodb account corresponds to exactly one client and users can have several several accounts. The idea is, in the same way as cosmosclient has many databases and you locate a database with databases["id"], you would have CosmosContext that includes all CosmosClient (i.e. accounts) with indexing to retrieve them. It was handy for me already to test localhost and on azure and there are compliance reasons why you would need more than one cosmos account. Above all it reflects best what the structure of cosmosdb is:

-User has many accounts, each account has many databases, each database has many containers, each container has many items

2) As we had situations where we want to make sure that certain poco classes belong to certain collections and should be forbidden to be accidentally persisted on others, I introduced a registration of each poco that is entended to be stored in documentdb and the program which will throw if a given poco is not allowed. This entity check can be circumvented by a Boolean. However, this is perhaps more along the lines of a details implementation.

3) Add DI injection for .Net Core, so far I am registering an application context as a singleton following the recommendation of documentdb (DocumentClient.OpenAsync). And do the same for uwp Xamarin etc with lazy loading of a singleton instance.

For .Net Core this would give the following fairly friendly flow

**Startup.cs**

`            services.AddGlobalDocumentDbContext<ApplicationGlobalDocumentDbContext>();`

**ApplicationGlobalDocumentDbContext which mimics EF strategy**

 ```
public sealed class ApplicationGlobalDocumentDbContext : GlobalDocumentDbContext
{
            protected override void OnConfiguring(GlobalDocumentDbContextOptionsBuilder optionsBuilder)
{
            var client1 = new DocumentClient("localhost".ToDocumentUri(), CosmosDbConstants.emulatorPrimaryKey,
            new ConnectionPolicy { ConnectionMode = ConnectionMode.Direct, ConnectionProtocol = Protocol.Https });
            var client2 = new DocumentClient("account2".ToDocumentUri(), CosmosDbConstants.emulatorPrimaryKey);

            optionsBuilder
            .AddClient(client1)
            .AllowEntity<Item>("dbperson", "col2", "col1")
            .AllowEntity<Item>("dbperson", "colperson")
            .AllowEntity<A<Item, Person>>("dbperson", "colperson")
            .AllowEntity<Search>("dbsearch", "colsearch")
            .AllowEntity<Person>("dbperson", "colperson");

            optionsBuilder
                .AddClient(client2)
                .AllowEntity<Item>("dbitem", "col2", "col1");
}

        public IDocumentDbRepository<Item> Items { get; set; } = new DocumentDbRepository<Item>();
        public IDocumentDbRepository<Person> People { get; set; } = new DocumentDbRepository<Person>();
        public IDocumentDbRepository<A<Item, Person>> AItemPeople { get; set; } = new DocumentDbRepository<A<Item, Person>>();
        public IDocumentDbRepository<Search> Searches { get; set; } = new DocumentDbRepository<Search>();

}

```

**DI on a controller**

```
public class HomeController : Controller
{
            private readonly ApplicationGlobalDocumentDbContext _globalDocumentDbContext;

      public HomeController(ApplicationGlobalDocumentDbContext globalDocumentDbContext)
      {
            _globalDocumentDbContext = globalDocumentDbContext;
      }

      public async Task<IActionResult>Index()
      {
                var myitem = new Item { Name = "Item's name", FirstName = "Item's FirstName", ItemProperty = "Item Property" };
                var myperson = new Person { FirstName = "Person's FirstName", LastName = "Person's LastName" };

                //Retrieve the document collection objects (you would normally define these outside of a view method)
                var documentCollection = _globalDocumentDbContext["localhost", "dbs/dbperson/colls/colperson"];
                var searchCollection = _globalDocumentDbContext["localhost", "dbs/dbsearch/colls/colsearch"];

                //Create an item in documentdb and return the result projected onto a ViewModel
                var itemViewModel = await _globalDocumentDbContext.Items.AddAsync<ViewModel>(documentCollection, myitem);

                //Create a person in documentdb and return the person (no casting)
                var person = await _globalDocumentDbContext.People.AddAsync(documentCollection, myperson);

                //Update person and return a ViewModel. A replace is typically followed by a FindById (not shown)
                person.FirstName = "updated person FirstName";
                var personVieModel = await _globalDocumentDbContext.People.ReplaceAsync<ViewModel>(documentCollection, person);

                //Find
                var searchString = "irst";

                var feedOptions = new FeedOptions { MaxItemCount = -1 };

                Expression<Func<Item, bool>> expression = x => x.FirstName.ToLower().Contains($"{searchString}".ToLower());

                //find at most numOfItems = 17 items and project to view model (use x=>x in the second lambda for a one to one mapping)
                var numOfItems = 17;
                var find = await _globalDocumentDbContext.Items
                    .FindAsync(numOfItems, expression,
                    x => new ViewModel { Id = x.Id, Type = x.Type, Name = x.Name }, documentCollection, feedOptions);

                //Find on page 2, pagesize = 17 and project to view model
                var findOnRank = await _globalDocumentDbContext.Items
                    .FindOnPagedAsync(2, 17, expression,
                    x => new ViewModel { Id = x.Id, Type = x.Type, Name = x.Name }, documentCollection, feedOptions);

                //Operate on a different collection
                var search = await _globalDocumentDbContext.Searches.FindByIdAsync(searchCollection, "searchId");
                return new JsonResult(new
                {
                    //Print all collections you have registered
                    collections = _globalDocumentDbContext.GetDocumentCollections("localhost"),

                    a = findOnRank,
                    b = find
                });

```

I will have to rework this whole api since, from my understanding, I do not need anymore the uri's, which is great, and I would gladly drop it out to use only the new sdk, so I wonder if you would be interested in implementing some of these features/concepts I will be happy to help of course, hence my post.

**Comment by kirankumarkolli** [comment]
@Ponant currently we are focusing on having a single account client part of GA effort. Post that we can look into it based on such asks. 

On limiting a type to a container/collection: Cosmos is a no-schema no-sql data store. It allows heterogeneous items. Application pattern limiting types is interesting and we will explore it post GA.

@j82w can you please explore on DI part?

**Comment by Ponant** [comment]
@kirankumarkolli , sorry your sentence is confusing, how can I help?

**Comment by kirankumarkolli** [comment]
@j82w will explore DI part mentioned above. 

Others we will explore post V3 SDK GA.
