### ISSUE TITLE
Add support for IAsyncEnumerable<T>

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-cosmos-dotnet-v3#903]
**Is your feature request related to a problem? Please describe.**

The API for enumerating query results isn't great, because it forces the user to be aware of the fact that the results are fetched page by page:
```csharp
var iterator = ...
while (iterator.HasMoreResults)
{
    var page = await iterator.ReadNextAsync();
    foreach (var item in page)
    {
        ...
    }
}
```

**Describe the solution you'd like**

The `FeedIterator<T>` API is useful, because it gives you more information (e.g. request charge), but in most cases the user just wants the results, so it would be nice to have a higher level abstraction. The `IAsyncEnumerable<T>` interface seems perfect for this.

There could be an `AsAsyncEnumerable` extension method like this:

```csharp
public static async IAsyncEnumerable<T> AsAsyncEnumerable<T>(
    this FeedIterator<T> iterator,
    [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
    while (iterator.HasMoreResults)
    {
        var page = await iterator.ReadNextAsync(cancellationToken);
        foreach (var item in page)
        {
            cancellationToken.ThrowIfCancellationRequested();
            yield return item;
        }
    }
}
```
The consuming code would be simplified to this:

```csharp
var iterator = ...
await foreach (var item in iterator.AsAsyncEnumerable())
{
    ...
}
```

**Describe alternatives you've considered**
N/A

**Additional context**

The `await foreach` feature was introduced in C# 8, so this would only be useful to people already using C# 8.
However, the `Microsoft.Bcl.AsyncInterfaces` package is compatible with netstandard2.0 and net461, so it wouldn't require running .NET Core 3.

**Comment by ealsur** [comment]
We are working on this at the moment 😄

**Comment by thomaslevesque** [comment]
Awesome!

**Comment by ealsur** [comment]
@thomaslevesque See the V4 (preview) package https://docs.microsoft.com/en-us/azure/cosmos-db/create-sql-api-dotnet-v4#query-the-items

**Comment by thomaslevesque** [comment]
Cool, thanks!

**Comment by cfindlayvcs** [comment]
@ealsur , I just tried this with the latest version of the Cosmos DB API (3.15.0) on .NET Core 3.1 and `GetItemQueryIterator<>` does not return `IAsyncEnumerable`. I get this:

![image](https://user-images.githubusercontent.com/73087164/100831721-75368200-34ba-11eb-83a6-c13926c60ec5.png)

**Comment by lorenpaulsen** [comment]
> @ealsur , I just tried this with the latest version of the Cosmos DB API (3.15.2) on .NET Core 3.1 and `GetItemQueryIterator<>` does not return `IAsyncEnumerable`. I get this:
> 
> There is no 4.0 preview package.
> 
> ![image](https://user-images.githubusercontent.com/73087164/100831721-75368200-34ba-11eb-83a6-c13926c60ec5.png)

The 4.0 preview package can be found here: https://www.nuget.org/packages/Azure.Cosmos

**Comment by thomaslevesque** [comment]
> The 4.0 preview package can be found here: https://www.nuget.org/packages/Azure.Cosmos

Indeed. Honestly, I'm not sure how we're supposed to guess that.
- The README says it's the repo for "Version 3", with no mention of a version 4 
- The README still points to the old package and doesn't mention the new one
- The old package doesn't mention that it's been superseded by a new one
- The new package points to this repo, which doesn't seem to know anything about the new package

I think I discovered the new package by accident in an article. There's almost no chance a new user will find it if they end up on this repo.

**Comment by paulirwin** [comment]
Is there an anticipated release date for the v4 SDK? It looks like the last preview came out almost a year and a half ago. Thanks for any updates!

**Comment by Socolin** [comment]
Hello, is there any ETA for this ? It look like the v4 is abandon since 2 year, is there any reason for this ?

**Comment by bartelink** [comment]
See https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2976

**Comment by dersia** [comment]
as of the comment https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2976#issuecomment-1495135859 I'd like to ask to reopen this issue. a feature like this needs to in the sdk, if it's not v4, then in v3, but this is very much needed.

**Comment by onionhammer** [comment]
Any movement on this?
