### ISSUE TITLE
Support multiple ChangeFeed handlers for a single container

### ISSUE THREAD

**Issue by Ceridan** [Azure/azure-cosmos-dotnet-v3#904]
**Is your feature request related to a problem? Please describe.**
In situations when you keep different types of documents in a single container you have a problem with change feed processor builder. Let me explain. Currently, you can build change feed processor like this:
```csharp
var changeFeedProcessor = database
	.GetContainer("MyContainer")
	.GetChangeFeedProcessorBuilder("MyContainerChangeFeed", HandleChangesAsync)
        ...
        .Build();
```
where `HandleChangesAsync` has a type of `ChangesHandler<T>`. Here I have a problem. The type `T` here should be a type of a document which I want to feed. It works great if I have only one type of documents in the container. If I have more than one type of documents the only way how to deal with it is to use `dynamic` type and create handler which will manually parse the change object as JSON and cast it to the correct type. It saves me a lot of time and make code much cleaner if I can attach multiple handlers to the single container in the change feed processor builder.

**Describe the solution you'd like**
It would be great to have API like this:
```csharp
ChangesHandler<DocumentType1> HandleChangesAsync1 = (changes, token) => { ... };
ChangesHandler<DocumentType2> HandleChangesAsync2 = (changes, token) => { ... };

var changeFeedProcessor = database
	.GetContainer("MyContainer")
	.GetChangeFeedProcessorBuilder("MyContainerChangeFeed")
        .WithHandler(HandleChangesAsync1)
        .WithHandler(HandleChangesAsync2)
        ...
        .Build();
```

**Comment by Ceridan** [comment]
Another possible solution could be extension of API that accepts array of handlers in the `GetChangeFeedProcessorBuilder` method like this:
```csharp
ChangesHandler<DocumentType1> HandleChangesAsync1 = (changes, token) => { ... };
ChangesHandler<DocumentType2> HandleChangesAsync2 = (changes, token) => { ... };

var changeFeedProcessor = database
	.GetContainer("MyContainer")
	.GetChangeFeedProcessorBuilder("MyContainerChangeFeed", new [] { HandleChangesAsync1, HandleChangesAsync2 })
        ...
        .Build();
```

**Comment by ealsur** [comment]
I'm not sure I follow the requirement, why can't your HandleChangesAsync1 call HandleChangesAsync2? They are all inside the same process.

**Comment by ealsur** [comment]
If you could attach multiple delegates, you would still get changes across all of them, there is no way to apply a filter based on the class you map to T.

**Comment by Ceridan** [comment]
> I'm not sure I follow the requirement, why can't your HandleChangesAsync1 call HandleChangesAsync2?

Yes, I can call HandleChangesAsync2 from HandleChangesAsync1, but I will lost data. For example:

```csharp
class DocumentType1
{
    public string Id { get; set; }
    public int Type { get; } = 1; // this property allows me to distinct two types of documents
    public string SomeData { get; set; }
}

class DocumentType2
{
    public string Id { get; set; }
    public int Type { get; } = 2; // this property allows me to distinct two types of documents
    public string YetAnotherData { get; set; }
}

ChangesHandler<DocumentType1> HandleChangesAsync1 = (changes, token) => { ... };
ChangesHandler<DocumentType2> HandleChangesAsync2 = (changes, token) => { ... };

var changeFeedProcessor = database
	.GetContainer("MyContainer")
	.GetChangeFeedProcessorBuilder("MyContainerChangeFeed", HandleChangesAsync1)
        ...
        .Build();
```

In this case inside the handler `HandleChangesAsync1` I will already obtain changes collection typed as `DocumentType1` and if I even call the `HandleChangesAsync2` from  `HandleChangesAsync1` the value of `YetAnotherData` property will be lost.

> If you could attach multiple delegates, you would still get changes across all of them, there is no way to apply a filter based on the class you map to T.

You are right. I thought about this problem. You need some base handler, let's call it `dispatcher` to cope with this situation. Currently I implemented dispatcher by myself, but it would be great If it become a part of CosmosClient. Here is what I actually do:

```csharp
public async Task HandleChangesDispatcherAsync(IReadOnlyCollection<dynamic> changes, CancellationToken ct = default)
{
    var jsonChanges = changes.Select(change => (JObject) change).ToList();

    var documentType1Changes = jsonChanges.Where(change => change.GetValue("type").ToObject<int>() == 1);
    if (documentType1Changes.Any())
    {
        var changesToHandle = documentType1Changes.Select(change => change.ToObject<DocumentType1>()).ToList().AsReadOnly();
        await HandleChangesAsync1(changesToHandle, ct);
    }

    var documentType2Changes = jsonChanges.Where(change => change.GetValue("type").ToObject<int>() == 2);
    if (documentType2Changes.Any())
    {
        var changesToHandle = documentType2Changes.Select(change => change.ToObject<DocumentType2>()).ToList().AsReadOnly();
        await HandleChangesAsync2(changesToHandle, ct);
    }
}

...

var changeFeedProcessor = database
	.GetContainer("MyContainer")
	.GetChangeFeedProcessorBuilder("MyContainerChangeFeed", HandleChangesDispatcherAsync)
        ...
        .Build();
```
As you can see I am using the `dynamic` type in the dispatcher and deal with changes as the raw json files. I manually parse it rely on `Type` property value and thus I extract the target type, than I can cast json to this typet and call proper handler. To make this code more general it could accepts some predicate (some rule) how to distinct documents (currently document requires to have `Type` property in my example) in the collection.

**Comment by ealsur** [comment]
Ideally for this scenario, from a performance point of view, the filtering should be on the server side, but this is not currently possible.

Sadly, doing this client-side filtering is the only option for scenarios where you use a Type pattern (different schemas in the same container).

**Comment by Ceridan** [comment]
From your experience how often do you meet Type pattern in practice? Should CosmosClient support ChangeFeeds in situation like this or not?

**Comment by ealsur** [comment]
In order to support the Type pattern effectively and without a compute bottle beck, this would need to work as a backend filter, where you could just read the Change Feed for a particular subsets of documents (for example, where Type = Something). That is not possible currently and I'm not aware of any roadmap for it.

If it's a feature that would need to be implemented in the client SDK, then it would simply do the same you are currently doing, basically take the List of documents and apply a filtering mechanism. I have not yet seen any other request for this in the repo, my guess is because it's something that would be nice in the Type pattern scenario, but it's not a blocker because it's simple to implement and it doesn't add any value to any other scenario.

**Comment by Ceridan** [comment]
Yes, sounds fair. I think we may close this issue, you answered to all my questions. Thank you for the explanation and for your time.
