### ISSUE TITLE
SelectMany linq query on dictionary property

### ISSUE THREAD

**Issue by coffeymatt** [Azure/azure-cosmos-dotnet-v3#910]
**Describe the bug**

I think this may be a bug, but I'm not sure if what I'm doing is supported or if there is another work around.

I'm trying to query a dictionary property on an object using a 'SelectMany'. I know this works on child arrays/lists on objects, but with my dictionary it's just returning zero results.

**To Reproduce**

I have an object cosmosDb with a dictionary property:

`public Dictionary<Guid, Response> Responses { get; set; } = new Dictionary<Guid, Response>();`

I'm trying to do a 'SelectMany' linq query to get all the responses across my objects with a certain key e.g.

```
query.SelectMany(q => q.Responses.Where(r => r.Key == questionId)
                .Select(r => r.Value));
```

**Expected behavior/Actual behavior**

In the above example I'd want a list of responses back, instead I get zero results.

**Environment summary**
SDK Version: 3.3.0
OS Version Windows

**Comment by j82w** [comment]
@coffeymatt can you provide an example of the JSON document?

**Comment by j82w** [comment]
@khdang is this supported?

**Comment by coffeymatt** [comment]
> @coffeymatt can you provide an example of the JSON document?

Sure, I've trimmed some properties out, but you can see the responses dictionary:

```
{
    "enrollmentId": "5391e49c-263f-4d0d-947e-6160e9c3b02e",
    "caseId": "406e2a1b-561f-4550-b164-03809ad2b059",
    "surveyId": "b3b603a3-5d10-42d0-b7d6-2560301ade31",
    "questionnaireSequence": 1,
    "deviceNumber": 128,
    "groupName": "AmazingGroup",
    "snapshotId": "3b7e05c4-bfd2-46ef-a0b0-f1aad17623a6",
    "start": "2019-10-10T13:30:01.887Z",
    "end": "2019-10-10T13:31:32.107Z",
    "responses": {
        "7376c265-8bb9-4aa4-97af-713d6e81c57d": {
            "itemId": "7376c265-8bb9-4aa4-97af-713d6e81c57d",
            "title": "Rural region",
            "number": "2.1",
            "values": [
                {
                    "Key": "Dire Dawa Astedadar",
                    "Value": "Dire Dawa Astedadar"
                }
            ],
            "completed": "2019-10-10T13:31:06.562Z",
            "elapsed": 0
        },
        "e6a6b9d3-f793-446a-a327-6436544e98c3": {
            "itemId": "e6a6b9d3-f793-446a-a327-6436544e98c3",
            "title": "Rural zone",
            "number": "2.2",
            "values": [
                {
                    "Key": "Dire Dawa",
                    "Value": "Dire Dawa"
                }
            ],
            "completed": "2019-10-10T13:31:08.69Z",
            "elapsed": 0
        }
    },
    "_dbPartition": "[5391e49c-263f-4d0d-947e-6160e9c3b02e][b3b603a3-5d10-42d0-b7d6-2560301ade31][1]",
    "id": "6db5bd32-4edf-44bd-b830-9d264c773999",
    "_type": "QuestionnaireResponseContainer",
    "_dateCreated": "2019-10-10T13:34:25.2604973Z",
    "_lastUpdated": "2019-10-10T13:34:25.2604973Z",
    "_rid": "iJ9LAMRY6gHESwAAAAAAAA==",
    "_self": "dbs/iJ9LAA==/colls/iJ9LAMRY6gE=/docs/iJ9LAMRY6gHESwAAAAAAAA==/",
    "_etag": "\"0000a160-0000-0d00-0000-5d9f33620000\"",
    "_attachments": "attachments/",
    "_ts": 1570714466
}
```

**Comment by khdang** [comment]
For dictionary, can you access the element using the key instead of filtering by a Where clause?
ie.
query.Select(q => q.Responses[questionId]);

This is due to there is no direct SQL equivalent for the LINQ expression semantics (i.e. SelectMany and filter on a dictionary) and the support for relative equivalent translation is not supported yet.

**Comment by coffeymatt** [comment]
Thanks @khdang , what you've suggested works using the key instead of the clause.

What you've said makes sense, I guess this is more a feature request than a bug. Shall I close this issue?

**Comment by khdang** [comment]
@coffeymatt Sure, I'm glad that it works for you. I'm closing the issue and will take a note to revisit it. Thanks.

**Comment by abhaldar** [comment]
Need to query a nested dictionary with Enum as Key

example
{
 abc : {
 "Code": "x",
 "Name": "y"
}]
}

Now I need to query s => s.abc.Any(x => x.Key == SomeEnum.Code && x.Value == "SomeValue)

but this is failing as translation to SQL has keywords like s0["Key"] and s0["Value"] which doesn't exist in the data.

Need help with this as failing to do this query would considerably reduce our scope of LINQ for CosmosDb query utilization.

**Comment by Matthewsre** [comment]
> @coffeymatt Sure, I'm glad that it works for you. I'm closing the issue and will take a note to revisit it. Thanks.

@khdang , was this ever revisited? I understand there is no "relative equivalent translation", but creating a query instead that will always returns zero results instead of throwing a not supported exception seems like a pretty big flaw. I had to go investigate the underlying query and figure out why no results were coming back. I see how this "might" work if a custom serializer is used that translates dictionaries into collections instead of objects, but how it is now just feels like a big trap with unexpected results using the default serializers.
