### ISSUE TITLE
ResourceId on DatabaseProperties and ContainerProperties should be made public

### ISSUE THREAD

**Issue by ylibrach** [Azure/azure-cosmos-dotnet-v3#912]
**Is your feature request related to a problem? Please describe.**
The `ResourceId` property on `DatabaseProperties` and `ContainerProperties` is currently marked as internal. However, this value is necessary for a lot of scenarios, such as requests to the Azure REST API.

**Describe the solution you'd like**
The property on these two classes should be made public.

**Comment by j82w** [comment]
If you are using the SDK what reason do you have for calling the Azure REST API?

**Comment by ylibrach** [comment]
The Rest API provides additional information such as metrics that the SDK doesn't provide. We could theoretically also get the ResourceId by querying the Rest API using the database & container name, but these are extra calls in code that already has the database and container objects from the SDK. 

Tangentially, the RID is not exactly a secret or internal value, so what's the benefit in having the SDK obscure it?

**Comment by j82w** [comment]
What metrics is the SDK missing? If you can give a specific list we can go over it and see if it should be added to the SDK so all users get the information. Also all the headers should be accessible on a response.

@kirankumarkolli can you explain the reason for not making the RID public?

**Comment by ylibrach** [comment]
Is the SDK able to produce metrics such as Max RUs Per Second for Physical Partition Key Range? From what I can tell, it doesn't. Are you saying that the SDK *should* provide these types of metrics?

**Comment by j82w** [comment]
The SDK does not track that. What's the reasoning for tracking Max RUs Per Second for Physical Partition Key Range?

**Comment by ylibrach** [comment]
This metric is one of the ones we use for programmatically tracking the throughput we are sending against the collection/container.

**Comment by j82w** [comment]
If you are only tracking it based on the collection/container what's the point of having the physical partition key range?

**Comment by ealsur** [comment]
@ylibrach You can get those metrics (partitionId and RU consumed) from the Cosmos DB metrics in Azure Monitor/Diagnostics: https://docs.microsoft.com/en-us/azure/cosmos-db/logging#interpret

SDK is not exposing the partition routing or partition information at this point.

**Comment by ylibrach** [comment]
@ealsur this ticket wasn't about exposing the metrics or any partition information, it was about exposing `ResourceId` (rid) for collections/databases. I don't think you should close this issue.

**Comment by ealsur** [comment]
@ylibrach The request is to include information that is not needed nor used in the SDK. There is no usage anywhere for the `ResourceId` within the SDK,

You mentioned that you needed `ResourceId` to use it on the REST API because the REST API gives you Metrics that the SDK does not. But if what you need are metrics, then that information is already available in Azure Monitor / Diagnostics without the need of any ResourceId.

This repo is to track usage and issues within the scope of the .NET SDK, and as I mentioned, within that scope, there is no need for the `ResourceId`.
