### ISSUE TITLE
Request signing with strong consistency does not work

### ISSUE THREAD

**Issue by visridha** [Azure/azure-cosmos-dotnet-v3#919]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
A read request with strong consistency with request signing enabled does not work - the head request isn't signed with the key

**To Reproduce**
Enable gateway signing, do a concurrent read/write workload with strong consistency. You'll see 403 in the internal sdk calls.

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by kirankumarkolli** [comment]
Simple test case validation showed that signinghandler is called as expected for both write and reads.

**Comment by kirankumarkolli** [comment]
Head/HeadFeed for Collection/Database are the ones having issues.
One suspicion is BarrierReqeustHelper.

@ausfeldt can you please look into it further?

**Comment by ausfeldt** [comment]
The workaround is the add the header the same way as ComputeTransportHandler.cs in Microsoft.Azure.Cosmos.Friends for Direct Mode. For Gateway the header will have to be added using "internal HttpMessageHandler httpMessageHandler" on DocumentClient
