### ISSUE TITLE
Running emulator as a service or in the background

### ISSUE THREAD

**Issue by pseudoramble** [Azure/azure-cosmos-dotnet-v3#929]
We have been looking and brainstorming ideas about running the Cosmos emulator as a Windows service or in the background. We would like this so we can perform our integration tests in our CI/CD environment which has very limited access to the internet. Any success with this kind of a setup? Any other ideas we haven't thought of yet?

So far we have tried the following:

- Wrap the emulator with a tool like srvstart (https://github.com/rozanski/srvstart/tree/master/srvstart) which was not able to start up properly.
- Run it via Powershell in the pipeline with /NoUI and /NoExplorer. I think this hasn't been working because it seems to need an interactive login to run at the time.

Other ideas we have but haven't tried yet:

- Run Docker for Windows and boot up the container then. This might work but it sounds like it also opens an interactive shell which will terminate the container when it's exited?
- Run a separate VM with a session that is always logged in and running. I think it would work fine but it isn't ideal.

Also - Thanks again for all your work on the Cosmos SDK. It's highly appreciated!

**Comment by milismsft** [comment]
We (Microsoft) have the emulator running in our CI/CD such as executing tests for PRs against this particular repo. The current process is to install/start the emulator before any tests are scheduled to execute, wait for it to initialize properly, then start the tests. You can use either the emulator from an MSI installation (see "msiexec /quiet /passive" for a prompt-less installation), as a Docker container, or the emulator's VSTS extension (see https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-setup-ci-cd).

**Comment by pseudoramble** [comment]
Thanks! Do you happen to know if there's a way to start and run either the Docker container or the emulator without having an interactive login session? We may be misunderstanding the documentation, but it seems like the Docker container runs in an interactive-only mode.

**Comment by milismsft** [comment]
This question will probably more appropriate to a Docker specific forum, in particular you would like to search for what's the difference between "docker run" versus "docker create" & "docker start"(https://docs.docker.com/engine/reference/commandline/create/)

Try the following:

set containerName=azure-cosmosdb-emulator
set hostDirectory=C:\emulator\bind-mount
mkdir %hostDirectory%
docker create --name azure-cosmosdb-emulator --memory 2GB --mount "type=bind,source=%hostDirectory%,destination=C:\CosmosDB.Emulator\bind-mount" --interactive --tty -p 8081:8081 -p 8900:8900 -p 8901:8901 -p 8902:8902 -p 10250:10250 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -p 10255:10255 -p 10256:10256 -p 10350:10350 mcr.microsoft.com/cosmosdb/windows/azure-cosmos-emulator
docker start azure-cosmosdb-emulator
