### ISSUE TITLE
Query refactor to handle query plan parameter

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#930]
Refactor query to have an interface that can accept query plan as a parameter. This will allow the query plan to be cached to avoid the service interop or gateway call to parse the query.

**Comment by bchong95** [comment]
We currently support this through either the continuation token or an internal API. Main usecase will be in compute gateway where we serialize the query plan in the continuation token (if it's not too large) and resume with it instead of making another call to service interop.
