### ISSUE TITLE
AllowBulkExecution property is missing in 3.3.x SDK

### ISSUE THREAD

**Issue by KhuongNtrd** [Azure/azure-cosmos-dotnet-v3#932]
**Describe the bug**
Latest version 3.3.2 SDK with public Bulk Execution but the AllowBulkExecution property can not found while using in netstandard project (included samples)

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a10e41103639c2ef037cd2cab140fceb059faa8d/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L365

**Comment by j82w** [comment]
The bulk feature is only in preview for version 3.3.2 and lower. The next [release](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md) will make it public.
