### ISSUE TITLE
Any way of querying an item by multiple partition keys?

### ISSUE THREAD

**Issue by mhabibal13** [Azure/azure-cosmos-dotnet-v3#939]
I couldn't find any way running such queries. The class ResourceFeedReaderClientExtensions is internal

**Comment by j82w** [comment]
I'm a little confused by the question as ResourceFeedReaderClientExtensions has FeedOptions which only supports a single partition key value.

The [samples](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0eb41935fbe80a4d52ce4a71397d53c3c0f998ed/Microsoft.Azure.Cosmos.Samples/Usage/Queries/Program.cs#L189) show how to do a query in the v3 SDK.

If you want to do a query with multiple partition key values then just include the values in the query. For example `select * from t where t.pk = "foo" or t.pk = "bar"` . The partition key values will be extracted from the query.

**Comment by mhabibal13** [comment]
Okay. I was looking for a way without writing SQL Queries directly (Lambda for instance)

**Comment by j82w** [comment]
There is [LINQ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0eb41935fbe80a4d52ce4a71397d53c3c0f998ed/Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs#L1021) support for items.

**Comment by mhabibal13** [comment]
So there is no ddirect way like defining a list of PartitionKey objects (new PartitionKey("somevalue"))?

**Comment by j82w** [comment]
A single partition key is supported through [QueryRequestOptions](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0eb41935fbe80a4d52ce4a71397d53c3c0f998ed/Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs#L90). For multiple partition keys the only way is through a query.
