### ISSUE TITLE
LINQ named parameter proposal

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#955]
LINQ named parameter proposal: Use an generic extension based model to generate parameters.

ex: 
```c#
IOrderedbyQueryable<T> tmp = ...;
tmp.Where(e => e.Org = CosmosExtenson.WithNamedParameter<T>("@orgName", "Value1" );
```

**Comment by kirankumarkolli** [comment]
/cc: @khdang , @simplynaveen20 , @sboshra , @bchong95

**Comment by bchong95** [comment]
There exists some alternative:

```
public IQueryable BuildSomeQuery(param1, ... , param2)
{
	IOrderedbyQueryable<T> tmp = ...;
	tmp.Where(e => e.Org = param1);
}
```

But if `LinqExtenson.CreateNamedParameter<T>("@orgName", "Value1" )`

**Comment by j82w** [comment]
The issue with the alternative is param1 can be any type of object, and each param can be a different type. I think the inline method would be the better user experience has it makes it easy to see what the parameter name and value will be in the same line.
