### ISSUE TITLE
Request Timeout not honoured under network connectivity issues.

### ISSUE THREAD

**Issue by afscrome** [Azure/azure-cosmos-dotnet-v3#959]
**Describe the bug**
When experiencing a network failure, the Cosmos SDK seems to ignore the `RequestTimeout` when calling `ReadItemAsync`, instead taking about 120secs before timing out

**To Reproduce**
Below is a console app that spins up a number of concurrent task, each of which tries to hit cosmos.  When it successfully calls cosmos, it writes the task id to the console.  When a failure happens, it writes the time to fail to the console in red.   We then simulate a network failure by setting a firewall rule to block traffic to cosmos.  Network is restored by undoing the firewall rule.

Console App: (Update the constants at the top to point to a known document)
```cs
class Program
{
    private const string DatabaseUri = "";
    private const string AuthKey = "";
    private const string DatabaseId = "";
    private const string CollectionId = "";
    private const string DocumentId = "";
    private const string PartitionKey = "";
    private const int ConcurrencyLevel = 2;

    private static Container _container;
    private static readonly object _writeLock = new object();

    static async Task Main()
    {
        var options = new CosmosClientOptions
        {
            RequestTimeout = TimeSpan.FromMilliseconds(1000)
        };

        var client = new CosmosClient(DatabaseUri, AuthKey, options);
        await client.ReadAccountAsync();

        _container = client.GetContainer(DatabaseId, CollectionId);

        var tasks = Enumerable
            .Range(0, ConcurrencyLevel)
            .Select(Loop);
        await Task.WhenAll(tasks);
    }

    static async Task Loop(int loopId)
    {
        var stopwatch = new Stopwatch();
        while (true)
        {
            try
            {
                stopwatch.Restart();
                await _container.ReadItemAsync<object>(DocumentId, new PartitionKey(PartitionKey));
                lock (_writeLock)
                {
                    Console.Write(loopId);
                }
            }
            catch
            {
                var elapsed = stopwatch.ElapsedMilliseconds;
                var message = $"Task {loopId}: {elapsed}ms";
                lock (_writeLock)
                {
                    Console.ForegroundColor = ConsoleColor.DarkRed;
                    Console.WriteLine(message);
                    Console.ResetColor();
                }
            }
        }
    }
}
```

Firewall Rule creation / enabling / disabling
```powershell
#Create Firewall Rule
$instance = 'foo.documents.azure.com'
$cosmosIp = (Resolve-DnsName $instance).IP4Address
New-NetFirewallRule `
	-Name CosmosFailureTest `
	-DisplayName CosmosFailureTest `
	-Enabled False `
	-Profile Any `
	-Direction Outbound `
	-Action Block `
	-RemoteAddress $cosmosIp

#Block traffic to comos
Enable-NetFirewallRule CosmosFailureTest

#Allow traffic to cosmos
Disable-NetFirewallrule CosmosFailureTest
```

**Expected behaviour**
`ReadItemAsync` should honour the `RequestTimeout` in the event of a network failure.  It certainly shouldn't take 120 secs to fail.

**Actual behavior**
Requests hang for 120secs, rather than the 1sec specified in `RequestTimeout`
![image](https://user-images.githubusercontent.com/289860/68031513-b8209780-fcb3-11e9-8c46-a0685ce765e8.png)

**Environment summary**
SDK Version: 3.3.3
OS Version Microsoft Windows [Version 10.0.18362.387]

**Additional context**
We are currently doing testing to determine how our app fails in various failure scenarios (This issue is an extension of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/931 after suggesting that turning off the cosmos emulator is not a good way to simulate failures)

This issue seems to be related to endpoint discovery, as if endpoint discovery is disabled as if `LimitToEndpoint = true` is specified on `CosmosClientOptions`, then requests fail well within the specified timeout.  `ClientRetryPolicy` is set to do 120 retries at 1sec delay between each - this is suspiciously close to the 120secs experienced earlier!

```cs
private const int RetryIntervalInMS = 1000; // Once we detect failover wait for 1 second before retrying request.
private const int MaxRetryCount = 120;
```

Similar issues can be reproduced on the V2 SDK - see https://gist.github.com/afscrome/bc4174bd70af9579dcc0479040af2503 for example repro steps.  (Can re-use the Powershell scripts above for firewall rules)

**Comment by kirankumarkolli** [comment]
@afscrome thanks for sharing full context.

It’s a trade-off of responsiveness and availability. SDK is trying to trying out others regions for availability extensively.

RequestTimeout is low level and is applicable to each NW/service interactions.
Application can define a CancellationToken and use it as preemption point for responsiveness.
