### ISSUE TITLE
Batch - an update?

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-cosmos-dotnet-v3#961]
Hi!

I was hoping for some insight into *Batching*.  If it's a committed upcoming feature (looks to be!) and when it'll be public (it's internal right now).

We started using it with 3.2.0-preview before you hid it under "internal" flags.  It's awesome!  We previously had our own custom workaround solution where we deployed a server-side javascript stored procedure in order to do batch operations.  But we don't need it any more, thanks to built-in batching.  Of course, we're stuck on 3.2.0-preview...…….. But that's okay, assuming it's still coming sooner or later?

**Comment by j82w** [comment]
The current plan is to make Batch part of the next SDK release which should happen sometime next week. It might get delayed if some major issue discovered before then.

**Comment by joshlang** [comment]
Thanks for the speedy answer.

The answer itself couldn't have been more awesome, too.  Thanks!

Will leave this issue open until the release just so others can see your answer.

**Comment by j82w** [comment]
Please take a look at this [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/965).

**Comment by joshlang** [comment]
Fantastic.  We've migrated to using the new TransactionalBatch (previously called Batch), and everything seem good.  Thanks!
