### ISSUE TITLE
Support for mac use of emulator

### ISSUE THREAD

**Issue by philwade** [Azure/azure-cosmos-dotnet-v3#969]
I would like to be able to use the cosmos emulator (running in a virtual machine) when developing on my mac. As far as I can tell, this workflow is only supported when using v2 of the SDK. The solution there is to create a custom `HttpClientHandler` that ignores the "bad" SSL cert used by the emulator. I would prefer to use v3 (the api is much nicer imo) but I cannot find a way to make it work.

Please consider a way to disable the SSL check or inject an http client. Or - if there actually is a viable workaround for v3, please update the documentation to make it clear.

Thanks!

**Comment by j82w** [comment]
You should be able to configure it via the web proxy on the cosmos client configuration. It was added in version 3.2.0. Take a look at this [PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/743).

**Comment by philwade** [comment]
@j82w per this comment: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/743#pullrequestreview-283833083 and the actual diff, it appears the disabling of SSL verification was removed from the pull request. I've tried to figure out if there is a way to use the WebProxy to disable it, but I haven't been able to find any examples. The API it provides doesn't present an obvious way. Could you point me to some documentation that might help?

**Comment by galvesribeiro** [comment]
@j82w do you have any clues on how to bypass the certificate issue? 

I'm on the same boat as @philwade running the emulator on a VM on Mac OSX and right now I'm unable to do the use it.

I have a requirement on the batch transactions that is only available on SDK 3.x so I _must_ migrate to it but without tests, things get difficult...

**Comment by j82w** [comment]
@galvesribeiro there is no longer a need to bypass SSL check. The certificate can be used on [Mac and Linux OS](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#mac-os).

**Comment by galvesribeiro** [comment]
@j82w sorry but this is not a solution. This is a very bad workaround... 

Use a VM just to run the emulator is something not desirable, at all...

This issue should be kept open until a real solution for it come up so we can track it...

**Comment by j82w** [comment]
The initial issue @philwade described was for being able to connect  the v3 SDK running on Mac or Linux to the emulator running on windows. That issue is fixed with the [workaround](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#mac-os). 

This repo is used for the Cosmos DB .NET V3 SDK. I'll update this thread once I find the correct place for this issue to be tracked.
