### ISSUE TITLE
Cosmos DB Automatic indexing

### ISSUE THREAD

**Issue by ankitvijay** [Azure/azure-cosmos-dotnet-v3#976]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

I had originally posted this issue in `StackOverflow`. But have not received any responses there.
Here is the link of the issue: https://stackoverflow.com/questions/58703586/automatic-indexing-in-comos-db

**Describe the bug**
I'm trying to define indexing on few properties in Comos but having some issues with automatic indexing. As per the Cosmos DB [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/index-overview):

> By default, Azure Cosmos DB automatically indexes every property for all items in your container without having to define any schema or configure secondary indexes.

Also, please refer to [this ](https://docs.microsoft.com/en-us/azure/cosmos-db/index-policy) piece of documentation:

> In some situations, you may want to override this automatic behavior to better suit your requirements. You can customize a container's indexing policy by setting its indexing mode, and include or exclude property paths.

What I understand from the above points is that unless we define our own custom indexing policy the automatic indexing is set to true (which makes sense). If however, we defined our own include and exclude paths for indexing else it should be false.

**To Reproduce**

Based on the documentation, if I define the container properties as below, the Indexing Policy Automatic property should be set to false on Cosmos DB. 
```
using Microsoft.Azure.Cosmos;  //Azure Cosmos SDK v3.3.1

 .

 .
var comosClient = new CosmosClient(serviceEndpoint, authKey, options);
var databaseName = "MY_DB_NAME";
var containerProperties = new ContainerProperties
        {
            Id = "SOME_CONTAINER_NAME",
            PartitionKeyPath = "/MY_PARTITION_KEY",
            DefaultTimeToLive = -1
        };

 containerProperties.IndexingPolicy.IncludedPaths.Add(new IncludedPath {Path = "/\"{MY_PARTITION_KEY}\"/?"});         

 containerProperties.IndexingPolicy.ExcludedPaths.Add(new ExcludedPath {Path = "/*"});

await comosClient.GetDatabase(databaseName).CreateContainerIfNotExistsAsync(containerProperties, 1000);

```
**Expected behavior**
The expected behavior of the above code was that `automatic` indexing is set to `false`. That is ComosDB settings in Azure portal should reflect `automatic` indexing as `false`.

**Actual behavior**
I see that with the above configuration on CosmosDb indexing being defined with `automatic` set to `true`. Here is the screenshot of indexing Policy on Azure Portal

![image](https://user-images.githubusercontent.com/5988564/68249849-596c6c80-006b-11ea-9be2-a813a6e9b2e0.png)

To add to the mystery, even if I set `containerProperties.Automatic` property to `false` explicitly, it still the property still remains `true` on the portal.

**Questions**

- Is it a possible UI bug or SDK bug? If not, what I could be missing?

- If we set `IncludedPaths` and `ExcludedPaths` as above, can you confirm if we no longer index any additional fields?

**Environment summary**
SDK Version: v3.3.1
OS Version (e.g. Windows, Linux, MacOSX): Windows 10

**Comment by ealsur** [comment]
Question answered in SO.
