### ISSUE TITLE
Support per-request serializer/serialization settings

### ISSUE THREAD

**Issue by lisardggY** [Azure/azure-cosmos-dotnet-v3#980]
**Is your feature request related to a problem? Please describe.**
Using the v2 SDK, we would pass customs serialization settings as part of a specific request's options - for instance, `CreateDocumentQuery` got passed in a `FeedOptions` instance with its own `JsonSerializerSettings`. This allowed us to have custom serialization settings for different calls, while still retaining a single `IDocumentClient` with a single shared connection. 
In our case, we needed a specific JsonConverter depending on runtime context to deserialize a specific payload embedded inside the serialized document, and different requests had a different set of known payloads.

Now in v3, the serialization can only be set during the CosmosClient build stage, and can't be changed per-request.

**Describe the solution you'd like**
A way to override the default serializer or serializationsettings on a per-request basis, not only on a CosmosClient instance basis.

**Describe alternatives you've considered**
The alternative I'm working on now is to pre-calculate all the possible payloads in advance, and load them into a custom serializer during CosmosClient initialization. It's not ideal, though it will probably work.

**Comment by j82w** [comment]
If you want per request serialize settings you can use the stream APIs. Then you can control the entire serialization process this way.

**Comment by lisardggY** [comment]
While this is simple enough when replacing `ReadItemAsync<T>` with `ReadStreamAsync`, it gets more complicated when trying to replace `query.ToFeedIterator<T>` with `query.ToStreamIterator` and parsing the response message stream as a stream of documents.

**Comment by j82w** [comment]
I don't think it that different to support query. There is a [sample ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/23f3d1c30e509541ec71d2937ebb01c4e9b4ed32/Microsoft.Azure.Cosmos.Samples/Usage/Queries/Program.cs#L166) showing how to do it.
