### ISSUE TITLE
Question - Using ItemRequestOptions to Override Consistency

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-cosmos-dotnet-v3#982]
If our database is configured for session level consistency and I would like to override that on a per read (query) using the `ItemRequestOptions`, am I able to go up to *strong*?

Or am I forced to create a stored procedure to do the read?

Thanks,

**Comment by ealsur** [comment]
All reads and reads happening inside a Stored Procedure will, by default, use the account consistency https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels#configure-the-default-consistency-level

Are you getting some error while trying to do the read with Strong?

**Comment by mpaul31** [comment]
sorry, i should have clarified more. I am trying not to use a stored procedure and just instead call `container.ReadItemAsync` (or query) and pass in an `ItemRequestOptions` with a consistency set to strong.

so i'm wondering if i can go from *session* to *strong* on a per-read (query) basis *without* using stored procedure.

**Comment by ealsur** [comment]
Yes you can, ItemRequestOptions has a Consistency property to override the account one.

What I don't understand though is the Stored Procedure mention. If your account is Strong, executing a Stored Procedure will also use Strong Consistency as per the link I shared.

Stored Procedures are meant to be used when you want a transactional scope, a group of operations that you want to either succeed or fail. In which case, [Transactional Batch](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/970) comes very handy too.

**Comment by mpaul31** [comment]
that's the thing, our account is `session` *not* `strong`.

so we want to execute a read that is more restrictive without calling a procedure.

does that help?

**Comment by ealsur** [comment]
You can then execute the ReadItem operation with Strong as the Consistency in the ItemRequestOptions.

**Comment by mpaul31** [comment]
It was a question from one of my team members so i will try myself and let you know.

i know you mentioned above all stored procedures use the specified account consistency but is this really true? i have to find where i read it but the doc mentioned stored procs always execute on the primary replica and are thus strong consistency.

**Comment by mpaul31** [comment]
to the top :)

**Comment by ealsur** [comment]
Sorry, I left this open and never clicked to send it.

I think this is going beyond the SDK and onto the conceptual ground.

From https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels#scope-of-the-read-consistency, 

> Read consistency applies to a single read operation scoped within a partition-key range or a logical partition. The read operation can be issued by a remote client or a stored procedure.

So doing the read from inside the stored procedure would have the same effect as doing the read from the SDK. It will apply either the account consistency or the request consistency.

**Comment by mpaul31** [comment]
here is the document i was talking about regarding stored procedures use strong consistency for reads.

> Stored procedures and triggers are always executed on the primary replica of an Azure Cosmos container. This feature ensures that reads from stored procedures offer strong consistency

Data consistency section below
https://docs.microsoft.com/en-us/azure/cosmos-db/stored-procedures-triggers-udfs

**Comment by ealsur** [comment]
Interesting, they kind of contradict themselves.

@markjbrown Do you have any insights?

In any case, I believe that your original question regarding how to change the per-request consistency level can be marked as answered?

**Comment by markjbrown** [comment]
It is not possible to set a stronger level of consistency than what is set in the account at the session level, it can only be relaxed.

Users should generally avoid using stored procedures for read operations because they only operate on the primary replica. This can become a bottleneck in very heavy read scenarios. The passage referred to above regarding strong consistency is intended for write-scenarios as there is guidance on not using stored procedures for read scenarios.

Overall there is no reason to use a stored procedure in this way if you are in the same session within an application. Session level consistency provides in-session strong consistency. You will always read your own writes. If you have multiple instances of an application or separate apps in the same region, if you are able to pass the session token between them you can also get strong consistency within that region.

Hope this helps.

#please-close

**Comment by mpaul31** [comment]
thank you both!

**Comment by mpaul31** [comment]
@markjbrown is there any way i can send you a question offline via email?

**Comment by markjbrown** [comment]
you bet. mjbrown <at> microsoft <dot> com
