### ISSUE TITLE
[Gremlin API] Add support for Bytecode

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/azure-cosmos-dotnet-v3#991]
(When) will Gremlin bytecode be supported for CosmosDb Graph API?
Please refer to the [Existing issue in the V2 repo](https://github.com/Azure/azure-documentdb-dotnet/issues/439)
The MS docs state Bytecode support is not **[yet](https://docs.microsoft.com/en-us/azure/cosmos-db/gremlin-compatibility#unsupported-features)** available.
Any information/guidance on planning/availability is very much appreciated!

**Comment by j82w** [comment]
This is not related to the .NET SQL SDK and is more of a Cosmos DB Service question. Please email askcosmosdb@microsoft.com .

**Comment by SeanFeldman** [comment]
@j82w is there a repo with Gremlin issue tracker?
