### ISSUE TITLE
Question: Is there a way to invoke an UDF?

### ISSUE THREAD

**Issue by cipryd** [Azure/azure-cosmos-dotnet-v3#993]
In v2 there was UserDefinedFunctionProvider.Invoke to invoke an UDF and could use it in a LINQ query. 

Is there a way to do this in v3 besides using it directly in an SQL query?

**Comment by j82w** [comment]
This appears to be a gap in the v3 SDK. The [class](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Linq/UserDefinedFunctionProvider.cs) is internal currently. There is some other extensions that need to be exposed to. It might need to be refactored into a `CosmosLinqExtensions` class.

**Comment by sarahm7** [comment]
any update on exposing the invoke method or is there any other workaround for this?

**Comment by MrMint** [comment]
This is a major pain point migrating from v2, are their plans to expose this? If not what's the best course of action for large projects relying on LINQ migrating from v2 to v3?

**Comment by buruguduys** [comment]
Having the same issue. Any updates regarding on this issue?

**Comment by bchong95** [comment]
@khdang is it okay to make this type public?

**Comment by bchong95** [comment]
Actually @khdang, I will put out the PR and you can approve it to avoid having to context switch from backend work.

**Comment by bchong95** [comment]
PR that can be tracked is here:

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1526

**Comment by mywyb2** [comment]
Three months later, UserDefinedFunctionProvider is still internal. This is clearly a bug and the issue has not been resolved yet.

**Comment by MrMint** [comment]
Reiterating that this is a major pain point for anyone that migrated from v2 relying on this feature. We are maintaining a fork that makes this class public so that we could complete the migration. Frankly, we expected #1526 to be merged long before we needed to push our fork to production and maintain it across versions. Any updates on this?

**Comment by abranaugh** [comment]
I also have to maintain a forked version that makes this class public so we can use V3 of the library.  Is there any update on getting #1526 merged?  That PR has been open for 5 months and this issue has been open for almost a year now.

**Comment by mkeravica** [comment]
Can this issue be re-opened? The last activity on the PR was over 7 months ago. The issue should not be considered "done" or "closed" if the code is not yet merged.
This is still an issue for anyone who is trying to use UDF from LINQ.
