### ISSUE TITLE
Question: Advice on setting AllowBulkExecution

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-cosmos-dotnet-v3#994]
We are currently looking for some guidance into setting the new `AllowBulkExecution=true` flag for `CosmosClient`. We have a scenario in our WebAPI where we wish for a certain request to utilise this new feature, however, since we currently resolve in DI the same instance of `CosmosClient` per web request, we note that when we set the `AllowBulkExecution` flag it will also remain set (as expected).

Would it be recommended that we have this value `true` all the time? Or should we be programatically setting it to `false` once we are done.

On a side note, we've also made the assumption that `CosmosClient` should still be created once and that instance shared across all requests?

**Comment by ealsur** [comment]
Recommendation is to have a separate client for Bulk. You can use a Proxy class that contains one CosmosClient instance for Bulk and one not for Bulk, and use it in DI and pick the one you need for each scenario.

The AllowBulkExecution flag is set and remains set on CosmosClient creation, it cannot be changed.
