### ISSUE TITLE
CosmosException Response status code 404: query '$resolveFor' is invalid

### ISSUE THREAD

**Issue by cipryd** [Azure/azure-cosmos-dotnet-v3#996]
I get the databaseId and collectionId from parsing a DocumentCollectionUri from v2 and try to use them as such in v3:

`GetContainer("RZwRAA==", "RZwRAPxiyBg=")`
For operations like _CreateItemAsync_ or get queries this works but for _ReadItemAsync_ and _DeleteItemAsync_ it throws this exception:
`Response status code does not indicate success: 404 Substatus: 0 Reason: (The value 'dbs/RZwRAA==/colls/RZwRAPxiyBg=/docs/6b2ef134-6a46-4e40-b7a0-c1ba1f458d04' specified  for query '$resolveFor' is invalid.ActivityId: 5c054fdf-b901-42b9-a32f-14466e36a1e3, Windows/10.0.17134 cosmos-netstandard-sdk/3.4.1).`

`GetContainer(databaseName, containerName)`
If the get container operation is made in this way, _ReadItemAsync_ and _DeleteItemAsync_ work fine.

The database provisioning is made by a 3rd party service and I only receive the DocumentCollectionUri without knowing the databaseName and containerName.
Am I missing something or this scenario is not valid?

**Comment by j82w** [comment]
V3 is named based. You need to use the container name and database name rather than the resource id.

**Comment by cipryd** [comment]
Then why it works for _CreateItemAsync_ and _GetItemLinqQueryable_ with the id?

**Comment by j82w** [comment]
Are you talking about the document rid or the document id?
